### ISSUE TITLE
Unable to find network where name in docker-compose file used template var. 

### ISSUE THREAD

**Issue by dazinator** [traefik/traefik#10005]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have a `docker-compose.yml` file with a service, that attaches to my traefik network declared as an existing external network.

```
version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest    
    deploy:      
      replicas: 1      
      restart_policy:        
        condition: any
        delay: 5s
      labels:
        traefik.tcp.services.sqlserver.loadbalancer.server.port: 1433
        traefik.tcp.routers.sqlserver.entrypoints: "mssql"
        traefik.tcp.routers.sqlserver.rule: "HostSNI(`*`)"
        traefik.tcp.routers.sqlserver.tls: "false"
        # traefik.tcp.routers.sqlserver.service: sqlserver
        traefik.enable: "true"
        # traefik.docker.network: "reverse-proxy-${TRAEFIK_NETWORK_NAME}"  
    # ports:
    #   - '1433:1433'
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_PASSWORD}"
    networks:
      - sqlserver
      - traefik-net

networks:   
  sqlserver:
    name: sqlserver   
    driver: overlay
    attachable: true  

  traefik-net:
    name: reverse-proxy-${TRAEFIK_NETWORK_NAME}
    driver: overlay
    external: true    
    

```

Note: I have several oother services such as web api's deployed in an identical way which all have this same issue.

When this is deployed using `docker stack deploy` note that the environment variable `${TRAEFIK_NETWORK_NAME}` is used in the template.

I then see errors in the traefic logs

```
67eem  time="2023-07-03T13:41:27Z" level=warning msg="Could not find network named 'reverse-proxy-${TRAEFIK_NETWORK_NAME}' for container 'mystack_sqlserver.1'! Maybe you're missing the project's prefix in the label? Defaulting to first available network." 
```

However if I uncomment this label

```
- traefik.docker.network=reverse-proxy-${TRAEFIK_NETWORK_NAME}
```

This error goes away.

I beleive that traefik should be able to work out the network name without this label but is this a wrong assumption, or could this be a bug?

### What did you see instead?

```
67eem  time="2023-07-03T13:41:27Z" level=warning msg="Could not find network named 'reverse-proxy-${TRAEFIK_NETWORK_NAME}' for container 'mystack_sqlserver.1'! Maybe you're missing the project's prefix in the label? Defaulting to first available network." 
```

### What version of Traefik are you using?

I am running the traefik 2.7 docker image:
```
services:
  reverse-proxy:
    # The official v2 Traefik docker image, Published on https://hub.docker.com/_/traefik?tab=tags
    image: traefik:v2.7   
```

### What is your environment & configuration?

```yaml
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"   # Listen to the UNIX Docker socket
    exposedByDefault: false                   # Only expose container that are explicitly enabled (using label traefik.enabled)
    network: "reverse-proxy-${env_name}"      # Default network to use for connections to all containers.
    #network: "{{ env "env_name" }}-reverse-proxy"   
    swarmMode: true                           # Activates the Swarm Mode (instead of standalone Docker).
    swarmModeRefreshSeconds: 15               # Defines the polling interval (in seconds) in Swarm Mode.
    watch: true                               # Watch Docker Swarm events
    # constraints: "Label(`traefik.env.name`,`{{ env "env_name" }}`)" # only consider services with a matching label.  I.e this traefix is scoped to services with this label
    # domain: "docker.{{ env "TRAEFIK_DOMAIN" }}"
  file:
    filename: "/etc/traefik/config.yml"       # Link to the dynamic configuration
    watch: true                               # Watch for modifications
  providersThrottleDuration: 10     
```

### If applicable, please paste the log output in DEBUG level

```
67eem  time="2023-07-03T13:41:27Z" level=warning msg="Could not find network named 'reverse-proxy-${TRAEFIK_NETWORK_NAME}' for container 'mystack_sqlserver.1'! Maybe you're missing the project's prefix in the label? Defaulting to first available network." 
```
