### ISSUE TITLE
Datadog tracing failing to initialise when using environment variable in the `localAgentHostPort` config

### ISSUE THREAD

**Issue by juanwolf** [traefik/traefik#10006]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have upgraded traefik from `v2.8.8` to `v2.10.3` where datadog's tracing is enabled however the tracer failed to initialise.

### What did you see instead?

Traefik was unable to initialise the datadog tracer and was throwing these errors:

```
2023/07/03 14:23:20 Datadog Tracer v1.51.0 ERROR: Loading features: parse "http://$%!B(MISSING)DD_AGENT_HOST%!D(MISSING):8126/info": invalid URL escape "%!B(MISSING)" (occurred: 03 Jul 23 14:22 UTC)
```

I suspect [the tracer version](https://github.com/DataDog/dd-trace-go/releases/tag/v1.51.0) to be the culprit 

### What version of Traefik are you using?

v2.10.3

### What is your environment & configuration?

Helm configuration for the datadog tracing:

```yaml
traefik:
  tracing:
    datadog:
      localAgentHostPort: "${DD_AGENT_HOST}:8126"
  env:
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
```
