### ISSUE TITLE
3.0 - Docker / Swarm provider: SwarmMode key still documented

### ISSUE THREAD

**Issue by Kangie** [traefik/traefik#10000]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

From the Docs: [swarmMode](https://doc.traefik.io/traefik/v3.0/providers/swarm/#swarmmode)

Optional, Default=false

Enables the Swarm Mode (instead of standalone Docker).

```toml
[providers.swarm]
  swarmMode = true
  # ...
```

This is redundant; the swarm provider is _always_ in swarmMode (and I believe the swarmMode key was removed altogether in beta3). I suspect this was overlooked when it was pulled out of the docker provider.

### What did you see instead?

```
{"level":"error","error":"command traefik error: field not found, node: swarmMode","time":"2023-07-01T23:43:35Z","message":"Command error"}
```

### What version of Traefik are you using?

3.0.0-beta3

### What is your environment & configuration?

```toml
[providers]
  [providers.swarm]
    # swarm classic (1.12-)
    # endpoint = "tcp://127.0.0.1:2375"
    # docker swarm mode (1.12+)
    endpoint = "tcp://127.0.0.1:2377"
    exposedByDefault = false
    network = "traefik-network"
    # This is a legacy value that I expect to disappear shortly; the swarm provider should _always_ be in swarmmode.
    swarmMode = true
```
