### ISSUE TITLE
K8s ingress samesite broken

### ISSUE THREAD

**Issue by davhdavh** [traefik/traefik#10009]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

1. set `"traefik.ingress.kubernetes.io/service.sticky.cookie.sameSite"  = "strict"` on service
2. delete cookie in browser
3. refresh page
4. get cookie with no samesite setting and browser warning that samesite setting is missing
Test with "none", or "lax" or "whyyyyyyy?" does nothing, and no error.

### What did you see instead?

![image](https://github.com/traefik/traefik/assets/1201165/6ba53483-0888-4197-834e-08f37edb293d)
![image](https://github.com/traefik/traefik/assets/1201165/087ee154-56ce-414f-bb1a-aa69aa25cdf8)

### What version of Traefik are you using?

3.0.0-beta3

### What is your environment & configuration?

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.httponly: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.samesite: strict
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
  name: whoami
  namespace: whoami
...
```
