### ISSUE TITLE
traefik v3.0.0-beta3 - command traefik error - swarmmode

### ISSUE THREAD

**Issue by ThomKrue** [traefik/traefik#10016]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Working traefik setup in Docker Swarm. Changed Image tag to -> traefik:v3.0.0-beta3

traefik:v3.0.0-beta2 Image from hub.docker.com is working.

### What did you see instead?

ERR Command error | error=command traefik error: failed to decode configuration from flags: field not found, node: swarmmode

### What version of Traefik are you using?

traefik:v3.0.0-beta3 from hub.docker.com

Version:      3.0.0-beta3
Codename:     beaufort
Go version:   go1.20.5
Built:        2023-06-22T08:58:13Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
services:
  traefik:
    image: traefik:v3.0.0-beta3
    restart: always
    ports:
      - target: 443
        published: 443
        - target: 8080
        published: 8080
    command:
      - --api=true
      - --api.dashboard=true
      - --log.level=DEBUG
      - --accesslog=true
      - --providers.docker=true
      - --providers.docker.swarmmode=true
      - --providers.docker.exposedbydefault=false 
      - --providers.file.watch=true
      - --providers.docker.network=proxy
      - --entryPoints.web-secure.address=:443
      - --entryPoints.web-secure.forwardedHeaders.trustedIPs=10.0.0.0/24
```

Add more configuration information here.
