### ISSUE TITLE
Traefik not registering removal of the last configuration in Redis

### ISSUE THREAD

**Issue by flopana** [traefik/traefik#10010]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have Redis configured as a provider in redis.

Enter a new configuration into redis for example:
```
traefik/http/routers/web/entrypoints = web-secured
traefik/http/routers/web/rule = Host(`some.domain.tld`)
traefik/http/routers/web/service = service@docker
traefik/http/routers/web/certresolver = letsencrypt
```

Enter another configuration like above.

Remove one, then remove the other.

### What did you see instead?

When one of the configurations gets removed Traefik will basically instantly no longer display this in the Dashboard and API and also will no longer provide this routing. (As it should)

When the last configuration gets removed and only `traefik/enable = true` is left the Dashboard and API will still show this configuration and Traefik will also still apply this routing.

Traefik will do this until I enter a new configuration. The old one that was already removed from Redis will no longer be displayed but the new one will.

I have tested if Redis is the problem here by subscribing to all changes for Traefik related keys but, as it should, the last configuration is properly displayed in Redis.
For this I used `psubscribe '__key*__:traefik*'`

In short when the last configuration remaining gets removed Traefik doesn't register this. Traefik only registers the removal of configuration when at least one is still present.

### What version of Traefik are you using?

Version:      2.10.3
Codename:     saintmarcelin
Go version:   go1.20.5
Built:        2023-06-19T16:18:54Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
api:
  insecure: true
  dashboard: true

log:
  filePath: "/var/log/traefik.log"
  level: info

providers:
  docker:
    exposedByDefault: false
    network: proxy
  file:
    filename: /etc/traefik/services.yml
    watch: true
  redis:
    endpoints:
      - "redis:6379"
    password: "redacted"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "web-secured"
          scheme: "https"
          permanent: true

  web-secured:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "redacted"
      httpChallenge:
        entryPoint: "web"
      storage: "/letsencrypt/acme.json"

```
