### ISSUE TITLE
Missing support for Kubernetes Ingress backend resource/apiGroup/kind

### ISSUE THREAD

**Issue by GiuseppeChiesa-TomTom** [traefik/traefik#10022]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm trying to use the following pattern:

1. Deploy Kubernetes Ingress CRD (with annotations it offers a flawless integration with both external-dns and cert-manager)
2. Set as backend for the ingress rule a `resource` instead typical service. As per [Kubernetes Ingress CRD documentation](https://kubernetes.io/docs/concepts/services-networking/ingress/#resource-backend) this should be possible. 

Example:
```yaml
---
apiVersion: traefik.io/v1alpha1                                                                                                                                                               
kind: TraefikService                                                                                                                                                                          
metadata:                                                                                                                                                                                     
  name: echo-server-my-application                                                                                                                                                            
  namespace: default                                                                                                                                                                          
spec:                                                                                                                                                                                         
  weighted:                                                                                                                                                                                   
    services:                                                                                                                                                                                 
    - name: echo-server-my-application-active # existing K8S Service                                                                                                                                             
      port: 80                                                                                                                                                                                
    - name: echo-server-my-application-preview # existing K8S Service                                                                                                                                                
      port: 80                                                                                                                                                                                
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.allow-http: 'false'
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.tls.options: default
  name: echo-server-my-application
  namespace: default
spec:
  ingressClassName: traefik
  rules:
    - host: echo-test.example.com
      http:
        paths:
          - backend:
              resource:
                apiGroup: traefik.io
                kind: TraefikService
                name: echo-server-my-application
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - echo-test.example.com
      secretName: sample-app-certificate                  
```

In other project this is a supported pattern, see for [example this link.](https://docs.netscaler.com/en-us/citrix-k8s-ingress-controller/configure/advanced-content-routing-using-http-crd.html)

### What did you see instead?

Traefik crashes with the following error:
```
traefik-5f8f776d4f-xdz6m time="2023-07-18T13:21:23Z" level=error msg="Error in Go routine: runtime error: invalid memory address or nil pointer dereference"                                  
traefik-5f8f776d4f-xdz6m time="2023-07-18T13:21:23Z" level=error msg="Stack: goroutine 62 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/traefik/traefik/v2/
pkg/safe.defaultRecoverGoroutine({0x415f180?, 0x8453b00})\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:66 +0xa5\ngithub.com/traefik/traefik/v2/pkg/safe.OperationWithRecover.func1.1()
\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:74 +0x35\npanic({0x415f180, 0x8453b00})\n\truntime/panic.go:884 +0x213\ngithub.com/traefik/traefik/v2/pkg/provider/kubernetes/ingress.(*
Provider).loadService(0xc000fde300, {0x57b7580, 0xc000c1db90}, {0xc007fc3cb8, 0x7}, {0x0?, 0xc00808e630?})\n\tgithub.com/traefik/traefik/v2/pkg/provider/kubernetes/ingress/kubernetes.go:522 
+0x6d\ngithub.com/traefik/traefik/v2/pkg/provider/kubernetes/ingress.(*Provider).loadConfigurationFromIngresses(0xc000fde300, {0x57a5930, 0xc000934750}, {0x57b7580, 0xc000c1db90})\n\tgithub.
com/traefik/traefik/v2/pkg/provider/kubernetes/ingress/kubernetes.go:302 +0x14cc\ngithub.com/traefik/traefik/v2/pkg/provider/kubernetes/ingress.(*Provider).Provide.func1.1()\n\tgithub.com/tr
aefik/traefik/v2/pkg/provider/kubernetes/ingress/kubernetes.go:164 +0x325\ngithub.com/traefik/traefik/v2/pkg/safe.OperationWithRecover.func1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routi
ne.go:78 +0x63\ngithub.com/cenkalti/backoff/v4.RetryNotifyWithTimer.func1()\n\tgithub.com/cenkalti/backoff/v4@v4.2.0/retry.go:18 +0x1b\ngithub.com/cenkalti/backoff/v4.doRetryNotify[...](0xc0
020d1e80?, {0x5781f18, 0xc0009389a0}, 0xc0020d1f48, {0x0, 0x0?})\n\tgithub.com/cenkalti/backoff/v4@v4.2.0/retry.go:88 +0x152\ngithub.com/cenkalti/backoff/v4.RetryNotifyWithTimer(0xc0005d5b60
?, {0x5781f18?, 0xc0009389a0?}, 0x0?, {0x0?, 0x0?})\n\tgithub.com/cenkalti/backoff/v4@v4.2.0/retry.go:61 +0x65\ngithub.com/cenkalti/backoff/v4.RetryNotify(...)\n\tgithub.com/cenkalti/backoff
/v4@v4.2.0/retry.go:49\ngithub.com/traefik/traefik/v2/pkg/provider/kubernetes/ingress.(*Provider).Provide.func1({0x57a5888?, 0xc000be0f50})\n\tgithub.com/traefik/traefik/v2/pkg/provider/kube
rnetes/ingress/kubernetes.go:192 +0x2fa\ngithub.com/traefik/traefik/v2/pkg/safe.(*Pool).GoCtx.func1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:36 +0x66\ngithub.com/traefik/traefi
k/v2/pkg/safe.GoWithRecover.func1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:59 +0x5b\ncreated by github.com/traefik/traefik/v2/pkg/safe.GoWithRecover\n\tgithub.com/traefik/traef
ik/v2/pkg/safe/routine.go:53 +0x72\n"                                                                                                                                                         
traefik-5f8f776d4f-xdz6m time="2023-07-18T13:21:23Z" level=error msg="Provider connection error: panic in operation: %!w(<nil>); retrying in 3.775014712s" providerName=kubernetes 
```

### What version of Traefik are you using?

version: 2.10.3

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.
