### ISSUE TITLE
RedirectRegex cuts off auth header

### ISSUE THREAD

**Issue by brunka09** [traefik/traefik#10031]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have a service under Traefik. After client's request to the service, it generates it's own request needs to be redirected to another instance. For that reason I am using RedirectRegex middleware and it cuts off service request's auth header and it is a big problem for me. All the info below.
P.S. I tried newer versions (2.3.0, 2.10) but the problem was the same.

### What did you see instead?

As a result I got this:
```
{
	"Request": "{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept-Encoding\":[\"gzip\"],\"Referer\":[\"http://10.17.25.21:8085/10.17.25.22/api/all_sources?depth=1\\u0026need_remotes=false\"],\"User-Agent\":[\"Go-http-client/1.1\"],\"X-Forwarded-Host\":[\"10.17.25.22\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"64f3b07e0add\"],\"X-Real-Ip\":[\"10.0.0.2\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"10.17.25.22\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.0.0.2:43308\",\"TLS\":null}",
	"level": "debug",
	"msg": "vulcand/oxy/roundrobin/rr: begin ServeHttp on request",
	"time": "2023-07-19T11:54:56Z"
} {
	"ForwardURL": {
		"Scheme": "http",
		"Opaque": "",
		"User": null,
		"Host": "10.0.9.141:80",
		"Path": "",
		"RawPath": "",
		"ForceQuery": false,
		"RawQuery": "",
		"Fragment": ""
	},
	"Request": "{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept-Encoding\":[\"gzip\"],\"Referer\":[\"http://10.17.25.21:8085/10.17.25.22/api/all_sources?depth=1\\u0026need_remotes=false\"],\"User-Agent\":[\"Go-http-client/1.1\"],\"X-Forwarded-Host\":[\"10.17.25.22\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"64f3b07e0add\"],\"X-Real-Ip\":[\"10.0.0.2\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"10.17.25.22\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.0.0.2:43308\",\"RequestURI\":\"/test\",\"TLS\":null}",
	"level": "debug",
	"msg": "vulcand/oxy/roundrobin/rr: Forwarding this request to URL",
	"time": "2023-07-19T11:54:56Z"
}
```
As we can see there is no Authorization header.
When I excluded RedirectRegex to see clear service's request headers, I got this (Authorization header is in the request):
```
{
	"Request": "{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/10.17.25.22/api/all_sources\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"depth=1\\u0026need_remotes=false\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept-Encoding\":[\"gzip\"],\"Authorization\":[\"Basic dGVzdDIyOjEyMzQ1\"],\"User-Agent\":[\"Go-http-client/1.1\"],\"X-Forwarded-Host\":[\"10.17.25.22:8081\"],\"X-Forwarded-Port\":[\"8081\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"f6d56af36d98\"],\"X-Real-Ip\":[\"10.255.0.2\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"10.17.25.22:8081\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.255.0.2:35146\",\"RequestURI\":\"/10.17.25.22/api/all_sources?depth=1\\u0026need_remotes=false\",\"TLS\":null}",
	"level": "debug",
	"msg": "vulcand/oxy/roundrobin/rr: begin ServeHttp on request",
	"time": "2023-07-20T20:44:30Z"
}
```

### What version of Traefik are you using?

```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

I use docker compose labels:
```
version: '3.7'
networks:
  traefik:
    external: true
services:
  traefik:
    image: traefik:v2.2.1
    ports:
    - 80:80
    - 8080:8080
    - 8085:8085
    networks:
      - traefik
    command:
    - "--api=true"
    - "--api.dashboard=true"
    - "--api.insecure=true"
    - "--providers.docker.swarmmode"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    - "--providers.docker.network=traefik"
    - "--log.level=DEBUG"
    - "--accesslog=true"
    - "--entrypoints.web.address=:80"
    - "--entrypoints.ss.address=:8085"
    - "--accesslog.filepath=/path/to/access.log"
    - "--log.filePath=/path/to/traefik.log"
    - "--log.format=json"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      placement:
        constraints:
        - node.hostname == node02
      mode: global
      labels:
      - traefik.docker.network=traefik
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`10.17.25.21`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.api.service=api@internal
       - traefik.http.routers.outgoing_s.rule=Host(`10.17.25.21`) && PathPrefix(`/{pathprefix:(([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)/(.*))}`)
       - traefik.http.routers.outgoing_s.service=traefik
       - traefik.http.routers.outgoing_s.entrypoints=ss
       - traefik.http.routers.outgoing_s.middlewares=replacepathregex
       - "traefik.http.middlewares.replacepathregex.redirectregex.regex=^[a-z]+://[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+:[0-9]+/([0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+)/(.*)"
       - "traefik.http.middlewares.replacepathregex.redirectregex.replacement=http://$${1}/sources/$${2}"
       - traefik.http.middlewares.replacepathregex.redirectregex.permanent=true
  my_service:
    networks:
      - traefik
    image: my_service:0.0.2.3
    deploy:
      restart_policy:
        condition: on-failure
      labels:
      - traefik.enable=true
      - traefik.http.routers.service.rule=(Host(`10.17.25.21`) && PathPrefix(`/{pathprefix:(([a-z]).*)}`))
      - traefik.http.routers.service.entrypoints=ss
      - traefik.http.services.service.loadbalancer.server.port=8085
      - traefik.docker.network=traefik
      - traefik.http.routers.service.service=service
      placement:
        constraints:
        - node.hostname == node02
```
