### ISSUE TITLE
Traefik handling fake http acme requests resulting in massive amounts of errors

### ISSUE THREAD

**Issue by flopana** [traefik/traefik#10042]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

As requested by @rtribotte I open a new issue for [this comment](https://github.com/traefik/traefik/issues/8786#issuecomment-1647832381).

When Traefik receives an http challenge to the `acme-http@internal` router, it processes the request regardless of whether Traefik has initiated an acme challenge or not. This results in a massive amount of errors being generated. As a result, I can't tell the difference between real validation errors and fake ones.

To reproduce this, you can simply send a `GET` request to this router:
`domain.tld/.well-known/acme-challenge/some-random-token-it-doesnt-matter`.

### What did you see instead?

As you can see this leads to many errors being printed to the log
![Traefik logs showing the error messages](https://github.com/traefik/traefik/assets/28308182/01849724-002d-489d-9dff-b8bc7addf489)

The problem for me is I get spammed daily by bots that trigger random acme challenges. This results in hundreds of validation errors in my log files.

This currently makes validation errors completely pointless because I can't differentiate between real ones from Let's Encrypt and fake requests from bots.

In my opinion Traefik should not output failed validation errors for acme challenges that Traefik never initiated. These requests should just be ignored and return 404 or something like that instead of error messages.

https://www.abuseipdb.com/check/3.144.155.159
https://www.abuseipdb.com/check/54.149.111.225
https://www.abuseipdb.com/check/3.129.66.5

These are just a couple of ip adresses that spam me. Every single one of them has been reported for this exact behaviour. I currently have a list of 17 IP Adresses all belonging to Amazon, with the exception of one from microsoft, that I collected over the weekend.

Unfortunately it is not viable to whitelist Let's Encrypt because they don't publish their IP Addresses. But it looks like Let's Encrypt uses the subnet `23.178.112.0/24` which is registered to the "Internet Security Research Group" which has Let's Encrypt as one if its projects.

The ISRG also owns a second subnet `64.112.117.0/24` but I haven't received any requests from that subnet.

[Internet Security Research Group on ARIN](https://whois.arin.net/rest/org/ISRG.html)
[List of their subnets](https://whois.arin.net/rest/org/ISRG/nets)

### What version of Traefik are you using?

Version:      2.10.3
Codename:     saintmarcelin
Go version:   go1.20.5
Built:        2023-06-19T16:18:54Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
api:
  insecure: false
  dashboard: true

log:
  filePath: "/var/log/traefik.log"
  level: info

providers:
  docker:
    exposedByDefault: false
    network: proxy
  file:
    filename: /etc/traefik/services.yml
    watch: true
  redis:
    endpoints:
      - "redis:6379"
    password: "redacted"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "web-secured"
          scheme: "https"
          permanent: true

  web-secured:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "redacted"
      httpChallenge:
        entryPoint: "web"
      storage: "/letsencrypt/acme.json"

```
