### ISSUE TITLE
Missing CORS headers

### ISSUE THREAD

**Issue by yongzhang** [traefik/traefik#10057]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have config like this:

```
    http:
      middlewares:
        corswide:
          headers:
            accessControlAllowMethods:
              - GET
              - HEAD
              - OPTIONS
            accessControlAllowHeaders:
              - "*"
            accessControlAllowOriginList:
              - "*"
            accessControlMaxAge: 86400
            addVaryHeader: true

      routers:
        myservice:
          entryPoints:
            - "web"
          middlewares:
            - "corswide@file"
```

I expect to see response headers as defined above.

### What did you see instead?

By curl my site, I got

```
< access-control-allow-origin: *
access-control-allow-origin: *
```

I don't understand why I'm seeing only one header, I read carefully about the docs, seems like nothing wrong in the config, please help, thanks.

### What version of Traefik are you using?

2.9.10

### What is your environment & configuration?

added above.

And we can see configured headers from dashboard:

![image](https://github.com/traefik/traefik/assets/15604715/e0c68eb3-694f-44df-a003-667b4f45ee7c)

And the middleware was added to that router:

![image](https://github.com/traefik/traefik/assets/15604715/77b31fa8-d895-45a7-b1c2-e4cf828bcffa)

**Comment by yongzhang** [comment]
OK, I think I found the cause,

https://github.com/traefik/traefik/blob/master/pkg/middlewares/headers/header.go#L140

According to above logic, seems like cors headers are only used when request method is `OPTIONS`, and if we need these response headers, we have to add them in customResponseHeaders:

https://github.com/traefik/traefik/blob/master/pkg/middlewares/headers/header.go#L53-L60

So, if I need my expected response headers and let traefik handle preflight requests, I have to use below configs according to https://github.com/traefik/traefik/blob/master/pkg/config/dynamic/middlewares.go#L304-L314:

```
    http:
      middlewares:
        corswide:
          headers:
            accessControlAllowOriginList:
                - "*"
            customResponseHeaders:
              accessControlAllowMethods:
                - GET
                - HEAD
               - OPTIONS
              accessControlAllowHeaders:
                - "*"
              accessControlAllowOriginList:
                - "*"
              accessControlMaxAge: 86400
              addVaryHeader: true
```

Does it make sense? Is it by design?
