### ISSUE TITLE
Bug: Truncated downloads over h2 when upstream delivers unexpected EOF

### ISSUE THREAD

**Issue by laube** [traefik/traefik#10050]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We are using traefik as a reverse proxy and TLS termination for our backend.

The backend serves large files for downloading them via a Webbrowser. The protocol in use is `https` / `h2`.

When the backend unexpectedly closes the connection (for example due to a crash) we expect the download to fail in the webbrowser.

### What did you see instead?

The download stops midway (at the point where the backend failed) and the download completes successfully, despite a mismatch between the downloaded amount of bytes and the `Content-Length` header.

We tested both Firefox and Chrome.

The issue cannot be reproduced when using the HTTP/1.1 protocol without TLS. In that situation the download fails as expected.

To investigate the problem I created a project with multiple configurations of traefik and nginx (as a control). The bug only appears with the configuration where traefik / TLS / h2 is the last reverse proxy facing the client.

The project with all the configuration files is located here: https://github.com/laube/traefik-download-reproducer

### What version of Traefik are you using?

```
Version:      2.10.3
Codename:     saintmarcelin
Go version:   go1.20.5
Built:        2023-06-19T16:18:54Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
entryPoints:
  dev-http:
    address: ':80'
  dev-https:
    address: ':443'
    http:
      tls:
        options: default

providers:
  file:
    directory: /etc/traefik/conf.d
    watch: true

log:
  level: DEBUG
  format: json
accessLog: {}
```

`/etc/traefik/conf.d/app.yml`:

```yaml
tls:
  options:
    default: {}

http:
  services:
    app:
      loadBalancer:
        servers:
          - url: "http://app:3000/"
  routers:
    app:
      entryPoints: ["dev-http", "dev-https"]
      rule: "Host(`localhost`)"
      middlewares: ["proxyHeader"]
      service: "app"
  middlewares:
    proxyHeader:
      headers:
        customRequestHeaders:
          X-Proxy-Name: "traefik"
```

### If applicable, please paste the log output in DEBUG level

```
traefik-download-reproducer-app-1            | 172.27.0.6 - - [26/Jul/2023 17:15:41] "GET /content/5000/kill HTTP/1.1" 200 -
traefik-download-reproducer-app-1            | ... killed before the response was fully produced ...
traefik-download-reproducer-traefik-1        | {"level":"debug","middlewareName":"traefik-internal-recovery","middlewareType":"Recovery","msg":"Request has been ab
orted [172.27.0.1:57648 - /content/5000/kill]: net/http: abort Handler","time":"2023-07-26T17:16:12Z"}
traefik-download-reproducer-traefik-1        | 172.27.0.1 - - [26/Jul/2023:17:15:41 +0000] "GET /content/5000/kill HTTP/2.0" 200 14035512 "-" "-" 3 "dev-https-app@
file" "http://app:3000/" 30465ms
traefik-download-reproducer-traefik-1        | 2023/07/26 17:16:12 reverseproxy.go:667: httputil: ReverseProxy read error during body copy: read tcp 172.27.0.6:462
12->172.27.0.3:3000: read: connection reset by peer
```
