### ISSUE TITLE
dashboard button back by default

### ISSUE THREAD

**Issue by bitdryvr** [traefik/traefik#10058]
>              Hey all, thanks for sharing your stance on this.
> As [2.7.0 is released](https://github.com/traefik/traefik/releases/tag/v2.7.0) and it doesn't have the Hub link anymore I'm going to close this issue.
> 
> _Originally posted by @ddtmachado in https://github.com/traefik/traefik/issues/8912#issuecomment-1140018057_

The button appears to be back as it shows up on a default photoprism installation on v2.9.10:

![image](https://user-images.githubusercontent.com/38570156/256924828-eefb48f1-0f86-4952-abcc-8b610a591477.png)

How do remove the button?

**Comment by ldez** [comment]
Hello,

the Hub button has never been removed in v2.7, I think Douglas made a confusion between Pilot and Hub buttons. Related to #9108.

But in v2.10.4 (the latest release), an option has been added to disable it. #10008
```yml
API:
  # ...
  disabledashboardad: true
  # ...
```
```toml
[api]
  # ...
  disabledashboardad = true
  # ...
```

```bash
# ...
--api.disabledashboardad=true
# ...
```
