### ISSUE TITLE
Traefik exiting with code 0

### ISSUE THREAD

**Issue by martinjgrunwald** [traefik/traefik#10062]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I rebooted the system

### What did you see instead?

This only occurs when the time between reboots is at least 24h. The container exits with code 0

### What version of Traefik are you using?

```
Version:      2.10.4
Codename:     saintmarcelin
Go version:   go1.20.6
Built:        2023-07-24T16:29:02Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/administrator/docker/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/administrator/docker/traefik/traefik.toml:/traefik.toml
      - /home/administrator/docker/traefik/traefik_dynamic.toml:/traefik_dynamic.toml
      - /var/log/traefik:/var/log/traefik

networks:
  default:
    name: proxy
    external: true

```

Add more configuration information here.

`Traefik.toml`
```toml
[entryPoints]
  [entryPoints.web]
    address = ":80"
    
    [entryPoints.web.proxyProtocol]
      insecure = true
[api]
  dashboard = true
  insecure = true

[providers.docker]
  watch = true
  network = "proxy"

[providers.file]
  filename = "traefik_dynamic.toml"

[log]
  level = "DEBUG"
  filePath = "/var/log/traefik/traefik.log"

[accessLog]
  filePath = "/var/log/traefik/access.log"
    [accessLog.filters]
      statusCodes = ["404-499"]
      [accessLog.fields.names]
         StartUTC = "drop"

```

### If applicable, please paste the log output in DEBUG level

```
time="2023-08-01T11:42:54+02:00" level=info msg="I have to go..."
time="2023-08-01T11:42:54+02:00" level=info msg="Stopping server gracefully"
time="2023-08-01T11:42:54+02:00" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2023-08-01T11:42:54+02:00" level=error msg="Error while starting server: accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2023-08-01T11:42:54+02:00" level=error msg="accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2023-08-01T11:42:54+02:00" level=error msg="close tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2023-08-01T11:43:04+02:00" level=info msg="Server stopped"
time="2023-08-01T11:43:04+02:00" level=info msg="Shutting down"
time="2023-08-01T11:43:04+02:00" level=error msg="Failed to list containers for docker, error Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?limit=0\": context canceled" providerName=docker
time="2023-08-01T11:43:04+02:00" level=error msg="Cannot connect to docker server context canceled" providerName=docker
```
