### ISSUE TITLE
Support Failover Load-balancing

### ISSUE THREAD

**Issue by Tester98** [traefik/traefik#1007]
### What version of Traefik are you using (`traefik version`)?
v1.1.2

### What is your environment & configuration (arguments, toml...)?
linux, simple file backend

```toml
[backends]
  [backends.testing]
    [backends.testing.servers.server1]
    url = "http://primary:80"
    weight = 1
    [backends.testing.servers.server2]
    url = "http://backup:80"
    weight = 1
```

### What did you do?

I want to do load balancing simple active passive. however i want to use server only as backup ( in case of failure of network issues)

### What did you expect to see?
Wanted to see a simple case working where failover is supported instead of load-balancing

### What did you see instead?
Couldn't figure out how it will work by reading documentation N times. 

The use case is simple i have 2 server in single backend, one primary and one backup. However i would like to sent traffic to backup  only when primary is not working ( tcp connection could not be made).

I have tested some odd forms, where i add some abnormally high weight to primary and set retry to yes. In this case if primary is not responding,  retry again chooses the  primary  instead of backup.  So,  retry should be skipping the primary server toactually retry. This is broken. 

Can someone help me  to configure such as a case ?
