### ISSUE TITLE
Docker privileged port are not openable in beaufort image

### ISSUE THREAD

**Issue by julichan** [traefik/traefik#10080]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hello,

I attempted to open port 80/443 in traeffik beaufort docker using a macvlan network but I get a permission denied error when trying to open them. There is no port binding and the NET_BIND and NET_ADMIN capabilities and user/group id are provided through docker-compose and set to 1000. It works if I remove the user/group setting in docker-compose (so using root user) Or if i set it to use a port above 1024.
I am using Docker on a synology host with latest DSM 7.2. I am able to open the same ports with other image/containers (e.g Adguard Home) with same user/group, capabilities settings in the same macvlan network which I think means there is some kind of restriction in the image.

Any idea ?

### What did you see instead?

A failure to open listening port with permission denied error.

### What version of Traefik are you using?

Version:      3.0.0-beta3
Codename:     beaufort
Go version:   go1.20.5
Built:        2023-06-22T08:58:13Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

docker-compose:
```yaml
networks:
  dockervlan:
    name: dockervlan
    external: true
  dockernet:
    name: dockernet
    external: true

services:
  server:
    restart: unless-stopped
    image: "traefik:beaufort"
    user: "1000:1000"
    container_name: "traefik-private-server"
    networks:
      dockernet:
      dockervlan:
        ipv4_address: 192.168.10.65
    volumes:
    - /volume2/docker/traefik-private/server/config:/etc/traefik:ro
    - /volume2/docker/traefik-private/server/log:/log/traefik
    - /volume2/docker/acme-certs:/etc/certs:ro
    - /etc/localtime:/etc/localtime:ro
    cap_add:
    - NET_ADMIN
    - NET_BIND_SERVICE
```
dockervlan is an external macvlan and dockernet is a bridge network

traefik.yml:
```yaml
defaultEntryPoints:
  - api
  - web
  - websecure

entryPoints:
  api:
    address: :1080
  web:
    address: :80
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

api:
  dashboard: true

providers:
  file:
    directory: /etc/traefik/services
    watch: true

log:
  level: DEBUG
  filepath: /log/traefik/log.log
  format: json

accessLog:
  filepath: /log/traefik/access.log
  format: json
  bufferingSize: 1000
```

### If applicable, please paste the log output in DEBUG level

{"level":"info","version":"3.0.0-beta3","time":"2023-08-14T14:06:59+02:00","caller":"github.com/traefik/traefik/v3/cmd/traefik/traefik.go:100","message":"Traefik version 3.0.0-beta3 built on 2023-06-22T08:58:13Z"}
{"level":"debug","staticConfiguration":{"global":{"checkNewVersion":true},"serversTransport":{"maxIdleConnsPerHost":200},"tcpServersTransport":{"dialKeepAlive":"15s","dialTimeout":"30s"},"entryPoints":{"api":{"address":":1080","transport":{"lifeCycle":{"graceTimeOut":"10s"},"respondingTimeouts":{"idleTimeout":"3m0s"}},"forwardedHeaders":{},"http":{},"http2":{"maxConcurrentStreams":250},"udp":{"timeout":"3s"}},"web":{"address":":80","transport":{"lifeCycle":{"graceTimeOut":"10s"},"respondingTimeouts":{"idleTimeout":"3m0s"}},"forwardedHeaders":{},"http":{"redirections":{"entryPoint":{"to":"websecure","scheme":"https","permanent":true,"priority":2147483646}}},"http2":{"maxConcurrentStreams":250},"udp":{"timeout":"3s"}},"websecure":{"address":":443","transport":{"lifeCycle":{"graceTimeOut":"10s"},"respondingTimeouts":{"idleTimeout":"3m0s"}},"forwardedHeaders":{},"http":{},"http2":{"maxConcurrentStreams":250},"udp":{"timeout":"3s"}}},"providers":{"providersThrottleDuration":"2s","file":{"directory":"/etc/traefik/services","watch":true}},"api":{"dashboard":true},"log":{"level":"DEBUG","format":"json","filePath":"/log/traefik/log.log"},"accessLog":{"filePath":"/log/traefik/access.log","format":"json","filters":{},"fields":{"defaultMode":"keep","headers":{"defaultMode":"drop"}},"bufferingSize":1000}},"time":"2023-08-14T14:06:59+02:00","caller":"github.com/traefik/traefik/v3/cmd/traefik/traefik.go:107","message":"Static configuration loaded [json]"}
{"level":"info","time":"2023-08-14T14:06:59+02:00","caller":"github.com/traefik/traefik/v3/cmd/traefik/traefik.go:656","message":"\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"}
{"level":"error","error":"command traefik error: error while building entryPoint web: error preparing server: error opening listener: listen tcp :80: bind: permission denied","time":"2023-08-14T14:06:59+02:00","caller":"github.com/traefik/traefik/v3/cmd/traefik/traefik.go:82","message":"Command error"}
