### ISSUE TITLE
Certificate generation error with lets encrypt

### ISSUE THREAD

**Issue by LucnElmr** [traefik/traefik#10094]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I expose a service with an auto-generated lets encrypt certificate and it doesn't work.

### What did you see instead?

/

### What version of Traefik are you using?

2.10.4

### What is your environment & configuration?

```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: ERROR
  format: common
  filePath: /var/log/traefik/traefik.log

accesslog:
  format: common
  filePath: /var/log/traefik/access.log

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
  #    http:
  #      redirections:
  #        entryPoint:
  #          to: websecure
  #          scheme: https

  websecure:
    address: :443

certificatesResolvers:
  staging:
    acme:
      email: lucien.elmer@icloud.com
      storage: /etc/traefik/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

  production:
    acme:
      email: lucien.elmer@icloud.com
      storage: /etc/traefik/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false

  rest:
    insecure: true
```

docker compose => 
```yaml
services:
  traefik:
    image: traefik
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080 # Dashboard
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
```

### If applicable, please paste the log output in DEBUG level

/var/log/traefik # cat traefik.log
time="2023-08-26T17:41:21Z" level=error msg="Unable to obtain ACME certificate for domains \"lucien.hortiprod.ch\": unable to generate a certificate for the domains [lucien.hortiprod.ch]: error: one or more domains had a problem:\n[lucien.hortiprod.ch] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 62.12.170.90: Fetching http://lucien.hortiprod.ch/.well-known/acme-challenge/BhnZBzc9gBXwP2EH5mOqeUIj2auoob4VsC3U4YsRGEM: Timeout during connect (likely firewall problem)\n" rule="Host(`lucien.hortiprod.ch`)" ACME CA="https://acme-staging-v02.api.letsencrypt.org/directory" providerName=staging.acme routerName=indra-ui@docker
