### ISSUE TITLE
Traefik responds with Connection: close even though upstream says Connection: keep-alive

### ISSUE THREAD

**Issue by ledgitbe** [traefik/traefik#10092]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

My Express server responds like this:

GET /events?project_id=83dd9e7f-ef6b-4f73-ae1b-8919ece25206&history=1 HTTP/1.1
Cache-Control: no-cache
Accept: text/event-stream
Authorization: Bearer XXXXXXXXXXX
Host: localhost:8777
Connection: close

HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: text/event-stream
Connection: keep-alive
Cache-Control: no-cache
Vary: Accept-Encoding
Date: Fri, 25 Aug 2023 08:23:42 GMT
Transfer-Encoding: chunked

59b
data: {"txid":"08ef1b5affe59521c4ec2436357f39f749aa877d0f80a899865e0a7156644ed5","status":2,"block":null } 
id: 08ef1b5affe59521c4ec2436357f39f749aa877d0f80a899865e0a7156644ed5 

### What did you see instead?

When proxied through Traefik, the response looks like this:

GET /events?project_id=c7e73fe5-2346-4206-8fb8-a74a45047d2c&history=1 HTTP/1.1
Cache-Control: no-cache
Accept: text/event-stream
Authorization: Bearer XXXXXXXXXXXXXXXXX
Host: viatraefik.test.com
Connection: close

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Content-Type: text/event-stream
Date: Fri, 25 Aug 2023 08:25:46 GMT
Vary: Accept-Encoding
Vary: Accept-Encoding
X-Powered-By: Express
Connection: close
Transfer-Encoding: chunked

### What version of Traefik are you using?

v2.10

### What is your environment & configuration?

configuration of traefik

```yaml

services:
  traefik:
    image: traefik:v2.10
    # sysctls:
    #     - net.ipv4.vs.conn_reuse_mode=0
    #     - net.ipv4.vs.expire_nodest_conn=1
    ports:
      - target: 80
        published: 80
          #mode: host
    command:
      - --providers.docker
      - --providers.file.directory=/etc/traefik/conf.d
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmMode=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.forwardedHeaders.insecure=true
      - --accesslog
      - --log
      - --api
      - --metrics.prometheus=true
      - --metrics.prometheus.buckets=0.1,0.3,1.2,5.0
    networks:
      - traefik-public
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    configs:
      - source: chaingraph
        target: /etc/traefik/conf.d/chaingraph.yaml
      - source: nftdocs
        target: /etc/traefik/conf.d/nftdocs.yaml
      - source: statuspage
        target: /etc/traefik/conf.d/statuspage.yaml
    deploy:
      mode: global
      update_config:
        order: stop-first
        parallelism: 1
      rollback_config:
        order: stop-first
        parallelism: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "2"
          memory: 4096M
        reservations:
          cpus: "0.5"
          memory: 1024M
      placement:
        constraints:
          - node.role == manager
        max_replicas_per_node: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.middlewares.admin-auth.basicauth.users=${USERS_ADMIN}
        - traefik.http.middlewares.developer-auth.basicauth.users=${USERS_DEVELOPER}
        - traefik.http.middlewares.guest-auth.basicauth.users=${USERS_GUEST}
        - "traefik.http.middlewares.redirect-dashboard-console.redirectregex.regex=^https?://dashboard\\.xxxxxxxxx\\.com/(.*)"
        - "traefik.http.middlewares.redirect-dashboard-console.redirectregex.replacement=https://console.xxxxxxxxx.com/$${1}"
        - "traefik.http.middlewares.redirect-dashboard-console.redirectregex.permanent=true"
        - 'traefik.http.middlewares.no-compress-sse.compress=true'
        - 'traefik.http.middlewares.no-compress-sse.compress.excludedcontenttypes=text/event-stream'
        - traefik.http.routers.traefik.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.traefik.entrypoints=web
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.routers.traefik.middlewares=admin-auth
        - traefik.http.services.traefik.loadbalancer.server.port=8080
        - traefik.http.middlewares.upload-limit.buffering.maxRequestBodyBytes=1000000000

configuration of the hosted service
```
yaml`

      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=traefik-public'
        - 'traefik.constraint-label=traefik-public'
        - 'traefik.http.routers.apixxxxxxxxx.rule=Host(`${DEPLOYMENT}`)'
        - 'traefik.http.routers.apixxxxxxxxx.service=apixxxxxxxxx'
        - 'traefik.http.routers.apixxxxxxxxx.middlewares=no-compress-sse@docker'
        - 'traefik.http.services.apixxxxxxxxx.loadbalancer.server.port=8777'
`
Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

I didn't see any related logs except for 

time="2023-08-25T09:50:58Z" level=debug msg="mime: no media type" middlewareName=no-compress-sse@docker middlewareType=Compress
