### ISSUE TITLE
Http -> Https redirect sends to 403 page

### ISSUE THREAD

**Issue by Grasume** [traefik/traefik#10104]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Attempting to set up a single HTTP - > HTTPS router returns 403 Forbidden page.
Page i have found out comes from Traefik and not the end user application
Tested with 2 different container images Custom / WHOAMI Traefik contianer

### What did you see instead?

I expect to be sent to https of the whoami not a 403 Forbidden Traefik container.

### What version of Traefik are you using?

Version:      3.0.0-beta3
Codename:     beaufort
Go version:   go1.20.5
Built:        2023-06-22T08:58:13Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

Code is below not sure what im doing wrong
Traefik container
```traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    command:
      - --log.level=DEBUG
      - --accesslog=true
      - --tracing=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --certificatesresolvers.seat.acme.tlschallenge=true
      - --certificatesresolvers.seat.acme.email=blah@blah.com
      - --certificatesresolvers.seat.acme.storage=./letsencrypt/seat-acme.json

    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt/
      - ./logs/access.log:/logs/access.log
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.home.arpa`)
      - traefik.http.services.traefik.loadBalancer.server.port=8080
      - traefik.http.routers.traefik.entrypoints=web
    networks:  
      - docker_services
  ```
Whoami Container
``` 
version: '3.7'

services:
  whoami-test:
    image: traefik/whoami:v1.9
    container_name: "whoami-test"
    restart: always
    labels:
      - traefik.enable=true

      - traefik.http.routers.whoami-http.rule=Host(`whoami.${DOMAIN}`)
      
      - traefik.http.routers.whoami-http.entrypoints=web
      - traefik.http.routers.whoami-http.middlewares=whoami-https-redirect
      - traefik.http.routers.whoami-https.rule=Host(`whoami.${DOMAIN}`)
      - traefik.http.routers.whoami-https.entrypoints=websecure
      - traefik.http.routers.whoami-https.tls.certResolver=seat
      - traefik.http.routers.whoami-https.tls=true
      - traefik.http.middlewares.whoami-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.whoami-https-redirect.redirectscheme.permanent=true
  
    networks:
      - docker_services

networks:
  docker_services:
    external: true
```

### If applicable, please paste the log output in DEBUG level

No good information found in Logs
