### ISSUE TITLE
Requests to main service breaks with 404 if mirrored service selected deployment has 0 pods.

### ISSUE THREAD

**Issue by vtomar10** [traefik/traefik#10120]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Not sure if this is a bug or a feature but seems like a bug.

I have a simple traefik service setup

**Traefik Services**

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: xyz
spec:
  mirroring:
    name: xyz-base
    kind: TraefikService
    mirrors:
      - name: xyz-mirror
        kind: TraefikService
        percent: 1
```

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: xyz-base
spec:
  weighted:
    services:
      - name: svc
        port : 80
```

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: xyz-mirror
spec:
  weighted:
    services:
      - name: svc-mirror
        port : 80
```

**K8s services**

```yaml
apiVersion: v1
kind: Service
metadata:
  name: svc-mirror
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: external-http-port
  selector:
    app: svc-mirror
  type: ClusterIP
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: external-http-port
  selector:
    app: svc
  type: ClusterIP
```

I have K8s _Deployments_ resources namely `xyz` and `xyz-mirror` which match these label selectors for `svc` and `svc-mirror` respectively to serve the requests. 

Now, everything works fine as long as k8s deployment `xyz-mirror` has more than 0 pods. But if we scale down pods to zero on `xyz-mirror`, requests on `svc` breaks with HTTP status code 404. This happens even if percentage mirroring is set to 0.

### What did you see instead?

Everything works fine as long as k8s deployment `xyz-mirror` has more than 0 pods. But if we scale down pods to zero on `xyz-mirror`, requests on `svc` breaks with HTTP status code 404. This happens even if percentage mirroring is set to 0.

### What version of Traefik are you using?

v2.9.1

### What is your environment & configuration?

Configs shared above.
