### ISSUE TITLE
mTLS RequireAndVerifyClientCert does not request cert actively

### ISSUE THREAD

**Issue by Flexusma** [traefik/traefik#10134]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I configured mTLS as laid out in the docs and https://smallstep.com/hello-mtls/doc/server/traefik.

Everything except traefik actively requesting the cert during the tls handshake works.

If traefik were requesting client auth correctly I would be notified by my browser to assign a valid client cert (ios as well as desktop firefox and chrome)

### What did you see instead?

I have to manually add the client cert to those browsers to make it work.
On ios it doesn't work at all even if the client cert is added to trusted certificates and with the root CA installed.

### What version of Traefik are you using?

2.10.4

### What is your environment & configuration?

```yaml

# mTLS (client cert auth)
tls:
  options:
    websecure:
      clientAuth:
        caFiles:
          - /etc/traefik/websecure.crt
        clientAuthType: "RequireAndVerifyClientCert"


------ other file
http:
  services:
    ans.xxx:
      loadBalancer:
        servers:
          - url: "http://10.0.xxx.xxx:3000"
  routers:
    ans.xxx-http:
      service: ans.xxx
      rule: "Host(`ans.xxx.eu`)"
      middlewares: 
        - red-https
      entrypoints:
        - http
    ans.xxx:
      service: ans.xxx
      rule: "Host(`ans.xxx.eu`)"
      middlewares: cfwarp
      entrypoints: 
        - https
      tls:
        certresolver: lets-encrypt
        options: websecure
```
