### ISSUE TITLE
无法代理SSH

### ISSUE THREAD

**Issue by twbworld** [traefik/traefik#10143]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

您好, 感谢您的观看

我用k8s部署了一个ubuntu容器, 并在容器内安装和配置了ssh-server; 当我尝试使用traefik代理ssh流量时, 无法成功连接, 希望您能帮到我

> 我在 `issues` 上没能找到解决方式

### 配置了traefik的`IngressRouteTCP`代理, 尝试使用代理端口`2222`连接上pod, 但是失败了
> 然而, 使用CLUSTER-IP或者pod-ip连接却是正常的

### 使用ssh连接pod
![image](https://github.com/traefik/traefik/assets/52546134/f1534c18-e00e-4356-8626-c45eb41a53eb)

### What version of Traefik are you using?

![image](https://github.com/traefik/traefik/assets/52546134/f6aa00da-b017-4bb6-8442-b0e6df1783e0)

### What is your environment & configuration?

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      sshport:
        port: 2222
        expose: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ssh
spec:
  entryPoints:
    - sshport
  tls:
    passthrough: true
  routes:
    - match: HostSNI(`*`)
      services:
        - name: ubuntu-svc
          port: sp
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-svc
spec:
  selector:
    app: ubuntu-container
  type: ClusterIP
  ports:
    - name: sp
      port: 22
---
#ssh-server is installed in the pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deploy
spec:
  selector:
    matchLabels:
      app: ubuntu-container
  template:
    metadata:
      name: ubuntu-deploy
      labels:
        app: ubuntu-container
    spec:
      containers:
        - name: ubuntu-container
          image: ubuntu:latest
          tty: true
          ports:
            - name: cp
              containerPort: 22
```
