### ISSUE TITLE
IngressRoute not updated on `kubectl apply`

### ISSUE THREAD

**Issue by lukaso** [traefik/traefik#10149]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I `kubectl apply` an `IngressRoute` to updated an existing `IngressRoute`. I expected the route to update.

I checked the output of `kustomize build`. The output there is correct.
The output of `kubectl apply` is not correct.

### What did you see instead?

What I saw was that my middlewares were not applied, and services did not have their ports set on the routes.

I assumed there was something wrong with the pipeline (which ate up a lot of time). However, when I deleted the existing `IngressRoute`, the `kubectl apply` worked perfectly.

This leads me to believe that `IngressRoutes` don't allow updates (at least of middlewares and service ports, but possibly much more).

There are no error messages or warnings in the logs.

Here is someone who appears to have the same problem: https://community.traefik.io/t/middleware-dont-work-with-ingressroute/16870/4

### What version of Traefik are you using?

docker.io/traefik:v2.10.4

### What is your environment & configuration?

Output of `kustomize build`

```yaml
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  namespace: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`ingress.example.com`) && PathPrefix(`/oauth2`)
    middlewares:
    - name: oauth-errors
      namespace: traefik
    services:
    - name: oauth2-proxy
      namespace: traefik
      port: 4180
  - kind: Rule
    match: Host(`ingress.example.com`)
    middlewares:
    - name: oauth2
      namespace: traefik
    services:
    - name: ingress
      namespace: traefik
      port: 8916
  tls:
    domains:
    - main: ingress.example.com
    secretName: ingress-tls
```

There is an existing `IngressRoute` which I was updating.

I don't have the log anymore, but noticed that `kubectl apply --v=9` was accessing the api and getting the old version from the server, which made me think the existing version was not being updated.
