### ISSUE TITLE
Traefik ACME DNS challenge error when TLS inspection is used on firewall level

### ISSUE THREAD

**Issue by brolifen** [traefik/traefik#10145]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I setup a docker compose using Traefik with DNS Challenge. We have a physical firewall that does TLS termination so everything outbound sees the cert of the firewall. I added this cert to the Traefik container by mounting the volume:

`/etc/pki/ca-trust/source/anchors/:/etc/ssl/certs:ro`

if I inspect the container the volume and cert files are visible to traefik. However Traefik complains that it doesnt trust the ACME provider due to its cert (which is the firewall cert). But  so what does it not trust these certs?

### What did you see instead?

level=error msg="Unable to obtain ACME certificate for domains \"************.************.****\": cannot get ACME client get directory at 'https://acme-v02.api.letsencrypt.org/directory': Get \"https://acme-v02.api.letsencrypt.org/directory\": tls: failed to verify certificate: x509: certificate signed by unknown authority" rule="Host(`************.************.****`)" ACME CA="https://acme-v02.api.letsencrypt.org/directory" providerName=myresolver.acme routerName=********-https@docker

### What version of Traefik are you using?

rsion:      2.10.4
Codename:     saintmarcelin
Go version:   go1.20.6
Built:        2023-07-24T16:29:02Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
version: '3'

networks:
  guacamole-net:
    driver: bridge
    ipam:
     config:
       - subnet: '172.28.0.0/24'
         gateway: '172.28.0.1'
         
services:
  traefik:
    image: 'traefik'
    container_name: traefik
    restart: unless-stopped
    command:
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web-secure.address=:443'
      - '--entrypoints.cockpit.address=:9922' 
      - '--entryPoints.web-secure.forwardedHeaders.trustedIPs=172.28.0.0/24'
      - '--entryPoints.web-secure.proxyProtocol.trustedIPs=172.28.0.0/24'
      #- "--api=true"
      #- "--api.dashboard=true"
      #- "--api.insecure=true"
      - '--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}'
      - '--certificatesresolvers.myresolver.acme.dnschallenge=true'
      - '--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
      - '--certificatesresolvers.myresolver.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53'
    environment:
      - CF_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${WORKING_DIR}/letsencrypt/:/letsencrypt
      - /etc/pki/ca-trust/source/anchors/:/etc/ssl/certs:ro
    networks:
      - guacamole-net
    dns:
      - ${TRAEFIK_DNS}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
```

Add more configuration information here.
