### ISSUE TITLE
Can't use the host assigned by TrayFik to visit the back -end Docker service

### ISSUE THREAD

**Issue by FunkyGod** [traefik/traefik#10158]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

config：
```
version: "3"

services:
  traefik:
    image: traefik:v3.0
    restart: always
    ports:
      - 80:80
      - 8080:8080
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--ping=true"
      - "--entrypoints.http.address=:80"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
    labels:
      - "traefik.http.routers.traefik-dashboard.entrypoints=http"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.console.lab.io`)"
      - "traefik.http.routers.traefik-dashboard.service=dashboard@internal"
      - "traefik.http.routers.traefik-dashboard-api.entrypoints=http"
      - "traefik.http.routers.traefik-dashboard-api.rule=Host(`traefik.console.lab.io`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-dashboard-api.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-dashboard-api.service=api@internal"
      # 中间件
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.routers.traefik-dashboard.middlewares=gzip@docker"
      - "traefik.http.routers.traefik-dashboard-api.middlewares=gzip@docker"
      # 具体服务
      # - "traefik.http.routers.backend-x.rule=Host(`backend-x`) && PathPrefix(`/x/`)"
      # - "traefik.http.routers.backend-auth-service.rule=PathPrefix(`/auth/`)"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy off localhost:8080/ping || exit 1"]
      interval: 3s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - platform-common-net
networks:
  platform-common-net:
    # 声明这个网络是外部定义的
    external: true
```

```
---
# This docker compose file is used for developer to setup
# dev enironment quickly. Only local machine with 
# docker and docker-compose is required.
version: '3.3'
services:
  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      - SMTP_HOST=${SMTP_HOST}
    ports:
      - "8988:8989"
    volumes:
      - ./src:/service
    # tty: true
    command: /bin/sh /service/script/start.sh
    networks:
      - platform-common-net
    labels:
      - "traefik.http.services.backend-x.loadbalancer.server.port=8988"
      - "traefik.http.services.backend-x.loadbalancer.server.scheme=http"
      - traefik.http.routers.backend-x.rule=Host(`backend-x-service`)
networks:
  platform-common-net:
    # 声明这个网络是外部定义的
    external: true
```

### What did you see instead?

![image](https://github.com/traefik/traefik/assets/39259580/3b8888b3-9853-49d1-bd2e-ed62b0699435)
![image](https://github.com/traefik/traefik/assets/39259580/21845dd8-649b-43ab-b537-c7b37bb31f93)
# TWO ISSUE
I try to curl api of backend, but find some problem.
## 1、Why do I need to specify a port for the back-end service？
![image](https://github.com/traefik/traefik/assets/39259580/9e72d744-02ea-4001-a6ed-4defaae3c035)
 ## 2、Can't use the host assigned by TrayFik to visit the back -end Docker service？
![image](https://github.com/traefik/traefik/assets/39259580/0c0a289d-6887-49da-89e6-03ae781511f1)

### What version of Traefik are you using?

v3.0

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.
