### ISSUE TITLE
traefik3.0.0-beta3 field not found, node: customResponseHeaders"

### ISSUE THREAD

**Issue by leonidas-o** [traefik/traefik#10159]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I've added the `customResponseHeaders` with `X-Robots-Tag: "noindex, nofollow"` which causes `field not found, node: customResponseHeaders"` in the logs.
According to docs this should be possible: https://doc.traefik.io/traefik/v3.0/middlewares/http/headers/#customresponseheaders
The same was used in traefik 2 without any issues.

### What did you see instead?

When re-starting traefik, I see the following entry in the logs:
```
2023-10-10T09:45:13Z DBG github.com/traefik/traefik/v3/pkg/provider/file/file.go:73 > Error while building configuration (for the first time) error="/etc/traefik/dynamic-conf/myapp.yml: field not found, node: customResponseHeaders" providerName=file
```

### What version of Traefik are you using?

Version:      3.0.0-beta3
Codename:     beaufort
Go version:   go1.20.5
Built:        2023-06-22T08:58:13Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

dynamic conf:
```yaml
http:
  routers:
    myapp-http-router:
      entryPoints:
      - web
      rule: "Host(`myapp.my-domain.com`)"
      middlewares:
      - myapp-redirectscheme
      service: myapp-service-secure

    myapp-https-router:
      entryPoints:
      - websecure
      rule: "Host(`myapp.my-domain.com`)"
      middlewares:
      - myapp-headers
      - myapp-ipwhitelist
      service: myapp-service-secure
      tls: {}

  services:
    myapp-service-secure:
      loadBalancer:
        servers:
        - url: "https://myapp1.my-domain.com:31349"

  middlewares:
    myapp-headers:
      headers:
        accessControlAllowOriginList: "*"
    myapp-redirectscheme:
      redirectScheme:
        scheme: https
    myapp-ipwhitelist:
      ipAllowList:
        sourceRange:
          - "xx.xx.xx.xx/32"
          - "xx.xxx.xx.xx/32"

tls:
  certificates:
    - certFile: /etc/traefik/ssl/my-domain.com.fullchain.pem
      keyFile: /etc/traefik/ssl/my-domain.com.key
```

Add more configuration information here.

static conf:
```yaml
api:
  dashboard: true
  debug: false
  insecure: false
log:
  # default: ERROR
  # possible: DEBUG, PANIC, FATAL, ERROR, WARN, INFO
  level: DEBUG

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

  ldap:
    address: ":389"

  ldaps:
    address: ":636"

providers:
  file:
    directory: /etc/traefik/dynamic-conf
    # fsnotify not working with nfs
    watch: true
```

### If applicable, please paste the log output in DEBUG level

```
2023-10-10T09:45:13Z DBG github.com/traefik/traefik/v3/pkg/provider/file/file.go:73 > Error while building configuration (for the first time) error="/etc/traefik/dynamic-conf/myapp.yml: field not found, node: customResponseHeaders" providerName=file
```

**Comment by ldez** [comment]
Hello,

To keep the repository focused, we ask that all questions be asked in the [community forum](https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there. 
If not, you can ask and get help from other community members pretty quickly.

https://doc.traefik.io/traefik/v3.0/reference/dynamic-configuration/file/

```yml
http:
  middlewares:
    myMiddleware:
      headers:
        customResponseHeaders:
          name0: foobar
          name1: foobar
```
