### ISSUE TITLE
Fix Service Fabric Integration with Traefik

### ISSUE THREAD

**Issue by nmengin** [traefik/traefik#10168]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

## Context

The embedded support of [Service Fabric](https://doc.traefik.io/traefik/v1.7/configuration/backends/servicefabric/) hasn't been ported to Traefik v2.

It was decided that people could take advantage of [Traefik plugins](https://plugins.traefik.io/plugins) to integrate Service Fabric support.

Microsoft provided an [integration](https://github.com/microsoft/service-fabric-traefik) using a different technology (they generate the dynamic configuration in a file). 

Users can add this file to their configuration using the [File](https://doc.traefik.io/traefik/providers/file/) provider.

However, some Service Fabric users have reported problems with it that seem to come from shortcut conditions when the file is deleted or emptied during the update, resulting in a temporary empty configuration.

## Goal

Consider a mechanism to fix the issue described above and decide whether this mechanism makes sense in the first place.

We are considering two solutions:

- Creating a dedicated (experimental) provider in Traefik (more information below)
- Extending the existing File provider (more information below)

Of course, feel free to discuss any other option here.

## Timeline

Conversation is time-boxed to one month.

## Additional Information on Dedicated Provider

Inspired by the existing File provider, it allows users to set the name of the file generated by Service Fabric plugin.

The configuration is propagated to Traefik when the file is modified, but only if it exists and it is not empty.

We propose to tag the provider as experimental at first.

```yaml
experimental:
  serviceFabric: true

providers:
  serviceFabric:
    filename: sf_xxx.yaml # Service Fabric generated file
```

### List the mandatories files

Add an option `mandatoriesFiles` to set the files that must exist and contain data to allow for configuration propagation. This option could be used with the existing `filename` and `directory` options.

```yaml
providers:
  file:
    mandatoriesFiles:
      - myfile01
      - myfile02
    filename: # mutually exclusive with directory
    directory: # mutually exclusive with filename
```

### Set a boolean

Add an option `files` that allows setting a list of files to watch (the `files`, `filename`, and `directory` options are mutually exclusive). Add a boolean `noEmptyConfiguration` to avoid propagating the configuration if the files set (`filename` or `files`) don't exist or are empty.

```yaml
providers:
  file:
    files: # mutually exclusive with directory and filename
      - myfile01
      - myfile02
    filename: # mutually exclusive with directory and files
    directory: # mutually exclusive with filename and files
    noEmptyConfiguration: true # False by default, not for directory
```
