### ISSUE TITLE
Cannot collect host header as label in prometheus metrics endpoint

### ISSUE THREAD

**Issue by drpebcak** [traefik/traefik#10169]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I added this static configuration to traefik - `--metrics.prometheus.headerlabels.hostname=Host` and expected to see metrics labelled with that information on the `/metrics` endpoint.

### What did you see instead?

I saw metrics being emitted with only an empty value for this label, like `hostname=""`.

Using `User-Agent` as the documentation does results in seeing real values on the label.

### What version of Traefik are you using?

2.10.5

### What is your environment & configuration?

Deployed into kubernetes, using the latest helm chart (24.0.0)

These are the values I am passing in:
```yaml
image:
  tag: v2.10.5
additionalArguments:
  - "--metrics.prometheus.headerlabels.hostname=Host"
  - "--accesslog"
  - "--accesslog.format=json"
  - "--accesslog.filepath=/data/access.log"
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
  kubernetesIngress:
    allowExternalNameServices: true
    publishedService:
      enabled: true
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
ingressRoute:
  dashboard:
    enabled: false
ingressClass:
  isDefaultClass: true
deployment:
  kind: DaemonSet
ports:
  web:
    redirectTo: websecure
```

Add more configuration information here.
