### ISSUE TITLE
Traefik dashboard returns 404 for rules that contain / character in their names

### ISSUE THREAD

**Issue by jwadolowski** [traefik/traefik#10177]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

1. Load the following config
```yaml
http:
  routers:
    "GET /dump/request":
      entryPoints:
        - internet
      service: httpbingo
      rule: >-
        Method(`GET`) &&
        Host(`localhost`) &&
        Path(`/dump/request`)
    get-headers:
      entryPoints:
        - internet
      service: httpbingo
      rule: >-
        Method(`GET`) &&
        Host(`localhost`) &&
        Path(`/headers`)
  services:
    httpbingo:
      loadBalancer:
        servers:
          - url: https://httpbingo.org
        passHostHeader: false
```
2. Go to http://localhost:8080/dashboard/#/http/routers
![cleanshot_2023-10-18T181243_Dcs6TBVm@2x](https://github.com/traefik/traefik/assets/6334715/5c464d0e-ccb3-4e39-bf53-f6fcf67d825b)
3. Click on the rule named `GET /dump/request@file` (browser URL: http://localhost:8080/dashboard/#/http/routers/GET%20/dump/request@file) -> 404
![cleanshot_2023-10-18T181317_itla7Meh@2x](https://github.com/traefik/traefik/assets/6334715/220a4f65-1e91-43d2-9a20-26e33194b653)
4. Go back and select `get-headers@file` rule (browser URL: http://localhost:8080/dashboard/#/http/routers/get-headers@file) -> 200
![cleanshot_2023-10-18T181555_xT2kmGXu@2x](https://github.com/traefik/traefik/assets/6334715/02da2d0b-035e-457e-82c8-d5035f15a464)

### What did you see instead?

404 from the dashboard

### What version of Traefik are you using?

```
$ docker run traefik version
Version:      2.10.5
Codename:     saintmarcelin
Go version:   go1.21.3
Built:        2023-10-11T13:54:02Z
OS/Arch:      linux/arm64
```

### What is your environment & configuration?

Configuration files:
- `traefik.yml`
```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: false
entryPoints:
  internet:
    address: :80
log:
  level: DEBUG
accessLog:
  format: common
api:
  insecure: true
  dashboard: true
ping:
  entryPoint: traefik
providers:
  file:
    filename: /etc/traefik/dynamic/dev.yml
    watch: true
```
- `dev.yaml`
```yaml
http:
  routers:
    "GET /dump/request":
      entryPoints:
        - internet
      service: httpbingo
      rule: >-
        Method(`GET`) &&
        Host(`localhost`) &&
        Path(`/dump/request`)
    get-headers:
      entryPoints:
        - internet
      service: httpbingo
      rule: >-
        Method(`GET`) &&
        Host(`localhost`) &&
        Path(`/headers`)
  services:
    httpbingo:
      loadBalancer:
        servers:
          - url: https://httpbingo.org
        passHostHeader: false
```

Start Treafik using the following command:

```
$ docker run -p 8080:8080 -p 80:80 -v "${PWD}/traefik.yml:/etc/traefik/traefik.yml" -v "${PWD}/dev.yml:/etc/traefik/dynamic/dev.yml" traefik:v2.10.5
```

Both routes work correctly, it's just a dashboard glitch:

```
$ curl http://localhost/dump/request -SsD -
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: text/plain; charset=utf-8
Date: Wed, 18 Oct 2023 16:19:37 GMT
Fly-Request-Id: 01HD1SBQHMC2PTQ5MCXJEC9F1E-waw
Server: Fly/55f8eaa0 (2023-10-09)
Via: 2 fly.io
Transfer-Encoding: chunked

GET /dump/request HTTP/1.1
Host: httpbingo.org
Accept: */*
Accept-Encoding: gzip
Fly-Client-Ip: 109.173.182.19
Fly-Forwarded-Port: 443
Fly-Forwarded-Proto: https
Fly-Forwarded-Ssl: on
Fly-Region: waw
Fly-Request-Id: 01HD1SBQHMC2PTQ5MCXJEC9F1E-waw
Fly-Traceparent: 00-a7cfe0633bf7f20cba25035e47572c92-2e8804282daae6e2-00
Fly-Tracestate:
User-Agent: curl/8.4.0
Via: 2 fly.io
X-Forwarded-For: 192.168.65.1, 77.83.142.42
X-Forwarded-Host: localhost
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: c03f3f6cfe87
X-Forwarded-Ssl: on
X-Real-Ip: 192.168.65.1
X-Request-Start: t=1697645977140856

$ curl http://localhost/headers -SsD -
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Date: Wed, 18 Oct 2023 16:19:41 GMT
Fly-Request-Id: 01HD1SBVSQDSN7WA7FAAMAN282-waw
Server: Fly/55f8eaa0 (2023-10-09)
Via: 2 fly.io
Transfer-Encoding: chunked

{
  "headers": {
    "Accept": [
      "*/*"
    ],
    "Accept-Encoding": [
      "gzip"
    ],
    "Host": [
      "httpbingo.org"
    ],
    "User-Agent": [
      "curl/8.4.0"
    ],
    "Via": [
      "2 fly.io"
    ],
    "X-Forwarded-For": [
      "192.168.65.1, 77.83.142.42"
    ],
    "X-Forwarded-Host": [
      "localhost"
    ],
    "X-Forwarded-Port": [
      "80"
    ],
    "X-Forwarded-Proto": [
      "http"
    ],
    "X-Forwarded-Server": [
      "c03f3f6cfe87"
    ],
    "X-Forwarded-Ssl": [
      "on"
    ],
    "X-Real-Ip": [
      "192.168.65.1"
    ],
    "X-Request-Start": [
      "t=1697645981495814"
    ]
  }
}
```

### If applicable, please paste the log output in DEBUG level

N/A
