### ISSUE TITLE
command traefik error: field not found, node: [0]

### ISSUE THREAD

**Issue by PunkHaz4rd** [traefik/traefik#10170]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Running docker compose up -d and checking the logs I get the single log, repeating each time the traefik container restarts:
```
command traefik error: field not found, node: [0]
```
It used to work before I `docker compose down` and `docker compose up -d`  and I haven't changed anything in the conf in between.

### What did you see instead?

 I tried getting more logs by changing the level, but since the image isn't even running, but keep restarting, I cannot get anything more than the cryptic error.
I tried to remove the image in case it was somehow corrupted, multiple times, to no avail.

### What version of Traefik are you using?

Version:      2.10.5
Codename:     saintmarcelin
Go version:   go1.21.3
Built:        2023-10-11T13:54:02Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
#docker-compose.yml

version: '3.7'
services:
  traefik:
    image: traefik:2.10
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    environment:
      - "TZ=Europe/Paris"
      - "OVH_ENDPOINT_FILE=/run/secrets/ovh_endpoint"
      - "OVH_APPLICATION_KEY_FILE=/run/secrets/ovh_application_key"
      - "OVH_APPLICATION_SECRET_FILE=/run/secrets/ovh_application_secret"
      - "OVH_CONSUMER_KEY_FILE=/run/secrets/ovh_consumer_key"
    secrets:
      - ovh_endpoint
      - ovh_application_key
      - ovh_application_secret
      - ovh_consumer_key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik-config/:/etc/traefik/config/:ro
      - ./logs:/var/log/traefik
      - traefik_ssl:/letsencrypt
    networks:
      - traefik
    restart: unless-stopped

  # ... other services that are all running ...

secrets:
  ovh_endpoint:
    file: "./secrets/ovh_endpoint.secret"
  ovh_application_key:
    file: "./secrets/ovh_application_key.secret"
  ovh_application_secret:
    file: "./secrets/ovh_application_secret.secret"
  ovh_consumer_key:
    file: "./secrets/ovh_consumer_key.secret"

volumes:
  traefik_ssl:
    name: traefik_ssl

networks:
  traefik:
    name: traefik
```
```yml
# traefik.yml
global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          - to: https
          - scheme: https
          - permanent: true
  https:
    address: :443

api:
  dashboard: false

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/config/
    watch: true
    debugLogGeneratedTemplate: true

certificatesResolvers:
  mydnschallenge:
    acme:
      email: "email@email.com"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: ovh
        delayBeforeCheck: 10
log:
  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: DEBUG
  filePath: /var/log/traefik/traefik.log
  # common, json
  format: json

accessLog:
  filePath: /var/log/traefik/access.log
  # common, json
  format: json
```

```yml
# middlewares.yml

http:
  middlewares:
    secHeaders:
      headers:
        forceSTSHeader: true
        stsIncludeSubdomains: false
        stsSeconds: 31536000
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
```

```yml
# tls.yml

tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
```
