### ISSUE TITLE
Body is ignored while in HTTP/3 over QUIC without pre-defined Content-Length

### ISSUE THREAD

**Issue by Ousret** [traefik/traefik#10185]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We use Traefik as part of our testing CI/CD pipelines for our HTTP client. And we have observed the following.

**Having the following HTTP client installed (Python):**

```
pip install niquests
```

**With the following script:**

```python
import niquests
from io import BytesIO
from base64 import b64decode

if __name__ == "__main__":
    fp = BytesIO(b"foo" * 256)
    
    # the first request will be made over TCP & HTTP/2
    r = niquests.post("https://httpbin.local/post", data=fp, verify=False)
    
    payload_seen_by_server = b64decode(r.json()["data"][37:])

    assert payload_seen_by_server == b"foo" * 256
    
    # the second request will be made over UDP & HTTP/3
    r = niquests.post("https://httpbin.local/post", data=fp)
    
    payload_seen_by_server = b64decode(r.json()["data"][37:], verify=False)

    assert payload_seen_by_server == b"foo" * 256
```

If you replace `https://httpbin.local` with `https://pie.dev` which is served by nginx behind Cloudflare (live wan), it works.

### What did you see instead?

The second assert always fails and the httpbin service never receives the payload.

Weirdly, in <= v2.10.4 if you patch the second request as follows:

```python
# the second request will be made over UDP & HTTP/3
r = niquests.post("https://httpbin.local/post", data=fp, headers={"Content-Length": "-1"}, verify=False)
```

It works, but it is a clear violation of HTTP 3/Streams protocols.

With >= v2.10.5, Traefik closes the stream with an error, so now it is properly rejected. (due to quic-go constraint version being updated I suppose?)
But unfortunately, the payload does not pass through. So the second assertion still fails.

It never fails when a request contains a precise Content-Length like so:

```python
r = niquests.post("https://httpbin.local/post", data=b"foo" * 254, verify=False)
```

### What version of Traefik are you using?

With v2.10.4: KO (But OK with illegal Content-Length: -1)
With v2.10.5: KO (Also KO with illegal Content-Length: -1)

### What is your environment & configuration?

```yaml
services:

  proxy:
    image: traefik:v2.10.4
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "traefik" ,"healthcheck", "--ping" ]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
        mode: host
      - target: 4443
        published: 4443
        protocol: tcp
        mode: host
      - target: 4443
        published: 4443
        protocol: udp
        mode: host
      - target: 9999
        published: 9999
        protocol: tcp
        mode: host
      - target: 8754
        published: 8754
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/certs
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # TLS providers
      - --providers.file.directory=/certs/
      # Auto discovery
      - --providers.file.watch=true
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Create an entrypoint "http" listening on port 8080
      - --entrypoints.http.address=:8888
      # Create an entrypoint "https" listening on port 4443
      - --entrypoints.https.address=:4443
      # Create alt-no-quic entrypoints
      - --entrypoints.alt-http.address=:9999
      - --entrypoints.alt-https.address=:8754
      # QUIC Related Configuration
      - --experimental.http3=true
      - --entrypoints.https.http3=true
      - --entrypoints.alt-https.http3=false
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      - --log.level=DEBUG
      # Disable the Dashboard and API
      - --api.dashboard=false
      # Enable healthcheck
      - --ping

  httpbin:
    image: mccutchen/go-httpbin:v2.11.1
    restart: unless-stopped
    depends_on:
      proxy:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.httpbin-http.rule=Host(`httpbin.local`) || Host(`alt.httpbin.local`)
      - traefik.http.routers.httpbin-http.entrypoints=http,alt-http
      - traefik.http.routers.httpbin-https.rule=Host(`httpbin.local`) || Host(`alt.httpbin.local`)
      - traefik.http.routers.httpbin-https.entrypoints=https,alt-https
      - traefik.http.routers.httpbin-https.tls=true
      - traefik.http.services.httpbin.loadbalancer.server.port=8080
```

```
mkdir ./certs
pip install trustme
python -m trustme -i httpbin.local alt.httpbin.local -d ./certs
mv ./certs/server.pem ./certs/httpbin.local.pem
mv ./certs/server.key ./certs/httpbin.local.key
mv ./certs/client.pem ./rootCA.pem
echo "127.0.0.1   httpbin.local alt.httpbin.local" | sudo tee -a /etc/hosts
```

**our certificates.toml** in ./certs

```toml
[[tls.certificates]]
  certFile = "/certs/httpbin.local.pem"
  keyFile = "/certs/httpbin.local.key"
```

### If applicable, please paste the log output in DEBUG level

Unfortunately nothing.
