### ISSUE TITLE
ClientIP does not properly match IPv6 anyaddr?

### ISSUE THREAD

**Issue by jbalonso** [traefik/traefik#10190]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I attempted to use `IngressRoute` and `IngressRouteTCP` to proxy `gitea` and `gitbucket` HTTPS and SSH to the same FQDN, using a dedicated `traefik` instance with its own dual-stack LoadBalancer. After confirming that HTTPS traffic routes correctly, I attempted to use the SSH endpoint.

### What did you see instead?

SSH connections worked over IPv4 but not over IPv6. In fact, IPv6 connections to the SSH port failed with an HTTP error. (I'm led to believe that this might be related to behaviors described in #9756, but this does not seem correct.

Moreover, switching from a `ClientIP` rule in the `IngressRouteTCP` to a `HostSNI` (which... didn't seem appropriate for SSH traffic), works around the issue.

### What version of Traefik are you using?

```
Version:      2.10.4
Codename:     saintmarcelin
Go version:   go1.20.6
Built:        2023-07-24T16:29:02Z
OS/Arch:      linux/arm64
```

### What is your environment & configuration?

I'm sanitizing hostnames.

```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-frontend
  namespace: gitea
  annotations:
    kubernetes.io/ingress.class: traefik-gitea
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gitea.srv.example.com`)
      services:
      - kind: Service
        name: gitea-http
        namespace: gitea
        passHostHeader: true
        port: 3000
  tls:
    secretName: gitea-cert
    domains:
      - main: gitea.srv.example.com
        sans:
        - gitea.vm.example.com
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingressroute-ssh
  namespace: gitea
  annotations:
    kubernetes.io/ingress.class: traefik-gitea
spec:
  entryPoints:
    - ssh
  routes:
    - match: ClientIP(`0.0.0.0/0`, `::`)
      services:
      - name: gitea-ssh
        namespace: gitea
        port: 22
```

Note: if I use the following instead in the `IngressRouteTCP`, I get desired results over both IPv4 and IPv6:
```yaml
  routes:
    - match: HostSNI(`*`)
      services:
      - name: gitea-ssh
        namespace: gitea
        port: 22
```

I installed `traefik` using the following FluxCD HelmRelease configuration (which resolved to traefik helm chart 24.0.0).

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: gitea
spec:
  chart:
    spec:
      chart: traefik
      version: "24.x.x"
      sourceRef:
        name: traefik
        kind: HelmRepository
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  interval: 10m
  releaseName: traefik-gitea
  targetNamespace: gitea
  values:
    ports:
      ssh:
        port: 2222
        expose: true
        exposedPort: 22
        protocol: TCP
    ingressRoute:
      dashboard:
        annotations:
          kubernetes.io/ingress.class: traefik-internal

    providers:
      kubernetesCRD:
        ingressClass: traefik-gitea
        namespaces:
        - gitea
      kubernetesIngress:
        ingressClass: traefik-gitea
        ingressEndpoint:
          publishedService: gitea/traefik
        namespaces:
        - gitea

    nodeSelector:
      example.com/bgp-peer: "true"

    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: gitea.srv.example.com
      spec:
        loadBalancerClass: io.cilium/bgp-control-plane
        externalTrafficPolicy: Local
        ipFamilyPolicy: PreferDualStack
        ipFamilies:
        - IPv4
        - IPv6

    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "250m"
```
