### ISSUE TITLE
AWS_REGION is no longer optional

### ISSUE THREAD

**Issue by hpwjnijs** [traefik/traefik#10195]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We updated to Traefik  2.10.5 . 
Renewal of certificates was not possible anymore automatically.

### What did you see instead?

```
linnaeus_ng-traefik-1       | time="2023-10-25T11:39:42Z" level=error msg="Unable to obtain ACME certificate for domains \"bseai.dryrun.link,malesianbutterflies.dryrun.link\": unable to generate a certificate for the domains [bseai.dryrun.link malesianbutterflies.dryrun.link]: error: one or more domains had a problem:\n[bseai.dryrun.link] [bseai.dryrun.link] acme: error presenting token: route53: failed to determine hosted zone ID: operation error Route 53: ListHostedZonesByName, failed to resolve service endpoint, an AWS region is required, but was not found\n[malesianbutterflies.dryrun.link] [malesianbutterflies.dryrun.link] acme: error presenting token: route53: failed to determine hosted zone ID: operation error Route 53: ListHostedZonesByName, failed to resolve service endpoint, an AWS region is required, but was not found\n" rule="Method(`GET`, `POST`) && Host(`bseai.dryrun.link`,`malesianbutterflies.dryrun.link`) && PathPrefix(`/`)" routerName=bare@docker providerName=route53.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"
```
When adding the environment variable AWS_REGION, it worked again.

### What version of Traefik are you using?

/etc # traefik version
Version:      2.10.5
Codename:     saintmarcelin
Go version:   go1.21.3
Built:        2023-10-11T13:54:02Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
  traefik:
    image: registry.gitlab.com/naturalis/bii/linnaeus/linnaeus_ng/traefik:${IMAGE_VERSION:?}
    restart: always
    command:
      - --global.sendAnonymousUsage=false
      - --providers.docker.exposedByDefault=false
      - --providers.docker.endpoint=tcp://docker-proxy:2375
      - --providers.docker.network=docker-proxy
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.route53.acme.dnschallenge=true
      - --certificatesresolvers.route53.acme.dnschallenge.provider=route53
      - --certificatesresolvers.route53.acme.storage=/letsencrypt/route53.json
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:?Variable AWS_ACCESS_KEY_ID is empty}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:?Variable AWS_SECRET_ACCESS_KEY is empty}
```

**Comment by ldez** [comment]
`AWS_REGION` is an internal env var of the SDK.
The region is required but not the env var.
From my memories, the region was already a requirement with SDKv1.

The region can be provided in several ways, I don't know the exhaustivity of these ways, but I know that some files are read to get this information.

**Comment by triplepoint** [comment]
Note that providing the AWS_REGION env var (which wasn't necessary before) just got me past that error - the next problem seems to still be AWS authentication related:

**Comment by triplepoint** [comment]
Confirmed that rolling back to [traefik 2.10.4](https://github.com/traefik/traefik/releases/tag/v2.10.4) unblocked this problem and allowed my credentials to update.  I'd consider this a pretty significant change in behavior, for a .1 bugfix increment.

**Comment by ldez** [comment]
Can you try to set `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`?

**Comment by meonkeys** [comment]
> Can you try to set `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`?

This worked for me.

**Comment by hpwjnijs** [comment]
> Can you try to set `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`?
We already (always) did that, before and after the issue. So no solution for us.

**Comment by hpwjnijs** [comment]
Dockerfile:
```
ARG TRAEFIK_VERSION=2.10
FROM traefik:${TRAEFIK_VERSION}
#10233 ENV AWS_REGION="eu-central-1"
# hadolint ignore=DL3017
RUN apk update && apk upgrade --no-cache
```
`docker buildx build -t traefik:testAWSREGION .`
```
---
version: '3.8'

services:
  traefik:
    image: traefik:testAWSREGION
    container_name: "traefik"
    restart: ${CONTAINER_RESTART:-unless-stopped}
    networks:
      - web
      - docker-socket-proxy
    depends_on:
      - whoami
    ports:
      - "${HOST_IP:-0.0.0.0}:80:80"
      - "${HOST_IP:-0.0.0.0}:443:443"
      - "127.0.0.1:${TRAEFIK_API_PORT:-8079}:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
    command:
      - "--global.sendAnonymousUsage=false"
      - "--log.level=${TRAEFIK_LOG_LEVEL:-ERROR}"
      - "--api=true"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.route53.acme.dnschallenge=true"
      - "--certificatesresolvers.route53.acme.dnschallenge.provider=route53"
      - "--certificatesresolvers.route53.acme.storage=/letsencrypt/route53.json"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=tcp://docker-socket-proxy:2375"
      - "--providers.docker.network=docker-socket-proxy"
      - "--providers.docker.exposedbydefault=false"
    env_file:
      - .env

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:${DOCKERPROXY_VERSION:-latest}
    container_name: "docker-socket-proxy"
    restart: unless-stopped
    networks:
      - docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro,delegated
    environment:
      CONTAINERS: 1

  whoami:
    image: traefik/whoami  
    ports: 
      - 2001:2001
    networks:
      -  web
    command:
       # It tells whoami to start listening on 2001 instead of 80
       - --port=2001
       - --name=iamfoo
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.homepage.loadbalancer.server.port=2001"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.rule=Host(`whoami.dryrun.link`)"
      - "traefik.http.routers.homepage.tls.certresolver=route53"
networks:
  web:
    name: web
    internal: false
  default:
    internal: false
  docker-socket-proxy:
    internal: true
```
In the .env I provide the credentials for AWS/ROUTE53 domain dryrun.link
I get 
```bash
root@dev-huub2:/opt/compose/test/compose# docker compose logs -f traefik
traefik  | time="2023-12-04T14:19:14Z" level=info msg="Configuration loaded from flags."
traefik  | time="2023-12-04T14:19:18Z" level=error msg="Unable to obtain ACME certificate for domains \"whoami.dryrun.link\": unable to generate a certificate for the domains [whoami.dryrun.link]: error: one or more domains had a problem:\n[whoami.dryrun.link] [whoami.dryrun.link] acme: error presenting token: route53: failed to determine hosted zone ID: operation error Route 53: ListHostedZonesByName, failed to resolve service endpoint, an AWS region is required, but was not found\n" routerName=homepage@docker rule="Host(`whoami.dryrun.link`)" providerName=route53.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"
```
If I uncomment the `ENV AWS_REGION="eu-central-1"` , I get a certificate.

Thanks in advance for your time
