### ISSUE TITLE
MiddlewareTCP ipwhitelist weird working for custom entrypoint

### ISSUE THREAD

**Issue by tkatrichenko** [traefik/traefik#10194]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

EKS v1.25, Traefik v2.9.10

Created custom entrypoint for some TCP service which does not have TLS
Created IngressrouteTCP and MiddlewareTCP with ipWhiteList, but looks like the application is accessible from any IP

### What did you see instead?

* the application is accessible from any IP *if* I include in-cluster IPs
```
    sourceRange:
      # In-cluster IPs 
      - 10.0.0.0/22 
      - 10.0.4.0/22
      - ip1
      - ip2
```
I tried with nc and some binary output was there, meaning the answer from service. Works from IP from the list and not from the list
```
nc -v tcp-service.domain.com 26656
Connection to tcp-service.domain.com port 26656 [tcp/*] succeeded!
"
 ���
    �Kq�PD7?d�|8����=>�5!E8)
```

* the application is not accessible from any IP *if* I comment in-cluster IPs
```
    sourceRange:
      # In-cluster IPs 
      # - 10.0.0.0/22 
      # - 10.0.4.0/22
      - ip1
      - ip2
```
nc shows the following without binary output, which means it is connected to the node port, but no answer from the application. The answer is the same if use IP from the list and not from it
```
nc -v tcp-service.domain.com 26656
Connection to tcp-service.domain.com port 26656 [tcp/*] succeeded!

```

### What version of Traefik are you using?

Traefik v2.9.10

### What is your environment & configuration?

My Ingressroute and middleware
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: tcp-service
spec:
  entryPoints:
  - tcp-test
  routes:
  - match: HostSNI(`*`) # For TCP without TLS you must use HostSNI(`*`)
    services:
    - name: tcp-p2p
      port: 26656
    middlewares:
      - name: ip-whitelist
  # don't need TLS here
  # tls:
  #   passthrough: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: MiddlewareTCP
metadata:
  name: ip-whitelist
spec:
  ipWhiteList:
    sourceRange:
      # In-cluster IPs 
      - 10.0.0.0/22 
      - 10.0.4.0/22
      - ip1 
      - ip2
```

My configuration for custom entrypoint (in helm chart values)
```yaml
additionalArguments:
- --entryPoints.tcp-test.address=:26656/tcp

ports:
  cometbft-test:
    expose: true
    port: 26656
    exposedPort: 26656
    protocol: TCP
     ]
```

### If applicable, please paste the log output in DEBUG level

If in-ckuster IPs in the list traefik just allows connections from any internal IP, but no external ones are logged
```
{"entryPointName":"tcp-test","level":"debug","msg":"Creating TCP server 0 at 10.0.1.86:26656","routerName":"service-tcp-673acf455cb2dab0b43a@kubernetescrd","serverName":0,"serviceName":"service-tcp-673acf455cb2dab0b43a","time":"2023-10-25T14:52:39Z"}
{"entryPointName":"tcp-test","level":"debug","middlewareName":"service-ip-whitelist@kubernetescrd","middlewareType":"IPWhiteListerTCP","msg":"Creating middleware","routerName":"service-tcp-673acf455cb2dab0b43a@kubernetescrd","time":"2023-10-25T14:52:39Z"}
{"entryPointName":"tcp-test","level":"debug","middlewareName":"service-ip-whitelist@kubernetescrd","middlewareType":"IPWhiteListerTCP","msg":"Setting up IPWhiteLister with sourceRange: [10.0.0.0/22 10.0.4.0/22 ip1 ip2]","routerName":"service-tcp-673acf455cb2dab0b43a@kubernetescrd","time":"2023-10-25T14:52:39Z"}
{"entryPointName":"tcp-test","level":"debug","msg":"Adding route for \"HostSNI(`*`)\"","routerName":"service-tcp-673acf455cb2dab0b43a@kubernetescrd","time":"2023-10-25T14:52:39Z"}
{"level":"debug","middlewareName":"service-ip-whitelist@kubernetescrd","middlewareType":"IPWhiteListerTCP","msg":"Connection from 10.0.0.117:61835 accepted","time":"2023-10-25T14:52:39Z"}
{"level":"debug","middlewareName":"service-ip-whitelist@kubernetescrd","middlewareType":"IPWhiteListerTCP","msg":"Connection from 10.0.1.38:30462 accepted","time":"2023-10-25T14:52:39Z"}
```

If in-cluster IPs commented, traefik rejects all connections regrdless from which IP
```
{"entryPointName":"tcp-test","level":"debug","msg":"Creating TCP server 0 at 10.0.2.24:26656","routerName":"service-tcp-673acf455cb2dab0b43a@kubernetescrd","serverName":0,"serviceName":"service-tcp-673acf455cb2dab0b43a","time":"2023-10-25T15:07:14Z"}
{"entryPointName":"tcp-test","level":"debug","middlewareName":"service-ip-whitelist@kubernetescrd","middlewareType":"IPWhiteListerTCP","msg":"Creating middleware","routerName":"service-tcp-673acf455cb2dab0b43a@kubernetescrd","time":"2023-10-25T15:07:14Z"}
{"entryPointName":"tcp-test","level":"debug","middlewareName":"service-ip-whitelist@kubernetescrd","middlewareType":"IPWhiteListerTCP","msg":"Setting up IPWhiteLister with sourceRange: [ip1 ip2]","routerName":"service-tcp-673acf455cb2dab0b43a@kubernetescrd","time":"2023-10-25T15:07:14Z"}
{"entryPointName":"tcp-test","level":"debug","msg":"Adding route for \"HostSNI(`*`)\"","routerName":"service-tcp-673acf455cb2dab0b43a@kubernetescrd","time":"2023-10-25T15:07:14Z"}
{"level":"error","middlewareName":"service-ip-whitelist@kubernetescrd","middlewareType":"IPWhiteListerTCP","msg":"Connection from 10.0.1.157:51480 rejected: \"10.0.1.157:51480\" matched none of the trusted IPs","time":"2023-10-25T15:07:45Z"}
{"level":"error","middlewareName":"service-ip-whitelist@kubernetescrd","middlewareType":"IPWhiteListerTCP","msg":"Connection from 10.0.2.3:27968 rejected: \"10.0.2.3:27968\" matched none of the trusted IPs","time":"2023-10-25T15:07:46Z"}
```

**Comment by rtribotte** [comment]
Hello @tkatrichenko,

Thanks for reporting this and your interest in Traefik!

If you are using a load-balancer in front of the Traefik service, which seems to be the case, then Traefik is always reached by the load-balancer IP.
To be able to filter connections on the client IP, one should use [proxy-protocol] (https://doc.traefik.io/traefik/routing/entrypoints/#proxyprotocol) configuration.
For the AWS side, here is some [documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#proxy-protocol).

**Comment by tkatrichenko** [comment]
Hello @rtribotte , thanks for the answer.

Yes, AWS Classic LB is in front of Traefik having `cidr_blocks = ["0.0.0.0/0"]` in its SG for this port.
I also annotating traefik service with 
```yaml
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
```

When I add the following to traefik helm values
```yaml
    forwardedHeaders:
     trustedIPs: [
       ip1,
       ip2
      # In-cluster IPs 
      10.0.0.0/22 
      10.0.4.0/22
     ]
    # Enable the Proxy Protocol header parsing for the entry point
    proxyProtocol:
     trustedIPs: [
       ip1,
       ip2
      # In-cluster IPs 
      10.0.0.0/22 
      10.0.4.0/22
    ]
```
And not touching middlewareTCP created earlier. Then scenario 2 happens, no traffik goes to the service from any IP. 
But no logs with `rejected` status...
