### ISSUE TITLE
Traefik fails to handle connection closure from pgbouncer

### ISSUE THREAD

**Issue by randrusiak** [traefik/traefik#10201]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I tried logging into the database using psql with the command `psql -h test-pgbouncer.example.com -p 5432 -U test -d test`, but I used the wrong password on purpose. In our setup, we use Traefik with IngressRouteTCP to route traffic to different PgBouncer instances based on SNI. 

EXPECTED OUTCOME
```
psql: error: connection to server at "test-pgbouncer.example.com" (x.x.x.x), port 5432 failed: FATAL:  password authentication failed
connection to server at "test-pgbouncer.example.com" (x.x.x.x), port 5432 failed: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

### What did you see instead?

Instead of getting an error message about the wrong password, the psql command just hung and didn't give any feedback. It seems there's an issue with how our setup, particularly Traefik, responds to failed login attempts in PgBouncer.

psql hangs
```
psql -h test-pgbouncer.example.com -p 5432 -U test -d test
Password for user test: 
```

### What version of Traefik are you using?

Version:      3.0.0-beta4
Codename:     beaufort
Go version:   go1.21.3
Built:        2023-10-12T07:53:33Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: test-pgbouncer
spec:
  entryPoints:
    - pgbouncers
  routes:
    - match: HostSNI(`test-pgbouncer.example.com`)
      priority: 10
      services:
        - name: test-pgbouncer
          port: 5432
          weight: 10
  tls:
    passthrough: true

```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

PGbouncer log:

```
2023-10-27 14:48:13.755 UTC [1] LOG C-0x563865cf9320: test/test@10.0.1.157:50292 closing because: password authentication failed (age=0s)
2023-10-27 14:48:13.755 UTC [1] WARNING C-0x563865cf9320: test/test @10.0.1.157:50292 pooler error: password authentication failed
```

traefik log:
```
2023-10-27T14:47:13Z DBG github.com/traefik/traefik/v3/pkg/tcp/proxy.go:41 > Handling TCP connection address=10.0.0.146:5432 remoteAddr=10.0.1.156:23419
2023-10-27T14:47:13Z DBG github.com/traefik/traefik/v3/pkg/tcp/proxy.go:104 > Error while terminating TCP connection error="close tcp 10.0.1.157:5432->10.0.1.156:23419: use of closed network connection"
2023-10-27T14:47:55Z DBG github.com/traefik/traefik/v3/pkg/provider/kubernetes/crd/kubernetes.go:176 > Skipping Kubernetes event kind *v1.Endpoints providerName=kubernetescrd
2023-10-27T14:48:11Z DBG github.com/traefik/traefik/v3/pkg/tcp/proxy.go:41 > Handling TCP connection address=10.0.0.146:5432 remoteAddr=10.0.2.253:9461
2023-10-27T14:48:13Z DBG github.com/traefik/traefik/v3/pkg/tcp/proxy.go:41 > Handling TCP connection address=10.0.0.146:5432 remoteAddr=10.0.1.174:34591
2023-10-27T14:48:13Z DBG github.com/traefik/traefik/v3/pkg/tcp/proxy.go:104 > Error while terminating TCP connection error="close tcp 10.0.1.157:50292->10.0.0.146:5432: use of closed network connection"
```

**Comment by nmengin** [comment]
Hey @randrusiak,

Thanks for reaching out.

Could you provide a minimal reproducible case (for instance, full Kubernetes manifest to reproduce the issue)?
In the remaining time, if any community member can help us find verified steps to reproduce, we would love the help.

**Comment by randrusiak** [comment]
Yes, sure. Here are steps to reproduce this issue:

1. Install traefik `helm install test-traefik traefik/traefik --values traefik-values.yaml `

traefik-values.yaml:
```yaml
image:
  tag: v3.0.0-beta4
ingressClass:
  enabled: false
  isDefaultClass: false
service:
  enabled: true
  type: ClusterIP
ports:
  web:
    expose: false
  websecure:
    expose: false
  pgbouncer:
    asDefault: true
    port: 5432
    expose: true
    exposedPort: 5432
    protocol: TCP
globalArguments: []
providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: false
ingressRoute:
  dashboard:
    enabled: true
```

2. Generate self-signed certs
```bash 
openssl req -x509 -newkey rsa:4096 -keyout tls1.key -out tls1.crt -days 365 -nodes -subj "/CN=pgbouncer1.example.com"
openssl req -x509 -newkey rsa:4096 -keyout tls2.key -out tls2.crt -days 365 -nodes -subj "/CN=pgbouncer2.example.com"
```

3. 
```bash
kubectl create secret tls pgbouncer-1-self-signed-tls --key tls1.key --cert tls1.crt
kubectl create secret tls pgbouncer-2-self-signed-tls --key tls2.key --cert tls2.crt
```
4. `kubectl apply -f`
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-traffic
spec:
  podSelector: {}
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress

## PG 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer-1
  labels:
    app: pgbouncer-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer-1
  template:
    metadata:
      labels:
        app: pgbouncer-1
    spec:
      containers:
      - name: postgres
        image: bitnami/postgresql:13.12.0
        env:
          - name: POSTGRESQL_PASSWORD
            value: "password123" 
          - name: POSTGRESQL_USERNAME
            value: "test" 
          - name: POSTGRESQL_DATABASE
            value: "test"
          - name: POSTGRESQL_PORT_NUMBER
            value: "5433"
        resources:
          requests: null
          limits: null
        ports:
          - containerPort: 5433
      - name: pgbouncer
        image: bitnami/pgbouncer:1.19.1
        resources:
          requests: null
          limits: null
        ports:
          - name: pgbouncer
            containerPort: 5432
            protocol: TCP
        env:
          - name: PGBOUNCER_PORT
            value: "5432"
          - name: PGBOUNCER_INIT_SLEEP_TIME
            value: "1"
          - name: PGBOUNCER_POOL_MODE
            value: statement
          - name: PGBOUNCER_AUTH_TYPE
            value: md5
          - name: PGBOUNCER_DATABASE
            value: test
          - name: POSTGRESQL_USERNAME
            value: "test"
          - name: POSTGRESQL_PASSWORD
            value: "password123"
          - name: POSTGRESQL_HOST
            value: localhost
          - name: POSTGRESQL_PORT
            value: "5433"
          - name: "PGBOUNCER_SERVER_TLS_SSLMODE"
            value: "disable"
          - name: PGBOUNCER_CLIENT_TLS_SSLMODE
            value: "require"
          - name: PGBOUNCER_CLIENT_TLS_CERT_FILE
            value: /certs/tls.crt
          - name: PGBOUNCER_CLIENT_TLS_KEY_FILE
            value: /certs/tls.key
        volumeMounts:
            - mountPath: /certs
              name: tls-certs
      volumes:
        - name: tls-certs
          secret:
            secretName: pgbouncer-1-self-signed-tls
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer1-service
  labels:
    app: pgbouncer-1
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: pgbouncer
      protocol: TCP
      name: pgbouncer
  selector:
    app: pgbouncer-1

---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: pgbouncer-1
spec:
  entryPoints:
    - pgbouncer
  routes:
  - match: "HostSNI(`pgbouncer1.example.com`)"
    priority: 10
    services:
    - name: pgbouncer1-service
      port: 5432
      weight: 10
  tls:
    passthrough: true

# PG2 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer-2
  labels:
    app: pgbouncer-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer-2
  template:
    metadata:
      labels:
        app: pgbouncer-2
    spec:
      containers:
      - name: postgres
        image: bitnami/postgresql:13.12.0
        env:
          - name: POSTGRESQL_PASSWORD
            value: "password1234" 
          - name: POSTGRESQL_USERNAME
            value: "test" 
          - name: POSTGRESQL_DATABASE
            value: "test"
          - name: POSTGRESQL_PORT_NUMBER
            value: "5433"
        resources:
          requests: null
          limits: null
        ports:
          - containerPort: 5433
      - name: pgbouncer
        image: bitnami/pgbouncer:1.19.1
        resources:
          requests: null
          limits: null
        ports:
          - name: pgbouncer
            containerPort: 5432
            protocol: TCP
        env:
          - name: PGBOUNCER_PORT
            value: "5432"
          - name: PGBOUNCER_INIT_SLEEP_TIME
            value: "1"
          - name: PGBOUNCER_POOL_MODE
            value: statement
          - name: PGBOUNCER_AUTH_TYPE
            value: md5
          - name: PGBOUNCER_DATABASE
            value: test
          - name: POSTGRESQL_USERNAME
            value: "test"
          - name: POSTGRESQL_PASSWORD
            value: "password1234"
          - name: POSTGRESQL_HOST
            value: localhost
          - name: POSTGRESQL_PORT
            value: "5433"
          - name: "PGBOUNCER_SERVER_TLS_SSLMODE"
            value: "disable"
          - name: PGBOUNCER_CLIENT_TLS_SSLMODE
            value: "require"
          - name: PGBOUNCER_CLIENT_TLS_CERT_FILE
            value: /certs/tls.crt
          - name: PGBOUNCER_CLIENT_TLS_KEY_FILE
            value: /certs/tls.key
        volumeMounts:
            - mountPath: /certs
              name: tls-certs
      volumes:
        - name: tls-certs
          secret:
            secretName: pgbouncer-2-self-signed-tls
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer2-service
  labels:
    app: pgbouncer-2
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: pgbouncer
      protocol: TCP
      name: pgbouncer
  selector:
    app: pgbouncer-2

---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: pgbouncer-2
spec:
  entryPoints:
    - pgbouncer
  routes:
  - match: "HostSNI(`pgbouncer2.example.com`)"
    priority: 10
    services:
    - name: pgbouncer2-service
      port: 5432
      weight: 10
  tls:
    passthrough: true
```
5. Expose traefik locally: `kubectl port-forward svc/test-traefik 5432:5432`
6. Add following entry to /etc/hosts
```
127.0.0.1       localhost pgbouncer1.example.com pgbouncer2.example.com
```
7. Connect to pgbouncers through traefik: `psql -h pgbouncer1.example.com  -U test -d test ` and pass wrong password.

If you pass proper password (password123 for pgbouncer1.example.com and password1234 pgbouncer2.example.com) everything works as expected.
