### ISSUE TITLE
plugin: Unknown plugin type: plugindemo

### ISSUE THREAD

**Issue by ndeitch** [traefik/traefik#10203]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm running k8s cluster using Kind with Traefik.

IngressRoute with [Headers](https://doc.traefik.io/traefik/middlewares/http/headers/) middleware works fine.

The problem is when I try to install [plugindemo](https://plugins.traefik.io/plugins/628c9ee2108ecc83915d7764/demo-plugin) to tests plugins.

### What did you see instead?

It gives the error:

```sh
time="2023-10-30T12:45:03Z" level=error msg="plugin: unknown plugin type: plugindemo" entryPointName=web routerName=dev-whoami-d2bf932cfd8b34ddb34b@kubernetescrd
```

### What version of Traefik are you using?

```sh
helm list
NAME     	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                 	APP VERSION
traefik  	default  	1       	2023-10-31 09:44:23.808919495 -0300 -03	deployed	traefik-25.0.0        	v2.10.5
```

### What is your environment & configuration?

```yaml
# traefik.yaml
providers:
  kubernetesCRD:
    allowCrossNamespace: true

experimental:
  plugins:
    enabled: true
    plugindemo:
      moduleName: "github.com/traefik/plugindemo"
      version: "v0.2.2"
```

```yaml
# middleware.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    name: plugindemo
    namespace: dev
spec:
    plugin:
        plugindemo:
            Headers:
                X-Demo: test
                X-URL: '{{URL}}'
```

```yaml
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: dev
spec:
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: dev
spec:
  selector:
    app: whoami
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: dev
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`whoami.localhost`)
      kind: Rule
      services:
        - name: whoami
          kind: Service
          port: 3000
      middlewares:
        - name: dev-plugindemo@kubernetescrd
          namespace: dev
```
