### ISSUE TITLE
Spelling mistake in docs

### ISSUE THREAD

**Issue by sssash18** [traefik/traefik#10212]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

The docs at [https://doc.traefik.io/traefik/middlewares/http/digestauth/
(https://doc.traefik.io/traefik/middlewares/http/digestauth/ ) says `restricts access to your services to known users.` 

### What did you see instead?

It should instead be `restricts access to your services to unknown users.` 

### What version of Traefik are you using?

Version:      2.10.5

### What is your environment & configuration?

```yaml
Codename:     saintmarcelin
Go version:   go1.21.3
Built:        2023-10-11T13:54:02Z
OS/Arch:      linux/arm64
```
