### ISSUE TITLE
Error message "the router <router name> uses a non-existent resolver: <resolver name>" is unhelpful and not representative of the actual issue

### ISSUE THREAD

**Issue by coaxial** [traefik/traefik#10241]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Basically #7414 which was closed and locked a while back.

The issue is still present, I spent hours trying to figure out what is wrong because my traefik.yml did define the resolver.

In my case, it was a typo, `certificateResolvers` vs `certificatesResolvers` (plural). But for others, it's an existing acme.json file, or a permission issue... 

The point is that this error message is unhelpful and cryptic: in all the cases above, the error message didn't help diagnose the issue other than from searching for it and finding issue #7414.

### What did you see instead?

The very unhelpful and non-descriptive error message `the router <router name> uses a non-existent resolver: <resolver name>`.

### What version of Traefik are you using?

2.10.5

### What is your environment & configuration?

```yaml
global:
  sendAnonymousUsage: false
api:
  # Enable dashboard for administration.
  dashboard: true
entryPoints:
  # https://doc.traefik.io/traefik/routing/entrypoints/#entrypoints
  # Answer requests on ports 80 and 443.
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: he
      middlewares:
        - default@file
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          # Redirect http to https.
          to: "websecure"
          scheme: "https"
serversTransport:
  # https://doc.traefik.io/traefik/routing/overview/#transport-configuration
  # Don't validate certs if the service is using a self signed cert between
  # Traefik and itself. This is fine because it's only traffic on the
  # traefik-net network.
  insecureSkipVerify: true
providers:
  docker:
    # https://doc.traefik.io/traefik/providers/docker/#provider-configuration
    endpoint: "unix:///var/run/docker.sock"
    # Services must be explicitly exposed with `traefik.enable=true` labels.
    exposedByDefault: false
    network: "traefik-net"
    swarmmode: true
    swarmmodeRefreshSeconds: 15
    # Watch Docker events
    watch: true
  file:
    filename: "/etc/traefik/config.yml"
    watch: true
certificatesResolvers: # NOTE this is plural, certificate_s_Resolver_s_
  he:
    acme:
      email: "letsencrypt@64b.it"
      storage: "/etc/traefik/acme/acme.json"
      # Use staging server while tweaking
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: "hurricane"
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

`the router websecure-traefik@docker uses a non-existent resolver: he`
