### ISSUE TITLE
Plugin not working on k0s

### ISSUE THREAD

**Issue by nghiepvo-ohmidasvn** [traefik/traefik#10259]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

- Install k0s
- Install MetalLB 
- Install Traefik via helm with values.yaml file

### What did you see instead?

the plugin not install on  the traefik pod

### What version of Traefik are you using?

v2.10.5

### What is your environment & configuration?

```yaml

experimental:
  # This value is no longer used, set the image.tag to a semver higher than 3.0, e.g. "v3.0.0-beta3"
  # v3:
  # -- Enable traefik version 3
  #  enabled: false
  plugins:
    # -- Enable traefik experimental plugins
    enabled: true
    plugindemo:
      moduleName: "github.com/traefik/plugindemo"
      version: "v0.2.2" 

....

additionalArguments:
#  - "--providers.kubernetesingress.ingressclass=traefik-internal"
  - "--log.level=DEBUG"
  - "--experimental.plugins.plugindemo.modulename=github.com/traefik/plugindemo"
  - "--experimental.plugins.plugindemo.version=v0.2.2"
```

### If applicable, please paste the log output in DEBUG level

```shell
....
time="2023-11-23T03:17:38Z" level=info msg="Help us improve Traefik by leaving this feature on :)"
time="2023-11-23T03:17:38Z" level=info msg="More details on: https://doc.traefik.io/traefik/contributing/data-collection/"
time="2023-11-23T03:17:38Z" level=debug msg="loading of plugin: plugindemo: github.com/traefik/plugindemo@v0.2.2"
time="2023-11-23T03:17:39Z" level=error msg="Plugins are disabled because an error has occurred." error="unable to set up plugins environment: unable to download plugin github.com/traefik/plugindemo: failed to call service: Get \"https://plugins.traefik.io/public/download/github.com/traefik/plugindemo/v0.2.2\": tls: failed to verify certificate: x509: certificate is valid for *.xserver.jp, xserver.jp, not plugins.traefik.io"
time="2023-11-23T03:17:39Z" level=debug msg="Configured Prometheus metrics" metricsProviderName=prometheus
....
```
