### ISSUE TITLE
Traefik sending SYN ACK referring to a previous closed connection after the 60 seconds TCP TIME_WAIT elapsed

### ISSUE THREAD

**Issue by jmgsoares** [traefik/traefik#10250]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hi community, 

We have a kubernetes cluster (1.25) running traefik (v2.9.9) as the ingress controller (3 pods). This is a cluster running on AWS EKS and using VPC IPs for pods, and worker nodes are AMD backed instances (specifically m6a.4xlarge). All the traffic reaches traefik via an AWS network load balancer that is targeting directly traefik pods IPs.

So the complete flow is: Client -> (TLS terminations with AWS public cert) NLB (Re-Encrypt) -> (TLS termination with self-signed PKI) traefik -> backend services

The Investigation:

When sending requests to the cluster (from the outside) at a rate of around 60 to 70rps it became noticeable that some requests were taking over 1s.

Some initial checks on the backend service running inside the k8s cluster showed that no request has took more than 200ms to process and we also crosscheck this finding with traefik generated metrics about the entrypoint. So with this information we started to look to what could be happening upstream.

Looking at the NLB access logs it was visible that some requests were in fact taking over 1s (connection_time field of the NLB access logs), this prompted us to look for the issue downstream.

After looking deeper at traefik it self, we found no apparent issues visible on the logs and the pods are not even close to limits in regards to cpu or memory, also looking at the cfs container throttled metric we have a flat 0 at all times. Thus we assume that under these conditions traefik should be able to cope with such loads without even breaking a sweat.

With all this info we did some packet captures on the traefik pods virtual interfaces and found a rather unusual behavior.

As per TCP design, after a connection is finished, the quadruple [src_ip; src_port; dst_ip; dst_port] is put in the TIME_WAIT state for 60 seconds.

When the NLB starts a new connection (by sending a SYN packet) it will choose a port from ephemeral port range and at times it will choose a previously used port and on top of this, sometimes this happens 60.2 seconds after the previous connection that used the same quadruple was closed (in order words, 200ms after the 60 seconds TIME_WAIT).

### What did you expected?

Since at this point more than 60 seconds have elapsed from the previous connection close using the same quadruple combination I would expect traefik to send back an SYN ACK and normally carry on with the new connection.

### What did you see instead?

Looking at the packet capture below:
Additional context:
NLB IP: 10.152.165.59
POD IP: 10.152.169.54

<img width="1577" alt="Screenshot 2023-11-18 at 03 28 04" src="https://github.com/traefik/traefik/assets/36493199/a32fe3b8-f1a8-46d3-b538-06be36aaed22">

We've seen that there seems to be some kind of delay on traefik end when clearing out expired entries and if the same quadruple combination is used (in other words, if the NLB chooses a port that was used by a closed connection around 60.2 seconds prior), traefik it will send back a SYN ACK referring to the previous connection and not the new one, as if the connection is still in the TIME_WAIT period but in fact the 60 seconds have already elapsed.

When the NLB receives this SYN ACK, since it doesn't know the connection the SYN ACK was referring to it will send a RST packet to clear it up, wait around 1 second, and then send the SYN over again. From there on it is business as usual and traefik handles the connection as expected.

After this we went into the traefik pod and started to look ant the actual entries and we found that sometimes (looks to be non-deterministic behavior) entries will linger around for 1 to 2 seconds even after the 60 second TIME_WAIT has gone by. In the image below there is such an example of this:

We can see the highlighted connections are in state 03 (TIME_WAIT) and on the first cat they both had around 1.2 seconds. (one connection had 1.17 seconds left and the other 0.8)

The second cat command was issued around 1 second later and both entries are still present but showing 0 on the time left.

The third cat command was issuer around 2 seconds later and both entries were still present even tho they should have already been cleaned out

![image](https://github.com/traefik/traefik/assets/36493199/854c3102-4610-44b5-bc21-8be9a3e715de)

Now, I'm not entirely sure that the update to /proc/net/tcp6 is done in a timely fashion but having these connections linger around and with what we can in fact see on the packet capture leads me to believe that there is some issue with the clean up of expired entries, and since sometimes the load balancer will reuse a port around 100 ~ 200 milliseconds after the 60 second TIME_WAIT expires this fits the pattern observed. 

### What did you though or try so far:

We've added replicas to traefik and also have the cross-zone load balancing enabled, thus creating more possible combinations for quadruples and so reduce the likelihood of a reuse but it is only a temporary fix and it is not guaranteed that this cannot happen, in fact we can still spot it happening, although less frequently, and is somewhat of a resource waste in some way.

Another test we've done was disabling access logs in an attempt to reduce load but that did not yield any positive results.

We thought about the possibility of reducing the TIME_WAIT to 55 seconds or so, but this is not possible.

I've thought about if the underlying EC2 instance being AMD could have some issue (as they tend to have lower clock speeds) but considering the fact that there is no CPU contention on the nodes where these pods are I find it a far fetched possibility.

I'm also considering the fact that we have the /ping set on the same port where traffic comes in that this does some unnecessary use of ports, but when looking and the total load of traefik we never get past 110rps and I reckon that traefik should be more than capable to handle these loads and even much bigger ones. 

### What version of Traefik are you using?

v2.9.9

### What is your environment & configuration?

```yaml
Kind: Pod
...
  spec:
    serviceAccountName: traefik
    hostNetwork: false
    containers:
    - image: docker.io/traefik:v2.9.9
      imagePullPolicy: IfNotPresent
      name: traefik
      resources:
        limits:
          cpu: 2000m
          memory: 4096Mi
        requests:
          cpu: 2000m
          memory: 2048Mi
      readinessProbe:
        httpGet:
          path: /ping
          port: 8443
          scheme: HTTPS
        failureThreshold: 2
        initialDelaySeconds: 5
        periodSeconds: 3
        successThreshold: 1
        timeoutSeconds: 1
      livenessProbe:
        httpGet:
          path: /ping
          port: 8443
          scheme: HTTPS
        failureThreshold: 3
        initialDelaySeconds: 15
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 2
      ports:
      - name: websecure
        containerPort: 8443
        protocol: TCP
      securityContext:
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
      args:
      - --entrypoints.websecure.address=:8443/tcp
      - --ping=true
      - --metrics.prometheus=true
      - --metrics.prometheus.entrypoint=metrics
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addServicesLabels=true
      - --metrics.prometheus.buckets=0.1,0.3,0.5,1.0
      - --providers.kubernetescrd
      - --providers.kubernetescrd.allowCrossNamespace=true
      - --providers.kubernetesingress
      - --providers.kubernetesingress.ingressClass=traefik
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.forwardedHeaders.insecure
      - --log.format=json
      - --log.level=INFO
      - --accesslog=true
      - --accesslog.format=json
      - --accesslog.bufferingsize=150
      - --accesslog.fields.defaultmode=keep
      - --accesslog.fields.headers.defaultmode=drop
      - --accesslog.fields.headers.names.X-Amzn-Trace-Id=keep
      - --accesslog.fields.headers.names.X-Forwarded-For=keep
      - --accesslog.fields.headers.names.X-Forwarded-Port=keep
      - --accesslog.fields.headers.names.X-Forwarded-Proto=keep
      - --accesslog.fields.headers.names.X-Request-ID=keep
      - --ping.entryPoint=websecure
```

EKS 1.25
Worker nodes running amazon linux 2, 5.10.192-183.736.amzn2.x86_64, Instance type m6a.4xlarge
