### ISSUE TITLE
`traefik.http.routers.<service>.tld.certresolver` is ignored when there is already a valid certificate from another resolver

### ISSUE THREAD

**Issue by coaxial** [traefik/traefik#10254]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Consider this `traefik.yml`:
```yaml
...
certificatesResolvers:
  staging:
    acme:
      email: fromage@example.org
      storage: "/etc/traefik/certificates/acme-staging.json"
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: "hurricane"
  production:
    acme:
      email: fromage@example.org
      storage: "/etc/traefik/certificates/acme-production.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: "hurricane"
...
```

A container with this label:
```
traefik.http.routers.staging.tls.certresolver: staging
traefik.http.routers.staging.tls.domains[0].sans: "*.example.org"
```
And a second container with this label:
```
traefik.http.routers.prod.tls.certresolver: production
traefik.http.routers.prod.tls.domains[0].sans: "*.example.org"
```

If both `staging` and `production` have a valid cert for `*.example.org`, Traefik will pick whatever certificate to serve with either router; thus ignoring the actual `certresolver` setting.

### What did you see instead?

Traefik serves the `staging` cert for both containers, instead of the matching cert in each resolver.

### What version of Traefik are you using?

2.10.5

### What is your environment & configuration?

```yaml
...
certificatesResolvers:
  staging:
    acme:
      email: fromage@example.org
      storage: "/etc/traefik/certificates/acme-staging.json"
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: "hurricane"
  production:
    acme:
      email: fromage@example.org
      storage: "/etc/traefik/certificates/acme-production.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: "hurricane"
...
```

Add more configuration information here.
