### ISSUE TITLE
WebSockets Support is poorly documented

### ISSUE THREAD

**Issue by fabiorauber** [traefik/traefik#1027]
### What version of Traefik are you using (`traefik version`)?
1.1.2 (camembert)

### What is your environment & configuration (arguments, toml...)?
Simple websocket backend with SSL frontend

### What did you do?
Tried to find out how to configure WS in Traefik. 

### What did you expect to see?
Some document stating how WS support works in Traefik.

### What did you see instead?
Googled and found a Github issue that described no special configuration was needed. Spent many hours trying to figure out that.

**Comment by burdandrei** [comment]
I think the main problem is that most of us are running Traefik behind the ELB =(
ELB HTTP/S Listener doesn't support web sockets. Switching it to TCP Listener makes the magic

**Comment by valentinvieriu** [comment]
I'm fighting with this issues for days. Is it websockets supported by Traefik or not?
No matter what I've tried my connection fails at the handshake level.
```
failed: Error during WebSocket handshake: Unexpected response code: 500
```
Can somebody bring some clarity to this? Can we use Traefik with an http backend and websockets over http in the same time?

Thank you,

**Comment by ldez** [comment]
Websockets and secured Websockets are supported by Traefik.
We need to add some documentation on this part.
Come on Slack (https://traefik.herokuapp.com, https://traefik.slack.com), if you want more help from the community.

**Comment by mstaicu** [comment]
The following that I'm about to write is nothing short of alchemy and pure experimentation

To set the scene up, running a development environment on my local machine with k8s and Traefik v2.6 as the ingress controller, custom resource definitions ( CRDs ) and a bunch of services

Among those services, I am running Remix.run as my client server in development mode. In development mode, Remix.run starts a websockets server that notifies the frontend of any changes made to the file system

The websockets protocol that the frontend uses to connect to the websockets server is dependent on the protocol of the running server, i.e. `https ? wss : ws`, and since I run an `https` connection, it `wss` is chosen, thus the websockets server that it attempts to connect to is `wss://{HOST_DOMAIN}:3001/socket`

Right so, here's what I currently have, in terms of deployment descriptors

Traefik's deployment descriptor:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.6
          args:
            - --api=true
            - --api.dashboard=true

            - --accesslog

            - --entrypoints.http.address=:80
            - --entrypoints.https.address=:443

            - --certificatesresolvers.pebble.acme.email=dimension@outlook.com

            - --certificatesresolvers.pebble.acme.httpchallenge=true

            - --certificatesresolvers.pebble.acme.httpchallenge.entrypoint=http

            # I'm running Pebble inside my cluster to automate the certificate provisioning, development mode only

            - --certificatesresolvers.pebble.acme.caserver=https://pebble:14000/dir

            - --certificatesresolvers.pebble.acme.storage=/acme/acme.json

            - --providers.kubernetescrd
          volumeMounts:
            - name: ingress-storage
              mountPath: /acme
      volumes:
        # This is defined in a different file, it allocates space for my ACME client ( LEGO ) to store certificates
        - name: ingress-storage
          persistentVolumeClaim:
            claimName: ingress-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-lb-srv
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: live-reload
      protocol: TCP
      #
      # Here's the kicker. Since we defined entry points for http ( :80 ) and https ( :443 )
      # we can listen for incoming traffic on port 3001 and forward that to either entrypoint (http or https) by using the targetPort
      #
      # Once it reaches those entry points, the IngressRoute comes into play. More on that below
      #
      port: 3001
      targetPort: 443
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: wss-live-reload
spec:
  entryPoints:
    # Entry point corresponding to port :443
    # Change the `targetPort` of the LoadBalancer's `live-reload` from :443 to :80 and you'll get a simple ws connection, as it will be forwarded to the :80 entry point. You will also have to adjust this IngressRoute to use the `http` entry point and remove the `tls` options
    - https
  routes:
    - match: Host(`${HOST_DOMAIN}`) && PathPrefix(`/socket`)
      kind: Rule
      services:
        - name: client-srv
          port: 3001
  tls:
    certResolver: pebble
    domains:
      - main: potato
```

And my client service deployment file

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      automountServiceAccountToken: false
      containers:
        - name: client
          image: dimensions/client-remix
          envFrom:
            - secretRef:
                name: dotenv
            - name: REMIX_DEV_SERVER_WS_PORT
              value: "3001"    
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: client-live-reload
      protocol: TCP
      port: 3001
      targetPort: 3001
```

If you guys have improvements to this, or any further explanations, please post them, as I think I'm not the only one frustrated with the lack of documentation on WebSockets
