### ISSUE TITLE
[3.0] When any type of "catch all" route exists on tls enabled entrypoint, mtls (TLSOption/clientAuth) becomes unstable to extract certificate

### ISSUE THREAD

**Issue by Owersun** [traefik/traefik#10271]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We are trying k8s deployed traefik 3.0, working through KubernetesCRD with traefik CRD's.
Part of our setup is mtls auth, through TLSOption/cluentAuth + Middleware/pass-x-tls-client-cert-header.
Additionally, we have "catch all" route for tls enabled entrypoint. This route is done as IngressRoute with "match: HostRegexp(`.*`)" or "match: 'PathPrefix(`/`)" (tried both, result is the same) attached to tls enabled entrypoint.
When this "catch all" route is present, any other route (catch all doesn't have mtls) which has mtls auth enabled, becomes unstable, and with some very high probability traefik will fail to extract client certificate from incoming connection, passing proper request, but without any client auth, to the route target.

### What did you see instead?

mtls keep working stable, when some variant of "catch all" exists on tls enabled entrypoint.

Additional Info: Despite any variant of "catch all" on tls throws some kind of warning, this setup work just fine on traefik 2.0, and especially the resulting effect is weird. I understand warnings about that it's not always possible to properly catch all in tls, but making client auth unstable as the result is unexpected.

### What version of Traefik are you using?

"traefik:v3.0" docker image - where issues is present
"traefik:v2.10" docker image where it is working fine

### What is your environment & configuration?

```yaml
    entryPoints:
      http:
        address: ':80'
        proxyProtocol:
          trustedIPs:
            - 10.117.16.0/21
      https:
        address: ':443'
        http:
          tls:
            options: default
        proxyProtocol:
          trustedIPs:
            - 10.117.16.0/21
      traefik:
        address: ':8080'
        proxyProtocol:
          trustedIPs:
            - 10.117.16.0/21
    ping: {}
    log:
      level: INFO
    api:
      dashboard: true
      insecure: true
    # log only 500's and long running requests to debug issues
    accessLog:
      filters:
        statusCodes:
          - "500-510"
        minDuration: "3s"
    providers:
      # process services of kind "Ingress" with "kubernetes.io/ingress.class" annotation set to "traefik"
      kubernetesIngress:
        ingressClass: traefik
      # process native traefik services of kind like "IngressRoute", "Middleware", etc.
      kubernetesCRD:
        # allow traefik IngressRoutes's reference resources in other namespace than theirs
        allowCrossNamespace: true
```

```yaml
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: default
  namespace: traefik
spec:
  minVersion: VersionTLS12
```

mtls option
```yaml
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: mtls
  namespace: traefik
spec:
  minVersion: VersionTLS12
  clientAuth:
    # the CA certificate is extracted from key `tls.ca` of the given secrets.
    secretNames:
      - defaultcertificate
    clientAuthType: VerifyClientCertIfGiven
```

mtls middleware
```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pass-x-tls-client-cert-header
  namespace: traefik
spec:
  passTLSClientCert:
    info:
      subject:
        commonName: true
        serialNumber: true
      issuer:
        organization: true
        commonName: true
        serialNumber: true
```

Catch all route
```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: catch-all
  namespace: legends
spec:
  entryPoints:
    - https
  routes:
    - match: 'PathPrefix(`/`)'
      kind: Rule
      priority: 1
      services:
        - name: catch-all
          port: 8080
  tls: {}
```

example mtls enabled route
```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: metadata
  namespace: legends
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`some...`)
      kind: Rule
      middlewares:
        - name: pass-x-tls-client-cert-header
          namespace: traefik
      services:
        - name: metadata
          port: 80
  tls:
    options:
      name: mtls
      namespace: traefik
    secretName: certificate-k8s-tl
```

### If applicable, please paste the log output in DEBUG level

when cahtch-all route is present, traefik gets elevated level of
2023-11-28T23:42:20Z WRN Tried to extract a certificate on a request without mutual TLS middlewareName=legends-pass-x-tls-client-cert-header@kubernetescrd middlewareType=PassClientTLSCert
messages
