### ISSUE TITLE
Request to API in k8s cluster behind Traefik times out after 30 seconds

### ISSUE THREAD

**Issue by PGimenez** [traefik/traefik#10282]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have an API ([link](https://apps.peregimenez.com/corstest)) to test my Traefik config in my k8s cluster. This API takes a query and sends it back after a delay. This is the command I use to test the API:

    curl -X 'POST' 'https://apps.peregimenez.com/corstest' -H 'accept: application/json' -H 'Content-Type: application/json' -H "Origin: https://peregimenez.com" -d '{ "query": "hello there", "sleep":30 }' -i --max-time 60
    
    

### What did you see instead?

If the delay is under 30 seconds, it works. However, if it is over 30 seconds, I get a `502 Server Error`. The Traefik log shows 

     time="2023-11-30T11:42:54Z" level=debug msg="'499 Client Closed Re │
    │ quest' caused by: context canceled" 

### What version of Traefik are you using?

helm.sh/chart: traefik-26.0.0

### What is your environment & configuration?

I'm running traefik on a GKE cluster. Everything works except for this API call. This is the config file, where I've added every option I could find related to timeouts:

```yaml
ingressClass:
  enabled: true
  isDefaultClass: false

additionalArguments:
  - "--log.level=DEBUG"
  - "--providers.kubernetesingress.ingressclass=traefik"
  - "--ping"
  - "--entryPoints.websecure.transport.respondingTimeouts.readTimeout=300"
  - "--entryPoints.websecure.transport.respondingTimeouts.writeTimeout=300"
  - "--entryPoints.websecure.transport.respondingTimeouts.idleTimeout=300"
  - "--entryPoints.websecure.transport.lifeCycle.graceTimeOut=300"
  - "--entryPoints.web.transport.respondingTimeouts.readTimeout=300"
  - "--entryPoints.web.transport.respondingTimeouts.writeTimeout=300"
  - "--entryPoints.web.transport.respondingTimeouts.idleTimeout=300"
  - "--entryPoints.web.transport.lifeCycle.graceTimeOut=300"
  - "--serversTransport.forwardingTimeouts.responseHeaderTimeout=300"
  - "--serversTransport.forwardingTimeouts.idleConnTimeout=301"

dashboard:
  enabled: true
rbac:
  enabled: true

providers:
  kubernetesCRD:
    enabled: true

ports:
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
    nodePort: 32080

  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP
    nodePort: 32443

service:
  enabled: true
  type: NodePort

requests:
  cpu: "100m"
  memory: "100Mi"
limits:
  cpu: "100m"
  memory: "101Mi"

maxIdleConnsPerHost: -1

```

**Comment by lbenguigui** [comment]
Hello @PGimenez ,

thanks for your interest in Traefik!

After analyzing the issue, we are unable to reproduce the issue.
Traefik logs show the client has canceled the request, meaning timeout is probably not the cause of the problem. Using `--max-time`  curl option can cancel the request, it is probably the reason why you see a 499 in the log.

Can you try again without using `--max-time` ?

**Comment by PGimenez** [comment]
Thanks for your reply @lbenguigui. It turns out it was an issue with GKE. There's a [default timeout of 30](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration#timeout) sec on backend services.

I don't know why, but switching from NodePort to LoadBalancer service fixed the timeout issue. This is what my chart config looks like now:

```yaml
ingressClass:
  enabled: true
  isDefaultClass: false

additionalArguments:
  - "--log.level=DEBUG"
  - "--providers.kubernetesingress.ingressclass=traefik"
  - "--ping"

dashboard:
  enabled: true
rbac:
  enabled: true

providers:
  kubernetesCRD:
    enabled: true

ports:
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP

  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP

service:
  enabled: true

requests:
  cpu: "100m"
  memory: "100Mi"
```
