### ISSUE TITLE
Traefik v3: postgres Cancel Request not handled

### ISSUE THREAD

**Issue by sjmiller609** [traefik/traefik#10280]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

If you start a connection to Postgres, for example with psql, through a Traefik proxy, then you start a transaction, then press control + C to send interrupt to psql, psql will send a Cancel request to the server, and this cancel request is not handled in Traefik

example query:
```
create table users(name text);

DO $$
DECLARE
    -- You can declare any necessary variables here
BEGIN
    LOOP
        -- Insert command goes here
        INSERT INTO users (name) VALUES ('brian');

        -- Pause for 1 second
        PERFORM pg_sleep(1);
    END LOOP;
END$$;
```

### What did you see instead?

The cancel request is initiated, TCP handshake works. Then PGSQL Cancel request is sent. The server ACK, then FIN / ACK. TCP connection closes. I'm not sure how this ought to work in the case of required encrypted connections, routing with SNI.

Here is a filtered down pcap that shows this interaction

[cancel-request-rejected.pcapng.zip](https://github.com/traefik/traefik/files/13550544/cancel-request-rejected.pcapng.zip)

This is what a Cancel request looks like
![image](https://github.com/traefik/traefik/assets/7516283/9c9d71e8-c3a0-49a1-9ce0-af10eafa5db9)

### What version of Traefik are you using?

```
Version:      3.0.0-beta2
Codename:     beaufort
Go version:   go1.19.4
Built:        2022-12-07T16:32:34Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
.... omitted
spec:
  entryPoints:
  - postgresql
  routes:
  - match: HostSNI(`org-tembo-test-inst-steven.data-1.use1.tembo-development.com`)
    services:
    - name: org-tembo-test-inst-steven-rw
      port: 5432
  tls:
    passthrough: true
```
