### ISSUE TITLE
Running microk8s breaks traefik host name resolution 

### ISSUE THREAD

**Issue by sidjakinsboriss** [traefik/traefik#10308]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have traefik running in a docker container, and I use it to access applications that also run in docker containers locally. I use labels in docker-compose for my applications to achieve that:

```yaml
labels:
  - traefik.http.routers.my-app.rule=Host(`my-app.localhost`)
  - traefik.http.routers.my-app_tls.rule=Host(`my-app.localhost`)
  - traefik.http.routers.my-app_tls.tls=true
  - traefik.http.services.my-app.loadbalancer.server.port=80
```

Going to http://my-app.localhost routes me to the necessary application via traefik, as expected. However, when I run `microk8s` on my machine, this doesn't work anymore. Going to the IP address displayed in traefik dashboard for a specific application still works, but accessing it via the Host doesn't. I suspect that `microk8s` edits some configuration crucial for traefik to function correctly. The only way I found to solve the issue is rebooting my machine.  

### What did you see instead?

Going to http://my-app.localhost results in `Error ECONNREFUSED` after I stop `microk8s`

### What version of Traefik are you using?

2.4

### What is your environment & configuration?

docker-compose:
```yaml
version: '3.5'
services:
  proxy:
    restart: always
    image: traefik:2.4
    ports:
      - target: 8080        
        host_ip: 127.0.0.1
        published: 8080
        protocol: tcp
        mode: host
      - target: 80        
        host_ip: 127.0.0.1
        published: 80
        protocol: tcp
        mode: host
      - target: 443       
        host_ip: 127.0.0.1
        published: 443
        protocol: tcp
        mode: host
      - target: 35729      
        host_ip: 127.0.0.1
        published: 35729
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./static.yaml:/etc/traefik/traefik.yaml
      - ./configuration:/configuration
      - ./certs:/certs
    labels:
      - traefik.enable=false
```
static.yaml:
```yaml
providers:
  docker: {}
  file:
    directory: /configuration
    watch: true

## Enable dashboard API through localhost:8080
api:
  insecure: true

## Enable both port 80 (HTTP) and 443 (HTTPS)
entryPoints:
  web-http:
    address: ":80"

  web-https:
    address: ":443"

  reload-http:
    address: ":35729"

accessLog: {}
```

Add more configuration information here.
