### ISSUE TITLE
Rate limiter source extractor header name handling of requests without the header name

### ISSUE THREAD

**Issue by arendhummeling** [traefik/traefik#10307]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I have just successfully implemented the rate limiter middleware for my application and everything is working as it should, which is great, thanks! 

I was left with 1 problem.

Below is an image of my current (debugging) configuration of the rate limiter middleware. 
<img width="438" alt="image" src="https://github.com/traefik/traefik/assets/112398219/e02abc89-77b0-4fe6-9b5f-f2f44084c753">

I've specified the `sourceCriterion` as `requestHeaderName` because the functional requirement of this rate limiting, is to rate limit API keys. All incoming API requests should have the header name present, or they will be served a `401` response.

This is where my problem lies. After some digging through the (Traefik) code (we're currently running on `3.0.0-beta5`), I found that the value returned when a header name is not present is simply an empty string. So all requests without the header are grouped. This is not desired in our case. I had hoped that requests without the specified header name would simply not be rate limited. 

I am wondering what your view on this is. And if you are open to any changes regarding the behaviour of the rate limiter with the `sourceCriterion` being `requestHeaderName` in the case that the header name is empty.

In this case I see 2 options:
1. Disable rate limiting for the mentioned case.
2. Implement an extra option that allows to specify the behaviour in this case (current behaviour or disabled rate limiting).

In case changes are welcomed, I would be happy to take a shot at it and present a PR to accomplish the change. If you have a different suggestion, I would also gladly see it. Thanks!

(And in case it helps, here is my configuration for the middleware)
```yaml
http:
  middlewares:
    rate-limit:
      rateLimit:
        average: {{ env "RATE_LIMIT_AVERAGE" }}  # Allow a maximum x requests / period
        period: {{ env "RATE_LIMIT_PERIOD" }}  # Allow a maximum of average requests / y seconds
        burst: {{ env "RATE_LIMIT_BURST" }}  # Allow a maximum of z requests within an infinitesimally small time-window
        sourceCriterion:
          requestHeaderName: Authentication-Key
```

**Comment by lbenguigui** [comment]
Hello @arendhummeling ,

thank for your interest in Traefik.
If I understood correctly, you aim to return a 401 when the header name is not present (return by your backend I guess).
I can suggest you a workaround. You can define 2 routes like this:

```yaml
http:
  routers:
    RouterWithRatelimit:
      entryPoints:
        - web
      middlewares:
        - rate-limit
      service: myBackend
      rule: Host(`example.com`) && HeaderRegexp(`Api-Key`, `^.+$`)

    RouterWithOutRatelimit:
      entryPoints:
        - web
      service: myBackend
      rule: Host(`example.com`)
```

By using https://doc.traefik.io/traefik/v3.0/routing/routers/#header-and-headerregexp, only request that contains the header is ratelimited.

Still, we are interested in this issue, but we’re unsure about the use case and the traction it will receive. We are going to leave the status as kind/proposal to give the community time to let us know if they would like this idea.

We will reevaluate as people respond.

If you or another community member would like to build it before that happens, let us know, and we will work with you to make sure you have all the information needed.
Let us know here before you start. We prefer to work with our community members at the beginning of the design process to ensure that we are aligned and can move quickly with the review and merge process.
