### ISSUE TITLE
Enhance middleware 'IPAllowList' to redirect to different URL or backend

### ISSUE THREAD

**Issue by peter-englmaier** [traefik/traefik#10305]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

**Motivation:** As a kubernetes devops engineer, I sometimes like to redirect users to a temporary maintenance page while not blocking myself from the application. 

**Proposal:**

The middleware 'IPAllowList' already provides a way to block access from IP addresses not in the provided IP ranges. However, it only blocks access with 403. What I would like to have, is an option to instead provide a 302 redirect to another page, when the IP is not allowed.

The manifest could look like this:

```
apiVersion: traefik.io/v1alpha1
kind: MiddlewareTCP
metadata:
  name: maintenance
spec:
  ipWhiteList:
    sourceRange:
      - 127.0.0.1/32
      - 192.168.1.7
    statusCode: 302
    redirectURL: https://fqdn.com/maintenance.html
```

A helm chart could deploy this middleware with the application. The application would be still available from the listed sourceRange, but users are redirected to the maintenance page. After testing, the maintenance page could be simply removed by deleting the middleware.

This would simplify maintenance for applications which need to be configured or tested after deployment. 

Similarily, other middleware used to block access based on presence of client certificate, or certain cookies or headers, could be useful.

This was originally proposed in https://github.com/traefik/traefik/pull/10249#issuecomment-1855950858
