### ISSUE TITLE
transport.respondingTimeouts.idleTimeout can't be defined as 0

### ISSUE THREAD

**Issue by olwe0002** [traefik/traefik#10314]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

assume this custom values for helm:

```
ports:
  postgresql:
    port: 5432
    expose: true
    exposedPort: 5432
    protocol: TCP

additionalArguments:
  - --entryPoints.postgresql.transport.respondingTimeouts.idleTimeout=0
```

using [this](https://github.com/traefik/traefik-helm-chart) chart and which gets applied to k8s manifests as expected. 

[Here](https://doc.traefik.io/traefik/routing/entrypoints/#transport) its described to set the desired value to 0, to achieve 

```
"If zero, no timeout exists."
```

### What did you see instead?

But seems like I am not able to define `0`, or , `0s`, `0m0s` , as all of them are printed out by [this](https://github.com/traefik/traefik/blob/b2bb96390a1f7cf8bcc67838c6cf1cf2638f6113/cmd/traefik/traefik.go#L105) line on startup as an empty `respondingTimeouts` block

```
    "postgresql": {
      "address": ":5432/tcp",
      "forwardedHeaders": {},
      "http": {},
      "http2": { "maxConcurrentStreams": 250 },
      "transport": {
        "lifeCycle": { "graceTimeOut": "10s" },
        "respondingTimeouts": {}
      },
      "udp": { "timeout": "3s" }
    },
```

seems like it's just possible to set values > 0, then it's printed out correctly like defined. But this doesn't match with the docs, and doesn't allow to set unlimited.

### What version of Traefik are you using?

traefik:v3.0.0-beta5 docker image

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.
