### ISSUE TITLE
rivaling http and tcp router with wrong priority

### ISSUE THREAD

**Issue by max06** [traefik/traefik#10322]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Backstory: I'm running traefik in a docker setup behind a nat enabled router. A wildcard certificate is in place and functional. A freshly installed kubernetes setup (with its own traefik) was added to the primary traefik as fallback (via tcp router) for everything that's not explicitly defined. Both traefiks will share the same domain.

Issues became apparent when response code and content of a testing service were different in my browser and with curl. Digging deeper a http/2 feature called connection coalescing showed up causing the issue: The browser considers requests to different subdomains belonging to the same origin as long as the CNs on the certificate and the resolved ips for the subdomains are identical, and subsequently reuses an existing http/2 connection. Since this is no new connection, the tcp router has no chance to pick up the request causing 404 errors.

To solve this issue, I tried adding another http fallback router returning 421 (misdirected request) causing browsers to try again with a fresh connection. Surprisingly that http router took precedence over the tcp router contrary to your documentation stating 

> If both HTTP routers and TCP routers listen to the same entry points, the TCP routers will apply before the HTTP routers. If no matching route is found for the TCP routers, then the HTTP routers will take over.

Currently, curl is always returning the 421, without even reusing a connection.

### What did you see instead?

Browser and curl are now showing the 421 for every catched request.

### What version of Traefik are you using?

Version:      2.10.7
Codename:     saintmarcelin
Go version:   go1.21.5
Built:        2023-12-06T15:54:59Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

The primary traefik deployment:

```yaml
version: "3"

services:
  traefik:
    image: traefik:v2.10
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - $PWD/traefik/acme:/etc/traefik/acme
      - $PWD/traefik/dynamic:/etc/traefik/dynamic
    networks:
      public:
        ipv4_address: 192.168.27.249
      shared:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.domain.com`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=secure"
      - "traefik.http.services.dashboard.loadbalancer.server.port=80"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=default"
      - "traefik.http.routers.dashboard.tls.domains[0].main=domain.com"
      - "traefik.http.routers.dashboard.tls.domains[0].sans=*.domain.com"
```

Dynamic content: The tcp router as catchall, then the http 421 workaround for open http/2 connections.

```yaml
tcp:
  routers:
    catchall:
      entryPoints:
        - secure
      service: catchall
      rule: HostSNI(`*`)
      priority: 2
      tls:
        passthrough: true

  services:
    catchall:
      loadBalancer:
        servers:
          - address: 192.168.27.19:443 # the k8s ingress

http:
  routers:
    catchallfix:
      entryPoints:
        - secure
      rule: PathPrefix(`/`)
      priority: 1
      middlewares:
        - killswitch
      service: catchallfix
      tls: true

  services:
    catchallfix:
      loadBalancer:
        servers:
          - url: https://127.0.0.1:9999 # nothing running here, just to satisfy traefik

  middlewares:
    killswitch:
      plugin:
        noop:
          responseCode: 421 # see https://plugins.traefik.io/plugins/634ed49499550ba2e3b43d5c/noop
```

### If applicable, please paste the log output in DEBUG level

(can be provided, but needs a lot of filtering and trimming...)

**Comment by rtribotte** [comment]
Hello @max06,

Thanks for reporting this!

This seems to be the same report as https://github.com/traefik/traefik/issues/10186.
Please take a look at https://github.com/traefik/traefik/issues/10186#issuecomment-1781200577 for more explanations.
I'm closing this issue as a duplicate, but don't hesitate to reopen it if you think this is not the case.

**Comment by max06** [comment]
Hello @rtribotte , thank you for your reply.

Yes, that issue matches mine. The documentation misses any mention of a different handling of tcp and tls-tcp, similar to http. $someone should find the chance to update this, since I've found multiple similar issues in your own community forum regarding the same confusion.

And while we're on it: Is there any preferred solution to my original question? I'm not a big fan of re-encrypting the traffic multiple times if there's no need for that. And somewhere on that way I'm loosing the original client ip... different issue.

**Comment by rtribotte** [comment]
Hello @max06,

To make the catchAll TCP-TLS router take precedence over the HTTPS catchAll router, you can redefine the TCP-TLS router rule to prevent Traefik from considering it as a "catchAll" rule, while being a rule matching any host.

```yaml
tcp:
  routers:
    catchall:
      entryPoints:
        - secure
      service: catchall
      # keep the catchAll behavior in regards to matching, but prevent Traefik from detecting this as a "catchAll" router.
      rule: !HostSNI(`foobar`)
      priority: 1
      tls:
        passthrough: true
```

This is only an example, the rule ```HostSNI(`*`) || HostSNI(`*`)``` would have worked too.
Here is the explanation of why:

https://github.com/traefik/traefik/blob/40de310927507c8c2e24b0ac6d32091e3c167e9b/pkg/muxer/tcp/mux.go#L158-L161
