### ISSUE TITLE
security problem `GHSA-754c-h4cg-2v7c` and no answer from Traefic team

### ISSUE THREAD

**Issue by alapierre** [traefik/traefik#10324]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

3 weeks ago I created security issue GHSA-754c-h4cg-2v7c with unwanted requests from Traefic to Amazon  EC2 instances and I got no aswer.

### What did you see instead?

no answer from Traefic team

### What version of Traefik are you using?

2.10

### What is your environment & configuration?

```yaml
  reverse-proxy:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--metrics.prometheus"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addRoutersLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

Add more configuration information here.
