### ISSUE TITLE
ACME Default Certificate can't be defined using labels

### ISSUE THREAD

**Issue by sgrodzicki** [traefik/traefik#10342]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I was following [the official instructions](https://doc.traefik.io/traefik/https/tls/#acme-default-certificate) on how to configure Traefik to use an ACME provider (like Let's Encrypt) to generate the default certificate on Docker using labels:

```yaml
## Dynamic configuration
labels:
  - "traefik.tls.stores.default.defaultgeneratedcert.resolver=myresolver"
  - "traefik.tls.stores.default.defaultgeneratedcert.domain.main=example.org"
  - "traefik.tls.stores.default.defaultgeneratedcert.domain.sans=foo.example.org, bar.example.org"
```

### What did you see instead?

This configuration would be ignored and for hosts that would not have a defined route (like the IP address of the server for instance) would still be served the `TRAEFIK DEFAULT CERT` instead:

```
curl -kv https://***.**.*.***  
*   Trying ***.**.*.***:443...
* Connected to ***.**.*.*** (***.**.*.***) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=TRAEFIK DEFAULT CERT
*  start date: Jan 10 18:52:03 2024 GMT
*  expire date: Jan  9 18:52:03 2025 GMT
*  issuer: CN=TRAEFIK DEFAULT CERT
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
```

A similar problem has been discussed in [this thread](https://community.traefik.io/t/traefik-v2-and-docker-compose-no-default-certificate/16146/7) on the community forum.

### What version of Traefik are you using?

```
Version:      2.9.10
Codename:     banon
Go version:   go1.20.3
Built:        2023-04-06T16:15:08Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
traefik:
  options:
    network: internal
    publish:
      - "443:443/tcp"
      - "443:443/udp"
    volume:
      - letsencrypt:/letsencrypt
  args:
    api.dashboard: true

    providers.docker.exposedbydefault: false

    entrypoints.http.address: ":80"
    entrypoints.http.http.redirections.entrypoint.to: https

    entrypoints.https.address: ":443"
    experimental.http3: true
    entrypoints.https.http3: true
    entrypoints.https.http.tls.certresolver: letsencrypt

    certificatesresolvers.letsencrypt.acme.httpchallenge: true
    certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint: http
    certificatesresolvers.letsencrypt.acme.email: *********@*********.**
    certificatesresolvers.letsencrypt.acme.storage: /letsencrypt/acme.json
```

This is a Docker Compose-like configuration from [Kamal](https://kamal-deploy.org).
