### ISSUE TITLE
Basic gRPC example with TLS not working as expected

### ISSUE THREAD

**Issue by mjpitz** [traefik/traefik#10352]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

OK. I've been poking around this issue for the last few days and haven't had any success in finding a solution. I currently own a domain (call it `local.mjpitz.com`) that points DNS queries to localhost for development. Inside docker, I run a traefik instance as a reverse proxy so I can label my services hostnames so I can refer to the systems by a hostname instead of by an obscure port mapping... This also allows me to secure my services using a locally signed certificate.  Outside of docker, I am attempting to connect to a service running inside docker using the labeled hostname. I was able to verify my service was reachable using a web browser (hitting the well-known/openid-configuration endpoint) but the same is not true when I tried to connect with grpc.

Here are a couple diagrams for context in case my explanation was not sufficient. This is the basics of my setup:

```mermaid
graph LR
    subgraph docker
        traefik
        identity
    end

    dev --  identity.local.mjpitz.com --> dns
    dns --  127.0.0.1 --> dev
    dev -- "identity.local.mjpitz.com HTTP/2.0 (tls)" --> traefik
    traefik -- "identity.local.mjpitz.com HTTP/2.0 (h2c)" --> identity
```

When requesting `/.well-known/openid-configuration` everything works fine and a result is returned.

```mermaid
sequenceDiagram
    dev ->> traefik: GET /.well-known/openid-configuration HTTP/2.0
    traefik ->> identity: GET /.well-known/openid-configuration HTTP/2.0 (H2C)
    identity -->> traefik: 200 OK
    traefik -->> dev: 200 OK
```

When making a call from gRPC, traefik doesn't appear to route the request and returns a 404 to the client. (The log indicates that it failed to match a backend for the call and I have debug logging on my server side that shows the request / connection didn't even make it to  the server).

```mermaid
sequenceDiagram
    dev ->> traefik: POST /users.v1.UserService/Signup HTTP/2.0
    traefik -->> dev: 404 Not Found
```

I've searched around on both the gRPC and traefik sides of the world to no avail. I know this kind of setup works with nginx and expected it to work with traefik. I tried adding `WithAuthority` to override the host header amongst a handful of other things in code, but nothing seems to change the behavior on traefiks end.

### What did you see instead?

When acting as a reverse proxy for gRPC services using HTTP routers, Traefik fails to route requests to backend instances as described in public docs.

### What version of Traefik are you using?

```
➜  docker run --rm -it traefik:v2.10 version
Version:      2.10.7
Codename:     saintmarcelin
Go version:   go1.21.5
Built:        2023-12-06T15:54:59Z
OS/Arch:      linux/amd64
```

### `docker-compose.yaml`

```yaml
version: "3.8"

services:
  identity:
    # more configuration...
    labels:
      #### Expose the public server
      - "traefik.http.routers.identity.rule=Host(`identity.local.mjpitz.com`)"
      - "traefik.http.routers.identity.service=identity"
      - "traefik.http.services.identity.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.identity.loadbalancer.server.port=8080"
      - "traefik.http.services.identity.loadbalancer.healthcheck.scheme=http"
      - "traefik.http.services.identity.loadbalancer.healthcheck.port=8081"
      - "traefik.http.services.identity.loadbalancer.healthcheck.path=/health"
      #### Expose the private admin server on a separate host
      - "traefik.http.routers.identity_admin.rule=Host(`admin.identity.local.mjpitz.com`)"
      - "traefik.http.routers.identity_admin.service=identity_admin"
      - "traefik.http.services.identity_admin.loadbalancer.server.port=8081"

  traefik:
    image: traefik:v2.10
    restart: always
    command:
      - --accesslog=true
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker
      - --providers.file.filename=/opt/traefik/etc/tls.yaml
      - --providers.file.watch=true
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entrypoint.to=https
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls.options=default
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.local.mjpitz.com`)"
      - "traefik.http.routers.traefik.service=traefik"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik:/opt/traefik/etc
```

### `tls.yaml`

```yaml
tls:
  certificates:
    - certFile: /opt/traefik/etc/certs/traefik.cert.pem
      keyFile: /opt/traefik/etc/certs/traefik.key.pem
```

### If applicable, please paste the log output in DEBUG level

time="2024-01-14T19:00:11Z" level=debug msg="Serving default certificate for request: \"https\""
192.168.65.1 - - [14/Jan/2024:19:00:11 +0000] "POST /users.v1.UserService/Signup HTTP/2.0" 404 19 "-" "-" 1 "-" "-" 0ms
time="2024-01-14T19:00:35Z" level=debug msg="Routine health check refresh for backend: identity@docker"
192.168.65.1 - - [14/Jan/2024:19:00:44 +0000] "GET /.well-known/openid-configuration HTTP/2.0" 200 258 "-" "-" 2 "https-identity@docker" "h2c://172.20.0.2:8080" 2ms
