### ISSUE TITLE
[HTTP/1] httputil: ReverseProxy read error during body copy - use of closed network connection

### ISSUE THREAD

**Issue by nsteinmetz** [traefik/traefik#10381]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Using Traefik v2.10.7 on top of Warp 10 lead to this issue:

> 2024/01/23 09:53:40 reverseproxy.go:666: httputil: ReverseProxy read error during body copy: read tcp 10.0.2.215:35006->10.0.2.215:8080: use of closed network connection

Seems the fix is in golang 1.21 with the usage of `http.ResponseController.EnableFullDuplex()`

More context on this:
* https://github.com/golang/go/issues/40747#issuecomment-1382404132
* https://github.com/golang/go/issues/57786
* https://github.com/golang/go/issues/15527

### What did you see instead?

```
2024/01/23 09:53:40 reverseproxy.go:666: httputil: ReverseProxy read error during body copy: read tcp 10.0.2.215:35006->10.0.2.215:8080: use of closed network connection
```

### What version of Traefik are you using?

2.10.7

### What is your environment & configuration?

Add more configuration information here.
* file provider
* debian 11 VM

**Comment by juliens** [comment]
Hello,

I've noted the concerns you raised, and I'd like to address two points regarding this matter.

Firstly, there is a consideration to introduce the new `EnableFullDuplex` but it might be prudent to hold off for now. We are uncertain about its potential impact on the reverse proxy. While we could implement it with an option, there's a chance it could become obsolete if it turns out to be necessary all the time. Therefore, I suggest waiting for feedback on Go issues before proceeding.

Secondly, I attempted to replicate the issue with Warp10, but unfortunately, I couldn't. To further investigate and verify if the proposed solution resolves the problem, could you provide a reproducible case?

**Comment by nsteinmetz** [comment]
Hi @juliens 

Sorry for the delay, I forgot to answer.

My deployment is as follow:
* traefik binary deployed on host (no container)
* Warp 10 deployed on host (no container) and accessed via localhost or via the private ip on the machine

```yaml
# /etc/traefik/traefik.yml
api:
  dashboard: true
certificatesResolvers:
  le:
    acme:
      email: me@company.com
      storage: /etc/traefik/acme.json
      tlsChallenge: {}
entryPoints:
  api:
    address: 127.0.0.1:9999
  metric:
    address: xxx.xxx.xxx.xxx:80
    http:
      redirections:
        entryPoint:
          scheme: https
          to: matricsecure
  metricsecure:
    address: xxx.xxx.xxx.xxx:443
  web:
    address: yyy.yyy.yyy.yyy:80
    http:
      redirections:
        entryPoint:
          permanent: true
          scheme: https
          to: websecure
  websecure:
    address: yyy.yyy.yyy.yyy:443
global:
  checkNewVersion: true
  sendAnonymousUsage: true
log:
  filePath: /var/log/traefik.log
  format: json
providers:
  file:
    fileName: /etc/traefik/file.yml
```

```yaml
# /etc/traefik/file.yml
http:
  middlewares:
    apiAuth:
      basicAuth:
        users:
        -xxx:yyy
    redirectToHttps:
      redirectScheme:
        permanent: true
        scheme: https
  routers:
    warp10:
      entryPoints:
      - metricsecure
      middlewares:
      - redirectToHttps
      rule: Host(`warp10.company.com`)
      service: warp10@file
      tls:
        certResolver: le
    warp10-http:
      entryPoints:
      - metric
      middlewares:
      - redirectToHttps
      rule: Host(`warp10.company.com`)
      service: warp10@file
  services:
    warp10:
      loadBalancer:
        servers:
        - url: http://10.0.2.215:8080/ (or http://127.0.0.1:8080/
```

On my IoT project, I have http calls to Warp10 every 100ms max but not with a lot of data within (a few data points each)

Hope it helps
