### ISSUE TITLE
Enable loading of TLS certs from directory without specifying every one in dynamic config

### ISSUE THREAD

**Issue by bluepuma77** [traefik/traefik#10407]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

When currently using custom TLS certs, every single one has to be specified manually ([doc](https://doc.traefik.io/traefik/https/tls/#user-defined)):
```
tls:
  certificates:
    - certFile: /path/to/domain.cert
      keyFile: /path/to/domain.key
    - certFile: /path/to/other-domain.cert
      keyFile: /path/to/other-domain.key
```

When looking at `providers.file`, there is already a nice feature to load all files from directory ([doc](https://doc.traefik.io/traefik/providers/file/#directory)) and even watch the directory for changes ([doc](https://doc.traefik.io/traefik/providers/file/#watch)):
```
providers:
  file:
    directory: /path/to/dynamic/conf
    watch: true
```
It would be great to have a similar feature for TLS certs, maybe like:
```
tls:
  certFiles:  
    directory: /path/to/certs
    certSuffix: .cert
    keySuffix: .key
    watch: true
```
We are dealing with 25+ certs and it's hard to create an additional automation to add them to the dynamic config file.

Kind of related: https://github.com/traefik/traefik/issues/5495
