### ISSUE TITLE
Dynamic configuration not reloaded

### ISSUE THREAD

**Issue by darkweak** [traefik/traefik#10409]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hello, I tried to run a dynamic configuration with the content below:
```yaml
# Static traefik configuration
providers:
  file:
    filename: /etc/traefik/dynamic/traefik-dynamic.yml
    watch: true

api:
  dashboard: true
  debug: true
  insecure: true

log:
  level: DEBUG

accessLog: {}
```

```yaml
# /etc/traefik/dynamic/traefik-dynamic.yml
http:
  routers:
    whoami-one:
      middlewares:
        - souin
      entrypoints:
        - http
      service: whoami1
      rule: Host(`whoami1.domain.com`)

  services:
    whoami1:
      loadBalancer:
        servers:
          - url: http://whoami1
        passHostHeader: false
```

I can see the service `whoami-one` is running, but if I update the `/etc/traefik/dynamic/traefik-dynamic.yml` file with the following configuration
```yaml
# /etc/traefik/dynamic/traefik-dynamic.yml
http:
  routers:
    whoami-one:
      middlewares:
        - souin
      entrypoints:
        - http
      service: whoami1
      rule: Host(`whoami1.domain.com`)
    whoami-two:
      middlewares:
        - souin
      entrypoints:
        - http
      service: whoami2
      rule: Host(`whoami2.domain.com`)

  services:
    whoami1:
      loadBalancer:
        servers:
          - url: http://whoami1
        passHostHeader: false
    whoami2:
      loadBalancer:
        servers:
          - url: http://whoami2
        passHostHeader: false
```
traefik won't update the handled routes and only `whoami1` persists. If I restart Træfik it loads the both endpoints.

### What did you see instead?

The configuration is unchanged.

### What version of Traefik are you using?

v3.0

### What is your environment & configuration?

```yaml
# Static traefik configuration
providers:
  file:
    filename: /etc/traefik/dynamic/traefik-dynamic.yml
    watch: true

api:
  dashboard: true
  debug: true
  insecure: true

log:
  level: DEBUG

accessLog: {}
```

```yaml
# /etc/traefik/dynamic/traefik-dynamic.yml
http:
  routers:
    whoami-one:
      middlewares:
        - souin
      entrypoints:
        - http
      service: whoami1
      rule: Host(`whoami1.domain.com`)

  services:
    whoami1:
      loadBalancer:
        servers:
          - url: http://whoami1
        passHostHeader: false
```

```yaml
# /etc/traefik/dynamic/traefik-dynamic.yml
http:
  routers:
    whoami-one:
      middlewares:
        - souin
      entrypoints:
        - http
      service: whoami1
      rule: Host(`whoami1.domain.com`)
    whoami-two:
      middlewares:
        - souin
      entrypoints:
        - http
      service: whoami2
      rule: Host(`whoami2.domain.com`)

  services:
    whoami1:
      loadBalancer:
        servers:
          - url: http://whoami1
        passHostHeader: false
    whoami2:
      loadBalancer:
        servers:
          - url: http://whoami2
        passHostHeader: false
```

I'm running traffic in a container and the both `whoami1` and `whoami2` are running in the same docker network so they are accessible.

**Comment by ldez** [comment]
Hello,

The documentation explains this inside the Limitations section: https://doc.traefik.io/traefik/providers/file/#provider-configuration

It's recommended to use `directory` instead of `filename` because `filename` can have issues with some filesystems.

**Comment by darkweak** [comment]
@kevinpollet @ldez  it still doesn't work using
```yaml
providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true
```

**Comment by rtribotte** [comment]
Hello @darkweak,

This is unexpected.
By looking at the config you have shared, I can see that the routers are using a middleware named `souin` but you didn’t share the definition of it nor the static part if it is indeed the souin plugin.
Can you please provide the full configuration needed to be able to try to reproduce the problem?

**Comment by darkweak** [comment]
@rtribotte here is the minimal reproducible example

```yaml
# ./dynamic-configuration.yml
http:
  routers:
    whoami-one:
      entrypoints:
        - http
      service: whoami1
      rule: Host(`whoami1.domain.com`)
    whoami-two:
      entrypoints:
        - http
      service: whoami2
      rule: Host(`whoami2.domain.com`)

  services:
    whoami1:
      loadBalancer:
        servers:
          - url: http://whoami1
        passHostHeader: false
    whoami2:
      loadBalancer:
        servers:
          - url: http://whoami2
        passHostHeader: false
```
```yaml
# ./traefik.yml
providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

api:
  dashboard: true
  debug: true
  insecure: true

log:
  level: DEBUG

accessLog: {}
```
```yaml
# ./compose.yml
version: '3'

services:
  traefik:
    image: traefik:v3.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./dynamic-configuration.yml:/etc/traefik/dynamic/traefik-dynamic.yml
    ports:
      - 80:80
      - 8080:8080

  whoami1:
    image: traefik/whoami

  whoami2:
    image: traefik/whoami
```

If I update the `./dynamic-configuration.yml` file (remove the `whom-two` router declaration and the `whoami2` service declaration) and save the file changes nothing get reloaded in Træfik but I set the `watch: true` on the directory I put my dynamic configuration. Even without middlewares it doesn't get reloaded. 
If I restart træfik, the new configuration get loaded well with only the `whoami-one` router and the `whoami1` service.
