### ISSUE TITLE
Middlewares: Compression - includedContentTypes field not found 

### ISSUE THREAD

**Issue by vst-name** [traefik/traefik#10402]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

 Created and defined compress middleware in dynamic as such:
```yml
middlewares:
   compress-it:
      compress:
        includedContentTypes:
          - text/html
          - text/css
          - text/javascript
          - application/javascript
          - application/json
          - application/xml
          - text/plain
```

### What did you see instead?
```
upon restart:
time="2024-02-01T06:12:34Z" level=error msg="Error while building configuration (for the first time): field not found, node: includedContentTypes" providerName=file
```

redefined middleware:
```yml
    compress-it:
      compress:
        # includedContentTypes:
        #   - text/html
        #   - text/css
        #   - text/javascript
        #   - application/javascript
        #   - application/json
        #   - application/xml
        #   - text/plain
        excludedContentTypes:
          - image/*
          - audio/*
          - video/*
          - application/octet-stream
          - application/pdf
          - application/zip
          - application/font-*
          - application/vnd.ms-fontobject
          - application/x-font-ttf
          - application/gzip
          - application/zip
          - application/x-tar
          - application/x-7z-compressed
        minResponseBodyBytes: 512
```
```
upon ispection of response headers, it appears that traefik compresses all content not in excluded list, which i believe is reflected on resource increase ( 1 visitor)(docker stats | grep traefik)
036d307e4770   traefik                                 0.31%     34.5MiB / 1GiB        3.37%     3.81MB / 340kB    0B / 3.55MB       10
036d307e4770   traefik                                 0.31%     34.5MiB / 1GiB        3.37%     3.81MB / 340kB    0B / 3.55MB       10
036d307e4770   traefik                                 1.76%     34.51MiB / 1GiB       3.37%     4.24MB / 429kB    0B / 3.55MB       10
036d307e4770   traefik                                 1.76%     34.51MiB / 1GiB       3.37%     4.24MB / 429kB    0B / 3.55MB       10
```

*.js : response headers:
Content-Encoding:    br

simple definition from traefik docs also does not seem to work: (https://doc.traefik.io/traefik/master/middlewares/http/compress/#includedcontenttypes)
```yml
    compress-it:
      compress:
        includedContentTypes:
          - application/json
          - text/html
          - text/plain
```

### What version of Traefik are you using?
```
Version:      2.10.7
Codename:     saintmarcelin
Go version:   go1.21.5
Built:        2023-12-06T15:54:59Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

docker-compose.yaml:
```yml
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --ping
    labels:
      # dashboard
......
    networks:
      - traefik-net
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1g"
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    secrets:
      - cf_api_email
      - cf_api_key
    environment:
      - CLOUDFLARE_EMAIL_FILE=/run/secrets/cf_api_email
      - CLOUDFLARE_API_KEY_FILE=/run/secrets/cf_api_key
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./conf/traefik.yaml:/traefik.yaml"
      - "./conf/traefik-dynamic.yaml:/traefik-dynamic.yaml"
      - "./conf/acme.json:/acme.json"
      - "./conf/certs/:/certs/"
      - traefik_net:/logs
```

traefik-dynamic.yaml:
```yml
http:
  #middleware
  middlewares:
    my-cloudflarewarp:
      plugin:
        cloudflarewarp:
          disableDefault: "false"
          trustip:
            - 2400:cb00::/32

    noRobots:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none"

    https-redirect:
      redirectscheme:
        scheme: https 
        permanent: true
            
    nextcloud-secure-headers:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"

    compress-it:
      compress:
        includedContentTypes:
          - application/json
          - text/html
          - text/plain
```
### If applicable, please paste the log output in DEBUG level

```
time="2024-02-01T06:26:11Z" level=info msg="Configuration loaded from file: /traefik.yaml"
time="2024-02-01T06:26:11Z" level=info msg="Traefik version 2.10.7 built on 2023-12-06T15:54:59Z"
time="2024-02-01T06:26:11Z" level=debug msg="Static configuration loaded {\"global\":{},\"serversTransport\":{\"insecureSkipVerify\":true,\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}},\"web\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}},\"websecure\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250},\"http3\":{},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"},\"file\":{\"watch\":true,\"filename\":\"/traefik-dynamic.yaml\"}},\"api\":{\"insecure\":true,\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"accessLog\":{\"filePath\":\"/logs/access.log\",\"format\":\"common\",\"filters\":{},\"fields\":{\"defaultMode\":\"keep\",\"names\":{\"GzipRatio\":\"keep\",\"Overhead\":\"keep\",\"RequestHost\":\"keep\",\"StartUTC\":\"drop\",\"User-Agent\":\"keep\"},\"headers\":{\"defaultMode\":\"drop\"}}},\"certificatesResolvers\":{\"cfresolver\":{\"acme\":{\"email\":\"admin@{REDACTED}\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"/acme.json\",\"keyType\":\"RSA4096\",\"certificatesDuration\":2160,\"dnsChallenge\":{\"provider\":\"cloudflare\",\"resolvers\":[\"1.1.1.1:53\",\"1.0.0.1:53\"]}}}},\"experimental\":{\"plugins\":{\"cloudflarewarp\":{\"moduleName\":\"github.com/BetterCorp/cloudflarewarp\",\"version\":\"v1.3.3\"},\"sablier\":{\"moduleName\":\"github.com/acouvreur/sablier\",\"version\":\"v1.5.0\"}},\"http3\":true}}"
time="2024-02-01T06:26:11Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
time="2024-02-01T06:26:11Z" level=debug msg="loading of plugin: cloudflarewarp: github.com/BetterCorp/cloudflarewarp@v1.3.3"
time="2024-02-01T06:26:11Z" level=debug msg="loading of plugin: sablier: github.com/acouvreur/sablier@v1.5.0"
time="2024-02-01T06:26:12Z" level=info msg="Starting provider aggregator aggregator.ProviderAggregator"
time="2024-02-01T06:26:12Z" level=debug msg="Starting TCP Server" entryPointName=web
time="2024-02-01T06:26:12Z" level=debug msg="Starting TCP Server" entryPointName=websecure
time="2024-02-01T06:26:12Z" level=info msg="Starting provider *file.Provider"
time="2024-02-01T06:26:12Z" level=debug msg="*file.Provider provider configuration: {\"watch\":true,\"filename\":\"/traefik-dynamic.yaml\"}"
time="2024-02-01T06:26:12Z" level=debug msg="Starting TCP Server" entryPointName=traefik
time="2024-02-01T06:26:12Z" level=error msg="Error while building configuration (for the first time): field not found, node: includedContentTypes" providerName=file
time="2024-02-01T06:26:12Z" level=info msg="Starting provider *docker.Provider"
time="2024-02-01T06:26:12Z" level=debug msg="*docker.Provider provider configuration: {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"}"
time="2024-02-01T06:26:12Z" level=info msg="Starting provider *traefik.Provider"
time="2024-02-01T06:26:12Z" level=debug msg="*traefik.Provider provider configuration: {}"
time="2024-02-01T06:26:12Z" level=info msg="Starting provider *acme.ChallengeTLSALPN"
time="2024-02-01T06:26:12Z" level=debug msg="*acme.ChallengeTLSALPN provider configuration: {}"
time="2024-02-01T06:26:12Z" level=info msg="Starting provider *acme.Provider"
```
