### ISSUE TITLE
IngressRouteTCP can't route to the right endpoint if service(k8s) endpoint is updated

### ISSUE THREAD

**Issue by feiyunzhou** [traefik/traefik#10410]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am using IngressRouteTCP to be the router, and set TLS passthrough.  IngressRouteTCP is pointed to a k8s service. This service's endpoint is changed sometimes.

### What did you see instead?

The service' endpoint is changed, but the IngressRouteTCP can't route traffic to the right endpoint.

### What version of Traefik are you using?

v2.10.4

### What is your environment & configuration?

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: vault-tcp
  namespace: vault
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`vault.my.example.com`)
      services:
        - name: vault-active
          namespace: vault
          port: 8200
  tls:
    passthrough: true

---
apiVersion: v1
kind: Service
metadata:
  name: vault-active
  namespace: vault
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.23.0
    helm.toolkit.fluxcd.io/name: vault
    helm.toolkit.fluxcd.io/namespace: vault
    vault-active: 'true'
  annotations:
    meta.helm.sh/release-name: vault
    meta.helm.sh/release-namespace: vault
spec:
  ports:
    - name: https
      protocol: TCP
      port: 8200
      targetPort: 8200
    - name: https-internal
      protocol: TCP
      port: 8201
      targetPort: 8201
  selector:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
    component: server
    vault-active: 'true'
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
  internalTrafficPolicy: Cluster

```

Add more configuration information here.
