### ISSUE TITLE
Possible memory leak in v2.10.5, maybe cause by consul/consulcatalog provider

### ISSUE THREAD

**Issue by caiuskong** [traefik/traefik#10413]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I deployed traefik in k8s and enabled the `consul/consulcatalog provider`.

### What did you see instead?

Everything is ok, BUT memory leak!
<img width="2105" alt="截屏2024-02-08 14 59 11" src="https://github.com/traefik/traefik/assets/128664758/4c24da0a-33a1-4ef7-84e5-f2cf807ed425">

> If I disable consul provider, memory leaks have been significantly improved.
> If I disable consul/consulcatalog provider, memory leak disappears.

#####  [after 72h] [just enable consulcatalog provider] pprof
- [goroutines20240208103528.pb.gz](https://github.com/traefik/traefik/files/14203882/goroutines20240208103528.pb.gz)
- [heap20240208103528.pb.gz](https://github.com/traefik/traefik/files/14203883/heap20240208103528.pb.gz)

##### [after 4h] [just enable file provider] pprof
- [goroutines20240208150500.pb.gz](https://github.com/traefik/traefik/files/14205416/goroutines20240208150500.pb.gz)
- [heap20240208150500.pb.gz](https://github.com/traefik/traefik/files/14205417/heap20240208150500.pb.gz)

### What version of Traefik are you using?

v2.10.5

### What is your environment & configuration?
- traefik: v2.10.5  (replicas: 12)
- k8s: v1.26
- consul-k8s: v1.3.1

### k8s deployment.yaml
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rdsec-one-apigateway-deployment
  labels:
    app: rdsec-one-apigateway

spec:
  replicas: 12
  selector:
    matchLabels:
      app: rdsec-one-apigateway
  template:
    metadata:
      labels:
        app: rdsec-one-apigateway
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector:
        usage: rdsec-01
      tolerations:
      - key: "HIGH_Critical"
        operator: "Equal"
        value: "r5.4xlarge"
        effect: "NoSchedule"
      containers:
        - name: rdsec-one-apigateway
          image: traefik:v2.10.5
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: dashboard
              containerPort: 8080
          envFrom:
          - configMapRef:
              name: rdsec-one-apigateway-env-config
          - secretRef:  
              name: rdsec-one-apigateway-secret
          volumeMounts:
            - name: rdsec-one-apigateway-traefik-config
              mountPath: /etc/traefik
            - name: rdsec-one-apigateway-traefik-file-provider-config
              mountPath: "/etc/traefik/config"
          resources:
            requests:
              memory: "256Mi"
              cpu: "256m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
      volumes:
        - name: rdsec-one-apigateway-traefik-config
          configMap:
            name: rdsec-one-apigateway-traefik-config
        - name: rdsec-one-apigateway-traefik-file-provider-config
          configMap:
            name: rdsec-one-apigateway-traefik-file-provider-config
```

### traefik.yaml
```yaml
global:
  checkNewVersion: false

serversTransport:
  maxIdleConnsPerHost: 1000
  forwardingTimeouts:
    dialTimeout: 60s
    responseHeaderTimeout: 60s
    idleConnTimeout: 90s

entryPoints:
  web:
    address: :80
    transport:
      respondingTimeouts:
        idleTimeout: 120s
      lifeCycle:
        graceTimeOut: 30s
    http2:
      maxConcurrentStreams: 1000
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      insecure: true
  # websecure:
  #   address: ":443"

api:
  dashboard: true
  insecure: true
  debug: true

ping:
  entryPoint: traefik

log:
  level: DEBUG
  # filePath: /var/log/traefik.log
  format: json

accessLog:
  # filePath: /var/log/access.log
  bufferingSize: 100
  format: json
  filters:
    minDuration: "3ms"
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep
      names:
        Lares-Authorization: redact
        Authorization: redact
        token: redact

metrics:
  prometheus:
    entryPoint: web

tracing:
  serviceName: traefik
  spanNameLimit: 150

  jaeger:
    localAgentHostPort: ""
    collector:
      endpoint: ***

providers:
  file:
    directory: "/etc/traefik/config"
    watch: true
  consul:
    endpoints:
      - "***"
    token: "***"
  consulCatalog:
    refreshInterval: 30s
    watch: false
    endpoint:
      address: ***
      scheme: "https"
      datacenter: aws1
      token: "***"
    exposedByDefault: false
    defaultRule: PathPrefix(`/stag/{{ normalize .Name }}`)
    connectAware: true
    connectByDefault: true

experimental:
  localPlugins:
    jwt-auth:
      moduleName: github.com/traefik/jwt-auth
    validate-request-schema:
      moduleName: github.com/traefik/validate-request-schema
```

**Comment by lbenguigui** [comment]
Hello @caiuskong ,

Thanks for your interest in Traefik.
It appears that your profiles are related to 2 different setups. To conduct a more accurate comparison, I recommend generating pprof profiles on the same setup (e.g., with consulcatalog enabled) at different intervals (e.g., 4 hours and 72 hours).
After analyzing your profiles it seems that the issue may be related to plugins.
To be able to dig further into this issue, can you send us a minimal reproducible setup?

**Comment by caiuskong** [comment]
Thanks for your(@lbenguigui) reply. 

I tried setting up the environment locally and testing, unfortunately I couldn't reproduce the memory leak.
In the local environment, I either file provider or consul provider for API stress testing (router using middlewares), and the memory changes were similar.

I enabled both consul/consulcatalog provider and did the following tests on the stag environment, potential memory leaks have occurred.
By analyzing the pprof, I suspect a goroutine leak and it is caused by the plugin (yaegi)?

### Testing Data
| time      | action |  pprof |
| ----------- | ----------- |  ----------- |
| 5m      | do nothing, only start traefik       | [goroutine-profile.pb.gz](https://github.com/traefik/traefik/files/14356867/goroutine-profile.pb.gz) , [heap-profile.pb.gz](https://github.com/traefik/traefik/files/14356868/heap-profile.pb.gz)         |
| 25m   | API stress testing (106540 requests in 5.00m). Router from consul provider.        |  [goroutine-profile.pb.gz](https://github.com/traefik/traefik/files/14356883/goroutine-profile.pb.gz), [heap-profile.pb.gz](https://github.com/traefik/traefik/files/14356884/heap-profile.pb.gz)       |
| 45m   | API stress testing (288594 requests in 5.00m). Router from consulcatalog. provider        |  [goroutine-profile.pb.gz](https://github.com/traefik/traefik/files/14356897/goroutine-profile.pb.gz), [heap-profile.pb.gz](https://github.com/traefik/traefik/files/14356898/heap-profile.pb.gz)      |
| 22h   | Regular requests, about 20,000+ per hour        |  [goroutine-profile.pb.gz](https://github.com/traefik/traefik/files/14357402/goroutine-profile.pb.gz), [heap-profile.pb.gz](https://github.com/traefik/traefik/files/14357403/heap-profile.pb.gz)      |

### Traefik Static Configration
```yml
global:
  checkNewVersion: false

serversTransport:
  maxIdleConnsPerHost: 1000
  forwardingTimeouts:
    dialTimeout: 60s
    responseHeaderTimeout: 60s
    idleConnTimeout: 90s

entryPoints:
  web:
    address: :80
    transport:
      respondingTimeouts:
        idleTimeout: 120s
      lifeCycle:
        graceTimeOut: 30s
    http2:
      maxConcurrentStreams: 1000
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      insecure: true
  # websecure:
  #   address: ":443"

api:
  dashboard: true
  insecure: true
  debug: true

ping:
  entryPoint: traefik

log:
  level: DEBUG
  # filePath: /var/log/traefik.log
  format: json

accessLog:
  # filePath: /var/log/access.log
  bufferingSize: 100
  format: json
  filters:
    minDuration: "3ms"
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep
      names:
        Lares-Authorization: redact
        Authorization: redact
        token: redact

metrics:
  prometheus:
    entryPoint: web

tracing:
  serviceName: traefik
  spanNameLimit: 150

  jaeger:
    localAgentHostPort: ""
    collector:
      endpoint: https://jaeger-collector-stg.***.com/api/traces

providers:
  file:
    directory: "/etc/traefik/config"
    watch: true
  consul:
    endpoints:
      - "consul-stag.***.com"
    token: "${CONSUL_HTTP_TOKEN}"
  consulCatalog:
    refreshInterval: 30s
    watch: false
    endpoint:
      address: consul-stag.***.com
      scheme: "https"
      datacenter: aws1
      token: "${CONSUL_HTTP_TOKEN}"
    exposedByDefault: false
    defaultRule: PathPrefix(`/stag/{{ normalize .Name }}`)
    connectAware: true
    connectByDefault: true

experimental:
  localPlugins:
    jwt-auth:
      moduleName: github.com/traefik/jwt-auth
    validate-request-schema:
      moduleName: github.com/traefik/validate-request-schema
```

### Traefik Dynamic Configuration Raw Data (Part)
```json
{
    "routers": {
        "caius-ex-service@consul": {
            "entryPoints": [
                "web"
            ],
            "middlewares": [
                "secured-chain@consul"
            ],
            "service": "caius-ex-service",
            "rule": "PathPrefix(`/stag/caius-ex-service`)",
            "status": "enabled",
            "using": [
                "web"
            ]
        },
        "caius-in-service@consulcatalog": {
            "entryPoints": [
                "web"
            ],
            "middlewares": [
                "secured-chain@consul"
            ],
            "service": "caius-in-service",
            "rule": "PathPrefix(`/stag/caius-in-service`)",
            "status": "enabled",
            "using": [
                "web"
            ]
        },
    },
    "middlewares": {
        "auth@consul": {
            "plugin": {
                "jwt-auth": {
                    "redisUrl": "***",
                    "secret": "***"
                }
            },
            "status": "enabled"
        },
        "validateRequestSchema@consul": {
            "plugin": {
                "validate-request-schema": {
                    "extension": {
                        "name": "x-amazon-apigateway-integration",
                        "replacePathServices": "***"
                    },
                    "redisUrl": "***"
                }
            },
            "status": "enabled"
        },
        "replacepathregex-gw-prefix@consul": {
            "replacePathRegex": {
                "regex": "^/(stag|prod)/[^/]+/?(.*?)/?$",
                "replacement": "/${2}"
            },
            "status": "enabled"
        },
        "secured-chain@consul": {
            "chain": {
                "middlewares": [
                    "auth@consul",
                    "validateRequestSchema@consul",
                    "replacepathregex-gw-prefix@consul"
                ]
            },
            "status": "enabled",
            "usedBy": [
                "caius-ex-service@consul",
            ]
        },
    },
    "services": {
        "caius-ex-service@consul": {
            "loadBalancer": {
                "servers": [
                    {
                        "url": "***"
                    }
                ],
                "passHostHeader": false
            },
            "status": "enabled",
            "usedBy": [
                "caius-ex-service@consul"
            ],
            "serverStatus": {
                "***": "UP"
            }
        },
        "caius-in-service@consulcatalog": {
            "loadBalancer": {
                "servers": [
                    {
                        "url": "***"
                    }
                ],
                "passHostHeader": true,
                "serversTransport": "tls-default-aws1-caius-in-service@consulcatalog"
            },
            "status": "enabled",
            "usedBy": [
                "caius-in-service@consulcatalog"
            ],
            "serverStatus": {
                "***": "UP"
            }
        },
    }
}
```
