### ISSUE TITLE
Traefik is removing Access-Control-Allow-Origin headers from the service response

### ISSUE THREAD

**Issue by GiamBoscaro** [traefik/traefik#10432]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have a Node service that manages the cors settings (using [cors middleware](https://www.npmjs.com/package/cors)). I am getting a CORS error from our frontend when calling this node service passing through Traefik. Since I haven't had this problem in the past when using nginx or caddy, I was wondering if Traefik was the culprit. I have done some testing.

Calling the API from inside the docker container:

```sh
curl --head -X OPTIONS \
  -H "Access-Control-Request-Method: GET" \
  -H "Origin: https://my-domain" \
  http://localhost:3000/info/version
```

The response I get is this, proving that the cors middleware is working.

```sh
X-Powered-By: Express
Access-Control-Allow-Origin: https://my-domain
Vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET,HEAD,PUT,PATCH,POST,DELETE
Access-Control-Allow-Headers: Content-Type,Authorization,Accepts,Set-Cookie,Cookie,Range
Access-Control-Expose-Headers: Accept-Ranges, Content-Encoding, Content-Length, Content-Range
Content-Length: 0
Date: Wed, 14 Feb 2024 09:29:17 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

Now, retried using the external URL, passing through Traefik:

```sh
curl --head -X OPTIONS \
  -H "Access-Control-Request-Method: GET" \
  -H "Origin: https://my-domain" \
  https://my-domain/info/version
```

The response is different. It is missing the `Access-Control-Allow-Origin `header.

```sh
access-control-allow-credentials: true
access-control-allow-headers: Content-Type,Authorization,Accepts,Set-Cookie,Cookie,Range
access-control-allow-methods: GET,HEAD,PUT,PATCH,POST,DELETE
access-control-expose-headers: Accept-Ranges, Content-Encoding, Content-Length, Content-Range
alt-svc: h3=":443"; ma=2592000
date: Wed, 14 Feb 2024 09:30:00 GMT
vary: Origin
x-powered-by: Express
```

I was wondering if our corporate proxy was doing something, since I see that also all the headers have been rewritten in lowercase, so I tested a similar call to another service that not using Traefik nor any other proxy but the corporate proxy. Indeed the headers where lowercase again, but `Access-Control-Allow-Origin` was there. This feels like is Traefik that is doing something to the header.

What I done is then configuring CORS directly with Traefik:

 ```yaml
 labels:
      # ...
      # CORS
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolexposeheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
```

In this case, everything work. I can also replace `*` with something more restrictive. The thing is, what if I wanted to continue managing the CORS from within the Node service instead of Traefik. Because in this situation I need to maintain double the code: the Traefik configuration and also the Node code. I could remove all CORS settings from Node, but what if in the future we change proxy, or if the microservice will be deployed to another environment without Traefik?

Is there a reason why Traefik is removing the header from the response? Is there a way to delegate the CORS management to the service and let Traefik forward all the CORS headers incoming from the service?

### What did you see instead?

The response is missing the `Access-Control-Allow-Origin `header.

```sh
access-control-allow-credentials: true
access-control-allow-headers: Content-Type,Authorization,Accepts,Set-Cookie,Cookie,Range
access-control-allow-methods: GET,HEAD,PUT,PATCH,POST,DELETE
access-control-expose-headers: Accept-Ranges, Content-Encoding, Content-Length, Content-Range
alt-svc: h3=":443"; ma=2592000
date: Wed, 14 Feb 2024 09:30:00 GMT
vary: Origin
x-powered-by: Express
```

### What version of Traefik are you using?

2.11

### What is your environment & configuration?

```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: false
  
api:
  dashboard: true
  insecure: false

experimental:
  http3: true

serversTransport:
  insecureSkipVerify: true

ping: {}

log:
  level: DEBUG # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: json # common, json, logfmt
  filePath: /var/log/traefik/out.log

accessLog:
  format: common  # common, json, logfmt
  filePath: /var/log/traefik/access.log

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    http3: 
      advertisedPort: 443

  dcv-tcp:
    address: ":8443"

  dcv-udp:
    address: ":8443/udp"

http:
  routers:
    dashboard:
      rule: Host(`traefik.my-domain.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal
      tls: {}
      entryPoints:
        - websecure
  middlewares:
    traefik-stripPrefix:
      stripPrefix:
        prefixes:
          - "/traefik"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /run/secrets/tls_cert
        keyFile: /run/secrets/tls_cert_key

providers:
  docker:
    exposedByDefault: false
    network: web
  file:
    directory: /etc/traefik
```

```yaml
version: '3.8'

networks:
  public-stage:
    name: public-stage
    driver: overlay
      
secrets:
  tls_cert:
    external: true
  tls_cert_rsa_key:
    external: true
  tls_root_ca:
    external: true

services:

  traefik:
    image: traefik:v2.11
    hostname: "traefik-{{.Task.ID}}"
    networks:
      - public-stage
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
      - 8443:8443/tcp
      - 8443:8443/udp
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/media/sambashare/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
    secrets:
      - source: tls_cert_rsa_key
        target: tls_cert_key
        mode: 0600
      - source: tls_cert
        target: tls_cert
        mode: 0600
      - source: tls_root_ca
        target: tls_root_ca
        mode: 0600
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
```
