### ISSUE TITLE
Subdomain wildcard

### ISSUE THREAD

**Issue by lucabecchetti** [traefik/traefik#10430]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

i have this part of configuration:

  ```
      image: ${DOCKER_IMAGE}
        labels:
            # Explicitly instruct Traefik to expose this service
            traefik.enable: true
            # 80 is the port that the nitrogen_app container image is listening to
            traefik.http.services.app-erp.loadbalancer.server.port: 80

            ## Unsecure configuration
            #traefik.http.routers.app-erp.entrypoints: web
            #traefik.http.routers.traefik-dashboard-http-router.rule: PathPrefix(`/`)

            ## Secure configuration
            traefik.http.routers.app-erp.entrypoints: web-secure
            ## Rule based on the Host of the request
            traefik.http.routers.app-erp.rule: HostRegexp(`{subdomain:[a-zA-Z0-9]+}.my.it`) && !Host(`www.my.it`) 
            # Enable SSL authentication for this domain
            traefik.http.routers.app-erp.tls: true
            traefik.http.routers.app-erp.tls.domains[0].main: my.it
            traefik.http.routers.app-erp.tls.domains[0].sans: "*.my.it"
            # Set letsencrypt as resolver
            traefik.http.routers.app-erp.tls.certresolver: letsencrypt
```

### What did you see instead?

I'm unable to get certificate for each subdomain, i cannot use Host name becouse it's a tenant application and name is dynamic, how can i solve this?

### What version of Traefik are you using?

2.10.5

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.
