### ISSUE TITLE
Default certificate not found when migrating to v3.0.0-rc1

### ISSUE THREAD

**Issue by Tchoupinax** [traefik/traefik#10455]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I upgraded Traefik `2.10.7` to `3.0.0-rc1` and saw that the default TLS certificate is not served anymore.

```
github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:320 > No default certificate, fallback to the internal generated certificate tlsStoreName=default
```

My default certificate is declared in my cluster like this

```
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
spec:
  certificates:
    - secretName: mydomain-wildcard-tls
    - secretName: mydomain-monitoring-wildcard-tls
  defaultCertificate:
    secretName: mydomain-wildcard-tls
```

I'm using `k3s` version `v1.29.1+k3s1`

### What did you see instead?

Certificates are not served anymore.

According to the [Traefik blog announcement](https://traefik.io/blog/announcing-traefik-proxy-v3-rc/), the migration should be smooth.

### What version of Traefik are you using?

v3.0.0-rc1

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.
