### ISSUE TITLE
Veeam 12 is sending Content-Length=0 in a GET request

### ISSUE THREAD

**Issue by GRADeS-Gwen** [traefik/traefik#10466]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

A service is calling ou own S3 (not amazon) through traefik. It send a `GET` with header `Content-length: 0` and `SignedHeaders=content-length` in header `Autorization`. But when the S3 service receive the request, the `SignedHeaders=content-length` in header `Autorization` is still there, but the header `Content-length: 0` got remove. Seeing that a header is missing, the S3 service reject the request with a 403.

We originaly use `HTTPS` as input, but to debug, we tried with `HTTP`. And so we `tcpdump` the input request : 
![image](https://github.com/traefik/traefik/assets/66824851/067cc8ae-554f-430d-a58f-0c95b5816cbd)

### What did you see instead?

And the output request : 
![image](https://github.com/traefik/traefik/assets/66824851/079173c8-2414-4358-8f0d-341bbefb0b2a)

You can clearly see the "Content-length" disapearing from the request between before and after Traefik. I know it is an optional parameter but it should not be removed, furthuermore if another header is refering to it (SignedHeaders).

### What version of Traefik are you using?

2.11.0

### What is your environment & configuration?

main.yml
```yaml
entryPoints:
  web:
    address: ":80"
serversTransport:
  insecureSkipVerify: true
  maxIdleConnsPerHost: 800
  forwardingTimeouts:
    idleConnTimeout: 60s

log:
  #level: WARN
  level: DEBUG
  filePath: /var/log/traefik.log
  format: json

accessLog:
  filePath: "/var/log/traefik/access.log"
  fields:
    defaultMode: keep
    names:
      StartUTC: drop
    headers:
      defaultMode: keep

api:
  dashboard: true
  debug: true
  insecure: true

ping: {}
providers:
  file:
    directory: "/etc/traefik/conf"
    watch: true
```

_acl.yml
```yaml
http:
  middlewares:
    internalOnly:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/32"
          - "172.16.0.0/12"
          - "192.168.10.0/24"
```

s3.yml
```yaml
http:
  routers:
    router-http-s3:
      rule: Host(`s3.xxxxxxx.fr`)
      entryPoints:
        - web
      middlewares:
        - internalOnly
      service: service-s3

  services:
    service-s3:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:8081/
        passHostHeader: true
```

**Comment by GRADeS-Gwen** [comment]
@mmatur Thank you for the analyse. Reading the Go method, it is clear that my case fall in the last return.
I also tried to read and understand the RFC2616, but that was not clear. So I search a bit everywhere and mostly the result is that "it is optionnal" ... 

We are on the same page that sending a GET with a Content-Length header equal to 0 is strange. Furthermore, the problem did not exist in the previous version of Veeam (11), only in the newest (12). We have exchanged a lot of ticket and did a lot of test with there support. In the end they say that they are not able to confirm that the "Content-Length" was present in the "SignHeader" on version 11 (what the ..., not able to confirm your code ??!!) and that it can not be removed in the version 12 ...
The solution they gave us was to remove Traefik and talk directlly to the service, or use another reverse to offload the SSL ... I am not particulary a fan to that, but I think we will need to do something like that in the short term.

**Comment by mmatur** [comment]
@GRADeS-Gwen thanks for your answer.

Strange that they can not confirm their code. It could be linked to an upgrade to the aws-sdk between Veeam 11 and Veeam 12.

As you can see in the following screenshot, this code is present in go since many years, we will not be able to do anything on our side for this subject.

<img width="1016" alt="image" src="https://github.com/traefik/traefik/assets/1776972/814eff5b-50e5-4fb0-9a75-8320ca7b9e92">

If I understood correctly your are using Traefik to handle TLS termination and add a ipAllowList Middleware. 
One possibility is to use a TCP Router instead of HTTP Router.

```yaml
tcp:
  middlewares:
    internalOnly:
      ipAllowList:
        sourceRange:
          - "127.0.0.1/32"
          - "172.16.0.0/12"
          - "192.168.10.0/24"
  routers:
    router-http-s3:
      rule: HostSNI(`s3.xxxxxxx.fr`)
      entryPoints:
        - websecure
      middlewares:
        - internalOnly
      service: service-s3
      tls: {}

  services:
    service-s3:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:8081/
        passHostHeader: true
```

Switching from HTTP to TCP router will allow you to do the TLS termination on Traefik and forward the TCP request to your s3.

**Comment by GRADeS-Gwen** [comment]
> Strange that they can not confirm their code.

In my opinion, they just dont want to search .. I found an old Veeam test server in Veeam 10, and I can confirm that the "Content-Length" was not present in the "SignHeader". I will try to upgrade to 11 and 12.0 to confirm our supposition and send them to Veeam.
I will report here if we got aything coming back from Veeam

> One possibility is to use a TCP Router instead of HTTP Router.

Good call ! I did not even think about it. I transposed our config like bellow and it worked \o/. It give us less parameters, but at least it work with a bit of security.

```yaml
tcp:
  routers:
    router-https-s3:
      rule: HostSNI(`s3.XXX.fr`)
      entryPoints:
        - web-secure
      middlewares:
        - internalOnly
      service: service-s3
      tls:
        certResolver: le-gandi

  services:
    service-s3:
      loadBalancer:
        servers:
          - address: "127.0.0.1:8081"
```
