### ISSUE TITLE
command traefik error: field not found, node: elastic

### ISSUE THREAD

**Issue by nehemiascr** [traefik/traefik#10461]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I updated my traefik container setup from v3.0.0-beta5 to v3.0.0-rc1, started to get the following error:

```
 ✔ Container traefik  Started                                                                                          0.0s 
traefik  | {"level":"error","error":"command traefik error: field not found, node: elastic","time":"2024-02-21T13:07:52Z","message":"Command error"}
traefik exited with code 0
```

this is the section of my traefik.toml file that is causing the error

```toml
[tracing]
  serviceName = "<redacted>"
  [tracing.elastic]
   serverURL = "<redacted>"
   serviceEnvironment = "<redacted>"
   secretToken = "<redacted>"
```

I have commented out the tracing configuration, traefik runs, but no tracing

### What did you see instead?

command traefik error: field not found, node: elastic

### What version of Traefik are you using?

v3.0.0-rc1

### What is your environment & configuration?

```toml
[tracing]
  serviceName = "<redacted>"
  [tracing.elastic]
   serverURL = "<redacted>"
   serviceEnvironment = "<redacted>"
   secretToken = "<redacted>"
```

docker on RHEL 9

### If applicable, please paste the log output in DEBUG level

```log 
✔ Container traefik  Started                                                                                          0.0s 
traefik  | {"level":"error","error":"command traefik error: field not found, node: elastic","time":"2024-02-21T13:07:52Z","message":"Command error"}
traefik exited with code 0
```
