### ISSUE TITLE
(re)enable labels for `loadbalancer.proxyprotocol=2`

### ISSUE THREAD

**Issue by Morriz** [traefik/traefik#10460]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hi, the docs on `proxyprotocol` are saying to set this part:
```yaml
services:
  x:
    loadbalancer:
      proxyProtocol: (1|2)
```
Unfortunately the option to configure this by labels seems to be nuked from the topology (I assume it was possible as many ppl referred to those labels in many issues on the web). Maybe regression, or just some weird decision, as now it is not possible to have labels-only dynamic config (meaning you also have to update the file to set that bit).

**Comment by rtribotte** [comment]
Hello @Morriz,

Thanks for your interest in Traefik!

The documentation seems correct: https://doc.traefik.io/traefik/routing/services/#proxy-protocol.

The configuration should be (in your example the `version` node is missing):
```yaml
## Dynamic configuration
tcp:
  services:
    my-service:
      loadBalancer:
        proxyProtocol:
          version: 1
```

I'm marking and closing this issue as a question accordingly, but feel free to reopen it if you think I'm missing something.
