### ISSUE TITLE
Update TLS Certificate Not Reloaded 

### ISSUE THREAD

**Issue by kakaNo1** [traefik/traefik#10463]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

create new cert : 
```
kubectl create secret tls cert2 --key 1.key --cert 1.pem
```

Update secretName on IngressRoute

### What did you see instead?

When I updated the secretName, the certificate information for the website address was not updated

### What version of Traefik are you using?

traefik:v2.10.1

### What is your environment & configuration?

traefik config
```yaml
deployment:
  podLabels:
    k8s-app: traefik

ingressClass:
  enabled: true
  isDefaultClass: false
  fallbackApiVersion: "v1beta1"

ingressRoute:
  dashboard:
    enabled: true
    annotations:
      "kubernetes.io/ingress.class": traefik-v2

globalArguments: []

providers:
  kubernetesCRD:
    enabled: true
    namespaces:
      - test
      - master
      - qa
      - staging
      - stable
      - logging
      - argocd
      - kube-system
      - task-uat
      - task-live
    ingressClass: traefik-v2
  kubernetesIngress:
    enabled: true
    ingressClass: traefik-v2
    namespaces:
      - test
      - master
      - qa
      - staging
      - stable
      - logging
      - argocd
      - kube-system
      - task-uat
      - task-live
additionalArguments:
  - "--accesslog"
  - "--log.level=WARN"
  - "--entryPoints.websecure.http.tls=true"
  - "--serverstransport.insecureskipverify=true"
  - "--metrics.prometheus=true"
  - "--api.insecure=true"
  - "--providers.kubernetesingress.ingressclass=traefik-v2"
  - "--providers.kubernetescrd.ingressclass=traefik-v2"

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
ports:
  traefik:
    port: 9000
    expose: false
  web:
    redirectTo: websecure
  websecure:
    tls:
      enabled: true
autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60
resources:
  requests:
    cpu: 0.3
    memory: 300Mi
  limits:
    cpu: 1
    memory: 1Gi
```

IngressRoute config
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik-v2
  name: test
  namespace: staging
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`xxxxxx`)
      services:
        - name: web
          port: 80
  tls:
    secretName: cert1 -> cert2
```

### If applicable, please paste the log output in DEBUG level

No associated log printing
