### ISSUE TITLE
Traefik Ingress Response Time Out 

### ISSUE THREAD

**Issue by venkat-99** [traefik/traefik#10485]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hi Team,

Actually Our request is taking  time(more than a minute) to get the response from server and Traefik is disconnecting before getting the response(below 1min). We increased the timeout parameters but still Traefik ingress is closing the connection before getting the response from the server. 
We configured traefik ingress route and serverstransport as below. is it Bug or missing anything from my end?
Please suggest us here.

Configs:

-entryPoints.web.transport.respondingTimeouts.writeTimeout=0 
--entryPoints.web.transport.respondingTimeouts.readTimeout=0 
--entryPoints.web.transport.respondingTimeouts.idleTimeout=0 
--entryPoints.websecure.transport.respondingTimeouts.writeTimeout=0
--entryPoints.websecure.transport.respondingTimeouts.readTimeout=0 
--entryPoints.websecure.transport.respondingTimeouts.idleTimeout=0 
--log.level=DEBUG 
--serversTransport.insecureSkipVerify=true

### What did you see instead?

Logs:
 "level=debug msg="'499 Client Closed Request' caused by: context canceled" error.

### What version of Traefik are you using?

traefik:2.5.3

### What is your environment & configuration?

```yaml
# (paste your configuration here)

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:  
  name: test-proxy
  namespace: test
  
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`exampledomain.net`) && PathPrefix(`/`)
      services:
        - name: test-proxy
          passHostHeader: true
          port: 80
          serversTransport: mytransport
  tls:
    domains:
      - main: exampledomain.net
    secretName: my-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata: 
  name: mytransport
  namespace: test
  
spec:
  forwardingTimeouts:
    dialTimeout: 360s
    idleConnTimeout: 360s
    responseHeaderTimeout: 360s
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

Logs:
 "level=debug msg="'499 Client Closed Request' caused by: context canceled" error.
