### ISSUE TITLE
Keep URIs in server list

### ISSUE THREAD

**Issue by rarecrumb** [traefik/traefik#10487]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I have two backends that I'd like to load balance between, but both servers are authenticated using a different URI:

```yaml
services:
  my-backend:
    loadBalancer:
      servers:
        - url: https://my-first-backend.com/my-auth-token
        - url: https://my-second-backend.com/my-other-different-auth-token
```

Since Traefik strips the URI, this configuration is impossible. Also, since the URIs are different between these servers, the add-prefix middleware will not work, nor will health checks...

The end goal is to have a request come into traefik (`https://traefik:8080`) and then get routed to either backend, as long as it's healthy. In the future, more backends could be added and I'd like Traefik to load balance between them.

Is there any solution to this with Traefik or should I find a different proxy?
