### ISSUE TITLE
TLS certificate generation mix the CN and SANs

### ISSUE THREAD

**Issue by ocanam** [traefik/traefik#10486]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I've observed a bug during the letsencrypt certificate generation.

Given the following endpoint config, defining the main and sans for a letsencrypt wildcard certificate.
The certresolver use the DNS challenge (as the goal is to get wildcard certificate). I won't go in more details about the certResolver and the rest of the config, as no problem on those sides.
```yaml
entryPoints:
  websecure:
    address: "1.2.3.4:443"
    proxyProtocol:
      trustedips:
        - "10.20.30.40/32"
    forwardedHeaders:
      trustedIPs:
        - "10.20.30.40/32"
    http:
      tls:
        certresolver: myle
        domains:
          - main: "eu.mydomain.com"
            sans: 
              - "*.eu.mydomain.com"
              - "*.archive.eu.mydomain.com"
              - "*.test.eu.mydomain.com"
```

I was expecting a certificate generated containing
```
...
Subject: CN = eu.mydomain.com
...
X509v3 Subject Alternative Name:
                DNS:*.eu.mydomain.com, DNS:*.archive.eu.mydomain.com, DNS:*.test.eu.mydomain.com
...
```

### What did you see instead?

Instead of the expected CN and SANs, in the generated certificate I have
```
...
Subject: CN = *.archive.eu.mydomain.com
...
X509v3 Subject Alternative Name:
                DNS:*.archive.eu.mydomain.com, DNS:*.eu.mydomain.com, DNS:*.test.eu.mydomain.com, DNS:eu.mydomain.com
...
```

Confirmed by the content of the acme.json
```json
"domain": {
    "main": "*.archive.eu.mydomain.com",
    "sans": [
        "*.eu.mydomain.com",
        "*.test.eu.mydomain.com",
        "eu.mydomain.com"
    ]
}
```
I tried swapping the main and sans, changing the sans order, in the config, the result is always the same.

It looks like the CN and SANs are just sorted as a unique list of string, the first element used as the CN and all the others used as SANs.

Of course as all the requested names (CN and SANs) are present in the certificate it do the job, but to be strict the generated certificate has not the asked CN, and that's bad (IMO).

### What version of Traefik are you using?

binary distribution, running on Debian12.5 amd64
```
# /usr/local/bin/traefik version
Version:      2.11.0
Codename:     cheddar
Go version:   go1.22.0
Built:        2024-02-12T15:26:45Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

not relevant
