### ISSUE TITLE
Only one node serve proper certificate

### ISSUE THREAD

**Issue by majkrzak** [traefik/traefik#10497]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

When setting up Traefik on Kubernetes as DaemonSet...

### What did you see instead?

only one node from the set serves the issued certificate, while others serves Traefik default ones. 

### What version of Traefik are you using?

2.10.5

### What is your environment & configuration?

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    deployment:
      kind: Deployment
    persistence:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteMany
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: true
    certResolvers:
      letsencrypt:
        email: example@example.com
        tlsChallenge: true
        storage: /data/acme.json
    ports:
      websecure:
        tls:
          certResolver: letsencrypt

```

Add more configuration information here.
