### ISSUE TITLE
Create a cross namespace load balancing using IngressRouteTCP, where only the last service can be accessed

### ISSUE THREAD

**Issue by nelsonstar** [traefik/traefik#10495]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I created two configurations using IngressRoute and IngressRouteTCP, respectively The configuration of IngressRoute is used normally and can rotate to access the two backend services. However, load balancing cannot be achieved through IngressRouteTCP, and only the last service can be accessed. My configuration is as follows:

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-http
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`test.k8sdeploy.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: nginx-service
      namespace: zone2
      port: 80
    - name: nginx-service
      namespace: zone1
      port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: nginx-tcp
spec:
  entryPoints:
    - port19036
  routes:
  - match: HostSNI(`*`)
    services:
      - name: nginx-service
        port: 80
        namespace: zone1
      - name: nginx-service
        port: 80
        namespace: zone2

### What did you see instead?

Does IngressRouteTCP currently not support load balancing for multiple services?

### What version of Traefik are you using?

Version:      3.0.0-rc1
Codename:     cheddar
Go version:   go1.22.0
Built:        2024-02-13T13:41:20Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

Official configuration

**Comment by nelsonstar** [comment]
```
apiVersion: v1
kind: Namespace
metadata:
  name: zone2
---
apiVersion: v1
kind: Namespace
metadata:
  name: zone1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: zone1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.24.0
        ports:
        - containerPort: 80
        command: ["nginx", "-g", "daemon off;"]
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/sites-available/default  # Updated mount path
          subPath: default
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: zone1
data:
  default: |
    server {
      listen 80;
      server_name localhost;
      location / {
        default_type text/plain;
        return 200 "This is Service A";
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: zone2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.24.0
        command: ["nginx", "-g", "daemon off;"]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/sites-available/default   # Updated mount path
          subPath: default
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: zone1
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: zone2
data:
  default: |
    server {
      listen 80;
      server_name localhost;

      location / {
        default_type text/plain;
        return 200 "This is Service B";
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: zone2
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
```
