### ISSUE TITLE
Access log has many items with "0"

### ISSUE THREAD

**Issue by Eliohoyeck** [traefik/traefik#10504]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am using Traefik as our Ingress Controller to expose the different services we run on top of Kubernetes.
We have some logs on kibana and logs from traefik pods where we investigate in case we have any problems whatsoever in the network, for that I wish to check the response status code in my access log to see if my services are working correctly, i am expecting to see 2XX, 4XX, 5XX status codes.

### What did you see instead?

i am getting a lot of DownStreamStatus: 0 and OriginStatus: 0 or DownStreamStatus:2XX,4XX and 5XX with OriginStatus:0 
`
traefik-secure-687cf57f46-dx6v7 traefik-secure {"ClientAddr":"X.X.X.X:3808","ClientHost":"A.A.A.A, B.B.B.B, C.C.C.C","ClientPort":"3808","ClientUsername":"-","DownstreamContentSize":0,"DownstreamStatus":0,"Duration":38786475932,"OriginContentSize":0,"OriginDuration":38786282729,"OriginStatus":0,"Overhead":193203,"RequestAddr":"tdc.ap.cloud.x.com","RequestContentSize":0,"RequestCount":6508019,"RequestHost":"tdc.ap.cloud.x.com","RequestMethod":"GET","RequestPath":"/api/v1/relay/ws","RequestPort":"-","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"app-data-apps-gateway-public-tdc-ap-cloud-x-com@kubernetes","ServiceAddr":"Y.Y.Y.Y:9999","ServiceName":"app-data-apps-gateway-80@kubernetes","ServiceURL":{"Scheme":"http","Opaque":"","User":null,"Host":"Y.Y.Y.Y:9999","Path":"","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"StartLocal":"2024-03-07T12:31:05.943820953Z","StartUTC":"2024-03-07T12:31:05.943820953Z","entryPointName":"websecure","level":"info","msg":"","request_User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/111.0.5563.146 Safari/537.36 CloudWatchSynthetics/arn:aws:synthetics:ap-northeast-1:1722922XXX:canary:tdc-login-fa","request_X-B3-Parentspanid":"1faexxx2327a1f6e","request_X-B3-Sampled":"0","request_X-B3-Spanid":"1cb933xxxce7e43e","request_X-B3-Traceid":"598ca1e32a664adf798c6fxxx1e2e1de","time":"2024-03-07T12:31:44Z"}
`
and 

`
traefik-secure-687cf57f46-q6tjc traefik-secure {"ClientAddr":"x.x.x.x:41912","ClientHost":"x.x.x.x","ClientPort":"41912","ClientUsername":"-","DownstreamContentSize":2,"DownstreamStatus":200,"Duration":83208,"GzipRatio":0,"OriginContentSize":0,"OriginDuration":0,"OriginStatus":0,"Overhead":83208,"RequestAddr":"y.y.y.y:9000","RequestContentSize":0,"RequestCount":6350295,"RequestHost":"y.y.y.y","RequestMethod":"GET","RequestPath":"/ping","RequestPort":"9000","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"ping@internal","StartLocal":"2024-03-06T14:40:07.752027527Z","StartUTC":"2024-03-06T14:40:07.752027527Z","entryPointName":"traefik","level":"info","msg":"","request_User-Agent":"kube-probe/1.26+","request_X-B3-Parentspanid":"0b9dc0219337xxx8","request_X-B3-Sampled":"0","request_X-B3-Spanid":"5d596xxb0f617a4b","request_X-B3-Traceid":"0ea3a33fcc34635e0b9dcxxx337cdc8","time":"2024-03-06T14:40:07Z"}
`

### What version of Traefik are you using?

Version:      2.10.5
Codename:     saintmarcelin
Go version:   go1.21.3
Built:        2023-10-11T13:54:02Z
OS/Arch:      linux/arm64

### What is your environment & configuration?

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-public
  namespace: ingress
  labels:
    app.x.com/name: x
spec:
  releaseName: traefik-public
  interval: 5m
  maxHistory: 2
  chart:
    spec:
      chart: traefik
      version: 24.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: tooling
      interval: 10m
  values:
    instanceLabelOverride: traefik-public
    image:
      registry: artifactory.x.com/docker-io-remote
      repository: traefik
      tag: 2.10.5
      pullPolicy: IfNotPresent

    # Enable RBAC
    rbac:
      enabled: true

    # Disable services and create them with Flux instead
    # This allow us to later create both public & private load-balancers pointing to the same Traefik release
    service:
      enabled: false

    # Disable the IngressRoute for the dashboard
    ingressRoute:
      dashboard:
        enabled: false

    # Create a default IngressClass for Traefik
    ingressClass:
      enabled: false

    ## Logs, see https://docs.traefik.io/observability/logs/
    logs:
      general:
        format: json
        level: INFO
      access:
        enabled: true
        format: json
        fields:
          headers:
            names:
              Authorization: redact
              Trace-Parent: keep
              X-B3-TraceId: keep
              X-B3-SpanId: keep
              X-B3-ParentSpanId: keep
              X-B3-Sampled: keep
              X-B3-Flags: keep
              User-Agent: keep

    ## Configure providers, see https://doc.traefik.io/traefik/providers/overview/
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true

    ## Static configuration, see https://docs.traefik.io/reference/static-configuration/cli
    globalArguments:
      - --global.checknewversion
    additionalArguments:
      - --api=true
      - --api.debug=true
      - --api.insecure=true
      - --metrics.prometheus=true
      - --metrics.prometheus.buckets=0.1,0.3,1.2,2.0,5.0
      - --providers.kubernetescrd.labelselector=traefik-public
      - --providers.kubernetescrd.namespaces=app,ingress,security
      - --providers.kubernetescrd.allowCrossNamespace
      - --providers.kubernetescrd.allowexternalnameservices
      - --providers.kubernetesingress.labelselector=traefik-public
      - --providers.kubernetesingress.namespaces=app,ingress,security
      - --providers.kubernetesingress.allowexternalnameservices
      - --entryPoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32,10.0.0.0/8,172.16.0.0/12
      - --entryPoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1/32,10.0.0.0/8,172.16.0.0/12
      - --tracing=true
      - --tracing.serviceName=traefik-public
      - --tracing.zipkin=true
      - --tracing.zipkin.httpEndpoint=xxx
      - --tracing.zipkin.sampleRate=0.01

    # Configure ports
    ports:
      traefik:
        port: 9000
        expose: false
        protocol: TCP
      web:
        port: 8000
        expose: true
        exposedPort: 80
        protocol: TCP
        redirectTo: websecure
      websecure:
        port: 8443
        expose: true
        exposedPort: 443
        protocol: TCP
        tls:
          enabled: false

    ## Configure the deployment
    deployment:
      replicas: 3

      # Gives 30 seconds after the preStop sleep commands for draining TCP connections
      terminationGracePeriodSeconds: 70
      imagePullSecrets:
        - name: x-registry

      # Labels used for cost tracking
      labels:
        app.x.com/name: traefik
      podLabels:
        app.x.com/name: traefik
      lifecycle:
        preStop:
          exec:
            command: [/bin/sh, -c, sleep 40]

    ## Pod disruption budget
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
      minAvailable: 0

    ## Create HorizontalPodAutoscaler object.
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 16
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 80
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 80

    ## Resource request/limits
    resources:
      limits:
        cpu: 1.5
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi

    # Compliancy with security policies
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsGroup: 65532
      runAsUser: 65532
      capabilities:
        drop: [ALL]

    ## Affinity to make Traefik more reliable, by enforcing spread on availability zones
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: topology.kubernetes.io/zone
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - traefik-public

```

Add more configuration information here.
