### ISSUE TITLE
Error with StripPrefix Middleware : `field not found, node: forceSlash`

### ISSUE THREAD

**Issue by TBG-FR** [traefik/traefik#10501]
### Hello there !

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I tried to use the **StripPrefix Middleware**, following the documentation https://doc.traefik.io/traefik/middlewares/http/stripprefix/
Everything looks to work well, however it looks like I can't use the `forceSlash` option. Even tried with `forceslash` (seen in community forum), same issue. I get an error inside Traefik logs every time (see below) telling me `field not found, node: forceSlash`.

### What did you see instead?

```
2024-03-06T10:17:40Z ERR error="field not found, node: forceSlash" container=app-xxx providerName=docker
2024-03-06T10:29:31Z ERR error="field not found, node: forceslash" container=app-xxx providerName=docker
2024-03-06T10:34:58Z ERR error="field not found, node: forceslash" container=app-xxx providerName=docker
2024-03-06T10:35:50Z ERR error="field not found, node: forceSlash" container=app-xxx providerName=docker
```

### What version of Traefik are you using?

```
Version:      3.0.0-beta4
Codename:     beaufort
Go version:   go1.21.3
Built:        2023-10-12T07:53:33Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
  app:
    container_name: app
    image: ...
    restart: unless-stopped
    labels:
      # Traefik - Basic configuration
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`fqdn.com`) || Host(`other.fqdn.com`) && PathPrefix(`/myroute`)"
      - "traefik.http.services.app.loadbalancer.server.port=5000"
      - "traefik.docker.network=gateway"
      # Traefik - Expose service in HTTPS
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"
      # Middleware - Remove '/myroute' from the URL
      - "traefik.http.routers.app.middlewares=app-stripprefix"
      - "traefik.http.middlewares.app-stripprefix.stripprefix.prefixes=/remote"
      - "traefik.http.middlewares.app-stripprefix.stripprefix.forceslash=true"
```

### If applicable, please paste the log output in DEBUG level

Nothing more relevant when switch to DEBUG level log
