### ISSUE TITLE
using forwardAuth + authResponseHeaders drops some original client headers

### ISSUE THREAD

**Issue by parkedwards** [traefik/traefik#10524]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

When testing the `forwardAuth` middleware inside of a router that sends requests to a test `whoami` deployment, I'm noticing that client-provided headers are dropped when using `authResponseHeaders` specifically

Setup:
1. `traefik:v2.11` deployment
2. `traefik/whoami` deployment
3. `forwardAuth` middleware configuration
4. An existing authentication server inside of my environment

When I set up an entrypoint-router-middleware-service chain (config attached), I can verify that the configuration comes up healthily + Traefik is running via the `/dashboard/`

I made Traefik accessible through `localhost:3000`, and curled the path that invokes the `forwardAuth` middleware and resolve to the `whoami` service

```
curl -H 'authorization: bearer <token>' -H 'some-random-header: foobar' localhost:3000/api/health3
```

Assuming the request is routed correctly, I expect two outcomes here:
1. The headers specified in `authResponseHeaders` are set from the authentication server's response
2. The original client headers will be passed through / overwritten if there's a conflict from the authentication server - but they should exist at `whoami`

### What did you see instead?

The request arrives at `whoami` successfully, as it prints the request metadata.  However, I've noticed two things:
1. The headers specified in `authResponseHeaders` (which I verified are passed from the authentication server) are properly set ✅ 
2. The `authorization` and `some-random-header` headers set on the curl are not ❌ 

While testing, I disabled `authResponseHeaders` and noticed that:
1. The authentication server's response headers were NOT forwarded to `whoami` ✅ 
2. The client's headers (`authorization` and `some-random-header` headers) were intact 🤔 

This is very similar to what this user has reported in the community channel
https://community.traefik.io/t/is-authresponseheaders-stripping-headers-or-keeping-them/21571

From the `authResponseHeaders` [documentation](https://doc.traefik.io/traefik/middlewares/http/forwardauth/#authresponseheaders):

> list of headers to **copy from the authentication server response and set on forwarded request, replacing any existing conflicting headers**.

Based on the documentation description, I'm wondering if there is a bug in how the authentication server's header copying is being handled onto the forwarded request, where it is stripping the client's headers only when `authResponseHeaders` is defined

### What version of Traefik are you using?

image: traefik:v2.11

### What is your environment & configuration?

```yaml
# dynamic File configuration

    http:
      # Add the router
      routers:
        whoami:
          entryPoints:
          - web
          middlewares:
          - ext-auth
          service: whoami
          rule: Path(`/api/health3`)

      # Add the middleware
      middlewares:
        ext-auth:
          forwardAuth:
            address: http://auth:4300/
            trustForwardHeader: true
            authRequestHeaders:
              - authorization
              - Origin
              - Access-Control-Request-Method
            authResponseHeaders:
              - authorization
              - x-actor-id
              - some-random-header

      # Add the service
      services:
        whoami:
          loadBalancer:
            servers:
            - url: http://whoami:80
            passHostHeader: false
```

Add more configuration information here.
