### ISSUE TITLE
Logo not working

### ISSUE THREAD

**Issue by onlinejudge95** [traefik/traefik#10528]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Upgrade Docker Image to `v3.0.0-rc3`

### What did you see instead?

I expected the logo to be present since I am running Traefik with a docker swarm provider. Instead, I am seeing a broken image.

![Traefik Bug](https://github.com/traefik/traefik/assets/44158581/33318279-202c-4678-ad5e-4906fbc49d70)

### What version of Traefik are you using?

`v3.0.0-rc3`

### What is your environment & configuration?

```yaml
global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
  websecure:
    address: :443
  postgres:
    address: :5432
  redis:
    address: :6379
  metrics:
    address: :8082

################################################################
# Traefik logs configuration
################################################################
log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"
  format: json

################################################################
# Access logs configuration
################################################################
accessLog:
  filePath: "/var/log/traefik/traefik.access.log"
  format: json

################################################################
# API and dashboard configuration
################################################################
api:
 insecure: false
 dashboard: true

################################################################
# Ping configuration
################################################################

# Enable ping
#ping:
  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
#  entryPoint: traefik

################################################################
# Docker configuration backend
################################################################
providers:
 swarm:
   endpoint: "unix:///var/run/docker.sock"
   defaultRule: "Host(`{{ normalize .Name }}`)"
   exposedByDefault: true
   network: cluster-ingress

################################################################
# Metrics configuraiton
################################################################
metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    entryPoint: metrics
```
