### ISSUE TITLE
PathPrefix RegEx

### ISSUE THREAD

**Issue by Bugs5382** [traefik/traefik#10526]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Dear Dev Team -

I have been working on condensing my IngressRoute "routers," so they are nice and neat when developing my React application. [Issue In Community](https://community.traefik.io/t/pathprefix-regex/21819/7)

To start, as many people know, or don't, react runs on the premise of everything runs off the / path and the react-router does the matching itself of the path in the URL to get to the page. In my app, I use vite, react, react-router, and graphql for a feature set talking to a NodeJS microservice. So for example, in my app:

```ts
/
/list
/queue
/pirnt/[:ID]
/print/list
/assets/[*.js]
/locale/en_US/[*.json]
/locale/en/[*.json]
```

The "URLs" or pages are:

```ts
/
/list
/queue
/pirnt/[:ID]
/print/list
```

and

```ts
/assets/[*.js]
/locale/en_US/[*.json]
/locale/en/[*.json]
```

Hold the "static" content.

In the App design, the frontend is its docker image hosting everything. The static and the dyanmic. It's not two different services. Someone suggested I create a service just to hold the static stuff. I wonder why someone would do this. Below is my Kube YAML for the IngressRoutes:

Note 1: I removed the ports, TLS info, and metadata from the YAML below for ease of clarity.
Note 2: "frontend" is where Nginx runs the html, js, and static. "controller" is the graphql service that federates all the other graphql gateways.

```ts
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
# Removed for cleaner stuff
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.frontend.fqdn }}`) && PathPrefix(`/{path:((assets.*|locales.*))}`) || PathPrefix(`/`)
      services:
        - kind: Service
          name: frontend
    - kind: Rule
      match: Host(`{{ .Values.frontend.fqdn }}`) && !PathPrefix(`/{path:((assets.*|locales.*))}`) && !PathPrefix(`/`)
      middlewares:
        - name: middleware-frontend-replacement-path
      services:
        - kind: Service
          name: frontend

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
# Removed for cleaner stuff
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.frontend.fqdn }}`) && Header(`X-Graphql`, `true`) && PathPrefix(`/graphql`)
      services:
        - kind: Service
          name: controller # This is the graphql
      middlewares:
        - name: middleware-controller-replacement-path
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: middleware-frontend-replacement-path
spec:
  replacePath:
    path: /
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: middleware-controller-replacement-path
spec:
  replacePath:
    path: /graphql
```

So, the regex in the top YAML for the frontend server, I have tested in several regex editor sites it does match all of these:

```ts
/
/assets/[*.js]
/locale/en_US/[*.json]
/locale/en/[*.json]
```

... paths correctly. The reason why / should be included is that this path ```does``` not need any middleware to replace anything.

In the second one, I have ```!``` before PatchPrefix and it should "not" the search for everything else. This is because GoLang Regex does not have a negative match operator. (Why not? Idk.) 

In the 3rd route, I have the same FQDN and the graphql endpoint plus the HTTP header, which is passed on by the client, so that the rule gets hit. And it does work. I had to add /graphql to the middleware because the service runs the graphql on the /graphql path and not the root of the path.

I am welcome to be proved wrong, but again, all my testing shows that Treafik shows it as valid input, but it doesn't seem to work correctly. I welcome being pointed to where this code is, and I can try to fix it myself if it is a bug. If it's a feature, I can work on it with my limited GoLang knowledge that I have been able to understand. (I am still learning.)

Thanks

### What did you see instead?

So this is what I am trying to achieve, but I am getting one working, not the other.

For instance, a user ```http://FQDN/``` loads up all the pages, js files, etc. with no issue, including talking to the graphql endpoint. Depending on what setting I change to get this to work, I can make it so that ```https;//FQDN/list``` does not 404, or is missing from the react logic, but it can't load the assets or js files in ```https://FQDN/assents/some_js_file_here.js ``` come up as not being able to be found. I looked at the ngnix logs and it seems not even to get there.

I tried 50 combos, so this has to be a bug in PathPrefix RegEx. I know this would it work if ifI put all possible paths like:

* PathPrefix(`/list`) PAthPrefix(`/queue`) PAthPrefix(`/print/{path:(.*)}`) PAthPrefix(`/print`) 

... in for every endpoint, but this could take a long time for a more elegant application.

### What version of Traefik are you using?

3.0.0 RC1

### What is your environment & configuration?

```yaml
additionalArguments:
- --serversTransport.insecureSkipVerify=true
- --log.level=DEBUG
additionalVolumeMounts: []
affinity: {}
autoscaling:
  enabled: false
certResolvers: {}
commonLabels: {}
deployment:
  additionalContainers: []
  additionalVolumes: []
  annotations: {}
  dnsConfig: {}
  enabled: true
  imagePullSecrets: []
  initContainers: []
  kind: Deployment
  labels: {}
  lifecycle: {}
  minReadySeconds: 0
  podAnnotations: {}
  podLabels: {}
  replicas: 1
  shareProcessNamespace: false
  terminationGracePeriodSeconds: 60
env:
- name: POD_NAME
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
- name: POD_NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
envFrom: []
experimental:
  kubernetesGateway:
    enabled: false
  plugins: {}
extraObjects: []
globalArguments:
- --global.sendanonymoususage=false
- --global.checknewversion=false
hostNetwork: false
image:
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: traefik
  tag: v3.0.0-rc1
ingressClass:
  enabled: true
  isDefaultClass: true
ingressRoute:
  dashboard:
    annotations: {}
    enabled: false
    entryPoints:
    - traefik
    labels: {}
    matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    middlewares: []
    tls: {}
  healthcheck:
    annotations: {}
    enabled: false
    entryPoints:
    - traefik
    labels: {}
    matchRule: PathPrefix(`/ping`)
    middlewares: []
    tls: {}
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 2
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2
logs:
  access:
    enabled: false
    fields:
      general:
        defaultmode: keep
        names: {}
      headers:
        defaultmode: drop
        names: {}
    filters: {}
  general:
    level: DEBUG
metrics:
  prometheus:
    entryPoint: metrics
nodeSelector: {}
persistence:
  accessMode: ReadWriteOnce
  annotations: {}
  enabled: false
  name: data
  path: /data
  size: 128Mi
podDisruptionBudget:
  enabled: false
podSecurityContext:
  fsGroupChangePolicy: OnRootMismatch
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
podSecurityPolicy:
  enabled: false
ports:
  metrics:
    expose: false
    exposeInternal: false
    exposedPort: 9100
    port: 9100
    protocol: TCP
  traefik:
    expose: false
    exposeInternal: false
    exposedPort: 9000
    port: 9000
    protocol: TCP
  web:
    expose: true
    exposeInternal: false
    exposedPort: 80
    port: 8000
    protocol: TCP
    redirectTo:
      port: websecure
      priority: 10
  websecure:
    expose: true
    exposeInternal: false
    exposedPort: 443
    http3:
      enabled: false
    middlewares: []
    port: 8443
    protocol: TCP
    tls:
      certResolver: ""
      domains: []
      enabled: true
      options: ""
priorityClassName: ""
providers:
  file:
    content: ""
    enabled: false
    watch: true
  kubernetesCRD:
    allowCrossNamespace: false
    allowEmptyServices: false
    allowExternalNameServices: true
    enabled: true
    ingressClass: traefik-external
    namespaces: []
  kubernetesIngress:
    allowEmptyServices: false
    allowExternalNameServices: false
    enabled: true
    namespaces: []
    publishedService:
      enabled: false
rbac:
  enabled: true
  namespaced: false
readinessProbe:
  failureThreshold: 1
  initialDelaySeconds: 2
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2
resources: {}
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
service:
  annotations: {}
  annotationsTCP: {}
  annotationsUDP: {}
  enabled: true
  externalIPs: []
  labels: {}
  loadBalancerIP: 172.22.0.2
  loadBalancerSourceRanges: []
  single: true
  spec: {}
  type: LoadBalancer
serviceAccount:
  name: ""
serviceAccountAnnotations: {}
tlsOptions: {}
tlsStore: {}
tolerations: []
topologySpreadConstraints: []
tracing: {}
updateStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate
volumes: []

```

Add more configuration information here.

**Comment by youkoulayley** [comment]
Hi @Bugs5382,

Thanks for your interest in Traefik!

`PathPrefix` doesn't support regexp in v3, you have to use `PathRegexp` to use regexp now (https://doc.traefik.io/traefik/v3.0/routing/routers/#path-pathprefix-and-pathregexp).

Here's how I rewrote your IngressRoute for my test (I focused exclusively on the frontend part on my tests and used two different `whoami` to see if the routing seems correct):

```yaml
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`toto.localhost`) && (PathRegexp(`^/((assets.*|locales.*))`) || Path(`/`))
      services:
        - kind: Service
          name: whoami1
          port: 80
    - kind: Rule
      match: Host(`toto.localhost`) && (!PathRegexp(`^/((assets.*|locales.*))`) && !Path(`/`))
      middlewares:
        - name: middleware-frontend-replacement-path
      services:
        - kind: Service
          name: whoami2
          port: 80
  
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: middleware-frontend-replacement-path
spec:
  replacePath:
    path: /
```

I replaced the `PathPrefix` by `PathRegexp`, and changed the `PathPrefix('/')` by a strict `Path('/')` because the it would match everything so it sounded weird (but maybe I'm wrong here).

<details><summary>Details</summary>
<p>

```shell
❯ curl -k https://toto.localhost:8443
Hostname: whoami1-7b6f7cbc7f-jw8zx
IP: 127.0.0.1
IP: ::1
IP: 10.42.0.13
IP: fe80::c848:baff:fe52:9201
RemoteAddr: 10.42.0.12:48320
GET / HTTP/1.1
Host: toto.localhost:8443
User-Agent: curl/8.4.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 127.0.0.1
X-Forwarded-Host: toto.localhost:8443
X-Forwarded-Port: 8443
X-Forwarded-Proto: https
X-Forwarded-Server: traefik-564cdb4977-4sz4h
X-Real-Ip: 127.0.0.1


❯ curl -k https://toto.localhost:8443/assets/test.js
Hostname: whoami1-7b6f7cbc7f-jw8zx
IP: 127.0.0.1
IP: ::1
IP: 10.42.0.13
IP: fe80::c848:baff:fe52:9201
RemoteAddr: 10.42.0.12:48320
GET /assets/test.js HTTP/1.1
Host: toto.localhost:8443
User-Agent: curl/8.4.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 127.0.0.1
X-Forwarded-Host: toto.localhost:8443
X-Forwarded-Port: 8443
X-Forwarded-Proto: https
X-Forwarded-Server: traefik-564cdb4977-4sz4h
X-Real-Ip: 127.0.0.1


❯ curl -k https://toto.localhost:8443/locales/test.js
Hostname: whoami1-7b6f7cbc7f-jw8zx
IP: 127.0.0.1
IP: ::1
IP: 10.42.0.13
IP: fe80::c848:baff:fe52:9201
RemoteAddr: 10.42.0.12:48320
GET /locales/test.js HTTP/1.1
Host: toto.localhost:8443
User-Agent: curl/8.4.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 127.0.0.1
X-Forwarded-Host: toto.localhost:8443
X-Forwarded-Port: 8443
X-Forwarded-Proto: https
X-Forwarded-Server: traefik-564cdb4977-4sz4h
X-Real-Ip: 127.0.0.1


❯ curl -k https://toto.localhost:8443/list
Hostname: whoami2-5f74765f4-cxhrn
IP: 127.0.0.1
IP: ::1
IP: 10.42.0.14
IP: fe80::9460:5bff:fe70:f36f
RemoteAddr: 10.42.0.12:53922
GET / HTTP/1.1
Host: toto.localhost:8443
User-Agent: curl/8.4.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 127.0.0.1
X-Forwarded-Host: toto.localhost:8443
X-Forwarded-Port: 8443
X-Forwarded-Proto: https
X-Forwarded-Server: traefik-564cdb4977-4sz4h
X-Real-Ip: 127.0.0.1
X-Replaced-Path: /list
```

</p>
</details> 

It seems to work nicely with this configuration.
If you have any other issues with the rules, don't hesitate to check the [migration guide](https://doc.traefik.io/traefik/v3.0/migration/v2-to-v3/#dynamic-configuration).

If this works for you, I will close the issue.
