### ISSUE TITLE
Support ability to set a specific redirect status in RedirectRegex

### ISSUE THREAD

**Issue by GeorgeMac** [traefik/traefik#10533]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

It would be awesome to control explicitly which (redirect appropriate) status code is returned via RedirectRegex:
https://doc.traefik.io/traefik/master/middlewares/http/redirectregex/

My usecase is that I specifically want to return a 302 (See Other) on a `PUT` request.
The purpose is to force my downstream user agent to switch to a GET on the redirect.

I see in the code it currenty makes some sensible, yet hard coded paths:
https://github.com/traefik/traefik/blob/c1ef7429771104e79f2e87b236b21495cb5765f0/pkg/middlewares/redirect/redirect.go#L93-L103

I would also be open to contributing this myself. However, I wanted to check if this is something folks would be happy with before taking a stab at it.

## Suggestion

Something like:
```yaml
# Redirect with domain replacement
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: test-redirectregex
spec:
  redirectRegex:
    status: 302 # or "see other" or similar, constrained to redirect appropriate range (3XX)
    regex: ^http://localhost/(.*)
    replacement: http://mydomain/${1}
```
