### ISSUE TITLE
Traefik does not forward on bridge network when also attached to ipvlan

### ISSUE THREAD

**Issue by mlamoure** [traefik/traefik#10537]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Configuration works perfectly if I remove the ipvlan from the traefik container, correctly forwarding to containers on the bridge network that have been configured.

When adding to the ipvlan network, and specifying in my traefik configuration:

`"traefik.docker.network=lab_net"`

Via command: docker network inspection lab_net, I can see that the containers are on the bridge network properly, but accessing via the host rule URL does not forward to the container. 

I've tried placing the network configuration configuration as a command, trafeik label, provider, and in the container config.  

### What did you see instead?

Trafeik does not forward to the bridge container hosts.

### What version of Traefik are you using?

Version:      2.11.0
Codename:     cheddar
Go version:   go1.22.0
Built:        2024-02-12T15:26:45Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
version: "3.3"

services:

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.domains[0].main=${DOMAIN_NAME}"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN_NAME}"

      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=route53"
#      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.disablepropagationcheck=true"
    networks:
      ipvlan_net:
        ipv4_address: 10.66.0.223
      lab_net:
    ports:
      - "80:80"
      - "443:443"
#      - "8080:8080"
    environment:
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
      - "AWS_HOSTED_ZONE_ID=${AWS_HOSTED_ZONE_ID}"
      - "AWS_POLLING_INTERVAL=15"
      - "AWS_PROPAGATION_TIMEOUT=900"
      - "TZ=${TZ}"
    volumes:
      - "./traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=lab_net"

      # HTTP Redirect
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik-dashboard.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080"
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - lab_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "WATCHTOWER_NOTIFICATIONS=email"
      - "WATCHTOWER_NOTIFICATION_EMAIL_FROM=${EMAIL}"
      - "WATCHTOWER_NOTIFICATION_EMAIL_TO=${EMAIL}"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SMTP_SERVER}"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${SMTP_PORT}"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${SMTP_USERNAME}"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${SMTP_PASSWORD}"

networks:
  ipvlan_net:
    name: 'ipvlan_net'
    driver: ipvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
      - subnet: "10.66.0.0/24"
        gateway: "10.66.0.1"

  lab_net:
    name: 'lab_net'
    driver: bridge

volumes:
  portainer_data:
```

Add more configuration information here.
