### ISSUE TITLE
middleware \"biz4000018p-svc-id4qrkl6hbe1c331oj6e@kubernetescrd\" does not exist

### ISSUE THREAD

**Issue by ruidanwang** [traefik/traefik#10544]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

log said middleware \"biz4000018p-svc-id4qrkl6hbe1c331oj6e@kubernetescrd\" does not exist but the actual situation is that when I refresh the page, I can open my target address.

### What did you see instead?

page 404 error

### What version of Traefik are you using?

2.11.0

### What is your environment & configuration?

```yaml
Name:         svc-id4qrkl6hbe1c331oj6e
Namespace:    biz4000018p
Labels:       <none>
Annotations:  <none>
API Version:  traefik.io/v1alpha1
Kind:         Middleware
Metadata:
  Creation Timestamp:  2024-03-27T02:42:50Z
  Generation:          1
  Resource Version:    42906418
  UID:                 8a827511-1823-4573-84a4-6f175d1301e0
Spec:
  Ip Allow List:
    Source Range:
      172.16.220.148
Events:  <none>
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

time="2024-03-27T02:42:50Z" level=error msg="middleware \"biz4000018p-svc-id4qrkl6hbe1c331oj6e@kubernetescrd\" does not exist" entryPointName=jupyter routerName=biz4000018p-svc-id4qrkl6hbe1c331oj6e-6f44e90bab462158646f@kubernetescrd
