### ISSUE TITLE
documented usage of excludedIPs with IPAllowList middleware

### ISSUE THREAD

**Issue by mloiseleur** [traefik/traefik#10549]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I tried to exclude an IP on Kubernetes with an IngressRoute + IPAllowList middleware following [this documentation](https://doc.traefik.io/traefik/middlewares/http/ipallowlist/#ipstrategyexcludedips):
![image](https://github.com/traefik/traefik/assets/97035654/605735e3-b753-4192-9310-881a49f07eed)

### What did you see instead?

The middleware was rejected with this message showed in the dashboard:
![image](https://github.com/traefik/traefik/assets/97035654/87be1a00-0870-4344-a4c1-619dbce38d5a)

### What version of Traefik are you using?

2.11.0

### What is your environment & configuration?

<details>
<summary>Example deployment with whoami</summary>
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: traefik/whoami
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: whoami
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: protect
spec:
  ipAllowList:
    ipStrategy:
      excludedIPs:
        - 10.244.0.6/32
--- 
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`whoami.docker.localhost`) 
    kind: Rule
    middlewares:
    - name: protect
    services:
    - name: whoami
      port: 80
```
</details>

### If applicable, please paste the log output in DEBUG level

```shell
time="2024-03-27T10:53:59Z" level=error msg="sourceRange is empty, IPAllowLister not created" entryPointName=web routerName=default-whoami-d027988890c9025cffce@kubernetescrd
```
