### ISSUE TITLE
Routing syntax in v3.0.0-rc3 is not backwards compatible

### ISSUE THREAD

**Issue by lhns** [traefik/traefik#10542]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I migrated a route ```Host(`example.com`) && Path(`/test{path:(/.*)?}`)``` to v3.0.0-rc3 and it is not working anymore.
I configured traefik to use the legacy syntax:
```yml
core:
  defaultRuleSyntax: v2
```

### What did you see instead?

Traefik doesn't match the route and returns 404.

### What version of Traefik are you using?

v3.0.0-rc3

### What is your environment & configuration?

```yaml
core:
  defaultRuleSyntax: v2

entryPoints:
  web:
    address: ":80"

providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik_web
```
