### ISSUE TITLE
Traefik api access not logged

### ISSUE THREAD

**Issue by Morriz** [traefik/traefik#10570]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have working access logs showing all requests to endpoints, but requests to the Traefik dashboard are omitted

### What did you see instead?

requests to the Traefik dashboard are not logged

### What version of Traefik are you using?

Version:      3.0.0-rc3
Codename:     beaufort
Go version:   go1.22.1
Built:        2024-03-13T15:49:38Z
OS/Arch:      linux/arm64

### What is your environment & configuration?

```yaml
accessLog:
  filePath: /var/log/traefik/access.log
  format: json
log:
  # level: INFO
  level: DEBUG
```

Add more configuration information here.
