### ISSUE TITLE
File provider in 2.11.0 fails to load configuration entirely

### ISSUE THREAD

**Issue by enticedwanderer** [traefik/traefik#10573]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I run traefik in docker. I have upgraded Traefik image (official) from 2.10.4 -> 2.11.0 with existing configuration without any changes. Most of my docker compose projects rely on middleware defined in a file config supplied by the file provider. Rolling back to 2.10.4 restores the functionality fully.

### What did you see instead?

After upgrading when traefik starts in the logs I see:

```
traefik  | time="2024-04-05T23:14:47-04:00" level=info msg="Configuration loaded from file: /etc/treafik/traefik.yml"
traefik  | time="2024-04-05T23:14:47-04:00" level=info msg="Traefik version 2.11.0 built on 2024-02-12T15:26:45Z"
traefik  | time="2024-04-05T23:14:47-04:00" level=info msg="Stats collection is enabled."
traefik  | time="2024-04-05T23:14:47-04:00" level=info msg="Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration."
traefik  | time="2024-04-05T23:14:47-04:00" level=info msg="Help us improve Traefik by leaving this feature on :)"
traefik  | time="2024-04-05T23:14:47-04:00" level=info msg="More details on: https://doc.traefik.io/traefik/contributing/data-collection/"
traefik  | time="2024-04-05T23:14:47-04:00" level=warning msg="Traefik Pilot has been removed."
traefik  | time="2024-04-05T23:14:47-04:00" level=info msg="Starting provider aggregator aggregator.ProviderAggregator"
traefik  | time="2024-04-05T23:14:47-04:00" level=info msg="Starting provider *file.Provider"
traefik  | time="2024-04-05T23:14:47-04:00" level=error msg="Cannot start the provider *file.Provider: error adding file watcher: no such file or directory"
traefik  | time="2024-04-05T23:14:47-04:00" level=info msg="Starting provider *traefik.Provider"
traefik  | time="2024-04-05T23:14:47-04:00" level=info msg="Starting provider *acme.ChallengeTLSALPN"
traefik  | time="2024-04-05T23:14:47-04:00" level=info msg="Starting provider *docker.Provider"
traefik  | time="2024-04-05T23:14:47-04:00" level=info msg="Starting provider *acme.Provider"
traefik  | time="2024-04-05T23:14:47-04:00" level=info msg="Testing certificate renew..." ACME CA="https://acme-v02.api.letsencrypt.org/directory" providerName=public.acme
traefik  | time="2024-04-05T23:14:47-04:00" level=info msg="Starting provider *acme.Provider"
traefik  | time="2024-04-05T23:14:47-04:00" level=info msg="Testing certificate renew..." providerName=internal.acme ACME CA="https://step-ca:9000/acme/home.lan/directory"
```

Followed by a bunch of entries like the following (and all of the services being down/unreachable):

```
...
traefik  | time="2024-04-05T23:14:48-04:00" level=error msg="middleware \"secured-fauth@file\" does not exist" routerName=autobrr@docker entryPointName=web
traefik  | time="2024-04-05T23:14:48-04:00" level=error msg="middleware \"secured@file\" does not exist" routerName=rss-bridge@docker entryPointName=web
traefik  | time="2024-04-05T23:14:48-04:00" level=error msg="middleware \"secured@file\" does not exist" entryPointName=web routerName=numblr@docker
traefik  | time="2024-04-05T23:14:48-04:00" level=error msg="middleware \"secured@file\" does not exist" entryPointName=web routerName=kiwix@docker
traefik  | time="2024-04-05T23:14:48-04:00" level=error msg="middleware \"secured@file\" does not exist" routerName=filebrowser@docker entryPointName=web
traefik  | time="2024-04-05T23:14:48-04:00" level=error msg="middleware \"secured@file\" does not exist" routerName=twitch-api@docker entryPointName=web
...
```

Notice specifically:
```
Cannot start the provider *file.Provider: error adding file watcher: no such file or directory
```

However I have confirmed that the files are indeed present in the expected location within the traefik container.

### What version of Traefik are you using?

alex@dockerino:/docker/config/traefik# docker run --rm traefik:2.11.0 version
Version:      2.11.0
Codename:     cheddar
Go version:   go1.22.0
Built:        2024-02-12T15:26:45Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

This is running in a docker environment on a ubuntu server 22.04 LTS. Docker version 25.0.4, build 1a576c5

# Traefik config
```yaml
#traefik.yml#

log:
  level: "INFO"

# tracing: {}
entryPoints:
  web:
    address: ":80"
    # http:
      # middlewares:
      #   - secured
  web-secure:
    address: ":443"
    http3: {}
    http:
      tls:
        certResolver: internal
      # middlewares:
      #  - secured
  ssh:
    address: ":2222"

api:
  dashboard: true
  insecure: false

pilot:
  dashboard: false

providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
    network: "traefik-network"
    exposedByDefault: false
    defaultRule: "Host(`{{ .Name }}.home.lan`)"
  file:
    directory: /conf/traefik/
    watch: true

certificatesResolvers:
  internal:
    acme:
      email: "<redacted>"
      storage: "/etc/traefik/acme/acme.json"
      caServer: "https://step-ca:9000/acme/home.lan/directory"
      httpChallenge:
        entryPoint: web
  public:
    acme:
      email: "<redacted>"
      storage: "/etc/traefik/acme/public.json"
      dnsChallenge:
        provider: <redacted>

# Log errors
accessLog:
  filePath: "/var/traefik-logs/errors.log"
  format: json
  filters:
    statusCodes:
      - "400-450"
      - "500-550"

metrics:
  prometheus: {}

experimental:
  http3: true
```

# Docker compose for traefik
```yaml
version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:2.10.4
    container_name: "traefik"
    command: --configfile=/etc/treafik/traefik.yml
    restart: always
    ports:
      # The HTTP port
      - "10.0.10.6:80:80"
      # The HTTPS port
      - "10.0.10.6:443:443"
      # The HTTP/3 port
      - "10.0.10.6:443:443/udp"
      # SSH access for gitea
      - "10.0.10.6:2222:2222"
      # The Web UI (enabled by --api.insecure=true)
      - "10.0.10.6:8080:8080"
    environment:
      # Patch the CA cert store for Go to use internal CA trust
      - LEGO_CA_CERTIFICATES=/etc/ssl/certs/ca-certificates.crt
      # ... other LEGO credentials here ...
      - TZ=America/New_York
    volumes:
      # So that Traefik can listen to the Docker events...
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/treafik/traefik.yml:ro
      - ./dynamic-conf:/conf/traefik:ro
      - ./logs:/var/traefik-logs/
      - ./certs/:/certs/
      - ./acme/acme.json:/etc/traefik/acme/acme.json
      - ./acme/public.json:/etc/traefik/acme/public.json
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.home.lan`)
      - traefik.http.routers.traefik.entrypoints=web,web-secure
      - traefik.http.routers.traefik.middlewares=secured@file
      - traefik.http.routers.traefik.service=api@internal
      - wud.watch=true
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.link.template=https://github.com/traefik/traefik/releases/tag/v$${major}.$${minor}.$${patch}
      - prometheus.job=traefik
      - prometheus.port=8080
networks:
  default:
    name: "traefik-network"
    external: true
```

# Extra traefik conf to be loaded by file provider

```bash
alex@dockerino:/docker/config/traefik# ls dynamic-conf/
certs.yml  client-mtls.yml  kopia-backend.crt  middlewares.yml
```

`middlewares.yml` defines `secured@file` and the likes. Docker compose should map that whole folder to `/conf/traefik` which I have confirmed it does via `docker exec reverse-proxy ash`.
