### ISSUE TITLE
v2.11.1 breaks file upload in some cases - related to PR #10569 (with solution described)

### ISSUE THREAD

**Issue by wollomatic** [traefik/traefik#10595]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

The issue seems to be related to https://github.com/traefik/traefik/pull/10569

We have an internal app based on SvelteKit. With traefik v2.11.0 everything works, but updating to v2.11.1 breaks the file upload.

We could get it solved by increasing the `transport.respondingTimeouts.tcp.lingeringTimeout` (see configuration below). Maybe the default of 2s is a bit too low.

### What did you see instead?

With traefik v2.11.1, the file upload breaks and traefik logs `level=debug msg="'499 Client Closed Request' caused by: context canceled"`

### What version of Traefik are you using?

```
Version:      2.11.1
Codename:     mimolette
Go version:   go1.22.2
Built:        2024-04-10T09:58:54Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

Entrypoint before (breaks):
```yaml
entryPoints:
  web:
    # [...]
  web-secure:
    address: ':10443'
    http:
      encodeQuerySemicolons: true
```

Entrypoint after (works again)
```yaml
entryPoints:
  web:
    # [...]
  web-secure:
    address: ':10443'
    transport:
      respondingTimeouts:
        tcp:
          lingeringTimeout: 30
    http:
      encodeQuerySemicolons: true
```

Traefik runs on a default linux webserver with docker compose, similar to this example: https://github.com/wollomatic/traefik-hardened

### If applicable, please paste the log output in DEBUG level

`level=debug msg="'499 Client Closed Request' caused by: context canceled"`
