### ISSUE TITLE
v2.11.1 regression. Websocket fail after 2-3 seconds with Code 1006

### ISSUE THREAD

**Issue by apollo13** [traefik/traefik#10601]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Upgraded to Traefik 2.11.1 and started websockets to my home assistant installation fail after 2-3 seconds. Downgrading to 2.11.0 fixes it

### What did you see instead?

Reopening of websockets after 2-3 seconds

### What version of Traefik are you using?

Version:      2.11.0
Codename:     cheddar
Go version:   go1.22.0
Built:        2024-02-12T15:26:45Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
http:
  services:
    hass:
      loadBalancer:
        serversTransport: hass
        servers:
        - url: http://127.0.0.1:8123/

  routers:
    hass:
      rule: "Host(`daisy.xxx.eu`) || Host(`hass.xxx.eu`)"
      service: hass
      tls:
        certResolver: le
        domains: [daisy.xxx.eu, hass.xxx.eu]

  serversTransports:
    hass:
      insecureSkipVerify: true

```

```yaml
global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  websecure:
    address: ":443"

certificatesResolvers:
  le:
    acme:
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

providers:
  file:
    filename: /etc/traefik/services.yml

#log:
#  level: DEBUG
#
#accessLog: {}

```
