### ISSUE TITLE
Significantly higher CPU usage in v2.11.1

### ISSUE THREAD

**Issue by clambin** [traefik/traefik#10606]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I upgraded to v2.11.1 and saw a dramatic increase in CPU usage.  See attached.   Possibly this is related to #10598?

### What did you see instead?

Avg CPU shot up from .2% to 8%.

<img width="994" alt="Screenshot 2024-04-11 at 20 37 04" src="https://github.com/traefik/traefik/assets/59534649/d7cc604f-7ed2-4088-94b1-f7652c15feeb">

### What version of Traefik are you using?

docker.io/traefik:v2.11.1

### What is your environment & configuration?

```yaml
deployment:
  podLabels:
    app: "traefik"
ingressClass:
  enabled: true
experimental:
  enabled: true
providers:
  kubernetesCRD:
    allowCrossNamespace: true
    namespaces:
       - ...
  kubernetesIngress:
    namespaces:
       - ...
    publishedService:
      enabled: true
logs:
  access:
    enabled: true
  fields:
    headers:
      defaultmode: keep
    names:
      StartUTC: drop
env:
  - name: TZ
    value: Europe/Brussels
additionalArguments:
  - --entrypoints.websecure.http.tls.certresolver=letsencrypt
  - --certificatesresolvers.letsencrypt.acme.email=christophe.lambin@gmail.com
  - --certificatesresolvers.letsencrypt.acme.storage=/data/letsencrypt/acme.json
  - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
  - --api.insecure=true
  - --api.dashboard=true
ports:
  traefik:
    expose:
      default: true
  websecure:
    tls:
      enabled: true
      certResolver: letsencrypt
persistence:
  enabled: true
  existingClaim: pvc-traefik
```
