### ISSUE TITLE
replacePathRegex doesn't work as expected

### ISSUE THREAD

**Issue by AntonKun** [traefik/traefik#10613]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I tried to make a redirect that would remove /en from the path:

```yaml
    en-redirect-regex:
      replacePathRegex:
        regex: "^/en(/(.*))?$"
        replacement: "/$2"
```

It should work like this:

```
1. https://my-domain/en -> https://my-domain
2. https://my-domain/en/ -> https://my-domain
3. https://my-domain/en/any/path -> https://my-domain/any/path
4. https://my-domain/en/any/path/ -> https://my-domain/any/path
```

### What did you see instead?

But I noticed that point 3 doesn't work for some reason. Now it works like this:

```
https://my-domain/en/any/path -> https://my-domain/en/any/path
```

In case `https://my-domain/en/any/path` **replacePathRegex.regex**:`^/en(/(.*))?$` should corresponds to `/en/any/path` and **replacePathRegex.replacement**:`/$2` should corresponds to `/any/path`.

And one more interesting thing, if I change **replacePathRegex.replacement** to `/$1` it works properly. But why? Is it a bug?

### What version of Traefik are you using?

Version:      2.11.1
Codename:     mimolette
Go version:   go1.22.2
Built:        2024-04-10T09:58:54Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305

http:
  middlewares:
    securityHeaders:
      headers:
        stsSeconds: 31536000
    en-redirect-regex:
      replacePathRegex:
        regex: "^/en(/(.*))?$"
        replacement: "/$1"

```

**Comment by ldez** [comment]
Hello,

I'm not able to reproduce your issue:

<details>
<summary>dynamic configuration</summary>

```yml
http:
  middlewares:
    en-redirect-regex:
      replacePathRegex:
        regex: "^/en(/(.*))?$"
        replacement: "/$2"
  routers:
    example:
      rule: "PathPrefix(`/`)"
      service: foo
      middlewares:
        - en-redirect-regex
  services:
    foo:
      loadBalancer:
        servers:
          - url: http://localhost:9092
```

</details>

<details>
<summary>static configuration</summary>

```yml
providers:
  file:
    directory: ./temp/

entryPoints:
  web:
    address: :9090
```

</details>

```console
$ curl http://localhost:9090/en/any/path 
IP: 127.0.0.1
IP: ::1
RemoteAddr: [::1]:38028
GET /any/path HTTP/1.1 ## <------------------
Host: localhost:9090
User-Agent: curl/8.6.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: ::1
X-Forwarded-Host: localhost:9090
X-Forwarded-Port: 9090
X-Forwarded-Proto: http
X-Real-Ip: ::1
X-Replaced-Path: /en/any/path
```

```console
$ curl http://localhost:9090/en/any/path/
IP: 127.0.0.1
IP: ::1
RemoteAddr: [::1]:44142
GET /any/path/ HTTP/1.1 ## <------------------
Host: localhost:9090
User-Agent: curl/8.6.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: ::1
X-Forwarded-Host: localhost:9090
X-Forwarded-Port: 9090
X-Forwarded-Proto: http
X-Real-Ip: ::1
X-Replaced-Path: /en/any/path/
```
