### ISSUE TITLE
Ipwhitelist with error middleware

### ISSUE THREAD

**Issue by bdoublet91** [traefik/traefik#10616]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hi,

I want to create a maintenance mode with ipwhitelist middleware and error middleware like my service returns a 403 forbidden like that gets caugth by error middleware:
<img width="942" alt="image" src="https://github.com/traefik/traefik/assets/57101863/c5da1936-4a0d-43a4-9284-095d7e6b8e5e">

FROM CLIENT:
1. A client try to get our dashboard -> whitelist IP get a 403 forbiden
2. The 403 forbiden is caugth by our error service and return an html maintenance page with css

FROM Admin:
I set up a VPN to bypass whitelist IP and access to the full application

If I change the middleware order -> get 403 forbiden with no error_page
If I use chain middleware -> get 403 forbiden with no error_page

I saw some discussion about that:
https://community.traefik.io/t/combine-ipwhitelist-and-errors-middlewares-is-it-possible/13381

Just I want to know if it's possible to combine whitelistIP and error middleware and maybe what I did wrong to load html but not the css ...

### What did you see instead?

FROM CLIENT:
1. A client try to get our dashboard -> whitelist IP get a 403 forbiden
2. The 403 forbiden is caugth by our error service and return an html maintenance page
-> That works but all content is not loaded (css gets blocked)

FROM Admin:
I set up a VPN to bypass whitelist IP and access to the full application

If I change the middleware order -> get 403 forbiden with no error_page
If I use chain middleware -> get 403 forbiden with no error_page

<img width="960" alt="image" src="https://github.com/traefik/traefik/assets/57101863/6a8fa82e-cd23-4325-8e61-4faf2155e12f">

### What version of Traefik are you using?

traefik 2.10.1

### What is your environment & configuration?

```yml

global:
  sendAnonymousUsage: false
  checkNewVersion: false
  #insecureSNI: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      middlewares:
        - SecHeaders@file
      tls:
        certResolver: letsencrypt
        domains:
          - main: "${PUBLIC_DOMAIN}"
            sans:
              - "*.${PUBLIC_DOMAIN}"
        options: security
  metrics:
    address: :8082

ping:
  manualRouting: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${EMAIL}
#      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: /certificate/acme/acme.json
      keyType: EC256
      dnsChallenge:
        provider: ovh
        delayBeforeCheck: 10
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
      #httpChallenge:
      #  entryPoint: foobar

api:
  #insecure: true
  dashboard: true
  debug: false

log:
  #filePath: "/etc/traefik/applog.log"
  level: INFO
  format: json

accessLog:
  filePath: "/var/log/traefik-access.log"
  format: json

providers:
  docker:
    endpoint: http://dockersocket:2375
    exposedByDefault: false
    watch: true
    swarmMode: true
    network: traefik-public
    constraints: "Label(`traefik.external`, `true`)"
  file:
    directory: /etc/traefik/dynamic-conf/
    watch: true

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    entryPoint: metrics
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
```

**Comment by rtribotte** [comment]
Hello @bdoublet91,

Thank you for your interest in Traefik!

Currently, the error middleware in Traefik is designed to handle only a single response, typically serving a simple error page. This limitation means that it cannot directly serve associated resources such as CSS files needed for styling the error page.

To achieve the desired functionality of serving associated resources (like CSS), you can use a dedicated router to serve these static files.

Here is an example of how you can configure Traefik to serve static files using a dedicated router:

```yaml

http:
  routers:
    # Define the main router that uses the error middleware
    my-router:
      rule: "Host(`example.com`)"
      service: my-service
      middlewares:
        - error-pages
    # Define a router for serving static files (CSS)
    static-files-router:
      rule: "Host(`example.com`) && PathPrefix(`/static/`)"
      service: static-file-server

  services:
    my-service:
      loadBalancer:
        servers:
          - url: "http://your-app"

    static-file-server:
      loadBalancer:
        servers:
          - url: "http://your-static-file-server"

    error-service:
      loadBalancer:
        servers:
          - url: "http://your-error-page-server"

  middlewares:
    error-pages:
      errors:
        status:
          - "400-599"
        service: error-service
        query: "/error.html"

```
In this example:

    my-router is your main router that includes the error middleware.
    static-files-router is the router handling requests for static files, such as CSS.
    The static files are served from http://your-static-file-server/static/.

This way, you can ensure that your error pages can reference and utilize external CSS files.

The GitHub issue tracker is dedicated to bug and feature requests.
For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik). 

We will close this issue accordingly but feel free to re-open it if you think that we missed something.
