### ISSUE TITLE
Latest is still 2.11.1

### ISSUE THREAD

**Issue by zackmuc** [traefik/traefik#10617]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Set docker compose to traefik:latest but still get 2.11.1 instead of 2.11.2

### What did you see instead?

2.11.1

### What version of Traefik are you using?

2.11.1

### What is your environment & configuration?
```yml
 traefik:
    depends_on:
      - authelia
    image: traefik:2.11.2
    container_name: traefik
    restart: always
    command:
```
### If applicable, please paste the log output in DEBUG level

2.11.1
