### ISSUE TITLE
ServersTransport should fallback to static/default config for unspecified values

### ISSUE THREAD

**Issue by cpboyd** [traefik/traefik#10612]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I've loaded my custom root CAs using the static config by adding this to the Helm values:
```yaml
additionalArguments:
  - "--serverstransport.rootcas=/vault/secrets/ca.crt"
 ```

However, since I don't define IP SANs (and Traefik doesn't seem to support SNI for Kubernetes service addresses like `service.namespace.svc`), I still have to use a custom `ServersTransport`.

With the custom `ServersTransport`, I would expect that the static/default root CA would still be expected unless overridden. However, I still get an error about the certificate (confirmed by checking the `DEBUG` logs) unless I also specify `rootCAsSecrets` (which also requires that I create a certificate with the CA).

An alternative might be to support `rootCAs` in the dynamic config with a local file path, since I've already got the file on my Traefik instances.

**Comment by nmengin** [comment]
Hey @cpboyd,

Thanks for reaching out.

Could you be more accurate and provide a minimal reproducible case (for instance, full Kubernetes manifest to reproduce the issue)?

**Comment by cpboyd** [comment]
With just the Helm values:
```
additionalArguments:
  - "--serverstransport.rootcas=/vault/secrets/ca.crt"
```
And `IngressRoute`:
```
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ${service}
  namespace: ${namespace}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`${service}.example.com`)
      priority: 0
      services:
        - name: ${service}
          port: 8080
```
As referenced on #4835, the error due to lacking IP SANs shows:
```json
{"level":"debug","msg":"'500 Internal Server Error' caused by: tls: failed to verify certificate: x509: cannot validate certificate for 172.8.9.191 because it doesn't contain any IP SANs","time":"2024-04-16T01:52:32Z"} 
127.0.0.6 - - [16/Apr/2024:01:52:32 +0000] "GET /home HTTP/1.1" 500 21 "-" "-" 8 "service-namespace-f37cf22c75625c34b341@kubernetescrd" "https://172.8.9.191:8080" 5ms
{"level":"debug","msg":"'500 Internal Server Error' caused by: tls: failed to verify certificate: x509: cannot validate certificate for 172.8.9.191 because it doesn't contain any IP SANs","time":"2024-04-16T01:52:32Z"}
```

When adding a `ServersTransport`, the `IngressRoute` becomes:
```
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ${service}
  namespace: ${namespace}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`${service}.example.com`)
      priority: 0
      services:
        - name: ${service}
          port: 8080
      serversTransport: ${service}
```
The `ServersTransport`:
```
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: ${service}
  namespace: ${namespace}
spec:
  serverName: "${each.value.name}.${var.namespace}.svc"
```

This gives the following error:
```json
{"level":"debug","msg":"'500 Internal Server Error' caused by: tls: failed to verify certificate: x509: certificate signed by unknown authority","time":"2024-04-16T02:30:09Z"}
127.0.0.6 - - [16/Apr/2024:02:30:09 +0000] "GET /home HTTP/1.1" 500 21 "-" "-" 461 "service-namespace-f37cf22c75625c34b341@kubernetescrd" "https://172.8.9.191:8080" 4ms 
{"level":"debug","msg":"'500 Internal Server Error' caused by: tls: failed to verify certificate: x509: certificate signed by unknown authority","time":"2024-04-16T02:30:09Z"}                                                                 
```

As a result, I have to create a secret (which is exactly the same as `/vault/secrets/ca.crt` from the Helm values / static config) and then reference it on the `ServersTransport`:
```
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: ${service}
  namespace: ${namespace}
spec:
  serverName: "${each.value.name}.${var.namespace}.svc"
  rootCAsSecrets: ["secret"]
```

I'd prefer not having to recreate the secret in each namespace alongside every `ServersTransport`, given that the certificate file is mounted to the Traefik pods at `/vault/secrets/ca.crt`

**Comment by cpboyd** [comment]
@nmengin It seems like initializing the `rootCAs` array here with the static/default config should resolve the problem:
https://github.com/traefik/traefik/blob/master/pkg/provider/kubernetes/crd/kubernetes.go#L342-L351

**Comment by nmengin** [comment]
I re-opened this issue because the feedback was done.

**Comment by bio-boris** [comment]
One workaround is the following:

1) Mount in your CA as a secret
2) Add it to the trust store of the container's OS, so traefik falls back to it

```
deployment:
  initContainers:
    - name: install-ca
      image: alpine
      command:
        - sh
        - -c
        - |
          cp /etc/ssl/certs/* /shared-certs/
          cat /internal-ca/ca.crt >> /shared-certs/ca-certificates.crt
      volumeMounts:
        - name: internal-ca
          mountPath: /internal-ca
        - name: shared-certs
          mountPath: /shared-certs
  additionalVolumes:
    - name: shared-certs
      emptyDir: {}

additionalVolumeMounts:
  - name: shared-certs
    mountPath: /etc/ssl/certs

```
