### ISSUE TITLE
Gitlab desktop client connect not found

### ISSUE THREAD

**Issue by nagy1991** [traefik/traefik#10636]
Hi, I would like to ask you for help, I'm just learning this world, I currently have a system that runs under docker swarm and portainer. I would like to run my own Gitlab for testing purposes, Gitlab's online interface works perfectly, but if I try to connect to it from my own computer, for example a SourceTree, it cannot connect to gitlab. Unfortunately, neither HTTP nor SSL works. Could you possibly help me find out what I'm doing wrong and why it doesn't work? Could it be that the SSH port of my server is 22222? I tried but unfortunately it didn't work either.
Thank you in advance for your help.  Traefik: v2.11.2 

Login Error
We couldn't connect to GitLab CE with your (username) credentials. Check your username and try the password again.

Traefik Stack
```yaml
version: "3.8"
services:
  traefik:
    restart: always
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.network=trnet"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entryPoints.ssh.address=:2222"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.letsencrypt.acme.email=adasd@asdasd.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    labels:
      - "api.dashboard=true"
      - "traefik.enable=true"
      - "traefik.docker.network=trnet"
      - "traefik.http.routers.traefik.rule=Host(`traefik.xcc.com`)"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.middlewares=force-https-traefik"
      - "traefik.http.middlewares.force-https-traefik.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik_https.rule=Host(`traefik.xcc.com`)"
      - "traefik.http.routers.traefik_https.entrypoints=https"
      - "traefik.http.routers.traefik_https.tls.certresolver=letsencrypt"  
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/nagysebestyen/letsencrypt:/letsencrypt"
    networks:
      - trnet

networks:
   trnet:
     external: true
```

Gitlab Stack
```yaml
version: "3.8"
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.exz.com'
    ports:
      - "2222:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.exz.com'
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.exz.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "gitlab@exz.com"
        gitlab_rails['smtp_password'] = "EMAILPASSWORD"
        gitlab_rails['smtp_domain'] = "exz.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      - trnet
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=trnet"
      - "traefik.http.routers.gitlab_insecure.entrypoints=http"
      - "traefik.http.routers.gitlab_insecure.rule=Host(`gitlab.exz.com`)"
      - "traefik.http.routers.gitlab_insecure.middlewares=force-https-traefik"

      - "traefik.http.routers.gitlab.entrypoints=https"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.exz.com`)"
      - "traefik.http.routers.gitlab.tls.certresolver=letsencrypt"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"

      - "traefik.tcp.routers.gitlab-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.gitlab-ssh.entrypoints=ssh"
      - "traefik.tcp.routers.gitlab-ssh.service=gitlab-ssh-svc"
      - "traefik.tcp.services.gitlab-ssh-svc.loadbalancer.server.port=2222"

networks:
   trnet:
     external: true

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
```
