### ISSUE TITLE
Enable STARTTLS for origin Postgres server in TLSRoute of Kubernetes Gateway API

### ISSUE THREAD

**Issue by hmoazzem** [traefik/traefik#10644]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

First, thanks all the contributors for the wonderful PR https://github.com/traefik/traefik/pull/9377. I've connected to Postgres with `PGSSLMODE=require`. It works like a charm!

**Now, how can we enable STARTTLS (essentially use PGSSLMODE=require) while forwarding the request to the origin server**?

Envoy apparently allows to set upstream sslmode https://github.com/envoyproxy/envoy/blob/af915efe430a670a9eed89bd57778657374acd4e/api/contrib/envoy/extensions/filters/network/postgres_proxy/v3alpha/postgres_proxy.proto#L24 but I couldn't get envoy/istio to work.

If you'd like to reproduce the scenario with traefik (for non-STARTTLS Postgres),

- Enable Gateway API and experimentalChannel (for TCPRoute and TLSRoute)
```shell
--entrypoints.postgres.address=:5432/tcp
--providers.kubernetesgateway=true
--providers.kubernetesgateway.experimentalchannel=true
```

- Ensure a similar section in `Gateway` definition

```yaml
  - allowedRoutes:
      namespaces:
        from: All
    hostname: 'postgres.example.org'
    name: tls-postgres-terminate
    port: 5432
    protocol: TLS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: postgres.example.org-tls-keypair
        namespace: traefik
      mode: Terminate
```

- Create a TLSRoute

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: postgres.example.org
spec:
  hostnames:
  - postgres.example.org
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: traefik-default
    namespace: traefik
    sectionName: tls-postgres-terminate
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: db-postgresql
      port: 5432
      weight: 1
```
