### ISSUE TITLE
Timeout (499 Client Closed Request) issue introduced with v2.11.2 (working correctly with all previous versions)

### ISSUE THREAD

**Issue by slym** [traefik/traefik#10647]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hello there,

I had recent issues on my setup where Traefik is reverse proxying an Harbor registry.

Version 2.11.2 is closing connection abruptly **after exactly 60 seconds** when doing a docker push to the Harbor registry behind traefik.
All previous versions do not have this behaviour.

Docker registry shows : 

`level=error msg="response completed with error"  err.code=unknown err.detail="client disconnected" err.message="unknown error" http.request.contenttype="application/octet-stream" http.request.host=redacted http.request.method=PATCH http.request.remoteaddr=redacted http.request.uri="/v2/internal/redacted/blobs/uploads/41e9-9478-836fc5d5c93f" http.response.duration=1m0.452685338s http.response.status=500 http.response.written=89 vars.name="internal/lina" vars.uuid=ecdca202-8964-41e9-9478-836fc5d5c93f `

Nginx proxy used in harbor shows:

`upstream prematurely closed connection while reading response header from upstream`

And Traefik logs shows : 
`traefik  | time="2024-04-21T19:12:25+02:00" level=debug msg="'499 Client Closed Request' caused by: context canceled"`

I've made a lot of testings and pinpointed this issue to exact version v2.11.2.

### What did you see instead?

To fix this issue I keep using v2.11.1 instead of v2.11.2.

### What version of Traefik are you using?

Tested with  2.11.2 => has this issue
Tested with 2.11.1 => working correctly
Tested with 2.9.5 => working correctly

### What is your environment & configuration?

```yaml

entryPoints:
  https:
    address: ":443"
    http:
      tls:
        certResolver: default
        domains:
          - main: "*.redacted.domain"
          
serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
    defaultRule: Host(`{{ default (.Name) (index .Labels "com.docker.compose.service") }}.redacted.domain`)
    network: "trafnet"

```

### If applicable, please paste the log output in DEBUG level

traefik  | time="2024-04-21T19:12:25+02:00" level=debug msg="'499 Client Closed Request' caused by: context canceled"
