### ISSUE TITLE
upload file  > 2G Fail with traefik 2.11

### ISSUE THREAD

**Issue by clementcohen** [traefik/traefik#10654]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

we update traefik from 2.10.4 to 2.11

### What did you see instead?

After an upgrade  of traefik  from version 2.10.4  to version 2.11 
all our pipelines which uplaod files greather than 2G  failed  with error 499 

![job_fail](https://github.com/traefik/traefik/assets/2699448/ba27d8da-a168-400c-a42e-5f664f0b3225)

### What version of Traefik are you using?

Version:      2.11.2
Codename:     mimolette
Go version:   go1.22.2
Built:        2024-04-11T15:38:45Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: ovhresolver

certificatesResolvers:
  ovhresolver:
    acme:

providers:
  file:
    directory: /routes
log:
  level: DEBUG
  filepath: "/var/log/traefik.log"
accessLog:
  filepath: "/var/log/access.log"
  filters:
    statusCodes:
      - "200-204"
      - "300-302"
    retryAttempts: true
    minDuration: "10ms"
```

routes/gitlab.yml:
```yaml
http:
  routers:
    gitlab:
      rule: "Host(`My.gitlab.instances`)"
      service: gitlab
      tls:
        certresolver: ovhresolver
      middlewares:
        - SecHeaders@file

  services:
    gitlab:
      loadBalancer:
        servers:
          - url: "http://172.29.1.25:80"
```

### If applicable, please paste the log output in DEBUG level

time="2024-04-23T11:49:02+02:00" level=debug msg="'499 Client Closed Request' caused by: context canceled"

**Comment by clementcohen** [comment]
I try to  add limit  middleware: 
```yaml

http:
  middlewares:
    limit:
      buffering:
        maxRequestBodyBytes: 5000000000
        maxResponseBodyBytes: 5000000000

```
same errors
