### ISSUE TITLE
customRequestHeaders always overwrite exist header value

### ISSUE THREAD

**Issue by nagisatosanae** [traefik/traefik#10669]
It seems that it also overwrites when there is already the same header in the request.
I want the headers to remain as they are when they already exist in the request.

For example, if you set it like below, even if you request with app-id: world, it will be overwritten with the hello header.
```
    http:
      middlewares:
        add-dapr-app-id:
          headers:
            customRequestHeaders:
              app-id: hello
```

Is there a setting to enable this? Or does it always overwrite?

Thank you.
