### ISSUE TITLE
Traefik v3 breaks Kubernetes Ingress Prefix Path Regex

### ISSUE THREAD

**Issue by fkollmann** [traefik/traefik#10672]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I upgraded from Traefik v2 to v3. Then I realized that all Kubernetes Ingress configurations which use a regex within as part of the prefix path (`pathType=Prefix`) break.

# Workaround

Add the following lines to the static config:

```yaml
core:
  defaultRuleSyntax: v2
```

# Suggestions

1. Revert to previous behavior for `pathType=Prefix`
2. Have an option for the Kubernetes Ingress provider to default to v2 behavior, by default
3. Have the Kubernetes Ingress provider to use `PathRegexp('^...')` insternally, instead
4. Add new `PathRegexp` value to `traefik.ingress.kubernetes.io/router.pathmatcher` annotation

### What did you see instead?

Kubernetes Ingress configurations which use a regex within as part of the Prefix path no longer work.

### What version of Traefik are you using?

v3.0.0

### What is your environment & configuration?

```yaml
providers:
  kubernetesIngress:
    ingressClass: traefik
    allowEmptyServices: true
    allowExternalNameServices: true
    throttleDuration: "3s"
```

Kubernetes Ingress Example:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalogservice-ingress
  namespace: uplift
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: https
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: 'api.xxx'
      http:
        paths:
          - path: /xxx/v1/yyyy/{customer:[a-z0-9]+}/push/
            pathType: Prefix
            backend:
              service:
                name: catalogservice-service
                port:
                  name: http
```
