### ISSUE TITLE
Warning when ExternalName service loading is enabled

### ISSUE THREAD

**Issue by morremeyer** [traefik/traefik#10676]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Start traefik v3.0.0 with the option

```
--providers.kubernetescrd.allowExternalNameServices=true
```

I expected this to not have any effects besides allowing the use of ExternalName services.

### What did you see instead?

There is a log with level warning about ExternalName services being enabled.

```
2024-05-02T10:04:22Z WRN ExternalName service loading is enabled, please ensure that this is expected (see AllowExternalNameServices option) providerName=kubernetescrd
```

Since ExternalName service loading is enabled because I explicitly configured it, I expect this to not print a log message of level warning, at most the level should be `INFO` in my opinion.

I expect a warning level log message to tell me about something that is wrong, not about me having configured an option.

### What version of Traefik are you using?

v3.0.0

### What is your environment & configuration?

Using the helm chart in [v28.0.0](https://github.com/traefik/traefik-helm-chart/releases/tag/v28.0.0) with the following values:

```yaml
updateStrategy:
  rollingUpdate:
    maxUnavailable: 1

globalArguments: ~

providers:
  kubernetesCRD:
    allowExternalNameServices: true

additionalArguments:
  - --serverstransport.insecureskipverify
  - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
  - --certificatesresolvers.cloudflare.acme.email=REDACTED_EMAIL
  - --certificatesresolvers.cloudflare.acme.storage=/data/acme.json
  - --metrics.prometheus=true
  - --providers.kubernetesingress.ingressclass=traefik
  - --providers.kubernetesingress.ingressendpoint.ip=REDACTED_IP
  
logs:
  general:
    level: WARN
  access:
    enabled: true

service:
  enabled: false

ports:
  web:
    hostPort: 80
    redirectTo:
      port: websecure
  websecure:
    hostPort: 443
    tls:
      enabled: true
      certResolver: cloudflare
      domains:
        - main: redacted.example.com
          sans:
            - "*.redacted.example.com"
  
ingressClass:
  enabled: true

env:
  - name: CLOUDFLARE_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-token
        key: CLOUDFLARE_DNS_API_TOKEN

persistence:
  enabled: true
```
