### ISSUE TITLE
v3 breaks TCP route HostSNI having multiple entries

### ISSUE THREAD

**Issue by resmo** [traefik/traefik#10674]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We configured TCP route based on HostSNI and in the past (in v2) we were able to pass severeal entries into HostSNI():

```json
"Tags": [
"traefik.enable=true",
"traefik.tcp.routers.example-prod-website-https.entrypoints=websecure",
"traefik.tcp.routers.example-prod-website-https.rule=HostSNI(`example.com`,`www.example.com`)",
"traefik.tcp.routers.example-prod-website-https.service=example-prod-website-https",
"traefik.tcp.routers.example-prod-website-https.tls.passthrough=true"
],
```

### What did you see instead?

```
error while adding rule Host(`example.com`,`www.example.com`): error while adding rule Host: unexpected number of parameters; got 2, expected one of [1]
```

### What version of Traefik are you using?

docker image traefik:v3.0.0

### What is your environment & configuration?

while we don't think it's relevant to the issue:

nomad job with consul catalog.

```yaml
providers:
  consulCatalog:
    refreshInterval: 5s
    prefix: traefik
    exposedByDefault: false
    endpoint:
      address: 127.0.0.1:8500
      scheme: http

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8080"
```
