### ISSUE TITLE
maxResponseBodyBytes exceed doesn't change response code to 500

### ISSUE THREAD

**Issue by AliaksandrZhloba** [traefik/traefik#10687]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I setup a response size limit, see https://doc.traefik.io/traefik/middlewares/http/buffering/#maxresponsebodybytes.

### What did you see instead?

Trimmed with maxResponseBodyBytes response body and 200 status code.

### What version of Traefik are you using?

2.11.2

### What is your environment & configuration?

- traefik.http.routers.backend.middlewares=limit@docker
- traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=2000000

**Comment by AliaksandrZhloba** [comment]
Hello @nmengin ,

docker-compose.yml:
```
services:
  reverse-proxy:
    image: traefik:v2.11.2
    command: --api.insecure=true --providers.docker --entryPoints.web.address=:80 --entryPoints.websecure.address=:443
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    image: ealen/echo-server
    labels:
      - traefik.http.routers.backend.rule=Host(`echo.docker.localhost`) || PathPrefix(`/echo`)
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.services.backend.loadbalancer.server.port=80
      - traefik.http.routers.backend.middlewares=limit@docker
      - traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=20000
```

POST echo.docker.localhost with any large body.

Tried _web_ and _websecure_ entrypoints - the result is the same.
Tried v2.11.2 and v3.0.0 - similar (although v3.0.0 sometimes writes `ERR write: total size of 32768 exceeded allowed 20000 entryPointName=web middlewareName=limit@docker middlewareType=Buffer routerName=backend@docker` to log).
When maxResponseBodyBytes=2000 - the response is 500 Internal Server Error
When maxResponseBodyBytes=20000 - the response is 200, by the body is not only trimmed but sometimes contains some trash.
