### ISSUE TITLE
TLS is not working after v3 upgrade

### ISSUE THREAD

**Issue by myoung34** [traefik/traefik#10681]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

[this yaml has been working for a very long time in Traefik V2](https://github.com/myoung34/homelab/blob/main/k8s/prod/hass/traefik.yaml#L22-L41)

Traefik, however, after the v28 helm upgrade (traefik v3) no longer serves the TLS certificate

### What did you see instead?

```
/ # curl -vvk https://hass.marcyoung.us  | grep 'Server certificate:' -A 7
* Server certificate:
*  subject: CN=TRAEFIK DEFAULT CERT
*  start date: Apr 30 20:02:36 2024 GMT
*  expire date: Apr 30 20:02:36 2025 GMT
*  issuer: CN=TRAEFIK DEFAULT CERT
*  SSL certificate verify result: self-signed certificate (18), continuing anyway.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
```

### What version of Traefik are you using?

```
$ k -n traefik exec -it pod/traefik-97579fd7-nww5m traefik version
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Version:      3.0.0
Codename:     beaufort
Go version:   go1.22.2
Built:        2024-04-29T14:25:59Z
OS/Arch:      linux/arm64
```

### What is your environment & configuration?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hass
  namespace: hass
  annotations:
    kubernetes.io/ingress.class: traefik
    certmanager.k8s.io/cluster-issuer: letsencrypt-hass-prod
    certmanager.k8s.io/acme-challenge-type: dns01
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`hass.marcyoung.us`)
      services:
        - name: hass-home-assistant
          port: 8123
  tls:
    secretName: hass-cert
```

Add more configuration information here.

The cert is provided from cert-manager and lands as a secret

```
$ k -n hass get secret/hass-cert
NAME        TYPE                DATA   AGE
hass-cert   kubernetes.io/tls   2      21m
```
