### ISSUE TITLE
Traefik v3.0 Let's encrypt TLS Challenge failing when behind a traefik TCP Router

### ISSUE THREAD

**Issue by jan-thoma** [traefik/traefik#10684]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have multiple servers in my Network and one public static IP. The firewall is forwarding all traffic to `Server 1` on ports 80 and 443. `Server 1` has multiple TCP Router in place to send the traffic to `Server 2` and `Server 3` which look live this:

```
tcp:
    routers:
        server_2:
            entrypoints:
                - websecure
            rule: HostSNIRegexp(`^.+\.server2\.subdomain\.example\.com$`)
            tls:
                passthrough: true
            service: server_2
    services:
        server_2:
            loadBalancer:
                proxyProtocol:
                    version: 2
                servers:
                    - address: 172.16.10.12:443
```

and

```
tcp:
    routers:
        server_3:
            entrypoints:
                - websecure
            rule: HostSNIRegexp(`^.+\.server3\.subdomain\.example\.com$`)
            tls:
                passthrough: true
            service: server_3
    services:
        server_3:
            loadBalancer:
                proxyProtocol:
                    version: 2
                servers:
                    - address: 172.16.10.13:443
```

On `Server 2` and` Server 3` lets's encrypt is configures like this:

```
certificatesResolvers:
    letsencrypt-tls:
        acme:
            email: le@example.com
            storage: /letsencrypt/acme.json
            tlsChallenge: true 
```

If try to create a Certificate on `Server 2` or `Server 3` for example `www.app.server2.subdomain.example.com` and `app.server2.subdomain.example.com` it always fails for the domain with the `www` prefix. With a `error 400` code.

On `Server 1` which is facing directly to the internet the problem is not present.

### What did you see instead?

---

### What version of Traefik are you using?

Version:      3.0.0
Codename:     beaufort
Go version:   go1.22.2
Built:        2024-04-29T14:25:59Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

Server 1
```
log:
    level: INFO

accessLog:
    filePath: /var/log/traefik/access.log
    format: json
    bufferingSize: 100
    fields:
        defaultMode: keep
        headers:
            defaultMode: keep

api:
    dashboard: true

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false
        network: external
    file:
        directory: /etc/traefik/rules
        watch: true

entryPoints:
    web:
        address: :80
        forwardedHeaders:
            trustedIPs:
                - 172.16.10.11
        http:
            middlewares:
                - crowdsec-bouncer@file
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https
    websecure:
        address: :443
        forwardedHeaders:
            trustedIPs:
                - 172.16.10.11
        http:
            middlewares:
                - crowdsec-bouncer@file
        http3:
            advertisedPort: 443

certificatesResolvers:
    letsencrypt-tls:
        acme:
            email: le@example.com
            storage: /letsencrypt/acme.json
            tlsChallenge: true 

metrics:
    influxDB2:
        address: https://influxdb.sg.t-k-f.ch
        token: ***
        org: ***
        bucket: traefik
        addEntryPointsLabels: true
        addRoutersLabels: true
        addServicesLabels: true
        additionalLabels:
            host: traefik.example.com
```

Server 2
```
log:
    level: INFO

accessLog:
    filePath: /var/log/traefik/access.log
    format: json
    bufferingSize: 100
    fields:
        defaultMode: keep
        headers:
            defaultMode: keep

api:
    dashboard: true

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false
        network: external
    file:
        directory: /etc/traefik/rules
        watch: true

entryPoints:
    websecure:
        address: :443
        forwardedHeaders:
            trustedIPs:
                - 172.16.10.12
        proxyProtocol:
            trustedIPs:
                - 172.16.10.11
        http:
            middlewares:
                - crowdsec-bouncer@file
        http3: true

certificatesResolvers:
    letsencrypt-tls:
        acme:
            email: le@example.com
            storage: /letsencrypt/acme.json
            tlsChallenge: true 

metrics:
    influxDB2:
        address: https://influxdb.sg.t-k-f.ch
        token: ***
        org: ***
        bucket: traefik
        addEntryPointsLabels: true
        addRoutersLabels: true
        addServicesLabels: true
        additionalLabels:
            host: traefik.example.com
```

**Comment by jan-thoma** [comment]
This Behaviour was introduced with [v3.0.0-rc4](https://github.com/traefik/traefik/releases/tag/v3.0.0-rc4) downgrading to [v3.0.0-rc3](https://github.com/traefik/traefik/releases/tag/v3.0.0-rc3) resolves the problem

**Comment by nmengin** [comment]
Hello @jan-thoma,

Thanks for reaching out.
We will check the merge back we have done from Traefik v2 Traefik v3.

**Comment by CybotTM** [comment]
Loks like we have the same issue for 2.11.2

**Comment by CybotTM** [comment]
Going back to 2.11.0 fixed the issue for us, waiting now for a fix in 2.11.x

**Comment by TheDevMinerTV** [comment]
We think this was caused by #10536.

**Comment by acul009** [comment]
Is there any fix planned?
Our certificates are starting to run out.

We use Traefik as a TLS proxy for sharing Port 443 without breaking open the encryption.

**Comment by CybotTM** [comment]
For some unknown reason it was only fixed for 3.0 RC

I'm also curious why this is still not confirmed. It's a blocker.

Hopefully someone will find the time to provide a MR soon. Thank you in advance.

**Comment by rtribotte** [comment]
Hello @jan-thoma @CybotTM @acul009 @TheDevMinerTV,

As @TheDevMinerTV mentioned, this behavior is due to changes in https://github.com/traefik/traefik/pull/10536.
This is an intended behavior and was introduced to make Traefik more secure in some context (multi-tenancy).

However, we think we could introduce an option to allow the "insecure" mode.
We are also considering enforcing this only when Traefik is configured to handle ACME TLS challenges.

**Comment by rtribotte** [comment]
I'm still confirming the behavior by changing the label, while this is not really a bug.

**Comment by acul009** [comment]
While I understand the intent when using TLS-termination, is it really intended to block the downstream challenge verification when using tls-passthrough? I‘d feel like the entire point of the tls-passthrough would be not to interfere and make exactly these things possible.

Either way, I‘d simply be happy to have the option back. Calling it insecure doesn‘t really bother me - although I‘d be interested in the possible attack vector from this. When using passthrough the downstream target already has a valid certificate, no?

Thank you for your hard work on traefik :)

**Comment by leeaash** [comment]
> I'm still confirming the behavior by changing the label, while this is not really a bug.

How to add ‘insecure’ option in docker labels? Could you give me a sample?

**Comment by rtribotte** [comment]
@leeaash This speculative "insecure" option remain to be implemented yet.

@acul009 Thanks for your feedback. Are you using a TLS resolver with Traefik? We are wondering if simply allowing the TLS challenge passthrough when no TLS resolver is configured is enough in your situation.

**Comment by acul009** [comment]
> @acul009 Thanks for your feedback. Are you using a TLS resolver with Traefik? We are wondering if simply allowing the TLS challenge passthrough when no TLS resolver is configured is enough in your situation.

Not really, since my configuration is shared between pretty much all my traefik instances.
The insecure flag for passthing through tls challenges as well would actually better suite my needs.

I'm using traefik both as a reverse proxy for my docker application as well as a network wide reverse proxy to allow things like a NAS to obtain a Let's encrypt Certificate.

To me the TLS-Passthrough is one of traefiks killer-features. It's just so convinient to share Port 443 without much reconfiguration needed on third party vm images. Some applications just assume they will handle TLS themselves and I actually like having those connections encrypted, even if it is inside my "secure" local network.

Here's a little diagram about how I use traefik:
```mermaid
flowchart LR
    
internet[Internet]
network-traefik[Network Traefik]
internet -->|Port 443 / 80| network-traefik
network-traefik -->|Port 443\nTLS-Passthrough| docker-traefik1[Docker Traefik 1]
network-traefik -->|Port 443\nTLS-Passthrough| docker-traefik2[Docker Traefik 2]
network-traefik -->|Port 443\nTLS-Passthrough| docker-traefik3[Docker Traefik 3]

network-traefik -->|Port 80\nPathprefix: /.well-known/acme-challenge| nas[NAS]
network-traefik -->|Port 80 / 443\nTLS-Passthrough\nPathprefix: /.well-known/acme-challenge| non-docker-host[Non Docker Host]
```

To make this easier I actually built myself a very basic Web-UI to configure routes so I don't have to use nano in the command line.

https://github.com/Rahn-IT/traefik-gui (Warning: very janky)

**Comment by jan-thoma** [comment]
Using basicly the same setup as @acul009. The change basically breaks the TLS-Passtrough functionality.

**Comment by CybotTM** [comment]
Same here.
For various reasons, including running a Traefik with ACME behind a Traefik with TLS pass through, we need this vanilla TLS passthrough.

Also, if i remember right, the same thing was fixed in 3.0 by reverting the commit - am I wrong and this has changed at some later point or why can we not just revert this for 2.11 too?

I must confess that I don't understand why this is considered unsafe.

I can configure HTTP (pass through) without any "unsafe" flag or similar stuff.

Thanks for effort in this case and the good work with Traefik at all.

**Comment by kristoficko** [comment]
Same use case and scenario as @acul009 showcased above - and same love for traefik. 

Initially I was trying to achieve this with nginx, took me enourmous time to get it at least partially working and then it still had issues (constant refreshes of webpages, etc.). Once I found out the options traefik provides, I had it running within couple of hours (including studying and understanding documentation) - the endresult exceeded my expectations!

Keep up the good work and if we don't get this rolled back my internet facing traefik will stay on 2.10.7 4ever :)

**Comment by rtribotte** [comment]
Hello @acul009 @jan-thoma @CybotTM @kristoficko,

Thanks for all the feedback!

We're not against introducing an option, but first we want to make sure that the solution from #10981 doesn't fit your use cases.

@CybotTM We introduced this breaking change as a fix because of security concerns we had regarding potential hijacking of certificate negotiation in a multi-tenant environment.
I have to admit that we probably moved too fast on this issue, because in the end we came to the conclusion that Traefik should not be considered secure "out of the box" when used to expose routes of multiple clients in a multi-tenant environment, simply because Traefik does not provide/enforce client isolation.

Now that we have introduced this behavior, we are reluctant to undo it and prefer to mitigate the use case exposed in this issue, if possible, without introducing yet another option.

As of today, regarding the ACME HTTP challenge, as long as no HTTP challenge resolver is configured, it is possible for a user to handle the challenge with a custom HTTP router.
Once an HTTP challenge resolver is configured, the HTTP challenge resolver handler would preempt any request on the `/.well-known/' path.

With #10981, we wanted to introduce the same tweak, so that as long as no TLS challenge resolver (and only this one) is configured, using custom TLS pass-through router would be possible without any additional configuration.

@acul009 In the setup you shared, it seems doable not to declare the TLS challenge resolver on the "gateway" `Network Traefik` instance, WDYT?

**Comment by acul009** [comment]
> @CybotTM We introduced this breaking change as a fix because of security concerns we had regarding potential hijacking of certificate negotiation in a multi-tenant environment.
I have to admit that we probably moved too fast on this issue, because in the end we came to the conclusion that Traefik should not be considered secure "out of the box" when used to expose routes of multiple clients in a multi-tenant environment, simply because Traefik does not provide/enforce client isolation.

So you're blocking this because in theory a compromised downstream application that is not supposed to have access to TLS certificates should not be able to generate a valid certificate that could then be used for additional attacks?

If I got this wrong, I'd be interested to hear more about your concerns. As far as I understand, the TLS challenge is already only handed through to the routers which actually match the SNI. Which means I can only try to obtain certificates for my own domain, just like the HTTP challenge. And that also only works then TLS passthrough is on. When it's off the TLS tunnel is terminated before reaching the target, thus blocking of the alpn request, right?

> @acul009 In the setup you shared, it seems doable not to declare the TLS challenge resolver on the "gateway" Network Traefik instance, WDYT?

In theory yes, but as I've said: my traefik configurations share their configuration and this would make matters more complicated than they already are. This also breaks apart if I had 3 traefik instances in a row.

I think the best option would still be the `insecure` option. Although I'd name it more explicitly. Maybe `allow_acme_challenge` or `passthrough_acme_challenge`?

In a full example this could look like this:

```yaml
tcp:
    routers:
        server_3:
            entrypoints:
                - websecure
            rule: HostSNIRegexp(`^.+\.server3\.example\.com$`)
            tls:
                passthrough:
                    allow_acme_challenge: true
            service: server_3
```

If passthrough is set to `true` you just fall back to your default options setting `allow_acme_challenge` to `false`.

---

If that is to much work, how about adding a static option or environment variable to bypass the check from #10536 for all routers?

Maybe something like `tls_passthrough_allow_acme_challenge` ?

People like me could just enable this option to get the old behaviour back - since I'm not in a multi-tentant environment I won't have any problems.
