### ISSUE TITLE
RedirectRegex broken since update to v3.0

### ISSUE THREAD

**Issue by lazka** [traefik/traefik#10690]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have the following RedirectRegex config: https://github.com/msys2/msys2-main-server/blob/8330fd44f4fdf76d27200e995fb8494a4006e6c3/docker-compose.yml#L153-L154

This resulted in "https://mingw-w64.org" being redirected to "https://www.mingw-w64.org", among other cases.

Since the update to v3.0 from  v2.11.2 this no longer works and requests using "https://mingw-w64.org" no longer get redirected. I've confirmed that downgrading to 2.11 makes things work again.

I couldn't find anything in the migration guide regarding any changes for RedirectRegex, so I'm filing this here.

### What did you see instead?

No redirect happening.

### What version of Traefik are you using?

3.0.0

### What is your environment & configuration?

See the linked docker-compose.yml above

**Comment by pbek** [comment]
I have the same issue on Traefik 3.0, e.g. also with a simple redirect from `www.mydomain` to `mydomain`.

Config:

```
      - traefik.http.middlewares.bekerle-web-2022-www.redirectregex.regex=^(https?://)www.(.*)$$
      - traefik.http.middlewares.bekerle-web-2022-www.redirectregex.replacement=$${1}$${2}
      - traefik.http.middlewares.bekerle-web-2022-www.redirectregex.permanent=true
```

There was no redirect, the webpage could not be accessed anymore.

**Comment by pbek** [comment]
But what did work on Traefik v3 was:

```
      - traefik.http.middlewares.nextcloud-redirectregex.redirectregex.permanent=true
      - traefik.http.middlewares.nextcloud-redirectregex.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav
      - traefik.http.middlewares.nextcloud-redirectregex.redirectregex.replacement=https://$${1}/remote.php/dav/
```

**Comment by mmatur** [comment]
Hello @lazka and @pbek,

Sorry for the late answer.

I tried to reproduce the issue with the following docker-compose:

```yaml
version: '3.8'

services:
  hub:
    image: traefik:v3.0
    command:
      - --providers.docker
      - --log.level=DEBUG
      - --api.insecure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:8080:8080"
  whoami:
    image: traefik/whoami
    labels:
      traefik.http.routers.whoami.rule: Host(`mingw-w64.org`) || Host(`mingw-w64.net`) || Host(`www.mingw-w64.net`)
      traefik.http.routers.whoami.middlewares: redir
      traefik.http.middlewares.redir.redirectregex.regex: ^http(s?)://(?:www[.])?mingw-w64[.](?:org|net)/(.*)$$
      traefik.http.middlewares.redir.redirectregex.replacement: http$${1}://www.mingw-w64.org/$${2}
```

```console
$ curl -Iv http://127.0.0.1 -H "Host: mingw-w64.org"
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80
> HEAD / HTTP/1.1
> Host: mingw-w64.org
> User-Agent: curl/8.6.0
> Accept: */*
>
< HTTP/1.1 307 Temporary Redirect
HTTP/1.1 307 Temporary Redirect
< Location: http://www.mingw-w64.org/
Location: http://www.mingw-w64.org/
< Date: Tue, 28 May 2024 08:24:08 GMT
Date: Tue, 28 May 2024 08:24:08 GMT
< Content-Length: 18
Content-Length: 18

<
* Connection #0 to host 127.0.0.1 left intact
```

And it seems is working as expected could you please provide a complete reproductible use case

**Comment by pbek** [comment]
Thank you for your answer, @mmatur. Was above `www` redirect also not reproducible?

https://github.com/traefik/traefik/issues/10690#issuecomment-2094144280

**Comment by mmatur** [comment]
@pbek with the following docker-compose

```yaml
version: '3.8'

services:
  hub:
    image: traefik:v3.0
    command:
      - --providers.docker
      - --log.level=DEBUG
      - --api.insecure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:8080:8080"
  whoami:
    image: traefik/whoami
    labels:
      traefik.http.routers.whoami.rule: Host(`www.whoami.localhost`)
      traefik.http.routers.whoami.middlewares: bekerle-web-2022-www
      traefik.http.middlewares.bekerle-web-2022-www.redirectregex.regex: ^(https?://)www.(.*)$$
      traefik.http.middlewares.bekerle-web-2022-www.redirectregex.replacement: $${1}$${2}
```

```console
$ curl -Iv http://127.0.0.1 -H "Host: www.whoami.localhost"
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80
> HEAD / HTTP/1.1
> Host: www.whoami.localhost
> User-Agent: curl/8.6.0
> Accept: */*
>
< HTTP/1.1 307 Temporary Redirect
HTTP/1.1 307 Temporary Redirect
< Location: http://whoami.localhost/
Location: http://whoami.localhost/
< Date: Tue, 28 May 2024 09:11:00 GMT
Date: Tue, 28 May 2024 09:11:00 GMT
< Content-Length: 18
Content-Length: 18

<
* Connection #0 to host 127.0.0.1 left intact
```

I'm not able to reproduce either.
