### ISSUE TITLE
ContentType middleware working not as expected

### ISSUE THREAD

**Issue by riedel** [traefik/traefik#10693]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

contentType detection seems to work unreliably. This might be due to the fact that it is hardly documented.

I am testing with a very limited "server":` (printf "HTTP/1.0 200 OK\nContent-Length: `wc -c <test.html`\n\n";cat test.html;echo)|nc -l 80`

I tried different payloads

and use a rather minimal setup

### What did you see instead?

this is my simple test case:

`>curl   http://localhost:8000/index.html`

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>hello world</title>
  </head>
  <body>
          hello world
  </body>
</html>
```

`curl -I  http://localhost:8000/index.html`
```
HTTP/1.1 200 OK
Content-Length: 152
Date: Sun, 05 May 2024 10:29:02 GMT
```

no content-type anywhere.

no debug message about a problem

First of all, I would love to see a better documentation in which cases the content-type autodetection is supposed to work.

Secondly, I saw it working, tried to reproduce, but now I not getting there anymore

Thirdly, the middleware does not seem to be configurable (e.g. with a fallback type=

### What version of Traefik are you using?

Version:      3.0.0
Codename:     beaufort
Go version:   go1.22.2
Built:        2024-04-29T14:25:59Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```
http:
  routers:
    test:
      rule: PathPrefix(`/`)
      entryPoints:
        - http
      service: netcat
      middlewares:
        - autodetect-type
  middlewares:
     autodetect-type:
      contentType: {}
  services:
    netcat:
      loadBalancer:
        servers:
          - url: http://192.168.32.1
```

### If applicable, please paste the log output in DEBUG level

```
2024-05-05T10:35:45Z DBG github.com/traefik/traefik/v3/pkg/middlewares/contenttype/content_type.go:42 > Enable Content-Type auto-detection. midd
lewareName=autodetect-type@file middlewareType=ContentType

2024-05-05T10:35:45Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:196 > Service selected by WRR: 52e8577fc4a2376
4
```
