### ISSUE TITLE
The final response code of my api service when using traefik error middleware is of main service ? -  error service ?    

### ISSUE THREAD

**Issue by jainasanthosh2023** [traefik/traefik#10742]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We have a couple of microservice applications with common error service deployed on k8s, i tried to redirect using error middleware option to redirect to error service but I always see final response code as of main service followed by response content from error service.

### What did you see instead?

I am expecting since error middleware successfully redirected to error service , the final response code should be 200.

### What version of Traefik are you using?

v2.10.6

### What is your environment & configuration?

```yaml
    errors:
      query: /
      service:
        name: nginx
        namespace: traefik-demo-failover
        nativeLB: true
        passHostHeader: false
        port: 80
        scheme: http
      status:
      - 500-599

```

Add more configuration information here.
