### ISSUE TITLE
Kubernetes Ingress With Wildcard Host Doesn't Cover Hosts With Undescores (_)

### ISSUE THREAD

**Issue by lemniskett** [traefik/traefik#10744]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I created an Ingress resource:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: le-dns01-prod
  labels:
    app.kubernetes.io/instance: odoo-17
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: odoo
    app.kubernetes.io/version: git
    helm.sh/chart: odoo-6.0.1
  name: wildcard-prefix.odoo17-dev.example.tld-odoo-17-ingress
  namespace: odoo
spec:
  ingressClassName: traefik
  rules:
    - host: '*.odoo17-dev.example.tld'
      http:
        paths:
          - backend:
              service:
                name: odoo-17
                port:
                  number: 8069
            path: /
            pathType: Prefix
          - backend:
              service:
                name: odoo-17
                port:
                  number: 8072
            path: /websocket
            pathType: Prefix
  tls:
    - hosts:
        - '*.odoo17-dev.mitija.com'
      secretName: wildcard-prefix.odoo17-dev.example.tld-tls
```

### What did you see instead?

When I visited a subdomain with underscores, say. "foo_bar.odoo17-dev.example.tld", Traefik will instead return 404, The Router that is generated by Traefik doesn't seem to include underscore in the PathRegexp

```
HostRegexp(`^[a-zA-Z0-9-]+\.odoo17e-dev\.example\.tld$`) && PathPrefix(`/`)
```

Creating IngressRoute manually to include underscore fixed the issue, but nonetheless still an unexpected behavior
```
HostRegexp(`^[a-zA-Z0-9-_]+\.odoo17e-dev\.example\.tld$`) && PathPrefix(`/`)
```

### What version of Traefik are you using?

```
Version:      3.0.0
Codename:     beaufort
Go version:   go1.22.2
Built:        2024-04-29T14:25:59Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

Traefik helm chart values.yml

```yaml
ports:
  websecure:
    transport:
      respondingTimeouts:
        idleTimeout: 300s
        readTimeout: 300s
        writeTimeout: 0s
service:
  spec:
    externalTrafficPolicy: Local
```
