### ISSUE TITLE
Environment Variables 

### ISSUE THREAD

**Issue by Ramalama2** [traefik/traefik#10759]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Setting up Environment Variables to Configure the "default-storage" Certificate resolver.

TRAEFIK_CERTIFICATESRESOLVERS_default-storage=true
TRAEFIK_CERTIFICATESRESOLVERS_default-storage_ACME_DNSCHALLENGE=true
TRAEFIK_CERTIFICATESRESOLVERS_default-storage_ACME_DNSCHALLENGE_DELAYBEFORECHECK=10
TRAEFIK_CERTIFICATESRESOLVERS_default-storage_ACME_DNSCHALLENGE_PROVIDER=ovh
TRAEFIK_CERTIFICATESRESOLVERS_default-storage_ACME_DNSCHALLENGE_RESOLVERS=ns12.ovh.net
TRAEFIK_CERTIFICATESRESOLVERS_default-storage_ACME_EMAIL="edv@mydomain.de"

### What did you see instead?

ERR Router uses a non-existent certificate resolver certificateResolver=default-storage routerName=api@file

### What version of Traefik are you using?

Version:      3.0.1
Codename:     beaufort
Go version:   go1.22.3
Built:        2024-05-22T13:12:16Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```toml
[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false
   watch = true
   network = "web"

[providers.file]
  directory = "traefik.d"
  watch = true

[log]
  level = "ERROR"

[api]
  dashboard = true
```

Environment Variables:
LEGO_DISABLE_CNAME_SUPPORT=true
OVH_ENDPOINT=ovh-eu
OVH_APPLICATION_KEY=xxxx
OVH_APPLICATION_SECRET=xxxxx
OVH_CONSUMER_KEY=xxxxxx
TRAEFIK_CERTIFICATESRESOLVERS_default-storage=true
TRAEFIK_CERTIFICATESRESOLVERS_default-storage_ACME_DNSCHALLENGE=true
TRAEFIK_CERTIFICATESRESOLVERS_default-storage_ACME_DNSCHALLENGE_DELAYBEFORECHECK=10
TRAEFIK_CERTIFICATESRESOLVERS_default-storage_ACME_DNSCHALLENGE_PROVIDER=ovh
TRAEFIK_CERTIFICATESRESOLVERS_default-storage_ACME_DNSCHALLENGE_RESOLVERS=ns12.ovh.net
TRAEFIK_CERTIFICATESRESOLVERS_default-storage_ACME_EMAIL="edv@mydomain.de"
