### ISSUE TITLE
Sectigo Certresolver does not populate cert field in JSON file

### ISSUE THREAD

**Issue by SolomonHD** [traefik/traefik#10787]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I found a similar discussion on the traefik forums but I am rate limited--due to being a new user--and can no longer reply in the thread.

I work for an educational institution, and we have Sectigo (aka InCommon) providing our certs. This is provided as a free service for the edu space. We recently begun experimenting with Certbot. The authentication is handled via EAB/HMAC key. Certbot works for any FQDN my admin has whitelisted for my EAB user. Minimum cert length appears to be a year.

### What did you see instead?

When attempting to use v2.11.2 Traefik's certresolver function with my Secitgo EAB, it creates the ACME JSON file, authenticates and all fields appear to be correct except cert which is set to `null`. If I provide an email for the resolver, the cert is emailed to me as if I was using the InCommon/Sectigo web console. If I provide no email, as far as I can tell nothing happens with the cert.

Oddly, if I provide an email to the resolver, the cert does not show up in the history of my email address in the web console, as it would If I actually used the web console to create a cert. That tells me the EAB is registering the cert, but for some reason it's being emailed instead of parsed by Traefik.
My Configuration reposted from the [forums](https://community.traefik.io/t/renewal-of-the-certificates-using-acme-doesnt-happen-automatically/20105/18):

### What version of Traefik are you using?

v.2.11.2

### What is your environment & configuration?

```yaml
### Traefik Docker Compose YML file

version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    # command:
    #   - "--certificatesresolvers.sectigo=true"
    #   - "--certificatesresolvers.sectigo.acme.caserver=https://acme.sectigo.com/v2/InCommonRSAOV"
    #   - "--certificatesresolvers.sectigo.acme.storage=/shared_files/sectigo_acme.json"
    #   - "--certificatesresolvers.sectigo.acme.eab.hmacencoded=${EAB_HMAC_KEY_BASE64_ENCODED}"
    #   - "--certificatesresolvers.sectigo.acme.eab.kid=${EAB_KID}"
    environment:
      HTTP_PROXY: http://webproxyaws.university.net:3128/
      HTTPS_PROXY: http://webproxyaws.university.net:3128/
      NO_PROXY: authelia,127.0.0.1,localhost,.university.edu,169.254.169.254,.university.net,.amazonaws.com,172.16.0.0/12,.docker.local
      # TRAEFIK_CERTIFICATESRESOLVERS_SECTIGO: true
      # TRAEFIK_CERTIFICATESRESOLVERS_SECTIGO_ACME_CASERVER: https://acme.sectigo.com/v2/InCommonRSAOV
      # TRAEFIK_CERTIFICATESRESOLVERS_SECTIGO_ACME_STORAGE: /shared_files/sectigo_acme.json
      # TRAEFIK_CERTIFICATESRESOLVERS_SECTIGO_ACME_EAB_KID: $EAB_KID
      # TRAEFIK_CERTIFICATESRESOLVERS_SECTIGO_ACME_EMAIL: solomonhd@university.edu
      # TRAEFIK_CERTIFICATESRESOLVERS_SECTIGO_ACME_EAB_HMACENCODED: $EAB_HMAC_KEY_BASE64_ENCODED
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - shared_files:/shared_files
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.http.routers.api.rule: Host(`${ENV_PREFIX:-}traefik.int.university.edu`)
      traefik.http.routers.api.entrypoints: websecure
      traefik.http.routers.api.tls: true
      traefik.http.routers.api.service: api@internal
      traefik.http.services.traefik.loadbalancer.server.port: 8080

      traefik.http.middlewares.traefik-redirect-https.redirectscheme.scheme: https
      traefik.http.routers.traefik-http.middlewares: traefik-redirect-https
      traefik.http.routers.traefik-http.rule: Host(`${ENV_PREFIX:-}traefik.int.university.edu`)
      traefik.http.routers.traefik-http.entrypoints: web

      traefik.http.routers.api.middlewares: authelia@docker
      traefik.http.middlewares.authelia.forwardAuth.address: http://authelia:9091/api/verify?rd=https%3A%2F%2Fdev-cloudbeaver.int.university.edu%2F
      traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader: true
      traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders: Remote-User,Remote-Groups,Remote-Name,Remote-Email
    restart: unless-stopped
volumes:
  shared_files:
    external: true
networks:
  default:
    name: general
    external: true
```
```yaml
# Traefik.yml static config:
global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

# (Optional) Log information
# ---
log:
  level: DEBUG  # DEBUG, INFO, WARNING, ERROR, CRITICAL
#   format: common  # common, json, logfmt
#   filePath: /var/log/traefik/traefik.log

# (Optional) Accesslog
# ---
# accesslog:
  # format: common  # common, json, logfmt
  # filePath: /var/log/traefik/access.log

# (Optional) Enable API and Dashboard
# ---
api:
  dashboard: true  # true by default
  insecure: true  # Don't do this in production!

# Entry Points configuration
# ---
entryPoints:
  web:
    address: :80
    http:
      encodeQuerySemicolons: true
    proxyProtocol:
      insecure: false
      trustedIPs:
        - 10.0.0.0/0
        - 172.16.0.0/16
    forwardedHeaders:
      insecure: false
      trustedIPs:
        - 10.0.0.0/0
        - 172.16.0.0/16
  websecure:
    address: :443
    http:
      encodeQuerySemicolons: true
    proxyProtocol:
      insecure: false
      trustedIPs:
        - 10.0.0.0/0
        - 172.16.0.0/16
    forwardedHeaders:
      insecure: false
      trustedIPs:
        - 10.0.0.0/0
        - 172.16.0.0/16

  # (Optional) Redirect to HTTPS
  # ---
  # http:
  #   redirections:
  #     entryPoint:
  #       to: websecure
  #       scheme: https


# Overwrite Default Certificates
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /shared_files/certs/cert.pem
        keyFile: /shared_files/certs/cert-key.pem
# Disable TLS version 1.0 and 1.1
  options:
    default:
      minVersion: VersionTLS12

certificatesResolvers:
  sectigo:
    acme:
      caServer: https://acme.sectigo.com/v2/InCommonRSAOV
      tlsChallenge: {}
      certificatesDuration: 8160
      eab:
        kid: '{{ env "EAB_KID" }}'
        hmacEncoded: '{{ env "EAB_HMAC_KEY_BASE64_ENCODED" }}'
      storage: /shared_files/sectigo_acme.json
      email: solomonhd@university.edu

providers:
  docker:
    exposedByDefault: false  # Default is true
    network: general
    # watch: true
  file:
    # watch for dynamic configuration changes
    directory: /etc/traefik
    watch: true
```
```yaml
#Website I'm testing with docker compose file
x-environment: &environment
  HTTP_PROXY: http://webproxyaws.university.net:3128/
  HTTPS_PROXY: http://webproxyaws.university.net:3128/
  NO_PROXY: authelia,127.0.0.1,localhost,.university.edu,169.254.169.254,.university.net,.amazonaws.com,172.16.0.0/12,.docker.local
  ENCRYPTION_KEY: 6c1fe4e407b8911c104518103505b218
  AUTH_SECRET: 5lrMXKKWCVocS/uerPsl7V+TX/aaUaI7iDkgl3tSmLE=
  POSTGRES_PASSWORD: infisical
  POSTGRES_USER: infisical
  POSTGRES_DB: infisical
  DB_CONNECTION_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@infisical-db:5432/${POSTGRES_DB}
  # Redis
  REDIS_URL: redis://infisical-dev-redis:6379
  # Website URL
  # Required
  SITE_URL: https://${ENV_PREFIX:-}infisical.int.university.edu

x-traefik_labels: &traefik_labels
  traefik.enable: true
  ## Minio Web console
  traefik.http.routers.infisical-https.rule: Host(`${ENV_PREFIX:-}infisical.int.university.edu`)
  traefik.http.routers.infisical-https.entrypoints: websecure
  traefik.http.routers.infisical-https.service: infisical-https
  traefik.http.services.infisical-https.loadbalancer.server.port: 8080
  traefik.http.routers.infisical-https.tls: true
  traefik.http.routers.infisical-https.tls.certresolver: sectigo
  # traefik.http.routers.infisical-https.tls.domains[0].main: ${ENV_PREFIX:-}infisical.int.university.edu
  ## Redirect HTTP to HTTPS
  traefik.http.middlewares.infisical-redirect-https.redirectscheme.scheme: https
  traefik.http.routers.infisical-http.middlewares: infisical-redirect-https
  traefik.http.routers.infisical-http.rule: Host(`${ENV_PREFIX:-}infisical.int.university.edu`)
  traefik.http.routers.infisical-http.entrypoints: web
  traefik.http.routers.infisical-http.service: infisical-https
services:
  db-migration:
    container_name: infisical-db-migration
    depends_on:
      db:
        condition: service_healthy
    image: infisical/infisical:latest-postgres
    environment: *environment
    command: npm run migration:latest
    pull_policy: always

  backend:
    container_name: infisical-backend
    labels: *traefik_labels
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      db-migration:
        condition: service_completed_successfully
    image: infisical/infisical:latest-postgres
    pull_policy: always
    environment:
      <<:
        - *environment
      NODE_ENV: production

  redis:
    image: redis
    container_name: infisical-dev-redis
    environment:
      <<:
        - *environment
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  db:
    container_name: infisical-db
    image: postgres:14-alpine
    restart: always
    environment: *environment
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10
volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
networks:
  default:
    name: $NETWORK
    external: true
```
