### ISSUE TITLE
Traefik 3.x can not download customized plugin

### ISSUE THREAD

**Issue by sim-wangyan** [traefik/traefik#10799]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I use three plugin: headers, traefik-plugin-jwt-antpath, stripprefix
Plugin of headers, stripprefix is ok
My customized plugin traefik-plugin-jwt-antpath can not work. But use traefik 2.x, every things is ok

### What did you see instead?

can see the log: load the plugin two times;  and can not found the plugin on the dashboard

### What version of Traefik are you using?

3.x

### What is your environment & configuration?

```yaml
experimental:
  plugins:
    traefik-plugin-jwt-antpath:
      moduleName: "github.com/x-ream/traefik-plugin-jwt-antpath"
      version: "v0.1.1"
```

### If applicable, please paste the log output in DEBUG level

2024-06-01T10:09:49Z DBG [github.com/traefik/traefik/v3/pkg/plugins/plugins.go:30](http://github.com/traefik/traefik/v3/pkg/plugins/plugins.go:30) > Loading of plugin: traefik-plugin-jwt-antpath: [github.com/x-ream/traefik-plugin-jwt-antpath@v0.1.1](http://github.com/x-ream/traefik-plugin-jwt-antpath@v0.1.1)
2024-06-01T10:09:49Z DBG [github.com/hashicorp/go-retryablehttp@v0.7.5/client.go:612](http://github.com/hashicorp/go-retryablehttp@v0.7.5/client.go:612) > Performing request method=GET url=https://plugins.traefik.io/public/download/github.com/x-ream/traefik-plugin-jwt-antpath/v0.1.1
2024-06-01T10:09:50Z DBG [github.com/hashicorp/go-retryablehttp@v0.7.5/client.go:612](http://github.com/hashicorp/go-retryablehttp@v0.7.5/client.go:612) > Performing request method=GET url=[https://plugins.traefik.io/public/validate/github.com/x-ream/traefik-plugin-jwt-antpath/v0.1.1 1](https://plugins.traefik.io/public/validate/github.com/x-ream/traefik-plugin-jwt-antpath/v0.1.1)
2024-06-01T10:09:50Z INF [github.com/traefik/traefik/v3/pkg/server/configurationwatcher.go:73](http://github.com/traefik/traefik/v3/pkg/server/configurationwatcher.go:73) > Starting provider aggregator aggregator.ProviderAggregator

**Comment by nmengin** [comment]
Hey @sim-wangyan,

Thanks for reaching out.

Could you provide a complete reproducible case (logs, router configuration)?
In the meantime time, could you check if your router is impacted by the rules matcher modification [between v2 and v3](https://doc.traefik.io/traefik/migration/v2-to-v3/#step-1-prepare-configurations-and-test-v3)?

**Comment by grider-withourai** [comment]
I'm having the same issue. With the same config, upgrade helm to app version 3.0.0 stop showing the middlewares on the admin dashboard and the middleware functionality stopped working.
Here is the log.
[logs-from-traefik-in-traefik-65755cfb4d-qsgb5.log](https://github.com/user-attachments/files/15878397/logs-from-traefik-in-traefik-65755cfb4d-qsgb5.log)
Helm values:
```
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`dashboard-traefik.abc.ai`)
    entryPoints: ["websecure"]
    middlewares:
      - name: traefik-dashboard-auth

extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: traefik-dashboard-auth-secret
      namespace: traefik
    type: kubernetes.io/basic-auth
    stringData:
      username: admin
      password: "xxx"

  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: traefik-dashboard-auth
      namespace: traefik
    spec:
      basicAuth:
        secret: traefik-dashboard-auth-secret

additionalArguments:
  - "--serverstransport.insecureskipverify=true"

providers:
  kubernetesIngress:
    publishedService:
      enabled: true # For external-dns to work

experimental:
  plugins:
    cloudflarewarp:
      moduleName: github.com/BetterCorp/cloudflarewarp
      version: v1.3.3
    headerdump:
      moduleName: github.com/jaybubs/headerdump
      version: v0.2.0
    path_auth_redirector:
      moduleName: github.com/WithourAI/path-auth-redirector
      version: v0.0.3

logs:
  general:
    level: DEBUG
  access:
    enabled: false
```
Middleware definitions are in CRDs:
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-cloudflarewarp
  namespace: traefik
spec:
  plugin:
    cloudflarewarp:
      disableDefault: "false"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: headerdump
  namespace: traefik
spec:
  plugin:
    headerdump:
      Prefix: "HDlog"
      TLS: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: llm-path-auth-redirector
  namespace: traefik
spec:
  plugin:
    path_auth_redirector:
      regex: "^/sk/(?P<token>[^/]+).*"
      redirect: ""
```

There is a ingress with the annotation
```
traefik.ingress.kubernetes.io/router.middlewares: "traefik-traefik-cloudflarewarp@kubernetescrd"
```
but the cloudflarewarp middleware was not loaded.
