### ISSUE TITLE
Can't upload docker images larger than 400MB or 2GB via traefik 3.0 3.0.1 3.0.2 proxy

### ISSUE THREAD

**Issue by code-wangshuyi** [traefik/traefik#10805]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

just simple proxy harbor http service

### What did you see instead?

the same issue https://github.com/traefik/traefik/issues/10741 but v2.10.0 work well

### What version of Traefik are you using?

Client: Docker Engine - Community
 Version:           24.0.4
 API version:       1.43
 Go version:        go1.20.5
 Git commit:        3713ee1
 Built:             Fri Jul  7 14:50:57 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.4
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.5
  Git commit:       4ffc614
  Built:            Fri Jul  7 14:50:57 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### What is your environment & configuration?

just simple proxy harbor http service

### If applicable, please paste the log output in DEBUG level

--log.level=DEBUG

**Comment by code-wangshuyi** [comment]
The push refers to repository [harbor.xxxx.com:8443/cuda/cuda]
d93d20af701b: Pushing [==================================================>]  2.367GB/2.367GB
b63c7fe2d89f: Layer already exists 
1a7b944dac25: Pushing [=====================>                             ]  2.012GB/4.709GB
8a741f0ee517: Layer already exists 
63296bbbf98b: Layer already exists 
980eb7f7bcb0: Layer already exists 
dbd5b7f451e3: Pushing [=======================================>           ]  1.919GB/2.418GB
f344b08ff6c5: Layer already exists 
86f0cc586e78: Layer already exists 
33e57ea5b30a: Layer already exists 
851dfeb18192: Layer already exists 
6c3e7df31590: Layer already exists 
error parsing HTTP 499 response body: invalid character 'C' looking for beginning of value: "Client Closed Request"

**Comment by code-wangshuyi** [comment]
the traefik conf files:

docker-compose file

**Comment by code-wangshuyi** [comment]
OK，I'll hava a try later.

**Comment by code-wangshuyi** [comment]
Thanks for your help! It works !  I have got some changes on the static conf file simillar to this BOLD configuration

``` toml
[api]
  insecure = true
  dashboard = true
  debug = true


[entryPoints]
  [entryPoints.web]
    address = ":{{ http_port }}"
    **[entryPoints.web.transport]
      [entryPoints.web.transport.respondingTimeouts]
        readTimeout = {{ entryPoints_web_transport_readTimeout }}
        writeTimeout = {{ entryPoints_web_transport_writeTimeout }}
        idleTimeout = {{ entryPoints_web_transport_idleTimeout }}**
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
  [entryPoints.websecure]
    address = ":{{ https_port }}"
    [entryPoints.websecure.transport]
      [entryPoints.websecure.transport.respondingTimeouts]
        **readTimeout = {{ entryPoints_websecure_transport_readTimeout }}
        writeTimeout = {{ entryPoints_websecure_transport_writeTimeout }}
        idleTimeout = {{ entryPoints_websecure_transport_idleTimeout }}**

[certificatesResolvers]
{% for resolver in traefik_certificatesResolvers %}
  [certificatesResolvers.{{ resolver.name }}]
    [certificatesResolvers.{{ resolver.name }}.acme]
      email = "wangwangjie88@gmail.com"
      storage = "/etc/traefik/acme/{{ resolver.name }}.json"
      certificatesDuration = 42
#      [certificatesResolvers.{{ resolver.name }}.acme.httpChallenge]
#        entryPoint = "web"
      [certificatesResolvers.{{ resolver.name }}.acme.dnsChallenge]
        provider = "alidns"
        delayBeforeCheck = 0
{% endfor %}



[providers]
  [providers.docker]
    exposedByDefault = true
  [providers.file]
    directory = "/etc/traefik/"
    watch = true
    filename = "traefik_dynamic.toml"
```
