### ISSUE TITLE
Support BackendTLSPolicy from Gateway API

### ISSUE THREAD

**Issue by justinrush** [traefik/traefik#10808]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

We are investigating a shift from NGINX w/ Ingress records to Traefik with Gateway API. All of the services that run in our cluster serve HTTP over TLS and use a certificate signed by an internal (to the cluster) root CA.

I can easily use the helm chart to have traefik request an internal cert from cert-manager and mount that secret into the pod and trust it via an env var - e.g.:

```yaml
volumes:
  - name: certmanager-issued-cert-for-traefik
    mountPath: /var/secrets/certs
    type: secret

env:
  - name: SSL_CERT_FILE
    value: /var/secrets/certs/ca.crt
```

However, gateway API requires that you use a [BackendTLSPolicy](https://gateway-api.sigs.k8s.io/api-types/backendtlspolicy/) to tell the Gateway provider that it should speak https to the backend and how to validate the certificate, e.g.:

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: tls-upstream-gort
spec:
  targetRefs:
    - kind: Service
      name: gort
      group: ""
  validation:
    wellKnownCACertificates: "System"
    hostname: gort
```

This API looks to like it may make it out of experimental in [Gateway API v1.2](https://github.com/kubernetes-sigs/gateway-api/discussions/3128#discussioncomment-9655022). Given that it is already on the third alpha and is supported on NGINX, Contour, and Envoy Gateway, I'm hoping this is something that can be included in traefik since we'll be unable to use traefik until it allows us to use https backends with Gateway API. I suspect I can figure out how IngressRoute works and use that instead, but migrating from one proprietary format (NGINX / ingress annotations) to another proprietary format doesn't really feel worth the effort... also it doesn't seem like work on the Kubernetes CRD is being prioritized, so we'd be blocked by https://github.com/traefik/traefik/issues/7097.
