### ISSUE TITLE
DownstreamStatus is 0 in v3 when server-sent event response is aborted from client

### ISSUE THREAD

**Issue by dj-shin** [traefik/traefik#10807]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

In Traefik v2.11, when client aborts server-sent events response stream, `DownstreamStatus` was `200` in the access log.
After upgrading to v3.0.0 the response itself is working as same as before, but in the access log `DownstreamStatus` is now logged as `0`.

### What did you see instead?

v2.11 access log:
```
{
  "@timestamp": "2024-06-12T07:35:16.316813044Z",
  "ClientUsername": "-",
  "DownstreamContentSize": 4493,
  "DownstreamStatus": 200,
  "Duration": 694375616,
  "GzipRatio": 0,
  "OriginContentSize": 0,
  "OriginDuration": 0,
  "OriginStatus": 0,
  "Overhead": 694375616,
  "RequestContentSize": 438,
  "RequestCount": 543,
  "RequestMethod": "POST",
  "RequestPath": "/v1/chat/completions",
  "RequestPort": "-",
  "RequestProtocol": "HTTP/1.1",
  "RequestScheme": "http",
  "RetryAttempts": 0,
  "StartLocal": "2024-06-12T07:35:15.622296575Z",
  "StartUTC": "2024-06-12T07:35:15.622296575Z",
  "downstream_Access-Control-Allow-Credentials": "REDACTED",
  "downstream_Content-Type": "REDACTED",
  "downstream_Date": "REDACTED",
  "downstream_Server": "REDACTED",
  "downstream_Vary": "REDACTED",
  "entryPointName": "inference-server",
  "level": "info",
  "msg": "",
  "request_Accept": "REDACTED",
  "request_Authorization": "REDACTED",
  "request_Content-Length": "REDACTED",
  "request_Content-Type": "REDACTED",
  "request_User-Agent": "REDACTED",
  "request_X-Amzn-Trace-Id": "REDACTED",
  "request_X-Forwarded-Host": "REDACTED",
  "request_X-Forwarded-Port": "REDACTED",
  "request_X-Forwarded-Proto": "REDACTED",
  "request_X-Forwarded-Server": "REDACTED",
  "request_X-Friendli-Model-Name": "meta-llama-3-8b-instruct",
  "request_X-Friendli-Team": "REDACTED",
  "request_X-Friendli-User": "REDACTED",
  "request_X-Real-Ip": "REDACTED",
  "request_X-Request-Id": "da53fa8d71fe4953928e12468f18ffd8",
  "time": "2024-06-12T07:35:16Z"
}
```

v3.0.2 access log:
```
{
  "@timestamp": "2024-06-12T07:48:16.096445637Z",
  "DownstreamContentSize": 0,
  "DownstreamStatus": 0,
  "Duration": 343245914,
  "OriginContentSize": 0,
  "OriginDuration": 0,
  "OriginStatus": 0,
  "Overhead": 343245914,
  "RequestContentSize": 0,
  "RequestCount": 2,
  "RequestMethod": "POST",
  "RequestPath": "/v1/chat/completions",
  "RequestPort": "-",
  "RequestProtocol": "HTTP/1.1",
  "RequestScheme": "http",
  "RetryAttempts": 0,
  "StartLocal": "2024-06-12T07:48:15.753032977Z",
  "StartUTC": "2024-06-12T07:48:15.753032977Z",
  "entryPointName": "inference-server",
  "level": "info",
  "msg": "",
  "request_Accept": "REDACTED",
  "request_Authorization": "REDACTED",
  "request_Content-Length": "REDACTED",
  "request_Content-Type": "REDACTED",
  "request_User-Agent": "REDACTED",
  "request_X-Amzn-Trace-Id": "REDACTED",
  "request_X-Forwarded-Host": "REDACTED",
  "request_X-Forwarded-Port": "REDACTED",
  "request_X-Forwarded-Proto": "REDACTED",
  "request_X-Forwarded-Server": "REDACTED",
  "request_X-Friendli-Model-Name": "meta-llama-3-8b-instruct",
  "request_X-Friendli-Team": "REDACTED",
  "request_X-Friendli-User": "REDACTED",
  "request_X-Real-Ip": "REDACTED",
  "request_X-Request-Id": "e37e4460614b428cbf4c1d474f1bdc5c",
  "time": "2024-06-12T07:48:16Z"
}
```

### What version of Traefik are you using?

Tested in v3.0.1 & v3.0.2 and both behaviors where same.
v2.11 works fine.

### What is your environment & configuration?

```yaml
apiVersion: v1
data:
  traefik.yaml: |
    providers:
      file:
        directory: /etc/traefik/
        watch: true
    entryPoints:
      traefik:
        address: :8080
      inference-server:
        address: :8090
        transport:
          lifeCycle:
            graceTimeOut: 3600s
    api:
      insecure: true
      dashboard: true
      debug: true
    metrics:
      prometheus:
        entryPoint: traefik
    accessLog:
      filePath: "/logs/access.jsonl"
      format: json
      fields:
        defaultMode: keep
        headers:
          defaultMode: redact
          names:
            X-Request-Id: keep
    ping:
      entryPoint: "inference-server"
    log:
      level: DEBUG
kind: ConfigMap
```

Add more configuration information here.

**Comment by dj-shin** [comment]
Hello @rtribotte, thank you for the fast check!

Here's our dynamic config:

```yaml
http:
  serversTransports:
    reuseConnection:
      maxIdleConnsPerHost: 5
      forwardingTimeouts:
        idleConnTimeout: 600s
  middlewares:
    CORS-Header:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
        accessControlAllowHeaders:
          - Authorization
          - Content-Type
        accessControlAllowOriginListRegex:
          - ...
        accessControlAllowCredentials: true
        accessControlMaxAge: 100
        addVaryHeader: true
  routers:
    router-test:
      entryPoints:
        - inference-server
      middlewares:
        - CORS-Header
        - auths
      service: test-cluster
      rule: PathPrefix(`/test`)
    router-inference:
      entryPoints:
      - inference-server
      middlewares:
      - CORS-Header
      - auths
      service: inference-cluster
      rule: PathPrefix(`/`)
  services:
    inference-cluster:
      loadBalancer:
        healthCheck:
          path: /ping
          interval: 15s
          timeout: 10s
        servers:
          - url: ...
        serversTransport: reuseConnection
    test-cluster:
      loadBalancer:
        servers:
        - url: ...
        serversTransport: reuseConnection
```
