### ISSUE TITLE
Dashboard JS  blocked because of a disallowed MIME type (“text/plain”)

### ISSUE THREAD

**Issue by ziqbal** [traefik/traefik#10826]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Loaded dashboard, viewed developer panel and see console and network requests

### What did you see instead?

Noticed blocked content in console and network traffic:

`
Loading module from “http://127.0.0.1:8080/dashboard/assets/_hacks.de068122.js” was blocked because of a disallowed MIME type (“text/plain”).
[dashboard](http://127.0.0.1:8080/dashboard/#/)
Loading module from “http://127.0.0.1:8080/dashboard/assets/_init.a396cff6.js” was blocked because of a disallowed MIME type (“text/plain”).
[dashboard](http://127.0.0.1:8080/dashboard/#/)
Loading failed for the module with source “http://127.0.0.1:8080/dashboard/assets/_hacks.de068122.js”. [dashboard:1:1022](http://127.0.0.1:8080/dashboard/#/)
Loading failed for the module with source “http://127.0.0.1:8080/dashboard/assets/_init.a396cff6.js”.
`

### What version of Traefik are you using?

3.0.3

### What is your environment & configuration?

Ubuntu 24.04 / Firefox 127.0

**Comment by rtribotte** [comment]
Hello @ziqbal,

Thanks for your interest in Traefik!

As mentioned in [the migration guide](https://doc.traefik.io/traefik/migration/v2-to-v3-details/#content-type-auto-detection):

```
In v3, the Content-Type header is not auto-detected anymore when it is not set by the backend. One should use the ContentType middleware to enable the Content-Type header value auto-detection.
```

Did you try to use the content-type middleware?

**Comment by ziqbal** [comment]
@rtribotte Maybe I was not clear - the console logs are for the builtin traefik dashboard.
Other internal js files are loaded fine without errors.

**Comment by nuxwin** [comment]
Any new regarding this issue ? I'm encountering the same issue, even through, there is not problem navigating in the Dashboard.

My setup for the dashboard is as follows (dynamic conffile):

```yaml
http:
  middlewares:
    authentication:
      basicAuth:
        users:
          - 'l.declercq@konzeptplus.ch:$apr1$jah9libv$JrCNNaYAmS8W9BAC/rX6j/'
    gzip:
      compress: true
    redirect-to-https:
      redirectScheme:
        scheme: https
    traefik-https:
      chain:
        middlewares:
          - authentication
          - gzip
  routers:
    traefik-http:
      entryPoints:
        - http
      middlewares:
        - redirect-to-https
      rule: Host(`traefik.srv01.konzeptplus-preview.ch`)
      service: api@internal
    traefik-https:
      entryPoints:
        - https
      middlewares:
        - traefik-https
      rule: Host(`traefik.srv01.konzeptplus-preview.ch`)
      service: api@internal
      tls:
        certResolver: letsencrypt
```

The errors in my FF console :  See the provided screenshot.
![Capture d’écran 2024-08-03 à 18 38 48](https://github.com/user-attachments/assets/3976d8b1-c7fa-4608-aa9d-ead814fc04a9)
