### ISSUE TITLE
StripPrefix not working in traefik3 but working in traefik2

### ISSUE THREAD

**Issue by zaphoodb** [traefik/traefik#10837]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I updated from traefik2 (2.11.5) to traefik3 (3.0.2). 
I'm running nextcloud on a sub-folder of my domain (domain.com/share) and I'm using StripPrefix http middleware as well as ForceSlash middleware with traefik2. Due to deprecation of "ForceSlash", I removed this in my traefik2 config for nextcloud. 

With traefik2 netxcloud works correctly even __without__ "ForceSlash" set to true. 

When I upgrade to traefik3, nextcloud stopps working and I'm getting 404 errors in the access log. 

### What did you see instead?

Not working anymore, getting 404 errors in the traefik log with traefik3. Same config is working with traefik2. 

### What version of Traefik are you using?

3.0.2

### What is your environment & configuration?

```yaml

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG
#  level: INFO

#metrics:
#  prometheus: true

accessLog:
  filePath: "/logs/access.log"

#experimental:
#  http3: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: https
  https:
    address: ":443"
    http:
      tls:
        certResolver: "myresolver"
    http3:
      advertisedPort: 443

# Docker configuration backend
providers:
  docker:
    exposedByDefault: false
    network: traefik
    # default network to connect to containers
    #defaultRule: "Host(`{{ trimPrefix `/` .Name }}.domain.tld`)"
  file:
    filename: "/config/dynamic-conf.yml"
# API and dashboard configuration
api:
  insecure: false
  dashboard: false

certificatesResolvers:
  myresolver:
    acme:
      httpChallenge:
        # used during the challenge
        entryPoint: http
      email: "webmaster@domain.com"
      storage: "/etc/traefik/acme/acme.json"
```

```
# Docker-compose.yml of traefik

services:
  traefik3:
#    image: traefik:2.11
    image: traefik:latest
    container_name: "traefik"
    hostname: "traefik"
    networks:
      - default
      - insecure
    restart: always
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/traefik.yml:/etc/traefik/traefik.yml
      - $PWD/config:/config
      - /data/acme:/etc/traefik/acme
      - /var/log/docker-container/traefik:/logs
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      - "TZ=Europe/Berlin"

networks:
  default:
    name: traefik
    external: true
  insecure:
    name: traefik-insecure
    external: true

```

```
# Nextcloud (just parts of the docker-compose.yml)

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.share.rule=Host(`domain.com`) && PathPrefix(`/share{regex:$$|/.*}`) || Host(`www.domain.com`) && PathPrefix(`/share{regex:$$|/.*}`)"
      - "traefik.http.routers.share.tls.certresolver=myresolver"
      - "traefik.http.routers.share.tls=true"
      - "traefik.http.services.share.loadbalancer.server.port=80"
# Middleware is called "strip-prefix and needs to be assigned to the router
      - "traefik.http.middlewares.strip-prefix-share.stripprefix.prefixes=/share"
#      - "traefik.http.middlewares.strip-prefix-share.stripprefix.forceSlash=true"
      - "traefik.http.routers.share.middlewares=strip-prefix-share@docker"


```
Add more configuration information here.
/

### If applicable, please paste the log output in DEBUG level

I'm not seeing those lines in traefik2 debug log, just traefik3: 

```
traefik  | 2024-06-21T21:01:31+02:00 DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:196 > Service selected by WRR: fade444c7a8144ce
traefik  | 2024-06-21T21:01:32+02:00 DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:196 > Service selected by WRR: 781b39536fa4762d
traefik  | 2024-06-21T21:01:32+02:00 DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:196 > Service selected by WRR: 781b39536fa4762d
traefik  | 2024-06-21T21:01:32+02:00 DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:196 > Service selected by WRR: 781b39536fa4762d
traefik  | 2024-06-21T21:01:33+02:00 DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:196 > Service selected by WRR: 781b39536fa4762d
```
