### ISSUE TITLE
certificatesDuration not honored when getting certs from internal StepCA

### ISSUE THREAD

**Issue by easpeagle** [traefik/traefik#10847]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We have configured traefik (3.0.3) to pull certificates from our internal StepCA, which has a default cert lifetime of 24h. When we use the `certificatesDuration` parameter to set say 48 or 72 hour duration, we expect to get certificates with those lifetimes. We use this same CA with tools such as acme.sh and can configure what lifetime we want up to 90d.

### What did you see instead?

What we see is that no matter what value we give to `certificatesDuration` we only get 24h+1m certs. I can clearly see in the StepCA pod logs for new-order transactions a request for:

`\"notBefore\":\"2024-06-25T21:30:14Z\",\"notAfter\":\"2024-06-26T21:31:14Z\"`

### What version of Traefik are you using?

```Version:      3.0.3
Codename:     beaufort
Go version:   go1.22.4
Built:        2024-06-18T14:31:20Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
version: '3'
services:
  traefik:
    container_name: traefik
    image: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.traefikresolver.acme.caserver=https://step.example.com/acme/acme/directory"
      - "--certificatesresolvers.traefikresolver.acme.certificatesDuration=48"
      - "--certificatesresolvers.traefikresolver.acme.email=support@example.com"
      - "--certificatesresolvers.traefikresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.traefikresolver.acme.tlschallenge=true"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - lb_web

networks:
  lb_web:
    external: true
```
