### ISSUE TITLE
Increased memory usage and memory leak in Traefik v3

### ISSUE THREAD

**Issue by Janhouse** [traefik/traefik#10859]
After upgrading to Traefik 3 (v3.0.3) I noticed it uses a lot more memory (`70 MB` vs `5 GB`) than v2 did. And it keeps increasing, indicating a possible memory leak.

![image](https://github.com/traefik/traefik/assets/1036439/c5973f42-5f97-4c68-a07b-5281a5c0285a)

Switching traefik container back to 2.11 fixes the issue.

I have 20 routers, 17 services and 12 middlewares (all HTTP). Most from docker container labels.

### What version of Traefik are you using?

3.0.3

### What is your environment & configuration?

traefik.yml
```yaml
metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
global:
  checkNewVersion: true
  sendAnonymousUsage: false
log:
  filePath: /var/log/traefik/traefik.log
  format: json
accessLog:
  filePath: /var/log/traefik/access.log
api:
  dashboard: true
  insecure: false
certificatesResolvers:
  le:
    acme:
      email: ***
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
      storage: /acme/acme.json
entryPoints:
  metrics:
    address: :8899
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
    http:
      tls:
        certResolver: le
    forwardedHeaders:
      trustedIPs:
        - ***
ping:
  entryPoint: websecure
providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: /etc/traefik
    watch: true

experimental:
  plugins:
    real-ip:
      moduleName: github.com/Paxxs/traefik-get-real-ip
      version: v1.0.3

```

dynamic.yml
```yaml
http:
  middlewares:
    test1:
      chain:
        middlewares:
          - compression
          - real-ip-plugin

    test2:
      retry:
        attempts: 1
        initialinterval: 100ms

    redirect-to-www:
      redirectregex:
        regex: ^https://(?:www\.)?(.*)
        replacement: https://www.$${1}

    auth:
      basicAuth:
        users:
          - "***"

    compression:
      compress:
        excludedContentTypes:
          - text/event-stream

    security:
      headers:
        accessControlAllowOriginList:
          - "*"

    real-ip-plugin:
      plugin:
        real-ip:
          Proxy:
            - proxyHeadername: ***
              proxyHeadervalue: ***
              realIP: ***
              OverwriteXFF: true
            - proxyHeadername: "*"
              realIP: ***

  serversTransports:
    insecure:
      insecureSkipVerify: true
```
docker-compose.yml

```yaml
networks:
  traefik:
    name: traefik
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24
          gateway: 192.168.3.1

services:
  traefik:
    #image: traefik:v2.11
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/:/etc/traefik/
      - ${DOCKER_DATA}/traefik/acme:/acme
      - ${DOCKER_DATA}/traefik/logs:/var/log/traefik
    environment:
      BASE_DOMAIN: ${BASE_DOMAIN}
      CF_ZONE_API_TOKEN: ${CF_ZONE_API_TOKEN}
      CLOUDFLARE_DNS_API_TOKEN: ${CF_ZONE_API_TOKEN}
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - traefik.http.routers.traefik.rule=Host(`traefik.${BASE_DOMAIN}`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.service=api@internal
      
      # Forward auth
      - traefik.http.middlewares.auth-traefik.forwardauth.address=http://authentik-outpost:9000/outpost.goauthentik.io/auth/traefik
      - traefik.http.middlewares.auth-traefik.forwardauth.trustForwardHeader=true
      - traefik.http.routers.traefik.middlewares=security@file, test1@file, auth-traefik@docker
      # Route logout pages
      - traefik.http.routers.traefik-auth.middlewares=security@file, test1@file
      - traefik.http.routers.traefik-auth.rule=Host(`traefik.${BASE_DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)
      - traefik.http.routers.traefik-auth.service=authentik-proxy@docker
      - traefik.http.routers.traefik-auth.entrypoints=websecure
      - traefik.http.routers.traefik-auth.tls.domains[0].main=${BASE_DOMAIN}
      - traefik.http.routers.traefik-auth.tls.domains[0].sans=*.${BASE_DOMAIN}

      - com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.scope=daily
```

**Comment by Janhouse** [comment]
I checked it on another server where v3.0.3 is running with almost the same configuration but even more routers and services, but it doesn't have that issue. Any recommendations on what to check?

**Comment by juliens** [comment]
Hello,

Could you share both configuration (static and dynamic) for the 2 use cases?
Could you try to enable the debug endpoints and to export pprof for heap (https://doc.traefik.io/traefik/operations/api/#debug)

enable debug endpoints by adding:
```
--api.debug
```

( if you are in an isolated environment, you should add --api.insecure to simplify the router configuration for this debug endpoints ) and then call

```
curl -o heap.pprof <traefik_ip>:<entrypoint_traefik_port>/debug/pprof/heap 
```

**Comment by joekrill** [comment]
I've been experiencing the same issue after upgrading to v3. Memory usage would just keep increasing until an OOM event. I found that when i set `watch: false` on the file provider, however, the problem went away. I'm not sure why exactly, as I haven't had a chance to investigate further, but perhaps try setting that to false and see if it helps?

**Comment by deyanp** [comment]
@joekrill does this setting work only if use config file?

I tried this:

![image](https://github.com/user-attachments/assets/572d22f9-562e-48ce-9817-f50c7a9bfc5e)

but got the error

`ERR Cannot start the provider *file.Provider error="error using file configuration provider, neither filename nor directory is defined"` ...

**Comment by deyanp** [comment]
Forgot to mention it seems we are also hit with the memory issue ..

**Comment by deyanp** [comment]
This is how it looks before upgrade/after upgrade to v3 (same command args for traefik):

![image](https://github.com/user-attachments/assets/dc3b6ebf-f47a-4466-b7d4-d5873f27ac1f)

**Comment by joekrill** [comment]
> `ERR Cannot start the provider *file.Provider error="error using file configuration provider, neither filename nor directory is defined"` ...

@deyanp I'm not sure, to be honest. I would try disabling it using the config file, instead. You must also be using the file provider in the first place, so if you don't even have it configured at all this won't matter.

**Comment by deyanp** [comment]
@joekrill , I do not have the file provider configured at all, so I guess your workaround is not applicable to me. 
Wondering how to get back to the very stable performance of Traefik v2 ...

**Comment by xuewenG** [comment]
@deyanp @Janhouse I also had a memory leak with the v3 version, when I removed the compress middleware the memory leak disappeared. Maybe you can try it.

**Comment by kris2kris** [comment]
> @deyanp @Janhouse I also had a memory leak with the v3 version, when I removed the compress middleware the memory leak disappeared. Maybe you can try it.

I have the same here

**Comment by Nowheresly** [comment]
I'm using traefik v3.1.2 and I'm experiencing the same issue with a high memory consumption. No issue in traefik v2.

**Comment by Janhouse** [comment]
> @deyanp @Janhouse I also had a memory leak with the v3 version, when I removed the compress middleware the memory leak disappeared. Maybe you can try it.

I downgraded to v2 since this already is a big issue and I can't just disable compression, but some other weird things were also happening with v3 and sadly I don't have that much time to hunt bugs. :slightly_smiling_face: 
Will check again once this gets fixed.

**Comment by aas47** [comment]
Seeing the same. Using Traefik 3.1.0.
Larger spike in memory usage with compression enabled.

**Comment by antoninarq** [comment]
Seeing same issue with Traefik 3.1.2. Seems related to the new zstd compression feature

Some local test showed high memory usage from the [klauspost/compress](https://git.hub.com/klauspost/compress) library. 

[Documentation](https://pkg.go.dev/github.com/klauspost/compress/zstd#readme-usage) seems to suggest avoid creating too many encoders and re-using them instead (see this [issue](https://github.com/klauspost/compress/issues/928))

```
Showing nodes accounting for 92.75MB, 81.54% of 113.74MB total
Dropped 140 nodes (cum <= 0.57MB)
Showing top 10 nodes out of 151
      flat  flat%   sum%        cum   cum%
      48MB 42.20% 42.20%       48MB 42.20%  github.com/klauspost/compress/zstd.(*fastBase).ensureHist
    9.58MB  8.42% 50.62%     9.58MB  8.42%  github.com/klauspost/compress/zstd.encoderOptions.encoder
```

**Comment by aas47** [comment]
Anyone from Traefik team looking at this? @juliens @nmengin

**Comment by juliens** [comment]
@aas47 needs more time to analyze. 
However, providing a pprof when the issue occurs could definitely help speed things up.

**Comment by toutvukantabu** [comment]
hello, i have  a similar problem memory consumption on traefi v3 @Janhouse , i 've inspecting your traefik configuration and i use Authentik sso , maybe a lead regarding our concern?

**Comment by nonodev96** [comment]
![image](https://github.com/user-attachments/assets/37818bb6-228e-40f6-93ed-dc3e5f2de4c6)

I have the same problem, I don't know how to debug.

If a log is needed, I have prometheus and grafana collecting metrics

**Comment by juliens** [comment]
Thank you all for your input and for sharing your experiences regarding the memory leak. After investigating on my end, I haven't been able to reproduce the memory leak issue with any compression method, including br and zstd. While it's true that compression does use additional memory, in my tests, memory usage returns to normal levels once traffic decreases.

However, there is one notable difference I would like to highlight between Traefik v2 and v3 regarding compression. In v2, only gzip was supported, whereas in v3, we added support for Brotli (br) and Zstandard (zstd). These newer compression algorithms are more memory-intensive compared to gzip. From my tests, I've observed that gzip consumes around 200MB, whereas Brotli and Zstandard can go up to 900MB.

To address this, a PR has been merged that introduces the ability to select which compression algorithms you want to enable. This feature will be available in the next major release, which is expected to be released very soon.

In the meantime, to further investigate this potential memory leak, could someone provide a complete reproducible case? This would greatly help us narrow down the issue. Ideally, here's what we would need:

 - Full Traefik configuration (including any middleware or specific settings related to compression).
 - Details about the backends you're using (e.g., type of services, behavior under load).
 - Traffic generation tool you're using to simulate load (e.g., curl, wrk, or other testing frameworks) and the exact parameters used during the tests.
 - If possible, any metrics or logs showing memory usage over time.

The more detailed the scenario, the quicker we can identify and resolve the issue.

**Comment by nmengin** [comment]
Hello @Janhouse,

Thank you for your feedback.

> traefik v3 ignoring wildcard cert config and leaking all internal subdomains to transparency logs by requesting cert for each separate subdomain, instead of using/updating the wildcard one.

Could you elaborate on the issues you are facing, please?

**Comment by Janhouse** [comment]
After some time of using v3 I noticed that my subdomains had appeared in transparency logs, after checking the acme file, I noticed it had acquired certs for each subdomain. I deleted them, started Traefik v3 again and they were requested again. Then I deleted the certs again, downgraded to Traefik v2 and it no longer reqested separate subdomain certs and used the wildcard one.
This was my 3rd or 4th big issue with v3 so I kind of gave up and did not spend more time debugging and reporting. I figured it was a beta quality release and I would not try v3 again for 6 to 12 months, or until thise other issues are solved first. I really like Traefik and v2 is great but tests apparently are missing a lot of scenarios.

**Comment by ttys3** [comment]
seems related to wasm

![image](https://github.com/user-attachments/assets/4c487cbf-b211-4b9e-9423-0f39e079e1a2)

**Comment by ttys3** [comment]
![pprof001](https://github.com/user-attachments/assets/f3cf4c12-027f-41ef-9302-9662aacf72da)

**Comment by cypx** [comment]
Same problem here with memory usage, version 3.1.5 seems to fix the problem but it come back with 3.1.6 (despite the improvements reported by changelog).

![Image](https://github.com/user-attachments/assets/6c88af9c-cf86-43a4-9cde-e36616b2fc2c)

No plugin used but a few middlewares (compress, basicauth, ratelimit, stripprefix....)

**Comment by deyanp** [comment]
Is this going to be finally fixed ? 3.1.7 (again?) has the problem?? Had to increase the memory limits yesterday for traefik pods to 500Mi due to hitting 300Mi and restarting a couple of times ... this has never been the case for traefik 2.x, it has always been very memory-efficient! 

No plugins, some middlewares, including compression ...

```
# https://doc.traefik.io/traefik/middlewares/http/compress/
# Enable gzip compression
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: compress-response
spec:
  compress: {}

```
