### ISSUE TITLE
http 3 does not work as expected on tcp backend service.

### ISSUE THREAD

**Issue by renothing** [traefik/traefik#10865]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

My traefik runs on docker, is used as my container service proxy
there are two types http service run on containers

A:  normal nginx container which serve local HTTP services
B:  several nginx containers running TCP stream proxy which proxy remote HTTPS service(like github etc)

there are two traefik enpoints at port 80 and 443.

What we expect is that both local HTTP and proxy HTTP service through TCP SNI proxy can run normally

### What did you see instead?

when I disable http 3, all jobs work fine as my expected. both service A and service B will be routed correctly.

but then I enable http3, 

only type A services work fine and http3 also work correctly.

all traffic to type B service will return 404 directly.
for example visit https://www.bbb.com will return 404

### What version of Traefik are you using?

```
Version:      3.0.3
Codename:     beaufort
Go version:   go1.22.4
Built:        2024-06-18T14:31:20Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

here are seagment of my traefik config
```yaml
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.reuseport=true"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.reuseport=true"
      - "--entrypoints.websecure.asdefault=true"
      - "--entrypoints.websecure.http.encodequerysemicolons=true"
     - "--entrypoints.websecure.http3=true"
      - "--entrypoints.websecure.http3.advertisedport=443"
      - "--entrypoints.websecure.forwardedheaders.insecure=true"
      .....
```
here is my type A service config seagment
```yaml
    labels:
      traefik.enable: "true"
      traefik.http.routers.fakesite.entrypoints: "websecure"
      traefik.http.routers.fakesite.rule: 'HostRegexp(`(?i)^img(1|2|3)?\.aaa\.net$`)'
      traefik.http.routers.fakesite.service: "fakesite"
      traefik.http.services.fakesite.loadbalancer.server.port: 80
      traefik.http.routers.fakesite.tls: "true"
      traefik.http.routers.fakesite.tls.certresolver: "le"
      ...
```
here is my type B service config seagment
```yaml
    labels:
      traefik.enable: "true"
      traefik.tcp.routers.cfproxy.entrypoints: "websecure"
      traefik.tcp.routers.cfproxy.rule: 'HostSNIRegexp(`(?i)^((.+\.)?bbb.com|(.+\.)?github\.com)$`)'
      traefik.tcp.routers.cfproxy.service: "cfproxy"
      traefik.tcp.services.cfproxy.loadbalancer.server.port: 4432
      traefik.tcp.routers.cfproxy.tls: "true"
      traefik.tcp.routers.cfproxy.tls.passthrough: "true"
      ......
```

### If applicable, please paste the log output in DEBUG level

172.19.0.1 - - [29/Jun/2024:10:20:47 +0000] "GET / HTTP/3.0" 404 19 "-" "-" 1 "-" "-" 0ms
172.19.0.1 - - [29/Jun/2024:10:20:47 +0000] "GET /favicon.ico HTTP/3.0" 404 19 "-" "-" 2 "-" "-" 0ms

### Question

Is it because http3 runs on udp, and udp does not implement HostSNIRegexp?

**Comment by nmengin** [comment]
Hello @renothing,

Thanks for reaching out!
To keep the repository focused, we ask that all questions be asked in the [community forum](https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there.  If not, you can ask and get help from other community members pretty quickly.

**Comment by nmengin** [comment]
Hey @renothing,

Could you provide a minimal reproducible case?

**Comment by leonboot** [comment]
I'm having a similar issue, probably related, but it does not seem to be related to HTTP/3.

I have a setup where I have a Docker setup for development. Docker services get exposed by setting Traefik labels on certain services and are accessible on `*.docker` domains which get resolved locally.
Besides this, I have a MAMP Pro installation, which I also want to have routed through Traefik. I have the following configuration for this:

```yaml
tcp:

  services:
    mamp-apache-tls:
      loadBalancer:
        servers:
          - address: "host.docker.internal:8890"

  routers:
    mamp-tls:
      rule: "HostSNIRegexp(`{domain:.+}.mamp`)"
      service: mamp-apache-tls@file
      entrypoints: ["https"]
      tls:
        passthrough: true

http:

  services:
    mamp-apache:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8888"

  routers:
    mamp:
      rule: "HostRegexp(`{domain:.+}.mamp`)"
      service: mamp-apache@file
      entrypoints: ["http"]
```
The HTTPS entrypoint is configured as follows:
```yaml
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
    http:
      tls:
        certResolver: step-ca
```
The `step-ca` certificate resolver is a local ACME service that issues certificates for my `*.docker` URL's.

MAMP listens on port 8888 for HTTP and 8890 for HTTPS. For HTTPS I use a TCP router, as I want to use MAMP's SSL configuration (MAMP generates a root CA which it installs in the trusted certificates, and uses that to sign certificates for all sites that have SSL enabled).

This setup works fine with Traefik 2, but fails on both Traefik 3.0 and 3.1. When I access `https://some.url.mamp` using Traefik 2, I get a working website with a certificate signed by MAMP's root CA. When using Traefik 3, I get the Traefik self signed certificate and the `404 page not found` error from Traefik. The logs show the following information:

```router-1  | 2024-08-22T11:14:59+02:00 DBG github.com/traefik/traefik/v3/pkg/server/service/tcp/service.go:95 > Creating TCP server entryPointName=https routerName=mamp-tls@file serviceName=mamp-apache-tls@file
router-1  | 2024-08-22T11:14:59+02:00 DBG github.com/traefik/traefik/v3/pkg/server/router/tcp/manager.go:332 > Adding Passthrough route for "HostSNIRegexp(`{domain:.+}.mamp`)" entryPointName=https routerName=mamp-tls@file


router-1  | 2024-08-22T11:15:10+02:00 DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "served.by.mamp"
router-1  | 2024-08-22T11:15:10+02:00 DBG log/log.go:245 > http: TLS handshake error from 172.26.0.1:58728: remote error: tls: bad certificate
router-1  | 2024-08-22T11:15:10+02:00 DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "served.by.mamp"
router-1  | 2024-08-22T11:15:10+02:00 DBG log/log.go:245 > http: TLS handshake error from 172.26.0.1:58742: remote error: tls: bad certificate
router-1  | 2024-08-22T11:15:17+02:00 DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "served.by.mamp"
router-1  | 172.26.0.1 - - [22/Aug/2024:09:15:17 +0000] "GET / HTTP/2.0" 404 19 "-" "-" 1 "-" "-" 0ms
```

Maybe the `remote error: tls: bad certificate` is a pointer? If Traefik tries to validate the upstream certificate, that will likely fail, as it is a certificate signed by an unknown CA.
