### ISSUE TITLE
Passing ACME http-01 challenge requests to services stopped working v3.0

### ISSUE THREAD

**Issue by Feelemoon** [traefik/traefik#10861]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Some services behind traefik want to run their own ACME client. This worked fine with traefik v2.x, but isn't working anymore with v3.0. The ACME http challenge request is always intercepted by traefik, regardless of the router priority. Even if a matching challenge isn't found, the request won't be passed downstream. I've increased it to MaxInt - 1000, but this didn't change anything.

### What did you see instead?

Increasing the router priority does not work anymore. This seems to be related to this commit:
https://github.com/traefik/traefik/commit/1e7dbc70a0a28f4ad7bed92d845faecdf2cb97d9

### What version of Traefik are you using?

From `docker inspect`:

```
                "org.opencontainers.image.description": "A modern reverse-proxy",
                "org.opencontainers.image.documentation": "https://docs.traefik.io",
                "org.opencontainers.image.source": "https://github.com/traefik/traefik",
                "org.opencontainers.image.title": "Traefik",
                "org.opencontainers.image.url": "https://traefik.io",
                "org.opencontainers.image.vendor": "Traefik Labs",
                "org.opencontainers.image.version": "v3.0.3"
```

### What is your environment & configuration?

```yaml
http:
  router:
    acmeRouter:
      entryPoints: ["web"]
      rule: "Host(`acme.example.com`) && PathPrefix(`/.well-known/acme-challenge/`)"
      middlewares:
        - serverHeader
      priority: 4294967296
      service: acmeService
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

```
2024-06-28T08:00:08Z DBG github.com/traefik/traefik/v3/pkg/provider/acme/challenge_http.go:104 > Retrieving the ACME challenge for acme.example.com (token "tCPN5wxK_3tUNtJZHFlulA")... providerName=acme
2024-06-28T08:00:08Z ERR github.com/traefik/traefik/v3/pkg/provider/acme/challenge_http.go:110 > Cannot retrieve the ACME challenge for acme.example.com (token "tCPN5wxK_3tUNtJZHFlulA") providerName=acme
```
