### ISSUE TITLE
Traefik memory leak

### ISSUE THREAD

**Issue by amit-gshe** [traefik/traefik#10864]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

check the pod memory and open the debug api

### What did you see instead?

![image](https://github.com/traefik/traefik/assets/7383028/aef2ecc0-7a31-40eb-b873-3dfe53ee5803)

### What version of Traefik are you using?

2.11.2

### What is your environment & configuration?

```yaml
      --serversTransport.forwardingTimeouts.responseHeaderTimeout=10s                                                                
      --entryPoints.web.proxyProtocol.insecure                                                                                       
      --entryPoints.web.forwardedHeaders.insecure                                                                                    
      --accesslog.filters.statuscodes=500-599                                                                                        
      --accesslog.fields.defaultmode=keep                                                                                                  --accesslog.fields.headers.defaultmode=keep                                                                                    
      --entryPoints.web.transport.keepAliveMaxTime=600s                                                                              
      --entryPoints.web.transport.keepAliveMaxRequests=1024                                                                                --entryPoints.web.transport.respondingTimeouts.writeTimeout=10                                                                 
      --entryPoints.websecure.transport.keepAliveMaxTime=600s                                                                        
      --entryPoints.websecure.transport.keepAliveMaxRequests=1024                                                                    
      --entryPoints.websecure.transport.respondingTimeouts.writeTimeout=10                                                           
      --api=true                                                                                                                     
      --api.debug=true                                                                                                               
      --api.insecure=true                                                                                                            
      --entrypoints.metrics.address=:9100/tcp                                                                                        
      --entrypoints.traefik.address=:9000/tcp                                                                                        
      --entrypoints.web.address=:8000/tcp                                                                                            
      --entrypoints.websecure.address=:8443/tcp                                                                                      
      --api.dashboard=true                                                                                                           
      --ping=true                                                                                                                    
      --metrics.prometheus=true                                                                                                      
      --metrics.prometheus.entrypoint=metrics                                                                                        
      --providers.kubernetescrd                                                                                                      
      --providers.kubernetescrd.allowCrossNamespace=true                                                                             
      --providers.kubernetescrd.allowExternalNameServices=true                                                                       
      --providers.kubernetesingress                                                                                                  
      --entrypoints.websecure.http.tls=true                                                                                          
      --log.level=DEBUG                                                                                                              
      --accesslog=true                                                                                                               
      --accesslog.fields.defaultmode=keep                                                                                            
      --accesslog.fields.headers.defaultmode=drop                                                                                    
      --accesslog.fields.headers.names.User-Agent=keep             
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

![profile001](https://github.com/traefik/traefik/assets/7383028/a9aa9954-2c87-4c52-8cc7-a242922a2503)
![profile002](https://github.com/traefik/traefik/assets/7383028/8c9fca23-462d-4cce-8654-87cae25aff85)

**Comment by amit-gshe** [comment]
Additional context: we are using TraefikService to do pressure test by sending weighted traffic from EKS to OKE. Like below:

![image](https://github.com/traefik/traefik/assets/7383028/b1c4bd3c-61f4-4a34-8bec-b8666977c9ae)
The TraefikService defination:
```
apiVersion: traefik.containo.us/v1alpha1                                                                                                                                                                               
kind: TraefikService                                                                                                                                                                                                   
metadata:                                                                                                                                                                                                                                                                                                                                                                                 
  name: app-server-traefik-service                                                                                                                                                                                                 namespace: default                                                                                                                                                                                                                        
spec:                                                                                                                                                                                                                  
  weighted:                                                                                                                                                                                                            
    services:                                                                                                                                                                                                          
    - name: externalname-app                                                                                                                                                                                        
      port: 80                                                                                                                                                                                                               weight: 30                                                                                                                                                                                                       
    - name: app-server                                                                                                                                                                                           
      port: 80                                                                                                                                                                                                         
      weight: 80  
```
We found that the received http2 request in EKS traefik get changed to http1.1 in OKE cluster from OKE's traefik access log. It's very strange that the memory of OKE traefik continues to increase up to OOM. It get normal when we test http2 traffic in OKE.

**Comment by lbenguigui** [comment]
Hello @amit-gshe ,

Thanks for your interest in Traefik.

To conduct a more accurate comparison, please send us complete pprof archive generated on the same setup at different intervals.

Ideally, to be able to dig further into this issue, can you send us a minimal reproducible setup?

**Comment by amit-gshe** [comment]
Thanks,
We have released our cluster in aws so we can not provide continus pprof files. I can only provide some pprof files that was captured during that migration. 
And I think it is difficult to give a mininal reproducible setup without the heavy load.
[pprof.zip](https://github.com/user-attachments/files/16100368/pprof.zip)

**Comment by lbenguigui** [comment]
Hello @amit-gshe,

Thank you for your response. After analyzing your latest pprof archive, we didn't identify any particular issues indicating a potential leak. To investigate further, we need a reproducible setup.

**Comment by i5-650** [comment]
Hello,

I encountered a similar issue (on a smaller scale).

The architecture consists of a Raspberry Pi 5 that hosts Traefik and a simple file uploader written in PHP.

Raspberry Pi 5 details:
```
$ uname -a
Linux rpi5 6.6.31+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux
```
Traefik (v3.1.2, image id: dfdbdfae3fb3) :
```yml
services:
    traefik-server:
        image: traefik:3.1.2
        container_name: traefik-server
        restart: unless-stopped
        dns: 1.1.1.1
        command:
            # Global
            - --global.sendanonymoususage=false
            - --global.checknewversion=false
            - --serverstransport.insecureskipverify=true
            - --api.debug=true
            # Logs
            - --log.level=DEBUG
            - --log.filepath=/logs/traefik.log
            - --accesslog=true
            - --accesslog.filepath=/logs/access.log
            # Providers - Docker
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            # Providers - file
            - --providers.file=true
            - --providers.file.watch=true
            - --providers.file.directory=/config
            # Entrypoint - HTTP
            - --entrypoints.http.address=:80
            - --entrypoints.http.http.redirections.entrypoint.to=https
            - --entrypoints.http.http.redirections.entrypoint.scheme=https
            - --entrypoints.http.http.redirections.entrypoint.permanent=true
            # Entrypoint - HTTPS
            - --entrypoints.https.address=:443
            - --entrypoints.https.http.tls=true
            # Dashboard
            - --api.dashboard=true
            # Plugin - Coraza
            - --experimental.plugins.coraza.moduleName=github.com/jcchavezs/coraza-http-wasm-traefik
            - --experimental.plugins.coraza.version=v0.2.2
            # Plugin - Cloudflare Warp
            - --experimental.plugins.cloudflarewarp.moduleName=github.com/BetterCorp/cloudflarewarp
            - --experimental.plugins.cloudflarewarp.version=v1.3.0
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik.d/config/:/config/:ro
            - ./traefik.d/data/:/data/:rw
            - ./traefik.d/logs/:/logs/:rw
        networks:
            - traefik
        ports:
            - "80:80"
            - "443:443"
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.traefik.loadbalancer.server.port=443"
            - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DASHBOARD_DOMAIN:?}`)"
            - "traefik.http.routers.traefik.service=api@internal"
            - "traefik.http.routers.traefik.entrypoints=https"
            - "traefik.http.routers.traefik.middlewares=traefik-auth@docker"
            - "traefik.http.routers.traefik.tls=true"
            - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_AUTH:?}"
            - "traefik.http.middlewares.traefik-auth.basicauth.removeHeader=true"

networks:
    traefik:
        external: true
```

Plugins:
```yml
# cloudflarewarp.yml
http:
    middlewares:
        cloudflarewarp:
            plugin:
                cloudflarewarp:
                    disableDefault: false

# coraza.yml
http:
    middlewares: 
        coraza-owasp:
            plugin: 
                coraza:
                    directives: 
                        - Include @coraza.conf-recommended
                        - Include @crs-setup.conf.example
                        - Include @owasp_crs/*.conf
                        # TODO issue / pr to fix the issue linked to this
                        - SecRequestBodyAccess Off
                        # - SecRuleRemoveByTag 'OWASP_CRS/POLICY/SIZE_LIMIT'
                        - SecRuleEngine On
```

This configuration is also available on my [github](https://github.com/i5-650/traefik-conf). 

I created two `pprof` dumps: one at the starting of my traefik and another after a significant increase of memory usage. 

[pprofs.zip](https://github.com/user-attachments/files/16841077/pprofs.zip)

> Note: `allocs-start.pprof` was taken about 3 minutes after the service started, and `allocs-1.96Gb.pprof` was taken after the memory usage increased. The 1.96 GB refers to the total memory usage on my Raspberry Pi 5, not the size of the file.
