### ISSUE TITLE
defaultRule migrate from v2 to v3 ("error while adding rule Host: unexpected number of parameters; got 2, expected one of [1])

### ISSUE THREAD

**Issue by XENNOK** [traefik/traefik#10882]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I wanted to migrate from v2 to v3 and everything seems to work except defaultRule.
I had the following rule in place:
`defaultRule: "Host(`{{ index .Labels com.docker.compose.service}}.{{env DOMAIN0}}`,`{{ index .Labels com.docker.compose.service}}.{{env DOMAIN1}}`)"`

now I changed it in the way to make it compatible with v3:
`defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\"}}.{{env \"DOMAIN0\"}}`)"`

(it needs the escaped quotations... took me 30-45 minutes to figure this out for v3.)

Now I wanted to add the second subdomain and made this line:

`defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\"}}.{{env \"DOMAIN0\"}}`,`{{ index .Labels \"com.docker.compose.service\"}}.{{env \"DOMAIN1\"}}`)"
`

### What did you see instead?

The result is this error:
2024-07-05T23:28:25+02:00 ERR github.com/traefik/traefik/v3/pkg/server/router/router.go:150 > error="error while adding rule Host(`traefik.lab.XXX.de`,`traefik.YYY.de`): error while adding rule Host: unexpected number of parameters; got 2, expected one of [1]" entryPointName=web routerName=web-traefik@docker

### What version of Traefik are you using?

[v3.1.0-rc3](https://github.com/traefik/traefik/releases/tag/v3.1.0-rc3)

### What is your environment & configuration?

```yaml
providers:
  docker:
    watch: true
    #network: traefik
    endpoint: "unix:///var/run/docker.sock"
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\"}}.{{env \"DOMAIN0\"}}`,`{{ index .Labels \"com.docker.compose.service\"}}.{{env \"DOMAIN1\"}}`)"
    httpClientTimeout: 60
    exposedByDefault: false
  file:
    # watch for dynamic configuration changes
    directory: /etc/traefik/traefik.d
    watch: true
```

### If applicable, please paste the log output in DEBUG level

2024-07-05T23:28:25+02:00 ERR github.com/traefik/traefik/v3/pkg/server/router/router.go:150 > error="error while adding rule Host(`traefik.lab.XXX.de`,`traefik.YYY.de`): error while adding rule Host: unexpected number of parameters; got 2, expected one of [1]" entryPointName=web routerName=web-traefik@docker
2024-07-05T23:28:25+02:00 DBG github.com/traefik/traefik/v3/pkg/middlewares/recovery/recovery.go:22 > Creating middleware entryPointName=web middlewareName=traefik-internal-recovery middlewareType=Recovery
