### ISSUE TITLE
ServiceURL format in access logs

### ISSUE THREAD

**Issue by r3kzi** [traefik/traefik#10891]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Using docker compose:

```yaml
version: "3.3"

services:

  traefik:
    image: "traefik:v3.0.4"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--accesslog=true"
      - "--accesslog.format=json"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
 ```

With `traefik:v2.11` the generated access logs formats `ServiceURL` as an *Object*:
```json
{
"RouterName":"whoami@docker",
"ServiceAddr":"172.27.0.3:80",
"ServiceName":"whoami-041-traefik@docker",
"ServiceURL":{"Scheme":"http","Opaque":"","User":null,"Host":"172.27.0.3:80","Path":"","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},
"StartLocal":"2024-07-09T06:54:54.724774395Z",
"StartUTC":"2024-07-09T06:54:54.724774395Z"
}  
```

With `traefik:v3.0` the generated access logs formats `ServiceURL` as an *String*:
```json
{
"RouterName":"whoami@docker",
"ServiceAddr":"172.27.0.3:80",
"ServiceName":"whoami-041-traefik@docker",
"ServiceURL":"http://172.27.0.3:80",
"StartLocal":"2024-07-09T06:54:17.963729346Z",
"StartUTC":"2024-07-09T06:54:17.963729346Z",
}  
```

I could not find any changelog entries for this behavoir and this is causing problems regarding our Index Templates in Elasticsearch that expect an JSON object.

### What did you see instead?

See difference in access logs format above

### What version of Traefik are you using?

3.0 vs. 2.11

### What is your environment & configuration?

See docker compose yaml above

### If applicable, please paste the log output in DEBUG level

Not applicable
