### ISSUE TITLE
Authorisation header gets added to every second request

### ISSUE THREAD

**Issue by benkeil** [traefik/traefik#10899]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Every second request from my paperless-nix instance gets an `Authorisation: basic xxx` header added, which in the end fail.

### What did you see instead?

By adding the `- "traefik.http.middlewares.paperless-workaround.headers.customrequestheaders.authorization="` label to the web server labels I could solve the issue.

### What version of Traefik are you using?

```
Version:      3.0.4
Codename:     beaufort
Go version:   go1.22.4
Built:        2024-07-02T13:46:37Z
OS/Arch:      linux/arm64
```

### What is your environment & configuration?

```yaml
services:
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      #- "--ping=true"
      - "--api=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=tcp://dockerproxy:2375"
      - "--providers.docker.network=paperless_external"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.email=${EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      #- "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    labels:
      traefik.enable: true
      traefik.http.routers.traefik-secure.rule: Host(`traefik.${DOMAIN}`)
      traefik.http.routers.traefik-secure.entrypoints: websecure
      traefik.http.routers.traefik-secure.service: api@internal
      traefik.http.routers.traefik-secure.tls: true
      traefik.http.routers.traefik-secure.tls.certresolver: letsencrypt
      traefik.http.routers.traefik-secure.middlewares: dashboard-auth
      traefik.http.middlewares.dashboard-auth.basicauth.users: "${TRAEFIK_USER}:${TRAEFIK_PASSWORD_HASH}"
      traefik.http.middlewares.dashboard-auth.basicauth.removeheader: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/mnt/documents/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    security_opt:
      - no-new-privileges=true
    networks:
      - external

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    volumes:
      - /mnt/documents/data:/usr/src/paperless/data
      - /mnt/documents/media:/usr/src/paperless/media
      - /mnt/documents/export:/usr/src/paperless/export
      - /mnt/documents/consume:/usr/src/paperless/consume
      - /mnt/documents/trash:/usr/src/paperless/trash
      - /mnt/documents/logs:/usr/src/paperless/logs
      - /mnt/documents/custom-cont-init.d:/custom-cont-init.d:ro
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.paperless.entrypoints=websecure"
      - "traefik.http.routers.paperless.service=paperless"
      - "traefik.http.routers.paperless.tls=true"
      - "traefik.http.routers.paperless.tls.certresolver=letsencrypt"
      - "traefik.http.routers.paperless.middlewares=paperless-cors,paperless-workaround"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.paperless-cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.paperless-cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.paperless-cors.headers.accesscontrolalloworiginlist=${DOMAIN}"
      - "traefik.http.middlewares.paperless-cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.paperless-cors.headers.addvaryheader=true"
      - "traefik.http.middlewares.paperless-workaround.headers.customrequestheaders.authorization="
    networks:
      - internal
      - external
```
