### ISSUE TITLE
Traefik Ingress Controller Fails with 404 errors due to plugin download failure

### ISSUE THREAD

**Issue by bmagic** [traefik/traefik#10900]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have found an issue raised in the forum : [Failed to download plugin caused all services to go down](https://community.traefik.io/t/failed-to-download-plugin-caused-all-services-to-go-down/17717).

I also noticed that if Traefik fails to download the modules at startup, it will consistently return 404 errors. 
On Kubernetes during a rollout of a deployment traefik, if a traefik cannot download the plugin (for any reason) then it will be ready (healthy) and always return 404.

### What did you see instead?

Wouldn't it be simpler to SIGTERM the process to ensure that the traefik (which isn't healthy without its plugins) doesn't become ready?

What is the best course of action in this scenario: building our own Docker image with the plugins included, or a PR modifying Traefik to stop if it fails to download the plugin?

### What version of Traefik are you using?

Version:      3.0.4
Codename:     beaufort
Go version:   go1.22.4
Built:        2024-07-02T13:46:37Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

Helm release 
```yaml
experimental:
  plugins:
    traefik-responsebodyrewrite:
      moduleName: github.com/quortex/traefik-responsebodyrewrite
      version: v0.0.2
    traefik-responseheadersfilter:
      moduleName: github.com/quortex/traefik-responseheadersfilter
      version: v0.0.2
[...]
ports:
  web:
    middlewares:
      - kube-system-traefik-external-compression@kubernetescrd # Compress requests with the corresponding middleware
      - kube-system-traefik-external-responseheadersfilter@kubernetescrd # Remove unwanted headers
      - kube-system-traefik-external-responsebodyrewrite@kubernetescrd # Rewrite response body
```
