### ISSUE TITLE
[Bug] ping log in Accesslog

### ISSUE THREAD

**Issue by changhyuni** [traefik/traefik#10915]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

The ping log is checked even though accesslog is true and addInternal is false.

### What did you see instead?

ping log in accesslog

### What version of Traefik are you using?

EKS - Kubernetes 1.27
Traefik 3.0.1
Helm Chart 29.0.0

### What is your environment & configuration?

```yaml
        - '--log.level=DEBUG'
        - '--accesslog=true'
```

### If applicable, please paste the log output in DEBUG level

 - - [18/Jul/2024:07:47:25 +0000] "GET /ping HTTP/1.1" 404 19 "-" "-" 4 "-" "-" 0ms
 - - [18/Jul/2024:07:47:25 +0000] "GET /ping HTTP/1.1" 404 19 "-" "-" 5 "-" "-" 0ms
- - [18/Jul/2024:07:47:25 +0000] "GET /ping HTTP/1.1" 404 19 "-" "-" 6 "-" "-" 0ms
 - - [18/Jul/2024:07:47:27 +0000] "GET /ping HTTP/1.1" 404 19 "-" "-" 7 "-" "-" 0ms
- - [18/Jul/2024:07:47:27 +0000] "GET /ping HTTP/1.1" 404 19 "-" "-" 8 "-" "-" 0ms
- - [18/Jul/2024:07:47:27 +0000] "GET /ping HTTP/1.1" 404 19 "-" "-" 9 "-" "-" 0ms
- - [18/Jul/2024:07:47:30 +0000] "GET /ping HTTP/1.1" 404 19 "-" "-" 10 "-" "-" 0ms
 - - [18/Jul/2024:07:47:30 +0000] "GET /ping HTTP/1.1" 404 19 "-" "-" 11 "-" "-" 0ms
 - - [18/Jul/2024:07:47:30 +0000] "GET /ping HTTP/1.1" 404 19 "-" "-" 12 "-" "-" 0ms

**Comment by nmengin** [comment]
Hello @changhyuni,

Thanks for reaching out.
Could you provide a minimal reproducible case (for instance, full Kubernetes and Helm manifest to reproduce the issue)?

**Comment by changhyuni** [comment]
@nmengin 
Thanks you for asking.
this is my manifest
```yaml
apiVersion: v1
kind: Pod
metadata:
spec:
  containers:
    - args:
        - '--global.checknewversion'
        - '--global.sendanonymoususage'
        - '--entryPoints.api-gw.address=:8081/tcp'
        - '--entryPoints.metrics.address=:9100/tcp'
        - '--entryPoints.traefik.address=:8080/tcp'
        - '--entryPoints.web.address=:8000/tcp'
        - '--entryPoints.websecure.address=:8443/tcp'
        - '--api.dashboard=true'
        - '--ping=true'
        - '--providers.kubernetescrd'
        - '--providers.kubernetescrd.allowCrossNamespace=true'
        - '--providers.kubernetescrd.allowExternalNameServices=true'
        - '--providers.kubernetescrd.allowEmptyServices=true'
        - '--providers.kubernetesingress'
        - '--log.level=INFO'
        - '--api.dashboard=true'
        - '--api.insecure=true'
        - '--log.level=DEBUG'
        - '--accesslog=true'
        - '--accesslog.fields.defaultmode=keep'
        - '--serversTransport.insecureSkipVerify=true'
        - '--entryPoints.web.forwardedHeaders.trustedIPs=10.0.0.0/8'
        - '--entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.0.0/8'
        - '--entryPoints.api-gw.forwardedHeaders.trustedIPs=10.0.0.0/8'
        - '--tracing.otlp.http.endpoint=http://$(DD_AGENT_HOST):4318'
      env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              divisor: '1'
              resource: limits.cpu
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              divisor: '1'
              resource: limits.memory
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /ping
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 2
        periodSeconds: 300
        successThreshold: 1
        timeoutSeconds: 2
      name: system-utils-traefik
      ports:
        - containerPort: 8081
          name: api-gw
          protocol: TCP
        - containerPort: 9100
          name: metrics
          protocol: TCP
        - containerPort: 8080
          name: traefik
          protocol: TCP
        - containerPort: 8000
          name: web
          protocol: TCP
        - containerPort: 8443
          name: websecure
          protocol: TCP
      readinessProbe:
        failureThreshold: 1
        httpGet:
          path: /ping
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 2
        periodSeconds: 300
        successThreshold: 1
        timeoutSeconds: 2
      resources:
        limits:
          cpu: '1'
          memory: 1Gi
        requests:
          cpu: '1'
          memory: 1Gi

```
