### ISSUE TITLE
[Bug] APM data is not ingested into DATADOG using OTLP

### ISSUE THREAD

**Issue by changhyuni** [traefik/traefik#10916]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

APM data is not ingested into DATADOG using OTLP

### What did you see instead?

No data received datadog log

### What version of Traefik are you using?

traefik 3.0.1
eks - kubernetes 1.27
helm chart 29.0.0

### What is your environment & configuration?

```yaml
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
      - '--tracing.otlp.http.endpoint=http://$(DD_AGENT_HOST):4318' (traefik args)
```
```yaml
  datadog:
    otlp:
      receiver:
        protocols:
          http:
            enabled: true
            endpoint: "0.0.0.0:4318"
            useHostPort: true
```
