### ISSUE TITLE
Add possibility to select or deactivate compression algorithms in compress middleware

### ISSUE THREAD

**Issue by wollomatic** [traefik/traefik#10927]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

First of all, thanks for implementing brotli and zstd.

Sadly, some firewalls don't support zstd compression yet, so websites using Traefik 3.1 with the compress middleware can cause problems in some corporate networks.

So an option to allow or forbid some comporession algorithms would be great, for example:

```
# Enable compression
http:
  middlewares:
    test-compress:
      compress:
        compressionAlgorithms:
          - gzip
          - brotli
```

**Comment by wollomatic** [comment]
Hello @kevinpollet,

thanks! I'll look what I can do the next days and will check the contributor docs.

**Comment by kevinpollet** [comment]
Hello @wollomatic,

I would personally use an include encoding list because if we support a new encoding in the future users will have to enable it. This will avoid issues for unsupported algorithms, like this one, something like the following:  

```yaml
http:
  middlewares:
    test-compress:
      compress:
        encodings:
          - gzip
```

What do you think?
