### ISSUE TITLE
Cloudflare ACME error - cant renew/obtain certs

### ISSUE THREAD

**Issue by therealpaulgg** [traefik/traefik#10922]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have had a Traefik server running using Cloudflare DNS ACME provider for a few months now and have had no issues. Suddenly I notice one of my websites is unreachable - this was due to a cert not being renewed. I look into it some more and it turns out Traefik is unable to renew my certificates due to an error. No configuration has changed on my end, and am getting an error message saying failed to find zone auth.acme-dns.io

### What did you see instead?

unable to generate a certificate for the domains [my.domain.com]: error: one or more domains had a problem:\n[my.domain.com] [my.domain.com] acme: error presenting token: cloudflare: failed to find zone auth.acme-dns.io.: zone could not be found\n

### What version of Traefik are you using?

3.1.0

(I saw this issue first on 3.0, then updated)

### What is your environment & configuration?

```yaml
version: '3'

services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dynamic
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --certificatesresolvers.autoresolver.acme.email=me@example.com
      - --certificatesresolvers.autoresolver.acme.storage=/acme/acme.json
      - --certificatesresolvers.autoresolver.acme.dnschallenge=true
      - --certificatesresolvers.autoresolver.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.autoresolver.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --serversTransport.insecureSkipVerify=true
      - --metrics.prometheus=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - CF_API_EMAIL=me@example.com
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
      - CLOUDFLARE_ZONE_API_TOKEN=${CLOUDFLARE_ZONE_API_TOKEN}
    volumes:
      # Allows Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the dynamic configuration
      - /opt/docker_services/traefik/certs-traefik.yaml:/etc/traefik/dynamic/certs-traefik.yaml
      # Mount the directory containing the certs
      - /etc/step/certs:/etc/certs/
      - /opt/docker_services/traefik/data/acme:/acme
networks:
  default:
    name: traefik-network
```
