### ISSUE TITLE
Some metrics are missing in v3

### ISSUE THREAD

**Issue by jidckii** [traefik/traefik#10928]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm using traefik v3.0.1 while debugging my application, I noticed that traefik is missing some metrics and it seems it started with v3.
I noticed that the following metrics are missing:

```
traefik_config_reloads_failure_total
traefik_config_last_reload_failure
traefik_entrypoint_open_connections
traefik_service_open_connections
traefik_service_retries_total
traefik_service_server_up
```

In particular, I was most interested in
```
traefik_service_open_connections
```

but these metrics are not in the versions **v3.0.0** , **v3.0.1** , **v3.1.0**

In version **v2.11.6** there is

### What did you see instead?

There is no part of the metrics in versions v3+

### What version of Traefik are you using?

- v3.0.0
- v3.0.1
- v3.1.0
- v2.11.6

### What is your environment & configuration?

Static:
```yaml
entryPoints:
  web:
    address: ":8081"

api:
  dashboard: true
  insecure: true

metrics:
  prometheus: {}

providers:
  file:
    directory: conf
    watch: true
```

Dynamic:
```yaml
http:
  services:
    test:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:8080
  routers:
    test:
      rule: "PathPrefix(`/`)" 
      entryPoints:
        - "web"
      service: "test"
```
