### ISSUE TITLE
Internal Node IPs for NodePort services feature breaks namespace scoped Traefik deployments

### ISSUE THREAD

**Issue by gites** [traefik/traefik#10937]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm running my Traefik deployment on Kubernetres in a fully name-spaced way. All Traefik RBAC permissions are configured using `Roles` and `RoleBindings`. The K8s cluster is owned by an infrastructure team and host multiple namespaces for multiple teams/clients. Until now I was able to run and configure Traefik permissions without any support from the infra team. 

With the [Internal Node IPs for NodePort services](https://github.com/traefik/traefik/pull/10278) feature introduced in Treafik 3.1 I no longer can do it. Traefik 3.1 requires cluster level permissions to list/watch nodes. This makes both me (as I need to ask/deploy an external team to manage/deploy my Traefik configuration) and the infrastructure team (that operate at a big scale and don't want to be bothered with an application level configurations) unhappy.

As stated in the original PR comment by @rtribotte nodes are not namespaced so I fully understand why it was implemented this way. But the possibility to run Traefik in a fully namespaced way is/was a cool and useful feature that, I think, should be kept. 
 
@rtribotte are you open to refactoring the code to fetch node resources in the service namespace or other solution that will allow for fully namespaced Traefik setups?

Also the documentation for [3.0 -> 3.1 migration](https://doc.traefik.io/traefik/migration/v3/) is missing any information about the new permissions requirements 

### What did you see instead?

Traefik 3.1 can't run in Kubernetes without cluster level permissions for listing nodes

### What version of Traefik are you using?

```
traefik version
Version:      3.1.0
Codename:     comte
Go version:   go1.22.5
Built:        2024-07-15T14:44:04Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

Traefik RBAC configuration:

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: traefik-service-discovery
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["endpoints", "pods", "secrets", "services","nodes"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses", "ingressclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["traefik.io", "traefik.containo.us"]
    resources: ["ingressroutes", "ingressroutetcps", "ingressrouteudps", "middlewares", "middlewaretcps", "tlsoptions", "tlsstores", "traefikservices", "serverstransports", "serverstransporttcps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: traefik-service-discovery
  apiGroup: rbac.authorization.k8s.io
```
