### ISSUE TITLE
Invalid value: "array": tls must be specified for protocols ['HTTPS', 'TLS']

### ISSUE THREAD

**Issue by conradwt** [traefik/traefik#10941]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm attempting to follow the following walkthrough of using the Gateway API:

https://traefik.io/blog/getting-started-with-kubernetes-gateway-api-and-traefik

When I run 

```zsh
helm upgrade --install --namespace traefik traefik traefik/traefik -f values.yaml
```

### What did you see instead?

```zsh
Release "traefik" does not exist. Installing it now.
Error: 1 error occurred:
	* Gateway.gateway.networking.k8s.io "traefik-gateway" is invalid: spec.listeners: Invalid value: "array": tls must be specified for protocols ['HTTPS', 'TLS']
```

### What version of Traefik are you using?

v3.1.0

### What is your environment & configuration?

```yaml
## File values.yaml ##
providers:
  # Disable the Ingress provider (optional)
  # We do not want to use Ingress objects anymore!
  kubernetesIngress:
	enabled: false
  # Enable the GatewayAPI provider
  kubernetesGateway:
	enabled: true
# Allow the Gateway to expose HTTPRoute from all namespaces
gateway:
  namespacePolicy: All
```
