### ISSUE TITLE
Setting timeout per service/router

### ISSUE THREAD

**Issue by da-wilky** [traefik/traefik#10962]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I am hosting a service that needs a higher (or better disabled) read timeout for its requests. Currently I can't find a possibility to set this.
It would be very helpful, so I can host those services alongside with others, that shouldnt be exposed to [CVE-2024-28869](https://github.com/traefik/traefik/security/advisories/GHSA-4vwx-54mw-vqfw) vulnerability. (#10622)

Is there any plan to integrate this feature? NGINX supports this out of the box, I just switched to traefik a few months ago, because I like those comfort features it provides, but feels its lacking some details.

The same issue already existed in Apr. 2020 and got mentioned in the traefik community forum, but never had a reaction:
https://community.traefik.io/t/setting-timeout-per-service-router/5650

Hope its possible to implement that feature in the future.

Have a good one!

**Comment by kevinpollet** [comment]
Hello @da-wilky and thanks for opening this issue,

This is an interesting idea,

If you or another community member would like to build it, let us know, and we will work with you to make sure you have all the information needed so that it can be merged.  

Don’t forget to check out the [contributor docs](https://doc.traefik.io/traefik/contributing/submitting-pull-requests/) and to link the PR to this issue.

**Comment by sreeram-venkitesh** [comment]
@kevinpollet I'd like to work on this :)

**Comment by kevinpollet** [comment]
Hello @sreeram-venkitesh, thanks! Please go ahead :)

**Comment by da-wilky** [comment]
@kevinpollet I'd also be interested in working on this, but I think it's not clever to have this solved by a group? Would be interested in your opinion. In case this should better be done by a single dev I think @sreeram-venkitesh will do a great work!

**Comment by kevinpollet** [comment]
Hey @sreeram-venkitesh and @da-wilky, it is up to you if you want to collaborate :)

**Comment by sreeram-venkitesh** [comment]
@da-wilky I'm open to working with you if you'd like to do that. Else if you want to implement it on your own, I'm good with that too! Let's discuss how we can proceed :)

**Comment by da-wilky** [comment]
@sreeram-venkitesh On the free choice I'd like to collaborate with you. Currently I've never worked on an opensource project/public repo, so I hope to learn it with this task and the contributor docs. In case you got any advice I'd be happy to learn from you :)
I dont know the best practice - should this issue be the place to communicate or another messaging software, e.g. discord?

**Comment by sreeram-venkitesh** [comment]
@da-wilky Awesome, we can collaborate together over Discord/Slack. Please let me know which works best for you. This would be my first time working on a feature in Traefik, but I've made other open source contributions before, so hoping we can learn from each other :)

**Comment by da-wilky** [comment]
@sreeram-venkitesh Currently im not using Slack but it wont be a problem to start with it. Just see that the messages are only hold for 90 days but think that should still be fine. If you like you can send me a message @da-wilky on Slack. Or do you need my registered e-mail?

**Comment by sreeram-venkitesh** [comment]
@da-wilky Which workspace are you part of in Slack? I'm part of [slack.cncf.io](https://slack.cncf.io) and [slack.kubernetes.io](https://slack.kubernetes.io). My Slack username is `sreeram-venkitesh`. If Discord is easier for you, you can add me, my username is `fillerink`.

**Comment by arp-mbender** [comment]
Just chiming in on a use-case for this (also I think this is definitely a needed feature).

We've got a number of "typical" services behind Traefik... and then we have Sonatype Nexus. This service hosts our private Nuget and Docker repositories which in turn can contain very large files.

Clients of this service need to have more time to upload / download data. And I mean a LOT of time, sometimes. A Docker image for a Windows container can have humongous layers (think 8+GBs!) - yes, Docker for Windows is a wee bit "meh", but it's still better than no Docker at all - but that's beside the point.

So right now I had to set these vastly increased timeouts for ALL of our Traefik services, even if only one service actually requires it.

**Comment by benscobie** [comment]
> Just chiming in with a use-case for this (also I think this is definitely a needed feature).
> 
> We've got a number of "typical" services behind Traefik... and then we have Sonatype Nexus. This service hosts our private Nuget and Docker repositories which in turn can contain very large files.
> 
> Clients of this service need to have more time to upload / download data. And I mean a LOT of time, sometimes. A Docker image for a Windows container can have humongous layers (think 8+GBs!) - yes, Docker for Windows is a wee bit "meh", but it's still better than no Docker at all - but that's beside the point.
> 
> So right now, if I wanted to expose this service via Traefic, I'd need to set these vastly increased timeouts for ALL of our Traefik services, even if only one service actually required it. But since I don't want to expose all of our services to DDOS attacks I need to use our aging firewall for this service instead...

This feature request might be more appropriate for that use-case: https://github.com/traefik/traefik/issues/10611

**Comment by arp-mbender** [comment]
> This feature request might be more appropriate for that use-case: #10611

I'd be fine either way, really. At this time there's no way to set this without increasing timeouts for all services...

**Comment by 0verEngineer** [comment]
> This feature request might be more appropriate for that use-case: [#10611](https://github.com/traefik/traefik/issues/10611)

But this feature here should still be implemented...

**Comment by thewickedengineer** [comment]
Hi Contributors/Moderators, 
Is this self increasing timeout for good clients feature has any update. Or is there any update on setting the timeout to 10 minutes per service / ingress route. 
We are desperately trying to find a solution in Traefik to increase this for a single service to allow a large file stream upload.
Also, on the other hand, what are the potential risks involved in setting the timeout of 10 minutes globally until this problem is resolved or we swtich to another product. 
We are definitely considering to switch due to minimum to no support preesnt with traefik. 

Thanks

**Comment by nmengin** [comment]
Hey @thewickedengineer,

Thanks for reaching out! This is definitely on our radar.
We're focused on other priorities right now though, and we don't have an ETA yet—even though we plan to get to it.
We'll keep you updated as soon as we can move forward!

**Comment by arp-mbender** [comment]
@nmengin Would you mind answering the second part of @thewickedengineer question? Specifically what risks are associated with increasing the timeout globally?

**Comment by MichaelMuz** [comment]
I have also had to set my global timeouts to 10 mins today to handle one route needing to upload large files. This is certainly a security issue because of ddos / slow loris / resource exhaustion attack potential. Additionally from a devexp standpoint it is frustrating to diagnose issues when timeouts take 10 mins. I am even willing to contribute the fix myself, though the fact that this has been a reported issue for so long makes me think it is likely something systemic and not friendly to a first time contributor here.

Here is a compilation of this being asked and unanswered throughout the years:
https://github.com/traefik/traefik/issues/3027
https://community.traefik.io/t/how-to-set-entrypoints-transport-respondingtimeouts-for-only-one-service/26940/2
https://community.traefik.io/t/setting-timeout-per-service-router/5650/2
https://community.traefik.io/t/per-ingress-read-write-timeout/13497

**Comment by PseudoResonance** [comment]
In the meantime, depending on the setup, if you are using Kubernetes with a load balancer like MetalLB, you can also try creating a second port for the increased timeouts. I did something similar to the following.

One thing to note with this config, is it will need to be domain based, so that DNS can route connections to the separate IPs used by the new service. This also means that the two timeouts CANNOT be mixed on the same domain.

<details>
<summary>Traefik Helm Config</summary>

```yaml
ports:
  web:
    asDefault: true
    expose:
      default: true
    exposedPort: 80
    port: 8080
    protocol: TCP
  webbig:
    expose:
      default: false
      bigingress: true
    exposedPort: 80
    port: 9080
    protocol: TCP
    transport:
      respondingTimeouts:
        readTimeout: "1800s"

service:
  annotations:
    metallb.universe.tf/address-pool: static
    metallb.universe.tf/loadBalancerIPs: 10.0.0.2,fd::10:0:0:2
  enabled: true
  single: true
  spec:
    externalTrafficPolicy: Local
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack

  additionalServices:
    bigingress:
      annotations:
        metallb.universe.tf/address-pool: static
        metallb.universe.tf/loadBalancerIPs: 10.0.0.3,fd::10:0:0:3
      enabled: true
      single: true
      spec:
        externalTrafficPolicy: Local
      type: LoadBalancer
      ipFamilyPolicy: PreferDualStack
```
</details>

I only showed the HTTP port, not HTTPS to save length. It can easily be applied to both through the same method.

Then, on whatever domain I want increased timeouts for, since I use External-DNS, I applied the following ingress annotations to manually force it to direct traffic to the separate service.

```yaml
annotations:
  external-dns.alpha.kubernetes.io/target: 10.0.0.3,fd::10:0:0:3
  traefik.ingress.kubernetes.io/router.entrypoints: webbig,websecurebig
```

This is really an awful solution though and you're probably better off just making a separate Traefik install with the adjusted timeouts, then assigning the ingress class based on what you want. I was just experimenting to see what could be done.
