### ISSUE TITLE
TCP Router Termination

### ISSUE THREAD

**Issue by alberk8** [traefik/traefik#10968]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I would like to for Traefik (v3.1.1) to have the ability to disconnect a connection when the backend server is not responding or ended.  From the dashboard I can see that the TCP route and service is removed if the the backend is stopped but new client can still connect to traefik and sending data without any error but of cause the data sent is lost since there is no backend to handle it.

I have tried this [configuration ](https://doc.traefik.io/traefik/routing/services/#serverstransport_2) but it does not seems to work.

**Comment by kevinpollet** [comment]
Hello @alberk8,

Thank you for opening this issue.

To help us better understand and diagnose the problem, could you please provide a reproducible use case?

**Comment by alberk8** [comment]
This is my traefik docker compose and the TCP I am testing against is a mqtt from emqx

Test procecure
1)  docker compose up -d
2) open browser to http://192.168.1.74/dashboard/
3) open browser to http://192.168.1.74/whoami/
4) open mqtt client to 192.168.8.174 port 1883    (result is connection is successful and can sent data)
5) stop nanomq container   docker compose stop nanomq
6) open mqtt client to 192.168.8.174 port 1883 (result is connection is establish but hang until timeout)

After step5, traefik should no longer accept connection as the route is gone.

**docker-compose.yaml**
```
services:
 
  traefik:
    container_name: traefik
    restart: always
    image: "traefik:3.1.1"
    deploy:
      mode: global
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 8883:8883
      - 1883:1883
  

    networks:
      - default
      - privnet
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.rule=Host(`192.168.1.74`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.service=api@internal

    volumes:
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./certs:/etc/traefik/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro


  whoami:
    image: traefik/whoami
    restart: always
    container_name: whoami
    depends_on:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`192.168.1.74`) && PathPrefix(`/whoami`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.service=whoami-svc
      - traefik.http.services.whoami-svc.loadbalancer.server.port=80 

    networks:
      - privnet
 
  nanomq:
    container_name: nanomq
    restart: always
    image: "nanomq/nanomq:0.6.6-alpine"

    networks:
      - privnet

    labels:
      - traefik.enable=true
      - traefik.tcp.routers.nanomq.entrypoints=mqtt
      - traefik.tcp.routers.nanomq.rule=HostSNI(`*`)
      - traefik.tcp.routers.service=nanomq-svc
      - traefik.tcp.services.nanomq-svc.loadbalancer.server.port=1883

    depends_on:
      - traefik

networks:
  privnet:
    name: privnet
    driver: bridge
    #internal: true
```

traefik.yaml
```
## STATIC CONFIG (restart traefik to update)

# shows you a log msg if a newer image tag can be used
global:
  checkNewVersion: true

# log default is ERROR, but WARN is more helpful
log:
        #level: WARN
   level: debug

# enable dashboard on 8080 with NO AUTH
api:
  insecure: true
  dashboard: true

# enable ping so the `traefik healthcheck` works
ping: {}

# auto-proxy containers if they have proper labels
# and also use this file for dynamic config (tls)
providers:
  docker:
    endpoint: "unix://var/run/docker.sock"
    exposedByDefault: false
    watch: true
  file:
    fileName: /etc/traefik/traefik.yaml
    watch: true

tcpServersTransport:
  dialTimeout: 5s
  dialKeepAlive: 3s  
  
# listen on 80/443, and redirect all 80 to 443 via 301
entryPoints:
  web:
    address: :80
    # comment out these lins if you don't want to redirect everything
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
  mqtt:
    address: :1883
```

**Comment by rtribotte** [comment]
Hello @alberk8,

Thanks for your feedback!

> open mqtt client to 192.168.8.174 port 1883 (result is connection is establish but hang until timeout)

We suspect your are facing a current known limitation of entryPoints handling both HTTP and TCP.
Indeed, if no TCP router is present, the "default" handler is the HTTP server one.

To avoid that, as a workaround, I'll suggest to catch every connection with a catchAll (`HostSNI(*)`) router with the lowest priority pointing to a empty loadBalancer service. 
This way, when your service is unavailable, this router will handle all incoming connections and close them right away.

**Comment by alberk8** [comment]
How do I go about creating such an catchAll router.  Do I need a specific docker image?

**Comment by kevinpollet** [comment]
Hello @alberk8,

> How do I go about creating such an catchAll router. Do I need a specific docker image?

You do not need a specific Docker image but you will have to use the File [provider](https://doc.traefik.io/traefik/providers/file/) to configure this catchall router. In the dynamic configuration file, which must be mounted in the Traefik container, the following configuration will configure the catchAll router.

```yaml
tcp:
  routers:
    catchall:
      entryPoints: ["mqtt"]
      rule: HostSNI(`*`)
      priority: 0
      service: catchall

  services:
    catchall:
      weighted:
        services: {}

```

**Comment by alberk8** [comment]
The configuration you have provided did not work.  I have to do the following.  I also notice from the traefik dashboard that the config you have provided does not create any TCP router where with my config the catchall TCP router was created.  Is there a configuration mismatch somewhere?  Thanks.


**Add to the labels: for the Traefik container section**
```
 - traefik.tcp.routers.catchall.entrypoints=mqtt
 - traefik.tcp.routers.catchall.priority=2
 - traefik.tcp.routers.catchall.rule=HostSNI(`*`)
 - traefik.tcp.routers.service=catchall-svc
 - traefik.tcp.services.catchall-svc.loadbalancer.server.port=65535
```

**Add to labels: for the nanomq container section**
` - traefik.tcp.routers.nanomq.priority=9999`

**Comment by kevinpollet** [comment]
Hello @alberk8,

> Is there a configuration mismatch somewhere?

I tested the configuration again, and it is working, even though I'm using the same file for both static and dynamic configurations, which seems to be your case as well. However, please note that we do not recommend sharing the same file for both configurations. 

Something like the following:

```yaml
## STATIC CONFIG
entryPoints:
  mqtt:
    address: :1883

api:
  insecure: true

log:
  level: debug

providers:
  file:
    fileName: /path/to/configuration.yaml
    watch: true

## DYNAMIC CONFIG

tcp:
  routers:
    catchall:
      entryPoints: ["mqtt"]
      rule: HostSNI(`*`)
      priority: 0
      service: catchall

  services:
    catchall:
      weighted:
        services: {}
```

Your alternative configuration works as well; however, the downside is that it will trigger an ERROR log, which won't occur with the empty WRR once [this pull request](https://github.com/traefik/traefik/pull/10989) is merged.

**Comment by alberk8** [comment]
I have tried the config again and it works and I tried to apply the changes to my other docker compose and it does not seems to work.    After some debugging I find that setting the `traefik.http.routers.traefik.tls.options` in the label causes the issue where the connection is not immediately terminated when the backend server has stopped.

**Docker Compose  labels:  in traefik container**
```
   labels:
      - traefik.enable=true
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.rule=Host(`www.company.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.traefik.tls.options=modern@file
      - traefik.http.routers.traefik.middlewares=default@file
      
    volumes:
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./traefik/config.yaml:/etc/traefik/config.yaml:ro
      - ./certs:/etc/traefik/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro     
```

**Static traefik.yaml**
```
## STATIC CONFIG (restart traefik to update)

# shows you a log msg if a newer image tag can be used
global:
  checkNewVersion: true

# log default is ERROR, but WARN is more helpful
log:
        #level: WARN
   level: debug

# enable dashboard on 8080 with NO AUTH
api:
  insecure: true
  dashboard: true

# enable ping so the `traefik healthcheck` works
ping: {}

# auto-proxy containers if they have proper labels
# and also use this file for dynamic config (tls)
providers:
  docker:
    endpoint: "unix://var/run/docker.sock"
    exposedByDefault: false
    watch: true
  file:
    fileName: /etc/traefik/config.yaml
    watch: true

# listen on 80/443, and redirect all 80 to 443 via 301
entryPoints:
  web:
    address: :80
    # comment out these lins if you don't want to redirect everything
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
  mqtt:
    address: :1883
```

**Dynamic config.yaml**
```
http:
  middlewares:
    default:
      chain:
        middlewares:
          - default-security-headers
          - gzip

    # Add automatically some security headers
    # Use with traefik.http.routers.myRouter.middlewares: "default-security-headers@file"
    default-security-headers:
      headers:
        browserXssFilter: true                            # X-XSS-Protection=1; mode=block
        contentTypeNosniff: true                          # X-Content-Type-Options=nosniff
        forceSTSHeader: true                              # Add the Strict-Transport-Security header even when the connection is HTTP
        frameDeny: true                                   # X-Frame-Options=deny
        referrerPolicy: "strict-origin-when-cross-origin"
        sslRedirect: true                                 # Allow only https requests
        stsIncludeSubdomains: false                       # Add includeSubdomains to the Strict-Transport-Security header
        stsPreload: false                                 # Add preload flag appended to the Strict-Transport-Security header
        stsSeconds: 15552000                              # Set the max-age of the Strict-Transport-Security header (63072000 = 2 years)


    # Enables the GZIP compression (https://docs.traefik.io/middlewares/compress/)
    #   if the response body is larger than 1400 bytes
    #   if the Accept-Encoding request header contains gzip
    #   if the response is not already compressed (Content-Encoding is not set)
    # Use with traefik.http.routers.myRouter.middlewares: "gzip@file"
    gzip:
      compress: true
        

tls:
  certificates:
    - certFile: /etc/traefik/certs/mycert.pem
      keyFile: /etc/traefik/certs/mycert.key
  options:
    # To use with the label "traefik.http.routers.myrouter.tls.options=modern@file"
    modern:
      minVersion: VersionTLS13                         # Minimum TLS Version
      #sniStrict: true                                     # Strict SNI Checking
    
    # To use with the label "traefik.http.routers.myrouter.tls.options=intermediate@file"
    intermediate:
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      minVersion: VersionTLS12                          # Minimum TLS Version
      #sniStrict: true                                     # Strict SNI Checking

tcp:
  routers:
    catchall:
      entryPoints: ["mqtt"]
      rule: HostSNI(`*`)
      priority: 0
      service: catchall

  services:
    catchall:
      weighted: 
        services: {}

```
