### ISSUE TITLE
Dashboard JS blocked because of a disallowed MIME type (“text/plain”)

### ISSUE THREAD

**Issue by nuxwin** [traefik/traefik#10969]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Setup of Dashboard as follows (dynamic traefik conffile)

```yml
http:
  middlewares:
    authentication:
      basicAuth:
        users:
          - 'l.declercq@konzeptplus.ch:$apr1$jah9libv$JrCNNaYAmS8W9BAC/rX6j/'
    gzip:
      compress: true
    redirect-to-https:
      redirectScheme:
        scheme: https
    traefik-dashboard-https:
      chain:
        middlewares:
          - authentication
          - gzip
  routers:
    traefik-dashboard-http:
      entryPoints:
        - http
      middlewares:
        - redirect-to-https
      rule: Host(`traefik.srv01.konzeptplus-preview.ch`)
      service: api@internal
    traefik-dashboard-https:
      entryPoints:
        - https
      middlewares:
        - traefik-dashboard-https
      rule: Host(`traefik.srv01.konzeptplus-preview.ch`)
      service: api@internal
      tls:
        certResolver: letsencrypt
```

Result to the following error in the Firefox console:

![Capture d’écran 2024-08-03 à 18 38 48](https://github.com/user-attachments/assets/a0dbe776-ace7-4deb-9b56-01735fa2159a)

### What did you see instead?

de

### What version of Traefik are you using?

Version:      2.11.7
Codename:     mimolette
Go version:   go1.22.5
Built:        2024-07-30T12:21:02Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.de
