### ISSUE TITLE
Bug: Safari couldn't open the page, redirections http to https

### ISSUE THREAD

**Issue by rbouteiller** [traefik/traefik#10971]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Configured Traefik to serve a React website.

### What did you see instead?

On Safari, the page does not load when accessed via HTTP (http://example.com). 
However, it works correctly when accessed via HTTPS (https://example.com). On Chrome, the HTTP to HTTPS redirection works as expected.

### What version of Traefik are you using?

Version:      3.1.1
Codename:     comte
Go version:   go1.22.5
Built:        2024-07-30T13:55:22Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint: 
          to: websecure
          scheme: https
          permanent: true
     
  websecure:
    address: ":443"
    asDefault: true
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32" # localhost
        - "10.0.0.0/8" # swarm mode IP range
        - "192.168.0.0/16" # stand-alone after 172.16.0.0/12 is exhausted
        - "172.16.0.0/12" # stand-alone 
    http:
      tls:
        certResolver: letsencrypt
      middlewares:
        - SecHeader@file
        # - middleware-crowdsec-bouncer@file
```

I have a middleware for hsts
```yaml
http:
  middlewares:
    redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    SecHeader:
      headers:
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 31536000
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        featurePolicy: "vibrate 'self'; geolocation 'self'; midi 'self'; notifications 'self'; push 'self'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'self'; fullscreen 'self'"
        # frame-ancestors: "'self' *.bouteiller.org"
        contentSecurityPolicy: "frame-src 'self' https://* http://* blob:;" 
        customrequestheaders:
            X-Forwarded-Proto: "https"
        customResponseHeaders:
            Permissions-Policy: "geolocation=();midi=();notifications=();push=();sync-xhr=();microphone=();camera=();magnetometer=();gyroscope=();speaker=(self);vibrate=();fullscreen=(self);payment=();"
```

docker-compose.yml

```yaml
services:
  website:
    build:
      context: ./finwise-website
      dockerfile: Dockerfile
    ports:
      - 3002:3000
    labels:
      - traefik.enable=true
      - traefik.http.services.finwise-website.loadbalancer.server.port=3000
      - traefik.http.routers.finwise-website.rule=Host(`finwise.club`)
      - traefik.http.routers.finwise-website.entrypoints=web, websecure
    restart: always
    networks:
      - network_net
      - internal
# Networks definition
networks:
  # Network defined externally shared with other containers
  internal:
    driver: bridge
  network_net:
    external: true
```

```yaml
traefik:
        image: traefik:latest
        env_file:
            - .env
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.traefik.loadbalancer.server.port=8080"
            - "traefik.http.routers.traefik-https.rule=Host(`traefik.${DOMAIN}`)"
            - "traefik.http.routers.traefik-https.middlewares=keycloak@file"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik/traefik.yml:/traefik.yml:ro
            - ${DATA_PATH}/traefik/traefik/certs:/certs
            - ./traefik/config/:/etc/traefik/config/:ro
            - ${DATA_PATH}/traefik/traefik/logs/:/log/
            - ${DATA_PATH}/traefik/traefik/acme-dns/:/acme-dns/
            - /etc/localtime:/etc/localtime:ro
        networks:
            internal: null
            network_net:
                ipv4_address: 10.10.0.100
        healthcheck:
            test: [ "CMD", "traefik", "healthcheck", "--ping" ]
            interval: 30s
            timeout: 10s
            retries: 3
```

### If applicable, please paste the log output in DEBUG level

Nothing looks relevant in logs
