### ISSUE TITLE
Cannot change traefik's dashboard port with `api.insecure=false`

### ISSUE THREAD

**Issue by Seluj78** [traefik/traefik#10986]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am trying to deploy `traefik` as a reverse proxy on my kubernetes cluster, to access DNS names for pods, because `nginx` won't work for me for `gRPC`.

Here is the manifest to deploy `traefik` (using this and not `helm` because I don't know how to use helm and how to configure anything with it dashboard and dns wise.)

```yaml
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-default
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-default
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingressclasses
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.io
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - middlewaretcps
      - serverstransports
      - serverstransporttcps
      - tlsoptions
      - tlsstores
      - traefikservices
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-default
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-default
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: default


---

apiVersion: v1
kind: Service
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      name: web
    - port: 8443
      name: websecure
    - port: 8081
      name: dashboard
  selector:
    app: traefik

---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: traefik
 labels:
   app: traefik
spec:
 replicas: 1
 strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 0
 selector:
   matchLabels:
     app: traefik
 template:
   metadata:
     labels:
       app: traefik
   spec:
     serviceAccountName: traefik
     terminationGracePeriodSeconds: 60
     hostNetwork: false
     containers:
       - name: traefik
         image: traefik:v3.1.0
         args:
           - "--api=true"
           - "--api.insecure=true"
           - "--accesslog=true"
           - "--entrypoints.web.address=:8000"
           - "--entrypoints.websecure.address=:8443"
           - "--entrypoints.dashboard.address=:8081"
           - "--providers.kubernetescrd"
           - "--providers.kubernetesingress"
           - "--api.dashboard=true"
           - "--ping=true"
           - "--log.level=INFO"
         ports:
           - name: web
             containerPort: 8000
           - name: websecure
             containerPort: 8443
           - name: dashboard
             containerPort: 8081
         volumeMounts:
           - name: acme
             mountPath: /data
     volumes:
       - name: acme
         emptyDir: {}
     securityContext:
       runAsGroup: 65532
       runAsNonRoot: true
       runAsUser: 65532

---

apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-default
  name: traefik
spec:
  controller: traefik.io/ingress-controller
```

As you can see, I have `api.insecure=true` set and dashboard.address=:8081`, so I would expect the `insecure` dashboard to be available on port `8081` but it isn't the case.

Connecting to the traefik pod using `ssh`:

```
~ $ wget localhost:8081
Connecting to localhost:8081 (127.0.0.1:8081)
wget: server returned error: HTTP/1.1 404 Not Found
~ $ wget localhost:8080
Connecting to localhost:8080 (127.0.0.1:8080)
Connecting to localhost:8080 (127.0.0.1:8080)
wget: can't open 'index.html': Permission denied
```

Which indicates that the `8081` port isn't taken into account but the `8080` one is still active.
If I switch the `8081` to `8080` I get an error because I have `alertmanager` running on `8080` and I have no idea how to change that. But that doesn't matter because I want to be able to have access to the dashboard in a secure way for production use.

If I set `api.insecure` to `false`, no matter the port I specify, it will not do anything, and no `wget` will return anything.

I would expect being able to set `api.insecure` to `false` and be able to change the `dashboard` port to any value and be able to access the port that way.

PS: I did try using a configmap and didn't get further
PPS: Yes I know the dashboard is on `/dashboard/` but that doesn't change the issue, no matter the path it didn't work
![Screenshot 2024-08-07 at 19 34 45](https://github.com/user-attachments/assets/d28713cb-c9e7-4e7f-ac35-4b25c1538bd1)

### 
What version of Traefik are you using?

v3.1.2
