### ISSUE TITLE
Plugin: Parsing string array in nested config structs doesn't work

### ISSUE THREAD

**Issue by sevensolutions** [traefik/traefik#10996]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'am working on a traefik plugin where i want to configure the plugin using a yaml-array.
This works fine on top-level, but not on a nested one.

I found the following depending PRs:
- https://github.com/traefik/traefik/pull/8886
- https://github.com/traefik/paerser/pull/15

They all talk about traefik 2.x but i'am using 3.1.
Is there something missing in v3?

Here is my code:
**Config:**
```yml
middlewares:
    oidc-auth:
      plugin:
        traefik-oidc-auth:
          Authorization:
            AssertClaims:
              - Name: "preferred_username"
                Values: ["value1", "value2", "value3"]
```

**Structs:**
```go
type Config struct {
	Authorization *AuthorizationConfig `json:"authorization"`
}
type AuthorizationConfig struct {
	AssertClaims []ClaimAssertion `json:"assert_claims"`
}
type ClaimAssertion struct {
	Name   string   `json:"name"`
	Value  string   `json:"value"`
	Values []string `json:"values"`
}
```

### What did you see instead?

When i loop over the Values-array, i get: `[║24║value1║value2║value3]`
Instead, i'am expecting to get a real array.
The only workaround is to use:
```yml
Values: "value1,value2,value3"
```

### What version of Traefik are you using?

Version:      3.1.2
Codename:     comte
Go version:   go1.22.5
Built:        2024-08-06T13:37:51Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    address: :80

# Enable API and dashboard
api:
  insecure: true
  dashboard: true
  debug: true

experimental:
  localPlugins:
    traefik-oidc-auth:
      moduleName: github.com/sevensolutions/traefik-oidc-auth

providers:
  file:
    filename: /etc/traefik/configs/http.yml
    watch: true
```
