### ISSUE TITLE
large streamed gRPC requests fail over time with 50x response

### ISSUE THREAD

**Issue by gites** [traefik/traefik#10991]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We have an micro service based application that is using gRPC to communicate between different services. All our gRPC traffic goes via Traefik. One of those services is using bidirectional streamed gRPC and receive a big stream of data over time (sometimes hundreds of megabytes). That application was working without any issues with endpoints exposed via Traefik v2. On Treafik v3 after some amount of data clients are getting disconnected by Treafik with 50x error code.

To test this issue I've modified an example gRPC app from grpc/grpc-go. The test app is constantly sending big gRPC messages over a bidirectional streamed connection. Every 1000 messages server sends back the received message. 

The test client app is always receiving 50x error after sending around 5k messages. When running the same app with Traefik 2 (v2.10.3) there is no such situation.

 How to reproduce:
Run this docker-compse file:
```yaml
services:
 
  traefik:
    container_name: traefik
    restart: always
    image: traefik:3.1.4
    command: --api.insecure=true --providers.docker --accesslog=true --log.format=common --log.level=DEBUG
    ports:
      - 80:80
      - 8080:8080
      - 9090:9090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"

  server:
    image: gites/grpc-stream:test1
    labels:
      - "traefik.http.routers.server.rule=PathPrefix(`/routeguide.RouteGuide/`)"
      - "traefik.http.middlewares.autodetect.contenttype=true"
      - "traefik.http.services.server.loadbalancer.server.port=8081"
      - "traefik.http.services.server.loadbalancer.server.scheme=h2c"
    command: /server -port 8081
    ports:
      - 8081:8081

  client:
    image: gites/grpc-stream:test1
    command: /bin/sh -c "while :; do /client -addr traefik:80 -data /data.txt; sleep 1; echo "------------"; done"
```
Source code for `gites/grpc-stream:test1` is available [here](https://github.com/gites/grpc-go/tree/traefik-3-grpc-stream-bug/examples/route_guide)

### What did you see instead?

Large streamed gRPC requests don't fail over time with 50x response from Traefik

### What version of Traefik are you using?

```
traefik version
Version:      3.1.2
Codename:     comte
Go version:   go1.22.5
Built:        2024-08-06T13:37:51Z
OS/Arch:      linux/amd64
```
and
```
traefik version
Version:      3.0.3
Codename:     beaufort
Go version:   go1.22.4
Built:        2024-06-18T14:31:20Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

 dynamic.toml:
```toml
    [tls.stores]
      [tls.stores.default]
        [tls.stores.default.defaultCertificate]
          certFile = "/cert.pem"
          keyFile  = "/key.pem"
    [tls.options]
      [tls.options.mtls]
        minVersion = "VersionTLS12"
        maxVersion = "VersionTLS13"
        cipherSuites = [
          "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
          "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
          "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        ]
        curvePreferences = ["CurveP521", "CurveP384", "CurveP256"]
        sniStrict = true
        [tls.options.mtls.clientAuth]
          caFiles = ["/ca.pem"]
          clientAuthType = "RequireAndVerifyClientCert"
      [tls.options.mtlsRequireAndVerify]
        minVersion = "VersionTLS12"
        maxVersion = "VersionTLS13"
        cipherSuites = [
          "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
          "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
          "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        ]
        curvePreferences = ["CurveP521", "CurveP384", "CurveP256"]
        sniStrict = true
        [tls.options.mtlsRequireAndVerify.clientAuth]
          caFiles = ["/ca.pem"]
          clientAuthType = "RequireAndVerifyClientCert"
    [http.serversTransports]
      [http.serversTransports.mTLSServersTransport]
        rootCAs = ["/ca.pem"]
        [[http.serversTransports.mTLSServersTransport.certificates]]
          certFile = "/cert.pem"
          keyFile  = "/key.pem"
      [http.serversTransports.internalgRPCmTLSServersTransport]
        rootCAs = ["/ca.pem"]
        maxIdleConnsPerHost = 100
        [[http.serversTransports.internalgRPCmTLSServersTransport.certificates]]
          certFile = "/cert.pem"
          keyFile  = "/key.pem"
```

static.toml:
```toml
    [core]
      defaultRuleSyntax = "v2"
    [serversTransport]
      rootCAs = ["/ca.pem"]
    [providers.kubernetesCRD]
      disableClusterScopeResources = true
      allowCrossNamespace = true
      namespaces = ["ns1","ns2"]
    [metrics]
      [metrics.prometheus]
    [entryPoints]
      [entryPoints.internal]
        address = ":8443"
      [entryPoints.grpc]
        address = ":4140"
    [log]
      format = "json"
      level = "DEBUG"
    [ping]
      manualRouting = true
    [global]
      checkNewVersion = false
      sendAnonymousUsage = false
    [providers]
      [providers.file]
        filename = "/etc/traefik-configs/dynamic.toml"
    [tracing]
      [tracing.otlp.http]
        endpoint = "https://opentelemetry-collector.ns1.svc:4318/v1/traces"
      [tracing.otlp.http.tls]
        cert = "/cert.pem"
        key = "/key.pem"
        ca = "/ca.pem"
    [accessLog]
      format = "json"
      [accessLog.fields]
        [accessLog.fields.headers]
          defaultMode = "keep"
          [accessLog.fields.headers.names]
            "User-Agent" = "drop"
```

### If applicable, please paste the log output in DEBUG level

```
{"time":"2024-08-09T11:50:52Z","caller":"log/log.go:245","level":"debug","message":"2024/08/09 11:50:52 reverseproxy.go:663: httputil: ReverseProxy read error during body copy: i/o timeout"}        
                                                                                                                                                               

{"level":"debug","middlewareName":"traefik-internal-recovery","middlewareType":"Recovery","time":"2024-08-09T11:50:52Z","caller":"github.com/traefik/traefik/v3/pkg/middlewares/recovery/recovery.go:38","message":"Request has been aborted [172.18.164.187:58274 - /routeguide.RouteGuide/RouteChat]: net/http: abort Handler"}                                    traefik-ingress-controller-6797fc6d99-rdwsn traefik-ingress-controller {"level":"debug","time":"2024-08-09T11:50:52Z","caller":"github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:196","message":"Service selected by WRR: 39b33f0b8d8a77f5"}
```
