### ISSUE TITLE
KubernetesGateway provider updates all gateways, ignoring gatewayclass reference

### ISSUE THREAD

**Issue by Gitopolis** [traefik/traefik#10999]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Two traefik-proxy instances in one namespace: one for internal LB, another for external.

One gateway in a different namespace, intended to be used for external connections:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example
  namespace: example
spec:
  gatewayClassName: external
```
Expectation:
* The gateway status is updated by Traefik 1 and ignored by Traefik 2

### What did you see instead?

Both instances of Traefik update status of the gateway

### What version of Traefik are you using?

```
Version:      3.1.2
Codename:     comte
Go version:   go1.22.5
Built:        2024-08-06T13:37:51Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

* Arguments
  * Traefik 1:
  ```
  --providers.kubernetesgateway.statusaddress.service.namespace=traefik
  --providers.kubernetesgateway.statusaddress.service.name=external
  --providers.kubernetesgateway.labelselector=traefik-lb-type=external
  ```
  * Traefik 2:
  ```
  --providers.kubernetesgateway.statusaddress.service.namespace=traefik
  --providers.kubernetesgateway.statusaddress.service.name=internal
  --providers.kubernetesgateway.labelselector=traefik-lb-type=internal
  ```
* GatewayClasses
  * Traefik 1:
  ```yaml
  apiVersion: gateway.networking.k8s.io/v1
  kind: GatewayClass
  metadata:
    labels:
      traefik-lb-type: external
    name: external
  spec:
    controllerName: traefik.io/gateway-controller
  ```
  * Traefik 2:
  ```yaml
  apiVersion: gateway.networking.k8s.io/v1
  kind: GatewayClass
  metadata:
    labels:
      traefik-lb-type: internal
    name: internal
  spec:
    controllerName: traefik.io/gateway-controller
  ```
