### ISSUE TITLE
traefik works with 127.0.0.1 but failed with localhost

### ISSUE THREAD

**Issue by zjqzero** [traefik/traefik#11002]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Usually, I use stunnel as a proxy to forward to traefik, so I only need to access the localhost address. However, after using the middleware stripPrefix, I found that localhost cannot be accessed, but 127.0.0.1 can be accessed. It seems there might be an issue here.

### What did you see instead?

None

### What version of Traefik are you using?

Version:      3.1.2
Codename:     comte
Go version:   go1.22.5
Built:        2024-08-06T13:37:51Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
http:
  routers:
    shotgun-sz:
      entryPoints:
        - http
      service: shotgun-sz
      middlewares:
        - shotgun-sz
      rule: PathPrefix(`/shotgun-sz/`)

  services:
    shotgun-sz:
      loadBalancer:
        servers:
        - url: http://192.168.1.8:8001
        passHostHeader: true

  middlewares:
    shotgun-sz:
      stripPrefix:
        prefixes:
          - "/shotgun-sz"
```

### If applicable, please paste the log output in DEBUG level

![image](https://github.com/user-attachments/assets/66a4724b-fac7-474b-a18e-793b1fda6ae0)

{"ClientAddr":"172.17.0.1:57966","ClientHost":"172.17.0.1","ClientPort":"57966","ClientUsername":"-","DownstreamContentSize":11,"DownstreamStatus":**502**,"Duration":43830099,"OriginContentSize":11,"OriginDuration":43805583,"OriginStatus":502,"Overhead":24516,"RequestAddr":"**localhost**","RequestContentSize":0,"RequestCount":1,"RequestHost":"localhost","RequestMethod":"GET","RequestPath":"/shotgun-sz/api/ping","RequestPort":"-","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"shotgun-sz@file","ServiceAddr":"183.234.94.164:8001","ServiceName":"shotgun-sz@file","ServiceURL":"http://183.234.94.164:8001","StartLocal":"2024-08-13T23:25:36.604262987+08:00","StartUTC":"2024-08-13T15:25:36.604262987Z","entryPointName":"http","level":"info","msg":"","time":"2024-08-13T23:25:36+08:00"}
{"ClientAddr":"172.17.0.1:58238","ClientHost":"172.17.0.1","ClientPort":"58238","ClientUsername":"-","DownstreamContentSize":4,"DownstreamStatus"**:200,**"Duration":75555337,"OriginContentSize":4,"OriginDuration":75522244,"OriginStatus":200,"Overhead":33093,**"RequestAddr":"127.0.0.1"**,"RequestContentSize":0,"RequestCount":2,"RequestHost":"127.0.0.1","RequestMethod":"GET","RequestPath":"/shotgun-sz/api/ping","RequestPort":"-","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"shotgun-sz@file","ServiceAddr":"183.234.94.164:8001","ServiceName":"shotgun-sz@file","ServiceURL":"http://183.234.94.164:8001","StartLocal":"2024-08-13T23:26:11.512633382+08:00","StartUTC":"2024-08-13T15:26:11.512633382Z","entryPointName":"http","level":"info","msg":"","time":"2024-08-13T23:26:11+08:00"}
