### ISSUE TITLE
Send body from forwardauth middleware

### ISSUE THREAD

**Issue by sokoide** [traefik/traefik#11029]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

## Summary

We'd like to send http body to a forward auth external server optionally.

## Background

* I understand sending body could be an overhead. However, there are some situations which we'd like to entitle against an element of body.
* To support the scenario, there is [a community question](https://community.traefik.io/t/forward-auth-middleware-is-there-any-way-to-pass-whole-request-body/20011/2) which suggested to make a feature request and a PR
* We will make a PR for this

## Feature

* Allow `forwardauth` middleware to send body to the configured external server (e.g. example.com/auth in the case) if `forwardBody` is true
* 
```yaml
  middlewares:
    test-auth:
      forwardauth:
        address: "https://example.com/auth"
        forwardBody: true
```

**Comment by nmengin** [comment]
Hey @sokoide.

Thanks for your suggestion.

We are interested in this issue, but we’re unsure about the use case and the traction it will receive. We are going to leave the status as kind/proposal to give the community time to let us know if they would like this idea.

We will reevaluate as people respond.

Conversation is time-boxed to 6 months.

**Comment by sokoide** [comment]
Hi @nmengin, thank you for the info. Our use case is as follows. I hope there are other use cases from the community.

- We put Traefik in front of a backend server (e.g. alertmanager) which doesn't support auth/z
- Traefik `forwardauth` middleware sends the request to `forwardauth` server to check the entitlement
- `forwardauth` server needs the body, for example, when the backend server takes the following POST request and it allows/denies per userid in one of the headers and `ldapgroup` in `labels` in body
```
curl https://$host:$port/api/v1/rules/foo -X POST -d"
rules:
  - alert: test-alert
    labels:
      ldapgroup: foogroup
      severity: critical
" --key key.pem --cert cert.pem --cacert ca.pem
```
