### ISSUE TITLE
Rule Priority v2 vs v3

### ISSUE THREAD

**Issue by bugficks** [traefik/traefik#11027]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Porting router rules from v2 to v3

### What did you see instead?

Rule matching priority has changed.

For hostname zzzz.ahost.net:
- with v2 router from service AAAAA matches first
- with v3 router from service BBBBB matches first.

According to doc "length of rule" is used but in this case rule length is same for v2 and v3 but priority is not?

### What version of Traefik are you using?

Version:      3.1.2
Codename:     comte
Go version:   go1.22.5
Built:        2024-08-06T13:37:51Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

docker-compose.yml:
```yaml
AAAAA:
  ...
  traefik.http.routers.AAAAA.ruleSyntax: "v2"
  traefik.http.routers.AAAAA.entrypoints: http
  traefik.http.routers.AAAAA.middlewares: "mdw-http-to-https@file"
  traefik.http.routers.AAAAA.rule: "
	  Host(`zzzz.ahost.net`)
	  || Host(`zzzz-host-net.bhost.net`)
	"

BBBBB:
  ...
  traefik.http.routers.BBBBB.ruleSyntax: "v2"
  traefik.http.routers.BBBBB.entrypoints: "http"
  traefik.http.routers.BBBBB.tls: "false"
  traefik.http.routers.BBBBB.middlewares: "mdw-http-to-https@file"
  traefik.http.routers.BBBBB.rule: "
	HostRegexp(`^(.+\\.)?ahost\\.net$`)
	  || HostRegexp(`zzzz(-xxxx)?.bhost.net`)
	"
```

Add more configuration information here.
