### ISSUE TITLE
IP Whitelist: IP whitelisted / detected, but user receives Forbidden

### ISSUE THREAD

**Issue by Aetherinox** [traefik/traefik#11033]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

- Installed [Mailu ](https://github.com/Mailu/Mailu) container set
- Created new routers inside `docker-compose.yml` and added `whitelist@file` middleware to block non-whitelisted IPs from accessing.
- Went to website and received **Forbidden**.
- Checked console, and did see:
  ```
   github.com/traefik/traefik/v3/pkg/middlewares/ipallowlist/ip_allowlist.go:85 > Accepting IP XX.XXX.XX.13 middlewareName=whitelist@file middlewareType=IPAllowLister
  ```

---

As a note, I also have the **GeoIP middleware** installed and I tested that on the same container. The Geoblock middleware works correctly. It restricts access to anyone outside of a geographical location.

The ipwhitelist prints in console that the IP address is indeed whitelisted and accepted, however, the user gets the "Forbidden" error in their browser.

The odd issue is that I use this same style of config for other containers, and they seem to correctly work. It makes no sense as to why this one container does not. So it's confusing as to whether it's this one container having an issue, or ipwhitelist.

The only extra noteworthy thing is that this particular subdomain is NOT behind Cloudflare.  But when I check the Traefik logs, it seems to be finding the IP address as pasted above. So I wouldn't think that it's because Cloudflare is not implemented with that particular subdomain.

Also, I provided my Whoami stats below. I have Authentik installed, however, authentik middleware is NOT set up for this particular site as it's not needed.

### What did you see instead?

User receives "Forbidden" error even though IP address is added to whitelist.

### What version of Traefik are you using?

```
Version:      3.1.2
Codename:     comte
Go version:   go1.22.5
Built:        2024-08-06T13:37:51Z
OS/Arch:      linux/amd64
```

## docker-compose.yml

```yml

  front:
    container_name: mail-server
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-latest}
    restart: unless-stopped
    env_file: ${MAILU_ENV}
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "${SERVER_IPV4}:25:25"
      - "${SERVER_IPV4}:465:465"
      - "${SERVER_IPV4}:587:587"
      - "${SERVER_IPV4}:110:110"
      - "${SERVER_IPV4}:995:995"
      - "${SERVER_IPV4}:143:143"
      - "${SERVER_IPV4}:993:993"
    volumes:
      - "${VOLUMES_DIR}/certs:/certs"
      - "${VOLUMES_DIR}/overrides/nginx:/overrides"
      - "${VOLUMES_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf"
    labels:

      #   General

      - traefik.enable=true
      - traefik.constraint-label=traefik
      - traefik.docker.network=traefik

      #   Route > http

      - traefik.http.routers.mail-http.rule=Host(Host(`${SERVICENAME}.${DOMAINNAME}`)
      - traefik.http.routers.mail-http.service=mail
      - traefik.http.routers.mail-http.entrypoints=http
      - traefik.http.routers.mail-http.middlewares=https-redirect@file

      #   Route > https

      - traefik.http.routers.mail-https.rule=Host(`${SERVICENAME}.${DOMAINNAME}`)
      - traefik.http.routers.mail-https.service=mail
      - traefik.http.routers.mail-https.entrypoints=https
      - traefik.http.routers.mail-https.tls=true
      - traefik.http.routers.mail-https.tls.certresolver=cloudflare
      - traefik.http.routers.mail-https.tls.domains[0].main=${DOMAINNAME}
      - traefik.http.routers.mail-https.tls.domains[0].sans=*.${DOMAINNAME}
      - traefik.http.routers.mail-https.middlewares=whitelist@file

      #   Load Balancer

      - traefik.http.services.mail.loadbalancer.server.port=80
      - traefik.http.services.mail.loadbalancer.server.scheme=http

    networks:
      - traefik
    depends_on:
      - resolver
```

<br />

## traefik.yml

```yml
http:
  middlewares:
    whitelist:
      ipAllowList:
        sourceRange:
          - "127.0.0.0/8"
          - "192.168.0.0/16"
          - "172.16.0.0/12"
          - "10.0.0.0/8"
          - "172.23.0.0/16"
          - "172.22.0.0/16"
          - "172.21.0.0/16"
          - "172.20.0.0/16"
          - "172.19.0.0/16"
          - "172.18.0.0/16"
          - "172.17.0.1/16"
          - "XX.XX.XX.XX"        <--- whitelisted entry
          - "10.11.0.0/16"

        ipStrategy:
          excludedIPs:
            # Cloudflare IP List
            # These will be ignored and the next IP in line will be checked
            - "103.21.244.0/22"
            - "103.22.200.0/22"
            - "103.31.4.0/22"
            - "104.16.0.0/13"
            - "104.24.0.0/14"
            - "108.162.192.0/18"
            - "131.0.72.0/22"
            - "141.101.64.0/18"
            - "162.158.0.0/15"
            - "172.64.0.0/13"
            - "173.245.48.0/20"
            - "188.114.96.0/20"
            - "190.93.240.0/20"
            - "197.234.240.0/22"
            - "198.41.128.0/17"
            - "2400:cb00::/32"
            - "2606:4700::/32"
            - "2803:f800::/32"
            - "2405:b500::/32"
            - "2405:8100::/32"
            - "2a06:98c0::/29"
            - "2c0f:f248::/32"
```

I did block out the actual IP in question as to not expose it online, but I assure you, it's not incorrectly typed. The IP digits match identically, and it works for other containers.

Here are the results of **Whoami** if you need those:
```
Hostname: whoami
IP: 127.0.0.1
IP: ::1
IP: 172.18.0.93
RemoteAddr: 172.18.0.2:52230
GET / HTTP/1.1
Host: whoami.domain.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding: gzip, br
Accept-Language: en-US,en;q=0.5
Cache-Control: max-age=0
Cdn-Loop: cloudflare
Cf-Connecting-Ip: XX.XX.XX.XX
Cf-Ipcountry: US
Cf-Visitor: {"scheme":"https"}
Dnt: 1
Priority: u=1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Sec-Gpc: 1
Upgrade-Insecure-Requests: 1
X-Authentik-Email: user@email.com
X-Authentik-Groups: Root
X-Authentik-Meta-App: whoami
X-Authentik-Meta-Jwks: https://auth.domain.com/application/o/whoami/jwks/
X-Authentik-Meta-Outpost: authentik Embedded Outpost
X-Authentik-Meta-Provider: Whoami ForwardAuth
X-Authentik-Meta-Version: goauthentik.io/outpost/2024.6.0
X-Authentik-Name: Username
X-Authentik-Uid: 2ac7b26a156ff0acccb2fca84b777d20ca820a1c3f9d8e1a776d3624aff0cef5
X-Authentik-Username: Aetherinox
X-Forwarded-For: XX.XX.XX.XX, 172.XX.XX.XX
X-Forwarded-Host: whoami.domain.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: traefik
X-Ipcountry: US
X-Real-Ip: 172.XX.XX.XX
```

### If applicable, please paste the log output in DEBUG level

```
github.com/traefik/traefik/v3/pkg/middlewares/ipallowlist/ip_allowlist.go:85 > Accepting IP XX.XXX.XX.XX middlewareName=whitelist@file middlewareType=IPAllowLister
github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:196 > Service selected by WRR: 940b25639b5db19c
Loaded from database:  {US 2024-08-22 20:14:27.635392066633 -0700 PDT m=+7.152318292}
geoblock@file: request allowed [XX.XX.XX.XX] for country [US]
```

**Comment by Aetherinox** [comment]
An added note. Sorry if this really wasn't a bug. I'm not sure.

I actually got it to work, but the solution was rather weird. So if there's an explaination, that would be awesome. To get the subdomain working, I had to create a second Whitelist rule excluding the Cloudflare IPs.

The new whitelist rule is:
```yml
    whitelistNoCF:
      ipAllowList:
        sourceRange:
          - "127.0.0.0/8"
          - "192.168.0.0/16"
          - "172.16.0.0/12"
          - "10.0.0.0/8"
          - "172.23.0.0/16"
          - "172.22.0.0/16"
          - "172.21.0.0/16"
          - "172.20.0.0/16"
          - "172.19.0.0/16"
          - "172.18.0.0/16"
          - "172.17.0.1/16"
          - "XX.XX.XX.XX"
          - "10.11.0.0/16"
        ipStrategy:
          depth: 0
```

So instead of using `excludedIPs`, I used `depth`. Now it seems to detect a properly blocked connection to that subdomain. But it doesn't work with the original rule which had all of the whitelisted Cloudflare IPs. Which makes no sense.

I'd assume this isn't a bug, but either by design? Or me misunderstanding something.
