### ISSUE TITLE
Traefik failing first authentication attempt to NTLM-protected website

### ISSUE THREAD

**Issue by arp-mbender** [traefik/traefik#11037]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm trying to set up Traefik v3 as a dockerized proxy server for our internal Microsoft DevOps 2022 Server. This server uses NTLM authentication (a requirement that, unfortunately, cannot be changed).

### What did you see instead?

There's an issue with the initial authentication step experienced by the users. Specifically, the first username+password from the user appears to be ignored and / or not proxied correctly, forcing users to provide their credentials twice (or provide "empty" credentials on the first attempt).

Since MS DevOps Server also handles GIT and Nuget this is bound to cause more issues down the line...

### What version of Traefik are you using?

```
docker exec traefik traefik version
Version:      3.1.2
Codename:     comte
Go version:   go1.22.5
Built:        2024-08-06T13:37:51Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

Since MS DevOps Server is NOT a docker-based service I'm using a file-based configuration to set up this service:
```yaml
http:
 routers:
   to-devops:
     rule: "Host(`devops-test.public-domain.com`)"
     service: devops
     entrypoints: websecure
 services:
   devops:
     loadBalancer:
       serversTransport: devops-transport
       servers:
       - url: https://srv-tfs-p03.internal.domain
 serversTransports:
   devops-transport:
     disableHTTP2: true
     insecureSkipVerify: true
```

### If applicable, please paste the log output in DEBUG level

Unfortunately there's nothing interesting in the `DEBUG` logs, only typical loadbalancer entries.
