### ISSUE TITLE
K8s IngressRoute "unable to find severs" when selecting a named port from a headless & selectorless ClusterIP Service

### ISSUE THREAD

**Issue by emerconnelly** [traefik/traefik#11041]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Create a headless & selectorless ClusterIP Service with a custom Endpoints pointing to an IP outside of the cluster.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: mikrotik-headless-proxy
  namespace: mikrotik-headless-proxy
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mikrotik-headless-proxy
  namespace: mikrotik-headless-proxy
subsets:
- addresses:
  - ip: 172.21.0.1
  ports:
  - port: 80
```

Then, create an IngressRoute:
```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: http
  namespace: mikrotik-headless-proxy
spec:
  entryPoints: ["web"]
  routes:
  - match: Host(`mikrotik.homelab.emerconnelly.com`)
    kind: Rule
    services:
    - name: mikrotik-headless-proxy
      port: 80
```

The route does not work and does not show up in the Traefik dashboard. View DaemonSet logs:
```
2024-08-28T07:45:27Z ERR error="no servers found for mikrotik-headless-proxy/mikrotik-headless-proxy" ingress=http namespace=mikrotik-headless-proxy providerName=kubernetescrd
```

Remove port name from ClusterIP:
```
apiVersion: v1
kind: Service
metadata:
  name: mikrotik-headless-proxy
  namespace: mikrotik-headless-proxy
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mikrotik-headless-proxy
  namespace: mikrotik-headless-proxy
subsets:
- addresses:
  - ip: 172.21.0.1
  ports:
  - port: 80
```

The route now works and shows in the Traefik dashboard. The DaemonSet logs have no errors.

### What did you see instead?

Traefik does not create the IngressRoute if the ClusterIP name has `name` attribute.

Once this attribute is removed, Traefik creates the IngressRoute.

### What version of Traefik are you using?

`kubectl exec -itn traefik daemonsets/traefik -- traefik version`
```
Version:      3.1.2
Codename:     comte
Go version:   go1.22.5
Built:        2024-08-06T13:37:51Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
spec:
  values:
    deployment:
      kind: DaemonSet
    ingressClass:
      name: traefik
      enabled: true
      isDefaultClass: false
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.homelab.emerconnelly.com`)
        entryPoints: ["websecure"]
        tls:
          secretName: ingress-tls
      healthcheck:
        enabled: true
        matchRule: Host(`traefik.homelab.emerconnelly.com`) && Path(`/ping`)
        entryPoints: ["websecure", "web"]
        tls:
          secretName: ingress-tls
    service:
      spec:
        loadBalancerIP: 172.21.0.170
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
      kubernetesGateway:
        enabled: true
    logs:
      access:
        enabled: true
        addInternals: true
    metrics:
      prometheus:
        service:
          enabled: true
        disableAPICheck: false
        serviceMonitor:
          enabled: true
          honorLabels: true
    tracing:
      addInternals: true
      otlp:
        enabled: true
        grpc:
          enabled: true
          endpoint: "openobserve-collector-agent-collector-headless.openobserve-collector.svc.cluster.local:4317"
          insecure: true
    globalArguments:
    - "--global.checknewversion"
    tolerations:
    - operator: "Exists"
```

Kubernetes 1.30.4
Helm Chart 30.1.0
