### ISSUE TITLE
Azure DNS LE challenge using _FILE

### ISSUE THREAD

**Issue by arp-mbender** [traefik/traefik#11045]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Using dockerized Traefik v3 I'd like to set up AzureDNS Let'sEncrypt challenge using `_FILES` suffixes, to not expose the relevant secrets / configuration items in the container's `ENV` variables.

This is based on [this](https://go-acme.github.io/lego/dns/#configuration-and-credentials) and [this](https://go-acme.github.io/lego/dns/azuredns/) documentation.

> The environment variable names can be suffixed by `_FILE` to reference a file instead of a value. More information [here](https://go-acme.github.io/lego/dns/#configuration-and-credentials).

### What did you see instead?

Traefik attempts to generate the certificate but fails with the following error message:
```
incomplete environment variable configuration. Only AZURE_TENANT_ID and AZURE_CLIENT_ID are set
```

I understand this may be an issue with go-acme.github.io/lego/ itself. I'd appreciate if someone could confirm or deny the problem, however...

### What version of Traefik are you using?

```
docker exec traefik traefik version
Version:      3.1.2
Codename:     comte
Go version:   go1.22.5
Built:        2024-08-06T13:37:51Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

`docker-compose.yml`:
```
services:
  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    env_file:
      - ./azuredns/.env
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt/:/letsencrypt/"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./services/:/services/"
      - "./azuredns/:/azuredns/"
      - "./certs/:/certs/"
      - "/var/log/traefik/:/var/log/traefik/"
```
and the following section inside `traefik.yml` configuration:
```
entryPoints:
  web:
    address: :80

  websecure:
    asDefault: true
    address: :443
    http:
      tls:
        certResolver: le
        domains:
          - main: "*.domain.com"
            sans: 
              - "domain.com"
certificatesResolvers:
  le:
    acme:
      email: admin@domain.com
      storage: /letsencrypt/acme.json
      caserver: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: azuredns
```
Finally, I have the following in the `/azuredns/` folder:
- `.env`
```
AZURE_SUBSCRIPTION_ID=<redacted>
AZURE_TENANT_ID=<redacted>
AZURE_CLIENT_ID=<redacted>
AZURE_CLIENT_SECRET_FILE=/azuredns/azuresecret
AZURE_RESOURCE_GROUP=<redacted>
```
- `azuresecret`:
```
MyAzureClientSecret
```

### If applicable, please paste the log output in DEBUG level

```
ERR Unable to obtain ACME certificate for domains error="cannot get ACME client azuredns: discover DNS zones: DefaultAzureCredential: failed to acquire a token.
Attempted credentials:
    EnvironmentCredential: incomplete environment variable configuration. Only AZURE_TENANT_ID and AZURE_CLIENT_ID are set
    WorkloadIdentityCredential: no token file specified. Check pod configuration or set TokenFilePath in the options
    ManagedIdentityCredential: managed identity timed out. See https://aka.ms/azsdk/go/identity/troubleshoot#dac for more information
    AzureCLICredential: Azure CLI not found on path
    AzureDeveloperCLICredential: Azure Developer CLI not found on path"
ACME CA=https://acme-staging-v02.api.letsencrypt.org/directory acmeCA=https://acme-staging-v02.api.letsencrypt.org/directory domains=["*.domain.com","domain.com"] providerName=le-staging.acme routerName=to-sup@file rule=Host(`sup.domain.com`)
```
