### ISSUE TITLE
Ability to choose compression algorithms in k8s Middleware

### ISSUE THREAD

**Issue by Object905** [traefik/traefik#11063]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I'm was having troubles after upgrade to 3.1 because it introduced zstd.
My CDN provider doesn't handle Vary: Accept-Encoding headers correctly, while Safari does not support zstd - so I had to downgrade.
Also https://github.com/traefik/traefik/issues/10859

While [encodings option](https://github.com/traefik/traefik/pull/10943) is not configurable from Kubernetes [Middleware](https://doc.traefik.io/traefik/middlewares/http/compress/)

**Comment by Object905** [comment]
Sorry, didn't see [this](https://github.com/traefik/traefik/pull/10943)

**Comment by nmengin** [comment]
Hello @Object905,

Thanks for reaching out.

Reading your issue, we're unsure to understand your need.

Do you report a bug in the new behavior of the compress middleware or do you expect we bring the #10943 in v3.1 to fix the encoding management?

**Comment by Object905** [comment]
I would like to see configuration options for `encodings` from https://github.com/traefik/traefik/pull/10943 in compression [middleware for k8s](https://doc.traefik.io/traefik/middlewares/http/compress/). Just like defaultEncoding, minResponseBodyBytes, etc.
So I can disable zstd on my "main" compression middleware. And also make seperate `compress-gzip-only` middleware.

 ```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: compress
spec:
  compress:
    includedContentTypes:
      - application/json
      - text/html
      - text/plain
    encodings:
      - br
      - gzip
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: compress-only-gzip
spec:
  compress:
    includedContentTypes:
      - application/json
      - text/html
      - text/plain
    encodings:
      - gzip
```
