### ISSUE TITLE
Run a modified plugin in local mode but failed

### ISSUE THREAD

**Issue by duj4** [traefik/traefik#11061]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I was modifying an existing [plugin](https://plugins.traefik.io/plugins/63a4cc653038a467c0ee9cb1/tls-auth) with customization and tried to run in local mode, but the code change seems not work.

I added three attributes in the `Config` part:
```
// Config is the plugin configuration.
type Config struct {
	Users          map[string]string
	UsernameHeader string
	// customization
	tlsCAPath   string
	tlsCertPath string
	tlsKeyPath  string
}
```

And tried to print it out in `New`:
```
// New created a new plugin.
func New(ctx context.Context, next http.Handler, config *Config, name string) (http.Handler, error) {
	// Log the instantiation of the plugin, including configuration.
	fmt.Fprintf(os.Stdout, "creating tlsauth plugin %q with config: %+v\n", name, config)

	// Return new plugin instance.
	return &TLSAuth2{
		next:   next,
		name:   name,
		config: config,
	}, nil
}
```

### What did you see instead?

I thought the config added would be loaded but what I got from log is as below, it seems the config part is not loaded at all:
> creating tlsauth plugin "tlsauth2@file" with config: &{Users:map[centos8-1:centos8-1] UsernameHeader:User XtlsCAPath: XtlsCertPath: XtlsKeyPath:}

May I know if I missed something and what is the `X` next to the attribute?

### What version of Traefik are you using?

```
Version:      3.1.2
Codename:     comte
Go version:   go1.22.5
Built:        2024-08-06T13:37:51Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration?

static.yml:
```yaml
experimental:
  localPlugins:
    tlsauth2:
      moduleName: github.com/duj4/tlsauth2
```

dynamic.yml:
```yaml
  middlewares:
    tlsauth2:
      plugin:
        tlsauth2:
          usernameHeader: "User"
          users:
            centos8-1: centos8-1
          tlsCAPath: "./tls/ca.crt"
          tlsCertPath: "./tls/centos8-1.crt"
          tlsKeyPath: "./tls/centos8-1.key"
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

> 2024-09-01T17:55:36+08:00 DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:321 > No default certificate, fallback to the internal generated certificate tlsStoreName=default
> creating tlsauth plugin "tlsauth2@file" with config: &{Users:map[centos8-1:centos8-1] UsernameHeader:User XtlsCAPath: XtlsCertPath: XtlsKeyPath:}
> 2024-09-01T17:55:36+08:00 DBG github.com/traefik/traefik/v3/pkg/middlewares/observability/middleware.go:33 > Adding tracing to middleware entryPointName=websecure middlewareName=tlsauth2@file routerName=traefik_https@file
>
