### ISSUE TITLE
Can not get Service Metrics

### ISSUE THREAD

**Issue by xieydd** [traefik/traefik#11069]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have installed Traefik via helm, but i can not get service metrics.

helm install command:
```shell
helm upgrade --install traefik traefik/traefik --version 28.1.0 --values ../hack/traefik-default-values.yaml --set deployment.replicas=1
```

helm values file:
```yaml
# ref: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
additionalArguments:
  - "--log.level=DEBUG"
#  - "--providers.kubernetesingress.ingressclass=traefik-internal"

ports:
  postgresql:
    expose: 
      default: true
    port: 5432
    exposedPort: 5432
    protocol: TCP
    transport:
      respondingTimeouts:
        readTimeout: "0"
  pg-pooler:
    expose: 
      default: true
    port: 6432
    exposedPort: 6432
    protocol: TCP
    transport:
      respondingTimeouts:
        readTimeout: "0"

service:
  enabled: true
  ## -- Single service is using `MixedProtocolLBService` feature gate.
  ## -- When set to false, it will create two Service, one for TCP and one for UDP.
  single: true
  type: LoadBalancer
  # -- Additional annotations applied to both TCP and UDP services (e.g. for cloud provider specific config)
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: deregistration_delay.timeout_seconds=200,deregistration_delay.connection_termination.enabled=true,preserve_client_ip.enabled=false,stickiness.enabled=true,stickiness.type=source_ip
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /ping
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "9000"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTP
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

entryPoints:
  metrics:
    address: :8082

metrics:
  addInternals: true
  prometheus:
    addEntryPointsLabels: true 
    addRoutersLabels: false 
    addServicesLabels: true
    service:
      enabled: true
    entryPoint: metrics
    # -- enable optional CRDs for Prometheus Operator
    #
    # Create a dedicated metrics service for use with ServiceMonitor
    service:
      enabled: true
    # When set to true, it won't check if Prometheus Operator CRDs are deployed
    disableAPICheck: false 
    serviceMonitor:
      enabled: true
      metricRelabelings: 
        - sourceLabels: [__name__]
          separator: ;
          regex: ^fluentd_output_status_buffer_(oldest|newest)_.+
          replacement: $1
          action: drop
      relabelings: 
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          separator: ;
          regex: ^(.*)$
          targetLabel: nodename
          replacement: $1
          action: replace
      jobLabel: traefik
      interval: 30s
      honorLabels: true
    prometheusRule:
      additionalLabels: {}
      namespace: "default"
      rules:
        - alert: TraefikDown
          expr: up{job="traefik-metrics"} == 0
          for: 5m
          labels:
            context: traefik
            severity: warning
          annotations:
            summary: "Traefik Down"
            description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"

deployment:
  replicas: 2
priorityClassName: "system-node-critical"
```

traefik image and parameters:
```
image: docker.io/traefik:v3.0.0
- args:
│     - --global.checknewversion
│     - --global.sendanonymoususage
│     - --entryPoints.metrics.address=:9100/tcp
│     - --entryPoints.pg-pooler.address=:6432/tcp
│     - --entryPoints.postgresql.address=:5432/tcp
│     - --entryPoints.traefik.address=:9000/tcp
│     - --entryPoints.web.address=:8000/tcp
│     - --entryPoints.websecure.address=:8443/tcp
│     - --api.dashboard=true
│     - --ping=true
│     - --metrics.addinternals
│     - --metrics.prometheus=true
│     - --metrics.prometheus.entrypoint=metrics
│     - --metrics.prometheus.addEntryPointsLabels=true
│     - --metrics.prometheus.addServicesLabels=true
│     - --providers.kubernetescrd
│     - --providers.kubernetesingress
│     - --entryPoints.pg-pooler.transport.respondingTimeouts.readTimeout=0
│     - --entryPoints.postgresql.transport.respondingTimeouts.readTimeout=0
│     - --entryPoints.websecure.http.tls=true
│     - --log.level=INFO
│     - --log.level=DEBUG
```

metrics get info:
```
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 1.7372e-05
go_gc_duration_seconds{quantile="0.25"} 7.6605e-05
go_gc_duration_seconds{quantile="0.5"} 0.000135107
go_gc_duration_seconds{quantile="0.75"} 0.000421178
go_gc_duration_seconds{quantile="1"} 0.000421178
go_gc_duration_seconds_sum 0.000650262
go_gc_duration_seconds_count 4
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 208
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.22.4"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 3.1886936e+07
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 5.6358736e+07
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.486536e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 185344
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 3.95508e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 3.1886936e+07
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 1.5720448e+07
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 3.6544512e+07
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 83769
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 2.056192e+06
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 5.226496e+07
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.725358730627489e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 269113
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 2400
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 15600
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 322560
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 505920
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 6.1375312e+07
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 448392
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 2.228224e+06
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 2.228224e+06
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 6.0904712e+07
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 9
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.95
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 16
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.26046208e+08
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.72535860997e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.421029376e+09
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes 1.8446744073709552e+19
# HELP traefik_config_last_reload_success Last config reload success
# TYPE traefik_config_last_reload_success gauge
traefik_config_last_reload_success 1.72535861e+09
# HELP traefik_config_reloads_total Config reloads
# TYPE traefik_config_reloads_total counter
traefik_config_reloads_total 2
# HELP traefik_entrypoint_request_duration_seconds How long it took to process the request on an entrypoint, partitioned by status code, protocol, and method.
# TYPE traefik_entrypoint_request_duration_seconds histogram
traefik_entrypoint_request_duration_seconds_bucket{code="200",entrypoint="metrics",method="GET",protocol="http",le="0.1"} 5
traefik_entrypoint_request_duration_seconds_bucket{code="200",entrypoint="metrics",method="GET",protocol="http",le="0.3"} 5
traefik_entrypoint_request_duration_seconds_bucket{code="200",entrypoint="metrics",method="GET",protocol="http",le="1.2"} 5
traefik_entrypoint_request_duration_seconds_bucket{code="200",entrypoint="metrics",method="GET",protocol="http",le="5"} 5
traefik_entrypoint_request_duration_seconds_bucket{code="200",entrypoint="metrics",method="GET",protocol="http",le="+Inf"} 5
traefik_entrypoint_request_duration_seconds_sum{code="200",entrypoint="metrics",method="GET",protocol="http"} 0.007907344
traefik_entrypoint_request_duration_seconds_count{code="200",entrypoint="metrics",method="GET",protocol="http"} 5
traefik_entrypoint_request_duration_seconds_bucket{code="200",entrypoint="traefik",method="GET",protocol="http",le="0.1"} 572
traefik_entrypoint_request_duration_seconds_bucket{code="200",entrypoint="traefik",method="GET",protocol="http",le="0.3"} 572
traefik_entrypoint_request_duration_seconds_bucket{code="200",entrypoint="traefik",method="GET",protocol="http",le="1.2"} 572
traefik_entrypoint_request_duration_seconds_bucket{code="200",entrypoint="traefik",method="GET",protocol="http",le="5"} 572
traefik_entrypoint_request_duration_seconds_bucket{code="200",entrypoint="traefik",method="GET",protocol="http",le="+Inf"} 572
traefik_entrypoint_request_duration_seconds_sum{code="200",entrypoint="traefik",method="GET",protocol="http"} 0.011785495999999996
traefik_entrypoint_request_duration_seconds_count{code="200",entrypoint="traefik",method="GET",protocol="http"} 572
traefik_entrypoint_request_duration_seconds_bucket{code="404",entrypoint="web",method="GET",protocol="http",le="0.1"} 1
traefik_entrypoint_request_duration_seconds_bucket{code="404",entrypoint="web",method="GET",protocol="http",le="0.3"} 1
traefik_entrypoint_request_duration_seconds_bucket{code="404",entrypoint="web",method="GET",protocol="http",le="1.2"} 1
traefik_entrypoint_request_duration_seconds_bucket{code="404",entrypoint="web",method="GET",protocol="http",le="5"} 1
traefik_entrypoint_request_duration_seconds_bucket{code="404",entrypoint="web",method="GET",protocol="http",le="+Inf"} 1
traefik_entrypoint_request_duration_seconds_sum{code="404",entrypoint="web",method="GET",protocol="http"} 2.7013e-05
traefik_entrypoint_request_duration_seconds_count{code="404",entrypoint="web",method="GET",protocol="http"} 1
traefik_entrypoint_request_duration_seconds_bucket{code="404",entrypoint="websecure",method="POST",protocol="http",le="0.1"} 9
traefik_entrypoint_request_duration_seconds_bucket{code="404",entrypoint="websecure",method="POST",protocol="http",le="0.3"} 9
traefik_entrypoint_request_duration_seconds_bucket{code="404",entrypoint="websecure",method="POST",protocol="http",le="1.2"} 9
traefik_entrypoint_request_duration_seconds_bucket{code="404",entrypoint="websecure",method="POST",protocol="http",le="5"} 9
traefik_entrypoint_request_duration_seconds_bucket{code="404",entrypoint="websecure",method="POST",protocol="http",le="+Inf"} 9
traefik_entrypoint_request_duration_seconds_sum{code="404",entrypoint="websecure",method="POST",protocol="http"} 0.00015051500000000002
traefik_entrypoint_request_duration_seconds_count{code="404",entrypoint="websecure",method="POST",protocol="http"} 9
# HELP traefik_entrypoint_requests_bytes_total The total size of requests in bytes handled by an entrypoint, partitioned by status code, protocol, and method.
# TYPE traefik_entrypoint_requests_bytes_total counter
traefik_entrypoint_requests_bytes_total{code="200",entrypoint="metrics",method="GET",protocol="http"} 0
traefik_entrypoint_requests_bytes_total{code="200",entrypoint="traefik",method="GET",protocol="http"} 0
traefik_entrypoint_requests_bytes_total{code="404",entrypoint="web",method="GET",protocol="http"} 0
traefik_entrypoint_requests_bytes_total{code="404",entrypoint="websecure",method="POST",protocol="http"} 0
# HELP traefik_entrypoint_requests_tls_total How many HTTP requests with TLS processed on an entrypoint, partitioned by TLS Version and TLS cipher Used.
# TYPE traefik_entrypoint_requests_tls_total counter
traefik_entrypoint_requests_tls_total{entrypoint="websecure",tls_cipher="TLS_AES_128_GCM_SHA256",tls_version="1.3"} 9
# HELP traefik_entrypoint_requests_total How many HTTP requests processed on an entrypoint, partitioned by status code, protocol, and method.
# TYPE traefik_entrypoint_requests_total counter
traefik_entrypoint_requests_total{code="200",entrypoint="metrics",method="GET",protocol="http"} 5
traefik_entrypoint_requests_total{code="200",entrypoint="traefik",method="GET",protocol="http"} 572
traefik_entrypoint_requests_total{code="404",entrypoint="web",method="GET",protocol="http"} 1
traefik_entrypoint_requests_total{code="404",entrypoint="websecure",method="POST",protocol="http"} 9
# HELP traefik_entrypoint_responses_bytes_total The total size of responses in bytes handled by an entrypoint, partitioned by status code, protocol, and method.
# TYPE traefik_entrypoint_responses_bytes_total counter
traefik_entrypoint_responses_bytes_total{code="200",entrypoint="metrics",method="GET",protocol="http"} 9722
traefik_entrypoint_responses_bytes_total{code="200",entrypoint="traefik",method="GET",protocol="http"} 1144
traefik_entrypoint_responses_bytes_total{code="404",entrypoint="web",method="GET",protocol="http"} 19
traefik_entrypoint_responses_bytes_total{code="404",entrypoint="websecure",method="POST",protocol="http"} 171
# HELP traefik_open_connections How many open connections exist, by entryPoint and protocol
# TYPE traefik_open_connections gauge
traefik_open_connections{entrypoint="metrics",protocol="TCP"} 2
traefik_open_connections{entrypoint="pg-pooler",protocol="TCP"} 0
traefik_open_connections{entrypoint="postgresql",protocol="TCP"} 0
traefik_open_connections{entrypoint="traefik",protocol="TCP"} 0
traefik_open_connections{entrypoint="web",protocol="TCP"} 0
traefik_open_connections{entrypoint="websecure",protocol="TCP"} 0

```

### What did you see instead?

I get service metrics like
```
traefik.service.requests.total
traefik.service.requests.tls.total
traefik.service.request.duration
traefik.service.retries.total
traefik.service.server.up
traefik.service.requests.bytes.total
traefik.service.responses.bytes.total
```

### What version of Traefik are you using?

v3.0.0

### What is your environment & configuration?

```yaml
# ref: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
additionalArguments:
  - "--log.level=DEBUG"
#  - "--providers.kubernetesingress.ingressclass=traefik-internal"

ports:
  postgresql:
    expose: 
      default: true
    port: 5432
    exposedPort: 5432
    protocol: TCP
    transport:
      respondingTimeouts:
        readTimeout: "0"
  pg-pooler:
    expose: 
      default: true
    port: 6432
    exposedPort: 6432
    protocol: TCP
    transport:
      respondingTimeouts:
        readTimeout: "0"

service:
  enabled: true
  ## -- Single service is using `MixedProtocolLBService` feature gate.
  ## -- When set to false, it will create two Service, one for TCP and one for UDP.
  single: true
  type: LoadBalancer
  # -- Additional annotations applied to both TCP and UDP services (e.g. for cloud provider specific config)
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: deregistration_delay.timeout_seconds=200,deregistration_delay.connection_termination.enabled=true,preserve_client_ip.enabled=false,stickiness.enabled=true,stickiness.type=source_ip
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /ping
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "9000"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTP
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

entryPoints:
  metrics:
    address: :8082

metrics:
  addInternals: true
  prometheus:
    addEntryPointsLabels: true 
    addRoutersLabels: false 
    addServicesLabels: true
    service:
      enabled: true
    entryPoint: metrics
    # -- enable optional CRDs for Prometheus Operator
    #
    # Create a dedicated metrics service for use with ServiceMonitor
    service:
      enabled: true
    # When set to true, it won't check if Prometheus Operator CRDs are deployed
    disableAPICheck: false 
    serviceMonitor:
      enabled: true
      metricRelabelings: 
        - sourceLabels: [__name__]
          separator: ;
          regex: ^fluentd_output_status_buffer_(oldest|newest)_.+
          replacement: $1
          action: drop
      relabelings: 
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          separator: ;
          regex: ^(.*)$
          targetLabel: nodename
          replacement: $1
          action: replace
      jobLabel: traefik
      interval: 30s
      honorLabels: true
    prometheusRule:
      additionalLabels: {}
      namespace: "default"
      rules:
        - alert: TraefikDown
          expr: up{job="traefik-metrics"} == 0
          for: 5m
          labels:
            context: traefik
            severity: warning
          annotations:
            summary: "Traefik Down"
            description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"

deployment:
  replicas: 2
priorityClassName: "system-node-critical"
```

### If applicable, please paste the log output in DEBUG level

```
2024-09-03T10:16:50Z INF github.com/traefik/traefik/v3/cmd/traefik/traefik.go:100 > Traefik version 3.0.4 built on 2024-07-02T13:46:37Z version=3.0.4
2024-09-03T10:16:50Z DBG github.com/traefik/traefik/v3/cmd/traefik/traefik.go:107 > Static configuration loaded [json] staticConfiguration={"api":{"dashboard":true},"entryPoints":{"metrics":{"address":":9100/tcp","forwardedHeaders":{},"http":{},"http2":{"maxConcurrentStreams":250},"transport":{"lifeCycle":{"graceTimeOut":"10s"},"respondingTimeouts":{"idleTimeout":"3m0s","readTimeout":"1m0s"}},"udp":{"timeout":"3s"}},"pg-pooler":{"address":":6432/tcp","forwardedHeaders":{},"http":{},"http2":{"maxConcurrentStreams":250},"transport":{"lifeCycle":{"graceTimeOut":"10s"},"respondingTimeouts":{"idleTimeout":"3m0s"}},"udp":{"timeout":"3s"}},"postgresql":{"address":":5432/tcp","forwardedHeaders":{},"http":{},"http2":{"maxConcurrentStreams":250},"transport":{"lifeCycle":{"graceTimeOut":"10s"},"respondingTimeouts":{"idleTimeout":"3m0s"}},"udp":{"timeout":"3s"}},"traefik":{"address":":9000/tcp","forwardedHeaders":{},"http":{},"http2":{"maxConcurrentStreams":250},"transport":{"lifeCycle":{"graceTimeOut":"10s"},"respondingTimeouts":{"idleTimeout":"3m0s","readTimeout":"1m0s"}},"udp":{"timeout":"3s"}},"web":{"address":":8000/tcp","forwardedHeaders":{},"http":{},"http2":{"maxConcurrentStreams":250},"transport":{"lifeCycle":{"graceTimeOut":"10s"},"respondingTimeouts":{"idleTimeout":"3m0s","readTimeout":"1m0s"}},"udp":{"timeout":"3s"}},"websecure":{"address":":8443/tcp","forwardedHeaders":{},"http":{"tls":{}},"http2":{"maxConcurrentStreams":250},"transport":{"lifeCycle":{"graceTimeOut":"10s"},"respondingTimeouts":{"idleTimeout":"3m0s","readTimeout":"1m0s"}},"udp":{"timeout":"3s"}}},"global":{"checkNewVersion":true,"sendAnonymousUsage":true},"log":{"format":"common","level":"DEBUG"},"metrics":{"addInternals":true,"prometheus":{"addEntryPointsLabels":true,"addServicesLabels":true,"buckets":[0.1,0.3,1.2,5],"entryPoint":"metrics"}},"ping":{"entryPoint":"traefik","terminatingStatusCode":503},"providers":{"kubernetesCRD":{},"kubernetesIngress":{},"providersThrottleDuration":"2s"},"serversTransport":{"maxIdleConnsPerHost":200},"tcpServersTransport":{"dialKeepAlive":"15s","dialTimeout":"30s"}}
2024-09-03T10:16:50Z INF github.com/traefik/traefik/v3/cmd/traefik/traefik.go:599 > Stats collection is enabled.
2024-09-03T10:16:50Z INF github.com/traefik/traefik/v3/cmd/traefik/traefik.go:600 > Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration.
2024-09-03T10:16:50Z INF github.com/traefik/traefik/v3/cmd/traefik/traefik.go:601 > Help us improve Traefik by leaving this feature on :)
2024-09-03T10:16:50Z INF github.com/traefik/traefik/v3/cmd/traefik/traefik.go:602 > More details on: https://doc.traefik.io/traefik/contributing/data-collection/
2024-09-03T10:16:50Z DBG github.com/traefik/traefik/v3/cmd/traefik/traefik.go:490 > Configured Prometheus metrics metricsProviderName=prometheus
2024-09-03T10:16:50Z INF github.com/traefik/traefik/v3/pkg/server/configurationwatcher.go:73 > Starting provider aggregator aggregator.ProviderAggregator
2024-09-03T10:16:50Z DBG github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:220 > Starting TCP Server entryPointName=pg-pooler
2024-09-03T10:16:50Z DBG github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:220 > Starting TCP Server entryPointName=postgresql
2024-09-03T10:16:50Z DBG github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:220 > Starting TCP Server entryPointName=traefik
2024-09-03T10:16:50Z DBG github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:220 > Starting TCP Server entryPointName=metrics
2024-09-03T10:16:50Z INF github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:202 > Starting provider *traefik.Provider
2024-09-03T10:16:50Z DBG github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:203 > *traefik.Provider provider configuration config={}
2024-09-03T10:16:50Z INF github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:202 > Starting provider *crd.Provider
2024-09-03T10:16:50Z DBG github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:203 > *crd.Provider provider configuration config={}
2024-09-03T10:16:50Z INF github.com/traefik/traefik/v3/pkg/provider/kubernetes/crd/kubernetes.go:90 > label selector is: "" providerName=kubernetescrd
2024-09-03T10:16:50Z INF github.com/traefik/traefik/v3/pkg/provider/kubernetes/crd/kubernetes.go:100 > Creating in-cluster Provider client providerName=kubernetescrd
2024-09-03T10:16:50Z DBG github.com/traefik/traefik/v3/pkg/server/configurationwatcher.go:227 > Configuration received config={"http":{"models":{"websecure":{"tls":{}}},"routers":{"ping":{"entryPoints":["traefik"],"priority":9223372036854775807,"rule":"PathPrefix(`/ping`)","ruleSyntax":"v3","service":"ping@internal"},"prometheus":{"entryPoints":["metrics"],"priority":9223372036854775807,"rule":"PathPrefix(`/metrics`)","ruleSyntax":"v3","service":"prometheus@internal"}},"serversTransports":{"default":{"maxIdleConnsPerHost":200}},"services":{"api":{},"dashboard":{},"noop":{},"ping":{},"prometheus":{}}},"tcp":{"serversTransports":{"default":{"dialKeepAlive":"15s","dialTimeout":"30s"}}},"tls":{},"udp":{}} providerName=internal
2024-09-03T10:16:50Z DBG github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:220 > Starting TCP Server entryPointName=web
2024-09-03T10:16:50Z DBG github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:220 > Starting TCP Server entryPointName=websecure
2024-09-03T10:16:50Z INF github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:202 > Starting provider *acme.ChallengeTLSALPN
2024-09-03T10:16:50Z DBG github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:203 > *acme.ChallengeTLSALPN provider configuration config={}
2024-09-03T10:16:50Z INF github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:202 > Starting provider *ingress.Provider
2024-09-03T10:16:50Z DBG github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:203 > *ingress.Provider provider configuration config={}
2024-09-03T10:16:50Z INF github.com/traefik/traefik/v3/pkg/provider/kubernetes/ingress/kubernetes.go:92 > ingress label selector is: "" providerName=kubernetes
2024-09-03T10:16:50Z INF github.com/traefik/traefik/v3/pkg/provider/kubernetes/ingress/kubernetes.go:102 > Creating in-cluster Provider client providerName=kubernetes
2024-09-03T10:16:50Z DBG github.com/traefik/traefik/v3/pkg/server/config
```
