### ISSUE TITLE
ability to disable http/3 on certain hosts

### ISSUE THREAD

**Issue by ivanjx** [traefik/traefik#11076]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

i want to be able to disable http/3 on certain hosts on the same port number. the way i usually do it with nginx in the past is to disable the `alt-svc` response header. i tried to create a middleware to remove the `alt-svc` header but didnt work.

```yaml
    mw-noh3:
      headers:
        customResponseHeaders:
          Alt-Svc: ""
```

as of why i want to disable http/3 is for openspeedtest. it does not seem to like http/3.
