### ISSUE TITLE
OpenTelemetry metric name issues

### ISSUE THREAD

**Issue by schewara** [traefik/traefik#11114]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

While reviewing the metrics for Traefik v3.1 with OpenTelemetry metrics enabled, I discovered some discrepancies which could be bugs and should be fixed or mentioned in the documentation depending on further analysis results.

The setup:

```mermaid
graph LR;
    traefik -- otlp --> otel-collector -- prometheus_exporter --> prometheus;
```

### What did you see instead?

The list of questionable metrics

| metric | comment |
| ------ | ------- |
| `http_client_duration_milliseconds_(bucket\|sum\|count)` | Only present for `net_peer_name="/var/run/docker.sock"`. As there is no mention in the docs about it, my guess would be that it should be actually `http_client_request_duration_seconds_(bucket\|sum\|count)` but is not. |
| `traefik_(entrypoint\|router\|service)_request_duration_seconds_milliseconds_(bucket\|sum\|count)` | This one is super confusing. Are the values now seconds or milliseconds. The output seems to be affected by the `add_metric_suffixes` setting of the [Prometheus Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusexporter/README.md), but as there is already a unit present, it is strange why this changes. |
| `traefik_open_connections_ratio` | the `_ratio` suffix seems also be coming from the [Prometheus Normalization](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/prometheus/README.md) of the otel-collector and also affected by the `add_metric_suffixes` setting |

My expectation would have been, that the type and unit suffixes behave the same, as looking at the Metrics documentation page shows identical metric names in the OpenTelementry and Prometheus tabs.

### What version of Traefik are you using?

```
Version:      3.1.3
Codename:     comte
Go version:   go1.23.1
Built:        2024-09-16T15:08:54Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
metrics:
  otlp:
    http:
      endpoint: "http://otel-collector:4318/v1/metrics"
    pushInterval: 10s
    addRoutersLabels: true
```

otel-collector config

```yaml
receivers:
  otlp:
    protocols:
      grpc: null
      http: null
exporters:
  logging:
    verbosity: normal
  prometheus:
    enable_open_metrics: true
    endpoint: 0.0.0.0:8080
    # add_metric_suffixes: false
processors:
  batch: null
  resource:
    attributes:
    - action: insert
      from_attribute: container.name
      key: service.name
    - action: upsert
      key: service.instance.id
      value: my.own.static.id
  resourcedetection/docker:
    detectors:
    - env
    - docker
    override: true
    timeout: 2s
  transform:
    metric_statements:
    - context: datapoint
      statements:
      - set(attributes["container.id"], resource.attributes["container.id"])
      - set(attributes["container.name"], resource.attributes["container.name"])
      - set(attributes["container.hostname"], resource.attributes["container.hostname"])
      - set(attributes["host.name"], resource.attributes["host.name"])
      - set(attributes["compose.project"], resource.attributes["compose.project"])
      - set(attributes["compose.service"], resource.attributes["compose.service"])
      - set(attributes["deployment.environment"], resource.attributes["deployment.environment"])
      - set(attributes["service.namespace"], resource.attributes["service.namespace"])
service:
  pipelines:
    metrics:
      exporters:
      - prometheus
      - logging
      processors:
      - resourcedetection/docker
      - resource
      - transform
      - batch
      receivers:
      - otlp
```
