### ISSUE TITLE
[DOCS] Add ingressclass definition in k8s quickstart

### ISSUE THREAD

**Issue by Arthurdw** [traefik/traefik#11118]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Follow the guide on a rke2 cluster

### What did you see instead?

No ingressclass was created

### What version of Traefik are you using?

v3.1

### What is your environment & configuration?

I had to add a ingressclass like this:
```yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik
spec:
  controller: traefik.io/ingress-controller
``` 
and in the whois example had to specifically say that I want to use traefik:
```diff
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ingress
spec:
+  ingressClassName: traefik
  # ...
  ```

Altough this fixes my issues, I feel like this should be mentioned in the docs for other people.

_(Thanks to all the maintainers for creating this amazing app <3)_
