### ISSUE TITLE
http3 and buffering does not work well

### ISSUE THREAD

**Issue by ivanjx** [traefik/traefik#11116]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

when using both with a web server that returns lots of data at the same time, for example: frigate debug page or a web server with a lot of images, it stops responding to further requests.

works fine if the browser does not connect via http3 by adding this middleware:
```yml
    mw-noh3:
      headers:
        customResponseHeaders:
          Alt-Svc: ""
```

### What did you see instead?

traefik stops responding

### What version of Traefik are you using?

v3.1.4

### What is your environment & configuration?

```yaml
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
          permanent: true
    transport:
      respondingTimeouts:
        readTimeout: 0
  websecure:
    address: ":443"
    http3: {}
    transport:
      respondingTimeouts:
        readTimeout: 0
```

```yml
    to-frigate:
      rule: "Host(`frigate.domain.com`)"
      service: frigate
      entryPoints:
        - web
        - websecure
      middlewares:
        - mw-errors
        - mw-auth
        - mw-buffering
      tls:
        certResolver: cloudflare
        domains:
          - main: "*.domain.com
```

```yml
    mw-auth:
      forwardAuth:
        address: "http://traefik-forward-auth:4181"
        authResponseHeaders:
          - "X-Forwarded-User"

    mw-errors:
      errors:
        status:
          - 401
        service: index
        query: "/{status}.html"
    
    mw-buffering:
      buffering:
        maxRequestBodyBytes: 4194304
        memRequestBodyBytes: 4194304
        memResponseBodyBytes: 33554432
```
