### ISSUE TITLE
Cloudflared Tunnel with Empty Request to Traefik

### ISSUE THREAD

**Issue by Axodouble** [traefik/traefik#11136]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

As the title implies, the request that Traefik seems to receive does not have any information, now I am lost and I do not know how to continue, other solutions I have found do not seem to work, for example setting the HTTP Host Header: https://imgur.com/a/BJXe55p

Unfortunately I cannot find any other solutions for this either, this is my current configuration:

Cloudflare:  
Cloudflare tunnel with http://rps.website.com, with a http service to traefik.  
With http settings containing the HTTP Host Header of rps.website.com.

Traefik:
```
  traefik:
    image: traefik
    hostname: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - exposed
      - private
```

### What did you see instead?

Log:
```
    192.168.128.4 - - [27/Sep/2024:20:14:18 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 1 "-" "-" 0ms
    192.168.128.4 - - [27/Sep/2024:20:16:20 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 2 "-" "-" 0ms
    192.168.128.4 - - [27/Sep/2024:20:17:28 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 3 "-" "-" 0ms
```

### What version of Traefik are you using?

Version:      3.1.4
Codename:     comte
Go version:   go1.23.1
Built:        2024-09-19T13:47:17Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
version: "3"

services:
  rockpaperscissors:
    image: ghcr.io/axodouble/rockpaperscissors:main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rockpaperscissors.rule=Host(`rps.website.com`)"
      - "traefik.http.services.rockpaperscissors.loadbalancer.server.port=80"
      - "traefik.http.routers.rockpaperscissors.entrypoints=web"
      - "traefik.http.routers.rockpaperscissors.tls=true"
    networks:
      - exposed
  
  tunnel:
    image: cloudflare/cloudflared
    restart: no
    command: tunnel run
    labels:
      - "traefik.enable=false"
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
    networks:
      - exposed
  
  traefik:
    image: traefik
    hostname: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - exposed
      - private

networks:
  exposed:
    driver: bridge
  private:
    driver: bridge
```
