### ISSUE TITLE
Error raised when configuring Traefik through CLI, referencing no yet discovered service (middleware)

### ISSUE THREAD

**Issue by nuxwin** [traefik/traefik#11145]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Good morning

For our project, we configure Traefik through CLI. For each entrypoints, we add the `errors` middleware which rely on a service configured through the Docker provider, so, it is referenced through CLI as `error-pages@docker`, or when using the Swarm provider, as `error-pages@swarm`. All is working as it should (see the provided screenshots), but when we start the Traefik instance, there is many (see below) errors raised.

Of course, from a strict point of view, these errors are expected because at the time Traefik is resolving the static configuration, the `error-pages` middleware has not been yet discovered. The thing is, those errors are not really TRUE, in sense that once the service were discovered, all is working as it should.

So, the idea here would be to defer configuration processing for options relying on services referenced as @docker or @swarm, meaning that those will be discovered later on. Of course, error handling should be still part of the process (eg, if after first discovering, service are still not defined ...)

Now, if the fact to reference a not yet discovered service should not be allowed, the error should be FATAL instead.

![Capture d’écran 2024-09-30 à 22 16 58](https://github.com/user-attachments/assets/d976145c-3a3b-40e8-ada3-dd1347985635)
![Capture d’écran 2024-09-30 à 22 18 10](https://github.com/user-attachments/assets/538e0e4a-4b82-4677-809a-f28cb7db83b6)
![Capture d’écran 2024-09-30 à 22 17 44](https://github.com/user-attachments/assets/58cc9808-67c7-49d7-a905-55b19988e6a1)
![Capture d’écran 2024-09-30 à 22 17 21](https://github.com/user-attachments/assets/6bf79d5d-cace-421d-afa0-0cbf49d5d823)

### What did you see instead?

```shell
iam-reverse-proxy-1  | 2024-09-30T19:57:33Z ERR error="middleware \"error-pages@docker\" does not exist" entryPointName=http routerName=acme-http@internal
iam-reverse-proxy-1  | 2024-09-30T19:57:33Z ERR error="middleware \"error-pages@docker\" does not exist" entryPointName=traefik routerName=api@internal
iam-reverse-proxy-1  | 2024-09-30T19:57:33Z ERR error="middleware \"error-pages@docker\" does not exist" entryPointName=traefik routerName=dashboard@internal
iam-reverse-proxy-1  | 2024-09-30T19:57:33Z ERR error="middleware \"error-pages@docker\" does not exist" entryPointName=traefik routerName=ping@internal
iam-reverse-proxy-1  | 2024-09-30T19:57:33Z ERR error="middleware \"error-pages@docker\" does not exist" entryPointName=http routerName=acme-http@internal
iam-reverse-proxy-1  | 2024-09-30T19:57:33Z ERR error="middleware \"error-pages@docker\" does not exist" entryPointName=traefik routerName=dashboard@internal
iam-reverse-proxy-1  | 2024-09-30T19:57:33Z ERR error="middleware \"error-pages@docker\" does not exist" entryPointName=traefik routerName=ping@internal
iam-reverse-proxy-1  | 2024-09-30T19:57:33Z ERR error="middleware \"error-pages@docker\" does not exist" entryPointName=traefik routerName=api@internal
```

### What version of Traefik are you using?

```shell
nuxwin@srv02:~/projects/git/agon-innovation/iam-helper/resources/traefik$ docker compose run iam-reverse-proxy traefik version 
[+] Creating 1/0
 ✔ Container traefik-iam-error-pages-1  Running                                                                                                                                        0.0s 
Version:      3.1.4
Codename:     comte
Go version:   go1.23.1
Built:        2024-09-19T13:47:17Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
services:
  # Traefik reverse proxy service.
  iam-reverse-proxy:
    image: traefik:v3.1
    command:
      - /bin/sh
      - -c
      - |
        mkdir -p ${IAM_HELPER_CACHE_DIR:-/opt/iam-helper/.cache}/traefik/dynamic/ \
        && touch ${IAM_HELPER_CACHE_DIR:-/opt/iam-helper/.cache}/traefik/acme.json \
        && chmod 0600 ${IAM_HELPER_CACHE_DIR:-/opt/iam-helper/.cache}/traefik/acme.json \
        && exec traefik \
        --log=true \
        --log.level='ERROR' \
        --log.filepath='/dev/stdout' \
        --log.format='common' \
        --accesslog='true' \
        --accesslog.addinternals='true' \
        --accesslog.filepath='/dev/stdout' \
        --accesslog.format='common' \
        --api=true \
        --api.dashboard='true' \
        --api.disabledashboardad='true' \
        --api.insecure='true' \
        --ping=true \
        --ping.entrypoint='traefik' \
        --entrypoints.traefik.address=':8080' \
        --entrypoints.traefik.http.middlewares='error-pages@docker' \
        --entrypoints.http.address=':80' \
        --entrypoints.http.http.middlewares='error-pages@docker' \
        --entryPoints.http.forwardedHeaders.insecure='true' \
        --entrypoints.http.http.encodequerysemicolons='true' \
        --entryPoints.http.http2.maxConcurrentStreams=50 \
        --entrypoints.https.address=':443' \
        --entrypoints.https.http.tls='true' \
        --entrypoints.https.http.middlewares='error-pages@docker' \
        --entryPoints.https.forwardedHeaders.insecure=true \
        --entrypoints.https.http.encodequerysemicolons=true \
        --entryPoints.https.http2.maxConcurrentStreams=50 \
        --providers.docker='true' \
        --providers.docker.constraints='Label(`iam.traefik.enable`, `true`)' \
        --providers.docker.exposedbydefault='false' \
        --providers.docker.watch='true' \
        --providers.docker.network='${IAM_NETWORK_NAME:-agon_iam_private}' \
        --providers.docker.endpoint='unix:///var/run/docker.sock' \
        --providers.file.directory='${IAM_HELPER_CACHE_DIR:-/opt/iam-helper/.cache}/traefik/dynamic/' \
        --providers.file.watch='true' \
        --certificatesresolvers.letsencrypt.acme.email='${LETSENCRYPT_ACCOUNT_EMAIL:-no_account}' \
        --certificatesresolvers.letsencrypt.acme.httpchallenge='true' \
        --certificatesresolvers.letsencrypt.acme.storage='${IAM_HELPER_CACHE_DIR:-/opt/iam-helper/.cache}/traefik/acme.json' \
        --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint='http'
    ports:
      # Entrypoints configuration (http).
      # Listen on port 80 (default) in the host and forward to port 80 in the container.
      - target: 80
        published: ${TRAEFIK_HTTP_PORT:-80}
        protocol: tcp
        mode: host
      # Entrypoints configuration (https).
      # Listen on port 443 (default) in the host and forward to port 443 in the container.
      - target: 443
        published: ${TRAEFIK_HTTPS_PORT:-443}
        protocol: tcp
        mode: host
      # Entrypoints configuration (traefik).
      # Listen on port 8080 (default) in the host and forward to port 8080 in the
      # container. Used for the Traefik dashboard.
      - target: 8080
        published: ${TRAEFIK_DASHBOARD_PORT:-8080}
        protocol: tcp
        mode: host
    stop_grace_period: 30s
    healthcheck:
      test: 'wget -qO- http://127.0.0.1:8080/ping || exit 1'
      interval: 30s
      timeout: 3s
      retries: 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - agon-iam-helper-cache:${IAM_HELPER_CACHE_DIR:-/opt/iam-helper/.cache}
      - $HOME/.iam/traefik:${IAM_HELPER_CACHE_DIR:-/opt/iam-helper/.cache}/traefik
    networks:
      - iam_private_network
    depends_on:
      - iam-error-pages

  # Error pages service for the reverse proxy.
  iam-error-pages:
    image: tarampampam/error-pages:3
    networks:
      - iam_private_network
    labels:
      - traefik.enable=true
      - iam.traefik.enable=true
      # Setup middlewares to use for this service.
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.port=${TRAEFIK_HTTPS_PORT:-443}
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=false
      - traefik.http.middlewares.gzip.compress=true
      # Setup HTTP router for this service.
      - traefik.http.routers.http-error-pages.entrypoints=http
      - traefik.http.routers.http-error-pages.middlewares=redirect-to-https
      - traefik.http.routers.http-error-pages.rule=HostRegexp(`.+`)
      - traefik.http.routers.http-error-pages.priority=1
      # Setup HTTPS router for this service.
      - traefik.http.routers.https-error-pages.entrypoints=https
      - traefik.http.routers.https-error-pages.middlewares=gzip
      - traefik.http.routers.https-error-pages.rule=HostRegexp(`.+`)
      - traefik.http.routers.https-error-pages.priority=1
      - traefik.http.routers.https-error-pages.service=https-error-pages
      # Setup service for this service.
      - traefik.http.services.https-error-pages.loadbalancer.server.port=8080
      # Setup error middleware which is used globally for error handling.
      - traefik.http.middlewares.error-pages.errors.status=401-599
      - traefik.http.middlewares.error-pages.errors.service=https-error-pages
      - traefik.http.middlewares.error-pages.errors.query=/{status}.html
    stop_grace_period: 30s
    environment:
      TEMPLATE_NAME: connection

networks:
  iam_private_network:
    name: ${IAM_NETWORK_NAME:-agon_iam_private}
    external: true

volumes:
  agon-iam-helper-cache:
    name: agon-iam-helper-cache
    external: true
```
