### ISSUE TITLE
RequestRedirect does'not preserve HTTP verb

### ISSUE THREAD

**Issue by BastienVigneron** [traefik/traefik#11190]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I've setup an `HTTPRoute` with a filter:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: drone-tls-redirect
  namespace: drone
spec:
  parentRefs:
  - name: internal-area-gateway
    sectionName: http
    namespace: traefik3
  hostnames:
  - drone.mydomain.io
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
```

The pb is the redirect transform the `POST` method in `GET` method, from the traefik logs:

```
10.16.1.61 - - [11/Oct/2024:10:23:06 +0000] "POST /hook?secret=my_secret HTTP/1.1" 301 17 "-" "-" 1462 "drone-drone-tls-redirect-internal-area-gateway-webInternal-0-89e598a4fcc949db1db8@kubernetesgateway" "-" 0ms
10.16.1.61 - - [11/Oct/2024:10:23:06 +0000] "GET /hook?secret=my_secret HTTP/1.1" 405 0 "-" "-" 1463 "drone-drone-http-route-internal-area-gateway-websecureInternal-0-89e598a4fcc949db1db8@kubernetesgateway" "http://10.16.1.77:80" 1ms 
``` 

### What did you see instead?

Like with Traefik V2, a redirect that keep HTTP verb:

```
10.16.1.61 - - [11/Oct/2024:10:22:24 +0000] "POST /hook?secret=my_secret HTTP/1.1" 200 972 "-" "-" 1441 "drone-drone-http-route-internal-area-gateway-websecureInternal-0-89e598a4fcc949db1db8@kubernetesgateway" "http://10.16.1.77:80" 37ms 
```

### What version of Traefik are you using?

traefik:v3.1.6

### What is your environment & configuration?

```yaml
        args:
          - "--global.checknewversion"
          - "--global.sendanonymoususage"
          - "--entryPoints.metrics.address=:9100/tcp"
          - "--entryPoints.traefik.address=:9000/tcp"
          - "--entryPoints.web.address=:8000/tcp"
          - "--entryPoints.webInternal.address=:8001/tcp"
          - "--entryPoints.websecure.address=:8443/tcp"
          - "--entryPoints.websecureInternal.address=:8444/tcp"
          - "--entryPoints.ssh-git.address=:8024/tcp"
          - "--api=true"
          - "--api.dashboard=true"
          - "--ping=true"
          - "--accesslog=true"
          - "--accesslog.addinternals=true"
          - "--metrics.prometheus=true"
          - "--metrics.prometheus.entrypoint=metrics"
          - "--metrics.otlp=true"
          - "--metrics.otlp.http=true"
          - "--metrics.otlp.http.endpoint=http://signoz-otel-collector.signoz.svc.cluster.local:4318"
          - "--tracing.otlp=true"
          - "--tracing.otlp.http=true"
          - "--tracing.otlp.http.endpoint=http://signoz-otel-collector.signoz.svc.cluster.local:4318"
          - "--providers.kubernetescrd.allowEmptyServices=true"
          - "--providers.kubernetesgateway"
          # - "--providers.kubernetesgateway.experimentalchannel"
          - "--log.level=INFO"
          - "--experimental.plugins.traefik-oidc-auth.modulename=github.com/sevensolutions/traefik-oidc-auth"
          - "--experimental.plugins.traefik-oidc-auth.version=v0.3.0"
```

Nothing special, we are just trying to move from `IngressRoute` with Traefik v2 to `HTTPRoute` with Traefik v3
