### ISSUE TITLE
The behavior of Kubernetes Ingress pathType Prefix does not align with Kubernetes docs

### ISSUE THREAD

**Issue by charlie0129** [traefik/traefik#11200]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Consider the following Ingress. We have two paths using Prefix:

- Backend: `/v1`
- Frontend: `/`

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "appName" . }}
spec:
  rules:
    - host: {{ include "appName" . }}.{{ .Values.domain }}
      http:
        paths:
          - path: /v1 # Backend
            pathType: Prefix
            backend:
              service:
                name:  {{ include "appName" . }}
                port:
                  number: 80
          - path: / # Frontend
            pathType: Prefix
            backend: 
              service:
                name: {{ include "frontAppName" . }}
                port:
                  number: 80       
```

According to [Kubernetes Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/#examples) documentation:

- `/v11` should match Frontend
- `/v1/something` should match Backend

### What did you see instead?

In our testing:

- `/v11` matched Backend

This is not consistent with [Kubernetes Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/#examples) documentation.

Kind | Path | Request Path | Matches?
-- | -- | -- | --
Prefix | /aaa/bbb | /aaa/bbbxyz | No, does not match string prefix

### What version of Traefik are you using?

v3.0.0

### What is your environment & configuration?

Traefik installed via Helm traefik-28.0.0
Kubernetes v1.28.4
