### ISSUE TITLE
502 Bad Gateway on dualstack services

### ISSUE THREAD

**Issue by viceice** [traefik/traefik#11206]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I've deployed a 3 node k3s cluster with dualstack network using calico.
I then enabled dualstack on a kubernetes service.

### What did you see instead?

I get almost always 502 errors from traefik.
It seems to only happen, when it tries to access the IPv6 endpoint which can be pinged from traefik pod.
It also only seems to happen on multi node cluster.

### What version of Traefik are you using?

```
Version:      3.1.6
Codename:     comte
Go version:   go1.23.2
Built:        2024-10-09T13:57:41Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  labels:
    app.kubernetes.io/name: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: whoami
  template:
    metadata:
      labels:
        app.kubernetes.io/name: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - name: http
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  labels:
    app.kubernetes.io/name: whoami
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: whoami
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: PreferDualStack

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  labels:
    app.kubernetes.io/name: whoami
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
spec:
  rules:
    - host: whoami.domain.test
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: whoami
                port:
                  name: http

```

Add more configuration information here.

If i enable nativelb or set service back to IPv4 only it works again.

**Comment by nmengin** [comment]
Hey @viceice,

Thank you for reaching out.

Could you please share your K3S configuration to create the same cluster as yours (3 nodes, dual stack, Calico)?
That would be helpful to reproduce the issue.

**Comment by viceice** [comment]
I think it should be reproducable on a two node cluster.
My cluster is bigger and has 3 controler and 5 worker nodes.
My cluster is also spread to two hosted vps (worker) connected to intranet via wireguard.


**k3s cluster**
version: v1.30.5+k3s1
```yaml
cluster-cidr: 10.42.0.0/16,fd01::/48
service-cidr: 10.43.0.0/16,fd02::/112

flannel-backend: none
disable-network-policy: true

disable:
  - traefik
  - servicelb
  - metrics-server
  - coredns
```

**calico (via tigera operator)**
repo: https://docs.tigera.io/calico/charts
chart: tigera-operator
version: v3.28.2
```yaml
installation:
  registry: quay.io
  # Configures Calico networking.
  calicoNetwork:
    mtu: 1342 # vxlan ipv6 (probably not relevant)
    nodeAddressAutodetectionV4:
      firstFound: false
      cidrs:
        - XX.XX.XX.0/24 # intranet, node has also a san network
    nodeAddressAutodetectionV6:
      firstFound: false
      cidrs:
        - 2001:XXXX:XXXX::/64 # intranet, node has also a san network

    ipPools:
      - blockSize: 26
        cidr: 10.42.0.0/16
        encapsulation: VXLAN
        natOutgoing: Enabled
        nodeSelector: all()

      - blockSize: 122
        cidr: fd01::/48
        encapsulation: VXLAN
        natOutgoing: Enabled
        nodeSelector: all()
```

**Comment by viceice** [comment]
@nmengin Anything else i can provide?

**Comment by nmengin** [comment]
Hello @viceice,

No, it's fine, we've added your issue to the bug to reproduce.

**Comment by jrderuiter** [comment]
I'm having a similar issue on a single node setup.

**Comment by jrderuiter** [comment]
The error I see in the Traefik pod is:

```
2025-05-11T17:47:02Z ERR Cannot create service error="service not found" ingress=dsmr namespace=dsmr-reader providerName=kubernetes serviceName=dsmr-reader servicePort=&ServiceBackendPort{Name:http,Number:0,}
```

**Comment by daegalus** [comment]
I am also encountering this issue, currently a single+node setup, but was planning to do a multi-node setup.

Regardless, I have this setup on a pure ipv6 vm on hetzner. The only ipv4 aspect is I have NAT64 and DNS64 setup to access Github and non-ipv6 services. Anything with an IP in my cluster is IPv6 only.

All my services are failing with Bad Gateway. The only one that doesn't is the TraefikService resource for the Traefik Dashboard. I will be testing to see if that will work for other services, but I am not going to spend time making TraefikServices for Helm charts I install, etc if that is the case.

This is my k3s config, some stuff is redacted for security. I will be using Tailscale for multi-node clustering. I use the public helm for Traefik, not the built in one to k3s.

```yaml
node-ip: fd7a:115c:a1e0::301:c565
node-external-ip: 2a01:4f8:xxx:xxx::1
cluster-cidr:
  - fd33:cafe:42:0::/56
service-cidr:
  - fd33:cafe:43:1::/112
disable:
  - traefik
vpn-auth: "name=tailscale,joinKey=tskey-auth-xxx...,extraArgs=--ssh"
tls-san:
  - lapis-lazuli.xxx-xxx.ts.net
write-kubeconfig-mode: "0644"
cluster-init: true
flannel-ipv6-masq: true
```
