### ISSUE TITLE
How to disable the cors@nomad middleware when using the Nomad provider?

### ISSUE THREAD

**Issue by alexreyes** [traefik/traefik#11227]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I expect to be able to modify the CORS headers for a nomad job. I did not expect to see that there is a default CORS middleware created when using Nomad with Traefik. 

### My setup:

I'm using the default Nomad provider with YAML:

```
          providers:
            nomad:
              endpoint:
                address: "http://127.0.0.1:4646"
                token: "${NOMAD_TOKEN}" 
```

Which seems to create a `cors@nomad` middleware:

![Image](https://github.com/user-attachments/assets/031dc3b2-1fa0-4595-822e-664e6413644c)

This is a problem because I want to customize the CORS headers being returned by a website hosted as a Nomad job. These default CORS headers set by the nomad job keep getting returned even when I create a new custom CORS middleware!

### Traefik version: 

traefik:v3.1 (using with Docker)
