### ISSUE TITLE
Desktop (macOS) Chrome pending more than 10s when access my blog, but it's very fast (less than 1s) on mobile (iOS) Chrome.

### ISSUE THREAD

**Issue by jaggerwang** [traefik/traefik#11224]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm using traefik to route traffics of my blog (https://blog.jaggerwang.net/), it's just a static site (using Nginx as the web server).

### What did you see instead?

When access my blog from desktop (macOS) Chrome (Version 130.0.6723.69 arm64), it is often pending more than 5s, sometimes even more than 10s, but it's very fast everytime (less than 1s) on mobile (iOS) Chrome, it's also very fast when request using curl.

It is pending for moren 10s for the first request when request in Chrome.
![Image](https://github.com/user-attachments/assets/b2de25b0-394e-4b97-a5f9-3eb325768d7f)

The console log did not print for more than ten seconds after I refreshed the page, so the problem seems related to the connection layer? It has nothing to do with whether https is used, I also tried using http without redirect to https.
![Image](https://github.com/user-attachments/assets/7d7454e0-47ce-4789-9a40-2c2cd7ce2844)

But it's very fast using curl (less than 1s).
![Image](https://github.com/user-attachments/assets/b0e7d27e-9fa0-4285-bd7f-85323f164347)

### What version of Traefik are you using?

```
$ docker run registry.cn-shanghai.aliyuncs.com/jaggerwang/traefik:v3.1 version
Version:      3.1.6
Codename:     comte
Go version:   go1.23.2
Built:        2024-10-09T13:57:41Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

I'm using Docker Compose to run my blog site, here is the Docker Compose file.
```yaml
services:
  traefik:
    image: registry.cn-shanghai.aliyuncs.com/jaggerwang/traefik:v3.1
    command:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=xxx"
      - "--certificatesresolvers.myresolver.acme.storage=/var/run/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/run/letsencrypt:/var/run/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirecttohttps.redirectscheme.scheme=https"
      - "traefik.http.middlewares.compressresponse.compress=true"
      - "traefik.http.middlewares.traefikauth.basicauth.users=xxx"
      - "traefik.http.routers.traefiksecure.rule=Host(`traefik.jaggerwang.net`)"
      - "traefik.http.routers.traefiksecure.entrypoints=websecure"
      - "traefik.http.routers.traefiksecure.tls.certresolver=myresolver"
      - "traefik.http.routers.traefiksecure.service=api@internal"
      - "traefik.http.routers.traefiksecure.middlewares=traefikauth"
  
  blog:
    image: registry.cn-shanghai.aliyuncs.com/jaggerwang/jw-blog
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirecttoblog.redirectregex.regex=^https://(?:www\\.)?jaggerwang\\.net/(.*)"
      - "traefik.http.middlewares.redirecttoblog.redirectregex.replacement=https://blog.jaggerwang.net/$${2}"
      - "traefik.http.routers.blog.rule=Host(`jaggerwang.net`) || Host(`www.jaggerwang.net`) || Host(`blog.jaggerwang.net`)"
      - "traefik.http.routers.blog.entrypoints=web"
      - "traefik.http.routers.blog.middlewares=redirecttohttps"
      - "traefik.http.routers.blogsecure.rule=Host(`jaggerwang.net`) || Host(`www.jaggerwang.net`) || Host(`blog.jaggerwang.net`)"
      - "traefik.http.routers.blogsecure.entrypoints=websecure"
      - "traefik.http.routers.blogsecure.tls.certresolver=myresolver"
      - "traefik.http.routers.blogsecure.middlewares=redirecttoblog,compressresponse"

```

And I'm using Nginx as my VitePress static site images's base image.

```Dockerfile
FROM registry.cn-shanghai.aliyuncs.com/jaggerwang/nginx:1.26

COPY .vitepress/dist /usr/share/nginx/html

```
