### ISSUE TITLE
Read labels from IngressClass

### ISSUE THREAD

**Issue by majkrzak** [traefik/traefik#11249]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I wanted to simplify my Ingresses configuration by splitting it to two classes, where one will be public another private.

It looked kinda obvious to me, that I can use ` traefik.ingress.kubernetes.io/router.middlewares: ...` on the IngressClass, instead of the Ingresses themselves. Apparently traefik ingnores such annotations.

In my opinion it would be extremely useful to be able to use some annotations on the IngressClasses, just like it is on Ingresses. Such implementation will also be relatively easy and quick.

```
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: private
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-authelia@kubernetescrd
spec:
  controller: traefik.io/ingress-controller
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: public
  annotations: {}
spec:
  controller: traefik.io/ingress-controller
```
