### ISSUE TITLE
Error while Peeking first byte

### ISSUE THREAD

**Issue by bogdanioanliviu** [traefik/traefik#11245]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Update to version 3.2.0 and this error `Error while Peeking first byte error`

This was not the case for 3.1.6

### What did you see instead?

```
2024-10-31T06:34:02+01:00 ERR Error while Peeking first byte error="read tcp 10.244.32.120:443->192.168.1.102:5711: read: connection reset by peer"
2024-10-31T06:34:02+01:00 ERR Error while Peeking first byte error="read tcp 10.244.32.120:443->192.168.1.102:37752: read: connection reset by peer"
```

### What version of Traefik are you using?

3.2.0

### What is your environment & configuration?

```yaml
api:
      insecure: true
      dashboard: true
    accessLog: {}
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
        http:
          tls: {}
    providers:
      kubernetesingress: {}
      kubernetesCRD: {}
    certificatesResolvers:
      file:
        acme:
          email: "removed"
          storage: "removed"
          certificatesDuration: 2160
          preferredchain: "ISRG Root X1"
          keytype: "RSA4096"
          dnschallenge:
            provider: "removed"
            resolvers: 
              - "1.1.1.1:53"
              - "8.8.8.8:53"
    metrics:
      influxDB2:
        address: "removed"
        token: "removed"
        org: "my_org"
        bucket: "trafik"
        pushInterval: 30s
        addServicesLabels: true
```

Kubernetes version 1.30.6
