### ISSUE TITLE
Compress middleware: duplicate 'Vary' header with already compressed backend

### ISSUE THREAD

**Issue by mazzz1y** [traefik/traefik#11259]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Similar issue: https://github.com/traefik/traefik/issues/6732

When I add compression middleware to a service that already includes compression, the Vary header is duplicated.

```bash
# plain nginx
» curl -i -H 'Accept-Encoding: gzip' 127.0.0.1:8080
HTTP/1.1 200 OK
...
Vary: Accept-Encoding
Content-Encoding: gzip

# nginx behind traefik
» curl -i -H 'Accept-Encoding: gzip' 127.0.0.1:8081
HTTP/1.1 200 OK
...
Vary: Accept-Encoding
Vary: Accept-Encoding
Transfer-Encoding: chunked
```

### What did you see instead?

The header should not be duplicated. Middleware should bypass already compressed requests without any modification

### What version of Traefik are you using?

```
Version:      3.2.0
Codename:     munster
Go version:   go1.23.2
Built:        2024-10-28T14:49:00Z
OS/Arch:      linux/amd64
````

### What is your environment & configuration?

```yaml
services:
  nginx:
    image: 'nginx:alpine'
    ports:
      - '127.0.0.1:8080:80'
    command: sh -c "echo 'gzip on;gzip_vary on;' > /etc/nginx/conf.d/gzip.conf && nginx -g 'daemon off;'"
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nginx.rule=PathPrefix(`/`)"
        - "traefik.http.services.nginx.loadbalancer.server.port=80"
        - "traefik.http.middlewares.nginx-compress.compress=true"
        - "traefik.http.routers.nginx.middlewares=nginx-compress"

  traefik:
    image: 'traefik:3.2.0'
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8081"
    ports:
      - '127.0.0.1:8081:8081'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
```
