### ISSUE TITLE
Zero downtime on rolling updates (PoC patch)

### ISSUE THREAD

**Issue by 5andr0** [traefik/traefik#11252]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Deploy a test stack and force an update
```
docker stack deploy -c test.yml test 
docker service update --force test_app
```

Run ApacheBench during update:
`ab -n 5000 -s 120 localhost:88/`

_Expected behavior_: no failed requests.

I'm not happy with the development of the issue https://github.com/traefik/traefik/issues/7886
I understand, that using the swarm load balancer with `traefik.docker.lbswarm=true` works flawlessly, but why even use traefik in the first place then? With the swarm lb I can't use any features like sticky sessions!

If I want to keep using traefiks lb with its features I have to set `--providers.swarm.refreshSeconds=1` which is not a satisfying solution because of the endless polls and it also adds ~1 sec delay in the test time.

The problem here is that swarm/docker.watch only listens for die events, which leaves too much time between the kill signal where the container is already stopping to answer requests.
```golang
case event := <-eventsc:
if event.Action == "start" ||
	event.Action == "die" ||
	strings.HasPrefix(string(event.Action), "health_status") {
	startStopHandle(event)
}
```

On a rolling update we're getting these events:
```
service update g4df9x05hdpwkxmdxxjcrn1o6 (name=test_app)
service update g4df9x05hdpwkxmdxxjcrn1o6 (name=test_app, updatestate.new=updating)
container create f7ec264a45cbf61b69e108eac7a235985e04ece791d8b9a56b2d0abafa44a4c7
network connect ipa6fafysfhh9umd3klbn7oy0 (container=f7ec264a45cbf61b69e108eac7a235985e04ece791d8b9a56b2d0abafa44a4c7
container start f7ec264a45cbf61b69e108eac7a235985e04ece791d8b9a56b2d0abafa44a4c7
container kill f31187a987bfe28730adc33ba7460784615542f9013eb67ed1b4cb2529912db0
network disconnect ipa6fafysfhh9umd3klbn7oy0 (container=f31187a987bfe28730adc33ba7460784615542f9013eb67ed1b4cb2529912db0
container stop f31187a987bfe28730adc33ba7460784615542f9013eb67ed1b4cb2529912db0
container die f31187a987bfe28730adc33ba7460784615542f9013eb67ed1b4cb2529912db0
```

I wrote a proof of concept patch which acts on kill and stop aswell
https://github.com/traefik/traefik/commit/537565ab29e0c9b21947e486b714e5d31f55fd53
##### [pkg/provider/docker/pdocker.go]
```golang
case event := <-eventsc:
if event.Action == "start" ||
	event.Action == "die" ||
	event.Action == "kill" ||
	event.Action == "stop" ||
.
.
.
func (p *Provider) listContainers(ctx context.Context, dockerClient client.ContainerAPIClient) ([]dockerData, error) {
	containerList, err := dockerClient.ContainerList(ctx, container.ListOptions{Filters: filters.NewArgs(
		filters.Arg("status", "created"),
		filters.Arg("status", "restarting"),
		filters.Arg("status", "running"),
	)})
```

With this patch I have zero failed requests and no extra second wait for lost requests
```
Complete requests:      5000
Failed requests:        0
```

It's only a poc, so I have not created a PR yet. I'd like to hear some input of you guys how to best implement it.
This poc will run containerlist 3 times when a container gets killed and all events are sent in following order: kill->stop->die
I also needed a containerlist filter to not include killed containers with status _removing|paused|exited|dead_

The best way to implement this would be to add a function to only add or remove a single container from the config build instead of listing all containers to rebuild the full config. There's too much inefficient redundancy here.
I think we should also wait after a start event until the container is fully running (or healthy) before it gets added to the config.
I don't have the time though to implement this, sorry!

### What did you see instead?

30 sec increase in test time due to request timeouts and failed requests.

### What version of Traefik are you using?

v3.1.7

### What is your environment & configuration?

```yaml
version: "3.9"
services:
  app:
    image: traefik/whoami
    networks:
      - swarm
    deploy:
      placement:
        constraints:
          - "node.role == manager"
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        #delay: 20s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.app.rule=PathPrefix(`/`)"
        - "traefik.http.services.app.loadbalancer.server.port=80"
        - "traefik.http.routers.app.entrypoints=web"
        #- traefik.docker.lbswarm=true

  load-balancer:
    image: traefik
    command:      
      - --providers.swarm
      - --providers.swarm.exposedbydefault=false
      - --providers.swarm.network=swarm
      #- --providers.swarm.refreshSeconds=1
      - "--entrypoints.web.address=:80"
    networks:
      - swarm
    ports:
      - target: 80
        published: 88
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - "node.role == manager"

networks:
  swarm:
    external: true
```

Add more configuration information here.
