### ISSUE TITLE
Traefik 3.1 acme renewal fails with tlsChallenge when multiple domains and one domain no longer points to server

### ISSUE THREAD

**Issue by ieugen** [traefik/traefik#11266]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Using traefik 3.1.x .

We've setup traefik with multiple acme cert resolvers, each with it's own file. 
We deployed a service with lots of domains ~ 42 .
Traefik got certs and things were ok. 
We moved some domains to be handled by another server and removed the domains from the service labels so traefik should not handle them.

On renewal day, traefik failed to renew the certs for the domains citing an issue with domains. 
We noticed this because of certificate monitoring via an external tool.

I've managed to fix the issue by stopping traefik, removing all the acme json files and starting traefik again.
However this is not something that should happen every time we move a domain from one server to anther. 

I believe traefik should hash the list of domains and try to get a new cert if it changes ?! 

### What did you see instead?

I saw errors in traefik logs. 

```
{"level":"error","providerName":"le-tls-challange.acme","acmeCA":"https://acme-v02.api.letsencrypt.org/directory","error":"error: one or more domains had a problem:\n[labelaebeta.mydomain.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for labelaebeta.mydomain.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for labelaebeta.mydomain.com - check that a DNS record exists for this domain\n","time":"2024-11-11T08:32:41Z","message":"Error renewing certificate from LE: {labelaebeta.mydomain.com []}"}
{"level":"info","providerName":"le-tls-challange.acme","acmeCA":"https://acme-v02.api.letsencrypt.org/directory","time":"2024-11-11T08:32:41Z","message":"Renewing certificate from LE : {Main:congressdev.myotherdomain.com SANs:[]}"}
{"level":"error","providerName":"le-tls-challange.acme","acmeCA":"https://acme-v02.api.letsencrypt.org/directory","error":"error: one or more domains had a problem:\n[congressdev.myotherdomain.com] acme: error: 400 :: urn:ietf:params:acme:error:tls :: 1x.x.x.78: remote error: tls: unrecognized name\n","time":"2024-11-11T08:32:47Z","message":"Error renewing certificate from LE: {congressdev.myotherdomain.com []}"}
{"level":"info","providerName":"le-tls-challange.acme","acmeCA":"https://acme-v02.api.letsencrypt.org/directory","time":"2024-11-11T08:32:47Z","message":"Renewing certificate from LE : {Main:labelaebeta.myotherdomain.com SANs:[]}"}
{"level":"error","providerName":"le-tls-challange.acme","acmeCA":"https://acme-v02.api.letsencrypt.org/directory","error":"error: one or more domains had a problem:\n[labelaebeta.mydomain.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for labelaebeta.mydomain.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for labelaebeta.mydomain.com - check that a DNS record exists for this domain\n[labelaebeta.myotherdomain.com] acme: error: 400 :: urn:ietf:params:acme:error:tls :: 1x.x.x.78: remote error: tls: unrecognized name\n","time":"2024-11-11T08:32:54Z","message":"Error renewing certificate from LE: {labelaebeta.myotherdomain.com []}"}
{"level":"info","providerName":"le-tls-challange.acme","acmeCA":"https://acme-v02.api.letsencrypt.org/directory","time":"2024-11-11T08:32:54Z","message":"Renewing certificate from LE : {Main:labelaedev.myotherdomain.com SANs:[]}"}
{"level":"error","providerName":"le-tls-challange.acme","acmeCA":"https://acme-v02.api.letsencrypt.org/directory","error":"error: one or more domains had a problem:\n[labelaedev.myotherdomain.com] acme: error: 400 :: urn:ietf:params:acme:error:tls :: 1x.x.x.78: remote error: tls: unrecognized name\n","time":"2024-11-11T08:32:58Z","message":"Error renewing certificate from LE: {labelaedev.myotherdomain.com []}"}
{"level":"info","providerName":"le-tls-challange.acme","acmeCA":"https://acme-v02.api.letsencrypt.org/directory","time":"2024-11-11T08:32:58Z","message":"Renewing certificate from LE : {Main:labeldev.myotherdomain.com SANs:[]}"}
{"level":"error","providerName":"le-tls-challange.acme","acmeCA":"https://acme-v02.api.letsencrypt.org/directory","error":"error: one or more domains had a problem:\n[labeldev.myotherdomain.com] acme: error: 400 :: urn:ietf:params:acme:error:tls :: 1x.x.x.78: remote error: tls: unrecognized name\n","time":"2024-11-11T08:33:06Z","message":"Error renewing certificate from LE: {labeldev.myotherdomain.com []}"}
{"level":"info","providerName":"le-tls-challange.acme","acmeCA":"https://acme-v02.api.letsencrypt.org/directory","time":"2024-11-11T08:33:06Z","message":"Renewing certificate from LE : {Main:label.myotherdomain.com SANs:[REDACTED_LONG_LIST_OF_DOMAINS]}"}
{"level":"error","providerName":"le-tls-challange.acme","acmeCA":"https://acme-v02.api.letsencrypt.org/directory","error":"error: one or more domains had a problem:\n[takedalablabel.myotherdomain.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 1x.1x.1x.123: Connection reset by peer\n","time":"2024-11-11T08:33:16Z","message":"Error renewing certificate from LE: {label.myotherdomain.com [REDACTED_LONG_LIST_OF_DOMAINS]}"}
```

### What version of Traefik are you using?

Version:      3.1.6
Codename:     comte
Go version:   go1.23.2
Built:        2024-10-09T13:57:41Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
log:
  level: INFO
  format: json

api:
  dashboard: true

metrics:
  prometheus: {}

providers:
  providersThrottleDuration: 10s
  file:
    filename: /etc/traefik/dynamic.yml
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    constraints: "Label(`traefik.constraint-label`, `traefik-public`)"
    exposedByDefault: false

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

certificatesResolvers:
  le:
    acme:
      email: REDACTED
      storage: /certificates/acme.json
      dnsChallenge:
        provider: route53
        delayBeforeCheck: "5"
  le-tls-challange:
    acme:
      email: REDACTED
      storage: /certificates/acme-tls-challange.json
      tlsChallenge: {}
  le-http01:
    acme:
      email: REDACTED
      storage: /certificates/acme-http01.json
      httpChallenge:
        entryPoint: http

```

I've omitted the dynamic configuration .
