### ISSUE TITLE
Traefik gateway time out with certain apps

### ISSUE THREAD

**Issue by tws101** [traefik/traefik#11272]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Migration from Docker in a Debian Jail to Native Docker on Truenas Scale....

Applications:
Prometheus
Grafana
Nextcloud

each were showing gateway time out..... At first I did not think it was traefik...

I striped nextcloud down to bare bones and even reinstalled it (clean install), it will work through traefik for a few moments then get a gateway time out..

Next I moved on to troubleshoot graphana and Prometheus and I realized as soon as I published a port and access them with Ip and port  they worked.....  

Now that I knew it was a traefik issue I began looking into the app traefik config which is simple for graphana and Prom...

Prom compose labels

```
labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.entrypoints=websecure
      - traefik.http.routers.prometheus.rule=Host(`${PROMETHEUS_DN}`)
      - traefik.http.routers.prometheus.tls=true
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
      - traefik.http.routers.prometheus.middlewares=authelia@docker
```

after not being able to fix it I went back to the other docker install and everything was working....  
All using the same version v3.2.0

then I realized the version were not the same as the image had been updated, index digest was different.... also the pinned versions all recent ones were updated and the issue is present even on v3.1.7....

I then went back to a version that the image had not been updated v3.1.6 and alleviated the issue

### What did you see instead?

Gateway time out on 

Applications:
Prometheus
Grafana
Nextcloud

***The other 43 applications are working fine

### What version of Traefik are you using?

v3.2.0
sha256:d12741b971f5c833919db2b680191dc23d5d96ef17e41a914e3c593a8c663ac4

Current on docker hub

I moved back to v3.1.6 to relieve the issue

### What is your environment & configuration?

My ingress Stack with Traefik

```yaml
networks:
  authelia:
    name: authelia
    ipam:
      driver: default
      config:
        - subnet: 172.24.5.0/24
          ip_range: 172.24.5.0/24
          gateway: 172.24.5.1
  proxy:
    name: proxy
    external: true
services:
  traefik:
    container_name: traefik
    image: traefik:${TRAEFIK_VERSION}
    hostname: traefik
    user: 0:568
    ports:
      - 80:80
      - 443:443
    expose:
      - 8080
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - CF_DNS_API_TOKEN=${CFT}
    networks:
      proxy:
        ipv4_address: 172.24.1.0
      authelia: null
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DN}`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=cloudflare
      - traefik.http.routers.traefik.tls.domains[0].main=${FQDN}
      - traefik.http.routers.traefik.tls.domains[0].sans=${SDN}
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.middlewares=authelia@docker
    volumes:
      - /var/run/docker.sock:/run/docker.sock:ro
      - ${TRAEFIK_YAML}:/etc/traefik/traefik.yaml:ro
      - ${TRAEFIK_CONFIG}:/etc/traefik/config.yaml:ro
      - ${TRAEFIK_CERTS}:/etc/traefik/certs/
  lldap:
    container_name: lldap
    image: lldap/lldap:${LLDAP_VERSION}
    hostname: lldap
    user: 0:568
    expose:
      - 17170 #WEB
      - 3890 #Database
    restart: unless-stopped
    environment:
      - PUID=568
      - TZ=${TZ}
      - LLDAP_JWT_SECRET=${SECRET}
      - LLDAP_KEY_SEED=${SECRET}
      - LLDAP_LDAP_BASE_DN=${DN}
    networks:
      - proxy
      - authelia
    labels:
      - traefik.enable=true
      - traefik.http.routers.lldap.entrypoints=websecure
      - traefik.http.routers.lldap.rule=Host(`${LLDAP_DN}`)
      - traefik.http.routers.lldap.tls=true
      - traefik.http.services.lldap.loadbalancer.server.port=17170
      - traefik.http.routers.lldap.middlewares=authelia@docker
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    volumes:
      - ${LLDAP_DATA}:/data
  authelia:
    container_name: authelia
    image: authelia/authelia:${AUTHELIA_VERSION}
    hostname: authelia
    user: 0:568
    expose:
      - 9091
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=568
    networks:
      - proxy
      - authelia
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`${AUTH_DN}`)
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.tls=true
      - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://${AUTH_DN}
      - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    depends_on:
      - redis
      - mariadb-authelia
    volumes:
      - ${AUTHELIA_CONFIG}:/config
  redis:
    container_name: redis
    image: bitnami/redis:${REDIS_VERSION}
    user: 5000:0
    expose:
      - 6379
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${SECRET}
      TZ: ${TZ}
    networks:
      - authelia
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    volumes:
      - ${REDIS_DATA}:/bitnami/
  mariadb-authelia:
    container_name: mariadb-authelia
    image: linuxserver/mariadb:${MARIADB_AUTHELIA_VERSION}
    user: 0:5000
    expose:
      - 3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${SECRET}
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: ${AUTHELIA_USER}
      MYSQL_USER: ${AUTHELIA_USER}
      MYSQL_PASSWORD: ${SECRET}
      PUID: 5000
      TZ: ${TZ}
    networks:
      - authelia
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    volumes:
      - ${MARIADB_AUTHELIA_CONFIG}:/config
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:${HOMARR_VERSION}
    hostname: homarr
    user: 568:568
    expose:
      - 7575
    restart: unless-stopped
    environment:
      - DEFAULT_COLOR_SCHEME=dark
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.homarr.entrypoints=websecure
      - traefik.http.routers.homarr.rule=Host(`${HOMARR_DN}`)
      - traefik.http.routers.homarr.tls=true
      - traefik.http.services.homarr.loadbalancer.server.port=7575
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    volumes:
      - ${HOMARR_CONFIG}:/app/data/configs
      - ${HOMARR_ICONS}:/app/public/icons
      - ${HOMARR_DATABASE}:/data
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:${UPTIMEKUMA_VERSION}
    expose:
      - 3001
    restart: unless-stopped
    environment:
      - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.entrypoints=websecure
      - traefik.http.routers.uptime-kuma.rule=Host(`${UPTIMEKUMA_DN}`)
      - traefik.http.routers.uptime-kuma.tls=true
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    volumes:
      - ${UPTIMEKUMA_DATA}:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
  nginx:
    container_name: nginx
    image: tws101/homelab:${WEBSERVER_VERSION}
    restart: unless-stopped
    expose:
      - 80
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.entrypoints=websecure
      - traefik.http.routers.nginx.rule=Host(`${FQDN}`)
      - traefik.http.routers.nginx.tls=true
      - traefik.http.services.nginx.loadbalancer.server.port=80
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G

```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

Nothing was logged, the log was empty
