### ISSUE TITLE
Add Support for Referencing Configuration Files via Docker Labels

### ISSUE THREAD

**Issue by kadirgun** [traefik/traefik#11279]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

In Traefik's integration with Docker, I suggest adding a feature to specify configuration files via Docker tags.

For example,
```yml
#compose.yml
services:
  nginx:
    image: nginx:alpine
    labels:
      - traefik.enable=true
      - traefik.config=traefik.yml
```

```yml
#traefik.yml
#Same as dynamic configuration file
http:
  routers:
    web:
      entryPoints:
        - web
      rule: Host(`example.com`)
      service: service-web
```
