### ISSUE TITLE
Change of offered cipher suites for http services/loadBalancers

### ISSUE THREAD

**Issue by MarauderXtreme** [traefik/traefik#11284]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We are running traefik infront of various services and also physical devices.
Our goal is to put everything with weak/weird/no encryption or just even a web interface behind traefik in private networks.
It worked until an update to 2.11.11.

### What did you see instead?

With an update to 2.11.11 and yesterday to 2.11.13 the connection to one of those physical devices stopped working and displayed a 502 Bad Gateway.
Debugging it and than capturing the packages we found that traefik had no matching cipher suites with the device.
The device answered the TLSv1.2 Client Hello from traefik with `Handshake Failure (40)` which we then found out that 40 means something along the lines of no matching cipher.

Traefik 2.11.13 offers the following cipher suites.

- `TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA`
- `TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA`
- `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA`
- `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA`
- `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`
- `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256`
- `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384`
- `TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384`
- `TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256`
- `TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256`
- `TLS_AES_128_GCM_SHA256`
- `TLS_AES_256_GCM_SHA384`
- `TLS_CHACHA20_POLY1305_SHA256`

Apparently a few cipher suites have been dropped in 2.11.x and we could not find anything of that matter in the changelog.
AFAIK it looks like all cipher suites without FS have been disabled.
The device accepts the following cipher suites which are still present in the 2.10.7:

- `TLS_RSA_WITH_AES_128_GCM_SHA256`
- `TLS_RSA_WITH_AES_256_GCM_SHA384`

It also accepts others like CBC and 3DES but lets not talk about them.

We even tried changing the accepted cipher suites in the router in the hopes that it somehow carries through to the service but to no avail.

Downgrading to 2.10.7 made it work again and unfortunately we have no option in changing any of the devices TLSv1.2 configuration.
Limiting cypher suites seems reasonable to us for routers but there we are able to change offered cipher suites which does not work for services.

### What version of Traefik are you using?

`2.11.13` and now downgraded to `2.10.7`.

### What is your environment & configuration?

Traefik is installed directly on a bare metal debian and run with systemd.
Every other router/service works fine.
The device itself is closed so we have no ability in upgrading the webserver or changing its configuration.
I changed IPs and anonymized some information but I hope that this is everything needed.

`/etc/traefik/file-provider.yml`

```yaml
http:
  routers:
    device:
      entrypoint:
        - websecure-device
      service: device@file
      rule: Host(`device.example.com`)
      tls:
        certResolver: cloudflare
  services:
    device:
      loadBalancer:
        servers:
          - url: https://192.168.100.2
        passHostHeader: true
        serversTransport: https-insecure@file
  serversTransports:
    http: []
    https-insecure:
      insecureSkipVerify: true
```

`/etc/traefik/traefik.yaml`

```yml
global:
  checkNewVersion: false
  sendAnonymousUsage: false
entryPoints:
  websecure-device:
    address: 192.168.101.2:443
providers:
  file:
    filename: /etc/traefik/file-provider.yaml
    watch: false
certificatesResolvers:
  cloudflare:
    acme:
      dnsChallenge:
        provider: cloudflare
        resolvers:
        - janet.ns.cloudflare.com
        - kianchau.ns.cloudflare.com
      email: user@example.com
      storage: /etc/traefik/acme.json
api:
  dashboard: true
```

`/etc/systemd/system/traefik.service`

```ini
# This unit file is retrieved from traefik github repository
# @see https://raw.githubusercontent.com/containous/traefik/master/contrib/systemd/traefik.service
[Unit]
Description=Traefik
Documentation=https://doc.traefik.io/traefik/
After=network-online.target
AssertFileIsExecutable=/usr/bin/traefik
AssertPathExists=/etc/traefik/traefik.yaml

[Service]
User=traefik
Group=traefik
AmbientCapabilities=CAP_NET_BIND_SERVICE
EnvironmentFile=/etc/traefik/traefik.env
Type=notify
ExecStart=/usr/bin/traefik --configFile=/etc/traefik/traefik.yaml
Restart=always
WatchdogSec=1s
# lock down system access
# prohibit any operating system and configuration modification
ProtectSystem=strict
# create separate, new (and empty) /tmp and /var/tmp filesystems
PrivateTmp=true
# make /home directories inaccessible
ProtectHome=true
# turns off access to physical devices (/dev/...)
PrivateDevices=true
# make kernel settings (procfs and sysfs) read-only
ProtectKernelTunables=true
# make cgroups /sys/fs/cgroup read-only
ProtectControlGroups=true

# allow writing of acme.json
ReadWritePaths=/etc/traefik/acme.json
# depending on log and entrypoint configuration, you may need to allow writing to other paths, too

[Install]
WantedBy=multi-user.target
```

### If applicable, please paste the log output in DEBUG level

The only output visible is the following:

`level=debug msg="'502 Bad Gateway' caused by: remote error: tls: handshake failure"`
