### ISSUE TITLE
middleware not found ( but it is defined ) ( unable to download: 404 )

### ISSUE THREAD

**Issue by AlexVeeBee** [traefik/traefik#11296]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I was just updating and restarting the server

### What did you see instead?

A 404 not found page

### What version of Traefik are you using?

Version:      3.2.1
Codename:     munster
Go version:   go1.23.3
Built:        2024-11-20T17:39:47Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

compose file
```yaml
version: "3.8"

services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      GID: "${GID-1000}"
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik"
    volumes:
      - ./crowdsec-config/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./crowdsec-config:/etc/crowdsec/
      - ./crowdsec-db:/var/lib/crowdsec/data/
#      - ./traefik-logs:/var/log/traefik/:ro
    ports:
      - 6060:6060
    networks:
      - management 
    depends_on:
      - traefik
    restart: unless-stopped

  bouncer-traefik:
    image: docker.io/fbonalair/traefik-crowdsec-bouncer:latest
    container_name: bouncer-traefik
    environment:
      CROWDSEC_BOUNCER_API_KEY: [REDACTED]
      CROWDSEC_AGENT_HOST: crowdsec:8080
      GIN_MODE: release
    restart: unless-stopped
    networks:
      - management 
    depends_on:
      - crowdsec


  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik
    ports:
      - 80:80
      - 443:443
      # - 8192:8080 # Dashboard NOT RECOMMENDED FOR PRODUCTION
    volumes:
      - ./traefik-data:/etc/traefik
# UNCOMMENT BELOW FOR GRAFANA LOGGING OF TRAEFIK
      - ./grafana/fluent/logs:/logs
      - ./grafana/fluent/logs:/var/log/crowdsec
      - /var/run/docker.sock:/var/run/docker.sock # Disable this when you enable dockersocket
    labels:
      traefik.enable: true   # Enable Traefik reverse proxy for the Traefik dashboard.
      traefik.http.routers.api.rule: Host(`traefik.alexveebee.nl`)    # Define the subdomain for the traefik dashboard.
      traefik.http.routers.api.entryPoints: https    # Set the Traefik entry point.
      traefik.http.routers.api.service: api@internal    # Enable Traefik API.
      traefik.http.routers.api.middlewares: auth@file
    environment:
      CF_DNS_API_TOKEN: [REDACTED]
    restart: unless-stopped
    networks:
      - management 

networks:
  management :
    driver: bridge
    external: true
```

traefik.yml
```yml
global:
  checkNewVersion: true
  sendAnonymousUsage: false
serversTransport:
  insecureSkipVerify: true

entryPoints:
  # Not used in apps, but redirect everything from HTTP to HTTPS
  http:
    address: :80
    forwardedHeaders:
      trustedIPs: &trustedIps
        # Start of Clouflare public IP list for HTTP requests, remove this if you don't use it
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/12
        - 172.64.0.0/13
        - 131.0.72.0/22
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
        # End of Cloudlare public IP list
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  # HTTPS endpoint, with domain wildcard
  https:
    address: :443
    forwardedHeaders:
     # Reuse list of Cloudflare Trusted IP's above for HTTPS requests
      trustedIPs: *trustedIps
    http:
      tls:
        # Generate a wildcard domain certificate
        certResolver: letsencrypt
        domains:
          - main: alexveebee.nl
            sans:
              - '*.alexveebee.nl'
          - main: alexveebee.is
            sans:
              - '*.alexveebee.is'
      middlewares:
        - securityHeaders@file
        - crowdsec-bouncer@file
        - gzip@file
        - cloudflarewarp@file # <<< Error start here

  metrics:
      address: ":8083"


providers:
  providersThrottleDuration: 2s

  # File provider for connecting things that are outside of docker / defining middleware
  file:
    filename: /etc/traefik/fileConfig.yml
    watch: true

  # Docker provider for connecting all apps that are inside of the docker network
  docker:
    watch: true
    network: management # Add Your Docker Network Name Here
    # Default host rule to containername.domain.example
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\"}}.alexveebee.nl`)"
    # swarmModeRefreshSeconds: 15s
    # Enable if swarm is used https://doc.traefik.io/traefik/master/migration/v2-to-v3/
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"

# Enable traefik ui
api:
  dashboard: false
  insecure: true
  debug: true

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    entryPoint: metrics

# :8083/ping  
ping:
  entryPoint: metrics


log:
  level: DEBUG # DEBUG, INFO, WARN, ERROR, FATAL, and PANIC
  filePath: "/logs/traefik.log"
  format: json
  
accessLog:
  filePath: "/var/log/crowdsec/traefik_access.log"
  bufferingSize: 50
  format: json
  filters:
    statusCodes:
      - "400-404"
      - "300-302"
      - "500"
    retryAttempts: true
    minDuration: "10ms"
  # fields:
  #   defaultMode: foobar
  #   names:
  #     name0: foobar
  #     name1: foobar
  #   headers:
  #     defaultMode: foobar
  #     names:
  #       name0: foobar
  #       name1: foobar
# 


# Use letsencrypt to generate ssl serficiates
certificatesResolvers:
  letsencrypt:
    acme:
      email: info@alexveebee.nl  # change to your provider account email address.
      storage: /etc/traefik/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      dnsChallenge:
        provider: cloudflare
       # Used to make sure the dns challenge is propagated to the rights dns servers
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"


# Plugins (optional)
# Real IP from Cloudflare Proxy/Tunnel
experimental:
  plugins:
    cloudflarewarp:
      moduleName: github.com/BetterCorp/cloudflarewarp
      version: "v1.3.3"
```

fileConfig.yml
```yml
http:
  ## EXTERNAL ROUTING EXAMPLE - Only use if you want to proxy something manually ##
  routers:
    # jellyfin:
    #   entryPoints:
    #     - https
    #   rule: 'Host(`flix.alexveebee.nl`)'
    #   service: jellyfin
    #   middlewares:
    #     - cloudflarewarp

    
    outage:
      entryPoints:
        - https
      rule: 'Host(`*.alexveebee.nl`)'
      service: outage

    flix:
      entryPoints:
        - https
      rule: 'Host(`flix.alexveebee.nl`)'
      service: outage

    reflix:
      entryPoints:
        - https
      rule: 'Host(`reflix.alexveebee.nl`)'
      service: outage

    radio:
      entryPoints:
        - https
      rule: 'Host(`radio.alexveebee.nl`)'
      service: outage

    seafile:
      entryPoints:
        - https
      rule: 'Host(`seafile.alexveebee.nl`)'
      service: outage

    git:
      entryPoints:
        - https
      rule: 'Host(`git.alexveebee.nl`)'
      service: outage

    wiki:
      entryPoints:
        - https
      rule: 'Host(`wiki.alexveebee.nl`)'
      service: outage

    blog:
      entryPoints:
        - https
      rule: 'Host(`blog.alexveebee.nl`)'
      service: outage

    photos:
      entryPoints:
        - https
      rule: 'Host(`photos.alexveebee.nl`)'
      service: outage
    
    office:
      entryPoints:
        - https
      rule: 'Host(`onlyoffice.alexveebee.nl`)'
      service: outage

    # traefik router


  ##======================SERVICES======================##
  # Define the base URL for srv-prod-1
  #srv_prod_1_url: &srv_prod_1_url http://192.168.x.x

  services:
    # service example
    outage:
      loadBalancer:
        servers:
          - url: http://192.168.1.219:4242

    jellyfin:
      loadBalancer:
        servers:
          - url: http://192.168.1.219:8110

  ##======================MIDDLEWARES======================##
  middlewares:
    # Only Allow Local networks
    ip-allowlist:
      ipAllowList:
        sourceRange:
          - 127.0.0.1/32 # localhost

  # Only Allow Trafic trough Authentik
    auth:
      forwardauth:
        address: http://authentik:9000/outpost.goauthentik.io/auth/traefik
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version

    # Crowdsec bouncer
    crowdsec-bouncer:
      forwardauth:
        address: http://bouncer-traefik:8080/api/v1/forwardAuth
        trustForwardHeader: true

    # Plugins (optional)
    # Real IP from Cloudflare Proxy/Tunnel
    cloudflarewarp:
      plugin:
        cloudflarewarp:
          disableDefault: false
          trustip: # Trust IPS not required if disableDefault is false - we will allocate Cloud Flare IPs automatically
            - "2400:cb00::/32"

    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex" # Prevents search engines from indexing the page and displaying it in search results.
          X-Forwarded-Proto: "https" # Indicates that the original request was sent over HTTPS.
          server: "" # Hides the server version and type by sending an empty Server header.
        sslProxyHeaders:
          X-Forwarded-Proto: https # Indicates to the backend server that the original request was sent over HTTPS.
        referrerPolicy: "same-origin" # Sends the referrer information only when navigating within the same origin.
        hostsProxyHeaders:
          - "X-Forwarded-Host" # Provides the original host requested by the client when proxies are used.
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        contentTypeNosniff: true # Prevents browsers from interpreting files as a different MIME type.
        browserXssFilter: true # Enables the cross-site scripting (XSS) filter in browsers.
        forceSTSHeader: true # Forces browsers to use HTTPS and prevents them from using HTTP.
        stsIncludeSubdomains: true # Applies the STS policy to all subdomains.
        stsSeconds: 63072000 # Specifies the duration (in seconds) for which the STS policy is in effect.
        stsPreload: true # Indicates the domain's intention to be included in browsers' preloaded HSTS lists.
    gzip:
      compress: {} # Enables gzip compression for responses to reduce bandwidth.


# Only use secure ciphers - https://ssl-config.mozilla.org/#server=traefik&version=2.6.0&config=intermediate&guideline=5.6
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
```

### If applicable, please paste the log output in DEBUG level

[traefik.log](https://github.com/user-attachments/files/17853127/traefik.log)
