### ISSUE TITLE
TLS errors only shown in debug mode

### ISSUE THREAD

**Issue by lboynton** [traefik/traefik#11292]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

My report seems the same as https://github.com/traefik/traefik/issues/9768.

It looks like some TLS errors are not shown unless debug level logs are enabled with `--log.level=DEBUG`. In our case we attempted to proxy to a downstream service that uses a self-signed TLS cert, and noticed requests return a 500 error to the client and nothing in the logs to indicate why. 

```
curl -H "Host: example.domain" <random>.elb.eu-west-2.amazonaws.com/test -i
HTTP/1.1 500 Internal Server Error
```

When setting the log level to debug it becomes clear:

```
2024-11-20T16:01:41Z DBG github.com/traefik/traefik/v3/pkg/proxy/httputil/proxy.go:113 > 500 Internal Server Error error="tls: failed to verify certificate: x509: cannot validate certificate for 10.100.1.100 because it doesn't contain any IP SANs"
```

This can be fixed in our case by configuring a `ServersTransport` resource referencing a secret created by cert-manager and specifying the `serverName`, and adding the `traefik.ingress.kubernetes.io/service.serverstransport` annotation on the service to use it.

```
---
apiVersion: v1
kind: Service
metadata:
  name: downstream-service
  annotations:
    traefik.ingress.kubernetes.io/service.serverstransport: default-traefik-test@kubernetescrd
spec:
  ports:
  - targetPort: 5000
    port: 443
    name: nginx-https
  selector:
    app: downstream-service
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-test
spec:
  serverName: downstream-service.default.svc.cluster.local
  rootCAsSecrets:
    - myca
---
apiVersion: v1
kind: Secret
metadata:
  name: myca
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
```

### What did you see instead?

No errors present in the log unless debug logs enabled.

### What version of Traefik are you using?

3.2.0

### What is your environment & configuration?

The rest of our set up looks like this:

```
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: downstream-service
spec:
  commonName: downstream-service.default.svc.cluster.local
  dnsNames:
  - downstream-service.default.svc.cluster.local
  duration: 720h
  renewBefore: 360h
  issuerRef:
    kind: ClusterIssuer
    name: internal-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    rotationPolicy: Always
    size: 2048
  secretName: myca
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
spec:
  ingressClassName: traefik
  rules:
    - host: example.domain
      http:
        paths:
          - path: /test
            pathType: Prefix
            backend:
              service:
                name: downstream-service
                port:
                  number: 443
```

### If applicable, please paste the log output in DEBUG level

```
2024-11-20T16:01:41Z DBG github.com/traefik/traefik/v3/pkg/proxy/httputil/proxy.go:113 > 500 Internal Server Error error="tls: failed to verify certificate: x509: cannot validate certificate for 10.100.1.100 because it doesn't contain any IP SANs"
```
