### ISSUE TITLE
Weird Command Order Differences in SMTP TCP connection without TLS

### ISSUE THREAD

**Issue by MondoGao** [traefik/traefik#11302]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

As discussed here: https://github.com/stalwartlabs/mail-server/discussions/356#discussioncomment-11360578

I'm trying to proxy port 25 and 587 for a SMTP mail server. And traefik behaves differently with no proxy included situation.

Setting: 
- Proxy protocol disabled for port 25
- Stalwart implicit tls for 25 is disabled, and the port is exposed to different port, e.g. 8025
- Traefik entrypoint 25 -> router SNI * -> 8025, neither TLS nor TLS passthrough is enabled.

### What did you see instead?

Testing:
1. direct access to stalwart by telnet and port 25: without sending any command, we receive the welcom msg from stalwart server.
![CleanShot 2024-11-23 at 20 18 44](https://github.com/user-attachments/assets/c703013f-8059-4bb0-a340-eb85ad05ba60)
2. through traefik 25 -> 8025:  we can only receive the welcom msg after sending first packet (e.g. an invalid ehlo command as shown here)
![CleanShot 2024-11-23 at 20 22 14](https://github.com/user-attachments/assets/b19771e2-25bf-4f6c-aab6-6b8d8ea317e3)

I believe Traefik might be rejecting or buffering the initial welcome message from the mail server for some reason, and this affects all the mail clients I've tried so far.

The general recommendation for avoiding this issue is do not proxy any plain tcp (no tls and starttls) ports though traefix at all. And this is exactly what the above anwser suggests.

### What version of Traefik are you using?

3.2.1

### What is your environment & configuration?

```yaml
# docker-compose
services:
    container_name: stalwart-mail
    image: stalwartlabs/mail-server:latest
    ports:
      - 8025:25 # SMTP
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.smtp.rule=HostSNI(`*`)
      - traefik.tcp.routers.smtp.entrypoints=smtp
      - traefik.tcp.routers.smtp.service=smtp@file
```

```yaml
# traefik.yml
entryPoints:
  smtp:
    address: :25
providers:
  docker:
  file:
    directory: ./config
```

```yaml
# config/stalwart.toml
[[tcp.services.smtp.loadBalancer.servers]]
address = "127.0.0.1:8025"
```

### If applicable, please paste the log output in DEBUG level

Noting special printed while conducting expr.

**Comment by nmengin** [comment]
Hey @MondoGao,

Thanks for reaching out.

If any community member can help us find verified steps to reproduce and fix the issue if possible, we would love the help.

**Comment by zone-zero** [comment]
I'm seeing the same issue with a postfix pod running plain SMTP on port 25 internally, and trying to expose it via port 25252 externally.


Ingress:
```YAML
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mail-ingress-tcp
  namespace: notify

spec:
  entryPoints:
    - mail-tcp
  routes:
  - match: HostSNI(`*`)
    services:
    - name: mail
      port: 25
```
Traefik helmrelease via Flux (with other ports redacted)
```YAML
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress
spec:
  interval: 10m
  chart:
    spec:
      chart: ./traefik
      version: "~3.5.0"
      sourceRef:
        kind: GitRepository
        name: traefik
        namespace: flux-system
  values:
    installCRDs: true
    deployment:
      replicas: 1
    service:
      type: LoadBalancer
      annotations:
    ports:

   ...

      mail-tcp:
        port: 25252
        expose:
          default: true
        exposedPort: 25252
        protocol: TCP

   ...
    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true" # ignore cert errors when communicating with containers
      - "--api.insecure=true" #expose api so it can be accessed by k8s services

    providers:
      kubernetesCRD:
        allowCrossNamespace: true

```
