### ISSUE TITLE
[BUG] `--api.basepath` is not recognized as a command

### ISSUE THREAD

**Issue by Copystrike** [traefik/traefik#11315]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

In my Docker Compose setup, I have configured a Traefik service. My goal is to keep the dashboard accessible and remap the dashboard's /api endpoint to /proxy/api. Here is my configuration:

```yaml
  traefik:
      image: traefik:v3.2.1
      command:
        - "--api.insecure=true" # Only for testing; ensure proper authentication in production
        - "--api.dashboard=true"
        - "--api.basepath=proxy"
        - "--providers.docker=true"
        - "--entrypoints.web.address=:80"
      ports:
        - "80:80"
        - "8080:8080"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
      labels:
        traefik.enable: "true"
```

However, it appears that the `--api.basepath` command is not recognized.

https://github.com/traefik/traefik/blob/33c1d700c02ad09ab793673a14674b39d78fe352/docs/content/reference/static-configuration/cli-ref.md?plain=1#L44-L47

### What did you see instead?

```
 ✔ Container devops-server-mysql-1     Running                                                          0.0s 
 ✔ Container devops-server-backend-1   Running                                                          0.0s 
 ✔ Container devops-server-frontend-1  Running                                                          0.0s 
 ✔ Container devops-server-traefik-1   Started                                                          0.8s 
 ✔ Container devops-server-jenkins-1   Running                                                          0.0s 
root@S140700:~/devops-server# docker logs devops-server-traefik-1
{"level":"error","error":"command traefik error: failed to decode configuration from flags: field not found, node: basepath","time":"2024-12-03T16:06:08Z","message":"Command error"}
```

### What version of Traefik are you using?

traefik:v3.2.1

### What is your environment & configuration?

```yaml
  traefik:
      image: traefik:v3.2.1
      command:
        - "--api.insecure=true" # For testing only; use proper auth in production
        - "--api.dashboard=true"
        - "--api.basepath=proxy"
        - "--providers.docker=true"
        - "--entrypoints.web.address=:80"
      ports:
        - "80:80"
        - "8080:8080"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
      labels:
        traefik.enable: "true"
```

### If applicable, please paste the log output in DEBUG level

N/A
