### ISSUE TITLE
Incorrect doc for maxRequestBodyBytes?

### ISSUE THREAD

**Issue by mrypdm** [traefik/traefik#11323]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We sending large POST request (~100 MB) through Traefik v3.1.2 and it is fails with `EOF occurred in violation of protocol` on client side

According to docs ([Traefik Buffering Documentation - Traefik](https://doc.traefik.io/traefik/middlewares/http/buffering/#maxrequestbodybytes)) `maxRequestBodyBytes=0` by default which means that there is no limitation for body size.

But if we add `maxRequestBodyBytes=0` explicitly, error does not happening.

Also, if we add `memRequestBodyBytes=115343360` (110 MB), which is by default 1 MB, the error does not occur either.

Also, if we send requests smaller than 1 MB, there is no error, but for larger sizes the error appears.

### What did you see instead?

There is a suspicion that `maxRequestBodyBytes` is actually not 0 by default, but is equal to or slightly greater than `memRequestBodyBytes`

### What version of Traefik are you using?

3.1.2

### What is your environment & configuration?

main config:

```yaml
---
log:
  level: "INFO"

global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  http:
    address: ":80"
    transport:
      respondingTimeouts:
        readTimeout: "0s"
    forwardedHeaders:
      trustedIPs:
        - "***"
  https:
    address: ":443"
    http:
      tls: true
    transport:
      respondingTimeouts:
        readTimeout: "0s"
    forwardedHeaders:
      trustedIPs:
        - "***"
  traefik:
    address: ":8080"

api:
  dashboard: true
  disabledashboardad: true

ping:
  entryPoint: "traefik"

metrics:
  datadog:
    address: ***

providers:
  file:
    directory: "/etc/traefik.d/dynamic"
  consulCatalog:
    prefix: "traefik"
    exposedByDefault: false
    defaultRule: "Host(`***`)"
    refreshInterval: "5s"
    endpoint:
      address: "***"
    stale: true
```

dynamic config:

```yaml
---
http:
  routers:
    catchall:
      entryPoints:
        - "http"
        - "https"
      rule: "PathPrefix(`/`)"
      service: unavailable
      priority: 1
  services:
    unavailable:
      loadBalancer:
        servers: {}

tls:
  stores:
    default:
      defaultCertificate:
        certFile: ***
        keyFile: ***
```

And during testing we added buffering settings via Consul in the label format.
