### ISSUE TITLE
Server-Side event in traefik - Waiting (TTFB)  Time is too long

### ISSUE THREAD

**Issue by mcxla** [traefik/traefik#11333]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have a server that has a URL that response sse

When I request this URL, it will give  me a  response that Content-Type is text/event-stream,and it will continuously return JSON object to me.

I want to use ytraefik as a proxy for this server.（And I need to use http router instead of TCP） 

### What did you see instead?

I tried to request this server directly and through Teaefik respectively, and recorded the time consumed for these two requests

I received a complete response both times

But

When I made a direct request, I  received responses soon.  About 1 second
|EVENT|TIME|
|---|---|
|Prepare|2.12ms|
|Socket Initialization|1.45ms|
|DNS Lookup|1.77ms|
|TCP Handshake|1.21ms|
|SSL Handshake|3.94ms|
|  **Waiting (TTFB)**  |1112.22ms| 
|  **Downloading**  |11683.53 ms| 
|  Processing  |0.21 ms| 
|  Total  |12806.44 ms| 

When requesting through Traefik，I waited for a long time to receive the first response .About 10 second

TTFB has spent too much time.It seems that Traefik has buffered the response

I hope to receive the first response soon ,Just like directly request
|EVENT|TIME|
|---|---|
|Prepare|1.06ms|
|Socket Initialization|0.80ms|
|DNS Lookup|Cache|
|TCP Handshake|0.74ms|
|  **Waiting (TTFB)**  |10557.09ms| 
|  **Downloading**  |2865.59 ms| 
|  Processing  |0.22 ms| 
|  Total  | 13425.50 ms| 

### What version of Traefik are you using?

I conducted the above test using two versions separately    v3.2.2 and  v2.10.5

### What is your environment & configuration?

I used almost the simplest configuration without using middleware

``` yaml
version: "3"

services:
  traefik:
    image: traefik:v3.2.2
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      - "8080:8080"
      - "81:81"
    volumes:
      - ./:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: compose_default
```

``` yaml
entryPoints:
  web:
    address: ":80"

  web-secure:
    address: ":443"

  tcp:
    address: ":81"

global:
  checkNewVersion: true
  sendAnonymousUsage: true

api:
  insecure: true
  dashboard: true


log:
  level: INFO

providers:  
  file:
    watch: true
    directory: "/etc/traefik/action"
    debugLogGeneratedTemplate: true
```

``` yml
http:
  routers:
    llmproxy-root:
      entryPoints:
        - web
      rule: "PathPrefix(`/`)"
      service: myservice

  services:
    myservice:
      loadBalancer:
        servers:
          - url: "https://chatgpt.mydomain.com"
```
