### ISSUE TITLE
When configuring multiple domains and SSL certificates with HTTP3 enabled, HTTP3 does not work for all domains.

### ISSUE THREAD

**Issue by kk-kwok** [traefik/traefik#11358]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

When Traefik is deployed in Kubernetes, with the `websecure` entrypoint having HTTP3 enabled, and multiple IngressRoute configurations for different primary domains, using Kubernetes secrets for TLS, only one domain's SSL certificate has HTTP3 working, while the others do not.

Using the example configuration below, accessing `a.foo.com` and `b.foo.com` has HTTP3 working correctly, ![Image](https://github.com/user-attachments/assets/e59aaba4-d9ea-46fd-b614-d4c08d13579c)

but accessing `c.bar.com` and `d.fb.com` only has HTTP2 without HTTP3.
![Image](https://github.com/user-attachments/assets/bd2bec2f-4570-4e7b-95d0-a9c3d535d168)

### What did you see instead?

When configuring multiple domains and SSL certificates with HTTP3 enabled, HTTP3 needs to work for all domains.

### What version of Traefik are you using?

v3.2.3

### What is your environment & configuration?

# traefik.yaml

```yaml
entryPoints:
  web:
    address: :80
    transport:
      respondingTimeouts:
        idleTimeout: 180
  websecure:
    address: :443
    http:
      tls: {}
    http3: {}
    transport:
      respondingTimeouts:
        idleTimeout: 180
```

# TLSOption

```yaml
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: my-tlsoption
spec:
  minVersion: VersionTLS12
```

# IngressRoute

```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: a-tls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`a.foo.com`)
      kind: Rule
      services:
        - name: a-service
          port: 80
          passHostHeader: true
  tls:
    options:
      name: my-tlsoption
    secretName: foo.com

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: b-tls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`b.foo.com`)
      kind: Rule
      services:
        - name: b-service
          port: 80
          passHostHeader: true
  tls:
    options:
      name: my-tlsoption
    secretName: foo.com

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: c-tls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`c.bar.com`)
      kind: Rule
      services:
        - name: c-service
          port: 80
          passHostHeader: true
  tls:
    options:
      name: my-tlsoption
    secretName: bar.com

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: d-tls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`d.fb.com`)
      kind: Rule
      services:
        - name: d-service
          port: 80
          passHostHeader: true
  tls:
    options:
      name: my-tlsoption
    secretName: fb.com
```
