### ISSUE TITLE
redirectRegex doesn't seem to match on fully capital paths.

### ISSUE THREAD

**Issue by Newman-Hui** [traefik/traefik#11369]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have a vanilla k8s ingress, using annotations, I specify a middleware that should redirect any request to `/license` path (non-case-sensitive). ie. /license, /LICENSE, /liCEnsE, should all redirect to the base url. 

### What did you see instead?

All scenarios except for fully capital case paths, will redirect to the base path. I've been scratching my head as to why this could be, and I really can't figure it out at all. 

### What version of Traefik are you using?

traefik v3.1.2

### What is your environment & configuration?

```yaml
---
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: harbor-license-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: domain.com
    http:
      paths:
      - backend:
          service:
            name: harbor-core
            port:
              number: 80
        path: /api/
        pathType: Prefix
      - backend:
          service:
            name: harbor-core
            port:
              number: 80
        path: /service/
        pathType: Prefix
      - backend:
          service:
            name: harbor-core
            port:
              number: 80
        path: /v2/
        pathType: Prefix
      - backend:
          service:
            name: harbor-core
            port:
              number: 80
        path: /c/
        pathType: Prefix
      - backend:
          service:
            name: harbor-portal
            port:
              number: 80
        path: /
        pathType: Prefix
---
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: license-redirect
  namespace: harbor
spec:
  redirectRegex:
    regex: ^(.*)/(?i)license
    replacement: ${1}
```

Add more configuration information here.
