### ISSUE TITLE
Large temporary multibuf files not getting cleaned up

### ISSUE THREAD

**Issue by pedropombeiro** [traefik/traefik#11372]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

In running Traefik 3.2.3 normally over the course of weeks, I expected the disk usage to remain normal.

### What did you see instead?

Instead, Traefik filled up the partition where my Docker overlay volumes are located. Running `ncdu` shows that the cultprit is a folder from traefik:

<img width="859" alt="Image" src="https://github.com/user-attachments/assets/9a2e9843-62db-4707-a2d1-9911c86e5753" />

```shell
$ docker inspect $(docker ps -qa) |  jq -r 'map([.Name, .GraphDriver.Data.MergedDir]) | .[] | "\(.[0])\t\(.[1])"' | rg 1a855c8cd8cfd67f638560f6dd870a396203193004cf6c5bb40acd62d3091285
/traefik	/share/CACHEDEV2_DATA/ContainerData/container-station-data/lib/docker/overlay2/1a855c8cd8cfd67f638560f6dd870a396203193004cf6c5bb40acd62d3091285/merged
```

<img width="912" alt="Image" src="https://github.com/user-attachments/assets/a4a8bfc9-8c08-4f17-ae09-e9e8495bd205" />

This seems to be the same issue already present in v1 with https://github.com/traefik/traefik/issues/5143

### What version of Traefik are you using?

Version:      3.2.3
Codename:     munster
Go version:   go1.23.4
Built:        2024-12-16T10:31:50Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
  traefik:
    image: traefik
    extends:
      file: ../common-services.yml
      service: baseapp_in_user_bridge
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - net_frontend
      - net_docker-socket-proxy
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp" # Used for HTTP/3
      - "10443:10443/tcp" # Client-cert protected port
      - "10443:10443/udp" # Client-cert protected port (used for HTTP/3)
      - "10444:10444/tcp" # HA unprotected port for iOS clients
      - "10444:10444/udp" # HA unprotected port for iOS clients (used for HTTP/3)
    extra_hosts:
      - nas:192.168.96.10
      - host.docker.internal:192.168.96.10
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./rules/:/rules
      - ../../config/traefik/client-certs/:/etc/traefik/client-certs/:ro
      - ../../data/letsencrypt/etc:/etc/letsencrypt/:ro
      - ../../data/traefik/plugins/:/plugins-local/
      - ../../log/traefik/:/var/log/traefik/
    restart: always
    depends_on:
      docker-socket-proxy:
        condition: service_started
    mem_limit: 1G
    labels:
      com.centurylinklabs.watchtower.monitor-only: true

      traefik.enable: true
      traefik.docker.network: traefik_net_frontend
      traefik.http.middlewares.home-ipallowlist.ipallowlist.sourcerange: "127.0.0.1/32, 172.16.0.0/12, 192.168.96.27, 192.168.4.0/24, 192.168.96.31"

      traefik.http.routers.dashboard.rule: Host(`traefik.pombei.ro`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.dashboard.entrypoints: websecure
      traefik.http.routers.dashboard.middlewares: home-ipallowlist,rate-limit@file
      traefik.http.routers.dashboard.tls: true
```

Add more configuration information here.

**Comment by nmengin** [comment]
Hey @pedropombeiro,

Thanks for reaching out.

Could you provide a full configuration?
If any community member can help us find verified steps to reproduce and fix the issue if possible, we would love the help.

**Comment by pedropombeiro** [comment]
The volume is again getting full (moved from 40% to 74% full in a matter of 5 days):

<img width="1278" alt="Image" src="https://github.com/user-attachments/assets/a40d0b60-d793-406a-ac68-f3a8de40d858" />

**Comment by creyD** [comment]
Same happens for 2 servers of mine with the same config. Can post it, if it helps?

**Comment by marvin-kolja** [comment]
@nmengin

I did some testing and could reproduce the issue by cancelling the request during response handling (buffering):

### Steps to Reproduce

1. Use a very simple `traefik/whoami` setup:

<details>
<summary>docker-compose.yaml</summary>

```yml
services:
  reverse-proxy:
    image: traefik:v3.6.10
    command: --api.insecure=true --providers.docker --entryPoints.web.address=:81 --configFile=/config.toml
    ports:
      - "81:81"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /path/config.toml:/config.toml

  backend:
    image: traefik/whoami
    labels:
      - traefik.http.routers.backend.rule=Host(`whoami.docker.localhost`)
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.services.backend.loadbalancer.server.port=80
      - traefik.http.routers.backend.middlewares=limit@docker
      - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=10000000
```

</details>

<details>
<summary>config.toml</summary>

```toml
[providers.docker]
[log]
level = "debug"

[entryPoints]
[entryPoints.web]
address = ":81"
```

</details>

2. Request a large file: `curl http://whoami.docker.localhost:81/data?size=2&unit=GB > output.txt`
3. Cancel the request while [`oxy`](https://github.com/vulcand/oxy/blob/master/buffer/buffer.go) - more specifically [`multibuff`](https://github.com/mailgun/multibuf/tree/master) - writes the response to disk, before it starts to return data to the client (I simply watched the `/tmp` dir of the container and waited for the right moment).

### Observed Behaviour

- Cancelling the request, while it is being written to disk, will stop that writing process immediately, but does not remove the file.

---

This definetly seems like a bug in the [`oxy`](https://github.com/vulcand/oxy/blob/master/buffer/buffer.go) or [`multibuff`](https://github.com/mailgun/multibuf/tree/master)  code.

### Couple of Notes

- I'm not sure if a similar behaviour could be observed during request handling (haven't found a way to test that well yet).
- Related to: https://github.com/traefik/traefik/issues/9218 (closed due to age)
- I'm not super familiar with Go and haven't got the time to look at the above mentioned libs to report or fix the issue. _I really hope someone @ traefik will though ❤️_
