### ISSUE TITLE
Support HostRegExp for TLSOptions selection

### ISSUE THREAD

**Issue by smerschjohann** [traefik/traefik#11375]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

## current status

Currently the selection of TLSOptions is only possible using Host() matchers, everything else is ignored.

Currently this configuration:
```
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: myingressroute
spec:
  routes:
  - match: HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.domain.tld`)
    kind: Rule
    priority: 10
    services:
    - name: backend
      port: 8080
  tls:
    options:
      name: withoutcerts
      namespace: default
```

leads to the warning: 
```
2024-12-29T08:19:29Z WRN No domain found in rule HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.domain.tld`), the TLS options applied for this router will depend on the SNI of each request entryPointName=web routerName=default-myingressroute-45a016b898ac859fd751@kubernetescrd
```

While the warning is basically telling the truth, the `HostRegexp` matcher could work for this as well.

With this limitation it is not possible to set a different TLSOption for wildcard routes. In my use case, I want to allow this IngressRoute access without client certificates, while my default TLSOptions require it. In the current state, this is not configurable at all. I could only change the default to optional client certificates, make sure that all non wildcard routes have a non default route and in cases I need client authentication in wildcard routes handle it via middleware. Nonetheless, this approach would have a lot of limitations.

### responsible code
The [ParseDomain function](https://github.com/traefik/traefik/blob/aa8eb1af6eb5457516169315676ec22f968e727d/pkg/server/router/tcp/manager.go#L143) only checks for Host matchers but not HostRegexp matchers and a hardcoded [HostSNI matcher](https://github.com/traefik/traefik/blob/master/pkg/server/router/tcp/router.go#L294) in the HTTPSForwarder logic. 

##  proposal
Instead of only supporting Host matchers for the TLSOptions, I would like to see HostRegexp matchers as well. This will allow use cases that are currently only possible with a lot of workarounds, if possible at all.

From a implementation and functional perspective, I don't see a reason why this shouldn't work. The whole domain is sent using TLS SNI and regex rule should work just fine. As there is already a `HostSNIRegexp` the implementation and all information is present in the code places, I think an extension is possible without too much effort.
