### ISSUE TITLE
every dynamic configuration, does not support log configuration

### ISSUE THREAD

**Issue by ccpwcn** [traefik/traefik#11379]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I Have a traefik instance, I have three backend serivces(like java based springboot, python act), so, I create a `traefik.yml` that's a static config, It's used the providers only one, and it's type is file, and it watch the directory look like `/my/traefik/conf`, and I configured the log option, set the log.filePath `logs/access.log`.
Then, I create three yml files for my backend services, now all logs are written in one file, when I watch the logs for every service, they are mixed together, difficult to distinguish, very inconvenient, which makes me very painful, I hope that each background service has its own log, so that when the corresponding background service of my application software fails, I can greatly narrow the scope of log search and investigation.

I want to written a plugin for logging, but I used Windows 10 computer, I can't build it (the command `go build -buildmode=plugin -o my-traefik-logging-plugin.dll main.go` does not support for windows os, This is Golang's limitation.).

finally, I cry while coding...

一个Traefik实例，拥有一个静态配置 traefik.yml，有多个后台服务，那么我创建了多个动态配置，当我需要日志的时候，目前日志是全局的，无法为各动态配置分别创建一个日志，所有后台的日志混在一起，要找到我想要的内容，非常不方便。

### What did you see instead?

none

### What version of Traefik are you using?

❯ .\traefik.exe version
Version:      3.2.3
Codename:     munster
Go version:   go1.23.4
Built:        2024-12-16T10:31:57Z
OS/Arch:      windows/amd64

### What is your environment & configuration?

traefik.yml static config
```yaml
# traefik.yaml static config
# Entrypoints have to be defined as static configuration in traefik.yml
entryPoints:
  web:
    address: ":9999"
    asDefault: true
    http:
      encodeQuerySemicolons: true
  websecure:
    address: ":9443"
  my-tcp-entrypoint-1521:
    address: ":1521"

log:
  level: INFO
  filePath: "logs/access.log"

providers:
  file:
    directory: conf
    watch: true
```

one website(backend) service config
```yaml
# Dynamic configuration
http:
  routers:
    to-cz-service:
      rule: PathPrefix(`/cz-api/`)
      service: cz-api

  services:
    cz-api:
      loadBalancer:
        servers:
        - url: http://localhost:10087/
```

another website(backend) service config
```yaml
# Dynamic configuration
http:
  routers:
    to-cs-service:
      rule: PathPrefix(`/cs-api/`)
      service: cs-api

  services:
    cs-api:
      loadBalancer:
        servers:
        - url: http://localhost:10088/
```

other configuration look like them, do not paste.
