### ISSUE TITLE
BackendTLSPolicy expects `targetRefs.group` to be `core`

### ISSUE THREAD

**Issue by ansarhun** [traefik/traefik#11384]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Using Gateway API configuring an `HTTPRoute` with a `BackendTLSPolicy`
Using the format from the official guide: https://gateway-api.sigs.k8s.io/guides/tls/#upstream-tls

e.g.:
```
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: tls-upstream-dev
spec:
  targetRefs:
    - kind: Service
      name: dev
      group: ""
  validation:
    wellKnownCACertificates: "System"
    hostname: dev.example.com
```

### What did you see instead?

When using the `group: ""` it will not take effect

### What version of Traefik are you using?

```
Version:      3.2.2
Codename:     munster
Go version:   go1.23.3
Built:        2024-12-10T14:53:02Z
OS/Arch:      linux/arm64
```

### What is your environment & configuration?

```yaml
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: unifi-gw
  namespace: unifi
spec:
  hostnames:
    - unifi-gw.example.tld
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: network
      sectionName: websecure
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: unifi-controller
          namespace: unifi
          port: 8443
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: unifi-gw
  namespace: unifi
spec:
  targetRefs:
    - kind: Service
      group: ""
      name: unifi-controller
  validation:
    wellKnownCACertificates: "System"
    hostname: unifi
```

### If applicable, please paste the log output in DEBUG level

Checking the code: https://github.com/traefik/traefik/blob/master/pkg/provider/kubernetes/gateway/client.go#L760
It seems it will enforce the group to be "core"
When checking the HTTPRoute it will treat the empty content as an implicit "core" group: https://github.com/traefik/traefik/blob/master/pkg/provider/kubernetes/gateway/httproute.go#L217
