### ISSUE TITLE
AWS Route53 DNS Challenge not possible with multiple hosted zones

### ISSUE THREAD

**Issue by life5ign** [traefik/traefik#11395]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

# summary & error
I'm running in Docker Swarm. Currently, if I do not specify `AWS_HOSTED_ZONE_ID` in the environment, I get the error

> acme: error presenting token: route53: failed to determine hosted zone ID

LEGO has the permission to list hosted zones by name, why can't it determine the hosted zone IDs based on my domains, like I described here? [Route53 dnsChallenge with multiple domains - #5 by waffleProOps](https://community.traefik.io/t/route53-dnschallenge-with-multiple-domains/1744/5)

Specifying the hosted zone ID in the environment applies to all certresolvers declared in traefik (we can't do one per hosted zone, like cert-manager allows for its issuers: [Failed to determine Route 53 hosted zone ID: SignatureDoesNotMatch · Issue #668 · cert-manager/cert-manager · GitHub](https://github.com/cert-manager/cert-manager/issues/668#issuecomment-419367887) so I can't use multiple domains.

# use case
I get TLS certs for my services with ACME with both LetsEncrypt for my public services, and my own internal step-ca ACME server for internal services.

I must use DNS01 challenge, since HTTP01 only works on port 80, which matters because... Due to the inability to configure on instance of traefik to serve some services on an internal IP, and some on a public IP ( [Handling internal and external apps with one instance of Traefik - #10 by waffleProOps](https://community.traefik.io/t/handling-internal-and-external-apps-with-one-instance-of-traefik/16374/10) ), I must therefore use non-standard HTTP ports (e.g. 8080) for my internal services, and rely on a simple firewall to keep the public internet out.

So I must use DNS01, which won't work for my public and internal hosted zone.

### What did you see instead?

> acme: error presenting token: route53: failed to determine hosted zone ID

### What version of Traefik are you using?

v3.2.3: Pulling from library/traefik
Digest: sha256:efb87236c8c92599bcd3a67a7a8a55e0f255665f4719722bf398935aa9b92270
Status: Downloaded newer image for traefik:v3.2.3
Version:      3.2.3
Codename:     munster
Go version:   go1.23.4
Built:        2024-12-16T10:31:50Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
services:
  nginx:
    image: nginx
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - 'traefik.enable=true'
        # publish internally within VPC
        - 'traefik.http.routers.nginx-secure-router.entrypoints=web-internal-secure'
        # we need to create a route53 entry for this host so an http01 challenge will succeed
        - 'traefik.http.routers.nginx-secure-router.rule=Host(`nginx-step-ca-app-monitoring.internal`)'
        # enable TLS
        - 'traefik.http.routers.nginx-secure-router.tls=true'
        # use internal step-ca ACME server
        - 'traefik.http.routers.nginx-secure-router.tls.certresolver=stepca'
        # backend port to nginx
        - 'traefik.http.services.nginx.loadbalancer.server.port=80'

  traefik:
    image: traefik:v3.2.3
    command:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      # new in v3: separate swarm provider
      - "--providers.swarm=true"
      # the docs' endpoint of --providers.swarm.endpoint=tcp://127.0.0.1:2377 does NOT work
      # see https://community.traefik.io/t/solved-traefik-3-not-working-with-providers-swarm-endpoint-tcp-127-0-0-1-2377/22593/6?u=waffleproops
      # see https://doc.traefik.io/traefik/v3.2/reference/install-configuration/providers/swarm/
      # you need to mount the socket if you will use the socket endpoint
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      # entrypoints
      - "--entrypoints.metrics.address=:8082"
      - "--entrypoints.web-internal.address=:9080"
      - "--entrypoints.web-internal-secure.address=:9443"
      - "--entrypoints.web-internal.http.redirections.entrypoint.to=web-internal-secure"
      - "--api=true"
      - "--api.dashboard=true"
      - "--metrics=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addentrypointslabels=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addRoutersLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--metrics.prometheus.entryPoint=metrics"
      # cert resolver for internal step-ca acme server in VPC
      # ! HTTP01 challenges can ONLY be done on port 80: https://letsencrypt.org/docs/challenge-types/ so the following would not work:
      #- "--certificatesresolvers.stepca.acme.httpchallenge.entrypoint=web-internal"
      # ! we will have to use DNS01 to the private route53 hosted zone
      - "--certificatesresolvers.stepca.acme.dnschallenge.provider=route53"
      # # * NOTE: in k8s with cert-manager, you can specify hosted zone id per issuer (like a certresolver): https://github.com/cert-manager/cert-manager/issues/668#issuecomment-419367887
      # I was getting the error
      # propagation: time limit exceeded: last error: authoritative nameservers: NS ns-512.awsdns-00.net.:53 returned REFUSED for _acme-challenge.nginx-step-ca-app-monitoring.internal
      # and the command
      # nslookup traefik-step-ca-app-monitoring.internal ns-1024.awsdns-00.org
      # returned REFUSED both in the container AND on the host
      # try the VPC DNS server
      #- "--certificatesresolvers.stepca.acme.dnschallenge.resolvers=172.31.0.2"
      #- "--certificatesresolvers.stepca.acme.dnschallenge.delaybeforecheck=2s"
      # was getting endless waiting for dns propagation messages in traefik logs
      # this solved the issue; see https://doc.traefik.io/traefik/https/acme/#dnschallenge
      - "--certificatesresolvers.stepca.acme.dnschallenge.disablepropagationcheck=true"
      # specify our internal ACME server:
      - "--certificatesresolvers.stepca.acme.caserver=https://step-ca.app-internal-services.internal:9000/acme/acme/directory"
      - "--certificatesresolvers.stepca.acme.email=ops@theapiguys.com"
      - "--certificatesresolvers.stepca.acme.storage=/etc/traefik/acme/acme.json"
    environment:
      # give traefik the root ca crt for step-ca, to bootstrap trust to the acme server
      # this is the path to a secret we mounted
      # see https://smallstep.com/docs/tutorials/acme-protocol-acme-clients/#traefik
      LEGO_CA_CERTIFICATES: /run/secrets/acme_root_ca_crt
      # to deal with error https://community.traefik.io/t/invalid-configuration-missing-region/23421
      AWS_REGION: us-west-2
      # trying to resolve traefik's inability to get an IMDS IAM token from
      # within the container, even though it works on the host
      # and the metadata enpoint can be reached from within the conainter;
      # solution: we had to increase the hop limit for IMDSv2 in the instance metadata configuration
      # see https://stackoverflow.com/questions/71884350/using-imds-v2-with-token-inside-docker-on-ec2-or-ecs
      # and the referenced docs: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html

      # still have error
      # acme: error presenting token: route53: failed to determine hosted zone ID: zone internal. not found for domain _acme-challenge.nginx-step-ca.app-monitoring.internal.
      # try setting hosted zone ID in env
      # internal hosted zone (internal):
      # ! specifying the zone id will NOT work where we have one instance of traefik serving multiple hosted zones
      # ! because traefik will receive the same zone id for all of its
      # ! certresolvers, even if we have separate certresolvers for internal and public zones
      # * I do not believe this has a solution: https://community.traefik.io/t/route53-dnschallenge-with-multiple-domains/1744
      AWS_HOSTED_ZONE_ID: 123456

      # * try using the aws config file as a supposed workaround: https://www.reddit.com/r/Traefik/comments/rrifbv/multiple_wildcard_domains_and_route53_or_suggest/
      # ! this did not work
      # I was going to try to have the config file tell us to assume the iam role, but
      # I can't find out how to specify the path to the config file; only a default ~/.aws/config is mentioned, the load config
      # variable is presumed to be any string such that when set, the config file is processed: https://go-acme.github.io/lego/dns/route53/#description
      #AWS_SDK_LOAD_CONFIG: true
      # revert to using a user's IAM keys to assume a role
      #AWS_SHARED_CREDENTIALS_FILE: /run/secrets/aws_credentials
      #AWS_ASSUME_ROLE_ARN: arn:aws:iam::614746748396:role/app-monitoring-role
    ports:
      # metrics
      - '0.0.0.0:8082:8082'
      # web-internal entrypoint, for internal http traffic within VPC
      - '0.0.0.0:9080:9080'
      # web-internal-secure entrypoint, for internal https traffic within VPC
      # due to the implementation of the swarm routing mesh, docker ignores IPs in published ports
      # when in swarm mode, so there is no point in only publishing on the instance's private IP
      # to try to restrict ingress to traffic originating within the VPC
      # we need to rely on firewalls instead, which works since these are non-standard ports
      #- '172.31.40.214:9443:9443'
      - '0.0.0.0:9443:9443'
    volumes:
      # this is necessary for swarm provider; see CLI args static provider config for explanation
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # persist TLS certs
      - traefik_data:/etc/traefik/acme
    secrets:
      - acme_root_ca_crt
      #- aws_config
      #- aws_credentials
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        # =======================================================================================================================
        # traefik dashboard
        # =======================================================================================================================
        # publish internally
        - 'traefik.enable=true'
        - 'traefik.http.routers.traefik-secure-router.rule=Host(`traefik-step-ca-app-monitoring.internal`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))'
        - 'traefik.http.routers.traefik-secure-router.service=api@internal'
        - 'traefik.http.routers.traefik-secure-router.entrypoints=web-internal-secure'
        - 'traefik.http.routers.traefik-secure-router.tls=true' # Enable TLS for the router
        - 'traefik.http.routers.traefik-secure-router.tls.certresolver=stepca'

        # =======================================================================================================================
        # Dummy service for Swarm port detection. The port can be any valid integer value.
        # this resolves the error: "nccs_production_stack_traefik.1.wajfzxn2wvq5@ip-172-31-40-214    | time="2024-11-01T22:26:54Z" level=error msg="service \"nccs-production-stack-traefik\" error: port is missing" providerName=docker container=nccs-production-stack-traefik-wajfzxn2wvq54843lkoc95kmj
        # =======================================================================================================================
        - 'traefik.http.services.dummy-svc.loadbalancer.server.port=9999' # this is essential

# step-ca root CA cert, which traefik needs to trust for ACME to work
secrets:
  acme_root_ca_crt:
    file: ./.secrets/step-ca-root-ca.crt
  #aws_config:
  #  file: ./.secrets/aws_config.ini
  #aws_credentials:
  #  file: ./.secrets/aws_credentials.ini

volumes:
  traefik_data: # Persistent storage for Traefik certificates

```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

>ERR github.com/traefik/traefik/v3/pkg/provider/acme/provider.go:457 > Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [traefik-step-ca-app-monitoring.internal]: error: one or more domains had a problem:\n[traefik-step-ca-app-monitoring.internal] [traefik-step-ca-app-monitoring.internal] acme: error presenting token: route53: failed to determine hosted zone ID: zone internal. not found for domain _acme-challenge.traefik-step-ca-app-monitoring.internal.\n" ACME CA=https://step-ca.app-internal-services.internal:9000/acme/acme/directory acmeCA=https://step-ca.app-internal-services.internal:9000/acme/acme/directory domains=["traefik-step-ca-app-monitoring.internal"] providerName=stepca.acme routerName=traefik-secure-router@swarm rule="Host(`traefik-step-ca-app-monitoring.internal`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
