### ISSUE TITLE
`sniStrict` doesn't seem to work properly with `HostRegexp`

### ISSUE THREAD

**Issue by FireDrunk** [traefik/traefik#11406]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I enabled `sniStrict`.

When I enable `sniStrict`, https://host.example.com works (404) but https://teleport.host.example.com and https://*.teleport.host.example.com **both** stop working. When I delete the HostRegexp rule, https://teleport.host.example.com starts working.

It looks like the HostRegexp function does a 'strict' validation if the given url is an exact match in the certificate, not a wildcard match. 

Also, there might be some conflict between the HostRegexp function and the sniStrict function.
It looks like the sniStrict protection kicks in after validationg just 1 rule, and not **all** rules.

### What did you see instead?

TLS errors stating the server has no certificate.

### What version of Traefik are you using?

3.2.2

### What is your environment & configuration?

Helm `values.yaml`:

```yaml
traefik:
  deployment:
    kind: DaemonSet

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1

  providers:
    kubernetesCRD:
      allowEmptyServices: false

    kubernetesGateway:
      enabled: false

    kubernetesIngress:
      enabled: false

  logs:
    general:
      level: WARN
    access:
      enabled: true

  ingressRoute:
    dashboard:
      enabled: false

  additionalArguments:
    - "--api.insecure=true"

  service:
    enabled: true
    single: true
    type: LoadBalancer
    spec:
      loadBalancerIP: "<internal-ip>"

  tlsStore:
    default:
      defaultCertificate:
        secretName: tls-wildcard-cert

  ports:
    traefik:
      expose:
        default: true

    websecure:
      expose:
        default: true
      hostPort: 443
```

IngressRoute:
```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: teleport-ingress
  namespace: teleport
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: HostRegexp(`^.+\.teleport\.host\.example\.com`)
    services:
    - name: teleport
      port: tls
      scheme: https
      serversTransport: teleport
  - kind: Rule
    match: Host(`teleport.host.example.com`)
    services:
    - name: teleport
      port: tls
      scheme: https
      serversTransport: teleport
  tls:
    options:
      name: strict-sni
```
`strict-sni` TLSOption:

```yaml
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: strict-sni
spec:
  sniStrict: true
```

My certificate from cert-manager:

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: thuis-wildcard-certificate
  namespace: traefik
spec:
  dnsNames:
  - host.example.com
  - '*.host.example.com'
  - '*.teleport.host.example.com'
  duration: 2160h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h0m0s
  secretName: tls-wildcard-cert
  usages:
  - server auth
  - client auth
status:
  conditions:
  - lastTransitionTime: "2024-12-24T07:45:33Z"
    message: Certificate is up to date and has not expired
    observedGeneration: 5
    reason: Ready
    status: "True"
    type: Ready
  notAfter: "2025-03-24T06:47:01Z"
  notBefore: "2024-12-24T06:47:02Z"
  renewalTime: "2025-03-09T06:47:01Z"
  revision: 3
```

### If applicable, please paste the log output in DEBUG level

2025-01-06T21:27:48Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:216 > TLS: strict SNI enabled - No certificate found for domain: "teleport.host.example.com", closing connection
2025-01-06T21:27:48Z DBG log/log.go:245 > http: TLS handshake error from 10.0.2.74:52655: tls: no certificates configured
2025-01-06T21:27:49Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: ""
2025-01-06T21:27:50Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: ""
2025-01-06T21:27:51Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: ""
2025-01-06T21:27:52Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: ""
