### ISSUE TITLE
traefik not able to find keys in etcd KV

### ISSUE THREAD

**Issue by mfreeman451** [traefik/traefik#11416]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

If I setup a watcher:

```shell
ETCDCTL_API=3 etcdctl --endpoints=https://10.0.1.140:2379,https://10.0.1.141:2379,https://10.0.1.142:2379   --cacert=/etc/etcd/ssl/ca.pem   --cert=/etc/etcd/ssl/etcd01.pem   --key=/etc/etcd/ssl/etcd01-key.pem   watch /traefik/ --prefix
```

I can see the data getting inserted into the KV:

```
PUT
/traefik/tcp/routers/k3s-api-router/entryPoints/0
k3s-api
PUT
/traefik/tcp/routers/k3s-api-router/service
k3s-api-svc
PUT
/traefik/tcp/routers/k3s-api-router/rule
HostSNI(`*`)
PUT
/traefik/tcp/routers/k3s-api-router/tls/passthrough
true
PUT
/traefik/tcp/services/k3s-api-svc/loadBalancer/servers/0/address
10.0.1.110:6443
PUT
/traefik/tcp/services/k3s-api-svc/loadBalancer/servers/1/address
10.0.1.120:6443
PUT
/traefik/tcp/services/k3s-api-svc/loadBalancer/servers/2/address
10.0.1.130:6443
```

### What did you see instead?

```shell
Jan 07 10:35:18 traefik traefik[1659]: 2025-01-07T10:35:18-06:00 DBG Users/v161400/src/traefik/pkg/provider/kv/kv.go:97 > RootKey: traefik
Jan 07 10:35:18 traefik traefik[1659]: 2025-01-07T10:35:18-06:00 DBG Users/v161400/src/traefik/pkg/provider/kv/storewrapper.go:78 > List: traefik
Jan 07 10:35:18 traefik traefik[1659]: 2025-01-07T10:35:18-06:00 ERR Users/v161400/src/traefik/pkg/provider/kv/kv.go:144 > Provider error, retrying in 9.019831478s error="key not found in store" providerName=etcd
```

### What version of Traefik are you using?

root@traefik:~# /bin/traefik version
Version:      6d3a685d5a09575f1b29d95779eb1c6578e9dab1
Codename:     cheddar
Go version:   go1.23.2
Built:        2025-01-07_04:31:31PM
OS/Arch:      linux/amd64
root@traefik:~#

### What is your environment & configuration?

```yaml
# /etc/traefik/traefik.yaml

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

# Entry points
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  k3s-api:
    address: ":6443"

providers:
  etcd:
    endpoints:
      - "10.0.1.140:2379"
      - "10.0.1.141:2379"
      - "10.0.1.142:2379"
    rootKey: "traefik"
    tls:
      ca: "/etc/traefik/certs/ca.pem"
      cert: "/etc/traefik/certs/traefik-client.pem"
      key: "/etc/traefik/certs/traefik-client-key.pem"

api:
  dashboard: true
  insecure: true

metrics:
  prometheus: {}
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

I added a little debugging to my code:

```go

func (p *Provider) watchKv(ctx context.Context, configurationChan chan<- dynamic.Message) error {
	operation := func() error {
		log.Printf("RootKey: %s", p.RootKey)
		list, err := p.kvClient.List(ctx, p.RootKey, nil)
		if err != nil {
			return err
		}
		// print the list
		for _, item := range list {
			log.Printf("Key: %s, Value: %s", item.Key, string(item.Value))
		}
		events, err := p.kvClient.WatchTree(ctx, p.RootKey, nil)
		if err != nil {
			return fmt.Errorf("failed to watch KV: %w", err)
		}

		for {
			select {
			case <-ctx.Done():
				return nil
			case _, ok := <-events:
				if !ok {
					return errors.New("the WatchTree channel is closed")
				}

				configuration, errC := p.buildConfiguration(ctx)
				if errC != nil {
					return errC
				}

				if configuration != nil {
					configurationChan <- dynamic.Message{
						ProviderName:  p.name,
						Configuration: configuration,
					}
				}
			}
		}
	}
```
