### ISSUE TITLE
Dashboard not accessible since last update (v3.3.0)

### ISSUE THREAD

**Issue by avidflyer17** [traefik/traefik#11415]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hello guys,

I updated to 3.3.0 but after this, dashboard is not reachable anymore.
After rolling back to 3.2.3, dashboard is working fine.

<img width="1463" alt="Image" src="https://github.com/user-attachments/assets/30a1c4ac-734c-42fe-8314-ba9eea8233fe" />

Other applications seams to work fine, except dashboard when running 3.3.0.

Regards,

### What did you see instead?

Nothing, it tries to download a file.

### What version of Traefik are you using?

Version:      3.3.0
Codename:     saintnectaire
Go version:   go1.23.4
Built:        2025-01-06T11:09:52Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

# -- (Optional) Change Log Level and Format here...
#     - loglevels [DEBUG, INFO, WARNING, ERROR, CRITICAL]
#     - format [common, json, logfmt]
log:
 level: INFO
 format: json
 filePath: /logs/traefik.log

# -- (Optional) Enable Accesslog and change Format here...
#     - format [common, json, logfmt]
accesslog:
  format: json
  filePath: /logs/access.log

# -- (Optional) Enable API and Dashboard here, don't do in production
api:
  dashboard: true
#  insecure: true
# -- Change EntryPoints here...
entryPoints:
  web:
    address: :80
    # -- (Optional) Redirect all HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    forwardedHeaders:
      trustedIPs:
        - "172.18.0.0/24"
        - "192.168.1.0/24"  # Adjust to restrict IPs if needed
    http:
      tls:
        # Generate a wildcard domain certificate
        certResolver: production
        domains:
          - main: xxxxxx.fr
            sans:
              - '*.xxxxxxx.fr'
      middlewares:
        - traefik-rate-limit@file
        - crowdsec-bouncer-traefik-plugin@file
        - securityHeaders@file
        - authelia@file
        - compress@file
    http3: {}
  # Ajout d'un point d'entree sur le port 8080
  metrics:
    address: :8080

#  mqtt:
#    address: :1883

#  mqtts:
#    address: :8883

# Ajout de la partie metrique qui concerne Prometheus
metrics:
  prometheus:
    # Nom du point d'entree defini au dessus
    entryPoint: metrics
    # On configure la latence des metriques
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    # Ajout des metriques sur les points d'entree
    addEntryPointsLabels: true
    # Ajout des services
    addServicesLabels: true
    # Ajout des routeurs
    addRoutersLabels: true

#tracing:
#  otlp:
#    http:
#      endpoint: http://localhost:4318/v1/traces

# -- Configure your CertificateResolver here...
certificatesResolvers:
  staging:
    acme:
      email: xxxxxxxx@gmail.com
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
#      -- (Optional) Remove this section, when using DNS Challenge
#      httpChallenge:
#        entryPoint: web
#       -- (Optional) Configure DNS Challenge
      dnsChallenge:
        provider: ionos
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
  production:
    acme:
      email: xxxxxx@gmail.com
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
#       -- (Optional) Remove this section, when using DNS Challenge
#       httpChallenge:
#         entryPoint: web
#       -- (Optional) Configure DNS Challenge
      dnsChallenge:
        provider: ionos
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
providers:
  providersThrottleDuration: 2s

  # File provider for connecting things that are outside of docker / defining middleware
  file:
    filename: /etc/traefik/fileConfig.yml
    watch: true

  # Docker provider for connecting all apps that are inside of the docker network
  docker:
    watch: true
    network: br-dams # Add Your Docker Network Name Here
    # Default host rule to containername.domain.example
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\"}}.xxxxxxxxx.fr`)"
    exposedByDefault: false
    endpoint: "tcp://dockersocket:2375" # Uncomment if you are using docker socket proxy

experimental:
  plugins:
    crowdsec-bouncer-traefik-plugin:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.3.5"
    geoblock:
      moduleName: "github.com/PascalMinder/geoblock"
      version: "v0.2.8"
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

N/A
