### ISSUE TITLE
Unable to access Traefik dashboard with contentTypeNosniff header enabled with Traefik v3.3.0

### ISSUE THREAD

**Issue by scoudibou** [traefik/traefik#11414]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I've updated my v2.2.3 to the latest version (v3.3) and now I can't access the Traefik dashboard.
I've done a small test with v2.2.4 and it seems it does neither work.
I've tested it with other terminal and I got the same behaviour.

Turnaround : 
If I disable the "contentTypeNosniff" header it's working.

Comments : 
I've made a rollback with v2.2.3 with the same header and it's working perfectly.

### What did you see instead?

The webpage is displaying : 
```html
<!DOCTYPE html><html><head><script>window.APIURL = "/api/"</script><title>Traefik</title><meta charset=utf-8><meta name=description content="Traefik UI"><meta name=format-detection content="telephone=no"><meta name=msapplication-tap-highlight content=no><meta name=viewport content="user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1,width=device-width"><link rel=icon type=image/png href=./app-logo-128x128.png><link rel=icon type=image/png sizes=16x16 href=./icons/favicon-16x16.png><link rel=icon type=image/png sizes=32x32 href=./icons/favicon-32x32.png><link rel=icon type=image/png sizes=96x96 href=./icons/favicon-96x96.png><link rel=icon type=image/ico href=./icons/favicon.ico><link rel=apple-touch-icon href=./icons/apple-icon-152x152.png><link rel=apple-touch-icon sizes=152x152 href=./icons/apple-icon-152x152.png><link rel=apple-touch-icon sizes=167x167 href=./icons/apple-icon-167x167.png><link rel=apple-touch-icon sizes=180x180 href=./icons/apple-icon-180x180.png>  <script type="module" crossorigin src="./assets/index-CLgUCYBL.js"></script>
  <link rel="stylesheet" crossorigin href="./assets/index-jjiyEA_O.css">
</head><body><div id=q-app></div></body></html>
```

### What version of Traefik are you using?

V3.3.0

### What is your environment & configuration?

Docker Compose extract : 
```yaml
  # Traefik dashboard 
      - traefik.http.routers.api.rule=Host(`traefik.mydomain.com`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.entrypoints=https
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.options=tls-opts@file
      - traefik.http.routers.api.tls.certresolver=letsencrypt
      - traefik.http.routers.api.tls.domains[0].main=mydomain.com
      - traefik.http.routers.api.tls.domains[0].sans=*.mydomain.com
      - traefik.http.services.api.loadbalancer.server.port=443
      - traefik.http.routers.api.middlewares=secHeaders_traefik@file,middlewares-authentik@file
```

Dynamic file extract : 
```yaml
    secHeaders_traefik:
      chain:
        middlewares:
          - secHeader_traefik
          - compress-it
          - request-limit

    request-limit:
      rateLimit:
        average: 100
        burst: 50

    compress-it:                   
      compress: {}

    secHeader_traefik:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000
        customFrameOptionsValue: "SAMEORIGIN"
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "vibrate 'self'; geolocation 'self'; midi 'self'; notifications 'self'; push 'self'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'self'; fullscreen 'self'"
        accessControlAllowMethods: ["GET, OPTIONS, PUT"]
        accessControlMaxAge: 100
        addVaryHeader: true
        sslProxyHeaders:
          X-Forwarded-Proto: "https"
        forceSTSHeader: true
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        accessControlAllowOriginList: "https://*.mydomain.com"
        customResponseHeaders:
          X-Robots-Tag: "noindex, nofollow, noarchive, nosnippet, notranslate, noimageindex"
          server: ""
        contentSecurityPolicy: "default-src 'none'; connect-src 'self'; script-src 'self'; style-src 'self'; style-src-elem 'self' 'unsafe-inline'; font-src 'self'; object-src 'none'; media-src 'self'; img-src 'self' data: https: ; frame-src 'self'; worker-src 'self'; report-uri /api/v1/csp-report; base-uri 'self'; frame-ancestors 'self'"
        framedeny: true
        sslredirect: true
        customRequestHeaders:
          X-Forwarded-Proto: "https"

    middlewares-authentik:
      forwardAuth:
        address: "http://authentik_server:9000/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-entitlements
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
```

### If applicable, please paste the log output in DEBUG level

NA
