### ISSUE TITLE
Increased memory usage in version 2.11.18

### ISSUE THREAD

**Issue by aucampia** [traefik/traefik#11423]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Upgrade from version 2.11.16 to 2.11.18. We did not expect any change in memory usage.

### What did you see instead?

It seems Træfik now uses at least 2x as much memory as before, and it may even be leaking memory.

![Image](https://github.com/user-attachments/assets/0c2a328a-d219-4a2f-9e03-7191f90c2aa8)
![Image](https://github.com/user-attachments/assets/9118c042-7778-4d8e-806d-611d23ef7bd2)

### What version of Traefik are you using?

2.11.18

### What is your environment & configuration?

N/A

**Comment by romainhealth** [comment]
Hi,

We are also experiencing this issue with the latest Traefik version 2.11.18.
We are noticing memory usage spikes, which ultimately lead to our Docker Swarm Managers being killed.

On January 8th, we updated to version 2.11.18.
![Image](https://github.com/user-attachments/assets/a6bb9917-805f-473f-b877-1a5084f006d2)

Traefik is running in our Docker Swarm environment. We have 3 managers, 2 workers, and over 20 services.

``` yaml
version: '3.3'

services:
  proxy:
    image: traefik:v2.11.16
    command: 
      - --api=true
      - --providers.docker
      - --providers.docker.swarmMode=true
      - --entryPoints.web-secure.address=:443
      - --entryPoints.web-secure.transport.respondingTimeouts.readTimeout=150
      - --entryPoints.metrics.address=:8082
      - --metrics=true
      - --metrics.prometheus=true
      - --metrics.prometheus.entryPoint=metrics
      - --ping=true
      - --entryPoints.ping.address=:8083
      - --ping.entryPoint=ping
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      sample:
      management:
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=(Host(`${url}`) && PathPrefix(`/api`)) || (Host(`${url}`) && PathPrefix(`/dashboard`))"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.tls=true"
        - "traefik.http.routers.traefik.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=sample:sample"
        - "traefik.http.routers.traefikping.rule=(Host(`${url}`) && PathPrefix(`/ping`))"
        - "traefik.http.routers.traefikping.service=ping@internal"
        - "traefik.http.routers.traefikping.tls=true"
        - "traefik.http.services.traefikping.loadbalancer.server.port=8083"
      placement:
        constraints:
          - node.role == manager
networks:
  sample:
    external: true
  management:
    external: true

volumes:
  logs:
```
