### ISSUE TITLE
clientAuth.caFiles not working

### ISSUE THREAD

**Issue by paigeadelethompson** [traefik/traefik#11424]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

this simple configuration does not work:

```
tls:
  options:
    default:
      sniStrict: true
      clientAuth:
        caFiles:
          - /certs/origin_ca_ecc_root.pem
          - /certs/origin_ca_rsa_root.pem
        clientAuthType: RequireAndVerifyClientCert
```

### What did you see instead?

A scenario where I have to use `RequireAnyClientCert` instead of the more appropriate and better suited `RequireAndVerifyClientCert`

### What version of Traefik are you using?

Traefik version 3.2.3

### What is your environment & configuration?

Microsoft Windows 95 

### If applicable, please paste the log output in DEBUG level

naturally this is all I get 

```
2025-01-09T14:59:01Z DBG log/log.go:245 > http: TLS handshake error from 108.162.245.57:28452: tls: failed to verify certificate: x509: certificate signed by unknown authority
```

startup also never says anything about loading the certificates,
