### ISSUE TITLE
Env variable in a dynamic file

### ISSUE THREAD

**Issue by BDIFluky** [traefik/traefik#11425]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Do you want to request a feature or report a bug?
Bug
What did you do?
Tried to use an environment variable inside a dynamic file
What did you expect to see?
flawless integration

```









### What did you see instead?

syntax error 
```yaml
{
  "level": "error",
  "providerName": "file",
  "error": "/dynamic/auth-mwr.yml: template: :5: unexpected \"\\\\\" in operand",
  "time": "2025-01-09T15:56:50Z",
  "message": "Error occurred during watcher callback"
}

### What version of Traefik are you using?

Version:      3.1.7
Codename:     comte
Go version:   go1.23.2
Built:        2024-10-28T10:41:06Z
OS/Arch:      linux/amd64

### What is your environment & configuration?


compose file:
```yaml
services:
  traefik:
    container_name: "$shrooTraefikName"
    image: "docker.io/traefik:v3.1"
    env_file:
      - "${shrooTraefikDir}/.traefik.env"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - TraefikNet
    volumes:
      - "${shrooCMSocket}:/var/run/docker.sock:ro"
      - "${shrooTraefikDir}/letsencrypt:/letsencrypt"
      - "${shrooTraefikDir}/traefik.yml:/etc/traefik/traefik.yml"
      - "${shrooTraefikDir}/dynamic:/dynamic"
      - "TraefikLogDir:/var/log/traefik"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  whoami:
    container_name: "whoami"
    image: "docker.io/traefik/whoami"
    networks:
      - TraefikNet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.middlewares=auth-mwr@file"

networks:
  TraefikNet:
    name: TraefikNet
    driver: bridge
    internal: false

volumes:
  TraefikLogDir:
```

traefik.yml
```yaml
################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false

################################################################
# Entrypoints configuration
################################################################
entryPoints:
  web: # entrypoint name
    address: :80 # entrypoint address
    http:
      redirections: # redirectScheme middleware
        entryPoint:
          to: "websecure" # name of entrypoint to redirect to
          scheme: "https" # scheme used after redirection
  websecure:
    address: :443
    asDefault: true # entrypoint set a s default
    http:
      tls: # tls enabled by default for the above entrypoint
        certResolver: "letsencrypt" # default certificate resolver

################################################################
# Let's Encrypt
################################################################
certificatesresolvers:
  letsencrypt: # certResolver name
    acme:
      email: "{{env \"PROVIDER_EMAIL\"}}" # email provided by an environment variable
      storage: "/letsencrypt/acme.json" # storage location for the acme.json
      preferredchain: 'ISRG Root X2'
      keytype: 'ECDSA P-384'
      dnsChallenge: # challenge type
        provider: "{{env \"PROVIDER\"}}" # provider code provided by an environment variable
        
################################################################
# Traefik logs configuration
################################################################        
accessLog:
  addInternals: true # adding logging for api and dashboard services
  filePath: "/var/log/traefik/access.log" # storage location for accessLog

log:
  level: "ERROR"
  filePath: "/var/log/traefik/traefik.log" # storage location for logs
  format: "json"

################################################################
# API, dashboard and ping configuration
################################################################
api:
  insecure: false
  dashboard: true

ping:
  entrypoint: "web"

################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false # label "traefik.enable=true" needed to expose a container
    defaultRule: "Host(`{{ .ContainerName }}.{{env \"DOMAIN_NAME\"}}`)" # default rule for exposed containers is [containername].[domainName]
    
  file:
    directory: "/dynamic" # dynamic file path
    watch: true
```

dynamic/auth-mwr.yml
```yaml
http:
    middlewares:
        auth-mwr:
            forwardAuth:
                address: "http://{{env \"shrooAuthName\"}}:9000/outpost.goauthentik.io/auth/traefik" # gets authentik server's container name from environment variables
                trustForwardHeader: true
                authResponseHeaders:
                    - X-authentik-username
                    - X-authentik-groups
                    - X-authentik-email
                    - X-authentik-name
                    - X-authentik-uid
                    - X-authentik-jwt
                    - X-authentik-meta-jwks
                    - X-authentik-meta-outpost
                    - X-authentik-meta-provider
                    - X-authentik-meta-app
                    - X-authentik-meta-version

```

### If applicable, please paste the log output in DEBUG level

If applicable, please paste the log output in DEBUG level (--log.level=DEBUG switch)
```yaml
{
  "level": "error",
  "providerName": "file",
  "error": "/dynamic/auth-mwr.yml: template: :5: unexpected \"\\\\\" in operand",
  "time": "2025-01-09T15:56:50Z",
  "message": "Error occurred during watcher callback"
}
```

I fixed the issue by removing the escape character `\` around `shrooAuthName` in the auth-mwr.yml, this should lead to syntax error on a yml file even tho it's accepted by Traefik.

**Comment by BDIFluky** [comment]
>[!NOTE]
>This part of the traefik.yml works without a problem:
```yml
providers:
  docker:
    exposedByDefault: false # label "traefik.enable=true" needed to expose a container
    defaultRule: "Host(`{{ .ContainerName }}.{{env \"DOMAIN_NAME\"}}`)" # default rule for exposed containers is [containername].[domainName]
```
