### ISSUE TITLE
Traefik v3.3 breaks Proxmox WebUI VNC

### ISSUE THREAD

**Issue by rageebm** [traefik/traefik#11421]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Placing Proxmox and Proxmox backup server behind Traefik. This should let me access the WebUI and the access the shell for the host and any guests via VNC

### What did you see instead?

Placing Proxmox and Proxmox backup server behind Traefik on the latest image (v3.3) breaks VNC and the SSH function via webui. It creates a 1006 error in Proxmox Backup server shell and timeout error for any VM shells via the Proxmox web gui.

Rolling back by using traefik:v3.2 fixes this issue. Using the latest tag breaks it once more.

### What version of Traefik are you using?

Broken:

Version:      3.3.0
Codename:     saintnectaire
Go version:   go1.23.4
Built:        2025-01-06T11:09:52Z
OS/Arch:      linux/amd64

Works:

Version:      3.2.5
Codename:     munster
Go version:   go1.23.4
Built:        2025-01-07T14:16:14Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
# global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default
# Writing Logs to a File
log:
  filePath: "/logs/traefik.log"
  level: ERROR
  maxSize: 10
  maxBackups: 3

api:
  dashboard: true
  debug: true

entryPoints:

  http:
    address: :80
    # (Optional) Redirect to HTTPS
    # ---
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443

serversTransport:
  insecureSkipVerify: true
providers:
#  docker:
#    endpoint: "unix:///var/run/docker.sock"
#    exposedByDefault: false
  docker:
    exposedByDefault: false
    endpoint: 'tcp://dockerproxy:2375'
    network: socket-proxy
  file:
    filename: /config.yml
certificatesResolvers:
  zerossl:
    acme:
      eab:
        kid:
        hmacEncoded:
      email:
      storage: /acme.json
      caServer: "https://acme.zerossl.com/v2/DV90"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

N/A
