### ISSUE TITLE
K8s Gateway API rule priority

### ISSUE THREAD

**Issue by augustozanellato** [traefik/traefik#11426]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hi,
I'm working on a system where TCP services are dynamically spawned via a controller and routed via TLS SNI using a TLSRoute like the following
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
spec:
  hostnames:
  - whoami-tcp.apps.local
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: my-gateway
    sectionName: tls
  rules:
  - backendRefs:
    - kind: Service
      name: my-backend
      namespace: my-ns
      port: 8080
```
Everything worked fine until I added a catch-all service that should handle connections to non-registered SNIs, the service has the following config
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
spec:
  hostnames:
  - "*.apps.local"
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: my-gateway
    sectionName: tls
  rules:
    - backendRefs:
        - name: catchall-svc
          kind: Service
          port: 1337
```
After adding that all the requests were routed to the catch-all service, even the ones to `whoami-tcp.apps.local`.
I looked into Traefik dashboard and figured out it was caused by the catch-all rule having higher priority over the specific SNI rule.
Would it be possible to have some way of overriding the rule priority?
Gateway API doesn't offer that possibility by itself but I guess it could be implemented using a label on the various *Route objects.
Please let me hear your thought about this, if there's enough consensus I might work myself on a PR addressing this
