### ISSUE TITLE
Fix docs and warnings about moved configuration

### ISSUE THREAD

**Issue by thomscode** [traefik/traefik#11431]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I was using the following options in my static config with Traefik 3.3.1:

```yaml
certificatesResolvers:
  letsencrypt:
    acme:
      email: ***@***
      storage: /data/acme.json
      dnsChallenge:
        provider: route53
        disablePropagationCheck: true
        delayBeforeCheck: 2s
```
I received the deprecation warning that the `disablePropagationCheck` and `delayBeforeCheck` options are deprecated and the options that replace them. Following the warning messages modified my config as follows:

```yaml
certificatesResolvers:
  letsencrypt:
    acme:
      email: ***@***
      storage: /data/acme.json
      dnsChallenge:
        provider: route53
        propagation:
          disableAllChecks: true
          delayBeforeChecks: 2s
```
Only to find out that `dnsChallenge.propagation.disableAllChecks` is not a valid option.

After reading the docs I changed my config to the following and it worked properly:

```yaml
certificatesResolvers:
  letsencrypt:
    acme:
      email: ***@***
      storage: /data/acme.json
      dnsChallenge:
        provider: route53
        propagation:
          disableChecks: true
          delayBeforeChecks: 2s
```
They key was to change `disableAllChecks` to `disableChecks`.

### What did you see instead?

My container would not start due to improper configuration.

### What version of Traefik are you using?

Traefik 3.3.1

### What is your environment & configuration?

```yaml
certificatesResolvers:
  letsencrypt:
    acme:
      email: ***@***
      storage: /data/acme.json
      dnsChallenge:
        provider: route53
        propagation:
          disableAllChecks: true
          delayBeforeChecks: 2s
```
