### ISSUE TITLE
Feature: ServersTransports k8s CRD - Root CA through config maps

### ISSUE THREAD

**Issue by zeronounours** [traefik/traefik#11441]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

# Context

As of today, when configuring SeversTransports using KubernetesCRD, it is only possible to provide root CA using Secret ressources (using `rootCAsSecrets`).

CA certificates are public ressources, hence does not need to be provided as secrets.

# Request

It would be interesting to provides them through other ressources, including config maps. For the CRD, it could use a structure similar to kubernetes volumes or to envFrom, e.g.:
```yaml
apiVersion: traefik.us/v1alpha1
kind: ServersTransport
metadata:
  name: my-server-transport
  namespace: default

spec:
  rootCAs:
    - secretRef: root-ca-as-secret
    - configMapRef: root-ca-as-cm
  serverName: server.default.svc.cluster.local
```

# Additional notes

Such solution would increase compatibility with Cert-Manager [trust-manager](https://github.com/cert-manager/trust-manager): by default it can only provides bundle through config maps. (Since recently it can create secrets too, but it comes with high security costs as it requires full read access to all secrets in a cluster)

**Comment by Nelwhix** [comment]
@nmengin I think I can work on this. One question though, what if instead of this suggested by @zeronounours 
```yaml
spec:
  rootCAs:
    - secretRef: root-ca-as-secret
    - configMapRef: root-ca-as-cm
  serverName: server.default.svc.cluster.local
```
We do something like:
```yaml
spec:
  rootCAsSecrets:
    - root-ca-as-secret
  rootCAsMaps:
    - root-ca-as-cm
  serverName: server.default.svc.cluster.local
```
That way we can still be backwards compatible and we don't duplicate logic for secrets stored in rootCAsSecrets and those stored in rootCAs
