### ISSUE TITLE
v3: providers.swarm.network not properly routing

### ISSUE THREAD

**Issue by bpinsard** [traefik/traefik#11459]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Deploying a stack with 2 networks `db_backend` and `traefik-public`, including traefik setup with `--providers.swarm.network=traefik-public` but was getting `Gateway errors` randomly for some of the containers.
Traefik logs showed that it was trying to access the container through the `db_backend` IP of the containers, the network to which traefik is not attached to. 

When I added  `--providers.docker.network=traefik-public` it seems to have solved the issue.

### What did you see instead?

ref: https://doc.traefik.io/traefik/providers/swarm/#network.

### What version of Traefik are you using?

v3.3.2

### What is your environment & configuration?

docker swarm

**Comment by nmengin** [comment]
Hey @bpinsard,

Thanks for reaching out.

Could you provide a minimal reproducible case (for Docker manifests, static and dynamic configuration to reproduce the issue)?

**Comment by bpinsard** [comment]
Thanks for the fast reply.

Here is a compose file for swarm to reproduce that (just did on my laptop, same issue as on our server)

```
networks:
  traefik-public:
    name: traefik-public
  db_backend:

services:

  whoami:
    image: traefik/whoami:latest
    networks:
      - traefik-public
      - db_backend
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)
      - traefik.http.routers.whoami.entrypoints=http
      - traefik.http.services.whoami.loadbalancer.server.port=80

  traefik:
    image: traefik:v3.3.2
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    labels:
        # Enable Traefik for this service, to make it available in the public network
        - traefik.enable=true
        # Use the custom label "traefik.constraint-label=traefik-public"
        # This public Traefik will only use services with this label
        # That way you can add other internal Traefik instances per stack if needed
        - traefik.constraint-label=traefik-public
        # Uses the environment variable DOMAIN
        - traefik.http.routers.traefik-public-http.rule=Host(`traefik.${DOMAIN?Variable not set}`)
        - traefik.http.routers.traefik-public-http.entrypoints=http
        # Use the special Traefik service api@internal with the web UI/Dashboard
        - traefik.http.routers.traefik-public-http.service=api@internal
        # Define the port inside of the Docker service to use
        - traefik.http.services.traefik-public.loadbalancer.server.port=8080
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --log.level=DEBUG
      # Add a constraint to only use services with the label "traefik.constraint-label=traefik-public"
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      # Enable Docker Swarm mode
      - --providers.swarm.network=traefik-public
      # - --providers.docker.network=traefik-public
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.swarm.exposedbydefault=false
      # Create an entrypoint "http" listening on port 80
      - --entrypoints.http.address=:80
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable the Dashboard and API
      - --api.dashboard=true
    networks:
      - traefik-public

```

then run
```
export DOMAIN=dummy.com
echo "127.0.0.1 traefik.$DOMAIN"  | sudo tee -a /etc/hosts
echo "127.0.0.1 whoami.$DOMAIN"  | sudo tee -a /etc/hosts
docker stack deploy -c docker-compose.traefik.yml tfk_bug
```

then `curl -vvv http://whoami.$DOMAIN/` should hang then timeout

the logs of traefik show that it tries to connect to that IP
```
docker service logs tfk_bug_traefik | grep whoami 
tfk_bug_traefik.1.1byq7awmc9ha@blob-XPS-9320    | 172.25.2.1 - - [20/Jan/2025:15:14:16 +0000] "GET / HTTP/1.1" 499 21 "-" "-" 1 "whoami@docker" "http://10.0.2.3:80" 6460ms
```
which is on the other network's subnet
```
docker inspect tfk_bug_db_backend   | grep IPv4Address
                "IPv4Address": "10.0.2.3/24",
                "IPv4Address": "10.0.2.4/24",
```
rather than on traefik-public one
```
docker inspect traefik-public   | grep IPv4Address
                "IPv4Address": "10.0.1.6/24",
                "IPv4Address": "10.0.1.3/24",
                "IPv4Address": "10.0.1.4/24",
```

## temporary remediation

uncommenting in the compose file above the option  
```
      - --providers.docker.network=traefik-public
```
and redeploying the stack `docker stack deploy -c docker-compose.traefik.yml tfk_bug` allows connecting as expected.
```
curl -vvv http://whoami.dummy.com/
* Host whoami.dummy.com:80 was resolved.
* IPv6: (none)
* IPv4: 127.0.0.1
*   Trying 127.0.0.1:80...
* Connected to whoami.dummy.com (127.0.0.1) port 80
> GET / HTTP/1.1
> Host: whoami.dummy.com
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 384
< Content-Type: text/plain; charset=utf-8
< Date: Mon, 20 Jan 2025 15:24:30 GMT
< 
Hostname: 8ba4c9e25791
IP: 127.0.0.1
IP: ::1
IP: 10.0.2.3
IP: 172.25.2.4
IP: 10.0.1.6
RemoteAddr: 10.0.1.7:43012
GET / HTTP/1.1
Host: whoami.dummy.com
User-Agent: curl/8.5.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 172.25.2.1
X-Forwarded-Host: whoami.dummy.com
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: e002ae3f8fb9
X-Real-Ip: 172.25.2.1

* Connection #0 to host whoami.dummy.com left intact
```

Going to the right subnet.
```
docker service logs -f tfk_bug_traefik | grep whoami 
....
tfk_bug_traefik.1.yc17ruhlwbc1@blob-XPS-9320    | 172.25.2.1 - - [20/Jan/2025:15:24:30 +0000] "GET / HTTP/1.1" 200 384 "-" "-" 2 "whoami@docker" "http://10.0.1.6:80" 0ms
```


So either my configuration is bogus and sends traefik off-track, or there is a bug in the new swarm provider that doesn't occur in with the docker provider.
Also, it sometimes happens that it picked-up the right network IP when redeploying without tearing down the stack first.

Thanks for your help.

**Comment by nmengin** [comment]
Hey @bpinsard,

Thank you for the additional information.
From what we see in your CLI argument, you start Traefik defining some options on the Docker provider (`--providers.docker`) and the Swarm provider (`--providers.swarm`).

Could you give it another try using only the Swarm provider?

To keep the repository focused, we ask that all questions be asked in the [community forum](https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there.  If not, you can ask and get help from other community members pretty quickly.

**Comment by bpinsard** [comment]
Thanks for the reply.
You are completely right, I had the `constraints` option creating the docker provider.

But I will  still follow up here as it seems to be really a bug, but cannot reopen that issue.

When I fix that constraint to `swarm` or completely remove it, so with only `swarm` as provider, it created another bug: the swarm containers configuration are not detected at all. 

Here is the compose file for that 2nd issue:
```
networks:
  traefik-public:
    name: traefik-public
  db_backend:

services:

  whoami:
    image: traefik/whoami:latest
    networks:
      - traefik-public
      - db_backend
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)
      - traefik.http.routers.whoami.entrypoints=http
      - traefik.http.services.whoami.loadbalancer.server.port=80

  traefik:
    image: traefik:v3.3.2
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    labels:
        # Enable Traefik for this service, to make it available in the public network
        - traefik.enable=true
        # Uses the environment variable DOMAIN
        - traefik.http.routers.traefik-public-http.rule=Host(`traefik.${DOMAIN?Variable not set}`)
        - traefik.http.routers.traefik-public-http.entrypoints=http
        # Use the special Traefik service api@internal with the web UI/Dashboard
        - traefik.http.routers.traefik-public-http.service=api@internal
        # Define the port inside of the Docker service to use
        - traefik.http.services.traefik-public.loadbalancer.server.port=8080
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --log.level=DEBUG
      # Enable Docker Swarm mode
      - --providers.swarm.network=traefik-public
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.swarm.exposedbydefault=false
      # Create an entrypoint "http" listening on port 80
      - --entrypoints.http.address=:80
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable the Dashboard and API
      - --api.dashboard=true
    networks:
      - traefik-public

``` 


the logs show that it filters out the swarm container:
```
tfk_bug_traefik.1.sapsmijmau8u@blob-XPS-9320    | 2025-01-23T14:55:52Z DBG github.com/traefik/traefik/v3/pkg/provider/docker/config.go:185 > Filtering disabled container container=tfk-bug-traefik-sapsmijmau8u5k5s86uvfrzdh providerName=swarm
tfk_bug_traefik.1.sapsmijmau8u@blob-XPS-9320    | 2025-01-23T14:55:52Z DBG github.com/traefik/traefik/v3/pkg/provider/docker/config.go:185 > Filtering disabled container container=tfk-bug-whoami-d2zh9g3ssagkb7286vkmi3wpj providerName=swarm
tfk_bug_traefik.1.sapsmijmau8u@blob-XPS-9320    | 2025-01-23T14:55:52Z DBG github.com/traefik/traefik/v3/pkg/server/configurationwatcher.go:227 > Configuration received config={"http":{},"tcp":{},"tls":{},"udp":{}} providerName=swarm
``` 

When setting `providers.swarm.exposedbydefault=true` it complains that `error: port is missing` , as if it had silently failed to read the labels which are indeed setting the port.

Adding the docker provider fixes again that issue.

It seems that the changes to [pkg/provider/docker/shared_labels.go](https://github.com/traefik/traefik/commit/514914639aeb2d493062126950192bb9bff82799#diff-e6f8a8d8da09fff729fe2fd7599e63f94bd427d40c787abf531a8b8fb45daffc) in that commit https://github.com/traefik/traefik/commit/514914639aeb2d493062126950192bb9bff82799#diff-e6f8a8d8da09fff729fe2fd7599e63f94bd427d40c787abf531a8b8fb45daffc and this seems not covered by unit tests. 

I am not entirely sure how paerser is supposed to work, but maybe that this line https://github.com/traefik/traefik/blob/2afa03b55cb9387826bdab383f34d0f748f08f92/pkg/provider/docker/shared_labels.go#L54 
fails to parse labels when no `traefik.docker` label is present to be parsed.
