### ISSUE TITLE
Gateway API TCPRoute: potential routing bug to backend

### ISSUE THREAD

**Issue by husira** [traefik/traefik#11454]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We are using Traefik as Ingress Gateway-Controller with the Kubernetes Gateway API. We are using TCPRoutes to route TCP traffic to MongoDB backend services.

There are two mongodb instances which running in two different namespaces:

- mongodb-foo
- mongodb-bar

The Port 27017 is used as Loadbalancer service port to route the TCP traffic via ingress to mongodb. Both TCPRoutes are using the protocol "TLS" with TLS-Termination (terminate mode) on the Gateway (letsencrypt certificates are in place).

### What did you see instead?

The routing to the mongodb instances works, but unfortunately the traffic is routed randomly between backend mongodb-foo and mongodb-bar.

Is that behaviour expected if we use the same ingress port 27017 for two TCP backends via TCProute?
Via TCPRoute the right backend services is referenes via sectionName from the Gateway resource. The Kubernetes resources for the Gateway and the TCPRoutes are accepted regarding the status (see configurations bellow).

I would expect, that the TCPRoutes should route the TCP trafic to the correct backend.

I try to break down the issue. Although I connect to mongodb-bar with the following mongosh command, the traffic is routed to the mongodb-foo backend:

```
mongosh "mongodb://mongodb-foo.lab.azure.k8wms.ch:27017" --tls --username root --password *** --authenticationDatabase admin

Current Mongosh Log ID:	6788b8768d964271f95b4c1c
Connecting to:		mongodb://<credentials>@mongodb-foo.lab.azure.k8wms.ch:27017/?directConnection=true&tls=true&authSource=admin&appName=mongosh+2.3.7
MongoServerError: Authentication failed.
```

In the logs of the mongodb-bar, we can see that the request was routed to the wrong backend. Credentials from mongodb foo & bar are different and you can see the authentication failure due to wrong routing to the mongodb-bar backend:
```
kubectl logs -f -n mongodb-bar deployment/mongodb-bar --tail=100 | grep -i admin

Defaulted container "mongodb" out of: mongodb, log-dir (init)
{"t":{"$date":"2025-01-16T07:42:46.928+00:00"},"s":"I",  "c":"ACCESS",   "id":5286307, "ctx":"conn4369","msg":"Failed to authenticate","attr":{"client":"10.0.0.236:42028","isSpeculative":true,"isClusterMember":false,"mechanism":"SCRAM-SHA-256","user":"root","db":"admin","error":"AuthenticationFailed: SCRAM authentication failed, storedKey mismatch","result":18,"metrics":{"conversation_duration":{"micros":58597,"summary":{"0":{"step":1,"step_total":2,"duration_micros":68},"1":{"step":2,"step_total":2,"duration_micros":34}}}},"extraInfo":{}}}
```

I can resend the mongo shell command and sometimes the traffic is routed to the right backend service mongodb-foo:
```
mongosh "mongodb://mongodb-foo.lab.azure.k8wms.ch:27017" --tls --username root --password *** --authenticationDatabase admin

Current Mongosh Log ID:	6788b95a325b52310c31e67e
Connecting to:		mongodb://<credentials>@mongodb-foo.lab.azure.k8wms.ch:27017/?directConnection=true&tls=true&authSource=admin&appName=mongosh+2.3.7
Using MongoDB:		8.0.4
Using Mongosh:		2.3.7
mongosh 2.3.8 is available for download: https://www.mongodb.com/try/download/shell
------

test> show databases
admin   100.00 KiB
config   60.00 KiB
local    72.00 KiB
```

```
kubectl logs -f -n mongodb-foo deployment/mongodb-foo --tail=100 | grep -i admin

{"t":{"$date":"2025-01-16T07:46:34.741+00:00"},"s":"I",  "c":"ACCESS",   "id":5286306, "ctx":"conn4524","msg":"Successfully authenticated","attr":{"client":"10.0.0.160:42680","isSpeculative":true,"isClusterMember":false,"mechanism":"SCRAM-SHA-256","user":"root","db":"admin","result":0,"metrics":{"conversation_duration":{"micros":50028,"summary":{"0":{"step":1,"step_total":2,"duration_micros":71},"1":{"step":2,"step_total":2,"duration_micros":40}}}},"extraInfo":{}}}
```

We have a workaround to solve this issue by using different Loadbalancer service ports:

- mongodb-foo: 27017
- mongodb-bar: 27018

### What version of Traefik are you using?

Used Version: Traefik: v3.2.2

### What is your environment & configuration?

**Service**
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-33.2.1
  name: traefik
  namespace: traefik
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.36.129
  clusterIPs:
    - 10.0.36.129
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: mongodb
      nodePort: 32478
      port: 27017
      protocol: TCP
      targetPort: mongodb
    - name: web
      nodePort: 30784
      port: 80
      protocol: TCP
      targetPort: web
    - name: websecure
      nodePort: 31132
      port: 443
      protocol: TCP
      targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 4.226.19.16
        ipMode: VIP
```

**Deployment (Traefik-Controller)**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    argocd.argoproj.io/instance: traefik
    helm.sh/chart: traefik-33.2.1
  name: traefik
  namespace: traefik
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: traefik
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: traefik
        helm.sh/chart: traefik-33.2.1
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - --global.checknewversion=false
            - --global.sendAnonymousUsage=false
            - --entryPoints.metrics.address=:9100/tcp
            - --entryPoints.mongodb.address=:27017/tcp
            - --entryPoints.traefik.address=:8080/tcp
            - --entryPoints.web.address=:8000/tcp
            - --entryPoints.websecure.address=:8443/tcp
            - --api.dashboard=true
            - --ping=true
            - --metrics.prometheus=true
            - --metrics.prometheus.entrypoint=metrics
            - --providers.kubernetesgateway
            - --providers.kubernetesgateway.statusaddress.service.name=traefik
            - --providers.kubernetesgateway.statusaddress.service.namespace=traefik
            - --providers.kubernetesgateway.experimentalchannel=true
            - --entryPoints.websecure.http.tls=true
            - --log.format=json
            - --log.level=DEBUG
            - --accesslog=true
            - --accesslog.format=json
            - --accesslog.fields.defaultmode=keep
            - --accesslog.fields.headers.defaultmode=drop
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: docker.io/traefik:v3.2.2
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          name: traefik
          ports:
            - containerPort: 9100
              name: metrics
              protocol: TCP
            - containerPort: 27017
              name: mongodb
              protocol: TCP
            - containerPort: 8080
              name: traefik
              protocol: TCP
            - containerPort: 8000
              name: web
              protocol: TCP
            - containerPort: 8443
              name: websecure
              protocol: TCP
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /tmp
              name: tmp
      dnsPolicy: ClusterFirst
      priorityClassName: high
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: traefik
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60
      volumes:
        - emptyDir: {}
          name: data
        - emptyDir: {}
          name: tmp
status:
  availableReplicas: 3
  conditions:
    - lastTransitionTime: "2025-01-06T17:45:11Z"
      lastUpdateTime: "2025-01-15T07:30:09Z"
      message: ReplicaSet "traefik-646fcfdb97" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-01-16T06:05:06Z"
      lastUpdateTime: "2025-01-16T06:05:06Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 2
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
```

**Gateway**
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/private-key-size: "4096"
  labels:
    ingress: "true"
  name: traefik
  namespace: traefik
spec:
  gatewayClassName: traefik
  listeners:
    - allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              ingress: "true"
      hostname: mongodb-bar.lab.azure.k8wms.ch
      name: mongodb-bar-acme-http
      port: 8000
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              ingress: "true"
      hostname: mongodb-bar.lab.azure.k8wms.ch
      name: mongodb-bar-tcp-tls
      port: 27017
      protocol: TLS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: mongodb-bar-tcp-tls
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              ingress: "true"
      hostname: mongodb-foo.lab.azure.k8wms.ch
      name: mongodb-foo-acme-http
      port: 8000
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              ingress: "true"
      hostname: mongodb-foo.lab.azure.k8wms.ch
      name: mongodb-foo-tcp-tls
      port: 27017
      protocol: TLS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: mongodb-foo-tcp-tls
        mode: Terminate
status:
  addresses:
    - type: IPAddress
      value: 4.226.19.16
  conditions:
    - lastTransitionTime: "2025-01-15T07:41:05Z"
      message: Gateway successfully scheduled
      observedGeneration: 4
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2025-01-15T07:41:05Z"
      message: Gateway successfully scheduled
      observedGeneration: 4
      reason: Programmed
      status: "True"
      type: Programmed
  listeners:
    - attachedRoutes: 0
      conditions:
        - lastTransitionTime: "2025-01-15T07:41:05Z"
          message: No error found
          observedGeneration: 4
          reason: Accepted
          status: "True"
          type: Accepted
        - lastTransitionTime: "2025-01-15T07:41:05Z"
          message: No error found
          observedGeneration: 4
          reason: ResolvedRefs
          status: "True"
          type: ResolvedRefs
        - lastTransitionTime: "2025-01-15T07:41:05Z"
          message: No error found
          observedGeneration: 4
          reason: Programmed
          status: "True"
          type: Programmed
      name: mongodb-bar-acme-http
      supportedKinds:
        - group: gateway.networking.k8s.io
          kind: HTTPRoute
        - group: gateway.networking.k8s.io
          kind: GRPCRoute
    - attachedRoutes: 1
      conditions:
        - lastTransitionTime: "2025-01-15T07:41:05Z"
          message: No error found
          observedGeneration: 4
          reason: Accepted
          status: "True"
          type: Accepted
        - lastTransitionTime: "2025-01-15T07:41:05Z"
          message: No error found
          observedGeneration: 4
          reason: ResolvedRefs
          status: "True"
          type: ResolvedRefs
        - lastTransitionTime: "2025-01-15T07:41:05Z"
          message: No error found
          observedGeneration: 4
          reason: Programmed
          status: "True"
          type: Programmed
      name: mongodb-bar-tcp-tls
      supportedKinds:
        - group: gateway.networking.k8s.io
          kind: TCPRoute
        - group: gateway.networking.k8s.io
          kind: TLSRoute
    - attachedRoutes: 0
      conditions:
        - lastTransitionTime: "2025-01-15T07:41:05Z"
          message: No error found
          observedGeneration: 4
          reason: Accepted
          status: "True"
          type: Accepted
        - lastTransitionTime: "2025-01-15T07:41:05Z"
          message: No error found
          observedGeneration: 4
          reason: ResolvedRefs
          status: "True"
          type: ResolvedRefs
        - lastTransitionTime: "2025-01-15T07:41:05Z"
          message: No error found
          observedGeneration: 4
          reason: Programmed
          status: "True"
          type: Programmed
      name: mongodb-foo-acme-http
      supportedKinds:
        - group: gateway.networking.k8s.io
          kind: HTTPRoute
        - group: gateway.networking.k8s.io
          kind: GRPCRoute
    - attachedRoutes: 1
      conditions:
        - lastTransitionTime: "2025-01-15T07:41:05Z"
          message: No error found
          observedGeneration: 4
          reason: Accepted
          status: "True"
          type: Accepted
        - lastTransitionTime: "2025-01-15T07:41:05Z"
          message: No error found
          observedGeneration: 4
          reason: ResolvedRefs
          status: "True"
          type: ResolvedRefs
        - lastTransitionTime: "2025-01-15T07:41:05Z"
          message: No error found
          observedGeneration: 4
          reason: Programmed
          status: "True"
          type: Programmed
      name: mongodb-foo-tcp-tls
      supportedKinds:
        - group: gateway.networking.k8s.io
          kind: TCPRoute
        - group: gateway.networking.k8s.io
          kind: TLSRoute
```

**TCPRoute mongodb-foo**
```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: mongodb-foo-tcp-route
  namespace: mongodb-foo
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik
      namespace: traefik
      sectionName: mongodb-foo-tcp-tls
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: mongodb-foo
          namespace: mongodb-foo
          port: 27017
          weight: 1
status:
  parents:
    - conditions:
        - lastTransitionTime: "2025-01-15T07:41:05Z"
          message: ""
          observedGeneration: 1
          reason: Accepted
          status: "True"
          type: Accepted
        - lastTransitionTime: "2025-01-15T07:41:05Z"
          message: ""
          observedGeneration: 1
          reason: ResolvedRefs
          status: "True"
          type: ResolvedRefs
      controllerName: traefik.io/gateway-controller
      parentRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        name: traefik
        namespace: traefik
        sectionName: mongodb-foo-tcp-tls
```

**TCPRoute mongodb-bar**
```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: mongodb-bar-tcp-route
  namespace: mongodb-bar
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik
      namespace: traefik
      sectionName: mongodb-bar-tcp-tls
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: mongodb-bar
          namespace: mongodb-bar
          port: 27017
          weight: 1
status:
  parents:
    - conditions:
        - lastTransitionTime: "2025-01-15T07:38:32Z"
          message: ""
          observedGeneration: 1
          reason: Accepted
          status: "True"
          type: Accepted
        - lastTransitionTime: "2025-01-15T07:38:32Z"
          message: ""
          observedGeneration: 1
          reason: ResolvedRefs
          status: "True"
          type: ResolvedRefs
      controllerName: traefik.io/gateway-controller
      parentRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        name: traefik
        namespace: traefik
        sectionName: mongodb-bar-tcp-tls
```

### If applicable, please paste the log output in DEBUG level

**Pod IP of mongodb-foo: 10.0.2.238**
```
kubectl get pod -n mongodb-foo -owide
NAME                          READY   STATUS    RESTARTS   AGE   IP           NODE                                NOMINATED NODE   READINESS GATES
mongodb-foo-bf59d958c-77fwn   1/1     Running   0          16h   10.0.2.238   aks-agentpool-23316837-vmss0000d5   <none>           <none>
```

**Pod IP of mongodb-bar: 10.0.1.19**
```
kubectl get pod -n mongodb-bar -owide
NAME                           READY   STATUS    RESTARTS   AGE   IP          NODE                                  NOMINATED NODE   READINESS GATES
mongodb-bar-5676f98548-78bhf   1/1     Running   0          16h   10.0.1.19   aks-servicepool-26422701-vmss0000dn   <none>           <none>
```

**Pod IPs of traefik replicas (3)**
```
kubectl get pod -n traefik -owide
NAME                             READY     STATUS     RESTARTS   AGE   IP           NODE                                  NOMINATED NODE   READINESS GATES
traefik-646fcfdb97-9rhs5         1/1       Running    0          17h   10.0.0.160   aks-servicepool-26422701-vmss0000dm   <none>           <none>
traefik-646fcfdb97-sc8kl         1/1       Running    0          17h   10.0.0.145   aks-servicepool-26422701-vmss0000dm   <none>           <none>
traefik-646fcfdb97-z4clq         1/1       Running    0          17h   10.0.0.236   aks-servicepool-26422701-vmss0000dm   <none>           <none>
```
---

**Connection which was routed to the wrong backend: mongodb-bar**

Connecting to mongodb-foo
```
mongosh "mongodb://mongodb-foo.lab.azure.k8wms.ch:27017" --tls --username root --password *** --authenticationDatabase admin
Current Mongosh Log ID: 6788f74441400f76e538fc02
Connecting to:    mongodb://<credentials>@mongodb-foo.lab.azure.k8wms.ch:27017/?directConnection=true&tls=true&authSource=admin&appName=mongosh+2.3.7

MongoServerError: Authentication failed.
```

Traefik Logs:
```
traefik-646fcfdb97-sc8kl traefik {"level":"debug","address":"10.0.2.238:27017","remoteAddr":"10.0.5.54:57100","time":"2025-01-16T12:10:44Z","caller":"github.com/traefik/traefik/v3/pkg/tcp/proxy.go:41","message":"Handling TCP connection"}
traefik-646fcfdb97-z4clq traefik {"level":"debug","address":"10.0.1.19:27017","remoteAddr":"10.0.1.25:61938","time":"2025-01-16T12:10:44Z","caller":"github.com/traefik/traefik/v3/pkg/tcp/proxy.go:41","message":"Handling TCP connection"}
traefik-646fcfdb97-z4clq traefik {"level":"debug","error":"set tcp 10.0.0.236:27017: use of closed network connection","time":"2025-01-16T12:10:44Z","caller":"github.com/traefik/traefik/v3/pkg/tcp/proxy.go:113","message":"Error while setting TCP connection deadline"}
```

In the log output of Traefik you can see, that the gateway controller tries to send the TCP traffic to address 10.0.1.19:27017 which is the mongodb-bar pod. But the connection should only be established to Pod IP 10.0.2.238 (mongodb-foo). 

---

**Connection which was routed to the correct backend: mongodb-foo**

Connecting to mongodb-foo
```
mongosh "mongodb://mongodb-foo.lab.azure.k8wms.ch:27017" --tls --username root --password *** --authenticationDatabase admin
Current Mongosh Log ID:	6788f9c2bf1672e3ae1247c0
Connecting to:		mongodb://<credentials>@mongodb-foo.lab.azure.k8wms.ch:27017/?directConnection=true&tls=true&authSource=admin&appName=mongosh+2.3.7
Using MongoDB:		8.0.4
Using Mongosh:		2.3.7
mongosh 2.3.8 is available for download: https://www.mongodb.com/try/download/shell

For mongosh info see: https://www.mongodb.com/docs/mongodb-shell/
------

test> show databases;
admin   100.00 KiB
config   72.00 KiB
local    72.00 KiB
```

Traefik Logs:
```
traefik-646fcfdb97-9rhs5 traefik {"level":"debug","address":"10.0.2.238:27017","remoteAddr":"10.0.5.54:49494","time":"2025-01-16T12:21:22Z","caller":"github.com/traefik/traefik/v3/pkg/tcp/proxy.go:41","message":"Handling TCP connection"}
traefik-646fcfdb97-9rhs5 traefik {"level":"debug","address":"10.0.2.238:27017","remoteAddr":"10.0.5.54:54883","time":"2025-01-16T12:21:22Z","caller":"github.com/traefik/traefik/v3/pkg/tcp/proxy.go:41","message":"Handling TCP connection"}
traefik-646fcfdb97-9rhs5 traefik {"level":"debug","address":"10.0.2.238:27017","remoteAddr":"10.0.3.116:62807","time":"2025-01-16T12:21:23Z","caller":"github.com/traefik/traefik/v3/pkg/tcp/proxy.go:41","message":"Handling TCP connection"}
traefik-646fcfdb97-9rhs5 traefik {"level":"debug","address":"10.0.2.238:27017","remoteAddr":"10.0.4.53:34873","time":"2025-01-16T12:21:23Z","caller":"github.com/traefik/traefik/v3/pkg/tcp/proxy.go:41","message":"Handling TCP connection"}
```

Unfortunately there is no access log for TCP traffic according to this issue: https://github.com/traefik/traefik/issues/7800

If necessary, I can also provide further information.
