### ISSUE TITLE
Kubernetes native service not picked up by `kubernetescrd` provider

### ISSUE THREAD

**Issue by guidojw** [traefik/traefik#11481]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am trying to create an IngressRoute and point it to an existing Kubernetes service of `spec.type` LoadBalancer that serves http/https:

```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole-web
  namespace: pihole
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - match: Host(`example.com`)
    kind: Rule
  services:
  - name: pihole-web
```

```yaml
apiVersion: v1
kind: Service
metadata: 
  name: pihole-web
  namespace: pihole
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
ports:
- port: 80
  targetPort: http
  protocol: TCP
  name: http
- port: 443
  targetPort: https
  protocol: TCP
  name: https
```

### What did you see instead?

Both the Traefik dashboard and logs show that the service my IngressRoute points does not exist:

![Image](https://github.com/user-attachments/assets/16b62cb6-1dee-4e08-a894-9b8144419a12)

The service can indeed not be found underneath the HTTP Services tab.

I tested out discovery by creating a dummy `TraefikService` in the `pihole` namespace, Traefik logs showed that it correctly discovered this as a service. I can however not utilise the `TraefikService` CRD here as the service is managed by the Pi-hole Helm chart I'm using.

From what I see on Traefik documentation, this should be a supported use case. Am I misunderstanding how the `kubernetescrd` provider works?

### What version of Traefik are you using?

Traefik v3.2.0
Traefik Proxy Helm Chart v33.0.0

### What is your environment & configuration?

```yaml
traefik:
  ingressRoute:
    dashboard:
      enabled: true

  logs:
    general:
      level: DEBUG

  globalArguments: []

  ports:
    traefik:
      expose:
        default: true

  service:
    annotations:
      "io.cilium/lb-ipam-ips": "192.168.31.2"
```

Thus using the Traefik Helm chart's [default `providers.kubernetesCRD` values](https://github.com/traefik/traefik-helm-chart/blob/906c7d0aaf492948f6cb78718e6c501b17612ef4/traefik/values.yaml#L264C3-L279C29).

### If applicable, please paste the log output in DEBUG level

```
2025-01-22T23:34:25Z ERR error="the service \"pihole-pihole-web-fe3df2bf5ee1ea33281d@kubernetescrd\" does not exist" entryPointName=websecure routerName=websecure-pihole-pihole-web-fe3df2bf5ee1ea33281d@kubernetescrd
```

It does not show anything about discovering/creating native services ever.
