### ISSUE TITLE
Traefik Does Not Detect Podman Containers Unless `allowEmptyServices: true`

### ISSUE THREAD

**Issue by designgears** [traefik/traefik#11494]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

When using Traefik **v3.3.2** with **Podman v5.3.2**, container service discovery does not work unless `allowEmptyServices: true` is set in the Traefik configuration. With `allowEmptyServices: false`, **no containers are detected**.

This behavior occurs in **both rootless and rootful Podman mode**, suggesting that Traefik is failing to retrieve or interpret container metadata correctly from the Podman socket.

### **Expected Behavior** 
- Containers with the correct Traefik labels (`traefik.enable=true`, `traefik.http.routers.xxx.rule`, etc.) should be detected and available as services in Traefik.  
- The `allowEmptyServices` flag should not be required unless the user wants to allow services with no backends.

### **Observed Behavior**  
- **With `allowEmptyServices: true`** → All containers (including those without Traefik labels) appear in the Traefik dashboard and function correctly.  
- **With `allowEmptyServices: false`** → No containers appear in the dashboard or logs, and new containers are not detected by Traefik.

### What version of Traefik are you using?

Traefik v3.3.2 with Podman v5.3.2

### What is your environment & configuration?

```yaml
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: "0.0.0.0:80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: "0.0.0.0:443"
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

serversTransport:
  insecureSkipVerify: true


providers:
  docker:
    allowEmptyServices: true
  file:
    filename: /etc/traefik/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: email@email.com
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

log:
  level: DEBUG
```

### **Steps to Reproduce**  
1. Install Podman **v5.3.2** and configure the socket:  
   - **Rootless:** `/run/user/1000/podman/podman.sock`  
   - **Rootful:** `/var/run/podman/podman.sock`
2. Deploy Traefik **v3.3.2** with the following provider settings:  
   ```yaml
   providers:
     docker:
       endpoint: "unix:///run/user/1000/podman/podman.sock" # (or /var/run/podman/podman.sock for rootful)
       exposedByDefault: false
       watch: true```
3. Start a container with Traefik labels: 
```dockerfile
podman run -d
  --name sonarr
  --network web
  -l "traefik.enable=true"
  -l "traefik.http.routers.sonarr.rule=Host(`sonarr.example.com`)"
  -l "traefik.http.routers.sonarr.entrypoints=websecure"
  -l "traefik.http.services.sonarr.loadbalancer.server.port=8989"
  linuxserver/sonarr:develop
```
4. Open the Traefik dashboard or check logs.
5. If `allowEmptyServices: false`, no services are detected.
6. If `allowEmptyServices: true`, all containers appear (even those without Traefik labels).
