### ISSUE TITLE
No headerField under forwardAuth KubernetesCRD

### ISSUE THREAD

**Issue by vrbgtrhr** [traefik/traefik#11490]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

i think that headerField  is not defined under forwardAuth https://raw.githubusercontent.com/traefik/traefik/v3.3/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml 

i have found it definition under basicauth but not forwardAuth

the problem was started from this Kubernetes error: 

`Error from server (BadRequest): error when creating "monitoring.yaml": Middleware in version "v1alpha1" cannot be handled as a Middleware: strict decoding error: unknown field "spec.forwardAuth.headerField"`

the middleware:
```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: grafana-auth
  namespace: monitoring
spec:
  forwardAuth:
    address: <url>
    headerField: X-WEBAUTH-USER
```

### What did you see instead?

`Error from server (BadRequest): error when creating "monitoring.yaml": Middleware in version "v1alpha1" cannot be handled as a Middleware: strict decoding error: unknown field "spec.forwardAuth.headerField"`

### What version of Traefik are you using?

rancher/mirrored-library-traefik:2.10.7

### What is your environment & configuration?

nothing not default about middleware
