### ISSUE TITLE
SERVER_NAME variable is not correctly paased on in a multiple domain setup used for Nginx Server Blocks (Virtual Hosts)

### ISSUE THREAD

**Issue by dirk-dhu** [traefik/traefik#11506]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have setup  trafik server for two domains with letsencrypt and tls, see configuration. the routing of both domains work perfectly

### What did you see instead?

I am using following index.php
<?php
echo "First level<br/>";
echo "HTTP_HOST: ";
echo $_SERVER['HTTP_HOST'] . "<br/>";
echo "SERVER_NAME: ";
echo $_SERVER['SERVER_NAME'] . "<br/>";
?>
and would expect that differnt HTTP_HOST and SERVER_NAME are printed out.
How ever only DOMAIN1 is printed out for SERVER_NAME but for HTTP_HOST the appropiate doamine of the calling URL

### What version of Traefik are you using?

I used traefik 3.2.5 and 3.3.3

### What is your environment & configuration?

I am using nginx behind traefik and want to use the two domains to access different content using server_name blocks.
for ${DOMAIN1} and ${DOMAIN2} I have used the real names not the environments 
```yaml
  traefik:
    # Der Name des Containers, der aus diesem Service erzeugt wird
    container_name: ${SERVICES_TRAEFIK_CONTAINER_NAME:-traefik}
    # Diese Option sorgt dafür, dass der Traefik-Service erst gestartet wird,
    # nachdem der Crowdsec-Service healthy ist
    depends_on:
      crowdsec:
        condition: service_healthy
    # Umgebungsvariablen für den Container.
    env_file: ./config/traefik.env
    # Hostname des Traefik-Containers, kann über eine Umgebungsvariable angepasst werden.
    hostname: ${SERVICES_TRAEFIK_HOSTNAME:-traefik}
    # Gesundheitsüberprüfung für den Traefik-Service
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 10s
    # Das Docker-Image, das für diesen Service verwendet wird
    # Version kann über eine Umgebungsvariable angepasst werden. Standard: 3.3
    image: ${SERVICES_TRAEFIK_IMAGE:-traefik}:${SERVICES_TRAEFIK_IMAGE_VERSION:-3.3}
    # Docker Labels für den Traefik-Service. Diese werden für die Traefik-Konfiguration verwendet
    labels:
      traefik.docker.network: proxy
      traefik.enable: "true"
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.middlewares: secHeaders@file, traefikAuth@file
      #traefik.http.routers.traefik.rule: Host(${SERVICES_TRAEFIK_LABELS_TRAEFIK_HOST})
      traefik.http.routers.traefik.rule: Host(`${DOMAIN1}`) || Host(`${DOMAIN2}`)
      traefik.http.routers.traefik.tls: "true"
      traefik.http.routers.traefik.tls.certresolver: http_resolver
      traefik.http.routers.traefik.tls.domains[0].main: ${DOMAIN1}
      traefik.http.routers.traefik.tls.domains[1].main: ${DOMAIN2}
      traefik.http.services.traefik.loadbalancer.sticky.cookie.httpOnly: "true"
      traefik.http.services.traefik.loadbalancer.sticky.cookie.secure: "true"
      traefik.http.routers.pingweb.rule: PathPrefix(`/ping`)
      traefik.http.routers.pingweb.service: ping@internal
      traefik.http.routers.pingweb.entrypoints: websecure

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        environment:
          - TZ=Europe/Berlin
        volumes_from:
          - perlite
        depends_on:
          - perlite
        volumes:
          - './app:/var/www/html'
          - './default.conf:/etc/nginx/conf.d/default.conf'
          - 'ssl_certs:/etc/ssl/certs:ro'
          - '/var/log/nginx:/var/log/nginx'
        networks:
          default:
          proxy:
            # IPv4-Adresse des Nginx Containers im Traefik-Netwerk: proxy
            ipv4_address: ${SERVICES_NGINX_NETWORKS_PROXY_IPV4:-172.30.251.254}
        labels:
          traefik.enable: true
          traefik.http.routers.nginx.entrypoints: websecure
          traefik.http.routers.nginx.rule: Host(`${DOMAIN1}`) || Host(`${DOMAIN2}`) 
          traefik.http.routers.nginx.tls: true
          traefik.http.routers.nginx.tls.certresolver: http_resolver
          traefik.http.routers.nginx.service: nginx
          #traefik.http.middlewares.secure-headers.headers.customresponseheaders.server: '{{.Node.Hostname}}'
          traefik.http.routers.nginx.middlewares: secHeaders@file #, secure-headers
          traefik.http.routers.nginx.priority: 70
          traefik.http.services.nginx.loadbalancer.server.port: 80
          #traefik.http.services.nginx.passHostHeader: false
          #traefik.http.services.nginx.loadbalancer.server.url: http://nginx:80
          traefik.docker.network: proxy
```

Add more configuration information here.
