### ISSUE TITLE
ingressRoute ignores namespaces

### ISSUE THREAD

**Issue by prudnitskiy** [traefik/traefik#11517]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm trying to create an ingress to service in another namespace. Even if traefik supports this configuration based on spec, it ignores the setup.

Setup example 1:
```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault
  namespace: intl
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`vault.domain.local`)
    middlewares:
    - name: oauth-errors
    - name: oauth-auth
    services:
    - name: vault
      namespace: vault
      port: http
```

Setup example 2, service is in the same NS as ingress but middleware is in another NS:
```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault
  namespace: vault
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`vault.domain.local`)
    middlewares:
    - name: oauth-errors
      namespace: intl
    - name: oauth-auth
      namespace: intl
    services:
    - name: vault
      port: http
```

Middleware could not reference to the service in another NS as well

### What did you see instead?

Setup 1:

```
level=error msg="service vault/vault not in the parent resource namespace intl" providerName=kubernetescrd ingress=vault namespace=intl
```

Setup 2:
```
level=error msg="Failed to create middleware keys: middleware intl/oauth-headers is not in the IngressRoute namespace vault" ingress=vault namespace=vault providerName=kubernetescrd
level=error msg="Failed to create middleware keys: middleware intl/oauth-errors is not in the IngressRoute namespace vault" ingress=vault namespace=vault providerName=kubernetescrd
```

### What version of Traefik are you using?

2.11.10

### What is your environment & configuration?

K3S bundled setup, no changes in traefik config
