### ISSUE TITLE
Allow multiple watched directories in file provider

### ISSUE THREAD

**Issue by cleboo** [traefik/traefik#11512]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hi!

# Feature Request:
I would like to configure multiple directories in the file provider config so that the configurations in multiple directories are loaded and watched for changes. This would look something like this:
```yaml
providers:
  file:
    directories: 
      - "/etc/traefik_dynamic/global"
      - "/etc/traefik_dynamic/host"
    watch: true
```

# Background
The issue I am running into is this: I am using traefik inside docker containers on multiple hosts. These hosts share a basic configuration (`traefik.toml` + `dynamic_conf.global.toml`) and then have specialized settings in a separate `dynamic_conf.host.toml`.

Now, because of the Limitations described in the [File Provider docs](https://doc.traefik.io/traefik/providers/file/), I have to mount these config files into the traefik container by mounting their parent directories - written something like this in docker-compose:
```yaml
services:
  traefik:
    ...
    volumes:
      - ./etc:/etc/traefik:ro
      - ./etc_dynamic.global:/etc/traefik_dynamic/global:ro
      - ./etc_dynamic.host:/etc/traefik_dynamic/host:ro
```
Then configure the file provider like above.

# Alternatives
+ I could mount a volume inside a volume - however this would run into this issue: https://github.com/traefik/traefik/issues/3986
+ have multiple file providers - that is not possible: https://github.com/traefik/traefik/issues/9101
+ use a script that copies together the right configurations - I can not run scripts on the hosts in this setup, so I would have to modify the traefik container itself and then implement my own  listener for file changes. Being able to configure this in traefik would be way easier and less prone to errors.

Thanks!
