### ISSUE TITLE
Traefik does not know how to handle .* in Host or HostRegexp

### ISSUE THREAD

**Issue by Daniel-lu-zeronetworks** [traefik/traefik#11525]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### current status

 Currently, when trying to use a wild card in the HostRegexp like this :
```
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-name
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`.*-example.com`)
      kind: Rule
      services:
        - name: service
          port: 80
  tls:
    options:
      name: cert```
```

i get the following warning:

`No domain found in rule HostRegexp(`.*-example.com`) the TLS options applied for this router will depend on the SNI of each request`

when trying to use the Host() it does not work at all: 
```
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-name
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`.*-example.com`)
      kind: Rule
      services:
        - name: service
          port: 80
  tls:
    options:
      name: cert
```

based on [this](https://github.com/traefik/traefik/blob/786d9f3272f09e55f8f1cc5bb9bb67b3f867b5c0/pkg/server/router/tcp/manager.go#L182) we found out that
rule: PathPrefix("/foo")
Wherever the request comes from, the TLS config used will be the default one, because of the Host(*) fallback.

and from what i understand that when a router is defined for HTTPS without any explicit Host rule, Traefik cannot decide on a TLS configuration based on a domain name from the routing rule. In such cases, Traefik “falls back” to a special, catch‐all configuration (represented internally as Host("*")) that uses the default TLS configuration.

In our case, traefik does not recognize this as a valid domain .*-foo.example.com, and this is why we get the error No domain found in rule HostRegexp

### proposal

instead of insisting on using only Rule:` "HostRegexp(`^.+$`)" ` you should consider allowing * at a host level 

Also, clarifying the expected format (e.g., whether users must use anchors for a valid match ^ at the start and $ at the end ) would help users write rules that Traefik can properly parse and use to select TLS options.
