### ISSUE TITLE
Include Kubernetes semantic resource attributes in spans

### ISSUE THREAD

**Issue by FredrikAugust** [traefik/traefik#11521]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hey, I was wondering if there was any recommended way or plan to include resource attributes from the pod into the resource attributes of a span?

Resource attributes in question (with fieldRef) would be:

```yaml
- k8s.pod.uid: metadata.uid
- k8s.pod.name: metadata.name
- k8s.pod.namespace: metadata.namespace
```

This would make it easier to enrich the spans in the Otel collector.

Thanks!
