### ISSUE TITLE
Content-Type header not set with Retry middleware

### ISSUE THREAD

**Issue by darkweaver87** [traefik/traefik#11533]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I've an environment with an `IngressRoute` attached to Traefik dashboard and with some security `Middleware`s enabled on the entrypoint serving the traffic.
Especially I'm using the `contentTypeNosniff` option.
After upgrading to v3.3.0, the dashboard is not displayed anymore.

### What did you see instead?

Instead of seeing the dashboard, I see it's HTML code.

### What version of Traefik are you using?

v3.3.3

### What is your environment & configuration?

I managed to isolate and reproduce the issue:
- setup a K8S cluster:
```bash
k3d cluster create --k3s-arg --disable=traefik@server:* -p 80:80@loadbalancer
```
-  install traefik with helm chart:
```bash
helm upgrade --install demo traefik/traefik -n traefik --create-namespace -f values.yaml
```

with `values.yaml`:
```yaml
image:
  registry: docker.io
  repository: traefik
  tag: v3.3.3

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true

ports:
  web:
    middlewares:
      - traefik-security@kubernetescrd
      - traefik-retry@kubernetescrd

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`plop.docker.localhost`)
    services:
      - name: api@internal
        kind: TraefikService
    entryPoints: ["web"]

extraObjects:
  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: security
      namespace: traefik
    spec:
      headers:
        contentTypeNosniff: true
        customResponseHeaders:
          Plop: "plop"
  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: retry
      namespace: traefik
    spec:
      retry:
        attempts: 4
        initialInterval: 100ms
```

It's not working because `X-Content-Type-Options: nosniff` blocks the browser from guessing the MIME type. As `Content-Type` is not returned, browser is displaying HTML code as it was `text/plain`.

With v3.3.0:
```bash
curl -s http://plop.docker.localhost/dashboard/ -I -XGET
HTTP/1.1 200 OK
Plop: plop
X-Content-Type-Options: nosniff
Date: Fri, 14 Feb 2025 08:30:12 GMT
Content-Length: 1193
```

With v3.2.5:
```bash
curl -s http://plop.docker.localhost/dashboard/ -I -XGET
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 1153
Content-Security-Policy: frame-src 'self' https://traefik.io https://*.traefik.io;
Content-Type: text/html; charset=utf-8
Plop: plop
X-Content-Type-Options: nosniff
Date: Fri, 14 Feb 2025 08:31:12 GMT
```

To make it work, either:
- setting `contentTypeNosniff` to `false`
- inverting the order of entrypoint middlewares on Traefik >= v3.3.2
