### ISSUE TITLE
[Feature] support dynamic compiled plugins

### ISSUE THREAD

**Issue by Sharaf5** [traefik/traefik#11540]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Looking at a project like [coredns](https://github.com/coredns/coredns) is very lightwight and resource aware while it support plugins in another way
it require compiling plugins in a custom build and enabling it via `plugin.cfg` file

[Nginx open source](https://github.com/nginx/nginx) and [Tengine](https://github.com/alibaba/tengine) has another better solution allowing dynamic modules `*.so` to be loaded, with a huge diff between requersts/sec handled

AFAIK : Traefik is mostly similar in core design to CoreDNS and could adapt the same approch for more better performance, or better : there should be a way to compile and load/unload external modules, so traefik core isn't affected by any buggy plugin and it's just dropped

I know it could mean a huge transition in core of traefik but it also could extend traefik so far and post it's performance beyond its current limits where users like me porting from other solutions find it at least similar in performance so no doughts on loosing current clients due to difference, also  I tried to implement plugins for both CoreDNS and Traefik and found CoreDNS away more simpler (2 hr learning and plugin worked perfectly on CoredNS - vs - 3w learning and didn't make a good step on Traefik | Maybe I'm just not familier but it's still huge amount of time)

I'm sugesting dynamic compiled modules for it's portablity, better performance, and dynamic nature

looking forward to hear your idea
; regards - Abdelaziz Sharaf

**Comment by Sharaf5** [comment]
I tried to see if chatgpt would give me a good approch and want to share this with the developers

https://chatgpt.com/share/681ce5f5-7428-8005-8270-b7ec0ba30310

> of course I need more human feedback but it's worth read
> not to be confused : I miss wrote nginx insted of traefik in the sequence message where I stopped deep-search

**Comment by yirwanditiket** [comment]
my experience with traefik interpreted plugin:
- unexpected panic: from using generic, reflection, from the 3rd party library i use (they are dependency injection libs)
- slow performance: my plugin use http client that call external auth service, my other plugin that only add random request id also increase the cpu usage quite a lot.

sure the panic issue can be fixed in the interpreter side / do some workaround, and the hot reload is nice, but i rather have type safety and performance with the compiled plugin

---

i'm planning to compare with injecting my middleware to the traefik source code and build a custom image.

---

Update:
I compared the plugin locally with the interpreter vs compiled (directly inserting the code)
result: the interpreter version shows 20 - 30% higher cpu in my laptop (7840hs) for 40k RPM target / endpoint


k6: 
```javascript
	scenarios: {
		constant_request_rate: {
			executor: 'constant-arrival-rate',
			rate: 40000,
			timeUnit: '1m',
			duration: '2m',
			preAllocatedVUs: 80,
			maxVUs: 600,
		},
	},

```

pkg/config/dynamic/middlewares.go

```go
 XPlugin map[string]PluginConf `json:"xplugin,omitempty" toml:"xplugin,omitempty" yaml:"xplugin,omitempty" export:"true"`
```

pkg/server/middleware/middlewares.go
```go
	if config.XPlugin != nil {
		if middlewareName == "super-initiate@file" {
			middleware = func(next http.Handler) (http.Handler, error) {
				return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
					next.ServeHTTP(w, initiate.InitiateRequestId(w, r))
				}), nil
			}
		}
	}

```

(the plugin)
```go
package initiate

import (
	"net/http"
	"context"

	"github.com/google/uuid"
)

const (
	RequestId = "requestId"
)

// InitiateRequestId implements PreProcessFn.
// It generates a new uuid random string
// then set it in the request and response header and context
func InitiateRequestId(w http.ResponseWriter, r *http.Request) *http.Request {
	requestId := uuid.NewString()
	w.Header().Set(RequestId, requestId)
	return wrapRequest(r, requestId)
}


// wrapRequest set the requestId header, request id context, and request id log attribute context
func wrapRequest(r *http.Request, requestId string) *http.Request {
	// setting the requestId header
	r.Header.Set(RequestId, requestId)

	// setting the request id context
	ctx := context.WithValue(r.Context(), RequestId, requestId)

	return r.WithContext(ctx)
}
```

static config
```yaml
  localPlugins:
    initiate:
      moduleName: github.com/mycompany/myrepo/plugins/initiate

```

dyn config
```yaml
http:
  routers:
    # Define a connection between requests and services
    endpoint1:
      rule: "Path(`/endpoint1`)"
      service: mockserver
      middlewares:
        - super-initiate           # the compiled version
        - initiate-middleware # the interpreter version
        
....

  middlewares:
    initiate-middleware:
      plugin:
        initiate: {}
    super-initiate:
      xplugin:
        initiate: {}

```
