### ISSUE TITLE
Fast Proxy not working when accessing Portainer

### ISSUE THREAD

**Issue by Power2All** [traefik/traefik#11552]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Deployed Traefik 3.3.3 through Docker Swarm.
Here the configuration of Traefik and the Docker Compose config:

### What did you see instead?

My own website showing weird numbers on each linebreak in the content response.
Portainer doesn't load at all, giving an "Content Encoding Error" in Firefox.
Disabling Fast Proxy resolved the issue.
Reverting to 3.3.2 with Fast Proxy resolved the issue as well.

### What version of Traefik are you using?

v3.3.3

### What is your environment & configuration?

traefik.yaml
```yaml
log:
  level: ERROR

accessLog:
  filePath: "***CENSORED***"
  fields:
    headers:
      defaultMode: keep

api:
  debug: false
  dashboard: true

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

experimental:
  plugins:
    middleflare:
      moduleName: github.com/neggles/middleflare
      version: v0.0.2
  fastProxy: {}

entryPoints:
  http:
    address: ":80"
    forwardedHeaders:
      trustedIPs:
        - "103.21.244.0/22"
        - "103.22.200.0/22"
        - "103.31.4.0/22"
        - "104.16.0.0/13"
        - "104.24.0.0/14"
        - "108.162.192.0/1"
        - "131.0.72.0/22"
        - "141.101.64.0/18"
        - "162.158.0.0/15"
        - "172.64.0.0/13"
        - "173.245.48.0/20"
        - "188.114.96.0/20"
        - "190.93.240.0/20"
        - "197.234.240.0/22"
        - "198.41.128.0/17"
        - "2400:cb00::/32"
        - "2606:4700::/32"
        - "2803:f800::/32"
        - "2405:b500::/32"
        - "2405:8100::/32"
        - "2c0f:f248::/32"
        - "2a06:98c0::/29"
        - "62.171.179.41"
        - "45.148.123.37"
        - "185.82.216.109"
        - "101.99.93.246"
  https:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
        - "103.21.244.0/22"
        - "103.22.200.0/22"
        - "103.31.4.0/22"
        - "104.16.0.0/13"
        - "104.24.0.0/14"
        - "108.162.192.0/1"
        - "131.0.72.0/22"
        - "141.101.64.0/18"
        - "162.158.0.0/15"
        - "172.64.0.0/13"
        - "173.245.48.0/20"
        - "188.114.96.0/20"
        - "190.93.240.0/20"
        - "197.234.240.0/22"
        - "198.41.128.0/17"
        - "2400:cb00::/32"
        - "2606:4700::/32"
        - "2803:f800::/32"
        - "2405:b500::/32"
        - "2405:8100::/32"
        - "2c0f:f248::/32"
        - "2a06:98c0::/29"
        - "62.171.179.41"
        - "45.148.123.37"
        - "185.82.216.109"
        - "101.99.93.246"

providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: External-Network
  file:
    filename: "***CENSORED***"

certificatesResolvers:
  cloudflare:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: "cloudflare"
  cloudns:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: "cloudns"
  httpChallenge:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: ***CENSORED***
      storage: acme.json
      httpChallenge:
        entryPoint: http
  tlsChallenge:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: ***CENSORED***
      storage: acme.json
      tlsChallenge: {}

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true
```

Compose file for Traefik
```yaml
  traefik:
    image: traefik:v3.3.3
    restart: always
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.entrypoints=http"
        - "traefik.http.routers.traefik.rule=Host(`***CENSORED***`)"
        - "traefik.http.middlewares.traefik-auth.basicauth.users=***CENSORED***"
        - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.traefik-cloudflare.plugin.middleflare.includeDefault=true"
        - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
        - "traefik.http.routers.traefik-secure.entrypoints=https"
        - "traefik.http.routers.traefik-secure.rule=Host(`***CENSORED***`)"
        - "traefik.http.routers.traefik-secure.middlewares=traefik-cloudflare,traefik-auth"
        - "traefik.http.routers.traefik-secure.tls=true"
        - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
        - "traefik.http.routers.traefik-secure.service=api@internal"
        - "traefik.http.services.traefik-secure.loadbalancer.server.port=80"
    environment:
      - "CF_API_EMAIL=***CENSORED***"
      - "CF_DNS_API_TOKEN=***CENSORED***"
      - "CLOUDNS_AUTH_ID=***CENSORED***"
      - "CLOUDNS_AUTH_PASSWORD=***CENSORED***"
    ports:
      - target: 80
        published: 80
        protocol: "tcp"
        mode: "host"
      - target: 8080
        published: 8080
        protocol: "tcp"
        mode: "host"
      - target: 443
        published: 443
        protocol: "tcp"
        mode: "host"
    volumes:
      - type: bind
        source: "/etc/localtime"
        target: "/etc/localtime"
        read_only: true
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
        read_only: true
      - type: bind
        source: "***CENSORED***"
        target: "/etc/traefik"
      - type: bind
        source: "***CENSORED***"
        target: "/var/log/traefik"
    networks:
      - External-Network
```

Compose file for Portainer
```yaml
  portainer:
    image: portainer/portainer-ee:latest
    command: "--log-level=DEBUG"
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - type: bind
        source: "/etc/localtime"
        target: "/etc/localtime"
        read_only: true
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
        read_only: true
      - type: bind
        source: ***CENSORED***
        target: "/data"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.entrypoints=http"
        - "traefik.http.routers.portainer.rule=Host(`***CENSORED***`)"
        - "traefik.http.middlewares.portainer-auth.basicauth.users=***CENSORED***"
        - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.portainer-cloudflare.plugin.middleflare.includeDefault=true"
        - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
        - "traefik.http.routers.portainer-secure.entrypoints=https"
        - "traefik.http.routers.portainer-secure.rule=Host(`***CENSORED***`)"
        - "traefik.http.routers.portainer-secure.middlewares=portainer-auth"
        - "traefik.http.routers.portainer-secure.tls=true"
        - "traefik.http.routers.portainer-secure.tls.certresolver=cloudflare"
        - "traefik.http.routers.portainer-secure.service=portainer"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        - "traefik.docker.network=External-Network"
    networks:
      - External-Network
```

### If applicable, please paste the log output in DEBUG level

Don't have any logs in the docker container.
