### ISSUE TITLE
Support BearerTokenAuth - similar to BasicAuth middleeware

### ISSUE THREAD

**Issue by milesgranger** [traefik/traefik#11563]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I would like to do something like this:

```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authorization-header-middleware
spec:
  headers:
    customRequestHeaders:
      Authorization: 
       secret: my-bearer-token-auth-value-secret

```

I'm using oauth2-proxy as a middleware before this middleware to authenticate users. This is for a Meilisearch service which requires a bearer token for the Authorization header.

This seems somewhat similar to BasicAuth; I think I'm aware of some longer work-around options for it but seems this might be a useful addition to Traefik. 

As headers values are presently displayed in the dashboard, I suspect some masking would be in order, but probably easy enough to determine based on if the value is a reference to a Secret? I'm much less sensitive to this though as the dashboard itself is again limited to people who would anyway be able to get to the same Secret.

Similar to this issue which was closed w/o much activity: https://github.com/traefik/traefik/issues/9271
