### ISSUE TITLE
Not possible to configure environment field for Elastic APM via OTLP resource attribute

### ISSUE THREAD

**Issue by symsfischer** [traefik/traefik#11573]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We are trying to send tracing data via otlp / http directly (without Open Telemetry Collector) to Elastic APM and set the environment field by "resourceAttributes" in the helm chart:

```yaml
tracing:
  addInternals: false
  serviceName:
  resourceAttributes:
    "deployment.environment": "development"
  capturedRequestHeaders: []
  capturedResponseHeaders: []
  safeQueryParams: []
  sampleRate:
  otlp:
    enabled: true
    http:
      enabled: true
      endpoint: "https://xxxxxxxxxxxxxxxxxxxxxxx.apm.westeurope.azure.elastic-cloud.com:443"
      headers:
        Authorization: "Bearer REDACTED"
      tls:
        ca: ""
        cert: ""
        key: ""
        insecureSkipVerify: false
    grpc:
      enabled: false
      endpoint: ""
      insecure: false
      tls:
        ca: ""
        cert: ""
        key: ""
        insecureSkipVerify: false
```

This leads to the following (expected) label for the traefik binary / pod (so it is probably not a problem of the helm chart):

`--tracing.resourceAttributes.deployment.environment=development`

### What did you see instead?

Problem: Tracing data is ingested in Elastic BUT the service.environment = development field is not set

(Background: Elastic APM is expecting a key "deployment.environment" and maps it automatically to "service.environment":
https://www.elastic.co/guide/en/observability/8.17/apm-open-telemetry-resource-attributes.html)

Setting the resource attribute via TRAEFIK_ environment variable in the helm chart does not work either:

```yaml
env:
  - name: TRAEFIK_TRACING_RESOURCEATTRIBUTES_deployment.environment
    value: development
```

**Workaround that was successful:**

Setting the OTEL specific environment variable (which is read directly from the otel go library):
```yaml
env:
  - name: OTEL_RESOURCE_ATTRIBUTES
    value: "deployment.environment=development"
```

Maybe the problem is related to the dot in the attribute resource key name? ("deployment.environment")

### What version of Traefik are you using?

3.3.3

### What is your environment & configuration?

kubernetes 1.30.7
traefik helm-chart 34.4.0
