### ISSUE TITLE
IngressClass doesn't work in Traefik >26.1.0

### ISSUE THREAD

**Issue by forc3meat** [traefik/traefik#11576]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hola, friends.

So to the problem.
If you deploy 2 traefik (external and internal, for example).
And want to split IngressRoutes for them, you will be not able to make it work in Traefik >v26.1.0

Steps to reproduce:
1. Deploy external Traefik v26.1.0 to AWS with simple values.ext.yaml
2. Deploy internal Traefik v34.4.0 to AWS with another values.int.yaml
3. Deliver some IngressRoute with ingress.class for internal balancer

Extected result:
You can serve both internal and external traffic simply

Actual result:
Internal Traefik can't find/see required resources, balancing doesn't work

### What did you see instead?

There is no new IngressRoutes in the Traefik dashboard

### What version of Traefik are you using?

External
`helm upgrade --install --namespace=traefik --create-namespace traefik traefik/traefik --values=values.ext.yaml --version v26.1.0`
Internal
`helm upgrade --install --namespace=traefik --create-namespace traefik-internal traefik/traefik --values=values.int.yaml --version v34.4.0`

### What is your environment & configuration?

External
```yaml
---
service:
  spec:
    externalTrafficPolicy: Local
  annotations:
    "service.beta.kubernetes.io/aws-load-balancer-target-group-attributes": "preserve_client_ip.enabled=true,proxy_protocol_v2.enabled=true"
    "service.beta.kubernetes.io/aws-load-balancer-proxy-protocol": "*"
    "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
    "prometheus/scrape": "true"
    "prometheus/port": "9100"
    "prometheus/path": /metrics

additionalArguments:
  - --serverstransport.maxidleconnsperhost=-1

deployment:
  kind: DaemonSet

providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowExternalNameServices: true
```

Internal
```yaml
```yaml
service:
  spec:
    externalTrafficPolicy: Local
  annotations:
    "service.beta.kubernetes.io/aws-load-balancer-target-group-attributes": "preserve_client_ip.enabled=true,proxy_protocol_v2.enabled=true"
    "service.beta.kubernetes.io/aws-load-balancer-proxy-protocol": "*"
    "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
    "service.beta.kubernetes.io/aws-load-balancer-internal": "true"
    "prometheus/scrape": "true"
    "prometheus/port": "9100"
    "prometheus/path": /metrics

additionalArguments:
  - --serverstransport.maxidleconnsperhost=-1
  - --providers.kubernetesingress.ingressclass=traefik-internal

deployment:
  kind: DaemonSet
  labels: traefik-internal

providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowExternalNameServices: true
    ingressClass: "traefik-internal"

ingressClass:
  enabled: true
  isDefaultClass: false
  name: "traefik-internal"
```

IngressRoute with ingress.class
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-1"
    kubernetes.io/ingress.class: traefik-internal
  generation: 1
  labels:
    helmChart: admin-panel
  name: admin-panel-internal
  namespace: ops-275
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`admin-panel.ops-275.domain.private`
    services:
    - kind: Service
      name: admin-panel
      port: 80
```
