### ISSUE TITLE
additionalContexts for kubernetesCRD

### ISSUE THREAD

**Issue by 49-3** [traefik/traefik#11575]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

hi, i have sucess do use kubernetesCRD for discovery of 1 cluster, my traefik was on a vm and do reverse proxy for all service (on vm) on my stack,>
now i was trying to discover on multiple cluster.
i have try:
```
providers:
  file:
    directory: /etc/traefik/config
    watch: true
  kubernetesCRD:
    endpoint: "https://10.0.20.18:6443"
    token: "xxxxxxx"
    certAuthFilePath: "/etc/traefik/kube-ca.crt"
    namespaces:
      - cattle-system
      - kube-system
    labelSelector: "traefik-discover=true"
    allowExternalNameServices: true
#    useNodePort: true
  kubernetesCRD:
    endpoint: "https://10.0.20.18:6443"
    token: "xxxxxxx"
    certAuthFilePath: "/etc/traefik/kube-ca-runners.crt"
    namespaces:
      - kube-system
    labelSelector: "traefik-discover=true"
    allowExternalNameServices: true
#    useNodePort: true
```

and 

```
providers:
  file:
    directory: /etc/traefik/config
    watch: true
  kubernetesCRD:
    endpoint: "https://10.0.20.18:6443"
    token: "xxxxxxxx"
    certAuthFilePath: "/etc/traefik/kube-ca.crt"
    namespaces:
      - cattle-system
      - kube-system
    labelSelector: "traefik-discover=true"
    allowExternalNameServices: true
#    useNodePort: true
    additionalContexts:
      - endpoint: "https://10.0.20.21:6443"
        token: "xxxxxxxx"
        certAuthFilePath: "/etc/traefik/kube-ca-runners.crt"
        namespaces:
          - kube-system
        labelSelector: "traefik-discover=true"
        allowExternalNameServices: true
#         useNodePort: true
```

have a way to do that?
i am using traefik v3.3.4
regards.
