### ISSUE TITLE
Custom respondingTimeouts per service

### ISSUE THREAD

**Issue by Silex** [traefik/traefik#11578]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello,

I'm trying to have different respondingTimeouts per services, but through the same entry point (443).

I found this related post https://community.traefik.io/t/reuseport-is-not-working-at-all/23592 but without any answer.

This is how they solved it in nginx: https://github.com/netbirdio/netbird/issues/651

Here's what I tried:

### traefik.yml

``` yaml
entryPoints:
  https:
    address: ':443'
    ReusePort: true
  https-signal:
    address: ':443'
    ReusePort: true
    transport:
      respondingTimeouts:
        readTimeout: '1h'

certificatesResolvers:
  letsencrypt:
    acme:
      email: support@domain.com
      storage: /data/traefik/acme.json
      tlsChallenge: {}

providers:
  file:
    filename: /etc/traefik/dynamic.yml
```

### dynamic.yml

``` yaml
http:
  routers:
    netbird-dashboard:
      rule: "Host(`netbird.domain.com`)"
      service: netbird-dashboard
      entryPoints: https
      tls:
        certResolver: letsencrypt

    netbird-signal:
      rule: "Host(`netbird.domain.com`) && PathPrefix(`/signalexchange.SignalExchange/`)"
      service: netbird-signal
      entryPoints: https-signal
      tls:
        certResolver: letsencrypt

  services:
    netbird-dashboard:
      loadBalancer:
        servers:
          - url: "http://dashboard:80"

    netbird-signal:
      loadBalancer:
        servers:
          - url: "h2c://signal:10000"
```

But traefik panics so it's not working.

At the moment I use `readTimeout: '1h'` on the https entry point, so for all services, and this is not ideal.
