### ISSUE TITLE
ERR Router uses a nonexistent certificate resolver

### ISSUE THREAD

**Issue by barbriqt** [traefik/traefik#11590]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have an instance of Traefik running in Docker under Debian 12. It has access to an internal docker network that is also connected to a self-hosted ACME provider [(step-ca)](https://github.com/smallstep/certificates). I only use yaml files for configuration: traefik.yml for static and providers.yml for dynamic.

```
# docker exec -it Traefik ls -l /etc/traefik/
total 19
-rw------- 1 traefik traefik  619 mar   8 18:32 ca.pem
-rw------- 1 traefik traefik 4272 mar   8 20:59 providers.yml
-rw------- 1 traefik traefik  526 mar   8 20:59 traefik.yml
```

I tried defining certResolver in static configuration and it didn't report any errors. But when I try to use it in router's dynamic configuration it shows an error.

### What did you see instead?

```
# docker stop Traefik && sleep 3 && docker start Traefik && sleep 3 && docker logs Traefik --since 3s
2025-03-09T10:11:47Z ERR Router uses a nonexistent certificate resolver certificateResolver=step-ca routerName=portainer@file
```

### What version of Traefik are you using?

```
Version:      3.3.4
Codename:     saintnectaire
Go version:   go1.23.6
Built:        2025-02-25T10:11:01Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

traefik.yml
```yaml
...
certificateResolvers:
  step-ca:
    acme:
      email: "{my email}"
      storage: "/etc/traefik/acme.json"
      caServer: "https://step-ca:9000/acme/acme/directory"
      certificateDuration: 24
      tlsChallenge: {}
      caCertificates:
        - "/etc/traefik/ca.pem"
```

providers.yml
```yaml
...
http:
  routers:
    portainer:
      rule: "Host(`{my url}`)"
      service: "portainer"
      tls:
        certResolver: step-ca
```

I have found similar issues on the forum but they seem to be related to the acme.json file. I tried all of the suggested steps but none seemed to work.
https://community.traefik.io/t/err-router-uses-a-nonexistent-certificate-resolver/26393
https://community.traefik.io/t/a-solution-to-the-incredibly-unhelpful-the-router-uses-a-non-existent-resolver-letsencrypt-message/3859

### If applicable, please paste the log output in DEBUG level

```
2025-03-09T10:28:08Z INF github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:202 > Starting provider *traefik.Provider
2025-03-09T10:28:08Z DBG github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:203 > *traefik.Provider provider configuration config={}
2025-03-09T10:28:08Z INF github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:202 > Starting provider *acme.ChallengeTLSALPN
2025-03-09T10:28:08Z DBG github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:203 > *acme.ChallengeTLSALPN provider configuration config={}

...

2025-03-09T10:28:08Z ERR github.com/traefik/traefik/v3/cmd/traefik/traefik.go:383 > Router uses a nonexistent certificate resolver certificateResolver=step-ca routerName=portainer@file
```
