### ISSUE TITLE
Dynamic ProxyProtocol.TrustedIPs from FQDN/DNS

### ISSUE THREAD

**Issue by BornToBeRoot** [traefik/traefik#11598]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello, if you are using a dynamic created AWS NLB (or any other LB), it could make sense to only whitelist the dynamically assigned IPs for the proxy protocol. Maybe something like this:

```
## Static configuration
entryPoints:
  web:
    address: ":80"
    proxyProtocol:
      trustedFQDN:
        - "my-custom-lb.elb.eu-central-1.amazonaws.com" (will resolve to n ip addresses)
```

If the LB is not in a separate subnet / IP range, I don't think it makes sense to whitelist the entire network (vpc).

Or are there any other solutions?
