### ISSUE TITLE
Healthchecks on external IPs do not work with swarm mode enabled

### ISSUE THREAD

**Issue by 2manyvcos** [traefik/traefik#11604]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I encountered a scenario where service health checks do not work like expected.
In my example, there are three services (e.g. `192.168.1.1:7000`, `192.168.1.2:7000`, `192.168.1.3:7000`), from which one serves a website, and the other two answer with status `500` by design, because those services are part of a cluster solution and the website can only ever be served from the active leader.

I want Traefik to always point to the active service, so I configured a health check:

<details>
<summary>Example configuration</summary>

docker-compose.yml:
```yaml
services:
  traefik:
    image: traefik:v3
    ports:
      - 80:80
    networks:
      - proxy
      - proxy2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic.yml:/dynamic/dynamic.yml
    command:
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.file.directory=/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.asdefault=true"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.mytraefik.rule=Host(`traefik.example.com`)
        - traefik.http.routers.mytraefik.service=api@internal
        - traefik.http.services.mytraefik.loadbalancer.server.port=9999 # https://github.com/traefik/traefik/issues/5732

networks:
  proxy:
  proxy2:
```

dynamic.yml:
```yaml
http:
  routers:
    # Ceph UI
    ceph:
      service: ceph@file
      rule: Host(`ceph.example.com`)

  services:
    ceph:
      loadBalancer:
        servers:
          - url: http://192.168.1.1:7000
          - url: http://192.168.1.2:7000
          - url: http://192.168.1.3:7000
        healthCheck:
          path: /
          interval: 10s
          timeout: 3s
          status: 200
```

</details>

But with this configuration I noticed a strange behavior:
First, all of the three services were displayed as healthy for a few seconds.
Then two of the three appeared as down (like expected).
But after around 10 to 30 seconds all appeared as healthy again for another few seconds.
This process repeated forever.

After a lot of testing I noticed that this behavior only occurs when the `swarm` provider is enabled.
I tested some more in an isolated environment and was able to reproduce the behavior with some Docker containers:

<details>
<summary>Test configuration</summary>

docker-compose.yml:
```yaml
services:
  traefik:
    image: traefik:v3
    ports:
      - 80:80
    networks:
      - proxy
      - proxy2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic.yml:/dynamic/dynamic.yml
    command:
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.file.directory=/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.asdefault=true"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.mytraefik.rule=Host(`traefik.example.com`)
        - traefik.http.routers.mytraefik.service=api@internal
        - traefik.http.services.mytraefik.loadbalancer.server.port=9999 # https://github.com/traefik/traefik/issues/5732

  whoami:
    image: traefik/whoami:v1.10
    networks:
      - proxy
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.mywhoami.rule=Host(`whoami.example.com`)
        - traefik.http.services.mywhoami.loadbalancer.server.port=80

  service_ok_1:
    image: hashicorp/http-echo
    command: ["-text=OK1", "-status-code=200"]
    networks:
      - proxy

  service_ok_2:
    image: hashicorp/http-echo
    command: ["-text=OK2", "-status-code=200"]
    networks:
      - proxy

  service_fail_1:
    image: hashicorp/http-echo
    command: ["-text=FAIL1", "-status-code=500"]
    networks:
      - proxy

  service_fail_2:
    image: hashicorp/http-echo
    command: ["-text=FAIL2", "-status-code=500"]
    networks:
      - proxy

networks:
  proxy:
  proxy2:
```

dynamic.yml:
```yaml
http:
  routers:
    healthy:
      service: healthy
      rule: Host(`healthy.example.com`)

  services:
    healthy:
      loadBalancer:
        servers:
          - url: http://service_ok_1:5678
          - url: http://service_ok_2:5678
          - url: http://service_fail_1:5678
          - url: http://service_fail_2:5678
        healthCheck:
          path: /
          interval: 10s
          timeout: 3s
          status: 200
```

</details>

It looks like with the configuration above the issue occurs when multiple Docker networks are involved.
When specifying a default network (with `--providers.swarm.network=proxy` in this case), the health check works as expected.

Some months ago I noticed a similar issue where Docker services, which were exposed to Traefik via labels, were not working correctly when they did not have the `docker.swarm.network` label set, so I think this two cases might be related.

However, with the information I collected through my tests I was able to find a hacky workaround for my original issue:
When setting the default swarm network to `ingress` (`--providers.swarm.network=ingress`), the issue disappears.

I suspect that something is wrong with how Traefik selects the network to reach the services for healthchecks when the `swarm` provider is enabled, maybe this even also affects other situations (like with the `docker.swarm.network` issue described above).
In my case, it shouldn't even have made a difference as the IPs I am trying to reach are not even on Docker hosts, but it does nonetheless.

I did not test if this issue is limited only to the `swarm` provider, so I cannot state if it may be occurring with the `docker` provider as well.

### What did you see instead?

I expected only one of the three services to be displayed as healthy continuously, but the following process repeated forever instead:

First, all of the three services were displayed as healthy for a few seconds.
Then two of the three appeared as down (like expected).
But after around 10 to 30 seconds all appeared as healthy again for another few seconds.

### What version of Traefik are you using?

```
Version:      3.3.4
Codename:     saintnectaire
Go version:   go1.23.6
Built:        2025-02-25T10:11:00Z
OS/Arch:      linux/arm64
```

... as well as ...

```
Version:      3.3.4
Codename:     saintnectaire
Go version:   go1.23.6
Built:        2025-02-25T10:11:01Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

See `What did you do?`, there are multiple configurations related.
