### ISSUE TITLE
SSL Labs Server Test reports no server preference for curves although configured

### ISSUE THREAD

**Issue by smares** [traefik/traefik#11613]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Given the TLS configuration below with preferred curves, I was expecting the SSL Server Test to report that the server has curve preferences.

### What did you see instead?

When no TLS options are specified for a router and `default` is being used, the SSL Server Test displays:

![Image](https://github.com/user-attachments/assets/69eaa42f-a8c6-4638-aaa4-0c6ff6e1c7d2)

If I change a router to use `modern`, the test does report that the server has curve preferences.

### What version of Traefik are you using?

```
Version:      3.3.4
Codename:     saintnectaire
Go version:   go1.23.6
Built:        2025-02-25T10:11:01Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
tls:
  options:
    default:
      minVersion: VersionTLS12
      curvePreferences:
        - X25519
        - CurveP256
        - CurveP384
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      sniStrict: true

    modern:
      minVersion: VersionTLS13
      curvePreferences:
        - X25519
        - CurveP256
        - CurveP384
      sniStrict: true
```
