### ISSUE TITLE
Using an anchored regex in an Ingress

### ISSUE THREAD

**Issue by SpecLad** [traefik/traefik#11618]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Let's say I want to define a router that matches paths `/a/`, `/aa/`, `/aaa/`, etc. With Docker, it's pretty easy:

```yaml
traefik.http.routers.xxx.rule: PathRegexp(`^/a+/$`)
```

However, there doesn't seem to be a way to do this via a Kubernetes Ingress. If you try to define an Ingress as follows:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
  annotations:
    traefik.ingress.kubernetes.io/router.pathmatcher: PathRegexp
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: ^/a+/$
        pathType: ImplementationSpecific
        backend:
          service:
            name: test
            port:
              number: 80
```

then Kubernetes will reject it with the following message:

```
The Ingress "test" is invalid: spec.rules[0].http.paths[0].path: Invalid value: "^/a+/$": must be an absolute path
```

It would be useful if there was some way to work around this. Some possibilities are:

* Add a new path matcher type that always adds `^...$` around the regex.
* Add an ingress annotation that does the same.
* Add an ingress annotation that strips the leading `/` from all paths (so that the above example could be written as `/^/a+/$`).
