### ISSUE TITLE
Supporting Anonymous Middleware / Parameterized Middleware

### ISSUE THREAD

**Issue by debuggedme** [traefik/traefik#11626]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Current middleware requires predefined configurations and explicit references in routes. For example:

```yaml
http:
  middlewares:
    ratelimit-100:
      plugin:
        ratelimit:
          qps: 100
    ratelimit-200:
      plugin:
        ratelimit:
          qps: 200
    ... (more)
```

For highly customizable middleware like rate limiting, defining 100 named middleware instances for 100 different QPS tiers is overly complex.

Proposed Solution: Anonymous Middleware or Parameterized Middleware
If anonymous middleware or direct parameter passing were supported, configuration could be simplified:

```yaml
http:
  routers:
    my-router:
      rule: "Path(`/foo`)"
      middlewares:
        - plugin:
            ratelimit:
              qps: 100  # Inline configuration without predefined names
```

Alternative Approach: Reading Parameters from Ingress Annotations
In a Kubernetes cluster, could middleware plugins read custom fields from Ingress annotations? For example:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  annotations:
    traefik.ingress.kubernetes.io/custom.ratelimit.qps: "100"  # Custom parameter
```

```go

func (a *Demo) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
        
        qps := a.GetAnnotation("ratelimit.qps")
	// ... use this qps
        a.next.ServeHTTP(rw, req)
}
```

However, this approach is not documented in the plugin’s official guidelines, and its feasibility is unclear.
