### ISSUE TITLE
NOMAD ignore TAG

### ISSUE THREAD

**Issue by jaimesalvador** [traefik/traefik#11621]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

In the service TAGs, I use "

```
tags = [
  "traefik.http.services.my-service.loadbalancer.serversTransport=mytransport",
  "traefik.http.serverstransports.mytransport.insecureSkipVerify=true"
]
```

but the TAG that configures 'mytransport' is ignored by traefik-nomad

### What did you see instead?

the TAG that configures 'mytransport' is ignored by traefik-nomad

### What version of Traefik are you using?

```
traefik -config='traefik.yml'
```

### What is your environment & configuration?

```yaml
api:
  insecure: true
  dashboard: true

serversTransport:
  insecureSkipVerify: true

log:
  level: DEBUG
  filePath: d:/servidores/nomad/traefik.log

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  traefik:
    address: ":8080"
```

Add more configuration information here.
