### ISSUE TITLE
Intermittent WASM tcp network failures

### ISSUE THREAD

**Issue by kellen-miller** [traefik/traefik#11629]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

When using a WASM plugin in Traefik to publish HTTP request/responses to Kakfa, Kafka clients to not be able to communicate correctly with Kafka servers. I initially opened an issue on the franz-go repo: https://github.com/twmb/franz-go/issues/938

But after further investigation, I am seeing the same problem when using the https://github.com/IBM/sarama client as well, leading me to believe there is an underlying issue with how Traefik and it's handling of wasm plugins.

### What did you see instead?

Intermittent failures

### What version of Traefik are you using?

`v3.3.4`

### What is your environment & configuration?

static
```yaml
log:
  level: "DEBUG"

experimental:
  localPlugins:
    pubPlugin:
      moduleName: publisher-plugin

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: :80

providers:
  file:
    directory: "/etc/traefik"
```

dynamic
```
http:
  routers:
    whoami-http:
      rule: "Host(`whoami.docker.localhost`)"
      entryPoints:
        - web
      middlewares:
        - pub-middleware
      service: "svc-whoami-http"

  services:
    svc-whoami-http:
      loadBalancer:
        servers:
          - url: "http://whoami:80"

  middlewares:
    pub-middleware:
      plugin:
        pubPlugin:
          dnsHost: "127.0.0.11" # Docker's embedded DNS resolver
          username: "user"
          password: "itsasecret"
          brokers:
            - "broker1:9092"
          produceTimeout: "10s"
          recordRetries: "3"
          updateMetadataBeforeProduce: "false"
          forceFlushAfterProduce: "false"
```

### If applicable, please paste the log output in DEBUG level

I created a [sample repository](https://github.com/kellen-miller/not-leader-for-partition-example) with detailed reproduction steps and logs.
