### ISSUE TITLE
Health checking not correctly routing traffic away from unhealthy endpoints - Kubernetescrd

### ISSUE THREAD

**Issue by Tyrone-W** [traefik/traefik#11622]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm experiencing an issue with Traefik's health checking feature.

I've configured healthchecking on an ingressroute and two traefikservices that reference a single externalname kubernetes service each, one of which intentionally returning a 503.

### What did you see instead?

Logs show one of the two services is returning a 503 which causes its status to be set as DOWN, as WRR is in use traffic is either sent to the healthy service(which returns a 200) or the now unhealthy service(which returns a 503) with the content "no available server"  response to the client

I would expect traffic is only sent to the one service marked as UP

### What version of Traefik are you using?

v3.3.2

### What is your environment & configuration?

```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute
spec:
  routes:
  - kind: Rule
    match: Host(`example.com`)
    services:
    - kind: TraefikService
      name: traefik-service-01
      healthCheck: 
        status: 200
        port: 443
        interval: 5s
    - kind: TraefikService
      name: traefik-service-02
      healthCheck: 
        status: 200
        port: 443
        interval: 5s
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: traefik-service-01
spec:
  weighted:
    services:
    - kind: Service
      name: service-az1
      port: 443
      scheme: https
      serversTransport: ca
      healthCheck: 
        status: 200
        port: 443
        interval: 5s
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: traefik-service-02
spec:
  weighted:
    services:
    - kind: Service
      name: service-az2
      passHostHeader: false
      port: 443
      scheme: https
      serversTransport: ca
      healthCheck: 
        status: 200
        port: 443
        interval: 5s
---
apiVersion: v1
kind: Service
metadata:
  name: service-az1
spec:
  externalName: az1.example.com
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: ExternalName
---
apiVersion: v1
kind: Service
metadata:
  name: service-az2
spec:
  externalName: az2.example.com
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: ExternalName
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: ca
spec:
  rootCAsSecrets:
  - ca
```

* OKD cluster (also tested in a KIND cluster)

### If applicable, please paste the log output in DEBUG level

```
WRN github.com/traefik/traefik/v3/pkg/healthcheck/healthcheck.go:125 > Health check failed. error="received error status code: 503 expected status code: 200" serviceName=default-service-az2-443@kubernetescrd targetURL=https://az2.example.com:443
DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:140 > Setting status of 6ad9dc8f8d0c83f9 to DOWN serviceName=default-service-az2-443@kubernetescrd
DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:157 > Still DOWN, no need to propagate serviceName=default-service-az2-443@kubernetescrd
DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:207 > Service selected by WRR: default-traefik-service-02
DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:207 > Service selected by WRR: default-service-az2-443
IP - - [] "GET / HTTP/2.0" 503 20 "-" "Client" 262346 "websecure-default-service-az2-a1d1979066eab82ba321@kubernetescrd" "-" 0ms

```
