### ISSUE TITLE
Error starting Traefik with IPVLAN L3 network

### ISSUE THREAD

**Issue by ar0311** [traefik/traefik#11631]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

My Traefik compose file works fine with a bridge network - when I am testing with an ipvlan l3 type network, traefik fails to start up properly.

### What did you see instead?

In the logs I see a single line:

2025-03-25T02:48:27Z ERR error="service \"traefik3-traefik\" error: port is missing" container=traefik3-traefik-abaa849fb18056e1a6e18a1d3ac0995dd4b1bf0459c062c1dd5673dcb3001e9d providerName=docker

### What version of Traefik are you using?

I'm using Traefik 3.3.4

### What is your environment & configuration?

```yaml
services:
  traefik3:
    image: traefik:3.3.4
    restart: always
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.dashboard.address=:9090"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--serverstransport.insecureskipverify"
      - "--certificatesresolvers.production.acme.email={my-email}"
      - "--certificatesresolvers.production.acme.storage=/etc/traefik/acme/acme_production.json"
      - "--certificatesresolvers.production.acme.httpchallenge.entrypoint=web"

    ports:
      - 80:80
      - 443:443
      - 9090:9090

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker/traefik/acme:/etc/traefik/acme
    container_name: traefik
    networks:
      default:
        ipv6_address: {my-ipv6-address}

    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.auth.basicauth.users={name}:{password-hash}"
      - "traefik.http.routers.dashboard.entrypoints=dashboard"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.routers.dashboard.rule=Host(`{my-fqdn}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=production"
networks:
  default:
   driver: ipvlan
   enable_ipv6: true
   driver_opts:
      ipvlan_mode: l3
      parent: ens18
   ipam:
      config:
        - subnet: {my-ipv6-subnet}

```

Add more configuration information here.
