### ISSUE TITLE
Traefik spamming warning: No domain found in rule PathPrefix(`/dashboard`) || PathPrefix(`/api`)

### ISSUE THREAD

**Issue by fcarucci** [traefik/traefik#11630]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Running traefik 3.3.4 on kubernetes cluster with dashboard enabled.

### What did you see instead?

This warning is being spammed:
> No domain found in rule PathPrefix(`/dashboard`) || PathPrefix(`/api`), the TLS options applied for this router will depend on the SNI of each request entryPointName=websecure routerName=traefik-traefik-dashboard-d012b7f875133eeab4e5@kubernetescrd

### What version of Traefik are you using?

3.3.4

### What is your environment & configuration?

```yaml
image: #
  registry: docker.io
  repository: traefik
  tag: 3.3.4
  pullPolicy: IfNotPresent

deployment:
  replicas: 3

api:
  enabled: true
  dashboard: true
  insecure: true # Allow insecure access (for testing only; use secure methods in production)
  # debug: true

additionalArguments:
  - --global.checknewversion
  # - --log.level=DEBUG

# Expose the dashboard via an IngressRoute
ingressRoute:
  dashboard:
    enabled: true
    match: "Host(`traefik.example.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
    entryPoints:
      - websecure

env:
  - name: TZ
    value: "America/Los_Angeles"

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    http3:
      enabled: true

tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard-k-carucci-studio-tls
      namespace: traefik

providers:
  kubernetesIngress:
    allowExternalNameServices: true
  kubernetesCRD:
    allowExternalNameServices: true
  kubernetesGateway:
    enabled: true

gateway:
  namespacePolicy: All

service:
  enabled: true
  type: LoadBalancer
  annotations:
    metallb.io/address-pool: default-pool
  loadBalancerIP: 10.20.0.160

nodeSelector:
  node-role.kubernetes.io/worker: "true"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: In
              values:
                - "true"
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
            - key: zima
              operator: NotIn
              values:
                - "true"
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - traefik
        topologyKey: "kubernetes.io/hostname"

experimental:
  abortOnPluginFailure: false
  fastProxy:
    enabled: true
    debug: true
  kubernetesGateway:
    enabled: true
  plugins: {}

```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

```
2025-03-24T17:41:11-07:00 INF ExternalName service loading is enabled, please ensure that this is expected (see AllowExternalNameServices option) providerName=kubernetescrd
2025-03-24T17:41:11-07:00 INF Starting provider *gateway.Provider
2025-03-24T17:41:11-07:00 INF Starting provider *acme.ChallengeTLSALPN
2025-03-24T17:41:12-07:00 WRN No domain found in rule PathPrefix(`/dashboard`) || PathPrefix(`/api`), the TLS options applied for this router will depend on the SNI of each request entryPointName=websecure routerName=traefik-traefik-dashboard-d012b7f875133eeab4e5@kubernetescrd


```
