### ISSUE TITLE
Timeout when attempting to provision certificates using slow CA server and http-01 challenge

### ISSUE THREAD

**Issue by tkw1536** [traefik/traefik#11636]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We attempted to provision https certificates for several domains using the ACME provider and specifically the 'http-01' challenge.
We used an (ACME) CA Server internal to our institution, which in turn internally communicates with an upstream CA to actually issue certificates. 
The ACME server seems to exceed the default limits set for the ACME client built into traefik (see below for more details). 

### What did you see instead?

At first several certificates were provisioned successfully.
However soon after certain domains (which had no specific pattern to them) received "time limit exceeded" errors during provisioning like the following:

```
2025-03-25T21:06:40Z ERR Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [subdomain.example.com]: error: one or more domains had a problem:\nsubdomain.example.com: certificate: time limit exceeded" ACME CA=https://acme.internal.example.com/ acmeCA=https://acme.internal.example.com/ domains=["subdomain.example.com"] providerName=institution.acme routerName=https_subdomain.example.com@file rule=Host(`subdomain.example.com`)
```

(We've redacted the actual domains used; here "subdomain.example.com" is the domain that started failing and "https://acme.internal.example.com" is our internal ca server).

We also checked with the internal team running the ACME server. 
They informed us that a certificate for "subdomain.example.com" was indeed issued, but took about 42 seconds to be returned to the client. 
At that point traefik had already timed out, failing after 30 seconds. 

We have investigated and determined that this timeout is not adjustable. 
It is hard coded to 30 seconds in https://github.com/traefik/traefik/blob/v3.3/pkg/provider/acme/provider.go#L377. 
We also found a similar but slightly different issue in https://github.com/traefik/traefik/issues/11483 (they are using the `tls-01` challenge as opposed to the `http-01` challenge). 

We believe that this issue might be resolved by making the timeout for traefiks ACME client configurable. 
We are currently preparing a pull request to enable exactly this by adding a new static configuration option.
We will submit it shortly, and expect that our PR will address #11483, this issue, and also supersede the existing PR https://github.com/traefik/traefik/pull/11484. 

### What version of Traefik are you using?

```
/ # traefik version
Version:      3.3.4
Codename:     saintnectaire
Go version:   go1.23.6
Built:        2025-02-25T10:11:01Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

Relevant parts of the static configuration:

```yaml
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  institution:
    acme:
      caServer: https://acme.internal.example.com
      httpChallenge:
        entryPoint: web
      storage: acme.json
```

Relevant parts of the dynamic configuration:

```yaml
http:
  routers:
    https_subdomain.example.com:
      rule: "Host(`subdomain.example.com`)"
      entryPoints: ["websecure"]
      service: "proxy_https_subdomain.example.com"
      tls:
        certResolver: institution
```
