### ISSUE TITLE
Explicit docker network and network_mode (incorrect) warning

### ISSUE THREAD

**Issue by Rycochet** [traefik/traefik#11645]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

## Context

I am using multiple docker compose services including a vpn, which several of the services use for their networking via `network_mode: service:vpn`.

I am setting a specific named network to be used by traefik (via `--providers.docker.network=<network>`), which is being routed through correctly for internal routing by all services (including all the services that use the vpn).

## Problem

The issue is that `network_mode:` prevents you from adding `networks:`, so Traefik will not be able to find any connected networks directly and warns that the networks that it can access are wrong / inaccessible (as they are not / cannot be directly connected in the config).

## Potential solutions

1. Follow the `network_mode` to discover the right service / container and check against that.
    - As `network_mode` may have [multiple values](https://docs.docker.com/reference/compose-file/services/#network_mode) this may also note that a container has no network access, or is on the host directly where traefik may not have access.
    - This affects [startup order](https://docs.docker.com/compose/how-tos/startup-order/) for `service:...`, so the linked name should already exist and be accessible (even if unhealthy) - this isn't true for `container:...` however.
1. Look at an explicit `traefik.http.routers.<name>=<service>` value and follow that.
    - In this case by *not* doing that it may believe it can route to a service that does not actually have the right network access as the actual service has access, but the service it is being pointed to might not.
    - This has no implicit order, so may refer to a service which is not up (yet) - so may cause future problems / reports if edge cases aren't taken into account.

### What did you see instead?

This is the specific warning that is seen:

```
WRN Could not find network named "<network>" for container "/<name>". Maybe you're missing the project's prefix in the label? 
```

### What version of Traefik are you using?

```
Version:      3.3.4
Codename:     saintnectaire
Go version:   go1.23.6
Built:        2025-02-25T10:11:01Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

The actual config is too large to post, but this shows the minimum *changes* needed to reproduce the (incorrect) warning:

```yaml
networks:
  random_name:
    name: random_name # so no project prefix needed

services:
  traefik:
    # ... add image and setup etc
    command:
      - "--providers.docker.network=random_name" # match the network name above
    networks:
      - random_name # and make sure we're actually connected to it

  whoami:
    # ... add image and setup etc
    network_mode: service:traefik # merge with the traefik network
    labels:
      - "traefik.http.routers.whoami=traefik@docker" # makes no difference but I like to be explicit
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
```
