### ISSUE TITLE
Using HostRegexp subdomain capture in loadBalancer.servers.url results in 404

### ISSUE THREAD

**Issue by ejohb** [traefik/traefik#11646]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

When visiting an address matching the host pattern, like `https://moon.gex.example.com` I expected to see the content served by `http://moon.lan`.

### What did you see instead?

I got saw `404 page not found` in the browser/`curl`.

Note: If I replace `- url: "http://$${1}.lan"` with `- url: "http://moon.lan"` in the config below, it _does_ work for that one host. It's only when I try to generalise using the subdomain capture group that it fails.

### What version of Traefik are you using?

`docker.io/library/traefik:v3.3.4`

### What is your environment & configuration?

```yaml
http:
  routers:
    gex-router:
      rule: "HostRegexp(`^(.+)\\.gex\\.example\\.com$`)"
      entryPoints:
        - websecure
      service: gex-service
      tls:
        certResolver: cloudflare
        domains:
          - main: "*.gex.example.com"
  services:
    gex-service:
      loadBalancer:
        servers:
          - url: "http://${1}.lan"
```

### If applicable, please paste the log output in DEBUG level

```
2025-03-27T19:16:05Z ERR github.com/traefik/traefik/v3/pkg/server/router/router.go:136 > error="error parsing server URL http://${1}.lan: parse \"http://${1}.lan\": invalid character \"{\" in host name" entryPointName=websecure routerName=gex-router@file
```
