### ISSUE TITLE
Dashboard Does Not Load, Results in White Page

### ISSUE THREAD

**Issue by ejbolt** [traefik/traefik#11667]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

**I wish to immediately clarify that I did find relevant forum posts and issues, however they were closed as fixed.**

I'm setting up IT-tools proxied behind traefik. I'm also setting up the dashboard to be over SSL. I can see the IT-tools container's page and all works as expected.

### What did you see instead?

When exposing my dashboard over SSL, I've run into this issue when using my default browsers: Brave and Vivaldi. I've also tested in Edge, Firefox, and Chrome, and only Chrome will display the dashboard. I've noticed [this was an issue prior](https://github.com/traefik/traefik/issues/10516) and suspect a regression has been introduced. This issue occurs when changing the dashboard to be the root of the domain too (just running traefik without the it-tools container). I did have a mix of a traefik.yml file and docker labels, but I moved everything to docker labels when I saw a forum post on the Traefik site saying those cannot/should not be mixed.

### What version of Traefik are you using?

This issue occurred across v3.3.3, v3.3.4, and v3.3.5. I did not test earlier versions.

### What is your environment & configuration?

Docker Compose:

```yaml
services:
  traefik:
    image: "traefik:${TRAEFIK_VERSION}"
    container_name: traefik
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.file.filename=/traefik/tls.yml"
      - "--providers.file.watch=true"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.basePath=/traefik"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http3"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.http3"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./configs/traefik/tls.yml:/traefik/tls.yml:ro"  # Dynamic config
      - "./certs:/certs:ro"                              # Your custom certs
    networks:
      - web
    labels:
      # Enable Traefik for this container
      - "traefik.enable=true"

      # --------------------------------------------------
      # 1) Dashboard Router at /traefik
      # --------------------------------------------------
      - "traefik.http.routers.dashboard.rule=Host(`${HOST}.${DOMAIN}`) && PathPrefix(`/traefik`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.priority=20"

      # --------------------------------------------------
      # 2) Global HTTP→HTTPS Redirect
      # --------------------------------------------------
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  it-tools:
    image: ghcr.io/sharevb/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ittools.rule=Host(`${HOST}.${DOMAIN}`)"
      - "traefik.http.routers.ittools.entrypoints=websecure"
      - "traefik.http.routers.ittools.tls=true"
      - "traefik.http.routers.ittools.priority=10"
    networks:
      - web

networks:
  web:
    driver: bridge
```

tls.yml

```yaml
## tls.yml
tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/tls.crt"
        keyFile: "/certs/tls.key"

```

.env file:

```env
# .env
TRAEFIK_VERSION=v3.3.5
HOST=it-tools
DOMAIN=mydomain.org
EMAIL=your-email@example.com

```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

Browser Network Console Logs:

```text
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
tesseract.js-c68ff542.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
unicode-9d1fc898.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
monaco-editor-fd1f5b64.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
manifest.webmanifest:1 Manifest: Line: 1, column: 1, Syntax error.
```

Traefik logs:

```text
traefik  | 2025-04-04T03:22:47Z INF github.com/traefik/traefik/v3/cmd/traefik/traefik.go:106 > Traefik version 3.3.5 built on 2025-03-31T08:45:53Z version=3.3.5
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/cmd/traefik/traefik.go:113 > Static configuration loaded [json] staticConfiguration={"api":{"basePath":"/traefik","dashboard":true},"entryPoints":{"web":{"address":":80","forwardedHeaders":{},"http":{"maxHeaderBytes":1048576,"redirections":{"entryPoint":{"permanent":true,"priority":9223372036854775806,"scheme":"https","to":"websecure"}}},"http2":{"maxConcurrentStreams":250},"http3":{},"transport":{"lifeCycle":{"graceTimeOut":"10s"},"respondingTimeouts":{"idleTimeout":"3m0s","readTimeout":"1m0s"}},"udp":{"timeout":"3s"}},"websecure":{"address":":443","forwardedHeaders":{},"http":{"maxHeaderBytes":1048576},"http2":{"maxConcurrentStreams":250},"http3":{},"transport":{"lifeCycle":{"graceTimeOut":"10s"},"respondingTimeouts":{"idleTimeout":"3m0s","readTimeout":"1m0s"}},"udp":{"timeout":"3s"}}},"global":{"checkNewVersion":true},"log":{"format":"common","level":"DEBUG"},"providers":{"docker":{"defaultRule":"Host(`{{ normalize .Name }}`)","endpoint":"unix:///var/run/docker.sock","watch":true},"file":{"filename":"/traefik/tls.yml","watch":true},"providersThrottleDuration":"2s"},"serversTransport":{"maxIdleConnsPerHost":200},"tcpServersTransport":{"dialKeepAlive":"15s","dialTimeout":"30s"}}
traefik  | 2025-04-04T03:22:47Z INF github.com/traefik/traefik/v3/cmd/traefik/traefik.go:632 >
traefik  | Stats collection is disabled.
traefik  | Help us improve Traefik by turning this feature on :)
traefik  | More details on: https://doc.traefik.io/traefik/contributing/data-collection/
traefik  |
traefik  | 2025-04-04T03:22:47Z INF github.com/traefik/traefik/v3/pkg/server/configurationwatcher.go:73 > Starting provider aggregator *aggregator.ProviderAggregator
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:231 > Starting TCP Server entryPointName=websecure
traefik  | 2025-04-04T03:22:47Z DBG log/log.go:245 > 2025/04/04 03:22:47 sys_conn.go:36: failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:231 > Starting TCP Server entryPointName=web
traefik  | 2025-04-04T03:22:47Z INF github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:202 > Starting provider *file.Provider
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:203 > *file.Provider provider configuration config={"filename":"/traefik/tls.yml","watch":true}
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/provider/file/file.go:122 > add watcher on: /traefik
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/provider/file/file.go:122 > add watcher on: /traefik/tls.yml
traefik  | 2025-04-04T03:22:47Z INF github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:202 > Starting provider *traefik.Provider
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:203 > *traefik.Provider provider configuration config={}
traefik  | 2025-04-04T03:22:47Z INF github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:202 > Starting provider *docker.Provider
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:203 > *docker.Provider provider configuration config={"defaultRule":"Host(`{{ normalize .Name }}`)","endpoint":"unix:///var/run/docker.sock","watch":true}
traefik  | 2025-04-04T03:22:47Z INF github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:202 > Starting provider *acme.ChallengeTLSALPN
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:203 > *acme.ChallengeTLSALPN provider configuration config={}
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/server/configurationwatcher.go:227 > Configuration received config={"http":{"middlewares":{"redirect-web-to-websecure":{"redirectScheme":{"permanent":true,"port":"443","scheme":"https"}}},"routers":{"web-to-websecure":{"entryPoints":["web"],"middlewares":["redirect-web-to-websecure"],"priority":9223372036854775806,"rule":"HostRegexp(`^.+$`)","ruleSyntax":"v3","service":"noop@internal"}},"serversTransports":{"default":{"maxIdleConnsPerHost":200}},"services":{"api":{},"dashboard":{},"noop":{}}},"tcp":{"serversTransports":{"default":{"dialKeepAlive":"15s","dialTimeout":"30s"}}},"tls":{},"udp":{}} providerName=internal
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/server/configurationwatcher.go:227 > Configuration received config={"http":{},"tcp":{},"tls":{"stores":{"default":{}}},"udp":{}} providerName=file
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/provider/docker/pdocker.go:90 > Provider connection established with docker 28.0.4 (API 1.48) providerName=docker
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/server/configurationwatcher.go:227 > Configuration received config={"http":{"middlewares":{"redirect-to-https":{"redirectScheme":{"scheme":"https"}}},"routers":{"dashboard":{"entryPoints":["websecure"],"priority":20,"rule":"Host(`it-tools.<domain>`) && PathPrefix(`/traefik`)","service":"api@internal","tls":{}},"http-catchall":{"entryPoints":["web"],"middlewares":["redirect-to-https"],"rule":"hostregexp(`{host:.+}`)","service":"traefik-it-tools"},"ittools":{"entryPoints":["websecure"],"priority":10,"rule":"Host(`it-tools.<domain>`)","service":"it-tools-it-tools","tls":{}}},"services":{"it-tools-it-tools":{"loadBalancer":{"passHostHeader":true,"responseForwarding":{"flushInterval":"100ms"},"servers":[{"url":"http://172.18.0.2:8080"}]}},"traefik-it-tools":{"loadBalancer":{"passHostHeader":true,"responseForwarding":{"flushInterval":"100ms"},"servers":[{"url":"http://172.18.0.3:80"}]}}}},"tcp":{},"tls":{},"udp":{}} providerName=docker
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:321 > No default certificate, fallback to the internal generated certificate tlsStoreName=default
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/middlewares/redirect/redirect_scheme.go:29 > Creating middleware entryPointName=web middlewareName=redirect-web-to-websecure@internal middlewareType=RedirectScheme routerName=web-to-websecure@internal
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/middlewares/redirect/redirect_scheme.go:30 > Setting up redirection to https 443 entryPointName=web middlewareName=redirect-web-to-websecure@internal middlewareType=RedirectScheme routerName=web-to-websecure@internal
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/middlewares/recovery/recovery.go:25 > Creating middleware entryPointName=web middlewareName=traefik-internal-recovery middlewareType=Recovery
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/server/service/service.go:312 > Creating load-balancer entryPointName=web routerName=http-catchall@docker serviceName=traefik-it-tools@docker
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/server/service/service.go:344 > Creating server URL=http://172.18.0.3:80 entryPointName=web routerName=http-catchall@docker serverIndex=0 serviceName=traefik-it-tools@docker
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/middlewares/redirect/redirect_scheme.go:29 > Creating middleware entryPointName=web middlewareName=redirect-to-https@docker middlewareType=RedirectScheme routerName=http-catchall@docker
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/middlewares/redirect/redirect_scheme.go:30 > Setting up redirection to https  entryPointName=web middlewareName=redirect-to-https@docker middlewareType=RedirectScheme routerName=http-catchall@docker
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/middlewares/redirect/redirect_scheme.go:29 > Creating middleware entryPointName=web middlewareName=redirect-web-to-websecure@internal middlewareType=RedirectScheme routerName=web-to-websecure@internal
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/middlewares/redirect/redirect_scheme.go:30 > Setting up redirection to https 443 entryPointName=web middlewareName=redirect-web-to-websecure@internal middlewareType=RedirectScheme routerName=web-to-websecure@internal
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/middlewares/recovery/recovery.go:25 > Creating middleware entryPointName=web middlewareName=traefik-internal-recovery middlewareType=Recovery
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/server/service/service.go:312 > Creating load-balancer entryPointName=websecure routerName=ittools@docker serviceName=it-tools-it-tools@docker
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/server/service/service.go:344 > Creating server URL=http://172.18.0.2:8080 entryPointName=websecure routerName=ittools@docker serverIndex=0 serviceName=it-tools-it-tools@docker
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/middlewares/recovery/recovery.go:25 > Creating middleware entryPointName=websecure middlewareName=traefik-internal-recovery middlewareType=Recovery
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/server/router/tcp/manager.go:237 > Adding route for it-tools.<domain> with TLS options default entryPointName=websecure
traefik  | 2025-04-04T03:22:47Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "it-tools.<domain>"
traefik  | 2025-04-04T03:23:19Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "it-tools.<domain>"
traefik  | 2025-04-04T03:23:19Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "it-tools.<domain>"
traefik  | 2025-04-04T03:23:22Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-04T03:28:03Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "it-tools.<domain>"
traefik  | 2025-04-04T03:28:05Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "it-tools.<domain>"
traefik  | 2025-04-04T18:28:52Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "it-tools.<domain>"
traefik  | 2025-04-04T18:28:52Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "it-tools.<domain>"
traefik  | 2025-04-04T18:28:52Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "it-tools.<domain>"
traefik  | 2025-04-04T18:28:53Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-04T18:28:53Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-04T18:28:54Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-04T18:28:54Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "it-tools.<domain>"
traefik  | 2025-04-04T18:28:54Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-04T18:28:54Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-04T18:28:54Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-04T18:28:54Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-04T18:28:54Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-04T18:28:54Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-04T18:28:54Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-04T18:28:54Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-04T18:28:56Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "it-tools.<domain>"
traefik  | 2025-04-04T18:28:56Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "it-tools.<domain>"
traefik  | 2025-04-04T18:28:58Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-04T18:28:58Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-05T15:02:43Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "it-tools.<domain>"
traefik  | 2025-04-05T15:02:43Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-05T16:43:35Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "it-tools.<domain>"
traefik  | 2025-04-05T16:43:35Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-05T16:43:35Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-05T16:43:35Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-05T16:43:35Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-05T16:43:35Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-05T16:43:35Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-05T16:43:35Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-05T16:43:35Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-05T16:43:35Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "it-tools.<domain>"
traefik  | 2025-04-05T16:43:35Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-05T16:43:35Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-05T16:43:35Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-05T16:43:37Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-05T16:43:37Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-05T16:43:38Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-05T18:11:52Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "it-tools.<domain>"
traefik  | 2025-04-05T18:11:52Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "it-tools.<domain>"
traefik  | 2025-04-05T18:11:54Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
traefik  | 2025-04-05T18:11:54Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.18.0.2:8080
```
