### ISSUE TITLE
Kubernetes Gateway API reference install docs refer to nonexisting option - publishedService

### ISSUE THREAD

**Issue by romantomjak** [traefik/traefik#11662]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I was following the guide at https://doc.traefik.io/traefik/reference/install-configuration/providers/kubernetes/kubernetes-gateway/ to configure a kubernetes service from which to copy status addresses, e.g.

```sh
providers.kubernetesGateway.statusAddress.publishedService
```

### What did you see instead?

I received an error that publishedService does not exist on statusaddress.

### What version of Traefik are you using?

Version:      3.3.5
Codename:     saintnectaire
Go version:   go1.23.7
Built:        2025-03-31T08:45:53Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
spec:
  template:
     spec:
        containers:
          - name: traefik
            image: traefik:v3.3.5
            args:
              - --entrypoints.web.address=:80
              - --entrypoints.websecure.address=:443
              - --providers.kubernetesgateway=true
              - --providers.kubernetesgateway.statusaddress.publishedService=traefik
              - --api.dashboard=true
              - --metrics.prometheus=true
```
