### ISSUE TITLE
Kubernetes GatewayAPIs & Traefik Issues

### ISSUE THREAD

**Issue by acelinkio** [traefik/traefik#11661]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

* **Gateway creates LoadBalancer kubernetes service in a different namespace**
Have been working with Cilium's gatewayapi implementation and assumed that the namespace the gateway was created in would also be where the corresponding Kubernetes LoadBalancer service would live.

* **Does not appear to be a way to specify a LoadBalancer ip address to the service Gateway creates**
In the gateway, have tried using both: 
```yaml
spec:
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.1.15
```
and via
```yaml
spec:
  addresses:
    - type: IPAddress
      value: 192.168.1.15
```
* *Unable to create second Traefik based Gateway**
Creating a second gateway, just resulted in reusing the same Traefik loadbalancer as the first.  Which is not desirable, traffic is intended to be seperated.

### What did you see instead?

Traefik based Gateway to create/manage Kubernetes services.  The expected outcome is that each Kubernetes Gateway creat its own resources and not rely upon the default Traefik.

### What version of Traefik are you using?

Deployed to Kubernetes via Helm chart
chart: https://traefik.github.io/charts
version: 34.5.0

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.
