### ISSUE TITLE
Allow to customize docker provider suffix for Docker Compose

### ISSUE THREAD

**Issue by dinigo** [traefik/traefik#11672]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Docker provider automagically creates services with https://github.com/traefik/traefik/blob/6c3b099c25661e9517c9d0d2e3a5aa37dd380d1a/pkg/provider/docker/shared.go#L209

However, if it is running inside docker compose, it creates it with
https://github.com/traefik/traefik/blob/6c3b099c25661e9517c9d0d2e3a5aa37dd380d1a/pkg/provider/docker/shared.go#L212C1-L213C1

To make a default rule that allows me to map `<service>` to `<service>.mydomain.tld` I need to strip this last part
```yaml
# traefik.yaml
providers:
  docker:
    defaultRule: |
      {{ $serviceName := regexFind "^[^-]+" .Name }}
      Host(`{{ $serviceName }}.{{ env "DOMAIN" }}`)
```

Having different environments for dev/qa/prod mapped to different projects creates services called `<service>_<env>`
Say I have a service that exposes ports 25, 80 and 9000. I need a way to map this to the environment it is running:
```yaml
services:
  my_service:
    expose: [ 25, 80, 9000 ]
  labels:
    traefik.http.services.my_service-<env>.loadbalancer.server.port=80
```
 
Any of the following could be done:

* Allow to disable it with a docker provider variable `ignoreProject: true` — Then the service names will be consistent between environments
* Allow to change the suffix to any other templated expression `defaultServiceName: {{ regexFind "^[^-]+" .Name }}`

**Comment by juliens** [comment]
Hello @dinigo

I'm not sure I understand your problem exactly.

If I understand correctly, you're saying that it's annoying that the service name on your service is "composed" with container name and com.docker.compose.project because if you want to change the port, you need to adapt your label for your different env.

But you may not know that if you don't put any labels with service, we generate the default service name. However, if you add a label with service (like `traefik.http.services.my_service.loadbalancer.server.port=80`), we will not create the default service and the router will automatically be linked to this service.

**Comment by dinigo** [comment]
Hello @juliens, thanks for the super quick response.

Let me explain the use-case a bit more:

* I want to use the default service names, the less config the better. They do have a very reasonable default name.
* I want those to be invariant with the project name, because the project name is used in my case to deploy to different environments. Easiest way would be allowing to configure the default name.


Example (not working):
```yaml
services:
  traefik:
    image: traefik
    ports: [ '80:80' ]
    # ...

  my_service:
    expose: [ 23, 80, 8080 ]
    labels:
      # exposes 3 ports, need to explicitly set the one to use with the router
      traefik.http.services.my_service-prod.loadbalancer.server.port: 80
```

Running `docker compose -p dev up -d` will error traefik, since there's no such service called `my_service-prod`

Convoluted working example:
It's true. I could also have the service defined as:
```yaml
  my_service:
    expose: [ 23, 80, 8080 ]
    labels:
      - traefik.http.services.my_service-{DEPLOY_ENV}.loadbalancer.server.port=80
```
And run it like `DEPLOY_ENV=dev docker compose -p $DEPLOY_ENV up -d`

---
The docs `providers > docker > defaultRule` ([link](https://doc.traefik.io/traefik/providers/docker/#defaultrule)) states:
> _The service name can be accessed with the Name identifier._
which is not true for Docker Compose.

I know the rule is there to provide some kind of namespacing (which is useful indeed).

In terms of development ergonomics it would be easier to have configuration in **to avoid one of**:
* Manually declaring the router for all the exposed services, which can be many — Necessary if I want consistent service naming across "projects".
* Templating the labels

> ```yaml
>   multiport:
>     expose:
>       - "3000"
>       - "4000"
>       - "5000"
> 
>     labels:
>       # 1. As the port we're interested is not the lowest one, it is mandatory to declare the LB
>       # 2. As the name of the service is a function of the deployment environment it has to be templated
>       - 'traefik.http.services.multiport-${DEPLOY_ENV}.loadbalancer.server.port=4000'
> ```

**Summary:**

You are absolutely right. It is doable with one of the above.

It just would be a lot less hacky and easier to set a default behavior if we had a way to set the default docker servicies. Simply
1. Set your `defaultServiceName`. Either include the `com.docker.compose.project` label or not. (1 LOC in config)
2. Set the network you want your services to be exposed
```yaml
providers:
  docker:
    defaultServiceName: {{ .Name }}
    network: frontend
```

```yaml
services:
  my_service_1:
    labels:
      - 'traefik.http.services.my_service_1.loadbalancer.server.port=4000'
 ```

Compared to creating labels for each service in the network and templating them. 
```yaml
services:
  my_service_1:
    labels:
      - 'traefik.http.services.my_service_1-${DEPLOY_ENV}.loadbalancer.server.port=4000'
  # ...
  my_service_N:
    labels:
      - 'traefik.http.services.my_service_N-${DEPLOY_ENV}.loadbalancer.server.port=4000'
```

**Comment by juliens** [comment]
In fact I don't understand why you're saying this example is not working:

```yaml
services:
  traefik:
    image: traefik
    ports: [ '80:80' ]
    # ...

  my_service:
    expose: [ 23, 80, 8080 ]
    labels:
      # exposes 3 ports, need to explicitly set the one to use with the router
      traefik.http.services.my_service-prod.loadbalancer.server.port: 80
```

As I previously explained, the default service name is created if you don't have any label concerning a service. In this example, the service created by Traefik will not have the default service name but the one you decide to configure on the label. So you should be able to even use the label `traefik.http.services.my_service.loadbalancer.server.port: 80` (without the env) even if your service is in prod or dev etc... And so, you deployment manifest should be ok for all your environment?
