### ISSUE TITLE
Dashboard stops working after running for a while

### ISSUE THREAD

**Issue by dougmaitelli** [traefik/traefik#11686]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Every time I restart Traefik I am able to access the dashboard using the route that points to the api@internal service. But after a couple days that endpoint always stops working and starts returning 404.

### What did you see instead?

Dashboard frequently reverts back to return 404

### What version of Traefik are you using?

3.3.5

### What is your environment & configuration?

```yaml
traefik:
    container_name: traefik
    image: traefik:v3.3.5
    environment:
      - CF_EMAIL=${EMAIL_ADDRESS}
      - CF_DNS_API_TOKEN=${CF_API_TOKEN}
      - DOMAIN=${DOMAIN}
    labels:
      - wud.watch=true
      - wud.tag.include=^v\d+\.\d+\.\d+$$
      - wud.link.template=https://github.com/traefik/traefik/releases/tag/v$${major}.$${minor}.$${patch}
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=myresolver
      - traefik.http.routers.traefik.tls.domains[0].main=${DOMAIN}
      - traefik.http.routers.traefik.tls.domains[0].sans=*.${DOMAIN}
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=authelia@docker
      - traefik.http.routers.traefik.middlewares=error-pages-middleware
    networks:
      - proxy
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8081
        published: 8081
        mode: host
      - target: 8083
        published: 8083
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/config/traefik/config.yml:/config.yml:ro
      - /srv/letsencrypt:/letsencrypt
      - /srv/log/traefik:/var/log/traefik
    command:
      - '--api=true'
      - '--log.maxage=30'
      - '--accesslog=true'
      - '--accesslog.filepath=/var/log/traefik/access.log'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
      - '--entrypoints.web.http.redirections.entrypoint.permanent=true'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.ws.address=:8081'
      - '--entrypoints.wss.address=:8083'
      - '--providers.file.filename=/config.yml'
      - '--providers.file.watch=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker.network=proxy'
      - '--serverstransport.insecureskipverify=true'
      - '--certificatesresolvers.myresolver.acme.dnschallenge=true'
      - '--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare'
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - '--certificatesresolvers.myresolver.acme.email=${EMAIL_ADDRESS}'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - authelia
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

I don't see any errors on logs
