### ISSUE TITLE
One traefik instance stop get updates from consul catalog after network partition

### ISSUE THREAD

**Issue by malmetom** [traefik/traefik#11688]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have a 3-node cluster using traefik together with consul catalog for routing

After a network partition where one node is isolated, one of the two traefik instances stops get updates from the consul catalog in configurationwatcher, and is still holding the data from before the partition.

### What did you see instead?

This leads to clients talking through this unsynced traefik instance is routed to the isolated node with a 499 as response. 

The issue can be resolved either by restart of traefik or by waiting approx. 15-16 min, then suddenly the instance get a new update of consul catalog and routes data correct.

Is this a know behaviour in traefik or consul? Is it most likely due to bad configuration?

### What version of Traefik are you using?

3.3.5

### What is your environment & configuration?

```yaml
global:
  checkNewVersion: false
  sendAnonymousUsage: false
entryPoints:
  api:
    address: ":85"
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
  https:
    address: ":443"
  amqps:
    address: ":5671"
  mqtts:
    address: ":8883"
accessLog:
  filePath: /var/log/traefik/access.log
  format: common
log:
  level: DEBUG
api:
  insecure: true
  dashboard: true
ping: {}
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
providers:
  consulCatalog:
    exposedByDefault: false
    prefix: "traefik"
    refreshInterval: "5s"
    endpoint:
      endpointWaitTime: 5s
      address: "consul:8500"
  file:
    directory: "etc/traefik/conf.d"
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

Will catch issue again, and share logs
