### ISSUE TITLE
Traefik stopped printing logs to stdout

### ISSUE THREAD

**Issue by alvitali** [traefik/traefik#11717]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

After configuring traefik to output logs to a log file, traefik doesn't print logs to stdout anymore after removing the file path again.

### What did you see instead?

Traefik doesn't print logs to stdout, breaking monitoring & discovery through loki / grafana

### What version of Traefik are you using?

3.3.6

### What is your environment & configuration?

```yaml
log:
  level: "INFO"
  # filePath: "/etc/traefik/logs/traefik.log"

accessLog:
  filePath: "/etc/traefik/logs/access.log"
```

Traefik is running in a docker container. Logs worked fine before setting `filePath`

### If applicable, please paste the log output in DEBUG level

no logs, as I cannot print them anymore!
