### ISSUE TITLE
sanitizePath in additional entryPoint not being respected

### ISSUE THREAD

**Issue by cinderblockgames** [traefik/traefik#11725]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am trying to disable sanitizePath for [ladder](https://github.com/everywall/ladder) so that I can continue to drop the ladder URL in front of another URL and have it work.

### What did you see instead?

Slashes are still being merged.

### What version of Traefik are you using?

Version:      3.3.6
Codename:     saintnectaire
Go version:   go1.23.8
Built:        2025-04-18T09:18:47Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```toml
  [entryPoints.web-secure]
    address = ":443"
  [entryPoints.no-sanitize]
    [entryPoints.no-sanitize.http]
      sanitizePath = false
```
```yaml
      - 'traefik.http.routers.ladder.entrypoints=web-secure,no-sanitize'
```
