### ISSUE TITLE
replacePathRegex middleware doesnt work when replacement contain question mark

### ISSUE THREAD

**Issue by s1495k043** [traefik/traefik#11735]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

When using Traefik's middleware (replacePathRegex, addPrefix, or other path modifiers), special characters like question marks (?) in the replacement path are automatically URL encoded to %3F.

For example, with this configuration:
```yaml
middlewares:
  pacs-replace:
    replacePathRegex:
      regex: "^/A=(.*)"
      replacement: "/externalinterface/viewexi?ENC=$1"
```
The actual result becomes "/externalinterface/viewexi%3FENC=$1" instead of "/externalinterface/viewexi?ENC=$1".
I've tried using multiple chained middlewares with placeholders, but the question mark is still encoded in every attempt.
Is there a way to prevent Traefik from encoding the question mark in path replacements, or is there an alternative approach to achieve the same result?

### What did you see instead?

- Input 
- https://localhost:8088/A=1234
- Expected 
- https://localhost:8088/externalinterface/viewexi?ENC=1234
- output
- https://localhost:8088/externalinterface/viewexi%3FENC=1234

### What version of Traefik are you using?

3.3.6

### What is your environment & configuration?

```yaml
 middlewares:
   pacs-replace:
     replacePathRegex:
       regex: "^/A=(.*)"
       replacement: "/externalinterface/viewexi?ENC=$1"
```

Add more configuration information here.
