### ISSUE TITLE
HTTP3 and Proxy protocol

### ISSUE THREAD

**Issue by vnghia** [traefik/traefik#11747]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I put `traefik` behind `frp` which is a popular port forwarding software with proxy protocol support.

### What did you see instead?

If I enable proxy protocol on `frp` side, I see `traefik` extract correctly the original client ip with HTTP1 and HTTP2. However, `traefik` show the ip of `frp` if the connection is HTTP3.

### What version of Traefik are you using?

`3.3.6`

### What is your environment & configuration?

```toml
[entryPoints.https]
address = "[::]:443"

[entryPoints.https.http3]
advertisedPort = 443

[entryPoints.public-https.proxyProtocol]
trustedIPs = ["172.0.0.1"] # frp ip
```
