### ISSUE TITLE
traefik_service_server_up is missing

### ISSUE THREAD

**Issue by D0wn3r** [traefik/traefik#11754]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

traefik_service_server_up seems to be missing in metrics (I use Prometheus)

### What did you see instead?

Nothing

### What version of Traefik are you using?

v3.1

### What is your environment & configuration?

```yaml
metrics:
  prometheus:
    entryPoint: websecure
    manualRouting: true
    addRoutersLabels: true
    addServicesLabels: true
```

**Comment by nmengin** [comment]
Hey @D0wn3r,

Thanks for the bug report.

We have put it on our (maintainer's) plate to reproduce.
We'll keep you updated on this ticket once we have moved forward on it.

**Comment by rtribotte** [comment]
@D0wn3r Thanks for reporting this!

Could you please share the dynamic configuration with us?
Did you enable health check?

**Comment by D0wn3r** [comment]
my dynamic configuration is simple:
```
http:
  middlewares:
    vpn-ipwhitelist:
      ipAllowList:
        sourceRange:
          - #####

tls:
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
```

**Comment by D0wn3r** [comment]
How to enabled health check ?

**Comment by rtribotte** [comment]
Hi @D0wn3r,

You should find every information you need about activating health-check in our documentation: https://doc.traefik.io/traefik/routing/services/#health-check.

The GitHub issue tracker is dedicated to bug and feature requests.
For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik). 

We are closing this issue accordingly but feel free to re-open it if you think that we missed something.

**Comment by D0wn3r** [comment]
if it's this healthcheck that you are talking, I have this in the compose of a service
```
       - traefik.http.routers.back-consultantio.tls=true
       - traefik.http.routers.back-consultantio.rule=Host(`xxxxxxxxxx`)
       - traefik.http.routers.back-consultantio.priority=150
       - traefik.http.services.back-consultantio.loadbalancer.server.port=8030
       - traefik.http.services.back-consultantio.loadbalancer.healthcheck.path=xxxxxxxxxxxx
       - traefik.http.services.back-consultantio.loadbalancer.healthcheck.interval=1m
```

Can you reopen this ticket please

**Comment by D0wn3r** [comment]
@rtribotte

**Comment by nmengin** [comment]
Hey @D0wn3r,

Thanks for the additional information. I re-open the issue accordingly.
If any community member can help us find verified steps to reproduce and fix the issue, if possible, we would love the help.

**Comment by davgia** [comment]
Hi, I have the same problem with helm chart 39.0.5 ... 

Those are my values:

``` yaml
logs:
  general:
    level: INFO
  access:
    enabled: true
    format: json
ingressRoute:
  healthcheck:
    enabled: true
metrics:
  prometheus:
    serviceMonitor:
      enabled: true
```
