### ISSUE TITLE
Traefik cannot access URL through domain name

### ISSUE THREAD

**Issue by ImDevinC** [traefik/traefik#11766]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am using the Traefik gateway in my cluster with httproutes for routing external traffic. From all pods _except_ the Traefik pod, I can properly `wget -O- https://<route>.<domain>` (IE: `get -O- https://login.int.mydomain.com`). The IP address for this request resolves back to the same node that is making the request (I only have a single cluster as this is my homelab).
However, when I run this request on the Traefik pod, the connection just hangs until it times out. In most cases this wouldn't be an issue, but I have an OIDC middleware that tries to route to `https://login.int.mydomain.com` and since Traefik can't properly connect to this pod, authentication fails.

### What did you see instead?

```
wget -O- https://login.int.mydomain.com
Connecting to login.int.mydomain.com (192.168.1.64:443)
wget: can't connect to remote host (192.168.1.64): Operation timed out
```

### What version of Traefik are you using?

```
traefik version
Version:      3.3.6
Codename:     saintnectaire
Go version:   go1.23.8
Built:        2025-04-18T09:18:47Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

Helm chart values
```yaml
    general:
      level: DEBUG
  providers:
    kubernetesIngress:
      enabled: false
    kubernetesGateway:
      enabled: true
  gateway:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-traefik
    listeners:
      web:
        hostname: "*.int.mydomain.com"
        namespacePolicy: All
        forwardedHeaders:
          insecure: true
      websecure:
        hostname: "*.int.mydomain.com"
        port: 8443
        namespacePolicy: All
        protocol: HTTPS
        certificateRefs:
          - name: wildcard-tls
        forwardedHeaders:
          insecure: true
  service:
    spec:
      externalTrafficPolicy: Local
  ports:
    web:
      redirections:
        entryPoint:
          scheme: https
          to: websecure
```

Add more configuration information here.
