### ISSUE TITLE
OpenTelemetry Logs not working with accesslog settings

### ISSUE THREAD

**Issue by henrikrexed** [traefik/traefik#11779]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We’ve been experimenting with the new OpenTelemetry logging support in Traefik (enabled via the experimental.otlpLogs flag), specifically using the gRPC exporter to send logs to our OpenTelemetry Collector.

Despite configuring everything according to the [official docs](https://doc.traefik.io/traefik/observability/logs/), we’re not seeing any logs arrive at the collector. Here’s what we’ve tried:

- Enabled experimental.otlpLogs: true

- Configured the gRPC endpoint under log.otlp.grpc.endpoint
- Verified that the collector is listening on port 4317 with the OTLP gRPC receiver enabled
- Confirmed network connectivity between Traefik and the collector

Still, no logs are being received.

i'm using the latest version of traefik in a kubernetes cluster.

I have tried to remove log settings and accesslog settings, and sunddenly i'm getting oltp logs. but not details about the accesslog .
When adding the access log settings , traefik stops emitting otlp logs and use stdout instead.

### What did you see instead?

When adding acesslogs details no otlp logs are produced.

### What version of Traefik are you using?

Traefik v3.4 with Gateway API experimental support

### What is your environment & configuration?

Here is my deployment settingds of taefik in my environment : 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:

    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: traefik

  labels:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-35.3.0
  name: traefik
  namespace: traefik

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik-traefik
      app.kubernetes.io/name: traefik
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: traefik-traefik
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: traefik
        helm.sh/chart: traefik-35.3.0
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --global.checknewversion
        - --global.sendanonymoususage
        - --entryPoints.metrics.address=:9100/tcp
        - --entryPoints.traefik.address=:8080/tcp
        - --entryPoints.web.address=:8000/tcp
        - --entryPoints.websecure.address=:8443/tcp
        - --api.dashboard=true
        - --ping=true
        - --metrics.addinternals
        - --metrics.prometheus=true
        - --metrics.prometheus.entrypoint=metrics
        - --metrics.otlp=true
        - --metrics.otlp.addEntryPointsLabels=true
        - --metrics.otlp.addRoutersLabels=true
        - --metrics.otlp.addServicesLabels=true
        - --metrics.otlp.grpc=true
        - --metrics.otlp.grpc.endpoint=otel-collector.default.svc.cluster.local:4317
        - --metrics.otlp.grpc.insecure=true
        - --tracing.addinternals
        - --tracing.serviceName=traefik
        - --tracing.resourceAttributes.fromProxy=
        - --tracing.otlp=true
        - --tracing.otlp.grpc=true
        - --tracing.otlp.grpc.endpoint=otel-collector.default.svc.cluster.local:4317
        - --tracing.otlp.grpc.insecure=true
        - --experimental.fastProxy
        - --providers.kubernetescrd
        - --providers.kubernetescrd.allowEmptyServices=true
        #- --experimental.kubernetesgateway
        - --providers.kubernetesgateway
        - --providers.kubernetesgateway.statusaddress.service.name=traefik
        - --providers.kubernetesgateway.statusaddress.service.namespace=traefik
        - --providers.kubernetesgateway.experimentalchannel=true
        - --entryPoints.websecure.http.tls=true
        #- --log.otlp.grpc.tls.insecureSkipVerify=true
        - --experimental.otlpLogs=true
    #    - --log.format=json
      #  - --log.otlp.grpc=true
       # - --log.otlp.grpc.endpoint=otel-collector.default.svc.cluster.local:4317
        - --log.otlp.http=true
        - --log.otlp.http.endpoint=http://otel-collector.default.svc.cluster.local:4318/v1/logs
        - --accesslog=true
        #- --accesslog.format=json
        #- --accesslog.fields.defaultmode=keep
       # - --accesslog.fields.headers.defaultmode=keep
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: docker.io/traefik:v3.4.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: traefik
        ports:
        - containerPort: 9100
          name: metrics
          protocol: TCP
        - containerPort: 8080
          name: traefik
          protocol: TCP
        - containerPort: 8000
          name: web
          protocol: TCP
        - containerPort: 8443
          name: websecure
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
      serviceAccount: traefik
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60
      volumes:
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: tmp
```
Side of this i'm deploying the opentelemetry demo and using the following opentelmetry collector to receive the otlplogs:

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: oteld
  labels:
    app: opentelemetry
    app.kubernetes.io/component: oteld-daemonset
spec:
  mode: daemonset
  serviceAccount: otelcontribcol
  image: otel/opentelemetry-collector-contrib:0.122.0
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
  env:
    - name: CLUSTER_ID
      valueFrom:
        secretKeyRef:
          name: dynatrace
          key: clusterid
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: DT_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: dynatrace
          key: dynatrace_oltp_url
    - name: DT_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: dynatrace
          key: dt_api_token
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: CLUSTERNAME
      valueFrom:
        secretKeyRef:
          name: dynatrace
          key: clustername
    - name: OTEL_SERVICE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['app.kubernetes.io/component']
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: service.name=$(OTEL_SERVICE_NAME)
  volumeMounts:
    - mountPath: /var/log
      name: varlog
      readOnly: true
    - mountPath: /var/lib/docker/containers
      name: varlibdockercontainers
      readOnly: true

  volumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers

  config:
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 5s
            static_configs:
            - targets:
              - ${MY_POD_IP}:8888




      filelog:
        include:
          - /var/log/pods/*/*/*.log

        start_at: beginning
        include_file_path: true
        include_file_name: false
        operators:
          # Find out which format is used by kubernetes
          - type: router
            id: get-format
            routes:
              - output: parser-docker
                expr: 'body matches "^\\{"'
              - output: parser-crio
                expr: 'body matches "^[^ Z]+ "'
              - output: parser-containerd
                expr: 'body matches "^[^ Z]+Z"'
          # Parse CRI-O format
          - type: regex_parser
            id: parser-crio
            regex: '^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$'
            output: extract_metadata_from_filepath
            timestamp:
              parse_from: attributes.time
              layout_type: gotime
              layout: '2006-01-02T15:04:05.999999999Z07:00'
          # Parse CRI-Containerd format
          - type: regex_parser
            id: parser-containerd
            regex: '^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$'
            output: extract_metadata_from_filepath
            timestamp:
              parse_from: attributes.time
              layout: '%Y-%m-%dT%H:%M:%S.%LZ'
          # Parse Docker format
          - type: json_parser
            id: parser-docker
            output: extract_metadata_from_filepath
            timestamp:
              parse_from: attributes.time
              layout: '%Y-%m-%dT%H:%M:%S.%LZ'
          - type: move
            from: attributes.log
            to: body
          # Extract metadata from file path
          - type: regex_parser
            id: extract_metadata_from_filepath
            regex: '^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9\-]{36})\/(?P<container_name>[^\._]+)\/(?P<restart_count>\d+)\.log$'
            parse_from: attributes["log.file.path"]
            cache:
              size: 128  # default maximum amount of Pods per Node is 110
          # Rename attributes
          - type: move
            from: attributes.stream
            to: attributes["log.iostream"]
          - type: move
            from: attributes.container_name
            to: resource["k8s.container.name"]
          - type: move
            from: attributes.namespace
            to: resource["k8s.namespace.name"]
          - type: move
            from: attributes.pod_name
            to: resource["k8s.pod.name"]
          - type: move
            from: attributes.restart_count
            to: resource["k8s.container.restart_count"]
          - type: move
            from: attributes.uid
            to: resource["k8s.pod.uid"]
    
    


    processors:
      batch:
        send_batch_max_size: 1000
        timeout: 30s
        send_batch_size : 800
    
    
     
      cumulativetodelta: {}
    





      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
    
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.statefulset.name
            - k8s.daemonset.name
            - k8s.cronjob.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.cluster.uid
        pod_association:
          - sources:
            - from: resource_attribute
              name: k8s.pod.name
            - from: resource_attribute
              name: k8s.namespace.name
          # Pod labels which can be fetched via K8sattributeprocessor
      memory_limiter:
        check_interval: 1s
        limit_percentage: 70
        spike_limit_percentage: 30
      
      resource:
        attributes:
        - key: k8s.cluster.name 
          value: ${CLUSTERNAME}
          action: insert

      resource/ebpf:
        attributes:
          - key: dt.pipeline.source
            value: ebpftop
            action: insert

      transform:
        error_mode: ignore
        log_statements:
          - context: resource
            statements:
              - set(attributes["dt.kubernetes.workload.kind"], "statefulset") where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.statefulset.name"]) where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["dt.kubernetes.workload.kind"], "deployment") where IsString(attributes["k8s.deployment.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.deployment.name"]) where IsString(attributes["k8s.deployment.name"])
              - set(attributes["dt.kubernetes.workload.kind"], "daemonset") where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.daemonset.name"]) where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["dt.kubernetes.cluster.id"], attributes["k8s.cluster.uid"]) where IsString(attributes["k8s.cluster.uid"])
    
        metric_statements:
          - context: resource
            statements:
              - set(attributes["dt.kubernetes.workload.kind"], "statefulset") where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.statefulset.name"]) where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["dt.kubernetes.workload.kind"], "deployment") where IsString(attributes["k8s.deployment.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.deployment.name"]) where IsString(attributes["k8s.deployment.name"])
              - set(attributes["dt.kubernetes.workload.kind"], "daemonset") where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.daemonset.name"]) where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["dt.kubernetes.cluster.id"], attributes["k8s.cluster.uid"]) where IsString(attributes["k8s.cluster.uid"])
        trace_statements:
          - context: resource
            statements:
              - set(attributes["dt.kubernetes.workload.kind"], "statefulset") where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.statefulset.name"]) where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["dt.kubernetes.workload.kind"], "deployment") where IsString(attributes["k8s.deployment.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.deployment.name"]) where IsString(attributes["k8s.deployment.name"])
              - set(attributes["dt.kubernetes.workload.kind"], "daemonset") where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.daemonset.name"]) where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["dt.kubernetes.cluster.id"], attributes["k8s.cluster.uid"]) where IsString(attributes["k8s.cluster.uid"])






    exporters:
      debug:
        verbosity: detailed
        sampling_initial: 5
     
      otlphttp:
        endpoint: ${DT_ENDPOINT}/api/v2/otlp
        headers:
          Authorization: "Api-Token ${DT_API_TOKEN}"
      otlp:
        endpoint: otel-collector.default.svc.cluster.local:4317
        tls:
          insecure: true
      
    
    
    service:
      pipelines:
        logs:
          receivers: [filelog]
          processors: [memory_limiter,k8sattributes,transform,resource,batch]
          exporters: [ otlphttp]



        metrics:
          receivers: [prometheus]
          processors: [memory_limiter,k8sattributes,transform,resource,cumulativetodelta,batch]
          exporters: [otlphttp]



      telemetry:
        logs:
          level: info
        metrics:
          address: ${MY_POD_IP}:8888


```

**Comment by ytugarev** [comment]
This setup is working for me today v3.4.1 . Normal logs go to file, access logs are going to Alloy and Loki in otlp. As far as I understend you need to do - "--accesslog.otlp=true" instead of - "--accesslog=true" when you go otlp

```
- "--log.level=DEBUG"
      - "--log.filePath=/var/log/traefik/traefik.log"
      - "--log.maxsize=5" #5MB log file size max
      - "--log.maxbackups=5" #maxBackups is the maximum number of old log files to retain      
      #- "--accesslog=true"
      #- "--accesslog.filepath=/var/log/traefik/access.json"
      #- "--accesslog.format=json"
      #- "--accesslog.fields.names.StartUTC=drop" #drop UTC time - local time is next
      #- "--accesslog.fields.headers.names.User-Agent=keep" #This helps CrowdSec to identify bad bots and block threat actors using known hacking tooling (nmap, gobuster, sqlmap etc.)
      - "--log.format=json"
      - "--experimental.otlpLogs=true"
      #- "--log.otlp=true"
      #- "--log.otlp.grpc=true"
      #- "--log.otlp.grpc.insecure=true"
      #- "--log.otlp.grpc.endpoint=192.168.50.151:4317"
      - "--accesslog.otlp=true"
      - "--accesslog.otlp.grpc=true"
      - "--accesslog.otlp.grpc.insecure=true"
      - "--accesslog.otlp.grpc.endpoint=192.168.50.151:4317"
```


![Image](https://github.com/user-attachments/assets/ea2ffb6e-584e-4ebf-aea9-0b4abac1be69)

PS. field/names manipulation commands seems to be ok as is - - "--accesslog.fields.headers.names.User-Agent=keep" . Not sure why there is this [strange section](https://doc.traefik.io/traefik/observability/access-logs/#headers_1) in the docs

![Image](https://github.com/user-attachments/assets/ced63342-bfa6-4606-aa97-69380f20a9ab)

**Comment by maikdiepenbroek** [comment]
I can't get it to work using 3.4.1 and with a yaml based config:

```yaml
experimental:
  otlpLogs: true

accesslog:
  filePath: /var/log/traefik/traefik-access.log
  format: json
  filters:
    statusCodes:
      - "200"
      - "400-599"
    retryAttempts: true
    minDuration: "10ms"
  bufferingSize: 100
  fields:
    headers:
      defaultMode: drop
      names:
        User-Agent: keep
  otlp:
    http:
      endpoint: http://[MY_HTTP_ENDPOINT]
```

**Comment by nmengin** [comment]
Hey @maikdiepenbroek,

Thank you for your feedback.

Could you give it another try, deleting the option `accesslog.filepath`, please?
It should fix the situation.

**Comment by maikdiepenbroek** [comment]
> Hey [@maikdiepenbroek](https://github.com/maikdiepenbroek),
> 
> Thank you for your feedback.
> 
> Could you give it another try, deleting the option `accesslog.filepath`, please? It should fix the situation.

I’ll try it asap, so it’s either locally or remote, not both? I’ll let you know, thanks so much for the reply!

**Comment by maikdiepenbroek** [comment]
~It doesn't seem to work, i've added it to both my logs and accessLogs but it doesn't appear to be pushed to loki, whereas `curl -v   -H "Content-Type: application/json"   --data-binary '{"streams":[{"stream":{"job":"traefik"},"values":[["'"$(date +%s%N)"'","{\"test\":\"entry\"}"]]}]}'   http://[IP]:3100/loki/api/v1/push` works~

A case of RTFM i guess, i was using the wrong endpoint: once i switched over to `/otlp/v1/logs` it started working! I could use both the filepath and the otlp exporter.

**Comment by nmengin** [comment]
Thank you for the feedback @maikdiepenbroek.
@henrikrexed have you tried the solution proposed?

**Comment by NEwa-05** [comment]
Hi,

@nmengin, I did try the experimental feature and can confirm that the stdout output stops working when OTel log export is activated, even when adding the filepath option.

Here's my log configuration from my value file:
```yaml
logs:
  general:
    format: json
    level: DEBUG
    filepath: /tmp/traefik.log
  access:
    enabled: true
    format: json
    addInternals: false
    filepath: /tmp/access.log
    fields:
      general:
        defaultmode: keep
      headers:
        defaultmode: keep
additionalArguments:
  - --experimental.otlpLogs=true
  - --log.otlp=true
  - --log.otlp.grpc=true
  - --log.otlp.grpc.insecure=true
  - --log.otlp.grpc.endpoint=otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317
  - --accesslog.otlp=true
  - --accesslog.otlp.grpc=true
  - --accesslog.otlp.grpc.insecure=true
  - --accesslog.otlp.grpc.endpoint=otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317
```
