### ISSUE TITLE
404 error after upgrading from 3.3 to latest (3.4)

### ISSUE THREAD

**Issue by pedropombeiro** [traefik/traefik#11778]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Upgrade docker image from `traefik:v3.3` to `traefik:latest` (3.4).

### What did you see instead?

Some containers were no longer accessible. This is confirmed by comparing the dump of `curl --connect-timeout 2 -sf https://traefik.mydomain.com/api/rawdata | jq` before and after the upgrade:

![Image](https://github.com/user-attachments/assets/880814dd-935b-4000-b8fa-6ef5bcc60dc1)

### What version of Traefik are you using?

```
Version:      3.4.0
Codename:     chaource
Go version:   go1.23.8
Built:        2025-05-05T13:50:06Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.middlewares.paperless-doc-limit.buffering.maxRequestBodyBytes: 30000000

      traefik.http.routers.paperless.rule: Host(`docs.mydomain.com`)
      traefik.http.routers.paperless.entrypoints: websecure
      traefik.http.routers.paperless.middlewares: rate-limit@file
      traefik.http.routers.paperless.tls: true

      traefik.http.routers.paperless-mtls.rule: Host(`docs.mydomain.com`)
      traefik.http.routers.paperless-mtls.entrypoints: websecure-external
      traefik.http.routers.paperless-mtls.middlewares: mtls_check_plugin-docs@file,paperless-doc-limit,rate-limit@file
      traefik.http.routers.paperless-mtls.tls: true
      traefik.http.routers.paperless-mtls.tls.options: require-mtls-docs@file

      traefik.http.services.paperless.loadbalancer.server.port: 8000
      traefik.http.services.paperless.loadbalancer.server.url: "http://docs_webserver:8000"
```

```yaml
x-tls13-settings: &tls13-settings
  minVersion: VersionTLS13
  cipherSuites:
    - TLS_AES_256_GCM_SHA384
    - TLS_CHACHA20_POLY1305_SHA256
  sniStrict: true

tls:
  ...
  options:
    default:
      <<: *tls13-settings

    ##########################
    # Client certificates

    require-mtls-docs:
      <<: *tls13-settings
      clientAuth:
        caFiles:
          - /etc/traefik/client-certs/docs/ca-docs.mydomain.com.crt
        clientAuthType: RequestClientCert # The actual verification needs to be done by the mtls_check_plugin-docs middleware
```

### v3.3

```
2025-05-22T10:52:06+00:00 -[-] DEBUG    -
  caller: github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213
  message: Service selected by WRR: http://172.29.8.7:3001
2025-05-22T10:52:10+00:00 -[-] DEBUG    -
  plugin: plugin-traefik-mtls-check-plugin
  module: github.com/WalterP/traefik-mtls-check-plugin
  runtime: 
  caller: fmt/print.go:225
  message: Found valid certificate: CN=docs.mydomain.com,***,C=CH
2025-05-22T10:52:10+00:00 -[-] DEBUG    -
  caller: github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213
  message: Service selected by WRR: http://172.29.8.17:8000
```

### v3.4

```
2025-05-22T10:53:49+00:00 -[-] INFO     
  ClientAddr: 172.29.8.1:26290
  ClientHost: 172.29.8.1
  ClientPort: 26290
  DownstreamContentSize: 19
  DownstreamStatus: 404
  Duration: 186371
  GzipRatio: 0
  OriginContentSize: 0
  OriginDuration: 0
  OriginStatus: 0
  Overhead: 186371
  RequestAddr: docs.mydomain.com:10443
  RequestContentSize: 0
  RequestCount: 32
  RequestHost: docs.mydomain.com
  RequestMethod: GET
  RequestPath: /
  RequestPort: 10443
  RequestProtocol: HTTP/1.1
  RequestScheme: https
  RetryAttempts: 0
  StartLocal: 2025-05-22T10:53:49.648456436+02:00
  StartUTC: 2025-05-22T08:53:49.648456436Z
  TLSCipher: TLS_CHACHA20_POLY1305_SHA256
  TLSVersion: 1.3
  downstream_Content-Type: text/plain; charset=utf-8
  entryPointName: websecure-external
  request_User-Agent: curl/8.10.1
```
