### ISSUE TITLE
ServersTransport rootCAs validation check is invalid and makes the CR unusable

### ISSUE THREAD

**Issue by LinAnt** [traefik/traefik#11774]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

When addressing deprecation warnings in our clusters, I stumbled upon this bug:

```
x-kubernetes-validations:
- message: RootCA cannot have both Secret and ConfigMap defined.
  rule: has(self.secret) && has(self.configMap)
```

This yaml is applied, but Traefik errors out when trying to parse the CR
```
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: derp
spec:
  insecureSkipVerify: false
  rootCAs:
    - secret: "secretname"
      configMap: ""
```

Dropping either `secret` or `configMap` makes the CR fail the API server validation.

### What did you see instead?

ERR Error while loading CA: both Secret and ConfigMap are defined

### What version of Traefik are you using?

Kubernetes, latest helm chart

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

ERR Error while loading CA: both Secret and ConfigMap are defined
