### ISSUE TITLE
Dashboard shows `REMOVE HEADER` value incorrectly

### ISSUE THREAD

**Issue by SlavikCA** [traefik/traefik#11780]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I added this middleware:
```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: kubetail-auth
  namespace: logs
spec:
  basicAuth:
    secret: kubetail-auth
```

And I saw that middleware in the dashboard, showing that `REMOVE HEADER` is set to true:

![Image](https://github.com/user-attachments/assets/2e74f4d3-f654-4da7-89b0-1beb926402dc)

If fact it was not set to true, it was set to false (that's default value)

### What did you see instead?

So, the dashboard shows incorrect value of `REMOVE HEADER`

### What version of Traefik are you using?

Traefik 3.4.0 installed via HELM

### What is your environment & configuration?

I have Traefik in my Kubernetes cluster
