### ISSUE TITLE
v3.3.3 Middleware RedirectRegex and ReplacePathRegex not capture

### ISSUE THREAD

**Issue by jplanckeel-ep** [traefik/traefik#11801]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hello,

We use version v3.3.3 on Kubernetes cluster EKS v1.32. We have a bug when we want use regex to rewrite url  with redirect or replace path. 

### What did you see instead?

We have in browser http://myapp.test/bar/foo/test but we want http://myapp.test/bar/test when we request http://myapp.test/foo/test 

### What version of Traefik are you using?

V3.3.3

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

```
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik-internal
  name: myapp
  namespace: myapp
spec:
  entryPoints:
    - web
    - metrics
    - websecure
  routes:
    - match: Host(`myapp.test`) && PathPrefix(`/foo/`) || PathPrefix(`/bar/`)
      kind: Rule
      priority: 200
      services:
        - name: myapp
          port: 8080
      middlewares:
        - name: myapp
          namespace:myapp
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: myapp
  namespace: myapp
spec:
  redirectRegex:
    regex: ^https://myapp.test/foo/(.*)$
    replacement: https://myapp.test/bar/$1
```

**Comment by nmengin** [comment]
Hey @jplanckeel-ep,

Thanks for the bug report.
If any community member can help us find verified steps to reproduce and fix the issue, if possible, we would love the help.

**Comment by joaodrmacas** [comment]
Hello @nmengin  and Traefik team,

I've been looking into this issue. I've successfully reproduced the bug on a local Kubernetes cluster using `kind` and Traefik v3.3.3.

I've put together a detailed guide with step-by-step instructions and all the necessary configuration files to reliably reproduce the issue:

https://gist.github.com/joaodrmacas/d6e971c08e3cdd7b5db5c6c794450c2d

I'll be working on finding a fix for this but will be a little busy in the near future. I wanted to share the reproduction steps as soon as possible in case it helps others or allows parallel efforts.

Please let me know if you have any questions or if anything in the reproduction steps needs clarification.

Thanks!

**Comment by joshua-siw** [comment]
@jplanckeel-ep i see that you are using HTTPS in your regex, but you call http://myapp.test/bar/foo/test
could that be the problem?


@joaodrmacas i setup the reproduction environment as you did and can get it to work, if I'm adding the exact request URL with port, to the field regex, to match the port forwarding in the setup

like this

```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: myapp-redirect
  namespace: myapp
spec:
  redirectRegex:
    regex: ^http://myapp.test:8080/foo/(.*)$
    replacement: http://myapp.test/bar/$1
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: myapp
  namespace: myapp
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`myapp.test`) && PathPrefix(`/foo/`) || PathPrefix(`/bar/`)
      kind: Rule
      services:
        - name: myapp
          port: 8080
      middlewares:
        - name: myapp-redirect
          namespace: myapp
```


curl -sLD - http://myapp.test:8080/foo/test -o /dev/null -w '%{url_effective}'
HTTP/1.1 302 Found
Location: http://myapp.test/bar/test
Date: Sun, 08 Jun 2025 10:31:46 GMT
Content-Length: 5

http://myapp.test/bar/test

**Comment by jplanckeel-ep** [comment]
We have the same problem with replacePathRegex

```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rewrite
  namespace: foo
spec:
  replacePathRegex:
    regex: ^/foo/(.*)$
    replacement: /bar/$1


```

**Comment by jplanckeel-ep** [comment]
Hello, we have upgrade to traefik 3.4.1 and we have the same problem

**Comment by bingoct** [comment]
> ment as you did and can get it to work, if I'm adding the exact request URL with port, to the field regex, to match the port forwarding in the setup

so, RedirectRegex  must be http instead of https ?

i meet similar question in 3.5.0 with docker entrypoint. http work well, but https fail.

```yaml
http:
  middlewares:
    fallback-redir:
      redirectRegex:
        regex: "^(http://(.+?)/(.*)"
        replacement: "https://myserver/${3}"

http:
  routers:
    fallback-web:
      entrypoints: http
      service: noop@internal
      rule: HostRegexp(`.+`)
      priority: 1
      middlewares:
        - "fallback-redir@file"
```

replacepathregex works well on https for me
```yaml
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.services.doc.loadbalancer.server.port=${port}
      - traefik.http.routers.doc.entrypoints=https
      - traefik.http.routers.doc.rule=Host(`${domain}`) && PathPrefix(`/`)
      - traefik.http.middlewares.doc-replace.replacepathregex.regex=^/(rust-course|rust-by-practice|rust-doc/rust/html)/$
      - traefik.http.middlewares.doc-replace.replacepathregex.replacement=/$${1}/index.html
      - traefik.http.routers.doc.tls=true
      - traefik.http.routers.doc.tls.certresolver=cloudflare
      - traefik.http.routers.doc.tls.domains[0].main=${comDomain}
      - traefik.http.routers.doc.tls.domains[0].sans=*.${comDomain}
      - traefik.http.routers.doc.middlewares=doc-replace@docker
```
