### ISSUE TITLE
Too low Let's Encrypt router priority

### ISSUE THREAD

**Issue by IngLP** [traefik/traefik#11826]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I use DNS-01 Let's enrypt challenge for all my domains. One domain is from a provider that is not supported (Aruba). I want to use HTTP-01 challenge for that.

My config:
```
entryPoints:
  web:
    address: ":80"
    allowACMEByPass: true
  websecure:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: 600s
    http:
      tls:
        certResolver: le

certificatesResolvers:
  le:
    acme:
      email: ***
      storage: /app/acme.json
      dnsChallenge:
        provider: ovh
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
  le-http:
    acme:
      email: ***
      storage: /app/acme-http.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    watch: true
    exposedByDefault: false
    network: traefik
  file:
    directory: /conf/proxies
    watch: true
```

docker labels for the website:
```
    labels:
      traefik.enable: true
      # HTTP router
      traefik.http.routers.domain-cloud.entrypoints: web
      traefik.http.routers.domain-cloud.rule: Host(`domain.cloud`) || Host(`www.domain.cloud`)
      traefik.http.routers.domain-cloud.middlewares: domain-cloud-redirect
      # Redirection
      traefik.http.middlewares.domain-cloud-redirect.redirectscheme.scheme: https
      traefik.http.middlewares.domain-cloud-redirect.redirectscheme.permanent: true
      # HTTPS router
      traefik.http.routers.domain-cloud-tls.entrypoints: websecure
      traefik.http.routers.domain-cloud-tls.rule: Host(`domain.cloud`) || Host(`www.domain.cloud`)
      traefik.http.routers.domain-cloud-tls.tls: true
      traefik.http.routers.domain-cloud-tls.tls.certresolver: le-http
      traefik.http.routers.domain-cloud-tls.middlewares: domain-cloud-headers
      # Headers
      traefik.http.middlewares.domain-cloud-headers.headers.customrequestheaders.X_FORWARDED_PROTO: https
      # Service
      traefik.http.services.domain-cloud.loadbalancer.server.port: 3000
      traefik.http.services.domain-cloud.loadbalancer.server.scheme: http
      traefik.http.services.domain-cloud.loadbalancer.passHostHeader: true
```

I expected this to work.

### What did you see instead?

HTTPS redirect rule had priority over the internal Traefik let's encrypt router, which had a priority of only 23 (!!).
I worked around this by lowering the priority of my HTTPS redirect:

      traefik.http.routers.domain-cloud.priority: 20

I would like to set Traefik let's encrypt router (acme-http-bypass) to something higher (100.000), but couldn't find a way to do so.

### What version of Traefik are you using?

Version:      3.4.1
Codename:     chaource
Go version:   go1.23.9
Built:        2025-05-27T12:45:16Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

Already pasted before.

**Comment by lbenguigui** [comment]
Hey @IngLP ,

Thanks for your interest in Traefik.

The `allowACMEBypass` option allows users to define a custom router to handle ACME challenges. 
When enabled, it means that the router automatically created by Traefik for ACME challenges won’t have a higher priority than user-defined routers.

By default, router priority is based on the length of the rule: in your case, your rule is longer than the one used by the ACME challenge router, which gives it higher priority.

However,  you haven’t defined a custom router to handle the ACME challenge, making `allowACMEBypass` ineffective. 
If you don’t need to customize the challenge handling, I recommend disabling this option. 
This will allow Traefik to assign a higher priority to its internal ACME router automatically, and you won’t need to manually lower the priority of your own router.

Let me know if this solves your issue.

**Comment by IngLP** [comment]
Hi, I need allowACMEBypass because Traefik also serves as proxy to a specific host that needs to issue its own let's encrypt cert, and it only supports HTTP-01 challenge. That's why I need it. (there are also other websites and hosts behind traefik)
Now, how do I set a priority for that router? I was't able to do that
Thanks

**Comment by nmengin** [comment]
Hey @IngLP,

Thanks for the additional information.

We are interested in this issue, but we’re unsure about the use case and the traction it will receive.
We are going to leave the status as kind/proposal to give the community time to let us know if they would like this idea.
We will reevaluate as people respond.

Conversation is time-boxed to 6 months.

**Comment by IngLP** [comment]
I'm not sure I understand. @lbenguigui  said "However, you haven’t defined a custom router to handle the ACME challenge,", how do I define such a router?
@nmengin in the mean time, is there any other workaround? only forcing the conflicting routers a lower priority than 23?

**Comment by lbenguigui** [comment]
Hey @IngLP ,

My point was about your initial issue:
 _"One domain is from a provider that is not supported (Aruba). I want to use HTTP-01 challenge for that."_

In the configuration you provided, only `domain.cloud` was linked to `le-http`, and since `allowACMEBypass` is set to `true`, I expected to see a dedicated router handling the HTTP-01 challenge.

This kind of router can be configured like any other. Here's an example:
```
labels:
  traefik.enable: true

  # Dedicated HTTP Challenge router
  traefik.http.routers.lehttp.entrypoints: web
  traefik.http.routers.lehttp.rule: PathPrefix(`/.well-known/acme-challenge/`)
  traefik.http.routers.lehttp.priority: 1000

  # HTTP router
  traefik.http.routers.domain-cloud.entrypoints: web
  traefik.http.routers.domain-cloud.rule: Host(`domain.cloud`) || Host(`www.domain.cloud`)
  traefik.http.routers.domain-cloud.middlewares: domain-cloud-redirect

  # Redirection
  traefik.http.middlewares.domain-cloud-redirect.redirectscheme.scheme: https
  traefik.http.middlewares.domain-cloud-redirect.redirectscheme.permanent: true

  # HTTPS router
  traefik.http.routers.domain-cloud-tls.entrypoints: websecure
  traefik.http.routers.domain-cloud-tls.rule: Host(`domain.cloud`) || Host(`www.domain.cloud`)
  traefik.http.routers.domain-cloud-tls.tls: true
  traefik.http.routers.domain-cloud-tls.tls.certresolver: le-http
  traefik.http.routers.domain-cloud-tls.middlewares: domain-cloud-headers

  # Headers
  traefik.http.middlewares.domain-cloud-headers.headers.customrequestheaders.X_FORWARDED_PROTO: https

  # Service
  traefik.http.services.domain-cloud.loadbalancer.server.port: 3000
  traefik.http.services.domain-cloud.loadbalancer.server.scheme: http
  traefik.http.services.domain-cloud.loadbalancer.passHostHeader: true
```
In this configuration, Let's Encrypt calls will reach your backend, which is what `allowACMEBypass: true` is meant for.

I hope that's clear. Let me know if you need anything else!
