### ISSUE TITLE
ERR Router uses a nonexistent certificate resolver - multiple cert resolvers

### ISSUE THREAD

**Issue by meppss** [traefik/traefik#11822]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hi all! Hoping I can get some help here. I'm using docker-compose to fully build out the traefik configuration and I'd like to maintain all of this as dynamic config using the command section. 

Below I'll include the docker-compose snippet for traefik. I've also confirmed that the letsencrypt and stepca directories are configured in parity and that the stepca acme file is successfully generated. 

GOAL: I'd like to have multiple resolvers such that only services that I require to be public facing are granted a letsencrypt cert w/ cloudflare  FQDN, otherwise I'd like to associate my private CA certs to the instance. I've already confirmed the appropriate labels as set for the instance leveraging cloudflare and letsencrypt. I am also using cloudflare tunnels to access the public services. 

Appreciate any assistance I can get here!

-----
The error I receive after the container initializes is this:
```
$ docker-compose logs -f traefik
Attaching to docker_traefik_1
traefik_1      | 2025-06-06T02:30:17Z ERR Router uses a nonexistent certificate resolver certificateResolver=letsencrypt routerName=n8n-external@docker
```

### What did you see instead?

traefik_1      | 2025-06-06T02:49:49Z ERR github.com/traefik/traefik/v3/cmd/traefik/traefik.go:384 > Router uses a nonexistent certificate resolver certificateResolver=letsencrypt routerName=n8n-external@docker

### What version of Traefik are you using?

$ docker-compose logs -f traefik
Attaching to docker_traefik_1
traefik_1      | 2025-06-06T02:30:17Z ERR Router uses a nonexistent certificate resolver certificateResolver=letsencrypt routerName=n8n-external@docker

$ docker-compose exec traefik traefik version
Version:      3.4.1
Codename:     chaource
Go version:   go1.23.9
Built:        2025-05-27T12:45:16Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

docker-compose snippet
```
  traefik:
    image: "traefik:v3.4"
    restart: always
    depends_on:
      step-ca:
        condition: service_healthy
    healthcheck:
        test: ["CMD", "traefik", "version"]
        interval: 10s
        retries: 3
    environment:
      - CF_DNS_API_TOKEN=${CF_API_TOKEN}
    command:
      # Enable Debug logging
      #- "--log.level=DEBUG"
      # Enable Traefik dashboard securely
      - "--api.dashboard=true"
      - "--api.insecure=false"
      # Enable Docker as configuration provider
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Define HTTP entrypoint and redirect to HTTPS
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # Step CA resolver for internal services
      - "--certificatesresolvers.stepca.acme.tlschallenge=true"
      - "--certificatesresolvers.stepca.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.stepca.acme.storage=/cert_resolvers/stepca/acme-stepca.json"
      - "--certificatesresolvers.stepca.acme.caserver=https://step-ca:9000/acme/acme/directory"
      # Trust Step CA root cert
      - "SSL_CERT_FILE=/etc/ssl/certs/root_ca.crt"
      # Let’s Encrypt resolver ONLY for public certs (n8n)
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=10"
      - "--certificatesresolvers.letsencrypt.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/cert_resolvers/letsencrypt/acme-letsencrypt.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './traefik/configs:/cert_resolvers'
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CA_CERT_PATH}:/etc/ssl/certs/root_ca.crt:ro
    networks:
      - internal
    labels:
    # Secure Traefik dashboard access via HTTPS
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.tls.certresolver=stepca"
```

Relevant service I'd like to put a public CA on via letsencrypt and cloudflare
```
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    depends_on:
      traefik:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      # Common service definition
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      # External HTTPS (via Cloudflare + Let's Encrypt)       
      - "traefik.http.routers.n8n-external.rule=Host(`n8n.${PUB_DOMAIN_NAME}`)"
      - "traefik.http.routers.n8n-external.entrypoints=websecure"
      - "traefik.http.routers.n8n-external.tls=true"
      - "traefik.http.routers.n8n-external.tls.certresolver=letsencrypt"
      - "traefik.http.routers.n8n-external.middlewares=n8n-headers@docker"
      # Internal HTTPS (via Step CA)
      - "traefik.http.routers.n8n-internal.rule=Host(`n8n.${DOMAIN_NAME}`)"
      - "traefik.http.routers.n8n-internal.entrypoints=websecure"
      - "traefik.http.routers.n8n-internal.tls=true"
      - "traefik.http.routers.n8n-internal.tls.certresolver=stepca"
      - "traefik.http.routers.n8n-internal.middlewares=n8n-headers@docker"
      # Middlewares for security headers, including forcing SSL redirect. Shared for internal/external routers.
      - "traefik.http.middlewares.n8n-headers.headers.SSLRedirect=true"
      - "traefik.http.middlewares.n8n-headers.headers.STSSeconds=315360000"
      - "traefik.http.middlewares.n8n-headers.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.n8n-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.n8n-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.n8n-headers.headers.SSLHost=${PUB_DOMAIN_NAME}"
      - "traefik.http.middlewares.n8n-headers.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.n8n-headers.headers.STSPreload=true"
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME} # Hostname n8n will use internally
      - N8N_PORT=5678                        # Internal port (default n8n port)
      - N8N_PROTOCOL=https                   # Because Traefik handles TLS termination
      - NODE_ENV=production                  # Production mode
      - WEBHOOK_URL=https://${SUBDOMAIN}.${PUB_DOMAIN_NAME}/       # Public webhook URL for n8n
      - GENERIC_TIMEZONE=${TZ}                                 # Timezone from env var (e.g. America/New_York)
    volumes:
      - './n8n/configs:/home/node/.n8n'
      - ./local-files:/files
    networks:
      - internal
```

### If applicable, please paste the log output in DEBUG level

attached in a file since the output is a bit long. 

[traefik-debug-logs.txt](https://github.com/user-attachments/files/20621093/traefik-debug-logs.txt)
