### ISSUE TITLE
two traefik instances (one with ingressClass, one without) both take ownership of Ingress with ingressClassNameSet

### ISSUE THREAD

**Issue by youngderekm** [traefik/traefik#11820]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have two instances of traefik setup in a Kubernetes cluster (installed via helm).  One, `traefik` is the default and has `providers.kubernetes.ingress.ingressClass` unset.  It should handle Ingress objects with `ingressClassName` unset, or set to `traefik` according to the doc.  The other, `traefik-prod` has `providers.kubernetes.ingress.ingressClass` set to `traefik-prod` and should only handle Ingress with `ingressClassName` set to `traefik-prod`.  I have an Ingress with `ingressClassName: traefik-prod`.  The default, `traefik`, should ignore the ingress while the `traefik-prod` should route traffic for the Ingress. 

### What did you see instead?

The `traefik` installation (with `providers.kubernetes.ingress.ingressClass` unset) sees the Ingress (named `kyk-live-dashboard`) with ingressClassName set to `traefik-prod`.  It starts logging messages about it, leading to a stream of error messages from both instances of traefik, referencing the same Ingress.

```
2025-06-05T17:04:25Z ERR Error while updating ingress status error="failed to update ingress status kyk-live-dashboard/live-dashboard: Operation cannot be fulfilled on ingresses.networking.k8s.io \"live-dashboard\": the object has been modified; please apply your changes to the latest version and try again" ingress=live-dashboard namespace=kyk-live-dashboard providerName=kubernetes
```

It shows up in the dashboards for both `traefik` and `traefik-prod`.

dashboard for traefik instance:

![Image](https://github.com/user-attachments/assets/329f847d-bbc8-424e-b9e2-435390aa9a20)

dashboard for traefik-prod instance:

![Image](https://github.com/user-attachments/assets/69351205-95ff-47bb-82ff-6b1e9ebd4060)

### What version of Traefik are you using?

Both instances of traefik in the cluster are running 3.3.4 (helm chart version 34.5.0).

### What is your environment & configuration?

traefik:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 34.5.0
  interval: 15m
  releaseName: traefik
  serviceAccountName: flux
  timeout: 5m
  values:
    deployment:
      replicas: 2
    ports:
      web:
        expose:
          default: true
        exposedPort: 80
        port: 8000
        protocol: TCP
        redirections:
          entryPoint:
            permanent: true
            scheme: https
            to: websecure
        tls:
          enabled: false
      websecure:
        expose:
          default: true
        exposedPort: 443
        port: 8443
        protocol: TCP
        tls:
          enabled: true
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
        enabled: true
      kubernetesIngress:
        allowExternalNameServices: true
        enabled: true
        publishedService:
          enabled: true
    service:
      annotations:
        metallb.universe.tf/address-pool: reserved-traefik
      spec:
        externalTrafficPolicy: Local
```

traefik-prod:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-prod
  namespace: traefik-prod
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 34.5.0
  interval: 15m
  releaseName: traefik-prod
  serviceAccountName: flux
  timeout: 5m
  values:
    deployment:
      replicas: 5
    ingressClass:
      enabled: true
      isDefaultClass: false
      name: traefik-prod
    ports:
      web:
        expose:
          default: true
        exposedPort: 80
        port: 8000
        protocol: TCP
        redirections:
          entryPoint:
            permanent: true
            scheme: https
            to: websecure
        tls:
          enabled: false
      websecure:
        expose:
          default: true
        exposedPort: 443
        port: 8443
        protocol: TCP
        tls:
          enabled: true
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
        enabled: true
        ingressClass: traefik-prod
      kubernetesIngress:
        allowExternalNameServices: true
        enabled: true
        ingressClass: traefik-prod
        publishedService:
          enabled: true
    service:
      annotations:
        metallb.universe.tf/address-pool: reserved-traefik-prod
      spec:
        externalTrafficPolicy: Local
```

Ingress live-dashboard:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: live-dashboard
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: traefik-prod
  rules:
    - host: "live.${R9_INGRESS_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: live-dashboard
                port:
                  number: 80
    - host: "live.runwaynine.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: live-dashboard
                port:
                  number: 80
    - host: "live.kp4.runwaynine.com"
      http:
        paths:
          - path: /elastic
            pathType: Prefix
            backend:
              service:
                name: kibana-external
                port:
                  number: 443
    - host: "live.runwaynine.com"
      http:
        paths:
          - path: /elastic
            pathType: Prefix
            backend:
              service:
                name: kibana-external
                port:
                  number: 443
  tls:
    - hosts:
        - live.kp4.runwaynine.com
        - live.runwaynine.com
      secretName: live-dashboard-tls
```
