### ISSUE TITLE
Health check on traefik 3.4.1 is not working

### ISSUE THREAD

**Issue by ghevge** [traefik/traefik#11836]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I just migrated from traefik 2.11 to 3.4.1 and I have noticed that the healthcheck mechanism is not working anymore.

I am in a docker-compose environment, and I am using labels to configure my system:

 ```
       - traefik.http.services.jira-secure.loadbalancer.server.port=8080
      - traefik.http.services.jira-secure.loadbalancer.healthcheck.path=/status
      - traefik.http.services.jira-secure.loadbalancer.healthcheck.interval=60s
      - traefik.http.services.jira-secure.loadbalancer.healthcheck.timeout=11s
```

I have noticed that with  3.4.1, no matter what I assign in the port and path labels , traefik will always show green status, even if the port or the path is invalid. 

I noticed there is a similar bug opened but only refers to a swarm environment. I am seeing the behavior in a docker-compose environment.

https://github.com/traefik/traefik/issues/11604

### What did you see instead?

Traefik 3.4.1 always shows green status, never shows red status.

### What version of Traefik are you using?

FROM traefik:3.4.1

### What is your environment & configuration?

```
traefik:
    build: traefik
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.watch"
      - "--providers.docker.network=frontend"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.metrics.address=:8082"
      - "--certificatesresolvers.myorg.acme.httpchallenge=true"
      - "--certificatesresolvers.myorg.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.myorg.acme.storage=acme.json"
      - "--certificatesresolvers.myorg.acme.caserver=<my caserver>"
      - "--log"
      - "--log.level=INFO"
      - "--log.format=json"
      - "--api"
      - "--api.dashboard"
      - "--api.insecure"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entrypoint=metrics"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--metrics.prometheus.addrouterslabels=true"
      - "--accessLog.format=json"
      - "--accesslog.bufferingsize=100"
      - "--accessLog.filters.statusCodes=200-201,400,500"
      - "--accessLog.filters.retryAttempts=true"
      - "--accessLog.filters.minDuration=400ms"
      - "--accesslog.fields.defaultmode=drop"
      - "--accesslog.fields.names.RequestHost=keep"
      - "--accesslog.fields.names.RequestMethod=keep"
      - "--accesslog.fields.names.RequestPath=keep"
      - "--accesslog.fields.names.DownstreamStatus=keep"
      - "--accesslog.fields.names.Duration=keep"
      - "--accesslog.fields.names.RetryAttempts=keep"
      - "--accesslog.fields.headers.defaultmode=drop"
      - "--accesslog.fields.headers.names.Content-Type=keep"
      - "--accesslog.fields.headers.names.X-Ausername=keep"
      - "--experimental.plugins.blockpath.moduleName=github.com/traefik/plugin-blockpath"
      - "--experimental.plugins.blockpath.version=v0.2.1"
    depends_on:
      - step
    entrypoint:
      [
        "dockerize",
        "-wait",
        "<my health path>",
        "-timeout",
        "300s",
        "-wait-retry-interval",
        "10s",
        "traefik",
      ]

    environment:
      LEGO_CA_CERTIFICATES: /etc/ssl/traefik/root_ca.crt
    image: traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.middlewares.dashboard-redirect-secure.redirectscheme.scheme=https
      - traefik.http.routers.dashboard-secure.entrypoints=https
      - traefik.http.routers.dashboard-secure.rule=Host(`${TRAEFIK_DNS_NAME}`)
      - traefik.http.routers.dashboard-secure.tls.domains[0].main=${TRAEFIK_DNS_NAME}
      - traefik.http.routers.dashboard-secure.tls=true
      - traefik.http.routers.dashboard-secure.tls.certresolver=<my resolver>
      - traefik.http.routers.dashboard.entrypoints=http
      - traefik.http.routers.dashboard.middlewares=dashboard-redirect-secure
      - traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DNS_NAME}`)
      - traefik.http.services.dashboard-secure.loadbalancer.server.port=8080
      - traefik.http.middlewares.loki-auth.basicauth.users=${MONITORING_AUTH_USER}:${MONITORING_AUTH_HASHED_PASSWORD}
    logging:
      driver: loki
      options:
        loki-url: http://127.0.0.1:18080/loki/api/v1/push
        mode: non-blocking
        max-buffer-size: 4m
        loki-retries: 3
        loki-tls-insecure-skip-verify: "true"
        loki-relabel-config: |
          - action: labelmap
            regex: swarm_stack
            replacement: namespace
          - action: labelmap
            regex: swarm_(service)
          - action: labelmap
            regex: compose_project
            replacement: namespace
          - action: labelmap
            regex: compose_(service)
        loki-pipeline-stages: |
          - json:
              expressions:
                level: level
                time: time
                msg: msg
                path: RequestPath
                status: DownstreamStatus
                method: RequestMethod
                router: RouterName
          - labels:
              level:
              status:
              method:
          - timestamp:
              source: time
              format: RFC3339Nano
          - tenant:
              value: "docker"
        loki-external-labels: container_name={{.Name}},environment=${ENV_TYPE}
    networks:
      application:
        aliases:
          - ${JIRA_DNS_NAME}
          - ${DMR_DNS_NAME}
          - ${TRAEFIK_DNS_NAME}
          - ${LABEL_SERVICE_DNS_NAME}
          - ${CONFLUENCE_INTEGRATION_DNS_NAME}
      frontend: null
      monitoring:
        aliases:
          - ${GRAFANA_DNS_NAME}
          - ${PROMETHEUS_DNS_NAME}
          - ${LOKI_DNS_NAME}
      loki:
        aliases:
          - ${LOKI_DNS_NAME}
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
      - 0.0.0.0:8080:8080
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    secrets:
      - MONITORING_USER
      - MONITORING_PASSWORD
```
