### ISSUE TITLE
Option to consider certificate expiry for calculation of renewal durations

### ISSUE THREAD

**Issue by git-developer** [traefik/traefik#11843]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### Context
Traefik triggers TLS certificate generation via ACME using a custom CA (e.g. step-ca).

<details>
  <summary><code>traefik.yaml</code></summary>

```yaml
certificatesResolvers:
  tlschallenge:
    acme:
      caServer: https://ca.lan/acme/acme/directory
      email: admin@local.lan
      storage: /etc/traefik/acme.json
      tlsChallenge: {}
      certificatesDuration: 24 # this duration must be explicitely set matching the CA's behavior
```
</details>

<details>
  <summary><code>compose.yml</code></summary>

```yaml
---
services:
  demo-service:
    ...
    labels:
      - traefik.enable=true
      - traefik.http.routers.demo.rule=Host(`demo.lan`)
      - traefik.http.routers.demo.tls.certResolver=tlschallenge
      - traefik.http.services.demo.loadbalancer.server.port=80
```
</details>

### Problem
When the value of `certificatesDuration` is not set according to the CA in the static traefik configuration, a validity of 90 days is assumed. This behavior can **cause a certificate to expire before traefik attempts to renew it**. For operators, this requirement and behavior is not easy to understand: traefik doesn't automatically renew certificates after their expiry, and the logs do not contain anything about the cause.

### Suggestion
1. On creation and renewal of a certificate, traefik inspects the expiry of the certificate and uses _actualDuration = min(`certificatesDuration`, expiry - now)_ to [calculate renew durations](https://doc.traefik.io/traefik/https/acme/#certificatesduration) (Renew Period & Renew Interval).
2. When _actualDuration_ differs from `certificatesDuration`, a message is added to the log.
