### ISSUE TITLE
[kubernetes gateway-api] Resolve gateway api listener ports to real ports instead of internal ones

### ISSUE THREAD

**Issue by cwrau** [traefik/traefik#11842]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Currently, when one wants to create a gateway with the default config from the helm chart (websecure internally 8443 but in reality 443), one needs to configure the listener port to be `8443`, which is semi-incorrect but at least unintuitive, as in every way that matters to the user it's really `443`.

It would be great if one could configure some kind of `realPort: 443`, or some kind of alias, ... to make this more user friendly.

**Comment by nmengin** [comment]
Hey @cwrau,

Thank you for reaching out.
From what I understand, you would like an option in the Helm chart to open port 443?

**Comment by cwrau** [comment]
> Hey [@cwrau](https://github.com/cwrau),
> 
> Thank you for reaching out. From what I understand, you would like an option in the Helm chart to open port 443?

Not directly, it's perfect that traefik doesn't use ports <1000 by default and I wouldn't want that anyways.

I'd like to have some sort of mapping between the "physical" port traefik opens (8443) and the "real" port in the LoadBalancer (443).

Essentially currently one needs to write a gateway this way;

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
spec:
  listeners:
  - name: https
    protocol: HTTPS
    port: 8443 <-
```

while the user actually would like to, and intuitively would, write the following;

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
spec:
  listeners:
  - name: https
    protocol: HTTPS
    port: 443 <-
```

Also, because `8443` is kind of an implementation detail, I'd like to hide this from the users
