### ISSUE TITLE
Option for multiple GatewayClass Controllers

### ISSUE THREAD

**Issue by bavarianbidi** [traefik/traefik#11851]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

## feature

If I want to expose different services via the gateway-API it would be nice to create multiple `GatewayClasses`.
For each `GatewayClass` I want to have dedicated instances for traefik running.

In https://github.com/traefik/traefik/issues/11661#issuecomment-2783350465 a user requested something similar

> > Sounds like if I wanted multiple Gateways with Traefik currently, I would need to deploy multiple Traefik instances and ensure they are each different GatewayClasses.

and got the following response from @kevinpollet 

> Multiple Gateway definitions can be handled by only one Traefik instance.

Therefore I'm not sure if this is a valid feature request.
To understand the limitations and possible solutions, I'm currently running two modified traefik instances to fulfill my initial needs - #11850 

## current limitation

ATM, traefik uses a hardcoded value to during the iteration over all `GatewayClass` objects within a cluster to determine the responsibility. https://github.com/traefik/traefik/blob/b39ee8ede5b64e7e1c6e78c276b79d3dd13e7a34/pkg/provider/kubernetes/gateway/kubernetes.go#L40

Therefore it's necessary that all `GatewayClass` CRs having `spec.controllerName` set to `"traefik.io/gateway-controller"`

That means, it's not possible to have multiple `traefik` instances with clear responsibility in one cluster (e.g. one traefik for internet-facing apps and one traefik for intranet-facing apps).

## expectation

It should be possible in the `kubernetesGateway` provider to define the value of the `controllerName`. And with that it will be possible to create different `GatewayClasses`, such as e.g.:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: traefik
spec:
  controllerName: traefik.io/internet-controller
``` 

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: traefik-tailscale
spec:
  controllerName: traefik.io/tailscale-controller
```

## additional notes

Traefik need an additional provider-config flag to define a non-default value, e.g.:
```
--providers.kubernetesgateway.controllerName=traefik.io/tailscale-controller
```
This new configuration-param must be implemented in the official traefik helm chart as well.

I'm volunteering to implement the needed in traefik and in the helm-chart as well.

**Comment by bavarianbidi** [comment]
cc @rtribotte - this is the feature-request which belongs to the draft-PR.
Would be nice to get some kind of feedback if this is something you would like to see.

**Comment by rtribotte** [comment]
@bavarianbidi At first glance, I would add the possibility to select a GatewayClass by its name, in addition to select it by the controllerName.

**Comment by bavarianbidi** [comment]
`controllerName` in GatewayClass is immutable ( just wanted to mention that somewhere 😅 - because I learned that when I run my custom traefik container)

got your point, like the idea, but isn't it a better approach to do it via a label selector?

**Comment by bavarianbidi** [comment]
but also thinking, if it might be confusing as well. `controllerName` from the GatewayClass spec already implies the  _name_ of the controller ( whatever the name might be ) which is responsible for the GatewayClass.

**Comment by rtribotte** [comment]
I'm not sure where the confusion lies.
To be clear, the first way to select a gateway class should be by name. Traefik expecting a given controller name isn't a limitation as long as you only need one gateway class per controller/Traefik instance.

**Comment by rtribotte** [comment]
Hi @bavarianbidi,

We marked this issue as proposal, because we are interested in this issue, but we’re unsure about the use case and the traction it will receive. The status as kind/proposal is here to give the community time to let us know if they would like this idea, and also build how we can implement it.

We will reevaluate as people respond.
Conversation is time-boxed to 6 months.

**Comment by bavarianbidi** [comment]
Hey @rtribotte thanks for the update. Totally fine with that.
In the meantime I took a short look into the `cilium` and `nginx-gateway-fabric` implementation to check if probably myself is doing GatewayAPI wrong 😅 

raised that question also in kubernetes-slack: https://kubernetes.slack.com/archives/CR0H13KGA/p1751291305820339

tl;dr:
`cilium` behaves same like `traefik`. Only `nginx-gateway-fabric` has a flag to define a custom controllerName:

* [cilium code where ](https://github.com/cilium/cilium/blob/57ac77bdba4344c981a36a9e27c77f87a948f95e/operator/pkg/gateway-api/gateway_reconcile.go#L78-L82)`controllerName`[ must match their constant](https://github.com/cilium/cilium/blob/57ac77bdba4344c981a36a9e27c77f87a948f95e/operator/pkg/gateway-api/gateway_reconcile.go#L78-L82)
* [nginx-gateway-fabric code where controllerName can be set for the controller itself](https://github.com/nginx/nginx-gateway-fabric/blob/5daf12e7a3d0611796683884ee8c9a5649d419a7/cmd/gateway/commands.go#L270-L275)

**Comment by gclark125** [comment]
Hi
Got bitten by this today. We have a cluster with separate network interfaces with connectivity to devices with different levels of trust  hence don't want TLS termination and decryption in a common traefik instance. We were trying to be future looking using GatewayClass. If I revert to using Ingress for now can I run the 3 traefiks attached to 3 networks that I desire or will I hit a similar issue ?

**Comment by gclark125** [comment]
> Hi Got bitten by this today. We have a cluster with separate network interfaces with connectivity to devices with different levels of trust hence don't want TLS termination and decryption in a common traefik instance. We were trying to be future looking using GatewayClass. If I revert to using Ingress for now can I run the 3 traefiks attached to 3 networks that I desire or will I hit a similar issue ?

For reference I believe I have achieved the behaviour I desired via the helm chart values gatewayClass.labels.app=traefik-instance-n  and providers.kubernetesGateway.labelselector="app=traefik-instance-n". I've had to apply this to pre-existing traefik deployments and GatewayClasses as well.

**Comment by lutcmoi** [comment]
Hello,
I am setting up my homelab and separating the gateway entry for internet and the gateway entry for internal use is very important.
So I am also very interested to be able to deploy two gateways on two gateway-controllers.
Any progress on this improvement?
Best regards.

**Comment by kevinpollet** [comment]
Hello,

We discussed this today and think a new option should be introduced that tells a Traefik instance to handle only one GatewayClass by name. This new option could be named `GatewayClass` to be consistent with the Ingress provider.

**Comment by thirdeyenick** [comment]
@kevinpollet Can you explain the difference to the way suggested in https://github.com/traefik/traefik/issues/11851#issuecomment-3033112192 by using a label selector for the gateway classes?

**Comment by Routhinator** [comment]
Demonstrating two non-colliding installs of Gateway controllers using Flux HelmRelease

Internal:
```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "37.4.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: cluster-conf
  install:
    crds: Skip
  values:
    commonLabels:
      traefik.io/controller: internal
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`localhost`)
        entryPoints:
          - web
    gatewayClass:
      enabled: true
      name: "traefik"
    ingressClass: # @schema additionalProperties: false
      enabled: true
      isDefaultClass: true
      name: "traefik"
    providers:
      kubernetesCRD:
        enabled: true
        allowExternalNameServices: true
        ingressClass: "traefik"
        labelSelector: "traefik.io/controller=internal"
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        ingressClass: "traefik"
      kubernetesGateway:
        enabled: true
        experimentalChannel: false
        statusAddress:
          ip: "192.168.2.11"
          service:
            enabled: true
            name: traefik
            namespace: traefik
        labelselector: "traefik.io/controller=internal"
      kubernetesIngressNginx:
        enabled: true
        ingressClassByName: true
        controllerClass: "k8s.io/ingress-nginx"
        ingressClass: "nginx"
    gateway:
      enabled: true
      name: traefik
      namespace: traefik
      listeners:
        web:
          namespacePolicy:
            from: All
    service:
      enabled: true
      single: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 192.168.2.11
    logs:
      access:
        enabled: true
        format: json

    additionalArguments:
      - --serverstransport.insecureskipverify=true

    metrics:
      prometheus:
        serviceMonitor:
          enabled: true
          jobLabel: traefik
          metricRelabelings:
            - action: replace
              sourceLabels:
                - "exported_service"
              regex: "(.*)"
              replacement: "$1"
              targetLabel: "service"
        prometheusRule:
          enabled: true
          rules:
            - alert: TraefikDown
              expr: up{job="traefik"} == 0
              for: 5m
              labels:
                context: traefik
                severity: warning
              annotations:
                summary: "Traefik Down"
                description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"

```

External:
```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-external
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "37.4.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: cluster-conf
  install:
    crds: Skip
  values:
    commonLabels:
      traefik.io/controller: external
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`localhost`)
        entryPoints:
          - web
    gatewayClass:
      enabled: true
      name: "traefik-external"
    ingressClass: # @schema additionalProperties: false
      enabled: true
      isDefaultClass: false
      name: "traefik-external"
    providers:
      kubernetesCRD:
        enabled: true
        allowExternalNameServices: true
        ingressClass: "traefik-external"
        labelSelector: "traefik.io/controller=external"
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        ingressClass: "traefik-external"
      kubernetesGateway:
        enabled: true
        experimentalChannel: false
        statusAddress:
          ip: "192.168.2.12"
          service:
            enabled: true
            name: traefik-external
            namespace: traefik-external
        labelselector: "traefik.io/controller=external"
      kubernetesIngressNginx:
        enabled: true
        ingressClassByName: true
        controllerClass: "k8s.io/external-ingress-nginx"
        ingressClass: "external-nginx"
    gateway:
      enabled: true
      name: traefik-external
      namespace: traefik-external
      listeners:
        web:
          namespacePolicy:
            from: All
    service:
      enabled: true
      single: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 192.168.2.12
    logs:
      access:
        enabled: true
        format: json

    additionalArguments:
      - --serverstransport.insecureskipverify=true

    metrics:
      prometheus:
        serviceMonitor:
          enabled: true
          jobLabel: traefik-external
          metricRelabelings:
            - action: replace
              sourceLabels:
                - "exported_service"
              regex: "(.*)"
              replacement: "$1"
              targetLabel: "service"
        prometheusRule:
          enabled: true
          rules:
            - alert: TraefikDown
              expr: up{job="traefik-external"} == 0
              for: 5m
              labels:
                context: traefik
                severity: warning
              annotations:
                summary: "Traefik Down"
                description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"

```

Gateways are now bound to the proper service LB in a stable manner, whereas before the IPs were flopping back and forth.

```console

routhinator@routhinator-desktop [17:24:12] [~/projects/routh-forgejo/routh-ca/cluster-config] [main]
-> % kubectl get gateways --all-namespaces                                                                                                                                                (⎈|kubernetes-admin@red-squadron:default) 
NAMESPACE          NAME               CLASS              ADDRESS        PROGRAMMED   AGE
traefik-external   traefik-external   traefik-external   192.168.2.12   True         70m
traefik            traefik            traefik            192.168.2.11   True         70m

routhinator@routhinator-desktop [17:24:14] [~/projects/routh-forgejo/routh-ca/cluster-config] [main]
-> % kubectl get gatewayclasses                                                                                                                                                           (⎈|kubernetes-admin@red-squadron:default) 
NAME               CONTROLLER                      ACCEPTED   AGE
traefik            traefik.io/gateway-controller   True       70m
traefik-external   traefik.io/gateway-controller   True       70m

```
