### ISSUE TITLE
Rancher provider host rules do not match documentation

### ISSUE THREAD

**Issue by kelchm** [traefik/traefik#1222]
### What version of Traefik are you using (`traefik version`)?
Traefik: v1.2.0-rc2 / morbier
Rancher: v1.4.1

### What is your environment & configuration (arguments, toml...)?
**docker-compose.yml**
```yaml
version: '2'
services:
  traefik:
    image: traefik:v1.2.0-rc2
    stdin_open: true
    tty: true
    ports:
    - 80:80/tcp
    - 443:443/tcp
    - 8080:8080/tcp
    command:
    - --web
    - --rancher
    - --rancher.domain=development.cluster.rancher.foo.com
    - --rancher.endpoint=https://ui.cluster.rancher.foo.com
    - --rancher.accesskey=...
    - --rancher.secretkey=...
    - --logLevel=DEBUG
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
```

### What did you do?
Spun up a test service with the following configuration:

**Stack Name:** test-server-mbk-ft-job-names

**docker-compose.yml**
```yaml
version: '2'
services:
  web:
    image: utzqf/test-server:mbk-ft-job-names
    stdin_open: true
    tty: true
    labels:
      traefik.port: '5000'
      traefik.enable: 'true'
      traefik.domain: development.cluster.rancher.foo.com
      io.rancher.container.pull_image: always
      io.rancher.service.external_dns: always
```

### What did you expect to see?
Ideally, I'd want to see a host rule matching Rancher's standard format: `Host:web.test-server-mbk-ft-job-names.development.cluster.rancher.foo.com`

The [Rancher provider documentation](https://github.com/containous/traefik/blob/v1.2/docs/toml.md#rancher-backend) states that the default is `Host:{containerName}.{domain}`, meaning I would expect a rule like this: `Host:test-server-mbk-ft-job-names-web-1.development.cluster.rancher.foo.com`

### What did you see instead?
The resulting host rule was:  `Host:test-server-mbk-ft-job-names.web.development.cluster.rancher.foo.com`

(The stack name is being prepended to the service name.)
