### ISSUE TITLE
Security: Container fail and users are redirected to administration backend (eg with Jenkins)

### ISSUE THREAD

**Issue by w3blogfr** [traefik/traefik#1314]
### What version of Traefik are you using (`traefik version`)?
I use docker image  traefik:1.2.0-rc2

### What is your environment & configuration (arguments, toml...)?

```toml
[web]
address = ":8080"

[docker]
domain = "docker.localhost"
watch = true
exposedbydefault = false
```

in docker-compose
```yml
 jenkins:
  image: jenkins:2.32.3
  labels:
   - "traefik.enable=true"
   - "traefik.backend=jenkins"
   - "traefik.frontend.rule=Host:jenkins.localhost.loc"
   - "traefik.port=8080"
```

### What did you do?

I use traefik as front of differente container. I have a container.

I have a container jenkins who fail, and container is stopped quickly.

In this case traefik show this url in backend : http://:8080
![image](https://cloud.githubusercontent.com/assets/2735852/24076400/ac57ab2c-0c2f-11e7-8a2b-cd204d6ed2ba.png)

### What did you expect to see?

If I go to url jenkins.localhost.loc with port 80, I'm expect a failure.
500 server error,
503 bad gateway
or 404 not found

### What did you see instead?

If I go on url jenkins.localhost.loc with port 80, I redirect to traefik monitoring page,
