### ISSUE TITLE
Kubernetes container arg consul.endpoint defaults back to 127.0.0.1 when Consul KV store has a /traefik/consul key present

### ISSUE THREAD

**Issue by BrandonPotter** [traefik/traefik#1372]
### What version of Traefik are you using (`traefik version`)?

Traefik version v1.2.1 built on 2017-03-27_03:19:40PM

### What is your environment & configuration (arguments, toml...)?

Kubernetes Deploy YAML:

```yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - name: traefik
          image: traefik
          args:
            - --consul
            - --consul.endpoint=consul-service.default.svc.cluster.local:8500
            - --logLevel=DEBUG
            - --web
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 8080
```

### What did you do?

Added a `/traefik/consul/watch` key to Consul KV store

### What did you expect to see?

Expected the consul `watch` parameter to change but nothing else.

### What did you see instead?

Traefik defaults the `consul.endpoint` back to 127.0.0.1.

### If applicable, please paste the log output in debug mode (`--debug` switch)

`kubectl logs traefik-684991098-96fgm`
```shell
time="2017-04-01T05:53:13Z" level=info msg="Traefik version v1.2.1 built on 2017-03-27_03:19:40PM" 
time="2017-04-01T05:53:13Z" level=debug msg="Global configuration loaded {\"GraceTimeOut\":10,\"Debug\":false,\"CheckNewVersion\":true,\"AccessLogsFile\":\"\",\"TraefikLo
gsFile\":\"\",\"LogLevel\":\"DEBUG\",\"EntryPoints\":{\"http\":{\"Network\":\"\",\"Address\":\":80\",\"TLS\":null,\"Redirect\":null,\"Auth\":null,\"Compress\":false}},\"C
luster\":{\"Node\":\"d4259539-0d2f-497b-a34f-974de3a8a2d5\",\"Store\":{\"Store\":{},\"Prefix\":\"traefik\"}},\"Constraints\":[],\"ACME\":{\"Email\":\"brandon@x9tech.com\"
,\"Domains\":null,\"Storage\":\"traefik/acme/account\",\"StorageFile\":\"\",\"OnDemand\":true,\"OnHostRule\":false,\"CAServer\":\"\",\"EntryPoint\":\"https\",\"DNSProvide
r\":\"\",\"DelayDontCheckDNS\":0,\"ACMELogging\":true,\"TLSConfig\":null},\"DefaultEntryPoints\":[\"http\"],\"ProvidersThrottleDuration\":2000000000,\"MaxIdleConnsPerHost
\":200,\"InsecureSkipVerify\":false,\"Retry\":null,\"Docker\":null,\"File\":null,\"Web\":{\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"St
atistics\":null,\"Metrics\":null,\"Auth\":null},\"Marathon\":null,\"Consul\":{\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"\",\"Prefix\":\"\",\"TL
S\":null},\"ConsulCatalog\":null,\"Etcd\":null,\"Zookeeper\":null,\"Boltdb\":null,\"Kubernetes\":null,\"Mesos\":null,\"Eureka\":null,\"ECS\":null,\"Rancher\":null}" 
time="2017-04-01T05:53:13Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> Compress:false}" 
time="2017-04-01T05:53:13Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8080\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Statistics\
":null,\"Metrics\":null,\"Auth\":null}" 
time="2017-04-01T05:53:13Z" level=info msg="Starting provider *provider.Consul {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"\",\"Prefix\":\"\",\"
TLS\":null}" 
time="2017-04-01T05:53:13Z" level=info msg="Starting server on :80" 
time="2017-04-01T05:53:13Z" level=debug msg="Node d4259539-0d2f-497b-a34f-974de3a8a2d5 running for election" 
time="2017-04-01T05:53:13Z" level=info msg="Node d4259539-0d2f-497b-a34f-974de3a8a2d5 elected slave ♝" 
time="2017-04-01T05:53:13Z" level=error msg="KV connection error: Failed to test KV store connection: Get http://127.0.0.1:8500/v1/kv/qmslkjdfmqlskdjfmqlksjaz%C3%A7ueznbv
bwzlkajzebvkwjdcqmlsfj?consistent=&wait=30000ms: dial tcp 127.0.0.1:8500: getsockopt: connection refused, retrying in 685.88577ms" 
```
