### ISSUE TITLE
Wrong PathPrefix and URL when in Docker swarm mode

### ISSUE THREAD

**Issue by bintut** [traefik/traefik#1724]
### Do you want to request a *feature* or report a *bug*?

I am reporting a bug.

### What did you do?

I built a Docker image on our base image using RHEL 7.3 with the [Traefik v1.3.0 GNU/Linux AMD64](https://github.com/containous/traefik/releases/download/v1.3.0/traefik_linux-amd64).

### What did you expect to see?

End-to-end HTTP transactions will work fine via Traefik load balancer.

### What did you see instead?

An intermittent HTTP 404, the IP address in the URL is not a valid IPv4 and the PathPrefix is not correct in the access logs.

### Output of traefik version: (_What version of Traefik are you using?_)

[Traefik v1.3.0 GNU/Linux AMD64](https://github.com/containous/traefik/releases/download/v1.3.0/traefik_linux-amd64)

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

- [RHEL Atomic Host v7.3.4](https://access.redhat.com/articles/2317361)
- docker-latest v1.13.1-4
- [Traefik v1.3.0 GNU/Linux AMD64](https://github.com/containous/traefik/releases/download/v1.3.0/traefik_linux-amd64)
- Below are the labels added when I created the Docker services of the backend servers:

```
traefik.backend
traefik.backend.circuitbreaker.expression
traefik.backend.loadbalancer.sticky
traefik.backend.loadbalancer.swarm
traefik.docker.network
traefik.frontend.passHostHeader
traefik.frontend.rule
traefik.port
```
- Below are the contents of my traefik.toml:

```toml
checkNewVersion = false
traefikLogsFile = "/var/log/traefik/traefik.log"
accessLogsFile = "/var/log/traefik/access.log"
logLevel = "INFO"
defaultEntryPoints = ["http","https"]
InsecureSkipVerify = true

[web]
  address = ":8080"
#  CertFile = "/etc/ssl/traefik.crt"  # Commented for Prometheus to work
#  KeyFile = "/etc/ssl/traefik.key"   # Commented for Prometheus to work
    [web.auth.basic]
      users = ["username:$apr1$bjvip@$5W0rDtXWQIDelobtcKDNu0H1"]
    [web.statistics]
      RecentErrors = 10
    [web.metrics]
      [web.metrics.prometheus]
        Buckets=[0.1,0.3,1.2,5.0]

[entryPoints]
  [entryPoints.http]
    address = ":52100"
  [entryPoints.https]
    address = ":52000"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
        certFile = "/etc/ssl/traefik.crt"
        keyFile = "/etc/ssl/traefik.key"

[retry]
  attempts = 3

[docker]
  endpoint = "tcp://master1.example.com:2376" # SPOF; ideally multiple master nodes
  watch = true
  domain = "example.com"
  swarmmode = true
  usebindportip = true

  [docker.tls]
    ca = "/etc/ssl/master1/master1-ca.pem"
    cert = "/etc/ssl/master1/master1-client-cert.pem"
    key = "/etc/ssl/master1/master1-client-key.pem"
```
### If applicable, please paste the log output in debug mode (--debug switch)

```shell
10.255.0.4 - - [08/Jun/2017:13:03:10.255.0.4 - - [08/Jun/2017:13:04:26 +0800] "POST /sprockets/api/v1/product/txn/docs/validate HTTP/1.1" 200 10665 "" "Apache-HttpClient/4.3.6 (java 1.5)" 285 "PathPrefix-sprockets-api-v1-product" "http://172.30.136.16:50100" 5829ms
10.255.0.4 - - [08/Jun/2017:14:41:40 +0800] "GET /sprockets/api/v1/project/console/styles/api-console-light-theme.css HTTP/1.1" 200 117165 "http://10.23.210.17:52100/sprockets/api/v1/project/console/" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E)" 427 "PathPrefix-sprockets-api-v1-c10.255.0.4 - - [08/Jun/2017:14:49:52 +0800] "POST /sprockets/api/v1/product/txn/docs/retrieve HTTP/1.1" 200 6842 "" "Apache-HttpClient/4.3.6 (java 1.5)" 304 "PathPrefix-sprockets-api-v1-product" "http://172.30.136.16:50100" 49ms
10.255.0.4 - - [08/Jun/2017:14:54:54 +0800] "GET /sprockets/api/v1/product/txn/docs/info HTTP/1.1" 404 35 "" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36" 244 "PathPrefix-sprockets-api-v1-product" "http://172.30.1310.255.0.4 - - [08/Jun/2017:14:58:36 +0800] "GET / HTTP/2.0" 200 1474 "" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36" 306 "PathPrefix" "http://172.30.136.168:51200" 3ms
```
