### ISSUE TITLE
Traefik frontend rule with AddPrefix gets the prefix twice when redirecting HTTP to HTTPS

### ISSUE THREAD

**Issue by fabiorauber** [traefik/traefik#1738]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Configured a website using AddPrefix in the frontend rule, listening on both http and https entrypoints, with http entrypoint redirecting all requests to https entrypoint.

### What did you expect to see?

Traefik redirecting all requests from http://www.domain to https://www.domain.

### What did you see instead?

Traefik added the Prefix twice, redirecting to https://www.domain/prefix instead. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.0
Codename:     raclette
Go version:   go1.8.3
Built:        2017-05-31_05:48:42PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Container
```yml
services:
  plone:
    labels:
      traefik.port: 8080
      traefik.enable: true
      traefik.frontend.rule: "Host:www.domain; AddPrefix: /VirtualHostBase/https/www.domain/portal/VirtualHostRoot"
      traefik.acme.domains: www.domain

```
Traefik
```yml
traefik:
  ports:
    - 8000:8080/tcp
    - 80:80/tcp
    - 443:443/tcp
  image: traefik:1.3.0-alpine
  command:
    - "--web"
    - "--entryPoints=Name:http\ Address::80\ Redirect.EntryPoint:https"
    - "--entryPoints=Name:https\ Address::443\ TLS"
    - "--defaultentrypoints=http,https"
    - "--rancher"
    - "--rancher.domain=${RANCHER_DOMAIN}"
    - "--rancher.endpoint=${RANCHER_ENDPOINT}"
    - "--rancher.accesskey=${RANCHER_ACCESSKEY}"
    - "--rancher.secretkey=${RANCHER_SECRETKEY}"
    - "--rancher.exposedbydefault=false"
    - "--acme"
    - "--acme.email=${ACME_EMAIL}"
    - "--acme.storage=/mnt/acme.json"
    - "--acme.entrypoint=https"
    - "--acme.ondemand=true"
    - "--logLevel=INFO"
```

What the backend sees:
```
GET /VirtualHostBase/https/www.domain/portal/VirtualHostRoot/VirtualHostBase/https/www.domain/portal/VirtualHostRoot/ HTTP/1.1" 404 29675 
```
