### ISSUE TITLE
Traefik is not purging old key value pairs or overwriting old config in any KV store for HA

### ISSUE THREAD

**Issue by billykwooten** [traefik/traefik#2093]
### Do you want to request a *feature* or report a *bug*?

BUG

### What did you do?

What I have done is enable consul as my KV store for testing HA, and I uploaded the following below config to the KV store, using the `traefik storeconfig` command.

What I did is enabled http -> https forwarding for the endpoints (you can see it's commented out below in the config). When I commented it out and enabled regular http port 80 endpoints again, and reran the 
 `traefik storeconfig`, traefik was still respecting the http -> https forwarding. 

The issue is that I uploaded the consul config to the KV store which created https endpoint KV pairs, when I commented out the https stuff and re-pushed the config to consul, it didn't purge the old keys.

*EDIT:* This has been seen in almost any HA configuration such as etcd as well.

See config below:

```toml
################################################################
# Global configuration
################################################################

# Enable debug mode
#
# Optional
# Default: false
#
# debug = true

# Traefik logs file
# If not defined, logs to stdout
#
# Optional
#
# traefikLogsFile = "log/traefik.log"

# Log level
#
# Optional
# Default: "ERROR"
#
# logLevel = "ERROR"

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["http"]

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
  [entryPoints.http]
  address = ":80"

#[entryPoints]
#  [entryPoints.http]
#  address = ":80"
#    [entryPoints.http.redirect]
#    entryPoint = "https"
#  [entryPoints.https]
#  address = ":443"



# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields.
#
# Optional
#
# [accessLog]

# Sets the file path for the access log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
#
# Optional
# Default: os.Stdout
#
# filePath = "/path/to/log/log.txt"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
# format = "common"

################################################################
# Web configuration backend
################################################################

# Enable web configuration backend
[web]

# Web administration port
#
# Required
#
address = ":8080"

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
#[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
# Default: "unix:///var/run/docker.sock"
#
# endpoint = "tcp://10.10.10.10:2375"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
#
# Optional
# Default: ""
#
# domain = "docker.localhost"

# Expose containers by default in traefik
#
# Optional
# Default: true
#
# exposedbydefault = true

################################################################
# Consul Catalog configuration backend
################################################################

# Enable Consul Catalog configuration backend
#
# Optional
#
[consulCatalog]

# Consul server endpoint
#
# Required
#
endpoint = "127.0.0.1:8500"

# Default domain used.
#
# Optional
#
#domain = "consul.localhost"

# Prefix for Consul catalog tags
#
# Optional
#
prefix = "traefik"

################################################################
# Consul KV configuration backend
################################################################

# Enable Consul KV configuration backend
#[consul]

# Consul server endpoint
#
# Required
#
endpoint = "127.0.0.1:8500"

# Enable watch Consul changes
#
# Optional
#
watch = true

# Prefix used for KV store.
#
# Optional
#
prefix = "traefik"

# Override default configuration template. For advanced users :)
#
# Optional
#
# filename = "consul.tmpl"

# Enable consul TLS connection
#
# Optional
#
# [consul.tls]
# ca = "/etc/ssl/ca.crt"
# cert = "/etc/ssl/consul.crt"
# key = "/etc/ssl/consul.key"
# insecureskipverify = true
```

### What did you expect to see?

I expected traefik to purge keys that were in the KV store (in this case the https endpoint KV pairs), or at least overwrite the entire config, however traefik kept them there and didn't respect my new config.

### What did you see instead?

The https endpoint stuff was still in the KV store, resulting in traefik still doing http -> https, even though the config I just pushed only had 80 as an endpoint.

### Output of `traefik version`: (_What version of Traefik are you using?_)

Traefik v1.3.8 (running the binary)

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

CentOS 7
Nomad + Consul + Docker

### My workaround

My workaround was to stop the traefik service (aka binary file), and go delete the entire KV store folder for traefik in consul. Once I deleted it and then ran `traefik storeconfig` again. Everything started working as expected.

### Why do we need this

It'd be nice if we could modify our config files and run the storeconfig command and it completely overwrite the current KV configuration. Instead of me having to go to consul, delete the entire folder and repush my configuration.

This could be accomplished numerous ways, one simple way is to delete the entire KV folder and recreate it when we run storeconfig, and/or go through and purge un-used key values compared to the new configuration deltas.
