### ISSUE TITLE
Add field mapping for traefik logs in JSON

### ISSUE THREAD

**Issue by mjeri** [traefik/traefik#2200]
### Do you want to request a *feature* or report a *bug*?

_feature_

### Description

Logrus provides the possibility to specify a `FieldMap` when logging in JSON. With the `FieldMap` it is possible to rename logrus internal fields, like `level` to other names. When running Traefik in for example the google cloud, it is handy to rename `level` to `severity` as this is the required field for StackDriver.

In the configuration this could look like the following:
```toml
[traefikLog]
format="json"
[traefikLog.jsonFieldMap]
level="severity"
```

I wonder whether there would be interest for such a feature by other users of Traefik. @containous/traefik WDYT?
