### ISSUE TITLE
Allow to route to invididual containers (e.g. variable substitution in frontend.rule)

### ISSUE THREAD

**Issue by djtm** [traefik/traefik#2578]
### Summary
Traefik changed the default frontend rule from `Host:{containerName}.{domain}` to `Host:{service}.{project_name}.{domain}` (see https://github.com/containous/traefik/issues/1235). This breaks setups and makes some setups very difficult or impossible (e.g. see https://github.com/containous/traefik/issues/1787): You can't easily attach to individual container. You'd need a manual frontend rule for each container. Or each container would need it's own service name.

### Possible solutions
* Revert change - bad, would break new setups
* Allow manual reverting of the change via config - easy, but limited fix
* Combine both rules: add `Host:{containerId}.{service}.{project_name}.{domain}`  (Rancher: `Host:{containerId}.{serviceName}.{domain}`) for invidual container and `Host:{service}.{project_name}.{domain}` (Rancher: `Host:{serviceName}.{domain}`) for a group of containers. Exposing individual containers could be a config flag: `traefik.<service-name>.exposeIndividualContainerBy=<id|name|false>`
* Allow variable name substitution for variables such as `{containerName} {containerId} {service} {projectName} {domain}`.  `traefik.frontend.rule=Host:{containerName}.{domain}` would actually work as expected.

### What did you do?
I've set a label: `traefik.frontend.rule=Host:{containerName}.{domain}`
My container is called `sampleName`, my domain is `sampleDomain`

### What did you expect to see?
A route to `sampleName.sampleDomain`.

### What did you see instead?
A route to `{containerName}.{domain}`.

**Comment by djtm** [comment]
Actually personally I'd want this in rancher. But docker would be nice, too, of course.

**Comment by redsux** [comment]
Hi,

It could be a nice feature !
For the moment I use a workaround with environment variables substitution in docker-compose...

I'll try to custom [config_container.go](https://github.com/containous/traefik/blob/master/provider/docker/config_container.go#L30) on a fork.
If it works I'll send a PR.

Regards,

**Comment by aantono** [comment]
A templating of default `FrontEndRule` solution has been implemented for Consul via https://github.com/containous/traefik/pull/1565, so a same pattern/approach can be taken here as well. See [`getFrontendRule`](https://github.com/containous/traefik/blob/master/provider/consulcatalog/consul_catalog_config.go#L100)

**Comment by warroyo** [comment]
i noticed this issue upgrading to 1.5.x from 1.4 . this really needs to be configurable at a global level. currently we have integrations with the old naming and 1.5 breaks this.

**Comment by sarahconor** [comment]
I have been also stuck at 1.4, also require a global setting (essentially backwards compatible). I wanted to upgrade to 1.5.x to leverage the backend http basic auth.

**Comment by djtm** [comment]
It seems rancher does not expose the individual containers but only services with containers in them:
https://github.com/containous/traefik/blob/0ea007b26f394013d18d6a3b39305743a7f73be4/provider/rancher/rancher.go#L50

So I think the config would need to split up the individual containers from `service.Containers` and then get their information. But containers only contains and IP address if I read the code correctly. So it seems to be a problem with the metadata supplied by rancher that it doesn't provide more information about individual containers in a service.

**Comment by samdjstevens** [comment]
+1 would be great to see this in

**Comment by SeanHood** [comment]
I have a different use case for this feature. I'd like to run a number of services within a single stack accessible via a different `Path:` rule. Currently I have to set each service with the same `Host:` rule which is okay if I maintain a separate file for each stack or invent some hack with environment variables. Use case would be to have a single compose file that would enable us to spin up a new stack for each PR for testing.

Here's a quick example (Invoked with: `docker stack deploy -c compose.yml dev`):

```yaml
services:
  app:
    image: app
    deploy:
      labels:
        - "traefik.frontend.rule=Host: dev-app.example.com"
  api:
    image: api
    deploy:
      labels:
        - "traefik.frontend.rule=Host: dev-app.example.com"; PathStrip: /api/"
```

What I'd like to do:

```yaml
services:
  app:
    image: app
    deploy:
      labels:
        - "traefik.frontend.rule=Host: Host:{project_name}-{service}.{domain}"
  api:
    image: api
    deploy:
      labels:
        - "traefik.frontend.rule=Host: Host:{project_name}-{service}.{domain}"; PathStrip: /api/"
```

--- 
I'm aware this isn't a support forum but it's vaguely related to this. All of my Host rules come up like `Host:{project_name}-{service}.{domain}` rather than `Host:{service}.{project_name}.{domain}` contrary to what is suggested in #1235. And I'm not sure why. (Traefik v1.7.2 using `traefik:alpine`)
