### ISSUE TITLE
Websocket connection errors in the logs

### ISSUE THREAD

**Issue by eskp** [traefik/traefik#2891]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
Configured 3 backends and 3 frontends - `/`, `/api` and `/wss`. The last one being websocket that, judging by the logs, is having issues connecting to it's backend.

### What did you expect to see?
No errors in the logs. Instead access log with appropriate status code for a successful websocket connection.

### What did you see instead?
I see the following in the logs:

```
proxy.1.goom36mvtfow@ip-10-1-0-20    | time="2018-02-19T16:30:59Z" level=error msg="vulcand/oxy/forward/websocket: Error dialing "dev.cloud": websocket: bad handshake with resp: 200 200 OK" 
proxy.1.goom36mvtfow@ip-10-1-0-20    | 10.0.0.126 - - [19/Feb/2018:16:30:59 +0000] "GET /wss HTTP/1.1" 0 0 - "Go-http-client/1.1" 6512 "websocket" "http://backend:8080" 3ms
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.2
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-12_10:56:31AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[backends]
  [backends.static]
    [backends.static.servers.server1]
    url = "http://frontend:80"

  [backends.backend]
    [backends.backend.servers.server1]
    url = "http://backend:8080"

  [backends.websocket]
    [backends.websocket.servers.server1]
    url = "http://backend:8080"

[frontends]
  [frontends.static]
  backend = "static"
  priority = 1
    [frontends.static.routes.root]
    rule = "Host:dev.cloud;PathPrefix:/"

  [frontends.api]
  backend = "backend"
  passHostHeader = true
  priority = 5
    [frontends.api.routes.api]
    rule = "PathPrefix:/api"

  [frontends.websocket]
  backend = "websocket"
  passHostHeader = true
  priority = 5
  #entrypoints = ["ws"] # overrides defaultEntryPoints
    [frontends.websocket.routes.wss]
    rule = "PathPrefix:/wss"
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
proxy.1.o3hiz9xtnzz4@ip-10-1-0-20    | time="2018-02-19T17:04:25Z" level=debug msg="vulcand/oxy/roundrobin/rr: competed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/wss","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Connection":["Upgrade"],"Sec-Websocket-Key":["85i04DOZ7rjxY581Za/ZKg=="],"Sec-Websocket-Version":["13"],"Upgrade":["websocket"],"User-Agent":["Go-http-client/1.1"],"X-Auth-Token":["xxx"]},"ContentLength":0,"TransferEncoding":null,"Host":"dev.cloud","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.0.0.126:46570","RequestURI":"/wss","TLS":null}" 
proxy.1.o3hiz9xtnzz4@ip-10-1-0-20    | 10.0.0.126 - - [19/Feb/2018:17:04:25 +0000] "GET /wss HTTP/1.1" 0 0 - "Go-http-client/1.1" 82 "websocket" "http://backend:8080" 3ms
```
