### ISSUE TITLE
HTTP requests are not proxied correctly when 100 Continue is requested from `Expect` header

### ISSUE THREAD

**Issue by jentfoo** [traefik/traefik#2899]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

@MafcoCinco originally found this issue.  With his help I think we have finally got the behavior nailed down.

Send a request with an `Expect: 100-continue` header.

This was done with `curl` (by default) when sending a large enough post.  When we specified `-H 'Expect:'` to disable the header, routing and functionality worked correctly.

### What did you expect to see?

A routed request to our downstream service, and a response.

Behavior described by the spec here: https://tools.ietf.org/html/rfc7231#section-5.1.1

Also reference section 8.2.3 of: https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html

### What did you see instead?

Two `HTTP/1.1 100 Continue` responses, without a final response from the downstream service.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.4.5
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik.toml
logLevel = "INFO"
defaultEntryPoints = ["http", "httpn"]
[entryPoints]
 [entryPoints.http]
 address = ":80"
 compress = false
 [entryPoints.httpn]
 address = ":8880"
 compress = false
[kubernetes]
[accessLog]
format = "common"
[web]
address = ":8080"
[web.metrics.prometheus]
[web.metrics.datadog]
 address = "dd-agent-datadog:8125"
 pushinterval = "10s"
```

**Comment by jentfoo** [comment]
Updated issue with previously missing information.  Let me know if there is any questions or further details I can provide.

**Comment by ldez** [comment]
@jentfoo Could you try with the latest version (1.5.2).

**Comment by jentfoo** [comment]
@ldez the defect seems to also be reproducible in `1.5.2`

**Comment by Grub01** [comment]
We also see this issue in 1.6.4. 
For me only seems to occur if the POST body is greater than 262144 bytes (256KiB). Anything smaller than that behaves correctly.

**Comment by animalcaretechnologies** [comment]
This happens for me with the latest version of traefik v1.7.9 (running in docker swarm mode). This happens on a post request that is only 34 bytes long.

**Comment by erenes** [comment]
After an afternoon investigating, it appears I ran into this as well (disabling 100-continue solved it). Will it help to provide a Wireshark log of the failure?

**Comment by mpl** [comment]
@erenes No need, thanks, we should be able to repro.

**Comment by shelby-moore** [comment]
I'm running in to this on 2.2.5. Happy to help contribute a fix if you're able to give me some direction on getting started :)

**Comment by SantoDE** [comment]
Hello @shelby-moore,

can you check in V 2.3 and share your configuration to repro the bug? That would be a good contribution start as of now :)

**Comment by turchinc** [comment]
We are running traefik:v2.4.6 and experiencing this issue, related somehow to #7431. Behind our traefik proxy is a webdav server and certain clients (for example cyberduck on a mac) issue "expect continue"
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/100

before doing a PUT. When traefik is not in the mix, the PUT works. If we proxy behind traefik then the PUT (upload) fails. 

Furthermore, the requests seem to "hang around" and only complete after a very long period of time. We see this in our logs like this:

```
2021-03-12 11:57:14,242 INFO  [io.milton.http.FilterChain] (default task-28) Slow request 148738ms in filter io.milton.http.StandardFilter@4183af48 for path=/dav/assetstore/21912_big.jpg
2021-03-12 11:57:14,243 INFO  [io.milton.http.FilterChain] (default task-32) Slow request 148383ms in filter io.milton.http.StandardFilter@4183af48 for path=/dav/assetstore/21912_big.jpg
2021-03-12 11:57:14,244 INFO  [io.milton.http.FilterChain] (default task-33) Slow request 148044ms in filter io.milton.http.StandardFilter@4183af48 for path=/dav/assetstore/21912_big.jpg
2021-03-12 11:57:14,244 INFO  [io.milton.http.FilterChain] (default task-36) Slow request 91036ms in filter io.milton.http.StandardFilter@4183af48 for path=/dav/assetstore/21912_big.jpg
2021-03-12 11:57:14,249 INFO  [io.milton.http.HttpManager] (default task-28) PUT :: myserver/dav/assetstore/21912_big.jpg finished 148745ms, Status:HTTP/1.1 201, Length:null
2021-03-12 11:57:14,249 INFO  [io.milton.http.HttpManager] (default task-36) PUT :: myserver/dav/assetstore/21912_big.jpg finished 91041ms, Status:HTTP/1.1 201, Length:null
2021-03-12 11:57:14,250 INFO  [io.milton.http.HttpManager] (default task-33) PUT :: myserver/dav/assetstore/21912_big.jpg finished 148050ms, Status:HTTP/1.1 201, Length:null
2021-03-12 11:57:14,250 INFO  [io.milton.http.HttpManager] (default task-32) PUT :: myserver/dav/assetstore/21912_big.jpg finished 148390ms, Status:HTTP/1.1 201, Length:null
2021-03-12 11:57:14,250 ERROR [org.jboss.as.txn] (default task-28) WFLYTX0003: APPLICATION ERROR: transaction still active in request with status 0
2021-03-12 11:57:14,250 ERROR [org.jboss.as.txn] (default task-32) WFLYTX0003: APPLICATION ERROR: transaction still active in request with status 0
2021-03-12 11:57:14,250 ERROR [org.jboss.as.txn] (default task-36) WFLYTX0003: APPLICATION ERROR: transaction still active in request with status 0
2021-03-12 11:57:14,250 ERROR [org.jboss.as.txn] (default task-33) WFLYTX0003: APPLICATION ERROR: transaction still active in request with status 0

```
While in the case of cyberduck, there is a workaround available:
https://trac.cyberduck.io/wiki/help/en/howto/dav#DisableExpect:100-continue
it is non-trival for a mac user to implement (hacking on plist files)

It would be nice if we could help y'all to get this working. In particular since those slow requests also seem to keep db transactions open  (see the ERROR lines immediately folloing) and eventually our thread pool fills up and the server crashes.

**Comment by turchinc** [comment]
some additional input from my tests today: I added a second host entry that routes via http instead of https behind the proxy:
```
- "traefik.enable=true"
- "traefik.http.routers.myserver.rule=Host(`myserver.myhost.com`)"
- "traefik.http.routers.myserver.service=myserver"
- "traefik.http.routers.myserver.tls.certresolver=letsencrypt"
- "traefik.http.services.myserver.loadbalancer.server.port=8443"
- "traefik.http.services.myserver.loadbalancer.server.scheme=https"
# add an additional http endpoint for the container
- "traefik.http.routers.myserver2.rule=Host(`myserver2.myhost.com`)"
- "traefik.http.routers.myserver2.service=myserver2"
- "traefik.http.routers.myserver2.tls.certresolver=letsencrypt"
- "traefik.http.services.myserver2.loadbalancer.server.port=8080"
- "traefik.http.services.myserver2.loadbalancer.server.scheme=http"
```
In that second case, the upload and the handling of expect continue works.  Again, without traefik in the mix, the webdav client works well with both http (8080) and https (8443) endpoints. So something is different in traefiks handling of the expect-continue when the backend is on https/8443. 

by the way, the webdav servlet disables this feature by default (I use default):
https://github.com/miltonio/milton2/blob/b17783b32403c3b3a3b68e991128c6914be99ae4/milton-server-ce/src/main/java/io/milton/config/HttpManagerBuilder.java#L493

**Comment by jakubhajek** [comment]
Hello @turchinc 👋 
I've just tried to replicate the issue in my test environment. I deployed Traefik (2.4.7) and Nginx with the attached persistent storage and enabled module Webdav. That stack allows uploading files and saves them on the attached storage. 

`HTTP-Request -> Traefik -> Nginx +Webdav module`

Here is the configuration that I've prepared for that stack

```yaml
apiVersion: v1
data:
  default.conf: |
    server {
    listen 80 default_server;
    server_name localhost ;
    location /upload {
        root   /usr/share/nginx/html;
        client_body_temp_path  /usr/share/nginx/html/upload/client_tmp;
        dav_methods  PUT DELETE MKCOL COPY MOVE;
        client_max_body_size 1500m;
        create_full_put_path   on;
        dav_access  group:rw  all:r;
      }
    }
kind: ConfigMap
metadata:
  name: upload
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: "nginx-test-with-pvc"
  name: nginx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "20Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-with-pvc
  name: nginx-with-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-with-pvc
  template:
    metadata:
      labels:
        app: nginx-with-pvc
    spec:
      containers:
        - image: nginx:1.19.8
          name: nginx
          ports:
            - containerPort: 80
              name: "http-server"

          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: vol1

            - name: upload
              mountPath: "/etc/nginx/conf.d/default.conf"
              subPath: "default.conf"

      initContainers:
        - name: create-dir
          image: busybox:1.31.1
          command: ["sh", "-c", "mkdir -pv /usr/share/nginx/html/upload/client_tmp && chown -Rv 101.101 /usr/share/nginx/html/*"]
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: vol1
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: nginx-pvc
        - name: upload
          configMap:
            name: upload
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-with-pvc
spec:
  type: ClusterIP
  selector:
    app: nginx-with-pvc
  ports:
    - port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-with-pvc
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dav.1.2.3.4.nip.io`)
      kind: Rule
      services:
        - name: nginx-with-pvc
          port: 80
  tls:
    certResolver: letsencrypt
```
Traefik has no special configuration, just a simple setup with enabled ACME. 

I tried to send large files using the `curl` command with the added extra header: `Expect: 100-continue` 

```
❯ curl -T512MB.zip -H "Expect: 100-continue" https://dav.1.2.3.4.nip.io/upload/ -v  -k
```
```
* Connected to dav.1.2.3.4.nip.io (1.2.3.4) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0

> PUT /upload/512MB.zip HTTP/2
> Host: dav.1.2.3.4.nip.io
> User-Agent: curl/7.64.1
> Accept: */*

> Expect: 100-continue

> Content-Length: 536870912

* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
* 
< HTTP/2 100

* We are completely uploaded and fine
< HTTP/2 201
< date: Mon, 15 Mar 2021 11:39:15 GMT
< location: http://dav.1.2.3.4..nip.io/upload/512MB.zip
< server: nginx/1.19.8
< content-length: 0
<
* Connection #0 to host dav.1.2.3.4.nip.io left intact
* Closing connection 0

```
As you can see I received the expected response `HTTP/2 100 ` once the client header `Expect: 100-continue` is added. 
The file has been also correctly uploaded and stored. 

It doesn't matter if I test that using HTTP or HTTPS, in both cases, the test is completed successfully.
