### ISSUE TITLE
Negative priority frontends

### ISSUE THREAD

**Issue by Beanow** [traefik/traefik#2930]
### Do you want to request a *feature* or report a *bug*?

Feature request

### What did you do?

```toml
[frontends]
	[frontends.frontend-specific]
	backend = "backend-specific"
		[frontends.frontend-specific.routes.route0]
		rule = "Host:something.example.com"

	[frontends.frontend-fallback]
	backend = "backend-fallback"
	priority = -5000
		[frontends.frontend-fallback.routes.anything]
		rule = "HostRegexp:{anything:[\\da-z\\._\\-]+}"
```

### What did you expect to see?

`frontend-specific` takes priority, due to negative priority on `frontend-fallback`.

### What did you see instead?

`frontend-fallback` takes priority.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.2
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-12_10:56:31AM
OS/Arch:      linux/amd64
```

#### My usecase

I've tried the above setup to use Traefik as a way to migrate away from a legacy webserver.
In the `[file]` section I set the fallback rules to route to the legacy server.
While in docker containers the new implementations would be dynamically configured.

In order to avoid setting priorities on all overrides, I would like to set a negative priority like above instead.
