### ISSUE TITLE
TLS client auth to backends

### ISSUE THREAD

**Issue by ishitatsuyuki** [traefik/traefik#3038]
## Proxy mutual TLS configuration proposal

This proposal adds mutual TLS  authentication with backends, as well as some other configuration format improvements.

### Added options

- Support for secrets are added. Secrets should be watched if available for hot reload.
- For all server certificate verification, add support for certification revocation lists and verification depth. See below.
- For specifying client certificate, the following options are used:
  ```toml
  [traefik.<service-name>.proxyCert]
  file = "secretkey" # file, content or secret
  serverName = "somehost" # Use this hostname for SNI and subject name verification
  ```
- For specifying server certificate, the contents of the following `ServerCA` are placed under the key `[traefik.<service-name>.proxyCA]`.

### Enhancement to existing configurations

- `FileOrContent` should also accept secrets as well, if supported in backend.
  * What should be the syntax for this? Something like `kubernetes:secret_name`?
- CA related configurations should be refactored so they have unity in syntax:
  ```toml
  [somepath.ClientCA] # Or ServerCA, renamed from RootCA
  files = ["..."] # file, content or secret
  crl = ["..."] # file, content or secret
  verify = true # renamed/flipped from optional
  verifyDepth = 1 # 0 -> self-signed only, 1 -> one level of CA, and so on...
  ```
  * Deprecate `RootCAs` and `InsecureSkipVerify`.
  * This change may create confusion for old users.

All the namings are for reference. Feel free to suggest anything better (less confusing).

[nginx doc](https://nginx.org/en/docs/http/ngx_http_proxy_module.html) is used as a strong reference on designing this.
