### ISSUE TITLE
Support for Marathon over Marathon

### ISSUE THREAD

**Issue by raravena80** [traefik/traefik#3200]
### Support for multiple Marathon's in the same Traefik process or app.

I'm having to run multiple traefik instances for each one of my Marathon instances.

### Support for MoM

Basically in the traefik.toml configs:

```toml
# Enable Marathon configuration backend.
[marathon]

# Marathon server endpoint.
# You can also specify multiple endpoint for Marathon:
# endpoint = "http://10.241.1.71:8080,10.241.1.72:8080,10.241.1.73:8080"
#
# Required
# Default: "http://127.0.0.1:8080"
#
endpoint = "http://127.0.0.1:8080"
```

I'd like to see maybe something like this:

```toml
# Enable Marathon configuration backend.
[marathon]

# Marathon server endpoint.
# You can also specify multiple endpoint for Marathon:
# endpoint = "http://10.241.1.71:8080,10.241.1.72:8080,10.241.1.73:8080"
#
# Required
# Default: "http://127.0.0.1:8080"
#
endpoint1 = "http://127.0.0.1:8080"
endpoint2 = "http://127.0.0.1:8080" -- Another marathon
```

### What did you see instead?

Single marathon support

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.4
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-03-15_01:35:21PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[entryPoints]
    [entryPoints.http]
       address = ":80"

[api]

#[Docker]
#  endpoint = "tcp://10.10.10.10:2375"
#  domain = "foo.bir"
#  exposedByDefault = true
#  swarmMode = true

#  [Docker.TLS]
#    CA = "dockerCA"
#    Cert = "dockerCert"
#    Key = "dockerKey"
#    InsecureSkipVerify = true
...
```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```
