### ISSUE TITLE
502 with rancher over https on some webpages

### ISSUE THREAD

**Issue by Guilhem30** [traefik/traefik#3208]
### Do you want to request a *feature* or report a *bug*?
It may be a bug, I was asked to open an issue on slack support 

### What did you do?
I tried to browse our web application (odoo) behind traefik

### What did you expect to see?
Our odoo application webpage

### What did you see instead?
XmlHttpRequestError 502 Bad Gateway

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.3
Codename:     cancoillotte
Go version:   go1.9.4
Built:        2018-02-27_02:47:04PM
OS/Arch:      linux/amd64
```
and also

```
Version:      v1.6.0-rc5
Codename:     tetedemoine
Go version:   go1.10.1
Built:        2018-04-12_09:50:36AM
OS/Arch:      linux/amd64


```
### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http", "https"]
[acme]
email = "hidden@secret.com"
storage = "/etc/traefik/acme.json"
entryPoint = "https"
OnHostRule = true
[acme.httpChallenge]
  entryPoint = "http"
[entryPoints]
   [entryPoints.http]
   address = ":80"
   [entryPoints.https]
   address = ":443"
     [entryPoints.https.tls]
[web]
address = ":8080"
[web.metrics.statsd]
address = "telegraf-service-telegraf-1:8125"
pushinterval = "10s"
[web.statistics]
   RecentErrors = 10
   [web.auth.basic]
     usersFile = "/etc/traefik/webui.htpasswd"
[file]
filename = "/etc/traefik/rules.toml"
watch = true
[rancher]
domain = "skinfra.cloud"
Watch = true
[rancher.metadata]
Prefix = "/2016-07-29"
```

Additional information :
We are running traefik on rancher. Traefik is used to proxy our containers and add https with letsencrypt. We are using it with nginx (for the cache) in front of our application (odoo).
On some webpages users encounter the following error half the time : XmlHttpRequestError 502 Bad Gateway.
This only seem to happen if we access the page in https (auto redirect is disabled for now) through traefik.
If we access our application directly through another nginx with https configured we can't reproduce the issue.
Same if we access the application through traefik via the http entrypoint it works fine.
