### ISSUE TITLE
Can't have RSA and EC certificates for same domain(s)

### ISSUE THREAD

**Issue by herver** [traefik/traefik#3483]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I wanted to add 2 certificates for the same domain name (one RSA and one EC cert) in order to mimic HAProxy (http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#5.1-crt)

### What did you expect to see?
I expected Traefik to serve the EC cert to clients advertising ECDSA in their cipher suite and RSA to the others

### What did you see instead?

During startup of `traefik` the following WARN is printed:
```
WARN[2018-06-12T18:06:09+02:00] Into EntryPoint https, try to add certificate for domains which already have this certificate (,*.xxx.tld,xxx.tld). The new certificate will not be append to the EntryPoint. 
```

It is generated by https://github.com/containous/traefik/blob/master/tls/certificate.go#L178

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      dev
Codename:     cheddar
Go version:   go1.10.3
Built:        I don't remember exactly
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = false
checkNewVersion = false
logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.traefik]
    address = ":6969"
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
      minVersion = "VersionTLS12"
    [[entryPoints.https.tls.certificates]]
      certFile = "cert.rsa.pem"
      keyFile = "cert.rsa.key"
    [[entryPoints.https.tls.certificates]]
      certFile = "cert.ecdsa.pem"
      keyFile = "cert.ecdsa.key"

[...]
```

If I understand correctly, only the certificate name is checked in order to it append (or not) to the map.

Maybe the check should be cert name + PublicKeyAlgorithm ? But then there might be other implications in other places of the code (I'm not very familiar with traefik's source code)
