### ISSUE TITLE
Datastore sync error: Object lock value: expected b8e35510

### ISSUE THREAD

**Issue by holms** [traefik/traefik#3487]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Launched Traefik as cluster form [this](https://docs.traefik.io/user-guide/cluster-docker-consul/)  manual.

### What did you expect to see?

No errors

### What did you see instead?

traefik output:

```shell
infra_proxy.0.eloqzxy578jr@swarm-manager-0    | time="2018-06-13T13:38:32Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 3.353099079s"
infra_proxy.0.eloqzxy578jr@swarm-manager-0    | time="2018-06-13T13:38:35Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 7.734764651s"
infra_proxy.0.eloqzxy578jr@swarm-manager-0    | time="2018-06-13T13:38:43Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 18.253019683s"
infra_proxy.0.eloqzxy578jr@swarm-manager-0    | time="2018-06-13T13:39:01Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 20.274627269s"
infra_proxy.0.eloqzxy578jr@swarm-manager-0    | time="2018-06-13T13:39:22Z" level=error msg="Datastore sync error: Object lock value: expected b8e35510-1397-4396-9a94-a8ed41560195, got , retrying in 269.349437ms"
infra_proxy.0.eloqzxy578jr@swarm-manager-0    | legolog: 2018/06/13 13:39:30 [INFO] acme: Registering account for aaaa@aaaa.io
infra_proxy.0.fv9ni12zaup4@swarm-manager-1    | 10.255.0.4 - - [13/Jun/2018:13:42:12 +0000] "GET / HTTP/1.0" 404 19 "-" "-" 1 "backend not found" "/" 0ms
infra_proxy.0.eloqzxy578jr@swarm-manager-0    | 10.255.0.4 - - [13/Jun/2018:13:42:21 +0000] "GET / HTTP/1.0" 404 19 "-" "-" 1 "backend not found" "/" 0ms
infra_proxy.0.eloqzxy578jr@swarm-manager-0    | 10.255.0.3 - - [13/Jun/2018:13:42:58 +0000] "GET / HTTP/1.0" 404 19 "-" "-" 2 "backend not found" "/" 0ms
infra_proxy.0.fv9ni12zaup4@swarm-manager-1    | time="2018-06-13T13:51:24Z" level=error msg="Leadership election error failed to read lock: Get http://consul:8500/v1/kv/traefik/leader?index=5848&wait=15000ms: dial tcp 10.0.0.8:8500: connect: no route to host, retrying in 42.481718789s"
infra_proxy.0.fv9ni12zaup4@swarm-manager-1    | time="2018-06-13T13:51:24Z" level=error msg="KV connection error: watchtree channel closed, retrying in 552.821584ms"


```

traefik_init:

```
infra_proxy_init.1.jkwmgpocxokv@swarm-manager-1    | 2018/06/13 13:38:13 Storing configuration: <big json here>
```

### Output of `traefik version`:

```
Version:      v1.6.3
Codename:     tetedemoine
Go version:   go1.10.2
Built:        2018-06-05_03:29:01PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
    consul:
      hostname: consul
      image: consul
      command: agent -server -bootstrap-expect=1
      environment:
        - CONSUL_LOCAL_CONFIG={"datacenter":"ams3","server":true,"enable_debug":true}
        - CONSUL_BIND_INTERFACE=eth0
        - CONSUL_CLIENT_INTERFACE=eth0
      deploy:
        labels:
          - "traefik.enable=false"
        replicas: 1
        placement:
          constraints:
            - node.role == manager
        restart_policy:
         condition: on-failure
      networks:
        - traefik
      volumes:
        - consul-data:/consul/data

    proxy_init:
      image: traefik:1.6.3-alpine
      command:
         - "traefik"
         - "storeconfig"
         - "--api"
         - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
         - "--entrypoints=Name:https Address::443 TLS"
         - "--defaultentrypoints=http,https"
         - "--acme"
         - "--acme.storage='traefik/acme/account'"
         - "--acme.entryPoint=https"
         - "--acme.httpChallenge.entryPoint=http"
         - "--acme.onHostRule=false"
         - "--acme.acmelogging=true"
         - "--acme.onDemand=false"
         - "--acme.email=roman@whatever.io"
         - "--docker"
         - "--docker.swarmMode"
         - "--docker.domain=swarm.whatever.io"
         - "--docker.watch"
         - "--consul"
         - "--consul.endpoint=consul:8500"
         - "--consul.prefix=traefik"
         - "--accesslogsfile=/dev/stdout"
      networks:
         - traefik
      deploy:
         placement:
            constraints:
              - node.role == manager
         restart_policy:
            condition: on-failure
      depends_on:
        - consul

  proxy:
      image: traefik:1.6.3-alpine
      depends_on:
        - proxy_init
        - consul
      command:
        - "traefik"
        - "--consul"
        - "--consul.watch"
        - "--consul.endpoint=consul:8500"
        - "--consul.prefix=traefik"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - traefik
      ports:
        - 80:80
        - 443:443
        - 8080:8080
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      deploy:
        mode: global
        restart_policy:
          condition: on-failure
        placement:
          constraints:
            - node.role == manager
        update_config:
          parallelism: 1
          delay: 10s

networks:
  traefik:
      driver: overlay

volumes:
  consul-data:

```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)
consul container

```shell
infra_consul.1.rxgmyuldfu6p@swarm-manager-1    |     2018/06/13 13:54:57 [ERR] http: Request PUT /v1/session/create?wait=30000ms, error: Missing node registration from=10.0.0.10:34330
infra_consul.1.rxgmyuldfu6p@swarm-manager-1    |     2018/06/13 13:55:01 [ERR] http: Request PUT /v1/session/create?wait=30000ms, error: Missing node registration from=10.0.0.11:46408
infra_consul.1.rxgmyuldfu6p@swarm-manager-1    |     2018/06/13 13:55:01 [WARN] consul.fsm: EnsureRegistration failed: failed inserting node: node ID "4400be7d-ecd1-c15c-594c-b8d763c65750" for node "consul" aliases existing node "ca84546beaf2"
infra_consul.1.rxgmyuldfu6p@swarm-manager-1    |     2018/06/13 13:55:01 [WARN] agent: Syncing node info failed. failed inserting node: node ID "4400be7d-ecd1-c15c-594c-b8d763c65750" for node "consul" aliases existing node "ca84546beaf2"
infra_consul.1.rxgmyuldfu6p@swarm-manager-1    |     2018/06/13 13:55:01 [ERR] agent: failed to sync remote state: failed inserting node: node ID "4400be7d-ecd1-c15c-594c-b8d763c65750" for node "consul" aliases existing node "ca84546beaf2"
```

And if I'd launch traefik 1.5 as on that manual without changing absolutely anything except ACME email -  it's similar output. Sorry without debug because it's really wordy.

```console
$ docker --tls service logs -f infra_traefik
infra_traefik.0.5wlrzsjcy1j0@swarm-manager-0    | time="2018-06-13T14:15:44Z" level=error msg="Load config error: Get http://consul:8500/v1/kv/traefik?consistent=&recurse=&wait=30000ms: dial tcp: lookup consul on 127.0.0.11:53: no such host, retrying in 532.066212ms" 
infra_traefik.0.5wlrzsjcy1j0@swarm-manager-0    | time="2018-06-13T14:15:45Z" level=error msg="Load config error: Get http://consul:8500/v1/kv/traefik?consistent=&recurse=&wait=30000ms: dial tcp: lookup consul on 127.0.0.11:53: no such host, retrying in 458.005135ms" 
infra_traefik.0.5wlrzsjcy1j0@swarm-manager-0    | time="2018-06-13T14:15:45Z" level=error msg="Load config error: Get http://consul:8500/v1/kv/traefik?consistent=&recurse=&wait=30000ms: dial tcp: lookup consul on 127.0.0.11:53: no such host, retrying in 878.925167ms" 
infra_traefik.0.71cmslvo7ul8@swarm-manager-1    | time="2018-06-13T14:15:44Z" level=error msg="Load config error: Get http://consul:8500/v1/kv/traefik?consistent=&recurse=&wait=30000ms: dial tcp: lookup consul on 127.0.0.11:53: no such host, retrying in 467.819053ms" 
infra_traefik.0.71cmslvo7ul8@swarm-manager-1    | time="2018-06-13T14:15:45Z" level=error msg="Load config error: Get http://consul:8500/v1/kv/traefik?consistent=&recurse=&wait=30000ms: dial tcp: lookup consul on 127.0.0.11:53: no such host, retrying in 520.709512ms" 
infra_traefik.0.71cmslvo7ul8@swarm-manager-1    | time="2018-06-13T14:15:45Z" level=error msg="Load config error: Get http://consul:8500/v1/kv/traefik?consistent=&recurse=&wait=30000ms: dial tcp: lookup consul on 127.0.0.11:53: no such host, retrying in 761.341364ms" 
infra_traefik.0.3q211ndstidz@swarm-master    | time="2018-06-13T14:15:44Z" level=error msg="Load config error: Get http://consul:8500/v1/kv/traefik?consistent=&recurse=&wait=30000ms: dial tcp: lookup consul on 127.0.0.11:53: no such host, retrying in 465.226492ms" 
infra_traefik.0.3q211ndstidz@swarm-master    | time="2018-06-13T14:15:44Z" level=error msg="Load config error: Get http://consul:8500/v1/kv/traefik?consistent=&recurse=&wait=30000ms: dial tcp: lookup consul on 127.0.0.11:53: no such host, retrying in 463.286566ms" 
infra_traefik.0.3q211ndstidz@swarm-master    | time="2018-06-13T14:15:45Z" level=error msg="Load config error: Get http://consul:8500/v1/kv/traefik?consistent=&recurse=&wait=30000ms: dial tcp: lookup consul on 127.0.0.11:53: no such host, retrying in 1.056679773s" 
infra_traefik.0.71cmslvo7ul8@swarm-manager-1    | time="2018-06-13T14:15:53Z" level=error msg="Load config error: Unexpected response code: 500, retrying in 1.251030901s" 
infra_traefik.0.3q211ndstidz@swarm-master    | time="2018-06-13T14:15:53Z" level=error msg="Load config error: Unexpected response code: 500, retrying in 1.135779476s" 
infra_traefik.0.5wlrzsjcy1j0@swarm-manager-0    | time="2018-06-13T14:15:53Z" level=error msg="Load config error: Unexpected response code: 500, retrying in 1.688059111s" 
infra_traefik.0.71cmslvo7ul8@swarm-manager-1    | time="2018-06-13T14:15:56Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing node registration), retrying in 580.210284ms" 
infra_traefik.0.71cmslvo7ul8@swarm-manager-1    | time="2018-06-13T14:15:56Z" level=error msg="Cannot unmarshall private key []" 
infra_traefik.0.71cmslvo7ul8@swarm-manager-1    | time="2018-06-13T14:15:56Z" level=error msg="Error building ACME client &{Email: Registration:<nil> PrivateKey:[] DomainsCertificate:{Certs:[] lock:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0}} ChallengeCerts:map[] HTTPChallenge:map[]}: private key was nil" 
infra_traefik.0.3q211ndstidz@swarm-master    | time="2018-06-13T14:15:57Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing node registration), retrying in 594.274959ms" 
infra_traefik.0.3q211ndstidz@swarm-master    | time="2018-06-13T14:15:57Z" level=error msg="Cannot unmarshall private key []" 
infra_traefik.0.3q211ndstidz@swarm-master    | time="2018-06-13T14:15:57Z" level=error msg="Error building ACME client &{Email: Registration:<nil> PrivateKey:[] DomainsCertificate:{Certs:[] lock:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0}} ChallengeCerts:map[] HTTPChallenge:map[]}: private key was nil" 
infra_traefik.0.5wlrzsjcy1j0@swarm-manager-0    | time="2018-06-13T14:15:57Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing node registration), retrying in 742.791882ms" 
infra_traefik.0.5wlrzsjcy1j0@swarm-manager-0    | time="2018-06-13T14:15:57Z" level=error msg="Cannot unmarshall private key []" 
infra_traefik.0.5wlrzsjcy1j0@swarm-manager-0    | time="2018-06-13T14:15:57Z" level=error msg="Error building ACME client &{Email: Registration:<nil> PrivateKey:[] DomainsCertificate:{Certs:[] lock:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0}} ChallengeCerts:map[] HTTPChallenge:map[]}: private key was nil" 
infra_traefik.0.71cmslvo7ul8@swarm-manager-1    | time="2018-06-13T14:15:57Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 840.089349ms" 
infra_traefik.0.3q211ndstidz@swarm-master    | time="2018-06-13T14:15:57Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 928.245698ms" 
infra_traefik.0.5wlrzsjcy1j0@swarm-manager-0    | time="2018-06-13T14:15:58Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 917.49328ms" 
infra_traefik.0.71cmslvo7ul8@swarm-manager-1    | time="2018-06-13T14:15:58Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 1.567695523s" 
infra_traefik.0.3q211ndstidz@swarm-master    | time="2018-06-13T14:15:58Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 1.013373382s" 
infra_traefik.0.5wlrzsjcy1j0@swarm-manager-0    | time="2018-06-13T14:15:59Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 717.059863ms" 
infra_traefik.0.3q211ndstidz@swarm-master    | time="2018-06-13T14:15:59Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 1.489577248s" 
infra_traefik.0.5wlrzsjcy1j0@swarm-manager-0    | time="2018-06-13T14:15:59Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 1.448180821s" 
infra_traefik.0.71cmslvo7ul8@swarm-manager-1    | time="2018-06-13T14:15:59Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 2.23620903s" 
infra_traefik.0.3q211ndstidz@swarm-master    | time="2018-06-13T14:16:01Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 1.310668277s" 
infra_traefik.0.5wlrzsjcy1j0@swarm-manager-0    | time="2018-06-13T14:16:01Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 3.450216199s" 
infra_traefik.0.71cmslvo7ul8@swarm-manager-1    | time="2018-06-13T14:16:02Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 3.534395919s" 
infra_traefik.0.3q211ndstidz@swarm-master    | time="2018-06-13T14:16:02Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 2.211433481s" 
infra_traefik.0.5wlrzsjcy1j0@swarm-manager-0    | time="2018-06-13T14:16:04Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 4.280841828s" 
infra_traefik.0.3q211ndstidz@swarm-master    | time="2018-06-13T14:16:04Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 5.420684251s" 
infra_traefik.0.71cmslvo7ul8@swarm-manager-1    | time="2018-06-13T14:16:05Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 4.230201542s" 
infra_traefik.0.5wlrzsjcy1j0@swarm-manager-0    | time="2018-06-13T14:16:08Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 7.971177426s" 
infra_traefik.0.71cmslvo7ul8@swarm-manager-1    | time="2018-06-13T14:16:09Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 4.362036267s" 
infra_traefik.0.3q211ndstidz@swarm-master    | time="2018-06-13T14:16:10Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 8.672095649s" 
infra_traefik.0.71cmslvo7ul8@swarm-manager-1    | time="2018-06-13T14:16:14Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 12.08051947s" 
infra_traefik.0.5wlrzsjcy1j0@swarm-manager-0    | time="2018-06-13T14:16:16Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 6.720661168s" 
infra_traefik.0.3q211ndstidz@swarm-master    | time="2018-06-13T14:16:18Z" level=error msg="Leadership election error Unexpected response code: 500 (Missing check 'serfHealth' registration), retrying in 12.498967374s" 
^C⏎                                                         
infra_traefik.0.3q211ndstidz@swarm-master    | time="2018-06-13T14:15:44Z" level=error msg="Load config error: Get http://consul:8500/v1/kv/traefik?consistent=&recurse=&wait=30000ms: dial tcp: lookup consul on 127.0.0.11:53: no such host, retrying in 465.226492ms" 
infra_traefik.0.3q211ndstidz@swarm-master    | time="2018-06-13T14:15:44Z" level=error msg="Load config error: Get http://consul:8500/v1/kv/traefik?consistent=&recurse=&wait=30000ms: dial tcp: lookup consul on 127.0.0.11:53: no such host, retrying in 463.286566ms" 
                                                                                                                                                               
```

Related to #3372

I've asked about this issue in Slack channel, and the only answer I've got, I have a problem with swarm setup. I have a regular swarm setup on digital ocean. There's eth0 and eth1 in there, one is for outer world, another one for inner. I have no idea what's happening. That Consul agent/server gives tons of errors when starting, first agent complains that it wasn't registered, after sometime it does register a node because server goes up in like 15sec. Meanwhile traefik bombs consul and getting error that it can't be registered. Then that datastore store sync error pops up. So many things happening in here that I don't even know what exact issue I'm having in the first place, and are they even connected in between. This setup doesn't work. If someone could replicate traefik cluster setup and send docker-compose file we can compare output.
