### ISSUE TITLE
A way to disable basic auth (or any auth) per frontend by label

### ISSUE THREAD

**Issue by Th0masStorm** [traefik/traefik#3562]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

In our setup our Traefik has basicAuth setting with htpasswd file. It's working for all frontends.
We have some web applications with login page, so i'm looking for a way to disable auth setting for that specific application using label. I couldn't find any handful information in the docs, so i tried this (we're using Marathon):

```
"traefik.frontend.auth.basic":  ""
```
### What did you expect to see?

I expected that empty value for this label will override the auth setting, allowing to open web page without entering credentials

### What did you see instead?

Same as without that label, I was requested to enter my login and password from htpasswd

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.6.3
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = false
checkNewVersion = false
'traefiklog.filepath' = "/var/log/traefik.log"
logLevel = "WARN"
accessLogsFile = "/var/log/access.log"

defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.auth.basic]
  usersFile = "/etc/.htpasswd"
  [entryPoints.api]
  address = ":6060"
  usersFile = "/etc/.htpasswd"

[accessLog]
filePath = "/var/log/access.log"

[retry]
attempts = 3

[marathon]
endpoint = "http://my_marathon:8080"
watch = true
exposedByDefault = true
domain = "example.com"


[api]
  entryPoint = "api"
  dashboard = true

[web.statistics]
RecentErrors = 10

[web.metrics.prometheus]
Buckets=[0.1,0.3,1.2,5.0,10.0]

[ping]
entryPoint = "api"

[metrics]
  [metrics.prometheus]
    entryPoint = "api"
    buckets = [0.1,0.3,1.2,5.0,10.0]
```

**Comment by Th0masStorm** [comment]
Thanks for the quick answer!

Then another question. Because Traefik sends Authentication header to the backend site, it fails with `Authentication failed`, cause the htpasswd credentials are different.

If i can not disable basicAuth can I at least make Traefik not to send that header?

**Comment by ldez** [comment]
https://github.com/containous/traefik/issues/3448

**Comment by Th0masStorm** [comment]
@ldez Thanks a lot, that helped.
At least our users won't have to create same credentials for both htpasswd and backend web app.

Is it possible to transform this issue into feature request? I'm sure i'm not the only one who would like to have that in Traefik.

**Comment by SteveEdson** [comment]
Just found this issue and wondered if it was possible to do the opposite and enable authentication via a label? Tried the following with no luck:

```yaml
deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:my.host.name"
        - "traefik.port=8080"
        - "traefik.frontend.auth.basic.users=[\"username:$$hashed$$password$$here/\"]"
```

**Comment by ldez** [comment]
https://docs.traefik.io/configuration/backends/docker/#on-containers

```yml
deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:my.host.name"
        - "traefik.port=8080"
        - "traefik.frontend.auth.basic.users=test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/,test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0"
```

For more information, please go to our [Slack Workspace](https://traefik.slack.io)
