### ISSUE TITLE
Forward authentication response headers

### ISSUE THREAD

**Issue by plaisted** [traefik/traefik#3660]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

It would be useful to allow headers returned from the forward authentication HTTP endpoint to be added to the final HTTP response. This would allow scenarios where the forward authentication endpoint can refresh authentication credentials and add the new credentials as a header/cookie.

This can be accomplished with a new configuration for http forward auth of "addHeadersToResponse" or similar.

Example:
```
addHeadersToResponse = ["Set-Cookie"]
```
This would result in any cookies added from HTTP forward auth response to be returned with the final response to the requesting client.

End-to-End example.
1. Traefik receives request to entrypoint with forward auth.
2. Traefik forward request to auth HTTP URI
3. JWT is used as a cookie for authentication. Forward auth server validates JWT, but expiration of JWT is soon.
4. Forward auth server requests new JWT for user and uses "Set-Cookie" header to overwrite previous JWT. Returns 20* response telling Traefik to continue routing.
5. Request is routed to correct frontend/backend and response obtained.
6. Forward auth middleware adds "Set-Cookie" header to outgoing response with new JWT.
7. New JWT cookie is used for subsequent requests.

**Comment by ldez** [comment]
Duplicate of #3515

Fixed by #3521

**Comment by plaisted** [comment]
@ldez I don't think this is a duplicate. That solution allows headers to be added to the request that is sent to the backend. The use case above requires the headers to be added to the outgoing response.

**Comment by cptaffe** [comment]
I could really use this.

We use a Rails server for authentication, and use forward authentication to convert the cookie to a JWT for other services. This works great, but doesn't allow the cookie to get updated.

My Kubernetes Ingress configuration looks like this

```yml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: example
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/auth-type: forward
    ingress.kubernetes.io/auth-url: http://example-rails.default/authenticate
    ingress.kubernetes.io/auth-response-headers: Authorization
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /api
            backend:
              serviceName: example
              servicePort: 80
```

A possible workaround is to add `Set-Cookie` to `ingress.kubernetes.io/auth-response-headers` and then have the service copy the header to the response itself; but that requires that the service know about the cookie. In this case, I want the service to only know about JWTs.
