### ISSUE TITLE
wrong FrontendName in accessLog

### ISSUE THREAD

**Issue by dazoot** [traefik/traefik#3725]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have 3 frontends defined, each of them matching via a simple `Host:` rule.
I use the file backend and define each frontend in a separate file.

```toml
[file]
    directory = "/etc/traefik/sites/"
    watch = true
```

This is my logging related configuration:
```toml
[traefikLog]
  filePath = "/var/log/traefik/traefik.log"

[accessLog]
  filePath = "/var/log/traefik/access.log"
  format = "json"

[accessLog.fields]
  defaultMode = "drop"

[accessLog.fields.names]
  "RequestHost" = "keep"
  "ClientHost" = "keep"
  "RequestLine" = "keep"
  "FrontendName" = "keep"
  "BackendAddr" = "keep"
  "RequestProtocol" = "keep"

[accessLog.fields.headers]
  defaultMode = "drop"
```

### What did you expect to see?

I expect to see the correct value of `"FrontendName"` in access log file.

### What did you see instead?

I see the name of the first frontend (alphabetically) which has the same backend as the requested one.

For example i request Host: n.example.net but in the accesslog file i see `FrontendName` from Host: c.example.net.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.0-rc3
Codename:     maroilles
Go version:   go1.10.3
Built:        2018-08-01_01:36:
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Example of 2 frontends files:

```toml
[frontends.nl_chic]
passHostHeader = true
backend = "back1"

[frontends.nl_chic.routes.default]
rule = "Host: c.example.net"
```

```toml
[frontends.nl_nor]
passHostHeader = true
backend = "back1"

[frontends.nl_nor.routes.default]
rule = "Host: n.example.net"
```
