### ISSUE TITLE
Ability to configure generic circuit breaker options

### ISSUE THREAD

**Issue by lpicanco** [traefik/traefik#3858]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I need to configure some Traefik circuit breaker options. Currently it is using the default options that is:

- checkPeriod: 100ms
- fallbackDuration: 10s
- recoveryDuration: 10s

Proposal
Allow the definition of a default configuration for the circuit breaker in the configuration file. 

Example:
```toml
[circuitBreaker]
  checkPeriod = 300ms
  fallbackDuration = 20s
  recoveryDuration = 20s
```
