### ISSUE TITLE
compression error

### ISSUE THREAD

**Issue by tipruzs** [traefik/traefik#3981]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

i configured traefik to serve tomcat 8.5 webapp using http2

### What did you expect to see?

working as expected (v1.6.6 works)

### What did you see instead?

internal server error

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7.1-alpine
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
services:
  traefik:
    image: traefik:1.7-alpine
    command:
      - "--loglevel=DEBUG"
      - "--checknewversion=false"
      - "--insecureskipverify=true"
      - "--defaultentrypoints=http,https"
      - "--entrypoints=Name:http Address::80 Compress:false Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS TLS.MinVersion:VersionTLS12 Compress:false"
      - "--api"
      - "--api.statistics"
      - "--metrics"
      - "--metrics.prometheus"
      - "--ping"
      - "--docker"
      - "--docker.watch"
      - "--docker.exposedbydefault=false"
      - "--docker.swarmmode"

...

  app:
   ...
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: "overlay"
        traefik.port: "8443"
        traefik.protocol: "https"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.rule: "Host:api.example.com;PathPrefix:/path1,/path2"
```

Stripped out unimportant details.

I already tried do disable compression on the backend, but the issue still happens. Only workaround is to downgrade back to v1.6.6

Tomcat uses self signed certificate (EC, prime256v1)

For the sake of completeness, this is the tomcat connector config
```xml
<Connector port="8443" protocol="org.apache.coyote.http11.Http11AprProtocol" executor="tomcatThreadPool" SSLEnabled="true" acceptorThreadCount="2"
           compression="off" connectionTimeout="120000" sendReasonPhrase="true" >
    <UpgradeProtocol className="org.apache.coyote.http2.Http2Protocol" />
    <SSLHostConfig>
        <Certificate certificateKeyFile="/path/to/localhost.key"
                     certificateFile="/path/to/localhost.pem"
                     type="EC" />
    </SSLHostConfig>
</Connector>
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
level=debug msg="Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel."
level=debug msg="'500 Internal Server Error' caused by: connection error: COMPRESSION_ERROR"
level=debug msg="vulcand/oxy/forward/http: Round trip: https://10.0.7.68:8443, code: 500, Length: 21, duration: 8.800802ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:api.example.com"
```

**Comment by Juliens** [comment]
Thanks for you interest in the project.

First of all, the message about pipelining is not linked to your problem.
I think, the message about COMPRESSION_ERRROR has been sent by the backend.
Do you have some logs on your backend when this error occur?

**Comment by tipruzs** [comment]
i created a sandbox for testing this issue without any custom applications. The issue is only tracked in the traefik logs.

I'm wondering what changed in traefik 1.7 at the compression handling. I currently have no idea how to debug this further.

Please find attached the required docker-compose and snippets in order to be able to reproduce this issue.

```yaml
version: "3.6"

networks:
  overlay:
    attachable: true

services:
  traefik:
    image: traefik:1.7-alpine
    command:
      - "--loglevel=DEBUG"
      - "--checknewversion=false"
      - "--insecureskipverify=true"
      - "--defaultentrypoints=http,https"
      - "--entrypoints=Name:http Address::80 Compress:false Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS TLS.MinVersion:VersionTLS12 Compress:false"
      - "--api"
      - "--api.statistics"
      - "--ping"
      - "--docker"
      - "--docker.watch"
      - "--docker.exposedbydefault=false"
      - "--docker.swarmmode"
    networks:
      - overlay
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    environment:
      TZ: "Europe/Berlin"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
  tomcat:
    image: tomcat:8-jre8-alpine
    entrypoint: "/entrypoint.sh"
    command: "catalina.sh run"
    networks:
      - overlay
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
      - target: 8443
        published: 8443
        protocol: tcp
        mode: host
    environment:
      TZ: "Europe/Berlin"
    volumes:
      - ./entrypoint_tomcat.sh:/entrypoint.sh
      - ./server.xml:/usr/local/tomcat/conf/server.xml
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: "overlay"
        traefik.port: "8443"
        traefik.protocol: "https"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.rule: "Host:tomcat.example.com"
```

[tomcat-server-xml-and-entrypoint.zip](https://github.com/containous/traefik/files/2464109/tomcat-server-xml-and-entrypoint.zip)
