### ISSUE TITLE
Missing error pages can crash Marathon provider

### ISSUE THREAD

**Issue by deric** [traefik/traefik#4172]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I've configured error page over Marathon labels, that looks like this:
```
        traefik.enable: true
        traefik.frontend.rule: Host:test.example.com
        traefik.protocol: http
        traefik.backend.healthcheck.path: /health
        traefik.frontend.entryPoints: http
        traefik.backend.loadbalancer.method: drr
        traefik.frontend.errors.rapi.query: "/"
        traefik.frontend.errors.rapi.backend: -error
        traefik.frontend.errors.rapi.status: 500-599
```

### What did you expect to see?

I'd expect that Traefik would forward requests to error backend.

### What did you see instead?

Marathon provider crashed. All frontends and backends were removed and Traefik returns just `404` for all requests.

```
time="2018-11-07T20:14:07Z" level=error msg="Error when creating error page \"web\" for frontend \"frontend-web-dev\": the backend \"backend-error\" doesn't exist."
time="2018-11-07T20:14:07Z" level=info msg="Server configuration reloaded on :8080"
time="2018-11-07T20:14:07Z" level=info msg="Server configuration reloaded on :8081"
time="2018-11-07T20:14:07Z" level=info msg="Server configuration reloaded on :10118"
time="2018-11-07T20:14:07Z" level=info msg="Skipping same configuration for provider marathon"
```
Also, there is a strange conveniton that forces you to name the error page backend with a dash at the begining. Otherwise the backend can't be found. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.4
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-30_10:44:30AM
OS/Arch:      linux/amd64
```

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[marathon]
  endpoint = "http://marathon.mesos:8080"
  domain = "example.com"
  exposedByDefault = false
  groupsAsSubDomains = false
  marathonLBCompatibility = false
  dialerTimeout = "60s"
  keepAlive = "10s"
  forceTaskHostname = false
  respectReadinessChecks = true
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```
(paste your output here)
```
