### ISSUE TITLE
Cannot authenticate with POST form in Forward Authentication process

### ISSUE THREAD

**Issue by remiberthoz** [traefik/traefik#4366]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm trying to configure forward authentication on my traefik install.

Web apps are accessible at `https://app.mydomain.tld/`, and I have a simple `http` authentication `POST` form at `https://auth.mydomain.tld/`. The latter is my authentication backend, ans is also accessible form `https://mydomain.tld:8081/` for testing purpose.

### What did you expect to see?

I'm expecting to be able to login when browsing either to `https://auth.mydomain.tld/` or `https://app.mydomain.tld/`, the following is true for both and I'll refer to them as `https://*.mydomain.tld/`.

When browsing to `https://*.mydomain.tld/` for the first time, the response from the forward auth service being `401`, the login form is displayed. When entering a valid password, the form data is send to `auth`, which responds with an authenticating cookie.

In presence of the cookie, any access attempt to `https://*.mydomain.tld/` should be validated by the forward auth server, and successful.

### What did you see instead?

* When browsing to `https://*.mydomain.tld/`, the authentication form is presented to me, as expected.
* After entering valid data in the form, no cookie is returned in the response.

The scenario is similar to the feature request #2620, which is closed by its creator with no solution.

I suspect this is because the `POST` request send to the authentication backend via  `https://*.mydomain.tld/` is also filtered through the forward authentication process. Because I'm not logged in when sending this request, a new request is created by Traefik and send to the authentication backend without the `POST` data.

A solution would be to disable the forward authentication process when the requested URL matches that of the authentication backend. With this solution I could login from `https://auth.mydomain.tld/` (not from `https://app.mydomain.tld/`, but that's solvable with appropriate redirections).

_Note that the authentication process is working correctly when login in with `https://mydomain.tld:8081/`, which sets the cookie correctly._

### Output of `traefik version`:

Version:      v1.7.4
Codename:     maroilles
Go version:   go1.11.1
Built:        2018-10-30_10:44:30AM
OS/Arch:      linux/arm

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik.toml
debug = true
logLevel = "DEBUG"

defaultEntryPoints = ["http", "https"]

[api]
    entryPoint = "traefik"

[docker]
    endpoint = "unix:///var/run/docker.sock"
    domain = "mydomain.tld"
    watch = true
    exposedByDefault = false

[entryPoints]
    [entryPoints.http]
        address = ":80"
        [entryPoints.http.redirect]
            entryPoint = "https"
    [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]
        [entryPoints.https.auth.forward]
            address = "http://auth:80/"
```

```yml
# docker-compose.yml for auth backend
version: '3.2'

services:
    auth:
        [...]
        container_name: auth
        labels:
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:auth.mydomain.tld"
        ports:
            - "8081:80"
        expose:
            - "80"
```

---------

I'll be happy to help on a solution to this problem. As per the suggested idea, I figured adding the following lines in `middlewares/auth/forward.go` could help:
```go
func Forward(config *types.Forward, w http.ResponseWriter, r *http.Request, next http.HandlerFunc)
     if (r.Host == config.Address) {                                                               
         next(w, r)                                                                                
     } 
    ...
```
but it can't work because the `config.Address` takes the form of `http://auth:80/`.
