### ISSUE TITLE
R53 LE certificate renewal fails with error for wildcard certificates

### ISSUE THREAD

**Issue by gurumark** [traefik/traefik#4371]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

No action has been taken in fully working traefik container.

### What did you expect to see?

I wanted to see the LE certificates automatically renewed

### What did you see instead?

The LE wildcard certificates expired with the following error:

```
time="2019-01-09T02:03:43Z" level=error msg="Error renewing certificate from LE: {*.example.com [example.com]}, acme: Error -> One or more domains had a problem:\n[*.example.com] [*.example.com] acme: error presenting token: route53: failed to change record set: InvalidChangeBatch: [RRSet with DNS name _acme-challenge.example.com. is not permitted in zone example1.com.]\n\tstatus code: 400, request id: ca7c49f4-13b2-11e9-a48c-adfe188b9f2d\n[example.com] [example.com] acme: error presenting token: route53: failed to change record set: InvalidChangeBatch: [RRSet with DNS name _acme-challenge.example.com. is not permitted in zone example1.com.]\n\tstatus code: 400, request id: ca73e52e-13b2-11e9-8ca3-89b4b24b15bc\n" 
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.7
Codename:     maroilles
Go version:   go1.11.4
Built:        2019-01-08_10:21:03AM
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "ERROR"
#logLevel = "DEBUG"


defaultEntryPoints = ["http","https"]

[entryPoints]
 [entryPoints.http]
  address = ":80"
  [entryPoints.http.redirect]
    entryPoint = "https"
    permanent = true

 [entryPoints.https]
  address = ":443"

   [entryPoints.https.tls]

[acme]
email = "admin@example.com"
storage = "acme.json"
#caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
acmeLogging = true
entryPoint = "https"
  [acme.dnsChallenge]
  provider = "route53"
  delayBeforeCheck = 0 


[[acme.domains]]
  main = "*.example.com"
  sans = ["example.com"]

[[acme.domains]]
  main = "*.example1.com"
  sans = ["example1.com"]

network = "emdnet"

[file]
watch = true

[respondingTimeouts]
idleTimeout = "360s"

[frontends]

  [frontends.slmain]
  backend = "host1"
  passHostHeader = true
  entrypoints = ["http","https"]

    [frontends.slmain.routes.example]
    rule = "Host:example.com"

  [frontends.slsub]
  backend = "host1"
  passHostHeader = true
  entrypoints = ["http","https"]

    [frontends.slsub.routes.subexample]
    rule = "HostRegexp:{subdomain:[a-z]+}.example.com"


  [frontends.intmain]
  backend = "host1"
  passHostHeader = true
  entrypoints = ["http","https"]

    [frontends.intmain.routes.example1]
    rule = "Host:example1.com"

  [frontends.intsub]
  backend = "host1"
  passHostHeader = true
  entrypoints = ["http","https"]

    [frontends.intsub.routes.subexample1]
    rule = "HostRegexp:{subdomain:[a-z]+}.example1.com"

[backends]

  [backends.host1]
    [backends.host1.servers.server1]
    url = "http://10.0.74.81:80"

```
