### ISSUE TITLE
oAuth, dashboard and path getting ignored

### ISSUE THREAD

**Issue by devster31** [traefik/traefik#4504]
#### Do you want to request a *feature* or report a *bug*?

Bug

#### What did you do?

Ran an instance of `traefik` to route services. I'm trying to secure the dashboard with `oauth2_proxy`. See pusher/oauth2_proxy#46

#### What did you expect to see?
Given my configuration I expected to see the dashboard at `DOMAIN/traefik` secured by oAuth and other services (a `znc` instance for example), reachable without authorization. Also if no rules are given the default rule is:
```
Host:<SERVICENAME>.home # maybe this is the name of the compose stack??
```

#### What did you see instead?
All paths seem have a `403` unauthorized code but only when using a domain name and not when using a LAN address.

#### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

#### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
version: '3.7'

networks:
  backend: {}

services:
  oauth2:
    command:
    # - -client-id     # environment
    # - -client-secret # environment
    # - -cookie-secret # environment
    - "-cookie-secure=false"
    - "-email-domain=*"
    - "-github-org=dispenserinc"
    - "-provider=github"
    - "-redirect-url=http://login.${DOMAIN}/oauth2/callback"
    - "-set-xauthrequest"
    - "-set-authorization-header"
    - "-http-address=0.0.0.0:4180"
    environment:
      - "OAUTH2_PROXY_CLIENT_ID=${GITHUB_OAUTH_CLIENT_ID}"
      - "OAUTH2_PROXY_CLIENT_SECRET=${GITHUB_OAUTH_CLIENT_SECRET}"
      - "OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}"
    expose:
      - "4180"
    image: quay.io/pusher/oauth2_proxy:v3.1.0
    labels:
      - "traefik.frontend.rule=Host:login.${DOMAIN},${DOMAIN},PathPrefix=/oauth2"
    networks:
      - backend
    restart: unless-stopped

  traefik:
    command:
      - --accesslog
      - --api # defaults to port 8080
      - --docker
      - --docker.network=backend
      - --defaultentrypoints=http
      # - --debug
    image: traefik:maroilles-alpine
    labels:
      - "traefik.api.port=8080"
      - "traefik.api.fronted.entrypoints=traefik"
      - "traefik.api.frontend.rule=PathPrefixStrip:/traefik"
      - "traefik.api.frontend.auth.forward.address=http://login.${DOMAIN}/oauth2/auth"
      - "traefik.api.frontend.auth.forward.authResponseHeaders=X-Auth-Request-User,X-Auth-Request-Email,Set-Cookie"
      - "traefik.api.frontend.auth.forward.headerField=X-Auth-Request-User"
      - "traefik.api.frontend.errors.401.backend=oauth2-home"
      - "traefik.api.frontend.errors.401.status=401"
      - "traefik.api.frontend.errors.401.query=/oauth2/sign_in"
    networks:
      - backend
      - default
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTPS port
      - "8080:8080" # The Web UI (enabled by --api)
    restart: unless-stopped
    # user: cannot run as user to bind privileged ports
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # So that Traefik can listen to the Docker events

  znc:
    container_name: znc
    image: znc:1.7
    labels:
      # requires URIPrefix = /znc/
      - "traefik.frontend.rule=PathPrefix:/znc"
    expose:
      - "6501"
    networks:
      - backend
    restart: unless-stopped
    user: "${UID}:${GID}"
    volumes:
      - "${MOUNT}/.znc:/znc-data"
```

Here a few request examples:
```
# example of a request from LAN
traefik_1    | 10.0.0.150 - - [18/Feb/2019:21:59:37 +0000] "GET / HTTP/1.1" 404 19 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.20 Safari/537.36" 2 "backend not found" "/" 0ms

# example of an expected redirect to oAuth request from the LAN (http://<LOCALIP>/traefik
traefik_1    | 10.0.0.150 - - [18/Feb/2019:21:44:50 +0000] "GET /traefik HTTP/1.1" 200 2471 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.20 Safari/537.36" 2 "Host-login-alioth-ovh-alioth-ovh-PathPrefix-oauth2-4" "http://172.18.0.3:4180" 51ms

# successfully reaching /znc path
traefik_1    | 10.0.0.150 - - [18/Feb/2019:22:00:52 +0000] "GET /znc HTTP/1.1" 302 380 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.20 Safari/537.36" 5 "PathPrefix-znc-5" "http://172.18.0.4:6501" 3ms
traefik_1    | 10.0.0.150 - - [18/Feb/2019:22:00:52 +0000] "GET /znc/ HTTP/1.1" 200 4123 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.20 Safari/537.36" 6 "PathPrefix-znc-5" "http://172.18.0.4:6501" 11ms

# 403 when trying DOMAIN/znc - the 10.0.0.1 is because of hairpin NAT on my router, the same happens with an external IP
traefik_1    | 10.0.0.1 - - [18/Feb/2019:22:01:34 +0000] "GET /znc HTTP/1.1" 403 2474 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.20 Safari/537.36" 7 "Host-login-alioth-ovh-alioth-ovh-PathPrefix-oauth2-4" "http://172.18.0.3:4180" 2ms
traefik_1    | 91.253.146.166 - - [18/Feb/2019:21:51:01 +0000] "GET /znc HTTP/1.1" 403 2474 "-" "Mozilla/5.0 (Android 8.0.0; Mobile; rv:65.0) Gecko/65.0 Firefox/65.0" 9 "Host-login-alioth-ovh-alioth-ovh-PathPrefix-oauth2-4" "http://172.18.0.3:4180" 2ms
```
