### ISSUE TITLE
Mimic consul node healthyness

### ISSUE THREAD

**Issue by pgrangelgo** [traefik/traefik#4536]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Deployed traefik with consul catalog. Exposed a service through consul service and appropriate tags. My services are exposed and accessible and everything works perfectly.

Then, a consul check on one of the backend servers switches from passing to warning.

### What did you expect to see?

Since all tests on the backend node are either passing or warning, I expect my node to still be used as a backend by traefik.

I expect that because this is the way consul manages healthyness: while a node has all its checks either passing or warning, the node is part of the service. Only when a check becomes critical is the node unable to serve.

### What did you see instead?

When a test became warning on my backend server, traefik stopped using my backend server.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.1
Codename:     maroilles
Go version:   go1.11
Built:        2018-09-28_10:24:34PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml#
traefik.toml
logLevel = "INFO"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
    address = ":80"
    compress = true
    [entryPoints.http.redirect]
      regex = "^http://(.*)"
      replacement = "https://$1"
  [entryPoints.https]
    address = ":443"
    compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
        CertFile = "/opt/traefik/ssl/default.crt"
        KeyFile = "/opt/traefik/ssl/default.key"
[consul]
  prefix = "traefik"
[consulCatalog]
  endpoint = "127.0.0.1:8500"
  exposedByDefault = false
  prefix = "traefik"
  constraints=["tag==public"]
[traefikLog]
  format = "json"
[accessLog]
  format = "json"
[acme]
  ...
[ping]
  entryPoint = "http"
[respondingTimeouts]
  # readTimeout is the maximum duration for reading the entire request, including the body.
  readTimeout = "60s"
  # writeTimeout is the maximum duration before timing out writes of the response.
  writeTimeout = "60s"
  # idleTimeout is the maximum duration an idle (keep-alive) connection will remain idle before closing itself.
  idleTimeout = "60s"
```

Seems to be related to this part of code:
https://github.com/containous/traefik/pull/3390/files#diff-cd8329c0a91a00757f75bd879fa2cf7cR284
