### ISSUE TITLE
Bolt WebSocket for Neo4J not working in Traefik

### ISSUE THREAD

**Issue by Gaddea** [traefik/traefik#4566]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm trying to get Neo4J working via Traefik, but so far I have only been able to make the Neo4J browser work, but not been able to login with bolt (bolt://neo4j.domain.com:7687) and get the following error message in the Neo4J browser:

`ServiceUnavailable: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of ...`

Here below are the docker-compose files I'm currently using.

**Traefik docker-compose.yml :**

```
version: '3'

services:
  app:
    container_name: traefik_app
    image: traefik
    restart: always
    command: --loglevel=ERROR
    ports:
      - 80:80
      - 443:443
    expose:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      - traefik.port=8080
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:traefik.domain.com
      - traefik.enable=true
    networks:
      - web

networks:
  web:
    external: true
```

**Neo4J docker-compose.yml :**

```
version: '3'                                                              
                                                                          
services:                                                                 
  neo4j:                                                                  
    container_name: neo4j_app                                             
    image: neo4j:3.5.3                                                    
    networks:                                                             
      - web                                                               
    ports:                                                                
      - 7474:7474                                                         
      - 7687:7687                                                         
    volumes:                                                              
      - ./data:/data                                                      
      - ./logs:/logs                                                      
    environment:                                                          
      - NEO4J_AUTH=neo4j/neo4j
      - NEO4J_dbms_connector_bolt_tls__level=OPTIONAL                     
    labels:                                                               
      - "traefik.backend=neo4j"                                           
      - "traefik.docker.network=web"                                      
      - "traefik.frontend.rule=Host: neo4j.domain.com"                      
      - "traefik.http.port=7474"                                                              
      - "traefik.enable=true"                                                   
    restart: always                                                                           
                                                                          
networks:                                                                 
  web:                                                                    
    external: true      
```                                                  
                                                                

### What did you expect to see?

I expected to be logged in.

### What did you see instead?

The following error message:

ServiceUnavailable: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of ...

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml

debug = false                                                              
logLevel = "ERROR"                                                         
                                                                           
defaultEntryPoints = ["http", "https"]                                     
                                                                           
[api]                                                                      
entryPoint = "traefik"                                                     
                                                                           
[entryPoints]                                                              
    [entryPoints.http]                                                     
    address = ":80"                                                        
        [entryPoints.http.redirect]                                        
        entryPoint = "https"                                               
                                                                           
    [entryPoints.https]                                                    
    address = ":443"                                                       
    [entryPoints.https.tls]                                                
                                                                           
    [entryPoints.traefik]                                                  
    address = ":8080"                                                      
        [entryPoints.traefik.auth.basic]                                   
        users = ["user:$key"]           
                                                                           
[retry]                                                                    
                                                                           
[docker]                                                                   
endpoint = "unix:///var/run/docker.sock"                                   
domain = "domain.com"                                                      
watch = true                                                               
exposedByDefault = false                                                   
                                                                           
[acme]                                                                     
email = "user@domain.com"                                       
storage = "acme.json"                                                      
entryPoint = "https"                                                       
onHostRule = true                                                          
    [acme.httpChallenge]                                                   
    entryPoint = "http"     
```

**Comment by mpl** [comment]
Hi,

Can you please first make sure that you're not hitting this problem?

https://neo4j.com/developer/kb/explanation-of-error-websocket-connection-failure/

**Comment by Gaddea** [comment]
> 
> 
> Hi,
> 
> Can you please first make sure that you're not hitting this problem?
> 
> https://neo4j.com/developer/kb/explanation-of-error-websocket-connection-failure/

Tried adding the following without any result:

```
environment:
  - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
  - NEO4J_dbms_connector_bolt_advertised__address=0.0.0.0:7687
```
When I try added `NEO4J_dbms_connector_bolt__address=0.0.0.0:7687` it just returns an error (See below). I think this has been changed to one of the above but they just forgot to update it on their website.

This is the error message I get when adding `NEO4J_dbms_connector_bolt__address=0.0.0.0:7687` to environment:

```
 ERROR [o.n.s.CommunityBootstrapper] Failed to start Neo4j on unknown address. Invalid connector setting: dbms.connector.bolt_address
org.neo4j.graphdb.config.InvalidSettingException: Invalid connector setting: dbms.connector.bolt_address
        at org.neo4j.kernel.configuration.ConnectorValidator.owns(ConnectorValidator.java:84)
        at org.neo4j.kernel.configuration.ConnectorValidator.lambda$ownedEntries$0(ConnectorValidator.java:131)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.neo4j.kernel.configuration.ConnectorValidator.validate(ConnectorValidator.java:141)
        at org.neo4j.kernel.configuration.IndividualSettingsValidator.validate(IndividualSettingsValidator.java:61)
        at org.neo4j.kernel.configuration.Config.migrateAndValidateAndUpdateSettings(Config.java:807)
        at org.neo4j.kernel.configuration.Config.<init>(Config.java:420)
        at org.neo4j.kernel.configuration.Config.<init>(Config.java:84)
        at org.neo4j.kernel.configuration.Config$Builder.build(Config.java:314)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:107)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
2019-03-08 17:41:15.396+0000 INFO [o.n.s.CommunityBootstrapper] Neo4j Server shutdown initiated by request
command failed: Invalid connector setting: dbms.connector.bolt_address
```

By the way, if I try to go directly to neo4j.domain.com:7687 on my browser I get the following error:

`not a WebSocket handshake request: missing upgrade`

**Comment by thetheodoros** [comment]
hi @Gaddea 
the problem you encountered is not - at least to my knowledge - fully resolvable.

There are two problems I have encountered trying to achieve this:
1. When the neo4j browser is connected by https it will not connect to an insecure bolt, so that is why you get the `Service unavailable ` message in your browser.
2. I am not really sure where the problem lies here exactly, but I will try to sum up what I did. After understanding that an encrypted connection to the neo4j browser via https requires a secured bolt connection, I created a rule for the bolt port too which was encrypted using https (the same way I set up my secure neo4j browser connection). When trying to connect via this new rule, it seems that bolt and https wouldn't work in this combination, to some people this might seem obvious but I thought since bolt is just some kind of websocket I might give it a try. 

IMPORTANT - This is not a solution to the https problem, just a simpler way to manage neo4j in a team due to subdomains instead of port managing. 
So what I do now is not use the neo4j browser at all on security relevant systems (I enter the shell manually if there is anything to do) and for development I am running neo4j over http and limiting neo4j connection via traefik's IP whitelist. 

This way you can at least configure multiple neo4j instances on the same machine without having to keep everybody on your team informed which ports lead to which instance.

Here is the configuration:
traefik.toml
```
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
   [entryPoints.https.tls]
  [entryPoints.bolt]
  address = ":7687"
  [entryPoints.neo]
  address = ":7474"
[accessLog]

[retry]

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true
[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "domain.com"
  watch = true
  exposedbydefault = false
[acme]
  email = "office@domain.com"
  storageFile = "acme.json"
  entryPoint = "https"
  onHostRule = true
[acme.httpChallenge]
  entryPoint = "http"

```
traefik docker-compose.yml
```
version: '2.4'
services:
  traefik:
    image: traefik:latest
    command: --api --docker
    restart: always
    networks:
      - web
      - neo4j
    ports:
      - 80:80
      - 443:443
      - 7474:7474
      - 7687:7687
    labels:
      - "traefik.frontend.rule=Host:traefik-dev.domain.com"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.docker.network=web"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
networks:
  web:
    external: true
  neo4j:
    external: true
```

neo4j docker-compose.yml
```
version: '2.4'
networks:
  neo4j:
    external: true
services:
  some-neo4j-dependent-webservice:
    image: service
  neo4j-container:
    image: neo4j
    networks:
      - default
      - neo4j
    labels:
      traefik.frontend.whiteList.sourceRange: 123.123.123.123
      traefik.docker.network: neo4j
      traefik.enable: true
      traefik.certificate.frontend.rule: Host:neo4j.domain.com
      traefik.certificate.frontend.entryPoints: http,https
      traefik.certificate.port: 7474
      traefik.basic.frontend.rule: Host:neo4j.domain.com
      traefik.basic.frontend.entryPoints: neo
      traefik.basic.port: 7474
      traefik.basic.frontend.protocol: http
      traefik.basic.protocol: http
      traefik.bolt.frontend.rule: Host:neo4j.domain.com
      traefik.bolt.frontend.entryPoints: bolt
      traefik.bolt.frontend.protocol: http
      traefik.bolt.port: 7687

```

**Comment by alexluna7** [comment]
Hi @Gaddea 

I’m also trying to setup a development environment using Docker, Traefik and Neo4j and I’m having a similar same issue as you: I can connect to Neo4j Browser interface but I’m not able to login to the database itself. Did you manage to use Neo4j behind Traefik? If yes, can you share the solution.

Cheers.

**Comment by cellcoresystems** [comment]
Hi All,
First, I really have to say that I have struggled with this issue a lot and it took me a while to get it working.

The solution is as always more easy than we think. **Do not use Firefox for that**. Chrome{,ium} is fine.

> Important !!! 
This is neo4j behind traefik 2 and all served over https and port 443.
And only for accessing the db with the neo4j browser through traefik.
Accessing the neo4j db with any other driver is not tested.

You should be able to access the neo4j browser with https://example.com/neo4j

./neo4j/conf/neo4j.conf:
```
dbms.default_listen_address=0.0.0.0
dbms.default_advertised_address=example.com  #only use an IP address or hostname NO port
dbms.connector.bolt.advertised_address=:443  #needed for accepting connections from neo4j browser
```
docker-compose.yml:
```
version: "3.7"
services:
  traefik:
    image: "traefik:v2.2"
    command:
      - --api
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websec
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websec.address=:443
      - --providers.file.directory=/config/
      - --providers.file.watch=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`example.com`) && PathPrefix(`/api`) || PathPrefix(`/dashboard`)" 
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.middlewares=authtraefik"
      # create entry with: printf "username:`openssl passwd -apr1`\n" >> users.db
      - "traefik.http.middlewares.authtraefik.basicauth.usersfile=/config/users.db"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/config:/config:ro"
      - "./traefik/certs:/certs:ro"
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"

  neo4j:
    image: neo4j:4.0.4
    depends_on:
      - traefik
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.neo4j.entrypoints=websec"
      - "traefik.http.routers.neo4j.rule=Host(`example.com`) && PathPrefix(`/neo4j`)||PathPrefix(`/browser`)"
      - "traefik.http.routers.neo4j.tls=true"
      - "traefik.http.routers.neo4j.middlewares=neo4j_strip"
      - "traefik.http.middlewares.neo4j_strip.stripprefix.prefixes=/neo4j"
      - "traefik.http.services.neo4j.loadbalancer.server.port=7474"
      - "traefik.http.routers.neo4jdb.entrypoints=websec"
      - "traefik.http.routers.neo4jdb.rule=Host(`example.com`)"
      - "traefik.http.routers.neo4jdb.tls=true"
      - "traefik.http.services.neo4jdb.loadbalancer.server.port=7687"
    volumes:
      - "./neo4j/data:/data"
      - "./neo4j/import:/var/lib/neo4j/import"
      - "./neo4j/conf:/var/lib/neo4j/conf"
    networks:
      - default
    # ports only for documentation
    #ports:
      #  - 7474
      #  - 7687
```
./traefik/config/certs.yml
```
tls:
  certificates:
    - certFile: "/certs/example.com.crt"
      keyFile: "/certs/example.com.nokey"
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/example.com.crt"
        keyFile: "/certs/example.com.nokey"
```
Put your certs in ./traefik/certs/example.com.crt
