### ISSUE TITLE
Support docker ssh daemon endpoint

### ISSUE THREAD

**Issue by frejonb** [traefik/traefik#4598]
### Do you want to request a *feature* or report a *bug*?
Feature

### Suggestion

Docker supports connecting to a daemon via ssh from 18.09: https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option 

Implementing this would solve the security issues of mounting the Unix socket, as well as being able to run on worker.

### What did you expect to see?
Support for ssh protocol

### What did you see instead?
Only TCP or Unix

**Comment by cakiwi** [comment]
While the documentation suggests that a user can run the docker provider with a providers.docker.endpoint using ssh the reality is the container is missing the ssh binary or a go ssh connector.

https://community.traefik.io/t/failing-to-specify-an-ssh-endpoint-for-docker-provider/9738

**Comment by nodje** [comment]
+1

**Comment by yvess** [comment]
I solved it like that, mounting root ssh folder and create a custom `entrypoint.sh`:

```yaml
# docker-compose.yml
services:
  traefik:
    image: traefik:v2.9
   ...
    volumes:
     ...
      - ./ssh:/root/.ssh/
      - ./entrypoint.sh:/entrypoint.sh
```

```bash
# entrypoint.sh
#!/bin/sh
set -e

# add openssh for ssh docker connection
apk add openssh

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- traefik "$@"
fi

# if our command is a valid Traefik subcommand, let's invoke it through Traefik instead
# (this allows for "docker run traefik version", etc)
if traefik "$1" --help >/dev/null 2>&1
then
    set -- traefik "$@"
else
    echo "= '$1' is not a Traefik command: assuming shell execution." 1>&2
fi

exec "$@"
```
