### ISSUE TITLE
Race between k8s Traefik client and k8s API

### ISSUE THREAD

**Issue by recet** [traefik/traefik#4711]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Using traefik 1.7.8 as daemonset, and gke 1.12.6 with autoscaling.
During scaling up, new traefik pod is started.

### What did you expect to see?

```
... 
level=info msg="Creating in-cluster Provider client"
```

### What did you see instead?

```
level=info msg="Creating cluster-external Provider client"
level=error msg="Error starting provider *kubernetes.Provider: endpoint missing for external cluster client"
```

and the pod starts responding with http 404 on all requests.

According to traefik docs (https://docs.traefik.io/configuration/backends/kubernetes/#endpoint), it will try to use external-cluster client if env variables are not there. However, regardless of it is successful or not, the pod starts.

From kubernetes api logs, I also notice that traefik actually starts about 10 seconds before the kube-proxy application on the node is ready.

It is quite hard to recreate as it does not always happen. Seems to happen during "rapid" upscaling (increase on cpu usage, scaling several nodes at the same time) - high pressure on the nodes.

Resolved by killing the treafik pod (it starts normally when we kill it).

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
image: traefik:1.7.8
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

GKE 1.12.6

```toml
    logLevel = "{{ .Values.logLevel }}"
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
          entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]
        {{- if .Values.acme.enabled }}
          [[entryPoints.https.tls.certificates]]
          CertFile = "REDACTED"
          KeyFile = "REDACTED"
        {{- else }} 
```

**Comment by emilevauge** [comment]
@dtomcej any idea on this? Shouldn't we have a retry/backoff instantiating the k8s client?

**Comment by dtomcej** [comment]
If the traefik pod does not have the proper secrets mounted, and the environment variables when the pod starts up, it would almost certainly require a pod restart to enforce a clean mount of the secrets.

Attempting to reconnect to k8s without the credentials after a failure would not really accomplish much, as the pod would not have changed in the interim.

I think that this is not a traefik issue, but a k8s issue, where the expected pod mounts are not propagating fast enough.

I would suggest that implementing a more stringent liveliness check could be implemented to ensure that the pod is automatically restarted if the volumes are not properly mounted.

@recet, Do you have readiness/liveliness checks enabled as part of your pod spec?

**Comment by recet** [comment]
@dtomcej  thanks for the response.

I see.

We have a very basic liveness check which in this case is not optimal.

```
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 2
```

Our initial thoughts were also similar to what you are suggesting, that is, setting a liveness probe that checks if the env variables are available for the pod. However, I suspect it might fail in some cases anyways. Considering the following startup scenario:
1. traefik is starting up.
2. liveness probe fails at first try.
3. traefik starts anyway "normally", with failed state `level=error msg="Error starting provider *kubernetes.Provider: endpoint missing for external cluster client"`
4. liveness probe gives OK at second try (since the node is now ready)
5. traffic is routed to that pod and starts to respond with 404.

Of course we can set a more "strict" liveness probe, that fails at first attempt, but that just doesn´t feel like the right approach. What do you suggest we do?

I am guessing that a lot of people that use traefik as daemonset are actually experiencing this issue, but not catching it due to following reasons:
1. Most teams/orgs do not count http response 404 as "down time" and do not track that error code closely
2. Most teams/orgs have limited set of endpoints they consider "critical" enough to closely monitor daily. However, when this issue is triggered, the "backend service" is not defined as the actual kubernetes service, but just named "traefik" in traefiks logs. So the 404 errors goes unnoticed by all alerts and measurements on critical endpoints for that team. Basically you are "dependent" on a well functioning ops team that catches spike on 404 on the overall traffic.
3. In larger environments with autoscaling, this issue affects just a "small percentage" of total requests, and most likely gets resolved after a short time period (when the traffic peak is over) due to "downscaling" (kubernetes nodes are scaled down in LIFO fashion and the node with the problem pod is gone during the downscaling).

And when they first catch it, it is hard to describe and is not that critical (for example; https://github.com/containous/traefik/issues/1989) 

In our case, we first noticed this behaviour few months ago but failed to "consider" it as critical as it was small percentage (<5%) and went away by itself. It became more obvious when our traffic more than doubled since, and the total number of 404 responses were too high to ignore. Then we started to track this specific response in our alerting systems and actually noticed that it is triggered several times a week during upscaling.

Our preferred solution for now is to stop using treafik as daemonset and go back to deployment setup.

**Comment by smithkb** [comment]
I'm seeing this same issue on Traefik 1.7.12 and k8s 1.18. I didn't see it prior to upgrading to 1.18, but it seems to be an almost daily occurrence now. I'm using Traefik in a deployment, not a daemonset.

**Comment by smithkb** [comment]
Interesting enough... I'm not seeing this on Traefik 1.7.5 with k8s 1.18.

**Comment by ddtmachado** [comment]
I agree with @dtomcej as this is probably a k8s issue and I propose a workaround that will not rely on timed delays or livenessProbe. 

You can add an init container to make sure that the service account credentials will be present by the time the Traefik container starts, something like this:

```yaml
initContainers:
        - name: wait-api
          image: busybox:1.31.1
          command: ['sh', '-c', 'until test -d /var/run/secrets/kubernetes.io/serviceaccount; do echo "Waiting for serviceaccount availability";sleep 1;done;']
```

I quickly tested this with `v1.7.26` running as daemonset on a GKE cluster while scaling up and down a few times and saw no failures on new pods/nodes.

Can you try this and let us know if it fixes the issue as well?
