### ISSUE TITLE
Traefik should report traefik_backend_server_up 0 for unhealthy backends

### ISSUE THREAD

**Issue by rinokadijk** [traefik/traefik#4853]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Scale an application that never becomes healthy in marathon. Traefik reports traefik_backend_server_up 1 for all backends

### What did you expect to see?

According to the documentation:
```
# HELP traefik_backend_server_up Backend server is up, described by gauge value of 0 or 1.
# TYPE traefik_backend_server_up gauge
traefik_backend_server_up{backend="backend-my-service",url="http://xxx:yyy"} 1
```

For an unhealthy backend I would expect:
```
# HELP traefik_backend_server_up Backend server is up, described by gauge value of 0 or 1.
# TYPE traefik_backend_server_up gauge
traefik_backend_server_up{backend="backend-my-service",url="http://xxx:yyy"} 0
```
### What did you see instead?

traefik_backend_server_up 1 for all (even unhealthy) backends

### Output of `traefik version`: 1.7.9
```
1.7.9
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
debug = true

logLevel = "DEBUG"


[api]
entryPoint = "api"

[entryPoints]
    [entryPoints.http]
       address = ":80"
     [entryPoints.api]
       address = ":8090"  

[marathon]
    endpoint = "http://marathon:8080"
    domain = "marathon.localhost"
    exposedbydefault = true
```

```
```
