### ISSUE TITLE
mesos provider does not work

### ISSUE THREAD

**Issue by osallou** [traefik/traefik#4870]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [ x] No

### What did you do?

Using Docker image of Traefik (v1.7.8) , I tried the mesos provider (tested against mini mesos mesos/mesos-mini).

### What did you expect to see?

I expected to see some rules from mesos container instances

### What did you see instead?

Traefik failed to connect to mesos. Reason is mesos removed at some time (don't know in which release) the .json endpoints ( master/state.json endpoint in your case) , replacing them with **/state (cf. http://mesos.apache.org/documentation/latest/endpoints/master/state/)

### Output of `traefik version`: (_What version of Traefik are you using?_)

<!-

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
#[mesos]

# Mesos server endpoint.
# You can also specify multiple endpoint for Mesos:
# endpoint = "192.168.35.40:5050,192.168.35.41:5050,192.168.35.42:5050"
# endpoint = "zk://192.168.35.20:2181,192.168.35.21:2181,192.168.35.22:2181/mesos"
#
# Required
# Default: "http://127.0.0.1:5050"
#
endpoint = "127.0.0.1:5050"

# Enable watch Mesos changes.
#
# Optional
# Default: true
#
#watch = true

# Default base domain used for the frontend rules.
# Can be overridden by setting the "traefik.domain" label on an application.
#
# Required
#
domain = "mesos.genouest.org"

```

By the way, examples give mesos endpoint to be *http://127.0.0.1:5050* but it fails with an error, trying to set http://http://127.0.0.1:5050 in this case, I needed to set endpoint to 127.0.0.1:5050 instead (removing http://)

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
# endpoint = http://127.0.0.1:5050
time="2019-05-13T06:48:53Z" level=error msg="Failed to create a client for Mesos, error: no master"
ERROR: 2019/05/13 06:48:53 generator.go:224: parse http://http:%2F%2F131.254.16.176:5050/master/state.json: invalid URL escape "%2F"


# endpoint = 127.0.0.1:5050
time="2019-05-13T06:51:35Z" level=debug msg="new masters detected: [131.254.16.176:5050]"
time="2019-05-13T06:51:35Z" level=error msg="Failed to create a client for Mesos, error: no master"
ERROR: 2019/05/13 06:51:35 generator.go:245: invalid character 'N' after top-level value
```
Looking at http traffic, it indeed receive a 404 Not Found

Wireshark extract:

```
GET /master/state.json HTTP/1.1
Host: 131.254.16.176:5050
User-Agent: Go-http-client/1.1
Content-Type: application/json
Accept-Encoding: gzip

HTTP/1.1 404 Not Found
Date: Mon, 13 May 2019 06:56:25 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 14
```
