### ISSUE TITLE
when upgrade from 1.6.5 to 1.7.12, it says "Leadership election error Existing key does not match lock use, retrying in 1m25.379337654s"

### ISSUE THREAD

**Issue by yourchanges** [traefik/traefik#5077]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

 No

### What did you do?

we have 3 nodes consul cluster to serve as kv store, and we have 4 nodes traefik 1.6.5 in our PROD env. 

and  then we upgrade  them to 1.7.12, by replace the binary file and restart the process
it serve the requests. but we found many errors in logs(same in 4 traefik nodes)

```
time="2019-07-10T12:47:01+08:00" level=info msg="Using TOML configuration file traefik.toml"
time="2019-07-10T12:47:01+08:00" level=info msg="Traefik version v1.7.12 built on 2019-05-29_07:35:02PM"
time="2019-07-10T12:47:01+08:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2019-07-10T12:47:01+08:00" level=info msg="Preparing server traefik &{Address::6081 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc000337220} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2019-07-10T12:47:01+08:00" level=info msg="Preparing server http &{Address::6080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc000337200} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2019-07-10T12:47:01+08:00" level=info msg="Starting server on :6081"
time="2019-07-10T12:47:01+08:00" level=info msg="Starting provider configuration.ProviderAggregator {}"
time="2019-07-10T12:47:01+08:00" level=info msg="Starting server on :6080"
time="2019-07-10T12:47:01+08:00" level=info msg="Starting provider *consul.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"192.168.254.8:8500\",\"Prefix\":\"traefik\",\"TLS\":null,\"Username\":\"\",\"Password\":\"\"}"
time="2019-07-10T12:47:01+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:47:01+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 336.412011ms"
time="2019-07-10T12:47:01+08:00" level=info msg="Server configuration reloaded on :6080"
time="2019-07-10T12:47:01+08:00" level=info msg="Server configuration reloaded on :6081"
time="2019-07-10T12:47:01+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:47:01+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 832.823106ms"
time="2019-07-10T12:47:02+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:47:02+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 1.553144605s"
time="2019-07-10T12:47:03+08:00" level=info msg="Server configuration reloaded on :6081"
time="2019-07-10T12:47:03+08:00" level=info msg="Server configuration reloaded on :6080"
time="2019-07-10T12:47:03+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:47:03+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 2.491552642s"
time="2019-07-10T12:47:06+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:47:06+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 3.24186298s"
time="2019-07-10T12:47:09+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:47:09+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 2.499415529s"
time="2019-07-10T12:47:12+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:47:12+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 6.854670728s"
time="2019-07-10T12:47:18+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:47:18+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 5.087221012s"
time="2019-07-10T12:47:24+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:47:24+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 11.500642444s"
time="2019-07-10T12:47:35+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:47:35+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 22.077969688s"
time="2019-07-10T12:47:57+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:47:57+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 21.961084832s"
time="2019-07-10T12:48:19+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:48:19+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 38.876177985s"
time="2019-07-10T12:48:58+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:48:58+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 1m14.215265352s"
time="2019-07-10T12:50:12+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:50:12+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 1m25.379337654s"
time="2019-07-10T12:51:38+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:51:38+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 49.463784658s"
time="2019-07-10T12:52:27+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:52:27+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 1m23.519772786s"
time="2019-07-10T12:53:51+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:53:51+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 1m1.224244398s"
time="2019-07-10T12:54:52+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:54:52+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 38.298958136s"
time="2019-07-10T12:55:30+08:00" level=info msg="Node 0e7efc5f-925c-4ce2-8cc9-196dce759e66 elected worker ♝"
time="2019-07-10T12:55:30+08:00" level=error msg="Leadership election error Existing key does not match lock use, retrying in 1m6.559788254s"


```

### Output of `traefik version`: (_What version of Traefik are you using?_)
traefik 1.7.12 1.6.5

consul_0.7.2

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# Global configuration
################################################################

# Enable debug mode
#
# Optional
# Default: false
#
#debug = true

# Log level
#
# Optional
# Default: "ERROR"
#
logLevel = "INFO"

maxIdleConnsPerHost = 100000

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
# defaultEntryPoints = ["http", "https"]

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
    [entryPoints.http]
    address = ":6080"
    [entryPoints.traefik]
    address = ":6081"

################################################################
# Traefik logs configuration
################################################################

# Traefik logs
# Enabled by default and log to stdout
#
# Optional
#
[traefikLog]

# Sets the filepath for the traefik log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
#
# Optional
# Default: os.Stdout
#
filePath = "/opt/traefik/log/traefik.log"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
# format = "common"

################################################################
# Access logs configuration
################################################################

# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields.
#
# Optional
#
# [accessLog]

# Sets the file path for the access log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
#
# Optional
# Default: os.Stdout
#
# filePath = "/path/to/log/log.txt"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
# format = "common"

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]

  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
entryPoint = "traefik"

  # Enabled Dashboard
  #
  # Optional
  # Default: true
  #
  # dashboard = false

################################################################
# Ping configuration
################################################################

# Enable ping
[ping]

  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  # entryPoint = "traefik"

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
#[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
# Default: "unix:///var/run/docker.sock"
#
# endpoint = "tcp://10.10.10.10:2375"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
#
# Optional
# Default: ""
#
# domain = "docker.localhost"

# Expose containers by default in traefik
#
# Optional
# Default: true
#
# exposedByDefault = true

################################################################
# Eureka configuration backend
################################################################

# Enable Eureka configuration backend.
#[eureka]

# Eureka server endpoint.
#
# Required
#
#endpoint = "http://192.168.254.8:8761/eureka"

# Override default configuration time between refresh.
#
# Optional
# Default: 30s
#
#refreshSeconds = "1m"

# Override default configuration template.
# For advanced users :)
#
# Optional
#
# filename = "eureka.tmpl"

################################################################
# Consul KV configuration backend
################################################################

# Enable Consul KV configuration backend.
[consul]

# Consul server endpoint.
#
# Required
# Default: "127.0.0.1:8500"
#
endpoint = "192.168.254.8:8500"

# Enable watch Consul changes.
#
# Optional
# Default: true
#
watch = true

# Prefix used for KV store.
#
# Optional
# Default: traefik
#
prefix = "traefik"

# Override default configuration template.
# For advanced users :)
#
# Optional
#
# filename = "consul.tmpl"

# Use Consul user/pass authentication.
#
# Optional
#
# username = foo
# password = bar

# Enable Consul TLS connection.
#
# Optional
#
#    [consul.tls]
#    ca = "/etc/ssl/ca.crt"
#    cert = "/etc/ssl/consul.crt"
#    key = "/etc/ssl/consul.key"
#    insecureSkipVerify = true

```
