### ISSUE TITLE
Docker Provider in swarm mode: Infer Traefik configuration from Service labels

### ISSUE THREAD

**Issue by shaun-blake** [traefik/traefik#5134]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I think the best way to explain the feature I'm requesting is through a concrete example.

I would like to add something like these labels to a service (in this case a compose file):

```yml
labels:
  - traefik.http.routers.my-router.rule=...
  - traefik.http.middlewares.my-middleware.stripprefix.prefixes=...
  - traefik.http.services.my-service.loadbalancer.server.port=...
```

Then, when Traefik (in swarm mode) reads the labels off the service, it could generate the Traefik configuration that would be the equivalent of this:
```yml
labels:
  - traefik.http.routers.<swarm-service-name>-my-router.rule=...
  - traefik.http.routers.<swarm-service-name>-my-router.middlewares="<swarm-service-name>-my-middleware"
  - traefik.http.middlewares.<swarm-service-name>-my-middleware.stripprefix.prefixes=...
  - traefik.http.routers.<swarm-service-name>-my-router.service="<swarm-service-name>-my-service"
  - traefik.http.services.<swarm-service-name>-my-service.loadbalancer.server.port=...
```

In the context of the deploying a service, Traefik has enough information that it could simplify the configuration that needs to be added manually. 

Doing that would allow deploying multiple stacks from the same compose file (see https://community.containo.us/t/traefik-v2-unique-deployment-labels-from-the-same-compose-file) and my guess is that it would be more intuitive to people (see https://community.containo.us/t/traefik-docker-label-scope/853/1).

This would also prevent the case where two teams that deploy into the same swarm accidentally choose the same router name and take down the other team's application.

The same thing could probably be done for the docker provider when not in swarm mode (using the container name), too.

Thanks!

**Comment by tuwaertuwa** [comment]
标签:
  - traefik.http.routers.<swarm-service-name>-my-router.rule=.
  - traefik.http.routers.<swarm-service-name>-my-router.middlewares=“<swarm-service-name>-my-middleware”
  - traefik.http.middlewares.<swarm-service-name>-my-middleware.stripprefix.prefixes=.
  - traefik.http.routers.<swarm-service-name>-my-router.service=“<swarm-service-name>-my-service”
  - traefik.http.services.<swarm-service-name>-my-service.loadbalancer.server.port=.

**Comment by kinghuang** [comment]
I'm also interested in this. For Swarm-based deployments, I originally thought I could get this done using [service templates](https://docs.docker.com/engine/reference/commandline/service_create/#create-services-using-templates). But, it turns out that Swarm only supports templating hostname, mount, and environment properties, not labels.

**Comment by trajano** [comment]
Perhaps use `*` or some other **single** character to represent the current service name.  It would be much easier to catch and type.

**Comment by ruimaciel** [comment]
I suspect this issue could also be interpreted as a bug, because apparently Traefik ignores services deployed in different stacks if they share the same service name.  For example, if I deploy two stacks to a swarm (stack `foo` and stack `bar`) which include services that share the same name (for example, `frontend`)  then, although Docker lists two independent services running well (i.e., `foo_frontend` and `bar_frontend`), traefik starts to behave poorly and ultimately cuts routes to the services launched as part of those stacks.

**Comment by ston3o** [comment]
Before traefik:v2 I just have to add this deploy labels and execute `docker stack deploy` multiple times :

```yaml
etherpad:
  image: etherpad/etherpad:latest
  deploy:
    labels:
      traefik.port: 80
      traefik.frontend.rule: Host:${DOMAIN:?err}
      traefik.enable: "true"
```
Now I can't deploy multiple etherpad instances :(

```yaml
etherpad:
  image: etherpad/etherpad:latest
  labels:
    - traefik.enable=true
    - traefik.http.routers.etherpad.rule=Host(`${DOMAIN:-etherpad.localhost}`)
    - traefik.http.routers.etherpad.tls=${HTTPS:-false}
    - traefik.http.routers.etherpad.tls.certresolver=mytlschallenge
```
I have an error : `Router defined multiple times with different configurations`
