### ISSUE TITLE
Traefik 1.7.12 - websockets memory load

### ISSUE THREAD

**Issue by WTFKr0** [traefik/traefik#5149]
### Do you want to request a *feature* or report a *bug*?

bug

### Did you try using a 1.7.x configuration for the version 2.0?

No

### What did you do?

After a load test on an app behind traefik, we see a lot a memory used by traefik, and not free after perf test
Sometimes, our traefik container growth to the hard memory limit and is killed
The perf test is about websocket connections
I found some issues but they seem to be already ok in version 1.7.12 that we used
We got 3 traefik instances, and each is growing to 800Mo RAM for 15000 websocket connections
Context: Docker swarm, 3 traefik instances, nodejs websocket backend

This is the graph of memory usage over the test, here 100% = 1GB RAM
We can see the 3 traefik replicas
When 100% is reach, linux kernel kill the containers (hard limit)
![image](https://user-images.githubusercontent.com/15888093/61720583-5755fa80-ad67-11e9-83ec-1275e07d9c33.png)

### What did you expect to see?

Less emory consuption and memory decrease after load test

### What did you see instead?

Memory not decrease, but stay same
High memory load

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
/traefik
--api
--api.dashboard
--entrypoints=Name:http Address::80
--entrypoints=Name:https Address::443 TLS
--metrics.prometheus
--defaultentrypoints=http,https
--insecureskipverify=true
--docker
--docker.swarmMode
--docker.swarmmoderefreshseconds=5
--docker.domain=our.domain.com
--docker.watch
--accessLog
--accessLog.format=json
--accessLog.fields.headers.defaultMode=redact
--lifecycle.gracetimeout=10s
--debug
```

### If applicable, please paste the log output at DEBUG level (`--log.level=DEBUG` switch)

Some pprof files just before crash (~900MB memory used)
[perfs.tar.gz](https://github.com/containous/traefik/files/3422534/perfs.tar.gz)

**Comment by dtomcej** [comment]
Hello @WTFKr0, can you please test with some responding and forwarding timeouts set?
(https://docs.traefik.io/configuration/commons/#timeouts)

Websockets have a tendancy to hold connections open after they are done sending data.
We want to confirm its not an issue of just connections being held open.

Thanks!

**Comment by WTFKr0** [comment]
Have done some more tests
I try to set traefik memory limit to a big value
In this scenario, it's the backend that can't handle load
I watch live tcp connection on traefik, and see it grows, and memory too
When backends crash, the tcp connection disappeared, but memory usage stay the same
I let traefik this night to see if it garbage collect memory later
I'll try timeouts tomorrow and let you know
Thanx

**Comment by WTFKr0** [comment]
@dtomcej 
Which timeouts and which values can i set ?
readTimeout / writeTimeout / idleTimeout ?

**Comment by dtomcej** [comment]
Hello @WTFKr0,

In particular, the responding  idleTimeout (https://docs.traefik.io/configuration/commons/#responding-timeouts) is the one that I am interested in.

By default, traefik keeps idle connections open for a default of 180s (3 minutes), which if you have high rps, may allow connections to stack up too quickly.

You may want to tune those values to suit your load.

But yes, traefik should GC and release memory as the connections decrease, but it is not immediate.

**Comment by WTFKr0** [comment]
Here some more information

I reproduce my issue with a simple docker-compose on my production-like node, by can't reproduce on my laptop (which has a different os and docker version)

This is what i do : 

docker-compose.yml:
```
version: "2"

services:

  traefik:
    image: traefik:1.7.12
    command: |
      - "--api"
      - "--api.dashboard"
      - "--entrypoints=Name:http Address::80"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--insecureskipverify=true"
      - "--docker"
      - "--docker.watch"
    ports:
      - "3080:80"
      - "38080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  ws:
    image: ksdn117/web-socket-test
    labels:
      - "traefik.frontend.rule=Host:localhost"
      - "traefik.port=8010"

```

loadtest1.yml:
```
  config:
    target: "ws://localhost:3080"
    phases:
      - duration: 60  # Test for 20 seconds
        arrivalRate: 100 # Every second, add 10 users
        rampTo: 1000 # Ramp it up to 100 users over the 20s period
        name: "Ramping up the load"
  scenarios:
    - engine: "ws"
      flow:
        - send: 'hello'
        - think: 5
```

Artillery test
```
npm install -g artillery
artillery run loadtest1.yml
```

1) On my laptop
- traefik after startup consume 20 MB memory
- traefik memory grows to 250MB during load test and stay at this level
- after ~ 8 minutes, memory decrease to 50 MB

2) On my production-like node
- traefik after startup consume 20 MB memory
- traefik memory grows to 310MB during load test and stay at this level
- after 30 minutes, memory i still the same

Laptop:
- ubuntu 19.04
- docker 19.03.0-beta1
- kernel 5.0.0-20-generic

Production like node:
- CoreOS 2135.5.0
- docker 18.06.3-ce
- kernel 4.19.50-coreos-r1
