### ISSUE TITLE
v2.0 Request - Fix trailing slash redirection once and for all.

### ISSUE THREAD

**Issue by mylesagray** [traefik/traefik#5159]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

The issue around URLs not being re-written from my.domain/app to my.domain/app/ on the backend has caused many issues over the years with only regex hacks being employed to fix them:

https://github.com/containous/traefik/issues/563
https://github.com/containous/traefik/issues/4521
https://github.com/containous/traefik/issues/3330
https://github.com/containous/traefik/issues/4804
https://github.com/containous/traefik/issues/3852
https://github.com/containous/traefik/issues/1037

This was apparently fixed in: https://github.com/containous/traefik/pull/1638 but it still persists today - even with the example on the Traefik docs:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cheeses
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: cheese.apps.belfast.blah.cloud
    http:
      paths:
      - path: /stilton
        backend:
          serviceName: stilton
          servicePort: http
      - path: /cheddar
        backend:
          serviceName: cheddar
          servicePort: http
      - path: /wensleydale
        backend:
          serviceName: wensleydale
          servicePort: http
```

The ask is that for 2.0 - The behaviour should be identical to `proxy_pass` Nginx - if a path is specified as `/stilton` it should always add a trailing slash to the path such that if `/stilton` or `/stilton/` are accessed, both work.

It is worth noting that this affects many non-custom built apps, Synology DSM, Portainer, etc - expecting users to implement rewrite rules manually to fix a trailing slash for applications users have no idea about the structure of is no good.

Currently, and it appears for some time this can only be achieved with regex which is terrible UX and results in many hours of searching, reading issues and StackOverflow answers, this should "just work".

**Comment by dtomcej** [comment]
Hey @mylesagray,

The reason that this is not as easy as it may seem is when you say:

>  if a path is specified as /stilton it should always add a trailing slash to the path such that if /stilton or /stilton/ are accessed, both work.

This is very clear in this example that `stilton` is a path component, so `/stilton` and `/stilton/` should be treated the same.

Here is an example where it is not so clear:

What if your path is `/stilton/test.html`? Should the path automatically have a slash added to become `/stilton/test.html/`?
This may be desirable in some situations, but certainly not all.

What happens if you want to have `/stilton/test.html` _and_ `/stilton/test.html/` as separate rules?

I am trying to illustrate why this has not been such a simple "fix" as you may be imagining it to be 😄

**Comment by dtomcej** [comment]
@mylesagray I have discussed this with some team members,

And I think I will work on a proposal for this.

Despite personally not agreeing with it, I do see the value in making it easier for users to use and understand, without having to resort to manual regex.

I will update this ticket with updates.

**Comment by mylesagray** [comment]
Oh for sure, I’m not imagining it to be simple, I’ve read plenty of threads here where people had that exact problem (the trailing slash after their .html or .css or such).

I don’t want it to come off that I think this is some triviality, it definitely isn’t.

I just think this is an important problem that has bitten many people (me included) and caused much frustration with Traefik, and Someone Should Fix It ™ :)

To me it makes sense that the rule is to add the trailing slash everywhere except there there appears to be file at the end, and the case you highlighted where you _want_ it to append a slash after what would appear to be a file, is the exception.

**Comment by tunstek** [comment]
I've been dealing with this issue myself just today. It's particularly annoying when using AddPrefix.

I'm using it to route to auto-generated docs where /redoc/ fails but /redoc works

**Comment by mylesagray** [comment]
Any progress on this given v2 is now GA?

**Comment by pascalandy** [comment]
Using some ninjafoo middleware, it's possible to do this :)
https://community.containo.us/t/fixed-how-to-add-the-missing-trailing-slash-redirectregex-stripprefixregex-no-need-for-replacepathregex/3816/5

**Comment by MikeZappa87** [comment]
I was looking at the internally provided middlewares for the api/dashboard and saw they use the redirectregex "^(http:\/\/[^:\/]+(:\d+)?)\/$" to do this. Or am I mistaken? Hopefully this is added I did something similar

**Comment by pascalandy** [comment]
@MikeZappa87 how would you replace this?

```
    labels:
      ...
        #___ add missing trailing slash
      - "traefik.http.middlewares.our-slash.chain.middlewares=strip-prefix-1,strip-prefix-2"
      - "traefik.http.middlewares.strip-prefix-1.redirectregex.regex=^(https?://[^/]+/[a-z0-9_]+)$$"
      - "traefik.http.middlewares.strip-prefix-1.redirectregex.replacement=$${1}/"
      - "traefik.http.middlewares.strip-prefix-1.redirectregex.permanent=true"
      - "traefik.http.middlewares.strip-prefix-2.stripprefixregex.regex=/[a-z0-9_]+"
```

**Comment by MindTooth** [comment]
@pascalandy Care to verify if this still works?  Copied your code, but still unable to serve Portainer on `URL/portainer`.

```yaml
portainer:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`battlestation.lan`) && PathPrefix(`/portainer`)"
      - "traefik.http.middlewares.our-slash.chain.middlewares=strip-prefix-1,strip-prefix-2"
      - "traefik.http.middlewares.strip-prefix-1.redirectregex.regex=^(https?://[^/]+/[a-z0-9_]+)$$"
      - "traefik.http.middlewares.strip-prefix-1.redirectregex.replacement=$${1}/"
      - "traefik.http.middlewares.strip-prefix-1.redirectregex.permanent=true"
      - "traefik.http.middlewares.strip-prefix-2.stripprefixregex.regex=/[a-z0-9_]+"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

**Comment by pascalandy** [comment]
I now use a middleware to manage the missing trailing slash:

```
# slash_step1 + slash_step2 | Add missing trailing slash
- "traefik.http.middlewares.slash-step1.redirectregex.regex=^(https?://[^/]+/[a-z0-9_]+)$$"
- "traefik.http.middlewares.slash-step1.redirectregex.replacement=$${1}/"
- "traefik.http.middlewares.slash-step1.redirectregex.permanent=true"
- "traefik.http.middlewares.slash-step2.stripprefixregex.regex=/[a-z0-9_]+"
```

**Comment by petercinibulk** [comment]
@pascalandy The above does not work for me. The URL ends up getting turned into https://example.com/$%7B1%7D/ instead of https://example.com/portainer/

**Comment by chris-aeviator** [comment]
This is causing issues on multiple products here - is there a reason why this has not been solved since 2019..I mean..it's 2021 now?!

**Comment by kedarnok** [comment]
@petercinibulk Replacement should be 
- "traefik.http.middlewares.slash-step1.redirectregex.replacement=${1}/"

**Comment by raph-berteaud** [comment]
This would be a very appreciated feature indeed ! I switched from nginx to Traefik because it was way more suited for dockerized applications, but the impossibility to recreate nginx's proxy_pass feature for path-based routing (without the middlewares witchcraft) is a pity !

**Comment by GokulNC** [comment]
As a temporary solution, on my `traefik` server's `routes.toml` file, I have added the following middleware (used only for code-server):

```
[http.middlewares.code-slash-suffix.redirectRegex]
      regex = "/code$"
      replacement = "/code/"
```

**Comment by FStefanni** [comment]
Hi,

same issue here: only for few services I need the trailing `/`, just in case of the base url where the service is exposed.
The trick with the regex redirect works fine for me.
Nevertheless, a simpler feature support would be nice.

Regards.

**Comment by mangkoran** [comment]
Any update regarding this issue? This issue has been opened for some time and several releases.

**Comment by gajus** [comment]
While these solutions work, it would be nice to have a built-in option for keeping trailing slashes.

For anyone else who run into this, the Go playground is a good place to debug your regex.

https://play.golang.org/p/mWU9p-wk2ru

If you are going with this approach, there are some gotchas to consider, e.g.

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
  # {{ include "app.resource_labels" . | indent 4 }}
  name: "{{ .Release.Name }}-trailing-slash"
spec:
  redirectRegex:
    regex: "^(.*)\\/freelance-industry-report-2021$"
    replacement: "${1}/freelance-industry-report-2021/"
    permanent: false
```

If you are debugging this locally by overriding `Host` header, this will produce unexpected redirect:

```
curl 'http://127.0.0.1:8020/freelance-industry-report-2021' -H 'Host: contra.com' -v
*   Trying 127.0.0.1:8020...
* Connected to 127.0.0.1 (127.0.0.1) port 8020 (#0)
> GET /freelance-industry-report-2021 HTTP/1.1
> Host: contra.com
> User-Agent: curl/7.77.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Location: http://contra.com/freelance-industry-report-2021/
< Date: Tue, 25 Jan 2022 20:22:10 GMT
< Content-Length: 5
< Content-Type: text/plain; charset=utf-8
```

In such case, you want to exclude the host from the redirect:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
  # {{ include "app.resource_labels" . | indent 4 }}
  name: "{{ .Release.Name }}-trailing-slash"
spec:
  redirectRegex:
    regex: "^(.*)\\/freelance-industry-report-2021$"
    replacement: "/freelance-industry-report-2021/"
    permanent: false
```
