### ISSUE TITLE
Strange behavior with Ingress Matching

### ISSUE THREAD

**Issue by santiagopoli** [traefik/traefik#5187]
Hi There! I’m having a strange behavior I believe is a Traefik bug (if it’s not, I would like to understand why it is happening).

Fortunately I was able to reproduce it with a simple setup which can be cloned from https://github.com/santiagopoli/ingress-bug.

The problem is as follows. Given these two ingresses:

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik
  labels:
    app: traefik
  annotations:
    ingress.kubernetes.io/custom-response-headers: X-Service-Name:traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefix
spec:
  rules:
  - host: traefik.127.0.0.1.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: traefik
          servicePort: web
```
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami
  labels:
    app: whoami
  annotations:
    ingress.kubernetes.io/custom-response-headers: X-Service-Name:whoami
    traefik.ingress.kubernetes.io/rule-type: Path
spec:
  rules:
  - host: api.whoami.127.0.0.1.nip.io
    http:
      paths:
      - path: /{any}
        backend:
          serviceName: whoami
          servicePort: http
```

when I do a `curl -H 'Cache-Control: no-cache' -v "http://traefik.127.0.0.1.nip.io:31111/dashboard/"`  it returns

```
< HTTP/1.1 301 Moved Permanently
< Content-Type: text/html; charset=utf-8
< Location: /dashboard
< Date: Thu, 08 Aug 2019 20:41:48 GMT
< Content-Length: 45
<
<a href="/dashboard">Moved Permanently</a>.
```

However, if I do a `kubectl delete ingress whoami` the response is correct:

```
> curl -H 'Cache-Control: no-cache' -v "http://traefik.127.0.0.1.nip.io:31111/dashboard/
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 716
< Content-Type: text/html; charset=utf-8
< Date: Thu, 08 Aug 2019 20:42:44 GMT
< Last-Modified: Wed, 29 May 2019 19:32:44 GMT
< X-Service-Name: traefik
<
* Connection #0 to host traefik.127.0.0.1.nip.io left intact
<!doctype html><html class="has-navbar-fixed-top"><head><meta charset="utf-8"><title>Traefik</title><base href="./"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" type="image/x-icon" href="./assets/images/traefik.icon.png"><link href="styles.e21e21d47be645f690e6.bundle.css" rel="stylesheet"/></head><body><app-root></app-root><script type="text/javascript" src="inline.318b50c57b4eba3d437b.bundle.js"></script><script type="text/javascript" src="polyfills.1457c99db4b6dba06e8d.bundle.js"></script><script type="text/javascript" src="scripts.ef668c5c0d42ec4c5e83.bundle.js"></script><script type="text/javascript" src="main.f341693bf9ed22060b42.bundle.js"></script></body></html>
```

It seems that because the `whoami` ingress has a `/{any}` route, it conflicts with the other ingress. But the Host is different in them, so there shouldn’t be any issues

I found two ways to fix it. One of them was setting the priority of the whoami ingress to 1. The other was replacing the host from api.whoami.127.0.0.1.nip.io to whoami.127.0.0.1.nip.io (without the api.). Adding the --keepTrailingSlash=true setting in traefik worked as well, but I believe this behavior should not be happening

The same behavior happens in both Traefik 1.7.9 and 1.7.12

Thanks!
