### ISSUE TITLE
Send proxy protocol information to service/backend.

### ISSUE THREAD

**Issue by Yivan** [traefik/traefik#5371]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Traefik in V2 can **accept** proxyprotocol (https://docs.traefik.io/v2.0/routing/entrypoints/#proxyprotocol).
It would be nice, if it could **send** proxyprotocol headers to service/backend.
As it now support **TCP** loadbalancer, we could transmit original IP to the service/backend.

Actually, there is no options for this. We tried to set an apache backend with `RemoteIPProxyProtocol On` (https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html#remoteipproxyprotocol), but it don't work (server errors) because Traefik don't send proxyprotocol headers (it is required for apache if this setting is activated).

Purpose of this new feature is to be able to use TCP for HTTPS loadbalancing which will transmit original IP. It will make faster/direct HTTPS request  and there will be no more need to have (X-... headers).

I hope this proposition of new feature make sense.

Thanks.

**Comment by JavierPandu** [comment]
This would be a great feature

**Comment by hirik** [comment]
+1

**Comment by hirik** [comment]
We also looking for the same feature

**Comment by flozano** [comment]
We are using traefik to handle a non-HTTP(s) protocol and this feature would be really handy. Right now our only option is to not-process proxy protocol in traefik so that the TCP backend server can see the message and process it, but we're missing some context in traefik which may be useful when troubleshooting.

**Comment by connesc** [comment]
This would definitely be a great improvement for non-HTTP proxies.

In addition to the original IP, the [PROXY protocol v2](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) allows to pass TLS client certificate information to a TCP backend server, as the PassTLSClientCert middleware does for HTTP.
This would make Traefik even more useful for TLS termination.

In case it helps, switching from [armon/go-proxyproto](https://pkg.go.dev/github.com/armon/go-proxyproto?tab=doc) to [pires/go-proxyproto](https://pkg.go.dev/github.com/pires/go-proxyproto?tab=doc) would add support for PROXY protocol v2 and allows to craft and write a custom [Header](https://pkg.go.dev/github.com/pires/go-proxyproto?tab=doc#Header) to an outgoing connection.

**Comment by chris13524** [comment]
I'm using 2 layers of Traefik in our k8s setup. Layer 1 I would call "IP terminating" and is the entry point to our whole infra. Layer 2 is a typical Traefik SSL-terminating ingress server. Layer 1 doesn't unwrap anything and just TCP/TLS load balances across the layer 2 Traefik instances in our k8s cluster.

The use-case here is that layer 1 Traefik would have to *send* proxy protocol info to layer 2 Traefik.

**Comment by mschneider82** [comment]
i have added support for proxyprotocolv1 in my PR, It works for me with this test config:

```
## STATIC CONFIGURATION
log:
  level: INFO

api:
  insecure: true
  dashboard: true

entryPoints:
  tcp:
    address: ":9999"
  web:
    address: ":8011"

providers:
  file:
    filename: "traefik.yml"

## DYNAMIC CONFIGURATION
tcp:
  routers:
    tcpfwd:
      rule: "HostSNI(`*`)"
      service: mysrv
      entryPoints:
      - "tcp"
  services:
    mysrv:
      loadBalancer:
        servers:
        - address: "127.0.0.1:2319"
          proxyProtocolV1: true
```
