### ISSUE TITLE
Traefik responds with 503 when backend server health is fine

### ISSUE THREAD

**Issue by hbellur** [traefik/traefik#5379]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

My setup : 
- 1 Traefik and 2 backend servers 
- both backend servers are running a service written in GO (application is compiled with GO 1.12.9)
- there is a steady stream of traffic hitting traefik from both HTTP/1.1 and HTTP/2 clients

### What did you expect to see?

Considering that the backend servers are healthy, I should never have seen this issue

### What did you see instead?

After a few days of uptime, I am observing traefik sending 503 in spite of the fact that the backend servers are up and running with health check returning 200 OK

As a basic validation step, I connected to the same backend servers from **another** Traefik instance to confirm the health of backend servers

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

** platform Traefik is running on **
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

** static config **
```toml
logLevel = "INFO"
defaultEntryPoints = ["https"]
[entryPoints]
        [entryPoints.http]
                address = ":80"
                compress = true
                [entryPoints.http.redirect]
                        entryPoint = "https"
        [entryPoints.https]
                address = ":443"
                compress = true
                minVersion = "VersionTLS12"
                cipherSuites = [
                        "TLS_RSA_WITH_RC4_128_SHA",
                        "TLS_RSA_WITH_AES_128_CBC_SHA",
                        "TLS_RSA_WITH_AES_256_CBC_SHA",
                        "TLS_RSA_WITH_AES_128_CBC_SHA256",
                        "TLS_RSA_WITH_AES_128_GCM_SHA256",
                        "TLS_RSA_WITH_AES_256_GCM_SHA384",
                        "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA",
                        "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
                        "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
                        "TLS_ECDHE_RSA_WITH_RC4_128_SHA",
                        "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA",
                        "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
                        "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
                        "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
                        "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
                        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
                        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
                        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
                        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
                        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
                        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
                ]
                [entryPoints.https.tls]
                        [[entryPoints.https.tls.certificates]]
                        certFile = "<certfile>"
                        keyFile = "<keyfile>"
        [entryPoints.foo]
                address = ":8080"
                [entryPoints.foo.auth]
                        [entryPoints.foo.auth.basic]
                                users = [
                                        "admin:$apr1$q3ADBZcc$bC6SDE79PPGYxivyJ.we1."
                                ]
[traefikLog]
        filePath = "/opt/traefik/log/traefik.log"
        format = "json"
[accesslog]
        filePath = "/opt/traefik/log/access.log"
        format = "json"
	bufferingSize = 1000
        [accessLog.fields]
		defaultMode = "drop"
        	[accessLog.fields.names]
			"BackendAddr" = "keep"
			"ClientAddr" = "keep"
			"DownstreamStatus" = "keep"
			"OriginDuration" = "keep"
			"OriginStatus" = "keep"
			"Overhead" = "keep"
			"RequestAddr" = "keep"
			"RequestMethod" = "keep"
			"RequestPath" = "keep"
			"RequestProtocol" = "keep"
			"RetryAttempts" = "keep"
			"StartUTC" = "keep"
        	[accessLog.fields.headers]
			defaultMode = "drop"
                	[accessLog.fields.headers.names]
                        	"Trace-Id" = "keep"
[api]
        entrypoint="foo"
[file]
        filename="/opt/traefik/runtime.toml"
        watch = true
```

** runtime config **
```toml
[backends]
	[backends.backend]
		[backends.backend.LoadBalancer]
			method = "wrr"
		[backends.backend.healthcheck]
			path = "/health"
			interval = "10s"
		[backends.backend.servers.server1]
			url = "https://<SRVR-1 FQDN>"
			weight = 1
		[backends.backend.servers.server2]
			url = "https://<SRVR-2 FQDN>"
			weight = 1

[frontends]
	[frontends.frontend1]
	backend = "backend"
	entrypoints = ["https"]
		[frontends.frontend1.routes.test_1]
		rule = "Path:/health,/provision/bulk,/identity"
	[frontends.frontend2]
	backend = "backend"
	entrypoints = ["https"]
		[frontends.frontend2.routes.test_1]
		rule = "PathPrefix:/v1/,/v1.1/,/v1.2/"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
