### ISSUE TITLE
Please support apiextensions.k8s.io/v1 api version for CRDs

### ISSUE THREAD

**Issue by andrewsav-bt** [traefik/traefik#5473]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Kubernetes 1.16 is now out and with it [CRDs graduated to GA](https://blog.openshift.com/a-look-into-the-technical-details-of-kubernetes-1-16/). The new api version which is now `apiextensions.k8s.io/v1` as opposed to the older one `apiextensions.k8s.io/v1beta1` is designed to support multiple versions of CRDs and added migration support between CRD versions. To this end it **requires** CRD openAPIV3Schema schema to be defined in the CRD, which was not a requirement for `v1beta1`.

All the examples of CRD given in traefik documentation are written for `v1beta1` and as such do not include the schema.

This makes it impossible to use them with `apiextensions.k8s.io/v1`. Since `apiextensions.k8s.io/v1beta1` is going to be removed in 1.19 it is extremely desirable, that `apiextensions.k8s.io/v1` is supported.

This is a request to make that happen.

**Comment by msnelling** [comment]
This issue prevents the use of IngressRoute CRDs on Kubernetes 1.16 as there are no examples for the CRD definitions with the `openAPIV3Schema` attribute.

**Comment by AndrewSav** [comment]
@msnelling That's not true. I'm using them on 1.16 and they work. Examples (without openAPIV3Schema) are in the docs and they still work in 1.16

**Comment by msnelling** [comment]
@AndrewSav Really? I have just tried this on a fresh MicroK8s snap install on Ubuntu 18.04 with the following CRD.
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ingressroutes.traefik.containo.us

spec:
  group: traefik.containo.us
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    kind: IngressRoute
    plural: ingressroutes
    singular: ingressroute
  scope: Namespaced
```
I get the following error...
```
The CustomResourceDefinition "ingressroutes.traefik.containo.us" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
```
