### ISSUE TITLE
[ECS Provider] Fargate tasks fail to launch without providing region

### ISSUE THREAD

**Issue by cmckni3** [traefik/traefik#5642]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I created a Docker image with my ECS provider configuration for traefik. I configured an ECS service and task definition for traefik specifying the Docker image I created. The ECS task role is configured with the policy document from the configuration docs. See https://docs.traefik.io/v1.7/configuration/backends/ecs/#policy

Tasks fail to launch because they are attempting to pull EC2 metadata ([relevant source code](https://github.com/containous/traefik/blob/v1.7/provider/ecs/ecs.go#L86)) which is not available in Fargate mode.

### What did you expect to see?

I expected traefik to start up and discover services.

### What did you see instead?

I see a connect dial tcp error that `http://169.254.169.254/latest/dynamic/instance-identity/document` cannot be reached.

Setting the region skips that code and traefik starts serving requests.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik version v1.7.18 built on 2019-09-26_01:56:30PM
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# ECS Provider
################################################################

watch = true
logLevel = "DEBUG"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.ping]
  address = ":8082"

[ping]
entryPoint = "ping"

[accessLog]
  format = "json"

  [accessLog.fields.headers]
    defaultMode = "drop"
    [accessLog.fields.headers.names]
      "Accept" = "keep"
      "Accept-Encoding" = "keep"
      "Accept-Language" = "keep"
      "Referer" = "keep"
      "User-Agent" = "keep"
      "Cache-Control" = "keep"
      "Content-Encoding" = "keep"
      "Content-Type" = "keep"
      "X-Trace-Id" = "keep"

[traefikLog]
  format = "json"

[ecs]
  clusters = ["default"]
  autoDiscoverClusters = true
  refreshSeconds = 15
  exposedByDefault = false
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
{"level":"info","msg":"No EC2 region provided, querying instance metadata endpoint...","time":"2019-10-11T17:48:07Z"}
{"level":"error","msg":"Provider connection error EC2MetadataRequestError: failed to get EC2 instance identity document\ncaused by: RequestError: send request failed\ncaused by: Get http://169.254.169.254/latest/dynamic/instance-identity/document: dial tcp 169.254.169.254:80: connect: invalid argument, retrying in 1.282580703s","time":"2019-10-11T17:48:07Z"}
```
