### ISSUE TITLE
Traefik v2 loadBalancer not refreshed when endpoint becomes dead

### ISSUE THREAD

**Issue by Planktonette** [traefik/traefik#5675]
Let's try this again; opening a new issue based on  https://github.com/containous/traefik/issues/5638 which mistakenly attributed the problem to DNS caching and was therefore closed with no further investigation. It would appear that the problem is actually that traefik has no handling for the proxy connection that it creates ending up dead when the remote end dies or is replaced/IP changes/etc.

Sometimes we have to redeploy kubernetes clusters and they come up with the same hostname but different IPs, leaving Traefik sending traffic to the wrong IP as it is maintaining the proxy and not detecting that the backend is dead.

Test is as follows:

Have an endpoint with DNS of long-k8ma-l001.domain.co.uk -> 10.9.10.11
Start Traefik, it creates a proxy to 10.9.10.11, and routing works fine.
Redeploy the VM in question with a new IP of 10.9.10.12
Send traffic to Traefik which continues to try and use the existing proxy long-k8ma-l001.domain.co.uk -> 10.9.10.11 resulting in a connection refused.
Restart Traefik, it starts a proxy to the new DNS mapping and routing now works fine

Dynamic config:

```http:
  routers:
    {{ENV}}-http:
      rule: "HostRegexp(`{subdomain:.+}.{{ENV}}.domain.co.uk`)"
      entrypoints: ["web"]
      service: {{ENV}}-http

  services:
    {{ENV}}-http:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "http://long-k8mi-{{ENV_LETTER}}001.domain.co.uk:30000"
        - url: "http://long-k8mi-{{ENV_LETTER}}002.domain.co.uk:30000"

tcp:
  routers:
    {{ENV}}-kubemaster:
      service: {{ENV}}-kubemaster
      rule: "HostSNI(`kubemaster.{{ENV}}.domain.co.uk`)"
      entryPoints: ["websecure"]
      tls:
        passthrough: true
    {{ENV}}-https:
      service: {{ENV}}-https
      rule: "HostSNI(`*`)"
      entryPoints: ["websecure"]
      tls:
        passthrough: true
    
  services:
    {{ENV}}-https:
      loadBalancer:
        passHostHeader: true
        servers:
        - address: "long-k8mi-{{ENV_LETTER}}001.domain.co.uk:30443"
        - address: "long-k8mi-{{ENV_LETTER}}002.domain.co.uk:30443"
    {{ENV}}-kubemaster:
      loadBalancer:
        passHostHeader: true
        servers:
{% for j in range(1, NUMBER_OF_K8_MASTERS) %}
        - address: "long-k8ma-{{ENV_LETTER}}00{{j}}.domain.co.uk:6443"
{% endfor %}
```

When instantiated, it appears some kind of proxy is created that maps to the loadBalancer.servers.address

This happens in https://github.com/containous/traefik/blob/4e9166759dca1a2e7bdba1780c6a08b655d20522/pkg/server/service/tcp/service.go#L62

The IP for this host is looked up in https://github.com/containous/traefik/blob/56e0580aa5ef5fc40a1969ec78014fef693c8a09/pkg/tcp/proxy.go#L19

Expected behavior: When the remote end dies or is rebuilt, the proxy gets timed out and a new one gets brought up.

Actual behavior: all connections to this load balancer fail for eternity (we left it for an hour and it was still broken) until traefik is restarted and a new connection is instantiated with the correct IP.

It does not appear that there is any support for a timeout or healthcheck for loadbalancer.servers.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0
Codename:     montdor
Go version:   go1.13
Built:        2019-09-16T17:35:17Z
OS/Arch:      linux/amd64
```
### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Our Traefik is run on two Centos7 VMs with round robin loadbalancing between the two, however when isolating one for testing purposes, the issues still occur.
We use PCS for managing the Virtual IPs for the VMs.
```yaml
accessLog: {}
api: {}
entryPoints:
  tcp:
    address: :8000
  web:
    address: :80
  websecure:
    address: :443
global:
  checkNewVersion: true
  sendAnonymousUsage: false
log:
  level: DEBUG
ping: {}
providers:
  file:
    directory: /etc/traefik/config
    watch: true
tracing: {}
```
```yaml
http:
  routers:
    {{ENV}}-http:
      rule: "HostRegexp(`{subdomain:.+}.{{ENV}}.domain.co.uk`)"
      entrypoints: ["web"]
      service: {{ENV}}-http

 

  services:
    {{ENV}}-http:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "http://long-k8mi-{{ENV_LETTER}}001.domain.co.uk:30000"
        - url: "http://long-k8mi-{{ENV_LETTER}}002.domain.co.uk:30000"

 

tcp:
  routers:
    {{ENV}}-kubemaster:
      service: {{ENV}}-kubemaster
      rule: "HostSNI(`kubemaster.{{ENV}}.domain.co.uk`)"
      entryPoints: ["websecure"]
      tls:
        passthrough: true
    {{ENV}}-https:
      service: {{ENV}}-https
      rule: "HostSNI(`*`)"
      entryPoints: ["websecure"]
      tls:
        passthrough: true
    
  services:
    {{ENV}}-https:
      loadBalancer:
        passHostHeader: true
        servers:
        - address: "long-k8mi-{{ENV_LETTER}}001.domain.co.uk:30443"
        - address: "long-k8mi-{{ENV_LETTER}}002.domain.co.uk:30443"
    {{ENV}}-kubemaster:
      loadBalancer:
        passHostHeader: true
        servers:
{% for j in range(1, NUMBER_OF_K8_MASTERS) %}
        - address: "long-k8ma-{{ENV_LETTER}}00{{j}}.domain.co.uk:6443"
{% endfor %}
```
### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
When VM is up and Traefik can resolve OLD_IP, we just get as it's configured to passthrough
``` 
time="2019-10-18T09:45:09Z" level=debug msg="Handling connection from MY_IP:49801"
```
Then we redeploy the VM, and it's IP changes to NEW_IP and we just get this forever.
```
time="2019-10-18T10:02:09Z" level=debug msg="Handling connection from MY_IP:49802"
time="2019-10-18T10:02:09Z" level=error msg="Error while connection to backend: dial tcp OLD_IP:6443: connect: connection refused"
```
However a quick "host" command reveals that the OS can resolve the new IP just fine.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by danperry72** [comment]
### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.0
Codename:     montdor
Go version:   go1.13
Built:        2019-09-16T17:35:17Z
OS/Arch:      linux/amd64
```
### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Our Traefik is run on two Centos7 VMs with round robin loadbalancing between the two, however when isolating one for testing purposes, the issues still occur.
We use PCS for managing the Virtual IPs for the VMs.
```yaml
accessLog: {}
api: {}
entryPoints:
  tcp:
    address: :8000
  web:
    address: :80
  websecure:
    address: :443
global:
  checkNewVersion: true
  sendAnonymousUsage: false
log:
  level: DEBUG
ping: {}
providers:
  file:
    directory: /etc/traefik/config
    watch: true
tracing: {}
```
```yaml
http:
  routers:
    {{ENV}}-http:
      rule: "HostRegexp(`{subdomain:.+}.{{ENV}}.domain.co.uk`)"
      entrypoints: ["web"]
      service: {{ENV}}-http

  services:
    {{ENV}}-http:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "http://long-k8mi-{{ENV_LETTER}}001.domain.co.uk:30000"
        - url: "http://long-k8mi-{{ENV_LETTER}}002.domain.co.uk:30000"

tcp:
  routers:
    {{ENV}}-kubemaster:
      service: {{ENV}}-kubemaster
      rule: "HostSNI(`kubemaster.{{ENV}}.domain.co.uk`)"
      entryPoints: ["websecure"]
      tls:
        passthrough: true
    {{ENV}}-https:
      service: {{ENV}}-https
      rule: "HostSNI(`*`)"
      entryPoints: ["websecure"]
      tls:
        passthrough: true
    
  services:
    {{ENV}}-https:
      loadBalancer:
        passHostHeader: true
        servers:
        - address: "long-k8mi-{{ENV_LETTER}}001.domain.co.uk:30443"
        - address: "long-k8mi-{{ENV_LETTER}}002.domain.co.uk:30443"
    {{ENV}}-kubemaster:
      loadBalancer:
        passHostHeader: true
        servers:
{% for j in range(1, NUMBER_OF_K8_MASTERS) %}
        - address: "long-k8ma-{{ENV_LETTER}}00{{j}}.domain.co.uk:6443"
{% endfor %}
```
### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
When VM is up and Traefik can resolve OLD_IP, we just get as it's configured to passthrough
``` 
time="2019-10-18T09:45:09Z" level=debug msg="Handling connection from MY_IP:49801"
```
Then we redeploy the VM, and it's IP changes to NEW_IP and we just get this forever.
```
time="2019-10-18T10:02:09Z" level=debug msg="Handling connection from MY_IP:49802"
time="2019-10-18T10:02:09Z" level=error msg="Error while connection to backend: dial tcp OLD_IP:6443: connect: connection refused"
```
However a quick "host" command reveals that the OS can resolve the new IP just fine.
