### ISSUE TITLE
using ingressroute, traffic is not distributed over all pods 

### ISSUE THREAD

**Issue by paul-is-a-legend** [traefik/traefik#5685]
We have a kubernetes service that can scale from 100 to 200 pods.  Traffic should of course be sent to all the pods 
### What did you expect to see?
using kong ingress controller, traffic is sent evenly to all pods

### What did you see instead?
out of the 140 pods currently running, here is the last hour of traffic, sorted by traefk endpoint url 
![Screenshot from 2019-10-18 06-12-32](https://user-images.githubusercontent.com/56083663/67086420-af39ad00-f16e-11e9-9c59-29bb1d36dd9b.png)

This happens on all our routes, Here is another endpoint with 25 pods in the service.
![Screenshot from 2019-10-18 06-14-25](https://user-images.githubusercontent.com/56083663/67086512-edcf6780-f16e-11e9-83df-ef40e8a54427.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)
Version:      2.0.2
Codename:     montdor
Go version:   go1.13.1
Built:        2019-10-09T19:26:05Z
OS/Arch:      linux/amd64
### What is your environment & configuration (arguments, toml, provider, platform, ...)?

      - args:
        - --api.insecure
        - --accesslog
        - --entrypoints.web.Address=:80
        - --entrypoints.websecure.Address=:443
        - --accesslog.fields.headers.defaultmode=:keep
        - --entrypoints.web.forwardedheaders.insecure
        - --entrypoints.websecure.forwardedheaders.insecure
        - --providers.kubernetescrd
        - --entryPoints.web.forwardedHeaders.insecure

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  creationTimestamp: "2019-10-08T14:20:39Z"
  generation: 1
  name: ingress-pool-1
  namespace: prod

spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`myweb.com`) && PathPrefix(`/api/1`,`/api/2`,`/api/3`)
    middlewares:
    - name: default-compress
    services:
    - name: prod-pool-main
      port: 3000

```
