### ISSUE TITLE
Traefik 1.7 breaks on 2.0 labels

### ISSUE THREAD

**Issue by BSchwetzel** [traefik/traefik#5756]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Right now I am preparing to migrate from Traefik 1.7 to 2.0. As this implies changing configs and all that I made the following plan:

1. Apply new labels to existing services, as this should be harmless
2. Create new Traefik config
3. Deploy Traefik 2.0
4. Rinse and repeat until it works

Right now I am still in phase 1 and have an interesting problem: As soon as I add the label **traefik.http.services.web.loadbalancer.server.port** Traefik doesn't recognize the frontend rule anymore, leading to an unreachable service. The other labels don't cause this problem.

### What did you expect to see?
I expected Traefik 1.7 to ignore the 2.0 labels and just work as it always did.

### What did you see instead?
Traefik says:

`Filtering container with empty frontend rule guestbook.1 http.services.web.loadbalancer.server `

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.19
Codename:     maroilles
Go version:   go1.12.12
Built:        2019-10-28_02:07:32PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Traefik is deployed as part of a docker stack, my service is just a regular docker service without any stack.

```toml
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      minVersion = "VersionTLS10"
      [[entryPoints.https.tls.certificates]]
      certFile = "run/secrets/entrypoint_cert"
      keyFile = "run/secrets/entrypoint_key"
[docker]
  endpoint = "unix:///var/run/docker.sock"
  swarmMode = true
  exposedByDefault = true
  network = "egov"
[ping]
  entryPoint = "https"
[traefikLog]
[accessLog]
```

docker-compose.yaml (unrelated services left out)
```yaml
traefik:
    image: traefik:1.7.19-alpine
    command: --logLevel="DEBUG"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        delay: 60s
    labels:
      - "logstash.ignore=true"
    environment:
      - TZ=Europe/Berlin
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    configs:
      - source: traefik_toml
        target: /etc/traefik/traefik.toml
    secrets:
      - source: entrypoint_cert
        target: /run/secrets/entrypoint_cert
      - source: entrypoint_key
        target: /run/secrets/entrypoint_key
    networks:
      - egov
```

The service in question has the following labels now:

```
 "Labels": {
                "commit": "1.5.9",
                "deployDate": "1572516247",
                "traefik.docker.lbswarm": "true",
                "traefik.docker.network": "egov",
                "traefik.frontend.headers.STSSeconds": "15768000",
                "traefik.http.routers.web-secured.middlewares": "sts@file",
                "traefik.http.routers.web-secured.rule": "PathPrefix(\"/guestbook\")",
                "traefik.http.routers.web-secured.tls": "",
                "traefik.http.services.web.loadbalancer.server.port": "8081",
                "traefik.web.frontend.rule": "PathPrefix:/guestbook",
                "traefik.web.port": "8080"
            },
```
### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

note: I grepped for my service name (guestbook)
```
time="2019-10-31T11:29:22+01:00" level=debug msg="originLabelsmap[commit:1.5.9 deployDate:1572516247 traefik.docker.lbswarm:true traefik.docker.network:egov traefik.frontend.headers.STSSeconds:15768000 traefik.http.routers.web-secured.middlewares:sts@file traefik.http.routers.web-secured.rule:PathPrefix(\"/guestbook\") traefik.http.routers.web-secured.tls: traefik.http.services.web.loadbalancer.server.port:8081 traefik.web.frontend.rule:PathPrefix:/guestbook traefik.web.port:8080]"
time="2019-10-31T11:29:22+01:00" level=debug msg="allLabelsmap[:map[traefik.docker.lbswarm:true traefik.docker.network:egov traefik.frontend.headers.STSSeconds:15768000 traefik.http.routers.web-secured.middlewares:sts@file traefik.http.routers.web-secured.rule:PathPrefix(\"/guestbook\") traefik.http.routers.web-secured.tls:] http.services.web.loadbalancer.server:map[traefik.port:8081] web:map[traefik.frontend.rule:PathPrefix:/guestbook traefik.port:8080]]"
time="2019-10-31T11:29:22+01:00" level=debug msg="Filtering container with empty frontend rule guestbook.1 http.services.web.loadbalancer.server"
```
