### ISSUE TITLE
Zipkin tracing continues retrying forever

### ISSUE THREAD

**Issue by dsseng** [traefik/traefik#5988]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Add Zipkin tracing to my config and create a circumstance when request to Zipkin fails.

### What did you expect to see?
It retries just like Docker provider does: exponentially increasing timeout and stop after e.g. 10 retries.

### What did you see instead?
![image](https://user-images.githubusercontent.com/19504461/70539969-7964e380-1b75-11ea-8fcf-e691698684a8.png)
It just retries every 1 second until I stop Traefik

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.1.0-rc3
Codename:     cantal
Go version:   go1.13.4
Built:        2019-12-02T18:29:57Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
#
# Configuration sample for Traefik v2.
#
# For Traefik v1: https://github.com/containous/traefik/blob/v1.7/traefik.sample.toml
#
################################################################

################################################################
# Global configuration
################################################################
[global]
  checkNewVersion = true
  sendAnonymousUsage = true

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
  [entryPoints.web]
    address = ":2080"

  [entryPoints.websecure]
    address = ":2443"

################################################################
# Traefik logs configuration
################################################################

# Traefik logs
# Enabled by default and log to stdout
#
# Optional
#
[log]

  # Log level
  #
  # Optional
  # Default: "ERROR"
  #
  level = "DEBUG"

  # Sets the filepath for the traefik log. If not specified, stdout will be used.
  # Intermediate directories are created if necessary.
  #
  # Optional
  # Default: os.Stdout
  #
  # filePath = "log/traefik.log"

  # Format is either "json" or "common".
  #
  # Optional
  # Default: "common"
  #
  # format = "json"

################################################################
# Access logs configuration
################################################################

# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields.
#
# Optional
#
# [accessLog]

  # Sets the file path for the access log. If not specified, stdout will be used.
  # Intermediate directories are created if necessary.
  #
  # Optional
  # Default: os.Stdout
  #
  # filePath = "/path/to/log/log.txt"

  # Format is either "json" or "common".
  #
  # Optional
  # Default: "common"
  #
  # format = "json"

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]

  # Enable the API in insecure mode
  #
  # Optional
  # Default: true
  #
  insecure = true

  # Enabled Dashboard
  #
  # Optional
  # Default: true
  #
  dashboard = true

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[providers.docker]
  exposedByDefault = false

[tracing]
  [tracing.zipkin]

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
