### ISSUE TITLE
Support Docker SwarmMode and Standalone Docker/Docker Compose Simultaneously

### ISSUE THREAD

**Issue by jawabuu** [traefik/traefik#6063]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Start traefik v2.0.4 in a single node docker swarm with
`docker stack deploy`
```yaml
version: '3.5'
networks:
  default:
    name: main
  traefik-net:
    name: traefik-net
    driver: overlay
    attachable: true
services:
  traefik:
    deploy:
      placement:
        constraints: [node.role==manager]
      update_config:
        delay: 60s
        monitor: 30s
        order: stop-first
        failure_action: rollback
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`dash.${HOST}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    image: "traefik:latest"
    env_file:
      - .env
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--log.level=DEBUG"
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`dash.${HOST}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
```
Once running, I would like to deploy another container in the node using;
`docker run..`
or 
`docker-compose up..`
with labels so traefik can route traefik to it.

```yaml
version: "3.5"
networks:
  traefik-net:
    external: true
services:
  whoami:
    image: containous/whoami
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=HostRegexp(`whoami.${HOST}`)"
        - "traefik.docker.network=traefik-net"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=HostRegexp(`whoami.${HOST`)"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
```

### What did you expect to see?
1. Dashboard accessible at http://dash.${HOST`)
2. Whoami accessible at http://whoami.${HOST`)

### What did you see instead?
1. Dashboard accessible at http://dash.${HOST`)
2. Whoami is not accessible at http://whoami.${HOST`)
No route is created

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v2.0.4
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
arguments
```yaml
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--log.level=DEBUG"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by g13013** [comment]
that would be really useful

**Comment by jawabuu** [comment]
> that would be really useful

Especially when deploying containers that require PRIVILEGED mode or other capabilities which docker swarm mode does not support.
VPN/Tunnelling containers are an example.

**Comment by mpl** [comment]
@jawabuu I'm afraid we still don't fully grasp what you're trying to do. In particular, it seems to us that you're trying to run containers both in docker non-swarm mode and in swarm mode on the same host, which we think is not possible (because the docker daemon would not allow it).
Could you please clarify some more a precise use-case, or even better, give us a fully reproducible example?

**Comment by jawabuu** [comment]
Hey @mpl 
It is entirely possible to run standalone containers in a docker swarm node/same host.
However, swarm-mode containers have a limitation when it comes to host capabilities i.e. Running as PRIVILEGED or a capability such as NET_ADMIN

Below is a scenario:
1.  Start traefik in swarm-mode to route traffic  to swarm-mode containers. This works as expected.
2. Start container(s) that require HOST privileges in non swarm-mode. One would still like to use Traefik to route traffic to these containers but this doesn't work.

Ultimately the goal is to have traefik docker provider support any docker container in the host.

You should be able to test with below compose files
https://github.com/containous/traefik/issues/6063#issue-539821452

**Comment by g13013** [comment]
@mpl it is possible to run both, but I am not sure if traefik could access `local` networks when deployed in a `swarm` network and vis-ver-sa

**Comment by jawabuu** [comment]
@g13013 I am attaching the container to an overlay network  that traefik is also connected to and specifying `traefik.docker.network`
The non swarm-mode containers are reachable from the traefik container

**Comment by g13013** [comment]
@jawabuu if it's true, there is no reason to no support both

**Comment by mfisher87** [comment]
Just to add another use case that tripped me up -- passing a device through (`--device` option on `docker run`) to a container is not supported by Docker Swarm, and that doesn't seem to be upcoming like the support for `--cap-add`. I think it may be a long time until all the reasons to mix and match swarm services with standalone containers go away.

I migrated a large number of stacks from compose to swarm and only after doing most of the work did I realize that some stacks which relied on those features would have to stay in compose. :( For now, I'm keeping the mix of standalone and swarm stacks and sidestepping Traefik to hit the standalone services directly at their exposed ports and that works fine. I could use a file provider to manually expose this container behind Traefik, I think.

This sounds like a complex problem for Traefik to solve, from a layman's perspective. Can Traefik running on a swarm manager see standalone containers running on worker nodes, or for that matter _any_ node other than its own? Or would that just magically work as long as the standalone container is attached to the correct network?

**Comment by jawabuu** [comment]
Hey @juliens @g13013 
A workaround for this is to use the file provider as below
Start traefik with file provider enabled providing the file **dynamic-conf.yml** as a config
`docker stack deploy -c traefik.yml traefik`
**traefik.yml**
``` 
version: '3.5'
networks:
  default:
    name: main
  traefik-net:
    name: traefik-net
    driver: overlay
    attachable: true
 configs:
   traefik_conf_v1:
   file: ./dynamic-conf.yml
services:
  traefik:
    deploy:
      placement:
        constraints: [node.role==manager]
      update_config:
        delay: 60s
        monitor: 30s
        order: stop-first
        failure_action: rollback
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`dash.${HOST}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    image: "traefik:latest"
    env_file:
      - .env
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=dynamic-conf.yml"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--log.level=DEBUG"
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`dash.${HOST}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    configs:
      - source: traefik_conf_v1
        target: /dynamic-conf.yml
        mode: 444
```
**dynamic-conf.yml**
```
http:
  # Add the router
  routers:
    router-whoami:
      entryPoints:
      - web
      service: service-whoami
      rule:  "Host(`whoami.${HOST}`)"

  # Add the service
  services:
    service-whoami:
      loadBalancer:
        servers:
        - url: http://whoami:80
        passHostHeader: true
```
Start whoami container with `docker-compose up` making sure to connect to traefik network.
**docker-compose.yml**
``` 
version: "3.5"
networks:
  traefik-net:
    external: true
services:
  whoami:
    image: containous/whoami
    networks:
      - traefik-net
```
Dashboard is  accessible at http://dash.${HOST`)
Whoami is accessible at http://whoami.${HOST`)

A plus for this method is that container IPs  can be resolved using docker DNS.
