### ISSUE TITLE
ForwardAuth Middleware - trustForwardHeader and authResponseHeaders cause 500 response

### ISSUE THREAD

**Issue by gregberns** [traefik/traefik#6124]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I got Traefik configured to route traffic to a Docker container via labels (with docker-compose). Then added the ForwardAuth middleware. 

Simply adding the `forwardauth.address` middleware works fine: The 'address' returns 200 and Traefik forwards the request on.

Then I tried using the `forwardauth.trustForwardHeader` and `forwardauth.authResponseHeaders` middleware.

### What did you expect to see?

I expected the responses to continue to come back as 200's.

### What did you see instead?

Traefik started returning 500 responses. The ForwardAuth 'address' endpoint continued to return 200's, but an error started occurring when any combination of middleware was provided:

* `forwardauth.trustForwardHeader` 
* `forwardauth.authResponseHeaders` 
* `forwardauth.trustForwardHeader` and `forwardauth.authResponseHeaders` 

Traefik log:

```
reverse-proxy_1  | time="2020-01-03T05:37:00Z" level=debug msg="Error calling . Cause: Get : unsupported protocol scheme \"\"" middlewareName=svc1-forwardauth-headers@docker middlewareType=ForwardedAuthType
```

### Output of `traefik version`: 

Docker image

```
traefik:v2.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

* Docker Compose
* Traefik is hooked into the Docker Socket to get labels from the services.

```yml
version: '3.7'

services:
  reverse-proxy:
    image: traefik:v2.1
    command: --api.insecure=true --providers.docker --log.level=DEBUG
    ports:
      - "80:80"
      - "81:8080"
    networks:
      - api
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  svc1:
    image: containous/whoami
    ports: 
      - target: 80
    networks:
      - api
    labels:
      - "traefik.http.routers.svc1.rule=PathPrefix(`/svc1/`)"
      - "traefik.http.middlewares.svc1-stripprefix.stripprefix.prefixes=/svc1"
      - "traefik.http.services.svc1.loadbalancer.server.port=80"
      # Each of these three will fail fail - meaning any combination of middleware fails
      - "traefik.http.routers.svc1.middlewares=svc1-stripprefix, svc1-forwardauth-address, svc1-forwardauth-trust, svc1-forwardauth-headers"
      - "traefik.http.routers.svc1.middlewares=svc1-stripprefix, svc1-forwardauth-address, svc1-forwardauth-headers"
      - "traefik.http.routers.svc1.middlewares=svc1-stripprefix, svc1-forwardauth-address, svc1-forwardauth-trust"
      # But this is fine
      - "traefik.http.routers.svc1.middlewares=svc1-stripprefix, svc1-forwardauth-address"

      # This alone works fine
      - "traefik.http.middlewares.svc1-forwardauth-address.forwardauth.address=http://validator:3000/verify"

      # But when including 'trustForwardHeader' or 'authResponseHeaders' middleware 
      #  a 500 response occurs from within Traefik
      - "traefik.http.middlewares.svc1-forwardauth-trust.forwardauth.trustForwardHeader=false"
      - "traefik.http.middlewares.svc1-forwardauth-headers.forwardauth.authResponseHeaders=X-Forwarded-User"

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

This error results from including the `authResponseHeaders` middleware

```
reverse-proxy_1  | time="2020-01-03T05:37:00Z" level=debug msg="Error calling . Cause: Get : unsupported protocol scheme \"\"" middlewareName=svc1-forwardauth-headers@docker middlewareType=ForwardedAuthType
```

Labels:

```
# - "traefik.http.routers.svc1.middlewares=svc1-stripprefix, svc1-forwardauth-address, svc1-forwardauth-headers"
# - "traefik.http.middlewares.svc1-forwardauth-address.forwardauth.address=http://validator:3000/verify"
# - "traefik.http.middlewares.svc1-forwardauth-headers.forwardauth.authResponseHeaders=X-Forwarded-User"
```

And again the same error occurs when including the `trustForwardHeader` middleware.

```
reverse-proxy_1  | time="2020-01-03T05:39:45Z" level=debug msg="Error calling . Cause: Get : unsupported protocol scheme \"\"" middlewareName=svc1-forwardauth-trust@docker middlewareType=ForwardedAuthType
```

With these labels
```
# - "traefik.http.routers.svc1.middlewares=svc1-stripprefix, svc1-forwardauth-address, svc1-forwardauth-trust"
# - "traefik.http.middlewares.svc1-forwardauth-address.forwardauth.address=http://validator:3000/verify"
# - "traefik.http.middlewares.svc1-forwardauth-trust.forwardauth.trustForwardHeader=false"
```
