### ISSUE TITLE
Using buffer middleware, HTTP status code 500 returned when request time exceed respondingTimeouts

### ISSUE THREAD

**Issue by rooholam** [traefik/traefik#6159]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I set respondingTimeout in traefik static config and I get different status code while the request time exceed the timeout for scenarios bellow:

buffer middleware enabled
without buffer middleware

### What did you expect to see?

I expected to have same HTTP status for those scenarios not 500 status code.

### What did you see instead?

buffer middleware enabled -> 500
without buffer middleware -> 502/504 (it seems for HTTP 1.1 requests 504, for HTTP 2.0 requests 502)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik v2.1.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
log:
  level: INFO
providers:
  docker: {}
entrypoints:
  web:
    address: ":80"
    transport:
      respondingTimeouts:
        readTimeout: "20s"
        writeTimeout: "20s"
        idleTimeout: 30
  web-secur:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: "20s"
        writeTimeout: "20s"
        idleTimeout: 30
accessLog: {}
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
10.0.0.4 - - [12/Jan/2020:08:13:37 +0000] "POST /api/log/v2 HTTP/2.0" 500 21 "-" "-" 9528165 "to-apiservice-location@file" - 20000ms
```
