### ISSUE TITLE
Service metrics do not account for rate limited requests

### ISSUE THREAD

**Issue by sylr** [traefik/traefik#6259]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have a service with a rate limiter middleware.

### What did you expect to see?

I expected the service metrics to have vectors with `code="429"` as requests have been rate limited.

### What did you see instead?

`traefik_service_*` metrics have no vectors for rate limited requests.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
master
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[global]
  checkNewVersion = false
  sendAnonymousUsage = false

#[api]
#  insecure = false
#  dashboard = false
#  debug = false

[metrics.prometheus]
  entryPoint = "web"
  buckets = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.5,2.0]

[log]
  level = "DEBUG"

[accessLog]
  format = "json"

[entryPoints]
  [entryPoints.web]
    address = "127.0.0.1:8081"


[providers.file]
  filename = "/Users/s.rabot/go/src/github.com/containous/traefik/ratelimit.toml"


## dynamic configuration ##

[http.routers]
  [http.routers.router1]
    service = "service1"
    middlewares = [ "ratelimit" ]
    rule = "Path(`/`)"

[http.middlewares]
  [http.middlewares.ratelimit.rateLimit]
    average = 1
    burst = 2

[http.services]
  [http.services.service1]
    [http.services.service1.loadBalancer]
      passHostHeader = true
      [[http.services.service1.loadBalancer.servers]]
        url = "http://127.0.0.1:8000"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
