### ISSUE TITLE
Websockets in jupyterhub issue [Missing header]

### ISSUE THREAD

**Issue by blacksailer** [traefik/traefik#6294]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Websocket in jupyter notebook not working, can't execute code.

My setup:

1. Institutional Nginx Https reverse proxy
2. Traefik proxy
3. Jupyterhub on host with dockerSpawner

### What did you expect to see?

Working jupyter notebook to execute code

### What did you see instead?

499 code for websocket requests.

Headers ```Connection``` and ```Upgrade``` are removed.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik version - 2.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Static:
```toml
[log]
  level = "DEBUG"
[entryPoints]
  [entryPoints.web]
    address = ":80"

[api]
  dashboard = true
  debug = true

[providers.file]
  filename = "/etc/traefik/traefik_dynamic.toml"
  debugLogGeneratedTemplate = true
```
Dynamic:
```toml
[http]
  [http.services]
    [http.services.giis_website.loadBalancer]
      [[http.services.giis_website.loadBalancer.servers]]
        url = "http://backend.example.org:81"

    [http.services.jhub.loadBalancer]
      passHostHeader = true
      [http.services.jhub.loadBalancer.sticky.cookie]
      [[http.services.jhub.loadBalancer.servers]]
        url = "http://backend.example.org:5000"

  [http.routers]
    [http.routers.website]
      entryPoints = ["web"]
      rule = "Host(`backend.example.org`)"
      service="giis_website"

    [http.routers.traefik]
      entryPoints = ["web"]
      rule = "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      service = "api@internal"
      middlewares = ["auth"]

    [http.routers.jhub]
      entryPoints = ["web"]
      rule = "Host(`backend.example.org`) &&  PathPrefix(`/jhub`)"
      service = "jhub"
      middlewares = ["testHeader"]

    [http.routers.jhubws]
      entryPoints = ["web"]
      rule = "HeadersRegexp(`Sec-Websocket-Version`,`(.*)`)  &&  PathPrefix(`/jhub/{user/[^/]+}/{api/kernels/[^/]+/channels|terminals/websocket}/`)"
      service = "jhub"



[http.middlewares]
  [http.middlewares.auth.basicAuth]
    users = [
      "master:___secret___"
    ]
  [http.middlewares.testHeader.headers]
    [http.middlewares.testHeader.headers.customRequestHeaders]
      Referer = "backend.example.org/jhub/hub"

```

**Comment by blacksailer** [comment]
But if add missing headers websocket connection starts to work. 

```
  [http.middlewares.wsUpgradeHeader.headers]
    [http.middlewares.wsUpgradeHeader.headers.customRequestHeaders]
      Upgrade = "websocket"
      Connection = "keep-alive, Upgrade"
```

**Comment by juliens** [comment]
Thx for your interest in the project!

I'm sorry, but I was unable to reproduce your problem.
I tried with

```sh
docker run --label "traefik.http.routers.jupyter.rule=Host(`my.jupyter`)" --label traefik.http.routers.jupyter.entrypoints=http jupyter/scipy-notebook
```
And if I use "my.jupyter" in my browser, everything seems to work.

Can you try with a simpler stack, only Traefik and your jupyter?

**Comment by blacksailer** [comment]
In my current production environment I have two proxies:
nginx (tls termination) -> traefik -> jupyterhub

I've encountered same issue when configured kubernetes (1 master and 1 worker) with traefik as Ingress and kubeflow.
So proxy chain is started to look like this:
nginx (tls termination) -> traefik(host, master node) -> traefik(Ingress, master node) -> kubeflow

Traefik host just proxies everything to ingress. So intially dynamic looks:
```toml
[http]
  [http.services]
    [http.services.k8s.loadBalancer]
      passHostHeader = true
      [[http.services.k8s.loadBalancer.servers]]
        url = "http://xx.xx.xx.xx:31972"

  [http.routers]
    [http.routers.website]
      entryPoints = ["web"]
      rule = "PathPrefix(`/`)"
      service="k8s"

```

But websockets also not working. So, I've changed hosts toml file to:

```toml
[http]
  [http.services]
    [http.services.k8s.loadBalancer]
      passHostHeader = true
      [[http.services.k8s.loadBalancer.servers]]
        url = "http://xx.xx.xx.xx:31972"

  [http.routers]
    [http.routers.website]
      entryPoints = ["web"]
      rule = "PathPrefix(`/`)"
      service="k8s"

    [http.routers.ws]
      entryPoints = ["web"]
      rule = "HeadersRegexp(`Sec-Websocket-Version`,`(.*)`) && PathPrefix(`/`)"
      service = "k8s"
      middlewares = ["wsUpgradeHeader"]


  [http.middlewares]
    [http.middlewares.wsUpgradeHeader.headers]
      [http.middlewares.wsUpgradeHeader.headers.customRequestHeaders]
        Upgrade = "websocket"
        Connection = "keep-alive, Upgrade"
```

And jupyter starts work fine. I am assuming it's mine configuration setup is wrong, because I've didn't configured  headers traefik ingress.

P.S. sorry for such delay, I was migrating everything to k8s
