### ISSUE TITLE
How to get router and service  traffic in traefik 

### ISSUE THREAD

**Issue by zhengqisong** [traefik/traefik#6495]
### Do you want to request a *feature* or report a *bug*?
Count the traffic for each service.  in prometheus metrics?

Feature

### What did you expect to see?
I expect to count traffic for each service.

|router | service | request_num| request_bytes| response_bytes|

**Comment by rtribotte** [comment]
Hi @zhengqisong,

Actually, the metrics counts the traffic for each service:
`traefik_service_requests_total{code="200",method="GET",protocol="http",service="foo@bar"} 1

But, if we add the router label in `traefik_service_requests_total` metric, this would lead to split the metric into x more occurrences, as two routers can point to the same service.

Another way to proceed, would be to create a metric for routers.

What do you think ?

I would like to better understand your use case and your proposal. Could you provide something more specific ?

**Comment by zhengqisong** [comment]
Hi @rtribotte, thank you for your reply.

The metrics counts the traffic for each service, only get the number of requests for a service, but I want to get the network traffic for each service, such as the number of bytes of upstream traffic each service and the number of bytes of downstream traffic.

Only when i know the number of bytes of upstream and downstream traffic each service can i use the speed limiting middleware.

**Comment by jorge07** [comment]
I'm working in adding this and I would like to know if it's something you can consider
```golang

// NewRouterMiddleware creates a new metrics middleware for an Entrypoint.
func NewRouterMiddleware(ctx context.Context, next http.Handler, registry metrics.Registry, routerName string, serviceName string) http.Handler {
	log.FromContext(middlewares.GetLoggerCtx(ctx, nameEntrypoint, typeName)).Debug("Creating middleware")

	return &metricsMiddleware{
		next:                 next,
		reqsCounter:          registry.EntryPointReqsCounter(),
		reqsTLSCounter:       registry.EntryPointReqsTLSCounter(),
		reqDurationHistogram: registry.EntryPointReqDurationHistogram(),
		openConnsGauge:       registry.EntryPointOpenConnsGauge(),
		baseLabels:           []string{"router", routerName, "service", serviceName},
	}
}


// Registry has to implemented by any system that wants to monitor and expose metrics.
type Registry interface {
	// IsEpEnabled shows whether metrics instrumentation is enabled on entry points.
	IsEpEnabled() bool
	// IsRouterEnabled shows whether metrics instrumentation is enabled on routers.
	IsRouterEnabled() bool
	// IsSvcEnabled shows whether metrics instrumentation is enabled on services.
	IsSvcEnabled() bool

	// server metrics
	ConfigReloadsCounter() metrics.Counter
	ConfigReloadsFailureCounter() metrics.Counter
	LastConfigReloadSuccessGauge() metrics.Gauge
	LastConfigReloadFailureGauge() metrics.Gauge

	// entry point metrics
	EntryPointReqsCounter() metrics.Counter
	EntryPointReqsTLSCounter() metrics.Counter
	EntryPointReqDurationHistogram() ScalableHistogram
	EntryPointOpenConnsGauge() metrics.Gauge

+	// router metrics
+	RouterReqsCounter() metrics.Counter
+	RouterReqsTLSCounter() metrics.Counter
+	RouterReqDurationHistogram() ScalableHistogram
+	RouterOpenConnsGauge() metrics.Gauge

	// service metrics
	ServiceReqsCounter() metrics.Counter
	ServiceReqsTLSCounter() metrics.Counter
	ServiceReqDurationHistogram() ScalableHistogram
	ServiceOpenConnsGauge() metrics.Gauge
	ServiceRetriesCounter() metrics.Counter
	ServiceServerUpGauge() metrics.Gauge
}
```

This will generate new router metrics to be able to relate a rule with a service (feature flag for sure).

### Why

This information is very valuable, and certainly possible in traefik 1, for cases where N domains for example point to the same service. You can be suffering an anomaly in one site but with the current v2 service metrics implementation it's impossible to know the origin just looking at your metrics unlike it was on `backend` metrics in v1.
To give you full context:
I generate this metrics from v1 backend metrics to identify anomalies for every single site we have. All of this domains points to the same traefik LB and tons of them to the same backend service. As in v1 backend relates to rule I can know the origin and generate cool things like 1w traffic prediction to detect anomalies like in this example.
 
```yaml
       - record: traffic:total:sum_rate_5m
         expr: sum by (backend) (rate(traefik_backend_requests_total{job="traefik-frontend-prometheus"}[5m]))
       - record: traffic:total:avg_over_time_5m
         expr: avg_over_time(traffic:total:sum_rate_5m[5m])
       - record: traffic:total:stddev_over_time_5m
         expr: stddev_over_time(traffic:total:sum_rate_5m[5m])
       - record: traffic:total:avg_over_time_1w
         expr: avg_over_time(traffic:total:sum_rate_5m[1w])
       - record: traffic:total:stddev_over_time_1w
         expr: stddev_over_time(traffic:total:sum_rate_5m[1w])
       - record: traffic:total:zscore_1w
         expr: |-
            (
              traffic:total:sum_rate_5m - traffic:total:avg_over_time_1w
            ) / traffic:total:stddev_over_time_1w
       - record: traffic:total:median_last_3w
         expr: |-
            quantile(0.5,
              label_replace(
                traffic:total:sum_rate_5m offset 1w + traffic:total:avg_over_time_1w - traffic:total:avg_over_time_1w offset 1w,
                "offset", "1w", "", ""
              )
            ) without (offset)
       - record: traffic:total:zscore_prediction_3w
         expr: (traffic:total:sum_rate_5m - traffic:total:median_last_3w) / traffic:total:stddev_over_time_1w
```
In grafana we generate 1 chart like that per `backend` label. (I've a red anomaly dot to test your superman vision)
![Site X](https://user-images.githubusercontent.com/4022187/98140230-79747d00-1ec5-11eb-86c1-12b534a27bbf.png)
