### ISSUE TITLE
Access log's ClientHost field does not respect trustedIPs from configurations

### ISSUE THREAD

**Issue by semekh** [traefik/traefik#6567]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
- Configure Traefik to use specific set of trusted IPs
- Configure it to log all requests to access log file
- Send an HTTP request with `X-Forwarded-For: 1.2.3.4` header from an untrusted IP `5.6.7.8`

### What did you expect to see?
Since the IP sending the `X-Forwarded-For` header is not trusted, I expected to see the real requester IP (i.e. `5.6.7.8`) in the `ClientHost` field.

### What did you see instead?
Instead you'll see the spoofed IP (i.e. `1.2.3.4`) in the `ClientHost` field. Please note that the downstream backend receives the expected headers, and the bug only applies to access logs.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.7.20
Codename:     maroilles
Go version:   go1.12.14
Built:        2019-12-10_05:02:10PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "info"
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.forwardedHeaders]
    trustedIPs = ["192.168.0.0/16", "172.16.0.0/12", "10.0.0.0/8"]
[traefikLog]
  format = "json"
[accessLog]
filePath = "/var/log/traefik/access.json"
  format = "json"
[accessLog.fields]
  defaultMode = "keep"
[accessLog.fields.names]
[accessLog.fields.headers]
  defaultMode = "keep"
[accessLog.fields.headers.names]
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
N/A
