### ISSUE TITLE
Traefik tries to use HTTP/2 with NTLM

### ISSUE THREAD

**Issue by tfenster** [traefik/traefik#6608]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have a service behind Traefik that uses Windows Auth. As stated here https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10/http2-on-iis#when-is-http2-not-supported, Windows Auth is not supported with HTTP/2. Unfortunately it seems to me like Traefik always uses HTTP/2 when the service scheme is https. This leads to the following error in the Traefik debug log:

```
traefik    | time="2020-03-31T16:31:51Z" level=debug msg="'500 Internal Server Error' caused by: stream error: stream ID 3; HTTP_1_1_REQUIRED"
```

If I run the backend service with http instead of https, then Windows Auth succeeds. 

### What did you expect to see?
Windows Authentication goes through, even when the backend service is running https. It would be good to have an option to e.g. force http/1.1 between Traefik and backend when needed

### What did you see instead?
Windows Authentication fails

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:17:27Z
OS/Arch:      windows/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

My docker-compose.yml looks like this when it works. Note that I disable SSL for the backend service and then use scheme http and port 80 on the service loadBalancer
```yml
  bc:
    image: mcr.microsoft.com/businesscentral/onprem:1810-ltsc2019
    container_name: bc
    hostname: traeftest
    environment:
      - accept_eula=y
      - clickonce=y
      - webserverinstance=bc
      - publicdnsname=traeftest.westeurope.cloudapp.azure.com
      - user=VM-Administrator
      - password=...
      - auth=Windows
#      - usessl=y
    labels:
      - traefik.enable=true
      - traefik.http.routers.bc.rule=Host(`traeftest.westeurope.cloudapp.azure.com`) && PathPrefix(`/bc`)
      - traefik.http.routers.bc.entrypoints=websecure
      - traefik.http.routers.bc.tls.certresolver=myresolver
      - traefik.http.routers.bc.service=bc@docker
      - traefik.http.services.bc.loadBalancer.server.scheme=http
      - traefik.http.services.bc.loadBalancer.server.port=80
```

If docker-compose.yml looks like this then it doesn't work. Note that I enable SSL for the backend service and then use scheme https and port 443 on the service loadBalancer
```yml
  bc:
    image: mcr.microsoft.com/businesscentral/onprem:1810-ltsc2019
    container_name: bc
    hostname: traeftest
    environment:
      - accept_eula=y
      - clickonce=y
      - webserverinstance=bc
      - publicdnsname=traeftest.westeurope.cloudapp.azure.com
      - user=VM-Administrator
      - password=...
      - auth=Windows
      - usessl=y
    labels:
      - traefik.enable=true
      - traefik.http.routers.bc.rule=Host(`traeftest.westeurope.cloudapp.azure.com`) && PathPrefix(`/bc`)
      - traefik.http.routers.bc.entrypoints=websecure
      - traefik.http.routers.bc.tls.certresolver=myresolver
      - traefik.http.routers.bc.service=bc@docker
      - traefik.http.services.bc.loadBalancer.server.scheme=https
      - traefik.http.services.bc.loadBalancer.server.port=443
```

The traefik config itself looks like this, unchanged in both cases. I've set insecureSkipVerify to true as the backend service uses self-signed certificates:
```yml
  traefik:
    image: traefik:2.2-windowsservercore-1809
    container_name: traefik
    command:
      - --log.level=DEBUG
      - --api.insecure=true
#      - --certificatesresolvers.myresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.endpoint=npipe:////./pipe/docker_engine
      - --entrypoints.websecure.address=:443
      - --entrypoints.sql.address=:1433
      - --entrypoints.rtc.address=:7046
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=tobias.fenster@cosmoconsult.com
      - --certificatesresolvers.myresolver.acme.storage=c:/le/acme.json
      - --serversTransport.insecureSkipVerify=true
    ports:
      - "8080:8080"
      - "443:443"
      - "1433:1433"
      - "7046:7046"
    volumes:
      - c:\users\tfenster8982\traefik:c:/le
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
see above
