### ISSUE TITLE
Please disable TLS 1.0 and 1.1 by default

### ISSUE THREAD

**Issue by schildbach** [traefik/traefik#6756]
Using TLS 1.0 or 1.1 is considered insecure these days. It should be used only by those who really know what they're doing. For that reason, I suggest disabling TLS 1.0 and 1.1 by default.

I'm on Traefik 2.2.1.

**Comment by heitorPB** [comment]
`tls.options.default.minVersion` should be `"VersionTLS12"` by default, IMHO.

What are the reasons to still use 1.0 and 1.1?

**Comment by dm17** [comment]
For now, how to disable manually using the docker options? This default is planned to be merged?
Thanks.

**Comment by heitorPB** [comment]
@dm17 add this to your dynamic configs:

```
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
```

**Comment by dm17** [comment]
> @dm17 add this to your dynamic configs:
> 
> ```
> tls:
>   options:
>     default:
>       minVersion: VersionTLS12
>       cipherSuites:
>         - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
>         - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
>         - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
>         - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
>         - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
>         - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
> ```

Every container needs that or just the traefik container? I.e. is this correct:
```
 image: "traefik:v2.2.8"
 tls:
   options:
     default:
       minVersion: VersionTLS12
       cipherSuites:
         - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
         - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
         - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
         - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
         - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
         - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
 restart: always
```
