### ISSUE TITLE
Middleware from Docker produces false error messages when used in File Provider routers

### ISSUE THREAD

**Issue by chan-vince** [traefik/traefik#6846]
### Do you want to request a *feature* or report a *bug*?

Bug

_Note: This is not exactly a functionality bug - it's what I think is a few false positive error logs. So it's probably low priority but potentially could cause some confusion._

### What did you do?

I have Authelia running in a Docker container that I use as middleware for SSO for other containers. I also use it as middleware for an HTTP router defined in a toml config file, which I pass to the file provider.

My router definition looks like this:

```toml
[http.routers.proxmox-router]
    entryPoints = ["websecure"]
    rule = "Host(`proxmox.example.com`)"
    service = "proxmox"
    middlewares=["authelia@docker"]
```

Which works fine - upon testing I do get redirected to the authelia login when I go to `proxmox.example.com`.

### What did you expect to see?

Nice clean logs :)

### What did you see instead?

The logs suggest that it does not have knowledge of Authelia.

```
time="2020-05-25T13:01:30Z" level=error msg="middleware \"authelia@docker\" does not exist" entryPointName=websecure routerName=proxmox-router@file
time="2020-05-25T13:01:31Z" level=error msg="middleware \"authelia@docker\" does not exist" entryPointName=websecure routerName=proxmox-router@file
time="2020-05-25T13:01:31Z" level=error msg="middleware \"authelia@docker\" does not exist" routerName=proxmox-router@file entryPointName=websecure
```

From the logs of the startup sequence, it's clear that the File Provider starts before the Docker Provider, which I suspect is why this happening; it's parsing the file, and cannot find `authelia@docker` because the Docker Provider hasn't finished initialising yet.

To be clear, I haven't tracked it down through the source, so this is only my guess.

If this is the case though, it would be good for the File Provider to be able to recognise the `@docker` suffix and treat it differently. I'm not sure on what the best way of handling it is however, without making it somewhat messy with the File Provider having knowledge of the Docker Provider etc.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.2.0
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

- Traefik in a Docker container
- Authelia in a Docker container
- Ubuntu 18.04 Docker host

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
chan-vince@dockerhost:$ docker logs traefik
time="2020-05-25T13:01:30Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.toml"
time="2020-05-25T13:01:30Z" level=info msg="Traefik version 2.2.0 built on 2020-03-25T17:32:57Z"
time="2020-05-25T13:01:30Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/contributing/data-collection/\n"
time="2020-05-25T13:01:30Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2020-05-25T13:01:30Z" level=info msg="Starting provider *file.Provider {\"watch\":true,\"filename\":\"/etc/traefik/rules.toml\"}"
time="2020-05-25T13:01:30Z" level=info msg="Starting provider *traefik.Provider {}"
time="2020-05-25T13:01:30Z" level=info msg="Starting provider *acme.Provider {\"email\":\"email@example.com\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"/etc/traefik/acme/acme.json\",\"keyType\":\"RSA4096\",\"dnsChallenge\":{\"provider\":\"cloudflare\",\"delayBeforeCheck\":60000000000},\"ResolverName\":\"letsencrypt\",\"store\":{},\"ChallengeStore\":{}}"
time="2020-05-25T13:01:30Z" level=info msg="Starting provider *docker.Provider {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"network\":\"default\",\"swarmModeRefreshSeconds\":15000000000}"
time="2020-05-25T13:01:30Z" level=info msg="Testing certificate renew..." providerName=letsencrypt.acme
time="2020-05-25T13:01:30Z" level=error msg="middleware \"authelia@docker\" does not exist" entryPointName=websecure routerName=proxmox-router@file
time="2020-05-25T13:01:31Z" level=error msg="middleware \"authelia@docker\" does not exist" entryPointName=websecure routerName=proxmox-router@file
time="2020-05-25T13:01:31Z" level=error msg="middleware \"authelia@docker\" does not exist" routerName=proxmox-router@file entryPointName=websecure
time="2020-05-25T13:11:30Z" level=warning msg="A new release has been found: 2.2.1. Please consider updating."```

**Comment by jbdoumenjou** [comment]
Hi @chan-vince ,

could you provide the docker-compose where you defined the authelia middleware and the complete logs ?

**Comment by chan-vince** [comment]
> Hi @chan-vince ,
> 
> could you provide the docker-compose where you defined the authelia middleware and the complete logs ?

Hi @jbdoumenjou 

My authelia docker-compose:

```yaml
services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: unless-stopped
    volumes:
      - ${USERDIR}/docker/authelia:/var/lib/authelia
      - ${USERDIR}/authelia/authelia.config.yml:/etc/authelia/configuration.yml:ro
    networks:
      - default
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`login.${DOMAINNAME}`)'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.${DOMAINNAME}/'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, X-Auth-User, X-Secret'
    expose:
      - 9091
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    depends_on:
      - authelia-redis
```

The logs for authelia are very short as its on info - (let me know if you need `debug`):

```
chan-vince@dockerhost:~/mina/authelia$ docker logs authelia
time="2020-05-25T16:52:48+01:00" level=info msg="Logging severity set to info"
time="2020-05-25T16:52:48+01:00" level=info msg="Selected public_html directory is ./public_html"
time="2020-05-25T16:52:48+01:00" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:9091"
```

Thanks! :)

**Comment by jbdoumenjou** [comment]
If you can share your log in "debug" it would be awesome.

**Comment by chan-vince** [comment]
Interestingly `debug` has no extra output. To be honest I hadn't switched it to debug before so I wasn't sure what to expect, but given there's no more output makes me think authelia is okay.

```
chan-vince@dockerhost:~/mina/authelia$ docker logs authelia
time="2020-05-25T17:30:38+01:00" level=info msg="Logging severity set to debug"
time="2020-05-25T17:30:38+01:00" level=debug msg="Notifier SMTP client initializing TLS configuration"
time="2020-05-25T17:30:38+01:00" level=info msg="Selected public_html directory is ./public_html"
time="2020-05-25T17:30:38+01:00" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:9091"
```

For completeness, here's my authelia config, with the sensitive stuff replaced but otherwise it's what I'm running:

```yaml
host: 0.0.0.0
port: 9091
log_level: debug
jwt_secret: a_very_important_secret
default_redirection_url: https://example.com/

authentication_backend:
  disable_reset_password: true

  ldap:
    url: ldap://openldap
    skip_verify: true
    base_dn: dc=example,dc=com
    username_attribute: uid
    additional_users_dn: ou=users
    additional_groups_dn: ou=groups
    users_filter: (&({username_attribute}={input})(objectClass=account))
    groups_filter: (&(member={dn})(objectclass=groupOfNames))
    user: cn=admin,dc=example,dc=com
    password: UPguCN7nm_d2Gprj9ysc

access_control:
  default_policy: deny

  rules:
    - domain: proxmox.example.com
      subject: "group:admin"
      policy: one_factor

session:
  name: authelia_session
  secret: example

  expiration: 24h
  inactivity: 12h
  remember_me_duration: 1M
  domain: example.com

  redis:
    host: authelia-redis
    port: 6379
    password: authelia
    database_index: 0

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  local:
    path: /var/lib/authelia/db.sqlite3

  smtp:
    username: me@example.com
    password: abc123
    sender: admin@example.com
    host: smtp.gmail.com
    port: 587
```
