### ISSUE TITLE
Service health checks appear to close persistent HTTP connections to backend servers.

### ISSUE THREAD

**Issue by clownba0t** [traefik/traefik#6885]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I noticed that Traefik maintains persistent HTTP connections to backend servers for services, which is great. However, I also noticed that when a health check is configured for a service, the persistent connection is killed each time Traefik executes the health check.

I was able to reproduce this using the "basic-example" from the quickstart guide.

1. Download the "basic-example" docker-compose.yml file from the Traefik GitHub repo.
1. Uncomment the DEBUG log level line in the command section.
1. Start the services using `docker-compose`.
1. Start a shell in the traefik container (e.g. `docker run -it <container ID> sh`).
1. In the shell, check the established connections involving port 80 (e.g. `netstat -an | grep ":80 " | grep "ESTABLISHED"`) and confirm that there aren't any.
1. Hit http://whoami.localhost in the browser (once).
1. Back in the shell, check the established connections involving port 80. Confirm that there's a connection from the host to the traefik container, and another from the traefik container to the whoami container.
1. Continue to check until both connections have been closed - this should take 90 - 120 seconds.
1. Close the shell and stop the services using `docker-compose`.
1. Modify the docker-compose file to add a simple health check for the whoami service, e.g.: "traefik.http.services.whoami.loadbalancer.healthcheck.path=/" Best to allow the default interval to be used, which IIRC is 30 seconds.
1. Start the services using `docker-compose`.
1. Start a shell in the traefik container.
1. In the shell, check the established connections involving port 80 and confirm that there aren't any.
1. Monitor the logs, and wait until a health check refresh entry ("Refreshing health check for backend: whoami@docker") appears.
1. Hit http://whoami.localhost in the browser(once).
1. Back in the shell, check the established connections involving port 80. Confirm that there's a connection from the host to the traefik container, and another from the traefik container to the whoami container.
1. Check a few more times over a few seconds to confirm that both connections remain.
1. Wait for the next health check refresh.
1. Check the connections again, and note that there's only one - the one from the host to the traefik container. The connection from the traefik container to the whoami container has been closed.

Of particular note here is that the default health check interval is 30 seconds, which is significantly shorter than the amount of time the persistent connection between the traefik container and the whoami container remained open (~90 seconds) when the health check was not enabled.

I did some research, and it seems that this may be being caused by the fact the code for the health check closes the response body without reading the entire body first. As per the go documentation for the `Do` function for `net.http.Client`:

> If the Body is not both read to EOF and closed, the Client's underlying RoundTripper (typically Transport) may not be able to re-use a persistent TCP connection to the server for a subsequent "keep-alive" request.

I wrote a tiny client server setup to check this, and confirmed that the connection does persist and is reused while the client reads the entire response body before closing it, and that the connection is closed if it simply closed the response body without reading the entire response body first.

### What did you expect to see?

Persistent HTTP connections from Traefik to the backend servers for services remain open after health checks for the service are executed.

### What did you see instead?

Persistent HTTP connections from Traefik to the backend servers for services are closed when health checks for the service are executed.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Using the docker-compose file from the basic-example in the quickstart guides, with minor modifications in line with the steps to reproduce above (uncommenting the log level argument, and later, adding a health check for the whoami service):

```
version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
```

Environment:
* MacOS 10.15.3
* Docker Desktop 2.3.0.3 (45519)
  * Docker version 19.03.8, build afacb8b
  * docker-compose version 1.25.5, build 8a1c60f6

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
