### ISSUE TITLE
X-Forwarded-Method is missing from request

### ISSUE THREAD

**Issue by Shemeikka** [traefik/traefik#6978]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

The header 'X-Forwarded-Method' is missing from request received by backend server. It's missing also when 
using ForwardAuth.

I'm trying to get Traefik with ForwardAuth to work with my authentication server. The server needs all information from the original request including all headers, URI, method, body. While working on this, I noticed that the method is not received by the authentication server.

I reduced my setup to a minimal setup and still the header is missing. Tested this behavior with Chrome, Firefox, HTTPie.

### What did you expect to see?

Expected to see 'X-Forwarded-Method' header in the request. Also should 'X-Forwarded-URI' be present?

### What did you see instead?

Received request by the backend server

```
# http https://api.localhost.local/api/foobar

HTTP/1.1 200 OK
Content-Length: 298
Content-Type: text/plain
Date: Tue, 30 Jun 2020 05:23:57 GMT
Server: openresty/1.11.2.5

GET /api HTTP/1.1
Host: api.localhost.local
User-Agent: HTTPie/0.9.8
Accept: */*
Accept-Encoding: gzip, deflate
X-Forwarded-For: 172.106.0.1
X-Forwarded-Host: api.localhost.local
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: afdadc467921
X-Real-Ip: 172.106.0.1

```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```
Problem exists also when using Docker images v2.0 and v2.1.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

TLS certificates are created using mkcert.

traefik/traefik.yml
```yaml
global:
  checkNewVersion: false
  sendAnonymousUsage: false
accessLog: {}
log:
  level: DEBUG

entryPoints:
  web:
    address: ':80'

  web-secure:
    address: ':443'

api:
  dashboard: true

providers:
  file:
    directory: /etc/traefik/conf
    watch: true

  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
```
traefik/conf/services.yml
```
http:
  routers:
        
    autsi:
      rule: "Host(`api.localhost.local`) && (
        PathPrefix(`/auth`) ||
        PathPrefix(`/authz`)
        )"
      entryPoints:
        - web-secure
      service: autsi@docker
      tls:
        domains:
          - main: "api.localhost.local"
    
    foobar:
      rule: "
        Host(`api.localhost.local`) &&
        (PathPrefix(`/api/foobar`))
        "
      entryPoints:
        - web-secure
      service: portal-backend@docker
    
    portal-backend-https:
      rule: "
        Host(`api.localhost.local`) &&
        (PathPrefix(`/api`))
        "
      entryPoints:
        - web-secure
      middlewares:
        - auth-request
      service: portal-backend@docker
      tls:
        domains:
          - main: "api.localhost.local"

  middlewares:
    auth-request:
      forwardAuth:
        address: "https://api.localhost.local/auth/authz"
        tls:
          insecureSkipVerify: true
```

traefik/conf/tls.yml
```
tls:
  certificates:
    - certFile: /certs/localhost+5.pem
      keyFile: /certs/localhost+5-key.pem
      stores:
        - default
  stores:
    default: {}
      
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      preferServerCipherSuites: true
```

traefik/conf/dashboard.yml
```
http:
  routers:
    api-dashboard:
      rule: "Host(`traefik.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      middlewares:
        - auth
      service: api@internal

  middlewares:
    auth:
      basicAuth:
        users:
          # => user:user
          - "user:$2y$10$ItlennzhImvIU9mOrh/Gq.p7upNwzLUUIB3m899lpFKBB9MfXSlq2"
```

docker-compose.yml
```
version: '3'
services:

  reverse-proxy:
    image: traefik:v2.2
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./traefik:/etc/traefik"
      - "./certs:/certs"

  portal-backend:
    image: brndnmtthws/nginx-echo-headers
    expose:
      - 8080
    networks:
      default:
    labels:
      - traefik.enable=true
      - traefik.http.services.portal-backend.loadbalancer.server.port=8080

  autsi:
    image: brndnmtthws/nginx-echo-headers
    expose:
      - 8080
    networks:
      default:
    labels:
      - traefik.enable=true
      - traefik.http.services.autsi.loadbalancer.server.port=8080

networks:
  default:
    external:
      name: traefik_bugs
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-06-30T05:44:51Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api/foobar\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Connection\":[\"keep-alive\"],\"User-Agent\":[\"HTTPie/0.9.8\"],\"X-Forwarded-Host\":[\"api.localhost.local\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"afdadc467921\"],\"X-Real-Ip\":[\"172.106.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"api.localhost.local\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.106.0.1:39126\",\"RequestURI\":\"/api/foobar\",\"TLS\":null}"
time="2020-06-30T05:44:51Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api/foobar\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Connection\":[\"keep-alive\"],\"User-Agent\":[\"HTTPie/0.9.8\"],\"X-Forwarded-Host\":[\"api.localhost.local\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"afdadc467921\"],\"X-Real-Ip\":[\"172.106.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"api.localhost.local\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.106.0.1:39126\",\"RequestURI\":\"/api/foobar\",\"TLS\":null}" ForwardURL="http://172.106.0.3:8080"
time="2020-06-30T05:44:51Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api/foobar\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Connection\":[\"keep-alive\"],\"User-Agent\":[\"HTTPie/0.9.8\"],\"X-Forwarded-Host\":[\"api.localhost.local\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"afdadc467921\"],\"X-Real-Ip\":[\"172.106.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"api.localhost.local\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.106.0.1:39126\",\"RequestURI\":\"/api/foobar\",\"TLS\":null}"
```
