### ISSUE TITLE
ACME DNS challange (LEGO) with INWX causes issus (command after logout)

### ISSUE THREAD

**Issue by dragetd** [traefik/traefik#6989]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

This is my ACME configuration:

```yml
certificatesResolvers:
  letsencrypt:
    acme:
      email: "admin@xxx"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      storage: "/data/acme.json"
      keyType: "EC384"
      dnsChallenge:
        provider: inwx
        delayBeforeCheck: 30
        # inwx ns1 (+ipv6), ns2 (+ipv6), quad9 (+ipv6)
        resolvers: ["192.174.68.104", "2001:67c:1bc::104", "176.97.158.104", "2001:67c:10b8::104", "9.9.9.9", "2620:fe::fe"]
  letsencrypt-staging:
    acme:
      email: "admin@xxx"
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      storage: "/data/acme-staging.json"
      keyType: "EC384"
      dnsChallenge:
        provider: inwx
        delayBeforeCheck: 30
        # inwx ns1 (+ipv6), ns2 (+ipv6), quad9 (+ipv6)
        resolvers: ["192.174.68.104", "2001:67c:1bc::104", "176.97.158.104", "2001:67c:10b8::104", "9.9.9.9", "2620:fe::fe"]

```

And this is the docker-compose config for the traefik container:

```yml
version: '3'

services:
  traefik:
    image: traefik:v2.2
    restart: always
    labels:
      # API dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`xxx.de`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:xxx"
      # HTTP to HTTPS redirect
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    environment:
      - INWX_USERNAME={{ INWX_USERNAME | mandatory }}
      - INWX_PASSWORD={{ INWX_PASSWORD | mandatory }}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /srv/traefik/:/data/
    networks:
      - traefik

networks:
  traefik:
    external: true
```

And this is the docker-compose config for the main website container:
```yml
version: '3'

services:
  nginx:
    image: 'nginx:1.17'
    restart: always
    hostname: 'xxx.de'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`www.xxx.de`) || Host(`xxx.de`)"
      - "traefik.http.middlewares.nginx.redirectregex.regex=^https://xxx.de/(.*)"
      - "traefik.http.middlewares.nginx.redirectregex.replacement=https://www.xxx.de/$${1}"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=letsencrypt"
    volumes:
      - '/srv/nginx:/usr/share/nginx/html:ro'
    networks:
      - traefik

networks:
  traefik:
    external: true
```

### What did you expect to see?

Apart from the main website, there are a few other services with other subdomains running that require a TLS certificate. For example one called maubot. After running these containers, I do end up infact with a valid and working TLS certificate. But not without me noticing the log filling up with some errors.

### What did you see instead?

The log shows repeated inwx: 2002 errors.
```
time="2020-07-02T11:26:54Z" level=error msg="Unable to obtain ACME certificate for domains \"maubot.xxx.de\": unable to generate a certificate for the domains [maubot.xxx.de]: error: one or more domains had a problem:
[maubot.xxx.de] [maubot.xxx.de] acme: error presenting token: inwx: (2002) Command use error
" providerName=letsencrypt.acme rule="Host(`maubot.xxx.de`)" routerName=maubot@docker

time="2020-07-02T11:26:54Z" level=error msg="Unable to obtain ACME certificate for domains \"xxx.de\": unable to generate a certificate for the domains [xxx.de]: error: one or more domains had a problem:
[xxx.de] [xxx.de] acme: error presenting token: inwx: (2002) Command use error
" providerName=letsencrypt.acme rule="Host(`xxx.de`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))" routerName=api@docker

time="2020-07-02T11:27:35Z" level=error msg="Unable to obtain ACME certificate for domains \"www.xxx.de,xxx.de\": unable to generate a certificate for the domains [www.xxx.de xxx.de]: error: one or more domains had a problem:
[xxx.de] [xxx.de] acme: error presenting token: inwx: (2002) Command use error
" providerName=letsencrypt.acme routerName=nginx@docker rule="Host(`www.xxx.de`) || Host(`xxx.de`)"
```

The INWX API documentation does not really help here (https://www.inwx.de/de/help/apidoc/f/ch04.html), but I contacted the INWX support and they said they notice these errors in their logs whenever my client tries to send a command while it is not logged in!

So my theory is, that traefik maybe tries to resolve those certificates in parallel and some instances log in and work correctly and log out again, while others still try to send commands and fail, needing to retry.

Or it is a bug in LEGO and it tries to send commands after the logout.

If there is anything I can help with debugging, please let me know. For members of the traefik project I would be even willing to setup a temporary INWX account if this helps debugging. I do not know if it is related to https://github.com/containous/traefik/issues/6141 . If you point me to what I need to change in my config, I can test wildcard certificate.

### Output of `traefik version`: (_What version of Traefik are you using?_)

(From the logs)

```
("Traefik version 2.2.1 built on 2020-04-29T18:02:09Z"
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

See above
