### ISSUE TITLE
Error when requesting an url with double slashes, right after hostname

### ISSUE THREAD

**Issue by bhughes4128** [traefik/traefik#7032]
### Do you want to request a *feature* or report a *bug*? Report a bug

Bug

### What did you do?
This appears to be a repeat of #1323 (https://github.com/containous/traefik/issues/1323) (which was fixed) but it appears to have come back in 2.2.

I am using traefik as an ingress controller for Kubernetes.  I created an Ingress route:
```yml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: test-ingress
  namespace: test
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`testname`) && PathPrefix(`/api`)
    kind: Rule
    services:
    - name: test-svc
      scheme: https
      port: 8443
  tls:
   store:
     name: default
```
When i try to access the backend it works fine if there is no double slash after the hostname but if there is a double slash I get a 404 error.  I tried to add a middleware to route //api to /api but it wasn't working for me.

https://tesname/api/version (works fine)
https://testname//api/version (404)
https://testname/api//version (works fine)

### What did you expect to see?
I expect the URLs to act the same but I get a 404 on the one with a double slash after hostname:
https://testname/api/version (Works fine)
https://testname//api/version (404)
https://testname/api//version (works fine>

### What did you see instead?
I got a 404 error on https://localhost//api/version

### Output of `traefik version`: (_What version of Traefik are you using?_)
2.2

```
It is being run via the traefil kuberentes yaml file.

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
10.138.192.84 - - [12/Jul/2020:14:16:29 +0000] "GET //api/version HTTP/2.0" 404 19 "-" "-" 2 "-" "-" 0ms

This is a working log entry:
time="2020-07-12T14:16:36Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api//version\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-US,en;q=0.9\"],\"Authorization\":[\"Basic dGFjdGljYWw6dGFjdGljYWw=\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36\"],\"X-Forwarded-Host\":[\"testhost\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"traefik-5fbf4899b6-zmspw\"],\"X-Real-Ip\":[\"10.138.192.84\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"testhost\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.1.1.1:20396\",\"RequestURI\":\"/api//version\",\"TLS\":null}"

```
