### ISSUE TITLE
Healthcheck repeated, one per router instead of service

### ISSUE THREAD

**Issue by wiliam-paradox** [traefik/traefik#7043]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Created 10 routers with 1 service, the service only has 1 server. (I have simplified the configuration, we have 130 routers to 2 services, each router is a project pointing to a cluster, develop or production)

The routers have individual files each one, where N a number from 1 to 10.

`/etc/traefik/projectN_develop_intern.yaml`

```
http:
  routers:
    projectN_develop_intern:
      service: cluster_develop-cluster
      entryPoints:
        - https
      rule: PathPrefix(`/project-N/`) && Host(`develop.my-domain.com`)
      middlewares: []
      priority: 1
```

The service has 1 health:

`/etc/traefik/conf.d/cluster_develop-cluster.yaml`
```
http:
  services:
    cluster_develop-cluster:
      loadBalancer:
        healthCheck:
          path: /health
          timeout: 3s
          interval: 5s
        servers:
          - url: 'http://127.0.0.1:81/'
        passHostHeader: true
```

### What did you expect to see?

Only 1 health per server of each service.

### What did you see instead?

1 health for each router:

![log](https://i.imgur.com/qm7xPTB.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
[root@centos ~]# traefik version
Version:      2.2.2
Codename:     chevrotin
Go version:   go1.14.4
Built:        2020-07-08T15:30:29Z
OS/Arch:      linux/386
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
#
# Configuration sample for Traefik v2.
#
################################################################

################################################################
# Global configuration
################################################################

[global]
  checkNewVersion = false
  sendAnonymousUsage = false

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
#
# Optional
# Default:

[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.https]
    address = ":443"

  [entryPoints.traefik]
    address = ":8082"

################################################################
# Traefik logs configuration
################################################################

# Traefik logs
# Enabled by default and log to stdout
#
# Optional
#
[log]

  # Log level
  #
  # Optional
  # Default: "ERROR"
  #
  level = "DEBUG"

  # Sets the filepath for the traefik log. If not specified, stdout will be used.
  # Intermediate directories are created if necessary.
  #
  # Optional
  # Default: os.Stdout
  #
  filePath = "/var/log/traefik/traefik.log"

  # Format is either "json" or "common".
  #
  # Optional
  # Default: "common"
  #
  # format = "json"

################################################################
# Access logs configuration
################################################################

# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields.
#
# Optional
#
# [accessLog]

  # Sets the file path for the access log. If not specified, stdout will be used.
  # Intermediate directories are created if necessary.
  #
  # Optional
  # Default: os.Stdout
  #
  # filePath = "/path/to/log/log.txt"

  # Format is either "json" or "common".
  #
  # Optional
  # Default: "common"
  #
  # format = "json"

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]

  # Enable the API in insecure mode
  #
  # Optional
  # Default: false
  #
  insecure = true

  # Enabled Dashboard
  #
  # Optional
  # Default: true
  #
  dashboard = true

################################################################
# Ping configuration
################################################################

# Enable ping
[ping]

  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  # entryPoint = "traefik"

################################################################
# File providers
################################################################

[providers]
  [providers.file]
    directory = "/etc/traefik/conf.d"
    watch = true


```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-07-13T18:18:08+02:00" level=info msg="Traefik version 2.2.2 built on 2020-07-08T15:30:29Z"
time="2020-07-13T18:18:08+02:00" level=debug msg="Static configuration loaded {\"global\":{},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"http\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"https\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"traefik\":{\"address\":\":8082\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"file\":{\"directory\":\"/etc/traefik/conf.d\",\"watch\":true}},\"api\":{\"insecure\":true,\"dashboard\":true},\"ping\":{\"entryPoint\":\"traefik\"},\"log\":{\"level\":\"DEBUG\",\"filePath\":\"/var/log/traefik/traefik.log\",\"format\":\"common\"}}"
time="2020-07-13T18:18:08+02:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/contributing/data-collection/\n"
time="2020-07-13T18:18:08+02:00" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2020-07-13T18:18:08+02:00" level=debug msg="Start TCP Server" entryPointName=http
time="2020-07-13T18:18:08+02:00" level=debug msg="Start TCP Server" entryPointName=https
time="2020-07-13T18:18:08+02:00" level=debug msg="Start TCP Server" entryPointName=traefik
time="2020-07-13T18:18:08+02:00" level=info msg="Starting provider *file.Provider {\"directory\":\"/etc/traefik/conf.d\",\"watch\":true}"
time="2020-07-13T18:18:08+02:00" level=info msg="Starting provider *traefik.Provider {}"
time="2020-07-13T18:18:08+02:00" level=debug msg="Configuration received from provider file: {\"http\":{\"routers\.... HIDE FOR SECURITY REASONS
time="2020-07-13T18:18:08+02:00" level=debug msg="Configuration received from provider internal: {\"http\":{\"routers\":{\"api\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/api`)\",\"priority\":2147483646},\"dashboard\":{\"entryPoints\":[\"traefik\"],\"middlewares\":[\"dashboard_redirect@internal\",\"dashboard_stripprefix@internal\"],\"service\":\"dashboard@internal\",\"rule\":\"PathPrefix(`/`)\",\"priority\":2147483645},\"ping\":{\"entryPoints\":[\"traefik\"],\"service\":\"ping@internal\",\"rule\":\"PathPrefix(`/ping`)\",\"priority\":2147483647}},\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{},\"ping\":{}},\"middlewares\":{\"dashboard_redirect\":{\"redirectRegex\":{\"regex\":\"^(http:\\\\/\\\\/(\\\\[[\\\\w:.]+\\\\]|[\\\\w\\\\._-]+)(:\\\\d+)?)\\\\/$\",\"replacement\":\"${1}/dashboard/\",\"permanent\":true}},\"dashboard_stripprefix\":{\"stripPrefix\":{\"prefixes\":[\"/dashboard/\",\"/dashboard\"]}}}},\"tcp\":{},\"tls\":{}}" providerName=internal
time="2020-07-13T18:18:08+02:00" level=debug msg="No store is defined to add the certificate HIDE, it will be added to the default store."
time="2020-07-13T18:18:08+02:00" level=debug msg="Adding certificate for domain(s) *.my-domain.com,my-domain.com"
time="2020-07-13T18:18:08+02:00" level=debug msg="No default certificate, generating one"
time="2020-07-13T18:18:08+02:00" level=debug msg="Creating middleware" middlewareName=pipelining middlewareType=Pipelining entryPointName=https routerName=voice-fixed_develop_extern@file serviceName=cluster_develop-cluster
time="2020-07-13T18:18:08+02:00" level=debug msg="Creating load-balancer" routerName=voice-fixed_develop_extern@file serviceName=cluster_develop-cluster entryPointName=https
time="2020-07-13T18:18:08+02:00" level=debug msg="Creating server 0 http://127.0.0.1:81/" serviceName=cluster_develop-cluster serverName=0 entryPointName=https routerName=voice-fixed_develop_extern@file
time="2020-07-13T18:18:08+02:00" level=debug msg="Added outgoing tracing middleware cluster_develop-cluster" routerName=voice-fixed_develop_extern@file middlewareName=tracing middlewareType=TracingForwarder entryPointName=https
time="2020-07-13T18:18:08+02:00" level=error msg="the service is missing on the router" entryPointName=https routerName=tesa_production_extern@file
time="2020-07-13T18:18:08+02:00" level=error msg="the service is missing on the router" entryPointName=https routerName=ftth_production_intern@file
time="2020-07-13T18:18:08+02:00" level=debug msg="Creating middleware" serviceName=cluster_develop-cluster middlewareName=pipelining middlewareType=Pipelining entryPointName=https routerName=monitoring_develop_extern@file
time="2020-07-13T18:18:08+02:00" level=debug msg="Creating load-balancer" routerName=monitoring_develop_extern@file serviceName=cluster_develop-cluster entryPointName=https
time="2020-07-13T18:18:08+02:00" level=debug msg="Creating server 0 http://127.0.0.1:81/" routerName=monitoring_develop_extern@file serviceName=cluster_develop-cluster serverName=0 entryPointName=https
time="2020-07-13T18:18:08+02:00" level=debug msg="Added outgoing tracing middleware cluster_develop-cluster" routerName=monitoring_develop_extern@file middlewareName=tracing middlewareType=TracingForwarder entryPointName=https
time="2020-07-13T18:18:08+02:00" level=debug msg="Creating middleware" entryPointName=https routerName=jira_develop_intern@file serviceName=cluster_develop-cluster middlewareName=pipelining middlewareType=Pipelining
time="2020-07-13T18:18:08+02:00" level=debug msg="Creating load-balancer" entryPointName=https routerName=jira_develop_intern@file serviceName=cluster_develop-cluster
time="2020-07-13T18:18:08+02:00" level=debug msg="Creating server 0 http://127.0.0.1:81/" entryPointName=https routerName=jira_develop_intern@file serverName=0 serviceName=cluster_develop-cluster
time="2020-07-13T18:18:08+02:00" level=debug msg="Added outgoing tracing middleware cluster_develop-cluster" entryPointName=https routerName=jira_develop_intern@file middlewareName=tracing middlewareType=TracingForwarder
time="2020-07-13T18:18:08+02:00" level=debug msg="Creating middleware" entryPointName=https routerName=callejero_develop_intern@file serviceName=cluster_develop-cluster middlewareName=pipelining middlewareType=Pipelining
time="2020-07-13T18:18:08+02:00" level=debug msg="Creating load-balancer" entryPointName=https routerName=callejero_develop_intern@file serviceName=cluster_develop-cluster
```

### Debug

I have tried to look at source code and found this:

The health setup is called 1 or 2 times, not 1 per router, ok.

```
[root@machine ~]# grep "Setting up health" /var/log/traefik/traefik.log
time="2020-07-13T18:12:13+02:00" level=debug msg="Setting up healthcheck for service cluster_develop-cluster@file with [Hostname:  Headers: map[] Path: /health Port: 0 Interval: 5s Timeout: 3s FollowRedirects: true]" serviceName=cluster_develop-cluster@file
time="2020-07-13T18:12:16+02:00" level=debug msg="Setting up healthcheck for service cluster_develop-cluster@file with [Hostname:  Headers: map[] Path: /health Port: 0 Interval: 5s Timeout: 3s FollowRedirects: true]" serviceName=cluster_develop-cluster@file
```

![](https://i.imgur.com/c3YYboS.png)

The problem is that `backend.LB.Servers()` returns 1 server per router.

![](https://i.imgur.com/0iqAQAP.png)
![](https://i.imgur.com/qdLiEou.png)

Each router has 1 load balancer and Servers() returns all of them? Without checking repeated urls?

**Comment by wiliam-paradox** [comment]
I have tried to join all files in only 1, but it happens too, it creates 1 healthcheck for every router:

The config file `gateway__services__routers__middlewares.yaml`:

```
http:
  services:
    cluster_develop-cluster:
      loadBalancer:
        healthCheck:
          path: /health
          timeout: 3s
          interval: 5s
        servers:
          - url: 'http://api-node3.our-domain.com'
          - url: 'http://api-node4.our-domain.com'
        passHostHeader: true
    app_develop-cluster:
      weighted:
        services:
          - name: cluster_develop-cluster
            weight: 1
    cluster_production-cluster:
      loadBalancer:
        healthCheck:
          path: /health
          timeout: 3s
          interval: 5s
        servers:
          - url: 'http://api-node1.our-domain.com'
          - url: 'http://api-node2.our-domain.com'
          - url: 'http://api-node3.our-domain.com'
          - url: 'http://api-node4.our-domain.com'
        passHostHeader: true
    app_production-cluster:
      weighted:
        services:
          - name: cluster_production-cluster
            weight: 1
  routers:
    project1_develop_extern:
      service: cluster_develop-cluster
      entryPoints:
        - https
      rule: PathPrefix(`/project1/`) && Host(`api-devel-ext.our-domain.com`)
      middlewares: []
      priority: 1
    project1_develop_intern:
      service: cluster_develop-cluster
      entryPoints:
        - https
      rule: PathPrefix(`/project1/`) && Host(`api-devel.our-domain.com`)
      middlewares: []
      priority: 1
    project1_production_extern:
      service: cluster_production-cluster
      entryPoints:
        - https
      rule: PathPrefix(`/project1/`) && Host(`api-ext.our-domain.com`)
      middlewares: []
      priority: 1
    project1_production_intern:
      service: cluster_production-cluster
      entryPoints:
        - https
      rule: PathPrefix(`/project1/`) && Host(`api.our-domain.com`)
      middlewares: []
      priority: 1
    project2_develop_extern:
      service: cluster_develop-cluster
      entryPoints:
        - https
      rule: PathPrefix(`/project2/`) && Host(`api-devel-ext.our-domain.com`)
      middlewares: []
      priority: 1
    project2_develop_intern:
      service: cluster_develop-cluster
      entryPoints:
        - https
      rule: PathPrefix(`/project2/`) && Host(`api-devel.our-domain.com`)
      middlewares: []
      priority: 1
    project2_production_extern:
      service: cluster_production-cluster
      entryPoints:
        - https
      rule: PathPrefix(`/project2/`) && Host(`api-ext.our-domain.com`)
      middlewares: []
      priority: 1
    project2_production_intern:
      service: cluster_production-cluster
      entryPoints:
        - https
      rule: PathPrefix(`/project2/`) && Host(`api.our-domain.com`)
      middlewares: []
      priority: 1

    ...

  middlewares:
    add-prod-host-header:
      headers:
        customRequestHeaders:
          Host: api.our-domain.com
```

The start log:
```
time="2020-07-16T10:03:10+02:00" level=info msg="Traefik version 2.2.2 built on 2020-07-08T15:30:29Z"
time="2020-07-16T10:03:10+02:00" level=debug msg="Static configuration loaded {\"global\":{},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"http\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"gr$
time="2020-07-16T10:03:10+02:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/contributing/data-collection/\n"
time="2020-07-16T10:03:10+02:00" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2020-07-16T10:03:10+02:00" level=debug msg="Start TCP Server" entryPointName=https
time="2020-07-16T10:03:10+02:00" level=debug msg="Start TCP Server" entryPointName=http
time="2020-07-16T10:03:10+02:00" level=debug msg="Start TCP Server" entryPointName=traefik
time="2020-07-16T10:03:10+02:00" level=info msg="Starting provider *file.Provider {\"directory\":\"/etc/traefik/conf.d\",\"watch\":true}"
time="2020-07-16T10:03:10+02:00" level=info msg="Starting provider *traefik.Provider {}"
time="2020-07-16T10:03:10+02:00" level=debug msg="Configuration received from provider file: {\"http\":{\"routers\":{\"project1_develop_extern\":{\"entryPoints\":[\"https\"],\"service\":\"cluster_develop-cluster\",\"rule$
time="2020-07-16T10:03:10+02:00" level=debug msg="Configuration received from provider internal: {\"http\":{\"routers\":{\"api\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/api`)\",\"pr$
time="2020-07-16T10:03:10+02:00" level=debug msg="No store is defined to add the certificate XXXXXXXXXXXXXXXXXXXXXXX, it will be added to the default store."
time="2020-07-16T10:03:10+02:00" level=debug msg="Adding certificate for domain(s) *.our-domain.com,our-domain.com"
time="2020-07-16T10:03:10+02:00" level=debug msg="No default certificate, generating one"
time="2020-07-16T10:03:11+02:00" level=debug msg="Creating middleware" entryPointName=https routerName=project2_develop_extern@file serviceName=cluster_develop-cluster middlewareName=pipelining middlewareType=Pipelining
time="2020-07-16T10:03:11+02:00" level=debug msg="Creating load-balancer" entryPointName=https routerName=project2_develop_extern@file serviceName=cluster_develop-cluster
time="2020-07-16T10:03:11+02:00" level=debug msg="Creating server 0 http://api-node3.our-domain.com" serverName=0 entryPointName=https routerName=project2_develop_extern@file serviceName=cluster_develop-cluster
time="2020-07-16T10:03:11+02:00" level=debug msg="Creating server 1 http://api-node4.our-domain.com" serverName=1 serviceName=cluster_develop-cluster entryPointName=https routerName=project2_develop_extern@file
time="2020-07-16T10:03:11+02:00" level=debug msg="Added outgoing tracing middleware cluster_develop-cluster" middlewareType=TracingForwarder routerName=project2_develop_extern@file entryPointName=https middlewareName=tra$
time="2020-07-16T10:03:11+02:00" level=debug msg="Creating middleware" middlewareType=Pipelining entryPointName=https routerName=project3_develop_intern@file serviceName=cluster_develop-cluster middlewareName=pipelining
time="2020-07-16T10:03:11+02:00" level=debug msg="Creating load-balancer" entryPointName=https routerName=project3_develop_intern@file serviceName=cluster_develop-cluster
time="2020-07-16T10:03:11+02:00" level=debug msg="Creating server 0 http://api-node3.our-domain.com" entryPointName=https routerName=project3_develop_intern@file serviceName=cluster_develop-cluster serverName=0
time="2020-07-16T10:03:11+02:00" level=debug msg="Creating server 1 http://api-node4.our-domain.com" serverName=1 entryPointName=https routerName=project3_develop_intern@file serviceName=cluster_develop-cluster
time="2020-07-16T10:03:11+02:00" level=debug msg="Added outgoing tracing middleware cluster_develop-cluster" middlewareName=tracing entryPointName=https routerName=project3_develop_intern@file middlewareType=TracingForwarder
time="2020-07-16T10:03:11+02:00" level=debug msg="Creating middleware" entryPointName=https routerName=project4_production_extern@file serviceName=cluster_production-cluster middlewareName=pipelining middlewareType=Pipelining
time="2020-07-16T10:03:11+02:00" level=debug msg="Creating load-balancer" routerName=project4_production_extern@file serviceName=cluster_production-cluster entryPointName=https
time="2020-07-16T10:03:11+02:00" level=debug msg="Creating server 0 http://api-node1.our-domain.com" entryPointName=https routerName=project4_production_extern@file serviceName=cluster_production-cluster serverName=0
time="2020-07-16T10:03:11+02:00" level=debug msg="Creating server 1 http://api-node2.our-domain.com" entryPointName=https routerName=project4_production_extern@file serverName=1 serviceName=cluster_production-cluster
time="2020-07-16T10:03:11+02:00" level=debug msg="Creating server 2 http://api-node3.our-domain.com" entryPointName=https routerName=project4_production_extern@file serviceName=cluster_production-cluster serverName=2
time="2020-07-16T10:03:11+02:00" level=debug msg="Creating server 3 http://api-node4.our-domain.com" entryPointName=https routerName=project4_production_extern@file serviceName=cluster_production-cluster serverName=3
time="2020-07-16T10:03:11+02:00" level=debug msg="Added outgoing tracing middleware cluster_production-cluster" middlewareName=tracing middlewareType=TracingForwarder entryPointName=https routerName=project4_production_exter$
time="2020-07-16T10:03:11+02:00" level=debug msg="Creating middleware" serviceName=cluster_develop-cluster middlewareName=pipelining middlewareType=Pipelining routerName=project5_develop_extern@file entryPointName=https
time="2020-07-16T10:03:11+02:00" level=debug msg="Creating load-balancer" routerName=project5_develop_extern@file entryPointName=https serviceName=cluster_develop-cluster
```

So we are receiving lots of health checks every 3 seconds:

```
1.1.1.1 - - [16/Jul/2020:10:08:50 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:50 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:50 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:50 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:50 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:50 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:50 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:50 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
1.1.1.1 - - [16/Jul/2020:10:08:53 +0200] "GET /health HTTP/1.1" 200 16 "-" "Go-http-client/1.1"
```
