### ISSUE TITLE
Origin IP as Router rule matcher

### ISSUE THREAD

**Issue by stevenkaras** [traefik/traefik#7138]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I'd like to be able to route requests based on source IP.
To some extent, this is already done via middlewares such as the IPWhitelist, which when used in combination with the Errors middleware can be used to guide requests somewhat, however this can be somewhat subpar in UX.

Ideally, this would support the following use cases:

1. Requiring basic auth when accessing a path from outside an IP range (I'm aware of two workarounds to support this already, but this makes it more explicit and less surprising for new users)
2. Routing requests from non-residential IPs towards a subset of servers (to avoid a misconfigured bot from denying service to actual human users)
3. Routing request from external IPs through extra logging middleware.

I want to propose two different syntaxes which are not mutually exclusive. The first one is preferable, but would require much more work to get working as it adds yet another top level element to configurations:

#### list-aware syntax

This syntax would be aware of IP lists (ideally the ipwhitelist middleware would be improved to also use this).
This allows there to be a single source of truth reused across similar components:

```yaml
sourceRanges:
  internalIPs:
    - 192.168.0.0/16
    - 172.16.0.0/12
    - 10.0.0.0/8
  anotherExample:
    - 192.0.2.0/24

...

http:
  middlewares:
    internal-restricted:
      ipWhiteList:
        sourceRangeList: anotherExample

  routers:
    internal-only:
      rule: "OriginList(internalIPs) ..."
```

#### CIDR-syntax

This syntax would simplify the current workaround used by providing a syntax that is CIDR based rather than regexp based:

```yaml
http:
  routers:
    internal-only:
      rule: "OriginCIDR(192.168.0.0/16) || OriginCIDR(10.0.0.0/8) ..."
```

**Comment by jspdown** [comment]
@stevenkaras Thanks for your proposal. I can see clear needs for this kind of criteria. The use cases I'm thinking of are:
- Having different middleware chains following the requester. Such as higher rate limits for internal IPs or different authentication methods.
- Forwarding requests to different services.
- Having different router rules for different requesters. e.g. ACL

In some cases we can leverage the `errors` middleware to forward the unauthorized request to a different service. But it works only if you want to split requesters in two groups and send them to different services.

There's one aspect of the source IP based routing which is not covered in your proposal. When behind a proxy you might also want these rules to work with the `X-Forwarded-For` header. The `ipWhitelist` middleware handles this using the `ipStrategy` field which can either be a `RemoteAddrStrategy`, `DepthStrategy` or a `CheckerStrategy` (excluded IPs). Handling this as a router rule sounds challenging.
I can see 3 different options if we want to support the different strategies:
- Different rules for different strategies.
- Define this configuration directly on the router as a source strategy:
  ```
  http:
    routers:
      example:
        rule: "OriginList(exampleIPs) || OriginCIDR(192.168.0.0/16)"
        sourceStrategy:
          excludedIPs:
            - 10.1.0.0/16
  ```
- Rely on the `sourceRanges` list to specify additional configuration:
  ```
  sourceRanges:
    internalIPs:
      ipStrategy:
        depth: 1
      sourceRange:
        - 192.168.0.0/16
        - 172.16.0.0/12
        - 10.0.0.0/8
    anotherExample:
      ipStrategy:
        excludedIPs:
          - 10.1.0.0/16
      sourceRange:
        - 192.0.2.0/24
  ```

The first option doesn't seem to be ideal. It would complicate router rules and would be really long and repetitive for the excluded IPs.

The second option sounds better but having the strategy defined on the router would have an impact on the understanding of the `ipWhitelist` middleware configuration. Changes on the `ipWhitelist` middleware would be required.

The 3rd option is also interesting. While avoiding duplicates this configuration could also be compatible with the `ipWhitelist` middleware. A downside of it is that we can't provide strategy configuration on the `OriginCIDR` rule.
