### ISSUE TITLE
Uploading file fails on Kubernetes multi-node cluster

### ISSUE THREAD

**Issue by GreedHub** [traefik/traefik#7149]
Bug

### What did you do?

I'm running Traefik inside a 3 master node HA Kubernetes cluster, and the file uploads fails randomly, sometimes it works, sometimes it fails. 

I've tryed setting the maximum file size, and rising the max number of retry, in middleware but it keeps failing

The cluster is running behind a F5 load balancer working as a https reverse proxy

### What did you expect to see?

The file uploads correctly

### What did you see instead?
```html
<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 14944147168071255888<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

`image: traefik:v2.0`

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 3
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.0
          args:
            - --api.insecure
            - --api
            - --api.dashboard=true
            - --accesslog
            - --entrypoints.web.Address=:8000
            - --entrypoints.websecure.Address=:4443
            - --providers.kubernetescrd
            - --certificatesResolvers.default.acme.httpChallenge=true
            - --certificatesresolvers.default.acme.tlschallenge=true
            - --certificatesresolvers.default.acme.email=xxx@xxx.com.ar
            - --certificatesresolvers.default.acme.storage=acme4.json
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            - name: admin
              containerPort: 8080
          resources:
            limits:
              cpu: 3
              memory: 8192Mi
            requests:
              cpu: 400m
              memory: 100Mi
```

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: max-limit
spec:
  buffering:
    maxRequestBodyBytes: 200000000
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: limits-middleware
spec:
  chain:
    middlewares:
    - name: prefix-middleware
    - name: limit
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  creationTimestamp: null
  name: prefix-middleware
spec:
  stripPrefix:
    prefixes:
    - /stripit
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: mem-limit
spec:
  buffering:
    memRequestBodyBytes: 2000000000
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: retry-limit
spec:
  buffering:
    retryExpression: "IsNetworkError() && Attempts() < 5"
```
