### ISSUE TITLE
traefik reset a persistence connection to upstream

### ISSUE THREAD

**Issue by ccdeville** [traefik/traefik#7154]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I deploy traefik using  daemonset in k8s 
Client connection traefik use http/1.1 
The client sends post request with keep-alive head and the reponse exceeds 4kb
The connection is busy　no idle situation

### What did you see instead?
The following log appears in traefik 
```
reverseproxy.go:445: httputil: ReverseProxy read error during body copy: read tcp 10.0.0.1:55818->10.0.0.2:80: use of closed network connection
```
 I captured all the traffic with tcpdump
```
9194	2020-08-04 11:28:10.486443	10.0.0.1	10.0.0.2	TCP	66	59958 → 80 [RST, ACK] Seq=28414 Ack=76298 Win=178304 Len=0 TSval=0 TSecr=279582616
```
I found this issue
[GitHub Pages](https://github.com/golang/go/issues/15527)
Is this caused by go? How can I fix it.
### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.8
Codename:     chevrotin
Go version:   go1.14.6
Built:        2020-07-28T15:46:03Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http"]
debug = false
logLevel = "WARN"
InsecureSkipVerify = true
[global]
  checkNewVersion = false
[entryPoints]
  [entryPoints.http]
  address = ":80"
[web]
  address = ":8090"
[api]
  insecure = true
  dashboard = true
  debug = false
[kubernetes]
[providers.kubernetesIngress]
  endpoint = "http://192.168.0.1:80"
[ping]
entryPoint = "http"
[log]
  filePath = "/data/traefik.log"
  level = "WARN"
[accessLog]
  filePath = "/data/access.log"
  [accessLog.filters]
    statusCodes = ["400-499", "500-504"]
    retryAttempts = true
    minDuration = "10ms"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time+"2020-08-04T10:50:27Z" level=debug msg="Request has been aborted [10.0.0.1:55818 - /urlpath/1.aspx]: net/http:abort Handler" middlewareName=traefik-internal-recovery middlewareType=Recovery
```
