### ISSUE TITLE
TlsStore default certificate does not work with sniStrict enabled.

### ISSUE THREAD

**Issue by sainipankaj90k** [traefik/traefik#7224]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

AIM: I wanted to have a default tls cert for traefik read from k8s secret. 

Actions:
1. Added TLSStore as mentioned below.
2. Added traefik deployment with image: traefik:v2.2.
3. Added configMap that doesn't have store, since TLSStore is been defined already.

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: ingress
spec:
  defaultCertificate:
    secretName: tls-cert
```

### What did you expect to see?
Expected to have tls-cert in k8s secret get used.

### What did you see instead?
The request failed as 'This site can’t provide a secure connection'.

**Surprisingly, it works if I disable sniStrict**, the TLSStore cert is used and works as expected.
**Also, it works if one of the ingressRoute has secretName (with sniStrict enabled)**. Given that all other ingressRoutes also entertains same host.
As a work around, I have added a dummy ingressRoute which uses tls-cert from secret. This makes it work for all the ingressRoute in different namespaces too (given that only the dummy ingressRoute has tls secretName mentioned).

dummy ingressRoute

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dummy-ingress
  namespace: ingress
spec:
  entryPoints:
  - websecure
  tls:
    secretName: tls-cert
```

other ingress route
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: service1-ingress
  namespace: service1-ns
spec:
  entryPoints:
  - websecure
  tls: {}
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v2.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: ingress
spec:
  defaultCertificate:
    secretName: tls-cert
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
