### ISSUE TITLE
Default metric endpoint can't be disabled with manualRouting: true

### ISSUE THREAD

**Issue by xoxys** [traefik/traefik#7227]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

What I try to do is to expose the prometheus metrics on a custom endpoint protected by a basic auth middleware. So the result should look like this: https://myhost.example.com/my_metrics.

What I've done so far:
```yml
metrics:
  prometheus:
    buckets: [0.1, 0.3, 1.2, 5.0]
    manualRouting: true
```
At this point, metrics should be enabled in general but I should not be able to access the endpoint on any route, right? I would need to define a dedicated router first because I've set `manualRouting: true`. At least, that was my understanding, but I'm still able to access the metrics at `/metrics`. Why is this possible?

To get https://myhost.example.com/my_metrics working I've added the following labels to my traefik container:

```
--label traefik.enable=true \
  --label traefik.docker.network=traefik \
  --label traefik.http.routers.metrics.rule="Host(`myhost.example.com`) && Path(`/my_metrics`)" \
  --label traefik.http.routers.metrics.service=prometheus@internal \
  --label traefik.http.routers.metrics.entrypoints=https \
  --label traefik.http.routers.metrics.tls=true \
  --label traefik.http.routers.metrics.middlewares=auth@file,https@file,secure@file \
  --label traefik.http.routers.metrics-insecure.rule="Host(`myhost.example.com`) && Path(`/my_metrics`)" \
  --label traefik.http.routers.metrics-insecure.service=prometheus@internal \
  --label traefik.http.routers.metrics-insecure.entrypoints=http \
  --label traefik.http.routers.metrics-insecure.middlewares=auth@file,https@file,secure@file
```
Now https://myhost.example.com/my_metrics works and this endpoint is also basic auth protected. But /metrics is still working even without auth...

### What did you expect to see?

I would expect to be able to configure a custom metrics endpoint and disable the default /metrics endpoint completely.

### Output of `traefik version`:
Version:      2.2.8
Codename:     chevrotin
Go version:   go1.14.6
Built:        2020-07-28T15:46:03Z
OS/Arch:      linux/amd64

**Comment by rtribotte** [comment]
Hello @xoxys,

Thanks for your interest in Traefik !

I cannot reproduce the bug with this docker-compose set up:

```yaml
version: '3.7'

services:
  traefik:
    image: traefik:v2.2.8
    ports:
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --entrypoints.websecure.address=:443
      - --log.level=DEBUG
      - --api
      - --providers.docker.exposedbydefault=false
      - --metrics.prometheus=true
      - --metrics.prometheus.manualrouting=true
    labels:
      traefik.enable: true

      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.tls: true
      traefik.http.routers.traefik.rule: Host(`traefik`)
      traefik.http.routers.traefik.service: api@internal

      traefik.http.routers.metrics.entrypoints: websecure
      traefik.http.routers.metrics.tls: true
      traefik.http.routers.metrics.rule: Host(`traefik`) && Path(`/my_metrics`)
      traefik.http.routers.metrics.service: prometheus@internal
```

Please, can you provide the output of the endpoint `/api/rawdata` ?

**Comment by xoxys** [comment]
Thanks for your feedback. Strange... I'll provide the required information and try to find a minimal reproduce setup.

**Comment by xoxys** [comment]
Sorry for the delay. I was able to reproduce it locally. Somehow this is related to a global errors middleware. The used image for the errors middleware should not matter. We should be able to reproduce it with e.g. and ngixn image like in this example: https://community.containo.us/t/global-404-handler/2144/10

```
version: '3.7'

services:
  traefik:
    image: traefik:v2.2.8
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --log.level=DEBUG
      - --api
      - --providers.docker.exposedbydefault=false
      - --metrics.prometheus=true
      - --metrics.prometheus.manualrouting=true
    labels:
      traefik.enable: true

      traefik.http.routers.traefik.entrypoints: http
      traefik.http.routers.traefik.rule: Host(`traefik`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.middlewares: errors-mw

      traefik.http.routers.metrics.entrypoints: http
      traefik.http.routers.metrics.rule: Host(`traefik`) && Path(`/metrics`)
      traefik.http.routers.metrics.service: prometheus@internal
      traefik.http.routers.metrics.middlewares: errors-mw

  errors:
    image: tboerger/errors
    labels:
      traefik.enable: true

      traefik.http.services.errors.loadbalancer.server.port: 8080
      traefik.http.services.errors.loadbalancer.server.scheme: http
      traefik.http.services.errors.loadbalancer.passhostheader: true

      traefik.http.routers.errors.rule: HostRegexp(`{host:.+}`)
      traefik.http.routers.errors.priority: 1
      traefik.http.routers.errors.service: errors
      traefik.http.routers.errors.entrypoints: http
      traefik.http.routers.errors.middlewares: errors-mw

      traefik.http.middlewares.errors-mw.errors.status: 400-599
      traefik.http.middlewares.errors-mw.errors.service: errors
      traefik.http.middlewares.errors-mw.errors.query: /{status}.html
```

With this compose file I'm now able to server:
http://traefik/metrics (expected)
http://127.0.0.1/metrics (unexpected)
http://localhost/metrics (unexpected)
