### ISSUE TITLE
Multiple entry regex redirects

### ISSUE THREAD

**Issue by truhlikfredy** [traefik/traefik#723]
I would like to do multiple URL redirects on the entrypoint which can't be formulated into one regex. When I do examples they work like this one

```toml
 [entryPoints]
   [entryPoints.http]
   address = ":80"
     [entryPoints.http.redirect]
       regex = "^http://localhost/(.*)"
       replacement = "http://mydomain/$1"

```

The moment if I try to add multiple regex conditions with multiple redirects then it fails in various ways. Tried to add multiple entrypoints with the same address, tried to different names [entryPoints.http.redirect1]  or [entryPoints.http.redirect2] or have duplicate regex conditions inside the [entryPoints.http.redirect] clause. And all the example just do there as URL redirect. And then have the https redirect after all the regexes fail.

I can get every example working isolated, but the moment I want to combine them or have multiple instances of the same functionality but with different parameters then I fail getting anywhere. Any help would be appreciated. If there would be some book or long long documentation explaining everything I would love to read it, but somehow I find the documentation explaining everything else that I need.

At the moment I don't need the docker features and I'm only preparing it for the future, so at the moment I'm doing more HAProxy kind of setup. So I'm not even using the strong sides of traefik yet.

Thank you in Advance

**Comment by f3l1x** [comment]
It seems I need this too. :+1: :-)

Any idea how to accomplish that?

**Comment by alexsandro-xpt** [comment]
Is it much better in frontends as a ruler?

https://github.com/containous/traefik/issues/987

**Comment by kallisti5** [comment]
It seems redirects could go with the same method as routes (and keep backward compatibility)

**Example (today):**
```
traefik/frontends/site.com/routes/default/rule "Host:mc777.site.com"
traefik/frontends/site.com/redirect/regex "//mc777.site.com/$"
traefik/frontends/site.com/redirect/replacement "//mc777.mywebsite.com/java/HomePageGetAction.do"
```


**Example (potential):**
```
traefik/frontends/site.com/routes/default/rule "Host:mc777.site.com"
traefik/frontends/site.com/redirects/default/regex "//mc777.site.com/$"
traefik/frontends/site.com/redirects/default/replacement "//mc777.site.com/java/HomePageGetAction.do"
traefik/frontends/site.com/redirects/protect/regex "//mc777.site.com/java/$"
traefik/frontends/site.com/redirects/protect/replacement "//mc777.site.com/"
```

That's more consistent as well.

**Comment by larskluge** [comment]
I too am in the need of multiple redirects per one frontend. Proposing another syntax (array of redirects): 

```toml
[frontends]
  [frontends.f1]
    backend = "a"
    [frontends.f1.routes.all]
      rule = "Host:a.com,b.com"
    [[frontends.f1.redirect]]
      regex = "^https://a.com/(.*)$"
      replacement = "https://b.com/$1"
    [[frontends.f1.redirect]]
      regex = "^https://b.com/(.*)$"
      replacement = "https://c.com/$1"
```

**Comment by adminko** [comment]
no progress?

**Comment by forrest-lookback** [comment]
Now that `traefik.frontend.redirect.regex` and `traefik.frontend.redirect.replacement` exist I think it makes more sense to talk about support for multiple regex in the frontend configuration as opposed to here at the network level no?

Right now you can still only have a single frontend redirect. @ldez about a year ago you suggested people watch this issue for respecting multiple regex issues. Has there been any progress or updates since then? I searched far and wide and I don't see a way to handle multiple regex frontend redirects within the same service.

**Comment by YarmoM** [comment]
Multiple regex redirects per frontend are an absolute need, it would be nice to have an update on this years-old issue.

In the meantime, would it be possible to define multiple frontends where some frontends already specifically match the paths you wish to redirect and one "catch-all" rule? Not applicable to all scenarios unfortunately, but not even sure if this would work at all

**Comment by geraldcroes** [comment]
Hi! We do have an update ... in the form of v2.0 alpha & middleware (you can chain as many regex-redirect as you want)

**Comment by YarmoM** [comment]
That's great to hear! Unfortunately, I don't have any testing setup, only a production server, so no alphas for me... Anyway good to know it's coming!

**Comment by makcuber** [comment]
> Hi! We do have an update smile ... in the form of v2.0 alpha & middleware (you can chain as many regex-redirect as you want) tada

Is there a guide for how to use middleware to accomplish a redirect as described in this issue? I've been reading through the middleware documentation and its not super clear, though I am very new to using Traefik. If anyone could help a newbie out on this functionality it'd be much appreciated :)

**Comment by MacGyver27** [comment]
> ```toml
> [frontends]
>   [frontends.f1]
>     backend = "a"
>     [frontends.f1.routes.all]
>       rule = "Host:a.com,b.com"
>     [[frontends.f1.redirect]]
>       regex = "^https://a.com/(.*)$"
>       replacement = "https://b.com/$1"
>     [[frontends.f1.redirect]]
>       regex = "^https://b.com/(.*)$"
>       replacement = "https://c.com/$1"
> ```

What I did was:
```
[frontends]
  [frontends.f1]
    backend = "a"
    [frontends.f1.routes.all]
      rule = "Host:a.com,b.com"
    [[frontends.f1.redirect]]
      regex = "^https://(a|b).com/(.*)$"
      replacement = "https://c.com/$1"
```
and it worked.

**Comment by PhilipMay** [comment]
I need this too.

**Comment by mstefanwalker** [comment]
> Hi! We do have an update smile ... in the form of v2.0 alpha & middleware (you can chain as many regex-redirect as you want) tada

@geraldcroes I am also looking for this feature. Is this documented and/or out of alpha?

I have looked at [doc.traefik.io/traefik/middlewares/http/redirectregex/](https://doc.traefik.io/traefik/middlewares/http/redirectregex/) but it only has examples for one redirect.

> ```
>[frontends]
>  [frontends.f1]
>    backend = "a"
>    [frontends.f1.routes.all]
>      rule = "Host:a.com,b.com"
>    [[frontends.f1.redirect]]
>      regex = "^https://(a|b).com/(.*)$"
>      replacement = "https://c.com/$1"
>```

This only works if the replacement for both should be `"https://c.com/$1". In the case where one regex should redirect to one url and another regex should redirect to a different url, we seem to be out of luck.

**Comment by kevinpollet** [comment]
Hello all,

As said by @geraldcroes, in v2 we introduced the `RedirectRegex` middleware (see https://doc.traefik.io/traefik/middlewares/http/redirectregex/) which can be chained in a router configuration as shown below:

```yaml
http:
  routers:
    dashboard:
      rule: Host(`foo.localhost`) || Host(`bar.localhost`)
      service: noop@internal
      middlewares:
        - foo-redirect
        - bar-redirect

  middlewares:
    foo-redirect:
      redirectRegex:
        regex: "^http://foo.localhost/(.*)"
        replacement: "http://a.localhost/${1}"
    bar-redirect:
      redirectRegex:
        regex: "^http://bar.localhost/(.*)"
        replacement: "http://b.localhost/${1}"
```

Here is the output of the `curl` commands:

```yaml
❯ curl -v foo.localhost
*   Trying 127.0.0.1:80...
* Connected to foo.localhost (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: foo.localhost
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Location: http://a.localhost/
< Date: Wed, 02 Nov 2022 14:02:36 GMT
< Content-Length: 5
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host foo.localhost left intact
Found%

❯ curl -v bar.localhost
*   Trying 127.0.0.1:80...
* Connected to bar.localhost (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: bar.localhost
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Location: http://b.localhost/
< Date: Wed, 02 Nov 2022 14:02:42 GMT
< Content-Length: 5
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host bar.localhost left intact
Found%
```

As multiple redirect regexs are now supported we are closing this issue. Feel free to re-open it if you think that we missed something.
