### ISSUE TITLE
Redirect Response Sent from API Endpoint behind Traefik is Targeted to HTTP rather than HTTPS

### ISSUE THREAD

**Issue by Reapor-Yurnero** [traefik/traefik#7279]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm new to Traefik and I've set up an API serivice with FASTAPI+UVICORN in docker behind traefik. Traefik is configured to use Let's Encrypt resolver to automatically deal with the SSL stuff for the hostname of this service so all the clients are talking with this API endpoint in https url e.g. https://foo.bar and the API service itself (a uvicorn server) is running in non-ssl mode. Everything works fine in most normal cases.

However, in certain cases, my API endpoint will send out some redirect responses e.g. 307 temporary redirect when the request path has no trailing slash. Those redirect response is targeting to http://foo.bar which is a different hostname (https->http). The client (e.g. browser) receiving such a redirect response will not carry the Authorization Header because of this. 

### What did you expect to see?

The redirect response sent from the service behind traefik should be in https scheme.

### What did you see instead?

The redirect response sent from the service behind traefik is in http scheme.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.11
Codename:     chevrotin
Go version:   go1.14.8
Built:        2020-09-07T14:12:48Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Docker-compose for traefik:
```yaml
  traefik:
    container_name: brickserver-traefik-deployment
    image: traefik:v2.2
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --certificatesresolvers.leresolver.acme.email=myemail
      - --certificatesresolvers.leresolver.acme.storage=/acme.json
      - --certificatesresolvers.leresolver.acme.httpchallenge=true
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
      - --log=true
      - --log.filepath=/traefik.log
      - --log.level=DEBUG
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./configs/acme.json:/acme.json
        #- ./configs/traefik.toml:/traefik.toml
    labels:
      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
```

Service (fastapi) creation in shell:
```bash
docker create --name brickserver-playground-deployment \
    --rm \
    -it \
    -e LOG_LEVEL="debug" \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v $PWD:/app \
    -e ENABLE_SSL=false \
    --entrypoint /app/docker/start-reload.sh \
    --privileged=true \
    --label "traefik.http.routers.bs-backend.rule=Host(\"myhost\") && ( PathPrefix(\"/docs\") || PathPrefix(\"/dummy-frontend\") || PathPrefix(\"/auth\") || PathPrefix(\"/brickapi\") )" \
    --label traefik.http.routers.bs-backend.entrypoints=websecure \
    --label traefik.http.routers.bs-backend.tls=true \
    --label traefik.http.routers.bs-backend.tls.certresolver=leresolver \
    --label "traefik.docker.network=deployment_default" \
    jbkoh/playground:0.1
docker network connect deployment_default brickserver-playground-deployment
docker network connect isolated_nw brickserver-playground-deployment
docker start -ai brickserver-playground-deployment
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

I've checked the log and it is not super helpful there.
