### ISSUE TITLE
redirectscheme not workaround

### ISSUE THREAD

**Issue by ElonH** [traefik/traefik#7298]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

```yml
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    container_name: "simple-service"
    labels:
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
      - "traefik.enable=true"
      - "traefik.http.routers.app-a-http.rule=Host(`a.example.com`)"
      - "traefik.http.routers.app-a-http.entrypoints=web"
      - "traefik.http.routers.app-a-http.middlewares=https_redirect"
      - "traefik.http.routers.app-a-https.rule=Host(`a.example.com`)"
      - "traefik.http.routers.app-a-https.entrypoints=websecure"
      - "traefik.http.routers.app-a-https.tls=true"
      - "traefik.http.routers.app-a-https.tls.certresolver=mysolver"
      - "traefik.http.routers.app-a-https.service=app-a-https-service"
      - "traefik.http.services.app-a-https-service.loadbalancer.server.port=80"

```

The above configuration is work well.

But when I append below labels, `redirectscheme` not workaround.

```yml

      - "traefik.http.routers.app-b-https.rule=Host(`b.example.com`)"
      - "traefik.http.routers.app-b-https.entrypoints=websecure"
      - "traefik.http.routers.app-b-https.tls=true"
      - "traefik.http.routers.app-b-https.tls.certresolver=mysolver"
      - "traefik.http.routers.app-b-https.service=app-b-https-service"
      - "traefik.http.services.app-b-https-service.loadbalancer.server.port=80"
```

`curl -v http://a.example.com` will be `404`
`curl -v https://a.example.com` is `200`
`curl -v https://b.example.com` is `200`

### What did you expect to see?

`curl -v http://a.example.com` should be `301`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.11
Codename:     chevrotin
Go version:   go1.14.8
Built:        2020-09-07T14:12:48Z
OS/Arch:      linux/amd64

```
