### ISSUE TITLE
http.Pusher interface not implemented by plugin middleware's response writer

### ISSUE THREAD

**Issue by pipe01** [traefik/traefik#7303]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm writing a [middleware plugin](https://github.com/pipe01/plugin-h2push) for HTTP2 pushing, [Checking](https://github.com/pipe01/plugin-h2push/blob/d29f3fab0b384a42e41fb898be4d40276ba8346d/h2push.go#L68) if the response writer supports pushing through the `http.Pusher` interface always returns false, even when the downstream service communicates using HTTP2.

### What did you expect to see?

`p, ok := rw.(http.Pusher); ok == true` in https://github.com/pipe01/plugin-h2push/blob/d29f3fab0b384a42e41fb898be4d40276ba8346d/h2push.go#L68

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.0-rc6
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-16T15:20:51Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Static:
```yaml
entryPoints:
    web:
        address: :80
    websec:
        address: :443

providers:
    file:
        filename: traefik.dyn.yaml

pilot:
    token: "****"

experimental:
    devPlugin:
        goPath: C:\Users\piper\go
        moduleName: github.com/pipe01/plugin-h2push
```

Dynamic:
```yaml
http:
  services:
    webserver:
      loadBalancer:
        servers:
        - url: 'http://localhost:5000'

  routers:
    my-router:
      entrypoints:
        - web
        - websec
      rule: "Host(`localhost`)"
      service: webserver
      tls: true
      middlewares:
        - push

  middlewares:
    push:
      plugin:
        dev:
          files:
          - url: url1
            match: match1
```
