### ISSUE TITLE
traefik v1.7  Error when creating error page

### ISSUE THREAD

**Issue by gezichenshan** [traefik/traefik#7307]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
It is a docker swarm,

A TOML file to define a backend as an error page.

A traefik server as edge router, a dummy server to handle request.

When the swarm services setup,

I visit http://a.fake.jd.com/traefik/dashboard/ can be displayed successfully,

However when I visit http://a.fake.jd.com/a-long-funding-api/401, I didn't see the wanted error page.

### What did you expect to see?

I wanted to see errors from 400 to 499 will trigger https://an-external-url/error-page.html to show.

### What did you see instead?

No custom error page show. When I check the traefik.log I found:

`Error when creating error page \"networks\" for frontend \"frontend-web-dummy-funding-web\": the backend \"backend-error\" doesn't exist.","time":"2020-09-16T11:05:03Z"}`

In fact, I've configured backend error in the TOML file. But why it shows `doesn't exist`?

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.16
Codename:     maroilles
Go version:   go1.12.9
Built:        2019-09-13_01:12:20PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

file provider: traefik_11 (TOML file)
```
logLevel = "INFO"

[respondingTimeouts]
idleTimeout = "360s"

[file]
[accessLog]
  format = "json"
[entryPoints]
  [entryPoints.http]
  address = ":80"

[backends]
  [backends.error]
    [backends.error.servers.server0]
    url = "https://an-external-url"

[traefikLog]
  filePath = "/traefik/traefik.log"
  format   = "json"
```
docker provider: a traefik service
```
version: "3.6"

networks:
  traefik:
    external: true

configs:
  traefik_cfg:
    name: traefik_11
    external: true

services:
  reverse-proxy:
    image: traefik:alpine # The official Traefik docker image
    networks:
      - traefik
    command: "--api --docker --docker.watch --docker.swarmMode --respondingtimeouts.idletimeout=360s --respondingtimeouts.writetimeout=360s" # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80" # The HTTP port
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    deploy:
      mode: global
      placement:
        constraints:
          - node.role==manager
      labels:
        - "traefik.port=8080"
        - "traefik.enable=true"
        - "traefik.passHostHeader=true"
        - "traefik.docker.network=traefik"
        - "traefik.frontend.entryPoints=http"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.frontend.rule=PathPrefix:/traefik;PathPrefixStrip:/traefik"
    configs:
      - source: traefik_cfg
        target: /etc/traefik/traefik.toml

```
docker provider: a dummy server to answer request:
```
version: "3.6"

networks:
  traefik:
    external: true

services:
  funding:
    image: jasonrm/dummy-server:latest # The official Traefik docker imageports:
    networks:
      - traefik
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role!=manager
      labels:
        - "traefik.domain=a.fake.jd.com"
        - "traefik.port=8080"
        - "traefik.enable=true"
        - "traefik.passHostHeader=true"
        - "traefik.docker.network=traefik"
        - "traefik.frontend.entryPoints=http"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.frontend.rule=PathPrefix:/a-long-funding-api;ReplacePathRegex:^/a-long-funding-api/(.*) /$$1;Host:a.fake.jd.com;"
        - "traefik.frontend.errors.networks.backend=error"
        - "traefik.frontend.errors.networks.status=400-599"
        - "traefik.frontend.errors.networks.query=/error-page.html"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
{"level":"error","msg":"Error when creating error page \"networks\" for frontend \"frontend-PathPrefix-a-long-funding-api-ReplacePathRegex-a-long-funding-api-1-Host-a-fake-jd-com-1\": the backend \"backend-error\" doesn't exist.","time":"2020-09-17T11:17:27Z"}
```
