### ISSUE TITLE
Traefik not using Host header for matching TLS settings

### ISSUE THREAD

**Issue by tomleb** [traefik/traefik#7313]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

1. Configure TLS using Let's Encrypt and Strict SNI.
2. Create simple route to traefik internal api.
3. Run the following command:

```sh
curl -k -H 'Host:traefik.<domain>' https://127.0.0.1:8443/dashboard/ -v
```

### What did you expect to see?

I expected to see a response and see the lets encrypt staging cert.

### What did you see instead?

I saw the following from the curl command.

```
*   Trying 127.0.0.1:8443...
* Connected to 127.0.0.1 (127.0.0.1) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, internal error (592):
* error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
* Closing connection 0
curl: (35) error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
```

and in the traefik log I see this:

```
time="2020-09-19T01:41:43Z" level=debug msg="http: TLS handshake error from 127.0.0.1:36436: strict SNI enabled - No certificate found for domain: \"\", closing connection"
```

It seems like it's trying to match the certificate with the ip address / host from Url, instead of the Host header. This also happens without Strict SNI checking.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.11
Codename:     chevrotin
Go version:   go1.14.8
Built:        2020-09-07T14:12:48Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
# traefik.yml
---
api:
  dashboard: true

entryPoints:
  http:
    address: ":8080"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":8443"
    http:
      tls:
        certResolver: myresolver
        domains:
          - main: <domain>
            sans:
              - "*.<domain>"

providers:
  file:
    directory: /traefik/config.d
    watch: true

certificatesResolvers:
  myresolver:
    acme:
      email: "<email>"
      storage: "acme.json"
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: route53
log:
  level: DEBUG

# config.d/00-dashboard.yml
---
http:
  routers:
    dashboard:
      rule: HostHeader(`traefik.<domain>`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal

tls:
  options:
    default:
      sniStrict: true

```
