### ISSUE TITLE
Kubernetes external service gives a gateway timeout error in Kubernetes 1.19

### ISSUE THREAD

**Issue by smyrgl** [traefik/traefik#7314]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

1. Create an external service [as described here](https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-mapping-external-services) using either scenario 1 or 2 (I did not test scenario 3).
2. Verify that the service is displayed in the Traefik dashboard.
3. Attempt to reach the service.

### What did you expect to see?

URL resolves correctly.

### What did you see instead?

Gateway timeout.  Reverting to Kubernetes 1.18 resolves the issue.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.0-rc7
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-18T15:34:31Z
OS/Arch:      linux/amd64
```

I have also tried this with version `2.2.11` with the same result.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Using the Traefik helm chart with these arguments as static configuration.

```bash
  - --log.level=WARN
  - --serverstransport.rootcas=/etc/certs/ca.crt
  - --serversTransport.insecureSkipVerify=true
  - --entrypoints.web.address=:8000
  - --entrypoints.websecure.address=:8443
  - --entrypoints.web.http.redirections.entryPoint.to=websecure
  - --entrypoints.websecure.http.tls.certResolver=main
  - --entrypoints.websecure.http.middlewares=default-secured@kubernetescrd
  - --api
  - --api.insecure
  - --api.dashboard=true
  - --accesslog
  - --providers.kubernetesingress=true
  - --providers.kubernetescrd=true
  - --certificatesresolvers.main.acme.storage=/data/acme.json
  - --certificatesresolvers.main.acme.email=REDACTED
  - --certificatesresolvers.main.acme.dnschallenge=true
  - --certificatesresolvers.main.acme.dnschallenge.provider=cloudflare
  - --certificatesresolvers.main.acme.keytype=EC256
  - --metrics.influxdb=true
  - --metrics.influxdb.address=REDACTED
  - --metrics.influxdb.database=REDACTED
  - --metrics.influxdb.username=REDACTED
  - --metrics.influxdb.password=REDACTED
  - --metrics.influxdb.protocol=http
```

And here is an example of one of my external service YAMLs.

```yaml
kind: Service
apiVersion: v1
metadata:
  name: diskstation
  labels:
    app.kubernetes.io/name: diskstation
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 5001
      targetPort: https
---
apiVersion: v1
kind: Endpoints
metadata:
  name: diskstation
  labels:
    app.kubernetes.io/name: diskstation
subsets:
  - addresses:
      - ip: REDACTED
    ports:
      - name: https
        port: 5001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diskstation
  labels:
    app.kubernetes.io/name: diskstation
  annotations:
    ingress.kubernetes.io/protocol: https
spec:
  rules:
    - host: REDACTED
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: diskstation
                port:
                  name: https
```

**Comment by ddtmachado** [comment]
@smyrgl I have tried the same setup in all combinations of these versions:

Kubernetes: v1.18 and v1.19 
Traefik: v2.2 and v2.3-rc

It all worked as expect and I was not able to reproduce the `gateway timeout` issue. It was also tested with CRD instead of Ingress just in case.

For reference this was my ingress on Kube v1.18:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: external-svc-ingress
  labels:
    app.kubernetes.io/name: external-svc
  annotations:
    ingress.kubernetes.io/protocol: https
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/service.serversscheme: https
spec:
  rules:
    - host: test.docker.localhost
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:        
              serviceName: external-svc
              servicePort: https
```

And this for Kuber v1.19:

```yaml
#v1.19
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-svc-ingress
  labels:
    app.kubernetes.io/name: external-svc
  annotations:
    ingress.kubernetes.io/protocol: https
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/service.serversscheme: https
spec:
  rules:
    - host: test.docker.localhost
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
             service:
               name: external-svc
               port:
                 name: https
```

And the service definition:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: external-svc
  labels:
    app.kubernetes.io/name: external-svc
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: https
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-svc
subsets:
  - addresses:
      - ip: REDACTED
    ports:
      - name: https
        port: 443
```

If you still have this issue please share with us the logs from your Traefik instance while running it at DEBUG level.
