### ISSUE TITLE
dnsChallenge: delayBeforeCheck functionality change

### ISSUE THREAD

**Issue by anjanms** [traefik/traefik#7316]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I recently received a Let's Encrypt expiry notice.  After further investigation it appears v2.2.10 (#7238) changed how `delayBeforeCheck` works.

My internal network uses split-horizon DNS and requires all outbound DNS pass through the local resolver.

I previously used `delayBeforeCheck` to skip the local validation and introduce a delay.  This no longer works.

### What did you expect to see?

`delayBeforeCheck > 0` should imply  `disablePropagationCheck` as it did before.  Or they should at least work together.

### What did you see instead?

`delayBeforeCheck` delays the check. `disablePropagationCheck` skips the check.  Pick one.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.11
Codename:     chevrotin
Go version:   go1.14.8
Built:        2020-09-07T14:12:48Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
log: {level: INFO}

entryPoints:
  http: {address: ':80'}
  https: {address: ':443'}

certificatesResolvers:
  example:
    acme:
      email: admin@example.com
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 15

providers: {file: {filename: /etc/traefik/provider.yml}}
```
