### ISSUE TITLE
[Regression] X-Frame-Options cannot be overwritten by docker labels with v2.2.11 (OK with v2.2.8)

### ISSUE THREAD

**Issue by doc75** [traefik/traefik#7317]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have made my traefik config to ensure `X-Frame-Options` is set to `deny` (cf. `dynamic.toml` content below)
I have a nextcloud service in which I have a label to override this value and ensure that `X-Frame-Options` is set to `sameorigin` (cf. docker-compose.yml below for nextcloud configured with FPM behind an NGINX)

I migrated my traefik image (official docker) from **2.2.8** to **2.2.11**, without any other change in my traefik or nextcloud configuration.

### What did you expect to see?

I expect that with **v2.2.11** the behavior is similar to the one I had with **v2.2.8** => the Nextcloud service has the `X-Frame-Options` set to `sameorigin`

**Edit**: issue also reproduced in **v2.2.10**. It seems that the **v2.2.10** is the first one with this issue (no version **v2.2.9** found on docker hub)

### What did you see instead?

With **v2.2.11**, the Nextcloud service has `X-Frame-Options` set to `deny`

Just changing the traefik container back to **v2.2.8** made the problem disappear (no other changes made).

### Output of `traefik version`:

`traefik version` output for **v2.2.8**:
```
Version:      2.2.8
Codename:     chevrotin
Go version:   go1.14.6
Built:        2020-07-28T15:46:03Z
OS/Arch:      linux/amd64
```

`traefik version` output for **v2.2.11**:
```
Version:      2.2.11
Codename:     chevrotin
Go version:   go1.14.8
Built:        2020-09-07T14:12:48Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

- `traefik.toml`:
```toml
[entryPoints]
  [entryPoints.webinsecure]
    address = ":80"
    [entryPoints.webinsecure.http]
      middlewares = ["security@file"]
      [entryPoints.webinsecure.http.redirections.entryPoint]
        to = "web"
        scheme = "https"
  [entryPoints.web]
    address = ":443"
    [entryPoints.web.http]
      middlewares = ["security@file"]
      [entryPoints.web.http.tls]
        options = "mytlsoption@file"
        certresolver = "le"

[providers]
  [providers.file]
    filename = "/etc/traefik/dynamic.toml"
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedbydefault = false
    network = "web"

[api]

[certificatesResolvers.le.acme]
  storage = "/etc/traefik/acme.json"
  [certificatesResolvers.le.acme.httpchallenge]
    entrypoint = "webinsecure"
```
- `dynamic.toml`:
```toml
[http.middlewares]
  [http.middlewares.security.headers]
    frameDeny = true
    sslRedirect = true
    browserXssFilter = true
    contentTypeNoSniff = true

[tls.options.mytlsoption]
  minVersion = "VersionTLS12"
  cipherSuites = [
    "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384", # TLS 1.2
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",   # TLS 1.2
    "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256", # TLS 1.2
    "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",   # TLS 1.2
    "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",  # TLS 1.2
    "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",    # TLS 1.2
    "TLS_AES_256_GCM_SHA384",                  # TLS 1.3
    "TLS_CHACHA20_POLY1305_SHA256",            # TLS 1.3
  ]
  curvePreferences = ["CurveP521", "CurveP384"]
  sniStrict = true
```
- docker-compose.yml:
```yaml
---
version: '3'
services:
  traefik:
    image: traefik:v2.2
    restart: unless-stopped
    env_file:
    - ".env"
    ports:
    - 80:80
    - 443:443
    networks:
    - web
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./traefik.toml:/etc/traefik/traefik.toml"
    - "./dynamic.toml:/etc/traefik/dynamic.toml"
    - "./acme.json:/etc/traefik/acme.json"
    command:
    - "--certificatesresolvers.le.acme.email=${ACME_EMAIL}"
```

Here is my **nextcloud** config:

- `docker-compose.yml` truncated:
```yaml
---
version: '3'
networks:
  web:
    external: true
services:
  db:
    <removed>
  app:
    <removed>
  web:
    build: "./nginx"### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)


    restart: unless-stopped
    volumes:
      - "/srv/domain.org/cloud/app:/var/www/html:ro"
    labels:
      traefik.enable: 'true'
      traefik.http.routers.servicedomainorg.rule: Host(`service.domain.org`)
      traefik.http.middlewares.servicedomainorg-redirect.redirectregex.permanent: 'true'
      traefik.http.middlewares.servicedomainorg-redirect.redirectregex.regex: https://(.*)/.well-known/(card|cal)dav
      traefik.http.middlewares.servicedomainorg-redirect.redirectregex.replacement: https://$${1}/remote.php/dav/
      traefik.http.middlewares.servicedomainorg-headers.headers.customFrameOptionsValue: sameorigin
      traefik.http.routers.servicedomainorg.middlewares: servicedomainorg-redirect@docker,servicedomainorg-headers@docker
    networks:
      - web
      - default
```

Let me know if you need more information.
