### ISSUE TITLE
enabling https and www redirect to a default domain is too verbose

### ISSUE THREAD

**Issue by StarpTech** [traefik/traefik#7322]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Hello, I would like to archive following result with minimal configuration. This is a common configuration these days

Domain: `https://google.de`
```
http://google.de => https://google.de
http://www.google.de => https://google.de
https://www.google.de => https://google.de
```

or

Domain: `https://www.google.de`
```
http://www.google.de => https://www.google.de
http://google.de => https://www.google.de
https://google.de => https://www.google.de
```

Currently, I need 4 `Routes`, 2 `IngressRoute` and 3 `CRD's`.

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: http-to-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: www-http-redirect
spec:
  redirectRegex:
    regex: ^http://www.google.de/(.*)
    replacement: https://google.de/${1}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: www-https-redirect
spec:
  redirectRegex:
    regex: ^https://www.google.de/(.*)
    replacement: https://google.de/${1}
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by StarpTech** [comment]
Please reopen. It's a feature request as stated. Dumb Bot 😄

**Comment by ldez** [comment]
Hello,

I think that you have to change your issue title :wink:

**Comment by rtribotte** [comment]
Hello @StarpTech,

Thanks for your contribution and your interest in Traefik.

From what i understand, in your use case, you maybe can simplify like this (not tested):

```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: www-http-redirect
spec:
  redirectRegex:
    regex: ^https?://(?:www\.)?(google\.de/?.*)$
    replacement: https://${1}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: www-https-redirect
spec:
  redirectRegex:
    regex: ^https?://(?:www\.)?(google\.de/?.*)$
    replacement: https://www.${1}
```

Anyway, what would be your proposal, how it will be configurable ?

**Comment by StarpTech** [comment]
Hi @rtribotte, great idea, and in combination with [`--entrypoints.websecure.http.tls=true`](https://github.com/traefik/traefik/pull/6417) I could save a lot of code.

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: www-redirect
spec:
  redirectRegex:
    regex: ^https?://(?:www\.)?(google\.de/?.*)$
    replacement: https://${1}
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
entryPoints:
  - websecure
routes:
  - match: Host(`www.google.de`) || Host(`google.de`)
    kind: Rule
    services:
    - name: google-web-prod
      port: 3000
    middlewares:
      - name: www-redirect
```
