### ISSUE TITLE
Wrong certificate when using Docker provider with a base domain and ACME DNS Challenge

### ISSUE THREAD

**Issue by arielmoraes** [traefik/traefik#7323]
### Do you want to request a *feature* or report a *bug*?

Bug.

When using a base domain in the Docker provider the default certificate TRAEFIK DEFAULT CERT is being served.

### What did you do?

Create a toml static configuration as stated below.

Run a simple Echo image from Docker Hub:

`docker run -d --name echo --network traefik jmalloc/echo-server`

For the Traefik dashboard I set the label `traefik.frontend.rule=Host:traefik.internal.home.mydomain.com`

### What did you expect to see?

Expected to see the generated wildcard certificate being used but it was not used for either rules (implicit and explicit)

### What did you see instead?

The TRAEFIK DEFAULT CERT being served.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.6
Codename:     maroilles
Go version:   go1.11.3
Built:        2018-12-14_06:43:37AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["redacted"]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[api]
entrypoint="dashboard"

[acme]
acmeLogging = true
email = "redacted"
entryPoint = "https"
storage = "acme.json"
  [acme.dnsChallenge]
  provider = "digitalocean"

[[acme.domains]]
  main = "*.mydomain.com"

[docker]
domain = "home.mydomain.com"
watch = true
network = "traefik"
```
