### ISSUE TITLE
Traefik not serve after docker update

### ISSUE THREAD

**Issue by rottmann** [traefik/traefik#7324]
The same problem i had last year with Traefik 1, now in 2.
After update docker, all containers are not accessible over Traefik Proxy, error "Bad Gateway".

Containers running, everything is ok.
Traefik backend shows all containers, with ports, ... it look normal.

I can stop, start, restart containers, nothing change. Stop, start docker service, nothing change. Reboot the machine, nothing changes.
Only when i completely remove the containers and create them new, Traefik serve them again.

### What did you do?

apt-get update
apt-get upgrade
Update docker from 19.03.xx to 19.03.13

### What did you expect to see?

My Webservice.

### What did you see instead?

"Bad Gateway"

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.8
Codename:     chevrotin
Go version:   go1.14.6
Built:        2020-07-28T15:46:03Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
api:
  dashboard: true
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/dynamic_conf.yml"
certificatesResolvers:
  http:
    acme:
      email: my@mail.address
      storage: acme.json
      httpChallenge:
        entryPoint: http
```

dynamic_conf.yml
```
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true
http:
  middlewares:
    secHeaders:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        sslRedirect: true
        # HSTS Configuration
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

It logs a ton of information on startup, but when i call a service nothing form the service appears in the log. Not even the "Bad Gateway" error.
