### ISSUE TITLE
Traefik returns 404 for the first few requests, and then starts working well when running on Cloud Run

### ISSUE THREAD

**Issue by pablote** [traefik/traefik#7347]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm running Traefik on Cloud Run where it's fronting 3 other services/website also on Cloud Run. Cloud Run stops your app when is not used for a while, and then starts your containers when a requests comes in.

When my traefik container has not been running for a while, the first time I try to access my site, it returns a 404 error. If I refresh the browser a few seconds later, it all works just fine. At first I thought this my be related with the other services I run behind Traefik, but I tried prewarming them by accessing them directly, the same thing happens. 

This are the logs showing how the container starts, returns a couple of 404, and a few seconds later the same requests work just fine:

![Screen_Shot_2020-09-24_at_13_29_07](https://user-images.githubusercontent.com/2463995/94174589-e1b65480-fe6b-11ea-92c8-880e00e8673a.jpg)

I suspect, although I can't be sure, that since Traefik is just starting, and Cloud Run sends the request right away, there might be a small period of time in which Traefik handles request but still hasn't loaded the configuration. If this is the case, it might be completely incompatible with Cloud Run or any service that scales to zero and activates on a new request. Not sure if there's a workaround for it, or maybe something else is going on.

### What did you expect to see?

I expect my site to work when accessed after it's been idle for a while.

### What did you see instead?

A 404 response, that goes away if I refresh.

![Screen_Shot_2020-09-24_at_13_27_09_copy](https://user-images.githubusercontent.com/2463995/94175122-9c465700-fe6c-11ea-9623-33f6d42ddf3b.jpg)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
/ # traefik version
Version:      2.3.0-rc5
Codename:     picodon
Go version:   go1.15.1
Built:        2020-09-07T16:41:00Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
➜  prod git:(master) cat traefik.yaml
api:
    dashboard: true
    insecure: false
accessLog: {}
providers:
    providersThrottleDuration: 5s
    file:
        directory: /etc/traefik/config/
        watch: true
entryPoints:
    http:
        address: ":8080"
```

![dynamic config](https://user-images.githubusercontent.com/2463995/94175685-69509300-fe6d-11ea-9515-3be131bf8bff.jpg)

Thanks.
