### ISSUE TITLE
Couldn't install pilot plugin

### ISSUE THREAD

**Issue by thaitanloi365** [traefik/traefik#7358]
I got this error after upgrade to v2.3. I tried to install cache plugin.

```
2020/09/26 10:33:00 traefik.go:76: command traefik error: failed to download plugin github.com/traefik/plugin-simplecache: error: 500: {"error":"failed to get plugin github.com/traefik/plugin-simplecache@v0.2.1"}
```

This is my configuration
```
- --pilot.token=${PILOT_TOKEN}
- --experimental.plugins.plugin-simplecache.modulename=github.com/traefik/plugin-simplecache
 - --experimental.plugins.plugin-simplecache.version=v0.2.1
```

**Comment by ldez** [comment]
Hello,

I'm not reproducing, could you retry?

**Comment by thaitanloi365** [comment]
Hi @ldez ,

I tried a few times but still getting that error.

I'm not sure why that happened, so wiered. I have a few projects that are using treafik. All of them are working fine except this one

I quite sure all projects are shared with the same configuration.

Here is my full configuration
```
services:
  traefik:
    image: traefik:v2.3
    restart: unless-stopped
    container_name: ${APP_NAME?APP_NAME is required}-traefik
    hostname: ${APP_NAME?APP_NAME is required}-traefik
    environment:
      - SELLER_WEB_BASE_URL=${SELLER_WEB_BASE_URL}
      - TPL_WEB_BASE_URL=${TPL_WEB_BASE_URL}
      - DOMAIN=${DOMAIN}
      - SUB_DOMAIN_SUFFIX=${SUB_DOMAIN_SUFFIX}
      - PILOT_TOKEN=${PILOT_TOKEN}
    ports:
      - 80:80
      - 443:443
    command:
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443

      - --providers.docker
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmmode=false

      - --providers.file.directory=/dynamic_conf
      - --providers.file.watch=true

      - --certificatesresolvers.le.acme.email=${TLS_EMAIL?TLS_EMAIL is required}
      - --certificatesresolvers.le.acme.storage=/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true

      - --accesslog.bufferingsize=100
      - --accesslog.fields.defaultmode
      - --accesslog.filepath=
      - --accesslog.format=common
      - --accesslog.filters.statuscodes=200,300-499

      - --log=false
      - --log.filepath=
      - --log.format=common
      - --log.level=ERROR

      - --api.dashboard=true
      - --api.debug=true
      - --api.insecure=false

      - --pilot.token=${PILOT_TOKEN}
      # - --experimental.plugins.plugin-simplecache.modulename=github.com/traefik/plugin-simplecache
      # - --experimental.plugins.plugin-simplecache.version=v0.2.1
```
