### ISSUE TITLE
Traefik UI 2.3.0 show empty page using Safari 14.0

### ISSUE THREAD

**Issue by BeckerFrank** [traefik/traefik#7361]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
1) In Safari clear the Cache (menu Developer)
2) start the docker container with version 2.3
3) go to the dashboard page

### What did you expect to see?

the content of the dashboard.

### What did you see instead?
the page is empty. But when you look into the page source you see the following error

**SyntaxError: Invalid regular expression: invalid group specifier name**

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.0
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-23T10:55:07Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
I run on a Mac with a test environment use vagrant to run ubuntu/focal64 with docker

```toml
[[tls.certificates]]
  certFile = "/mylyn_ssl/mylyndocker.cert"
  keyFile = "/mylyn_ssl/mylyndocker.key"

[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/mylyn_ssl/mylyndocker.cert"
      keyFile = "/mylyn_ssl/mylyndocker.key"
```

Here the docker cmd parm
    cmd: "--providers.docker.exposedbydefault=false" +
    " --api=true" +
    " --api.dashboard=true" +
    " --providers.docker" +
    " --providers.file.directory=/config" +
    " --providers.file.watch=true" +
    " --entrypoints.web.address=:80" +
    " --entrypoints.websecure.address=:443" +
    " --entrypoints.web.http.redirections.entryPoint.to=websecure" +
    " --entrypoints.web.http.redirections.entryPoint.scheme=https" +
    " --entrypoints.web.http.redirections.entrypoint.permanent=true" +
   " --accesslog=false" 
and the following label
    " --label 'traefik.enable=true'" +
    " --label 'traefik.http.routers.dashboard.rule=Host(`mylyntest.docker`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))'" +
    " --label 'traefik.http.routers.dashboard.entrypoints=websecure'" +
    " --label 'traefik.http.routers.dashboard.tls=true'" +
    " --label 'traefik.http.routers.dashboard.middlewares=auth'" +
    " --label 'traefik.http.middlewares.auth.basicauth.users=test:.......'" +
    " --label 'traefik.http.routers.dashboard.service=api@internal'"

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
