### ISSUE TITLE
Issue with getting Cloudflare with Letsencrypt. Mesage: some credentials information are missing

### ISSUE THREAD

**Issue by securisec** [traefik/traefik#7362]
I am trying to use traefik with a wildcard domain while using cloudflare as my DNS provider. I cannot really find any issues with my DNS setup, and cloudflare SSL has also been disabled to try to get this to work. 

The error I am getting is 

```
level=error msg="Unable to obtain ACME certificate for domains \"example.com,*.example.com\" : cannot get ACME client cloudflare: some credentials information are missing: CLOUDFLARE_EMAIL,CLOUDFLARE_API_KEY or some credentials information are missing: CLOUDFLARE_DNS_API_TOKEN,CLOUDFLARE_ZONE_API_TOKEN" providerName=mydnschallenge.acme
```

To try to resolve this error, I have tried the following:

- Tried setting all the envars in a `.env` file (that is when this error fires.
- Tried setting all the envars under the `environment` key in my compose file. (then the api request to cloudflare for zones will error with the message `Invalid request headers`
- Tried a combination of the above methods
- Tried putting all the envars in a file, and running docker-compose with the env-file flag

The environment variables I set for all of the above attempts are:

```
CF_API_EMAIL=myvalue
CF_API_KEY=myvalue
CLOUDFLARE_EMAIL=myvalue
CLOUDFLARE_API_KEY=myvalue
```

I really have no idea why this isnt working, and some direction would be very much appreciated! 

I have been working with this example file [here](https://gist.github.com/darth-veitcher/93acda9617bab3e1de0264cebf4637fc) although I made sure to change all the values to my domain, and my secrets. 
```yaml
version: "3"

services:
  traefik:
    image: "traefik:v2.0"
    container_name: "traefik"
    command:
      # Globals
      - "--log.level=DEBUG"
      - "--api=true"
      - "--global.sendAnonymousUsage=false"
      # Docker
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # LetsEncrypt
      # - "--certificatesresolvers.mydnschallenge.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.mydnschallenge.acme.email=${CF_API_EMAIL}"
      - "--certificatesresolvers.mydnschallenge.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.mydnschallenge.acme.storage=/etc/traefik/acme.json"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    volumes:
      - "/etc/traefik/acme.json:/etc/traefik/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      # API
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.mydomain.fyi`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.services.traefik.loadbalancer.server.scheme=http"
      # Wildcard cert
      - "traefik.http.routers.traefik.tls.domains[0].main=mydomain.fyi"
      - "traefik.http.routers.traefik.tls.domains[0].sans=*.mydomain.fyi"
      - "traefik.http.routers.traefik.tls.certresolver=mydnschallenge"
      # Global http-->https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:[a-z-.]+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
```
