### ISSUE TITLE
Getting some 502 bad gateway while doing rolling updates on Docker Swarm

### ISSUE THREAD

**Issue by MatthieuBarthel** [traefik/traefik#7373]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?

Deploying an example app with rolling update and doing a "ping" to ensure there is no downtime.

### What did you expect to see?

Zero downtime update

### What did you see instead?

For a short time I have some 502 bad gateway errors (plus sometimes a 504 gateway timeout).
Here is how to reproduce the error (code is at the end of the issue) :

1. Set up a docker server in swarm-mode (single node is fine)
2. Deploy traefik
    `docker network create --driver=overlay traefik`
    `docker stack deploy --compose-file /path/to/traefik/docker-compose.yml traefik`
3. Deploy the example app
    `docker stack deploy --compose-file /path/to/website/docker-compose.yml website`
4. Change image version (in website/docker-compose.yml)
5. Start ping
    `./ping.sh`
6. Deploy the rolling update
    `docker stack deploy --compose-file /path/to/website/docker-compose.yml website`

The ping script will output a dot when the status is 200, or output the status itself. You will see an output like this (here I got two 502 and then a 504) :
```
❯ ./ping.sh
.............................................................502502..504...............................................
```

You can change the ping script to target `http://EXAMPLE.COM:8080` (direct access to the website image through swarm loadbalancing), there is no downtime. So it seams this is a Traefik issue.

I found various issues similar to this one, but they are all closed. I tried the following solutions without success :
* Using the retry middleware
* Increase or dicrease router's priority on deploy

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.3.0
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-23T10:55:07Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
```
Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-48-generic x86_64)

Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

#### Traefik Stack

**traefik/docker-compose.yml**
```yaml
version: '3.8'
services:
  reverse_proxy:
    image: traefik:v2.3
    networks:
      - default
      - traefik
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - ./acme.json:/acme.json
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefik:
    external: true
```

**traefik/traefik.yml**
```yaml
global:
  sendAnonymousUsage: false

api:
  dashboard: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          scheme: https
          to: websecure
  websecure:
    address: :443
    http:
      tls:
        certResolver: letsEncrypt

certificatesResolvers:
  letsEncrypt:
    acme:
      email: INFO@EXAMPLE.COM
      storage: acme.json
      tlsChallenge: {}

log:
  level: DEBUG

providers:
  docker:
    exposedByDefault: false
    network: traefik
    swarmMode: true
```

#### Example website Stack

**website/docker-compose.yml**
```yaml
version: "3.8"
services:
  website:
    image: nginx:1.19
    # we will need to change the image for the rolling update
    # image: nginx:1.19.2
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.website.entrypoints=websecure
        - traefik.http.routers.website.rule=Host(`EXAMPLE.COM`)
        - traefik.http.services.website.loadbalancer.server.port=80
      replicas: 4 # doesn't matter how many
      update_config:
        order: start-first
        parallelism: 2 # doesn't matter how many
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 10
      test: curl --fail http://localhost || exit 1
    networks:
      - default
      - traefik
    ports:
      - 8080:80 # open port 8080 to be able to ping the website without traefik
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html

networks:
  traefik:
    external: true
```

**website/index.html**
```
Hello Traefik !
```

#### Ping script
This script is used to ping the website while doing a rolling update :
```
#!/bin/sh
for (( ; ; ))
do
  STATUS=$(wget --spider --tries=1 -S https://EXAMPLE.COM 2>&1 | grep "HTTP/" | awk '{print $2}')
  if [[ "$STATUS" == "200" ]]; then
    printf '.'
  else
    printf $STATUS
  fi
done
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Here are the only related logs i can find :
```
traefik_reverse_proxy.1.ztejr6lomezg@hostname    | time="2020-09-30T15:10:58Z" level=debug msg="'502 Bad Gateway' caused by: dial tcp 10.0.1.195:80: connect: connection refused"
traefik_reverse_proxy.1.ztejr6lomezg@hostname    | time="2020-09-30T15:10:58Z" level=debug msg="'502 Bad Gateway' caused by: dial tcp 10.0.1.194:80: connect: connection refused"
traefik_reverse_proxy.1.ztejr6lomezg@hostname    | time="2020-09-30T15:11:29Z" level=debug msg="'504 Gateway Timeout' caused by: dial tcp 10.0.1.195:80: i/o timeout"
```

--
Thank you 👍
