### ISSUE TITLE
Traefik not picking up Docker container

### ISSUE THREAD

**Issue by Philantrop** [traefik/traefik#7377]
Bug

### What did you do?

I'm using Docker containers to run Synapse, a homeserver for the Matrix protocol. One container runs the primary process while some others run so-called workers. Everything was working fine until I updated to Traefik 2.3 (curiously a downgrade does not fix my issue, though!).  

Since then, while the primary container is recognised just fine by Traefik via the labels in my compose file, the workers aren't recognised anymore at all. They don't appear in the dashboard nor can they be routed to. The containers themselves are running just fine and are functional, though.  

I'm completely unable to see what might be wrong and I've been experimenting for days now. Since asking for advice in your community (https://community.traefik.io/t/traefik-2-3-0-not-picking-up-docker-container/7936) didn't yield any results and there was one person on Reddit who had the same issue (https://www.reddit.com/r/Traefik/comments/j22034/traefik_230_not_picking_up_docker_container/), I assume they and I are hitting some obscure bug.

Here's the docker-compose yaml configuration for the main process which does get picked up by Traefik:

https://mailstation.de/~krueger/traefik/main_process-working.yaml

Here's the worker configuration that does NOT get picked up by Traefik:

https://mailstation.de/~krueger/traefik/worker_unseen_by_traefik.yaml

Should you need any additional information, please just let me know.

### What did you expect to see?
The worker should be displayed in Traefik's dashboard and - more importantly - routed to.

### What did you see instead?
Neither of my above expectations were fulfilled.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.3.1
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-29T15:49:06Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
 
  [entryPoints.web2]
    address = ":81"

  [entryPoints.websecure]
    address = ":443"

  [entryPoints.matrix-login]
    address = ":8448"

[log]
  level = "WARN"
  filePath = "/var/log/traefik/traefik.log"

[accessLog]
  filePath = "/var/log/traefik/access.log"

[api]
  insecure = false
  dashboard = true

[ping]


[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

[certificatesResolvers.le.acme]
  email = "wk@mailstation.de"
  #caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  storage = "/etc/traefik/acme/acme.json"
  [certificatesResolvers.le.acme.httpChallenge]
  # used during the challenge
  entryPoint = "web"

[providers]
  # Enable the file provider to define routers / middlewares / services in file
  [providers.file]
    directory = "/etc/traefik/dynamic"
    watch = true

[pilot]
    token = "removedXXX"
```
