### ISSUE TITLE
Dashboard not found in traefik release version 2.3.1

### ISSUE THREAD

**Issue by psy-core** [traefik/traefik#7378]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
1. download traefik from url and put it in $PATH: 
```
wget https://github.com/traefik/traefik/releases/download/v2.3.1/traefik_v2.3.1_linux_amd64.tar.gz
```

2. run it directly and try to visit dashboard，refering document: https://doc.traefik.io/traefik/v2.0/operations/dashboard/#insecure-mode
```
$ nohup traefik > /dev/null 2>&1 &
$ curl http://127.0.0.1:8080/dashboard/
404 page not found
```

### What did you expect to see?
visit `http://127.0.0.1:8080/dashboard/` and return the dashboard page successfully.

### What did you see instead?
404 page not found.

### Output of `traefik version`: 
```
Version:      2.3.1
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-29T15:49:06Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

/etc/traefik/traefik.yaml
```yaml
entryPoints:
  web:
    # Listen on port 8081 for incoming requests
    address: :8080

providers:
  file:
    directory: "/etc/traefik/route-conf"
    watch: true

log:
  level: INFO
  filepath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log

api:
  dashboard: true
  insecure: true
```

/etc/traefik/route-conf/route.yaml:
```yaml
## Dynamic configuration
http:
  routers:
    my-router:
      entryPoints:
      - web
      rule: "Path(`/foo`)"
      service: service-foo


  services:
    service-foo:
      loadBalancer:
        servers:
        - url: http://127.0.0.1:8888/
        passHostHeader: false
```

system: 
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
