### ISSUE TITLE
Supporting a new provider - AWS S3

### ISSUE THREAD

**Issue by pvalletbo** [traefik/traefik#7389]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I would like include support for AWS S3 as a dynamic configuration provider. The configuration would be stored as an object in a S3 bucket and the provider would retrieve it using the AWS SDK. 
This new provider is really similar to the HTTP one, but getting the config from an S3 object instead of getting it directly from a HTTP connection. 

I really like the way how the HTTP provider works, since it gives you the flexibility to change the configuration in one place and share it with many Traefik instances in an easy way. However, serving HTTP files requires maintaining a HTTP server that should always be available serving the configuration file. 

I'd like to create a PR for this new provider if you consider that it could also be helpful for the community.

**Comment by rtribotte** [comment]
Hello @pvalletbo,

Before starting to create a PR to add this new provider, it would be great if you can detail here your proposal to be able to engage discussion about it.
How do you plan to implement it and how configurable would it be ?

Also, as a side question, what is the main motivation for you to create such provider since the http provider is designed for that specific purpose, allowing fetching configuration from custom providers (that, indeed, need to be able to serve it) ?
For instance, why don't you use a cloudfront endpoint to serve your file from the S3 bucket ?

Thanks for your interest in Traefik !

**Comment by pvalletbo** [comment]
Hey, thanks for replying that fast 😄 

Regarding the first part, about how the configuration would look like, we could do something similar to the HTTP provider config. Check the example below: 
```yaml
providers:
  s3:
    bucket: traefik-config-bucket
    object: dynamic.yml
    # The version ID would be an optional field
    versionID: xxxxxxx
    # The aws_session would be optional. The recommeneded way of setting up the AWS access would be using 
    # an IAM role attached to the EC2 instance.
    # We are not allowing the possibility of adding the AWS key ID & secret harcoded in the config since it 
    # is considered to be a security bad practice. 
    aws_session:
      region: eu-west-2
      profile: custom-aws-profile
    # As in the HTTP provider, the pollInterval would be optional
    pollInterval: "5s" 
```
The implementation would be really similar to the HTTP one, but using the AWS SDK for S3 instead of the HTTP client directly. 

About the other question, the S3 + CloudFront setup looks being too big for the purpose that we want to achieve, which is just getting a copy of the config to some Traefik instances. When the access to this config should not be public, and it should only be accessible to certain instances of a VPC, it is even harder to set it up with S3 + Cloudfront. 

Let me know what do you think about it. 
Thanks again!
