### ISSUE TITLE
Ingress produce only one router

### ISSUE THREAD

**Issue by unitto1** [traefik/traefik#7393]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

This is actually the duplicate of #7069

1. Install helm charts as described here - https://doc.traefik.io/traefik/v2.2/getting-started/install-traefik/#use-the-helm-chart
2. Setup ingress resource as described here - https://doc.traefik.io/traefik/v2.2/migration/v2/#expose-an-ingress-on-80-and-443

### What did you expect to see?

As described in the documentation ingress resource should open both 80 and 443 ports, which meant the creation of 2 separate routers from traefik, one for http and second for https.

### What did you see instead?

But as described in #7069 this is not true, and traefik generates only one router, and only http works, https produce 404.

### Output of `traefik version`: (_What version of Traefik are you using?_)

name: traefik
version: 9.1.1
repository: https://containous.github.io/traefik-helm-chart

```
Version:      2.2.8
Codename:     chevrotin
Go version:   go1.14.6
Built:        2020-07-28T15:46:03Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

* Config file generates via official helm chart with these values:

```yaml
  deployment:
    replicas: 2

  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1

  logs:
    access:
      enabled: true
      format: json
      fields:
        general:
          defaultmode: keep
        headers:
          defaultmode: keep
          names:
            Authorization: drop

  additionalArguments:
    - "--metrics.datadog=true"
    - "--tracing.datadog=true"

  env:
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP

#  ports:
#    web:
#      redirectTo: websecure

  service:
    annotations: {}
    spec:
      externalTrafficPolicy: Local
#      loadBalancerIP: "1.2.3.4"

  resources:
     requests:
       cpu: 300m
       memory: 150Mi
     limits:
       cpu: 300m
       memory: 150Mi

  nodeSelector:
    "cloud.google.com/gke-preemptible": "false"

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "topology.gke.io/zone"
          labelSelector:
            matchLabels:
              "app.kubernetes.io/name": traefik
```

* Used ingress resource:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: RELEASE-NAME-***
  labels:
    "helm.sh/chart": ***-0.1.0
    "app.kubernetes.io/version": "***"
    app: ***
    release: RELEASE-NAME
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts:
        - ***
      secretName: ***
  rules:
    - host: ***
      http:
        paths:
          - path: /
            backend:
              serviceName: RELEASE-NAME-***
              servicePort: 80
```
