### ISSUE TITLE
traefik2 does not recognize the ingress tls configuration

### ISSUE THREAD

**Issue by chenchensheng** [traefik/traefik#7420]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I created Ingress

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-home
  namespace: production
spec:
  rules:
    - host: home.my.com
      http:
        paths:
          - backend:
              serviceName: web-home
              servicePort: 80
            path: /
  tls:
    - hosts:
        - home.my.com
      secretName: home-tls

```

Traefik dashboard showed no TLS configured.

Then I created IngressRoute
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web-home
  namespace: production
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`home.my.com`) && PathPrefix(`/`)
      services:
        - name: web-home
          port: 80
  tls:
    secretName: home-tls

```

Traefik dashboard showed TLS enable.

### What did you expect to see?

Traefik can recognize the Ingress TLS configuration

### What did you see instead?

Traefik dashboard showed no TLS configured.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.1
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-29T15:49:06Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Traefik install by helm , `helm install traefik traefik/traefik --namespace kube-system`

K8s version is 1.18.9

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by rtribotte** [comment]
Hello @chenchensheng,

You have to pass the right annotation to your Ingress as you can see in the [documentation](https://doc.traefik.io/traefik/v2.3/routing/providers/kubernetes-ingress/#on-ingress):
```yml
traefik.ingress.kubernetes.io/router.tls: "true"
```
The full Ingress :
```yml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-home
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: whoami
      http:
        paths:
          - backend:
              serviceName: whoami
              servicePort: 80
            path: /
  tls:
    - hosts:
        - whoami
      secretName: home-tls
```

As this issue is a question i'll close this accordingly.

Anyway thanks for your interest in Traefik !
