### ISSUE TITLE
UDP: traefik uses wrong IP to reply

### ISSUE THREAD

**Issue by jescholl** [traefik/traefik#7430]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I tried to use Traefik in front of a DNS server to load balance UDP and TCP DNS requests on a server with multiple IP's on its primary network interface.

### What did you expect to see?

I expected both TCP and UDP DNS requests to return successfully.

### What did you see instead?

TCP requests return successfully, but responses to UDP requests return with the wrong source IP preventing the client from associating the response with the request it sent.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.1
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-29T15:49:06Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I initially noticed this issue in nomad, but have been able to reproduce it in the following docker-compose configuration as suggested in https://github.com/traefik/traefik/issues/6802.

I've included keepalived, but manually adding the extra IP with `ip addr add 192.168.10.16 dev eth0` has the same result.

```yaml
# docker-compose.yml

version: "3.3"

services:
  keepalived:
    image: "osixia/keepalived:2.0.20"
    container_name: "keepalived"
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BROADCAST
    environment:
      - KEEPALIVED_UNICAST_PEERS=""
      # The following lines will need to be customized for your environment
      - KEEPALIVED_ROUTER_ID=55
      - KEEPALIVED_VIRTUAL_IPS="192.168.10.16"
      - KEEPALIVED_INTERFACE="eth0"

  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    network_mode: host
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # pihole entrypoints
      - "--entrypoints.pihole-udp.address=:1053/udp"
      - "--entrypoints.pihole-tcp.address=:1053/tcp"
      # unbound entrypoints
      - "--entrypoints.unbound-udp.address=:1054/udp"
      - "--entrypoints.unbound-tcp.address=:1054/tcp"
      # dnsmasq entrypoints
      - "--entrypoints.dnsmasq-udp.address=:1055/udp"
      - "--entrypoints.dnsmasq-tcp.address=:1055/tcp"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

###############
# DNS SERVERS #
###############

  pihole:
    image: "pihole/pihole:latest"
    container_name: "pihole"
    ports:
      - "2053:53/udp"
      - "2053:53/tcp"
    labels:
      - "traefik.enable=true"

      - "traefik.tcp.routers.pihole-tcp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.pihole-tcp.entrypoints=pihole-tcp"
      - "traefik.tcp.routers.pihole-tcp.service=pihole-tcp@docker"
      - "traefik.tcp.services.pihole-tcp.loadbalancer.server.port=53"

      - "traefik.udp.routers.pihole-udp.entrypoints=pihole-udp"
      - "traefik.udp.routers.pihole-udp.service=pihole-udp@docker"
      - "traefik.udp.services.pihole-udp.loadbalancer.server.port=53"

  unbound:
    image: "mvance/unbound:latest"
    container_name: "unbound"
    ports:
      - "2054:53/udp"
      - "2054:53/tcp"
    labels:
      - "traefik.enable=true"

      - "traefik.tcp.routers.unbound-tcp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.unbound-tcp.entrypoints=unbound-tcp"
      - "traefik.tcp.routers.unbound-tcp.service=unbound-tcp@docker"
      - "traefik.tcp.services.unbound-tcp.loadbalancer.server.port=53"

      - "traefik.udp.routers.unbound-udp.entrypoints=unbound-udp"
      - "traefik.udp.routers.unbound-udp.service=unbound-udp@docker"
      - "traefik.udp.services.unbound-udp.loadbalancer.server.port=53"

  dnsmasq:
    image: "jpillora/dnsmasq:latest"
    container_name: "dnsmasq"
    ports:
      - "2055:53/udp"
      - "2055:53/tcp"
    labels:
      - "traefik.enable=true"

      - "traefik.tcp.routers.dnsmasq-tcp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.dnsmasq-tcp.entrypoints=dnsmasq-tcp"
      - "traefik.tcp.routers.dnsmasq-tcp.service=dnsmasq-tcp@docker"
      - "traefik.tcp.services.dnsmasq-tcp.loadbalancer.server.port=53"

      - "traefik.udp.routers.dnsmasq-udp.entrypoints=dnsmasq-udp"
      - "traefik.udp.routers.dnsmasq-udp.service=dnsmasq-udp@docker"
```

Using this configuration you can query pihole, unbound, and dnsmasq through traefik using ports 1053, 1054, and 1055 respectively, or query them directly using ports 2053, 2054, and 2055.

TCP queries through traefik work as expected
```
# pihole
~ › dig +short @192.168.10.16 +tcp -p 1053 google.com
172.217.14.206

# unbound
~ › dig +short @192.168.10.16 +tcp -p 1054 google.com
172.217.14.206

# dnsmasq
~ › dig +short @192.168.10.16 +tcp -p 1055 google.com
172.217.14.206
```

UDP queries through traefik fail because the response comes from the wrong IP
```
# pihole
~ › dig +short @192.168.10.16 -p 1053 google.com
;; reply from unexpected source: 192.168.10.11#1053, expected 192.168.10.16#1053
;; reply from unexpected source: 192.168.10.11#1053, expected 192.168.10.16#1053
;; reply from unexpected source: 192.168.10.11#1053, expected 192.168.10.16#1053
;; connection timed out; no servers could be reached

# unbound
~ › dig +short @192.168.10.16 -p 1054 google.com
;; reply from unexpected source: 192.168.10.11#1054, expected 192.168.10.16#1054
;; reply from unexpected source: 192.168.10.11#1054, expected 192.168.10.16#1054
;; reply from unexpected source: 192.168.10.11#1054, expected 192.168.10.16#1054
;; connection timed out; no servers could be reached

# dnsmasq
~ › dig +short @192.168.10.16 -p 1055 google.com
;; reply from unexpected source: 192.168.10.11#1055, expected 192.168.10.16#1055
;; reply from unexpected source: 192.168.10.11#1055, expected 192.168.10.16#1055
;; reply from unexpected source: 192.168.10.11#1055, expected 192.168.10.16#1055
;; connection timed out; no servers could be reached

```

Both TCP and UDP queries direct to the dns server work as expected
```
# pihole TCP
~ › dig +short @192.168.10.16 +tcp -p 2053 google.com
172.217.14.206

# unbound TCP
~ › dig +short @192.168.10.16 +tcp -p 2054 google.com
172.217.14.206

# dnsmasq TCP
~ › dig +short @192.168.10.16 +tcp -p 2055 google.com
172.217.14.206

# pihole UDP
~ › dig +short @192.168.10.16 -p 2053 google.com
172.217.14.206

# unbound UDP
~ › dig +short @192.168.10.16 -p 2054 google.com
172.217.14.206

# dnsmasq UDP
~ › dig +short @192.168.10.16 -p 2055 google.com
172.217.14.206
```

**Comment by jspdown** [comment]
@jescholl Thanks for the bug report. I tried to reproduce this bug but on my side everything seems to work fine.  As we a running this in docker I suspect the problem might come from the system underneath. Could you give me more information about the system you are running on? 

Also, could you try to change the VIP so it's not in the same subnet as the first address of your eth0?

**Comment by Legogris** [comment]
I think this may be the same issue I have as well.

* dockerized traefik is running on physical host A, which is acting as ingress and egress gateway
* UDP P2P service us running on physical host B.
* I don't see the throughput and number of connections and throughput I would expect - but it's not abysmal, either.

On host A, when enabling logging of martian packets, I get loads of these:

```
IPv4: martian source [external_ip] from [container_ip_on_host_b], on dev [host_a_internal_interface]
ll header: ...
```

Running with default bridge networking settings, routing works fine otherwise. Packets seem to be taking a weird route.

This is not limited to a single software on host B, but with various P2P protocols. Debian Linux, saw the same behavior with various host kernels >=5.4 (did not try earlier).

**Comment by visibilityspots** [comment]
I do encounter the same behaviour using a nomad cluster with archlinux and docker underneath. Having keepalived running to register a VIP address, traefik which gets its configuration from consul and a cloudflared container for dns over https.

When querying the VIP address of the keepalived setup I only get result when using tcp. Through UDP I get a time out :(

using VIP address:
```
$ dig +short @192.168.0.10 -p 5054 visibilityspots.org +tcp
13.225.238.9

$ dig +short @192.168.0.10 -p 5054 visibilityspots.org +notcp 
;; connection timed out; no servers could be reached
```

using the real IP address:
```
$ dig +short @192.168.0.11 -p 5054 visibilityspots.org +tcp 
13.225.238.9

$ dig +short @192.168.0.11 -p 5054 visibilityspots.org +notcp
13.225.238.9
```

and directly towards the container running on one of the nomad nodes:
```
$ dig +short @192.168.0.5 -p 27950 visibilityspots.org +tcp 
13.225.238.9

$ dig +short @192.168.0.5 -p 27950 visibilityspots.org +notcp
13.225.238.9
```

**Comment by jescholl** [comment]
@jspdown In your testing were you using different computers for client and server?  This issue seems to only be visible when the client and server are on different hosts.  When I try from the same host both request and response come from the VIP and everything works, but when querying from a different host the response comes from the host IP instead of the VIP.

Here is a tcpdump I took of the queries from the server side.
```
# tcpdump -ni any "port (1053 or 1054 or 1055 or 2053 or 2054 or 2055)"

####
# client IP:      192.168.10.9
# server host IP: 192.168.10.11
# server VIP:     192.168.10.16
####

# UDP direct to pihole
# success, one request, one response, no errors from the client
08:04:35.224013 IP 192.168.10.9.55323 > 192.168.10.16.2053: UDP, length 39
08:04:35.255890 IP 192.168.10.16.2053 > 192.168.10.9.55323: UDP, length 55

# UDP direct to unbound
# success, one request, one response, no errors from the client
08:04:43.122463 IP 192.168.10.9.60593 > 192.168.10.16.2054: UDP, length 39
08:04:43.460689 IP 192.168.10.16.2054 > 192.168.10.9.60593: UDP, length 55

# UDP direct to dnsmasq
# success, one request, one response, no errors from the client
08:04:47.686742 IP 192.168.10.9.51175 > 192.168.10.16.2055: UDP, length 39
08:04:47.699657 IP 192.168.10.16.2055 > 192.168.10.9.51175: UDP, length 55

# UDP through traefik to pihole
# failure, request hits VIP, response comes from host IP, client retries 3 times and displays unexpected source message
08:04:53.830027 IP 192.168.10.9.52032 > 192.168.10.16.1053: UDP, length 39
08:04:53.832394 IP 192.168.10.11.1053 > 192.168.10.9.52032: UDP, length 55
08:04:58.829696 IP 192.168.10.9.52032 > 192.168.10.16.1053: UDP, length 39
08:04:58.830986 IP 192.168.10.11.1053 > 192.168.10.9.52032: UDP, length 55
08:05:03.837265 IP 192.168.10.9.52032 > 192.168.10.16.1053: UDP, length 39
08:05:03.838565 IP 192.168.10.11.1053 > 192.168.10.9.52032: UDP, length 55

# UDP through traefik to unbound
# failure, request hits VIP, response comes from host IP, client retries 3 times and displays unexpected source message
08:05:14.821415 IP 192.168.10.9.63332 > 192.168.10.16.1054: UDP, length 39
08:05:14.822606 IP 192.168.10.11.1054 > 192.168.10.9.63332: UDP, length 55
08:05:19.820463 IP 192.168.10.9.63332 > 192.168.10.16.1054: UDP, length 39
08:05:19.821649 IP 192.168.10.11.1054 > 192.168.10.9.63332: UDP, length 55
08:05:24.821731 IP 192.168.10.9.63332 > 192.168.10.16.1054: UDP, length 39
08:05:24.822687 IP 192.168.10.11.1054 > 192.168.10.9.63332: UDP, length 55

# UDP through traefik to dnsmasq
# failure, request hits VIP, response comes from host IP, client retries 3 times and displays unexpected source message
08:06:18.016926 IP 192.168.10.9.58445 > 192.168.10.16.1055: UDP, length 39
08:06:18.018146 IP 192.168.10.11.1055 > 192.168.10.9.58445: UDP, length 55
08:06:23.017876 IP 192.168.10.9.58445 > 192.168.10.16.1055: UDP, length 39
08:06:23.019153 IP 192.168.10.11.1055 > 192.168.10.9.58445: UDP, length 55
08:06:28.017939 IP 192.168.10.9.58445 > 192.168.10.16.1055: UDP, length 39
08:06:28.019177 IP 192.168.10.11.1055 > 192.168.10.9.58445: UDP, length 55

```

I did try changing the VIP to something outside my subnet (192.168.50.16), this broke routing from client to server until I manually added a static interface route.  With the static route the results were the same as above, TCP works fine through traefik or direct, UDP works direct but going through traefik results in the `unexpected source message`.

Here's all the relevant info I could think of about the server, let me know if you need more.
**Docker version:** Docker version 19.03.13, build 4484c46d9d
**Operating system:** Ubuntu 20.04.1 LTS
**Kernel version:** 5.4.0-42-generic
**Network config:**
```
cat /etc/netplan/01-netcfg.yaml
---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: 'no'
      addresses:
      - 192.168.10.11/24
      gateway4: 192.168.10.1
      nameservers:
        addresses:
        - 192.168.10.1
```
**Network card:**
```
lspci | grep -i ethernet
02:00.0 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
02:00.1 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
```

I have also seen this behavior on different hardware with a fresh install of Debian 10.7 with a fresh install of docker, though I don't have detailed specs.

**Comment by Legogris** [comment]
@jescholl this reflects my experience as well.

**Comment by jspdown** [comment]
@jescholl, @Legogris Thanks for your answers. I indeed didn't try between 2 distinct hosts. I will give it a try today.

**Comment by jspdown** [comment]
@jescholl I've been able to reproduce the issue using your docker-compose file with the client and the server on 2 distinct hosts.

**Comment by jspdown** [comment]
I investigated the issue this morning and there doesn't seem to be an easy fix.

The behavior is somewhat expected as the Go net package doesn't let us specify what the source address (of the response) should be. Go relies on the `sendTo` syscall to deliver the response and it does source address selection using the default algorithm (as described in [RFC-6724](https://tools.ietf.org/html/rfc6724)) unless specified by the application. As there's no way to specify the source it just relies on the default algorithm. 

There was an issue talking about this problem on https://github.com/golang/go/issues/17930. 

The `x/net` package provides a way to send and retrieve control messages such as `IP_RECVDSTADDR` or `IP_PKTINFO`:
```
lconn := ipv4.NewPacketConn(conn)
lconn.SetControlMessage(ipv4.FlagDst, true)

n, controlmsg, raddr, err := lconn.ReadFrom(data)
if err != nil {
  return err
}

# Set the desired source
controlmsg.Src = controlmsg.Dst

n, err = l.WriteTo(data, controlmsg, raddr)
if err != nil {
  return err
}
```

But control message types are OS specific and some OS are clearly no supported (e.g windows).

They only workaround I can suggest right now is to add a new route (using iproute) in which you tell that everything leaving the eth0 interface should use your VIP.

**Comment by Legogris** [comment]
@traefiker don't close, still an issue

**Comment by jescholl** [comment]
@jspdown You may have already explored this, but it just occurred to me that Consul is also written in Go and it too has a DNS interface.

As a test I added Consul to the `docker-compose.yaml` file above, and I see the same behavior as the other resolvers.  Both TCP and UDP requests are successful when connecting directly to Consul by the VIP, but only TCP is successful when connecting to Traefik by the VIP.

I'm a Go novice and struggle to follow Consul's code, but it seems Hashicorp has done something to work around the issue you mentioned.

```yaml
# docker-compose.yml

version: "3.3"

services:
  keepalived:
    image: "osixia/keepalived:2.0.20"
    container_name: "keepalived"
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BROADCAST
    environment:
      - KEEPALIVED_UNICAST_PEERS=""
      # The following lines will need to be customized for your environment
      - KEEPALIVED_ROUTER_ID=55
      - KEEPALIVED_VIRTUAL_IPS="192.168.10.16"
      - KEEPALIVED_INTERFACE="eth0"

  traefik:
    image: "traefik:v2.9.4"
    container_name: "traefik"
    network_mode: host
    command:
      # consul entrypoints
      - "--entrypoints.consul-udp.address=:1056/udp"
      - "--entrypoints.consul-tcp.address=:1056/tcp"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

###############
# DNS SERVERS #
###############

consul:
  image: "consul:latest"
  container_name: "consul"
  command:
    - "agent"
    - "-dev"
    - "-client=0.0.0.0"
    - "-recursor=8.8.8.8"
  ports:
    - "2056:8600/udp"
    - "2056:8600/tcp"
  labels:
    - "traefik.enable=true"

    - "traefik.tcp.routers.consul-tcp.rule=HostSNI(`*`)"
    - "traefik.tcp.routers.consul-tcp.entrypoints=consul-tcp"
    - "traefik.tcp.routers.consul-tcp.service=consul-tcp@docker"
    - "traefik.tcp.services.consul-tcp.loadbalancer.server.port=8600"

    - "traefik.udp.routers.consul-udp.entrypoints=consul-udp"
    - "traefik.udp.routers.consul-udp.service=consul-udp@docker"
    - "traefik.udp.services.consul-udp.loadbalancer.server.port=8600"
```

UDP queries through Traefik get responses from the wrong IP
```
# consul
~ › dig +short @192.168.10.16 -p 1056 google.com
;; reply from unexpected source: 192.168.10.11#1056, expected 192.168.10.16#1056
;; reply from unexpected source: 192.168.10.11#1056, expected 192.168.10.16#1056
;; reply from unexpected source: 192.168.10.11#1056, expected 192.168.10.16#1056
;; connection timed out; no servers could be reached
```
TCP queries through Traefik work as expected

```
# consul
~ › dig +short @192.168.10.16 +tcp -p 1056 google.com
142.251.215.238
```

Both UDP and TCP queries direct to Consul work as expected
```
# consul TCP
~ › dig +short @192.168.10.16 +tcp -p 2056 google.com
142.251.215.238

# consul UDP
~ › dig +short @192.168.10.16 -p 2056 google.com
142.251.215.238

```

**Comment by dwydler** [comment]
I had with some services with udp connection the same problem.
Is there anything new here or/and workarounds for this issue?

**Comment by c3pmark** [comment]
I ran into this problem too.  As a workaround, you can bind the UDP entrypoint to a specific IP address so that responses will be generated from that IP:

### Non-working configuration, responds from wrong IP:
```yaml
entrypoints:
  dns:
    address: ":53/udp"
```

### Working configuration, responds from correct IP:
```yaml
entrypoints:
  dns:
    address: "192.168.15.10:53/udp"
```
