### ISSUE TITLE
Failed to request certificate via cloudlflare dnschallenge when there is a dash in the domain name

### ISSUE THREAD

**Issue by gy6221** [traefik/traefik#7437]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Here are the labels i used in the docker-compose.yml for the service:
```
labels:
      - "traefik.enable=true"
      - "traefik.docker.network=nginx-proxy"
      - "traefik.http.routers.portus-registry.rule=Host(`${REGISTRY_MACHINE_FQDN}`)" 
      - "traefik.http.routers.portus-registry.entrypoints=https" 
      - "traefik.http.routers.portus-registry.tls=true" 
      - "traefik.http.routers.portus-registry.tls.certresolver=mycertresolover"

```
I used docker provider to build a proxy for a service. There is a dash sign in the domain name, eg: foo-bar.example.com.
my cert resolver is configured to use dnschallenge via cloudflare api to validate the domain name.

### What did you expect to see?

Traefik can request the certificate successfully.

### What did you see instead?

Certification request was failed, please see the debug log below for detail. 
It is working if I remove the dash from the host name.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.1
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-29T15:49:06Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

CF_API_EMAIL and CF_API_KEY is also configured via environment variable.

```toml
[serversTransport]
  insecureSkipVerify = true
  maxIdleConnsPerHost = 0

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[providers]
  providersThrottleDuration = "2s"
  [providers.docker]
    exposedByDefault = false
  [providers.file]
    directory = "/etc/traefik/rules/"
    watch = true

[api]
  insecure = true
  dashboard = true

[log]
  level = "DEBUG"

[certificatesResolvers]
  [certificatesResolvers.mycertresolver]
    [certificatesResolvers.mycertresolver.acme]
      email = "my@email.com"
      storage = "acme.json"
      [certificatesResolvers.mycertresolver.acme.dnsChallenge]
        provider = "cloudflare"
        delayBeforeCheck = "5s"

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-10-20T18:28:50+08:00" level=debug msg="Try to challenge certificate for domain [foo-bar.example.org] found in HostSNI rule" providerName=mycertresolver.acme routerName=portus-registry@docker rule="Host(`foo-bar.example.org`)"
time="2020-10-20T18:28:50+08:00" level=debug msg="Looking for provided certificate(s) to validate [\"foo-bar.example.org\"]..." providerName=mycertresolver.acme routerName=portus-registry@docker rule="Host(`foo-bar.example.org`)"
time="2020-10-20T18:28:50+08:00" level=debug msg="Domains [\"foo-bar.example.org\"] need ACME certificates generation for domains \"foo-bar.example.org\"." rule="Host(`foo-bar.example.org`)" providerName=mycertresolver.acme routerName=portus-registry@docker
time="2020-10-20T18:28:50+08:00" level=debug msg="Loading ACME certificates [foo-bar.example.org]..." routerName=portus-registry@docker rule="Host(`foo-bar.example.org`)" providerName=mycertresolver.acme
time="2020-10-20T18:28:50+08:00" level=debug msg="legolog: [INFO] [foo-bar.example.org] acme: Obtaining bundled SAN certificate"
time="2020-10-20T18:28:51+08:00" level=debug msg="legolog: [INFO] [foo-bar.example.org] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/8020543400"
time="2020-10-20T18:28:51+08:00" level=debug msg="legolog: [INFO] [foo-bar.example.org] acme: Could not find solver for: tls-alpn-01"
time="2020-10-20T18:28:51+08:00" level=debug msg="legolog: [INFO] [foo-bar.example.org] acme: Could not find solver for: http-01"
time="2020-10-20T18:28:51+08:00" level=debug msg="legolog: [INFO] [foo-bar.example.org] acme: use dns-01 solver"
time="2020-10-20T18:28:51+08:00" level=debug msg="legolog: [INFO] [foo-bar.example.org] acme: Preparing to solve DNS-01"
time="2020-10-20T18:28:51+08:00" level=warning msg="A new release has been found: 2.3.2. Please consider updating."
time="2020-10-20T18:28:51+08:00" level=debug msg="legolog: [INFO] [foo-bar.example.org] acme: Cleaning DNS-01 challenge"
time="2020-10-20T18:28:51+08:00" level=debug msg="legolog: [WARN] [foo-bar.example.org] acme: cleaning up failed: cloudflare: failed to find zone org.: Zone could not be found "
time="2020-10-20T18:28:51+08:00" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/8020543400"
time="2020-10-20T18:28:52+08:00" level=error msg="Unable to obtain ACME certificate for domains \"foo-bar.example.org\": unable to generate a certificate for the domains [foo-bar.example.org]: error: one or more domains had a problem:\n[foo-bar.example.org] [foo-bar.example.org] acme: error presenting token: cloudflare: failed to find zone org.: Zone could not be found\n" routerName=portus-registry@docker rule="Host(`foo-bar.example.org`)" providerName=mycertresolver.acme
```
