### ISSUE TITLE
How to fix "unsafe" error for traefik plugin

### ISSUE THREAD

**Issue by Darkweak** [traefik/traefik#7459]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm trying to write a Træfik plugin

### What did you expect to see?

Everything is ok

### What did you see instead?

Loog error related to unsafe (and third-party libraries too)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v2.3.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
# traefik.yml
api:
  dashboard: true
  insecure: true

pilot:
  token: "XXX-SECRET-XXX"

experimental:
  devPlugin:
    goPath: /plugins/go
    moduleName: github.com/darkweak/souin

log:
  level: DEBUG

accessLog: {}
```
| Type | Value |
|---|---|
|Platform|MacOS and Docker (with and without compose)|
|Arguments|None|

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
2020/10/25 18:38:25 traefik.go:76: command traefik error: github.com/darkweak/souin: failed to import plugin code "github.com/darkweak/souin/plugins/traefik": 1:21: import "github.com/darkweak/souin/plugins/traefik" error: /plugins/go/src/github.com/darkweak/souin/plugins/traefik/main.go:10:2: import "github.com/darkweak/souin/cache/providers" error: /plugins/go/src/github.com/darkweak/souin/cache/providers/ristrettoProvider.go:6:2: import "github.com/dgraph-io/ristretto" error: /plugins/go/src/github.com/darkweak/souin/vendor/github.com/dgraph-io/ristretto/cache.go:29:2: import "github.com/dgraph-io/ristretto/z" error: /plugins/go/src/github.com/darkweak/souin/vendor/github.com/dgraph-io/ristretto/z/bbloom.go:28:2: import "unsafe" error: unable to find source related to: "unsafe"
```
