### ISSUE TITLE
Add plugin extension point for providers

### ISSUE THREAD

**Issue by SantoDE** [traefik/traefik#7461]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Currently, it is possible to extend Traefik with Plugins in the scope of middlewares. As discussed in #7389, we want to eventually open up the system and provide an extensions points for providers as plugins.

Plugin providers could be configured closely to how middleware plugins are configured:

```
experimental:
  plugins:
    denyip:
      modulename = "github.com/mypath/myproviderpluginname"
      version = "v0.1.0"

providers:
  myname:
    plugin:
       providerpluginname:
           foo: "bar"
```

From there, they could be-reused in the same way as normal providers
