### ISSUE TITLE
Forwarding to https backend fails

### ISSUE THREAD

**Issue by Xat59** [traefik/traefik#7462]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am trying to setting traefik to forward request to backend using https protocol.

On my backend service, I have a valid SSL certificate and I'm able to query the service using https. To ensure the problem is not related to the certificate, I also configured traefik with ```serverstransport.insecureskipverify=true```.

Traefik documentation says there are 3 ways to configure Traefik to use https to communicate with pods:
- If the service port defined in the ingress spec is 443 (note that you can still use targetPort to use a different port on your pod).
- If the service port defined in the ingress spec has a name that starts with https (such as https-api, https-web or just https).
- If the ingress spec includes the annotation ```traefik.ingress.kubernetes.io/service.serversscheme: https```.

In my case, I'm trying to forward to https backend using the 3rd way : If the ingress spec includes the annotation ```traefik.ingress.kubernetes.io/service.serversscheme: https``` .

First, I do not have ingress resource for traefik, only ingressroute. So I tried to set the annotation on the ingress route, but it does not forward to backend using https.

Plus, I can see in this issue that the annotation must be set on the service resource (not on ingress such as the documentation says), so it make me confused : https://github.com/traefik/traefik/issues/6725#issuecomment-618910667 . 
I also tried to set the annotation on the service side, but it does not work.

I also tried to set the annotation on service and ingressroute, but same behavior : it does not forward to backend using https.

### What did you expect to see?

Traefik forwards requests to service backend using https protocol.

### What did you see instead?

Traefik forwards request to service backend using http protocol. So it does not work because the backend only uses https.

### Output of `traefik version`: (_What version of Traefik are you using?_)

traefik version : ```Traefik version 2.1.1```
image version : ```traefik:v2.1.1```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

***kubectl version***
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"3a3612132641768edd7f7e73d07772225817f630", GitTreeState:"clean", BuildDate:"2020-09-02T06:46:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

***kubernetes cluster*** : AKS 

***traefik arguments***
```
--log.level=DEBUG
--providers.kubernetescrd
--entrypoints.web.address=:80
--entrypoints.websecure.address=:443
--api.insecure
--serverstransport.insecureskipverify=true
```

***traefik k8s resources***
```
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: elastic-system
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: elastick8s
    traefik.ingress.kubernetes.io/service.serversscheme: https
spec:
  type: LoadBalancer
  loadBalancerIP: X.X.X.X
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  - port: 8080
    targetPort: 8080
    name: api
  - port: 443
    targetPort: 443
    name: websecure
  - port: 80
    targetPort: 80
    name: web
...
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https-kibana
  namespace: elastic-system
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`kibana.example.io`) && PathPrefix(`/`)
    services:
    - name: kibana
      port: 5601
  tls:
    secretName: elastic-certificates
...
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https-elasticsearch
  namespace: elastic-system
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`es.example.io`) && PathPrefix(`/`)
    services:
    - name: elasticsearch-master
      port: 9200
  tls:
    secretName: elastic-certificates
...
```

***traefik logs***
```
time="2020-10-23T16:54:33Z" level=debug msg="Creating load-balancer" entryPointName=websecure routerName=elastic-system-https-kibana-c370b7746f3f7ce84513@kubernetescrd serviceName=elastic-system-https-kibana-c370b7746f3f7ce84513                                                                                        
time="2020-10-23T16:54:33Z" level=debug msg="Creating server 0 http://10.2.0.24:5601" routerName=elastic-system-https-kibana-c370b7746f3f7ce84513@kubernetescr
d serviceName=elastic-system-https-kibana-c370b7746f3f7ce84513 serverName=0 entryPointName=websecure 

time="2020-10-23T16:54:33Z" level=debug msg="Creating load-balancer" serviceName=elastic-system-https-elasticsearch-d73cc805544db6911021 entryPointName=websec
ure routerName=elastic-system-https-elasticsearch-d73cc805544db6911021@kubernetescrd                                                                          time="2020-10-23T16:54:33Z" level=debug msg="Creating server 0 http://10.2.0.39:9200" serverName=0 entryPointName=websecure routerName=elastic-system-https-elasticsearch-d73cc805544db6911021@kubernetescrd serviceName=elastic-system-https-elasticsearch-d73cc805544db6911021                                            time="2020-10-23T16:54:33Z" level=debug msg="Creating server 1 http://10.2.0.8:9200" serverName=1 entryPointName=websecure routerName=elastic-system-https-elasticsearch-d73cc805544db6911021@kubernetescrd serviceName=elastic-system-https-elasticsearch-d73cc805544db6911021                                             time="2020-10-23T16:54:33Z" level=debug msg="Creating server 2 http://10.2.0.89:9200" routerName=elastic-system-https-elasticsearch-d73cc805544db6911021@kuber
netescrd serverName=2 serviceName=elastic-system-https-elasticsearch-d73cc805544db6911021 entryPointName=websecure
```

As you can see, it creates backend using http protocol.

***traefik logs when I query configured ingress routes***

```
curl -k -L https://kibana.example.io/
Bad Gateway

# traefik logs for that request
time="2020-10-23T17:02:51Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.69.1\"],\"X-Forwarded-Host\":[\"kibana.example.io\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"aks-agentpool-35064155-vmss000002\"],\"X-Real-Ip\":[\"X.X.X.X\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"kibana.example.io\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"X.X.X.X:36258\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2020-10-23T17:02:51Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.69.1\"],\"X-Forwarded-Host\":[\"kibana.example.io\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"aks-agentpool-35064155-vmss000002\"],\"X-Real-Ip\":[\"X.X.X.X\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"kibana.example.io\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"X.X.X.X:36258\",\"RequestURI\":\"/\",\"TLS\":null}" ForwardURL="http://10.2.0.24:5601"
time="2020-10-23T17:02:51Z" level=debug msg="'502 Bad Gateway' caused by: EOF"
time="2020-10-23T17:02:51Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.69.1\"],\"X-Forwarded-Host\":[\"kibana.example.io\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"aks-agentpool-35064155-vmss000002\"],\"X-Real-Ip\":[\"X.X.X.X\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"kibana.example.io\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"X.X.X.X:36258\",\"RequestURI\":\"/\",\"TLS\":null}"
```

**Comment by jbdoumenjou** [comment]
Hi @Xat59,

Thanks for your interest in Traefik.

At first look, it seems you are mixing two providers: [Ingress](https://doc.traefik.io/traefik/v2.3/providers/kubernetes-ingress/) and [IngressRoute](https://doc.traefik.io/traefik/v2.3/providers/kubernetes-crd/). 
If you want to use IngressRoute, the dynamic configuration is explained [here](https://doc.traefik.io/traefik/v2.3/routing/providers/kubernetes-crd/) and don't use the annotation.
If you want to use the Ingress, the dynamic configuration is explained [here](https://doc.traefik.io/traefik/v2.3/routing/providers/kubernetes-ingress/).

So, for the IngressRoute provider it could be something like that:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https-kibana
  namespace: elastic-system
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`kibana.example.io`) && PathPrefix(`/`)
    services:
    - name: kibana
      port: 5601
      scheme: https # <-
  tls:
    secretName: elastic-certificates
```

As a side note, a good practice is to use the latest stable version wich is the `v2.3.2`

Let me know if it answers your question.
