### ISSUE TITLE
ConfigReloadsFailureCounter metric does not increment on config reload failures

### ISSUE THREAD

**Issue by pbarsotti-glovo** [traefik/traefik#7471]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I introduced deliberately an error in the dynamic config load sequence (404 response to the HTTP provider).

### What did you expect to see?

I expected to see an increment in the metric `ConfigReloadsFailureCounter`. In this particular case I'm using DataDog so the metric should be `config.reload.total` with the tag `failure: true`. 

### What did you see instead?

I did not see the metric mentioned above with the tag `failure: true`.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.1
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-29T15:49:06Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
entryPoints:
  Main:
    address: ":8888"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 42
        graceTimeOut: 42
      respondingTimeouts:
        readTimeout: 42
        writeTimeout: 42
        idleTimeout: 42
providers:
  http:
    endpoint: "http://127.0.0.1:8000/dynamic-config.yaml"

log:
  level: INFO
tracing:
  datadog: {}
metrics:
  datadog: {}

ping:
  entryPoint: "Main"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
N/A
```
