### ISSUE TITLE
Group routes by hostname

### ISSUE THREAD

**Issue by WLun001** [traefik/traefik#7476]
Feature
Group routes by by hostname

This is currently support
```yaml
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.example.com`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: zone-printer-service
          port: 80
    - match: Host(`traefik.example.com`) && PathPrefix(`/whoami`)
      kind: Rule
      services:
        - name: whoami
          port: 80
    - match: Host(`traefik.example.com`) && PathPrefix(`/zone`)
      kind: Rule
      services:
        - name: zone-printer-service
          port: 80
    - match: Host(`traefik.example.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
```
### What did you expect to see?
Possible to achieve with this?
```yaml
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.example.com`) # avoid code duplicate like Host(`traefik.example.com`) && 
      routes:
        - match: PathPrefix(`/`)
           kind: Rule
           services:
           - name: zone-printer-service
              port: 80
        - match:  PathPrefix(`/whoami`)
           kind: Rule
           services:
             - name: whoami
                port: 80
          - match: PathPrefix(`/zone`)
             kind: Rule
             services:
               - name: zone-printer-service
                 port: 80
          - match: (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
             kind: Rule
             services:
               - name: api@internal
                kind: TraefikService
```
