### ISSUE TITLE
kubectl watch (streaming request) to kube-apiserver stays open indefinitely

### ISSUE THREAD

**Issue by dlipovetsky** [traefik/traefik#7489]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

1.  Deploy traefik 1.7.24 and create an Ingress for kube-apiserver

    ```yaml
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
    annotations:
        ingress.kubernetes.io/protocol: https
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    name: kubernetes
    namespace: default
    spec:
    rules:
    - http:
        paths:
        - backend:
            serviceName: kubernetes
            servicePort: https
            path: /
    ```

1.  Configure my local kubeconfig `kubectl` to use the Ingress

1.  Create a Kubernetes deployment and monitor its status

    ```shell
    kubectl create deployment nginx --image=nginx && kubectl rollout status deploy nginx
    ```

    Both commands terminate:

    ```shell
    deployment.apps/nginx created
    Waiting for deployment "nginx" rollout to finish: 0 of 1 updated replicas are available...
    deployment "nginx" successfully rolled out
    ```

1.  Now, monitor the deployment status again

    ```shell
    kubectl rollout status deploy nginx
    ```

    The command writes

    ```shell
    deployment "nginx" successfully rolled out
    ```

    But the command does not terminate until either:
    (a) the connection is closed (e.g. if the request goes through a load balancer, and it closes the connection when the idle timeout is reached), or
    (b) the Deployment resource is updated, or deleted.

    If I configure `kubectl` to talk directly to `kube-apiserver`, i.e., not via the Ingress, then this same command *does* terminate, almost immediately.

    My theory for the different behavior is that the `rollout status` command creates a watch, which kube-apiserver creates using the SPDY protocol. Support for this was added in #6553 (included in release [v1.7.23](https://github.com/traefik/traefik/releases/tag/v1.7.23)), and works by using HTTP/1.1. But the original request is a GET request, for which the HTTP/1.1 pipelining implementation (#3513) does not implement the `CloseNotify()` method, as is the recommendation, per the [net/http](https://github.com/golang/go/commit/99fb19194c03c618c0d8faa87b91ba419ae28ee3) library. For reference, that recommendation merged in [this commit](https://github.com/golang/go/commit/99fb19194c03c618c0d8faa87b91ba419ae28ee3), which has more context in its commit message.

    The theory is mostly based on the debug message that traefik logs just after receiving the request.

### What did you expect to see?

When talking to `kube-apiserver` via traefik, I expected the `kubectl rollout status deploy nginx` command to terminate.

### What did you see instead?

The command does not terminate (please see above).

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.24
Codename:     maroilles
Go version:   go1.14.1
Built:        2020-03-25_04:34:11PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik.toml
logLevel = "debug"
InsecureSkipVerify = true
defaultEntryPoints = ["http","https"]
[entryPoints]
    [entryPoints.http]
    address = ":80"
    compress = true
    [entryPoints.http.redirect]
        regex = "^http://(.*)"
        replacement = "https://$1"
    [entryPoints.https]
    address = ":443"
    compress = true
    [entryPoints.https.tls]
        [entryPoints.https.tls.defaultCertificate]
        CertFile = "/ssl/tls.crt"
        KeyFile = "/ssl/tls.key"
    [entryPoints.traefik]
    address = ":8080"
    [entryPoints.velero-minio]
    address = ":9000"
    compress = true
    [entryPoints.velero-minio.tls]
    [entryPoints.velero-minio.tls.defaultCertificate]
    certFile = "/ssl/tls.crt"
    keyFile = "/ssl/tls.key"
    [entryPoints.prometheus]
    address = ":9100"
[ping]
entryPoint = "http"
[kubernetes]
    [kubernetes.ingressEndpoint]
    publishedService = "kubeaddons/traefik-kubeaddons"
[traefikLog]
    format = "json"
[accessLog]
    format = "common"
[accessLog.fields]
    defaultMode = "keep"
[accessLog.fields.names]
[accessLog.fields.headers]
    defaultMode = "keep"
[accessLog.fields.headers.names]
[api]
    entryPoint = "traefik"
    dashboard = true
[metrics]
    [metrics.prometheus]
    entryPoint = "prometheus"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
{"Request":"{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"https\",\"Opaque\":\"\",\"User\":null,\"Host\":\"10.0.193.235:6443\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"application/json\"],\"Accept-Encoding\":[\"gzip\"],\"Authorization\":[\"Bearer REDACTED\"],\"User-Agent\":[\"kubectl/v1.18.9 (linux/amd64) kubernetes/94f372e\"],\"X-Forwarded-Prefix\":[\"/\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"REDACTED\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.0.129.78:35174\",\"RequestURI\":\"/apis/apps/v1/namespaces/kubeaddons/deployments?allowWatchBookmarks=true\\u0026fieldSelector=metadata.name%3Dkubernetes-dashboard\\u0026resourceVersion=72202\\u0026timeoutSeconds=483\\u0026watch=true\",\"TLS\":null}","level":"debug","msg":"vulcand/oxy/forward/http: begin ServeHttp on request","time":"2020-10-28T21:35:01Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2020-10-28T21:35:01Z"}
```
