### ISSUE TITLE
Traefik Pilot, Duplicate proxies and Request Duration only

### ISSUE THREAD

**Issue by wahmedswl** [traefik/traefik#7492]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Integrated with Pilot via ```Connect with Traefik Pilot```

### What did you expect to see?

Integration was succesful and everything seems nice. Integrated to get basic metrics eg: RPS etc but once i enabled it, it shows 2 proxies per Instance and on restart, it doubles up. Also, only Request Duration was showing up no other metric.

### What did you see instead?

There should be only single proxy created and every metrics should work.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.2
Codename:     picodon
Go version:   go1.15.3
Built:        2020-10-19T18:36:22Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[entryPoints]
  [entryPoints.http]
    address = ":12345"
  [entryPoints.traefik]
    address = ":9090"
	
[log]
  filePath = "/home/gitlab/ArtifactService/traefik/logs/traefik.log"
  format = "json"

[api]
  dashboard = true
  insecure = true

[ping]

[pilot]
    token = "xxx"

[providers]
  [providers.file]
    directory = "/home/gitlab/ArtifactService/traefik/conf"
    watch = true
```

![Traefik-Pilot-Issue-Screenshot1](https://user-images.githubusercontent.com/15020561/97749136-5a19d080-1b10-11eb-8eff-00d929942e34.png)
![Traefik-Pilot-Issue-Screenshot2](https://user-images.githubusercontent.com/15020561/97749140-5b4afd80-1b10-11eb-901a-ab1a80292be9.png)
![Traefik-Pilot-Issue-Screenshot3](https://user-images.githubusercontent.com/15020561/97749142-5be39400-1b10-11eb-9672-38f9267f335e.png)
