### ISSUE TITLE
Using TLS-Storage when CertProvider should be used

### ISSUE THREAD

**Issue by aendeavor** [traefik/traefik#7493]
### Do you want to request a *feature* or report a *bug*?

**Bug**

### What did you do?

I am runnig Traefik in Docker Swarm. When I started out, I used wildcard certificates from Let'sEncrypt. This certificate is still being deployed, but only to one service now. There reason being Cloudflare offering so-called Origin Certificates. I'm using these Origin Certificates, but (obviously), they are not usable with mail servers, and I am running one.

Therefore, I use a webmailer (RoundCube) which provides a webinterface, and `docker-mailserver` as the actual mail server. The situation now is actually simple: The webmailer request a certificate (via Traefik) from Let'sEncrypt. I want this certificate to **now be** `mail.<DOMAIN>.com` (whereas previously it was a wildcard cert: `main: <DOMAIN>.com   sans: *.<DOMAIN>.com`). The `acme.json` is then mounted into the mail server and everything should be fine.

The Origin Certificates from Cloudflare are valid for `main: <DOMAIN>.com   sans: *.<DOMAIN>.com` like the original Let'sEncrypt certificates. The TLSStore holds these certificates (as can be seen below in the dynamic configuration).

### What did you expect to see?

When _Traefik_ starts and the webmailer too, I expected Traefik to pull a certificate for `mail.<DOMAIN>.com` via the certresolver (called `lcdns`). 

### What did you see instead?

Actually, **my best guess is** that _Traefik_ uses the TLS-Storage, i.e. the certificates from Cloudflare. Therefore, it comes to the conclusion that no certificate generation is required. These are the logs (captured in `loglevel: debug`):

``` LOG
Try to challenge certificate for domain [mail.<DOMAIN>.com] found in HostSNI rule" providerName=lcdns.acme routerName=webmailer@docker rule="Host(`mail.<DOMAIN>.com`)

Looking for provided certificate(s) to validate [\"mail.<DOMAIN>.com\"]..." rule="Host(`mail.<DOMAIN>.com`)" providerName=lcdns.acme routerName=webmailer@docker

No ACME certificate generation required for domains [\"mail.<DOMAIN>.com\"]." providerName=lcdns.acme routerName=webmailer@docker rule="Host(`mail.<DOMAIN>.com`)
```

Is this expected behavior? How could I resolve this?

### Output of `traefik version`:

```
Version:      2.3.2
Codename:     picodon
Go version:   go1.15.3
Built:        2020-10-19T18:36:22Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

``` YAML
# static configuration
...
certificatesResolvers:  # <-- ISSUES CERTIFICATES FROM LETSENCRYPT
  lcdns:
    acme:
      email: "some-mail@<DOMAIN>.com"
      storage: /etc/traefik/acme.json
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: "cloudflare"
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

# stack file
traefik:
    image: traefik:v2.3.2
    ports:
      - "80:80"
      - "443:443"
    environment: # <-- SETTINGS UP A DNS-01 CHALLANGE
      - CLOUDFLARE_EMAIL=some-mail@<DOMAIN>.com
      - CLOUDFLARE_DNS_API_TOKEN=<REDACTED>
      - CLOUDFLARE_ZONE_API_TOKEN=<REDACTED>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro
      - ./public.pem:/etc/traefik/public.pem:ro
      - ./private.pem:/etc/traefik/private.pem:ro
      - ./acme.json:/etc/traefik/acme.json
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 15s
      placement:
        constraints:
          - node.role == manager
          - node.platform.os == linux
...

# dynamic configuration
...
tls:
  options:
    modern:
      minVersion: VersionTLS13
      sniStrict: true
      curvePreferences:
        - secp521r1
        - secp384r1
        - secp256r1
        - x25519
  
  certificates: # <-- VALID FOR <DOMAIN>.com and *.<DOMAIN>.com
    - certFile: /etc/traefik/public.pem     # <-- THESE ARE THE CLOUDFLARE ORIGIN CERTIFICATES
      keyFile: /etc/traefik/private.pem     # <-- THESE ARE THE CLOUDFLARE ORIGIN CERTIFICATES

# the actual mail-stack.yaml
version: '3.8'

services:

  server:
    image: tvial/docker-mailserver:stable
    ... # (unimportant)

  web:
    image: roundcube/roundcubemail:latest
    environment:
      ...
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 15s
      labels:
        - traefik.enable=true
        # ? Router
        - traefik.http.routers.webmailer.rule=Host(`mail.<DOMAIN>.com`)
        - traefik.http.routers.webmailer.entrypoints=https
        # ? TLS
        - traefik.http.routers.webmailer.tls=true
        - traefik.http.routers.webmailer.tls.options=modern@file
        - traefik.http.routers.webmailer.tls.certresolver=lcdns
        # - traefik.http.routers.webmailer.tls.domains[0].main=<DOMAIN>.com   # <-- This was used in the past
        # - traefik.http.routers.webmailer.tls.domains[0].sans=*.<DOMAIN>.com # <-- This was used in the past
        # ? Service
        - traefik.http.services.webmailer.loadbalancer.server.port=80

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
Try to challenge certificate for domain [mail.<DOMAIN>.com] found in HostSNI rule" providerName=lcdns.acme routerName=webmailer@docker rule="Host(`mail.<DOMAIN>.com`)

Looking for provided certificate(s) to validate [\"mail.<DOMAIN>.com\"]..." rule="Host(`mail.<DOMAIN>.com`)" providerName=lcdns.acme routerName=webmailer@docker

No ACME certificate generation required for domains [\"mail.<DOMAIN>.com\"]." providerName=lcdns.acme routerName=webmailer@docker rule="Host(`mail.<DOMAIN>.com`)
```
