### ISSUE TITLE
frp + traefik tcp routers

### ISSUE THREAD

**Issue by tentree** [traefik/traefik#7496]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

i want publish frp with docker, i want use only one port but diff dns to router to diff tcp port.

frp docker-compose.yml
```
version: '3'
services:

  frps:
    restart: always
    container_name: frps
    image: fatedier/frps:v0.34.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./frps.ini:/app/frps.ini:ro
    command: frps -c /app/frps.ini
    expose:
      - 9870
      - 7890
    environment:
      - FRP_SERVER_PORT=9870
      - FRP_SERVER_TOKEN=xxxxx
      - FRP_ADMIN_PORT=7890
      - FRP_ADMIN_USER=xxx
      - FRP_ADMIN_PASS=xxx
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      - "traefik.http.routers.frpspage.middlewares=https-redirect@file"
      - "traefik.http.routers.frpspage.entrypoints=http"
      - "traefik.http.routers.frpspage.rule=Host(`frp.xxx.xxx`)"

      - "traefik.http.routers.frpsssl.rule=Host(`frp.xxx.xxx`)"
      - "traefik.http.routers.frpsssl.entrypoints=https"
      - "traefik.http.routers.frpsssl.tls=true"

      - "traefik.tcp.routers.frpssh.rule=HostSNI(`frp.xxx.xxx`)"
      - "traefik.tcp.routers.frpssh.entrypoints=tcp"
      - "traefik.tcp.routers.frpssh.tls=true"
      - "traefik.tcp.routers.frpssh.tls.passthrough=true"
      - "traefik.tcp.routers.frpssh.service=frpserver"

      - "traefik.tcp.services.frpserver.loadbalancer.server.port=9870"

    networks:
      - frps
      - traefik
    logging:
        driver: "json-file"
        options:
          max-size: "1m"

# docker network create frps
networks:
  frps:
  traefik:
    external: true
```

traefik docker-compose

```
version: '3'

services:
  traefik:
    container_name: traefik
    image: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "5200:5200"
    networks:
      - traefik
    command: traefik --configFile /etc/traefik.toml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/data/logs
      - ./ssl/:/data/ssl
      - ./traefik.toml:/etc/traefik.toml
      - ./config:/etc/traefik/config
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy off localhost:8080/ping || exit 1"]
      interval: 3s
      timeout: 5s
networks:
  traefik:
    external: true
```

traefik.toml
```
[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[log]
  level = "INFO"
  format = "common"
  filePath = "/data/logs/traefik.log"

[api]
  dashboard = true
  insecure = true

[ping]

[accessLog]
  filePath = "/data/logs/access.log"
  format = "common"

[providers]
  [providers.docker]
    watch = true
    exposedByDefault = false
    endpoint = "unix:///var/run/docker.sock"
    swarmMode = false
    useBindPortIP = false
    network = "traefik"
  [providers.file]
    watch = true
    directory = "/etc/traefik/config"
    debugLogGeneratedTemplate = true

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
  [entryPoints.tcp]
    address = ":5200"
```

frpc.ini 
```
[common]
server_addr = frp.xxx.xxx
server_port = 5200
token = xxx
tls_enable = true
```

in traefik dashboard, it seem like work well, but when i run frpc, it can not  connet well
![image](https://user-images.githubusercontent.com/46660079/97839973-31672600-1d1e-11eb-8382-68ab2e03dbb3.png)

### What did you expect to see?

frpc can connect well 

### What did you see instead?
```
2020/11/02 14:57:13 [W] [service.go:102] login to server failed: tls: first record does not look like a TLS handshake
```
or
```
2020/11/02 14:57:14 [W] [service.go:102] login to server failed: session shutdown
session shutdown
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
root@VM-0-10-ubuntu:~# docker exec traefik traefik version
Version:      2.3.2
Codename:     picodon
Go version:   go1.15.3
Built:        2020-10-19T18:36:22Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[log]
  level = "INFO"
  format = "common"
  filePath = "/data/logs/traefik.log"

[api]
  dashboard = true
  insecure = true

[ping]

[accessLog]
  filePath = "/data/logs/access.log"
  format = "common"

[providers]
  [providers.docker]
    watch = true
    exposedByDefault = false
    endpoint = "unix:///var/run/docker.sock"
    swarmMode = false
    useBindPortIP = false
    network = "traefik"
  [providers.file]
    watch = true
    directory = "/etc/traefik/config"
    debugLogGeneratedTemplate = true

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
  [entryPoints.tcp]
    address = ":5200"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
