### ISSUE TITLE
Kubernetes Ingress PathPrefix service name with dash duplicate

### ISSUE THREAD

**Issue by seuf** [traefik/traefik#7497]
### What did you do?

Declare a kubernetes Ingress resource with 2 rules with different names but almost the sames :

```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: strip@file # middleware stripPrefixRegex with regex ["/"]
  name: whoami
  namespace: traefik
spec:
  rules:
  - host: domain.com
    http:
      paths:
      - backend:
          serviceName: whoami
          servicePort: web
        path: /whoami/test
  - host: domain.com
    http:
      paths:
      - backend:
          serviceName: whoami
          servicePort: web
        path: /whoami-test
  tls:
    - secretName: traefik-default-cert
```

### What did you expect to see?

I Can access both path `/whoami-test` and `/whoami/test`

### What did you see instead?

Only `/whoami-test` is working
If I change the order of the rules in the ingress configuration the last one is working (/whoami/test) but not the first one.
I think it's an issue with the generated name of the traefik router :
Both ingress rules have the same router name : `websecure-whoami-traefik-traefik-domain-com-whoami-test`

### Output of `traefik version`: 

```
image: traefik:2.2.7
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[providers]
  [providers.kubernetesIngress]
  [providers.kubernetesIngress.ingressEndpoint]
      publishedService = "traefik/traefik-ingress-service"
  [providers.file]
    directory = "/config"
    watch = true
```

**Comment by jorge07** [comment]
Coming from #7510, it's affected too I expose router name labels so it's affected and change it after release this could generate a very important breaking change and leave empty tons of charts as routerName/serviceName changed.

**Comment by SamuelTechwolf** [comment]
We are experiencing the same problem in our setup where we grouped a wildcard path and it's subdomain together. In seperate ingresses, this works, but when thrown together, only a single router is made, and one of the two, depending on statement order, is inaccessible:
`spec:
  ingressClassName: <traefik-class>
  rules:
  - host: '*.domain.com'
    http:
      paths:
      - backend:
          serviceName: <service>
          servicePort: <port>
        path: /
        pathType: ImplementationSpecific
  - host: domain.com
    http:
      paths:
      - backend:
          serviceName: <service>
          servicePort: <port>
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - '*.domain.com'
    - domain
    secretName: <name>-cert`

**Comment by jorge07** [comment]
It's an option consider things like `*` of `/` as exceptions in https://github.com/traefik/traefik/blob/master/pkg/provider/configuration.go#L350?

I did a PoC in local and I've the results I want but with 2 problems:
- I don't cover all use cases
- Breaks tons of tests and generate a **very very important breaking change**

**Comment by jspdown** [comment]
Hello @seuf and thanks for reporting this bug. I have been able to reproduce consistently the issue. 

As spotted, the issue comes from the router key:

https://github.com/traefik/traefik/blob/64a65cadf3420734a578b0b02717d349be99fd53/pkg/provider/kubernetes/ingress/kubernetes.go#L276

**Comment by avdhoot** [comment]
We trying to migrate from traefik 1.7.24 to 2.3 We are facing similar issue. In 1.7.24 things work well. but in 2.3 traefik ignore host with wild card. It will be great if we get fix in traefik 2.4 as it is breaking change. 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: k8s-service
  namespace: my-path
spec:
  rules:
  - host: '*.somthing.svc.foo.bar'
    http:
      paths:
      - backend:
          serviceName: k8s-service-app
          servicePort: 8000
        path: /my-path
      - backend:
          serviceName: k8s-service-app
          servicePort: 8000
        path: /api
  - host: '*.somthing.api.foo.bar'
    http:
      paths:
      - backend:
          serviceName: k8s-service-app
          servicePort: 8000
        path: /my-path
      - backend:
          serviceName: k8s-service-app
          servicePort: 8000
        path: /api
  - host: somthing.svc.foo.bar
    http:
      paths:
      - backend:
          serviceName: k8s-service-app
          servicePort: 8000
        path: /my-path
      - backend:
          serviceName: k8s-service-app
          servicePort: 8000
        path: /api
  - host: somthing.api.foo.bar
    http:
      paths:
      - backend:
          serviceName: k8s-service-app
          servicePort: 8000
        path: /my-path
      - backend:
          serviceName: k8s-service-app
          servicePort: 8000
        path: /api

```
