### ISSUE TITLE
Persistent path redirect from addprefix middleware

### ISSUE THREAD

**Issue by linareyne** [traefik/traefik#7498]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
Used `addprefix` middleware to add a path prefix... took a little messing with it to get it work, and I somehow ended up with a redirect that I can't get rid of.

### What did you expect to see?
My service has an interface at path `/public/stream` that I'd like to expose through traefik at `foo.mysite.com`. I'm using the following labels on the container:

```
- "traefik.http.middlewares.foo-addprefix.addprefix.prefix=/public/stream"
- "traefik.http.routers.foo.middlewares=foo-addprefix@docker"
```

### What did you see instead?
I can now see that it's working because an interface available at path `/public/stream/bar` is now available at `foo.mysite.com/bar`. But I'm getting redirected from `foo.mysite.com` to `foo.mysite.com/public/stream`, which is returning a  404 because the `addprefix` middleware is then making the path `foo.mysite.com/public/stream/public/stream`. If I comment out the `addprefix` labels, it redirects and resolves to `foo.mysite.com/public/stream`, and I can see that the interface is correctly being served by traefik (along with the previously mentioned interface at `foo.mysite.com/public/stream/bar`).

The redirect seems to somehow have occurred while figuring out the addprefix feature, and it's now happening even with those labels commented out or with the path changed - still redirecting `foo.mysite.com` to `foo.mysite.com/public/stream` specifically.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.2
Codename:     picodon
Go version:   go1.15.3
Built:        2020-10-19T18:36:22Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Ubuntu 20.04.1 on an NUC8, official Traefik docker image.  No toml.

```yml
# Azuracast nginx container being served by traefik
labels:
      - "traefik.enable=true"
      - "traefik.http.routers.foo.rule=Host(`foo.mysite.com`)"
      - "traefik.http.routers.foo.entrypoints=websecure"
      - "traefik.http.routers.foo.tls.certresolver=myresolver"
      - "traefik.http.middlewares.foo-addprefix.addprefix.prefix=/public/stream"
      - "traefik.http.routers.fresh.middlewares=foo-addprefix@docker"
networks: 
      - frontend

# Traefik config
traefik:
    image: traefik
    container_name: traefik
    networks: 
      - frontend
    environment:
      - CF_API_EMAIL=[email]
      - CF_API_KEY=[secret]
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=[email]"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always

networks:
    frontend:
      external: true
      driver: bridge
```
