### ISSUE TITLE
IngressRoute validation during kubectl apply

### ISSUE THREAD

**Issue by WLun001** [traefik/traefik#7499]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
For example i have the following IngressRoute
```yaml
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/whoami` # here is missing closing bracket
      kind: Rule
      services:
        - name: whoami
          port: 80
```

And after i `kubectl apply` it doesn't throw any error. Only when i found out the route is not working and read the log from deployment, to know the actual error
```bash
kubectl logs -f deployment/traefik -n traefik
```

Possible to have validation during `kubectl apply`? Or it is related or can be done with https://github.com/traefik/traefik/issues/5473?
