### ISSUE TITLE
Error parsing config file traefik.toml: field not found, node: middlewares

### ISSUE THREAD

**Issue by o1dnik** [traefik/traefik#7502]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Not sure. Something what I definitely didn't expect to break my traefik configuration on local machine. Here's the list of possible reasons (a guess):

 - upgraded traefik via Homebrew on Mac to latest stable version 2.3.2
 - re-generated certificate to use for local web app development with mkcert or openssl, self-signed, with rootCA crt and key ( I tested several variants here )
 - restarted traefik via brew services
 - upgraded Chrome, FireFox and Safari versions since last use of local web app in development environment
 - upgraded version of Xcode to latest

### What did you expect to see?

Starting a development app on localhost should be loaded with correct certificate on local machine so that I could load a dev.something.com on localhost and debug new changes in development env quickly.

### What did you see instead?

tail -10 /usr/local/var/log/traefik.log  shows following:

```bash
time="2020-11-03T14:58:40+01:00" level=error msg="accept tcp [::]:15772: use of closed network connection" entryPointName=api
time="2020-11-03T14:58:40+01:00" level=error msg="Error while starting server: http: Server closed" entryPointName=https
time="2020-11-03T14:58:40+01:00" level=error msg="Error while starting server: http: Server closed" entryPointName=api
time="2020-11-03T14:58:40+01:00" level=error msg="Error while starting server: http: Server closed" entryPointName=api
time="2020-11-03T14:58:41+01:00" level=error msg="close tcp [::]:443: use of closed network connection" entryPointName=https
time="2020-11-03T14:58:41+01:00" level=error msg="close tcp [::]:15772: use of closed network connection" entryPointName=api
time="2020-11-03T14:58:41+01:00" level=error msg="close tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2020-11-03T14:58:41+01:00" level=error msg="close tcp [::]:80: use of closed network connection" entryPointName=http
time="2020-11-03T14:58:46+01:00" level=info msg="Configuration loaded from file: /Users/username/.config/traefik.toml"
time="2020-11-03T14:58:46+01:00" level=error msg="Cannot start the provider *file.Provider: /Users/username/.config/traefik.toml: field not found, node: middlewares"
```

### Output of `traefik version`:

```bash
Version:      2.3.2
Codename:     cheddar
Go version:   go1.15.3
Built:        I don't remember exactly
OS/Arch:      darwin/amd64
```

### What is your environment & configuration

I removed `TRAEFIK_PROVIDERS_HTTP_TLS_CERT` and `TRAEFIK_PROVIDERS_HTTP_TLS_KEY` from ~/.zshrc so that there's no overlapping.

This file is located in /Users/username/.config/traefik.toml with the correct "username". "domainname" is also a replacement for the actual domain name.

```toml
[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[serversTransport]
  insecureSkipVerify = true
  maxIdleConnsPerHost = 200
  rootCAs = ["/Users/username/certs/myCA.crt"]

[entryPoints]
  [entryPoints.api]
    address = ":15772"
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.proxyProtocol]
      insecure = true
      trustedIPs = ["0.0.0.0/0"]
    [entryPoints.http.forwardedHeaders]
      trustedIPs = ["0.0.0.0/0"]
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.proxyProtocol]
      insecure = true
      trustedIPs = ["0.0.0.0/0"]
    [entryPoints.https.forwardedHeaders]
      trustedIPs = ["0.0.0.0/0"]

[providers]
  providersThrottleDuration = "2s"
  [providers.file]
    directory = "/Users/username/.config/"
    filename = "traefik.toml"
    watch = true

[api]
  insecure = true
  dashboard = true
  debug = true

[log]

[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/Users/username/certs/local.domainname.com.crt"
      keyFile  = "/Users/username/certs/local.domainname.com.key"

[[tls.certificates]]
  certFile = "/Users/username/certs/local.domainname.com.crt"
  keyFile  = "/Users/username/certs/local.domainname.com.key"

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS13"

[http.middlewares]
  [http.middlewares.compress.compress]
  [http.middlewares.redirectscheme.redirectScheme]
    scheme = "https"
    permanent = true

[http.routers]
  [http.routers.rabbitmq-http]
    service = "rabbitmq"
    rule = "Host(`rabbitmq.admin.localhost`)"
    middlewares = ["redirect"]

  [http.routers.rabbitmq-https]
    service = "rabbitmq"
    rule = "Host(`rabbitmq.admin.localhost`)"
    [http.routers.rabbitmq-https.tls]
    middlewares = ["compress"]

  [http.routers.traefik-http]
    service = "api@internal"
    rule = "Host(`traefik.admin.localhost`)"
    middlewares = ["redirect"]

  [http.routers.traefik-https]
    service = "api@internal"
    rule = "Host(`traefik.admin.localhost`)"
    [http.routers.traefik-https.tls]
    middlewares = ["compress"]

  [http.routers.k8s-http]
    service = "k8s"
    priority = 1
    rule = "HostRegexp(`catchall:.*`)"
    middlewares = ["redirect"]

  [http.routers.k8s-https]
    service = "k8s"
    priority = 1
    rule = "HostRegexp(`catchall:.*`)"
    [http.routers.k8s-https.tls]
    middlewares = ["compress"]

  [http.routers.domainname-api-http]
    rule = "Host(`api.local.domainname.com`,`api.username.domainname.com`)"
    service = "domainname-api"
    middlewares = ["redirect"]

  [http.routers.domainname-api-https]
    rule = "Host(`api.local.domainname.com`,`api.username.domainname.com`)"
    service = "domainname-api"
    [http.routers.domainname-api-https.tls]
    middlewares = ["compress"]

  [http.routers.domainname-my-http]
    rule = "Host(`my.local.domainname.com`,`my.username.domainname.com`)"
    service = "domainname-my"
    middlewares = ["redirect"]

  [http.routers.domainname-my-https]
    rule = "Host(`my.local.domainname.com`,`my.username.domainname.com`)"
    service = "domainname-my"
    [http.routers.domainname-my-https.tls]
    middlewares = ["compress"]

  [http.routers.domainname-other-http]
    rule = "Host(`other.local.domainname.com`,`other.username.domainname.com`)"
    service = "domainname-other"
    middlewares = ["redirect"]

  [http.routers.domainname-other-https]
    rule = "Host(`other.local.domainname.com`,`other.username.domainname.com`)"
    service = "domainname-other"
    [http.routers.domainname-other-https.tls]
    middlewares = ["compress"]

[http.services]
  [[http.services.rabbitmq.loadBalancer.servers]]
    url = "http://localhost:15672"

  [[http.services.traefik.loadBalancer.servers]]
    url = "http://localhost:15772"

  [[http.services.k8s.loadBalancer.servers]]
    url = "http://localhost:7080"

  [[http.services.domainname-api.loadBalancer.servers]]
    url = "http://localhost:3000"

  [[http.services.domainname-my.loadBalancer.servers]]
    url = "http://localhost:3010"

  [[http.services.domainname-other.loadBalancer.servers]]
    url = "http://localhost:3020"

```

brew info traefik outputs following:

```bash
➜  .config brew info traefik
traefik: stable 2.3.2 (bottled), HEAD
Modern reverse proxy
https://traefik.io/
/usr/local/Cellar/traefik/2.3.2 (7 files, 93.2MB) *
  Poured from bottle on 2020-10-27 at 15:20:52
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/traefik.rb
License: MIT
==> Dependencies
Build: go ✔, go-bindata ✘
==> Options
--HEAD
	Install HEAD version
==> Caveats
To have launchd start traefik now and restart at login:
  brew services start traefik
Or, if you don't want/need a background service you can just run:
  traefik
==> Analytics
install: 283 (30 days), 947 (90 days), 3,668 (365 days)
install-on-request: 283 (30 days), 947 (90 days), 3,662 (365 days)
build-error: 0 (30 days)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```bash
time="2020-11-03T15:22:19+01:00" level=info msg="Stats collection is enabled."
time="2020-11-03T15:22:19+01:00" level=info msg="Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration."
time="2020-11-03T15:22:19+01:00" level=info msg="Help us improve Traefik by leaving this feature on :)"
time="2020-11-03T15:22:19+01:00" level=info msg="More details on: https://doc.traefik.io/traefik/contributing/data-collection/"
time="2020-11-03T15:22:19+01:00" level=info msg="Enabling ProxyProtocol for trusted IPs [0.0.0.0/0]" entryPointName=http
time="2020-11-03T15:22:19+01:00" level=info msg="Enabling ProxyProtocol for trusted IPs [0.0.0.0/0]" entryPointName=https
time="2020-11-03T15:22:19+01:00" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2020-11-03T15:22:19+01:00" level=debug msg="Start TCP Server" entryPointName=http
time="2020-11-03T15:22:19+01:00" level=debug msg="Start TCP Server" entryPointName=api
time="2020-11-03T15:22:19+01:00" level=info msg="Starting provider *file.Provider {\"directory\":\"/Users/username/.config/\",\"watch\":true,\"filename\":\"traefik.toml\"}"
time="2020-11-03T15:22:19+01:00" level=debug msg="Start TCP Server" entryPointName=https
time="2020-11-03T15:22:19+01:00" level=debug msg="Start TCP Server" entryPointName=traefik
time="2020-11-03T15:22:19+01:00" level=error msg="Cannot start the provider *file.Provider: /Users/username/.config/traefik.toml: field not found, node: middlewares"
time="2020-11-03T15:22:19+01:00" level=info msg="Starting provider *traefik.Provider {}"
time="2020-11-03T15:22:19+01:00" level=debug msg="Configuration received from provider internal: {\"http\":{\"routers\":{\"api\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/api`)\",\"priority\":2147483646},\"dashboard\":{\"entryPoints\":[\"traefik\"],\"middlewares\":[\"dashboard_redirect@internal\",\"dashboard_stripprefix@internal\"],\"service\":\"dashboard@internal\",\"rule\":\"PathPrefix(`/`)\",\"priority\":2147483645},\"debug\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/debug`)\",\"priority\":2147483646}},\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{}},\"middlewares\":{\"dashboard_redirect\":{\"redirectRegex\":{\"regex\":\"^(http:\\\\/\\\\/(\\\\[[\\\\w:.]+\\\\]|[\\\\w\\\\._-]+)(:\\\\d+)?)\\\\/$\",\"replacement\":\"${1}/dashboard/\",\"permanent\":true}},\"dashboard_stripprefix\":{\"stripPrefix\":{\"prefixes\":[\"/dashboard/\",\"/dashboard\"]}}}},\"tcp\":{},\"tls\":{}}" providerName=internal
time="2020-11-03T15:22:19+01:00" level=debug msg="Added outgoing tracing middleware dashboard@internal" middlewareName=tracing entryPointName=traefik routerName=dashboard@internal middlewareType=TracingForwarder
time="2020-11-03T15:22:19+01:00" level=debug msg="Creating middleware" entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_stripprefix@internal middlewareType=StripPrefix
time="2020-11-03T15:22:19+01:00" level=debug msg="Adding tracing to middleware" routerName=dashboard@internal middlewareName=dashboard_stripprefix@internal entryPointName=traefik
time="2020-11-03T15:22:19+01:00" level=debug msg="Creating middleware" middlewareName=dashboard_redirect@internal middlewareType=RedirectRegex entryPointName=traefik routerName=dashboard@internal
time="2020-11-03T15:22:19+01:00" level=debug msg="Setting up redirection from ^(http:\\/\\/(\\[[\\w:.]+\\]|[\\w\\._-]+)(:\\d+)?)\\/$ to ${1}/dashboard/" routerName=dashboard@internal middlewareName=dashboard_redirect@internal middlewareType=RedirectRegex entryPointName=traefik
time="2020-11-03T15:22:19+01:00" level=debug msg="Adding tracing to middleware" entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_redirect@internal
time="2020-11-03T15:22:19+01:00" level=debug msg="Added outgoing tracing middleware api@internal" middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik routerName=debug@internal
time="2020-11-03T15:22:19+01:00" level=debug msg="Added outgoing tracing middleware api@internal" entryPointName=traefik routerName=api@internal middlewareName=tracing middlewareType=TracingForwarder
time="2020-11-03T15:22:19+01:00" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2020-11-03T15:22:19+01:00" level=debug msg="No default certificate, generating one"
```

What I do not understand is:

 - Why it does not see the middlewares node in TOML
 - Why it does not see the default certificates and re-generates a new one every time I restart

As far as I understand, the issue was actually hidden before and revealed itself after this: https://doc.traefik.io/traefik/migration/v2/#file-provider but still can't find the problem.

**Comment by o1dnik** [comment]
Answering own question.

The order of lines was not correct:

```toml
    middlewares = ["compress"]
    [http.routers.rabbitmq-https.tls]
```

middlewares should be above next square brackets "[]" since it's opening another scope, but should be still in the scope of [http.routers.rabbitmq-https].
And the certificate can still be generated with mkcert and feeded with the config

```toml
[[tls.certificates]]
  certFile = "/Users/username/certs/localhost.pem"
  keyFile  = "/Users/username/certs/localhost-key.pem"
```
