### ISSUE TITLE
Traefik Crashes on Kubernetes

### ISSUE THREAD

**Issue by mishushakov** [traefik/traefik#7508]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Install and run traefik

### What did you expect to see?

My SaaS

### What did you see instead?

```
time="2020-11-04T17:02:59Z" level=info msg="Configuration loaded from flags."
10.42.0.1 - - [04/Nov/2020:17:03:29 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 1 "ping@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:03:38 +0000] "GET / HTTP/1.1" 301 17 "-" "-" 2 "http-to-https@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:03:38 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 3 "ping@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:03:56 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 4 "ping@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:03:56 +0000] "GET / HTTP/2.0" - - "-" "-" 5 "-" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:03:56 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 6 "ping@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:03:56 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 7 "ping@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:03:56 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 8 "ping@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:03:57 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 9 "ping@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:03:57 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 10 "ping@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:03:57 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 11 "ping@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:03:57 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 12 "ping@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:03:57 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 13 "ping@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:04:08 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 14 "ping@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:04:10 +0000] "GET / HTTP/1.1" 301 17 "-" "-" 15 "http-to-https@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:04:12 +0000] "GET /ping HTTP/1.1" 503 19 "-" "-" 16 "ping@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:04:12 +0000] "GET /ping HTTP/1.1" 503 19 "-" "-" 17 "ping@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:04:12 +0000] "GET /ping HTTP/1.1" 503 19 "-" "-" 18 "ping@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:04:12 +0000] "GET /ping HTTP/1.1" 503 19 "-" "-" 19 "ping@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:04:12 +0000] "GET /ping HTTP/1.1" 503 19 "-" "-" 20 "ping@internal" "-" 0ms
10.42.0.1 - - [04/Nov/2020:17:04:12 +0000] "GET /ping HTTP/1.1" 503 19 "-" "-" 21 "ping@internal" "-" 0ms
time="2020-11-04T17:04:21Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=http
time="2020-11-04T17:04:21Z" level=error msg="Error while starting server: accept tcp [::]:80: use of closed network connection" entryPointName=http
time="2020-11-04T17:04:21Z" level=error msg="Error while starting server: http: Server closed" entryPointName=http
time="2020-11-04T17:04:22Z" level=error msg="accept tcp [::]:443: use of closed network connection" entryPointName=https
time="2020-11-04T17:04:22Z" level=error msg="accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2020-11-04T17:04:22Z" level=error msg="Error while starting server: http: Server closed" entryPointName=traefik
time="2020-11-04T17:04:25Z" level=error msg="Error while starting server: http: Server closed" entryPointName=https
time="2020-11-04T17:04:25Z" level=error msg="close tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2020-11-04T17:04:25Z" level=error msg="Error while starting server: http: Server closed" entryPointName=traefik
time="2020-11-04T17:04:27Z" level=error msg="Error while starting server: http: Server closed" entryPointName=https
time="2020-11-04T17:04:28Z" level=error msg="close tcp [::]:443: use of closed network connection" entryPointName=https
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

traefik:v2.3

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Deployment.yaml

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: traefik
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik
      containers:
      - name: traefik
        image: traefik:v2.3
        args:
          - --ping
          - --accesslog
          - --entrypoints.http.address=:80
          - --entrypoints.https.address=:443
          - --entrypoints.https.http.tls
          - --entrypoints.http.http.redirections.entrypoint.to=https
          - --entrypoints.http.http.redirections.entrypoint.scheme=https
          - --providers.kubernetescrd
          - --providers.kubernetesingress
          - --providers.kubernetesingress.ingressclass=traefik
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
```

CustomResourceDefinition.yaml

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressroutes.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRoute
    plural: ingressroutes
    singular: ingressroute
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: middlewares.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: Middleware
    plural: middlewares
    singular: middleware
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressroutetcps.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRouteTCP
    plural: ingressroutetcps
    singular: ingressroutetcp
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressrouteudps.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRouteUDP
    plural: ingressrouteudps
    singular: ingressrouteudp
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tlsoptions.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TLSOption
    plural: tlsoptions
    singular: tlsoption
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tlsstores.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TLSStore
    plural: tlsstores
    singular: tlsstore
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: traefikservices.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TraefikService
    plural: traefikservices
    singular: traefikservice
  scope: Namespaced
```

ClusterRole.yaml

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - middlewares
      - ingressroutes
      - traefikservices
      - ingressroutetcps
      - ingressrouteudps
      - tlsoptions
      - tlsstores
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: traefik
```

Namespace.yaml

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
```

ServiceAccount.yaml

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: traefik
  name: traefik
```

Service.yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: traefik
  type: LoadBalancer
```

thanks!
