### ISSUE TITLE
Error publishing http service

### ISSUE THREAD

**Issue by tadeo-n** [traefik/traefik#7509]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm trying to publish a web service internally using IP instead hostname/URL, the IP may change depending on our environment

### What did you expect to see?

Publish web service ussing HTTP and HTTPS

### What did you see instead?

HTTP: Web service works correctly
HTTPS: Accept self-signed certificate alert and I got -> 404 page not found

### Output of `traefik version`: 2.3.2

```
time="2020-11-04T17:17:55Z" level=debug msg="Serving default certificate for request: \"\""
time="2020-11-04T17:17:55Z" level=debug msg="http: TLS handshake error from XXXXXX:44035: remote error: tls: unknown certificate"
time="2020-11-04T17:17:55Z" level=debug msg="Serving default certificate for request: \"\""
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

docker-compose:
```
version: '3.2'
traefik:
    image: traefik:v2.3.2
    command:
      - "--log.level=DEBUG"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--entryPoints.traefik.address=:8081"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
    labels:
      - "traefik.enable=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

myapp:
    image: myapp:latest
    ports:
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.myapp.loadbalancer.server.port=8080"
      - "traefik.http.routers.myapp.rule=Path(``)" # <-- I put this to accept any URL. it can be done in another way?
      - "traefik.http.routers.myapp.entrypoints=web,web-secure"
```
