### ISSUE TITLE
Cannot setup metrics credentials outside Traefik configuration files

### ISSUE THREAD

**Issue by jlandercy** [traefik/traefik#7511]
### Do you want to request a *feature* or report a *bug*?

I would like to report what seems to be a configuration issue with Traefik v2.x.

My goal is to **push Traefik metrics into InfluxDB without leaking credentials to Docker Compose YAML setup**.
I had tried several times with latests v2.x versions, I never succeeded.
Either I am missing something that would worth being documented or it might be a bug.

#### Working configuration

If I configure Traefik using commands, it works as expected:

``` bash
      # Metrics:
      - "--metrics.influxdb=true"
      - "--metrics.influxdb.address=influxdb:8086"
      - "--metrics.influxdb.protocol=http"
      - "--metrics.influxdb.database=traefik"
      - "--metrics.influxdb.retentionpolicy=monthly"
      - "--metrics.influxdb.addentrypointslabels=true"
      - "--metrics.influxdb.addserviceslabels=true"
      - "--metrics.influxdb.pushinterval=10s"
      - "--metrics.influxDB.username=user"
      - "--metrics.influxDB.password=pass"
```

Metrics are published, therefore I know the complete acquisition chain is working.
This is what I want to achieve without having at least the `password` field into the YAML configuration.

Note: I also have tried if it is a case issue (`influxdb` vs `influxDB`) but this does not seem to affect this kind of configuration.

#### Yet another working configuration

I also have tried it with TOML static configuration file:

```yaml
    volumes:
      - "./configuration/traefik.toml:/etc/traefik/traefik.toml:ro"
```

And it works as well:

```toml
[metrics]
  [metrics.influxdb]
    address = "influxdb:8086"
    protocol = "http"
    database = "traefik"
    retentionPolicy = "monthly"
    addEntryPointsLabels = true
    addServicesLabels = true
    pushInterval = "10s"
    username = "user"
    password = "pass"
```

But I prefer stick to single YAML file which is more convenient.

#### Environment Variable configuration does nothing

If I try to move this configuration into environment variables (eg. `../secrets/traefik.env`):

```yaml
    env_file:
      #- TRAEFIK_METRICS_INFLUXDB_PASSWORD=
      - ../secrets/traefik.env
```

```bash
TRAEFIK_METRICS_INFLUXDB="true"
TRAEFIK_METRICS_INFLUXDB_ADDRESS="influxdb:8086"
TRAEFIK_METRICS_INFLUXDB_PROTOCOL="http"
TRAEFIK_METRICS_INFLUXDB_DATABASE="traefik"
TRAEFIK_METRICS_INFLUXDB_RETENTIONPOLICY="monthly"
TRAEFIK_METRICS_INFLUXDB_PUSHINTERVAL="10s"
TRAEFIK_METRICS_INFLUXDB_ADDSERVICESLABELS="true"
TRAEFIK_METRICS_INFLUXDB_ADDENTRYPOINTSLABELS="true"
TRAEFIK_METRICS_INFLUXDB_USERNAME="user"
TRAEFIK_METRICS_INFLUXDB_PASSWORD="pass"
```

Then nothing happens, no errors, no pushed metrics, it seems it is just ignored by Traefik.
I also have tested mixed configuration, just having the following lines as environment variables:

```bash
TRAEFIK_METRICS_INFLUXDB_USERNAME="user"
TRAEFIK_METRICS_INFLUXDB_PASSWORD="pass"
```

But then the error is:

```
time="2020-11-05T07:25:16Z" level=error msg="Error while writing to InfluxDB: {\"error\":\"unable to parse authentication credentials\"}\n" metricsProviderName=influxdb
time="2020-11-05T07:25:16Z" level=info msg="[during WriteTo err {\"error\":\"unable to parse authentication credentials\"}\n]" metricsProviderName=influxdb
```

It seems to claim it did not found any credentials when provided as environment variable.

#### Trying some workaround

Then I tried to override the command configuration using templated variable as it sometimes solves the problem when dealing with docker-compose parametrization which lack a setup mechanism. I came with this version:

```yaml
      - "--metrics.influxDB.username=$${TRAEFIK_INFLUXDB_USERNAME}"
      - "--metrics.influxDB.password=$${TRAEFIK_INFLUXDB_PASSWORD}"
```

And off course I have setup the variables in `./secrets/traefik.env`. I deliberately have chosen different names to avoid clash with traefik documentation:

```bash
TRAEFIK_INFLUXDB_USERNAME="user"
TRAEFIK_INFLUXDB_PASSWORD="pass"
```

But it sadly fails, Traefik cannot make it:

```
time="2020-11-05T08:19:02Z" level=error msg="Error while writing to InfluxDB: {\"error\":\"authorization failed\"}\n" metricsProviderName=influxdb
time="2020-11-05T08:19:02Z" level=info msg="[during WriteTo err {\"error\":\"authorization failed\"}\n]" metricsProviderName=influxdb
```

And what a surprise, variables are not replaced by their value:

```
[httpd] 172.19.0.6 - ${TRAEFIK_INFLUXDB_USERNAME} [05/Nov/2020:07:35:35 +0000] "POST /write?consistency=&db=traefik&precision=ns&rp=monthly HTTP/1.1" 401 33 "-" "InfluxDBClient" 7e4e43d6-1f39-11eb-b178-0242ac130007 486
```

Traefik submit the variable name instead of its value, as we may expect from this manipulation.

After those tests, it seems Docker does load environment variables but Traefik prevent it to use it in configuration or to be replaced in command line. This is somehow disappointing.

### What did you expect to see?

Traefik is a great peace of software and I hope it will continue to grow and consolidate in the future. 
Thank you for having made this so user-friendly!

About this specific issue, I know handling several configuration flows is quite a challenge and having the documentation up-to-date is a great burden.

Anyway, I would expect to have a path to setup metrics without having the password in a Traefik configuration file (YAML or TOML).
It seems environment variables are handled in a specific way by Traefik, and this is a bit confusing to the user.

I would like to understand how I can achieve it. Is it:

 - A bad configuration at my side?
 - This behaviour documented somewhere?
 - A bug?
 - An on-purpose limitation of the product?
 - Something else...

Thank you for your help.

Do not hesitate to contact me if you need extra insights.
I did my best to make this issue self contained.

Best regards,

### What did you see instead?

I see that I need to store my credentials in clear text in static configuration and this is somehow a leak I want to avoid.
I cannot use environment variables as I expected either as documented [here](https://doc.traefik.io/traefik/reference/static-configuration/env/) or trying to tweak the commands.

### What version of Traefik are you using?

My Traefik version is the latest (at writing time), the bug was also present in previous 2.x versions.

```bash
docker image inspect traefik
```

```json
{
    "org.opencontainers.image.description": "A modern reverse-proxy",
    "org.opencontainers.image.documentation": "https://docs.traefik.io",
    "org.opencontainers.image.title": "Traefik",
    "org.opencontainers.image.url": "https://traefik.io",
    "org.opencontainers.image.vendor": "Traefik Labs",
    "org.opencontainers.image.version": "v2.3.2"
}
```

### What is your environment & configuration?

I use always latest traefik version running into Docker. 
Docker host is an Ubuntu 20.04 LTS up-to-date.

```
docker --version
Docker version 19.03.8, build afacb8b7f0

docker-compose --version
docker-compose version 1.25.0, build unknown

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

I use pure docker-compose configuration for Traefik with a single YAML file.

```yaml
version: "3.6"

services:

  traefik:
    image: traefik
    env_file:
      - ../secrets/traefik.env
    command:
      # General settings:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.lets.acme.tlschallenge=true"
      - "--certificatesresolvers.lets.acme.email=jlandercy@example.com"
      - "--certificatesresolvers.lets.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - backend
    ports:
      - "80:80"
      - "443:443"

networks:
  backend:
    external: true
```

No extra configuration files for Traefik.
I added relevant log outputs from InfluxDB and Traefik in the sections above.
