### ISSUE TITLE
RFC2136 DNS provider not working, illegal base64 data input at byte 12

### ISSUE THREAD

**Issue by domibarton** [traefik/traefik#7520]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am trying to create a new wildcard certificate via ACME Let's Encrypt. Since I've a BIND in place, I'd like to use the RFC 2136 provider. However, that doesn't work.

I created all the files required for the rfc2136 provider, and copy them together w/ the config into the Docker image.

### What did you expect to see?

- The certificate is issued

### What did you see instead?

- An error when Traefik is started : 

```
time="2020-11-06T07:30:44Z" level=error msg="Unable to obtain ACME certificate for domains \"confirm.ch\" : unable to generate a certificate for the domains [confirm.ch]: error: one or more domains had a problem:\n[confirm.ch] [confirm.ch] acme: error presenting token: rfc2136: failed to insert: DNS update failed: illegal base64 data at input byte 12\n" providerName=letsencrypt.acme
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.2
Codename:     picodon
Go version:   go1.15.3
Built:        2020-10-19T18:36:22Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Dockerfile:

```Dockerfile
FROM traefik:v2.3

VOLUME /data

ENV RFC2136_NAMESERVER_FILE /rfc2136/nameserver
ENV RFC2136_TSIG_ALGORITHM_FILE /rfc2136/algorithm
ENV RFC2136_TSIG_KEY_FILE /rfc2136/key
ENV RFC2136_TSIG_SECRET /rfc2136/secret

COPY traefik/traefik.yml /traefik.yml
COPY traefik/config /config
COPY traefik/auth /auth
COPY rfc2136 /rfc2136
```

My `traefik.yml`:

```yaml
---
providers:
    directory: /config
  docker:
    endpoint: "unix:///var/run/docker.sock"

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "confirm.ch"

certificatesResolvers:
  letsencrypt:
    acme:
      email: …
      dnsChallenge:
        provider: rfc2136
      storage: /data/acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory

api:
  dashboard: true
```

Environment Vars / RFC files:

```
export | grep RFC
export RFC2136_NAMESERVER_FILE='/rfc2136/nameserver'
export RFC2136_TSIG_ALGORITHM_FILE='/rfc2136/algorithm'
export RFC2136_TSIG_KEY_FILE='/rfc2136/key'
export RFC2136_TSIG_SECRET='/rfc2136/secret'

ls -l /rfc2136/
total 16
-rw-r--r--    1 root     root            13 Nov  6 07:10 algorithm
-rw-r--r--    1 root     root             8 Nov  6 07:10 key
-rw-r--r--    1 root     root            19 Nov  6 07:17 nameserver
-rw-r--r--    1 root     root            89 Nov  6 07:10 secret

cat /rfc2136algorithm
hmac-sha512.

/rfc2136 # cat /rfc2136key
traefik

/rfc2136 # cat /rfc2136nameserver
ns1.pub.confirm.ch

/rfc2136 # cat /rfc2136secret
…
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

### What I tried so far 

When I do the same directly in lego, it works:

My env file:

```
RFC2136_NAMESERVER=ns1.pub.confirm.ch
RFC2136_TSIG_KEY=traefik
RFC2136_TSIG_SECRET=…
RFC2136_TSIG_ALGORITHM=hmac-sha512.
```

Docker Run (on the same environment where the Traefik container is running):

```bash
docker run -it --env-file env goacme/lego -a --email="…" --domains="confirm.ch" --dns="rfc2136" --server=https://acme-staging-v02.api.letsencrypt.org/directory run
```

Output:

```
2020/11/06 06:30:30 [INFO] [confirm.ch] acme: Cleaning DNS-01 challenge
2020/11/06 06:30:30 [INFO] [confirm.ch] acme: Validations succeeded; requesting certificates
2020/11/06 06:30:31 [INFO] [confirm.ch] Server responded with a certificate.
```

So the BIND server is configured correctly and lego works as well.

I also tried defining the DNS server via the IP and defining the parameters directly via ENV vars, instead of the `_FILE` vars.
