### ISSUE TITLE
mTLS authentication not working with routers using HostRegexp rule

### ISSUE THREAD

**Issue by rbeuque74** [traefik/traefik#7530]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

When I created an endpoint with a `HostRegexp` rule, my TLS options for `clientAuth` (mTLS) was not taken into account.
I created two routers, one with a basic `Host` rule, one with a `HostRegexp` rule, both of them configured on the same entrypoint with the same TLS options.

### What did you expect to see?
I expected to have the same behavior, a TLS certificate being prompted.
 

### What did you see instead?
Requests on the `HostRegexp` router are not requiring the client authentication.

Routers configuration:
```yaml
http:
    # Add the router
    routers:
        foobarfoobar:
            entryPoints:
                - websecure
            service: api@internal
            rule: Host(`foobarfoobarfoobar.local`)
            tls:
                options: mTLS@file
        wildcard:
            entryPoints:
                - websecure
            service: api@internal
            rule: "HostRegexp(`{host:.+}`)"
            tls:
                options: mTLS@file

tls:
    stores:
        default:
            defaultCertificate:
                certFile: /certs/foo.crt
                keyFile: /certs/foo.key
    options:
        mTLS:
            minVersion: VersionTLS12
            cipherSuites:
                - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
                - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
                - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
                - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
                - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
            clientAuth:
              caFiles:
                - "/certs/certs/root_ca.crt"
              clientAuthType: RequireAndVerifyClientCert

```
cURLs:
```
romain$ curl -m 3 --url https://foobarfoobarfoobar.local:4443/ -k
curl: (56) OpenSSL SSL_read: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate, errno 0

romain$ curl -m 3 --cert client.crt --key client.key --cacert certs/root_ca.crt --url https://foobarfoobarfoobar.local:4443/ -k
<a href="/dashboard/">Found</a>.

romain$ curl -m 3 --url https://foobar.local:4443/ -k
<a href="/dashboard/">Found</a>.
```

Last cURL should have return the same output that the first cURL returned.

Access logs
```
172.17.0.1 - - [08/Nov/2020:23:42:23 +0000] "GET / HTTP/2.0" 302 34 "-" "-" 2 "foobarfoobar@file" "-" 0ms
172.17.0.1 - - [08/Nov/2020:23:42:51 +0000] "GET / HTTP/2.0" 302 34 "-" "-" 3 "wildcard@file" "-" 0ms
```
for respectively request 2 and 3.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v2.3 (official docker image)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: true
entryPoints:
  websecure:
    address: :4443
    http:
      tls: {}
log:
  level: INFO
accessLog: {}
api:
  insecure: false
  debug: false
  dashboard: true
providers:
  file:
    directory: /appconfig
    watch: true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
