### ISSUE TITLE
Sometimes traefik does not synchronize the data in redis

### ISSUE THREAD

**Issue by renl0314** [traefik/traefik#7531]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I store my configuration in Redis.Sometimes when I modify redis data, traefik does not synchronize the modified data.Every time this happens, I need to restart the Traefik service.The configuration will not take effect until you restart。But that doesn't happen every time.

### What did you expect to see?

When I modify the data in redis, traefik synchronizes these configurations immediately.

### What did you see instead?

When this bug occurred, there was no log.I checked the data in the Traefik Dashboard and Redis, and they didn't match.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v2.2.8
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Here is my Redis config stored in /etc/traefik/traefik.toml
```toml
[providers.redis]
    endpoints = ["traefik-redis:6379"]
    rootKey = "traefik"
    password = "1"
```

Docker-compose file:
```
version: '3'
services:
  traefik:
     image: traefik:v2.2.8
     restart: always
     container_name: traefik
     command: --api.insecure=true --providers.docker
     privileged: true
     ports:
       - "9080:80"
       - "9090:8080"
       - "443:443"
       - "4399:4399"
       - "4398:4398"
     volumes:
       - ./dynamic/:/dynamic/
       - ./static/:/etc/traefik/
       # So that Traefik can listen to the Docker events
       - /var/run/docker.sock:/var/run/docker.sock

   traefik-redis:
     image: redis:5.0.8
     restart: always
     container_name: traefik-redis
     privileged: true
     ports:
       - "6379:6379"
     volumes:
       - ./redis/config:/etc/config
       - ./redis/data:/data
     command: redis-server /etc/config/redis.conf
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
