### ISSUE TITLE
Flapping whitelisted requests

### ISSUE THREAD

**Issue by jlsan92** [traefik/traefik#7536]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I enabled Frontend whitelisting (`traefik.ingress.kubernetes.io/whitelist-source-range`) by reading the X-Forwarded-For header (`ingress.kubernetes.io/whitelist-x-forwarded-for`).

ℹ️  My Traefik is behind a L7 Loadbalancer, I'm able to spot the `X-Forwarded-For` header with the expected value

### What did you expect to see?

The whitelisting to work properly

### What did you see instead?

The rule seems to be flapping. Randomly it forbids or allows connections from the whitelisted IP.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:1.7.19
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
    ingress.kubernetes.io/ssl-proxy-headers: 'X-Forwarded-Proto: https'
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/whitelist-x-forwarded-for: "true"
    kubernetes.io/ingress.class: my-class
    traefik.ingress.kubernetes.io/priority: "4"
    traefik.ingress.kubernetes.io/rule-type: Path
    traefik.ingress.kubernetes.io/whitelist-source-range: 1.2.3.4/20 # Just an example
```
