### ISSUE TITLE
Unable to make `/ping` work on `traefik` entrypoint with `manualrouting=true` using file provider

### ISSUE THREAD

**Issue by leshik** [traefik/traefik#7543]
Hi,

Trying to make `/ping` work with `manualrouting=true` using file provider, but it doesn't work.

```
traefik --accesslog=true --api.insecure=true --log --log.level=INFO --ping=true --ping.manualrouting=true --providers.file.directory=/etc/traefik
```

> /etc/traefik/ping.yml
```
http:
  routers:
    ping:
      entryPoints:
        - traefik
      rule: PathPrefix(`/ping`)
      service: ping@internal
```

> curl localhost:8080/ping
```
404 page not found
```

Requests end up in `dashboard@internal` service:
```
127.0.0.1 - - [12/Nov/2020:04:54:32 +0000] "GET /ping HTTP/1.1" 404 19 "-" "-" 89 "dashboard@internal" "-" 0ms
```

I suppose this might be somehow related to providers' priority.
