### ISSUE TITLE
Wrong backend URL when backend redirects to URL without trailing /

### ISSUE THREAD

**Issue by linkvt** [traefik/traefik#7544]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I setup a health check to a backend which does a redirect (I disabled following redirects afterwards as I don't need it but traefik behaviour still seems wrong, see below).
I used this config:
```yaml
http:
  routers:
    airflow:
      rule: "Host(`airflow.domain`)"
      service: airflow
  services:
    airflow:
      loadBalancer:
        servers:
          - url: "http://host.domain:80/"
        healthCheck:
          path: /health
```

### What did you expect to see?
Redirect produces a successful URL for traefik to check, health check succeeds.

### What did you see instead?
It seems that traefik constructs a wrong URL after the redirect, the logs show the following error:
```
Nov 12 16:09:02 host cdeb4208a769[3334]: time="2020-11-12T15:09:02Z" level=warning msg="Health check still failing. Backend: \"airflow@file\" URL: \"http://host.domain:80/\" Reason: HTTP request failed: Get \"https://airflow.domainhealth\": dial tcp: lookup airflow.domainhealth on dns.ser.ver.ip:53: no such host"
```
It seems that the path (`/health`) and the resulting url of the redirect (`https://airflow.domain`, the `Location` header is without a trailing slash) were incorrectly merged so that the `/` was skipped.

### Output of `traefik version`: (_What version of Traefik are you using?_)
v2.3.2 with the slight modification to use a lego version which handles our non-RFC compliant ACME endpoint... 
see https://github.com/traefik/traefik/compare/v2.3.2...linkvt:2.3.2-optional-angle-brackets?expand=1 and 
https://github.com/go-acme/lego/compare/master...linkvt:4.0.1-optional-angle-brackets

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Nothing special.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Thanks for your help, I will also try to debug this next week if I have time.
