### ISSUE TITLE
Use router regexp matches in middleware

### ISSUE THREAD

**Issue by ccakes** [traefik/traefik#7547]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I'd love to be able to use matches from the HostRegex in a middleware. My example use case is something like this:

```yaml
# traefik.yaml
entryPoints:
  http:
   address: ":80"

providers:
  file:
    filename: /local/config.yml

# config.yaml
http:
  routers:
    r-web-pr:
      entryPoints:
        - http
      service: s-web-pr
      rule: HostRegexp(`web--{pr:[0-9]+}.example.com`)

  middlewares:
    m-web-pr:
      replacePathRegex:
        regex: .*
        replacement: /web--${host_pr}/index.html

  services:
    s-web-pr:
      loadBalancer:
        servers:
          - url: http://example.s3-website.eu-west-1.amazonaws.com
```

We extract a match from the Host header which can be then used in the replace path. The high-level use here is I want deploy pull request builds to a S3 bucket and then forward requests there
