### ISSUE TITLE
Proposal: Behavioral Configuration

### ISSUE THREAD

**Issue by SantoDE** [traefik/traefik#7550]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

This proposal is centered around a new configuration paradigm: a behavioral configuration
(in contrast to the current implementation, more declarative, yet powerful and flexible).

This behavioral configuration aims to simplify the setup of basic use cases.

With no further ado, this is how it may look for the file provider.

```yaml
# static configuration
entryPoints:
  web:
    address: :80

  websecure:
    address: :443
```

```yaml
# dynamic configuration
HTTPRoute: # maps to a combination of router/service
  rule: Host(`my.blog.com`) && (Path(`/...`) || ...)
  entrypoint: websecure
  redirectFrom: web
  tls:
    resolver: letsencrypt
    certificate: /path/to/cert # Path to Certificate
    key: /path/to/cert # Path to Certificate Key
  # Request modifier
  stripPrefix: 
    priority: 12 # all modifiers have a default priority that may be overriden
    prefixes:
      - foobar
      - foobar
    forceSlash: true
  ##
  loadBalancer:
    weighted:
      servers:
        - url: http://<private-ip-server-1>:<private-port-server-1>/
          weight: 1
        - url: http://<private-ip-server-2>:<private-port-server-2>/
```

Objects like HTTPRoute provide an opt-in to behavioral configuration patterns. For example, the declarative approach may look like:

```yaml
# static configuration
entryPoints:
  web:
    address: :80
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https

  websecure:
    address: :443
```

```yaml
# dynamic configuration
http:
  # Add the routerHTTPouters:
  router0:
    rule: Host(`my.blog.com`) && (Path(`/...`) || ...) 
    entryPoints:
      - websecure
    middlewares:
      - my-stripPrefix
    service: service-foo
    tls: {}
  ##
  middlewares:
    test-stripprefix:
      stripPrefix:
        prefixes:
          - "/foobar"
          - "/foobar"
        forceSlash: true
  ##
  services:
    service-foo:
      loadBalancer:
        servers:
        - url: http://foo/
        - url: http://bar/
##
tls:
  certificates:
    - certFile: /path/to/cert # Path to Certificate
      keyFile: /path/to/cert # Path to Key for Certificate
```

In Docker Swarm, this structure may appear as:

```yaml
labels:
  - "traefik.httproute.rule=Host(`my.blog.com`) && (Path(`/...`) || ...)"
  - "traefik.httproute.entrypoint=websecure"
  - "traefik.httproute.redirectFrom=web"
  - "traefik.httproute.tls.resolver=letsencrypt" 
  - "traefik.httproute.cors.priority=42" # all middlewares have a default priority that could be overridden to keep a default behavior
  - "traefik.httproute.cors.accessControlAllowCredentials=true"
  - "traefik.httproute.cors.accessControlAllowMethods=foo,bar"
  - "traefik.httproute.cors.accessControlAllowOrigin=foobar"
  - "traefik.httproute.cors.accessControlMaxAge=42"
  - "traefik.httproute.stripPrefix.priority=42"
  - "traefik.httproute.stripPrefix.prefixes=foo,bar"
  - "traefik.httproute.stripPrefix.forceSlash=true"
```

We already see some limitations with this approach, e.g.:

* Not suited for complex scenarios (limited to 1 router per container, 1 middleware per type per router, ...)
* No middleware reference: you need to copy/paste the same configuration everywhere
* 1 file per router (TOML / YAML)
* load balancing limited to round-robin

To counterbalance the limitations, we're thinking about introducing this new system while keeping support for the existing one.
This would provide users with quick configuration options for common use cases (behavioral configuration)
while allowing for more complex scenarios (current configuration).

This is an open discussion with you, the community, and the Traefik maintainers, so please let us know what you think.
Together we can continue to further enhance Traefik and ensure it is always easy to use.

**Comment by ldez** [comment]
Another approach can be the approach that I suggested in https://github.com/traefik/traefik/issues/5630#issuecomment-593628496


Model/kind/default/template for routers:

```yml
# Dynamic configuration.
# We used File provider only the demo (it can be available on all providers)
http:
  kinds:
    kind0:
      router:
        entryPoints:
          mergePolicy: force
          value:
            - foobar
            - foobar
        middlewares:
          mergePolicy: force
          value:
            - foobar
            - foobar
        priority:
          mergePolicy: force
          value: 42
        tls:
          mergePolicy: force
          value: true
          options:
            mergePolicy: force
            value: foobar
          certResolver:
            mergePolicy: force
            value: foobar
          domains:
            mergePolicy: force
            values:
              - main: foo
                sans:
                  - foo
                  - foo
              - main: bar
                sans:
                  - bar
                  - bar
```
