### ISSUE TITLE
HTTP2 non ssl not routed correctly

### ISSUE THREAD

**Issue by bayucandra** [traefik/traefik#7552]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
In my Kubernetes cluster ( AWS/EKS to be exact ), I have `IngressRoute` which expecting SSL HTTP/V2.0 Request to my gRPC service. **It works great**.

But when I made another `IngressRoute` which expecting HTTP/V2.0 request ( non SSL ) to the same gRPC service, it does not route correctly to my service. When I call it with HTTP/V.1 ( just call the domain name in browser ), I can see in my kubernetes log, it is correctly routed to my service, but of course, it is not the way I expected.

### What did you expect to see?
I expect to see that HTTP/V2.0 routed correctly to my service.

Just like the following log when I called with HTTPS/V2.0 ( SSL ) trough `websecure` entrypoint:
`xx.xx.xx.xx - - [13/Nov/2020:15:58:30 +0000] "POST /androidAuthService.Auth/PhoneVerification HTTP/2.0" 200 32 "-" "-" 1 "mai-android-api-4d344413596dc218d249@kubernetescrd" "h2c://192.168.182.175:5000" 2ms`

### What did you see instead?
Instead, when the `IngressRoute` get called from HTTP/V.2.0 ( Non SSL). It gives me following log ( expect to see service detail at the end part ):
`xx.xx.xx.xx - - [13/Nov/2020:15:22:27 +0000] "POST /androidAuthService.Auth/PhoneVerification HTTP/2.0" - - "-" "-" 3 - - 0ms`

But I see only HTTP/V1.1 ( non SSL ) is routed to my service correctly as on traefik log below ( I see service detail at the end part ):
`xx.xx.xx.xx - - [13/Nov/2020:15:22:13 +0000] "GET /favicon.ico HTTP/1.1" 500 21 "-" "-" 2 "mai-android-api-non-tls-bffc1c44a2e14f51134b@kubernetescrd" "h2c://192.168.182.175:5000" 0ms`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v2.1.4
```

Actually, I have tried the latest version, but it gets worst. Even the SSL `IngressRoute` doesn't work either.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Here is my "Non SSL" `IngressRoute` configuration
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: android-api-non-tls
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`grpc.mydomain.com`)
    services:
    - name: android-api
      port: 5000
      scheme: h2c
```
