### ISSUE TITLE
Chrome browser is slow on first load

### ISSUE THREAD

**Issue by Pabrisson** [traefik/traefik#7556]
Hi,

I have a load time of about ten seconds which only occurs on Chrome browser and on the first load.
Then it starts over every 5 minutes or so...
I specify that the certificates are valid, that no chrome extension is activated and that I am on Docker for Mac.

### Do you want to request a *feature* or report a *bug*?
Bug

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
v2.3
```
### What is your environment & configuration (arguments, toml, provider, platform, ...)?

> traefik.yml

```yaml
## Global Configuration
global:
  sendAnonymousUsage: false
  checkNewVersion: false

api:
  insecure: false
  dashboard: true

## Entrypoint Configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: default

## Provider Configuration
providers:
  docker:
    network: domain_traefik_default
    watch: true
    exposedByDefault: false
  file:
    filename: /etc/traefik/certs.yml
    watch: true
```

> docker-compose.yml

```yaml
version: '3'

services:
    reverse-proxy:
      image: traefik:v2.3
      restart: unless-stopped
      container_name: domain_reverse_proxy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./docker/certs/:/certs
        - ./docker/traefik.yml:/etc/traefik/traefik.yml:ro
        - ./docker/certs.yml:/etc/traefik/certs.yml:ro
      labels:
        traefik.enable: 1
        traefik.http.routers.api.entrypoints: websecure
        traefik.http.routers.api.rule: Host(`traefik.domain.local`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
        traefik.http.routers.api.tls: 1
        traefik.http.routers.api.service: api@internal
        traefik.http.routers.api.middlewares: auth
        traefik.http.middlewares.auth.digestauth.users: admin:traefik:645edc07321b34a1c5801f5cfca836ad
```

> certs.yml

```yaml
tls:
  certificates:
  - certFile: /certs/server.cer
    keyFile: /certs/server.key
```
