### ISSUE TITLE
Can't access api@internal using kubernetes CRD

### ISSUE THREAD

**Issue by Altiano** [traefik/traefik#7557]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Enabling `--api.dashboard=true` and using this CRD definition to route to the dashboard:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-route
spec:
  routes:
    - match: Host(`dash.domain.dev`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
      middlewares:
        - name: traefik-dashboard-auth
  # certResolver: traefikresolver

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-dashboard-auth
spec:
  basicAuth:
    secret: traefik-dashboard-auth-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-auth-secret
data:
  users: |2
    xxxxxx

```

### What did you expect to see?

If using wrong Auth, expecting Unauthorzied on `curl` to `dash.domain.dev`, otherwise the dashboard.

### What did you see instead?

Unauthorized on wrong Auth. But just 404 page not found when using the right Auth header.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v2.3.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
- --api.dashboard
- --accesslog
- --entrypoints.web.Address=:80
- --entrypoints.websecure.Address=:443
- --entrypoints.testplain.Address=:8080
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
10.42.0.1 - - [15/Nov/2020:06:58:34 +0000] "GET /dashboard HTTP/1.1" 401 17 "-" "-" 7 "default-traefik-dashboard-route-cab28368509e55d289fd@kubernetescrd" │
│  "-" 0ms                                                                                                                                                   │
│ 10.42.0.1 - tean [15/Nov/2020:06:58:36 +0000] "GET /dashboard HTTP/1.1" 404 19 "-" "-" 8 "default-traefik-dashboard-route-cab28368509e55d289fd@kubernetesc │
│ rd" "-" 1ms
```
