### ISSUE TITLE
Traefik trusts X-Forwarded-Prefix and X-Replaced-Path headers from untrusted IPs

### ISSUE THREAD

**Issue by branden** [traefik/traefik#7559]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm running Traefik 1.7 with the ForwardAuth middleware. I'm using an auth server that intends to authorize requests based on the incoming request's path, before it was modified by frontend rules. The PathPrefixStrip and ReplacePath rules set the `X-Forwarded-Prefix` and `X-Replaced-Path` headers with the content they removed from the request path. So in order to correctly handle requests to frontends that use those rules, the auth server needs to use the headers they set in order to reconstruct the incoming request path. However if the incoming request sets either of those headers, then the rules will append to the incoming header value, and it will be present in the request to the auth server. So the auth server could be tricked into granting access to an unauthorized path by forging one of the headers and setting it to an authorized path. I'm not aware of another way for an auth server to reconstruct a request path that was modified by these rules except via the headers they set.

To demonstrate I created a frontend with the path `/foo/` that uses PathPrefixStrip. Requests to this frontend have `X-Forwarded-Prefix: /foo` set on the proxied request by the PathPrefixStrip middleware. (Though I'm using PathPrefixStrip to demonstrate, the same problem exists for ReplacePath and its `X-Replaced-Path` header.)

### What did you expect to see?

I expected that a request from an untrusted IP for path `/foo/` that sets `X-Forwarded-Prefix: /bar` would result in a request to the auth server with the header `X-Forwarded-Prefix: /foo`.

### What did you see instead?

The request to the auth server had the header `X-Forwarded-Prefix: /bar /foo`.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.26
Codename:     maroilles
Go version:   go1.14.6
Built:        2020-07-28_03:45:27PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Running on Kubernetes, using the Kubernetes Ingress provider. 
```toml
    # traefik.toml
    logLevel = "debug"
    InsecureSkipVerify = true
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
        [entryPoints.http.redirect]
          regex = "^http://(.*)"
          replacement = "https://$1"
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]
          [entryPoints.https.tls.defaultCertificate]
          CertFile = "/ssl/tls.crt"
          KeyFile = "/ssl/tls.key"
      [entryPoints.traefik]
      address = ":8080"
      [entryPoints.velero-minio]
      address = ":9000"
      compress = true
        [entryPoints.velero-minio.tls]
        [entryPoints.velero-minio.tls.defaultCertificate]
        certFile = "/ssl/tls.crt"
        keyFile = "/ssl/tls.key"
      [entryPoints.prometheus]
      address = ":9100"
    [ping]
    entryPoint = "http"
    [kubernetes]
      [kubernetes.ingressEndpoint]
      publishedService = "kubeaddons/traefik-kubeaddons"
    [traefikLog]
      format = "json"
    [accessLog]
      format = "common"
    [accessLog.fields]
      defaultMode = "keep"
    [accessLog.fields.names]
    [accessLog.fields.headers]
      defaultMode = "keep"
    [accessLog.fields.headers.names]
    [api]
      entryPoint = "traefik"
      dashboard = true
    [metrics]
      [metrics.prometheus]
        entryPoint = "prometheus"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
This is a log entry for a request for a frontend`/foo/` that uses `PathPrefixStrip`, with the added header `X-Forwarded-Prefix: /bar` (unrelated header noise is removed):
```
{"Request":"{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{ <snip> \"X-Forwarded-Prefix\":[\"/bar\",\"/foo\"], <snip> },\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"a30d6f05b3a4f4cd981469e032c27d26-1734468285.us-west-2.elb.amazonaws.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.235.128:5233\",\"RequestURI\":\"/\",\"TLS\":null}","level":"debug","msg":"vulcand/oxy/roundrobin/rr: begin ServeHttp on request","time":"2020-11-18T00:24:06Z"}
```
