### ISSUE TITLE
IngressRoute service support named port

### ISSUE THREAD

**Issue by WLun001** [traefik/traefik#7560]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Currently it doesn't support named port
```yaml
match: Host(`whoami.example.com`)
kind: Rule
services:
 - name: whoami
   port: http -> not support named port
```

Only this working
```yaml
match: Host(`whoami.example.com`)
kind: Rule
services:
 - name: whoami
   port: 80
```
