### ISSUE TITLE
DNS lookup cached for http services

### ISSUE THREAD

**Issue by jwh** [traefik/traefik#7564]
This is similar to  #7354 - TCP now reacts to changes so is it possible to apply similar to HTTP services as presently the target address isn't refreshed, ideally this should be configurable as transient DNS errors will cause requests to fail so an on/off switch would be useful for instances where it should continue to only be looked up on start/reload

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by tlex** [comment]
I was just about to open an issue for this, after talking today to @emilevauge about it. Happy to see someone already did that.

My use case is for all routers defined via file providers (not only TCP or HTTP). Nginx has a caching control option - so basically that's what I'm using right now:

Request --> Traefik --> Nginx --> Service.

The relevant Nginx configuration is:
```
stream {
  resolver 127.0.0.11 valid=1s ipv6=off;
  map $remote_addr $backend_udp {
    default openvpn-udp;
  }
  map $remote_addr $backend_tcp {
    default openvpn-tcp;
  }
  server {
    listen 1194 udp;
    proxy_pass $backend_udp:1194;
  }
  server {
    listen 1194;
    proxy_pass $backend_tcp:1194;
  }
}
```

If I were able to define that `valid=1s` option for the router, I would get rid of quite a few containers floating around.

**Comment by ddtmachado** [comment]
@jwh and @tlex I don't see an issue with HTTP routers on this matter, as they are already doing lookup on a request basis when using a hostname as URL.

If that is not happening on your use case it may be another issue, so can you share the static + dynamic configs for a reproducible case?

**Comment by tlex** [comment]
Sorry, my comment was more of a general nature, not necessarily for HTTP routers. My pain is for TCP and UDP routers (as documented by the workaround above)

**Comment by tlex** [comment]
This is the configuration I was using without nginx:

```yml
udp:
  routers:
    openvpn-udp:
      entryPoints:
        - openvpn-udp
      service: openvpn-udp
  services:
    openvpn-udp:
      loadBalancer:
        servers:
          - address: "openvpn-udp:1194"
tcp:
  routers:
    openvpn-tcp:
      entryPoints:
        - openvpn-tcp
      rule: "HostSNI(`*`)"
      service: openvpn-tcp
  services:
    openvpn-tcp:
      loadBalancer:
        servers:
          - address: "openvpn-tcp:1194"
```

**Comment by jwh** [comment]
> @jwh and @tlex I don't see an issue with HTTP routers on this matter, as they are already doing lookup on a request basis when using a hostname as URL.
> 
> If that is not happening on your use case it may be another issue, so can you share the static + dynamic configs for a reproducible case?

The destination address of a service doesn't appear to be re-resolved at any point, whereas for TCP it is now (after the commit linked in the issue) - nothing special in my config

**Comment by ddtmachado** [comment]
@tlex thanks, so for you it should be fine after [v2.3.3](https://github.com/traefik/traefik/releases/tag/v2.3.3) as TCP was fixed and UDP already works in a per request basis.

@jwh for UDP, as I mentioned, it should be already covered. See here:

https://github.com/traefik/traefik/blob/2112de6f1515da1fa1d093697ed09e40c2622d58/pkg/udp/proxy.go#L22-L32

It resolves per request when serving, there is even a comment suggesting the reverse:

https://github.com/traefik/traefik/blob/2112de6f1515da1fa1d093697ed09e40c2622d58/pkg/udp/proxy.go#L12

which is really not what we want now :-)

**Comment by ddtmachado** [comment]
@jwh I did some quick tests with the File provider + k8s (local k3d) and, as expected, could not reproduce on http:

**File provider:**

```yaml
http:
  routers:
    whoami:
      entryPoints:
      - web
      service: whoami@file
      rule: Host(`whoami.docker.localhost`)      
  services:
    whoami:
      loadBalancer:
        servers:
        - url: http://whoami.apps.svc.cluster.local
```

**Service:**
```yaml
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: containous/whoami
          ports:
            - name: web
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: whoami
```

Deleting the pods, thus changing the underlying IP addresses of the service, has no impact and I can keep hitting then as soon as the new pod goes live.

```bash
curl -H "Host:whoami.docker.localhost" localhost
```

but maybe I missed something here
