### ISSUE TITLE
Traefik in Docker do not detect correct IP source when using IPv6

### ISSUE THREAD

**Issue by pichouk** [traefik/traefik#7572]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I think I found some king of bug when I tried to use the IPWhiteList middleware with any IPv6 client. I guess Traefik doesn't get the source IP address for IPv6 request.

I setup Traefik with Docker and the `containous/whoami` container. On the `whoami` container I configured IPWhitelist middleware to allow access to only 2 IP : one IPv4 and one IPv6 addresses. Both IP belong to the client I am using with those curl commands :

```
$ curl -4 https://whoami.example.com
IP: 127.0.0.1
IP: 192.168.32.5
RemoteAddr: 192.168.32.4:54298
GET / HTTP/1.1
Host: whoami.example.com
User-Agent: curl/7.52.1
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 92.212.47.91
X-Forwarded-Host: whoami.example.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: ea65cf991bc2
X-Real-Ip: 92.212.47.91
```

```
$ curl -6 https://whoami.example.com
Forbidden
```

### What did you expect to see?

I would expect to be able to access the service using IPv4 and IPv6.

### What did you see instead?

When using IPv4 Traefik get the correct source IP and the whitelisting middleware let me int. When using IPv6 Traefik do not get the IPv6 source address, so access is forbidden.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.0-rc4
Codename:     picodon
Go version:   go1.15
Built:        2020-08-19T16:02:03Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Here is my Docker Compose setup (I removed some useless parts).

```yaml
version: '3.7'

networks:
  proxy:
    name: 'proxy'

services:
  traefik:
    image: traefik:2.3
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
  whoami:
    image: containous/whoami
    labels:
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.service: whoami
      traefik.http.routers.whoami.rule: Host(`whoami.example.com`)
      traefik.http.routers.whoami.middlewares: "whoami-whitelist@docker"
      traefik.http.middlewares.whoami-whitelist.ipwhitelist.sourcerange: "92.212.47.91/32,2a03:8112:7171:3d00::1"
      traefik.http.services.whoami.loadbalancer.server.port: 80
      traefik.enable: true
    networks:
      - proxy
```

Here is some part of my Traefik TOML static config

```toml
[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
  [entryPoints.websecure]
    address = ":443"

[providers]
  providersThrottleDuration = "2s"
  [providers.docker]
    watch = true
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false
    network = "proxy"
  [providers.file]
    filename = "/traefik_dynamic.toml"
    watch = true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

I have this only one log message when doing the IPv6 request

```
time="2020-11-19T20:44:48+01:00" level=debug msg="rejecting request &{Method:GET URL:/ Proto:HTTP/2.0 ProtoMajor:2 ProtoMinor:0 Header:map[Accept:[*/*] User-Agent:[curl/7.52.1] X-Forwarded-Host:[whoami.example.com] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Server:[ea65cf991bc2] X-Real-Ip:[192.168.32.1]] Body:0xc00086c690 GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:whoami.example.com Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:192.168.32.1:54330 RequestURI:/login TLS:0xc00052ad10 Cancel:<nil> Response:<nil> ctx:0xc00086c990}: \"192.168.32.1\" matched none of the trusted IPs" middlewareName=whoami-whitelist@docker middlewareType=IPWhiteLister

```
