### ISSUE TITLE
Token value is appended with \\n thus API call to CloudFlare fails

### ISSUE THREAD

**Issue by prandelicious** [traefik/traefik#7576]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?

Successful DNS challenge

### What did you see instead?

Unsuccessful DNS challenge. It appears to be added `\\n` to the token value. I am able to query the CloudFlare API endpoint via curl using the token value but without the `\\n` at the end as indicated in the debug log below.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik 2.3-alpine
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Kubernetes: **k3s version v1.19.3+k3s3 (0e4fbfef)**
```yml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kube-system
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.3
          args:
            - --api.insecure=true
            - --accesslog
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --providers.kubernetescrd
            - --certificatesResolvers.le.acme.dnschallenge=true
            - --certificatesResolvers.le.acme.dnschallenge.provider=cloudflare
            - --certificatesresolvers.le.acme.email=<email_redacted>
            - --certificatesresolvers.le.acme.storage=/etc/traefik/certs/acme.json
            # Please note that this is the staging Let's Encrypt server.
            # Once you get things working, you should remove that whole line altogether.
            - --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
            - --log
            - --log.level=DEBUG
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: admin
              containerPort: 8080
          volumeMounts:
            - name: certificates
              mountPath: /etc/traefik/certs
          env:
            - name: CF_DNS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare
                  key: CF_ZONE_API_TOKEN
      volumes:
        - name: certificates
          persistentVolumeClaim:
            claimName: traefik-certs-pvc
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-11-22T09:58:48Z" level=error msg="Unable to obtain ACME certificate for domains \"domain.com\": unable to generate a certificate for the domains [traefik.domain.com]: error: one or more domains had a problem:\n[traefik.domain.com] [traefik.domain.com] acme: error presenting token: cloudflare: failed to find zone domain.com.: ListZonesContext command failed: error from makeRequest: HTTP request failed: Get \"https://api.cloudflare.com/client/v4/zones?name=domain.com\": net/http: invalid header field value \"Bearer <redacted_token_value>\\n\" for key Authorization\n" providerName=le.acme routerName=kube-system-traefik-dashboard-8029f61ce2558f9ce46c@kubernetescrd rule="Host(`traefik.domain.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
```
