### ISSUE TITLE
IngressRoute-configured Traefik uses different Datadog service for metrics and traces

### ISSUE THREAD

**Issue by tazle** [traefik/traefik#7578]
### IngressRoute-configured Traefik uses different Datadog *service* for metrics and APMs

We are configuring our Traefik using IngressRoutes. We have also configured Traefik to produce metrics and traces to Datadog.

The metrics and traces it produces have different service tags, which makes correlation difficult.

For metrics, the format appears to be:
`<IngressRoute.metadata.namespace>-<IngressRoute.metadata.name>-<some hex identifier>_kubernetescrd`

whereas for `forward_...` traces the service values is:
`<IngressRoute.metadata.namespace>-<IngressRoute.metadata.name>-<some hex identifier>`

### What did you expect to see?

Expected to see same service label on Datadog metrics and traces.

### What did you see instead?

The service label that is present on metrics is not present on traces.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.2
Codename:     picodon
Go version:   go1.15.3
Built:        2020-10-19T18:36:22Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: our-service-name-ingress-route
  namespace: anamespace
spec:
  entryPoints:
    - https
  routes:
    - match: HostRegexp(`our.main.host.name`, `{dpeloymentprefix:.+}.our.main.host.name`)
      kind: Rule
      priority: 1
      services:
        - name: our-service-name-service
          port: 8080
  tls:
    secretName: our-service-tls-cert
```
