### ISSUE TITLE
Add "traefik.http.middlewares.myservice.headers.server" label option

### ISSUE THREAD

**Issue by rogervila** [traefik/traefik#7585]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Traefik comes with some handy configuration options to override default headers, but it seems that there is no way to set the "Server" header.

https://doc.traefik.io/traefik/middlewares/headers/#configuration-options

This would be useful to override the server name header with a custom value, which is a good cybersecurity practice.

If you like the idea I can try to work on a PR.

Thank you.

**Comment by jbdoumenjou** [comment]
Hello @rogervila,

Thanks for your interest in Traefik!

You can already override this header thanks to the [header middleware](https://doc.traefik.io/traefik/v2.3/middlewares/headers/#adding-headers-to-the-request-and-the-response)
For example, you can have a docker-compose like :

```yaml
version: '3.7'

services:
  traefik:
    image: traefik:v2.3
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --entrypoints.http.address=:80
      - --providers.docker

  whoami:
    image: nginx:1.19
    labels:
      traefik.enable: true
      traefik.http.routers.myrouter.rule: Host(`localhost`)
      traefik.http.routers.myrouter.middlewares: testheader
      traefik.http.middlewares.testheader.headers.customResponseHeaders.Server: "foo"
```

So, I close this issue as a question.
