### ISSUE TITLE
[BUG] idleTimeout for transport don't work, it stay to always to 180 sec (default)

### ISSUE THREAD

**Issue by Yivan** [traefik/traefik#7590]
### Do you want to request a *feature* or report a *bug*?

Bug

We looked documentation.

### What did you do?

We have some long request and wanted to increase the `idleTimeout` of `transport` but we are stuck because this settings stay always to 180 seconds whatever value is setted in the toml config file.

The chain is like this:
Traefik -> Apache -> PHP (FPM) -> script PHP.

At PHP, PHP FPM and APACHE timeout are well setted larger.
Doing a curl on apache directly (bypassing traefik so) and having a sleep of 5 min in our PHP script, curl is well exextuted with a timing of 5 min.
Doing a curl on traefik (with this same apache container as backend), we got a "504 Gateway Time-out - The server didn't respond in time." error after 3 min exactly.

We looked all possible trafik settings in documentation and the only one setted to 180s in documentation is `idleTimeout` for `transport`.
So we updated our config by adding `[entryPoints.http.transport]` section:

```
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.proxyProtocol]
      trustedIPs = ["127.0.0.0/8", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "169.254.0.0/16"]
    [entryPoints.http.forwardedHeaders]
      trustedIPs = ["127.0.0.0/8", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "169.254.0.0/16"]
    [entryPoints.http.transport]
      [entryPoints.http.transport.respondingTimeouts]
        # 6 hours timeout
        idleTimeout = 21600
```
We reloaded traefik (logs are ok, it starts well and respond well), we checked the toml config directly in the container in /etc the idleTimeout are well here, so all seems ok at the config level.
But after 3 mins, there is always this gateway errors.

We tried reduce it to 30sec, but always 180sec too.

It seems this `idleTimeout` is totally bypassed.

### What did you expect to see?

We expected that changing `idleTimeout ` will change the timeout.

### What did you see instead?

Timeout is always the same : 180 secs.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.2
Codename:     picodon
Go version:   go1.15.3
Built:        2020-10-19T18:36:22Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
################################################################
# Static configuration
################################################################

[global]
  sendAnonymousUsage = false

[serversTransport]
  insecureSkipVerify = true
  [serversTransport.forwardingTimeouts]
    # Apache KeepAliveTimeout is set at 5 secondes, traefik idleConnTimeout must be lower
    idleConnTimeout = 4

[entryPoints]
    
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.proxyProtocol]
      #insecure = true
      trustedIPs = ["127.0.0.0/8", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "169.254.0.0/16"]
    [entryPoints.http.forwardedHeaders]
      #insecure = true
      trustedIPs = ["127.0.0.0/8", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "169.254.0.0/16"]
    [entryPoints.http.transport]
      [entryPoints.http.transport.respondingTimeouts]
        # 6 hours timeout
        idleTimeout = 21600

  [entryPoints.https]
    address = ":443"
    [entryPoints.https.proxyProtocol]
      trustedIPs = ["127.0.0.0/8", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "169.254.0.0/16"]
    [entryPoints.https.forwardedHeaders]
      trustedIPs = ["127.0.0.0/8", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "169.254.0.0/16"]
    [entryPoints.https.transport]
      [entryPoints.https.transport.respondingTimeouts]
        # 6 hours timeout
        idleTimeout = 21600

  [entryPoints.traefik]
    address = ":${TRAEFIK_PORT}"
    [entryPoints.traefik.proxyProtocol]
      trustedIPs = ["127.0.0.0/8", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "169.254.0.0/16"]
    [entryPoints.traefik.forwardedHeaders]
      trustedIPs = ["127.0.0.0/8", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "169.254.0.0/16"]

  [entryPoints.portainer]
    address = ":${PORTAINER_PORT}"
    [entryPoints.portainer.proxyProtocol]
      trustedIPs = ["127.0.0.0/8", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "169.254.0.0/16"]
    [entryPoints.portainer.forwardedHeaders]
      trustedIPs = ["127.0.0.0/8", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "169.254.0.0/16"]

  [entryPoints.secured]
    address = ":${SECURED_PORT}"
    [entryPoints.secured.proxyProtocol]
      trustedIPs = ["127.0.0.0/8", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "169.254.0.0/16"]
    [entryPoints.secured.forwardedHeaders]
      trustedIPs = ["127.0.0.0/8", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "169.254.0.0/16"]
    [entryPoints.secured.transport]
      [entryPoints.secured.transport.respondingTimeouts]
        # 6 hours timeout
        idleTimeout = 21600

[providers]

  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = false
    swarmMode = false

  [providers.file]
    filename = "/etc/traefik/traefik.toml"
    watch = true

[api]
  #insecure = true
  dashboard = true
  debug = false

[log]
  # Accepted values, in order of severity: "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "PANIC"
  level = "ERROR"

# Uncomment to activate access log ("docker logs tools-traefik" to view them)
[accessLog]


################################################################
# Dynamic configuration
################################################################

[http.routers.api-dashboard]
  entryPoints = ["traefik"]
  #rule = "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
  rule = "Host(`traefik.${COMPOSE_PROJECT_ENV}.${BASE_DOMAIN}`) && PathPrefix(`/`)"
  service = "api@internal"
  middlewares=["tools-traefik-basicauth"]
  [http.routers.api-dashboard.tls]
    options = "mintls12"

[http.middlewares]

  [http.middlewares.redirectscheme-https.redirectScheme]
    scheme = "https"
    permanent = true
    port = "443"

  [http.middlewares.tools-traefik-basicauth.basicAuth]
    users = [
      "${TRAEFIK_LOGIN}:${TRAEFIK_PASSWORD}"
    ]
    usersFile = "${TRAEFIK_HTPASSWD_FILE}"

[tls]

  [[tls.certificates]]
    certFile = "/etc/traefik/certs/shared.crt"
    keyFile = "/etc/traefik/certs/shared.key"

  #[tls.stores]
  #  [tls.stores.default]
  #    [tls.stores.default.defaultCertificate]
  #      certFile = "/etc/traefik/certs/shared.crt"
  #      keyFile  = "/etc/traefik/certs/shared.key"

  [tls.options]
    [tls.options.default]
      minVersion = "VersionTLS10"
      cipherSuites = [
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
        "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
        "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
        "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
        "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"
      ]

    [tls.options.mintls12]
      minVersion = "VersionTLS12"
      cipherSuites = [
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
      ]

```

We use docker provider.

Thanks a lot for reading.
I really hope it could be fixed because we are really stuck, we need more longuer http request wihtout backend response to be possible.

Thanks.
Best regards.
