### ISSUE TITLE
Failed to update ingress status on Traefik 1.7.19

### ISSUE THREAD

**Issue by pvcnt** [traefik/traefik#7598]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I updated a Kubernetes deployment that has an ingress connected to it.

### What did you expect to see?

Be able to access my service through Traefik.

### What did you see instead?

"This site can’t be reached" when trying to navigate to my website, and an error in the logs:
```
{"level":"error","msg":"Cannot update Ingress  myns/myingress due to error: failed to update ingress status myns/myingress: Operation cannot be fulfilled on ingresses.extensions \"myingress\": the object has been modified; please apply your changes to the latest version and try again","time":"2020-11-26T20:59:26Z"}
```

It happened multiple times since I switched to Traefik 1.7.19.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.19
Codename:     maroilles
Go version:   go1.12.12
Built:        2019-10-28_02:07:32PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "info"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
  [entryPoints.prometheus]
  address = ":9100"
[ping]
entryPoint = "http"
[kubernetes]
  [kubernetes.ingressEndpoint]
  publishedService = "kube-system/traefik"
[traefikLog]
  format = "json"
[metrics]
  [metrics.prometheus]
    entryPoint = "prometheus"
```
