### ISSUE TITLE
Can't issue cert via DNS-01 with Cloudflare

### ISSUE THREAD

**Issue by lexfrei** [traefik/traefik#7601]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: longhorn
    meta.helm.sh/release-namespace: longhorn-system
  labels:
    app: longhorn-ingress
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.0.2
  name: longhorn-ingress
  namespace: longhorn-system
spec:
  rules:
  - host: longhorn.k8s.home.lex.la
    http:
      paths:
      - backend:
          serviceName: longhorn-frontend
          servicePort: 80
        pathType: ImplementationSpecific
```

### What did you expect to see?

Valid HTTPS connection to longhorn.k8s.home.lex.la

### What did you see instead?

`time="2020-11-29T09:18:14Z" level=error msg="Unable to obtain ACME certificate for domains \"longhorn.k8s.home.lex.la\": unable to generate a certificate for the domains [longhorn.k8s.home.lex.la]: error: one or more domains had a problem:\n[longhorn.k8s.home.lex.la] [longhorn.k8s.home.lex.la] acme: error presenting token: cloudflare: failed to find zone k8s.home.lex.la.: Zone could not be found\n" routerName=websecure-longhorn-ingress-longhorn-system-longhorn-k8s-home-lex-la@kubernetes rule="Host(`longhorn.k8s.home.lex.la`)" providerName=prodssl.acme`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.3.3
Codename:     picodon
Go version:   go1.15.5
Built:        2020-11-19T17:43:21Z
OS/Arch:      linux/arm64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik

releases:
  # https://artifacthub.io/packages/helm/traefik/traefik
  #
  # Check this page before upgrade
  # https://doc.traefik.io/traefik/migration/v2/
  #
  - name: traefik
    namespace: traefik-system
    chart: traefik/traefik
    version: 9.11.0
    installed: true
    values:
      - service:
          annotations:
            metallb.universe.tf/address-pool: traefik
        additionalArguments:
          # Disable internal ssl check
          - "--serversTransport.insecureSkipVerify=true"
          # SSL for testing
          - "--certificatesresolvers.stagessl.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
          - "--certificatesresolvers.stagessl.acme.dnschallenge.provider=cloudflare"
          - "--certificatesresolvers.stagessl.acme.storage=/data/stage-acme.json"
          # SSL for prod
          - "--certificatesresolvers.prodssl.acme.dnschallenge.provider=cloudflare"
          - "--certificatesresolvers.prodssl.acme.storage=/data/acme.json"
          - "--entrypoints.websecure.http.tls.certresolver=prodssl"
          - "--log.level=DEBUG"
        env:
          - name: CF_DNS_API_TOKEN
            value: XXX
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-11-29T09:18:11Z" level=debug msg="Using DNS Challenge provider: cloudflare" providerName=prodssl.acme
time="2020-11-29T09:18:11Z" level=debug msg="legolog: [INFO] [longhorn.k8s.home.lex.la] acme: Obtaining bundled SAN certificate"
time="2020-11-29T09:18:12Z" level=debug msg="legolog: [INFO] [longhorn.k8s.home.lex.la] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/8946364152"
time="2020-11-29T09:18:12Z" level=debug msg="legolog: [INFO] [longhorn.k8s.home.lex.la] acme: Could not find solver for: tls-alpn-01"
time="2020-11-29T09:18:12Z" level=debug msg="legolog: [INFO] [longhorn.k8s.home.lex.la] acme: Could not find solver for: http-01"
time="2020-11-29T09:18:12Z" level=debug msg="legolog: [INFO] [longhorn.k8s.home.lex.la] acme: use dns-01 solver"
time="2020-11-29T09:18:12Z" level=debug msg="legolog: [INFO] [longhorn.k8s.home.lex.la] acme: Preparing to solve DNS-01"
time="2020-11-29T09:18:13Z" level=debug msg="legolog: [INFO] [longhorn.k8s.home.lex.la] acme: Cleaning DNS-01 challenge"
time="2020-11-29T09:18:13Z" level=debug msg="legolog: [WARN] [longhorn.k8s.home.lex.la] acme: cleaning up failed: cloudflare: failed to find zone k8s.home.lex.la.: Zone could not be found "
time="2020-11-29T09:18:14Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/8946364152"
time="2020-11-29T09:18:14Z" level=error msg="Unable to obtain ACME certificate for domains \"longhorn.k8s.home.lex.la\": unable to generate a certificate for the domains [longhorn.k8s.home.lex.la]: error: one or more domains had a problem:\n[longhorn.k8s.home.lex.la] [longhorn.k8s.home.lex.la] acme: error presenting token: cloudflare: failed to find zone k8s.home.lex.la.: Zone could not be found\n" routerName=websecure-longhorn-ingress-longhorn-system-longhorn-k8s-home-lex-la@kubernetes rule="Host(`longhorn.k8s.home.lex.la`)" providerName=prodssl.acme
```
Same from lego itself (with same token):
```
2020/11/29 12:21:07 [INFO] [longhorn.k8s.home.lex.la] acme: Obtaining bundled SAN certificate
2020/11/29 12:21:07 [INFO] [longhorn.k8s.home.lex.la] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/8946411068
2020/11/29 12:21:07 [INFO] [longhorn.k8s.home.lex.la] acme: Could not find solver for: tls-alpn-01
2020/11/29 12:21:07 [INFO] [longhorn.k8s.home.lex.la] acme: Could not find solver for: http-01
2020/11/29 12:21:07 [INFO] [longhorn.k8s.home.lex.la] acme: use dns-01 solver
2020/11/29 12:21:07 [INFO] [longhorn.k8s.home.lex.la] acme: Preparing to solve DNS-01
2020/11/29 12:21:10 [INFO] cloudflare: new record for longhorn.k8s.home.lex.la, ID 31bca54a57651af5bf1a798af62169c1
2020/11/29 12:21:10 [INFO] [longhorn.k8s.home.lex.la] acme: Trying to solve DNS-01
2020/11/29 12:21:10 [INFO] [longhorn.k8s.home.lex.la] acme: Checking DNS record propagation using [google-public-dns-a.google.com:53 google-public-dns-b.google.com:53]
2020/11/29 12:21:12 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
2020/11/29 12:21:18 [INFO] [longhorn.k8s.home.lex.la] The server validated our request
2020/11/29 12:21:18 [INFO] [longhorn.k8s.home.lex.la] acme: Cleaning DNS-01 challenge
2020/11/29 12:21:19 [INFO] [longhorn.k8s.home.lex.la] acme: Validations succeeded; requesting certificates
2020/11/29 12:21:20 [INFO] [longhorn.k8s.home.lex.la] Server responded with a certificate.

```

Related:
https://github.com/go-acme/lego/issues/1303
