### ISSUE TITLE
 Traefik 2.3.1 KubernetesCRD: Can’t Create IngressRoute on Headless Service 

### ISSUE THREAD

**Issue by popopame** [traefik/traefik#7603]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I tried to create a Traefik IngressRoute and to make it point to a Headless Service (the service point to a DataBase behind the cluster).
Here is an example of the yaml I tried to apply:
```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: webapp-ingressroute
  namespace: traefik
  labels:
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`couchdb.test.io`)
      kind: Rule
      services:
        - name: central-db-service
          kind: Service
          port: 5984
          namespace: dev
  tls:
    secretName: certificate
---
kind: Endpoints
apiVersion: v1
metadata:
  name: central-db-service
  namespace: dev
subsets:
  - addresses:
        - ip: 192.168.0.50
    ports:
      - port: 5984
        name: central-db-service
---
kind: Service
apiVersion: v1
metadata:
  name: central-db-service
  namespace: dev
spec:
  clusterIP: None
  ports:
  - port: 5984
    targetPort: 5984
```

### What did you expect to see?

I expected the IngressRoute to work, and to redirect me on my service.

### What did you see instead?

When I apply the IngressRoute above I get the following logs:
```bash
time="2020-11-29T16:23:25Z" level=error msg="cannot define a port for dev/central-db-service" providerName=kubernetescrd ingress=webapp-ingressroute namespace=traefik
```

And when I try to access the  service I have a 404 not found.

I tried to:
* create the same ingressRoute using an"normal" service, and it worked.
* To deploy the ingressRoute in the same namespace as the service, It did not solve the problem.
* To re-deploy the traefik, same problem

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Docker Image Used: traefik:2.3.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I deployed Traefik using the official traefik Helm chart, I am on premise, and deployed traefik using a NodePort service, Traefik is deployed on it's own namespace, along with cert-manager.

Here is the configuration of the traefik pod:
```yaml
Namespace:    traefik
Containers:
  traefik:
    Image:         traefik:2.3.1
    Image ID:      docker-pullable://traefik@sha256:71dc633dd4241ef34076cf3ab01ddb73ee19744328ffd0726fffad857908055f
    Ports:         9000/TCP, 8000/TCP, 8443/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      --global.checknewversion
      --global.sendanonymoususage
      --entryPoints.traefik.address=:9000/tcp
      --entryPoints.web.address=:8000/tcp
      --entryPoints.websecure.address=:8443/tcp
      --api.dashboard=true
      --ping=true
      --providers.kubernetescrd
      --providers.kubernetesingress
      --log.level=DEBUG
      --accesslog=true
      --accesslog.fields.defaultmode=keep
      --accesslog.fields.headers.defaultmode=drop
      --providers.kubernetesingress.ingressClass=traefik-cert-manager
      --metrics.prometheus=true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-11-29T16:32:12Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetescrd
time="2020-11-29T16:32:13Z" level=error msg="cannot define a port for dev/dev-backend-central-db-service" providerName=kubernetescrd ingress=webapp-ingressroute namespace= traefik
time="2020-11-29T16:32:13Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetescrd
time="2020-11-29T16:32:14Z" level=error msg="cannot define a port for dev/dev-backend-central-db-service" namespace= traefik providerName=kubernetescrd ingress=webapp-ingressroute
time="2020-11-29T16:32:14Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetescrd
time="2020-11-29T16:32:15Z" level=error msg="cannot define a port for dev/dev-backend-central-db-service" ingress=webapp-ingressroute namespace= traefik providerName=kubernetescrd
time="2020-11-29T16:32:15Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetescrd
time="2020-11-29T16:32:16Z" level=error msg="cannot define a port for dev/dev-backend-central-db-service" providerName=kubernetescrd ingress=webapp-ingressroute namespace= traefik
time="2020-11-29T16:32:16Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetescrd
51.210.34.185 - - [29/Nov/2020:16:32:17 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 23619 "ping@internal" "-" 0ms
time="2020-11-29T16:32:17Z" level=error msg="cannot define a port for dev/dev-backend-central-db-service" ingress=webapp-ingressroute providerName=kubernetescrd namespace= traefik
time="2020-11-29T16:32:17Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetescrd
time="2020-11-29T16:32:18Z" level=error msg="cannot define a port for dev/dev-backend-central-db-service" namespace= traefik providerName=kubernetescrd ingress=webapp-ingressroute
time="2020-11-29T16:32:18Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetescrd
time="2020-11-29T16:32:19Z" level=error msg="cannot define a port for dev/dev-backend-central-db-service" namespace= traefik providerName=kubernetescrd ingress=webapp-ingressroute
time="2020-11-29T16:32:19Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetescrd
time="2020-11-29T16:32:21Z" level=error msg="cannot define a port for dev/dev-backend-central-db-service" providerName=kubernetescrd ingress=webapp-ingressroute namespace= traefik
time="2020-11-29T16:32:21Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetescrd
time="2020-11-29T16:32:21Z" level=error msg="cannot define a port for dev/dev-backend-central-db-service" namespace= traefik providerName=kubernetescrd ingress=webapp-ingressroute
time="2020-11-29T16:32:21Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetescrd
51.210.34.185 - - [29/Nov/2020:16:32:21 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 23620 "ping@internal" "-" 0ms
time="2020-11-29T16:32:23Z" level=error msg="cannot define a port for dev/dev-backend-central-db-service" providerName=kubernetescrd ingress=webapp-ingressroute namespace= traefik
time="2020-11-29T16:32:23Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetescrd
time="2020-11-29T16:32:23Z" level=error msg="cannot define a port for dev/dev-backend-central-db-service" namespace= traefik ingress=webapp-ingressroute providerName=kubernetescrd
time="2020-11-29T16:32:23Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetescrd
```
