### ISSUE TITLE
Intermediate 404 error on cluster autoscaling

### ISSUE THREAD

**Issue by sarkistlt** [traefik/traefik#7622]
**This is not the same issue that is related to [upgrading from 2.2.1](https://community.traefik.io/t/consolidated-404-issue-thread-in-versions-since-2-2-1/6865).** 

First time I had this issue (~3 month ago) we were running traefik v1.7.1 (DaemonSet), k8s cluster v1.15.12-gke.20 on GKE. 
Later (~3 month ago) we upgraded to traefik v2.3.1 (DaemonSet), and yesterday that issue happened again.

Basically what is happening on cluster autoscaling sometime new traefik instances don't detect any routs at all, so if I'll make a call directly through those new instances I'm consistently getting 404. 

Restarting them manually does help (but that's not a solution).
In v1.7.1 when this was happening if I would check traefik online dashboard on new instance, it wouldn't show any routs, so looks like new instance having some issues scanning the routs. 
On v2.3.1 when this happened I wasn't able to connect to online dash at all, it was just showing empty page.

We are currently running 12 nodes in our cluster, based on the traffic it may scale to 15-16 nodes, and when this issue happens (and it doesn't happen all the time so supper hard to even try to replicate) we are getting intermediate 404.

My guess is, since restarting those pods does help, is probably when new node is added to cluster and traefik pod is started, maybe that node still doesn't have full access to all operators or cluster resources? Maybe traefik pod is starting too early and when it can't check or find k8s resources it just assumes that there are no routs? But in that case shouldn't it periodically check for resources in case of any k8s operator issues?

_**Current traefik DeamonSet config:**_

```yml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik-ingress-lb
  namespace: kube-system
spec:
  minReadySeconds: 30
  revisionHistoryLimit: 5
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "35%"
  selector:
    matchLabels:
      app: traefik-ingress-lb
      tier: frontend
  template:
    metadata:
      labels:
        app: traefik-ingress-lb
        tier: frontend
    spec:
      priorityClassName: traefik
      restartPolicy: Always
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: DoesNotExist
      containers:
      - name: traefik-ingress-lb
        image: traefik:v2.3.1
        imagePullPolicy: IfNotPresent
        args:
          - --accesslog
          - --accesslog.format=json
          - --accesslog.filters.statuscodes=300-600
          - --accesslog.filters.retryattempts
          - --accesslog.filters.minduration=3s
          - --log
          - --log.level=FATAL
          - --api
          - --api.dashboard
          - --api.insecure
          - --ping
          - --ping.entrypoint=http
          - --entryPoints.metrics.address=:8082
          - --entrypoints.http.address=:80
          - --entrypoints.http.transport.lifecycle.gracetimeout=180
          - --entrypoints.http.transport.respondingtimeouts.idletimeout=360
          - --entrypoints.https.address=:443
          - --entrypoints.https.transport.lifecycle.gracetimeout=180
          - --entrypoints.https.transport.respondingtimeouts.idletimeout=360
          - --hostresolver
          - --hostresolver.cnameflattening
          - --providers.kubernetescrd
          - --providers.kubernetesingress
          - --providers.kubernetesingress.ingressclass=traefik
          - --serverstransport.insecureskipverify
          - --serverstransport.maxidleconnsperhost=-1
        ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
          - containerPort: 8080
            name: admin
        readinessProbe:
          httpGet:
            path: /ping
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 3
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /ping
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: "3Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
```

**Comment by dtomcej** [comment]
@sarkistlt can you reproduce this issue with debug logging enabled?

There are a few reasons that this could happen, but I am suspecting that it may have to do with this:

1. You do not have a meaningful readiness probes configured. As soon as Traefik starts up, you are sending traffic to it.
2. Traefik needs to load all of the resources, and parse them before it can begin routing. This can take a few seconds for the first load to fully sync with the kubernetes API.
3. Since you have no readiness probes, while Traefik is loading your ingress and ingressRoute data (including all of your required certificates), you are sending traffic to it, resulting in the 404s.
4. Once the routes are fully loaded and populated, Traefik automatically uses the data, and your "issue" disappears.

To start with, I would recommend adding a meaningful readiness probe to tell your upstream load balancer that traefik has loaded, and is ready to receive traffic.

If that still does not resolve your problem, I would look further into the debug logs to see what the kubernetes api is responding with.

**Comment by sarkistlt** [comment]
thank you @dtomcej for a quick response. I will increase initialDelaySeconds for readiness prob to 10s, this should be more than enough. 
I can't enable debug logging since this is production cluster with high volume traffic, it may eventually increase latency or create a lot of unused records in our logging platform. It would make sense if I could replicate the issue, but since it happens randomly and I can't replicate it, enabling debug logging won't be ideal.

Also to be honest I don't think it is `readinessProbe`, since if it would be, as you mentioned: ```Once the routes are fully loaded and populated, Traefik automatically uses the data, and your "issue" disappears.```

But it doesn't, that's the issue, it can run for days and it won't auto resolve. The only reason I found this issue because our monitoring systems were alerting periodically for system outages, and google start removing some of our ads, because it was receiving 404 error.

**Comment by dtomcej** [comment]
@sarkistlt There was another issue filed here regarding a kubernetes system that didn't properly mount tokens, meaning that the kubernetes provider couldn't load information from the api:

https://github.com/traefik/traefik/issues/4711

I would also see if some of those suggestions help.

**Comment by sarkistlt** [comment]
I think @recet is right, and probably it's not widely reported because most of the users / companies won't pay too much attention to 404, when it's intermediate and happens only on scaling up and resolves on scaling down, but it is critical when you are running high volume SaaS or any other critical services.

I believe behavior described in that topic is exactly what is happening.

What do you think about solution suggested by @ddtmachado:
```yml
initContainers:
        - name: wait-api
          image: busybox:1.31.1
          command: ['sh', '-c', 'until test -d /var/run/secrets/kubernetes.io/serviceaccount; do echo "Waiting for serviceaccount availability";sleep 1;done;']
```
Sounds like this could work. Or would you suggest to move to Deployment until this issue is fully resolved?
