### ISSUE TITLE
Error while Hello once in a while, restarting Docker fix it

### ISSUE THREAD

**Issue by budimanjojo** [traefik/traefik#7626]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Nothing, it happens by itself once in a while (happened three times now in 7 months of using Traefik in this machine)

### What did you expect to see?
Shouldn't happen all of a sudden

### What did you see instead?
Log is filled with the Error while Hello messages and I can not access some web pages (not all). If I look into the traefik Dashboard, The server address of the problematic service is changed from `http://172.xx.x.x:xx` to `http://36.xx.x.xx:xx`. Or by looking at that I think Traefik is changing the server address from the Docker network to my real public IP address (my ISP public IP starts with 36.xx)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
{"level":"error","msg":"Cannot connect to docker server context canceled","providerName":"docker","time":"2020-11-27T08:30:00Z"}
{"level":"error","msg":"Error while Hello: read tcp 172.20.0.7:80-\u003e80.82.70.118:60000: read: connection reset by peer","time":"2020-11-27T09:20:21Z"}
{"level":"error","msg":"Error while Hello: read tcp 172.20.0.7:80-\u003e34.86.211.97:34060: read: connection reset by peer","time":"2020-11-27T10:51:36Z"}
{"level":"error","msg":"Error while Hello: read tcp 172.20.0.11:80-\u003e185.220.100.243:32978: read: connection reset by peer","time":"2020-12-01T20:19:23Z"}
{"level":"error","msg":"Error while Hello: read tcp 172.20.0.11:80-\u003e80.82.70.118:60000: read: connection reset by peer","time":"2020-12-01T20:42:31Z"}
{"level":"error","msg":"Error while Hello: read tcp 172.20.0.4:80-\u003e80.82.70.118:60000: read: connection reset by peer","time":"2020-12-04T21:06:22Z"}

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
# traefik.yml
global:
    checkNewVersion: true
providers:
    docker:
        watch: true
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false
        network: "traefik_default"
    file:
        watch: true
        filename: "/etc/traefik/dynamic.yml"
entryPoints:
    http:
        address: ":80"
        http:
            redirections:
                entryPoint:
                    to: "https"
                    scheme: "https"
                    permanent: true
        forwardedHeaders:
            trustedIPs:
                - "127.0.0.1"
        proxyProtocol:
            trustedIPs:
                - "127.0.0.1"
    https:
        address: ":443"
        forwardedHeaders:
            trustedIPs:
                - "127.0.0.1"
        proxyProtocol:
            trustedIPs:
                - "127.0.0.1"
api:
    dashboard: true
    debug: true
log:
    level: "ERROR"
    filePath: "/etc/log/traefik.log"
    format: "json"
accesslog:
    filePath: "/etc/log/access.log"
    format: "json"
    filters:
        statusCodes:
            - "200"
            - "300-302"
        retryAttempts: true
certificatesResolvers:
    default:
        acme:
            email: "email@email.com"
            storage: "/etc/acme/acme.json"
            dnsChallenge:
                provider: "cloudflare"
                resolvers:
                    - "1.1.1.1:53"
                    - "1.0.0.1:53"
                delayBeforeCheck: 10

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
