### ISSUE TITLE
Recognize Datadog tracer environment variables

### ISSUE THREAD

**Issue by mckeown-dd** [traefik/traefik#7628]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Datadog tracer supports two environment variables: `DD_AGENT_HOST` and `DD_TRACE_AGENT_PORT`. These are important because in a distributed environment, Docker or K8s, Datadog correlates infra metrics with traces. Hardcoding a value in the config is not best practice when it comes to Datadog. Datadog, in a best practice, is deployed as a daemonset in K8s and one per node in Docker and a trace agent lives on each host. 

In Datadog documentation it recommends setting the DD_AGENT_HOST as such:
```
    apiVersion: apps/v1
    kind: Deployment
     # ...
        spec:
          containers:
          - name: "<CONTAINER_NAME>"
            image: "<CONTAINER_IMAGE>"/"<TAG>"
            env:
              - name: DD_AGENT_HOST
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
```
[this function](https://github.com/traefik/traefik/blob/v2.3.4/pkg/tracing/datadog/datadog.go#L29) which sets default Datadog values
```go
func (c *Config) SetDefaults() {
	c.LocalAgentHostPort = "localhost:8126"
	c.GlobalTag = ""
	c.Debug = false
	c.PrioritySampling = false
}
```
could be rewritten to something like 
```go
func (c *Config) SetDefaults() {
	var host string
	var port string
	ddAgentHost := os.Getenv("DD_AGENT_HOST")
	if ddAgentHost == "" {
		host = "localhost"
	} else {
		host = ddAgentHost
	}
	ddAgentPort := os.Getenv("DD_TRACE_AGENT_PORT")

	if ddAgentPort == "" {
		port = "8126"
	} else {
		port = ddAgentPort
	}
	c.LocalAgentHostPort = net.JoinHostPort(host,port)
	c.GlobalTag = ""
	c.Debug = false
	c.PrioritySampling = false
}
```
to recognize Datadog default values,  accept static config, as well as work with dynamic environments.
