### ISSUE TITLE
Possibility to disable Client-Initiated Secure Renegotiation

### ISSUE THREAD

**Issue by aendeavor** [traefik/traefik#7643]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I would like to see an option to disable **Client-Initiated Secure Renegotiation**. I searched through the docs and the issue tracker but did not find any solution. Can this be implemented, or did I miss something?

**Comment by rtribotte** [comment]
Hello @aendeavor,

Thanks for your interest in Traefik!

It's indeed not configurable. But the default configuration for the TCP server is currently to not allow renegotiation support.
As you can see [here](https://github.com/golang/go/blob/5627a4dc3013fed02c4b8097413643b682cac276/src/crypto/tls/common.go#L702), the default tlsConfig does not support renegotiation.
From what I understand, the current behavior covers your use case.

Have you experimented the opposite?

**Comment by aendeavor** [comment]
Thanks @rtribotte for your answer. Indeed, <https://www.immuniweb.com> reports

![Screenshot_2020-12-09 cloud itbsd com SSL Security Test](https://user-images.githubusercontent.com/44545919/101667686-ee504f00-3a4f-11eb-9660-f3add550106b.png)

on a domain behind Traefik which uses a default TLS configuration for the HTTPS entrypoint where the TLS configuration looks like this:

``` YAML
tls:
  options:
    modern:
      minVersion: VersionTLS13
      sniStrict: true
      curvePreferences:
        - secp521r1
        - secp384r1
        - secp256r1
        - x25519
  
  certificates:
    - certFile: /etc/traefik/public.pem
      keyFile: /etc/traefik/private.pem
```

The TLS configuration is loaded in the dynamic configuration. If this really is/was the default behavior, maybe providing a config overwrites this somehow? Maybe I did somehow overwrite it?

**Comment by jbdoumenjou** [comment]
Hi @aendeavor ,

I created a local stack with the following configuration:

<details>
    <summary>docker-compose.yml</summary>

```yml
version: '3.7'

services:
  traefik:
    image: traefik:v2.3.4
    hostname: whoami
    ports:
      - '80:80'
      - '8080:8080'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/:/etc/traefik/conf/
      - ./certs:/etc/traefik/certs/
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --providers.file.directory=/etc/traefik/conf

  whoami:
    image: traefik/whoami:v1.6.0
    labels:
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.tls: true
      traefik.http.routers.whoami.rule: Host(`whoami.com`)
```
</details>

<details>
    <summary>tls conf</summary>

```yml
# conf/dyn.yml
tls:
  options:
    default:
      minVersion: VersionTLS13
      sniStrict: true
      curvePreferences:
        - secp521r1
        - secp384r1
        - secp256r1
        - x25519

  certificates:
    - certFile: /etc/traefik/certs/whoami.pem
      keyFile: /etc/traefik/certs/whoami-key.pem
```
</details>

I used [testssl](https://github.com/drwetter/testssl.sh) to check this stack with the following command

```
./testssl.sh --openssl /usr/bin/openssl -R whoami:443
```

And I obtained:

```
 Start 2020-12-10 15:20:26        -->> 127.0.0.1:443 (whoami) <<--

 A record via:           /etc/hosts 
 rDNS (127.0.0.1):       --
 Service detected:       HTTP


 Testing for Renegotiation vulnerabilities 

 Secure Renegotiation (RFC 5746)           not vulnerable (OK)
 Secure Client-Initiated Renegotiation     not vulnerable (OK)
```

I tried openssl command too:
```
openssl s_client -connect whoami:443                                                                                                                                         ±[3.1dev]
CONNECTED(00000003)
139876365383040:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:ssl/record/rec_layer_s3.c:1543:SSL alert number 80
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 293 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
```

So, I was not able to validate this vulnerability, could you provide an easy reproducible case?
