### ISSUE TITLE
yaml Parsing - middleware does not exist - upgrade from 2.2 to 2.3

### ISSUE THREAD

**Issue by FloMiau** [traefik/traefik#7657]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Hi, im upgrading from 2.2.x to 2.3.5 and my config broke. The root cause is that I'm using duplicate keys in my yml. See the config below.

### What did you expect to see?

I expected:
1. my config works like before
2. error messages should describe my problem: "there was an yaml-Parsing error: duplicate key"
3. It would be nice if the yaml parser merges the dict. (I think I'm violating the yaml spec here)
4. the migrating docs should be more explanatory about the changes in the yaml-Parser

### What did you see instead?

1. Nearly all pages showed "404 page not found".
2. I got the message "middleware does not exist".

### Output of `traefik version`: (_What version of Traefik are you using?_)

```

Version:      2.3.5
Codename:     picodon
Go version:   go1.15.6
Built:        2020-12-10T16:09:01Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Im using the yaml file provider on Ubuntu.

Working in 2.2, not working in 2.3
```yaml
---
http:
  routers:
    errorpages_example_net-https:
      rule: "Host(`errorpages.example.net`)"

      entryPoints:
        - https
      service: errorpages_example_net
      middlewares:
        - error-middleware
        - add-catcodes
      tls:
        certResolver: letsencrypt-dns

  services:
    errorpages_example_net:
      loadBalancer:
        servers:
          - url: http://192.168.1.105/
        passHostHeader: false

http:
  middlewares:
    error-middleware:
      errors:
        status:
          - "400-599"
        service: errorpages_example_net
        query: "/catcodes/{status}.html"

    add-catcodes:
      addPrefix:
        prefix: "/catcodes"

```

I had to  comment out the http to make it work for 3.3. Im using the duplicate keys for example when the config is longer than one page or when I configure multiple servers/routers that belong to one application:
```yaml
---
http:
  routers:
    errorpages_example_net-https:
      rule: "Host(`errorpages.example.net`)"

      entryPoints:
        - https
      service: errorpages_example_net
      middlewares:
        - error-middleware
        - add-catcodes
      tls:
        certResolver: letsencrypt-dns

  services:
    errorpages_example_net:
      loadBalancer:
        servers:
          - url: http://192.168.1.105/
        passHostHeader: false

# http:
  middlewares:
    error-middleware:
      errors:
        status:
          - "400-599"
        service: errorpages_example_net
        query: "/catcodes/{status}.html"

    add-catcodes:
      addPrefix:
        prefix: "/catcodes"

```
