### ISSUE TITLE
I downloaded an empty plugin zip file

### ISSUE THREAD

**Issue by ytyuanxi** [traefik/traefik#7658]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?

I want to download my plugin oauth2client from pilot

### What did you see instead?

but i download an empty zip file. 

I have successfully run my own userinfo plug-in . they look the same.

### Output of `traefik version`: v2.3.2

```
error: failed to check archive integrity of the plugin github.com/ytyuanxi/oauth2client: plugin integrity check failed

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[experimental.plugins]
  [experimental.plugins.rewritebody]
    modulename = "github.com/traefik/plugin-rewritebody"
    version = "v0.3.1"
  [experimental.plugins.userinfo]
    modulename = "github.com/ytyuanxi/userinfo"
    version = "v1.0.0"
  [experimental.plugins.oauth2client]
   modulename = "github.com/ytyuanxi/oauth2client"
   version = "v3.0.0"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by rtribotte** [comment]
Hello @ytyuanxi,

Thanks for your interest in Traefik!

It seems that you are referencing a version which does not exist. The current version for this plugin is the `v0.0.1`:
```yaml
  experimental:
    plugins:
      oauth2client:
        modulename: github.com/ytyuanxi/oauth2client
        version: v0.0.1
```
I'll close this issue as a question accordingly.
