### ISSUE TITLE
an error format plugin zip

### ISSUE THREAD

**Issue by ytyuanxi** [traefik/traefik#7660]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?

i already download a userinfo plugin, than i want to down another plugin named oauth2client.
i want to see something like this. they all wrote by me.

![image](https://user-images.githubusercontent.com/30840540/102059736-427e7900-3e2c-11eb-94fa-72e1eaed98f7.png)

### What did you see instead?

![image](https://user-images.githubusercontent.com/30840540/102059819-6346ce80-3e2c-11eb-8da4-841babe9da95.png)

### Output of `traefik version`: v2.3.2

![image](https://user-images.githubusercontent.com/30840540/102059674-2bd82200-3e2c-11eb-98dc-31d52cca4ab0.png)

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)

[experimental.plugins]
  [experimental.plugins.rewritebody]
    modulename = "github.com/traefik/plugin-rewritebody"
    version = "v0.3.1"
  [experimental.plugins.userinfo]
    modulename = "github.com/ytyuanxi/userinfo"
    version = "v1.0.0"
  [experimental.plugins.oauth2client]
   modulename = "github.com/ytyuanxi/oauth2client"
   version = "v0.0.1"

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
