### ISSUE TITLE
help: How do I implement the Rewrite function like nginx-controller

### ISSUE THREAD

**Issue by lijingchun0** [traefik/traefik#7662]
### Do you want to request a *feature* or report a *bug*?

feature

### What did you do?
I want  to distinguish items by path like nginx-controller `nginx.ingress.kubernetes.io/rewrite-target` 

- rewrite.bar.com/something rewrites to rewrite.bar.com/
- rewrite.bar.com/something/ rewrites to rewrite.bar.com/
- rewrite.bar.com/something/new rewrites to rewrite.bar.com/new

Now I pass the stripPrefix middleware  but some 404 errors

### What did you see instead?

![image](https://user-images.githubusercontent.com/26979634/102068986-208af380-3e38-11eb-83b1-97feb5cf4891.png)
![image](https://user-images.githubusercontent.com/26979634/102069090-43b5a300-3e38-11eb-9b01-d7ede6353fcf.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik v2.3.3 installed via helm in k8s 1.9
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: jenkins
spec:
  stripPrefix:
    prefixes:
      - /jenkins

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-jenkins
spec:
  routes:
  - match: Host(`test.example.com`) && PathPrefix(`/jenkins`)
    kind: Rule
    services:
    - name: jenkins
      port: 80
    middlewares:
    - name: jenkins
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
