### ISSUE TITLE
Deploying with an empty Host rule breaks all routing in Docker / Docker Swarm

### ISSUE THREAD

**Issue by ddtmachado** [traefik/traefik#7679]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

1. deployed Traefik with docker-compose and the docker provider enabled
2. deployed a few docker apps with Traefik labels (also added labels for Dashboard access)
3. checked everything was fine and working
4. deployed this app:

```yaml
version: "3.3"
services:
  whoami-http:
    image: "containous/whoami:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.rule=(Host(``) && PathPrefix(`/hammered`))"
```

5. All routing is broken

### What did you expect to see?

My latest router config failing with a message: "empty args for matcher Host, []" as it would on the file provider.

### What did you see instead?

All requests failing, including Dashboard access which uses an internal service, with `Gateway timeout`.

```bash
$ curl traefik.docker.localhost
Gateway Timeout
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.5
Codename:     picodon
Go version:   go1.15.6
Built:        2020-12-10T16:09:01Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
log:
  level: "DEBUG"

api:
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker: { }
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```raw
traefik_1  | time="2020-12-16T20:17:42Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL="http://172.19.0.2:80" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api/overview\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"application/json, text/plain, */*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7,nl;q=0.6,fr;q=0.5\"],\"Connection\":[\"keep-alive\"],\"Referer\":[\"http://traefik.docker.localhost/dashboard/\"],\"Sec-Fetch-Dest\":[\"empty\"],\"Sec-Fetch-Mode\":[\"cors\"],\"Sec-Fetch-Site\":[\"same-origin\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36\"],\"X-Forwarded-Host\":[\"traefik.docker.localhost\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"16a133d62f4b\"],\"X-Real-Ip\":[\"172.18.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"traefik.docker.localhost\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.18.0.1:57798\",\"RequestURI\":\"/api/overview\",\"TLS\":null}"
traefik_1  | time="2020-12-16T20:17:43Z" level=debug msg="'504 Gateway Timeout' caused by: dial tcp 172.19.0.2:80: i/o timeout"
```
