### ISSUE TITLE
Traefik access log HTTP 499, client and backend server HTTP 200

### ISSUE THREAD

**Issue by mr-manuel** [traefik/traefik#7681]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I opened a normal webpage that is published through the Traefik reverse proxy

### What did you expect to see?
I expected to see the same HTTP status code on backend server, Traefik and client.

### What did you see instead?
I see a HTTP 200 status code in the webserver access log, a HTTP 499 status code in Traefik access log and a HTTP 200 status code in the browser.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.3.5
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[entryPoints.web]
    address = ":80"

[entryPoints.web-secure]
    address = ":443"

[serversTransport]
    insecureSkipVerify = true
    [serversTransport.forwardingTimeouts]
        dialTimeout = "30s"

[log]
    filePath = "/var/log/traefik/error.log"
    format = "json"
    level  = "DEBUG"

[accessLog]
    filePath = "/var/log/traefik/access.log"
    format        = "json"
    bufferingSize = 100
    [accessLog.fields.headers.names]
        "origin_Location"   = "keep"
        "User-Agent"        = "keep"
        "X-Forwarded-Host"  = "keep"
        "X-Forwarded-Port"  = "keep"
        "X-Forwarded-Proto" = "keep"
```

```toml
[http.routers.domain_tld__tls]
    entryPoints = ["web-secure"]
    rule = "Host(`domain.tld`,`www.domain.tld`)"
    service = "domain_tld__tls"

[http.routers.domain_tld]
    entryPoints = ["web"]
    rule = "Host(`domain.tld`,`www.domain.tld`)"
    service = "domain_tld__tls"

[[http.services.domain_tld__tls.loadBalancer.servers]]
    url = "https://33.33.33.33"

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

<details>
<summary>backend server access log (ip 33.33.33.33)</summary>

```
22.22.22.22 - - [16/Dec/2020:21:17:08 +0100] "POST /wp-admin/admin-ajax.php HTTP/2.0" 200 47 "https://domain.tld/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Foverview" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
```

</details>

<details>
<summary>Traefik access log (ip 22.22.22.22)</summary>

```json
{"Request":
    "{
        \"Method\":\"POST\",
        \"URL\":{\"Scheme\":\"\",
        \"Opaque\":\"\",
        \"User\":null,
        \"Host\":\"\",
        \"Path\":\"/wp-admin/admin-ajax.php\",
        \"RawPath\":\"\",
        \"ForceQuery\":false,
        \"RawQuery\":\"\",
        \"Fragment\":\"\",
        \"RawFragment\":\"\"},
        \"Proto\":\"HTTP/2.0\",
        \"ProtoMajor\":2,
        \"ProtoMinor\":0,
        \"Header\":
        {
            \"Accept\":[\"application/json,text/javascript,*/*; q=0.01\"],\"Accept-Encoding\":[\"gzip,deflate,br\"],\"Accept-Language\":[\"de-DE,en-US;q=0.8,en;q=0.5,it;q=0.3\"],
            \"Cache-Control\":[\"no-cache\"],
            \"Content-Length\":[\"98\"],
            \"Content-Type\":[\"application/x-www-form-urlencoded; charset=UTF-8\"],
            \"Cookie\":[\"wordpress_sec_0e918asdfasdfasdfasdf0e398448d=user%40domain.tld%7C160831453asdfasdfasdfasdfasdfQt9ibI1u3ZeYq2wB0ckL6N4u8p%7Cca7c5aeasdfasdfasdfasdfasdfe63cbe8954726d13eb9d094a10; wordpress_0e91806asdfasdfasdfasdf8448d_xframe=bceasdfasdfasdfasdf981; wp-settings-time-2=16asdfasdfasdfasdf5; wp-settings-2=libraryContent%3Dbrowse; wordpress_test_cookie=WP%20Cookie%20check; wordpress_logged_in_0e9asdfasdfasdfasdfasdf448d=user%40domain.tld%7C1608asdfasdf533%7asdfasdfasdfasdfasdfp%7C4c87fa7asdfasdfasdfasdfasdfasdf3f; tk_ai=woo%3AoRasdfasdfasdfasdfasdfLGn; tk_tc=casdfasdfasdfasdfnfR%2BGE; tk_qs=; tk_qs=\"],
            \"Origin\":[\"https://domain.tld\"],
            \"Pragma\":[\"no-cache\"],
            \"Referer\":[\"https://domain.tld/wp-admin/admin.php?page=wc-admin\\u0026path=%2Fanalytics%2Foverview\"],
            \"Te\":[\"trailers\"],
            \"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"],
            \"X-Forwarded-Host\":[\"domain.tld\"],
            \"X-Forwarded-Port\":[\"443\"],
            \"X-Forwarded-Proto\":[\"https\"],
            \"X-Forwarded-Server\":[\"traefik\"],
            \"X-Real-Ip\":[\"11.11.11.11\"],
            \"X-Requested-With\":[\"XMLHttpRequest\"]
        },
        \"ContentLength\":98,
        \"TransferEncoding\":null,
        \"Host\":\"domain.tld\",
        \"Form\":null,
        \"PostForm\":null,
        \"MultipartForm\":null,
        \"Trailer\":null,
        \"RemoteAddr\":\"11.11.11.11:59903\",
        \"RequestURI\":\"/wp-admin/admin-ajax.php\",
        \"TLS\":null
    }",
    "level":"debug",
    "msg":"vulcand/oxy/roundrobin/rr: begin ServeHttp on request",
    "time":"2020-12-16T21:17:08+01:00"
}
{
    "ForwardURL":{
        "Scheme":"https",
        "Opaque":"",
        "User":null,
        "Host":"33.33.33.33",
        "Path":"",
        "RawPath":"",
        "ForceQuery":false,
        "RawQuery":"",
        "Fragment":"",
        "RawFragment":""
    },
    "Request":"{\"Method\":\"POST\",\"URL\":
    {
        \"Scheme\":\"\",
        \"Opaque\":\"\",
        \"User\":null,
        \"Host\":\"\",
        \"Path\":\"/wp-admin/admin-ajax.php\",
        \"RawPath\":\"\",
        \"ForceQuery\":false,
        \"RawQuery\":\"\",
        \"Fragment\":\"\",
        \"RawFragment\":\"\"
    },
    \"Proto\":\"HTTP/2.0\",
    \"ProtoMajor\":2,
    \"ProtoMinor\":0,
    \"Header\":
    {
        \"Accept\":[\"application/json,text/javascript,*/*; q=0.01\"],
        \"Accept-Encoding\":[\"gzip,deflate,br\"],
        \"Accept-Language\":[\"de-DE,en-US;q=0.8,en;q=0.5,it;q=0.3\"],
        \"Cache-Control\":[\"no-cache\"],
        \"Content-Length\":[\"98\"],
        \"Content-Type\":[\"application/x-www-form-urlencoded; charset=UTF-8\"],
        \"Cookie\":[\"wordpress_sec_0e91asdfasdfasdfasdf160e398448d=user%40domain.tld%7C1sdfgsdfg14533%7CNt8X6Zu6FNsrgwWEPQt9sdfgfsdfgfsdfgfsdfgfsdfgfs4726d13eb9d094a10; wordpress_0e918060sdfgfsdfgfsdfgsdfgf398448d_xframe=bceda9112sdfgfsdfgfsdfgsdfgfsdfgf0e2264981; wp-settings-time-2=1608142465; wp-settings-2=libraryContent%3Dbrowse; wordpress_test_cookie=WP%20Cookie%20check; wordpress_logged_in_0e918sdfgsdfgfsdfgfsdfgsdfgsdf448d=user%40domain.tld%7C16083asdfasdf33%asdfasdf8X6Zu6FNsrgwWEPasdfasdfasdfB0ckL6N4u8p%7C4c87fa73f989361e0cf46asdfasdfasdfasdfasdf4045688a52f23f; tk_ai=woo%3AoR7VJ0wDasdfasdfasdfasdfWS3dDLGn; tk_tc=cEhyiasdfasdfasdffR%2BGE; tk_qs=; tk_qs=\"],
        \"Origin\":[\"https://domain.tld\"],
        \"Pragma\":[\"no-cache\"],
        \"Referer\":[\"https://domain.tld/wp-admin/admin.php?page=wc-admin\\u0026path=%2Fanalytics%2Foverview\"],
        \"Te\":[\"trailers\"],
        \"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\"],
        \"X-Forwarded-Host\":[\"domain.tld\"],
        \"X-Forwarded-Port\":[\"443\"],
        \"X-Forwarded-Proto\":[\"https\"],
        \"X-Forwarded-Server\":[\"traefik\"],
        \"X-Real-Ip\":[\"11.11.11.11\"],
        \"X-Requested-With\":[\"XMLHttpRequest\"]
    },
    \"ContentLength\":98,
    \"TransferEncoding\":null,
    \"Host\":\"domain.tld\",
    \"Form\":null,
    \"PostForm\":null,
    \"MultipartForm\":null,
    \"Trailer\":null,
    \"RemoteAddr\":\"11.11.11.11:59903\",
    \"RequestURI\":\"/wp-admin/admin-ajax.php\",
    \"TLS\":null}",
    "level":"debug",
    "msg":"vulcand/oxy/roundrobin/rr: Forwarding this request to URL",
    "time":"2020-12-16T21:17:08+01:00"
}
```

</details>

<details>
<summary>client browser status (ip 11.11.11.11)</summary>

![grafik](https://user-images.githubusercontent.com/12592765/102407573-9b950b00-3fec-11eb-8947-c9d19d581fdc.png)

</details>

If there is some data/logs/information missing, please let me know. There is a lot of different URL that throw HTTP 499 only on Traefik.

Edit: Changed to minimum configuration
