### ISSUE TITLE
two hosts in one kuberntes Ingress not work

### ISSUE THREAD

**Issue by kong62** [traefik/traefik#7682]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
when I set two hosts: `wanda-remote-api-sit.hupu.io` and  `wanda-remote-api.sit.hupu.io` to one kubernetes ingress, it not working. 

### What did you expect to see?

wanda-remote-api-sit.hupu.io   ok
wanda-remote-api.sit.hupu.io   ok

### Output of `traefik version`: (_What version of Traefik are you using?_)
v2.3.4

test one:( two ingresses)
```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app: wanda-remote-api
    env: sit
  name: wanda-remote-api
  namespace: sit
spec:
  rules:
  - host: wanda-remote-api-sit.hupu.io
    http:
      paths:
      - backend:
          serviceName: wanda-remote-api-grpc
          servicePort: 8088
        path: /grpc
      - backend:
          serviceName: wanda-remote-api
          servicePort: 8080
        path: /
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app: wanda-remote-api
    env: sit
  name: wanda-remote-api-new
  namespace: sit
spec:
  rules:
  - host: wanda-remote-api.sit.hupu.io
    http:
      paths:
      - backend:
          serviceName: wanda-remote-api-grpc
          servicePort: 8088
        path: /grpc
      - backend:
          serviceName: wanda-remote-api
          servicePort: 8080
        path: /

# curl -H "Host: wanda-remote-api-sit.hupu.io" 192.168.38.2/info 
ok

# curl -H "Host: wanda-remote-api.sit.hupu.io" 192.168.38.2/info  
ok
```

test two:(one ingress, two host)
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app: wanda-remote-api
    env: sit
  name: wanda-remote-api
  namespace: sit
spec:
  rules:
  - host: wanda-remote-api-sit.hupu.io
    http:
      paths:
      - backend:
          serviceName: wanda-remote-api-grpc
          servicePort: 8088
        path: /grpc
      - backend:
          serviceName: wanda-remote-api
          servicePort: 8080
        path: /
  - host: wanda-remote-api.sit.hupu.io
    http:
      paths:
      - backend:
          serviceName: wanda-remote-api-grpc
          servicePort: 8088
        path: /grpc
      - backend:
          serviceName: wanda-remote-api
          servicePort: 8080
        path: /

# curl -H "Host: wanda-remote-api-sit.hupu.io" 192.168.38.2/info 
404 not found

# curl -H "Host: wanda-remote-api.sit.hupu.io" 192.168.38.2/info  
ok

```

test three:(one ingress, two host)
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app: wanda-remote-api
    env: sit
  name: wanda-remote-api
  namespace: sit
spec:
  rules:
  - host: wanda-remote-api-sit.hupu.io
    http:
      paths:
      - backend:
          serviceName: wanda-remote-api-grpc
          servicePort: 8088
        path: /grpc
      - backend:
          serviceName: wanda-remote-api
          servicePort: 8080
        path: /
  - host: wanda-remote-api.sitx.hupu.io
    http:
      paths:
      - backend:
          serviceName: wanda-remote-api-grpc
          servicePort: 8088
        path: /grpc
      - backend:
          serviceName: wanda-remote-api
          servicePort: 8080
        path: /

# curl -H "Host: wanda-remote-api-sit.hupu.io" 192.168.38.2/info 
ok

# curl -H "Host: wanda-remote-api.sitx.hupu.io" 192.168.38.2/info  
ok
```
