### ISSUE TITLE
Dashboard / API | See TLSStore, TLSOptions, and certificate loaded by kubernetes

### ISSUE THREAD

**Issue by melck** [traefik/traefik#7685]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Hello, i would love to see more informations in dashboard about TLSStore, TLSOptions and certificates (imported or lets encrypt) in dashboard.

**Comment by rtribotte** [comment]
Hello @melck,

Thanks for your interest in Traefik!

Can you detail how you would see this implemented, what are the specific data you would like to see?
Due to the sensitivity of certificate data, we currently not expose it through the API on purpose.

**Comment by melck** [comment]
I would love to see without watching logs :
- List of TLSStore loaded by Traefik (their names and options)
- List of Certificates loaded by Traefik (Certificates added manualy or created through letsencrypt and maybe some details about expiration, name, CN, SAN). 

Actually i have no way to see what's is loaded for debugging / learning purposes.

**Comment by adamdecaf** [comment]
It would be great to see the most recent errors from attempting to generate certificates as well.

**Comment by obeyler** [comment]
By example does the TLSStore need to be set on default or it can be set inside traefik namespace ? (I don't want to put the secret with the TLS certificate inside the default namespace). Like this:
```
      apiVersion: traefik.containo.us/v1alpha1
      kind: TLSStore
      metadata:
        name: default
        namespace: traefik
      spec:
        defaultCertificate:
          secretName: tls-certificate
```

and so on the tls-certificate is located into a secret inside traefik namespace

I ask that in reference of the doc https://doc.traefik.io/traefik/v2.4/routing/providers/kubernetes-crd/#kind-tlsstore
who document the tls store but put it in `default` namespace

I also note that all example of IngressRoute inside the #Declaring and referencing a TLSOption   https://doc.traefik.io/traefik/v2.4/routing/providers/kubernetes-crd/#kind-tlsoption are made by using 'web' as entry point instead of 'websecure'
