### ISSUE TITLE
Wildcard(*) in ingress.spec.host is not honored

### ISSUE THREAD

**Issue by avdhoot** [traefik/traefik#7691]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
Request  to  `*.somthing.svc.foo.bar/api` goes to to correct svc ie `k8s-service-app`

### What did you see instead?
Request  to `somthing.svc.foo.bar/api` goes to **correct** svc.
Request  to  `*.somthing.svc.foo.bar/api` goes to to **incorrect**(default) svc.  

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.3
Codename:     picodon
Go version:   go1.15.5
Built:        2020-11-19T17:43:21Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
#traefik.yaml
serversTransport:
  insecureSkipVerify: true
entryPoints:
  http:
    address: :8080
    proxyProtocol:
      trustedIPs:
      - 10.0.0.0/8
  https:
    address: :8443
    http:
      tls: {}
    proxyProtocol:
      trustedIPs:
      - 10.0.0.0/8
  traefik:
    address: :8888
  ping:
    address: :9000
providers:
  providersThrottleDuration: 2s
  kubernetesIngress:
    ingressEndpoint:
      publishedService: traefik/traefik
  kubernetesCRD: {}
tls:
  options:
    default:
      minVersion: "VersionTLS11"
api:
  insecure: true
ping: 
  entryPoint: "ping"
metrics:
  prometheus: {}
log:
  level: DEBUG
  format: json
accessLog:
  format: json
  fields:
    defaultMode: keep
    names:
      ServiceURL: keep
      ServiceName: keep
      RouterName: kep
      ClientAddr: keep
      Duration: keep
      OriginDuration: keep
      OriginStatus: keep
      RequestMethod: keep
      RequestPath: keep
      RequestProtocol: keep
      RequestUserAgentHeader: keep
      RetryAttempts: keep
      headers: keep
    headers:
      defaultMode: drop
      names:
        CF-Connecting-IP: keep
        User-Agent: keep
        X-Forwarded-For: keep

```
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: k8s-service
  namespace: my-path
spec:
  rules:
  - host: '*.somthing.svc.foo.bar'
    http:
      paths:
      - backend:
          serviceName: k8s-service-app
          servicePort: 8000
        path: /my-path
      - backend:
          serviceName: k8s-service-app
          servicePort: 8000
        path: /api
  - host: '*.somthing.api.foo.bar'
    http:
      paths:
      - backend:
          serviceName: k8s-service-app
          servicePort: 8000
        path: /my-path
      - backend:
          serviceName: k8s-service-app
          servicePort: 8000
        path: /api
  - host: somthing.svc.foo.bar
    http:
      paths:
      - backend:
          serviceName: k8s-service-app
          servicePort: 8000
        path: /my-path
      - backend:
          serviceName: k8s-service-app
          servicePort: 8000
        path: /api
  - host: somthing.api.foo.bar
    http:
      paths:
      - backend:
          serviceName: k8s-service-app
          servicePort: 8000
        path: /my-path
      - backend:
          serviceName: k8s-service-app
          servicePort: 8000
        path: /api
```
There is **no** `*` in dashboard rule. 
![no-star](https://user-images.githubusercontent.com/1314627/102627000-94493b00-416d-11eb-878f-9fc54dd3bb63.png)

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
