### ISSUE TITLE
Weighted round robin with healthcheck

### ISSUE THREAD

**Issue by michaelcplusplus** [traefik/traefik#7693]
### Do you want to request a feature or report a bug?

Feature

### What did you do?

Configure two servers with weighted round robin and health checks.

### What did you expect to see?

If one of the two servers is offline then the whole traffic should be routed to the other server.

### What did you see instead?
Traefik response with 503 Service unavailable if the request ist dispatched to the offline server.
It seems to me that the health check did not remove the unhealthy server from the wrr service list.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.3.1
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-29T15:49:06Z
OS/Arch:      windows/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
# traefik.yaml
entryPoints:
  wsp-1:
    address: ":8080"
  traefik:
    address: ":9090"
  debug: true
  
api:
  dashboard: true
  insecure: true
  debug: true

log:
  filePath: "d:/projects/golang/traefik/traefik.log"
  level: INFO

providers:
  file:
    filename: d:\projects\golang\traefik\dynamic.simple.yaml
    watch: true
```

```yaml
# dynamic.simple.yaml
http:
   routers:
      wsp-router-1:
         rule: PathPrefix(`/`)
         entryPoints:
         - wsp-1
         service: wsp-service
   services:
      wsp-service:
         weighted:
            services:
            -  name: wsp1
               weight: 3
            -  name: wsp2
               weight: 1
      wsp1:
         loadBalancer:
            healthCheck:
               path: /status
               interval: 10s
               timeout: 3s
            servers:
            -  url: http://localhost:8081
      wsp2:
         loadBalancer:
            healthCheck:
               path: /status
               interval: 10s
               timeout: 3s
            servers:
            -  url: http://localhost:8082
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-12-18T17:39:21+01:00" level=info msg="Traefik version 2.3.1 built on 2020-09-29T15:49:06Z"
time="2020-12-18T17:39:21+01:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
time="2020-12-18T17:39:21+01:00" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2020-12-18T17:39:21+01:00" level=info msg="Starting provider *file.Provider {\"watch\":true,\"filename\":\"d:\\\\projects\\\\golang\\\\traefik\\\\dynamic.simple.yaml\"}"
time="2020-12-18T17:39:21+01:00" level=info msg="Starting provider *traefik.Provider {}"
time="2020-12-18T17:40:03+01:00" level=warning msg="Health check failed, removing from server list. Backend: \"wsp1@file\" URL: \"http://localhost:8081\" Weight: 1 Reason: HTTP request failed: Get \"http://localhost:8081/status\": dial tcp [::1]:8081: connectex: No connection could be made because the target machine actively refused it."
time="2020-12-18T17:40:13+01:00" level=warning msg="Health check still failing. Backend: \"wsp1@file\" URL: \"http://localhost:8081\" Reason: HTTP request failed: Get \"http://localhost:8081/status\": dial tcp [::1]:8081: connectex: No connection could be made because the target machine actively refused it."

```
