### ISSUE TITLE
Provide more realistic examples

### ISSUE THREAD

**Issue by marcbria** [traefik/traefik#7700]
Traefik's documentation is great but sometimes you can find examples like this:

https://github.com/traefik/traefik/blob/3ff83fc1f8281851e56dcc5f18600be8fbb6fe9f/docs/content/reference/dynamic-configuration/file.yaml#L5

It's a great example but the use of "foobar" is excesive and don't let you understand the references or make searches in the example.

To make it easier to follow, I would encourage to modify to something like this:

```yaml
http:
  routers:
    Router0:
      entryPoints:
      - varWebInsecure
      - varWebSecure
...
```

The "var" prefix will let you know that's something to change and the name will make the example more realistic and significative.

Thanks a lot for the great project.
