### ISSUE TITLE
Dynamic file does not take effect

### ISSUE THREAD

**Issue by AP0rPi7uQ9** [traefik/traefik#7709]
```yaml
version: '3'
    
services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    environment:
    - TZ=Asia/Shanghai
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      - "443:443"
    restart: on-failure
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yaml:/traefik.yaml
      - ./traefik/config:/traefik
      - ./traefik/log:/etc/traefik/log
    networks:
      em:
       ipv4_address: 10.0.0.2
```

Environment: Windows 10 uses Docker Desktop
Image: traefik v2.4
Operating:
1. When I change the dynamic configuration file in the windows mount directory(for example: Edit ./traefik/config/xxxxx.yaml), traefik does not take effect, and traefik must be restarted to take effect dynamic configuration.
2. When I enter the docker container and modify the dynamic configuration file, traefik dynamic configuration is take effect.

How to solve the first point? I don't want to enter the container every time

**Comment by ldez** [comment]
Hello,

---

https://doc.traefik.io/traefik/v2.3/getting-started/configuration-overview/#the-static-configuration
> There are three different, mutually exclusive (e.g. you can use only one at the same time), ways to define static configuration options in Traefik:

So you cannot use cli flags (`command: --api.insecure=true --providers.docker`) and file (`- ./traefik/traefik.yaml:/traefik.yaml) at  the same time to define the static configuration.

---

Also to be able to use a file as a dynamic configuration, you must enable the file provider.
https://doc.traefik.io/traefik/v2.3/providers/file/

**Comment by AP0rPi7uQ9** [comment]
@ldez 
Thank you for your kind reply.

I modified it, but it still doesn't work

I can open the dashboard normally. 
But the modification of the dynamic configuration does not take effect , Can only be restarted to take effect.

System:Windows 10 Pro 10.0.19041 Build 19041
Software:Docker Desktop community version 2.3.0.4(46911) stable  (with linux container)
Image: traefik v2.4

I tried to use them in  Debian+Docker  and they are normal. This is a bug in windows??


> docker-compose.yml
```yaml
version: '3'
    
services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    environment:
    - TZ=Asia/Shanghai
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      - "443:443"
    restart: on-failure
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yaml:/traefik.yaml
      - ./traefik/config:/traefik
      - ./traefik/log:/etc/traefik/log
    networks:
      em:
       ipv4_address: 10.0.0.2
```

> traefik/config/dashboard.yaml

```yaml
http:
 routers:
  dashboard:
   entryPoints:
   - "dashboard"
   rule: (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
   service: api@internal
   middlewares:
    - auth

 middlewares:
  auth:
   basicAuth:
    users:
    - "admin:$apr1$sadEhKwW$BNpyOakcbLp/P7JyP5ghs0"     # admin admin
```
