### ISSUE TITLE
Docker deploying traefik error

### ISSUE THREAD

**Issue by alan-et** [traefik/traefik#7713]
command traefik error: read /etc/traefik/traefik.toml: is a directory

docker-compose.yml config

```
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.3
    container_name: traefik
    # restart: always
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
```
start-up
```
docker-compose up -d reverse-proxy
```
log
```
2020-12-29T02:53:24.234761300Z 2020/12/29 02:53:24 command traefik error: read /etc/traefik/traefik.toml: is a directory
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by alan-et** [comment]
It's OK to change it to this
```
version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.3
    container_name: traefik
    # restart: always
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - ./:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
```
