### ISSUE TITLE
Netcup ACME-DNS challenge fails for .com domains

### ISSUE THREAD

**Issue by renekaesler** [traefik/traefik#7719]
### What did you do?

Generating a wildcard certificate for my `de` domain works as it should. But as soon as I try to generate a wildcard certificate for my 'com' domain the dns challenge fails.

### What did you expect to see?

The domain name of the `updateDnsRecords` request should be identical to the defined domains in the `docker-comose.yml`.

### What did you see instead?

By monitoring the **updateDnsRecords** request you can see, that the top level domain has been sent in uppercase:

![updateDnsRecods](https://user-images.githubusercontent.com/13448180/103468543-3e25eb80-4d5a-11eb-8655-212426d4aa15.png)

Netcup only supports lowercase top level domains, as defined in thier webservice definition (simpleType name="domainname"):
https://ccp.netcup.net/run/webservice/xsd/simpletypes.xsd

--> The uppercase top level domain does not match with the netcup requirements & so the TXT record will not be added. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik version 2.3.6 built on 2020-12-17T16:34:27Z
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
version: '3'

services:
  traefik:
    image: traefik:v2.3
    container_name: traefik
    command:
      - --certificatesresolvers.netcup.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.netcup.acme.dnschallenge=true
      - --certificatesresolvers.netcup.acme.dnschallenge.delaybeforecheck=600
      - --certificatesresolvers.netcup.acme.dnschallenge.provider=netcup
      - --certificatesresolvers.netcup.acme.email=rene.kaesler@gmail.com
      - --certificatesresolvers.netcup.acme.storage=/letsencrypt/acme.json

      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.to=websecure

      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=netcup
      - --entrypoints.websecure.http.tls.domains[0].main=renekaesler.com
      - --entrypoints.websecure.http.tls.domains[0].sans=*.renekaesler.com
      - --entrypoints.websecure.http.tls.domains[1].main=renekaesler.de
      - --entrypoints.websecure.http.tls.domains[1].sans=*.renekaesler.de

      - --log.level=DEBUG

      - --providers.docker.exposedbydefault=false
      - --providers.docker=true
    environment:
      - NETCUP_API_KEY=${ACME_NC_APIKEY}
      - NETCUP_API_PASSWORD=${ACME_NC_APIPW}
      - NETCUP_CUSTOMER_NUMBER=${ACME_NC_CID}
    labels:
      - traefik.enable=true

      - traefik.http.middlewares.non-de.redirectregex.permanent=true
      - traefik.http.middlewares.non-de.redirectregex.regex=^(?:https|http):\/\/([a-z-]+)\.renekaesler\.de(.*)
      - traefik.http.middlewares.non-de.redirectregex.replacement=https://$${1}.renekaesler.com$${2}

      - traefik.http.middlewares.non-www.redirectregex.permanent=true
      - traefik.http.middlewares.non-www.redirectregex.regex=^(?:https|http):\/\/www\.(.*)
      - traefik.http.middlewares.non-www.redirectregex.replacement=https://$${1}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./mounts/traefik/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
<details>
<summary>logs</summary>

```console
$ docker-compose up
Creating network "landscape_default" with the default driver
Creating traefik ... done
Attaching to traefik
traefik    | time="2021-01-02T22:12:24Z" level=info msg="Configuration loaded from flags."
traefik    | time="2021-01-02T22:12:24Z" level=info msg="Traefik version 2.3.6 built on 2020-12-17T16:34:27Z"
traefik    | time="2021-01-02T22:12:24Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"web\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{\"redirections\":{\"entryPoint\":{\"to\":\"websecure\",\"scheme\":\"https\",\"permanent\":true,\"priority\":2147483647}}}},\"websecure\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{\"tls\":{\"certResolver\":\"netcup\",\"domains\":[{\"main\":\"renekaesler.com\",\"sans\":[\"*.renekaesler.com\"]},{\"main\":\"renekaesler.de\",\"sans\":[\"*.renekaesler.de\"]}]}}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":15000000000}},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"certificatesResolvers\":{\"netcup\":{\"acme\":{\"email\":\"rene.kaesler@gmail.com\",\"caServer\":\"https://acme-staging-v02.api.letsencrypt.org/directory\",\"storage\":\"/letsencrypt/acme.json\",\"keyType\":\"RSA4096\",\"dnsChallenge\":{\"provider\":\"netcup\",\"delayBeforeCheck\":600000000000}}}}}"
traefik    | time="2021-01-02T22:12:24Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
traefik    | time="2021-01-02T22:12:24Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
traefik    | time="2021-01-02T22:12:24Z" level=debug msg="Start TCP Server" entryPointName=web
traefik    | time="2021-01-02T22:12:24Z" level=debug msg="Start TCP Server" entryPointName=websecure
traefik    | time="2021-01-02T22:12:24Z" level=info msg="Starting provider *traefik.Provider {}"
traefik    | time="2021-01-02T22:12:24Z" level=info msg="Starting provider *acme.Provider {\"email\":\"rene.kaesler@gmail.com\",\"caServer\":\"https://acme-staging-v02.api.letsencrypt.org/directory\",\"storage\":\"/letsencrypt/acme.json\",\"keyType\":\"RSA4096\",\"dnsChallenge\":{\"provider\":\"netcup\",\"delayBeforeCheck\":600000000000},\"ResolverName\":\"netcup\",\"store\":{},\"ChallengeStore\":{}}"
traefik    | time="2021-01-02T22:12:24Z" level=info msg="Testing certificate renew..." providerName=netcup.acme
traefik    | time="2021-01-02T22:12:24Z" level=info msg="Starting provider *docker.Provider {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":15000000000}"
traefik    | time="2021-01-02T22:12:24Z" level=debug msg="Configuration received from provider netcup.acme: {\"http\":{},\"tls\":{}}" providerName=netcup.acme
traefik    | time="2021-01-02T22:12:24Z" level=debug msg="No default certificate, generating one"
traefik    | time="2021-01-02T22:12:24Z" level=debug msg="Configuration received from provider internal: {\"http\":{\"routers\":{\"web-to-websecure\":{\"entryPoints\":[\"web\"],\"middlewares\":[\"redirect-web-to-websecure\"],\"service\":\"noop@internal\",\"rule\":\"HostRegexp(`{host:.+}`)\",\"priority\":2147483647}},\"services\":{\"noop\":{}},\"middlewares\":{\"redirect-web-to-websecure\":{\"redirectScheme\":{\"scheme\":\"https\",\"port\":\"443\",\"permanent\":true}}},\"models\":{\"websecure\":{\"tls\":{\"certResolver\":\"netcup\",\"domains\":[{\"main\":\"renekaesler.com\",\"sans\":[\"*.renekaesler.com\"]},{\"main\":\"renekaesler.de\",\"sans\":[\"*.renekaesler.de\"]}]}}}},\"tcp\":{},\"tls\":{}}" providerName=internal
traefik    | time="2021-01-02T22:12:24Z" level=debug msg="Provider connection established with docker 19.03.8 (API 1.40)" providerName=docker
traefik    | time="2021-01-02T22:12:24Z" level=debug msg="Configuration received from provider docker: {\"http\":{\"routers\":{\"traefik-landscape\":{\"service\":\"traefik-landscape\",\"rule\":\"Host(`traefik-landscape`)\"}},\"services\":{\"traefik-landscape\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.22.0.2:80\"}],\"passHostHeader\":true}}},\"middlewares\":{\"non-de\":{\"redirectRegex\":{\"regex\":\"^(?:https|http):\\\\/\\\\/([a-z-]+)\\\\.renekaesler\\\\.de(.*)\",\"replacement\":\"https://${1}.renekaesler.com${2}\",\"permanent\":true}},\"non-www\":{\"redirectRegex\":{\"regex\":\"^(?:https|http):\\\\/\\\\/www\\\\.(.*)\",\"replacement\":\"https://${1}\",\"permanent\":true}}}},\"tcp\":{},\"udp\":{}}" providerName=docker
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Added outgoing tracing middleware noop@internal" routerName=web-to-websecure@internal middlewareName=tracing middlewareType=TracingForwarder entryPointName=web
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Creating middleware" middlewareType=RedirectScheme entryPointName=web routerName=web-to-websecure@internal middlewareName=redirect-web-to-websecure@internal
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Setting up redirection to https 443" middlewareType=RedirectScheme entryPointName=web routerName=web-to-websecure@internal middlewareName=redirect-web-to-websecure@internal
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Adding tracing to middleware" entryPointName=web routerName=web-to-websecure@internal middlewareName=redirect-web-to-websecure@internal
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=web
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="No default certificate, generating one"
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [web websecure]" routerName=traefik-landscape
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Added outgoing tracing middleware noop@internal" routerName=web-to-websecure@internal entryPointName=web middlewareType=TracingForwarder middlewareName=tracing
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Creating middleware" middlewareType=RedirectScheme entryPointName=web routerName=web-to-websecure@internal middlewareName=redirect-web-to-websecure@internal
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Setting up redirection to https 443" routerName=web-to-websecure@internal middlewareName=redirect-web-to-websecure@internal middlewareType=RedirectScheme entryPointName=web
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Adding tracing to middleware" entryPointName=web routerName=web-to-websecure@internal middlewareName=redirect-web-to-websecure@internal
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Creating middleware" middlewareType=Pipelining middlewareName=pipelining entryPointName=web routerName=traefik-landscape@docker serviceName=traefik-landscape
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Creating load-balancer" entryPointName=web routerName=traefik-landscape@docker serviceName=traefik-landscape
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Creating server 0 http://172.22.0.2:80" routerName=traefik-landscape@docker serverName=0 serviceName=traefik-landscape entryPointName=web
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Added outgoing tracing middleware traefik-landscape" middlewareName=tracing middlewareType=TracingForwarder entryPointName=web routerName=traefik-landscape@docker
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Creating middleware" middlewareType=Recovery entryPointName=web middlewareName=traefik-internal-recovery
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Creating middleware" entryPointName=websecure routerName=websecure-traefik-landscape@docker middlewareType=Pipelining middlewareName=pipelining serviceName=traefik-landscape
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Creating load-balancer" serviceName=traefik-landscape entryPointName=websecure routerName=websecure-traefik-landscape@docker
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Creating server 0 http://172.22.0.2:80" serverName=0 entryPointName=websecure routerName=websecure-traefik-landscape@docker serviceName=traefik-landscape
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Added outgoing tracing middleware traefik-landscape" entryPointName=websecure routerName=websecure-traefik-landscape@docker middlewareName=tracing middlewareType=TracingForwarder
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=websecure
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="No default certificate, generating one"
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Adding route for traefik-landscape with TLS options default" entryPointName=websecure
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Looking for provided certificate(s) to validate [\"renekaesler.de\" \"*.renekaesler.de\"]..." providerName=netcup.acme
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Domains [\"renekaesler.de\" \"*.renekaesler.de\"] need ACME certificates generation for domains \"renekaesler.de,*.renekaesler.de\"." providerName=netcup.acme
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Loading ACME certificates [renekaesler.de *.renekaesler.de]..." providerName=netcup.acme
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Looking for provided certificate(s) to validate [\"renekaesler.com\" \"*.renekaesler.com\"]..." providerName=netcup.acme
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Domains [\"renekaesler.com\" \"*.renekaesler.com\"] need ACME certificates generation for domains \"renekaesler.com,*.renekaesler.com\"." providerName=netcup.acme
traefik    | time="2021-01-02T22:12:25Z" level=debug msg="Loading ACME certificates [renekaesler.com *.renekaesler.com]..." providerName=netcup.acme
traefik    | time="2021-01-02T22:12:33Z" level=debug msg="Building ACME client..." providerName=netcup.acme
traefik    | time="2021-01-02T22:12:33Z" level=debug msg="https://acme-staging-v02.api.letsencrypt.org/directory" providerName=netcup.acme
traefik    | time="2021-01-02T22:12:34Z" level=info msg=Register... providerName=netcup.acme
traefik    | time="2021-01-02T22:12:34Z" level=debug msg="legolog: [INFO] acme: Registering account for rene.kaesler@gmail.com"
traefik    | time="2021-01-02T22:12:34Z" level=debug msg="Using DNS Challenge provider: netcup" providerName=netcup.acme
traefik    | time="2021-01-02T22:12:34Z" level=debug msg="legolog: [INFO] [renekaesler.de, *.renekaesler.de] acme: Obtaining bundled SAN certificate"
traefik    | time="2021-01-02T22:12:34Z" level=debug msg="legolog: [INFO] [renekaesler.com, *.renekaesler.com] acme: Obtaining bundled SAN certificate"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] [*.renekaesler.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/183416304"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] [renekaesler.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/183416305"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] [*.renekaesler.com] acme: use dns-01 solver"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] [renekaesler.com] acme: Could not find solver for: tls-alpn-01"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] [renekaesler.com] acme: Could not find solver for: http-01"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] [renekaesler.com] acme: use dns-01 solver"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] [*.renekaesler.com] acme: Preparing to solve DNS-01"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] [*.renekaesler.de] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/183416299"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] [renekaesler.de] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/183416300"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] [*.renekaesler.de] acme: use dns-01 solver"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] [renekaesler.de] acme: Could not find solver for: tls-alpn-01"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] [renekaesler.de] acme: Could not find solver for: http-01"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] [renekaesler.de] acme: use dns-01 solver"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] [*.renekaesler.de] acme: Preparing to solve DNS-01"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] no existing records, error ignored: error when sending the request: an error occurred during the action : [Status=error, StatusCode=4013, ShortMessage=Validation Error., LongMessage=Value in field domainname does not match requirements of type: domainname. ]"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] [renekaesler.com] acme: Preparing to solve DNS-01"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] no existing records, error ignored: error when sending the request: an error occurred during the action : [Status=error, StatusCode=4013, ShortMessage=Validation Error., LongMessage=Value in field domainname does not match requirements of type: domainname. ]"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] [*.renekaesler.com] acme: Cleaning DNS-01 challenge"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [WARN] [*.renekaesler.com] acme: cleaning up failed: netcup: error when sending the request: an error occurred during the action : [Status=error, StatusCode=4013, ShortMessage=Validation Error., LongMessage=Value in field domainname does not match requirements of type: domainname. ] "
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] [renekaesler.com] acme: Cleaning DNS-01 challenge"
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [WARN] [renekaesler.com] acme: cleaning up failed: netcup: error when sending the request: an error occurred during the action : [Status=error, StatusCode=4013, ShortMessage=Validation Error., LongMessage=Value in field domainname does not match requirements of type: domainname. ] "
traefik    | time="2021-01-02T22:12:35Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/183416304"
traefik    | time="2021-01-02T22:12:36Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/183416305"
traefik    | time="2021-01-02T22:12:36Z" level=error msg="Unable to obtain ACME certificate for domains \"renekaesler.com,*.renekaesler.com\" :  [renekaesler.com *.renekaesler.com]: error: one or more domains had a problem:\n[*.renekaesler.com] [*.renekaesler.com] acme: error presenting token: netcup: failed to add TXT-Record: error when sending the request: an error occurred during the action : [Status=error, StatusCode=4013, ShortMessage=Validation Error., LongMessage=Value in field domainname does not match requirements of type: domainname. ]\n[renekaesler.com] [renekaesler.com] acme: error presenting token: netcup: failed to add TXT-Record: error when sending the request: an error occurred during the action : [Status=error, StatusCode=4013, ShortMessage=Validation Error., LongMessage=Value in field domainname does not match requirements of type: domainname. ]\n" providerName=netcup.acme
traefik    | time="2021-01-02T22:12:37Z" level=debug msg="legolog: [INFO] [renekaesler.de] acme: Preparing to solve DNS-01"
traefik    | time="2021-01-02T22:12:39Z" level=debug msg="legolog: [INFO] [*.renekaesler.de] acme: Trying to solve DNS-01"
traefik    | time="2021-01-02T22:12:39Z" level=debug msg="legolog: [INFO] [*.renekaesler.de] acme: Checking DNS record propagation using [127.0.0.11:53]"
traefik    | time="2021-01-02T22:12:44Z" level=debug msg="legolog: [INFO] Wait for propagation [timeout: 2m0s, interval: 5s]"
traefik    | time="2021-01-02T22:12:44Z" level=debug msg="Delaying 600000000000 rather than validating DNS propagation now." providerName=netcup.acme
```

</details>
