### ISSUE TITLE
Ingressclasses not available on namespace scope level

### ISSUE THREAD

**Issue by bschoenbach** [traefik/traefik#7729]
Hi traefik community,

After upgrading of k8s cluster to  **v1.18+**  we get the following error during startup of traefik **v2.3+**

`E0107` 06:45:40.895430       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1beta1.IngressClass: ingressclasses.networking.k8s.io is forbidden: User "system:serviceaccount:traefik:traefik" cannot list resource "ingressclasses" in API group "networking.k8s.io" at the cluster scope`

**The problem:**
Within k8s v1.18+ the "IngressClass" was introduced to avoid bad annotations on "Ingress" resource objects themselves (see [here)](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/) . However,  the idea of that concept is pretty cool but lacks in implementation because it requires access on cluster scope level. Hence, developers or teams which can only work on namespace scope cannot use traefik ingress > 2.3.x on gke > 1.18.x.

**Possible solutions could be:**

- Introduce a configuration switch to disable the listing/ usage of ingressclasses during startup of traefik  v2.3+
OR
- Raise this issue to k8s community so that they can work on the cluster scope issue of "ingressclasses" on k8s v1.18+. In my opinion it must be possible to define ingressclasses also on namespace scope.

**Temporary Solution** 

Currently we downgraded our traefik to **v2.2.11** where lisitng of "ingressclasses" is not implemented and treafik starts up correctly also on gke 1.18+

**Comment by nustiueudinastea** [comment]
Having the same issue when trying to run the latest Helm chart using namespaced deployment.

**Comment by joeldeteves** [comment]
Just ran into the same issue. Downgrading for now.

**Comment by joeldeteves** [comment]
Hello, any update on this issue?

We are unable to patch Traefik for security releases until this is resolved.

Thank you,

**Comment by alexangas** [comment]
Also experiencing this issue on Kubernetes 1.19.7 with Traefik 2.3.3.

Possibly related issue posted [on Stack Overflow](https://stackoverflow.com/q/63109422/6651) but the suggested fix was already in the helm chart.

**Comment by rtribotte** [comment]
Hello @bschoenbach @nustiueudinastea @joeldeteves @alexangas,

Thanks for your interest in Traefik!

This error can happen because Traefik, as a Kubernetes client, has no rights to fetch resources.
As mentioned in the [migration guide](https://doc.traefik.io/traefik/v2.4/migration/v2/#ingressclass), when updating to Traefik v2.3+, the support of IngressClasses makes necessary to update the RBACs.

Can you please check that your RBACs granted to Traefik contains:
```
- apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
```

More generally you can find up-to-date RBACs in the documentation in the [dynamic-configuration reference](https://doc.traefik.io/traefik/v2.4/reference/dynamic-configuration/kubernetes-crd/#rbac) for Kubernetes CRD provider page.

**Comment by joeldeteves** [comment]
> Hello @bschoenbach @nustiueudinastea @joeldeteves @alexangas,
> 
> Thanks for your interest in Traefik!
> 
> This error can happen because Traefik, as a Kubernetes client, has no rights to fetch resources.
> As mentioned in the [migration guide](https://doc.traefik.io/traefik/v2.4/migration/v2/#ingressclass), when updating to Traefik v2.3+, the support of IngressClasses makes necessary to update the RBACs.
> 
> Can you please check that your RBACs granted to Traefik contains:
> 
> ```
> - apiGroups:
>       - extensions
>       - networking.k8s.io
>     resources:
>       - ingresses
>       - ingressclasses
>     verbs:
>       - get
>       - list
>       - watch
> ```
> 
> More generally you can find up-to-date RBACs in the documentation in the [dynamic-configuration reference](https://doc.traefik.io/traefik/v2.4/reference/dynamic-configuration/kubernetes-crd/#rbac) for Kubernetes CRD provider page.

Thank you, I see the documentation was recently updated to reflect this change: #7914 

Note: I also had to add the following to my CRD:
```
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serverstransports.traefik.containo.us

spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: ServersTransport
    plural: serverstransports
    singular: serverstransport
  scope: Namespaced
```

This worked for me, I believe this issue can be closed
