### ISSUE TITLE
Router defined multiple times with different configurations error

### ISSUE THREAD

**Issue by Darktortue** [traefik/traefik#7738]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

After configuring multiple services, 2 aren't working because of a  `router defined multiple times with different configurations` error. Theses 2 services are Netdata and PiHole. For PiHole, I created a 53/tcp entry point and created a TCP and UDP services in Traefik.

### What did you expect to see?

I expected to have access to my pihole website and my netdata website.

### What did you see instead?

404 page not found error and in the Traefik logs : `router defined multiple times with different configurations`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.3.6
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

**TRAEFIK docker-compose.yml**
```
version: "3.3"

services:

  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Web UI
      - "--entrypoints.web-secure.address=:443"
      # PiHole DNS
      - "--entryPoints.53-tcp.address=:53"
      - "--entryPoints.53-udp.address=:53/udp"
      # ACME
      - "--certificatesResolvers.primary.acme.email=me@email.com"
      - "--certificatesResolvers.primary.acme.storage=acme.json"
      - "--certificatesResolvers.primary.acme.dnsChallenge=true"
      - "--certificatesResolvers.primary.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesResolvers.primary.acme.dnsChallenge.delayBeforeCheck=0"
    ports:
      - "443:443"
      - "53:53/udp"
      - "53:53"
    environment:
      - "CF_API_EMAIL=me@email.com"
      - "CF_API_KEY=key"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
    restart: unless-stopped
    labels:
      - "com.ouroboros.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.domain.com`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=web-secure"
      - "traefik.http.routers.api.tls.certResolver=primary"
      - "traefik.http.middlewares.trauth.forwardauth.address=http://trauth.web:8080/"
      - "traefik.http.routers.api.middlewares=trauth"
      # wildcard certs
      - "traefik.http.routers.api.tls.domains[0].main=domain.com"
      - "traefik.http.routers.api.tls.domains[0].sans=*.domain.com"
    networks:
      - web

  trauth:
    build:
      context: https://github.com/leonjza/trauth.git
      dockerfile: Dockerfile
    image: trauth:local
    container_name: trauth
    environment:
      - TRAUTH_DOMAIN=domain.com
      - TRAUTH_PASSWORD_FILE_LOCATION=/htpass/htpass
    volumes:
      - "./htpass:/htpass"
    restart: unless-stopped
    networks:
      - web


networks:
  web:
    external: true
```

**PIHOLE docker-compose.yml**
```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: Europe/Paris
      WEBPASSWORD: password
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    networks:
     - web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.domain.com`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.entrypoints=web-secure"
      - "traefik.http.routers.pihole.tls.certResolver=primary"
      - "traefik.http.routers.netdata.middlewares=trauth"
      # 53/udp
      - "traefik.udp.routers.53-udp.entrypoints=53-udp"
      - "traefik.udp.routers.53-udp.service=pihole-53-udp"
      - "traefik.udp.services.pihole-53-udp.loadbalancer.server.port=53"
      # 53/tcp
      - "traefik.tcp.routers.53-tcp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.53-tcp.entrypoints=53-tcp"
      - "traefik.tcp.routers.53-tcp.service=pihole-53-tcp"
      - "traefik.tcp.services.pihole-53-tcp.loadbalancer.server.port=53"

networks:
  web:
    external: true
```

**NETDATA docker-compose.yml**

```
version: '3'
services:
  netdata:
    image: netdata/netdata
    hostname: example.com # set to fqdn of host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - web
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netdata.rule=Host(`netdata.domain.com`)"
      - "traefik.http.routers.netdata.entrypoints=web-secure"
      - "traefik.http.routers.netdata.tls.certResolver=primary"
      - "traefik.http.routers.pihole.middlewares=trauth"

networks:
  web:
    external: true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

There are more lines like theses : 
```
traefik    | time="2021-01-10T16:47:56Z" level=error msg="Router defined multiple times with different configurations in [netdata-netdata-1912e898360782e9d45256312059a073e65c6df15e167520c7ae8423d5a18f2c pihole-pihole-32e9fe85e92722b0cd508a2f66cddda736112a4d8c2f8af05f063dc7062969bb]" providerName=docker routerName=netdata
traefik    | time="2021-01-10T16:47:56Z" level=error msg="Router defined multiple times with different configurations in [netdata-netdata-1912e898360782e9d45256312059a073e65c6df15e167520c7ae8423d5a18f2c pihole-pihole-32e9fe85e92722b0cd508a2f66cddda736112a4d8c2f8af05f063dc7062969bb smokeping-smokeping-feb519e3a578cd7097b1e64dc5468e99b0954d0a15b8e0412feace9befb45652]" providerName=docker routerName=pihole
traefik    | time="2021-01-10T16:47:56Z" level=info msg="Skipping same configuration" providerName=docker
traefik    | time="2021-01-10T16:48:04Z" level=error msg="Router defined multiple times with different configurations in [pihole-pihole-32e9fe85e92722b0cd508a2f66cddda736112a4d8c2f8af05f063dc7062969bb smokeping-smokeping-feb519e3a578cd7097b1e64dc5468e99b0954d0a15b8e0412feace9befb45652]" providerName=docker routerName=pihole
traefik    | time="2021-01-10T16:48:05Z" level=error msg="Router defined multiple times with different configurations in [pihole-pihole-32e9fe85e92722b0cd508a2f66cddda736112a4d8c2f8af05f063dc7062969bb smokeping-smokeping-feb519e3a578cd7097b1e64dc5468e99b0954d0a15b8e0412feace9befb45652]" providerName=docker routerName=pihole
traefik    | time="2021-01-10T16:48:05Z" level=info msg="Skipping same configuration" providerName=docker
traefik    | time="2021-01-10T16:48:09Z" level=error msg="Router defined multiple times with different configurations in [pihole-pihole-32e9fe85e92722b0cd508a2f66cddda736112a4d8c2f8af05f063dc7062969bb smokeping-smokeping-feb519e3a578cd7097b1e64dc5468e99b0954d0a15b8e0412feace9befb45652]" providerName=docker routerName=pihole
traefik    | time="2021-01-10T16:48:09Z" level=info msg="Skipping same configuration" providerName=docker
traefik    | time="2021-01-10T16:48:14Z" level=error msg="Router defined multiple times with different configurations in [pihole-pihole-32e9fe85e92722b0cd508a2f66cddda736112a4d8c2f8af05f063dc7062969bb smokeping-smokeping-feb519e3a578cd7097b1e64dc5468e99b0954d0a15b8e0412feace9befb45652]" routerName=pihole providerName=docker
traefik    | time="2021-01-10T16:48:14Z" level=info msg="Skipping same configuration" providerName=docker
traefik    | time="2021-01-10T16:48:15Z" level=error msg="Router defined multiple times with different configurations in [pihole-pihole-32e9fe85e92722b0cd508a2f66cddda736112a4d8c2f8af05f063dc7062969bb smokeping-smokeping-feb519e3a578cd7097b1e64dc5468e99b0954d0a15b8e0412feace9befb45652]" routerName=pihole providerName=docker
traefik    | time="2021-01-10T16:48:15Z" level=info msg="Skipping same configuration" providerName=docker
traefik    | time="2021-01-10T16:49:15Z" level=error msg="Router defined multiple times with different configurations in [netdata-netdata-8eac57df5b66943ba211dfd0d34dba10c7466350d9b61ff3e22f55f4fe9d5965 pihole-pihole-32e9fe85e92722b0cd508a2f66cddda736112a4d8c2f8af05f063dc7062969bb]" providerName=docker routerName=netdata
traefik    | time="2021-01-10T16:49:15Z" level=error msg="Router defined multiple times with different configurations in [netdata-netdata-8eac57df5b66943ba211dfd0d34dba10c7466350d9b61ff3e22f55f4fe9d5965 pihole-pihole-32e9fe85e92722b0cd508a2f66cddda736112a4d8c2f8af05f063dc7062969bb smokeping-smokeping-feb519e3a578cd7097b1e64dc5468e99b0954d0a15b8e0412feace9befb45652]" providerName=docker routerName=pihole
traefik    | time="2021-01-10T16:50:57Z" level=error msg="Router defined multiple times with different configurations in [netdata-netdata-8eac57df5b66943ba211dfd0d34dba10c7466350d9b61ff3e22f55f4fe9d5965 pihole-pihole-32e9fe85e92722b0cd508a2f66cddda736112a4d8c2f8af05f063dc7062969bb]" routerName=netdata providerName=docker
traefik    | time="2021-01-10T16:50:57Z" level=error msg="Router defined multiple times with different configurations in [netdata-netdata-8eac57df5b66943ba211dfd0d34dba10c7466350d9b61ff3e22f55f4fe9d5965 pihole-pihole-32e9fe85e92722b0cd508a2f66cddda736112a4d8c2f8af05f063dc7062969bb smokeping-smokeping-feb519e3a578cd7097b1e64dc5468e99b0954d0a15b8e0412feace9befb45652]" routerName=pihole providerName=docker
traefik    | time="2021-01-10T16:50:57Z" level=info msg="Skipping same configuration" providerName=docker
```

I guess I did something wrong in my configurations but I really don't know where. As soon as I shut down my Pihole container, everything is working well again. I also have a Smokeping website but it's working without any problem.

Please help me because I'm kind of lost here ^^ Thanks :)
