### ISSUE TITLE
'502 Bad Gateway' caused by: read tcp xx.xx.x.xxx:yyyyy->xx.xx.x.xxx:yyyy: wsarecv: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by imtiazpk** [traefik/traefik#7739]
### Do you want to request a *feature* or report a *bug*?
Bug

Bug

### What did you do?
Deploy Tarek on windows without using docker.
Configure Traefik with two REST API's hosted on IIS 10.0 on two different VM's using sticky sessions.
Using jmeter put load of 2500 users http request almost 200 requests per second with 2500 web socket connection to receive notifications of the information coming from backend web api signal server.
The load run for few hours

### What did you expect to see?
The traefik should load balance the request using sticky session with 1250 on one of REST API and 1250 to second VM box of REST API.
There should not be any error during test for http request and websocket for received data.

### What did you see instead?
Few of request failed with error '502 Bad Gateway' caused by: read tcp xx.xx.x.xxx:yyyyy->xx.xx.x.xxx:yyyy: wsarecv: An existing connection was forcibly closed by the remote host

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.6
OS/Arch:      Windows/amd64 (Not using docker straight deployment on windows 2016)on
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
## Static configuration
[entryPoints.ApiGateway]
	address = "10.58.1.107:8450"
	
[entryPoints.ApiGateway.http.tls]
      certResolver = "leresolver"
	  
	  
[serversTransport]
  insecureSkipVerify = true # insecureSkipVerify disables SSL certificate verification.
  
[providers]
  [providers.file]
	directory = "C:\\traefik_v2.3.6_windows_amd64\\config"

[log]
  level = "ERROR"
  filePath = "log/traefik.log"
  
  
## Dynamic configuration
[http]
 [http.routers] 
 [http.routers.ApiGatewayRoute] 
   entryPoints = "ApiGateway" 
   rule = "Host(`10.58.1.107`)" 
   service = "ApiGatewayService"
 	
[http.services]
[http.services.ApiGatewayService]
[http.services.ApiGatewayService.loadBalancer]
[http.services.ApiGatewayService.loadBalancer.sticky.cookie]
	  name = "api-session-id"
      secure = true
      httpOnly = true
      sameSite = "none"
[http.services.ApiGatewayService.loadBalancer.healthCheck]
      path = "/api/v1.0/Authentication/Health"
      interval = "6s"
      timeout = "3s"
  [[http.services.ApiGatewayService.loadBalancer.servers]]
      url = "https://10.58.1.253:8445"
  [[http.services.ApiGatewayService.loadBalancer.servers]]
      url = "https://10.58.1.112:8445"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2021-01-09T07:45:01Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL="https://10.58.1.112:8445" Request="{\"Method\":\"PUT\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api/v1.0/Cache/AddCache\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Connection\":[\"keep-alive\"],\"Content-Length\":[\"1113\"],\"Content-Type\":[\"application/json\"],\"Cookie\":[\"api-session-id=https://10.58.1.112:8445; session-id=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2MTAyMDU3NTYsImV4cCI6MTYxMDIwOTM4NiwiaWF0IjoxNjEwMjA1NzU2LCJBY2Nlc3NUb2tlbklEIjoiZjA3YmZkMTZlZTgyNGZhYTk1YmRiZTMwODU3ZTY5ZjciLCJVc2VySUQiOiIwMDU3RjAwMDAwMjQ5ckhRMTExMCIsIlVzZXJHcm91cHMiOltdLCJSb2xlcyI6W10sIlBlcm1pc3Npb25zIjpbIkNUSVNlcnZpY2UiLCJDYWNoZVNlcnZpY2UiLCJBdXRoZW50aWNhdGlvblNlcnZpY2UiXX0.0ReFfgSDoeXWwQAoH3ApRXKspPRHbSM6F2WV7C9RquE\"],\"User-Agent\":[\"Apache-HttpClient/4.5.10 (Java/1.8.0_271)\"],\"X-Forwarded-Host\":[\"10.58.1.107:8450\"],\"X-Forwarded-Port\":[\"8450\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"pk-crmc-load-s1\"],\"X-Real-Ip\":[\"10.58.1.111\"]},\"ContentLength\":1113,\"TransferEncoding\":null,\"Host\":\"10.58.1.107:8450\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.58.1.111:58954\",\"RequestURI\":\"/api/v1.0/Cache/AddCache\",\"TLS\":null}"
time="2021-01-09T07:45:01Z" level=debug msg="'502 Bad Gateway' caused by: read tcp 10.58.1.107:23362->10.58.1.112:8445: wsarecv: An existing connection was forcibly closed by the remote host."

```
