### ISSUE TITLE
a problem "plugin integrity check failed" occurs when starting up Traefik with a plugin developed by myself

### ISSUE THREAD

**Issue by LeslieRan** [traefik/traefik#7740]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I have developed a plugin meeting criteria and wanna use it in Traefik.

### What did you expect to see?

Traefik uses my plugin normally.

### What did you see instead?

there is a problem with starting Traefik.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
v2.3.6
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
static configuration:
```yaml
pilot:
  token: "c5b1e067-2062-420f-a8ad-xxxx"
providers:
  file:
    filename: "./traefik_dynamic.yml"
    watch: true
    debugLogGeneratedTemplate: true
ping:
  entrypoint: traefik
api:
  insecure: true
  dashboard: true
  debug: true
experimental:
    plugins:
        pluginDemo:
            moduleName: "github.com/LeslieRan/pluginDemo"
            version: "v0.3"
```

dynamic configuration:
```
middlewares:
    my-pluginDemo:
        plugin:
            pluginDemo:
                Info: hello
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
INFO[0000] Configuration loaded from file: /home/rf/RF/traefik/traefik_v2.3.6/traefik_static.yml 
2021/01/11 16:53:19 traefik.go:76: command traefik error: failed to check archive integrity of the plugin github.com/LeslieRan/pluginDemo: plugin integrity check failed
```
or
```
2021/01/11 16:53:09 traefik.go:76: command traefik error: failed to download plugin github.com/LeslieRan/pluginDemo: failed to call service: Get "https://plugin.pilot.traefik.io/public/download/github.com/LeslieRan/pluginDemo/v0.3": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
