### ISSUE TITLE
Double encoding header triggers HTTP 500 response

### ISSUE THREAD

**Issue by RafPe** [traefik/traefik#7741]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

The bug report is when the following occurs which is just a usual flow of client making http request towards a service. 

```
client req -> alb -> traefik ingress -> service on k8s -> traefik ingress 

------------- request ------------- | ------------- response -------------
```

Service response headers 

```
Date: Mon, 11 Jan 2021 09:14:59 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Content-Type: application/json
Transfer-Encoding: chunked
````

### What did you expect to see?

I have expected to see `HTTP 200` response on traefik proxy towards the client

 
### What did you see instead?

The client receives HTTP 500 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.1
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-29T15:49:06Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: traefik-ingress-public
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: ingress
        app.kubernetes.io/instance: public
        app.kubernetes.io/name: traefik
        app.kubernetes.io/version: 2.3.1
    spec:
      containers:
      - args:
        - --api
        - --api.insecure=true
        - --api.dashboard=true
        - --accesslog=true
        - --accesslog.format=json
        - --accesslog.fields.headers.defaultmode=keep
        - --log.level=DEBUG
        - --entrypoints.web.address=:32280
        - --entryPoints.websecure.address=:443
        - --entryPoints.web.forwardedHeaders.insecure
        - --entryPoints.websecure.forwardedHeaders.insecure
        - --entrypoints.traefik.address=:8100
        - --ping=true
        - --ping.entryPoint=traefik
        - --providers.kubernetescrd=true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2021-01-06T12:30:52Z" level=debug msg="'500 Internal Server Error' caused by: net/http: HTTP/1.x transport connection broken: too many transfer encodings: [\"chunked\" \"chunked\"]"
```
