### ISSUE TITLE
Sticky session invalid cookie handling

### ISSUE THREAD

**Issue by msumner91** [traefik/traefik#7767]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Hit an IngressRoute CRD backed by a TraefikService CRD and finally a single K8 Service backed by two pods with cookies enabled several times.

This was done several times with no cookie set to verify the Pod IP cookie we get back from Traefik matches the actual pod that served the request.

This was then done several more times with lvl1/lvl2 set to verify whether Traefik honors the Pod asked for in the cookie.

### What did you expect to see?
1. The pod that services the request to match the Pod IP returned on the Traefik cookie (i.e. 10.42.31.247 instead of 10.42.32.196).
2. When the cookie is set on a request, for Traefik to honor that Pod IP as the destination

### What did you see instead?
This returns a cookie as expected, but the Pod IP that does not match the actual destination that served the request (note sometimes it will because this example is just two pods and therefore has 50-50 chance to be 'lucky').

If the lvl1 and lvl2 cookies are set on the request, the same behavior is observed -- i.e. it does not honor the pod IP requested.

**Send several calls to:** 
curl myurl.com/abcd

**Traefik access log:**
10.42.56.0 - - [15/Jan/2021:12:47:34 +0000] "GET myurl.com/abcd HTTP/1.1" 200 411 "-" "-" 173 "namespace-route-xyz@kubernetescrd" "**http://10.42.31.247:8081**" 887ms
10.42.42.0 - - [15/Jan/2021:12:47:39 +0000] "GET myurl.com/abcd HTTP/1.1" 200 411 "-" "-" 176 "namespace-route-xyz@kubernetescrd" "**http://10.42.32.196:8081**" 447ms

**Response cookie:**
myurl.com FALSE   /       FALSE   0       lvl2    http://10.42.32.196:8081
myurl.com FALSE   /       FALSE   0       lvl1    namespace-my-svc-8081

Actual destination was a different pod IP: 10.42.31.247

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v2.3.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
We are running in Rancher, but using IngressRouter CRD providers.

Stickyness is configured as per the below:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`{{ .Values.prefix }}`)
    kind: Rule
    services:
    - name: wrr-{{ .Values.name }}
      namespace: {{ .Release.Namespace }}
      kind: TraefikService
---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: wrr-{{ .Values.name }}
  namespace: {{ .Release.Namespace }}

spec:
  weighted:
    services:
      - name: {{ .Values.service }}
        port: {{ .Values.apiport }}
        kind: Service
        weight: 1
        sticky:
          cookie:
            name: lvl2
    sticky:
      cookie:
        name: lvl1

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
