### ISSUE TITLE
Request with HTTP "CONNECT" method gets routed to wrong service

### ISSUE THREAD

**Issue by ericlathrop** [traefik/traefik#7771]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm running a custom app that acts as a HTTP proxy using the CONNECT method. I hooked it up to traefik with the following docker labels:

```
      traefik.docker.network: web
      traefik.enable: "true"
      traefik.http.routers.correcthost.rule: Host(`correct-host.example`)
      traefik.http.routers.correcthost.tls: "true"
      traefik.http.routers.correcthost.tls.certresolver: leresolver
```

When I run `curl -v https://correct-host.example` I get a 200 and this traefik log message:

```
192.168.1.1 - - [17/Jan/2021:05:52:42 +0000] "GET / HTTP/2.0" 200 3 "-" "-" 320705 "correcthost@docker" "http://172.18.0.21:8080" 0ms
```

However, when I run `curl -v --proxy https://correcthost.example https://some-other-host.example` I get a 500 and this traefik log message:

```
192.168.1.1 - - [17/Jan/2021:05:40:34 +0000] "CONNECT - HTTP/1.1" 500 0 "-" "-" 319979 "incorrecthost@docker" "http://172.18.0.2:3000" 0ms
```

You can see in the log message that the request was forwarded to the `incorrecthost` service, which responds with a 500.

### What did you expect to see?

I expected to see `correcthost@docker` in the log file, and have the request routed to my `correcthost` service.

### What did you see instead?

I saw the `incorrecthost@docker` service in the log file, and my request was routed to the incorrects service.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.7
Codename:     picodon
Go version:   go1.15.6
Built:        2021-01-11T18:03:02Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[accessLog]
[api]
  dashboard = true

[serversTransport]
  insecureSkipVerify = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

    [entryPoints.web.http]
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
          to = "websecure"
          scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.leresolver.acme]
  email = "..."
  storage = "/etc/traefik/acme.json"
  [certificatesResolvers.leresolver.acme.dnsChallenge]
    provider = "namecheap"

[providers.docker]
  exposedByDefault = false
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
