### ISSUE TITLE
TCP Router with TLS sends incorrect ALPN

### ISSUE THREAD

**Issue by ericlathrop** [traefik/traefik#7776]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I was trying to work around #7771 so I put my app behind a TCP router with these docker labels:

```
      traefik.docker.network: web
      traefik.enable: "true"
      traefik.tcp.routers.awslambdaproxy.rule: HostSNI(`aws-lambda-proxy.ericlathrop.dev`)
      traefik.tcp.routers.awslambdaproxy.tls: "true"
      traefik.tcp.routers.awslambdaproxy.tls.certresolver: leresolver
```

My app only supports HTTP 1.1, but traefik negotiates an ALPN of `h2` which causes connections to fail. 

```
$ curl -v https://my-app.example/
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to my-app.example (x.x.x.x) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=my-app.example
*  start date: Jan 17 03:55:14 2021 GMT
*  expire date: Apr 17 03:55:14 2021 GMT
*  subjectAltName: host "my-app.example" matched cert's "my-app.example"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* Using Stream ID: 1 (easy handle 0x557c11fd35c0)
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> GET / HTTP/2
> Host: my-app.example
> User-Agent: curl/7.58.0
> Accept: */*
>
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* http2 error: Remote peer returned unexpected data while we expected SETTINGS frame.  Perhaps, peer does not support HTTP/2 properly.
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* SSL_write() returned SYSCALL, errno = 104
* Failed sending HTTP2 data
* Connection #0 to host my-app.example left intact
curl: (55) SSL_write() returned SYSCALL, errno = 104
```

If I force HTTP 1.1 mode with `curl -v --http1.1 https://my-app.example`, it works successfully.

Perhaps traefik should do one or more of the following:
1. only send a ALPN of `http/1.1` when it is configured to terminate TLS connections
2. inspect the service to see which protocol it supports
3. allow for configuring which ALPN is sent

### What did you expect to see?

I expected `curl -v https://my-app.exmaple` to return successfully.

### What did you see instead?

A `curl` error like `* http2 error: Remote peer returned unexpected data while we expected SETTINGS frame.  Perhaps, peer does not support HTTP/2 properly.`. See above for the full output.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.7
Codename:     picodon
Go version:   go1.15.6
Built:        2021-01-11T18:03:02Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[accessLog]
[api]
  dashboard = true

[serversTransport]
  insecureSkipVerify = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

    [entryPoints.web.http]
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
          to = "websecure"
          scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.leresolver.acme]
  email = "..."
  storage = "/etc/traefik/acme.json"
  [certificatesResolvers.leresolver.acme.dnsChallenge]
    provider = "namecheap"

[providers.docker]
  exposedByDefault = false
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
