### ISSUE TITLE
Memory keeps increasing during load

### ISSUE THREAD

**Issue by mikaelsjostrand** [traefik/traefik#7801]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am using traefik to route to Consul catalog services (using dynamic configuration with Consul tags, version 1.4.1 of Consul).
Typically, there are around 10 million request each day to this traefik instance (installed as a binary on an AWS EC2 Ubuntu 16.04 instance, controlled by systemd).

### What did you expect to see?

When sending requests, I expect the memory usage of traefik process to increase. After a while, I expect that it will release its memory back to the OS, especially when there is memory pressure.

### What did you see instead?

Traefik memory keeps growing until it finally reach its limit and are OOM killed. 
Output from dmesg:
```
Out of memory: Kill process 10663 (traefik) score 966 or sacrifice child
Killed process 10663 (traefik) total-vm:31611108kB, anon-rss:31326412kB, file-rss:0kB
```
<img width="1605" alt="oom_killed_traefik_cut" src="https://user-images.githubusercontent.com/29058720/105865846-9d8eb880-5ff3-11eb-88b5-136a1f6f795e.png">

Example of a pprof heap data:
```
File: traefik
Type: inuse_space
Time: Jan 19, 2021 at 2:39pm (CET)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top20
Showing nodes accounting for 5486.10MB, 92.68% of 5919.59MB total
Dropped 278 nodes (cum <= 29.60MB)
Showing top 20 nodes out of 64
      flat  flat%   sum%        cum   cum%
 3599.44MB 60.81% 60.81%  3599.44MB 60.81%  github.com/vulcand/oxy/utils.CopyURL
  821.20MB 13.87% 74.68%  4420.64MB 74.68%  github.com/vulcand/oxy/roundrobin.(*RoundRobin).UpsertServer
  526.63MB  8.90% 83.57%   526.63MB  8.90%  regexp/syntax.(*compiler).inst
  106.52MB  1.80% 85.37%   106.52MB  1.80%  github.com/sirupsen/logrus.(*Entry).WithFields
   82.01MB  1.39% 86.76%    82.01MB  1.39%  encoding/json.(*decodeState).literalStore
   79.01MB  1.33% 88.09%   692.65MB 11.70%  regexp.compile
   69.52MB  1.17% 89.27%    69.52MB  1.17%  github.com/gorilla/mux.(*Router).NewRoute
      46MB  0.78% 90.05%       46MB  0.78%  github.com/containous/traefik/v2/pkg/server/provider.MakeQualifiedName
      42MB  0.71% 90.76%       42MB  0.71%  regexp/syntax.(*parser).maybeConcat
      34MB  0.57% 91.33%       34MB  0.57%  github.com/containous/traefik/v2/pkg/middlewares/accesslog.NewFieldHandler
   30.50MB  0.52% 91.84%    30.50MB  0.52%  github.com/vulcand/oxy/roundrobin.New
      25MB  0.42% 92.27%   372.79MB  6.30%  github.com/gorilla/mux.newRouteRegexp
      15MB  0.25% 92.52%   363.85MB  6.15%  github.com/containous/traefik/v2/pkg/middlewares/replacepathregex.New
       7MB  0.12% 92.64%  4596.31MB 77.65%  github.com/containous/traefik/v2/pkg/server/service.(*Manager).upsertServers
    0.72MB 0.012% 92.65%   121.50MB  2.05%  github.com/containous/traefik/v2/pkg/provider/consulcatalog.(*Provider).getConsulServicesData
    0.53MB 0.0089% 92.66%    65.53MB  1.11%  github.com/containous/traefik/v2/pkg/provider/consulcatalog.(*Provider).buildConfiguration
    0.50MB 0.0084% 92.67%    48.50MB  0.82%  regexp/syntax.Parse
    0.50MB 0.0084% 92.68%       37MB  0.63%  regexp/syntax.(*parser).push
         0     0% 92.68%   117.28MB  1.98%  encoding/json.(*Decoder).Decode
         0     0% 92.68%    91.51MB  1.55%  encoding/json.(*decodeState).array
```

Profiling for objects in-use:
```
File: traefik
Type: inuse_objects
Time: Jan 19, 2021 at 2:39pm (CET)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top20
Showing nodes accounting for 70050608, 94.03% of 74499229 total
Dropped 262 nodes (cum <= 372496)
Showing top 20 nodes out of 80
      flat  flat%   sum%        cum   cum%
  29587250 39.71% 39.71%   59073857 79.29%  github.com/vulcand/oxy/roundrobin.(*RoundRobin).UpsertServer
  29486607 39.58% 79.29%   29486607 39.58%  github.com/vulcand/oxy/utils.CopyURL
   1059588  1.42% 80.72%    1059588  1.42%  github.com/gorilla/mux.(*Router).NewRoute
    877211  1.18% 81.89%     877211  1.18%  encoding/json.(*decodeState).literalStore
    789754  1.06% 82.95%     789754  1.06%  github.com/containous/traefik/v2/pkg/server/provider.MakeQualifiedName
    732954  0.98% 83.94%     732954  0.98%  github.com/sirupsen/logrus.(*Entry).WithFields
    720916  0.97% 84.91%     720916  0.97%  strings.(*Builder).WriteString
    655369  0.88% 85.79%     655369  0.88%  github.com/gorilla/mux.(*Route).addMatcher
    655366  0.88% 86.67%   61616999 82.71%  github.com/containous/traefik/v2/pkg/server/service.(*Manager).upsertServers
    568004  0.76% 87.43%     568004  0.76%  github.com/gorilla/mux.(*Route).getRegexpGroup
    568004  0.76% 88.19%     568004  0.76%  regexp/syntax.(*compiler).init
    557089  0.75% 88.94%     557089  0.75%  github.com/containous/traefik/v2/pkg/middlewares/accesslog.NewFieldHandler
    524300   0.7% 89.64%     524300   0.7%  regexp/syntax.(*Regexp).CapNames
    517812   0.7% 90.34%    2677831  3.59%  regexp.compile
    504647  0.68% 91.01%     504647  0.68%  github.com/containous/traefik/v2/pkg/server/service.buildProxy
    482792  0.65% 91.66%     482792  0.65%  regexp/syntax.(*compiler).inst
    482187  0.65% 92.31%     482187  0.65%  github.com/vulcand/oxy/roundrobin.New
    466984  0.63% 92.94%     466984  0.63%  regexp/syntax.(*parser).maybeConcat
    415074  0.56% 93.49%     415074  0.56%  fmt.Sprintf
    398700  0.54% 94.03%     402340  0.54%  github.com/containous/traefik/v2/pkg/middlewares/metrics.NewServiceMiddleware
```

And for allocs:
```
File: traefik
Type: alloc_space
Time: Jan 19, 2021 at 2:39pm (CET)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top20
Showing nodes accounting for 4.36TB, 81.57% of 5.35TB total
Dropped 707 nodes (cum <= 0.03TB)
Showing top 20 nodes out of 153
      flat  flat%   sum%        cum   cum%
    1.52TB 28.47% 28.47%     1.52TB 28.47%  github.com/sirupsen/logrus.(*Entry).WithFields
    0.57TB 10.57% 39.04%     0.74TB 13.86%  encoding/json.(*Decoder).refill
    0.40TB  7.42% 46.45%     0.40TB  7.42%  net/url.parse
    0.39TB  7.38% 53.83%     0.39TB  7.38%  github.com/vulcand/oxy/utils.CopyURL
    0.21TB  4.00% 57.83%     0.21TB  4.00%  regexp/syntax.(*compiler).inst
    0.16TB  2.94% 60.77%     0.16TB  3.02%  encoding/json.(*decodeState).literalStore
    0.13TB  2.37% 63.14%     0.52TB  9.72%  github.com/vulcand/oxy/roundrobin.(*RoundRobin).UpsertServer
    0.13TB  2.35% 65.50%     0.13TB  2.35%  compress/flate.(*dictDecoder).init
    0.12TB  2.30% 67.80%     0.12TB  2.30%  strings.(*Builder).WriteString
    0.10TB  1.91% 69.71%     0.10TB  1.91%  bufio.NewReaderSize
    0.10TB  1.79% 71.50%     0.10TB  1.80%  io.copyBuffer
    0.08TB  1.57% 73.07%     0.08TB  1.57%  github.com/containous/traefik/v2/pkg/log.Str.func1
    0.07TB  1.37% 74.44%     2.54TB 47.51%  github.com/containous/traefik/v2/pkg/server/service.(*Manager).upsertServers
    0.07TB  1.36% 75.80%     0.07TB  1.36%  reflect.mapassign
    0.07TB  1.27% 77.07%     0.07TB  1.27%  reflect.New
    0.06TB  1.07% 78.14%     0.06TB  1.07%  reflect.unsafe_NewArray
    0.05TB  1.01% 79.15%     0.05TB  1.01%  regexp/syntax.(*parser).newRegexp
    0.05TB  0.92% 80.07%     0.05TB  0.92%  github.com/vulcand/oxy/roundrobin.Weight
    0.04TB   0.8% 80.87%     0.04TB   0.8%  bufio.NewWriterSize
    0.04TB   0.7% 81.57%     0.04TB   0.7%  github.com/containous/traefik/v2/pkg/tcp.(*Router).GetConn
```
### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.1.6
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[api]
dashboard = true
debug = true
insecure = true
[entryPoints.http]
address = ":8300"
[entryPoints.http.forwardedHeaders]
insecure = "true"
[entryPoints.traefik]
address = ":8400"
[global]
checkNewVersion = false
[log]
filepath = "/opt/log/traefik/traefik.log"
format = "common"
level = "INFO"
[metrics.influxDB]
addEntryPointsLabels = true
addServicesLabels = true
address = "http://127.0.0.1:8086"
database = "traefik"
protocol = "http"
pushInterval = "10s"
[ping]
entryPoint = "http"
[providers.consulCatalog]
cache = false
constraints = "TagRegex(`traefik\\.tag\\..*`) || TagRegex(`traefik\\.tags=.+`)"
defaultRule = "PathPrefix(`/{{ .Name }}`)"
exposedByDefault = true
prefix = "traefik"
refreshInterval = "10s"
[providers.consulCatalog.endpoint]
address = "http://example.com:8500"
datacenter = "dc1"
[serversTransport.forwardingTimeouts]
responseHeaderTimeout = "300s"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
null
```
