### ISSUE TITLE
traefik not change path/location in www-authenticate or location redirect header

### ISSUE THREAD

**Issue by HalliHalloSchatz** [traefik/traefik#7806]
### Do you want to request a *feature* or report a *bug*?
*feature* or *bug*; I don't know

traefik not change the original path in www-authenticate header or location redirect header

traefikrules
```toml
[http]
#Servcies, the original servers
  [http.services]
    [http.services.Arti]
      [http.services.Arti.loadBalancer]
        [[http.services.Arti.loadBalancer.servers]]
          url = "http://asset-repository.xxx.de"

  [http.middlewares]
    [http.middlewares.Arti-header.headers]
      [http.middlewares.Arti-header.headers.customRequestHeaders]
        Host = "asset-repository.xxx.de"
        X-Forwarded-Host = "asset-repository.xxx.de"
#Aus apache. Es muss der WWW-Authenticate Header an ZWEI Stellen angepasst werden
#Header edit* WWW-Authenticate asset-repository.xxx.de:80 arti.xxx.de:80

    [http.middlewares.Arti-Replaces.redirectRegex]
      regex = "asset-repository.xxx.de"
      replacement = "arti.xxx.de"

  [http.routers]
    [http.routers.Arti_root]
      entryPoints = ["web"]
      rule = "Host(`arti.xxx.de`) || Host(`arti`)"
      middlewares = ["Arti-Replaces", "Arti-header"]
      service = "Arti"
```

Wrong Header:

```
DEBUG header = http.Header{"Content-Type":[]string{"application/json;charset=ISO-8859-1"}, "Www-Authenticate":[]string{"Bearer realm=\"http://**asset-repository.xxx.de**:80/artifactory/api/docker/docker/v2/token\",service=\"**asset-repository.xxx.de**:80\",scope=\"repository:nginx:pull\""}, "X-Artifactory-Id":[]string{"392eea59b78b0bb0:5d53ff9a:175ff425e03:-8000"}, "X-Artifactory-Node-Id":[]string{"b10d8b8b742e"}, "Content-Length":[]string{"87"}, "Date":[]string{"Fri, 22 Jan 2021 13:38:57 GMT"}, "Docker-Distribution-Api-Version":[]string{"registry/2.0"}, "Server":[]string{"Artifactory/7.7.8 70708900"}}
```
