### ISSUE TITLE
Verbosity in setting router for both HTTP and HTTPS

### ISSUE THREAD

**Issue by gutenye** [traefik/traefik#7807]
The doc says you need to define two different routers for it. If you have lots of settings for one router (e.g. middlewares), you have to duplicate all of them for another router. 

<img width="655" alt="Screen Shot 2021-01-27 at 7 55 25 PM" src="https://user-images.githubusercontent.com/377544/105987754-afe32200-60d9-11eb-8a18-f41fae456602.png">

To be clear, I'm not talking about redirect HTTP to HTTPS. (So this is not a duplicate of #4863). I just want to access it both from HTTP and HTTPS.

@rtribotte gave an answer [here](https://github.com/traefik/traefik/issues/7235#issuecomment-690059948), but it does not work. (that thread is closed so I create this one.)

Given below configuration

```yaml
entryPoints:
  websecure:
    address: ":443"
  webinsecure:
    address: ":80"
    
http:
  routers:
    my-https-router:
      rule: "Host(`foo.com`)"
      service: service-id
      tls: {}
```

You can only access it via `https://foo.com`. And if you remove `tls: {}`, then you can only access it via `http://foo.com` but not both. 
I want a simple setting so that I can access it via both `https://foo.com` and `http://foo.com` (without redirection.)

**Comment by ldez** [comment]
Hello,

the feature is already available: https://doc.traefik.io/traefik/v2.4/routing/entrypoints/#http-options

**Comment by gutenye** [comment]
@ldez Thanks for the quick response, I'd love to open a thread on the community forum, but I'm afraid this is a missing feature, no solution would come up during the discussion.

> the feature is already available: doc.traefik.io/traefik/v2.4/routing/entrypoints/#http-options

Can you elaborate a bit more, how entrypoints can solve this? (I'll use docker-compose format)

Replace verbose config

```yaml
    labels:
      # for https
      traefik.http.routers.hello.tls: true
      traefik.http.routers.hello.rule: Host(`hello.lan`)
      traefik.http.services.hello.loadbalancer.server.port: 80
      traefik.http.routers.hello.entryPoints: websecure,webinsecure
      traefik.http.routers.hello.middlewares: helloAuth
      traefik.http.middlewares.helloAuth.basicauth.users: $AUTH
      # for http
      traefik.http.routers.hello2.rule: Host(`hello.lan`)
      traefik.http.services.hello2.loadbalancer.server.port: 80
      traefik.http.routers.hello2.entryPoints: websecure,webinsecure
      traefik.http.routers.hello2.middlewares: hello2Auth
      traefik.http.middlewares.helloAuth.basicauth.users: $AUTH
     
```

with simple one

```yaml
    labels:
      # for https and http
      traefik.http.routers.hello.tls: true
      traefik.http.routers.hello.rule: Host(`hello.lan`)
      traefik.http.services.hello.loadbalancer.server.port: 80
      traefik.http.routers.hello.entryPoints: websecure,webinsecure
      traefik.http.routers.hello.middlewares: helloAuth
      traefik.http.middlewares.helloAuth.basicauth.users: $AUTH
```

**Comment by ldez** [comment]
```yml
version: '3.7'

services:

  traefik:
    image: traefik:v2.4.0
    command:
      - --log.level=DEBUG
      - --api
      - --providers.docker.exposedbydefault=false

      - --entrypoints.web.address=:80
      # global redirect to https
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https

      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: 'true'

      # Dashboard
      traefik.http.routers.traefik.rule: Host(`traefik.localhost`)
      traefik.http.routers.traefik.entrypoints: websecure,web
      traefik.http.routers.traefik.service: api@internal

  whoami:
    image: traefik/whoami:v1.6.0
    labels:
      traefik.enable: 'true'

      traefik.http.routers.aaa.rule: Host(`whoami.localhost`)
      traefik.http.routers.aaa.entrypoints: websecure,web
```
