### ISSUE TITLE
tls.options not applying to entrypoint

### ISSUE THREAD

**Issue by dbarrosop** [traefik/traefik#7816]
### Do you want to request a *feature* or report a *bug*?

Apologies if this is not a bug but a user problem but I have read the documentation and looked at the logs and everything seems to be fine so figured I'd report it in case it was a bug.

### What did you do?

I want to configure two different entrypoints:

1. :65443 with mtls
2. :65444 without it

I have the following sample `docker-compose.yaml`:

```
---
version: "3.1"
services:
    fltraefik:
        image: "traefik:2.4"
        command:
        - --log=true
        - --log.level=DEBUG
        - --providers.file.directory=/config
        - --providers.file.watch=true
        - --providers.docker=true
        - --providers.docker.exposedbydefault=false
        - --entrypoints.nomtls.address=:65444
        - --entrypoints.nomtls.http.tls.options=`nomtls@file`
        - --entrypoints.withmtls.address=:65443
        - --entrypoints.withmtls.http.tls
        - --providers.file.debugloggeneratedtemplate

        ports:
          - "127.0.0.1:65443:65443"  # requires mtls
          - "127.0.0.1:65444:65444"  # no mtls
        volumes:
          - "./certs/:/certs"
          - "./config/:/config"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
    whoami:
        image: traefik/whoami
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
```

And the following file inside the config folder:

```
---
tls:
    stores:
        default:
            defaultCertificate:
                certFile: /certs/server.crt
                keyFile: /certs/server.key
    options:
        default:
            clientAuth:
                clientAuthType: RequireAndVerifyClientCert
                caFiles:
                    - /certs/ca.crt
        nomtls:
            clientAuth:
                clientAuthType: NoClientCert
```

### What did you expect to see?

I would expect the `nomtls` entrypoint to follow the configuration defined under `tls.options.nomtls` in the yaml file 

### What did you see instead?

No matter what I try only the default tls options work.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.0
Codename:     livarot
Go version:   go1.15.6
Built:        2021-01-19T17:26:51Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I provided this info above, if you need anything else don't hesitate to ask

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Logs don't show any warning or error, unfortunately.
