### ISSUE TITLE
Route Prefix

### ISSUE THREAD

**Issue by theobouwman** [traefik/traefik#7820]
I've configured an Ingress with config:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nuclio-dashboard
  namespace: nuclio
spec:
  rules:
    - host: nuc.local
      http:
        paths:
          - path: /nuclio
            backend:
              serviceName: nuclio-dashboard
              servicePort: 8070
```

Not when I go to `nuc.local/nuclio` I'm getting a response but the page requests js and css files at:
```
http://nuc.local/assets/css/vendor-fc43143698.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

I want every request mage from `/nuclio` to `/` to go to `/nuclio`.

How can I accomplish this?
