### ISSUE TITLE
Allow custom peer certificate verification for services

### ISSUE THREAD

**Issue by jbdoumenjou** [traefik/traefik#7826]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Currently, the [serversTransport](https://doc.traefik.io/traefik/v2.4/routing/services/#serverstransport_1) configuration is based on Go default peer certificate validation.

The #7407 points out the need to define a custom validation for Spiffe certificates that will use URIs instead of DNSNames. 

The goal is to be able to apply custom validation mechanisms such as URIs check or whatever build on available certificate data.

#### Actual Configuration

```yaml
  serversTransports:
    ServersTransport0:
      serverName: foobar
      insecureSkipVerify: true
      rootCAs:
      - foobar
      certificates:
      - certFile: foobar
        keyFile: foobar
```

#### Proposed Configurations

It is the first step to engage the discussion, the naming and the final configuration might evolve.

```yaml
serversTransports:
  # Proposition 1
  ServersTransport1:
    # use as SNI if defined
    serverName: foobar
    # if true, will skip all certificate verification
    insecureSkipVerify: false
    # custom certificate verification configuration
    certificateVerification:
      # will apply the default go verification, and use serverName value if specified
      verifyHostname: true
      # define explicitly the dns names to check
      DNSNames:
        - foobar
      # check the certificate URIs
      URIs:
        - spiffe://foo.com
    rootCAs:
      - foobar
    certificates:
      - certFile: foobar
        keyFile: foobar

  # Proposition 2
  ServersTransport2:
    serverName: foobar
    insecureSkipVerify: false
    certificateVerificationRule: IsValidHostname() && (URIs(`spiffe://foo.com`) || DNSNames(`foobar`))
    rootCAs:
      - foobar
    certificates:
      - certFile: foobar
        keyFile: foobar
```

The first proposition is simpler, it will be a AND between types of verification (DNSNames, URIs) and OR inside.
The second proposition is more complex but allows us to fine-tune the verification. 

* If the insecureSkipVerify is `true`, no validation mechanism will be applied.

| serverName  | verifyHostname | URIs           | Behavior                                                                                                                 |
|-------------------|----------------------|-----------------|-----------------------------------------------------------------------------------------------------------|
| not defined    | false                  | not defined  | no validation                                                                                                          |
| not defined    | false                  | defined        | URIs validation                                                                                                      |
| not defined    | true                   | not defined  | "common" validation                                                                                              |
| not defined    | true                   | defined        | "common" validation && URIs validation                                                               |
| defined          | false                  | not defined  | no validation                                                                                                          |
| defined          | false                  | defined        | URIs validation                                                                                                      |
| defined          | true                   | not defined  | "common" validation with the serverName attribute                                               |
| defined          | true                   | defined        | "common" validation with the serverName attribute && URIs validation                |
