### ISSUE TITLE
Traefik ignores Let's Encrypt certResolver for router, when default certificate matches host

### ISSUE THREAD

**Issue by TomasTokaMrazek** [traefik/traefik#7827]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Traefik is configured with custom wildcard self-signed certificate matching one of my domains. This is for services in my local network. The rest of the services are publicly availible, thus using Let's Encrypt certificate resolver. 

### What did you expect to see?

Traefik using ACME client to generate LE certificates and use it for configured routers.

### What did you see instead?

Traefik does not generate LE certificates and uses default self-signed certificate, because it is matching the domain. Acme.json is not modified, and logs shows `No ACME certificate generation required for domains`. I don't think it's misconfiguration, becuase LE cert for `secondary-domain.com` `web` service is generated sucessfully. Once I removed the whole `defaultCertificate` from dynamic configuration, LE certs were generated for the rest of services on `primary-domain.com` domain. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.0
Codename:     livarot
Go version:   go1.15.6
Built:        2021-01-19T17:26:51Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Static
```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'

certificatesResolvers:
  le:
    acme:
      email: <redacted>
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: http

serversTransport:
  insecureSkipVerify: true

ping: {}

api:
  dashboard: true

log:
  level: DEBUG

providers:
  file:
    directory: /etc/traefik
    watch: true
```
Dynamic
```yaml
http:

  routers:
    traefik:
      entryPoints:
        - https
      rule: Host(`traefik.primary-domain.com`)
      service: api@internal
      tls: {}
    unifi:
      entryPoints:
        - https
      rule: Host(`unifi.primary-domain.com`)
      service: unifi
      tls: {}
    heimdall:
      entryPoints:
        - https
      rule: Host(`heimdall.primary-domain.com`)
      service: heimdall
      tls: {}
    portainer:
      entryPoints:
        - https
      rule: Host(`portainer.primary-domain.com`)
      service: portainer
      tls: {}
    bitwarden:
      entryPoints:
        - https
      rule: Host(`bitwarden.primary-domain.com`)
      service: bitwarden
      tls:
        certResolver: le
    plex:
      entryPoints:
        - https
      rule: Host(`plex.primary-domain.com`)
      service: plex
      tls:
        certResolver: le
    nextcloud:
      entryPoints:
        - https
      rule: Host(`nextcloud.primary-domain.com`)
      service: nextcloud
      tls:
        certResolver: le
    web-http:
      entryPoints:
        - http
      rule: Host(`secondary-domain.com`)
      middlewares:
        - redirect-http
      service: web
    web-https:
      entryPoints:
        - https
      rule: Host(`secondary-domain.com`)
      service: web
      tls:
        certResolver: le

  middlewares:
    redirect-http:
      redirectScheme:
        permanent: true
        scheme: https

  services:
    unifi:
      loadBalancer:
        servers:
          - url: https://management.primary-domain.com:8443
    heimdall:
      loadBalancer:
        servers:
          - url: http://management.primary-domain.com:12080
    portainer:
      loadBalancer:
        servers:
          - url: http://management.primary-domain.com:9000
    bitwarden:
      loadBalancer:
        servers:
          - url: http://management.primary-domain.com:16080
    plex:
      loadBalancer:
        servers:
          - url: https://entertainment.primary-domain.com:32400
    nextcloud:
      loadBalancer:
        servers:
          - url: http://nextcloud.primary-domain.com
    web:
      loadBalancer:
        servers:
          - url: http://web.primary-domain.com

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/_.primary-domain.com.crt
        keyFile: /etc/traefik/certs/_.primary-domain.com.pem
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
