### ISSUE TITLE
Allow status 308 for middleware RedirectRegex

### ISSUE THREAD

**Issue by ronald** [traefik/traefik#7829]
### What did you expect to see?
Redirect with status 308

```yaml
# Redirect with domain replacement
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-with-308
spec:
  redirectRegex:
    regex: ^https?://example.com/script-path
    replacement: https://v3.example.com/new-script-path
    permanent: 308 # invalid value. traefik expects "true"
```
