### ISSUE TITLE
traefik does not recognize my jackett service? keeps loading

### ISSUE THREAD

**Issue by jboesh** [traefik/traefik#7837]
Hello,

I've been trying for days but can't get it done so hope some of you can help.
I have rolled out the following docker compose (YAML) file, that all seems to be going well because I can access jackett on my LAN at this address: 192.168.1.1:8008/jackett

however as soon as I try to make it available with Traefik at an external address (eg jackett.mydomain.com) nothing happens. then it runs in a timeout. What am I missing? it looks like Traefik does not recognize the IP or something...?

a note, if I try this with for example emby image and I enter network_mode HOST there, this is recognized directly by Traefik ... but in this example I cannot use HOST and it seems to me there must be another solution.

my services:
```
version: "3.4"
services:
  nordvpn:
    image: bubuntux/nordvpn:3.7.4
    container_name: nordvpn
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun
    environment:
      - "USER=mymail@gmail.com"
      - "PASS=mypassword"
      - CONNECT=Netherlands
      - TECHNOLOGY=NordLynx
      - TZ=Europe/Amsterdam
      - DEBUG=On

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=100
    volumes:
      - /share/docker/compose/appdata/jackett:/config
      - /share/downloads:/media/torrent
    restart: always
    network_mode: service:nordvpn
    depends_on: 
      - nordvpn

  web:
    image: dperson/nginx
    links:
      - nordvpn:jackett
    depends_on:
      - jackett
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx
    ports:
      - 8008:80
      - 4431:443
    command: -w "http://jackett:9117/jackett;/jackett"
```

my traefik dynamic file:
```
http:
  routers:
    jackett-rtr:
      entryPoints: https
      rule: "Host(`jackett.mydomain.com`)"
      service: jack1-svc
      middlewares:
        - chain-no-auth
      tls:
        options: default
        certResolver: cloudflare
        domains:
          - main: "*.mydomain.com"
            sans:
              - mydomain.com
```

my traefik yml file:
```
version: "3.4"
services:
  app:
    image: traefik:latest
networks:
  traefik_public:
    external: true
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /share/docker/swarm/configs/traefik:/etc/traefik
      - /share/docker/swarm/appdata/traefik:/etc/traefik/logs
      - /share/docker/swarm/appdata/traefik:/etc/traefik/certs:rw
    networks:
      - traefik_public
    command: --configFile=/etc/traefik/traefik-static.yaml
    deploy:
      placement:
        constraints: 
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.mydomain.com`)"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.middlewares=chain-oauth@file"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
```

my traefik static file:
```
global:
  checkNewVersion: true

entryPoints:
  http:
    address: ":80"
    # Trust IPv4 Private Address Space
    forwardedHeaders:
      trustedIPs:
      # Local Network IP ranges
      - "192.168.1.0/16"
      - "172.16.0.0/12"
      - "10.0.0.0/8"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
          priority: 300

  https:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
      # Local Network IP ranges
      - "192.168.1.0/16"
      - "172.16.0.0/12"
      - "10.0.0.0/8"
    http:
      tls:
        options: default
        certResolver: cloudflare
        domains:
          - main: mydomain.com
            sans:
            - "*.mydomain.com"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock" 
    watch: true
    swarmMode: true
    network: traefik_public
    useBindPortIP: false
    exposedByDefault: false

  file:
    filename: /etc/traefik/traefik-dynamic.yaml
    watch: true
    debugLogGeneratedTemplate: false

  rest:
    insecure: true

api:
  dashboard: true
  insecure: true
  debug: false

log:
  level: DEBUG
  filePath: "/etc/traefik/logs/traefik.log"

accessLog:
  filePath: "/etc/traefik/logs/access.log"

certificatesResolvers:
  cloudflare:
    acme:
      email: "myemail@gmail.com"
      storage: "/etc/traefik/certs/acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 60
        resolvers:
        - "1.1.1.1:53"
        - "8.8.8.8:53"
```
traefik log:
```
time="2021-02-01T07:36:06Z" level=debug msg="Adding route for jackett.mydomain.com with TLS options default" entryPointName=https

time="2021-02-01T07:36:17Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7\"],\"Cache-Control\":[\"max-age=0\"],\"Cookie\":[\"__cfduid=d0cc17c12b29509676d4901320ddf93401612162996; _forward_auth=amzNTMUBIEP4oZYm2EnmxYa_CG1o2UNOjpoGeHZP5_g=|1612768019|mymail@gmail.com\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Sec-Gpc\":[\"1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36\"],\"X-Forwarded-Host\":[\"jackett.mydomain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"a570af98e94b\"],\"X-Real-Ip\":[\"192.168.2.254\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"jackett.mydomain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.2.254:56115\",\"RequestURI\":\"/\",\"TLS\":null}"

time="2021-02-01T07:36:17Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7\"],\"Cache-Control\":[\"max-age=0\"],\"Cookie\":[\"__cfduid=d0cc17c12b29509676d4901320ddf93401612162996; _forward_auth=amzNTMUBIEP4oZYm2EnmxYa_CG1o2UNOjpoGeHZP5_g=|1612768019|myemail@gmail.com\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Sec-Gpc\":[\"1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36\"],\"X-Forwarded-Host\":[\"jackett.mydomain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"a570af98e94b\"],\"X-Real-Ip\":[\"192.168.2.254\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"jackett.mydomain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.2.254:56115\",\"RequestURI\":\"/\",\"TLS\":null}" ForwardURL="http://192.168.1.1:8008/"
```

thank you in advance!!!
