### ISSUE TITLE
2.4.0 not pick up IngressRoute CRD ?

### ISSUE THREAD

**Issue by terrych0u** [traefik/traefik#7838]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Upgrade traefik from `2.3.7` to `2.4.0` using [helm charts](https://github.com/traefik/traefik-helm-chart)

### What did you expect to see?

everything running well

### What did you see instead?

My endpoint becomes 404 status, and when I looking the dashboard, all my IngressRouete CRD were disappeared,
(But using kubectl command to get ingressroute, it still there.)
Seems like traefik 2.4.0 didn't pick up the ingressroute crd.

But everything working well when I downgrade back to `2.3.7`

Is there anything I missed?

PS. I also try to add the newest ServersTransport crd with IngreeRoute, but still got 404.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.4.0
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
globalArguments:
  - "--global.checknewversion"
  - "--global.sendanonymoususage"
  - "--api.insecure=true"
  - "--metrics=true"
  - "--metrics.prometheus=true"
  - "--ping.entryPoint=web"
  - "--entryPoints.web.forwardedHeaders.insecure"
  - "--providers.kubernetesingress=true"

additionalArguments:
  - '--providers.kubernetesingress.ingressclass="traefik"'
  - "--providers.kubernetescrd.labelselector=traefik=traefik"
```
others using default from charts

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```json
{"ClientAddr":"10.10.10.10:1234","ClientHost":"1.1.1.1","ClientPort":"51350","ClientUsername":"-","DownstreamContentSize":19,"DownstreamStatus":404,"Duration":85981,"OriginContentSize":19,"OriginDuration":21555,"OriginStatus":404,"Overhead":64426,"RequestAddr":"www.example.com","RequestContentSize":0,"RequestCount":30,"RequestHost":"www.example.com","RequestMethod":"GET","RequestPath":"/","RequestPort":"-","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"StartLocal":"2021-02-01T08:11:42.626276514Z","StartUTC":"2021-02-01T08:11:42.626276514Z","entryPointName":"web","level":"info","msg":"","request_User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:85.0) Gecko/20100101 Firefox/85.0","time":"2021-02-01T08:11:42Z"}
```
