### ISSUE TITLE
TLS options don't take any effect

### ISSUE THREAD

**Issue by pkarrot** [traefik/traefik#7844]
I have added 'default' TLS options to main traefik config:

```
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
```

But it has no effect. openssl s_client and www.ssllabs.com still reports TLS1.0.
Routers are created dynamically via k8s ingress and don't specify any TLS options.
Also dashboard doesn't show any TLS options on routers.

Any hints what can be wrong?
