### ISSUE TITLE
Traefik v2.3 not finding any services in Docker Swarm Stack

### ISSUE THREAD

**Issue by mstaicu** [traefik/traefik#7850]
Hello!

I think this question has been asked many times before but it always seems to creep back up because of different nuances of uniqueness to every case.

> tl;dr;

Traefik not discovering any services in a 3 node Swarm Stack cluster

> tl;dr;

The 3 node cluster is made out of 3 Droplets on Digital Ocean, each one of those droplets has a DNS A record (same host name) pointing to the public IP of the Droplet.

> Aim

What I'm trying to do is to get the example at [dockerswarm.rocks/traefik](https://dockerswarm.rocks/traefik/) working in a 3 node Swarm Stack Cluster

Current status:

> /api/entrypoints

```
[
  {
    address: ':80',
    transport: {
      lifeCycle: { graceTimeOut: 10000000000 },
      respondingTimeouts: { idleTimeout: 180000000000 },
    },
    forwardedHeaders: {},
    http: {},
    name: 'web',
  },
  {
    address: ':443',
    transport: {
      lifeCycle: { graceTimeOut: 10000000000 },
      respondingTimeouts: { idleTimeout: 180000000000 },
    },
    forwardedHeaders: {},
    http: {},
    name: 'websecure',
  },
];
```

> /api/routers

```
[
  {
    entryPoints: ['websecure'],
    service: 'api@internal',
    rule: 'Host(`${DOMAIN}?Variable not set`)',
    tls: { certResolver: 'le' },
    status: 'enabled',
    using: ['websecure'],
    name: 'traefik@docker',
    provider: 'docker',
  },
];
```

> /api/services

```
[
  {
    status: 'enabled',
    usedBy: ['traefik@docker'],
    name: 'api@internal',
    provider: 'internal',
  },
  { status: 'enabled', name: 'dashboard@internal', provider: 'internal' },
  { status: 'enabled', name: 'noop@internal', provider: 'internal' },
  {
    loadBalancer: {
      servers: [{ url: 'http://10.0.16.4:8080' }],
      passHostHeader: true,
    },
    status: 'enabled',
    name: 'traefik@docker',
    provider: 'docker',
    type: 'loadbalancer',
  },
];
```

Configuration files

> docker-compose.yml

```
version: "3.1"

services:

  traefik:
    image: traefik:2.3

  api:
    image: secretexpress/api

  postgres:
    image: postgres
```

> docker-compose-staging.yml

```
version: "3.1"

services:

  traefik:
    ports:
      - 80:80
      - 443:443
    deploy:
      placement:
        constraints:
          - node.labels.traefik-certificates == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        - traefik.http.routers.traefik.tls=true
        - traefik.http.routers.traefik.tls.certresolver=le
        - traefik.http.routers.traefik.entrypoints=websecure
        - traefik.http.routers.traefik.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.services.traefik.loadbalancer.server.port=8080
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `public`)
      - --providers.docker.exposedbydefault=false
      #
      - --providers.docker.swarmMode=true
      #
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.websecure.address=:443
      #
      - --certificatesresolvers.le.acme.email=${EMAIL?Variable not set}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      #
      - --accesslog
      - --log
      - --api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-certificates:/certificates
    networks:
      - public

  api:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.docker.network=public
      #
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=le
      #
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.rule=Host(`${DOMAIN?Variable not set}`) && PathPrefix(`/api`)
      - traefik.http.routers.api.middlewares=api-stripprefix
      - traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api
      - traefik.http.services.api-service.loadbalancer.server.port=3000
    environment:
      - API_ENV_FILE=/run/secrets/api_env
    secrets:
      - api_env
    networks:
      - public

  postgres:
    environment:
      - POSTGRES_USER_FILE=/run/secrets/psql_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_password
    secrets:
      - psql_user
      - psql_password
    networks:
      - public

networks:
  public:
    external: true

volumes:
  traefik-certificates:

secrets:
  api_env:
    external: true
  #
  psql_user:
    external: true
  psql_password:
    external: true
```

I'm deploying my stack in the following way:

```
$ docker stack deploy --compose-file docker-compose.yml -c docker-compose.staging.yml --with-registry-auth tma1
```

And here are some details about my cluster

```
$ docker stack ls
NAME      SERVICES   ORCHESTRATOR
tma1      3          Swarm

$ docker stack ps tma1
ID             NAME              IMAGE                      NODE      DESIRED STATE   CURRENT STATE            ERROR     PORTS
nve5grdy466q   tma1_api.1        secretexpress/api:latest   tma-2     Running         Running 22 minutes ago
r9lfawkkjbv6   tma1_postgres.1   postgres:latest            tma-4     Running         Running 22 minutes ago
q8n3o1wncjcn   tma1_traefik.1    traefik:2.3                tma-2     Running         Running 22 minutes ago

root@tma-2:~# docker node ls
ID                            HOSTNAME   STATUS    AVAILABILITY   MANAGER STATUS   ENGINE VERSION
wivscyn7mbqlb2svv39ho1zsi *   tma-2      Ready     Active         Leader           20.10.2
o2pq2zdoevbgp3b8hkvhlbw8a     tma-3      Ready     Active                          20.10.2
zyp4nwh3ym8xydlmla1uy6ewo     tma-4      Ready     Active         Reachable        20.10.2

root@tma-2:~# docker node ps
ID             NAME             IMAGE                      NODE      DESIRED STATE   CURRENT STATE            ERROR     PORTS
nve5grdy466q   tma1_api.1       secretexpress/api:latest   tma-2     Running         Running 27 minutes ago
q8n3o1wncjcn   tma1_traefik.1   traefik:2.3                tma-2     Running         Running 27 minutes ago
```

When viewing the Traefik instance logs, there is no mention whatsoever of the `api` service

```
root@tma-2:~# docker service logs -f a75am0o0pne0
tma1_traefik.1.q8n3o1wncjcn@tma-2    | time="2021-02-02T08:32:18Z" level=info msg="Configuration loaded from flags."
tma1_traefik.1.q8n3o1wncjcn@tma-2    | 10.0.0.2 - - [02/Feb/2021:08:32:24 +0000] "GET / HTTP/2.0" 302 34 "-" "-" 1 "traefik@docker" "-" 0ms
tma1_traefik.1.q8n3o1wncjcn@tma-2    | 10.0.0.2 - - [02/Feb/2021:08:32:24 +0000] "GET /dashboard/ HTTP/2.0" 304 0 "-" "-" 2 "traefik@docker" "-" 0ms
tma1_traefik.1.q8n3o1wncjcn@tma-2    | 10.0.0.2 - - [02/Feb/2021:08:32:25 +0000] "GET /api/version HTTP/2.0" 200 85 "-" "-" 3 "traefik@docker" "-" 0ms
tma1_traefik.1.q8n3o1wncjcn@tma-2    | 10.0.0.2 - - [02/Feb/2021:08:32:25 +0000] "GET /api/version HTTP/2.0" 200 85 "-" "-" 4 "traefik@docker" "-" 0ms
```

Last but not least, the network on which the Swarm runs is the `public` network

```
root@tma-2:~# docker network ls
NETWORK ID     NAME              DRIVER    SCOPE
eb9307d02fe7   bridge            bridge    local
4b68edde0727   docker_gwbridge   bridge    local
fd35d8cf012f   host              host      local
xi7i24kk6rfa   ingress           overlay   swarm
2ecb3b601edd   none              null      local
odng3c8kllyw   public            overlay   swarm
```

Now for the million dollar question. What am I doing wrong?
