### ISSUE TITLE
Failing to extract span context for Traefik Jaeger Tracing

### ISSUE THREAD

**Issue by franz-josef-kaiser** [traefik/traefik#7855]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
I set up Traefik, attached _Jaeger_ as Tracer and some other services proxied behind Traefik.

Stack: Docker Compose, File + Docker provider.

### What did you expect to see?
Traces that combine spans which show the full request cycle (Traefik > App > Traefik).

### What did you see instead?
Separated traces of Traefik and Applications. And errors in the Traefik `error.log` that explain that the _(…) SpanContext was not found in the `Extract` carrier_.

### Output of `traefik version`:

```python
/etc/traefik # traefik version
Version:      2.3.6
Codename:     picodon
Go version:   go1.15.6
Built:        2020-12-17T16:34:27Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

* macOS 11.1
* Docker Compose `docker-compose version 1.27.4, build 40524192`
* [Jaeger as Container `jaegertracing/all-in-one:1.21.0`](https://hub.docker.com/layers/jaegertracing/all-in-one/1.21.0/images/sha256-941be50636925febf76c55545e3ff45c0ffb01818666eef20168c61c9ee7f8d4?context=explore)
* [Traefik as Container `traefik:2.4.2`](https://hub.docker.com/layers/traefik/library/traefik/2.4.2/images/sha256-d8b5a6ce57328c624e7c2c1c4540ab3991e341e8b26e63ce5878f44a53422b95?context=explore)

#### Traefik Compose
```env
# Network
ROOT_DOMAIN=example.test
DEFAULT_NETWORK=traefik
```

```yaml
---
version: '3'
services:
    image: "traefik:2.4.2"
    hostname: "controller"
    restart: on-failure
    security_opt:
      - no-new-privileges:true
    ports:
      - "443:443"
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      - "8082:8082"
      - "8083:8083"
    networks:
      - default
    working_dir: /etc/traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/controller/static.yml:/etc/traefik/traefik.yml:ro
      - ${PWD}/controller/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - cert-storage:/usr/local/share/ca-certificates:ro
      - ${PWD}/logs/traefik:/var/log/traefik

volumes:
  cert-storage:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/certs/certs

networks:
  default:
    external: true
    name: ${DEFAULT_NETWORK}
```

##### Traefik Conf
```yaml
# static.yaml (Traefik conf)
debug: true

log:
  level: DEBUG
  filePath: /var/log/traefik/error.log
  format: json

serversTransport:
  insecureSkipVerify: true

api:
  dashboard: true
  insecure: true
  debug: true

providers:
  docker:
    exposedByDefault: false
    swarmMode: false
    watch: true
    defaultRule: "Host(`{{ normalize .Name }}.bell.test`)"
    endpoint: "unix:///var/run/docker.sock"
    network: traefik
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

tracing:
  serviceName: "controller"
  spanNameLimit: 250
  jaeger:
    samplingType: const
    samplingParam: 1.0
    samplingServerURL: http://tracer:5778/sampling
    localAgentHostPort: 127.0.0.1:6831
    gen128Bit: true
    propagation: jaeger
    traceContextHeaderName: "traefik-trace-id"
    collector:
      endpoint: http://tracer:14268/api/traces?format=jaeger.thrift
```

#### Jaeger
```yaml
---
version: '3'
services:
  tracer:
    image: "jaegertracing/all-in-one:1.21.0"
    hostname: "tracer"
    command:
      - "--log-level=info"
      - "--admin.http.host-port=:14269"
      - "--query.ui-config=/usr/local/share/jaeger/ui/conf.json"
    environment:
      SPAN_STORAGE_TYPE: memory
    restart: on-failure
    security_opt:
      - no-new-privileges:true
    expose:
      # (default) host:port for the UDP server
      #   @see --processor.zipkin-compact.server-host-port
      - 5775/udp
      # (default) Agent: accept jaeger.thrift in compact Thrift protocol used by most current Jaeger clients
      #   @see --processor.jaeger-compact.server-host-port
      - 6831/udp
      # (default) Agent: accept jaeger.thrift in binary Thrift protocol used by Node.js Jaeger client
      #   @see --processor.jaeger-binary.server-host-port
      - 6832/udp
      # (default) Agent: serve configs, sampling strategies, @see --http-server.host-port
      - 5778
      # (default) The host:port (e.g. 127.0.0.1:14250 or :14250) of the query's gRPC server
      #   @see --query.grpc-server.host-port
      - 14250
      # (default) Collector: can accept spans directly from clients in jaeger.thrift format over binary thrift protocol
      - 14268
      # Collector: admin port: health check at `/` and metrics at /metrics
      - 14269
      # Agent: admin port: health check at `/` and metrics at /metrics
      - 14271
      # (default) Query Service & UI: The host:port (e.g. 127.0.0.1:14268 or :14268) of the query's HTTP server
      #   @see --query.http-server.host-port
      #   + (http) `/api/*` endpoints and Jaeger UI at `/`
      #   + (grpc) Protobuf/gRPC QueryService
      - 16686
      # Query Service & UI: admin port: health check at `/` and metrics at /metrics
      - 16687
    volumes:
      - ${PWD}/tracer/conf:/usr/local/share/jaeger
      - ${PWD}/logs/jaeger:/var/log/@TODO
      - cert-storage:/usr/local/share/ca-certificates
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DEFAULT_NETWORK}"
      # Admin UI router
      - "traefik.http.routers.tracer-router.rule=Host(`tracer.$ROOT_DOMAIN`)"
      - "traefik.http.routers.tracer-router.entrypoints=https"
      - "traefik.http.routers.tracer-router.tls=true"
      - "traefik.http.routers.tracer-router.tls.options=default"
      - "traefik.http.routers.tracer-router.service=tracer"
      # Service/ Load Balancer
      - "traefik.http.services.tracer.loadbalancer.passhostheader=true"
      - "traefik.http.services.tracer.loadbalancer.server.port=16686"
      - "traefik.http.services.tracer.loadbalancer.server.scheme=http"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
Single entry
```json
{
  "level":"debug",
  "middlewareName":"tracing",
  "middlewareType":"TracingEntryPoint",
  "msg":"Failed to extract the context: opentracing: SpanContext not found in Extract carrier",
  "time":"2021-02-02T23:16:51+01:00"
}
```
Logs
```json
{"level":"debug","msg":"Reporting span 79286f384d3b9b912c4b92ad02dc706a:2c4b92ad02dc706a:0000000000000000:1","time":"2021-02-03T12:02:23+01:00","tracingProviderName":"jaeger"}
{"level":"debug","middlewareName":"tracing","middlewareType":"TracingEntryPoint","msg":"Failed to extract the context: opentracing: SpanContext not found in Extract carrier","time":"2021-02-03T12:02:29+01:00"}
{"level":"debug","middlewareName":"auth@file","middlewareType":"BasicAuth","msg":"Authentication succeeded","time":"2021-02-03T12:02:29+01:00"}
{"level":"debug","msg":"Reporting span 388aa1f4282e0fb2223b0ede9038d936:461c666cd634ffd1:41ddd3c10c662912:1","time":"2021-02-03T12:02:29+01:00","tracingProviderName":"jaeger"}
{"level":"debug","msg":"Reporting span 388aa1f4282e0fb2223b0ede9038d936:41ddd3c10c662912:5364c358cbd6db57:1","time":"2021-02-03T12:02:29+01:00","tracingProviderName":"jaeger"}
{"level":"debug","msg":"Reporting span 388aa1f4282e0fb2223b0ede9038d936:5364c358cbd6db57:765ff1b2dfd4dd01:1","time":"2021-02-03T12:02:29+01:00","tracingProviderName":"jaeger"}
{"level":"debug","msg":"Reporting span 388aa1f4282e0fb2223b0ede9038d936:765ff1b2dfd4dd01:6e3cc63d3dc5a43a:1","time":"2021-02-03T12:02:29+01:00","tracingProviderName":"jaeger"}
{"level":"debug","msg":"Reporting span 388aa1f4282e0fb2223b0ede9038d936:6e3cc63d3dc5a43a:4c4ecc40ce9b68e1:1","time":"2021-02-03T12:02:29+01:00","tracingProviderName":"jaeger"}
{"level":"debug","msg":"Reporting span 388aa1f4282e0fb2223b0ede9038d936:4c4ecc40ce9b68e1:5a8e7785199b7274:1","time":"2021-02-03T12:02:29+01:00","tracingProviderName":"jaeger"}
{"level":"debug","msg":"Reporting span 388aa1f4282e0fb2223b0ede9038d936:5a8e7785199b7274:223b0ede9038d936:1","time":"2021-02-03T12:02:29+01:00","tracingProviderName":"jaeger"}
{"level":"debug","msg":"Reporting span 388aa1f4282e0fb2223b0ede9038d936:223b0ede9038d936:0000000000000000:1","time":"2021-02-03T12:02:29+01:00","tracingProviderName":"jaeger"}
{"level":"debug","middlewareName":"tracing","middlewareType":"TracingEntryPoint","msg":"Failed to extract the context: opentracing: SpanContext not found in Extract carrier","time":"2021-02-03T12:02:33+01:00"}
{"level":"debug","middlewareName":"auth@file","middlewareType":"BasicAuth","msg":"Authentication succeeded","time":"2021-02-03T12:02:33+01:00"}
{"level":"debug","msg":"Reporting span 02a9543f2fc252557b4b2dcaf71bac7d:44695a42b9926466:578074b65aa32461:1","time":"2021-02-03T12:02:33+01:00","tracingProviderName":"jaeger"}
{"level":"debug","msg":"Reporting span 02a9543f2fc252557b4b2dcaf71bac7d:578074b65aa32461:2ca148487ec0313b:1","time":"2021-02-03T12:02:33+01:00","tracingProviderName":"jaeger"}
```
