### ISSUE TITLE
ingressroute to externalname with host header issue

### ISSUE THREAD

**Issue by yongzhang** [traefik/traefik#7861]
My traefik version: 2.3.6

Original issue is here:
https://github.com/traefik/traefik/issues/6000

The issue was closed, but I don't know why, I have the same config but it doesn't work:

```
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  ports:
  - name: https
    port: 443
  type: ExternalName
  externalName: https://externaldomain.com

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: proxy-headers
spec:
  headers:
    customRequestHeaders:
      Host: mydomain2.com

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: proxy
  annotations:
    kubernetes.io/ingress.class: traefik-public
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`mydomain1.com`)
    kind: Rule
    services:
    - name: proxy
      port: 443
      passHostHeader: false
    middlewares:
    - name: proxy-headers

```

Please help, thanks.
