### ISSUE TITLE
Poor TCP Load Balancing

### ISSUE THREAD

**Issue by dadgar** [traefik/traefik#7863]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have three instances of a service that are registered in a Consul Catalog as TCP services. They all have the following tags:

```yml
          "traefik.enable=true",
          "traefik.tcp.routers.scada.entrypoints=scada",
          "traefik.tcp.routers.scada.rule=HostSNI(`*`)",
          "traefik.tcp.routers.scada.tls=true",
          "traefik.tcp.routers.scada.tls.passthrough=true",
```

Relevant part of Traefik config:

```toml
# Load services from Consul catalog
[providers]
  [providers.consulCatalog]
    # Do not automatically expose our services.
    exposedByDefault = false

    # Poll Consul every 5 seconds
    refreshInterval = "5s"

    # Address to talk to Consul
    [providers.consulCatalog.endpoint]
      address = "XXX:YYY"

[entryPoints]
  [entryPoints.scada]
    address = "0.0.0.0:7223"
```

 I have client connecting at a very steady rate to the endpoint.

### What did you expect to see?

I would expect to see a very even balance of connections to the three services.

### What did you see instead?

So when I do a rollout of the service they start out with an even load but over time the load distribution becomes heavily weighted to the first service instance return from the Consul Catalog, followed by the second, then third. You can see that in this graph here which tracks the number of open connections by instance:

<img width="2216" alt="Screen Shot 2021-02-05 at 6 05 57 PM" src="https://user-images.githubusercontent.com/1047914/107105824-24eedf80-67dd-11eb-8b34-3b2ac71045c0.png">

The next graph shows new connections being established over time group by instance type. You can see it is essentially all going to a single instance:

<img width="2214" alt="Screen Shot 2021-02-05 at 6 19 55 PM" src="https://user-images.githubusercontent.com/1047914/107106116-cfb3cd80-67de-11eb-8ccb-a1c234c4ef06.png">

Thus as clients disconnect naturally, all new connections keep bunching up on just one instance.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v2.1.8
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Running on Nomad on AWS.

### Hypothesis

<img width="834" alt="Screen Shot 2021-02-05 at 6 06 17 PM" src="https://user-images.githubusercontent.com/1047914/107105854-6a131180-67dd-11eb-9982-a3e5bc2939a2.png">

Digging through the code a bit, my hypothesis is that every five seconds when the Consul catalog is pulled and passed as a new config, a new router is created here:

https://github.com/traefik/traefik/blob/d211437d6ca4b26bd5e8f7901adb916bdf44f61b/cmd/traefik/traefik.go#L284

Following the following code bits:

https://github.com/traefik/traefik/blob/d211437d6ca4b26bd5e8f7901adb916bdf44f61b/pkg/server/routerfactory.go#L80-L81
https://github.com/traefik/traefik/blob/d211437d6ca4b26bd5e8f7901adb916bdf44f61b/pkg/server/router/tcp/router.go#L80
https://github.com/traefik/traefik/blob/d211437d6ca4b26bd5e8f7901adb916bdf44f61b/pkg/server/router/tcp/router.go#L242
https://github.com/traefik/traefik/blob/d211437d6ca4b26bd5e8f7901adb916bdf44f61b/pkg/server/service/tcp/service.go#L68

It appears the end result is the weighted round robin load balancer gets reset every 5 seconds to the same order of services returned by the Consul Catalog.
