### ISSUE TITLE
Errors middleware mixes response code on 302 query response

### ISSUE THREAD

**Issue by linuxgemini** [traefik/traefik#7872]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

  * Implemented the example Traefik config at https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#configuring-for-use-with-the-traefik-v2-forwardauth-middleware (Disclosure: I am the author of the example config.)

  * Enabled a feature on oauth2-proxy where the sign-in is done automatically instead of requiring user input.

  * Went to `a-service.example.com`.

### What did you expect to see?

A series of redirects to the authentication provider and access to the `a-service.example.com`.

### What did you see instead?

A 401 response with a Location header when the errors query actually gives a 302.

![](https://btw.i-use-ar.ch/i/vgq3yed5.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
root@fsn1:~# traefik version
Version:      2.4.2
Codename:     livarot
Go version:   go1.15.7
Built:        2021-02-02T17:20:41Z
OS/Arch:      linux/amd64
root@fsn1:~#
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
root@fsn1:~# uname -a
Linux fsn1 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@fsn1:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
root@fsn1:~#
```

Using File provider for both Static and Dynamic Configuration.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
Feb 08 18:54:52 fsn1 traefik[144341]: time="2021-02-08T18:54:52+01:00" level=debug msg="Remote error http://172.16.0.1:4180/oauth2/auth. StatusCode: 401" middlewareType=ForwardedAuthType middlewareName=asd-auth@file
Feb 08 18:54:52 fsn1 traefik[144341]: time="2021-02-08T18:54:52+01:00" level=debug msg="Caught HTTP Status Code 401, returning error page" middlewareType=customError middlewareName=asd-errors@file
Feb 08 18:54:52 fsn1 traefik[144341]: time="2021-02-08T18:54:52+01:00" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request=SEEBELOW
Feb 08 18:54:52 fsn1 traefik[144341]: time="2021-02-08T18:54:52+01:00" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request=SEEBELOW
Feb 08 18:54:52 fsn1 traefik[144341]: time="2021-02-08T18:54:52+01:00" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request=SEEBELOW
```

```json
{
    "Method": "GET",
    "URL": {
        "Scheme": "http",
        "Opaque": "",
        "User": null,
        "Host": "0.0.0.0",
        "Path": "/oauth2/sign_in",
        "RawPath": "",
        "ForceQuery": false,
        "RawQuery": "",
        "Fragment": "",
        "RawFragment": ""
    },
    "Proto": "HTTP/1.1",
    "ProtoMajor": 1,
    "ProtoMinor": 1,
    "Header": {
        "Accept": [
            "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
        ],
        "Accept-Encoding": [
            "gzip"
        ],
        "Accept-Language": [
            "en-US,en;q=0.9,tr-TR;q=0.8,tr;q=0.7"
        ],
        "Cache-Control": [
            "no-cache"
        ],
        "Connection": [
            "Keep-Alive"
        ],
        "Cookie": [
            ""
        ],
        "Dnt": [
            "1"
        ],
        "Pragma": [
            "no-cache"
        ],
        "Referer": [
            "https://a-service.example.com/"
        ],
        "Sec-Fetch-Dest": [
            "document"
        ],
        "Sec-Fetch-Mode": [
            "navigate"
        ],
        "Sec-Fetch-Site": [
            "same-origin"
        ],
        "Sec-Fetch-User": [
            "?1"
        ],
        "Upgrade-Insecure-Requests": [
            "1"
        ],
        "User-Agent": [
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"
        ],
        "X-Forwarded-For": [
            "REDACTED"
        ],
        "X-Forwarded-Host": [
            "a-service.example.com"
        ],
        "X-Forwarded-Port": [
            "443"
        ],
        "X-Forwarded-Proto": [
            "https"
        ],
        "X-Forwarded-Server": [
            "fsn1"
        ],
        "X-Real-Ip": [
            "REDACTED"
        ]
    },
    "ContentLength": 0,
    "TransferEncoding": null,
    "Host": "0.0.0.0",
    "Form": null,
    "PostForm": null,
    "MultipartForm": null,
    "Trailer": null,
    "RemoteAddr": "",
    "RequestURI": "/oauth2/sign_in",
    "TLS": null
}
```

**Comment by jbdoumenjou** [comment]
Hello @linuxgemini,

Could you provide a simple complete reproducible case?

**Comment by linuxgemini** [comment]
Hi @jbdoumenjou,

The example config is mentioned below:

```yaml
http:
  routers:
    a-service:
      rule: "Host(`a-service.example.com`)"
      service: a-service-backend
      middlewares:
        - error
        - auth
    oauth:
      rule: "Host(`a-service.example.com`, `oauth.example.com`) && PathPrefix(`/oauth2/`)"
      middlewares:
        - auth-headers
      service: oauth-backend
  services:
    a-service-backend:
      loadBalancer:
        servers:
          - url: http://172.16.0.2:7555
    oauth-backend:
      loadBalancer:
        servers:
          - url: http://172.16.0.1:4180
  middlewares:
    auth-headers:
      headers:
        sslRedirect: true
        stsSeconds: 315360000
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        sslHost: example.com
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
    auth:
      forwardAuth:
        address: http://oauth.example.com/oauth2/auth
        trustForwardHeader: true
    errors:
      errors:
        status:
          - "401-403"
        service: oauth-backend
        query: "/oauth2/sign_in"
```

To reproduce:

  * Client goes to `a-service.example.com`, and let `oauth.example.com/oauth2/auth` return a 401
  * When the 401 is returned, `errors` middleware will make a query to `oauth.example.com/oauth2/sign_in`, let `oauth.example.com/oauth2/sign_in` return a 302 with `Location` header set to any other URL
  * Client will get a 401 response with the set `Location` header.

**Comment by jbdoumenjou** [comment]
By a reproducible case, I mean a way to allow reproducing easily the issue quickly without having to configure and to build the whole context. For example, it could be a [docker compose](https://docs.docker.com/compose/) file with the minimal Traefik configuration ([static](https://doc.traefik.io/traefik/v2.4/getting-started/configuration-overview/#the-static-configuration) and [dynamic](https://doc.traefik.io/traefik/v2.4/getting-started/configuration-overview/#the-dynamic-configuration)) that reproduce the issue and all the containers needed for the use case. Finally, all commands used to prove the issue.

Thanks

**Comment by linuxgemini** [comment]
traefik.yaml (Static configuration)

```yaml
serversTransport:
  insecureSkipVerify: true

entryPoints:
  http:
    address: :80
    forwardedHeaders:
      insecure: true

providers:
  providersThrottleDuration: 2s
  file:
    watch: true
    filename: rules.yml

log:
  level: DEBUG
```

</br>

rules.yml (Dynamic Configuration)

```yaml
http:
  routers:
    an-example:
      rule: "Host(`another.example.com`)"
      service: an-example
      middlewares:
        - error
        - auth

  services:
    an-example:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: http://example.com

    httpstatus:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: https://httpstat.us

  middlewares:
    auth:
      forwardAuth:
        address: https://httpstat.us/403
        trustForwardHeader: false

    errors:
      errors:
        status:
          - "401-403"
        service: httpstatus
        query: "/302"
```

A test site is also available on https://traefik7872.linuxgemini.space/
