### ISSUE TITLE
After update from 2.3 consul kv seems not to be recognized. 

### ISSUE THREAD

**Issue by cberescu** [traefik/traefik#7873]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have updated Traefik from version 2.3 to 2.4, i received the fallowing error after the update: 

```connot build the configuration field not found node: providerName=consul```

### What did you expect to see?

That things will still work, i looked in the docs and did not see any changes to this. 

### What did you see instead?

The error described , and 404 on the request.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```

Version:      2.4.2
Codename:     livarot
Go version:   go1.15.7
Built:        2021-02-02T17:20:41Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[entryPoints]
    [entryPoints.http]
		address = ":80"
	[entryPoints.traefik]
		address = ":8081"
	[entryPoints.metrics]
		address = ":8082"	
[metrics]
  [metrics.prometheus]
    entryPoint = "metrics"	
[api]
    dashboard = true
    insecure  = true		
	[providers.consulCatalog]
		prefix = "traefik"
		exposedByDefault = false
		constraints = "Tag(`nid=something`)"
		[providers.consulCatalog.endpoint]
			address = "example.com:8500"
			scheme  = "http"
			token = "something"
	[providers.consul]
		endpoints = ["example:8500"]
		rootKey = "traefik"
		
```
