### ISSUE TITLE
Support fullchain and/or CA certificates

### ISSUE THREAD

**Issue by samip5** [traefik/traefik#7876]
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you expect to see?

I expect to see possibility for custom SSL certificates to get passed CA/fullchain file as well.

### What did you see?

This following syntax not accepted, not with caFile nor fullchainFile.

```toml
[[tls.certificates]]
   certFile = "*.cer"
   keyFile  = "*.key"
   fullchainFile = "fullchain.crt"
```

### Why is this deemed necessary?

Because not all devices will be able to trust the certificate otherwise, this is even more needed due to LetsEncrypt switching to a newer root certificate which a lot of older devices does not support without a fullchain provided to them.
