### ISSUE TITLE
Support multiple certificates for TLSStore defined via K8S

### ISSUE THREAD

**Issue by Jakob3xD** [traefik/traefik#7880]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

The goal of this proposal is to be able to have multiple certificate in a single TLSStore defined via K8S.

### Issue
I have two wildcard certificates for two domain zones.
Both zones have a DNS entry for my k8s pod. Therefore I defined an IngressRoute listening on both domains.
Issue #4756 wont solve my issue, as I want to use both domains in a single IngressRoute definition using `tls: {}`
The following IngressRoute works when using the `file provider` to define the TLSStore but it is not possible to define the same TLSStore within k8s.
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
  name: configs
  namespace: configs
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`config.cluster-name.some.example`)
    services:
    - name: configs
      port: 80
  - kind: Rule
    match: Host(`test.some.example`)
    services:
    - name: configs
      port: 80
  tls: {}
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ traefik_namespace }}-v2-dynamic-file
  namespace: {{ traefik_namespace }}-v2
data:
  tls.yaml: |
    tls:
      certificates:
        - certFile: /cert/example/tls.crt
          keyFile: /cert/example/tls.key
          stores:
            - default
        - certFile: /cert/default/tls.crt
          keyFile: /cert/default/tls.key
          stores:
            - default
      stores:
        default:
          defaultCertificate:
            certFile: /cert/example/tls.crt
            keyFile: /cert/example/tls.key
``` 

### Example of a TLSStore definition
Beside the `defaultCertificate` key add a `certificates` key where a list of certs can be parsed.
```
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik-v2
spec:
  certificates:
    - secretName: some-cert
    - secretName: k8s-cluster-name-wildcard
  defaultCertificate:
    secretName:  k8s-cluster-name-wildcard
```

### Side note
The issue is duplicate to #7210 but it was closed with duplicate of #4756 even so it is not duplicate in my opinion.
I also opened this issue as non of the forum entry's about this issue were answered in any way.
Issue #4756 won't solve my issue as I would need to define an IngressRoute for each Domain I want to use. This would result in an doubled amount of definitions which are unneeded.

**Comment by Segflow** [comment]
Is there any update on this? We also need this

**Comment by grigorov** [comment]
+1

**Comment by ekarlso** [comment]
+1

**Comment by christianvw** [comment]
+1

**Comment by Xitric** [comment]
This is also quite an important feature to us - not because we need to specify multiple certificates, but because we wish to use the `TLSStore` CRD to add certificates to the `default` store to be resolved even with strict SNI enabled.

Correct me if I am wrong (and I would love to be wrong on this one), but when setting Strict SNI on your `TLSOption`, the `defaultCertificate` for a `TLSStore` will simply be ignored. At least, that seems to be what is going on in `tlsmanager.go`, and this is also the behaviour I have observed in our deployments:

https://github.com/traefik/traefik/blob/1048348ae65497feb4a05e090f0ac910586c7996/pkg/tls/tlsmanager.go#L152-L162

The method `GetBestCertificate` only looks through `DynamicCerts` - is the `DefaultCertificate` not part of that data structure?

https://github.com/traefik/traefik/blob/1048348ae65497feb4a05e090f0ac910586c7996/pkg/tls/certificate_store.go#L91-L99

For instance, we have deployed the following `TLSStore` to our kubernetes cluster:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-10.19.4
    app.kubernetes.io/managed-by: Helm
spec:
  defaultCertificate:
    secretName: "our-certificate-secret"
```

But using this along with strict SNI, we get errors stating that no certificate could be found that matches the requested domains. However, after deploying an `IngressRoute` that explicitly references a certificate secret (and implicitly linking with the `default` certificate store), the certificate is resolved correctly even from other `IngressRoutes` with an empty `tls` configuration. Seems that this has caused the certificate to become part of the `DynamicCerts` structure?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "some-ingress"
  annotations:
    kubernetes.io/ingress.class: "traefik-internal"
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`something.something`)
    services:
    - kind: Service
      name: "some-service"
      namespace: "some-namespace"
      port: 8080
  tls:
    secretName: "our-certificate-secret"
```

So it seems that it would be highly valuable to be able to specify certificates for the `DynamicCerts` structure via the `TLSStore` CRD.

**Comment by Xitric** [comment]
Hello @rtribotte and thanks for the swift reply,

While it is certainly possible to add certificates via `IngressRoutes`, it does not quite fit with our setup. Our setup has two layers of TLS termination:

1. An application gateway serving client-facing certificates
2. Traefik ingress controller in Kubernetes

With this design, we are using a broad SAN certificate for the Traefik ingress controller. So pretty much all `IngressRoutes` should use the same TLS certificate (with some exceptions). _We do, however, still want to enable strict SNI if possible_, because we only want to return the certificate for requests with matching host names.

So, we are looking for a way to add the certificate centrally, as opposed to having an arbitrary `IngressRoute` with that responsibility. After all, a developer would not anticipate that removing one `IngressRoute` adversely impacts the others (in completely different namespaces even) by removing their shared TLS certificate. And we also don't want to add the certificate secret to every single namespace (we have a lot).

We know that it is possible to configure this with the configuration file that we can mount onto the Traefik pod (and this is how we do it for the time being). But it just seems like a missed opportunity now that `TLSOptions` and the default certificate are supported with Kubernetes CRDs, why not go the entire way and add support for centrally configuring certificates via Kubernetes secrets and the TLSStore CRD? Essentially the CRD alternative to this configuration:

```toml
[tls]
  [[tls.certificates]]
    certFile = "/certs/tls.crt"
    keyFile = "/certs/tls.key"
    stores = ["default"]
```

For us, this is the only configuration we cannot currently express _centrally_ via either CRDs or CLI arguments to Traefik.
