### ISSUE TITLE
Can not add x-forwarded-for 

### ISSUE THREAD

**Issue by winds6206** [traefik/traefik#7881]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I use traefik to proxy some application, but my traefik can not add remote-ip to X-Forwarded-For to header

Client(1.1.1.1) -> F5(2.2.2.2) -> traefik(3.3.3.3) -> application(5.5.5.5) 

Header value will be  
X-Forwarded-For: 1.1.1.1, 3.3.3.3

2.2.2.2 won't be add to behind 1.1.1.1

I have set `forwardedHeaders` to forwarded headers information (X-Forwarded-*).

```
      [entryPoints.websecure]
        address = ":443"
        [entryPoints.websecure.forwardedHeaders]
          insecure = true
```

Do I loss any configuration?

Thanks a lot!

### What did you expect to see?

Traefik can add add remote-ip to X-Forwarded-For to header like Nginx

```
proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

Docker Image 
traefik:v2.4

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
      [entryPoints.websecure]
        address = ":443"
        [entryPoints.websecure.forwardedHeaders]
          insecure = true
```
