### ISSUE TITLE
SSE with compression still does not work correctly 

### ISSUE THREAD

**Issue by djmaze** [traefik/traefik#7882]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have an app which serves server-sent events on a certain path. In front of it, I am running traefik 2.2 with the compress middleware activated.

Using the following curl commands, I request the events url without and with compression:

```bash
$ curl 'https://mydomain.com/events' -H 'Accept: text/event-stream' -H 'Cache-Control: no-cache
$ curl 'https://mydomain.com/events' -H 'Accept: text/event-stream' -H 'Cache-Control: no-cache --compressed
```

### What did you expect to see?

Both command output events correctly, like this:

```
event: gameStarted
data:

```

### What did you see instead?

The second command does not output anything.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Using the docker provider in swarm mode. The middleware is configured as follows:

```yaml
traefik.http.middlewares.traefik-compress.compress: "true"
traefik.http.middlewares.traefik-compress.excludedcontenttypes: text/event-stream
```

The app service is configured as follows:

```yaml
traefik.enable: "true"
traefik.docker.network: traefik_traefik
traefik.http.routers.myapp.entrypoints: web-secure
traefik.http.routers.myapp.rule: Host(`app.mydomain.com`)
traefik.http.routers.myapp.middlewares: traefik-compress@docker
traefik.http.services.myapp.loadbalancer.server.port: 8889 
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

The app output shows that it writes the event to the response, but the second curl command does not show it.

### What I think is wrong

I guess the change in #5721 does not fix the problem with SSE because it only allows filtering based on the request `Content-Type` header. SSE uses GET requests and thus does not have a `Content-Type` header at all, but an `Accept` header with `text/event-stream` instead. (At least that's what modern browsers do.)

So in order to solve this problem, we need to be able to filter on the `Accept` header in the compress plugin as well.
