### ISSUE TITLE
entrypoint web breaks acme-challenge when enabling TLS certResolver

### ISSUE THREAD

**Issue by sgohl** [traefik/traefik#7883]
### Do you want to request a *feature* or report a *bug*?

Bug

This worked in v1.7, but now things are designed differently which breaks HTTP-01 challenge.

Presumption: Traefik wrongly assumes web entrypoint is now completely HTTPS/TLS

### What did you do?

According to Traefik Dashboard -> Routers, `PathPrefix .well-known/acme-challenge` has TLS enabled.
This makes me think, therefore letsencrypt-acme verification (and any backend-service too) results in 404

traefik.yml
```
web:
  address: ":80"
  http:
    tls:
      certResolver: letsencrypt

certificatesResolvers:
  letsencrypt:
    acme:
      httpChallenge:
        entryPoint: web
```

This configuration should serve/provide acme-challenge still via HTTP, not suddenly expecting HTTPS.

Evidence: If you disable `tls:  certResolver: letsencrypt` here in the entrypoint, and then set it via docker labels like `- "traefik.http.routers.foo.tls.certresolver=letsencrypt"`, acme-challenge will work, but this is **not** applicable.

### What did you expect to see?

I expect that `tls: certResolver: letsencrypt` will enable certificate-generation for services, but not change the expected HTTP-scheme, at least for acme-challenge, when `HTTP-01` challenge is enabled.

### What did you see instead?

traefik responds with 404 to acme-challenge

```
| 10.0.0.2 - - [05/Feb/2021:12:30:28 +0000] "GET /.well-known/acme-challenge/JSDgbpXAfSu7vuHbEwUFlPbNwp9Pn2PFcT7y_0-981o HTTP/1.1" - - "-" "-" 4 "-" "-" 0ms

msg="Unable to obtain ACME certificate for domains \"bla.mydomain.com\": unable to generate a certificate for the domains [bla.mydomain.com]: error: one or more domains had a problem:\n[bla.mydomain.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://bla.mydomain.com/.well-known/acme-challenge/JSDgbpXAfSu7vuHbEwUFlPbNwp9Pn2PFcT7y_0-981o [51.91.51.41]:
404\n" routerName=bla@docker rule="Host(`bla.mydomain.com`)" providerName=letsencrypt.acme
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
docker.io/traefik:2.4.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
entryPoints:
  web:
    address: ":80"
    http:
      tls:
        certResolver: letsencrypt

accessLog: {}

log:
  level: DEBUG

api:
  insecure: true
  dashboard: true
  debug: true

providers:

  docker:
    exposedByDefault: false
    swarmMode: true
    watch: true
    swarmModeRefreshSeconds: 10
    network: "traefik"

certificatesResolvers:
  letsencrypt:
    acme:
      email: acme@mydomain.com
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: web
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

see ### What did you see instead?
