### ISSUE TITLE
Problem uploading large Maven Artifacts to Nexus Repository Manager (3.29.0) with Traefik (2.4.2) as Reverse Proxy

### ISSUE THREAD

**Issue by BigBrokkokliMan** [traefik/traefik#7885]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I want to use Traefik (2.4.2) as Reverse Proxy for Nexus Repository Manager (3.29.0). Both Applications are running as Docker-Containers on the same host.

### What did you expect to see?

Everything works fine, but uploading large maven artifacts (100MB) fails.

### What did you see instead?

Everything works fine, but uploading large maven artifacts (100MB) with Jenkins fails.

In the traefik log ther is the message "vulcand/oxy/buffer: error when reading request body, err: local error: tls: record overflow". We don't find more informtaion about this error ... The Jenkins-Pipeline (wich wants to upload to the maven-snapshot reporitory with maven-deploy-plugin in version 3.0.0-M1) fails with: Caused by: javax.net.ssl.SSLException: Broken pipe (Write failed). 
For testing, we changes Traefik to Apache (as Reverse Proxy). Now there is no problem - uploading large maven artifacts is working.

Additional there are some warnings "Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel." in the log. It's not clear if there is a connection between the error and the warning.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.2
Codename:     livarot
Go version:   go1.15.7
Built:        2021-02-02T17:20:41Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
services:
  traefik:
    restart: unless-stopped
    image: nexus:10081/traefik:2.4.2
    container_name: traefik
    command:
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.middlewares=default-security,redirect-to-intra-de"
      - "--accesslog.filepath=/log/traefik-access.log"
#     - "--metrics.prometheus=true"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2021-02-10T14:32:32Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:49Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:49Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:49Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:49Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:49Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:49Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:49Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:49Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:49Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:49Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:49Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:49Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:49Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:49Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:49Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:50Z" level=error msg="vulcand/oxy/buffer: error when reading request body, err: local error: tls: record overflow"
time="2021-02-10T14:32:50Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:50Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:50Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:50Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:50Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
time="2021-02-10T14:32:50Z" level=warning msg="Upstream ResponseWriter of type *headers.responseModifier does not implement http.CloseNotifier. Returning dummy channel."
```
