### ISSUE TITLE
Gateway errors during rolling deployment w/sticky sessions

### ISSUE THREAD

**Issue by allanjackson** [traefik/traefik#7886]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
I'm using traefik as a load balancer for a docker swarm so I can enable sticky sessions (loadBalancer.sticky.cookie=true). Everything works great except for during a rolling update of my service. Docker swarm brings up my new containers and then shuts down the old ones.

During this process, there's a few seconds where the old containers have been stopped, but traefik is still trying to route requests to them (resulting in 502 and 504 errors). The default docker swarm routing network works correctly (stops sending requests to stopped containers), but I need to use traefik's routing to enable the sticky sessions.

I tried enabling traefik's retry middleware, but when I checked the debug logs, it just keeps retrying the ip address of the old container that has already been shut down. I am able to produce errors in the browser as well as via the command line with curl or ab (where the sticky cookie isn't actually included in the request).

### What did you expect to see?
I expected that when a docker container goes down, traefik would instantly stop routing requests to it. If that's not actually possible, it should at least detect that requests are failing and the retry middleware should send the subsequent calls to one of the instances that is working.

### What did you see instead?
502 and 504 errors during rolling deployments. Retry middleware keeps retrying the same ip/container that isn't running any more. After a few seconds, the configuration updates and then things start working again.

### Output of `traefik version`: 
traefik:v2.4.2 docker image
```
Version:      2.4.2
Codename:     livarot
Go version:   go1.15.7
Built:        2021-02-02T17:20:41Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?
Docker swarm configured with docker-compose deploy labels. Traefik running with swarmMode=true, and all containers using external "traefik_network". 

App config labels:
```
- "traefik.http.routers.app.rule=PathPrefix(`/`)"
- "traefik.http.services.app.loadbalancer.server.port=8080"
- "traefik.http.services.app.loadBalancer.sticky.cookie=true"

- "traefik.http.middlewares.retry-mw.retry.attempts=10"
- "traefik.http.middlewares.retry-mw.retry.initialinterval=250ms"
- "traefik.http.routers.app.middlewares=retry-mw@docker"

- "traefik.http.services.app.loadBalancer.healthCheck.path=/healthcheck"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2021-02-10T14:59:12Z" level=debug msg="New attempt 4 for request: /MyRequestPath" middlewareName=retry-mw@docker middlewareType=Retry
time="2021-02-10T14:59:12Z" level=debug msg="'502 Bad Gateway' caused by: dial tcp 10.0.2.OldContainerIpHere:8080: connect: no route to host"
```

**Comment by pozylon** [comment]
@allanjackson Similar situation here, I also see "Bad Gateway" often but not only when updating, it occurs independent of service updates and independent of task crashes. This happens with the latest 2.3 here.

 I also use retry middleware and stickiness basically the same way like you (without the traefik lb healthCheck).

It happened around 260 times in 48 hours (50 req/s average)

**Comment by jbdoumenjou** [comment]
Hello @allanjackson,

could you provide a simple complete reproducible case with the minimal Traefik configuration ([static](https://doc.traefik.io/traefik/v2.4/getting-started/configuration-overview/#the-static-configuration) and [dynamic](https://doc.traefik.io/traefik/v2.4/getting-started/configuration-overview/#the-dynamic-configuration)) that reproduce the issue and all the commands used to prove the issue.

Thanks

**Comment by allanjackson** [comment]
Here's a simple setup to reproduce the errors.

docker-stack.yml file:

```
version: "3.7"
services:
    
    app:
        image: traefik/whoami
        
        networks:
            - traefik_network
        
        ports:
            - 80
      
        deploy:
            replicas: 1
            update_config:
                order: start-first
                parallelism: 1

            labels:
                - "traefik.http.routers.app.rule=PathPrefix(`/`)"
                - "traefik.http.services.app.loadbalancer.server.port=80"
                - "traefik.http.services.app.loadBalancer.sticky.cookie=true"

                - "traefik.http.middlewares.retry-mw.retry.attempts=3"
                - "traefik.http.routers.app.middlewares=retry-mw@docker"
    
    
    load-balancer:
        image: traefik:v2.4.2
        
        command:            
            - --providers.docker=true
            - --providers.docker.swarmMode=true
            - --providers.docker.network=traefik_network
            - --entryPoints.app.address=:80
            
            - --log.level=DEBUG
            
        networks:
            - traefik_network
            
        ports:
            - "80:80"
        
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock


networks:
    traefik_network:
        external: true

```


Setup commands:
```
docker swarm init
docker network create -d overlay traefik_network --attachable
docker stack deploy -c docker-stack.yml demo
```


Testing commands:
`docker service update --force demo_app`
IMMEDIATELY after previous command, run:
`ab -n 5000 -s 120 localhost/`

Adjust the 5000 parameter based on how fast your computer handles the incoming requests. If you run those two commands close enough together, the requests will initially go to the first container, but then at some point it'll switch over to the new one.

During the switchover, there will be errors where Traefik tries to send requests to the container that just shut down rather than using the new container that should already be working correctly. You can also see from the logs that the Retry middleware just keeps trying the ip address of the old container rather than switching over to the new one.

Typically when I've been testing it, I see somewhere from 10-30 failed requests each time. If you inspect the docker logs for the traefik container, you can find the errors easily by searching for "gateway". They're typically a mixture of 502 and 504 errors. You can also find the retries easily if you search for "New attempt".

Let me know if you have any other questions or any difficulties with reproducing the issue.

**Comment by Alvise88** [comment]
I have the same problem even without sticky session.

./checkres.sh http://loadbalancer > out.csv
docker service update loadbalancer_whoami --force
awk -F "," '{print $1}' out.csv | grep -v code | grep -v 200

the output contains some 504 rows

```
version: "3.8"

networks:
  ingress-public:
    external: true

services:
  whoami:
    image: traefik/whoami
    networks:
      - ingress-public
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.loadbalancer-test.rule=Host(`loadbalancer`)"
        - "traefik.http.routers.loadbalancer-test.entrypoints=http"
        - "traefik.http.routers.loadbalancer-test.service=configurationserver"
        - "traefik.http.routers.loadbalancer-test.service=loadbalancer-test"
        - "traefik.http.services.loadbalancer-test.loadbalancer.server.port=80"
        #- "traefik.http.services.loadbalancer-test.loadbalancer.sticky=true"
        #- "traefik.http.services.loadbalancer-test.loadbalancer.sticky.cookie.name=traefik_xxx_cookie"
        #- "traefik.http.services.loadbalancer-test.loadbalancer.sticky.cookie.httpOnly=true"
        #- "traefik.http.services.loadbalancer-test.loadbalancer.sticky.cookie.secure=false"
```

```
#!/usr/bin/env bash

# Prereqs: curl

# Set the `errexit` option to make sure that
# if one command fails, all the script execution
# will also fail (see `man bash` for more
# information on the options that you can set).
set -o errexit

# This is the main routine of our bash program.
# It makes sure that we've supplied the necessary
# arguments, then it prints a CSV header and then
# keeps making requests and printing their responses.
#
# Note.: because we're calling `curl` each time in
#        the loop, a new `curl` process is created for
#        each request.
#
#        This means that a new connection will be made
#        each time.
#
#        Such property might be useful when you're testing
#        if a given load-balancer in the middle might be
#        messing up with some requests.
main() {
  local url=$1

  if [[ -z "$url" ]]; then
    echo "ERROR:
  An URL must be provided.

  Usage: check-res <url>

Aborting.
    "
    exit 1
  fi

  print_header
  for i in $(seq 1 10000); do
    make_request $url
  done
}

# This method does nothing more that just print a CSV
# header to STDOUT so we can consume that later when
# looking at the results.
print_header() {
  echo "code,time_total,time_connect,time_appconnect,time_starttransfer"
}

# Make request performs the actual request using `curl`.
# It specifies those parameters that we've defined before,
# taking a given `url` as its parameter.
make_request() {
  local url=$1

  curl \
    --write-out "%{http_code},%{time_total},%{time_connect},%{time_appconnect},%{time_starttransfer}\n" \
    --silent \
    --output /dev/null \
    "$url"
}

main "$@"
```
