### ISSUE TITLE
v2.3 Unable to obtain ACME certificate. Connection reset by peer

### ISSUE THREAD

**Issue by 0xDagal** [traefik/traefik#7887]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Adding a new service from file provider with Let's Encrypt as certificate Resolver.

### What did you expect to see?

A new certificate obtention.

### What did you see instead?

```log
level=error msg="Unable to obtain ACME certificate for domains \"my.service.com\" : cannot get ACME client get directory at 'http://acme-v02.api.letsencrypt.org/directory' : Get \"http://acme-v02.api.letsencrypt.org/directory\": read tcp ip_address:port->ip_address2:80: read: connection reset by peer" providerName=le.acme
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version: 2.3.2
Codename: picodon
Go version: go1.15.3
Built : 2020-10-19T18:36:22Z
OS/Arch : linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
# traefik.yaml
entryPoints:
  http:
    address: ":80"
    http:
      entryPoint:
        to: https
        scheme: https
  https:
    address: ":443"

api:
  dashboard: true
  insecure: true

providers:
  file:
    directory: "/etc/traefik/services"
    watch: true
  docker:
    endpoint: "unix://var/run/docker.sock"

log:
  level: DEBUG
  filepath: /etc/traefik/traefik.log

accessLog:
  filePath: /etc/traefik/access.log
  bufferingSize: 100

certificateResolvers:
  le:
    acme:
      email: my.email@corp.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: http
      caServer: http://acme-v02.api.letsencrypt.org/directory
serverTransport:
  insecureSkipVerify: true

#myService.yaml

http:
  routers:
    myService:
      entryPoints:
      - https
      - http
      
      service: myService
      rule: Host(`my.service.com`)

      tls:
        certResolver: le
        options:
        domains:
          - main: "my.service.com"

  services:
    myService:
      loadBalencer:
        servers:
        - url: "https://my.service.com"

  middlewares:
    nextcloud-redirect:
      permanent: true
      regex: "https://(.*)/.well-known/(card|cal)dav"
      replacement: "https://${1}/remote.php/dav/"
```

This service is a basic copy/paste of one that I use for another website that actually work. I use this middleware because my NC admin asked me to if you had to ask.
