### ISSUE TITLE
Conflict: traefik instances with ingressClass

### ISSUE THREAD

**Issue by paltryeffort** [traefik/traefik#7896]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

2 separate traefik instances and one ingress object using IngressClassName

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld
  namespace: test
  annotations:
#    kubernetes.io/ingress.class: traefik # can't set if ingressClassName is set
spec:
  ingressClassName: traefik-external
  rules:
  - host: test.mydomain.com
  # ...
```

```yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: "false"
  name: traefik-external
  spec:
    controller: traefik.io/ingress-controller
```
  
traefik-external cli parameters:
```
    --providers.kubernetesingress
    --providers.kubernetescrd.ingressclass=traefik-external
    --providers.kubernetesingress.ingressclass=traefik-external
```

**Result: This works fine at all times!**

Now I create **additionally** a new traefik instance "traefik-internal" which is exactly the same except for the ingressClass name:

```yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: "false"
  name: traefik-internal
  spec:
    controller: traefik.io/ingress-controller
```

traefik-internal cli parameters:
```
    --providers.kubernetesingress
    --providers.kubernetescrd.ingressclass=traefik-internal
    --providers.kubernetesingress.ingressclass=traefik-internal
```

### What did you expect to see?

My helloworld should be served by the `traefik-external` instance as before. The `traefik-internal` should not serve this ingress object.

### What did you see instead?

What I am seeing now is that randomly about every 5-15 seconds the http service `test-helloworld-80@kubernetes` and the corresponding http route appears and disappears again.
I can see this on both traefik dashboards, the traefik-external and the traefik-internal one.

### Output of `traefik version`: (_What version of Traefik are you using?_)

traefik 2.4.0

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

kubernetes 1.19

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

every 5-10 seconds:
```
level=debug msg="Configuration received from provider kubernetes: {\"http\":{\"routers\":{\"helloworld-test-test-mydomain-com\":{\"service\":\"test-helloworld-80\",\"rule\":\"Host(`test.mydomain.com`) \\u0026\\u0026 PathPrefix(`/`)\"}},\"services\":{\"test-helloworld-80\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://10.42.0.43:80\"}],\"passHostHeader\":true}}}},\"tcp\":{},\"tls\":{}}" providerName=kubernetes
level=debug msg="Creating middleware" entryPointName=web routerName=helloworld-test-test-mydomain-com@kubernetes serviceName=test-helloworld-80 middlewareName=pipelining middlewareType=Pipelining
level=debug msg="Creating load-balancer" routerName=helloworld-test-test-mydomain-com@kubernetes serviceName=test-helloworld-80 entryPointName=web
level=debug msg="Creating server 0 http://10.42.0.43:80" entryPointName=web routerName=helloworld-test-test-mydomain-com@kubernetes serviceName=test-helloworld-80 serverName=0
level=debug msg="Added outgoing tracing middleware test-helloworld-80" routerName=helloworld-test-test-mydomain-com@kubernetes middlewareName=tracing middlewareType=TracingForwarder entryPointName=web
```

**Comment by rtribotte** [comment]
Hello @paltryeffort,

Thanks for your interest in Traefik!

From what I understand, I can see two things that are going wrong.

First, Traefik currently not support selecting ingressClasses by their name, using the ingressClass provider configuration property. This only has an effect to select ingresses that have the annotation `kubernetes.io/ingress.class` to the same value.

Second, only since the v2.4.2, Traefik is supporting multiple ingress classes. This is why you are experiencing routes appearing and disappearing randomly with the 2.4.0. Traefik fetches alternatively one ingress class or another.

Regarding the first point, using the provider configuration ingressClass property to match ingressClasses in the cluster by their name, would be an enhancement and I'll label it accordingly.

(The subject of using multiple Traefik ingress controller in one cluster has already been discussed in #7611 and the related PR #7624, thus we declined to do it through customizing the controller attribute)

**Comment by paltryeffort** [comment]
I upgraded to traefik 2.4.2 and did some more tests:

my helloworld ingress object:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld
  namespace: test
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  #ingressClassName: traefik-external # NOT SET
```

Result as expected: ingress is only served by the traefik-external instance and not by the traefik-internal.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld
  namespace: test
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  #ingressClassName: traefik-external # NOT SET
```

Result as expected: ingress is not served by any traefik instance because one is listening to "traefik-external" and the other to "traefik-internal"

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld
  namespace: test
  annotations:
    # kubernetes.io/ingress.class: traefik # NOT SET
spec:
  ingressClassName: traefik-external
```

Result NOT as expected: The ingress is served by BOTH traefik instances although it should be only traefik-external

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld
  namespace: test
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  ingressClassName: traefik-external
```

Result NOT as expected: The ingress is served by BOTH traefik instances although it should be only traefik-external

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld
  namespace: test
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik-external
```

Result NOT as expected: The ingress is served by BOTH traefik instances. It should either be served by NONE or by "traefik-external"


```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld
  namespace: test
  annotations:
    kubernetes.io/ingress.class: blahhh123
spec:
  ingressClassName: traefik-external
```

Result NOT as expected: The ingress is served by BOTH traefik instances. It should either be served by NONE or by "traefik-external"

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld
  namespace: test
  annotations:
    kubernetes.io/ingress.class: blahhh123
spec:
  ingressClassName: traefik-internal
```

Result NOT as expected: The ingress is served by BOTH traefik instances. It should either be served by NONE or by "traefik-internal"

So apparently as soon as I set `ingressClassName` to either `traefik-internal` or `traefik-external` the ingress is always served by both traefik instances. The `kubernetes.io/ingress.class: blahhh123` is ignored which is fine by me.

I could not find a combination where `ingressClassName` is set and only served by one traefik instance.
