### ISSUE TITLE
HTTP entrypoint - middleware defined in file not found

### ISSUE THREAD

**Issue by R-VdP** [traefik/traefik#7902]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

See config below, this config worked fine without any errors in v2.3, since v2.4, the log shows errors about a middleware not being found.
Everything seems to be working as it should and the middleware seems to be functionally, but the error messages are still not ideal.

### What did you expect to see?

A clean log without errors.

### What did you see instead?

```
Feb 16 15:49:33 XXXX docker[5023]: time="2021-02-16T15:49:33+01:00" level=error msg="middleware \"default-middleware@file\" does not exist" routerName=web-to-websecure@internal entryPointName=web
Feb 16 15:49:33 XXXX docker[5023]: time="2021-02-16T15:49:33+01:00" level=error msg="middleware \"default-middleware@file\" does not exist" routerName=acme-http@internal entryPointName=web
Feb 16 15:49:33 XXXX 6f64799bf0d0[998]: time="2021-02-16T15:49:33+01:00" level=error msg="middleware \"default-middleware@file\" does not exist" routerName=web-to-websecure@internal entryPointName=web
Feb 16 15:49:33 XXXX 6f64799bf0d0[998]: time="2021-02-16T15:49:33+01:00" level=error msg="middleware \"default-middleware@file\" does not exist" routerName=acme-http@internal entryPointName=web
Feb 16 15:49:34 XXXX docker[5023]: time="2021-02-16T15:49:34+01:00" level=debug msg="Creating middleware" middlewareType=Chain entryPointName=web routerName=web-to-websecure@internal middlewareName=default-middleware@file
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
$ docker run --rm -it traefik:2.4 version
Version:      2.4.2
Codename:     livarot
Go version:   go1.15.7
Built:        2021-02-02T17:20:41Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Command line args: `--configfile=/traefik-static.yml`

#### Static config:
```yml
{
  "accessLog": {
    "fields": {
      "headers": {
        "names": {
          "User-Agent": "keep"
        }
      },
      "names": {
        "StartUTC": "drop"
      }
    }
  },
  "api": {
    "dashboard": true
  },
  "certificatesresolvers": {
    "letsencrypt": {
      "acme": {
        "email": "XXXX",
        "httpChallenge": {
          "entryPoint": "web"
        },
        "keyType": "EC256",
        "preferredChain": "DST Root CA X3",
        "storage": "/letsencrypt/acme.json"
      }
    },
    "letsencrypt_dns": {
      "acme": {
        "dnsChallenge": {
          "provider": "route53",
          "resolvers": [
            "9.9.9.9:53",
            "8.8.8.8:53",
            "1.1.1.1:53"
          ]
        },
        "email": "XXXX",
        "keyType": "EC256",
        "preferredChain": "DST Root CA X3",
        "storage": "/letsencrypt/acme.json"
      }
    }
  },
  "entryPoints": {
    "traefik": {
      "address": ":8080",
      "http": {
        "middlewares": [
          "dashboard-middleware@file"
        ]
      }
    },
    "web": {
      "address": ":80",
      "http": {
        "middlewares": [
          "default-middleware@file"
        ],
        "redirections": {
          "entryPoint": {
            "scheme": "https",
            "to": "websecure"
          }
        }
      }
    },
    "websecure": {
      "address": ":443",
      "http": {
        "middlewares": [
          "default-ssl-middleware@file"
        ],
        "tls": {
          "certResolver": "letsencrypt"
        }
      }
    }
  },
  "global": {
    "sendAnonymousUsage": true
  },
  "log": {
    "level": "TRACE"
  },
  "pilot": {
    "token": "XXXX"
  },
"ping": {},
  "providers": {
    "docker": {
      "exposedbydefault": false,
      "network": "web",
      "swarmMode": false
    },
    "file": {
      "directory": "/traefik-dynamic.conf.d",
      "watch": true
    }
  }
}
```

#### Dynamic config:
```yml
{
  "http": {
    "middlewares": {
      "autodetect-middleware": {
        "contentType": {
          "autoDetect": false
        }
      },
      "compress-middleware": {
        "compress": {}
      },
      "dashboard-middleware": {
        "chain": {
          "middlewares": [
            "security-headers@file",
            "compress-middleware@file"
          ]
        }
      },
      "default-middleware": {
        "chain": {
          "middlewares": [
            "security-headers@file",
            "compress-middleware@file",
            "autodetect-middleware@file"
          ]
        }
      },
      "default-ssl-middleware": {
        "chain": {
          "middlewares": [
            "hsts-headers@file",
            "default-middleware@file"
          ]
        }
      },
      "hsts-headers": {
        "headers": {
          "sslRedirect": true,
          "stsIncludeSubdomains": true,
          "stsPreload": true,
          "stsSeconds": "31536000"
        }
      },
      "security-headers": {
        "headers": {
          "browserXssFilter": true,
          "customFrameOptionsValue": "SAMEORIGIN",
          "customResponseHeaders": {
            "Expect-CT": "max-age=86400, enforce",
            "Server": "",
            "X-AspNet-Version": "",
            "X-Generator": "",
            "X-Powered-By": ""
          },
          "referrerPolicy": "no-referrer, strict-origin-when-cross-origin"
        }
      }
    },
    "routers": {
      "dashboard": {
        "entryPoints": [
          "traefik"
        ],
        "rule": "PathPrefix(`/api`) || PathPrefix(`/dashboard`)",
        "service": "api@internal"
      }
    }
  },
  "tls": {
    "options": {
      "default": {
        "cipherSuites": [
          "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
          "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
          "TLS_AES_256_GCM_SHA384",
          "TLS_CHACHA20_POLY1305_SHA256"
        ],
        "minVersion": "VersionTLS12",
        "sniStrict": true
      }
    }
  }
}
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

https://gist.github.com/R-VdP/f6ba42dc40dcc876ed5a9e7a545f082f
