### ISSUE TITLE
Certificate fallback priority

### ISSUE THREAD

**Issue by tripleawwy** [traefik/traefik#7908]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Naming a certificate resolver in dynamic configuration doesn't result in a HTTP-01 challenge if a self signed wildcard certificate for that corresponding domain already exists in the provided TLS store.
The certifcate resolver is passed from entrypoints in the static configuration see below. (This does apply when explicitly setting the TLS section and certificate resolver too)

This is related to https://github.com/traefik/traefik/issues/7493 except for the fact that it is a self signed certificate and a private ACME CA is involved.

I would really appreciate if there's a way to solve this. Additionally I assume @ldez will be the one answering this report and thus I'd like to contribute and not only request changes but I will need a little bit of help where to begin. Thanks in advance!

### What did you expect to see?

The expectation was for Traefik to request a new certificate by using the named certificate resolver.
- Documentation says so https://doc.traefik.io/traefik/https/acme/#fallback

### What did you see instead?

Traefik uses the provided wildcard certificate provided by the TLS store.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.2
Codename:     livarot
Go version:   go1.15.7
Built:        2021-02-02T17:20:41Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# static configuration

[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[serversTransport]
  insecureSkipVerify = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"
    [entryPoints.web-secure.http.tls]
      certResolver = "mycompany-ca"

[providers]
  providersThrottleDuration = "2s"
  [providers.docker]
    watch = true
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false
    swarmMode = true
    swarmModeRefreshSeconds = 42
  [providers.file]
    directory = "/etc/traefik/conf.d/"
    watch = true

[api]
  insecure = true

[accessLog]
  filePath = "/path/to/access.log"
  bufferingSize = 100

[metrics]
  [metrics.prometheus]
    buckets = [0.1, 0.3, 1.2, 5.0]
    entryPoint = "traefik"

[certificatesResolvers.mycompany-ca.acme]
  email = "traefik@mycompany.org"
  storage = "acme.json"
  caServer = "https://acme.my-company.org/acme/acme/directory"
  [certificatesResolvers.mycompany-ca.acme.httpChallenge]
    entryPoint = "web"

[log]
  level = "INFO"

```

```toml
# SSL/TLS certificates

[tls]

  [tls.options]
    [tls.options.default]
      minVersion = "VersionTLS12"

  [[tls.certificates]]
    certFile = "/etc/ssl/private/wildcard.mycompany.org-cert.pem"
    keyFile = "/etc/ssl/private/wildcard.mycompany.org-private-key.pem"

```

```toml
# dynamic configuration
[http.routers.sw1]
  rule = "Host(`sw1.mycompany.org`)"
  service = "iot-158"
  entrypoints = ["web-secure"]

```
![image](https://user-images.githubusercontent.com/43851917/108354779-3c20ca80-71ea-11eb-8d80-485d61a97637.png)
