### ISSUE TITLE
traefik does not respect kubernetes.io/tls-acme

### ISSUE THREAD

**Issue by jetersen** [traefik/traefik#7912]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

currently slowly switching from nginx to traefik.
I plan to use both ingressroute and k8s provider.

We use both external-dns and cert-manager, where cert-manager is configured for ingressShim.

So all our current ingress we have `kubernetes.io/tls-acme: "true"` which should be equivalent to `traefik.ingress.kubernetes.io/router.tls: "true"`
This seems like a oversight in the user experience for the k8s provider.

### What did you expect to see?

Expected traefik to respect `kubernetes.io/tls-acme`

### What did you see instead?

Had to add `traefik.ingress.kubernetes.io/router.tls: "true"` which feels redundant.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik v2.4.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

using [traefik helm chart](https://github.com/traefik/traefik-helm-chart)

```yaml
traefik:
  globalArguments:
    - "--global.checknewversion"
  logs:
    general:
      format: json
  additionalArguments:
    - "--providers.kubernetescrd.ingressclass=traefik-internal"
    - "--providers.kubernetesingress.ingressclass=traefik-internal"
  deployment:
    replicas: 2
  ingressRoute:
    dashboard:
      annotations:
        kubernetes.io/ingress.class: traefik-internal
  providers:
    providersThrottleDuration: 2s
    kubernetesIngress:
      publishedService:
        enabled: true
  service:
    spec:
      externalTrafficPolicy: Local
    annotations:
      external-dns.alpha.kubernetes.io/hostname: traefik-internal.company.io
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
  tlsOptions:
    default:
      minVersion: VersionTLS12
      cipherSuites:
      - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
      - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
      - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
      - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
      - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
```

ingress

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-k8s
  labels:
    app.kubernetes.io/name: example-k8s
    app.kubernetes.io/instance: example
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    kubernetes.io/ingress.class: "traefik-internal"
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - "example.company.io"
      secretName: example.company.io-tls
  rules:
    - host: "example.company.io"
      http:
        paths:
          - path: /
            backend:
              serviceName: example-k8s
              servicePort: http
```
