### ISSUE TITLE
ForwardAuth - trustForwardHeader not forwarding headers correctly

### ISSUE THREAD

**Issue by FlomoN** [traefik/traefik#7923]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I was trying to use Traefik's ForwardAuth Middleware with a self-written OAuth-proxy. When trying to **get a correct URL for redirecting back to the service** after authentication with the OAuth provider I am using the **`X-Forwarded-Host` header**. For the middleware, I set the `trustForwardHeader` to true. However, the headers that reach my auth service, do not contain the Host of the service I am trying to protect for `X-Forwarded-Host` but the host of the actual auth service itself.

Something that does solve the problem is to start Traefik with `--entryPoints.websecure.forwardedHeaders.insecure` (https://stackoverflow.com/questions/63683668/traefik-forward-auth-request-uri) but I'm unsure of the security implications of this and as far as I understand the documentation, setting `trustForwardHeader` should do the same thing (but only when the auth-middleware is used).

### What did you expect to see?

`X-Forwarded-Host` should contain the host of the service that is protected by the middleware.

### What did you see instead?

`X-Forwarded-Host` contains the host of the auth service itself when reaching the auth service.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.6
Codename:     picodon
Go version:   go1.15.6
Built:        2020-12-17T16:34:27Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I am using Traefik version 2.3.6 in my K3s Cluster as an ingress controller deployed via the Helm chart.

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  repo: https://helm.traefik.io/traefik
  chart: traefik
  version: 9.12.3
  bootstrap: true
  targetNamespace: traefik
  valuesContent: |-

    additionalArguments:
      - "--certificatesresolvers.default.acme.email=xxxxxxxxxxxxxxxxxx"
      - "--certificatesresolvers.default.acme.storage=/data/acme.json"
      - "--certificatesresolvers.default.acme.tlschallenge=true"
      - "--log.level=INFO"
      - "--serverstransport.insecureskipverify"
      - "--accesslog=true"
      - "--accesslog.filepath=/data/access.log"
      
    pilot:
      enabled: true
      token: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

    ports:
      websecure:
        tls:
          enabled: true
          certResolver: default

    persistence:
      enabled: true
      path: /data

    # We will apply our own ingress rule for the dashboard in the next step
    ingressRoute:
      dashboard:
        enabled: false
```

Also this is the kubernetes manifest for the middleware:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: auth
  name: fwauth
spec:
  forwardAuth:
    address: https://auth.redacted.de/auth
    trustForwardHeader: true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Not the output of Traefik, but the headers that reach the auth service under `/auth`
```
{
  host: 'auth.redacted.de',
  'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7',
  'sec-ch-ua': '"Chromium";v="88", "Google Chrome";v="88", ";Not A Brand";v="99"',
  'sec-ch-ua-mobile': '?0',
  'sec-fetch-dest': 'document',
  'sec-fetch-mode': 'navigate',
  'sec-fetch-site': 'none',
  'sec-fetch-user': '?1',
  'upgrade-insecure-requests': '1',
  'x-forwarded-for': '10.42.0.1',
  'x-forwarded-host': 'auth.redacted.de',
  'x-forwarded-port': '443',
  'x-forwarded-proto': 'https',
  'x-forwarded-server': 'traefik-5c86bf4c8f-jtmsn',
  'x-real-ip': '10.42.0.1'
}
```
