### ISSUE TITLE
RedirectScheme incorrectly redirects when specifying port 443

### ISSUE THREAD

**Issue by santachago** [traefik/traefik#7927]
Hi, 
we detected an incorrect behavior when using RedirectScheme and sending a request where you specify the default port for https (443).
Ex: https://domain.com:443/test

### What did you do?
Implemented a middleware using RedirectScheme to redirect from HTTP to HTTPS using:
```
  [http.middlewares.http2https.redirectScheme]
    scheme = "https"
    permanent = true
```
Then made a request to the url: https://domain.com:443/test

### What did you expect to see?
i expected to receive a response code 200

### What did you see instead?
Received a 308 response code with a redirect to: 
https://domain.com/test (without port especification)

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
/ # traefik version
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

### More info
I traced this to be related to the way the new url is built and compared on pkg/middlewares/redirect/redirect.go:63
The newURL variable does not contain the port when the port is the default for the protocol, for example https and 443. And the oldURL variable does contain the port as it was originally specified on the request by the client (which is completely valid)

**Comment by jakubhajek** [comment]
Hi! 
Thank you for spending your time and reporting the issue.

I've built a test environment running on Kubernetes and I tried to reproduce your issue.  Please have a look at details concerning my environment.

1. Traefik deployed through Helm chart, version: `2.2.1`
2. The following additional values arguments have been added:
```yaml
additionalArguments:
  - "--certificatesresolvers.le.acme.storage=/data/acme.json"
  - "--certificatesresolvers.le.acme.tlschallenge"
  - "--certificatesresolvers.le.acme.email=foo@you.com"
  - "--log.level=DEBUG"
```
3. Here is the config file I've deployed. 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: whoami
  name: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  strategy: {}
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - image: containous/whoami
          name: whoami
          ports:
            - containerPort: 80
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-svc
  namespace: default
  labels:
    app: whoami
spec:
  type: ClusterIP
  selector:
    app: whoami
  ports:
    - port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ingress-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`whoami.example.com`) && PathPrefix(`/test`)
      services:
        - kind: Service
          name: whoami-svc
          passHostHeader: true
          port: 80
  tls:
    certResolver: le
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ingress-http
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`whoami.example.com) && PathPrefix(`/test`)
      middlewares:
        - name: http2https
      services:
        - kind: Service
          name: whoami-svc
          passHostHeader: true
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: http2https
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
```
4. The first request has been sent without a port in the URL. The expected result is a permanent redirect from `http` to `https`

`➜ curl http://whoami.example.com/test/  -Iv`
```
* Connected to whoami.example.com (<IP>) port 80 (#0)
> HEAD /test/ HTTP/1.1
> Host: whoami.example.com
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 308 Permanent Redirect
HTTP/1.1 308 Permanent Redirect
< Location: https://whoami.example.com/test/
Location: https://whoami.example.com/test/
< Date: Thu, 25 Feb 2021 21:12:49 GMT
Date: Thu, 25 Feb 2021 21:12:49 GMT
```
The redirection from `http` to `https` works as expected.

5. The second request has been sent with the 443 port in the URL.

`➜ curl https://whoami.example.com:443/test/  -Iv`
```
*   Trying <cut>..
* TCP_NODELAY set
* Connected to whoami.example.com (<IP>) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=whoami.example.cm
*  start date: Feb 25 11:47:57 2021 GMT
*  expire date: May 26 11:47:57 2021 GMT
*  subjectAltName: host "whoami.example.com" matched cert's "whoami.example.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fc488809200)
> HEAD /test/ HTTP/2
> Host: whoami.example.com
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 200
HTTP/2 200
< content-type: text/plain; charset=utf-8
content-type: text/plain; charset=utf-8
< date: Thu, 25 Feb 2021 21:15:42 GMT
date: Thu, 25 Feb 2021 21:15:42 GMT
< content-length: 425
```

The request has been finished with a `200` HTTP response, which is the expected result. There is no redirection that you experienced, the issue was not replicated. 

If you are still experiencing that issue, can you please share your Traefik configuration?

Thank you,
