### ISSUE TITLE
Docker container "504 Gateway Timeout" after adding a file provider to Traefik config (v2)

### ISSUE THREAD

**Issue by waterdrop01** [traefik/traefik#7929]
### Do you want to request a *feature* or report a *bug*?

<!--
DO NOT FILE ISSUES FOR GENERAL SUPPORT QUESTIONS.

The issue tracker is for reporting bugs and feature requests only.
For end-user related support questions, please refer to one of the following:

- the Traefik community forum: https://community.containo.us/

-->

Bug

<!--

The configurations between 1.X and 2.X are NOT compatible.
Please have a look here https://doc.traefik.io/traefik/getting-started/configuration-overview/.

-->

### What did you do?
I added a **file provider**, in addition to the previously existing docker provider.
<!--

HOW TO WRITE A GOOD BUG REPORT?

- Respect the issue template as much as possible.
- The title should be short and descriptive.
- Explain the conditions which led you to report this issue: the context.
- The context should lead to something, an idea or a problem that you’re facing.
- Remain clear and concise.
- Format your messages to help the reader focus on what matters and understand the structure of your message, use Markdown syntax https://help.github.com/articles/github-flavored-markdown

-->
### What did you expect to see?

I expect to see my nextcloud docker container **NOT** returning "504 Gateway Timeout" because **it is working perfectly fine when I disable the file provider**

### What did you see instead?

I see "504 Gateway Timeout" in the Traefik logs

### Output of `traefik version`: (_What version of Traefik are you using?_)

<!--
`latest` is not considered as a valid version.

For the Traefik Docker image:
    docker run [IMAGE] version
    ex: docker run traefik version

-->

```
2.4.5
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I have two providers, here is my static config file (as cli args in traefik docker-compose.yml):
```yml
version: '3'                                                                                                                                    
                                                                                                                                                
services:                                                                                                                                       
  traefik:                                                                                                                                      
    image: traefik:2.4.5                                                                                                                        
    container_name: traefik
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/config"
      - "--providers.file.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=me@email.com"
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - web
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./acme.json:/acme.json
      - ./config:/etc/traefik/config

networks:
  web:
    external: true
```
And here is my dynamic config, for the **file provider**:
```
http:
  routers:
    LocalhostRouter:
      entryPoints:
        - "websecure"
      rule: "Host(`localhost.example.com`)"
      service: "LocalhostService"
      tls:
        certResolver: "myresolver"
  services:
    LocalhostService:
      loadBalancer:
        servers:
          - url: http://172.18.0.1:9191
```
And here is the dynamic config (of nextcloud) for the **docker provider**:
```yml
version: '3'                                                                                                                                    
                                                                                                                                                
services:                                                                                                                                       
  nextcloud-db:                                                                                                                                 
    image: mariadb                                                                                                                              
    restart: always                                                                                                                             
    networks:                                                                                                                                   
      - nextcloud                                                                                                                               
    volumes:                                                                                                                                    
      - nextcloud-db:/var/lib/mysql                                                                                                             
    env_file:                                                                                                                                   
      - db.env                                                                                                                                  
                                                                                                                                                
  nextcloud:                                                                                                                                    
    hostname: cloud.example.com                                                                                                              
    build: .           
   restart: always
    networks:
      - web
      - nextcloud
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=
      - NEXTCLOUD_ADMIN_USER=
      - NEXTCLOUD_ADMIN_PASSWORD=
      - NEXTCLOUD_UPDATE=
      - NEXTCLOUD_HOSTNAME=
    env_file:
      - db.env
    depends_on:
      - nextcloud-db
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.example.com`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"

volumes:
  nextcloud-db:
  nextcloud:

networks:
  nextcloud:
    external: true
  web:
    external: true
```
<!--
Add more configuration information here.
-->


### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2021-02-24T16:15:48Z" level=debug msg="'504 Gateway Timeout' caused by: dial tcp 172.19.0.3:80: i/o timeout"                              
time="2021-02-24T16:15:48Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\$
Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/index.php/apps/photos/service-worker.js\",\"RawPath\":\"\",\"ForceQuery\"$
false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\"$
[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-US,en;q=0.5\"],\"Cache-Control\":[\"max-age=0\"],\"Cookie\":[\"$
_Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; nc_username=vict$
r; nc_token=W6WvfSGLLksSrblL8Nv49XI9TeDvzBud; nc_session_id=8765e4da304e650239090396f1ddadc4; ocnjzfeml3yy=8765e4da304e650239090396f1ddadc4; oc$
sessionPassphrase=9JDwB2Qu5Uh4sOzZSrv5s%2FNZAA1pZ2aWznMYfstI8CDnAfpavo0opy1e8$
RE6RTu\"],\"Service-Worker\":[\"script\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/201001$
1 Firefox/85.0\"],\"X-Forwarded-Host\":[\"cloud.example.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-$
erver\":[\"1f6184cf1a26\"],\"X-Real-Ip\":[\"90.65.98.90\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"cloud.example.com\",\"For$
\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"90.55.98.91:56770\",\"RequestURI\":\"/index.php/apps/photos/$
ervice-worker.js\",\"TLS\":null}"    
```
