### ISSUE TITLE
ACME: preferredChain option seems to be ignored

### ISSUE THREAD

**Issue by phlmn** [traefik/traefik#7936]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I've set the `preferredChain` option for a certificate resolver to "ISRG Root X1".

### What did you expect to see?

Traefik serving a certificate with the ISRG Root X1 chain.

### What did you see instead?

Traefik serving a certificate with the default chain (DST Root X3).

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.5
Codename:     livarot
Go version:   go1.15.8
Built:        2021-02-18T17:21:25Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

traefik/traefik.yml
```yaml
providers:
    docker:
        exposedByDefault: false
        network: traefik

certificatesResolvers:
    le_isrg:
        acme:
            email: admin@example.com
            caServer: https://acme-v02.api.letsencrypt.org/directory
            storage: /etc/traefik/acme/acme.json
            preferredChain: ISRG Root X1
            tlsChallenge: {}

api:
    insecure: true

entryPoints:
    web:
        address: ":80"

    websecure:
        address: ":443"

log:
    level: DEBUG
```

docker-compose.yml
```yaml
version: "3.8"

networks:
    traefik:
        external: true

services:
    traefik:
        image: traefik:2.4
        volumes:
            - "./traefik/traefik.yml:/etc/traefik/traefik.yml"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./traefik/acme:/etc/traefik/acme"
        ports:
            - "443:443"
            - "80:80"
        networks:
            - traefik
    app:
        image: foobar/app:latest
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.backend.rule=Host(`app.example.com`)"
            - "traefik.http.services.backend.loadbalancer.server.port=8000"
            - "traefik.http.middlewares.limit-request.buffering.maxRequestBodyBytes=2000000"
            - "traefik.http.routers.backend.middlewares=limit-request"
            - "traefik.http.routers.backend.tls.certResolver=le_isrg"
        networks:
            - traefik

    api:
        image: foobar/api:latest
        labels:
            - "traefik.enable=true"
            - "traefik.tcp.routers.api.rule=HostSNI(`api.example.com`)"
            - "traefik.tcp.services.api.loadbalancer.server.port=1234"
            - "traefik.tcp.services.api.loadbalancer.terminationDelay=10000"
            - "traefik.tcp.routers.api.tls.certResolver=le_isrg"
        networks:
            - traefik
```

I've also tried to reproduce this with lego v4.2.0 since this seems to be used to request the certificate. With the lego CLI it is working as expected.

```sh
 docker run -it -v $(pwd)/lego:/.lego -p 80:80 -p 443:443 goacme/lego:v4.2.0 \
    --email=admin@example.com \
    --server=https://acme-v02.api.letsencrypt.org/directory \
    --tls --domains=app.example.com run \
    --preferred-chain="ISRG Root X1"
```
