### ISSUE TITLE
Add the ability to globally configure Security Headers for all frontend traefik

### ISSUE THREAD

**Issue by 31RFCAPELI** [traefik/traefik#7949]
### Do you want to request a *feature* or report a *bug*?

bug

Bug

### What did you do?

I want to be able to configure Security Headers once for all frontend and not in each fontend configuration.

### What did you expect to see?

I want to be able to configure Security Headers once for all frontend and not in each fontend configuration.

### What did you see instead?

In my docker-compose I have 10 frontends. I have to add in labels section of each services configuration these properties :

```
- traefik.frontend.headers.STSPreload=true
- traefik.frontend.headers.STSSeconds=31536000
- traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security:15552000
```

It’s a lot to set and to maintain.

I add in labels in file docker-compose in traefik and restart my stack traefik, this configure don't result effect for all my services.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.26
Codename:     maroilles
Go version:   go1.14.6
Built:        2020-07-28_03:45:27PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

docker-compose.yml

```
version: "3"
services:
  traefik:
    image: traefik:1.7
    command:
      - "--web"
      - "--api"
      - "--entrypoints=Name:internal_http Address::80 Redirect.EntryPoint:internal_https"
      - "--entrypoints=Name:internal_https Address::443 TLS:/x/x/x/x.crt,/x/x/ssl/x.key TLS.MinVersion:VersionTLS12 TLS.CipherSuites:x
      - "--entrypoints=Name:external_https Address::10443 TLS:/x/traefik/x/x.crt,/x/x/ssl/x.key TLS.MinVersion:x"
      - "--defaultentrypoints=internal_http,internal_https"
      - "--insecureSkipVerify=true"
    volumes:
      - /x/x:/etc/traefik/ssl
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "dockerwall.outbound=x.x.x.x"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.STSSeconds=31536000"        
      - "traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security:15552000"        
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 10080
        published: 10080
        mode: host
      - target: 10443
        published: 10443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    deploy:
      mode: global
      labels:
        - traefik.frontend.headers.frameDeny=true
        - traefik.frontend.headers.SSLRedirect=true
        - traefik.frontend.headers.STSPreload=true
        - traefik.frontend.headers.STSSeconds=31536000
        - traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security:15552000          
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: x
      restart_policy:
        condition: on-failure

networks:
  default:
    external:
      name: x
```
I have to add in labels section of each services configuration these properties and doing test: 

```
curl -s -D- https://x.x.com.br | grep -i Strict return strict-transport-security: 15552000
```
When I test a frontend where don´t was not added the labels services configure properties not return  strict-transport-security.
