### ISSUE TITLE
Traefik triggers letsencrypt rate limit

### ISSUE THREAD

**Issue by Dandrum** [traefik/traefik#7952]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?

I checked for `storage` path and docker bind mound to be correct but when i restart traefik or a container hooked up to it. It tries to renew or create a new certificate. But in my acme.json are all currently valid certificates save and valid until October 2021.

I deployed a container about 5-7 times to test some seo stuff and meta tags for preview rendering in facebook or slack.
Everythings works so far but in the traefik logs i saw an error of lets encrypt that i triggered the rate limit for that domain, but traefik uses the already valid cert ( i think its a fallback if other fails ). So i only recognized it because of the traefik logs.

### Output of `traefik version`: (_What version of Traefik are you using?_)
traefik:v2.4

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

docker-compose.yml: 

```yml
version: "3.3"

services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    volumes:
      - ./letsencrypt:/letsencrypt
      - ./traefik.yml:/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: "true"
      traefik.docker.network: proxy

      # Global redirection: http to https
      traefik.http.routers.http-catchall.rule: HostRegexp(`{host:(www\.)?.+}`)
      traefik.http.routers.http-catchall.entrypoints: http
      traefik.http.routers.http-catchall.middlewares: wwwtohttps

      # Global redirection: https (www.) to https
      traefik.http.routers.wwwsecure-catchall.rule: HostRegexp(`{host:(www\.).+}`)
      traefik.http.routers.wwwsecure-catchall.entrypoints: https
      traefik.http.routers.wwwsecure-catchall.tls: "true"
      traefik.http.routers.wwwsecure-catchall.middlewares: wwwtohttps

      # middleware: http(s)://(www.) to  https://
      traefik.http.middlewares.wwwtohttps.redirectregex.regex: ^https?://(?:www\.)?(.+)
      traefik.http.middlewares.wwwtohttps.redirectregex.replacement: https://$${1}
      traefik.http.middlewares.wwwtohttps.redirectregex.permanent: "true"

      # middleware: default security headers for all
      traefik.http.middlewares.securityHeader.headers.customFrameOptionsValue: "SAMEORIGIN"
      traefik.http.middlewares.securityHeader.headers.sslRedirect: "true"
      traefik.http.middlewares.securityHeader.headers.contentTypeNosniff: "true"
      traefik.http.middlewares.securityHeader.headers.browserXssFilter: "true"
      traefik.http.middlewares.securityHeader.headers.forceSTSHeader: "true"
      traefik.http.middlewares.securityHeader.headers.stsIncludeSubdomains: "true"
      traefik.http.middlewares.securityHeader.headers.stsSeconds: "31536000"

      # tls min version
      traefik.tls.options.default.minVersion: "VersionTLS12"

      # traefik Dashboard
      traefik.http.routers.traefik.entrypoints: "http,https"
      traefik.http.routers.traefik.middlewares: securityHeader
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.rule: Host(`###########`)
      traefik.http.routers.traefik.tls.certresolver: secure
      traefik.http.routers.traefik.tls.domains[0].main: "#########"
      traefik.http.routers.traefik.tls.options: default

networks:
  proxy:
    external: true
```

traefik.yml:

```yml
global:
  checkNewVersion: true

api:
  dashboard: true
#  debug: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
    forwardedHeaders:
      insecure: true

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  secure:
    acme:
      tlsChallenge: {}
      httpChallenge:
        # used during the challenge
        entryPoint: http
      email: ###########
      storage: /letsencrypt/acme_prod.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
#      storage: /letsencrypt/acme_stagging.json
#      caServer: https://acme-staging-v02.api.letsencrypt.org/directory #staging
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```log
 time="2021-03-03T19:54:19Z" level=error msg="Unable to obtain ACME certificate for domains \"*****.de\" : unable to generate a certificate for the domains [******]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/" providerName=secure.acme
```

**Comment by ldez** [comment]
Hello,

> But in my acme.json are all currently valid certificates save and valid until October 2021.

The LE certificates are valid for 3 months only, it seems impossible to get a valid certificate until October 2021.

The current max validity date is 90 days after now: June 01, 2021

https://letsencrypt.org/docs/faq/#what-is-the-lifetime-for-let-s-encrypt-certificates-for-how-long-are-they-valid

Check your `acme.json` file, be sure that your certificates are not from the LE staging.

**Comment by Dandrum** [comment]
Hi ok thats strange but is it possible that if the cert is from last year that the expire date is more than 3 month ?

and my acme.json is correct so far

```json
  "secure": {
    "Account": {
      "Email": "############",
      "Registration": {
        "body": {
          "status": "valid",
          "contact": [
            "#################"
          ]
        },
        "uri": "https://acme-v02.api.letsencrypt.org/acme/acct/79107981"
      },
      "PrivateKey": "############",
      "KeyType": "4096"
    },
```

**Comment by Dandrum** [comment]
i Noticed that traefik tries to check my certificates on every container i startup and join into my network and to traefik.
Everytime it did a ACME Lookup so if i test some projekts and need to restart my container it always triggers the acme even if there is already a cert in my acme.json and its valid and not expired.
```json
{"level":"error","msg":"Unable to obtain ACME certificate for domains \"xxxxxxxx\" : unable to generate a certificate for the domains [xxxxxxxe]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/","providerName":"secure.acme","time":"2021-03-27T20:52:52Z"}
{"level":"error","msg":"Unable to obtain ACME certificate for domains \xxxxxx" : unable to generate a certificate for the domains [xxxxxxxx]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/","providerName":"secure.acme","time":"2021-03-27T20:52:52Z"}
```
My Traefik .yml
```yml
global:
  checkNewVersion: true

api:
  dashboard: true
#  debug: true

log:
  filePath: /logs/traefik.log
  format: json
  level: ERROR

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
    forwardedHeaders:
      insecure: true

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  secure:
    acme:
      tlsChallenge: {}
      httpChallenge:
        # used during the challenge
        entryPoint: http
      email: schmidt@mediendesign-schmidt.de
      storage: letsencrypt/acme_prod.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      #storage: letsencrypt/acme_stagging.json
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory #staging
```
my Docker-Compose
```yml
version: "3.3"

services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    volumes:
      - ./letsencrypt:/letsencrypt
      - ./logs:/logs
      - ./traefik.yml:/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: "true"
      traefik.docker.network: proxy

      # Global redirection: http to https
      traefik.http.routers.http-catchall.rule: HostRegexp(`{host:(www\.)?.+}`)
      traefik.http.routers.http-catchall.entrypoints: http
      traefik.http.routers.http-catchall.middlewares: wwwtohttps

      # Global redirection: https (www.) to https
      traefik.http.routers.wwwsecure-catchall.rule: HostRegexp(`{host:(www\.).+}`)
      traefik.http.routers.wwwsecure-catchall.entrypoints: https
      traefik.http.routers.wwwsecure-catchall.tls: "true"
      traefik.http.routers.wwwsecure-catchall.middlewares: wwwtohttps

      # middleware: http(s)://(www.) to  https://
      traefik.http.middlewares.wwwtohttps.redirectregex.regex: ^https?://(?:www\.)?(.+)
      traefik.http.middlewares.wwwtohttps.redirectregex.replacement: https://$${1}
      traefik.http.middlewares.wwwtohttps.redirectregex.permanent: "true"

      # middleware: default security headers for all
      traefik.http.middlewares.securityHeader.headers.customFrameOptionsValue: "SAMEORIGIN"
      traefik.http.middlewares.securityHeader.headers.sslRedirect: "true"
      traefik.http.middlewares.securityHeader.headers.contentTypeNosniff: "true"
      traefik.http.middlewares.securityHeader.headers.browserXssFilter: "true"
      traefik.http.middlewares.securityHeader.headers.forceSTSHeader: "true"
      traefik.http.middlewares.securityHeader.headers.stsIncludeSubdomains: "true"
      traefik.http.middlewares.securityHeader.headers.stsSeconds: "31536000"

      # tls min version
      traefik.tls.options.default.minVersion: "VersionTLS12"

      # traefik Dashboard
      traefik.http.routers.traefik.entrypoints: "http,https"
      traefik.http.routers.traefik.middlewares: securityHeader
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.rule: Host(`xxxxxxxxx`)
      traefik.http.routers.traefik.tls.certresolver: secure
      traefik.http.routers.traefik.tls.domains[0].main: "xxxxxxxxxx"
      traefik.http.routers.traefik.tls.options: default

networks:
  proxy:
    external: true
```
My Projekt docker-compose
```yml
version: "3.7"
services:
  frontend:
    image: registry.gitlab.com/xxxxxxxxx
    restart: always
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.projektname.rule=Host(`xxxxxxx`)"
      - "traefik.http.routers.projektname.entrypoints=https"
      - "traefik.http.services.projektname.loadbalancer.server.port=3000"
      - "traefik.http.routers.projektname.middlewares=securityHeader"
      - "traefik.http.routers.projektname.tls.certresolver=secure"
      - "traefik.http.routers.projektname.tls.domains[0].main=xxxxxxx"

networks:
  proxy:
    external: true

```
