### ISSUE TITLE
ACME crashes and all ingress return Bad Gateway

### ISSUE THREAD

**Issue by pkarrot** [traefik/traefik#7955]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?

After upgrade 2.4.0 -> 2.4.6 of traefik from docker (tag 2.4.6) started to get crashes in logs:

```
time="2021-03-04T17:01:50Z" level=error msg="Unable to obtain ACME certificate for domains \"some.com\": unable to generate a certificate for the domains [some.com]: error: one or more domains h
ad a problem:\n[some.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Connection reset by peer\n" providerName=letsencrypt.acme rule="Host(`some.com`) && PathPrefix(`/register`)
" routerName=myservice-d283b86321f534a8-default-some-com-register@kubernetes
time="2021-03-04T17:01:53Z" level=error msg="Error in Go routine: close of closed channel"
time="2021-03-04T17:01:53Z" level=error msg="Stack: goroutine 16 [running]:\nruntime/debug.Stack(0xc00016a000, 0x366c429, 0x17)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine(0x302cde0, 0x3ac5b30)\n\t/go/src/github.com/traefik/traefik/pkg/safe/routine.go:66 +0xb4\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1.1(0x37853c0)\n\t/go/src/github.com/traefik/traefik/pkg/safe/routine.go:56 +0x57\npanic(0x302cde0, 0x3ac5b30)\n\t/usr/local/go/src/runtime/panic.go:969 +0x1b9\ngithub.com/traefik/traefik/v2/pkg/provider/acme.(*ChallengeTLSALPN).ListenConfiguration(0xc000398e40, 0xc000b47ef0, 0xc00166b850, 0xc00166b860, 0xc000b47f20)\n\t/go/src/github.com/traefik/traefik/pkg/provider/acme/challenge_tls.go:125 +0x16a\ngithub.com/traefik/traefik/v2/pkg/server.(*ConfigurationWatcher).loadMessage(0xc0000adcc0, 0x3647be9, 0xc, 0xc00203c740)\n\t/go/src/github.com/traefik/traefik/pkg/server/configurationwatcher.go:155 +0x20e\ngithub.com/traefik/traefik/v2/pkg/server.(*ConfigurationWatcher).listenConfigurations(0xc0000adcc0, 0x3bb8480, 0xc0000b4500)\n\t/go/src/github.com/traefik/traefik/pkg/server/configurationwatcher.go:135 +0x51\ngithub.com/traefik/traefik/v2/pkg/safe.(*Pool).GoCtx.func1()\n\t/go/src/github.com/traefik/traefik/pkg/safe/routine.go:36 +0x64\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1(0x37853c0, 0xc0002dc7e0)\n\t/go/src/github.com/traefik/traefik/pkg/safe/routine.go:59 +0x4f\ncreated by github.com/traefik/traefik/v2/pkg/safe.GoWithRecover\n\t/go/src/github.com/traefik/traefik/pkg/safe/routine.go:53 +0x49\n"
```

```
Error in Go routine: close of closed channel
Stack: goroutine 16 [running]:
runtime/debug.Stack(0xc00016a000, 0x366c429, 0x17)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine(0x302cde0, 0x3ac5b30)
	/go/src/github.com/traefik/traefik/pkg/safe/routine.go:66 +0xb4
github.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1.1(0x37853c0)
	/go/src/github.com/traefik/traefik/pkg/safe/routine.go:56 +0x57
panic(0x302cde0, 0x3ac5b30)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/traefik/traefik/v2/pkg/provider/acme.(*ChallengeTLSALPN).ListenConfiguration(0xc000398e40, 0xc000b47ef0, 0xc00166b850, 0xc00166b860, 0xc000b47f20)
	/go/src/github.com/traefik/traefik/pkg/provider/acme/challenge_tls.go:125 +0x16a
github.com/traefik/traefik/v2/pkg/server.(*ConfigurationWatcher).loadMessage(0xc0000adcc0, 0x3647be9, 0xc, 0xc00203c740)
	/go/src/github.com/traefik/traefik/pkg/server/configurationwatcher.go:155 +0x20e
github.com/traefik/traefik/v2/pkg/server.(*ConfigurationWatcher).listenConfigurations(0xc0000adcc0, 0x3bb8480, 0xc0000b4500)
	/go/src/github.com/traefik/traefik/pkg/server/configurationwatcher.go:135 +0x51
github.com/traefik/traefik/v2/pkg/safe.(*Pool).GoCtx.func1()
	/go/src/github.com/traefik/traefik/pkg/safe/routine.go:36 +0x64
github.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1(0x37853c0, 0xc0002dc7e0)
	/go/src/github.com/traefik/traefik/pkg/safe/routine.go:59 +0x4f
created by github.com/traefik/traefik/v2/pkg/safe.GoWithRecover
	/go/src/github.com/traefik/traefik/pkg/safe/routine.go:53 +0x49
```

and similar but different one:
```
time="2021-03-04T17:01:53Z" level=error msg="Unable to obtain ACME certificate for domains \"some.at\": unable to generate a certificate for the domains [some.at]: error: one or more domains had a problem:\n[some.at] [some.at] acme: error presenting token: timeout 2021-03-04 17:01:49.800276595 +0000 UTC m=+80.007289179\n" providerName=letsencrypt.acme routerName=ui-ba7a27397b0c2bd0-default-some-at@kubernetes rule="Host(`some.at`)"
time="2021-03-04T17:01:53Z" level=error msg="Error in Go routine: close of closed channel"
time="2021-03-04T17:01:53Z" level=error msg="Stack: goroutine 15242 [running]:\nruntime/debug.Stack(0xc00016a000, 0x366c429, 0x17)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine(0x302cde0, 0x3ac5b30)\n\t/go/src/github.com/traefik/traefik/pkg/safe/routine.go:66 +0xb4\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1.1(0x37853c0)\n\t/go/src/github.com/traefik/traefik/pkg/safe/routine.go:56 +0x57\npanic(0x302cde0, 0x3ac5b30)\n\t/usr/local/go/src/runtime/panic.go:969 +0x1b9\ngithub.com/traefik/traefik/v2/pkg/provider/acme.(*ChallengeTLSALPN).Present(0xc000398e40, 0xc00161c0e0, 0x18, 0xc003b54090, 0x2b, 0xc000f08180, 0x57, 0xc00225a0a0, 0x3)\n\t/go/src/github.com/traefik/traefik/pkg/provider/acme/challenge_tls.go:70 +0x5ee\ngithub.com/go-acme/lego/v4/challenge/tlsalpn01.(*Challenge).Solve(0xc00089bce0, 0xc00225a0a3, 0x7, 0x0, 0xed7dc43f6, 0x0, 0xc00225a0a0, 0x3, 0xc00161c0e0, 0x18, ...)\n\t/go/pkg/mod/github.com/go-acme/lego/v4@v4.2.0/challenge/tlsalpn01/tls_alpn_challenge.go:58 +0x333\ngithub.com/go-acme/lego/v4/challenge/resolver.parallelSolve(0xc000d62030, 0x1, 0x1, 0xc0007f6150)\n\t/go/pkg/mod/github.com/go-acme/lego/v4@v4.2.0/challenge/resolver/prober.go:158 +0x3f5\ngithub.com/go-acme/lego/v4/challenge/resolver.(*Prober).Solve(0xc0005fe1c8, 0xc0003da070, 0x1, 0x1, 0x14, 0xc000b3da00)\n\t/go/pkg/mod/github.com/go-acme/lego/v4@v4.2.0/challenge/resolver/prober.go:84 +0x396\ngithub.com/go-acme/lego/v4/certificate.(*Certifier).Obtain(0xc0003995c0, 0xc0021ddaf0, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/pkg/mod/github.com/go-acme/lego/v4@v4.2.0/certificate/certificates.go:124 +0x347\ngithub.com/traefik/traefik/v2/pkg/provider/acme.(*Provider).resolveCertificate(0xc0001b0600, 0x3bb8540, 0xc00294b590, 0xc001de1f61, 0x18, 0x0, 0x0, 0x0, 0x3636db5, 0x7, ...)\n\t/go/src/github.com/traefik/traefik/pkg/provider/acme/provider.go:483 +0x45a\ngithub.com/traefik/traefik/v2/pkg/provider/acme.(*Provider).resolveDomains.func1()\n\t/go/src/github.com/traefik/traefik/pkg/provider/acme/provider.go:365 +0xc5\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1(0x37853c0, 0xc000e92e70)\n\t/go/src/github.com/traefik/traefik/pkg/safe/routine.go:59 +0x4f\ncreated by github.com/traefik/traefik/v2/pkg/safe.GoWithRecover\n\t/go/src/github.com/traefik/traefik/pkg/safe/routine.go:53 +0x49\n"
```

```
Error in Go routine: close of closed channel
Stack: goroutine 15242 [running]:
runtime/debug.Stack(0xc00016a000, 0x366c429, 0x17)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine(0x302cde0, 0x3ac5b30)
	/go/src/github.com/traefik/traefik/pkg/safe/routine.go:66 +0xb4
github.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1.1(0x37853c0)
	/go/src/github.com/traefik/traefik/pkg/safe/routine.go:56 +0x57
panic(0x302cde0, 0x3ac5b30)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/traefik/traefik/v2/pkg/provider/acme.(*ChallengeTLSALPN).Present(0xc000398e40, 0xc00161c0e0, 0x18, 0xc003b54090, 0x2b, 0xc000f08180, 0x57, 0xc00225a0a0, 0x3)
	/go/src/github.com/traefik/traefik/pkg/provider/acme/challenge_tls.go:70 +0x5ee
github.com/go-acme/lego/v4/challenge/tlsalpn01.(*Challenge).Solve(0xc00089bce0, 0xc00225a0a3, 0x7, 0x0, 0xed7dc43f6, 0x0, 0xc00225a0a0, 0x3, 0xc00161c0e0, 0x18, ...)
	/go/pkg/mod/github.com/go-acme/lego/v4@v4.2.0/challenge/tlsalpn01/tls_alpn_challenge.go:58 +0x333
github.com/go-acme/lego/v4/challenge/resolver.parallelSolve(0xc000d62030, 0x1, 0x1, 0xc0007f6150)
	/go/pkg/mod/github.com/go-acme/lego/v4@v4.2.0/challenge/resolver/prober.go:158 +0x3f5
github.com/go-acme/lego/v4/challenge/resolver.(*Prober).Solve(0xc0005fe1c8, 0xc0003da070, 0x1, 0x1, 0x14, 0xc000b3da00)
	/go/pkg/mod/github.com/go-acme/lego/v4@v4.2.0/challenge/resolver/prober.go:84 +0x396
github.com/go-acme/lego/v4/certificate.(*Certifier).Obtain(0xc0003995c0, 0xc0021ddaf0, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/go-acme/lego/v4@v4.2.0/certificate/certificates.go:124 +0x347
github.com/traefik/traefik/v2/pkg/provider/acme.(*Provider).resolveCertificate(0xc0001b0600, 0x3bb8540, 0xc00294b590, 0xc001de1f61, 0x18, 0x0, 0x0, 0x0, 0x3636db5, 0x7, ...)
	/go/src/github.com/traefik/traefik/pkg/provider/acme/provider.go:483 +0x45a
github.com/traefik/traefik/v2/pkg/provider/acme.(*Provider).resolveDomains.func1()
	/go/src/github.com/traefik/traefik/pkg/provider/acme/provider.go:365 +0xc5
github.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1(0x37853c0, 0xc000e92e70)
	/go/src/github.com/traefik/traefik/pkg/safe/routine.go:59 +0x4f
created by github.com/traefik/traefik/v2/pkg/safe.GoWithRecover
	/go/src/github.com/traefik/traefik/pkg/safe/routine.go:53 +0x49
```

### What did you expect to see?

works as usual

### What did you see instead?

traefik stopped responding with Bad Gateway to all domains/ingresses.
So I believe this is 2 bugs actually:
- acme crashes
- traefik survives crash, but stops responding

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
log:
  level: INFO

entryPoints:
  web:
    address: "0.0.0.0:80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: "0.0.0.0:443"
    http:
      tls:
        certResolver: letsencrypt
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
  metrics:
    address: ":9090"

certificatesResolvers:
  letsencrypt:
    acme:
      email: my@email.com
      storage: /storage/acme.json
      tlsChallenge: {}

providers:
  kubernetesIngress: {}
  file:
    filename: "/config/dynamic.yaml"

api: {}

ping:
  entryPoint: metrics

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.2
      - 0.4
      - 7
    entryPoint: metrics

tracing:
  serviceName: traefik
  zipkin:
    httpEndpoint: http://zipkin-proxy.monitoring.svc.cluster.local:9411/api/v2/spans
```

dynamic.yaml:
```yaml
tls:
  options:
    tlsDefault:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305

http:
  routers:
    api:
      rule: Host(`traefik.myhost`)
      entrypoints:
        - websecure
      service: api@internal
      middlewares:
        - MonitoringAuth
      tls:
        certResolver: letsencrypt

  middlewares:
    Compress:
      compress: {}
```
