### ISSUE TITLE
Custom ConsulCatalog prefix disables h2c service scheme

### ISSUE THREAD

**Issue by parkedwards** [traefik/traefik#7976]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Hello!  We're setting up Traefik + Consulcatalog configuration provider.  Our destination services are both HTTP/1 and gRPC (h2c)

From the [docs](https://doc.traefik.io/traefik/user-guides/grpc/#conclusion), we've labeled our gRPC services to use the h2c protocol, and confirmed that this works:

```
# on the service Consul tags (which get converted to Traefik labels)
traefik.http.services.grpc-service.loadbalancer.server.scheme=h2c
```

However, we recently decided to use a custom [Consulcatalog prefix](https://doc.traefik.io/traefik/providers/consul-catalog/#prefix) so make some of our service label tags more generic.  We configured this using the `TRAEFIK_PROVIDERS_CONSULCATALOG_PREFIX` environment variable

```
TRAEFIK_PROVIDERS_CONSULCATALOG_PREFIX=myprefix
```

### What did you expect to see?

We expected the provider configuration hydrate service configurations as normal, even with the addition of a custom Consulcatalog prefix (absent this parameter, I think the prefix defaults to "traefik."

### What did you see instead?
The gRPC service, which has the h2c label, ceased to be configured as an h2c protocol service.  Requests forwarded to this service based on the router rules got downgraded to HTTP/1, making the request fail.

From:
![image](https://user-images.githubusercontent.com/19556538/110672194-359bc800-8184-11eb-8d46-30b377b59ef9.png)

To:
![image](https://user-images.githubusercontent.com/19556538/110672202-3896b880-8184-11eb-83b5-301d653db5fb.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
/ # traefik version
Version:      2.4.7
Codename:     livarot
Go version:   go1.16
Built:        2021-03-08T17:18:28Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
To make it easy to reproduce, I put together a docker-compose, which should spin up all the parameters and dependencies.  However, I'm seeing this in the deployed instances as well:

```
version: '3'

services:

  # TRAEFIK SERVICE
  traefik:
    image: traefik:v2.4
    environment:
      - TRAEFIK_ENTRYPOINTS_MAIN=true
      - TRAEFIK_ENTRYPOINTS_MAIN_ADDRESS=:7000
      - TRAEFIK_ENTRYPOINTS_MAIN_HTTP_MIDDLEWARES=retry-on-service-unavailable@file
      - TRAEFIK_LOG_LEVEL=debug
      - TRAEFIK_PING=true
      - TRAEFIK_PING_ENTRYPOINT=main
      - TRAEFIK_API=true
      - TRAEFIK_API_INSECURE=true

      # ------ COMMENT / UNCOMMENT TO REPRODUCE ISSUE -------
      # - TRAEFIK_PROVIDERS_CONSULCATALOG_PREFIX=myprefix
      # -----------------------------------------------------

      - TRAEFIK_PROVIDERS_CONSULCATALOG_ENDPOINT_ADDRESS=http://consul:8500
      - TRAEFIK_PROVIDERS_CONSULCATALOG_REFRESHINTERVAL=5s
      - TRAEFIK_PROVIDERS_CONSULCATALOG_CONSTRAINTS=Tag(`api_endpoint`) || Tag(`api_grpc_endpoint`) || Tag(`internal_api_endpoint`)
      - TRAEFIK_PROVIDERS_CONSULCATALOG_DEFAULTRULE=Host(`{{ normalize .Name}}`) || Headers(`Host`, `{{ normalize .Name}}`) {{- if (index .Labels "traefik.pathprefix") -}}|| PathPrefix(`/{{- index .Labels "traefik.pathprefix" -}}`){{- end -}}
      - TRAEFIK_PROVIDERS_FILE_DIRECTORY=/tmp/traefik
      - TRAEFIK_PROVIDERS_FILE_WATCH=true
    depends_on:
      - consul
    links:
      - consul
    ports:
      - 7000:7000
      - 8080:8080
    volumes:
      - ./config/traefik/local:/tmp/traefik
    build:
      context: .

  # TEST SERVICES
  grpc-service:
    image: moul/grpcbin
    environment:
      - SERVICE_9000_NAME=grpc-service
      - SERVICE_9000_TAGS=prometheus_metrics,api_grpc_endpoint,type=grpc,traefik.http.services.grpc-service.loadbalancer.server.scheme=h2c
    ports:
      - 9000:9000

  # CONSUL CONTAINERS
  registrator:
    image: gliderlabs/registrator:master
    network_mode: host
    depends_on:
      - consul
    command: "-internal consul://localhost:8500"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  consul:
    image: "consul:${CONSUL_VERSION:-1.8.3}"
    working_dir: /
    command:
      - "agent"
      - "-dev"
      - "--client=0.0.0.0"
      - "--node=consul-dev"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    restart: always

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
