### ISSUE TITLE
accessLog won't filter

### ISSUE THREAD

**Issue by edipdincer** [traefik/traefik#7982]
### Do you want to request a *feature* or report a *bug*?
Report a bug

Bug

### What did you do?
Configured traefik.yml to log access for 401, 403 and 404 errors.

### What did you expect to see?
AccessLog which shows only 401, 403 and 404 errors.

### What did you see instead?
All status codes logged.

### Output of `traefik version`: (_What version of Traefik are you using?_)

Version:      2.4.7
Codename:     livarot
Go version:   go1.16
Built:        2021-03-08T17:18:28Z
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
# (paste your configuration here)
accessLog:
  filePath: "log/access.log"
  filters:    
    statusCodes:
      - "401"
      - "403"
      - "404"
    retryAttempts: true
    minDuration: "10ms"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
....
192.168.1.85 - - [12/Mar/2021:16:48:22 +0000] "REPORT /remote.php/dav/calendars/contact_birthdays/ HTTP/2.0" 207 239 "-" "-" 103 "nextcloud@docker" "http://172.19.0.2:80" 821ms
192.168.1.85 - - [12/Mar/2021:16:48:22 +0000] "REPORT /remote.php/dav/calendars/wwwofficeholidayscom/ HTTP/2.0" 207 239 "-" "-" 104 "nextcloud@docker" "http://172.19.0.2:80" 1190ms
192.168.1.85 - - [12/Mar/2021:16:48:36 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 105 "-" "-" 0ms
192.168.1.85 - - [12/Mar/2021:16:48:45 +0000] "GET /styles.1c995213107c2ec08ac5.css HTTP/2.0" 200 171424 "-" "-" 107 "pigallery2@docker" "http://172.19.0.7:80" 119ms
192.168.1.85 - - [12/Mar/2021:16:48:45 +0000] "GET /polyfills-es2015.c5a8f019fc426e2772a2.js HTTP/2.0" 200 98936 "-" "-" 110 "pigallery2@docker" "http://172.19.0.7:80" 157ms
192.168.1.85 - - [12/Mar/2021:16:48:45 +0000] "GET /main-es2015.ed20722ba3d7347a1343.js HTTP/2.0" 200 1840304 "-" "-" 111 "pigallery2@docker" "http://172.19.0.7:80" 771ms
192.168.1.85 - - [12/Mar/2021:16:48:47 +0000] "GET /api/user/me HTTP/2.0" 401 130 "-" "-" 112 "pigallery2@docker" "http://172.19.0.7:80" 13ms
192.168.1.85 - - [12/Mar/2021:16:48:47 +0000] "GET /open-iconic.woff HTTP/2.0" 200 14984 "-" "-" 113 "pigallery2@docker" "http://172.19.0.7:80" 12ms
....
```
As this is my first issue, I hope I didn't do something wrong :)

**Comment by tomMoulard** [comment]
Hello @edipdincer,

Thanks for your interest in Traefik!

Can you please provide more configuration (static configuration, docker configuration) in order to reproduce your bug ?

Can you also provide more logs of Traefik by [setting the log level to DEBUG](https://doc.traefik.io/traefik/observability/logs/#level) ?

**Comment by edipdincer** [comment]
Hi, thanks for the response. Here are my conf files and debug log:

traefik.yml
```
api:
  dashboard: true
  insecure: true

log:
  filePath: "log/traefik.log"
  level: WARN

accessLog:
  filePath: "log/access.log"
  filters:    
    statusCodes:
      - "401"
      - "403"
      - "404"
    retryAttempts: true
    minDuration: "10ms"

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  http:
    acme:
      email: email@email.com
      storage: acme.json
      httpChallenge:
        entryPoint: http
```

docker-compose.yml
```
version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 80:80
      - 443:443
      - 9006:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./acme.json:/acme.json
      - ./log:/log
    environment:
      - "DYNU_API_KEY=DYNU_API_KEY"
      - "TZ=TZ/TZ"

networks:
  proxy:
    external: true
```
Debug Log: https://pastebin.com/raw/6EZvpAEU
