### ISSUE TITLE
traefik.ingress.kubernetes.io/service.serversscheme: http <- not working

### ISSUE THREAD

**Issue by KlavsKlavsen** [traefik/traefik#7987]
traefik 2.4.5

The following ingress makes traefik assume backend is https.. I tried telling it, its http (using serverscheme annotation), but it still sees it as https :(

I gleaned that was the right setting from here. https://github.com/traefik/traefik/blob/29908098e47f0458b5d5f50a59fe3583f63874c7/pkg/provider/kubernetes/ingress/kubernetes.go

ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/service.serversscheme: http
  labels:
    app: opendistro-es
    argocd.argoproj.io/instance: opendistro-es
    chart: opendistro-es-1.13.1
    heritage: Helm
    release: opendistro-es
  name: opendistro-es-kibana-ing
  namespace: graylog
spec:
  rules:
    - host: kibana.ops.example.io
      http:
        paths:
          - backend:
              serviceName: opendistro-es-kibana-svc
              servicePort: 443
            path: /
  tls:
    - hosts:
        - kibana.ops.example.io
      secretName: opendistro-es-tls
```
