### ISSUE TITLE
File name based route rule 

### ISSUE THREAD

**Issue by TheYkk** [traefik/traefik#7988]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I want to able to define file name based route rule.
File rule with regex like this :

```yaml
routes:
  - match: Host(`site.com`) && File(`*.png`)
    kind: Rule
    services:
      - name: fullName
        port: svcPort 
  - match: Host(`site.com`)
    kind: Rule
    services:
      - name: fullName
        port: svcPort 
    middlewares:
      - name: auth
```
