### ISSUE TITLE
traefik fails to use ingress/service with multiple ports defined - "Cannot create service: cannot define a port"

### ISSUE THREAD

**Issue by martinvizvary** [traefik/traefik#7991]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Deployment of the Traefik 2.4.7 via official helm chart using kubernetes ingress provider. Traefik has issues using a kubernetes ingress/service with multiple ports defined. It fails to search through all subsets in endpoint object.

### What did you expect to see?

Discover ingress for a `foo` app add a new route and service for `foo`. 

### What did you see instead?

Error:
```
time="2021-03-19T07:37:23Z" level=error msg="Cannot create service: cannot define a port" providerName=kubernetes serviceName=proxy-service ingress=proxy-service servicePort=http namespace=mvtest
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.7
Codename:     livarot
Go version:   go1.16
Built:        2021-03-08T17:18:28Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
    spec:
      containers:
      - args:
        - --entryPoints.traefik.address=:9000/tcp
        - --entryPoints.web.address=:8000/tcp
        - --entryPoints.websecure.address=:8443/tcp
        - --entrypoints.websecure.http.tls=true
        - --entrypoints.websecure.http.middlewares=traefik2-global-custom-header@kubernetescrd
        - --api.dashboard=true
        - --ping=true
        - --providers.kubernetescrd
        - --log.level=DEBUG
        - --providers.kubernetesingress
        - --accesslog=false
        - --accesslog.fields.defaultmode=keep
        - --accesslog.fields.headers.defaultmode=drop
        - --providers.kubernetesingress.ingressclass=traefik2
        image: traefik:2.4.7
```

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":[""],"port":443,"protocol":"HTTPS","serviceName":"mvtest:foo","ingressName":"mvtest:foo","hostname":"foo.example.com","path":"/","allNodes":false}]'
    kubernetes.io/ingress.class: traefik2
  labels:
    app: foo
  name: foo
  namespace: mvtest
spec:
  rules:
  - host: foo.example.com
    http:
      paths:
      - backend:
          serviceName: foo
          servicePort: http
        path: /
  tls:
  - hosts:
    - foo.example.com
    secretName: mvtest-cert
```

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: foo
  name: foo
  namespace: mvtest
  spec:
    clusterIP: {}
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http-api
  - name: http-admin
    port: 8079
    protocol: TCP
    targetPort: http-admin
  selector:
    app: foo
  sessionAffinity: None
  type: ClusterIP
```

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: foo
  name: foo
  namespace: mvtest
subsets:
- addresses:
  - ip: ...
    nodeName: ...
  ports:
  - name: http-admin
    port: 8079
    protocol: TCP
- addresses:
  - ip: ...
    nodeName: ...
    targetRef:
  ports:
  - name: http
    port: 8080
    protocol: TCP
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2021-03-19T07:37:23Z" level=error msg="Cannot create service: cannot define a port" providerName=kubernetes serviceName=proxy-service ingress=proxy-service servicePort=http namespace=mvtest
```

**Comment by martinvizvary** [comment]
I belive the bug is here https://github.com/traefik/traefik/blob/29908098e47f0458b5d5f50a59fe3583f63874c7/pkg/provider/kubernetes/ingress/kubernetes.go#L551 - the error is returned when no port is found in the first subset from inner for loop. The outer loop is not fully iterated

**Comment by SantoDE** [comment]
Hey hey,

thanks for your interest.

From what I can spot from your config, couldn't that potentially be a missconfig? You target the service port `http` which has a target port of `http-api` which is not present on your endpoint?

**Comment by martinvizvary** [comment]
> Hey hey,
> 
> thanks for your interest.
> 
> From what I can spot from your config, couldn't that potentially be a missconfig? You target the service port `http` which has a target port of `http-api` which is not present on your endpoint?

Hello,

my bad I didn't add the deployment configuration here. The container port is named `http-api`. So the configuration of the service is ok. 

```yaml
    ...
     containers:
        ...
        name: foo
        ports:
        - containerPort: 8080
          name: http-api
          protocol: TCP
        - containerPort: 8079
          name: http-admin
          protocol: TCP
   ...
```

**Comment by jakubhajek** [comment]
Hey @martinvizvary 

Thanks for using Traefik!

I am able to reproduce the issue only when I did a typo by purpose in a service definition in targetPort named ports.  

Then I got from Traefik on the ingress Foo. 

```
traefik-traefik-5b447d6b84-vrn8g traefik-traefik time="2021-03-22T12:31:21Z" level=error msg="Cannot create service: cannot define a port" namespace=default serviceName=foo servicePort=foo-port-1 providerName=kubernetes ingress=foo
```

Here is the configuration manifest I used:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik-lb
    traefik.ingress.kubernetes.io/router.entrypoints: web
  labels:
    app: foo
  name: foo
spec:
  rules:
    - host: foo.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: foo
              servicePort: foo-port-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: w1
  name: w1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: w1
  template:
    metadata:
      labels:
        app: w1
    spec:
      containers:
        - image: traefik/whoami:v1.6.1
          name: whoami
          ports:
            - containerPort: 80
              name: port-who
            - containerPort: 8080
              name: port-who-2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: foo
  name: foo
spec:
  type: ClusterIP
  ports:
    - name: foo-port-1
      port: 80
      protocol: TCP
      targetPort: port-who
    - name: foo-port-2
      port: 8080
      protocol: TCP
      targetPort: port-who-2
  selector:
    app: w1
```

Can you please send us the results of the `kubectl get endpoints`?
 
```
NAME         ENDPOINTS                         AGE
foo          172.17.0.12:8080,172.17.0.12:80   6s
```
I might be wrong but IMO it is a configuration issue.

**Comment by martinvizvary** [comment]
Hi @jakubhajek,

here is my `kubectl get endpoints`

```
(⎈ |fi2:mvtest) ~  k get endpoints foo
NAME            ENDPOINTS                                                   AGE
foo   100.101.223.6:8080,100.101.223.6:8079,100.101.223.6:24231   5m
```

and complete object

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2021-03-22T13:11:27Z"
  creationTimestamp: null
  labels:
    app: foo
  name: foo
subsets:
- addresses:
  - ip: 100.101.223.5
    nodeName: ip-10-207-11-146.eu-west-1.compute.internal
    targetRef:
      kind: Pod
      name: foo-6f85f877f9-fqfkv
      namespace: mvtest
  - ip: 100.101.223.6
    nodeName: ip-10-207-11-146.eu-west-1.compute.internal
    targetRef:
      kind: Pod
      name: foo-95bf7bbb9-6d6t6
      namespace: mvtest
  ports:
  - name: http-admin
    port: 8079
    protocol: TCP
  - name: fluentd-metrics
    port: 24231
    protocol: TCP
- addresses:
  - ip: 100.101.223.6
    nodeName: ip-10-207-11-146.eu-west-1.compute.internal
    targetRef:
      kind: Pod
      name: foo-95bf7bbb9-6d6t6
      namespace: mvtest
  ports:
  - name: http
    port: 8080
    protocol: TCP
```

There is one important thing to watch when you try to reproduce the bug. `Endpoints` are gerenated dynamically and the order is not guaranteed. So if k8s generates endpoints object, where your `foo-port-1` is on the first place, it will work. 

It should be straight forward to see from the fix I created here https://github.com/traefik/traefik/pull/7997 . Without the fix, the inner for loop returns error without iterating through all elements of the outer for loop.
