### ISSUE TITLE
Traefik CRD not up to date.

### ISSUE THREAD

**Issue by leier69** [traefik/traefik#7996]
Documentation specifies the following:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressroutes.traefik.containo.us

spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRoute
    plural: ingressroutes
    singular: ingressroute
  scope: Namespaced
  ```
  
  When it should be updated to:
  ```
  apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ingressroutes.traefik.containo.us

spec:
  group: traefik.containo.us
  versions:
    - name: v1
      served: true
      storage: true
      deprecated: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            host:
              type: string
            port:
              type: string
  names:
    kind: IngressRoute
    plural: ingressroutes
    singular: ingressroute
  scope: Namespaced
  ```
  
  To work on kubernetes 1.2 and up. Using "version" as appose to "versions" is depricated.
  I also noticed that traefik is spesifically looking for version "v1alpha1", which does not make sense for prod.
