### ISSUE TITLE
Traefik not working redirect and let's encrypt certs [question?]

### ISSUE THREAD

**Issue by stefanodecillis** [traefik/traefik#8002]
### I hope it's a question and not a bug

I'm trying to use Traefik:v2 in a docker-compose but it looks like that it doesn't work properly. 
I copied the `docker-compose.yaml` from [here](https://doc.traefik.io/traefik/v2.4/user-guides/docker-compose/acme-http/).  I will rewrite it here:

```
version: "3.3"

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=something@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.something.it`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
```

Running this docker-compose, I cannot reach whoami.something.it - I tried with different services and it doesn't work the redirect.
I also think it doesn't generate certs since I get

```
traefik    | time="2021-03-23T17:37:44Z" level=info msg=Register... providerName=myresolver.acme
traefik    | time="2021-03-23T17:37:44Z" level=debug msg="legolog: [INFO] acme: Registering account for something@gmail.com"
traefik    | time="2021-03-23T17:37:45Z" level=debug msg="Using HTTP Challenge provider." providerName=myresolver.acme
traefik    | time="2021-03-23T17:37:45Z" level=debug msg="legolog: [INFO] [whoami.something.it] acme: Obtaining bundled SAN certificate"
traefik    | time="2021-03-23T17:37:45Z" level=debug msg="legolog: [INFO] [whoami.something.it] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/14144671"
traefik    | time="2021-03-23T17:37:45Z" level=debug msg="legolog: [INFO] [whoami.something.it] acme: Could not find solver for: tls-alpn-01"
traefik    | time="2021-03-23T17:37:45Z" level=debug msg="legolog: [INFO] [whoami.something.it] acme: use http-01 solver"
traefik    | time="2021-03-23T17:37:45Z" level=debug msg="legolog: [INFO] [whoami.something.it] acme: Trying to solve HTTP-01"
traefik    | time="2021-03-23T17:37:51Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/14144671"
traefik    | time="2021-03-23T17:37:51Z" level=debug msg="legolog: [INFO] Unable to deactivate the authorization: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/14144671"
traefik    | time="2021-03-23T17:37:51Z" level=error msg="Unable to obtain ACME certificate for domains \"whoami.something.it\": unable to generate a certificate for the domains [whoami.something.it]: error: one or more domains had a problem:\n[whoami.something.it] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for whoami.something.it - check that a DNS record exists for this domain\n" providerName=myresolver.acme routerName=whoami@docker rule="Host(`whoami.something.it`)"
        traefik    | time="2021-03-23T17:38:45Z" level=debug msg="Serving default certificate for request: \"www.something.it\""
traefik    | time="2021-03-23T17:38:45Z" level=debug msg="http: TLS handshake error from 5.253.207.204:53652: remote error: tls: unknown certificate"
```

therefore it provides this default cert getting an error during the handshake

```
traefik    | time="2021-03-23T17:47:18Z" level=debug msg="Serving default certificate for request: \"www.something.it\""
traefik    | time="2021-03-23T17:47:18Z" level=debug msg="http: TLS handshake error from 5.253.207.204:21406: remote error: tls: unknown certificate"
```

Since it doesn't work both the redirect and the certs generation, is it a problem with my docker-compose? It also looks like that let's encrypt have one service down (but the generation of certs should be fine).
