### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by Darkbladecr** [traefik/traefik#8005]
Bug

unexpected status: 413 Request Entity Too Large
Despite adjusting the buffering and applying it to the service/router.

<img width="1364" alt="Screen Shot 2021-03-24 at 13 06 05" src="https://user-images.githubusercontent.com/4283896/112315305-eb493980-8ca1-11eb-8c33-f91cf8c131c4.png">

`docker-compose.yml`
```YAML
version: '3'

services:
  # Traefik Reverse-Proxy Service
  traefik:
    image: traefik:v2.4
    container_name: traefik-proxy
    restart: always
    labels:
      - traefik.enable=true
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik

  registry:
    image: registry:2
    container_name: docker-registry
    restart: always
    expose:
      - 5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./auth:/auth
      - ./data:/data
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.docker-registry.rule=Host(`docker.example.com`)
      - traefik.http.routers.docker-registry.tls=true
      - traefik.http.routers.docker-registry.middlewares=https_redirect@file, limit@docker
      - traefik.http.services.docker-registry-service.loadbalancer.server.port=5000
      # Sets the maximum request body to 10GB
      - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=10737418240
      - traefik.http.middlewares.limit.buffering.memRequestBodyBytes=200000000
      - traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=10737418240
      - traefik.http.middlewares.limit.buffering.memResponseBodyBytes=200000000

# Do not forget to 'docker network create traefik-proxy' before launch, and to add '--network traefik-proxy' to proxied containers.

networks:
  default:
    external:
      name: traefik-proxy
```

`traefik/traefik.toml`
```TOML
[entryPoints.web]
  address = ":80"

[entryPoints.websecure]
  address = ":443"

[providers.docker]
  useBindPortIP = true
  exposedByDefault = false
  network = "traefik-proxy"
[providers.file]
  filename = "/etc/traefik/custom.toml"
```

`traefik/custom.toml`
```TOML
[http.middlewares]
  [http.middlewares.https_redirect.redirectScheme]
    scheme = "https"
    permanent = true
```

### What did you do?

Tried to push a `docker buildx` multi-arch image to the docker-registry service, however I keep receiving:
`error: failed to solve: rpc error: code = Unknown desc = failed to copy: unexpected status: 413 Request Entity Too Large`

I have tried to increase the `maxRequestBodyBytes` but no change in the error.

### What did you expect to see?

I expect for traefik to be able to process a ~500MB docker image

### DEBUG Log output of `traefik:v2.4` is attached

[debug.log](https://github.com/traefik/traefik/files/6197555/debug.log)
