### ISSUE TITLE
Enhance rate limiting middleware to support multiple headers

### ISSUE THREAD

**Issue by yashmehrotra** [traefik/traefik#8006]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Currently, traefik's rate limiting middleware (https://doc.traefik.io/traefik/middlewares/ratelimit/) only supports a single header as key. We had a usecase for rate limiting on the basis of multiple headers.

It would look something like

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-ratelimit
spec:
  rateLimit:
    sourceCriterion:
      requestHeaderNames:
        - X-Token
        - X-Real-Ip
```

I would be more than happy to write the code and documentation for this if you are happy with this feature.

#### Why I did not write a plugin ?

I tried, but have faced numerous issues ranging from yaegi issues, panics without a stacktrace to traefik not being able to download a registered plugin (See #8004). The plugin I wrote was a bit more complex which used redis as a storage backend

I know that the plugin ecosystem is new and there will be a few hiccups till it gets mass adoption which is why I feel the existing ratelimiting middleware could be enhanced and would benefit other people too.

#### Proposed code changes

For rate limiting, instead of the single header being the key, the values of all the headers would be concatenated to form the key. As I said earlier, would be glad to write the code and documentation for this myself :)
