### ISSUE TITLE
Consul service error: field not found, node: server

### ISSUE THREAD

**Issue by marcaurele** [traefik/traefik#8013]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Deploying a container using Nomad + Consul which has multiple services/ports to configure from traefik (1 http, 1 https) going to 2 different ports on the container, using the standard service tags to provide the configuration.

### What did you expect to see?

I expected to see both services listed on the dashboard, on on the http entrypoint and one on the https entrypoint.

### What did you see instead?

I only saw one service binding on the http, and could not see the https one. Both services seems correctly registered in Consul (see API output).

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
accesslog:
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep
      names:
        Authorization: drop
        Cookie: redact
        User-Agent: redact
  format: json
api:
  dashboard: true
certificatesResolvers:
  main:
    acme:
      dnsChallenge:
        provider: redacted
      email: redacted
      storage: /etc/traefik/acme/acme.json
  staging:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: redacted
      email: redacted
      storage: /etc/traefik/acme/acme-staging.json
entryPoints:
  dnstcp:
    address: 192.168.78.31:53/tcp
  dnsudp:
    address: 192.168.78.31:53/udp
  http:
    address: :80
  https:
    address: :443
global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  filePath: /var/log/traefik.log
  format: json
  level: ERROR
metrics:
  prometheus:
    manualRouting: true
pilot:
  dashboard: false
ping:
  manualRouting: true
providers:
  consulCatalog:
    endpoint:
      address: 127.0.0.1:8500
      scheme: http
    exposedByDefault: false
  file:
    directory: /etc/traefik/config.d
    watch: true
```

Consul output of the "unifi" service API endpoint (`/v1/catalog/service/unifi`):
```json
[
  {
    "ID": "03663bd9-e660-8a15-fdb1-45b625a411e3",
    "Node": "dk2",
    "Address": "X.X.X.X",
    "Datacenter": "dc1",
    "TaggedAddresses": {
      "lan": "X.X.X.X",
      "lan_ipv4": "X.X.X.X",
      "wan": "X.X.X.X",
      "wan_ipv4": "X.X.X.X"
    },
    "NodeMeta": {
      "consul-network-segment": ""
    },
    "ServiceKind": "",
    "ServiceID": "_nomad-task-ad54cdb4-11cd-4325-3f8a-9048529692ee-group-unifi-unifi-http",
    "ServiceName": "unifi",
    "ServiceTags": [
      "traefik.enable=true",
      "traefik.http.routers.unifi.entrypoints=http",
      "traefik.http.routers.unifi.rule=Host(`unifi`) || Host(`unifi.example.com`)"
    ],
    "ServiceAddress": "X.X.X.X",
    "ServiceTaggedAddresses": {
      "lan_ipv4": {
        "Address": "X.X.X.X",
        "Port": 28040
      },
      "wan_ipv4": {
        "Address": "X.X.X.X",
        "Port": 28040
      }
    },
    "ServiceWeights": {
      "Passing": 1,
      "Warning": 1
    },
    "ServiceMeta": {
      "external-source": "nomad"
    },
    "ServicePort": 28040,
    "ServiceEnableTagOverride": false,
    "ServiceProxy": {
      "MeshGateway": {},
      "Expose": {}
    },
    "ServiceConnect": {},
    "CreateIndex": 140706,
    "ModifyIndex": 140706
  }
]
```

Consul output of the "unifi-secure" service API endpoint (`/v1/catalog/service/unifi-secure`):

```json
[
  {
    "ID": "03663bd9-e660-8a15-fdb1-45b625a411e3",
    "Node": "dk2",
    "Address": "X.X.X.X",
    "Datacenter": "dc1",
    "TaggedAddresses": {
      "lan": "X.X.X.X",
      "lan_ipv4": "X.X.X.X",
      "wan": "X.X.X.X",
      "wan_ipv4": "X.X.X.X"
    },
    "NodeMeta": {
      "consul-network-segment": ""
    },
    "ServiceKind": "",
    "ServiceID": "_nomad-task-ad54cdb4-11cd-4325-3f8a-9048529692ee-group-unifi-unifi-secure-https",
    "ServiceName": "unifi-secure",
    "ServiceTags": [
      "traefik.enable=true",
      "traefik.http.routers.unifi-secure.entrypoints=https",
      "traefik.http.routers.unifi-secure.rule=Host(`unifi`) || Host(`unifi.example.com`)",
      "traefik.http.routers.unifi-secure.tls=true",
      "traefik.http.services.unifi-secure.server.scheme=https"
    ],
    "ServiceAddress": "X.X.X.X",
    "ServiceTaggedAddresses": {
      "lan_ipv4": {
        "Address": "X.X.X.X",
        "Port": 30853
      },
      "wan_ipv4": {
        "Address": "X.X.X.X",
        "Port": 30853
      }
    },
    "ServiceWeights": {
      "Passing": 1,
      "Warning": 1
    },
    "ServiceMeta": {
      "external-source": "nomad"
    },
    "ServicePort": 30853,
    "ServiceEnableTagOverride": false,
    "ServiceProxy": {
      "MeshGateway": {},
      "Expose": {}
    },
    "ServiceConnect": {},
    "CreateIndex": 140715,
    "ModifyIndex": 140715
  }
]
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
{"level":"debug","msg":"Filtering disabled item","serviceName":"consul","time":"2021-03-27T22:07:19+01:00"}
{"level":"debug","msg":"Filtering disabled item","serviceName":"nomad","time":"2021-03-27T22:07:19+01:00"}
{"level":"error","msg":"field not found, node: server","serviceName":"dk2-unifi-secure-nomad-task-ad54cdb4-11cd-4325-3f8a-9048529692ee-group-unifi-unifi-secure-https","time":"2021-03-27T22:07:19+01:00"}
{"level":"debug","msg":"Configuration received from provider consulcatalog: {\"http\":{\"routers\":{\"lms\":{\"entryPoints\":[\"http\",\"https\"],\"service\":\"lms\",\"rule\":\"Host(`music`) || Host(`music.example.com`)\"},\"unifi\":{\"entryPoints\":[\"http\"],\"service\":\"unifi\",\"rule\":\"Host(`unifi`) || Host(`unifi.example.com`)\"}},\"services\":{\"lms\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://X.X.X.X:9000\"}],\"passHostHeader\":true}},\"unifi\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://X.X.X.X:28040\"}],\"passHostHeader\":true}}}},\"tcp\":{},\"udp\":{}}","providerName":"consulcatalog","time":"2021-03-27T22:07:19+01:00"}
{"level":"info","msg":"Skipping same configuration","providerName":"consulcatalog","time":"2021-03-27T22:07:19+01:00"}
```
