### ISSUE TITLE
Certificate served doesn't match request URL

### ISSUE THREAD

**Issue by MarkErik** [traefik/traefik#8018]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I curl one URL, and a certificate for another URL is served. This is with SNI strict enabled.

### What did you expect to see?

The certificate served matches the requested URL.

### What did you see instead?

I curl www.iwtk.me but the certificate for two.iwtk.me is served.
* Server certificate:
*  subject: CN=two.iwtk.me

```
curl -vL http://www.iwtk.me
* Rebuilt URL to: http://www.iwtk.me/
*   Trying 149.28.116.226...
* TCP_NODELAY set
* Connected to www.iwtk.me (149.28.116.226) port 80 (#0)
> GET / HTTP/1.1
> Host: www.iwtk.me
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Location: https://www.iwtk.me/
< Date: Mon, 29 Mar 2021 00:11:39 GMT
< Content-Length: 17
< Content-Type: text/plain; charset=utf-8
< 
* Ignoring the response-body
* Connection #0 to host www.iwtk.me left intact
* Issue another request to this URL: 'https://www.iwtk.me/'
*   Trying 149.28.116.226...
* TCP_NODELAY set
* Connected to www.iwtk.me (149.28.116.226) port 443 (#1)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=two.iwtk.me
*  start date: Mar 28 18:06:37 2021 GMT
*  expire date: Jun 26 18:06:37 2021 GMT
*  subjectAltName: host "www.iwtk.me" matched cert's "www.iwtk.me"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fcb12005200)
> GET / HTTP/2
> Host: www.iwtk.me
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< accept-ranges: bytes
< content-type: text/html
< date: Mon, 29 Mar 2021 00:11:40 GMT
< etag: "60479ce6-264"
< last-modified: Tue, 09 Mar 2021 16:05:58 GMT
< server: nginx/1.19.8
< content-length: 612
< 
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>

```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

docker-compose for Nginx service behind traefik
```yaml
version: "3.9"

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    networks:
      - services
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ng.rule=Host(`two.iwtk.me`) || Host(`www.iwtk.me`) || Host(`iwtk.me`)"
      - "traefik.http.routers.ng.entrypoints=websecure"
      - "traefik.http.routers.ng.tls.certresolver=myresolver"

networks:
  services:
    external: true
```

docker-compose for traefik
```yaml
version: "3.9"

#MYUID="$(id -u)" docker-compose up -d

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    volumes:
      - ./traefik.toml:/traefik.toml
      - ./data/traefik/tmp:/tmp
      - ./data/traefik/conf:/conf
      - ./data/traefik/access.log:/access.log
      - ./letsencrypt:/letsencrypt
      - /run/user/${MYUID}/docker.sock:/var/run/docker.sock
    networks:
      - services

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`who.iwtk.me`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    networks:
      - services

networks:
  services:
    external: true
```

traefik.toml
```toml
[providers]
[providers.docker]
  exposedByDefault = false
[providers.file]
  directory = "/conf/"
  watch = true

[accessLog]
  filePath = "/access.log"
  format = "json"
  bufferingSize = 100

  [accessLog.fields]
    defaultMode = "keep"

[entryPoints]
  [entryPoints.api]
    address = ":8080"

  [entryPoints.web]
    address = ":80"

  [entryPoints.web.http]
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[log]
  level = "DEBUG"

[certificatesResolvers.myresolver.acme]
  email = "xyz@xyz.com"
  storage = "/letsencrypt/acme.json"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "web"

[api]
  dashboard = true
```

sni.toml in /conf directory
```toml
[tls.options]
  [tls.options.default]
    sniStrict = true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2021-03-29T00:03:24Z" level=debug msg="Looking for provided certificate(s) to validate [\"two.iwtk.me\" \"www.iwtk.me\" \"iwtk.me\"]..." providerName=myresolver.acme routerName=ng@docker rule="Host(`two.iwtk.me`) || Host(`www.iwtk.me`) || Host(`iwtk.me`)"
time="2021-03-29T00:03:24Z" level=debug msg="No ACME certificate generation required for domains [\"two.iwtk.me\" \"www.iwtk.me\" \"iwtk.me\"]." providerName=myresolver.acme routerName=ng@docker rule="Host(`two.iwtk.me`) || Host(`www.iwtk.me`) || Host(`iwtk.me`)"
time="2021-03-29T00:03:32Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.54.0\"],\"X-Forwarded-Host\":[\"www.iwtk.me\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"1b5dcca30c09\"],\"X-Real-Ip\":[\"172.19.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"www.iwtk.me\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.19.0.1:40938\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2021-03-29T00:03:32Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.54.0\"],\"X-Forwarded-Host\":[\"www.iwtk.me\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"1b5dcca30c09\"],\"X-Real-Ip\":[\"172.19.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"www.iwtk.me\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.19.0.1:40938\",\"RequestURI\":\"/\",\"TLS\":null}" ForwardURL="http://172.19.0.4:80"
```
