### ISSUE TITLE
Docker + Traefik + Robo3T

### ISSUE THREAD

**Issue by jonit-dev** [traefik/traefik#8021]
Hey folks, 

I've been trying to connect to my production MongoDB database for a while now, but I couldn't make it work together with Traefik.

I always get a "connection refused" or "network couldn't be reached" error.

Could someone give me some help?

Here's my docker-compose.yml file

```
version: "3"

networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge

services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
      - "${NODE_API_PORT}:${NODE_API_PORT}"
      - "${MONGO_PORT}:${MONGO_PORT}"
      - "8081:8081"
    volumes:
      - "./traefik/traefik.toml:/traefik.toml"
      - "./traefik/traefik_dynamic.toml:/traefik_dynamic.toml"
      - "./traefik/acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web
    command:
      - "--accesslog"
      - "--log.level=INFO"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.mongo.address=:${MONGO_PORT}"
      - "--providers.docker"

  app-api:
    container_name: app-api
    restart: always
    build: .
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "app-database"
    links:
      - app-database
    networks:
      - internal
      - web
    labels:
      - "traefik.http.routers.be.rule=Host(`${NODE_API_SUBDOMAIN}`)"
      - "traefik.http.routers.be.tls=true"
      - "traefik.http.routers.be.tls.certresolver=lets-encrypt"
      - "traefik.port=${NODE_API_PORT}"
      - "traefik.docker.network=web"

  app-database:
    container_name: app-database
    restart: always
    image: mongo
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./docker_scripts/:/docker-entrypoint-initdb.d
    networks:
      - internal
      - web
    labels:
      - "traefik.http.routers.botz.rule=Host(`database.empregourgente.com`)"
      - "traefik.http.routers.botz.tls=true"
      - "traefik.http.routers.botz.tls.certresolver=lets-encrypt"
      - "traefik.port=${MONGO_PORT}"
      - "traefik.docker.network=web"

  app-admin-database:
    container_name: app-admin-database
    image: mongo-express
    env_file:
      - .env
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      ME_CONFIG_MONGODB_SERVER: app-database
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${DATABASE_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - app-database
    networks:
      - internal
      - web
    labels:
      - "traefik.http.routers.mongoadmin.rule=Host(`mongo-express.empregourgente.com`)"
      - "traefik.http.routers.mongoadmin.tls=true"
      - "traefik.http.routers.mongoadmin.tls.certresolver=lets-encrypt"
      - "traefik.port=8081"
      - "traefik.docker.network=web"

  app-bots:
    container_name: app-bots
    restart: on-failure
    build:
      context: ./bots
      dockerfile: Dockerfile
    volumes:
      - "./bots:/usr/src/app"
      - "/bots/node_modules/"
      - "/bots/tokens"
    networks:
      - internal
      - web
    labels:
      - "traefik.http.routers.botz.rule=Host(`${BOTS_SUBDOMAIN}`)"
      - "traefik.http.routers.botz.tls=true"
      - "traefik.http.routers.botz.tls.certresolver=lets-encrypt"
      - "traefik.port=${BOTS_CONTAINER_PORT}"
      - "traefik.docker.network=web"

```

My guess is that it uses a TCP connection instead of HTTP. But how could I proceed?

Thank you in advance!

PS: Currently I'm using a mongo-express GUI, but it's awful.
