### ISSUE TITLE
GnuTLS error 

### ISSUE THREAD

**Issue by viggy96** [traefik/traefik#8038]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Use wget on webpage. However, using curl works just fine. And all served webpages work fine in the browser as well. This issue affects all client side applications that depend on GnuTLS.

### What did you expect to see?
wget saving index.html.

### What did you see instead?
```
--2021-04-06 10:50:43--  https://jellyfin.viggy96.me/
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving jellyfin.viggy96.me (jellyfin.viggy96.me)... 10.0.0.1
Connecting to jellyfin.viggy96.me (jellyfin.viggy96.me)|10.0.0.1|:443... connected.
GnuTLS: A TLS fatal alert has been received.
GnuTLS: received alert [47]: Illegal parameter
Unable to establish SSL connection.
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

traefik.yaml
```yml
api:
   dashboard: true
   debug: true
 
 log:
   level: INFO
 
 accessLog: {}
 
 entryPoints:
   web:
     address: ":80"
     http:
       redirections:
         entryPoint:
           to: websecure
           scheme: https
   websecure:
     address: ":443"
 
 providers:
   docker:
     endpoint: "unix:///var/run/docker.sock"
     exposedByDefault: false
   file:
     filename: "/etc/traefik/config.yaml"
     watch: true
 
 certificatesResolvers:
   letsencrypt:
     acme:
       email: "admin@viggy96.me"
       storage: "/etc/traefik/acme.json"
       tlsChallenge: {}

```

config.yaml
```yml
http:
  middlewares:
    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        customFrameOptionsValue: "SAMEORIGIN"
        stsSeconds: 15552000
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
      
    local-only:
      ipWhiteList:
        sourceRange:
        - "192.168.0.0/16"
        - "172.16.0.0/12"
        - "10.0.0.0/8"

    private:
      chain:
        middlewares:
          - default-headers
          - local-only

    secure:
      chain:
        middlewares:
          - default-headers

tls:
  options:
    default:
      preferServerCipherSuites: true
      minVersion: VersionTLS12
      sniStrict: true
      curvePreferences:
        - "CurveP521"
        - "CurveP384"
      cipherSuites:
        - "TLS_AES_256_GCM_SHA384"
        - "TLS_CHACHA20_POLY1305_SHA256"
          #- "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
          #- "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
```

**Comment by viggy96** [comment]
I have this issue with several applications, not just Jellyfin, which is mentioned above. Nextcloud for example exhibits the same issue.

**Comment by viggy96** [comment]
Jellyfin has the following config in its docker-compose.yaml file:
```
jellyfin:
     image: jellyfin/jellyfin:latest
     restart: always
     environment:
       - UID=33
       - GID=33
       - TZ=America/New_York
     devices:
       - /dev/dri
     volumes:
       - /tmp/jellyfin:/transcodes
       - /tank/container_data/jellyfin_config:/config
       - /tank/container_data/jellyfin_cache:/cache
       - /tank/cloud/videos/:/media/video
       - /tank/cloud/music:/media/music
     expose:
       - 8096
     ports:
       - 1900:1900/udp
     labels:
       - "traefik.enable=true"
       - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
       - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.viggy96.me`)"
       - "traefik.http.routers.jellyfin.middlewares=secure@file"
       - "traefik.http.routers.jellyfin.tls=true"
       - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
```
