### ISSUE TITLE
mirroring failed for GET requests when maxBodySize is set

### ISSUE THREAD

**Issue by cszichao** [traefik/traefik#8045]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

add a mirroring sevice with maxBodySize set to a positive value (1024), request this service without body (e.g. GET)
```yaml
    mirrored-whami:
      mirroring:
        service: whami
        maxBodySize: 1024
        mirrors:
          - name: mirror
            percent: 100
```

### What did you expect to see?

routed whoami service

### What did you see instead?

Internal Server Errorerror creating reusable request: EOF

https://github.com/traefik/traefik/blob/b1e11f3e885f77b81cebc37e915a173ed57f0ecf/pkg/server/service/loadbalancer/mirror/mirror.go#L197-L200

the above mirroring code uses `io.ReadFull` to test body size, and this function reutrns EOF if no bytes were read. Since the GET request usually has no body, so `EOF` error is always returned when request content length is zero

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.7
Codename:     livarot
Go version:   go1.16
Built:        2021-03-08T17:18:28Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
