### ISSUE TITLE
Support service-name as address value in the forawrdAuth middleware

### ISSUE THREAD

**Issue by objque** [traefik/traefik#8051]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Hey!
I use the bundle nomad + consul + traefik: after starting container, nomad creates a service in the consul (if not presented) and adds the container address to it.
Traefik uses consul's services to create own service with `loadbalancer` type.

I want to add forwardAuth middleware that uses traefik's service as auth backend.

The problem is that this cannot be done: traefik does not support (?) internal routing in the forwardAuth middleware and sends a request to the specified address (domain or ip+port)

As a work-round, it possible to create a separate entry point with the address e.g 127.0.0.1:6000 and then use hard-coded address in the forwardAuth middleware. But it's not fully CloudNative, where life is too dynamic

I've tried to use different addresses e.g
1. `http://internal/v1/auth` where `internal` it's name of entryPoint
2. `http://auth@consulcatalog/v1/auth` where `auth@consulcatalog` it's service's name with type `loadbalancer`
3. `http://auth/v1/auth` where `auth` it's service's name with type `loadbalancer`

![example if auth service](https://user-images.githubusercontent.com/7000585/114316743-75e8c000-9b0d-11eb-9919-065decf881fd.png)

![example of auth middleware](https://user-images.githubusercontent.com/7000585/114316717-58b3f180-9b0d-11eb-9d29-c54fff370604.png)

**Comment by jbdoumenjou** [comment]
Hello @objque,

Thanks for your interest in Traefik!
> As a work-round, it possible to create a separate entry point with the address e.g 127.0.0.1:6000 and then use hard-coded address in the forwardAuth middleware. But it's not fully CloudNative, where life is too dynamic

As soon as you have a dedicated entrypoint and use the local URL in the forwardauth configuration, you can create an HTTP router and service on your authentication service and bind it to this entrypoint.
In this way, you have a dynamic forward auth backend thanks to "Traefikception" :smile:

WDYT?

**Comment by objque** [comment]
I'm sorry for late answer. 
Yes this is definitely a solution that I'm currently using, but it's require additional entrypoint, that may be overkill just for e.g proxy-pass auth. Instead of this will be more helpful to forward-request to already registered service, isn't it?

**Comment by szymswiat** [comment]
Hi!

@jbdoumenjou Is there any update on this issue? 

Basically, I'm trying to wrap external containerized application and constrain access to it using authentication method from my backend. It would be nice to have a way to point forwardauth.address to entrypoint in internal service.

I have tried to apply @objque workaround but I think I don't understand how should it work. Below is the configuration sample I used.

```yaml

version: "3.9"
services:

  traefik:
    ports:
      - "8080:8080"
      - "80:80"
    command:
      - --api
      - --api.insecure=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --accesslog
      - --log
      - --entrypoints.web.address=:80
      - --entrypoints.auth.address=:6000

  backend:
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./backend:/code
      - ~/.cache.pypoetry:/root/.cache/pypoetry
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.entrypoints=web,auth
      - traefik.http.routers.backend.rule=PathPrefix(`/api`)
      - traefik.http.routers.backend.priority=10


  external:
    expose:
      - "80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.external.entrypoints=web
      - traefik.http.routers.external.rule=PathPrefix(`/external`)
      - traefik.http.routers.external.priority=10
      - traefik.http.routers.external.tls=false

      - traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/external

      - traefik.http.middlewares.external-auth.forwardauth.address=http://localhost:6000/api/v1/auth/

      - traefik.http.routers.external.middlewares=cors-allow,strip-prefix,external-auth

```

When I'm trying to access "external" service I'm getting below error and looks like forwardauth does not send anything to backend endpoint.
```
traefik               | 127.0.0.1 - - [10/Mar/2023:20:08:20 +0000] "GET /api/v1/auth/ HTTP/1.1" - - "-" "-" 2 "-" "-" 0ms
traefik               | time="2023-03-10T20:08:20Z" level=debug msg="Remote error http://localhost:6000/api/v1/auth/. StatusCode: 404" middlewareType=ForwardedAuthType middlewareName=external-auth@docker
```

**Comment by lysilver** [comment]
This problem has not been implemented in the closed v2 project, will this be implemented in the future?

**Comment by nmengin** [comment]
Hello there,

This would not make it to our roadmap as we are focused elsewhere. If a community member would like to build it, let us know, and we will work with you to ensure you have all the information needed to merge it.

We prefer to work with our community members at the beginning of the design process to ensure that we are aligned and can move quickly with the review and merge process. Let us know here or create a PR before you start, and we will work with you there.

Don’t forget to check out the [contributor docs](https://github.com/traefik/contributors-guide/blob/master/pr_guidelines.md) and link the PR to this issue.

**Comment by helmut72** [comment]
Came here because I've searched for the same feature. I run Traefik with `network_mode: host` in Docker and therefore, Traefik can't find any address like for example:

```
services:
  oauth2-proxy:
  (...)
     labels:
       - traefik.http.middlewares.test-auth.forwardauth.address=http://oauth2-proxy:4180
```

... but a:

```
- traefik.http.services.test-auth.loadbalancer.server.port=4180
```
... did.

Would be cool to have something like:

```
- traefik.http.middlewares.test-auth.forwardauth.service=test-auth
```

Thanks.
