### ISSUE TITLE
Consulcatalog: tags are not recognized

### ISSUE THREAD

**Issue by LauriKem** [traefik/traefik#8053]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I have set up Consul between two machines (192.168.0.201 and 192.168.0.203) running docker-compose. I have set up the consulcatalog provider in Traefik container and automatic tag adding in Nextcloud container.

Output in Consul UI:
![image](https://user-images.githubusercontent.com/71082826/114693516-57a7dd80-9d22-11eb-8b6a-80649324fdc5.png)

The Nextcloud service in Consul UI:
![image](https://user-images.githubusercontent.com/71082826/114695993-dbfb6000-9d24-11eb-9a00-c80eb3729a27.png)

Output of ```curl http://192.168.0.201:8500/v1/catalog/services``` in Traefik's machine
```json
{"consul":[],
"nextcloud":[
"traefik.tcp.routers.nextcloud-tcp.entrypoints=https",
"traefik.tcp.routers.nextcloud-tcp.rule=HostSNI(`nextcloud.MYDOMAINNAME.net`)",
"traefik.tcp.routers.nextcloud-tcp.tls.certresolver=dns-cloudflare",
"traefik.tcp.routers.nextcloud-tcp.tls.passthrough=true",
"traefik.tcp.routers.nextcloud-tcp.service=nextcloud-tcp-svc",
"traefik.tcp.services.nextcloud-tcp-svc.loadbalancer.server.port=443",
"traefik.enable=true"
]}
```
### What did you expect to see?

Traefik recognizing the Nextcloud container with tag ```traefik.enable=true```and adding it to reverse proxy with the given ruleset.

### What did you see instead?

Traefik gives a message "Filtering disabled item" and ignores nextcloud.

If setting ``` - --providers.consulcatalog.exposedByDefault=true``` in Traefik, the other arguments given in Nextcloud's tags are still ignored but Nextcloud itself is recognized.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Traefik Docker container TOML arguments
```yml
      - --providers.consulcatalog=true
      - --providers.consulcatalog.prefix="traefik"
      - --providers.consulcatalog.endpoint.address=192.168.0.203:8500
      - --providers.consulcatalog.exposedByDefault=false
      - --providers.consulcatalog.defaultRule=Host(`{{ .Name }}.$DOMAINNAME`)
      - --providers.consulcatalog.cache=false
```
Nextcloud Docker container services
```yml
services:
  registrator:
    image: gliderlabs/registrator:latest
    command: "-ip 192.168.0.203 consul://192.168.0.203:8500"
    container_name: registrator
    hostname: consul-02
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: always
    ports:
      - 80:80
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/nextcloud:/config
      - /mnt/data:/data
      - $DOCKERDIR/nextcloud:/var/www/html
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - SERVICE_TAGS=traefik.enable=true,traefik.tcp.routers.nextcloud-tcp.entrypoints=https,traefik.tcp.routers.nextcloud-tcp.rule=HostSNI(`nextcloud.$DOMAINNAME`),traefik.tcp.routers.nextcloud-tcp.tls.certresolver=dns-cloudflare,traefik.tcp.routers.nextcloud-tcp.tls.passthrough>

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Logs when `- --providers.consulcatalog.exposedByDefault=false`
```
time="2021-04-12T08:27:59Z" level=debug msg="Filtering disabled item" serviceName=consul
time="2021-04-12T08:27:59Z" level=debug msg="Filtering disabled item" serviceName=nextcloud
time="2021-04-12T08:27:59Z" level=debug msg="Configuration received from provider consulcatalog: {\"http\":{},\"tcp\":{},\"udp\":{}}" providerName=consulcatalog
time="2021-04-12T08:27:59Z" level=info msg="Skipping same configuration" providerName=consulcatalog
```

Logs when ` - --providers.consulcatalog.exposedByDefault=true`
```
time="2021-04-12T08:41:31Z" level=debug msg="Configuration received from provider consulcatalog: {\"http\":{\"routers\":{\"consul\":{\"service\":\"consul\",\"rule\":\"Host(`consul.MYDOMAIN.net`)\"},\"nextcloud\":{\"service\":\"nextcloud\",\"rule\":\"Host(`nextcloud.MYDOMAIN.net`)\"}},\"services\":{\"consul\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://192.168.0.201:8300\"},{\"url\":\"http://192.168.0.203:8300\"},{\"url\":\"http://192.168.0.221:8300\"}],\"passHostHeader\":true}},\"nextcloud\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://192.168.0.203:80\"}],\"passHostHeader\":true}}}},\"tcp\":{},\"udp\":{}}" providerName=consulcatalog
time="2021-04-12T08:41:31Z" level=info msg="Skipping same configuration" providerName=consulcatalog
```
