### ISSUE TITLE
Traefik upgrade from 2.4.6 to 2.4.7+ broke "something" with chunked encoding

### ISSUE THREAD

**Issue by BSchwetzel** [traefik/traefik#8060]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Today I upgraded one of our traefik instances from 2.4.6 to 2.4.8, which had unexpected consequences. It seems traefik 2.4.7+ changed something, which leads to it forwarding a `Transfer-Encoding: chunked` header, but only if using HTTP 1.1 for the request. If we use HTTP 2 the behaviour is the same as before.

To reproduce this a simple curl against a traefik instance suffices, if the backend sets `Transfer-Encoding` (in our case Spring Boot does that, we use version 2.4 of it if that helps):

`curl --http1.1 -v URL`

When using this against Traefik 2.4.6 there is a `Content-Length: 15` header (or whatever your content length might be, of course), when using this against traefik 2.4.7+ we find `Transfer-Encoding: chunked`. So it seems traefik has removed some special handling for this (just guessing, i couldn't work this out from a simple comparison between the versions)

Now, why does it matter? Because our "request stack" looks as follows:

Note: traefik-2 is the one I upgraded, traefik-1 is the one that throws an error. Both services are Spring Boot, which sets the `Transfer-Encoding` header.

Client asks traefik-1, which forwards to service-1. service-1 then talks to traefik-2, which in turn talks to service-2. Now we have two possible scenarios: service-2 responds with JSON and sets the `Transfer-Encoding: chunked` header ->traefik-1 errors out. If service-2 has a timeout, traefik-2 itself will respond, thereby not forwarding `Transfer-Encoding`, which leads to a `Content-Length` header which is no problem.

We have verified that our service-1 makes the correct requests, and everything works as expected when we circumvent traefik-1 or downgrade it to 2.4.6.

### What did you expect to see?
Everything works like before.

### What did you see instead?
When a `Transfer-Encoding: chunked` header is present (which is the case from 2.4.7 onwards) our traefik-1 throws an Internal server error:
` time="2021-04-13T12:50:29Z" level=debug msg="'500 Internal Server Error' caused by: net/http: HTTP/1.x transport connection broken: too many transfer encodings: [\"chunked\" \"chunked\"]"`

The duplication of this header is not something we observe in our service-1, we don't know where this comes from. All we know is that traefik 2.4.7 added the header and neither traefik 2.4.6 nor 2.4.7+ are able to handle this.

### Output of `traefik version`: (_What version of Traefik are you using?_)

Both traefik instances are the same:
```
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64
```

#### traefik-1

static

```yaml
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
          priority: 1000

  web-secure:
    address: ":443"
    http:
      middlewares:
        - sts@file
      tls: {}

providers:
  file:
    directory: /etc/traefik
    filename: traefik_dynamic.yaml
  docker:
    endpoint: "unix:///var/run/docker.sock"
    swarmMode: true
    exposedByDefault: true
    watch: true
log:
  level: "DEBUG"
accessLog: {}
api:
  dashboard: true
ping:
  entryPoint: "web-secure"
```

dynamic

```yaml
http:
  routers:
    api:
      entryPoints:
        - web-secure
      middlewares:
        - dashboard-trailing-slash
        - api-auth
      rule: "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      service: "api@internal"
      priority: 500

  middlewares:
    sts:
      headers:
        stsSeconds: 15768000
    api-auth:
      basicAuth:
        usersFile: "/run/secrets/traefik_api_users"
    dashboard-trailing-slash:
      redirectRegex:
        regex: '^(.*)/dashboard$'
        replacement: '${1}/dashboard/'
tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/run/secrets/ssl_cert"
        keyFile: "/run/secrets/ssl_key"
```

labels (service-1)

```
"traefik.docker.lbswarm": "true",
"traefik.http.routers.service-list.rule": "PathPrefix(`/service-list`)",
"traefik.http.services.service-list.loadBalancer.server.port": "8080"
```

#### traefik-2

static

```yaml
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
          priority: 1000

  web-secure:
    address: ":443"
    http:
      middlewares:
        - sts@file
      tls: {}

providers:
  file:
    directory: /etc/traefik
    filename: traefik_dynamic.yaml
  docker:
    endpoint: "unix:///var/run/docker.sock"
    swarmMode: true
    watch: true
log:
  level: "INFO"
accessLog: {}
api:
  dashboard: true
ping:
  entryPoint: "web-secure"
```

dynamic

```yaml
http:
  routers:
    api:
      entryPoints:
        - web-secure
      middlewares:
        - dashboard-trailing-slash
        - api-auth
      rule: "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      service: "api@internal"
      priority: 500
      tls: {}

  middlewares:
    sts:
      headers:
        stsSeconds: 15768000
    api-auth:
      basicAuth:
        usersFile: "/run/secrets/entrypoint_api_users"
    dashboard-trailing-slash:
      redirectRegex:
        regex: '^(.*)/dashboard$'
        replacement: '${1}/dashboard/'
tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/run/secrets/entrypoint_cert"
        keyFile: "/run/secrets/entrypoint_key"
```

labels (service-2)

```
"traefik.docker.lbswarm": "true",
"traefik.http.routers.crypt-service.rule": "PathPrefix(\"/crypt-service\")",
"traefik.http.services.crypt-service.loadBalancer.server.port": "8080"
```
### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2021-04-13T12:50:29Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/service-list/status/DEV/crypt-service\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6\"],\"Cache-Control\":[\"max-age=0\"],\"Cookie\":[\"rl_anonymous_id=%224f4bbd81-ddbb-4982-ab4f-67b75dccc523%22; rl_user_id=%22%22; screenResolution=1920x1080\"],\"Dnt\":[\"1\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.75\"],\"X-Forwarded-Host\":[\"load-balancer.my-organisation.org\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"f31722fa6667\"],\"X-Real-Ip\":[\"10.0.203.102\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"load-balancer.my-organisation.org\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.0.203.102:53916\",\"RequestURI\":\"/service-list/status/DEV/crypt-service\",\"TLS\":null}"
 time="2021-04-13T12:50:29Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/service-list/status/DEV/crypt-service\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6\"],\"Cache-Control\":[\"max-age=0\"],\"Cookie\":[\"rl_anonymous_id=%224f4bbd81-ddbb-4982-ab4f-67b75dccc523%22; rl_user_id=%22%22; screenResolution=1920x1080\"],\"Dnt\":[\"1\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.75\"],\"X-Forwarded-Host\":[\"load-balancer.my-organisation.org\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"f31722fa6667\"],\"X-Real-Ip\":[\"10.0.203.102\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"load-balancer.my-organisation.org\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.0.203.102:53916\",\"RequestURI\":\"/service-list/status/DEV/crypt-service\",\"TLS\":null}" ForwardURL="http://10.0.11.73:8080"
 time="2021-04-13T12:50:29Z" level=debug msg="'500 Internal Server Error' caused by: net/http: HTTP/1.x transport connection broken: too many transfer encodings: [\"chunked\" \"chunked\"]"
 time="2021-04-13T12:50:29Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/service-list/status/DEV/crypt-service\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6\"],\"Cache-Control\":[\"max-age=0\"],\"Cookie\":[\"rl_anonymous_id=%224f4bbd81-ddbb-4982-ab4f-67b75dccc523%22; rl_user_id=%22%22; screenResolution=1920x1080\"],\"Dnt\":[\"1\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.75\"],\"X-Forwarded-Host\":[\"load-balancer.my-organisation.org\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"f31722fa6667\"],\"X-Real-Ip\":[\"10.0.203.102\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"load-balancer.my-organisation.org\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.0.203.102:53916\",\"RequestURI\":\"/service-list/status/DEV/crypt-service\",\"TLS\":null}"
```
