### ISSUE TITLE
Traefik upgrade from 2.3.3 to 2.4.8 breaks some routing configurations

### ISSUE THREAD

**Issue by nicholasnovakovic** [traefik/traefik#8065]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Upgraded Traefik from 2.3.3 to 2.4.8 on my Kubernetes cluster (v1.17.13).
Some services which were named with multiple sequential '-' stopped receiving traffic.
Found out that Traefik cannot detect the middlewares with these names.

### What did you expect to see?

Middlewares named with multiple sequential '-' characters are recognised by Traefik as per normal.

### What did you see instead?

Middlewares named with multiple sequential '-' characters are not recognised by Traefik anymore.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

We use Traefik as a Daemonset running on each node on Kubernetes.

Below is the config file we use. 

```yaml
    serversTransport:
      forwardingTimeouts:
        dialTimeout: 3s
    entryPoints:
      web:
        address: ":80"
        transport:
          respondingTimeouts:
            idleTimeout: 90s
      websecure:
        address: ":443"
        http:
          tls:
            options: default
        transport:
          respondingTimeouts:
            idleTimeout: 90s
    providers:
      providersThrottleDuration: 2s
      file:
        watch: true
        filename: "/certs/traefik-v2.toml"
      kubernetesCRD:
        namespaces:
          - gameid
    api:
      insecure: true
      dashboard: true
      debug: true
    metrics:
      prometheus:
        buckets:
        - 0.1
        - 0.3
        - 0.5
        - 1
        entryPoint: traefik
    log:
      level: INFO
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2021-04-14T02:15:06Z" level=error msg="middleware \"gameid-django-fantasy---tommy-tanam-https-redirect@kubernetescrd\" does not exist" entryPointName=web routerName=gameid-django-fantasy-tommy-tanam-05389a19201907336c32@kubernetescrd
time="2021-04-14T02:15:06Z" level=error msg="middleware \"gameid-django-fantasy---tommy-tanam-https-redirect@kubernetescrd\" does not exist" entryPointName=websecure routerName=websecure-gameid-django-fantasy-tommy-tanam-05389a19201907336c32@kubernetescrd
time="2021-04-14T02:15:06Z" level=error msg="middleware \"gameid-fe-fantasy---tommy-tanam-https-redirect@kubernetescrd\" does not exist" entryPointName=websecure routerName=websecure-gameid-fe-fantasy-tommy-tanam-45c92a04dec4f4f23367@kubernetescrd
time="2021-04-14T02:31:43Z" level=error msg="middleware \"gameid-django-fantasy---tommy-tanam-https-redirect@kubernetescrd\" does not exist" entryPointName=web routerName=gameid-django-fantasy-tommy-tanam-05389a19201907336c32@kubernetescrd
time="2021-04-14T02:31:43Z" level=error msg="middleware \"gameid-django-fantasy---tommy-tanam-https-redirect@kubernetescrd\" does not exist" entryPointName=websecure routerName=websecure-gameid-django-fantasy-tommy-tanam-05389a19201907336c32@kubernetescrd
```

**Comment by SantoDE** [comment]
Hey @nicholasnovakovic,

thanks for your interest in the project :)

Do you have a simple reproducible example?

**Comment by nicholasnovakovic** [comment]
Hi @SantoDE, thank you for the prompt response :)

You can create a demo application with this deployment, service, ingressroute, and middleware.

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-fantasy---tommy-tanam
  namespace: gameid
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe-fantasy---tommy-tanam
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fe-fantasy---tommy-tanam
    spec:
      containers:
      - command:
        - nginx
        - -g
        - daemon off;
        image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: fe-fantasy---tommy-tanam
  namespace: gameid
spec:
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fe-fantasy---tommy-tanam
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fe-fantasy---tommy-tanam
  namespace: gameid
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - kind: Rule
    match: Host(`test-traefik-bug.test-domain.com`) && PathPrefix(`/`)
    middlewares:
    - name: fe-fantasy---tommy-tanam-https-redirect
    services:
    - name: fe-fantasy---tommy-tanam
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: fe-fantasy---tommy-tanam-https-redirect
  namespace: gameid
spec:
  redirectScheme:
    permanent: true
    scheme: https
```
 
In the end these are the logs that I got from my Traefik pods.

```
time="2021-04-14T08:28:50Z" level=error msg="middleware \"gameid-fe-fantasy---tommy-tanam-https-redirect@kubernetescrd\" does not exist" entryPointName=web routerName=gameid-fe-fantasy-tommy-tanam-efd4e4509336bb2a775f@kubernetescrd
time="2021-04-14T08:28:50Z" level=error msg="middleware \"gameid-fe-fantasy---tommy-tanam-https-redirect@kubernetescrd\" does not exist" entryPointName=websecure routerName=websecure-gameid-fe-fantasy-tommy-tanam-efd4e4509336bb2a775f@kubernetescrd
```

When I try to curl the host in this ingressroute, I just get a 404 response.

Please advise!

Thank you very much :)

**Comment by SantoDE** [comment]
Hi @nicholasnovakovic,

I can confirm you're issue on 2.4, but I also have the issue on 2.3. I don't see how this works on 2.3. You got an example? :)

**Comment by nicholasnovakovic** [comment]
Hi @SantoDE so sorry for the late reply.

Yes I have an example that is working on 2.3.3 currently. 
The naming is slightly different in that the --- occurs on the rightmost.

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-fantasy---draw
  namespace: gameid
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe-fantasy---draw
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fe-fantasy---draw
    spec:
      containers:
      - command:
        - nginx
        - -g
        - daemon off;
        image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: fe-fantasy---draw
  namespace: gameid
spec:
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fe-fantasy---draw
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fe-fantasy---draw
  namespace: gameid
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - kind: Rule
    match: Host(`test-traefik-bug.test-domain.com`) && PathPrefix(`/`)
    middlewares:
    - name: fe-fantasy---draw-https-redirect
    services:
    - name: fe-fantasy---draw
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: fe-fantasy---draw-https-redirect
  namespace: gameid
spec:
  redirectScheme:
    permanent: true
    scheme: https
```
So instead the deployment would look something like the above.

Thank you!
