### ISSUE TITLE
[doc]tls/https with selfsigned certificate improvement

### ISSUE THREAD

**Issue by Grummfy** [traefik/traefik#8073]
### Do you want to request a *feature* or report a *bug*?
I would like to improve the documentation

### What did you expect to see?
A working example for TLS like we have with let's encrypt with more explanation.

### More detail
I read the documentation. Perhaps not carefully enough?
I find a lot of example of configuration regarding https with let's encrypt. But example with tls are quiete theorical.

What I find not clear enough

Adding a certificate in `[[tls.certificates]]` section means
* automatically matching it in https by it's domain name

If you want to change the default certificate you need to redeclare it in 

```
[tls.stores]
	[tls.stores.default]
		[tls.stores.default.defaultCertificate]
```

So perhaps in https://doc.traefik.io/traefik/https/tls/
It could be interesting to have a working example using a certificate generated using [mkcert](https://github.com/FiloSottile/mkcert/releases) with some explanation about the implication of each config?

Except the following example, with perhaps some extra explanation. I don't really have more suggestion. If I find a better way, I will try a PR, but for now, I can only do suggestion.

----
### Example

generate a certificate (in subdirectory named traefik)

```
mkcert traefik.docker.localhost whoami.docker.localhost
```

docker-compose.yml file:

```
version: '3'

services:
  reverse-proxy:
    image: traefik:v2.4
    command:
      # use dynamic configuration file for certificate declaration
      - --providers.file.directory=/opt/traefik/config
      # Enables the dashboard
      - --api.insecure=true
      #  tells Traefik to listen to docker
      - --providers.docker=true
      - --entryPoints.web.address=:80
      - --entryPoints.https.address=:443
      - --entrypoints.https.http.tls=true

    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/traefik:/opt/traefik:ro
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.service=dashboard@internal"

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
```

the traefik/config/tls.toml (the name have no, importance, but the path yes) file
```
# add certificate for [traefik|whoami].docker.localhost (will be automatched regarding domain name)
[[tls.certificates]]
  certFile = "/opt/traefik/traefik.docker.localhost+1.pem"
  keyFile = "/opt/traefik/traefik.docker.localhost+1-key.pem"
```

thanks for reading,
feel free to close or improve regarding if you find it usefull or not
