### ISSUE TITLE
Ability to downgrade http to http2 when using tcp routers

### ISSUE THREAD

**Issue by samip5** [traefik/traefik#8074]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I expected to see a way to handle connecting to a backend which does not support http2.
In this case the backend in question is Unifi Controller, the software does not seem to support it and thus the connection with passthough=false, fails.

Config snippet:

```toml
[tcp.routers]
  [tcp.routers.unifi-rtr]
      entryPoints = ["https"]
      rule = "HostSNI(`unifi.<snip>.fi`)"
      service = "unifi-svc"
      [tcp.routers.unifi-rtr.tls]
      #  certresolver = "dns-cloudflare"
        passthrough = false

[tcp.services]
  [tcp.services.unifi-svc]
    [tcp.services.unifi-svc.loadBalancer]
      [[tcp.services.unifi-svc.loadBalancer.servers]]
        address = "192.168.2.44:8443"
```
