### ISSUE TITLE
Traefik runs out of FD on sudden high load

### ISSUE THREAD

**Issue by MTRNord** [traefik/traefik#8075]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I did log into my [matrix server](https://github.com/matrix-org/synapse) running behind traefik 2.4.8 with the [nheko](https://github.com/Nheko-Reborn/nheko) client which causes an expected high amount of requests for a short amount of time.

### What did you expect to see?

The requests work without issues,

### What did you see instead?

A sudden traefik crash and multiple errors in the logs:

```
Apr 17 22:04:11 Debian-108-buster-64-minimal traefik[16881]: time="2021-04-17T22:04:11+02:00" level=error msg="accept tcp [::]:443: accept4: too many open files" entryPointName=web-secure
Apr 17 22:04:11 Debian-108-buster-64-minimal traefik[16881]: time="2021-04-17T22:04:11+02:00" level=error msg="accept tcp [::]:8448: accept4: too many open files" entryPointName=synapse
Apr 17 22:04:11 Debian-108-buster-64-minimal traefik[16881]: time="2021-04-17T22:04:11+02:00" level=error msg="accept tcp [::]:443: accept4: too many open files" entryPointName=web-secure
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[http]
  [http.routers]
    [http.routers.https-redirect]
      rule = "HostRegexp(`{any:.*}`)"
      middlewares = ["https-redirect"]
      service = "dummy"

    [http.routers.dashboard]
      rule = "Host(`dashboard.nordgedanken.dev`)"
      service = "api@internal"
      entrypoints = ["web-secure"]
      middlewares = ["hstsHeader@file"]
      [http.routers.dashboard.tls]
        certResolver = "letsencrypt"
      [http.middlewares.dashboard.compress]

    [http.routers.git]
      rule = "Host(`git.nordgedanken.dev`)"
      service = "gitlab"
      entrypoints = ["web-secure"]
      middlewares = ["hstsHeader@file"]
      [http.routers.git.tls]
        certResolver = "letsencrypt-http"
      [http.middlewares.git.compress]

    [http.routers.metrics]
      rule = "Host(`dashboard.nordgedanken.dev`) && PathPrefix(`/metrics`)"
      service = "prometheus@internal"
      entrypoints = ["web-secure"]
      middlewares = ["hstsHeader@file"]
      [http.routers.metrics.tls]
        certResolver = "letsencrypt"
      [http.middlewares.metrics.compress]

    [http.routers.well-known]
      rule = "Host(`nordgedanken.dev`) && PathPrefix(`/.well-known/matrix`)"
      service = "matrix-well-known"
      entrypoints = ["web-secure"]
      middlewares = ["well-knownHeader@file", "matrix-stripprefix@file"]
      priority = 100000
      [http.routers.well-known.tls]
        certResolver = "letsencrypt"

    [http.routers.well-known-keymaker]
      rule = "Host(`nordgedanken.dev`) && Path(`/.well-known/matrix/metadata`)"
      service = "well-known-keymaker"
      entrypoints = ["web-secure"]
      middlewares = ["well-knownHeader@file", "well-known-keymaker-stripprefix@file", "well-known-keymaker-content_type@file"]
      priority = 1001
      [http.routers.well-known-keymaker.tls]
        certResolver = "letsencrypt"

    [http.routers.fdroid]
      rule = "((Host(`fdroid.nordgedanken.dev`) && PathPrefix(`/repo`)) || (Host(`fdroid.nordgedanken.dev`) && PathPrefix(`/repos/CeqjCgrW_4yY_px59cntLkkAov3QRlwQ/repo`)) || Host(`fdroid.nordgedanken.dev`)) || ((Host(`fdroid.fluffychat.im`) && PathPrefix(`/repo`)) || (Host(`fdroid.fluffychat.im`) && PathPrefix(`/repos/CeqjCgrW_4yY_px59cntLkkAov3QRlwQ/repo`)) || Host(`fdroid.fluffychat.im`))"
      service = "fdroid"
      entrypoints = ["web-secure"]
      middlewares = ["hstsHeader@file", "fdroid-stripprefix@file"]
      [http.routers.fdroid.tls]
        certResolver = "letsencrypt-http"
      [http.middlewares.fdroid.compress]

    [http.routers.fdroid-nightly]
      rule = "Host(`nightly.fdroid.fluffychat.im`)"
      service = "fdroid-nightly"
      entrypoints = ["web-secure"]
      middlewares = ["hstsHeader@file", "fdroid-stripprefix@file"]
      [http.routers.fdroid-nightly.tls]
        certResolver = "letsencrypt-http"
      [http.middlewares.fdroid-nightly.compress]

    [http.routers.keymaker]
      rule = "Host(`joinmatrix.rocks`) || Host(`homeservers.mx`)" 
      service = "keymaker"
      entrypoints = ["web-secure"]
      middlewares = ["hstsHeader@file"]
      [http.routers.keymaker.tls]
        certResolver = "letsencrypt"
      [http.middlewares.keymaker.compress]

    [http.routers.synapse]
      rule = "Host(`matrix.nordgedanken.dev`) || (Host(`matrix.nordgedanken.dev`) && PathPrefix(`/.well-known/matrix/`))"
      service = "synapse"
      entrypoints = ["web-secure", "synapse"]
      middlewares = ["hstsHeader@file", "well-knownHeader@file"]
      priority = 1000
      [http.routers.synapse.tls]
        certResolver = "letsencrypt"
      [http.middlewares.synapse.compress]

    [http.routers.conduit]
      rule = "Host(`conduit.nordgedanken.dev`)"
      service = "conduit"
      entrypoints = ["web-secure", "synapse"]
      middlewares = ["hstsHeader@file", "well-knownHeader@file"]
      [http.routers.conduit.tls]
        certResolver = "letsencrypt-http"
      [http.middlewares.conduit.compress]

    [http.routers.webmin]
      rule = "Host(`webmin.nordgedanken.dev`)"
      service = "webmin"
      entrypoints = ["web-secure"]
      middlewares = ["hstsHeader@file"]
      [http.routers.webmin.tls]
        certResolver = "letsencrypt-http"
      [http.middlewares.webmin.compress]

    [http.routers.element-testing]
      rule = "Host(`element-testing.nordgedanken.dev`)"
      service = "element-testing"
      entrypoints = ["web-secure"]
      middlewares = ["hstsHeader@file"]
      [http.routers.element-testing.tls]
        certResolver = "letsencrypt-http"
      [http.middlewares.element-testing.compress]

    [http.routers.grafana]
      rule = "Host(`grafana.nordgedanken.dev`)"
      service = "grafana"
      entrypoints = ["web-secure"]
      middlewares = ["hstsHeader@file"]
      [http.routers.grafana.tls]
        certResolver = "letsencrypt-http"
      [http.middlewares.grafana.compress]

    [http.routers.nextcloud]
      rule = "Host(`cloud.nordgedanken.dev`)"
      service = "nextcloud"
      entrypoints = ["web-secure"]
      middlewares = ["hstsHeader@file", "nextcloud-host@file", "nextcloud-redirectregex@file"]
      [http.routers.nextcloud.tls]
        certResolver = "letsencrypt-http"
      [http.middlewares.nextcloud.compress]

  [http.services]
    [[http.services.dummy.LoadBalancer.servers]]
      url = ""
    [[http.services.fdroid.LoadBalancer.servers]]
      url = "http://172.18.0.1:5000"
    [[http.services.fdroid-nightly.LoadBalancer.servers]]
      url = "http://172.18.0.1:7000"
    [[http.services.well-known-keymaker.LoadBalancer.servers]]
      url = "http://172.18.0.1:6000"
    [[http.services.keymaker.LoadBalancer.servers]]
      url = "http://172.18.0.1:8000"
    [[http.services.gitlab.LoadBalancer.servers]]
      url = "http://127.0.0.1:800"
    [[http.services.synapse.LoadBalancer.servers]]
      url = "http://[::1]:8008"
    [[http.services.matrix-well-known.LoadBalancer.servers]]
      url = "http://127.0.0.1:6001"
    [[http.services.conduit.LoadBalancer.servers]]
      url = "http://127.0.0.1:6167"
    [[http.services.webmin.LoadBalancer.servers]]
      url = "http://127.0.0.1:10000"
    [[http.services.element-testing.LoadBalancer.servers]]
      url = "http://127.0.0.1:8083"
    [[http.services.grafana.LoadBalancer.servers]]
      url = "http://127.0.0.1:3333"
    [[http.services.nextcloud.LoadBalancer.servers]]
      url = "http://127.0.0.1:5555"

  [http.middlewares]
    [http.middlewares.fdroid-stripprefix.stripPrefix]
      prefixes = ["/repos/CeqjCgrW_4yY_px59cntLkkAov3QRlwQ/repo", "/repo"]
    [http.middlewares.matrix-stripprefix.stripPrefix]
      prefixes = ["/.well-known"]
    [http.middlewares.well-known-keymaker-content_type.headers]
      [http.middlewares.well-known-keymaker-content_type.headers.customResponseHeaders]
        Content-Type = "application/json"
    [http.middlewares.well-known-keymaker-stripprefix.stripPrefix]
      prefixes = ["/.well-known/matrix"]
    [http.middlewares.https-redirect.redirectscheme]
      scheme = "https"
    [http.middlewares.well-knownHeader.headers]
      stsSeconds = 63072000
      stsIncludeSubdomains = true
      stsPreload = true
      forceSTSHeader = true
#      hostsProxyHeaders = ["matrix.nordgedanken.dev"]
      accessControlAllowMethods= ["*"]
      accessControlAllowOriginList = ["*"]
      accessControlAllowHeaders = ["*"]
      [http.middlewares.well-knownHeader.headers.customRequestHeaders]
        Host = "matrix.nordgedanken.dev"
        X-Forwarded-Host = "matrix.nordgedanken.dev"
        X-Forwarded-Proto = "https"
      [http.middlewares.well-knownHeader.headers.customResponseHeaders]
        Content-Type = "application/json"
    [http.middlewares.nextcloud-host.headers]
      [http.middlewares.nextcloud-host.headers.customRequestHeaders]
          Host = "cloud.nordgedanken.dev"
          X-Forwarded-Host = "cloud.nordgedanken.dev"
          X-Forwarded-Proto = "https"

    [http.middlewares.hstsHeaderMediaRepo.headers]
      stsSeconds = 63072000
      stsIncludeSubdomains = true
      stsPreload = true
      forceSTSHeader = true
      #hostsProxyHeaders = ["nordgedanken.dev", "matrix.nordgedanken.dev"]
      [http.middlewares.hstsHeaderMediaRepo.headers.customRequestHeaders]
        Host = "nordgedanken.dev"
        X-Forwarded-Host = "nordgedanken.dev"

    [http.middlewares.hstsHeader.headers]
      stsSeconds = 63072000
      stsIncludeSubdomains = true
      stsPreload = true
      forceSTSHeader = true

    [http.middlewares.nextcloud-redirectregex.redirectRegex]
      permanent = true
      regex = "https://(.*)/.well-known/(card|cal)dav"
      replacement = "https://${1}/remote.php/dav/"
      
[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
    ]
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

(Non debug but relevant snippet)

```
Apr 17 22:04:11 Debian-108-buster-64-minimal traefik[16881]: time="2021-04-17T22:04:11+02:00" level=error msg="accept tcp [::]:443: accept4: too many open files" entryPointName=web-secure
Apr 17 22:04:11 Debian-108-buster-64-minimal traefik[16881]: time="2021-04-17T22:04:11+02:00" level=error msg="accept tcp [::]:8448: accept4: too many open files" entryPointName=synapse
Apr 17 22:04:11 Debian-108-buster-64-minimal traefik[16881]: time="2021-04-17T22:04:11+02:00" level=error msg="accept tcp [::]:443: accept4: too many open files" entryPointName=web-secure
```

### Additional Information

The sysctl and ulimits for FDs are set to the max of `1048576`. I cannot increase this any further.

Also none of the other services on my server die. Only traefik dies due to this.
