### ISSUE TITLE
Set the access log field invalid

### ISSUE THREAD

**Issue by openstack-test** [traefik/traefik#8079]
Hi, I need some help

**Environment**

- traefik: 2.1.1
- k8s: 1.16.1(backend)

**Steps**
cli  configuration access log
```
spec:
      containers:
      - args:
        - --api
        - --api.dashboard=true
        - --api.insecure=true
        - --accesslog=true
        - --accesslog.format=json
        - --accesslog.bufferingsize=10
        - --accesslog.filters.retryattempts
        - --accesslog.fields.defaultmode=drop
        - --accesslog.fields.names.StartLocal=keep
        - --accesslog.fields.names.Duration=keep
        - --accesslog.fields.names.ClientAddr=keep
        - --accesslog.fields.names.RequestAddr=keep
        - --accesslog.fields.headers.defaultmode=drop
        - --accesslog.fields.headers.names.User-Agent=redact
        - --accesslog.fields.headers.names.Authorization=drop
        - --accesslog.fields.headers.names.Content-Type=keep
        - --log.level=INFO
        ......
```

**Issue**
See the log
```
# kubectl logs traefik-ingress-lb-bsmrb -n kube-system --tail 10
time="2021-04-19T06:59:54Z" level=error msg="kubernetes service not found: mk-master/mk-wat-api-master" providerName=kubernetescrd ingress=ingressroute-https namespace=mk-master
time="2021-04-19T06:59:54Z" level=error msg="kubernetes service not found: mk-dev3/qw-assistant-api" ingress=ingressroute-qw-assistant-api-https namespace=mk-dev3 providerName=kubernetescrd
time="2021-04-19T06:59:54Z" level=error msg="kubernetes service not found: crm-master/xtestxxx" ingress=test-xxx-ingressroute2 namespace=crm-master providerName=kubernetescrd
time="2021-04-19T06:59:54Z" level=error msg="kubernetes service not found: crm-master/xtestxxx" ingress=test-xxx-ingressroute2 namespace=crm-master providerName=kubernetescrd
time="2021-04-19T06:59:54Z" level=error msg="kubernetes service not found: default/wp-client" providerName=kubernetescrd ingress=ingressroute-crm namespace=default
time="2021-04-19T06:59:54Z" level=error msg="kubernetes service not found: default/wp-manage" ingress=ingressroute-crm namespace=default providerName=kubernetescrd
time="2021-04-19T06:59:54Z" level=error msg="subset not found for mk-master/mk-sdk" providerName=kubernetescrd namespace=mk-master ingress=ingressroute-mk-mesh-https
time="2021-04-19T06:59:54Z" level=error msg="kubernetes service not found: mk-master/mk-cof-free-svc" providerName=kubernetescrd ingress=ingressroute-internal-https namespace=mk-master
time="2021-04-19T06:59:54Z" level=error msg="Cannot create service: service not found" ingress=kf-app namespace=java-test serviceName=java-im-service providerName=kubernetescrd servicePort=8064
time="2021-04-19T06:59:54Z" level=error msg="Cannot create service: service not found" providerName=kubernetescrd ingress=kf-pc namespace=java-test serviceName=java-im-service servicePort=8063
```

The log content of standard output is not the field content (StartLocal、ClientAddr、RequestAddr etc) set by user. What's wrong with my configuration? How can I configure to output only the specified field content such as StartLocal、ClientAddr、RequestAddr etc.
I checked the official documents and other materials, but I didn't find a solution. Thank
