### ISSUE TITLE
entrypoint global middlewares ignore entrypoint specific middlewares. 

### ISSUE THREAD

**Issue by dirtycajunrice** [traefik/traefik#8106]
When setting a middleware at the entrypoint level in a kubernetes deployment, additional middlewares defined in an ingress annotation are ignored. This caused authenticated endpoints to fail to use forwardAuth. Here are the relevant config bits:

argument:
```
--entrypoints.websecure.http.middlewares=ingress-error-pages@kubernetescrd
```

ingress annotations:
```yaml
traefik.ingress.kubernetes.io/router.entrypoints: websecure
traefik.ingress.kubernetes.io/router.middlewares: domain-tld-my-backend-my-auth@kubernetescrd
```

In the dashboard it showed both middlewares in the order of `error pages > my-app-my-auth`

the endpoint was accessible without auth.

When removing the argument and setting:
```
traefik.ingress.kubernetes.io/router.middlewares: ingress-error-pages@kubernetescrd,domain-tld-my-backend-my-auth@kubernetescrd
```

The endpoint was not accessible without auth. This is a huge problem! Any thoughts?

**Comment by ldez** [comment]
Hello,

could you provide more information (configuration, crds, ...)?

the issue template: https://raw.githubusercontent.com/traefik/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by DirtyCajunRice** [comment]
@ldez  I gave the all of the relevant information in the initial post. The things you have specifically asked for are either directly in my initial post or blatantly inferable. The only thing that does not exist in my initial post is logs. There are no logs because the logs do not show any helpful information as it is just _**ignoring**_ the other middleware as also previously stated in my initial post. 

While we are linking issue templates, Do you find you have an easy time using a template that is only readable when previewed? When you click your own link, it is 99% html comment and 1% actual markdown. The user has to wade through an obnoxious amount of meant-to-be-helpful commentary that ultimately slows the entire issue reporting process down significantly. I would rather delete the entire thing and post the relevant information than wade through the muck that defines the readability of that template.

Here is the overly verbose information you asked for that provides identical supplementary information

> configuration
>kubernetes
> --entrypoints.websecure.http.middlewares=ingress-error-pages@kubernetescrd

> ingress 
> traefik.ingress.kubernetes.io/router.entrypoints: websecure
> traefik.ingress.kubernetes.io/router.middlewares: domain-tld-my-backend-my-app@kubernetescrd

crd is not relevant to the issue as it is directly inferred from the name `error-pages`

All that said here is the overly verbose version that gives the same information,,, sanitized:

# Helm 
```yaml
fullnameOverride: traefik
image:
  name: traefik
  tag: 2.4.8
globalArguments:
  - "--global.checknewversion"
  - "--serverstransport.insecureskipverify=true"
  - "--providers.kubernetesingress.ingressclass=traefik"
  - "--metrics.prometheus=true"
  - "--metrics.prometheus.entryPoint=metrics"
  - "--entrypoints.websecure.http.middlewares=ingress-error-pages@kubernetescrd"
additionalArguments:
  - "--providers.kubernetesingress.ingressendpoint.hostname=do.traefik.k8s.domain.com"
providers:
  kubernetesIngress:
    publishedService:
      enabled: true
logs:
  general:
    format: json
    level: DEBUG
  access:
    enabled: true
    format: json
service:
  spec:
    externalTrafficPolicy: Local
ports:
  web:
    redirectTo: websecure
  websecure:
    tls:
      enabled: true
  metrics:
    port: 8082
    expose: true
    exposedPort: 8082
ingressRoute:
  dashboard:
    enabled: false
ingressClass:
  enabled: true
  isDefaultClass: true
  fallbackApiVersion: v1
service:
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: traefik
    service.beta.kubernetes.io/do-loadbalancer-protocol: tcp
    service.beta.kubernetes.io/do-loadbalancer-size-slug: lb-small
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "10"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "3"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "3"
pilot:
  enabled: true
experimental:
  plugins:
    enabled: true
    token: "snip"
rollingUpdate:
  maxUnavailable: 3
  maxSurge: 3
resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "300m"
    memory: "150Mi"
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 30
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - traefik
          topologyKey: kubernetes.io/hostname
```
# Ingress
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.priority: "10"
    cert-manager.io/cluster-issuer: le-production
  name: my-backend
spec:
  rules:
    - host: domain.tld
      http:
        paths:
          - path: /auth-required
            pathType: Prefix
            backend:
              service:
                name: my-backend
                port:
                  number: 80
  tls:
    - hosts: [domain.tld]
      secretName: domain-tld
```

# Error Pages middleware
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: error-pages
spec:
  errors:
    status:
      - "400-599"
    query: /{status}.html
    service:
      name: error-pages
      port: 8080
```

# Forward Auth middlware
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: my-auth
spec:
  forwardAuth:
    address: https://domain.tld/api/v2/auth?group=0
```

# Logs
## Working
### Authorized
```json
{
   "ClientAddr":"snip:64506",
   "ClientHost":"snip",
   "ClientPort":"64506",
   "ClientUsername":"-",
   "DownstreamContentSize":208,
   "DownstreamStatus":200,
   "Duration":67073352,
   "OriginContentSize":208,
   "OriginDuration":66683587,
   "OriginStatus":200,
   "Overhead":389765,
   "RequestAddr":"domain.tld",
   "RequestContentSize":0,
   "RequestCount":16039,
   "RequestHost":"domain.tld",
   "RequestMethod":"GET",
   "RequestPath":"/api/v2/auth?group=0",
   "RequestPort":"-",
   "RequestProtocol":"HTTP/2.0",
   "RequestScheme":"https",
   "RetryAttempts":0,
   "RouterName":"my-backend-namespace-domain-tld@kubernetes",
   "ServiceAddr":"snip:80",
   "ServiceName":"namespace-my-backend-80@kubernetes",
   "ServiceURL":{
      "Scheme":"http",
      "Opaque":"",
      "User":null,
      "Host":"snip:80",
      "Path":"",
      "RawPath":"",
      "ForceQuery":false,
      "RawQuery":"",
      "Fragment":"",
      "RawFragment":""
   },
   "StartLocal":"2021-04-30T01:18:01.107550909Z",
   "StartUTC":"2021-04-30T01:18:01.107550909Z",
   "entryPointName":"websecure",
   "level":"info",
   "msg":"",
   "time":"2021-04-30T01:18:01Z"
}

{
   "ClientAddr":"snip:54244",
   "ClientHost":"snip",
   "ClientPort":"54244",
   "ClientUsername":"-",
   "DownstreamContentSize":874,
   "DownstreamStatus":200,
   "Duration":186338432,
   "OriginContentSize":874,
   "OriginDuration":186024969,
   "OriginStatus":200,
   "Overhead":313463,
   "RequestAddr":"domain.tld",
   "RequestContentSize":0,
   "RequestCount":16805,
   "RequestHost":"domain.tld",
   "RequestMethod":"GET",
   "RequestPath":"/auth-required/",
   "RequestPort":"-",
   "RequestProtocol":"HTTP/2.0",
   "RequestScheme":"https",
   "RetryAttempts":0,
   "RouterName":"my-backend-namespace-domain-tld-my-backend@kubernetes",
   "ServiceAddr":"snip:80",
   "ServiceName":"namespace-my-backend-80@kubernetes",
   "ServiceURL":{
      "Scheme":"http",
      "Opaque":"",
      "User":null,
      "Host":"snip:80",
      "Path":"",
      "RawPath":"",
      "ForceQuery":false,
      "RawQuery":"",
      "Fragment":"",
      "RawFragment":""
   },
   "StartLocal":"2021-04-30T01:18:00.995508628Z",
   "StartUTC":"2021-04-30T01:18:00.995508628Z",
   "entryPointName":"websecure",
   "level":"info",
   "msg":"",
   "time":"2021-04-30T01:18:01Z"
}
```
### Unauthorized
```
{
   "ClientAddr":"snip:62707",
   "ClientHost":"snip",
   "ClientPort":"62707",
   "ClientUsername":"-",
   "DownstreamContentSize":221,
   "DownstreamStatus":401,
   "Duration":100687758,
   "OriginContentSize":221,
   "OriginDuration":100213035,
   "OriginStatus":401,
   "Overhead":474723,
   "RequestAddr":"domain.tld",
   "RequestContentSize":0,
   "RequestCount":19666,
   "RequestHost":"domain.tld",
   "RequestMethod":"GET",
   "RequestPath":"/api/v2/auth?group=0",
   "RequestPort":"-",
   "RequestProtocol":"HTTP/2.0",
   "RequestScheme":"https",
   "RetryAttempts":0,
   "RouterName":"my-backend-domain-tld-domain-tld@kubernetes",
   "ServiceAddr":"192.168.14.162:80",
   "ServiceName":"domain-tld-my-backend-80@kubernetes",
   "ServiceURL":{
      "Scheme":"http",
      "Opaque":"",
      "User":null,
      "Host":"snip:80",
      "Path":"",
      "RawPath":"",
      "ForceQuery":false,
      "RawQuery":"",
      "Fragment":"",
      "RawFragment":""
   },
   "StartLocal":"2021-04-30T01:28:01.188466535Z",
   "StartUTC":"2021-04-30T01:28:01.188466535Z",
   "entryPointName":"websecure",
   "level":"info",
   "msg":"",
   "time":"2021-04-30T01:28:01Z"
}
{
   "ClientAddr":"snip:54764",
   "ClientHost":"snip.245",
   "ClientPort":"54764",
   "ClientUsername":"-",
   "DownstreamContentSize":1885,
   "DownstreamStatus":401,
   "Duration":154265486,
   "OriginContentSize":1885,
   "OriginDuration":153894827,
   "OriginStatus":401,
   "Overhead":370659,
   "RequestAddr":"domain.tld",
   "RequestContentSize":0,
   "RequestCount":16570,
   "RequestHost":"domain.tld",
   "RequestMethod":"GET",
   "RequestPath":"/auth-required/",
   "RequestPort":"-",
   "RequestProtocol":"HTTP/2.0",
   "RequestScheme":"https",
   "RetryAttempts":0,
   "RouterName":"my-app-domain-tld-domain-tld-my-app@kubernetes",
   "ServiceAddr":"192.168.14.148:8080",
   "ServiceName":"ingress-error-pages-errorpage-service@kubernetescrd",
   "ServiceURL":{
      "Scheme":"http",
      "Opaque":"",
      "User":null,
      "Host":"snip:8080",
      "Path":"",
      "RawPath":"",
      "ForceQuery":false,
      "RawQuery":"",
      "Fragment":"",
      "RawFragment":""
   },
   "StartLocal":"2021-04-30T01:28:01.139231806Z",
   "StartUTC":"2021-04-30T01:28:01.139231806Z",
   "entryPointName":"websecure",
   "level":"info",
   "msg":"",
   "time":"2021-04-30T01:28:01Z"
}
```
## Not Working
### Success
```json
{
   "ClientAddr":"snip:54006",
   "ClientHost":"snip",
   "ClientPort":"54006",
   "ClientUsername":"-",
   "DownstreamContentSize":208,
   "DownstreamStatus":200,
   "Duration":79053973,
   "OriginContentSize":208,
   "OriginDuration":78969651,
   "OriginStatus":200,
   "Overhead":84322,
   "RequestAddr":"domain.tld",
   "RequestContentSize":0,
   "RequestCount":979,
   "RequestHost":"domain.tld",
   "RequestMethod":"GET",
   "RequestPath":"/api/v2/auth?group=0",
   "RequestPort":"-",
   "RequestProtocol":"HTTP/2.0",
   "RequestScheme":"https",
   "RetryAttempts":0,
   "RouterName":"my-backend-domain-tld-domain-tld@kubernetes",
   "ServiceAddr":"snip:80",
   "ServiceName":"domain-tld-my-backend-80@kubernetes",
   "ServiceURL":{
      "Scheme":"http",
      "Opaque":"",
      "User":null,
      "Host":"snip:80",
      "Path":"",
      "RawPath":"",
      "ForceQuery":false,
      "RawQuery":"",
      "Fragment":"",
      "RawFragment":""
   },
   "StartLocal":"2021-04-30T01:49:29.720340443Z",
   "StartUTC":"2021-04-30T01:49:29.720340443Z",
   "entryPointName":"websecure",
   "level":"info",
   "msg":"",
   "time":"2021-04-30T01:49:29Z"
}
{
   "ClientAddr":"snip:55304",
   "ClientHost":"snip",
   "ClientPort":"55304",
   "ClientUsername":"-",
   "DownstreamContentSize":874,
   "DownstreamStatus":200,
   "Duration":81218563,
   "OriginContentSize":874,
   "OriginDuration":81122741,
   "OriginStatus":200,
   "Overhead":95822,
   "RequestAddr":"domain.tld",
   "RequestContentSize":0,
   "RequestCount":3307,
   "RequestHost":"domain.tld",
   "RequestMethod":"GET",
   "RequestPath":"/auth-required/",
   "RequestPort":"-",
   "RequestProtocol":"HTTP/2.0",
   "RequestScheme":"https",
   "RetryAttempts":0,
   "RouterName":"my-backend-domain-tld-domain-tld-my-backend@kubernetes",
   "ServiceAddr":"snip:80",
   "ServiceName":"domain-tld-my-backend-80@kubernetes",
   "ServiceURL":{
      "Scheme":"http",
      "Opaque":"",
      "User":null,
      "Host":"snip:80",
      "Path":"",
      "RawPath":"",
      "ForceQuery":false,
      "RawQuery":"",
      "Fragment":"",
      "RawFragment":""
   },
   "StartLocal":"2021-04-30T01:49:29.71965955Z",
   "StartUTC":"2021-04-30T01:49:29.71965955Z",
   "entryPointName":"websecure",
   "level":"info",
   "msg":"",
   "time":"2021-04-30T01:49:29Z"
}
```
### Failure (Actually Success)
```json
{
   "ClientAddr":"snip:39525",
   "ClientHost":"snip",
   "ClientPort":"39525",
   "ClientUsername":"-",
   "DownstreamContentSize":1885,
   "DownstreamStatus":401,
   "Duration":76615731,
   "OriginContentSize":1885,
   "OriginDuration":76452095,
   "OriginStatus":401,
   "Overhead":163636,
   "RequestAddr":"domain.tld",
   "RequestContentSize":0,
   "RequestCount":232,
   "RequestHost":"domain.tld",
   "RequestMethod":"GET",
   "RequestPath":"/api/v2/auth?group=0",
   "RequestPort":"-",
   "RequestProtocol":"HTTP/2.0",
   "RequestScheme":"https",
   "RetryAttempts":0,
   "RouterName":"my-backend-domain-tld-domain-tld@kubernetes",
   "ServiceAddr":"snip:8080",
   "ServiceName":"ingress-error-pages-errorpage-service@kubernetescrd",
   "ServiceURL":{
      "Scheme":"http",
      "Opaque":"",
      "User":null,
      "Host":"snip:8080",
      "Path":"",
      "RawPath":"",
      "ForceQuery":false,
      "RawQuery":"",
      "Fragment":"",
      "RawFragment":""
   },
   "StartLocal":"2021-04-30T01:44:42.487639343Z",
   "StartUTC":"2021-04-30T01:44:42.487639343Z",
   "entryPointName":"websecure",
   "level":"info",
   "msg":"",
   "time":"2021-04-30T01:44:42Z"
}
{
   "ClientAddr":"snip:55624",
   "ClientHost":"snip",
   "ClientPort":"55624",
   "ClientUsername":"-",
   "DownstreamContentSize":874,
   "DownstreamStatus":200,
   "Duration":165840995,
   "OriginContentSize":874,
   "OriginDuration":165491446,
   "OriginStatus":200,
   "Overhead":349549,
   "RequestAddr":"domain.tld",
   "RequestContentSize":0,
   "RequestCount":1871,
   "RequestHost":"domain.tld",
   "RequestMethod":"GET",
   "RequestPath":"/auth-required/",
   "RequestPort":"-",
   "RequestProtocol":"HTTP/2.0",
   "RequestScheme":"https",
   "RetryAttempts":0,
   "RouterName":"my-backend-domain-tld-domain-tld-my-backend@kubernetes",
   "ServiceAddr":"snip:80",
   "ServiceName":"domain-tld-my-backend-80@kubernetes",
   "ServiceURL":{
      "Scheme":"http",
      "Opaque":"",
      "User":null,
      "Host":"snip:80",
      "Path":"",
      "RawPath":"",
      "ForceQuery":false,
      "RawQuery":"",
      "Fragment":"",
      "RawFragment":""
   },
   "StartLocal":"2021-04-30T01:44:42.400487114Z",
   "StartUTC":"2021-04-30T01:44:42.400487114Z",
   "entryPointName":"websecure",
   "level":"info",
   "msg":"",
   "time":"2021-04-30T01:44:42Z"
}
```
