### ISSUE TITLE
Pilot error with Docker

### ISSUE THREAD

**Issue by FelippeChemello** [traefik/traefik#8108]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am trying to use Pilot with Traefik running on Docker as Proxy. However when I add `--pilot.token=REPLACE_TRAEFIK_PILOT_TOKEN ` to command section It brokes showing the message above.

```sh
command traefik error: failed to decode configuration from flags: field not found, node: pilot
```

### What did you expect to see?

It running normally

### What did you see instead?

```sh
command traefik error: failed to decode configuration from flags: field not found, node: pilot
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

v2.0

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
traefik-proxy:
        image: traefik:v2.0
        restart: REPLACE_RESTART
        container_name: traefik
        ports:
            - '8080:8080'
            - target: 80
              published: 80
              mode: host
            - target: 443
              published: 443
              mode: host
        command:
            - --api.dashboard=true
            - --api=true
            - --log.level=DEBUG
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --providers.docker.network=external
            - --entrypoints.web.address=:80
            - --entrypoints.web-secured.address=:443
            - --certificatesresolvers.codestack.acme.tlschallenge=true
            - --certificatesresolvers.codestack.acme.email=myemail@host.com
            - --certificatesresolvers.codestack.acme.storage=/letsencrypt/acme.json
            - --accesslog=true
            - --accesslog.filepath=/tmp/access.log
            - --accesslog.format=json
            - --log.filePath=/tmp/traefik.log
            - --log.format=json
            - --log.level=DEBUG
            - --pilot.token=my-valid-token
        volumes:
            - ./letsencrypt-certs:/letsencrypt
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - external
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.api.rule=Host(`monitor.api.docker`)'
            - 'traefik.http.routers.api.service=api@internal'
            - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
            - 'traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true'
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
command traefik error: failed to decode configuration from flags: field not found, node: pilot
```
