### ISSUE TITLE
[Documentation] IngressRoute with ExternalName service shows example without mandatory 'port' field

### ISSUE THREAD

**Issue by ChristianCiach** [traefik/traefik#8112]
I think this is an error in the documentation, even though I wish it would work as shown there :)

Please have a look at this screenshot of the current documentation for the IngressRoute resource found at https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroute

![grafik](https://user-images.githubusercontent.com/19341644/117009896-834c3100-acec-11eb-81e8-53b5771c3b0f.png)

This example shows the declaration of an IngressRoute to a service of type "ExternalName" with no port number:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: test.route
  namespace: default

spec:
  entryPoints:
    - foo

  routes:
  - match: Host(`example.net`)
    kind: Rule
    services:
    - name: external-svc
```

This seems to be an error, because the field `spec.routes[].services[].port` seems to be mandatory, even if the declared `Service` already defines its port. The text above the example is correct, but the example itself seems to be wrong.
