### ISSUE TITLE
Turning on full metrics will lose 40% performance and needs to be optimized

### ISSUE THREAD

**Issue by letian0805** [traefik/traefik#8118]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
Version: v2.4, contain routers metrics.
Metrics provider: prometheus
Metrics: entryPoints, services, routers
Trun off accessLog.
Case 1:
Turn off all metrics,  traefik can get 14000 QPS.
Case 2:
Turn on all metrics, can get only 9400 QPS.

Performance of metrics needs to be optimized.

**Comment by rtribotte** [comment]
Hello @letian0805,

Thanks for your interest in Traefik!

Which metric provider are you using?
Can you share something reproducible or the methodology you've used to reach your conclusions?

Without knowing exactly the context of the performance drop you are facing, it will be difficult to address your issue.
Nonetheless, it comes without saying that enabling metrics or access log, or any middleware, which remain as additional computations, the performances will drop accordingly to those additional computations.

**Comment by letian0805** [comment]
Hi @rtribotte 

I'm using prometheus.

Metrics configures of case 1:
```toml
#[accesslog]

[metrics]
    [metrics.prometheus]
        entryPoint = "metrics"
        addEntryPointsLabels = false
        addServicesLabels = false
        addRoutersLabels = false
```
case 2:
```toml
#[accesslog]

[metrics]
    [metrics.prometheus]
        entryPoint = "metrics"
        addEntryPointsLabels = true
        addServicesLabels = true
        addRoutersLabels = true
```
