### ISSUE TITLE
Allow assuming default host if no SNI indication is given (for Let's Encrypt)

### ISSUE THREAD

**Issue by akx** [traefik/traefik#8123]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Following up on https://github.com/traefik/traefik/issues/2829, I have a situation where I'd like to proxy Redis (TCP, non-HTTP) connections over TLS with automatic Let's Encrypt certificates. (I am aware that Redis 6 has built-in TLS, but it doesn't have built-in Let's Encrypt 😄)

Redis clients in general do not send SNI indications, so one needs a HostSNI(`*`) on the router for it to basically do any routing. However, with that enabled, Traefik always serves the built-in default certificate since there's no other indication on the connection. `openssl s_client` connects nicely, and I can talk Redis to the underlying server, but the certificate is `CN = TRAEFIK DEFAULT CERT`, of course.

### Takeaway

It would be handy to be able to tell Traefik to assume a given fallback SNI name if none was sent by the peer, e.g. (c.f. the below example configuration)

```toml
[tcp.routers.redis-tls-router.tls]
fallbackSNI = "some-example-domain.example.com"
```

### Testing configuration

My very simple file-based testing configuration is (with DNS names censored)

#### static configuration

```toml
[log]
level = "DEBUG"

[entryPoints]
web = { address = ":80" }
redis-tls = { address = ":55555" }

[certificatesResolvers.le.acme]
email = "example@example.com"
storage = "acme.json"
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

[certificatesResolvers.le.acme.httpChallenge]
entryPoint = "web"

[providers.file]
filename = "/root/traefik.dyn.toml"
```

#### traefik.dyn.toml
```toml
[tcp.routers.redis-tls-router]
entryPoints = [ "redis-tls" ]
rule = "HostSNI(`*`)"
service = "redis"

[tcp.routers.redis-tls-router.tls]
certResolver = "le"

[[tcp.routers.redis-tls-router.tls.domains]]
main = "some-example-domain.example.com"

[tcp.services.redis.loadBalancer]
servers = [ { address = "127.0.0.1:6379" } ]
```
