### ISSUE TITLE
middleware %q does not exist 

### ISSUE THREAD

**Issue by yuzujoe** [traefik/traefik#8138]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I was migrating Traefik from v1 to v2, I got a CORS error, so I decided to configure middleware for my setup.
I originally used toml to manage the configuration, so I configured cors as follows.

I  was expecting this cors configuration to be loaded by setting it in the kubernetes Ingress manifest or entryPoints field.

but error occured.

```
level=error msg="middleware \"cors@file\" does not exist" routerName=<my-router-name> entryPointName=web
level=error msg="middleware \"cors@file\" does not exist" entryPointName=https routerName=<my-router-name>@kubernetes
```

### What did you expect to see?

I was expecting the Middleware configuration to be loaded.

### What did you see instead?

https://doc.traefik.io/traefik/routing/entrypoints/#middlewares

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
arm64v8/traefik:v2.4.8
EKS 1.19
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
    [entryPoints]
      [entryPoints.http]
        address = ":80"
        [entryPoints.http.http]
            middlewares = ["cors@file"]

      [entryPoints.name.transport]
        [entryPoints.name.transport.lifeCycle]
          requestAcceptGraceTimeout = 60

      [entryPoints.web.http.redirections.entryPoint]
        to = "https"
        scheme = "https"
        [entryPoints.web.http]
            middlewares = ["cors@file"]

      [entryPoints.https]
        address = ":443"
        [entryPoints.https.http]
            middlewares = ["cors@file"]

   [http.middlewares]
      [http.middlewares.cors.headers]
        accessControlAllowMethods = ["GET", "OPTIONS", "PUT", "POST", "DELETE"]
        accessControlAllowHeaders = "*"
        accessControlAllowOriginList = ["*"]
        accessControlMaxAge = 100
        addVaryHeader = true
```

my ingress configuration

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: my-ingress-class
    traefik.ingress.kubernetes.io/router.entrypoints: http,https
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: cors@file
  name: my-ingress-name
spec:
  rules:
  - host: my-host
    http:
      paths:
      - backend:
          serviceName: service-name
          servicePort: port
        path: /
        pathType: ImplementationSpecific
```
