### ISSUE TITLE
ipWhitelist middleware doesn't work as expected

### ISSUE THREAD

**Issue by TheSilkky** [traefik/traefik#8139]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
```yml
  portainer:
    image: portainer/portainer-ce:alpine
    hostname: portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    networks:
      - agent
      - traefik-public
    volumes:
      - /mnt-gluster/config-1/core/portainer-data:/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"

        # Access Router
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_HOSTNAME}`)"
        - "traefik.http.routers.portainer.middlewares=portainer-ip"
        - "traefik.http.routers.portainer.service=portainer-service"

        # Ip Whitelist
        - "traefik.http.middlewares.portainer-ip.ipwhitelist.sourcerange=hidden/32, hiddenipv6/128"

        # Service
        - "traefik.http.services.portainer-service.loadbalancer.server.port=9000"
```

### What did you expect to see?

I expected to be able to access the app from my ip address.

### What did you see instead?
In the browser I get "forbidden" 

and for some reason instead of getting a 403 Forbidden I get a 308 Permanent Redirect

HTTP/1.1 308 Permanent Redirect
Location: https://app.com/
Date: Mon, 17 May 2021 07:21:56 GMT
Content-Length: 18
Content-Type: text/plain; charset=utf-8

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v2.4.8
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Docker swarm mode

#### Static config
```yml
api: 
  dashboard: true

pilot:
  token: ""

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

  matrix:
    address: :8448
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

providers:
  docker:
    network: traefik-public
    swarmMode: true
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /configurations/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: 
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web

```
### Dynamic file
```yml
# Dynamic configuration
http:
  
  middlewares:
    # Security Headers
    secureHeaders:
      headers:
        stsSeconds: 31536000                # Strict-Transport-Security
        stsIncludeSubdomains: true
        stsPreload: true
        browserXssFilter: true              # X-XSS-Protection                 
        customFrameOptionsValue: "SAMEORIGIN" # X-Frame-Options
        contentTypeNosniff: true            # X-Content-Type-Options
        referrerPolicy: "strict-origin-when-cross-origin"   # Referrer-Policy
        
    user-auth:
      basicAuth:
        users:
          # generate:
          # echo $(htpasswd -nb <username> <password>)
          - ""

    duplicatiAuth:
      basicAuth:
        users:
          - ""

  routers:
    traefik-mailcow: 
      rule: "Host(``)"
      tls:
        certResolver: letsencrypt
      entrypoints: websecure
      service: traefik-mailcow-service

  services:
    traefik-mailcow-service:
      loadBalancer:
        servers:
          - url: http://nginx-mailcow:8080/

tls:
  options:
    default:
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      minVersion: VersionTLS12

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
