### ISSUE TITLE
Kubernetes: Liveness/Readiness check for external Endpoints Services

### ISSUE THREAD

**Issue by ChristianCiach** [traefik/traefik#8147]
Traefik `IngressRoute` has no support for health checks. Unfortunately, the issue https://github.com/traefik/traefik/issues/6492 has been closed with this comment:

> You have to use the heathcheck systems from k8s.

As we can read here, Kubernetes has no support for health checks of headless services (with custom `Endpoints`) or services of type `ExternalName`: https://github.com/kubernetes/kubernetes/issues/77738#issuecomment-491560980

This leaves us with the unsatisfying situation that it is currently impossible to have health checks for external services when using the KubernetesCRD provider. 

I see no good reason for omitting this feature from KubernetesCRD and forcing people to use the file provider instead.

Please see the comments starting at https://github.com/traefik/traefik/issues/6492#issuecomment-599699681 for further use-cases of this feature.

**Comment by marcmognol** [comment]
Dear traefik team,

Is there any solution that you could provide to anwser our needs?
I would like to use Traefik as a load balancer for some services hosted outside our Kubernetes cluster, so today I use file provider and it worked like a charm.

But I would prefere using CRD resources.

Would be possible to have the same level of feature between the CRD and the file provider for Service objects ?

Thanks

Marc

**Comment by emilevauge** [comment]
If someone from the community wants to contribute on this, the maintainers team would love to support & help :)

**Comment by marcmognol** [comment]
Hi @emilevauge,
Thank you for your reply.

Are we in line that the need is to be able to use a CRD type TraefikService, in order to replace the following configuration in file ?
```
  services:
    uat-service:
      loadBalancer:
        serversTransport: uat-transport
        servers:
          - url: https://localserver-1.asf.pri:443
          - url: https://localserver-2.asf.pri:443
        healthCheck:
          hostname: uat.local.pri
          path: /landing-page/
          interval: 15s
        sticky:
          cookie:
            secure: true
            httpOnly: true
```
