### ISSUE TITLE
Cloudflare DNS challenge error for certificate renewal

### ISSUE THREAD

**Issue by devster31** [traefik/traefik#8150]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?

Automatic renewal of the LE certificate

### What did you see instead?

Certs fail to renew with the following

```
traefik_1           | time="2021-05-21T22:06:34Z" level=info msg="Renewing certificate from LE : {Main:rpi3.metrics.example.ovh SANs:[rpi3p.metrics.example.ovh]}" providerName=cf.acme
traefik_1           | time="2021-05-21T22:06:34Z" level=debug msg="legolog: [INFO] [rpi3.metrics.example.ovh] acme: Trying renewal with -272 hours remaining"
traefik_1           | time="2021-05-21T22:06:34Z" level=debug msg="legolog: [INFO] [rpi3.metrics.example.ovh, rpi3p.metrics.example.ovh] acme: Obtaining bundled SAN certificate"
traefik_1           | time="2021-05-21T22:06:34Z" level=debug msg="No ACME certificate generation required for domains [\"ceph.example.ovh\"]." providerName=cf.acme routerName=ceph@file rule="Host(`ceph.example.ovh`)"
traefik_1           | time="2021-05-21T22:06:34Z" level=debug msg="Added outgoing tracing middleware noop@internal" routerName=web-to-websecure@internal middlewareName=tracing middlewareType=TracingForwarder entryPointName=web
--
--
traefik_1           | time="2021-05-21T22:06:39Z" level=debug msg="legolog: [WARN] [rpi3p.metrics.example.ovh] acme: cleaning up failed: cloudflare: unknown record ID for '_acme-challenge.rpi3p.metrics.example.ovh.' "
traefik_1           | time="2021-05-21T22:06:39Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/13323641978"
traefik_1           | time="2021-05-21T22:06:39Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/13323641979"
traefik_1           | time="2021-05-21T22:06:40Z" level=error msg="Error renewing certificate from LE: {rpi3.metrics.example.ovh [rpi3p.metrics.example.ovh]}, error: one or more domains had a problem:\n[rpi3.metrics.example.ovh] [rpi3.metrics.example.ovh] acme: error presenting token: cloudflare: failed to create TXT record: HTTP status 400: Record already exists. (81057)\n[rpi3p.metrics.example.ovh] [rpi3p.metrics.example.ovh] acme: error presenting token: cloudflare: failed to create TXT record: HTTP status 400: Record already exists. (81057)\n" providerName=cf.acme
```
OR
```
traefik_1           | time="2021-05-21T21:33:20Z" level=info msg="Testing certificate renew..." providerName=cf.acme
traefik_1           | time="2021-05-21T21:33:20Z" level=info msg="Renewing certificate from LE : {Main:example.ovh SANs:[*.example.ovh]}" providerName=cf.acme
traefik_1           | time="2021-05-21T21:37:45Z" level=error msg="Error renewing certificate from LE: {example.ovh [*.example.ovh]}, error: one or more domains had a problem:\n[*.example.ovh] time limit exceeded: last error: read udp 172.18.0.4:51247->172.64.32.198:53: i/o timeout\n[example.ovh] time limit exceeded: last error: read udp 172.18.0.4:45513->172.64.32.198:53: i/o timeout\n" providerName=cf.acme
traefik_1           | time="2021-05-21T21:37:45Z" level=info msg="Renewing certificate from LE : {Main:rpi3.metrics.example.ovh SANs:[rpi3p.metrics.example.ovh]}" providerName=cf.acme
traefik_1           | time="2021-05-21T21:41:59Z" level=error msg="Error renewing certificate from LE: {rpi3.metrics.example.ovh [rpi3p.metrics.example.ovh]}, error: one or more domains had a problem:\n[rpi3.metrics.example.ovh] time limit exceeded: last error: NS melinda.ns.cloudflare.com. did not return the expected TXT record [fqdn: example.ovh., value: aoHnuJhjqkrS0_gOslfT7FVllyGtgDJbyxlMibmkEbw]: \n[rpi3p.metrics.example.ovh] time limit exceeded: last error: NS melinda.ns.cloudflare.com. did not return the expected TXT record [fqdn: example.ovh., value: iwUUH532s9ukWFbptQuObFosnFpZgeluftapI6Q8b30]: \n" providerName=cf.acme
```

### Output of `traefik version`:

```
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64
```
Running on `docker` with `docker-compose`.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Abridged `docker-compose.yml` with a couple of configs.

```yaml
networks:
  backend: {}
services:
  metrics:
    expose:
    - '9000'
    image: nginx:alpine
    labels:
      traefik.enable: "true"
      traefik.http.routers.metrics.rule: HostRegexp(`{nodeexporter:[a-z0-9]+}.metrics.example.ovh`)
      traefik.http.routers.metrics.tls: "true"
      traefik.http.routers.metrics.tls.certresolver: cf
      traefik.http.services.metrics.loadbalancer.server.port: '9000'
    networks:
      backend: {}
    restart: unless-stopped
    volumes:
    - /srv/pv/nginx:/etc/nginx/conf.d:ro
  traefik:
    command:
    - --accesslog=true
    - --api.dashboard=true
    - --providers.docker=true
    - --providers.docker.network=home_backend
    - --providers.docker.exposedByDefault=false
    - --providers.file.directory=/etc/traefik/conf.d
    - --providers.file.watch=true
    - --certificatesResolvers.cf.acme.email=email@example.com
    - --certificatesResolvers.cf.acme.storage=/etc/traefik/acme.json
    - --certificatesResolvers.cf.acme.dnsChallenge=true
    - --certificatesResolvers.cf.acme.dnsChallenge.provider=cloudflare
    - --entrypoints.web.address=:80
    - --entrypoints.web.http.redirections.entryPoint.to=websecure
    - --entrypoints.web.http.redirections.entryPoint.scheme=https
    - --entrypoints.websecure.address=:443
    - --log.level=INFO
    - --metrics.prometheus=true
    environment:
      CLOUDFLARE_API_KEY: api
      CLOUDFLARE_EMAIL: email
    image: traefik:livarot
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.basic-auth.basicauth.users: user:pass
      traefik.http.routers.api.middlewares: basic-auth
      traefik.http.routers.api.rule: Host(`traefik.example.ovh`)
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.tls: "true"
      traefik.http.routers.api.tls.certresolver: cf
      traefik.http.routers.api.tls.domains[0].main: example.ovh
      traefik.http.routers.api.tls.domains[0].sans: '*.example.ovh'
    networks:
      backend: {}
      default: {}
    ports:
    - published: 80
      target: 80
    - published: 443
      target: 443
    restart: unless-stopped
    volumes:
    - /srv/pv/traefik:/etc/traefik:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
  znc:
    container_name: znc
    expose:
    - '6501'
    image: znc:1.8
    labels:
      traefik.enable: "true"
      traefik.http.routers.znc.rule: PathPrefix(`/znc`)
      traefik.http.routers.znc.tls: "true"
      traefik.http.routers.znc.tls.certresolver: cf
    networks:
      backend: {}
    ports:
    - published: 6501
      target: 6501
    restart: unless-stopped
    user: 1000:1000
    volumes:
    - /srv/pv/znc:/znc-data:rw
version: '3.7'
volumes:
  ... some volumes ...
```

The only file-based configuration is the following:
```yaml
## Dynamic configuration
http:
  routers:
    ceph:
      rule: "Host(`ceph.example.ovh`)"
      service: "ceph"
      tls:
        certresolver: "cf"
  services:
    ceph:
      loadBalancer:
        servers:
        - url: "http://10.0.0.166:8088"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
traefik_1           | time="2021-05-21T21:55:24Z" level=debug msg="legolog: [INFO] [example.ovh] acme: Preparing to solve DNS-01"
traefik_1           | time="2021-05-21T21:55:25Z" level=debug msg="legolog: [INFO] [*.example.ovh] acme: Cleaning DNS-01 challenge"
traefik_1           | time="2021-05-21T21:55:25Z" level=debug msg="legolog: [WARN] [*.example.ovh] acme: cleaning up failed: cloudflare: unknown record ID for '_acme-challenge.example.ovh.' "
traefik_1           | time="2021-05-21T21:55:25Z" level=debug msg="legolog: [INFO] [example.ovh] acme: Cleaning DNS-01 challenge"
traefik_1           | time="2021-05-21T21:55:25Z" level=debug msg="legolog: [WARN] [example.ovh] acme: cleaning up failed: cloudflare: unknown record ID for '_acme-challenge.example.ovh.' "
traefik_1           | time="2021-05-21T21:55:25Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/13323395324"
traefik_1           | time="2021-05-21T21:55:26Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/13323395326"
traefik_1           | time="2021-05-21T21:55:26Z" level=debug msg="legolog: [INFO] [rpi3.metrics.example.ovh] acme: Trying renewal with -272 hours remaining"
traefik_1           | time="2021-05-21T21:55:26Z" level=debug msg="legolog: [INFO] [rpi3.metrics.example.ovh, rpi3p.metrics.example.ovh] acme: Obtaining bundled SAN certificate"
traefik_1           | time="2021-05-21T21:55:27Z" level=debug msg="legolog: [INFO] [rpi3.metrics.example.ovh] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/13323409739"
traefik_1           | time="2021-05-21T21:55:27Z" level=debug msg="legolog: [INFO] [rpi3p.metrics.example.ovh] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/13323409741"
traefik_1           | time="2021-05-21T21:55:27Z" level=debug msg="legolog: [INFO] [rpi3.metrics.example.ovh] acme: Could not find solver for: tls-alpn-01"
traefik_1           | time="2021-05-21T21:55:27Z" level=debug msg="legolog: [INFO] [rpi3.metrics.example.ovh] acme: Could not find solver for: http-01"
traefik_1           | time="2021-05-21T21:55:27Z" level=debug msg="legolog: [INFO] [rpi3.metrics.example.ovh] acme: use dns-01 solver"
traefik_1           | time="2021-05-21T21:55:27Z" level=debug msg="legolog: [INFO] [rpi3p.metrics.example.ovh] acme: Could not find solver for: tls-alpn-01"
traefik_1           | time="2021-05-21T21:55:27Z" level=debug msg="legolog: [INFO] [rpi3p.metrics.example.ovh] acme: Could not find solver for: http-01"
traefik_1           | time="2021-05-21T21:55:27Z" level=debug msg="legolog: [INFO] [rpi3p.metrics.example.ovh] acme: use dns-01 solver"
traefik_1           | time="2021-05-21T21:55:27Z" level=debug msg="legolog: [INFO] [rpi3.metrics.example.ovh] acme: Preparing to solve DNS-01"
traefik_1           | time="2021-05-21T21:55:28Z" level=debug msg="legolog: [INFO] cloudflare: new record for rpi3.metrics.example.ovh, ID 80ad8b70b3b9989588b7d7615acc15f5"
traefik_1           | time="2021-05-21T21:55:28Z" level=debug msg="legolog: [INFO] [rpi3p.metrics.example.ovh] acme: Preparing to solve DNS-01"
traefik_1           | time="2021-05-21T21:55:29Z" level=debug msg="legolog: [INFO] cloudflare: new record for rpi3p.metrics.example.ovh, ID 701ac2feb5d758f5531b984d1aafd376"
traefik_1           | time="2021-05-21T21:55:29Z" level=debug msg="legolog: [INFO] [rpi3.metrics.example.ovh] acme: Trying to solve DNS-01"
traefik_1           | time="2021-05-21T21:55:29Z" level=debug msg="legolog: [INFO] [rpi3.metrics.example.ovh] acme: Checking DNS record propagation using [127.0.0.11:53]"
traefik_1           | time="2021-05-21T21:55:31Z" level=debug msg="legolog: [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]"
traefik_1           | time="2021-05-21T21:55:31Z" level=debug msg="legolog: [INFO] [rpi3.metrics.example.ovh] acme: Waiting for DNS record propagation."```
