### ISSUE TITLE
dashboard main.js not found 404

### ISSUE THREAD

**Issue by Casper-Mars** [traefik/traefik#8151]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

deploy to k8s. And then tried to open dashbord. But some js can not find with status code 404.

### What did you expect to see?

dashboard work.

### What did you see instead?

Nothing. An empty page.

Here is the info from Chrome
```
Request URL: http://traefik.zhisheng.com/dashboard/main.00dd2e9293e5589a155c.bundle.js
Request Method: GET
Status Code: 404 Not Found
```

But I build locally from the source code and run it. The dashboard is working fine.

### Output of `traefik version`: (_What version of Traefik are you using?_)

I have tried image v2.4、v2.4.8 and v2.3.7. All get the same problem.

```
Version:      2.3.7
Codename:     picodon
Go version:   go1.15.6
Built:        2021-01-11T18:03:02Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

dp.yaml
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: traefik-ingress-controller

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  namespace: kube-system
  name: traefik
  labels:
    app: traefik

spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: harbor.zhisheng.com:5000/public/traefik:v2.3.7
          args:
            - --log.level=INFO
            - --api.insecure=true
            - --api=true
            - --api.dashboard=true
            - --ping=true
            - --accesslog
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --providers.kubernetescrd
          ports:
            - name: web
              containerPort: 80
              hostPort: 81
            - name: websecure
              containerPort: 443
            - name: admin
              containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              drop:
              - ALL
              add:
              - NET_BIND_SERVICE
```

dashboard.yaml
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: kube-system
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`traefik.zhisheng.com`)
    kind: Rule
    services:
    - name: traefik
      port: 8080
```

svc.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: admin
      port: 8080
    - protocol: TCP
      name: websecure
      port: 443
  selector:
    app: traefik
```

and the `IngressRoute Definition` is just same as the [document](https://doc.traefik.io/traefik/user-guides/crd-acme/#ingressroute-definition)
