### ISSUE TITLE
file watch update does not update on dynamic configuration

### ISSUE THREAD

**Issue by dev852com** [traefik/traefik#8155]
### Do you want to request a *feature* or report a *bug*?
bug

Bug

### What did you do?

replace lxc nginx reverse proxy to lxc docker traefik
enabled provider file to route to lxc containers
enabled file provider file watch true
mounted /etc/traefik/:/etc/traefik (routes.yaml)

### What did you expect to see?

live editing on /etc/traefik/routes.yaml to update routers, services and middlewares and not require to restart traefik on every update

### What did you see instead?

Does not push update to traefik and requires container restart on every update

2.3

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

traefik docker-compose file:

```
version: '3.3'
services:
  traefik:
    image: traefik:v2.3
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.enable=true
      - traefik.swarmmode=false
      - traefik.docker.network=traefik-public
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.traefik-public-http.rule=Host(`traefik.example.com`)
      - traefik.http.routers.traefik-public-http.entrypoints=http
      - traefik.http.routers.traefik-public-http.middlewares=https-redirect
      - traefik.http.routers.traefik-public-https.rule=Host(`traefik.example.com`)
      - traefik.http.routers.traefik-public-https.entrypoints=https
      - traefik.http.routers.traefik-public-https.tls=true
      - traefik.http.routers.traefik-public-https.service=api@internal
      - traefik.http.routers.traefik-public-https.tls.certresolver=le
      - traefik.http.services.traefik-public.loadbalancer.server.port=8080
      - traefik.http.routers.traefik-public-https.middlewares=authelia
      - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.example.com/
      - traefik.http.middlewares.authelia.forwardauth.trustforwardheader=true
      - traefik.http.middlewares.authelia.forwardauth.authresponseheaders=X-Forwarded-User
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates
      - /var/log/traefik:/var/log/traefik
      - /etc/traefik/:/etc/traefik
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.file=true
      - --providers.file.watch=true
      - --providers.file.filename=/etc/traefik/routes.yaml
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=hello@example.com
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog=true
      - --accesslog.filepath=/var/log/traefik/access.log
      - --log
      - --api
    networks:
      - traefik-public
 
volumes:
  traefik-public-certificates:
 
networks:
  traefik-public:
    external: true
```

providers.file:

```
http:
  routers:
    wordpress-http:
      entryPoints:
      - http
      middlewares:
      - https-redirect
      rule: "Host(`example.com`)"
      service: wordpress
    wordpress-https:
      entryPoints:
      - https
      middlewares:
      - security-headers
      rule: "Host(`example.com`)"
      service: wordpress
      tls:
        certResolver: le

services:
    wordpress:
      loadBalancer:
        servers:
          - url: "http://microk8s.lxd:32001"

security-headers:
      headers:
        forceSTSHeader: true
        stsPreload: true
        stsSeconds: 2592000
        stsIncludeSubdomains: true
        contentTypeNosniff: true
        contentSecurityPolicy: script-src 'self' 'unsafe-inline' 'unsafe-eval' *.google.com maps.gstatic.com *.googleapis.com *.google-analytics.com *.googletagmanager.com *.gstatic.com *.googlesyndication.com *.facebook.com *.facebook.net *.google.com.hk *.googletagservices.com *.googleadservices.com
        frameDeny: true
        browserXssFilter: true
        referrerPolicy: same-origin
        customResponseHeaders: 
          permissions-policy: geolocation=(self "https://example.com"), microphone=()
```
### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
