### ISSUE TITLE
Impossible to reach a service with a weight of zero and a sticky cookie

### ISSUE THREAD

**Issue by ralmn** [traefik/traefik#8157]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

As part of the migration of some legacy applications to kubernetes we needed to reproduce the principle of parallel deployment of tomcat. This consists in having several versions of the same application at the same time with a sticky cookie that allows users not to change version during their sessions.

We have reproduced this operation with the weighted round robin. For this we declare a TraefikService with several services. Only the current version (the one accessible by default) has a weight of 1, the others have a weight of 0.

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  labels:
    published: "true"
  name: mutli-ver-test
  namespace: appli
spec:
  weighted:
    services:
    - name: mutli-ver-test-1-0-0
      port: 80
      weight: 0
    - name: mutli-ver-test-2-0-0
      port: 80
      weight: 1
    sticky:
      cookie:
        name: mutli-ver-test
```

### What did you expect to see?

In the previous example, we expect that if we don't have a version cookie, we'll access to the version "2.0.0" (service `mutli-ver-test-2-0-0`) (service `mutli-ver-test-2-0-0`). If the cookie exists we go to the instance specified by the cookie. 

Examples:
 * with the cookie `multi-ver-test=mutli-ver-test-1-0-0-80` we expect to join the version "1.0.0" (service: `mutli-ver-test-1-0-0`)
 * with the cookie `multi-ver-test=mutli-ver-test-2-0-0-80` we expect to join the version "2.0.0" (service: `mutli-ver-test-2-0-0`)
 * with the cookie `multi-ver-test=mutli-ver-test-0-1-0-80` as there is no version "0.1.0" we expect to reach the service `mutli-ver-test-2-0-0`.

### What did you see instead?

With version 2.1.9 and above we have no problem.  The behavior is as expected.
Since version 2.2.0:
  * with the cookie `multi-ver-test=mutli-ver-test-1-0-0-80` we join the `mutli-ver-test-2-0-0` service and not the `mutli-ver-test-1-0-0`

After investigations we think that the regression was introduced by the commit: https://github.com/traefik/traefik/commit/98f304f8b0e6e89aee51d7d27a950dcf024ac4d0

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.14-mirantis-1", GitCommit:"660c71e756db6b40ac9a82daf16a39fbd3010035", GitTreeState:"clean", BuildDate:"2021-01-12T10:25:04Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```

```toml
[accessLog]
format = "json"

[entryPoints]
 [entryPoints.metrics]
 address = ":8082"

 [entryPoints.http]
 address = ":80"
 [entryPoints.http.http]
 middlewares=["defaultErrors@file"]
 [entryPoints.http.transport.lifeCycle]
  requestAcceptGraceTimeout = "15s"
  graceTimeOut = "30s"

 [entryPoints.https]
 address = ":443"
 [entryPoints.https.http]
 middlewares=["defaultErrors@file"]
 [entryPoints.https.http.tls]
 [entryPoint.https.transport.lifeCycle]
  requestAcceptGraceTimeout = "15s"
  graceTimeOut = "30s"


 [entryPoints.openvpn]
 address = ":26880"
 [entryPoints.openvpn.http]
 middlewares=["defaultErrors@file"]
 [entryPoints.openvpn.http.tls]
 [entryPoint.openvpn.transport.lifeCycle]
  requestAcceptGraceTimeout = "15s"
  graceTimeOut = "30s"

[entryPoints.tcpssl]
 address = ":26843"

# Publication du dashboard
[api]
 dashboard = true
 insecure = true

# Activation de l'URL de ping
[ping]
entrypoint = "http"

[metrics]
  [metrics.prometheus]
  entryPoint = "metrics"

# Configuration Docker Kubernetes
[providers.kubernetesCRD]
  labelselector = "published=true"

[providers.file]
  directory = "/.sen/datas/config/traefik/"
  filename = "dynamic-traefik.toml"
  watch = true
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: "multi-ver-test-1-0-0"
  namespace: "appli"
  labels:
    app: "multi"
    env: "test"
    component: "ver"
    app-cmp: multi-ver
    release: "multi-ver-test"
    published: "true"
    version: "1.0.0"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: "multi"
    env: "test"
    component: "ver"
    app-cmp: multi-ver
    release: "multi-ver-test"
    published: "true"
    version: "1.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: "multi-ver-test-2-0-0"
  namespace: "appli"
  labels:
    app: "multi"
    env: "test"
    component: "ver"
    app-cmp: multi-ver
    release: "multi-ver-test"
    published: "true"
    version: "2.0.0"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: "multi"
    env: "test"
    component: "ver"
    app-cmp: multi-ver
    release: "multi-ver-test"
    published: "true"
    version: "2.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: multi-ver-test
  namespace: "appli"
  labels:
    app: "multi"
    env: "test"
    component: "ver"
    app-cmp: multi-ver
    release: "multi-ver-test"
    published: "true"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: "multi"
    env: "test"
    component: "ver"
    app-cmp: multi-ver
    release: "multi-ver-test"
    published: "true"
    version: "2.0.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "multi-ver-test-1-0-0"
  namespace: "appli"
  labels:
    app: "multi"
    env: "test"
    component: "ver"
    app-cmp: multi-ver
    release: "multi-ver-test"
    published: "true"
    version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "multi"
      env: "test"
      component: "ver"
      app-cmp: multi-ver
      release: "multi-ver-test"
      published: "true"
      version: "1.0.0"
  template:
    metadata:
      labels:
        app: "multi"
        env: "test"
        component: "ver"
        app-cmp: multi-ver
        release: "multi-ver-test"
        published: "true"
        version: "1.0.0"
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
        - name: "ver"
          image: containous/whoami
          imagePullPolicy: Always
          env:
            - name: VERSION
              value: 1.0.0
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests: #default value
              cpu: 100m
              memory: 400M
            limits: #default value
              cpu: 500m
              memory: 2G
      imagePullSecrets:
        - name: "dtr-prod"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "multi-ver-test-2-0-0"
  namespace: "appli"
  labels:
    app: "multi"
    env: "test"
    component: "ver"
    app-cmp: multi-ver
    release: "multi-ver-test"
    published: "true"
    version: "2.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "multi"
      env: "test"
      component: "ver"
      app-cmp: multi-ver
      release: "multi-ver-test"
      published: "true"
      version: "2.0.0"
  template:
    metadata:
      labels:
        app: "multi"
        env: "test"
        component: "ver"
        app-cmp: multi-ver
        release: "multi-ver-test"
        published: "true"
        version: "2.0.0"
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
        - name: "ver"
          image: containous/whoami
          imagePullPolicy: Always
          env:
            - name: VERSION
              value: 2.0.0
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests: #default value
              cpu: 100m
              memory: 400M
            limits: #default value
              cpu: 500m
              memory: 2G
      imagePullSecrets:
        - name: "dtr-prod"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "multi-ver-test"
  namespace: "appli"
  labels:
    app: "multi"
    component: "ver"
    app-cmp: multi-ver
    release: "multi-ver-test"
    published: "true"
spec:
  entryPoints:
    - https
    - http
  routes:
  - match: "Host(`multiversion.apps-test.domain.fr`)"
    kind: Rule
    namespace: "appli"
    services:
      - name: "multi-ver-test"
        kind: TraefikService
        namespace: "appli"
---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: multi-ver-test
  namespace: "appli"
  labels:
    published: "true"
spec:
  weighted:
    sticky:
      cookie: 
        name: multi-ver-test
    services:
      - name: "multi-ver-test-1-0-0"
        weight: 0
        port: 80
      - name: "multi-ver-test-2-0-0"
        weight: 1
        port: 80

```
