### ISSUE TITLE
Docker labels in traefik 1.7.26 and 2.4.8 interfere with each other

### ISSUE THREAD

**Issue by AndreasKl** [traefik/traefik#8159]
### What did you do?

While migrating from traefik 1.7 to 2.4 I tried to run both versions in the same docker stack, as afaics the used labels should not interfere. However in an edge case traefik 1.7 picks up the traefik 2.x annotations and fails adding the frontend.

```yml
  echo2:
    image: brndnmtthws/nginx-echo-headers
    labels:
      traefik.enable: "true"
      traefik2.enable: "true"

      traefik.echo1.frontend.rule: "PathPrefix:/foo" <-- We OR different rules
      traefik.echo2.frontend.rule: "Host:somehost.io"

      traefik.http.services.echo1.loadbalancer.server.port: "80"
      # traefik.http.services.echo2.loadbalancer.server.frontend.rule: "PathPrefix:/hmmm"

      traefik.http.routers.echo1.service: echo1
      traefik.http.routers.echo1.rule: "PathPrefix(`/foobar`)"
```

### What did you expect to see?
The traefik 2 labels are ignored.

### What did you see instead?
The traefik 2 labels are somewhat interpreted and the traefik 1 config is not applied.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yml
  traefik:
    image: traefik:1.7.26-alpine
    command: |
      --entrypoints="Name:http Address::82"
      --defaultentrypoints="http"
      --docker
      --docker.endpoint="unix:///var/run/docker.sock"
      --docker.exposedbydefault=false
      --docker.watch
      --api
      --ping
      --logLevel=DEBUG
    ports:
      - 82:82
      - 8180:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"

  traefik2:
    image: traefik:2.4
    command:
      - --entrypoints.web.address=:80

      - --providers.docker
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.watch
      - --providers.docker.constraints=Label(`traefik2.enable`,`true`)

      - --api
      - --api.dashboard
      - --api.insecure=true
      - --ping
      
      - --log.level=DEBUG
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
```
time="2021-05-27T11:51:30Z" level=debug msg="originLabelsmap[com.docker.stack.namespace:echo com.docker.swarm.node.id:yzm7zj5lcuadb4lca96mw2ycx com.docker.swarm.service.id:r8xd2fzl38s1kgpa5h9to8sn0 com.docker.swarm.service.name:echo_echo2 com.docker.swarm.task: com.docker.swarm.task.id:amwch0xybw5dtv4kcayguaa3y com.docker.swarm.task.name:echo_echo2.1.amwch0xybw5dtv4kcayguaa3y traefik.echo1.frontend.rule:PathPrefix:/foo traefik.echo2.frontend.rule:PathPrefix:/bar traefik.enable:true traefik.http.routers.echo1.rule:PathPrefix(`/foobar`) traefik.http.routers.echo1.service:echo1 traefik.http.services.echo1.loadbalancer.server.port:80 traefik2.enable:true]"

time="2021-05-27T11:51:30Z" level=debug msg="allLabelsmap[:map[traefik.enable:true traefik.http.routers.echo1.rule:PathPrefix(`/foobar`) traefik.http.routers.echo1.service:echo1] echo1:map[traefik.frontend.rule:PathPrefix:/foo] echo2:map[traefik.frontend.rule:PathPrefix:/bar] http.services.echo1.loadbalancer.server:map[traefik.port:80]]"

time="2021-05-27T11:51:30Z" level=debug msg="Filtering container with empty frontend rule /echo_echo2.1.amwch0xybw5dtv4kcayguaa3y http.services.echo1.loadbalancer.server"
```
