### ISSUE TITLE
Unable to obtain ACME wildcard certificate - regru

### ISSUE THREAD

**Issue by ilyapavkin** [traefik/traefik#8165]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Setup Traefik 2 to obtain wildcard certificate from regru, following https://doc.traefik.io/traefik/user-guides/docker-compose/acme-dns/ with addition of labels (see below)

### What did you expect to see?

Certificate obtained.
Standalone goacme/lego client does it successfully.

### What did you see instead?

acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Incorrect TXT record

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
version: "3.3"

services:

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - 'REGRU_USERNAME=xxxxx'
      - 'REGRU_PASSWORD=xxxxx'
      - 'REGRU_PROPAGATION_TIMEOUT=7200'
      - 'REGRU_POLLING_INTERVAL=30'
    command:
      - '--log.level=DEBUG'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--providers.docker'
      - '--api'
      - '--certificatesresolvers.regru.acme.email=xxxx'
      - '--certificatesresolvers.regru.acme.dnschallenge=true'
      - '--certificatesresolvers.regru.acme.dnschallenge.provider=regru'
      - '--certificatesresolvers.regru.acme.storage=/letsencrypt/acme.json'
      - '--certificatesresolvers.regru.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory'
    volumes:
      - "/var/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      # global redirect to https
      - 'traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)'
      - 'traefik.http.routers.http-catchall.entrypoints=web'
      - 'traefik.http.routers.http-catchall.middlewares=redirect-to-https'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'

      # global wildcard certificates
      - 'traefik.http.routers.wildcard-certs.tls.certresolver=regru'
      - 'traefik.http.routers.wildcard-certs.tls.domains[0].main=example.com'
      - 'traefik.http.routers.wildcard-certs.tls.domains[0].sans=*.example.com'

      # dashboard
      - 'traefik.http.routers.traefik.rule=Host(`ctl.example.com`)'
      - 'traefik.http.routers.traefik.tls=true'
      - 'traefik.http.routers.traefik.entrypoints=websecure'
      - 'traefik.http.routers.traefik.service=api@internal'
      - 'traefik.http.routers.traefik.middlewares=authtraefik'
      - 'traefik.http.middlewares.authtraefik.basicauth.users=admin:$apr1$VBdwGiao$kOPg3zsYuS8VCzb06QB9v0'
    networks:
      - web

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.example.com`)"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
    networks:
      - web
networks:
  web:
    external: true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```

time="2021-05-31T23:07:22Z" level=debug msg="legolog: [INFO] acme: Registering account for xxxx"
time="2021-05-31T23:07:23Z" level=debug msg="legolog: [INFO] [example.com, *.example.com] acme: Obtaining bundled SAN certificate"
time="2021-05-31T23:07:24Z" level=debug msg="legolog: [INFO] [*.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/59765274"
time="2021-05-31T23:07:24Z" level=debug msg="legolog: [INFO] [example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/59765275"
time="2021-05-31T23:07:24Z" level=debug msg="legolog: [INFO] [*.example.com] acme: use dns-01 solver"
time="2021-05-31T23:07:24Z" level=debug msg="legolog: [INFO] [example.com] acme: Could not find solver for: tls-alpn-01"
time="2021-05-31T23:07:24Z" level=debug msg="legolog: [INFO] [example.com] acme: Could not find solver for: http-01"
time="2021-05-31T23:07:24Z" level=debug msg="legolog: [INFO] [example.com] acme: use dns-01 solver"
time="2021-05-31T23:07:24Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Preparing to solve DNS-01"
time="2021-05-31T23:07:25Z" level=debug msg="legolog: [INFO] [example.com] acme: Preparing to solve DNS-01"
time="2021-05-31T23:07:25Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Trying to solve DNS-01"
time="2021-05-31T23:07:25Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Checking DNS record propagation using [127.0.0.11:53]"
time="2021-05-31T23:07:55Z" level=debug msg="legolog: [INFO] Wait for propagation [timeout: 2h0m0s, interval: 30s]"
time="2021-05-31T23:07:55Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Waiting for DNS record propagation."
time="2021-05-31T23:08:25Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Waiting for DNS record propagation."
time="2021-05-31T23:08:55Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Waiting for DNS record propagation."
time="2021-05-31T23:09:31Z" level=debug msg="legolog: [INFO] [example.com] acme: Trying to solve DNS-01"
time="2021-05-31T23:09:31Z" level=debug msg="legolog: [INFO] [example.com] acme: Checking DNS record propagation using [127.0.0.11:53]"
time="2021-05-31T23:10:01Z" level=debug msg="legolog: [INFO] Wait for propagation [timeout: 2h0m0s, interval: 30s]"
time="2021-05-31T23:10:01Z" level=debug msg="legolog: [INFO] [example.com] acme: Waiting for DNS record propagation."
time="2021-05-31T23:10:31Z" level=debug msg="legolog: [INFO] [example.com] acme: Waiting for DNS record propagation."
time="2021-05-31T23:11:09Z" level=debug msg="legolog: [INFO] [*.example.com] acme: Cleaning DNS-01 challenge"
time="2021-05-31T23:11:09Z" level=debug msg="legolog: [INFO] [example.com] acme: Cleaning DNS-01 challenge"
time="2021-05-31T23:11:10Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/59765274"
time="2021-05-31T23:11:10Z" level=debug msg="legolog: [INFO] Unable to deactivate the authorization: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/59765274"
time="2021-05-31T23:11:10Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/59765275"
time="2021-05-31T23:11:10Z" level=debug msg="legolog: [INFO] Unable to deactivate the authorization: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/59765275"
time="2021-05-31T23:11:10Z" level=error msg="Unable to obtain ACME certificate for domains \"example.com,*.example.com\" : unable to generate a certificate for the domains [example.com *.example.com]: error: one or more domains had a problem:\n[*.example.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Incorrect TXT record \"iGtIe5q8eXDU5mQKq0_aDn9UExIg0uMTZVZmjjsJFBc\" (and 1 more) found at _acme-challenge.example.com\n[example.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Incorrect TXT record \"iGtIe5q8eXDU5mQKq0_aDn9UExIg0uMTZVZmjjsJFBc\" (and 1 more) found at _acme-challenge.example.com\n" providerName=regru.acme
```
