### ISSUE TITLE
more specific non-wildcard domain doesn't override wildcard domain

### ISSUE THREAD

**Issue by candlerb** [traefik/traefik#8166]
### Do you want to request a *feature* or report a *bug*?

Bug I think - although the [k8s ingress spec](https://kubernetes.io/docs/concepts/services-networking/ingress/#hostname-wildcards) isn't clear whether a precise match overrides a wildcard match.

### What did you do?

* Create a namespace
* Deploy a kubernetes ingress+service+deployment that matches `*.example.com`
* Deploy a second ingress+service+deployment that matches `bar.example.com`

### What did you expect to see?

Requests for `foo.example.com` hit the first ingress, but `bar.example.com` hits the second ingress.

### What did you see instead?

Requests for both `foo.example.com` and `bar.example.com` are routed to the first ingress/service.

### Output of `traefik version`: (_What version of Traefik are you using?_)

This is the version of traefik bundled with k3s, which appears to be v1.7.19.

```
$ k3s --version
k3s version v1.20.6+k3s1 (8d043282)
go version go1.15.10

$ sudo kubectl describe pod traefik-6f9cbd9bd4-rlngf -n kube-system
...
Containers:
  traefik:
    Container ID:  containerd://04262071901fa00f5e7d3505a728f323bdd76b57a81e74630ad2ec4b620a1834
    Image:         rancher/library-traefik:1.7.19
    Image ID:      docker.io/rancher/library-traefik@sha256:3ba3ed48c4632f2b02671923950b30b5b7f1b556e559ce15446d1f5d648a037d
...
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

k3s under Ubuntu 18.04 (amd64).  To reproduce, apply these resources in order:

traefik0.yaml

```
apiVersion: v1
kind: Namespace
metadata:
  name: test123
  labels:
    name: test123
```

traefik1.yaml

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wild-ingress
  namespace: test123
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: "*.example.com"
      http:
        paths:
          - backend:
              service:
                name: wild-service
                port:
                  number: 8000
            path: /
            pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: wild-service
  namespace: test123
  labels:
    app: wild
spec:
  selector:
    app: wild
  ports:
    - port: 8000
      name: wild
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wild
  namespace: test123
spec:
  selector:
    matchLabels:
      app: wild
  replicas: 1
  template:
    metadata:
      labels:
        app: wild
    spec:
      shareProcessNamespace: true
      containers:
        - name: wild
          image: python:3.9-buster
          command: ["python3", "-m", "http.server", "-d", "/usr"]
          ports:
            - containerPort: 8000
              name: wild
```

traefik2.yaml

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: single-ingress
  namespace: test123
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: "bar.example.com"
      http:
        paths:
          - backend:
              service:
                name: single-service
                port:
                  number: 8000
            path: /
            pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: single-service
  namespace: test123
  labels:
    app: single
spec:
  selector:
    app: single
  ports:
    - port: 8000
      name: single
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: single
  namespace: test123
spec:
  selector:
    matchLabels:
      app: single
  replicas: 1
  template:
    metadata:
      labels:
        app: single
    spec:
      shareProcessNamespace: true
      containers:
        - name: single
          image: python:3.9-buster
          command: ["python3", "-m", "http.server", "-d", "/var"]
          ports:
            - containerPort: 8000
              name: single
```

(The first service lists contents of `/usr` directory, and the second `/var` directory)

Then hit them, either using `/etc/hosts` or `curl --resolve`.  For example, if the node external IP is 10.12.253.4, then:

```
curl http://foo.example.com/ --resolve foo.example.com:80:10.12.253.4
curl http://bar.example.com/ --resolve bar.example.com:80:10.12.253.4
```

Note that `kubectl describe ingress` doesn't show any problem with the second ingress.

```
# kubectl describe ingress wild-ingress -n test123
Name:             wild-ingress
Namespace:        test123
Address:          10.12.253.4
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host           Path  Backends
  ----           ----  --------
  *.example.com
                 /   wild-service:8000 (10.42.0.24:8000)
Annotations:     kubernetes.io/ingress.class: traefik
Events:          <none>

# kubectl describe ingress single-ingress -n test123
Name:             single-ingress
Namespace:        test123
Address:          10.12.253.4
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host             Path  Backends
  ----             ----  --------
  bar.example.com
                   /   single-service:8000 (10.42.0.25:8000)
Annotations:       kubernetes.io/ingress.class: traefik
Events:            <none>
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

N/A

**Comment by rtribotte** [comment]
Hello @candlerb,

Thanks for your interest in Traefik!

You are experiencing a correct behavior because the first ingress can indeed handle the two request.

Thus, technically the explanation is that Traefik internally evaluates routers that have longer rules length by descending order.
While a domain without wildcard will produce a rule like ```Host(`foo.bar`)```, a wildcard domain would produce a rule like ```HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.bar`)```.
So that the `HostRegexp` is evaluated first, and matches both requests.

To control the priority during routers evaluation, you have to fix it explicitly, with the ingress provider through [router's annotations](https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/#on-ingress)

**Comment by candlerb** [comment]
Many thanks for the reply.

Does this feature require a newer traefik than v1.7.19?  Setting a high priority (e.g. 1000) on the more specific route using an annotation doesn't appear to make any difference.

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: single-ingress
  namespace: test123
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.priority: "1000"
spec:
  rules:
    - host: "bar.example.com"
      http:
        paths:
          - backend:
              service:
                name: single-service
                port:
                  number: 8000
            path: /
            pathType: Prefix
```

I've also tried setting 10 on the first and 20 on the second: still the first rule wins.

```
# kubectl describe ingress wild-ingress -n test123
Name:             wild-ingress
Namespace:        test123
Address:          10.12.253.4
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host           Path  Backends
  ----           ----  --------
  *.example.com
                 /   wild-service:8000 (10.42.0.29:8000)
Annotations:     kubernetes.io/ingress.class: traefik
                 traefik.ingress.kubernetes.io/router.priority: 10
Events:          <none>

# kubectl describe ingress single-ingress -n test123
Name:             single-ingress
Namespace:        test123
Address:          10.12.253.4
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host             Path  Backends
  ----             ----  --------
  bar.example.com
                   /   single-service:8000 (10.42.0.28:8000)
Annotations:       kubernetes.io/ingress.class: traefik
                   traefik.ingress.kubernetes.io/router.priority: 20
Events:            <none>
```

If I `kubectl delete -f` the first set, then the second starts working.  As soon as I re-apply the first set, it takes over the traffic for `bar.example.com`

However, the annotation `traefik.ingress.kubernetes.io/redirect-entry-point: https` *does* work, as described [here](https://doc.traefik.io/traefik/v1.7/configuration/backends/kubernetes/).
