### ISSUE TITLE
Problems with internal Exchange behind traefik - looking for tcp-timeout settings

### ISSUE THREAD

**Issue by Crofex** [traefik/traefik#8172]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

We have an internal Exchange Server behind traefik.
We have lots of Errors in our traefik log. 

```
reverse-proxy_1  | time="2021-06-04T12:57:43+02:00" level=error msg="Error during connection: read tcp 172.30.0.2:56734->172.X.X.X:443: read: connection reset by peer"
reverse-proxy_1  | time="2021-06-04T12:57:43+02:00" level=error msg="Error during connection: read tcp 172.30.0.2:56196->172.X.X.X:443: read: connection reset by peer"
reverse-proxy_1  | time="2021-06-04T12:57:43+02:00" level=debug msg="Error while terminating connection: close tcp 172.30.0.2:56196->172.X.X.X:443: shutdown: transport endpoint is not connected"
reverse-proxy_1  | time="2021-06-04T12:57:43+02:00" level=debug msg="Error while terminating connection: close tcp 172.30.0.2:56734->172.X.X.X:443: shutdown: transport endpoint is not connected"
```

We have many Users complaining about poor Outlook / Exchange Performance

While following this Guide (https://techcommunity.microsoft.com/t5/exchange-team-blog/checklist-for-troubleshooting-performance-related-issues-in/ba-p/604792) we stumbled across the Load Balance Section where they are talking about keep alives and TCP idle Timeouts.

```
Firewall time out = 40 minutes
LB TCP Idle time out = 35 minutes
Exchange Keep Alive = 30 minutes
```

Or even to a feature called "least connections".

I´ve googled a lot to come over to this settings in traefik but can´t find any.

Could you please help? Ist this a Bug or a Feature Request?
Its my first risen Issue so pls be kind.

I´ve also opened an entry in traefik-community: https://community.traefik.io/t/traefik-as-reverse-proxy-for-internal-exchange/10798
### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Feel free to request more if needed.
File-Provider
```yaml 
# tcp:
  routers:
    https.activesync.DOMAIN.de:
      rule: HostSNI(`activesync.DOMAIN.de`)
      entryPoints:
        - websecure
      service: activesync.DOMAIN.de
      tls:
       passthrough: true

  services:
    activesync.DOMAIN.de:
      loadBalancer:
        servers:
          - address: 172.X.X.X:443

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
