### ISSUE TITLE
TLSStores & TLSOptions use the label selector

### ISSUE THREAD

**Issue by tcolgate** [traefik/traefik#8173]
### Do you want to request a *feature* or report a *bug*?

Bug  (maybe)

### What did you do?

Using the kubernetescrd and kubernetesingress providers.
I need to run two instances of traefik that will handle ingresses separated by labels.
I want to use a default TLS config common to both using in cluster secrets (via TLSStore and TLSOptions)

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: default
  namespace: infra
spec:
  minVersion: VersionTLS12
  cipherSuites:
  - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
  - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
  - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
  - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
  - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
  - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
  - "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
  - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
```

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: infra
spec:
  defaultCertificate:
    secretName: wildcards-tls
```
The code lists both stores and options from all namespaces, and RBAC permits that. Note that there are no labes.

my config.toml:
```toml
defaultEntryPoints = []
[entryPoints]
  [entryPoints.https-auth-tls]
  address = ":8884"
  [entryPoints.https-auth-tls.http.tls]

[providers.kubernetescrd]
endpoint = "http://localhost:8001"
allowcrossnamespace = true
ingressclass  = "traefik"
labelselector = "externalAccess in (private)"

[providers.kubernetesingress]
endpoint = "http://localhost:8001"
ingressclass  = "traefik"
labelselector = "externalAccess in (private)"

[log]
level = "debug"
```

### What did you expect to see?

I expect all discovered ingresses (that match the private label) to use the default certificate and options.

### What did you see instead?

Traefik discovers the ingresses, but uses an self signed cert and default options.

If I snoop the kube api requests I can see that traefik is requesting tlsoptions and tlsstores using the label selector:
```
GET /apis/traefik.containo.us/v1alpha1/tlsstores?labelSelector=externalAccess+in+%28private%29&limit=500&resourceVersion=0 HTTP/1.1\r\n
```

If I comment out the label selector, traefik discovers my options and stores, but this means the selector must match the stores/options and the ingresses/crd-resources, but that precludes mutually exlusive sets of ingresses.

Two workarounds exist (I think):
- have a 2 tlsstore and tlsoptions objects, in different namespaces, which match diffferent label queries.
- use two different ingress classes, and drop the use of labels.

The docs don't mention that stores/options have to match the label selectors, and it's not really obvious that the default ones should.

### Output of `traefik version`: 
```
Version:      2bbb6fc427cbc8354f15405ffa5715738b5cfabf
Codename:     cheddar
Go version:   go1.16
Built:        2021-06-04_01:11:35pm
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = []
[entryPoints]
  [entryPoints.https-auth-tls]
  address = ":8884"
  [entryPoints.https-auth-tls.http.tls]

[providers.kubernetescrd]
endpoint = "http://localhost:8001"
allowcrossnamespace = true
ingressclass  = "traefik"
labelselector = "externalAccess in (private)"

[providers.kubernetesingress]
endpoint = "http://localhost:8001"
ingressclass  = "traefik"
labelselector = "externalAccess in (private)"

[log]
level = "debug"```

```
