### ISSUE TITLE
Significant performance drop when compression is enabled

### ISSUE THREAD

**Issue by StarpTech** [traefik/traefik#8175]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

Enabled https and compression on a single route.

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: compress
spec:
  compress: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: foo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`foo.de`)
      kind: Rule
      services:
        - name: foo
          port: 5002
      middlewares:
        - name: compress
```

Compressing a 1.1 MB javascript costs around ~1.5 seconds. Disabling compression reduces the time to ~300ms.

### What did you expect to see?

Traefik should utilize all reserved cpu resources and compress without significant performance lose.

### What did you see instead?

Traefik compresses very slow. I'd say it's unusable for serious web performance.

### Output of `traefik version`: (_What version of Traefik are you using?_)

2.4.7

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Kubernetes, Release in default settings with https://github.com/traefik/traefik-helm-chart
