### ISSUE TITLE
wrong period type in Middleware ressource on Kubernetes for rate limit

### ISSUE THREAD

**Issue by saphoooo** [traefik/traefik#8177]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

When creating a Middleware for rate limit with a period, the type of the period is int but the documentation point that is a duration:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-ratelimit
spec:
  plugin:
    rateLimit:
      average: 5
      period: 1m // <-- following the documentation, it's the right type 1m or "1m" for 1 minute
```

### What did you expect to see?

A rate limit middleware configured for 5reqs/min

### What did you see instead?

```
time="2021-06-08T08:32:36Z" level=error msg="unable to decode plugin config: plugin: failed to decode configuration: 1 error(s) decoding:\n\n* cannot parse 'Period' as int: strconv.ParseInt: parsing \"1m\": invalid syntax" entryPointName=web routerName=default-test-c334c465aef00b56b79a@kubernetescrd
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
$ teectl version
Client:
Version:      v2.4.4
Codename:     Ventoux-Blanc
Go version:   go1.15.10
Built:        2021-03-29_07:46:06AM
OS/Arch:      darwin/amd64

Server:
Version:      v2.4.4
Codename:     Ventoux-Blanc
Go version:   go1.15.10
Built:        2021-03-29_07:46:06AM
OS/Arch:      darwin/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-ratelimit
spec:
  plugin:
    rateLimit:
      average: 5
      period: 1m // <-- following the documentation, it's the right type 1m or "1m" for 1 minute
```

```yaml
---
providers:
  kubernetesCRD: {}

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

mesh: {}

metrics:
  prometheus:
    addEntryPointsLabels: true
```
