### ISSUE TITLE
ns1 acme API calls using root tld (not root domain)

### ISSUE THREAD

**Issue by JakeDEvans** [traefik/traefik#8181]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
configure acme certs to issue via dns w/ ns1 provider

### What did you expect to see?
txt dns record created on ns1

### What did you see instead?
```
acme: error presenting token: ns1: failed to get zone [authZone: \"net\", fqdn: \"_acme-challenge.example.net.\"]: GET https://api.nsone.net/v1/zones/net: 400 \"net\" not a valid zone\n[example.net] [example.net] acme: error presenting token: ns1: failed to get zone [authZone: \"net\", fqdn: \"_acme-challenge.example.net.\"]: GET https://api.nsone.net/v1/zones/net: 400 \"net\" not a valid zone\n" providerName=myresolver.acme
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
sudo docker run traefik:v2.4 version
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
  traefik:
    image: traefik:v2.4
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.middlewares.admin-auth.basicauth.users=user:password
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.traefik-public-http.rule=Host(`traefik.example.net`)
        - traefik.http.routers.traefik-public-http.entrypoints=http
        - traefik.http.routers.traefik-public-http.middlewares=https-redirect
        - traefik.http.routers.traefik-public-https.rule=Host(`traefik.example.net`)
        - traefik.http.routers.traefik-public-https.entrypoints=https
        - traefik.http.routers.traefik-public-https.tls=true
        - traefik.http.routers.traefik-public-https.service=api@internal
        - traefik.http.routers.traefik-public-https.tls.certresolver=myresolver
        - traefik.http.routers.traefik-public-https.tls.domains[0].main=example.net
        - traefik.http.routers.traefik-public-https.tls.domains[0].sans=*.example.net
        - traefik.http.routers.traefik-public-https.middlewares=admin-auth
        - traefik.http.services.traefik-public.loadbalancer.server.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_vol:/certificates
    environment:
      - NS1_API_KEY=XXXXXXXXXXX
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmmode
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.myresolver.acme.dnschallenge.provider=ns1
      - --accesslog
      - --log
      - --api
    networks:
      - traefik-public

volumes:
  traefik_vol:
    external: true

networks:
  traefik-public:
    external: true

```
