### ISSUE TITLE
Middleware not created from docker labels with file provider

### ISSUE THREAD

**Issue by malcolm061990** [traefik/traefik#8186]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

This issue is similar #6789 but only similar :)
I run traefik 2.4.8 in docker-compose on Mac.

Here is traefik.yml:
```yaml
api:
  debug: true
  dashboard: true

log:
  level: DEBUG

ping: {}

entryPoints:
  http:
    address: ":8088"
    forwardedHeaders:
      insecure: true
      trustedIPs:
        - "172.18.0.0/16"
        - "10.0.0.0/8"

providers:
  file:
    filename: /etc/traefik/config.yml
    watch: true
```

Here is config.yml:
```yaml
http:
  routers:
    react-app:
      rule: "PathPrefix(`/`)"
      service: react-app
      priority: 1
    flask-app:
      rule: "PathPrefix(`/api/v1`,`/apidocs`,`/flasgger_static`,`/apispec_1.json`)
      || Path(`/api/v1/management/identities/{regex:.*}/workspaces/{regex:.*}/data`)"
      service: flask-app
      priority: 2
    fastapi:
      rule: "PathPrefix(`/api/v1/reports`,
      `/api/v1/hosts/{regex:.*}/{regex:whois|ports}`,
      `/api/v1/management/identities/{regex:.*}/workspaces`,
      `/api/v1/{regex:domains|hosts}/{regex:.*}/stats/{regex2:vulnerabilities|capabilities|device|ioc}`,
      `/api/v1/{regex:domains|hosts}/{regex:.*}/ioc`,
      `/api/v1/domains/{regex:.*}/servers`,
      `/api/v1/management/identities/client/tags`,
      `/api/v1/management/identities/{regex:stats|ioc}`,
      `/api/v1/{regex:.*}-password`,
      `/api/v1/management/identities/{regex:.*}/stats/refresh`,
      `/api/v2`)"
      service: fastapi
      priority: 3
      # middlewares:
      # - redirect-v1-to-v2
      # - redirect-v1-to-v2-http
    ws-app:
      rule: "PathPrefix(`/ws`)"
      service: ws-app
      priority: 4
    documentation:
      rule: "PathPrefix(`/documentation`)"
      service: documentation
      priority: 5
      middlewares:
      - redirect-documentation
    # dashboard:
    #   rule: "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
    #   service: api@internal
    #   priority: 6

  middlewares:
    redirect-v1-to-v2:
      redirectRegex:
        permanent: true
        regex: "^http://(.*)/api/v1/(.*)"
        replacement: "https://${1}/api/v2/${2}"
    redirect-v1-to-v2-http:
      redirectRegex:
        permanent: true
        regex: "/api/v1/(.*)"
        replacement: "/api/v2/${1}"
    redirect-documentation:
      stripPrefix:
        prefixes:
          - "/documentation"

  services:
    react-app:
      loadBalancer:
        servers:
        - url: http://react-app
    flask-app:
      loadBalancer:
        servers:
        - url: http://flask-app:8000
    fastapi:
      loadBalancer:
        servers:
        - url: http://api:8000
    ws-app:
      loadBalancer:
        servers:
        - url: http://ws-app:9000
    documentation:
      loadBalancer:
        servers:
        - url: http://documentation:80
```

Here is docker-compose.yml:
```yaml
version: '3.7'

services:

  edge-router:
    image: edge-router:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--providers.file.filename=/etc/traefik/config.yml"
    ports:
      - 80:8088
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=vulncano"
      - "traefik.http.routers.fastapi.middlewares=redirect-v1-to-v2-test"
      - "traefik.http.middlewares.redirect-v1-to-v2-test.redirectregex.permanent=true"
      - "traefik.http.middlewares.redirect-v1-to-v2-test.redirectregex.regex=/api/v1/(.*)"
      - "traefik.http.middlewares.redirect-v1-to-v2-test.redirectregex.replacement=/api/v2/$${1}"
    healthcheck:
      test: ["CMD", "nc", "localhost", "8088", "-v", "-w", "2"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  default:
    external:
      name: vulncano
```

### What did you expect to see?

I tested both middlewares from fastapi router commenting one and uncommenting another separately. It works perfect.
I want to use `redirect-v1-to-v2` middleware in kubernetes and `redirect-v1-to-v2-http` middleware in docker.
So I am expecting to **have some mechanism to switch between middlewares using env vars or docker labels**. 
I added labels in docker compose but it doesn't work. I checked different variants:
- add new middleware in compose labels and use it
- just use existing label from config.yml file

### What did you see instead?

The middleware from docker labels isn't appeared in dashboard. So I don't get any redirectRegex :(
For example:
`http://localhost/api/v1/management/identities/stats?` must be redirected to `http://localhost/api/v2/management/identities/stats?` **using docker labels** but instead I just get 404 that means that no redirects happened.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64
```
