### ISSUE TITLE
priority not work in diff ingressroute

### ISSUE THREAD

**Issue by sinoon** [traefik/traefik#8191]
### Do you want to request a *feature* or report a *bug*?

I create two IngressRoute with diff level priority.

First with
```yaml
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: >-
        HostRegexp(`*.abc.com`,
        `{subdomain:[a-z0-9]+}.abc.com`)
      priority: 5
      services:
        - name: main-service
          port: 3000
```

And 
```yaml
spec:
  entryPoints: web
  routes:
    kind: Rule
    match: Host(`9mfya.abc.com`)
    middlewares:
      - name: webide-auth
    priority: 100
    services:
      - name: 9mfya-1024
        port: 1024
```

But always target to first(*.abc.com) 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
