### ISSUE TITLE
Server-side redirect

### ISSUE THREAD

**Issue by malcolm061990** [traefik/traefik#8195]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I want to implement server-side redirect as it was in nginx.

/etc/traefik/traefik.yml 
```yaml
api:
  debug: true

log:
  level: DEBUG

ping: {}

entryPoints:
  http:
    address: ":8088"
    forwardedHeaders:
      insecure: true
      trustedIPs:
        - "172.18.0.0/16"
        - "10.0.0.0/8"
    http:
      middlewares:
         - limit@file

providers:
  file:
    filename: /etc/traefik/config.yml
    watch: true
```

/etc/traefik/config.yml 
```
http:
  routers:
    react-app:
      rule: "PathPrefix(`/`)"
      service: react-app
      priority: 1
    flask-app:
      rule: "PathPrefix(`/api/v1`,`/apidocs`,`/flasgger_static`,`/apispec_1.json`)
      || Path(`/api/v1/management/identities/{regex:.*}/workspaces/{regex:.*}/data`)"
      service: flask-app
      priority: 2
    api:
      rule: "PathPrefix(`/api/v1/reports`,
      `/api/v1/hosts/{regex:.*}/{regex:whois|ports}`,
      `/api/v1/management/identities/{regex:.*}/{regex2:recommendation|workspaces|explorations|timeline|typosquatted_domains|breached_accounts|ioc|cases|reference|issues}`)"
      service: api
      priority: 3
      middlewares:
      - redirect-v1-to-v2-https
    ws-app:
      rule: "PathPrefix(`/ws`)"
      service: ws-app
      priority: 4
    documentation:
      rule: "PathPrefix(`/documentation`)"
      service: documentation
      priority: 5
      middlewares:
      - redirect-documentation

  middlewares:
    redirect-v1-to-v2-https:
      redirectRegex:
        permanent: true
        regex: "^http://(.*)/api/v1/(.*)"
        replacement: "https://${1}/api/v2/${2}"
    redirect-v1-to-v2-http:
      redirectRegex:
        permanent: true
        regex: "/api/v1/(.*)"
        replacement: "/api/v2/${1}"
    redirect-documentation:
      stripPrefix:
        prefixes:
          - "/documentation"
    limit:
      buffering:
        maxRequestBodyBytes: 100000000

  services:
    react-app:
      loadBalancer:
        servers:
        - url: http://react-app:80
    flask-app:
      loadBalancer:
        servers:
        - url: http://flask-app:8000
    api:
      loadBalancer:
        servers:
        - url: http://api:8000
    ws-app:
      loadBalancer:
        servers:
        - url: http://ws-app:9000
    documentation:
      loadBalancer:
        servers:
        - url: http://documentation:80
```

In nginx.conf it was:
```
    location ~ ^/api/v1/management/identities/.*/(recommendation|workspaces|explorations|timeline|typosquatted_domains|breached_accounts|ioc|cases|reference|issues).*$ {
        set $upstream_backend_fast_api http://api:8000;
        rewrite ^/api/v1/(.*)$ /api/v2/$1  break;
        keepalive_timeout 0;
        proxy_redirect off;
        proxy_set_header Connection "";
        proxy_set_header HOST $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_buffering off;
        proxy_read_timeout 600s;
        proxy_pass $upstream_backend_fast_api;
    }
```

### What did you expect to see?

I want to see just 200 status code when the request goes to `/api/v1/management/identities/f09c3d66-9733-46e8-a2c5-6cfbfd496e32/workspaces`. It is the nginx behaviour.

### What did you see instead?

I see 301 status code that redirects to the correct path but I don't want to see doubled count of requests:
- the first request goes to `/api/v1/management/identities/f09c3d66-9733-46e8-a2c5-6cfbfd496e32/workspaces`, gets 301 status code
- the second request goes to `/api/v2/management/identities/f09c3d66-9733-46e8-a2c5-6cfbfd496e32/workspaces`

I want traefik to do it internally as nginx does. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64
```
