### ISSUE TITLE
Redirection from port 80 to 443 does not verify the host

### ISSUE THREAD

**Issue by pbromb** [traefik/traefik#8208]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

**Redirection from port 80 to 443 does not verify the host**

```
# curl -L 172.20.11.11 -H "Host: github.com" -I
HTTP/1.1 308 Permanent Redirect
Location: https://github.com/
Date: Tue, 22 Jun 2021 05:59:46 GMT
Content-Length: 18
Content-Type: text/plain; charset=utf-8

HTTP/2 200
server: GitHub.com
date: Tue, 22 Jun 2021 05:59:41 GMT
```

This allows you to gain unauthorized access to internal services that have entries in the internal DNS server

### What did you expect to see?

404 page not found

### What did you see instead?

I accessed an undefined host configuration

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
containers:
        - name: traefik-external
          image: 'traefik:2.4.8'
          args:
            - '--global.checknewversion'
            - '--global.sendanonymoususage'
            - '--entryPoints.traefik.address=:9000/tcp'
            - '--entryPoints.web.address=:8000/tcp'
            - '--entryPoints.websecure.address=:8443/tcp'
            - '--api.dashboard=true'
            - '--ping=true'
            - '--providers.kubernetescrd'
            - '--providers.kubernetesingress'
            - >-
              --providers.kubernetesingress.ingressendpoint.publishedservice=traefik-external/traefik-external
            - '--entrypoints.web.http.redirections.entryPoint.to=:443'
            - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
            - '--log.level=INFO'
            - '--accesslog=true'
            - '--accesslog.fields.defaultmode=keep'
            - '--accesslog.fields.headers.defaultmode=drop'
            - '--metrics.prometheus=true'
            - '--providers.kubernetesingress.ingressclass=traefik-external'
            - '--providers.kubernetescrd.ingressclass=traefik-external'
          ports:
            - name: traefik
              containerPort: 9000
              protocol: TCP
            - name: web
              containerPort: 8000
              protocol: TCP
            - name: websecure
              containerPort: 8443
              protocol: TCP
```
