### ISSUE TITLE
Traefik TLS Kubernetes namespace isolation is broken

### ISSUE THREAD

**Issue by nerzhul** [traefik/traefik#8211]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

We have traefik as ingress controller on our big Kubernetes environments, 3 pods for ~120 ingress objects per cluster.

In some cases, we have Ingress for domain a.staging.example.org (namespace A) and another for b.staging.example.org (namespace B)
a.staging.example.org has a TLS SNI with a.staging.example.org and b.staging.example.org and *.staging.example.org wildcard.
In generic case, no specific issue here, but at a point we forgot to renew b.staging.example.org certificate wildcard on Kubernetes. We expected to have SSL issue only on b.staging.example.org but in fact both a & b has issue, and used the wildcard, and randomly, depdending on which traefik pod we request.

### What did you expect to see?

a.staging.example.org TLS certificate must be the one provided in the ingress object in namespace A, not a random matching one for the domain in the global TLSstore.

### What did you see instead?

a.staging.example.org uses the first TLS certificate in the TLS store matching its name

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.3.7 (sure) & 2.4.8
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
containers:
      - args:
        - --api
        - --api.dashboard=true
        - --api.insecure=true
        - --providers.kubernetescrd=true
        - --providers.kubernetesingress=true
        - --providers.kubernetesingress.ingressclass=
        - --ping=true
        - --log.format=json
        - --log.level=INFO
        - --accesslog=true
        - --accesslog.format=json
        - --accesslog.bufferingsize=10
        - --entryPoints.https.address=:443
        - --entryPoints.https.http.tls=true
        - --entryPoints.https.proxyProtocol.insecure=true
        - --entryPoints.http.address=:80
        - --metrics.prometheus=true
        - --serversTransport.insecureSkipVerify=true
        - --providers.file=true
        - --providers.file.filename=/etc/traefik/dynamic.yaml
        - --tracing=true
        - --tracing.serviceName=platform-k8s-traefik-ingress
        - --tracing.elastic=true
        - --tracing.elastic.serverurl=http://apm-stag.noc.example.org:8200
        - --tracing.elastic.secrettoken=
        - --tracing.elastic.serviceenvironment=staging
        env:
        - name: ELASTIC_APM_TRANSACTION_SAMPLE_RATE
          value: "1.0"
        - name: ELASTIC_APM_IGNORE_URLS
          value: (?-i)/ping,(?-i)/metrics
        - name: ELASTIC_APM_GLOBAL_LABELS
          value: dc1,k8s_cluster=platform-staging-dc1
        - name: ELASTIC_APM_VERIFY_SERVER_CERT
          value: "false"
        image: traefik:2.4.8

```

dynamic.yaml
```
apiVersion: v1
data:
  dynamic.yaml: |
    tls:
      options:
        default:
          minVersion: VersionTLS12
          cipherSuites:
            - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
            - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
            - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
            - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
            - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
            - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        mintls13:
          minVersion: VersionTLS13
kind: ConfigMap
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```
