### ISSUE TITLE
Incorrect middleware order

### ISSUE THREAD

**Issue by WLun001** [traefik/traefik#8218]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I am aware that [midleware definition order is the calling order](https://community.traefik.io/t/can-we-set-priority-for-the-middlewares-in-v2/1326), but on the dashboard it shows different order of the definition order

Here is the IngressRoute definition order for Kubernetes 

```yaml
- kind: Rule
  match: PathPrefix(`/`)
  middlewares:
     - name: my-strip-prefix
     - name: my-headers
     - name: my-errorpage
```

### What did you see instead?
Dashboard showing different order of middlewares (every refresh it shows different orders)

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/23547929/123032476-96d86600-d418-11eb-814f-0fa576d2e6d1.png">

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64
```
