### ISSUE TITLE
Can't get External IP when I use `loadbalancerIP`in GKE

### ISSUE THREAD

**Issue by rohitsakala** [traefik/traefik#8227]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

-> Create a kubernetes cluster in GKE.
-> Installed Traefik v2.3.3 with traefik service as LoadBalancer with `loadbalancerIP: {static-ip-addres}`from GCP.

-> When I do ` kubectl -n traefik get svc traefik`, I see the EXTERNAL-IP as `pending`. 

### What did you see instead?

-> Trarfik SVC 

```spec:
  clusterIP: 10.67.139.225
  externalTrafficPolicy: Cluster
  loadBalancerIP: 35.190.63.47
  ports:
  - name: web
    nodePort: 32552
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    nodePort: 30499
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

Is this the right behaviour. 

I have some other doubts. 

Now, if I create an ingress for my deployment, it doesn't work

```

spec:
  rules:
  - host: epinio.rohitsakala.in
    http:
      paths:
      - backend:
          serviceName: epinio-server
          servicePort: 80
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
```

My {static-ip} points to epinio.rohitsakala.in

### What version of Traefik are you using?

v2.3.3

### What is your environment & configuration?

GKE : 1.19.10-gke.1600
