### ISSUE TITLE
Error messages when no HTTP routes defined and using GatewayAPI

### ISSUE THREAD

**Issue by fnakstad-f3** [traefik/traefik#8242]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Clean install of Gateway API 0.0.2 CRDs and Traefik 2.4.8 into EKS from Helm chart with the following values:
```yaml
ports:
  web:
    expose: false
service:
  type: NodePort
autoscaling:
  enabled: false
deployment:
  replicas: 3
experimental:
  kubernetesGateway:
    enabled: true
globalArguments: []
ingressRoute:
  dashboard:
    enabled: false
logs:
  general:
    format: json
podSecurityPolicy:
  enabled: true
providers:
  kubernetesIngress:
    enabled: false
resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
```

Expected pods to start up normally without any error messages.

### What did you see instead?

Pods keep spamming the following error message:
```
an error occurred while creating gateway status: 1 error occurred:\n\t* Cannot fetch HTTPRoutes for namespace \"default\" and matchLabels map[app:traefik]
```

When we created an `HTTPRoute` matching the selectors (seen below) the error messages stopped.
```yaml
apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: my-route
  namespace: default
spec:
  gateways:
    allow: FromList
    gatewayRefs:
    - name: traefik
      namespace: default
```

I'm guessing this will be a common case for people just setting things up, so seems like the log level should be less severe.

### What version of Traefik are you using?

Digest: sha256:eda951fd29a8762c3b5efb906afecc5d5de23406710b9d1fd0cbfe06f151f307
Status: Downloaded newer image for traefik:v2.4.8
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

Installed via Helm chart with the following Values:
```yaml
ports:
  web:
    expose: false
service:
  type: NodePort
autoscaling:
  enabled: false
deployment:
  replicas: 3
experimental:
  kubernetesGateway:
    enabled: true
globalArguments: []
ingressRoute:
  dashboard:
    enabled: false
logs:
  general:
    format: json
podSecurityPolicy:
  enabled: true
providers:
  kubernetesIngress:
    enabled: false
resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
```

Add more configuration information here.
