### ISSUE TITLE
Support Gateway Namespaces for Kubernetes GatewayAPI

### ISSUE THREAD

**Issue by ah-f3** [traefik/traefik#8246]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

We are looking to use Traefik as an implementation of the K8s GatewayAPI, we wanted to use a single Gateway managed by one team to provide the ability for teams using different namespaces to use. 

We have found that the implementation only looks for HTTPRoutes in the same namespace as the Gateway as per: https://github.com/traefik/traefik/blob/master/pkg/provider/kubernetes/gateway/kubernetes.go#L488

We currently would need to create a Gateway per-namespace for Traefik to pickup HTTPRoutes.

We have a listner configured on a GW with Namespaces: All
```yaml
  Listeners:
    Port:      8000
    Protocol:  HTTP
    Routes:
      Group:  networking.x-k8s.io
      Kind:   HTTPRoute
      Namespaces:
        From:  All
      Selector:
        Match Labels:
          App:  traefik
```

but it only looks in the Default NS (where the Gateway is deployed)
