### ISSUE TITLE
Traefik configures a certificate for a first-level domain name, and sites that visit the first-level domain name indicate that the site is not secure

### ISSUE THREAD

**Issue by gaoyang02** [traefik/traefik#8247]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Our company has set up a website for customers, using the K8S architecture.The domain name is configured to be a domain name such as www.test.com.The domain name is configured on Traefik, and secret is configured to mount *.test.com's generic domain name certificate;Now the customer has a request to be able to access the site via https://test.com.This is usually achieved by setting explicit URL jumps on the DNS server.However, the client explicitly stated that their DNS server does not support explicit URL jumps.So now I've configured the https://test.com domain name on Traefik and I'm listening for the same secret.The customer confirms that the generic domain name certificate they provide supports both https://www.test.com and at.I then created a RedirectRegex type middleware to support an automatic jump from https://test.com to green.A problem has been found. When visiting https://test.com through the browser, sometimes the certificate is trusted, and sometimes it is warned that the certificate is not secure.Traefik's custom certificate is used.I also confirmed that middleware has nothing to do with middleware.Even if I remove the reference to Middleware, I have the occasional problem of the certificate not being trusted;

### What did you see instead?

When I visit https://test.com, I sometimes prompt the following
The site is not secure, which could mean that someone is trying to trick you or steal any information you send to the server.You should close this site immediately

### What version of Traefik are you using?

```
 # traefik version
Version:      2.2.0
Codename:     chevrotin
Go version:   go1.14.1
Built:        2020-03-25T17:32:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: web
  labels:
    k8s-app: ui
spec:
  replicas: 3
  revisionHistoryLimit: 3  
  minReadySeconds: 70
  strategy:    
    rollingUpdate:    
      maxSurge: 1         
      maxUnavailable: 1   
  selector:
    matchLabels:
      k8s-app: ui
  template:
    metadata:
      labels:
        k8s-app: ui
    spec:
      containers:
      - name: ui
        image: 192.168.0.2/prod-k88/ui-1.0.0-release:build-41       
        resources:          
          limits:
            memory: 4096Mi
            cpu:  2000m
          requests:
            cpu: 1000m
            memory:  2048Mi
        ports:        
        - containerPort: 80
          name: ui
          protocol: TCP        
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 360
          periodSeconds: 20   
        volumeMounts:
        - mountPath: "/var/log/nginx/"
          name: logsdata
      imagePullSecrets:
      - name: registrykey    
      volumes:
      - name: logsdata
        hostPath:
          path: /data/logs/
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: web
  labels:
    k8s-app: ui
spec:
  ports: 
  - port: 80
    name: ui
    protocol: TCP    
    targetPort: 80
  selector:
    k8s-app: ui
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: web
spec:
  redirectScheme:
    scheme: https
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rewriteurl
  namespace: web
spec:
  redirectRegex:
    regex: ^https://test.com/(.*)
    replacement: https://www.test.com/${1}

# Add http://test.com domain name listening, and through middleware rediret-https to achieve a jump to"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: k88ui-http-rewrite
  namespace: web
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`test.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: ui
      port: 80
    middlewares:
    - name: redirect-https

# Add https://test.com domain name listening, and through the middleware rewrriteurl to achieve a skip to
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: k88ui-https-rewrite
  namespace: web
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`test.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: ui
      port: 80
    middlewares:
    - name: rewriteurl
  tls:
    secretName: produik88

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: k88ui-https
  namespace: web
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`www.test.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: ui
      port: 80
  tls:
    secretName: produik88
#    options:
#      name: mintls11
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: k88ui-http
  namespace: web
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`www.test.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: ui
      port: 80
    middlewares: 
    - name: redirect-https  
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: k88ui2-https
  namespace: web
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`isv-web.test.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: ui
      port: 80
  tls:
    secretName: produik88
#    options:
#    #      name: mintls11
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: k88ui3-https
  namespace: web
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`home.test.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: ui
      port: 80
  tls:
    secretName: produik88
```

Add more configuration information here.

I used the Traefik installed by Helm, and made some changes to the Traefik configuration, including changing the format and output of the Access Log logs, and mounting a custom certificate secret.Now you see that the log output is all Access Log and no system log.And when I visit https://test.com, I sometimes get a certificate that I can't trust, which is the Traefik's custom certificate that I defined

```
    spec:
      containers:
      - args:
        - --global.checknewversion
        - --global.sendanonymoususage
        - --api.insecure
        - --accesslog
        - --log.filePath="/var/log/traefik.log"
        - --accesslog.format=json
        - --accesslog.fields.names.defaultmode=keep
        - --accesslog.fields.names.RequestAddr=keep
        - --accesslog.fields.names.RequestHost=keep
        - --accesslog.fields.names.RequestPath=keep
        - --accesslog.fields.names.RequestLine=keep
        - --accesslog.fields.names.ServiceName=keep
        - --accesslog.fields.names.ClientAddr=keep
        - --entrypoints.web.Address=:80
        - --entrypoints.websecure.Address=:443
        - --providers.kubernetescrd
        - --certificatesresolvers.default.acme.tlschallenge
        - --certificatesresolvers.default.acme.email=zhangsan@test.com
        - -certificatesresolvers.default.acme.storage=acme.json
        - --entryPoints.traefik.address=:9000
        - --entryPoints.web.address=:80
        - --entryPoints.websecure.address=:443
        - --api.dashboard=true
        - --ping=true
        - --providers.kubernetescrd
        - --providers.file.filename=/dynamic_conf.toml/dynamic_conf.toml
		
		
		volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /certs
          name: public-cert
          readOnly: true
        - mountPath: /dynamic_conf.toml
          name: traefik-dynamic
		
		
	  volumes:
      - name: data
        persistentVolumeClaim:
          claimName: traefik
      - name: public-cert
        secret:
          defaultMode: 420
          secretName: public-cert
      - configMap:
          defaultMode: 420
          name: traefik-dynamic
        name: traefik-dynamic
	
# Enter the Traefik container to view the contents of the configuration file	
		
		/ # cat /dynamic_conf.toml/dynamic_conf.toml
[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/certs/tls.crt"
      keyFile  = "/certs/tls.key"
/ #
```

### If applicable, please paste the log output in DEBUG level

Because I changed the configuration of Traefik to Access-Log, why can't I see the system log now
