### ISSUE TITLE
v2.5.0-rc2 HTTP3 "QUIC is not supported"

### ISSUE THREAD

**Issue by chesskuo** [traefik/traefik#8255]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

enable the experimental http3 on entryPoint 443 and use it on http router

### What did you see instead?

I'm using https://http3check.net/ to check my website, but it show me
```
QUIC is not supported

HTTP/3 Check failed to establish a QUIC connection for all attempts made with the given endpoint. See the connection errors below for more information.

Attempted 4 connection(s).
Received packets for 4 connection(s).
Successful handshake for 2 connection(s).
```

I already check the response header, it had `Alt-Svc: h3-29=":443"; ma=2592000,h3-34=":443"; ma=2592000,h3-32=":443"; ma=2592000`.

Besides enable the experimental http3 in `traefik.yml`, what should I do anything else?

### What version of Traefik are you using?

`v2.5.0-rc2`

### `traefik.yml`
```yaml
experimental:
  http3: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
    enableHTTP3: true

api:
  dashboard: true

accessLog:
  fields:
    names:
      StartUTC: drop

providers:
  file:
    directory: /etc/traefik/dynamic_conf
    watch: true
```

### `dynamic_conf/main.yml`
```yaml
http:
  routers:
    www-http:
      entryPoints:
        - http
      rule: "Host(`ctf.example.com`)"
      middlewares:
        - redirect-to-https
      service: ctfd

    www-https:
      entryPoints:
        - https
      rule: "Host(`ctf.example.com`)"
      service: ctfd
      tls: {}

  services:
    ctfd:
      loadBalancer:
        servers:
          - url: "http://ctfd:8000/"

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

tls:
  certificates:
    - certFile: /ca/fullchain.pem
      keyFile: /ca/privkey.pem
```

**Comment by jbdoumenjou** [comment]
Hi @chesskuo, 

We tested your website to check http3 with Traefik and the result is that we support http3 but not QUIC.
If you don't have the sentence that says HTTP3 is supported, you probably need to open port 443 with UDP.

As the tool you mentioned is not very explicit, we can't know exactly what part is needed to be "QUIC compliant".
We may suppose it checks the Google QUIC compatibility without being sure.
Could you give more information?

**Comment by chesskuo** [comment]
@jbdoumenjou
Sir, thx for your reply.

At the first, in my `docker-compose.yml`, I already open TCP and UDP for 443 port at the same time, so the connection can upgrade to HTTP/3 correctly.

According the tool checking my website (https://http3check.net/?host=ctf.nisra.net), it returned my website already have HTTP/3, but doesn't support QUIC and showed some error msg about connection failed (QLog is at bottom).

And then I use this tool to check google.com, it doesn't show any error, so I think traefik maybe has something bug when creating QUIC connection. (But HTTP/3 is working perfectly, so I really have no idea about it...)

**Comment by thematchless** [comment]
Hi everybody 🖖🏼 

I tested the `v2.5.0-rc2` as well and can confirm that the [HTTP3Check](https://http3check.net/?host=thematchless.dev) will report that HTTP/3 is supported but shows no compatibility for QUIC.

@chesskuo how did you manage your TCP und UPD Port in your `docker-compose.yml`? I came across the following in the traefik documentation: 

![image](https://user-images.githubusercontent.com/19527555/125464018-098a1029-eaed-442b-9901-cb2b9f65277a.png)

**Comment by chesskuo** [comment]
hey @thematchless

this is my `docker-compose.yml`:
```yml
version: '3.8'

services:
  traefik:
    image: traefik:v2.5.0-rc2
    container_name: traefik
    restart: always
    environment:
      - TZ=Asia/Taipei
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./conf:/etc/traefik
      - ./log:/var/log/traefik
      - ./ca:/ca
    networks:
      traefik:
        ipv4_address: 172.100.0.1

networks:
  traefik:
    name: traefik
    attachable: true
    ipam:
      config:
        - subnet: 172.100.0.0/24
          gateway: 172.100.0.254
```

It is not especially at all.
I just forwarding TCP and UDP 443 to let http3 works.
According the docs you mentioned, I think it just talk about how is http3 working on traefik.
Setting `enableHTTP3` in a TCP entrypoint, and then this TCP entrypoint will open a UDP at the same time.
So you cannot set this port for UDP, it will show you the port is been used.

**Comment by thematchless** [comment]
Thanks for the reply @chesskuo 🙇🏼‍♂️ 

That's exactly how I configured my system. But to be clear, that's just the Docker port mapping.
I was just wondering if you have made some more adjustments to traefik itself. 

My understanding was that i have to configure multiple `entrypoints`: 
- my old one for TCP Connections (like 443)
- one new explicit TCP Connection for UDP 
- map both `entrypoints` two your `router`

Now with your `docker-compose` file i understand that the explicit `enableHTTP3` flag is enabling `443/udp` for traefik. I tried multiple configurations even with a different UDP Port than `443`, but it traefik seems to use only `443` for HTTP/3 as you can see in the HTTP headers.

Would be nice to have the possibility to configure the HTTP/3 Port as mentioned in https://github.com/traefik/traefik/issues/8130

**Comment by chesskuo** [comment]
@thematchless 

But on my setting, http3 could work besides the port 443.

This is a example for my site.
I opened port 8443 to enable http3 and worked perfectly.
You can also check it by yourself, my site is still online now.

![image](https://user-images.githubusercontent.com/30174763/125551580-f11be6e6-4074-4239-b27c-25b5f45ed7ba.png)

I provide some my configs, maybe it can help you.

- `docker-compose.yml`
  ```yml
  ports:
    - "80:80"
    - "443:443/tcp"
    - "443:443/udp"
    - "8443:8443/tcp"
    - "8443:8443/udp"
  ```

- `traefik.yml`
  ```yml
  entryPoints:
    http:
      address: ":80"
    https:
      address: ":443"
      enableHTTP3: true
    https2:
      address: ":8443"
      enableHTTP3: true
  ```

- `dynamic.yml`
  ```yml
  http:
    www-https:
      entryPoints:
        - https
        - https2
      rule: "Host(`ctf.nisra.net`)"
      service: ctfd
      tls: {}
  ```
