### ISSUE TITLE
Customize Host header for Errors middleware

### ISSUE THREAD

**Issue by jhyot** [traefik/traefik#8267]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

The Errors middleware currently does not allow to customize the Host header that is sent to the error service. This means that some service setups are currently not supported as an error page backend (if the server requires a specific Host header).

In our concrete case, we have Kubernetes with Traefik CRDs, and want to redirect error pages to an Kubernetes "ExternalName" service, which is a DNS redirect to Azure Storage (similar to Amazon S3). This does not work because the Errors middleware does not use the correct hostname in the Host header.

Example setup:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: external-errorpage
spec:
  type: ExternalName
  externalName: "customsubdomain.blob.core.windows.net"

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: errorpage
spec:
  errors:
    status:
      - "503"
    query: "/error.html"
    service:
      name: external-errorpage
      port: 443
```

Incidentally, a normal IngressRoute that points to the external service works correctly. Apparently Traefik rewrites the Host header to the new DNS name in that case. Example:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: exampleroute
spec:
  routes:
    - kind: Rule
      match: "PathPrefix(`/`)"
      priority: 1
      services:
        - kind: Service
          name: external-errorpage
          namespace: default
          passHostHeader: false
          port: 443
```

So I would propose to add a config option to Errors middleware that defines what to do with the Host header: don't touch, automatically determine (as for IngressRoute), or use a custom fixed value.

There was already a GitHub issue for this, but it was ignored: https://github.com/traefik/traefik/issues/7275

**Comment by dtomcej** [comment]
The default error URL is set here: https://github.com/traefik/traefik/blob/master/pkg/middlewares/customerrors/custom_errors.go#L32

And is not currently overwritten. Since the errors middleware has access to the request, it should use the host of the request, or be overridable.

**Comment by kevinpollet** [comment]
Hello @jhyot,

As the Errors middleware reference a service it is also possible to use the [`PassHostHeader`](https://doc.traefik.io/traefik/routing/services/#pass-host-header) option in the `Middleware` CRD. By doing that, the forwarded Host header value will be inferred from the `externalName` value (in your example `customsubdomain.blob.core.windows.net`).

```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: errorpage
spec:
  errors:
    status:
      - "503"
    query: "/error.html"
    service:
      name: external-errorpage
      passHostHeader: false
      port: 443
```

Can you confirm that this solves your issue?

Moreover, after a deeper look to the Errors middleware implementation we thought that instead of forwarding the Host value `0.0.0.0` to the service it would be better to forward the value of the client request Host. The following PR https://github.com/traefik/traefik/pull/8460 has been opened to fix that.
