### ISSUE TITLE
Uneven load on application pods as Traefik scales replicas up on K8s

### ISSUE THREAD

**Issue by dpoll** [traefik/traefik#8275]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Running Traefik on K8s cluster with Kubernetes version `v1.19.10`, I scaled my Traefik Deployment from 12 replicas up to 80 replicas. I then send 1000 requests to a helloworld application using a `IngressRouteTCP` object.  I used postman to send the requests and added the "Connection: close" header. 

### What did you see instead?

As the number of Traefik replicas increases, the load sent to application pods from Traefik is uneven. Looking in the Traefik dashboard, the IPs under the Service are listed in order of priority. The IPs at the top of the list corresponds to pods that receive the highest amount of load.

Distribution is fairly even when running Traefik with 12 replicas:
<img width="1672" alt="12-traefik-replicas" src="https://user-images.githubusercontent.com/12955041/126006762-f54328d7-a420-4e9d-ad15-3de696391065.png">

Distribution of load is uneven when Traefik is scaled up to 80 replicas:
<img width="1896" alt="80-traefik-replicas" src="https://user-images.githubusercontent.com/12955041/126006821-8826d91e-cb10-4460-802a-822ac37e815c.png">

In our production cluster, the skew is even worse. In this case we are running 64 replicas of Traefik:
<img width="1903" alt="prod-distribution" src="https://user-images.githubusercontent.com/12955041/126007898-191c55f7-19eb-4930-a49c-ab5497d1e0cd.png">

### What version of Traefik are you using?

Tested on `2.2.0`, `2.2.11` and now `2.4.9`. The issue still persists on all versions. I tried upgrading versions based on the discussion in [this issue](https://github.com/traefik/traefik/issues/7863).

### What is your environment & configuration?

Traefik manifest:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/path":"/metrics","prometheus.io/port":"9000","prometheus.io/scheme":"http","prometheus.io/scrape":"true","service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled":"true","service.beta.kubernetes.io/aws-load-balancer-internal":"true","service.beta.kubernetes.io/aws-load-balancer-type":"nlb"},"name":"traefik-internal","namespace":"traefik"},"spec":{"externalTrafficPolicy":"Local","loadBalancerSourceRanges":["0.0.0.0/0"],"ports":[{"name":"tls","nodePort":33767,"port":443,"protocol":"TCP","targetPort":8443}],"selector":{"app":"traefik"},"type":"LoadBalancer"}}
    prometheus.io/path: /metrics
    prometheus.io/port: "9000"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: traefik-internal
  namespace: traefik
spec:
  externalTrafficPolicy: Local
  healthCheckNodePort: 30809
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: tls
    nodePort: 33767
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: traefik
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: traefik
  name: traefik-ingress-controller
  namespace: traefik
  progressDeadlineSeconds: 600
  replicas: 6
  selector:
    matchLabels:
      app: traefik
      name: traefik-ingress-controller
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: traefik
        name: traefik-ingress-controller
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - traefik
              topologyKey: kubernetes.io/hostname
            weight: 10
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - traefik
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 5
      containers:
      - args:
        - --entrypoints.traefik=true
        - --entrypoints.traefik.address=:8080
        - --entrypoints.tls=true
        - --entrypoints.tls.address=:8443
        - --entrypoints.ping=true
        - --entrypoints.ping.address=:8082
        - --log=true
        - --log.level=fatal
        - --accesslog=true
        - --accesslog.format=json
        - --accesslog.bufferingSize=100
        - --accesslog.filters.statusCodes=400-599
        - --accesslog.filters.retryAttempts=true
        - --accesslog.filters.minDuration=10ms
        - --metrics.statsd=true
        - --metrics.statsd.address=statsd.k8s-newrelic.svc.cluster.local:8128
        - --metrics.statsd.prefix="hydrogen_shared_ingress_traefik"
        - --metrics.prometheus=true
        - --entryPoints.metrics.address=:9000
        - --metrics.prometheus.entryPoint=metrics
        - --ping=true
        - --ping.entrypoint=ping
        - --providers.kubernetescrd=true
        - --providers.kubernetescrd.ingressclass=shared-ingress
        - --providers.providersThrottleDuration=30s
        - --serversTransport.forwardingTimeouts.idleConnTimeout=10s
        - --serverstransport.maxidleconnsperhost=0
        image: traefik:v2.4.9
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: traefik
        ports:
        - containerPort: 8080
          name: api
          protocol: TCP
        - containerPort: 8443
          name: tls
          protocol: TCP
        - containerPort: 8082
          name: ping
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /ping
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 2
          timeoutSeconds: 2
        resources:
          requests:
            cpu: "2"
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: temp-dir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: traefik-ingress-controller
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: temp-dir

```

Helloworld app config:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: helloworld
  namespace: traefik
spec:
  progressDeadlineSeconds: 600
  replicas: 10
  selector:
    matchLabels:
      app: helloworld
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - helloworld
              topologyKey: kubernetes.io/hostname
            weight: 10
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - helloworld
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 5
      containers:
      - image: bench_test_server:latest
        imagePullPolicy: IfNotPresent
        name: application
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: nginx:stable
        imagePullPolicy: Always
        name: tls-sidecar
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          subPath: nginx.conf
        - mountPath: /var/run
          name: nginx-run
        - mountPath: /var/cache/nginx
          name: nginx-cache
        - mountPath: /app/certs
          name: nginx-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: hello
      serviceAccountName: hello
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: nginx-cache
      - emptyDir: {}
        name: nginx-run
      - name: nginx-certs
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
          secretName: helloworld-tls-certs
      - configMap:
          defaultMode: 420
          name: helloworld
        name: nginx-config
---
apiVersion: v1
data:
  nginx.conf: |2-

    worker_processes  1;
    events {
        worker_connections  1024;
    }
    http {
        access_log    /dev/stdout;
        include       mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;
        server {
          listen       8443 ssl;
          server_name  localhost;
          ssl_certificate      /app/certs/tls.crt;
          ssl_certificate_key  /app/certs/tls.key;
          ssl_protocols TLSv1.2;
          ssl_ciphers EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:!EECDH+3DES:!RSA+3DES:!MD5;
          ssl_prefer_server_ciphers on;
          location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_pass http://127.0.0.1:8080/;
          }
        }
    }
kind: ConfigMap
metadata:
  name: helloworld
  namespace: traefik
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
  name: helloworld
  namespace: traefik
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: helloworld
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: helloworld-ingressroutetcp
  namespace: traefik
spec:
  entryPoints:
  - tls
  routes:
  - kind: Rule
    match: HostSNI(`dakota.dev.net`)
    services:
    - name: helloworld
      port: 443
  tls:
    passthrough: true
```
