### ISSUE TITLE
 "traefik","level":"error","msg":"accept tcp [::]:8080: use of closed network connection"

### ISSUE THREAD

**Issue by mahb2018** [traefik/traefik#8277]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

when i set up traefik-deploy.yaml , it is display like that

### What did you see instead?

```
time="2021-07-18T02:22:35Z" level=info msg="Configuration loaded from file: /config/traefik.yaml"
{"entryPointName":"traefik","level":"error","msg":"accept tcp [::]:8080: use of closed network connection","time":"2021-07-18T02:23:14Z"}
{"entryPointName":"traefik","level":"error","msg":"close tcp [::]:8080: use of closed network connection","time":"2021-07-18T02:23:14Z"}
{"entryPointName":"admin","level":"error","msg":"accept tcp [::]:9000: use of closed network connection","time":"2021-07-18T02:23:14Z"}
{"entryPointName":"admin","level":"error","msg":"close tcp [::]:9000: use of closed network connection","time":"2021-07-18T02:23:14Z"}
{"entryPointName":"web","level":"error","msg":"accept tcp [::]:80: use of closed network connection","time":"2021-07-18T02:23:14Z"}
{"entryPointName":"web","level":"error","msg":"close tcp [::]:80: use of closed network connection","time":"2021-07-18T02:23:14Z"}
```
### What version of Traefik are you using?

traefik v2.2.4

kubernets v1.21.0

### What is your environment & configuration?

```yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  ports:
    - name: web
      port: 80
      #- name: websecure
      #port: 443
    - name: admin
      port: 9000 
  selector:
    app: traefik
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    app: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      name: traefik
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 1
      containers:
        - image: traefik:v2.2.4
          name: traefik-ingress-lb
          ports:
            - name: web
              containerPort: 80
              hostPort: 80    ## 将容器端口绑定所在服务器的 80 端口
              #- name: websecure
              #containerPort: 443
              #hostPort: 443    ## 将容器端口绑定所在服务器 443 端口
            - name: admin
              containerPort: 9000  ## Traefik Dashboard 端口
          resources:
            limits:
              cpu: 4000m
              memory: 10000Mi
            requests:
              cpu: 2000m
              memory: 10000Mi
          env:
             - name: PILOT_LOG_PREFIX
               value: "pilot,custom"
             - name: pilot_logs_nginx
               value: stdout
             - name: pilot_logs_nginx_format
               value: json
             - name: pilot_logs_nginx_target
               value: "prod-crs-k8s-ingress-traefik-json-log"
             - name: pilot_logs_nginx_tags
               value: "stage=prod"
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          args:
            - --configfile=/config/traefik.yaml
          volumeMounts:
            - mountPath: "/config"
              name: "config"
          readinessProbe:
            httpGet:
              path: /ping
              port: 9000
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: 9000
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
      volumes:
        - name: config
          configMap:
            name: traefik-config
      nodeSelector:             ## 设置node筛选器，在特定label的节点上启动
        IngressProxy: "true"
```

Add more configuration information here.
