### ISSUE TITLE
Missing metrics

### ISSUE THREAD

**Issue by thekoma** [traefik/traefik#8278]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

traefik_service_server_up metric is missing.

https://community.traefik.io/t/prometheus-metrics-traefik-service-server-up-missing/9920

### What did you see instead?

Missing metric

### What version of Traefik are you using?

2.4 and 2.5RC2

### What is your environment & configuration?

Docker compose, but is the same in k8s

```yaml
# (paste your configuration here)
metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true

```

Add more configuration information here.
