### ISSUE TITLE
Global middleware

### ISSUE THREAD

**Issue by JasonN3** [traefik/traefik#8305]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

After the last version update, cross-namespace references have been disabled by default. While this is a good idea for security, it would be great if some middleware could be flagged as global/re-usable. That way the security still blocks references to services in other namespaces and most of the middleware in other namespaces, but select middleware can be allowed to be referenced.

Example:
Create a single middleware that redirects http to https and have multiple routers in multiple namespaces references the middleware.

**Comment by JasonN3** [comment]
@ldez I gave a specific use case, but what about any other middleware where someone wants to write it once and reuse it without granting the ability to access services in other namespaces?

**Comment by rtribotte** [comment]
@JasonN3 IngressRoute resources are able to reference middlewares that can be defined by any other provider.
So, for instance, you can totally define a middleware with the file provider and reference it from an IngressRoute.
With cross-provider references, there is no namespace constraint applied.
Does it make sense for your use case?

**Comment by JasonN3** [comment]
That does make sense, but it means you'll have to manage the middleware in two separate ways: your preferred provider for app specific configurations and a separate provider for global configurations. There's currently a bug where you can reference something in another namespace by defining it as a cross-provider reference even if it's still in the same provider, but hopefully that gets fixed at some point since it currently defeats the purpose of allowCrossNamespace=false.

The point of this feature request was to allow someone to still use a single management system (CRDs in my case) while still being able to create global resources that can be reused across namespaces and without disabling the security of blocking access to resouces in most other namespaces.

Example setup of what I'm proposing:
main config:
```yaml
allowCrossNamespace: false
globalResourcesNamespace: traefik-resources
```

global middleware:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-redirectscheme
  namespace: traefik-resources
spec:
  redirectScheme:
    scheme: https
```
ingressroute:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute
  namespace: someapp
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`example.net`)
      kind: Rule
      services:
        - name: s1
          port: 80
      middlewares:
        - name: test-redirectscheme
          namespace: traefik-resources
```
The security constraint for references would then become "namespace == current_namespace or namespace == global_namespace" instead of just "namespace == current_namespace".
