### ISSUE TITLE
allowCrossNamespace can be bypassed

### ISSUE THREAD

**Issue by JasonN3** [traefik/traefik#8306]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

When creating an IngressRoute, you can enter the reference to middleware as a cross-platform reference and then it will be accepted even if the namespace is different and allowCrossNamespace is set to false.

### What did you see instead?

The middleware was accepted even though it was in a different namespace and allowCrossNamespace is set to false.

### What version of Traefik are you using?

2.4.11

### What is your environment & configuration?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: webserver
  namespace: namespace1
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`web.example.com`)
    middlewares:
    - name: namespace2-forcehttps@kubernetescrd
    services:
    - name: web
      namespace: namespace1
      port: 80
```

Add more configuration information here.
