### ISSUE TITLE
Switching from Staging to Production acme not working

### ISSUE THREAD

**Issue by valentin-ed** [traefik/traefik#8311]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I use traefik on Docker and i setted up two "letsencrypt" resolver.
The first one for production and the second one for "Staging".
One is writting file to "acme-prod.json" and the other one "acme-staging.json".

I use in my docker label "le-prod" and "le-staging". 

When i first creat my app i set "le-staging" as certificate resolver. When all is good i switch to "le-prod" and recreate my container. 

I suppose the certificate, which is not in the file "acme-prod.json", would be regenerate at this moment. 

### What did you see instead?

Unfortunately my certificate is not renewed and traefik use the one in "staging" file.

### What version of Traefik are you using?

Version:      2.4.12
Codename:     livarot
Go version:   go1.16.6
Built:        2021-07-26T16:16:11Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
certificatesResolvers:
  le-prod:
    acme:
      email: "certificate@mydomain.com"
      storage: "/letsencrypt/acme-prod.json"
      tlsChallenge: {}
  le-staging:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: "certificate@mydomain.com"
      storage: "/letsencrypt/acme-staging.json"
      tlsChallenge: {}
```
