### ISSUE TITLE
Traefik ingress controller - ingressClassName doesn't work correctly

### ISSUE THREAD

**Issue by guybarzi** [traefik/traefik#8312]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Hi,

I have the **EXACT** same issue as #7896 . Isn't this issue supposed to have already been resolved?

### What did you see instead?

Exactly the same as the aforementioned issue states...

### What version of Traefik are you using?

traefik:2.4.9

### What is your environment & configuration?

kubernetes 1.20

**Comment by rtribotte** [comment]
Hello @guybarzi,

Thanks for your interest in Traefik!

After reading #7896, there are multiple combinations of configuration that were exposed.

Can you please document specifically the issue you are encountering?

**Comment by guybarzi** [comment]
Hi @rtribotte,

Thank you for your response.

I experience the following problem:

I have 2 Traefik ingress controllers in my Kubernetes cluster - "traefik-1" and "traefik-2", each of them in its own namespace. I've installed them using your official helm chart in the following manner:

**traefik 1:**
`helm upgrade --version 10.0.0 -f values.yml -n traefik-1 traefik-1 traefik/traefik`

values.yml:
```

ingressClass:
  enabled: true
  isDefaultClass: false
additionalArguments:
  - "--metrics.prometheus=true"
  - "--providers.kubernetesingress.ingressclass=traefik-1"
  - "--providers.kubernetescrd.ingressclass=traefik-1"
  - "--log.level=DEBUG"


service:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
```
**traefik 2:**
`helm upgrade --version 10.0.0 -f values.yml -n traefik-2 traefik-2 traefik/traefik`

values.yml:
```

ingressClass:
  enabled: true
  isDefaultClass: false
additionalArguments:
  - "--metrics.prometheus=true"
  - "--providers.kubernetesingress.ingressclass=traefik-2"
  - "--providers.kubernetescrd.ingressclass=traefik-2"
  - "--log.level=DEBUG"


service:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
```

As you can understand, each of those ingress controller was created with its own corresponding ingress class, named like the ingress controller deployment (by default).

I expected that when I would create the following ingress rule, it would only be processed by "traefik-1" ingress controller:

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-backend
  namespace: test-nginx
spec:
  ingressClassName: traefik-1
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
```
However, I was surprised to find out that it was exposed through both of the aforementioned ingress controllers ("traefik-1" and "traefik-2").

When I created the ingress rule in the following manner (the "old school" annotation) however, it was processed only by the desired ingress controller:

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-backend
  namespace: test-nginx
  annotations:
    kubernetes.io/ingress.class: "traefik-1"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
```
I do need to be able to create my ingress rules in the former manner, and also should be, as I understood from the aforementioned issue.

I would really appreciate your help with this issue!

Thanks :)
