### ISSUE TITLE
SIGSEGV: Traefik, docker image crashing on Raspberry Pi 4 

### ISSUE THREAD

**Issue by Palid** [traefik/traefik#8340]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Restarted docker-compose to hope traefik will get new certs, but instead it just crashed. I assume there's some additional configuration that have changed for let's encrypt that should let you know that you've passed some wrong options, but it goes for a crash instead.
This has worked for a few months, so a crash was very unexpected.

Update:
Looks like after wiping __all__ the config files and letsencrypt and recreating traefik from scratch things are working again. That sounds extremely weird, considering that it hasn't been touched for a good while.

### What did you see instead?
```
traefik          | time="2021-08-06T20:40:00Z" level=info msg="Configuration loaded from flags."
traefik          | panic: runtime error: invalid memory address or nil pointer dereference
traefik          | [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x12b3784]
traefik          |
traefik          | goroutine 1 [running]:
traefik          | github.com/traefik/traefik/v2/pkg/provider/acme.(*LocalStore).get(0x6a4d830, 0x68c989e, 0xf, 0x0, 0x0, 0x0)
traefik          | 	/home/semaphore/go/src/github.com/traefik/traefik/pkg/provider/acme/local_store.go:77 +0x668
traefik          | github.com/traefik/traefik/v2/pkg/provider/acme.(*LocalStore).GetAccount(0x6a4d830, 0x68c989e, 0xf, 0x6cfc200, 0x1, 0x2f30acc)
traefik          | 	/home/semaphore/go/src/github.com/traefik/traefik/pkg/provider/acme/local_store.go:130 +0x2c
traefik          | github.com/traefik/traefik/v2/pkg/provider/acme.(*Provider).Init(0x6dee5b0, 0x8, 0x0)
traefik          | 	/home/semaphore/go/src/github.com/traefik/traefik/pkg/provider/acme/provider.go:137 +0x10c
traefik          | github.com/traefik/traefik/v2/pkg/provider/aggregator.(*ProviderAggregator).AddProvider(0x70adc7c, 0x2f17b58, 0x6dee5b0, 0x16, 0x70adb0c)
traefik          | 	/home/semaphore/go/src/github.com/traefik/traefik/pkg/provider/aggregator/aggregator.go:98 +0x24
traefik          | main.initACMEProvider(0x6a99180, 0x70adc7c, 0x6a4d7d0, 0x2f17b10, 0x6df8080, 0x2f17b28, 0x6a4d800, 0x0, 0x0, 0x0)
traefik          | 	/home/semaphore/go/src/github.com/traefik/traefik/cmd/traefik/traefik.go:407 +0x204
traefik          | main.setupServer(0x6a99180, 0x6bada40, 0x1e, 0x6b55e48)
traefik          | 	/home/semaphore/go/src/github.com/traefik/traefik/cmd/traefik/traefik.go:196 +0x2d4
traefik          | main.runCmd(0x6a99180, 0x0, 0x0)
traefik          | 	/home/semaphore/go/src/github.com/traefik/traefik/cmd/traefik/traefik.go:122 +0x314
traefik          | main.main.func1(0x6840130, 0xf, 0x10, 0x10, 0x6a991c0)
traefik          | 	/home/semaphore/go/src/github.com/traefik/traefik/cmd/traefik/traefik.go:63 +0x20
traefik          | github.com/traefik/paerser/cli.run(0x6a991c0, 0x6840130, 0xf, 0x10, 0x13, 0x6a99200)
traefik          | 	/home/semaphore/go/pkg/mod/github.com/traefik/paerser@v0.1.4/cli/commands.go:133 +0x130
traefik          | github.com/traefik/paerser/cli.execute(0x6a991c0, 0x6840120, 0x11, 0x12, 0x1, 0x0, 0x6844001)
traefik          | 	/home/semaphore/go/pkg/mod/github.com/traefik/paerser@v0.1.4/cli/commands.go:76 +0x3d4
traefik          | github.com/traefik/paerser/cli.Execute(...)
traefik          | 	/home/semaphore/go/pkg/mod/github.com/traefik/paerser@v0.1.4/cli/commands.go:51
traefik          | main.main()
traefik          | 	/home/semaphore/go/src/github.com/traefik/traefik/cmd/traefik/traefik.go:79 +0x3b4
```
### What version of Traefik are you using?

https://hub.docker.com/layers/traefik/library/traefik/v2.5/images/sha256-4996f7f535729539f4aec415c1e67264a263d5e4df735641e699b49cd3765123?context=explore
The same thing appeared with v2.4, image data below:
```json
    {
        "Id": "sha256:0f9d8f9270701f73afed1ff644a8b1d1124581418fa76527b45ea36641bb46db",
        "RepoTags": [
            "traefik:v2.4"
        ],
        "RepoDigests": [
            "traefik@sha256:3123d05e444f6297592c8443bcffe4bd291ab5b62e11a3d4eeb7ba3fd809540d"
        ],
```

### What is your environment & configuration?

```yml
version: '3.2'
services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.redactedresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.redactedresolver.acme.dnschallenge.provider=ovh"
      - "--certificatesresolvers.redactedresolver.acme.dnschallenge.delayBeforeCheck=10"
      - "--certificatesresolvers.redactedresolver.acme.email=redacted@redacteddomain.com"
      - "--certificatesresolvers.redactedresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.redactedresolver.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
      # - "--certificatesresolvers.redactedresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      # Force HTTPS
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"


    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - "OVH_ENDPOINT=ovh-eu"
      - "OVH_APPLICATION_KEY=REDACTED_APPLICATION_KEYKEY"
      - "OVH_APPLICATION_SECRET=REDACTED_SECRET"
      - "OVH_CONSUMER_KEY=REDACTED_CONSUMER_KEY"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    extra_hosts:
      - host.docker.internal:172.17.0.1 # Necessary to avoid bad gateway due to HA using host network
    labels:
    - "traefik.enable=true"
    - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    - "traefik.http.routers.traefik.rule=Host(`traefik.redacteddomain.com`)"
    - "traefik.http.routers.traefik.entrypoints=websecure"
    - "traefik.http.routers.traefik.tls.certresolver=redactedresolver"
    - "traefik.http.routers.traefik.service=traefik"

  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - /home/pi/opt/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyAMA0
     # - /dev/ttyS0
    restart: unless-stopped
    network_mode: host
    ports:
      - "8123:8123"
    expose:
      - 8123
    environment:
      - TZ=Europe/Warsaw
    labels:
    - "traefik.enable=true"
    - "traefik.http.services.hass.loadbalancer.server.port=8123"
    - "traefik.http.routers.hass.rule=Host(`hass.redacteddomain.com`)"
    - "traefik.http.routers.hass.entrypoints=websecure"
    - "traefik.http.routers.hass.tls.certresolver=redactedresolver"
    - "traefik.http.routers.hass.service=hass"

  grocy:
    image: ghcr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ='Europe/Warsaw'
    volumes:
      - /home/pi/opt/grocy/data:/config
    # ports:
    #   - 9283:80
    expose:
      - 80
    restart: unless-stopped
    # networks:
    #   - traefik-network
    labels:
    - "traefik.enable=true"
    # - traefik.docker.network=traefik-network
    - "traefik.http.services.grocy.loadbalancer.server.port=80"
    - "traefik.http.routers.grocy.rule=Host(`grocy.redacteddomain.com`)"
    - "traefik.http.routers.grocy.entrypoints=websecure"
    - "traefik.http.routers.grocy.tls.certresolver=redactedresolver"
    - "traefik.http.routers.grocy.service=grocy"
    # middleware redirect
    - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    # global redirect to https
    - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
    - "traefik.http.routers.redirs.entrypoints=web"
    - "traefik.http.routers.redirs.middlewares=redirect-to-https"

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      # - "81:80/tcp"
    expose:
      - 80
      - "53/tcp"
      - "53/udp"
      - "67/udp"
    environment:
      TZ: 'Europe/Warsaw'
      WEBPASSWORD: "REDACTED"
    # Volumes store your data between container upgrades
    volumes:
      - '/home/pi/opt/pihole/etc-pihole/:/etc/pihole/'
      - '/home/pi/opt/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 8.8.4.4
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    # networks:
    #   - traefik-network
    labels:
    - "traefik.enable=true"
    # - "traefik.docker.network=traefik-network"
    - "traefik.http.services.pihole.loadbalancer.server.port=80"
    - "traefik.http.routers.pihole.rule=Host(`pihole.redacteddomain.com`)"
    - "traefik.http.routers.pihole.entrypoints=websecure"
    - "traefik.http.routers.pihole.tls.certresolver=redactedresolver"
    - "traefik.http.routers.pihole.service=pihole"
    # - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
    # - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"
```

### If applicable, please paste the log output in DEBUG level

Crashes at the same place with or without debug, so that's not very helpful at this case.

### Rules.toml

```toml
[http.routers]
  # Define a connection between requests and services
    [http.routers.ha]
      rule = "Host(`ha.redacteddomain.com`)"
      entrypoints = ["websecure"]
      service = "ha"
    [http.routers.ha.tls]
      certResolver = "haresolver"
    [http.routers.homeassistant]
      rule = "Host(`homeassistant.redacteddomain.com`)"
      entrypoints = ["websecure"]
      service = "homeassistant"
    [http.routers.homeassistant.tls]
      certResolver = "homeassistantresolver"


[http.services]
      # Define how to reach an existing service on our infrastructure
      [http.services.ha.loadBalancer]
          [[http.services.ha.loadBalancer.servers]]
            url = "http://192.168.1.254:8123"
      [http.services.homeassistant.loadBalancer]
          [[http.services.homeassistant.loadBalancer.servers]]
            url = "http://192.168.1.254:8123"

```
