### ISSUE TITLE
If a service only has one port then ingress routes should not be required to specify one

### ISSUE THREAD

**Issue by solidDoWant** [traefik/traefik#8341]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

If a service targeted by an ingress route only has one port then Traefik should not require one to be specified. Instead, Traefik should get the service's port number from k8s directly. Services using more than one port should still require the port to be specified.

For example, given this service:
```
NAME             TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
media-organizr   ClusterIP   10.43.79.77   <none>        80/TCP    4d21h
```
the below ingress route resource should be sufficient to describe what service/port is being targeted.
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "organizr-dashboard"
spec:
  routes:
    - match: Host(`organizrr.myhost.local`)
      kind: Rule
      services:
      - name: "media-organizr"
        kind: Service
```

However this service:
```
NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
kube-dns   ClusterIP   10.43.0.10   <none>        53/UDP,53/TCP,9153/TCP   7d8h
```
uses multiple ports, so a port field should still be required to describe the service/port that's being targeted.

This could potentially be made "smarter" by making it so ingressroutes.traefik.containo.us resources will work without a port specification if only one TCP port is available (even if multiple UDP ports are available), ingressrouteudps.traefik.containo.us resources will work without a port specification if only one UDP port is available, etc.
