### ISSUE TITLE
Traefik not repeating lookup for services not present at initialisation in Docker environment

### ISSUE THREAD

**Issue by pa-exonar-com** [traefik/traefik#8347]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Set up Traefik as a proxy to another group of services using a file provider in a docker swarm environment. Expected Traefik to fail on DNS lookups for those  prior to the initialisation, but then succeed when those downstream services initialised.

### What did you see instead?

Traefik failed the initial DNS looks up on initialisation, and then continued to fail the DNS lookups for those services even once they had instantiated. The services are available by their name from within the Traefik container. Furthermore, restarting the Traefik service/container caused it to start succeeding on the DNS lookups.

### What version of Traefik are you using?

behaviour present with v2.3.2, v2.3.7 v.2.4.13

### What is your environment & configuration?

```yaml
#dynamic

tcp:

  routers:
    <router_name>:
      entrypoints:
        - "<entrypoint_name>"
      rule: "HostSNI(`*`)"
      service: <service_name>

  services:
    <service_name>:
      loadBalancer:
        servers:
          - address: "<service_name_1>:<port>"
          - address: "<service_name_2>:<port>"
          - address: "<service_name_n>:<port>"
          
#static

entryPoints:
  <entrypoint_name>:
    address: ":<port>"


providers:
  file:
    filename: "/etc/traefik/traefik-dynamic.yml"
    watch: true

serversTransport:
  maxIdleConnsPerHost: -1
```

### If applicable, please paste the log output in DEBUG level

`time="<timestamp" level=error msg="no available server"` - this line repeated ad infinitum, mixed in with other items about other services which are not relevant to this bug.
