### ISSUE TITLE
PathType missing in docs

### ISSUE THREAD

**Issue by iamNoah1** [traefik/traefik#8379]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I used an example yaml from the docs to create an ingress resource. It failed with the message: 

`The Ingress "myingress" is invalid: spec.rules[0].http.paths[0].pathType: Required value: pathType must be specified` 

I used the following docs as reference: 

https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/#certificates-management, with the tab k8s 1.19+

I also saw several other places where pathType is missing in the example manifests. Here for example: https://doc.traefik.io/traefik/providers/kubernetes-ingress/ 

### What did you see instead?

see the above description

### What version of Traefik are you using?

helm version: traefik-10.0.0	app version: 2.4.9

### What is your environment & configuration?

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  namespace: ns
spec:
  rules:
  - host: hostname.de
    http:
      paths:
      - path: /
        backend:
          service:
            name:  mysvc
            port:
              number: 80
  tls:
  - secretName: cert
```

Add more configuration information here.
