### ISSUE TITLE
Can't connect to a middleware in another namespace

### ISSUE THREAD

**Issue by OlivierAlves** [traefik/traefik#8380]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I have the following ingress route:
```yaml
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: auth-route-secure
  namespace: authentication
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.domain.com`)
      kind: Rule
      services:
        - kind: Service
          name: auth-service
          port: 9091
      middlewares:
        - name: traefik-security@kubernetescrd
```
and the following middleware:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: traefik
  name: security
spec:

  headers:
    frameDeny: true               
    sslRedirect: true             
    browserXssFilter: true    
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true              
    stsSeconds: 31536000  
```

Up until traefik v2.5.0 everything was working perfectly...

### What did you see instead?
```console
level=error msg="Failed to create middleware keys: invalid reference to middleware traefik-security@kubernetescrd: with crossnamespace disallowed, the namespace field needs to be explicitly specified" providerName=kubernetescrd ingress=auth-route-secure namespace=authentication
```
### What version of Traefik are you using?

v2.5.0

### What is your environment & configuration?

```yaml
persistence:
  enabled: true
  storageClass: "longhorn"
  size: 128Mi

```

Default helm chart with added changes defined above
