### ISSUE TITLE
_FILE counterpart environment variable are not being honored

### ISSUE THREAD

**Issue by cyamato** [traefik/traefik#8386]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Using Docker Secrets and the _FILE envars counterparts does not populate the envars in the container causing Traefik to fail to generate a Lets Encrypt cert. 

Not using the _FILE variants and passing the DO_AUTH_TOKEN and email directly in the compose file works as expected.

### What did you see instead?

NOTE:  '/ #' is the Root shell prompt

``` sh
root@docker-ubuntu-s-1vcpu-1gb-amd-fra1-01:~# docker exec -it 44d4cb9589eb sh
```

Within the Traefik container:
``` sh
/ # printenv
DO_AUTH_TOKEN_FILE=/run/secrets/do_auth_token
HOSTNAME=44d4cb9589eb
SHLVL=1
HOME=/root
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
TRAEFIK_CERTIFICATESRESOLVERS_MYRESOLVER_ACME_EMAIL_FILE=/run/secrets/cert_email
/ # ls /run/secrets/
cert_email     do_auth_token
/ # cat /run/secrets/cert_email 
someone@example.com
/ # 
`````

### What version of Traefik are you using?

v2.5

### What is your environment & configuration?

Cloud Provider: Digital Ocean
Image Used: https://marketplace.digitalocean.com/apps/docker
OS: Ubuntu 20.04
Docker CE: 20.10.7
Docker Compose: 1.27.0
Traefik: 2.5

docker-compose.yaml:
``` yaml
version: "3.8"

services:
  traefik:
    image: "traefik:v2.5"
    command:
      - "--log.level=DEBUG"
      - "--api=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=digitalocean"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    secrets:
      - do_auth_token
      - cert_email
    environment:
      - "DO_AUTH_TOKEN_FILE=/run/secrets/do_auth_token"
      - "TRAEFIK_CERTIFICATESRESOLVERS_MYRESOLVER_ACME_EMAIL_FILE=/run/secrets/cert_email"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=PathPrefix(`/`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.rule=(Host(`traefik.example.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`)))"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.domains[0].main=traefik.example.com"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.service=api@internal"
    ports:
      - "80:80"
      - "443:443"

  whoami:
    image: "traefik/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.example.com`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

secrets:
  do_auth_token:
    file: "./secrets/do_auth_token.secret"
  cert_email:
    file: "./secrets/cert_email.secret"
```
