### ISSUE TITLE
context deadline exceeded on plugin analyzer

### ISSUE THREAD

**Issue by Darkweak** [traefik/traefik#8388]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I'm trying to make my plugin pass the analyser on Github but there is an issue with it.  
The plugin loads well in Træfik `v2.5.0`

```
traefik_1  | time="2021-08-21T20:56:12Z" level=info msg="Configuration loaded from file: /traefik.yml"
traefik_1  | time="2021-08-21T20:56:12Z" level=info msg="Traefik version 2.5.0 built on 2021-08-17T16:16:03Z"
traefik_1  | time="2021-08-21T20:56:12Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true,\"sendAnonymousUsage\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"http\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}},\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"file\":{\"watch\":true,\"filename\":\"/souin-configuration.yaml\"}},\"api\":{\"insecure\":true,\"dashboard\":true,\"debug\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"accessLog\":{\"format\":\"common\",\"filters\":{},\"fields\":{\"defaultMode\":\"keep\",\"headers\":{\"defaultMode\":\"drop\"}}},\"pilot\":{\"token\":\"75223eaf-380a-4c16-840d-2b3ee4a2765a\",\"dashboard\":true},\"experimental\":{\"localPlugins\":{\"souin-plugin\":{\"moduleName\":\"github.com/darkweak/souin\"}}}}"
traefik_1  | time="2021-08-21T20:56:12Z" level=info msg="Stats collection is enabled."
traefik_1  | time="2021-08-21T20:56:12Z" level=info msg="Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration."
traefik_1  | time="2021-08-21T20:56:12Z" level=info msg="Help us improve Traefik by leaving this feature on :)"
traefik_1  | time="2021-08-21T20:56:12Z" level=info msg="More details on: https://doc.traefik.io/traefik/contributing/data-collection/"
traefik_1  | time="2021-08-21T20:56:14Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
traefik_1  | time="2021-08-21T20:56:14Z" level=debug msg="Start TCP Server" entryPointName=http
traefik_1  | time="2021-08-21T20:56:14Z" level=debug msg="Start TCP Server" entryPointName=traefik
traefik_1  | time="2021-08-21T20:56:14Z" level=info msg="Starting provider *file.Provider {\"watch\":true,\"filename\":\"/souin-configuration.yaml\"}"
traefik_1  | time="2021-08-21T20:56:14Z" level=info msg="Starting provider *traefik.Provider {}"
traefik_1  | time="2021-08-21T20:56:14Z" level=info msg="Starting provider *acme.ChallengeTLSALPN {\"Timeout\":4000000000}"
traefik_1  | time="2021-08-21T20:56:14Z" level=debug msg="Configuration received from provider file: {\"http\":{\"routers\":{\"whoami\":{\"entryPoints\":[\"http\"],\"middlewares\":[\"souin\"],\"service\":\"whoami\",\"rule\":\"Host(`domain.com`)\"}},\"services\":{\"whoami\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://whoami\"}],\"passHostHeader\":false}}},\"middlewares\":{\"souin\":{\"plugin\":{\"souin-plugin\":{\"default_cache\":{\"headers\":\"Authorization,Content-Type\",\"regex\":{\"exclude\":\"ARegexHere\"},\"ttl\":\"10s\"},\"log_level\":\"debug\",\"urls\":{\"domain.com/testing\":{\"headers\":\"Authorization\",\"ttl\":\"2s\"},\"mysubdomain.domain.com\":{\"headers\":\"Authorization,Content-Type\",\"ttl\":\"50s\"}},\"ykeys\":{\"The_First_Test\":{\"headers\":{\"Content-Type\":\".+\"}},\"The_Second_Test\":{\"url\":\"the/second/.+\"}}}}}}},\"tcp\":{},\"udp\":{},\"tls\":{}}" providerName=file
traefik_1  | time="2021-08-21T20:56:14Z" level=debug msg="Configuration received from provider internal: {\"http\":{\"routers\":{\"api\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/api`)\",\"priority\":2147483646},\"dashboard\":{\"entryPoints\":[\"traefik\"],\"middlewares\":[\"dashboard_redirect@internal\",\"dashboard_stripprefix@internal\"],\"service\":\"dashboard@internal\",\"rule\":\"PathPrefix(`/`)\",\"priority\":2147483645},\"debug\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/debug`)\",\"priority\":2147483646}},\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{}},\"middlewares\":{\"dashboard_redirect\":{\"redirectRegex\":{\"regex\":\"^(http:\\\\/\\\\/(\\\\[[\\\\w:.]+\\\\]|[\\\\w\\\\._-]+)(:\\\\d+)?)\\\\/$\",\"replacement\":\"${1}/dashboard/\",\"permanent\":true}},\"dashboard_stripprefix\":{\"stripPrefix\":{\"prefixes\":[\"/dashboard/\",\"/dashboard\"]}}},\"serversTransports\":{\"default\":{\"maxIdleConnsPerHost\":200}}},\"tcp\":{},\"tls\":{}}" providerName=internal
...
```

Everything loads in 2 seconds ([this issue](https://github.com/traefik/traefik/issues/8199) and more precisely [this answer](https://github.com/traefik/traefik/issues/8199#issuecomment-864420663) say that it throws a context deadline after `5s`).
There are some tests to ensure 
* golangci-lint pass (https://github.com/Darkweak/Souin/runs/3390614374?check_suite_focus=true#step:4:68)
* The Træfik plugin loads well (https://github.com/Darkweak/Souin/runs/3390614406?check_suite_focus=true)
And it uses the same configuration as the running one.

Do you have an idea how to debug/fix this ?

### What did you see instead?

```
failed to run the plugin with Yaegi: the load of the plugin takes too much time, or an error, inside the plugin, occurs during the load: context deadline exceeded
```

### What version of Traefik are you using?

I'm using the `v2.5.0` of Træfik using docker-compose.

### What is your environment & configuration?

`docker-compose.yml`
```yaml
traefik:
    image: traefik:v2.5.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../..:/plugins-local/src/github.com/darkweak/souin
      - ./traefik.yml:/traefik.yml
      - ./souin-configuration.yaml:/souin-configuration.yaml
    environment:
      GOPATH: /plugins-local
    ports:
      - 80:80
```

`souin-configuration.yaml`
```yaml
http:
  routers:
    whoami:
      middlewares:
        - souin
      entrypoints:
        - http
      service: whoami
      rule: Host(`domain.com`)

  services:
    whoami:
      loadBalancer:
        servers:
          - url: http://whoami
        passHostHeader: false

  middlewares:
    souin:
      plugin:
        souin-plugin:
          default_cache:
            headers:
              - Authorization
              - Content-Type
            regex:
              exclude: 'ARegexHere'
            ttl: 10s
          log_level: debug
          urls:
            'domain.com/testing':
              ttl: 2s
              headers:
                - Authorization
            'mysubdomain.domain.com':
              ttl: 50s
              headers:
                - Authorization
                - 'Content-Type'
          ykeys:
            The_First_Test:
              headers:
                Content-Type: '.+'
            The_Second_Test:
              url: 'the/second/.+'
            The_Third_Test:
            The_Fourth_Test:
```

`traefik.yml`
```yaml
providers:
  file:
    filename: /souin-configuration.yaml
    watch: true

api:
  dashboard: true
  debug: true
  insecure: true

pilot:
  token: XXX

experimental:
  localPlugins:
    souin-plugin:
      moduleName: github.com/darkweak/souin

log:
  level: DEBUG

accessLog: {}
```

`.traefik.yaml`
```yaml
displayName: Souin
type: middleware
import: github.com/darkweak/souin/plugins/traefik
summary: 'Souin is a powerfull cache system as fast as Varnish but easier to configure'

# Refer to https://github.com/darkweak/Souin/blob/master/configuration/configuration.sample.yml for full configuration
testData:
  default_cache:
    headers:
      - Authorization
      - Content-Type
    regex:
      exclude: 'ARegexHere'
    ttl: 10s
  log_level: debug
  urls:
    'domain.com/testing':
      ttl: 2s
      headers:
        - Authorization
    'mysubdomain.domain.com':
      ttl: 50s
      headers:
        - Authorization
        - 'Content-Type'
  ykeys:
    The_First_Test:
      headers:
        Content-Type: '.+'
    The_Second_Test:
      url: 'the/second/.+'
    The_Third_Test:
    The_Fourth_Test:
```

### If applicable, please paste the log output in DEBUG level

```bash
traefik_1  | time="2021-08-21T20:56:12Z" level=info msg="Configuration loaded from file: /traefik.yml"
traefik_1  | time="2021-08-21T20:56:12Z" level=info msg="Traefik version 2.5.0 built on 2021-08-17T16:16:03Z"
traefik_1  | time="2021-08-21T20:56:12Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true,\"sendAnonymousUsage\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"http\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}},\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"file\":{\"watch\":true,\"filename\":\"/souin-configuration.yaml\"}},\"api\":{\"insecure\":true,\"dashboard\":true,\"debug\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"accessLog\":{\"format\":\"common\",\"filters\":{},\"fields\":{\"defaultMode\":\"keep\",\"headers\":{\"defaultMode\":\"drop\"}}},\"pilot\":{\"token\":\"75223eaf-380a-4c16-840d-2b3ee4a2765a\",\"dashboard\":true},\"experimental\":{\"localPlugins\":{\"souin-plugin\":{\"moduleName\":\"github.com/darkweak/souin\"}}}}"
traefik_1  | time="2021-08-21T20:56:12Z" level=info msg="Stats collection is enabled."
traefik_1  | time="2021-08-21T20:56:12Z" level=info msg="Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration."
traefik_1  | time="2021-08-21T20:56:12Z" level=info msg="Help us improve Traefik by leaving this feature on :)"
traefik_1  | time="2021-08-21T20:56:12Z" level=info msg="More details on: https://doc.traefik.io/traefik/contributing/data-collection/"
traefik_1  | time="2021-08-21T20:56:14Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
traefik_1  | time="2021-08-21T20:56:14Z" level=debug msg="Start TCP Server" entryPointName=http
traefik_1  | time="2021-08-21T20:56:14Z" level=debug msg="Start TCP Server" entryPointName=traefik
traefik_1  | time="2021-08-21T20:56:14Z" level=info msg="Starting provider *file.Provider {\"watch\":true,\"filename\":\"/souin-configuration.yaml\"}"
traefik_1  | time="2021-08-21T20:56:14Z" level=info msg="Starting provider *traefik.Provider {}"
traefik_1  | time="2021-08-21T20:56:14Z" level=info msg="Starting provider *acme.ChallengeTLSALPN {\"Timeout\":4000000000}"
traefik_1  | time="2021-08-21T20:56:14Z" level=debug msg="Configuration received from provider file: {\"http\":{\"routers\":{\"whoami\":{\"entryPoints\":[\"http\"],\"middlewares\":[\"souin\"],\"service\":\"whoami\",\"rule\":\"Host(`domain.com`)\"}},\"services\":{\"whoami\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://whoami\"}],\"passHostHeader\":false}}},\"middlewares\":{\"souin\":{\"plugin\":{\"souin-plugin\":{\"default_cache\":{\"headers\":\"Authorization,Content-Type\",\"regex\":{\"exclude\":\"ARegexHere\"},\"ttl\":\"10s\"},\"log_level\":\"debug\",\"urls\":{\"domain.com/testing\":{\"headers\":\"Authorization\",\"ttl\":\"2s\"},\"mysubdomain.domain.com\":{\"headers\":\"Authorization,Content-Type\",\"ttl\":\"50s\"}},\"ykeys\":{\"The_First_Test\":{\"headers\":{\"Content-Type\":\".+\"}},\"The_Second_Test\":{\"url\":\"the/second/.+\"}}}}}}},\"tcp\":{},\"udp\":{},\"tls\":{}}" providerName=file
traefik_1  | time="2021-08-21T20:56:14Z" level=debug msg="Configuration received from provider internal: {\"http\":{\"routers\":{\"api\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/api`)\",\"priority\":2147483646},\"dashboard\":{\"entryPoints\":[\"traefik\"],\"middlewares\":[\"dashboard_redirect@internal\",\"dashboard_stripprefix@internal\"],\"service\":\"dashboard@internal\",\"rule\":\"PathPrefix(`/`)\",\"priority\":2147483645},\"debug\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/debug`)\",\"priority\":2147483646}},\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{}},\"middlewares\":{\"dashboard_redirect\":{\"redirectRegex\":{\"regex\":\"^(http:\\\\/\\\\/(\\\\[[\\\\w:.]+\\\\]|[\\\\w\\\\._-]+)(:\\\\d+)?)\\\\/$\",\"replacement\":\"${1}/dashboard/\",\"permanent\":true}},\"dashboard_stripprefix\":{\"stripPrefix\":{\"prefixes\":[\"/dashboard/\",\"/dashboard\"]}}},\"serversTransports\":{\"default\":{\"maxIdleConnsPerHost\":200}}},\"tcp\":{},\"tls\":{}}" providerName=internal
```
