### ISSUE TITLE
Kubernetes Middleware Resource 'namespace' key does not have effect in IngressRoute Resource

### ISSUE THREAD

**Issue by garygan89** [traefik/traefik#8389]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Namespace key specified in IngressRoute `middlewares.namespace` resource has no effect. For some reason Traefik cannot locate the Middleware defined in the IngressRoute `middlewares.namespace` key.

However this has no problem with `TLSOption` namespace. Where my TLSOption resource is defined in `proxy` namespace, and all IngressRoute in different namespace with `tlsoption.namespace=proxy` works fine.

My scenario:
Middleware namespace: proxy
Traefik deploy namespace: proxy
IngressRoute namespace: monitoring

Example of IngressRoute (partial)
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: $INGRESS_ROUTE_NAME
  annotations:
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host("$DNS_NAME")
    kind: Rule
    middlewares:
    - name: redirect-http-to-https   
      namespace: $NAMESPACE_MIDDLEWARE
...
```

### What did you see instead?

Traefik log output that the middleware key is not found:
```
...
{"ingress":"prometheus-ui","level":"error","msg":"Failed to create middleware keys: middleware proxy/redirect-http-to-https is not in the IngressRoute namespace monitoring","namespace":"monitoring","providerName":"kubernetescrd","time":"2021-08-21T01:24:19Z"}
...
```

Confirmed that the IngressRoute resource is using the Middleware namespace key.
kubectl describe ingressroute/...
```
...
Spec:
  Entry Points:
    websecure
  Routes:
    Kind:   Rule
    Match:  Host("...")
    Middlewares:
      Name:       redirect-http-to-https
      Namespace:  proxy
...
```

Solution:
It is most likely that Traefik operator forgot to monitor the Middlware `namespace` key.

### What version of Traefik are you using?

2.4.13

### What is your environment & configuration?

- Bare metal kubernetes
- Docker runtime
- Host OS: Ubuntu Linux 18.04 LTS x64

### If applicable, please paste the log output in DEBUG level

...
{"ingress":"prometheus-ui","level":"error","msg":"Failed to create middleware keys: middleware proxy/redirect-http-to-https is not in the IngressRoute namespace monitoring","namespace":"monitoring","providerName":"kubernetescrd","time":"2021-08-21T01:24:19Z"}
...
```

**Comment by rtribotte** [comment]
Hello @garygan89,

Thanks for your interest in Traefik!

Can you share also the definition of the middleware?
It would definitely help to troubleshoot the issue you are facing.

A few things though:
- The ingressRoute definition you shared has no namespace defined so I assume it is the `default` one.
- The namespace for the reference to the middleware is `proxy`.
- Though, in the logline you have pasted, it seems that the namespace of the ingressRoute is `monitoring`.

Did you enable the cross-namespace referencing? (https://doc.traefik.io/traefik/v2.4/migration/v2/#k8s-crossnamespace)

**Comment by garygan89** [comment]
Thanks for the reply!

In my configuration, I define all IngressRoute in the namespace where the Service is defined, instead of centralizing them all in a single namespace that Traefik is running on. This helps me to setup TLSOption to use any clientcert issued for the Service in case I need mTLS for the Service backend. I have my system issued all client cert in the same namespace where the service is running.

Following is my Middleware YAML defined in `proxy` namespace, where my Traefik pod is running.
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-http-to-https
spec:
  redirectScheme:
    scheme: https
    # permanent redirect
    permanent: true
    port: "443"
```

Following is an example just to illustrate that I can refer the `TLSOption` defined in `proxy` namespace in all my `IngressRoute` in other namespace by setting the `namespace` key explicitly.

`TLSOption` defined in `proxy` namespace, where my Traefik Pod is running.
```
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: traefik-client-auth

spec:
  minVersion: VersionTLS12
  maxVersion: VersionTLS13
  curvePreferences:
    - CurveP521
    - CurveP384
  cipherSuites:
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_RSA_WITH_AES_256_GCM_SHA384
  clientAuth:
    secretNames:
      - traefik-dashboard-client-auth-ca
    clientAuthType: RequireAndVerifyClientCert     
  sniStrict: true
```

`IngressRoute` defined in another namespace `monitoring`
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: $INGRESS_ROUTE_NAME
  annotations:
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host("$DNS_NAME")
    kind: Rule
    # middlewares:
    # - name: redirect-http-to-https   
      # namespace: $NAMESPACE_MIDDLEWARE
    services:
    - name: $BACKEND_SVC_NAME
      port: $BACKEND_SVC_PORT
      scheme: $BACKEND_SVC_SCHEME
      passHostHeader: true
  tls:
    secretName: $CERT_SECRET_NAME
    domains:
    - main: $DOMAIN_NAME
      sans:
      - $DNS_NAME
    # mtls
    options:
      name: traefik-client-auth
      namespace: proxy <<-- Can refer to that TLSOption just fine :D
```

I didn't know that `cross-namespace` had to be enabled explicitly, since I thought if all my other `IngressRoute` defined in other namespace can reference the `TLSOptions`  that I created in `proxy` namespace via the explicit `namespace` key, the `Middleware` should too hmm.
