### ISSUE TITLE
Custom response middleware for .well-known requests

### ISSUE THREAD

**Issue by S7evinK** [traefik/traefik#8391]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

I'm not sure if that's just too niche, or if that would also benefit others. 

Most [Matrix](https://matrix.org) servers use `/.well-known/matrix/(server/client)` to determine the actual server behind a domain.
Unfortunately, currently there's the need for an extra webserver behind Traefik, to respond to those requests.

It'd be great if Traefik could handle that itself.

My suggestion:
Add a middleware which can be used to directly respond to requests to a specific endpoint.

e.g. (k8s CRD):
```yaml
- match: Host(`my.domain`) && PathPrefix(`/.well-known/matrix/server`)
    kind: Rule
    services:
    - name: nginx-service-web
      port: 80
 ```

could be replaced by something like

```yaml
- match: Host(`my.domain`) && PathPrefix(`/.well-known/matrix/server`)
    kind: Rule
    middlewares:
   - name: json
     body: '{ "m.server": "my.domain:443" }'
```
