### ISSUE TITLE
Error while setting deadline && Error while terminating connection

### ISSUE THREAD

**Issue by loveyang2012** [traefik/traefik#8412]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I need proxy tcp port for mysql 

### What did you see instead?

sometimes it happend
![clipboard3](https://user-images.githubusercontent.com/24237714/131481876-532e0842-5040-4ae3-accd-842cd0e277f2.png)
![clipboard1](https://user-images.githubusercontent.com/24237714/131481881-e9732235-5805-494d-8263-ccef023057f9.png)
![clipboard](https://user-images.githubusercontent.com/24237714/131481883-2a6b5f0f-51f8-4224-9b77-ea7472b2d7bb.png)

### What version of Traefik are you using?

Version:      2.5.1
Codename:     livarot
Go version:   go1.17
Built:        2021-08-20T16:32:51Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
cat traefik.yml

api:
  dashboard: true
entryPoints:
  mysql:
     address: :3306
log:
  level: DEBUG
providers:
  file:
    filename: /data/traefik/dynamic.yml

cat dynamic.yml

tcp:
  routers:
    Router-1:
       rule: "HostSNI(`*`)" 
       service: mysql-service
  services:
    mysql-service:
     loadBalancer:
       servers:
       - address: 10.250.64.65:8306
```
```
Version:      2.5.1
Codename:     livarot
Go version:   go1.17
Built:        2021-08-20T16:32:51Z
OS/Arch:      linux/amd64
```
Add more configuration information here.
