### ISSUE TITLE
Cross namespace is always allowed for TLSOptions, TLSStore and ServersTransport resources

### ISSUE THREAD

**Issue by rtribotte** [traefik/traefik#8415]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I tried the behavior of the option `allowCrossNamespace` of the Kubernetes CRD provider, and made references to resources in the namespace `bar` from an IngressRoute in the namespace `default`.

I would have expected to be limited by default and not be able to reference all kinds of resources without setting the option `allowCrossNamespace` to `true`.

### What did you see instead?

When the option `allowCrossNamespace` is set to `false`:

As expected, a `Middleware` resource cannot be referenced from another namespace than the one of the `IngressRoute`.

Thus, it's possible to reference `TLSOptions` and `ServersTransport` resources from another namespace than the one of the `IngressRoute`.

For `TLSStore` resources, since references are not used to configure the TLS section of the underlying router for an `IngressRoute`, it may appear to one that it is working (cross namespace reference), but it's not and it's not generating an error.

### What version of Traefik are you using?

v2.5.1

### What is your environment & configuration?

CRD resources (middleware reference commented out):
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: supersecret
  namespace: bar

data:
  tls.crt: ...
  tls.key: ...

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myingressroute

spec:
  entryPoints:
    - web
  routes:
    - match: Host(`example.com`) && PathPrefix(`/stripit`)
      kind: Rule
      services:
        - name: whoami
          port: 8080
          serversTransport: mytransport
#      middlewares:
#        - name: stripprefix
#          namespace: bar
  tls:
    options:
      name: mytlsoption
      namespace: bar
    store:
      name: default
      namespace: bar

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: bar

spec:
  stripPrefix:
    prefixes:
      - /stripit

---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: bar

spec:
  defaultCertificate:
    secretName:  supersecret

---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: mytlsoption
  namespace: bar

spec:
  minVersion: VersionTLS12

---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: mytransport
  namespace: bar

spec:
  disableHTTP2: true

```

### If applicable, please paste the log output in DEBUG level

```
time="2021-09-01T08:20:37Z" level=debug msg="Configuration received from provider kubernetescrd: {\"http\":{\"routers\":{\"default-myingressroute-4a3b81efcb57af221fa6\":{\"entryPoints\":[\"web\"],\"service\":\"default-myingressroute-4a3b81efcb57af221fa6\",\"rule\":\"Host(`example.com`) \\u0026\\u0026 PathPrefix(`/stripit`)\",\"tls\":{\"options\":\"bar-mytlsoption\"}}},\"services\":{\"default-myingressroute-4a3b81efcb57af221fa6\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://10.42.0.7:80\"},{\"url\":\"http://10.42.0.8:80\"},{\"url\":\"http://10.42.0.9:80\"}],\"passHostHeader\":true,\"serversTransport\":\"mytransport\"}}},\"middlewares\":{\"bar-stripprefix\":{\"stripPrefix\":{\"prefixes\":[\"/stripit\"]}}},\"serversTransports\":{\"mytransport\":{\"forwardingTimeouts\":{\"dialTimeout\":\"30s\",\"idleConnTimeout\":\"1m30s\"}}}},\"tcp\":{},\"udp\":{},\"tls\":{\"options\":{\"bar-mytlsoption\":{\"minVersion\":\"foobar\",\"clientAuth\":{},\"alpnProtocols\":[\"h2\",\"http/1.1\",\"acme-tls/1\"]}},\"stores\":{\"default\":{}}}}" providerName=kubernetescrd
```

Config received:

```json
{
   "http":{
      "routers":{
         "default-myingressroute-4a3b81efcb57af221fa6":{
            "entryPoints":[
               "web"
            ],
            "service":"default-myingressroute-4a3b81efcb57af221fa6",
            "rule":"Host(`example.com`) u0026u0026 PathPrefix(`/stripit`)",
            "tls":{
               "options":"bar-mytlsoption"
            }
         }
      },
      "services":{
         "default-myingressroute-4a3b81efcb57af221fa6":{
            "loadBalancer":{
               "servers":[
                  {
                     "url":"http://10.42.0.7:80"
                  },
                  {
                     "url":"http://10.42.0.8:80"
                  },
                  {
                     "url":"http://10.42.0.9:80"
                  }
               ],
               "passHostHeader":true,
               "serversTransport":"mytransport"
            }
         }
      },
      "middlewares":{
         "bar-stripprefix":{
            "stripPrefix":{
               "prefixes":[
                  "/stripit"
               ]
            }
         }
      },
      "serversTransports":{
         "mytransport":{
            "forwardingTimeouts":{
               "dialTimeout":"30s",
               "idleConnTimeout":"1m30s"
            }
         }
      }
   },
   "tcp":{
      
   },
   "udp":{
      
   },
   "tls":{
      "options":{
         "bar-mytlsoption":{
            "minVersion":"foobar",
            "clientAuth":{
               
            },
            "alpnProtocols":[
               "h2",
               "http/1.1",
               "acme-tls/1"
            ]
         }
      },
      "stores":{
         "default":{
            
         }
      }
   }
}
```
