### ISSUE TITLE
new user on traefik,traefik  return 404

### ISSUE THREAD

**Issue by wanghonglei5181** [traefik/traefik#8420]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

**the os**
```
0> cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 

my ip address
10.17.8.64 
```

**the kernel version**
`4.16.12`

**traefik version**

```
0> ./traefik version
Version:      2.5.2
Codename:     livarot
Go version:   go1.17
Built:        2021-09-02T15:07:43Z
OS/Arch:      linux/amd64
```

**the start up command**

```
0> ./traefik --configfile=traefik.yaml --accesslog=true --log=true --loglevel=debug
INFO[0000] Configuration loaded from file: /data1/traefik/traefik.yaml 
```

**the content of traefik.yaml**

```
0> cat traefik.yaml 
global:
  checkNewVersion: true
  sendAnonymousUsage: true


entryPoints:
  web:
    address: :80

  websecure:
    address: :443

http:
  routers:
    my-router:
      rule: "Host(`gotest.sina.cn`) && Path(`/foo`)"
      service: my-service
http:
  services:
    my-service:
      loadBalancer:
        servers:
        - url: "http://10.41.42.78:80/"

```
**the test command**
```
7> curl -H Host:gotest.sina.cn http://10.17.8.64
404 page not found
```

```
**my quesion**
1，why 404
2，why i have no debug logs and access logs
```

### What did you see instead?

i need help

### What version of Traefik are you using?

v2.5.2

### What is your environment & configuration?

it is in the what did you do

### If applicable, please paste the log output in DEBUG level

it is in the what did you do
