### ISSUE TITLE
[2.5.1] ingres k8s 1.22 v1alpha1.MiddlewareTCP problem

### ISSUE THREAD

**Issue by sacesare** [traefik/traefik#8436]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Migrated to k8s 1.22, logs show:
`Failed to watch *v1alpha1.MiddlewareTCP: failed to list *v1alpha1.MiddlewareTCP`
Similar problem described in #8342 , but it's related to "v1beta1.Ingress failed to list" errors.
It seems, there's serious issues with ingres k8s 1.22.
[https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes](url)
Because of that, this crd not working:
```
    apiVersion: traefik.containo.us/v1alpha1
    kind: Middleware
    metadata:
      name: stripprefix
    spec:
      stripPrefix:
        prefixes:
          - /onlyofficeds
```

### What did you see instead?

`Failed to watch *v1alpha1.MiddlewareTCP: failed to list *v1alpha1.MiddlewareTCP`

### What version of Traefik are you using?

2.5.1

### What is your environment & configuration?

k0s 1.22
