### ISSUE TITLE
Kubernetese IngressRoute configuration throwing an Internal Server Error

### ISSUE THREAD

**Issue by groovenarula** [traefik/traefik#8437]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I have successfully setup Traefik Ingress Controller (ver 2.2.8) on an OnPerm K8s cluster (ver 1.21.1) with LetsEncrypt integrated and it's working fine handling TLS termination a.k.a Local Lan-> Load Balancer (MetalLB) -> Traefik Ingress (HTTPS) -> K8s Service (HTTP) -> Pods (HTTP). This route uses a LetEncrypt signed Wild Card Cert and it's working very well.

Where I am struggling with an example with connecting to a secure (HTTPS) backend service where I have to use a Self Signed Cert. My use case requires ALL traffic to be encrypted even within the K8s Cluster. So I need the following route  Local Lan-> Load Balancer (MetalLB) -> Traefik Ingress (HTTPS) -> K8s Service (HTTPS) -> Pods (HTTPS) where the Pods are configured with certificates that are signed by a local CA (cfssl). I have verified that the K8s Service is working using CURL using openssl s_client and the local CA's certificate (-CAFile) option. But when I try to connect to it through Traefik using the following configuration : 

```yml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-secure
  namespace: whoami
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`whoami.k8s.narulas.org`)
      kind: Rule
      middlewares:
        - name: headers-default@file
      services:
        - name: whoami-https
          namespace: whoami
          port: 443
          scheme: https
          kind: Service
```

I am getting an Internal Server Error. I go believe it's because of the self sighed certificate. I know I can use insecureSkipVerify option, but that won't be an acceptable solution and need to find the documentation on how to configure the CA Cert for the backend service when configuring the IngressRoute. I tried to read the documentation but went down different rabbit holes and could not figure out the required configuration on how to accomplish this.

Would appreciate any help in pointing me to the appropriate sections of the documentation (preferably with examples). 

### What did you see instead?

Internal Server Error

### What version of Traefik are you using?

2.2.8

### What is your environment & configuration?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-secure
  namespace: whoami
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`whoami.k8s.narulas.org`)
      kind: Rule
      middlewares:
        - name: headers-default@file
      services:
        - name: whoami-https
          namespace: whoami
          port: 443
          scheme: https
          kind: Service
```
