### ISSUE TITLE
X-Forwarded-Proto is set to `https` instead of `http`

### ISSUE THREAD

**Issue by pehbehbeh** [traefik/traefik#8440]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

We set up a `http` router in front of an existing `https` service. The service is available under `https://example.com` and we have to allow `http` requests from `http://unencrypted.example.com`. This is a requirement to support some legacy devices which do not support https - don't ask... ^^

Everything is working properly except one thing. Traefik sets the `X-Forwarded-Proto` to `https` which causes some trouble in the application. We would expect this:

```
X-Forwarded-For:    x.x.x.x,x.x.x.x,,x.x.x.x,
X-Forwarded-Host:   unencrypted.example.com
X-Forwarded-Port:   80
X-Forwarded-Proto:  http
X-Forwarded-Server: xxx
```

### What did you see instead?

We get this instead:

```
X-Forwarded-For:    x.x.x.x,x.x.x.x,,x.x.x.x,
X-Forwarded-Host:   unencrypted.example.com
X-Forwarded-Port:   80
X-Forwarded-Proto:  https
X-Forwarded-Server: xxx
```

Is this correct behaviour?

### What version of Traefik are you using?

2.5.2

### What is your environment & configuration?

```yaml
http:
  routers:
    myExampleRouter:
      entryPoints:
        - "web"
      rule: "Host(`unencrypted.example.com`)"
      service: "myExampleService@file"
  services:
    myExampleService:
      loadBalancer:
        servers:
          - url: "https://example.com/"
        passHostHeader: false
```

**Comment by jbdoumenjou** [comment]
Hello @pehbehbeh,

Could you provide a minimal reproducible case?

**Comment by pehbehbeh** [comment]
Hey @jbdoumenjou,

this is the static configuration:

```yml
# traefik.yml

################################################################
# Global configuration
################################################################

global:
  checkNewVersion: false
  sendAnonymousUsage: false

################################################################
# EntryPoints configuration
################################################################

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

################################################################
# Traefik logs configuration
################################################################

log:
  level: INFO

################################################################
# Access logs configuration
################################################################

accessLog: {}

################################################################
# API and dashboard configuration
################################################################

api:
  insecure: true
  dashboard: true

################################################################
# Ping configuration
################################################################

ping: {}

################################################################
# HTTPS & TLS and configuration
################################################################

certificatesResolvers:
  letsencrypt:
    acme:
      httpChallenge:
        entrypoint: web
      email: "admin@example.com"
      storage: /etc/letsencrypt/acme.json

################################################################
# Provider configuration
################################################################

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/config
```

This is the dynamic configuration:

```yml
# api.yml

http:
  routers:
    apiWeb:
      entryPoints:
        - "web"
      rule: "Host(`traefik.example.com`)"
      service: "api@internal"
      middlewares:
      - redirectToHttps
    apiWebsecure:
      entryPoints:
        - "websecure"
      rule: "Host(`traefik.example.com`)"
      service: "api@internal"
      middlewares:
        - basicAuthApi
      tls:
        certresolver: letsencrypt
  middlewares:
    redirectToHttps:
      redirectScheme:
        scheme: https
        permanent: true
    basicAuthApi:
      basicAuth:
        users:
          - "xxx:xxx"
```

```yml
# unencrypted.yml

http:
  routers:
    myExampleRouter:
      entryPoints:
        - "web"
      rule: "Host(`unencrypted.example.com`)"
      service: "myExampleService@file"
  services:
    myExampleService:
      loadBalancer:
        servers:
          - url: "https://example.com/"
        passHostHeader: false
```

**Comment by kevinpollet** [comment]
Hello @pehbehbeh and thanks for your interest in Traefik,

We tried to reproduce the issue but without any success with the following configuration. Before using this docker-compose the whoami certificates must be generated in the `certs` folder.

```yaml
version: "3.9"
services:
  traefik:
    image: traefik:v2.5.2
    command:
      - --api.insecure
      - --log.level=debug
      - --providers.docker.exposedByDefault=false
      - --entrypoints.http.address=:80
      - --serversTransport.insecureSkipVerify=true # <-- needed to skip the cert validation between Traefik and the whoami service (do not use in production).

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    ports:
      - "8080:8080"
      - "80:80"

  whoami:
    image: traefik/whoami
    command:
      - --cert=/certs/cert.pem
      - --key=/certs/key.pem

    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=http
      - traefik.http.routers.whoami.rule=Host(`whoami.localhost`)
      - traefik.http.services.whoami-service.loadbalancer.server.scheme=https
      - traefik.http.services.whoami-service.loadbalancer.passHostHeader=false

    volumes:
      - ./certs:/certs
```

The following response comes from the whoami service after sending a request to `http://whoami.localhost`.

```
Hostname: e3b8335d8895
IP: 127.0.0.1
IP: 172.22.0.3
RemoteAddr: 172.22.0.2:36798
GET / HTTP/1.1
Host: 172.22.0.3:80
...
X-Forwarded-Proto: http
...
```

As expected the value for the `X-Forwarded-Proto` header is `http`, even if the request between Traefik and the whoami service is secured with TLS.

According to this, we will close this issue. Do not hesitate to re-open it, if you think that we are missing something or to open a topic in the [community forum](https://community.traefik.io/c/traefik/traefik-v2/10) to get some help from the community.
