### ISSUE TITLE
Manually replacing the TLS certificate does not take effect

### ISSUE THREAD

**Issue by houzhx759** [traefik/traefik#8441]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

The certificates I serve are secret TLS certificates created in different namespaces    ，Now I manually delete them and create a new Secret TLS with the CRT and key of the new certificate  ，But they won't take effect. The accessed certificate is the old certificate.，This problem has been bothering me for days，Hope to get your help, thank you

### What did you see instead?

Even weirder is that they are sometimes valid and it is possible to access new certificates  ，It's not the browser. I clean the cache every time I visit,But in my pre-live environment it didn't work at all

### What version of Traefik are you using?

I use traefik2.2.8  

### What is your environment & configuration?

I created Traefik in a K8s environment  ,This is the YAML file  

```yml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik
  namespace: ingress-system

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  namespace: ingress-system
  name: traefik
  labels:
    k8s-app: traefik
spec:
  selector:
    matchLabels:
      k8s-app: traefik
  template:
    metadata:
      labels:
        k8s-app: traefik
        logging: "true"
    spec:
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: traefik
          image: traefik:2.2.8-alpine
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
          args:
            - --api.insecure
            - --api.dashboard
            - --log.format=json
            - --log.level=INFO
            - --accesslog.bufferingsize=100
            - - --accesslog
            - --accessLog.fields.headers.defaultMode=keep
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
#            - --entrypoints.mysql.Address=:3306
            - --providers.kubernetescrd
            - --metrics.prometheus
            - --metrics.prometheus.entrypoint=metrics
            - --metrics.prometheus.addEntryPointsLabels=true
            - --entryPoints.metrics.address=:8082
            - --serverstransport.insecureskipverify=true
            - --providers.kubernetesingress.disablepasshostheaders=true
            - --configfile=/config/traefik.toml
            - ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: websecure
              containerPort: 443
              hostPort: 443
            - name: admin
              containerPort: 8080
              hostPort: 8080
            - name: http-metrics
              containerPort: 8082
              hostPort: 8082
#            - name: mysql
#              containerPort: 3306
#              hostPort: 3306
          volumeMounts:
            - mountPath: "/ssl"
              name: "ssl"
#            - mountPath: "/config"
#              name: "config"
          securityContext:
            capabilities:
              drop:
              - ALL
              add:
              - NET_BIND_SERVICE
                nodeSelector:
        route: "traefik"
      tolerations:
      - effect: NoExecute
        key: route
        value: "traefik"
        operator: Equal
#        tolerationSeconds: 3600
#       - operator: "Exists"
      volumes:
#        - name: nginx-config
#          configMap:
#            name: nginx-config
        - name: ssl
          secret:
            secretName: traefik-cert
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: traefik
  name: traefik
  namespace: ingress-system
  annotations:
     prometheus.io/port: "8082"
     prometheus.io/scrape: 'true'
spec:
  ports:
- protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: admin
      port: 8080
    - protocol: TCP
      name: websecure
      port: 443
    - protocol: TCP
      name: http-metrics
      port: 8082

  selector:
    k8s-app: traefik
```
### If applicable, please paste the log output in DEBUG level

The log does not contain any exception information
