### ISSUE TITLE
No straightforward way to redirect to https

### ISSUE THREAD

**Issue by lllamnyp** [traefik/traefik#8444]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I have deployed a k8s ingress (the native resource, not the CRD, see below for exact manifests) and configured the ingress controller with annotations to serve a resource with https.

With the help of Middleware and some annotations I expected this setup to work on both ports 80 and 443 and get the usual result of an http request being redirected to https and then having the webpage served.

I have considered workarounds, such as using a second Ingress resource, but this is problematic: while many helm charts support annotations to an Ingress resource, none provide an option of a second ingress.

### What did you see instead?

Instead, this resource is not served on the "web" entrypoint under this configuration:
```
$ curl http://thanos-querier.csip.x5.ru/ -vL
*   Trying 100.64.40.72...
* TCP_NODELAY set
* Connected to thanos-querier.csip.x5.ru (100.64.40.72) port 80 (#0)
> GET / HTTP/1.1
> Host: thanos-querier.csip.x5.ru
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Tue, 14 Sep 2021 12:53:45 GMT
< Content-Length: 19
< 
404 page not found
* Connection #0 to host thanos-querier.csip.x5.ru left intact
```
Conversely, if I remove the `router.tls` annotation, then I get the redirect, but it leads to nowhere:
```
n$ curl http://thanos-querier.csip.x5.ru/ -vL
*   Trying 100.64.40.53...
* TCP_NODELAY set
* Connected to thanos-querier.csip.x5.ru (100.64.40.53) port 80 (#0)
> GET / HTTP/1.1
> Host: thanos-querier.csip.x5.ru
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Location: https://thanos-querier.csip.x5.ru/
< Date: Tue, 14 Sep 2021 12:55:15 GMT
< Content-Length: 5
< Content-Type: text/plain; charset=utf-8
< 
* Ignoring the response-body
* Connection #0 to host thanos-querier.csip.x5.ru left intact
* Issue another request to this URL: 'https://thanos-querier.csip.x5.ru/'
*   Trying 100.64.40.53...
SNIPPED
< HTTP/2 404 
< content-type: text/plain; charset=utf-8
< x-content-type-options: nosniff
< content-length: 19
< date: Tue, 14 Sep 2021 12:55:15 GMT
< 
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
404 page not found
* Connection #1 to host thanos-querier.csip.x5.ru left intact
```

### What version of Traefik are you using?

```Version:      2.5.1
Codename:     livarot
Go version:   go1.17
Built:        2021-08-20T16:32:51Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

I have deployed traefik with the helm chart (10.3.2) into a 1.20 k8s cluster
```yaml
#$ helm get values -n traefik traefik
#USER-SUPPLIED VALUES:
deployment:
  kind: DaemonSet
hostNetwork: true
image:
  name: dockerhub-proxy.do.x5.ru/library/traefik
nodeSelector:
  node-role.kubernetes.io/ingress: ""
ports:
  metrics:
    port: 9899
  traefik:
    port: 9999
  web:
    port: 80
  websecure:
    port: 443
securityContext:
  allowPrivilegeEscalation: true
  capabilities:
    add:
    - NET_BIND_SERVICE
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0
service:
  spec:
    clusterIP: None
  type: ClusterIP
```

I have then deployed the manifests

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thanos-query-frontend
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-3.14.0
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/managed-by: Helm
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: csip-monitoring-tls-redirect@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: thanos-querier.csip.x5.ru
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: thanos-query-frontend
                port:
                  name: http
  tls:
    - hosts:
      - thanos-querier.csip.x5.ru
      secretName: csip-x5-ru
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: tls-redirect
spec:
  redirectScheme:
    scheme: https
```

**Comment by jakubhajek** [comment]
hello @lllamnyp 

Thanks a lot for using Traefik and asking the question here. 

Basically speaking if you would like to create a redirection from HTTP to HTTPS you just need to create two routers that match the same rule. The first router should be running on HTTP (web) and the second router should be running on HTTPS (web secure). 
Then you create the middleware RedirectScheme. The middleware should be assigned to the first routers, to that one with HTTP. 

The HTTP router:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-redirectscheme@kubernetescrd
spec:
  rules:
    - host: whoami.<FIXME>.demo.traefiklabs.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami-svc
                port:
                  number: 80
```

the HTTPS router

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-https
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  rules:
    - host: whoami.<FIXME>.demo.traefiklabs.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami-svc
                port:
                  number: 80
```

the redirectscheme middleware
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirectscheme
spec:
  redirectScheme:
    scheme: https
    permanent: true
```

More details you can find by watching the[ Getting Started with Traefik Workshop](https://youtu.be/CL5Cxxz-yHo) .

You can also create a global redirection on the entry point level as it is described in [the docs:](https://doc.traefik.io/traefik/routing/entrypoints/#entrypoint)


```yaml
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
```
I hope that helps. Let us know :)

**Comment by lllamnyp** [comment]
@jakubhajek thanks for the reply, I was afraid that would be the case. As I mentioned,

> I have considered workarounds, such as using a second Ingress resource, but this is problematic: while many helm charts support annotations to an Ingress resource, none provide an option of a second ingress.

This worsens the compatibility of traefik with many existing applications, stuff that just works with the community nginx ingress controller will fail under traefik and nothing short of creating an extra resource will suffice.

Would it be too much of a stretch to turn this into a feature request? E.g. an annotation in the Ingress responsible for the https router would prompt the creation of an http router as well? Maybe this has been discussed in some other issue that I haven't found?

**Comment by jakubhajek** [comment]
Hey @lllamnyp 

Thanks a lot for your answer. 

Could you please try to implement a global redirection on the entry point level? The idea I suggested with having two HTTP and HTTPS routers works fine, but you have to manually create two routers. Having global redirection should solve that challenge. 
Let me know your thoughts. 

Sure, we will discuss your proposal during today's issue triage.

**Comment by lllamnyp** [comment]
Hey @jakubhajek,

This is an option on one hand, after all, https everywhere is a noble goal, but it might not be viable in many situations, such as non-production clusters where not all resources have TLS setup, or situations where the performance hit from encryption is unacceptable.

**Comment by jakubhajek** [comment]
Hello @lllamnyp 

Thanks for your comment.

This is how Traefik has been designed, so if you would like to have redirection from HTTP to HTTPS you need to create two separate routers and on the HTTP router just add the redirection. You can also have a global redirection on an entrypoint level as I suggested. 

For production and non-production environment, I would recommend creating separate Traefik instances and keep the configuration separate for each of the environments. 

Thank you,

**Comment by lllamnyp** [comment]
Thanks @jakubhajek 

Just one more time, to fully clarify. Routers are Traefik's entities, if two are required to achieve what I'm looking for, that\s fine. Ingresses, however, are k8s' entities and the mapping between the two is, presumably, not part of the core codebase. Is it worth trying to put out a PR that would permit, given the appropriate annotations, `one ingress -> two routers`? Or is there an architectural decision made that one ingress always corresponds to one router?

**Comment by rtribotte** [comment]
@lllamnyp

> Is it worth trying to put out a PR that would permit, given the appropriate annotations, one ingress -> two routers? Or is there an architectural decision made that one ingress always corresponds to one router?

I would say no, in this case, we probably don't want to create two routers from one Ingress resource automatically.
The reason is not that an Ingress should indeed correspond to one router in Traefik.
For instance, you can define multiple paths on one Ingress which leads to create multiple routers from this Ingress.

The reason why is that we are not convinced that creating two routers automatically is really needed to redirect to HTTPS.

To clarify, as explained by @jakubhajek in a [previous comment](https://github.com/traefik/traefik/issues/8444#issuecomment-919238687), there are two ways to configure HTTPS redirect:

- Create two Ingresses, one attached to the `web` EntryPoint and with a redirect middleware, and a TLS one attached on the `websecure` EntryPoint.
- Create a global redirect on the web EntryPoint and create one Ingress attached to both EntryPoints.

Thus, there is one more alternative, you can leverage the TLS configuration on EntryPoints:
```yaml
entryPoints:
  web:
    address: :80

  websecure:
    address: :443
    tls:
        options: foobar
        certResolver: leresolver
        domains:
          - main: example.com
            sans:
              - foo.example.com
              - bar.example.com
          - main: test.com
            sans:
              - foo.test.com
              - bar.test.com
```
By doing this you can declare only one ingress:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-https
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-redirectscheme@kubernetescrd
spec:
  rules:
    - host: whoami.<FIXME>.demo.traefiklabs.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami-svc
                port:
                  number: 80
```

This will create two routers, one TLS and one without, and while both will have the redirect middleware attached, it would be transparent on the TLS one.

Unfortunately, I'll close this issue, as there are multiple ways to achieve what you want to do.
