### ISSUE TITLE
"Error while serving UDP: read udp 172.18.0.7:57095->172.18.0.6:3992: read: connection refused"

### ISSUE THREAD

**Issue by aSemy** [traefik/traefik#8455]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

This issue might be a duplicate of, or related to, these issues

* #7000
* #7430

### What did you do?

I'm running Traefik using a docker-compose file. I have static and dynamic configuration. I'm running `traefik/whoami`, and a node website successfully. However when I try and run an OpenTTD server (UDP and TCP) it starts up, and configuration all looks green. But the server isn't visible and there's an error in the Traefik logs.

```none
traefik    | time="2021-09-18T10:54:45Z" level=debug msg="Handling connection from 172.18.0.1:57470"
traefik    | time="2021-09-18T10:54:45Z" level=debug msg="Handling connection from 172.18.0.1:45636"
traefik    | time="2021-09-18T10:54:45Z" level=error msg="Error while serving UDP: read udp 172.18.0.7:33058->172.18.0.6:3992: read: connection refused"
traefik    | time="2021-09-18T10:54:45Z" level=error msg="Error while serving UDP: read udp 172.18.0.7:36469->172.18.0.6:3992: read: connection refused"
traefik    | time="2021-09-18T10:54:45Z" level=debug msg="Error while terminating connection: close udp 172.18.0.7:36469->172.18.0.6:3992: use of closed network connection"
```

I've configured port forwarding in my router.

I've tried the following.

* Using `"HostSNI(*)"` and `"HostSNI(mywebsite.com)"`
* using file config or Docker label config
* setting OpenTTD's exposed ports to be different (e.g. `"3991:3979/tcp"` and `"3992:3979/udp"` and configuring the Traefik services to use these ports

I can connect directly over the local network (e.g. `192.178.1.100:3990`), but not directly via IP or via hostname.

### What did you see instead?

The OpenTTD server is not connectable, and there are errors in the logs.

Debug log, `docker-compose logs -f`

```none
traefik    | time="2021-09-18T10:54:43Z" level=debug msg="Handling connection from 172.18.0.1:57470"
traefik    | time="2021-09-18T10:54:43Z" level=debug msg="Handling connection from 172.18.0.1:45636"
traefik    | time="2021-09-18T10:54:43Z" level=error msg="Error while serving UDP: read udp 172.18.0.7:47116->172.18.0.6:3990: read: connection refused"
traefik    | time="2021-09-18T10:54:43Z" level=debug msg="Error while terminating connection: close udp 172.18.0.7:47116->172.18.0.6:3990: use of closed network connection"
traefik    | time="2021-09-18T10:54:43Z" level=error msg="Error while serving UDP: read udp 172.18.0.7:39478->172.18.0.6:3990: read: connection refused"
traefik    | time="2021-09-18T10:54:43Z" level=debug msg="Error while terminating connection: close udp 172.18.0.7:39478->172.18.0.6:3990: use of closed network connection"
traefik    | time="2021-09-18T10:54:45Z" level=debug msg="Handling connection from 172.18.0.1:57470"
traefik    | time="2021-09-18T10:54:45Z" level=debug msg="Handling connection from 172.18.0.1:45636"
traefik    | time="2021-09-18T10:54:45Z" level=error msg="Error while serving UDP: read udp 172.18.0.7:33058->172.18.0.6:3990: read: connection refused"
traefik    | time="2021-09-18T10:54:45Z" level=error msg="Error while serving UDP: read udp 172.18.0.7:36469->172.18.0.6:3990: read: connection refused"
traefik    | time="2021-09-18T10:54:45Z" level=debug msg="Error while terminating connection: close udp 172.18.0.7:36469->172.18.0.6:3990: use of closed network connection"
traefik    | time="2021-09-18T10:54:45Z" level=debug msg="Error while terminating connection: close udp 172.18.0.7:33058->172.18.0.6:3990: use of closed network connection"
```

### What version of Traefik are you using?

`image: "traefik:v2.5.2"`

##### static config yml

```yaml
entryPoints:

  # http
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"

  # https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: "le-cert"
        domains: 
          - main: "mywebsite.com"
            sans: 
              - "*.mywebsite.com"

  # openttd
  openttd-tcp:
    address: ":3979/tcp"
  openttd-udp:
    address: ":3979/udp"

providers:
  file:
    directory: "/etc/traefik-dynamic/"
    watch: "true"
  docker:
    network: "traefik-nw"
    watch: "true"
    exposedByDefault: "false"

api:
  insecure: "true"
  dashboard: "true"
  debug: "true"

log:
  level: "debug"

certificatesResolvers:
  le-cert:
    acme:
      email: "example @ blah com"
      # LE staging server - uncomment to test
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: gcloud
        delayBeforeCheck: 0
#        resolvers:
#        disablePropagationCheck: true


```

##### dynamic config yml

(OpenTTD only, I've omitted the others)

```yml
tcp:
  routers:
    openttd-tcp:
      rule: "HostSNI(`*`)"
      # rule: "HostSNI(`mywebsite.com`)"
      # service: "openttd-tcp@docker"
      service: "openttd-tcp"
      tls: false
      entryPoints:
        - "openttd-tcp"
      # tls:
        # passthrough: true
  services:
    openttd-tcp:
      loadBalancer:
        servers:
          - address: "openttd:3990"
       # proxyProtocol:
       #   version: 1
       # terminationDelay: 500

udp:
  routers:
    openttd-udp: 
      # service: "openttd-udp@docker" 
      service: "openttd-udp" 
      entryPoints:
        - "openttd-udp"
  services:
    openttd-udp:
      loadBalancer:
        servers:
          - address: "openttd:3990"
```

##### Traefik

```yaml
version: "3.8"

services:

  traefik:
    image: "traefik:v2.5.2"
    container_name: "traefik"
    restart: "unless-stopped"
    ports:
      # web, http
      - "80:80"
      # websecure, https
      - "443:443"
      # traefik web-ui
      - "8080:8080"

      # open-ttd
      - "3979:3979/tcp"
      - "3979:3979/udp"

    environment:
      GCE_SERVICE_ACCOUNT_FILE: "/auth/.secret.dns-api-key.json"
    volumes:
      # docker
      - "${DOCKER_SOCKET}:/var/run/docker.sock:ro"
      # config
      - "./config/static:/etc/traefik/"
      - "./config/dynamic:/etc/traefik-dynamic/"
      - "./auth:/auth"
      # cert
      - "./letsencrypt:/letsencrypt"

  whoami:
    image: "traefik/whoami"
    container_name: "traefik-whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/`)"
      - "traefik.http.routers.whoami.entrypoints=web,websecure"
      - "traefik.http.routers.whoami.priority=1"

networks: 
  default:
    name: traefik-nw 
```

##### OpenTTD

```yaml
version: "3.8"

services: 
  
  openttd: 
    image: "bateau/openttd:1.11.2"
    container_name: "openttd"
    ports: 
      - "3990:3979/tcp"
      - "3990:3979/udp"
    environment:
      loadgame: "last-autosave"
    networks: 
      - traefik-nw
    # labels:
    #   - "traefik.enable=true"
    #   # tcp - https://doc.traefik.io/traefik/routing/providers/docker/#tcp
    #   # - "traefik.tcp.routers.openttd-tcp.rule=HostSNI(`mywebsite.com`)"
    #   - "traefik.tcp.routers.openttd-tcp.rule=HostSNI(`*`)"
    #   - "traefik.tcp.routers.openttd-tcp.entrypoints=openttd-tcp"
    #   - "traefik.tcp.routers.openttd-tcp.tls=false"
    #   - "traefik.tcp.services.openttd-tcp.loadbalancer.servers.port=3990"
    #   # udp - https://doc.traefik.io/traefik/routing/providers/docker/#udp
    #   - "traefik.udp.routers.openttd-udp.entrypoints=openttd-udp"
    #   - "traefik.udp.services.openttd-udp.loadbalancer.server.port=3990"

networks: 
  traefik-nw:
    external: true
```

**Comment by aSemy** [comment]
Just found out the issue!

I thought because the OpenTTD container was exposing port `3990` (to `3979` I should set 

``` yaml
upd:
  services:
    openttd-udp:
      loadBalancer:
        servers:
          - address: "openttd:3990"
```

But that's incorrect. Because OpenTTD and Traefik are on the same Docker network (`traefik-nw`), it's okay to use a non-exposed port.

This configuration is working:

##### dynamic config 

```yaml
tcp:
  services:
    openttd-tcp:
      loadBalancer:
        servers:
          - address: "openttd:3979"
upd:
  services:
    openttd-udp:
      loadBalancer:
        servers:
          - address: "openttd:3979"
```


##### docker-compose

```yaml
services:
  openttd: 
    image: "bateau/openttd:1.11.2"
    container_name: "openttd"
    ports: 
      - "3990:3979/tcp" # these ports are exposed, but not used by Traefik
      - "3990:3979/udp"
```

Also I can't set a host SNI, for example

```yaml
tcp:
  routers:
    openttd-tcp:
      rule: "HostSNI(`openttd.mywebsite.com`)" # doesn't work
```

It has to be a wildcard 

```yaml
tcp:
  routers:
    openttd-tcp:
      rule: "HostSNI(`*`)" # doesn't work
```

I don't understand why...
