### ISSUE TITLE
404 Not Found when using secure dashboard

### ISSUE THREAD

**Issue by Bence98007** [traefik/traefik#8458]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Tried to change from insecure to secure dashboard, as the documentation describes.

### What did you see instead?

I've got 404 Not Found error.
DNS settings are ok.
HTTPS not working for the dashboard (should it?)
I try to access the dashboard by this: https://mysrv-traefik.domain.com/dashboard/

### What version of Traefik are you using?

Traefik v2.4

### What is your environment & configuration?

```yaml
 traefik:
    image: "traefik:v2.4"
    restart: "unless-stopped"
    container_name: "mysrv-traefik"
    command:
      - "--log.level=DEBUG"
      - "--pilot.token=xxx"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=db-net"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      # cert resolver
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=mail@mail.hu"
      - "--certificatesresolvers.myresolver.acme.storage=/etc/letsencrypt/acme.json"
      # dashboard
      - "--api.dashboard=true"
      - "--api=true"
      - "--api.insecure=false"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`mysrv-traefik.sup.hu`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.middlewares.test-auth.basicauth.usersfile=/var/containersdata/auth/usersfile"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/containersdata/db-traefik/letsencrypt:/etc/letsencrypt"
    networks:
      - db-net
```
