### ISSUE TITLE
allowExternalNameServices not working

### ISSUE THREAD

**Issue by atze234** [traefik/traefik#8462]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I installed Traefik with the helm Chart and set:
```
  globalArguments:
    - "--providers.kubernetescrd.allowexternalnameservices"
```

Heres a thread in the Forums about it too. Without a solution: https://community.traefik.io/t/allowexternalnameservices-parameter-not-working-well-in-helm-chart/11653

### What did you see instead?

Looking good at startup in the Logs:
```
time="2021-09-23T14:33:51Z" level=info msg="Starting provider *crd.Provider {\"allowCrossNamespace\":true,\"allowExternalNameServices\":true}"
time="2021-09-23T14:33:51Z" level=warning msg="Cross-namespace reference between IngressRoutes and resources is enabled, please ensure that this is expected (see AllowCrossNamespace option)" providerName=kubernetescrd
time="2021-09-23T14:33:51Z" level=warning msg="ExternalName service loading is enabled, please ensure that this is expected (see AllowExternalNameServices option)" providerName=kubernetescrd

```
but then:
```
time="2021-09-23T14:33:51Z" level=error msg="Cannot create service: externalName services not allowed: <redacted>/<redacted>" serviceName=<redacted> servicePort="&ServiceBackendPort{Name:,Number:443,}" namespace=<redacted> ingress=<redacted> providerName=kubernetes
```
So my externalService Ingress isnt working. 

With Traefik 2.4.8 this Ingress is working.

### What version of Traefik are you using?

2.5.3

### What is your environment & configuration?

This the Ingress, nothing special i think. Namespace is the same for Ingress and Service:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/service.passhostheader: "false"
  name: <redacted>
  namespace: <redacted>
spec:
  ingressClassName: traefik2-private
  rules:
  - host: <redacted>
    http:
      paths:
      - backend:
          service:
            name: <redacted>
            port:
              number: 443
        path: /
        pathType: Prefix
```
and the Service:
```
apiVersion: v1
kind: Service
metadata:
  name: <redacted>
  namespace: <redacted>
spec:
  externalName: <redacted>
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: ExternalName

```
Traefik Pod, Installed from Helm Chart traefik-10.3.5:
    Image:         traefik:2.5.3
    Args:
      --api=true
      --entryPoints.web.forwardedHeaders.insecure
      --entryPoints.websecure.forwardedHeaders.insecure
      --providers.kubernetescrd.allowCrossNamespace=true
      --experimental.plugins.rco.modulename=github.com/Lepkem/traefik-plugin-response-code-override
      --experimental.plugins.rco.version=v0.0.3
      --providers.kubernetescrd.allowexternalnameservices
      --entryPoints.metrics.address=:9100/tcp
      --entryPoints.traefik.address=:9000/tcp
      --entryPoints.web.address=:8000/tcp
      --entryPoints.websecure.address=:8443/tcp
      --api.dashboard=true
      --ping=true
      --metrics.prometheus=true
      --metrics.prometheus.entrypoint=metrics
      --providers.kubernetescrd
      --providers.kubernetesingress
      --entrypoints.web.http.redirections.entryPoint.to=:443
      --entrypoints.web.http.redirections.entryPoint.scheme=https
      --log.level=DEBUG
      --accesslog=true
      --accesslog.fields.defaultmode=keep
      --accesslog.fields.headers.defaultmode=drop
      --pilot.token=xxx
