### ISSUE TITLE
UDP Middleware Support

### ISSUE THREAD

**Issue by danmasta** [traefik/traefik#8463]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

I recently migrated a kubernetes cluster with many types of workloads to use traefik proxy via IngressRoute, IngressRouteTCP, and IngressRouteUDP. We use a variety of protocols including https, tcp, udp, and websockets. Everything worked great except for one use case that was missing. Some of the workloads include game servers, dns servers, and vpn servers. These all use udp and some of those workloads can be public, but some need to be private and/or have limited accessibility.

With http and tcp we can use the `IpWhiteList` middleware, but there is no such support for udp packets. Can you add support for an IpWhiteList middleware for udp?

As a workaround we're using a separate LoadBalancer service for private udp services and using the loadBalancerSourceRanges field as an ipwhitelist.

**Comment by 3nprob** [comment]
@traefiker don't auto-close

**Comment by odg0318** [comment]
@danmasta Can you share a workaround for UDP whitelisting?

**Comment by danmasta** [comment]
@odg0318 Yeah sure, I just removed the udp port entrypoints from traefik config and then added a separate kubernetes load balancer service like this:
```
apiVersion: v1
kind: Service
metadata:
  name: app-udp
  namespace: default
  labels:
    app: app
  annotations:
spec:
  externalTrafficPolicy: Local
  ports:
    - port: 8888
      targetPort: udp1
      name: udp1
      protocol: UDP
    - port: 7777
      targetPort: udp2
      name: udp2
      protocol: UDP
  type: LoadBalancer
  loadBalancerIP: {{LOAD_BALANCER_IP}}
  selector:
    app: app
  loadBalancerSourceRanges:
    - 0.0.0.0/0
```
Note the `loadBalancerSourceRanges` field is where you can add your ip whitelist ranges. Downside is this costs more money per load balancer if you are using cloud services, so it does not scale well if you have many separate services you need to add whitelists for.
