### ISSUE TITLE
Issue with IngressRouteTCP in Kubernetes 1.19.13 and later

### ISSUE THREAD

**Issue by AvinashRamireddy31** [traefik/traefik#8466]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I was running Kubernetes v1.19.11  with Traefik 2.3.1 and everything worked fine. 
Now I tried to upgrade to K8s v1.20.9 with Traefik 2.5.1 using helm 3.6.3 and facing issue with **kind: rule and kind:service** in IngressRouteTCP yaml file 
  
```

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: myingressroutetcp
spec:
  entryPoints:             
    - tcp
  routes:
{{- range .Values.ingress.tcphosts }}
  - match: HostSNI(`*`)  
    kind: Rule     
    services:              
    - name: {{ .host.name | replace "." "-" }}-{{ $.Release.Name | replace "." "-"}} 
      port: 808            
      kind: Service
{{- end }}                                 
```

**Error:** _unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(IngressRouteTCP.spec.routes[0]): unknown field "kind" in us.containo.traefik.v1alpha1.IngressRouteTCP.spec.routes, ValidationError(IngressRouteTCP.spec.routes[0].services[0]): unknown field "kind" in us.containo.traefik.v1alpha1.IngressRouteTCP.spec.routes.services]_

So I **commented out the kind: rule and kind: service in line 11 and 15 respectively** as per the error messsage 
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: myingressroutetcp
spec:
  entryPoints:             
    - tcp
  routes:
{{- range .Values.ingress.tcphosts }}
  - match: HostSNI(`*`)  
    # kind: Rule     
    services:              
    - name: {{ .host.name | replace "." "-" }}-{{ $.Release.Name | replace "." "-"}} 
      port: 808            
      # kind: Service
{{- end }}                                 
```

Only thing I changed in **helm** traefik was in values.yaml was

```
service:
  enabled: true
  type: LoadBalancer
  # Additional annotations applied to both TCP and UDP services (e.g. for cloud provider specific config)
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true" #this is added by me
```

BTW I am using Azure kubernetes service (AKS)

### What did you see instead?

After commenting kind validation error is gone but when I check in dashboard TCP route

![image](https://user-images.githubusercontent.com/44237026/134699656-5609db59-8ef7-45fa-809f-1860184d8c7e.png)

This is happening in kubernetes versions I tried( 1.19.13 and 1.20.9 ) but it was working fine with kind: rule and kind: service in included in kubernetes 1.19.11

### What version of Traefik are you using?

traefik 2.5.1
kubernetes 1.20.9
helm 2.6.3

### What is your environment & configuration?

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: myingressroutetcp
spec:
  entryPoints:             
    - tcp
  routes:
{{- range .Values.ingress.tcphosts }}
  - match: HostSNI(`*`)  
    # kind: Rule     
    services:              
    - name: {{ .host.name | replace "." "-" }}-{{ $.Release.Name | replace "." "-"}} 
      port: 808            
      # kind: Service
{{- end }}      
```
