### ISSUE TITLE
Traefik does not work with .me domains

### ISSUE THREAD

**Issue by eliminyro** [traefik/traefik#8470]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Hello,

I was battling a 404 message on a page when I stumbled upon this problem. To be honest, it didn't occur to me at first that it would be possible, yet it is.
I have a test JS application running in a docker container, the traffic to which is being forwarded by Traefik.
I have several other services set up absolutely identically and they work as expected. This one, however, is not.
I have made the conclusion that the problem is with the domain name itself when I successfully accessed the app via a different domain by adding the Host() mask to the rule of the router.
The snippet of the config is below. app.eliminyro.com is working while viceartur.me does not.

I would really appreciate if you could take a look at this. The issue seems bizarre (at least to me), and I am not sure it can be solved on my side.

Thanks.

### What did you see instead?

404 error instead of a proper page of the application.

### What version of Traefik are you using?

Tested with 2.4.14 and latest (2.5.3)

### What is your environment & configuration?

```yaml
http:
  routers:
    viceartur:
      entryPoints: https
      rule: "Host(`app.eliminyro.com`) || Host(`viceartur.me`)"
      service: viceartur
      tls: {}
      middlewares: chain-no-auth@file
  services:
   viceartur:
      loadBalancer:
        servers:
          - url: 'http://viceartur'
```
