### ISSUE TITLE
Mapping port 22, gives random port instead

### ISSUE THREAD

**Issue by sudocraft** [traefik/traefik#8475]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Trying to map port 22 ( I already change host's sshd_config to 222)

    ports:
      - 22:22

      - --entrypoints.ssh.address=:22/tcp

### What did you see instead?

There is no error message, but instead Traefik gives out a random port number:

.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:49163->1342/tcp, :::49163->1342/tcp

### What version of Traefik are you using?

traefik:v2.3

### What is your environment & configuration?

```
Ubuntu 20.04, docker.io docker-compose 
```
```
version: '3.3'
services:
  traefik:
    image: traefik:v2.3
    restart: always
    ports:
      - 22:22
      - 80:80
      - 443:443
    labels:
      - traefik.enable=true
      - traefik.swarmmode=false
      - traefik.docker.network=traefik-public
      # - traefik.http.middlewares.admin-auth.basicauth.users= # htpasswd
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.traefik-public-http.rule=Host(``)
      - traefik.http.routers.traefik-public-http.entrypoints=http
      - traefik.http.routers.traefik-public-http.middlewares=https-redirect
      - traefik.http.routers.traefik-public-https.rule=Host(``)
      - traefik.http.routers.traefik-public-https.entrypoints=https
      - traefik.http.routers.traefik-public-https.tls=true
      - traefik.http.routers.traefik-public-https.service=api@internal
      - traefik.http.routers.traefik-public-https.tls.certresolver=le
      # - traefik.http.routers.traefik-public-https.middlewares=admin-auth
      - traefik.http.services.traefik-public.loadbalancer.server.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates
      - /var/log/traefik:/var/log/traefik
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.ssh.address=:22/tcp
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog=true
      - --accesslog.filepath=/var/log/traefik/access.log
      - --log
      - --api
    networks:
      - traefik-public
 
volumes:
  traefik-public-certificates:
 
networks:
  traefik-public:
    external: true
```
Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

traefik_1  | time="2021-09-28T16:44:51Z" level=info msg="Configuration loaded from flags."
