### ISSUE TITLE
Outdated Documentation or Wrong Configuration to enable http3?

### ISSUE THREAD

**Issue by jerrywoo96** [traefik/traefik#8479]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Try to enable http3 by following the instructions in this URL:
https://doc.traefik.io/traefik/master/routing/entrypoints/#http3_1

![image](https://user-images.githubusercontent.com/26324139/135309744-c5d1491f-0109-42d6-ae48-b49c38ace685.png)

### What did you see instead?

![image](https://user-images.githubusercontent.com/26324139/135309652-dd97c0a4-b105-49f9-92c6-4cd26a58c3f0.png)

### What version of Traefik are you using?

Version:      2.5.3
Codename:     livarot
Go version:   go1.17.1
Built:        2021-09-20T15:43:56Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /Certificates/fullchain.pem
        keyFile: /Certificates/privkey.pem
  certificates:
  - certFile: /Certificates/fullchain.pem
    keyFile: /Certificates/privkey.pem
    stores:
    - default
  options:
    default:
      sniStrict: true
      minVersion: VersionTLS12
      preferServerCipherSuites: true
      alpnProtocols:
      - h2
      cipherSuites:
      - TLS_AES_256_GCM_SHA384
      - TLS_CHACHA20_POLY1305_SHA256
      - TLS_RSA_WITH_AES_256_CBC_SHA
      curvePreferences:
      - X25519
      - CurveP521
      - CurveP384

experimental:
  http3: true

entryPoints:

  websecure:
    address: ':30443'
    http3: {}
    http:
      tls:
        options: default
    forwardedHeaders:
      insecure: true

```

Add more configuration information here.
