### ISSUE TITLE
Unable to set sticky cookie with Docker Swarm

### ISSUE THREAD

**Issue by richardtc** [traefik/traefik#8546]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Hi,
I'm having some trouble setting a sticky cookie for docker swarm.

I created an overlay and ran the following commands (yml file configurations below):

        docker network create -d overlay --attachable test_net2
        docker stack deploy -c docker-compose-traefik.yml 9c9t
        docker stack deploy -c docker-compose-shinyapp.yml 9c9t

Within the traefik api (http://en.localexample.com:9020/) I can see that the cookie is enabled (for http only as I am testing this on my laptop, with the domain specified as en.localexample.com for 127.0.0.2 in /etc/hosts)

![image](https://user-images.githubusercontent.com/1285650/139533469-12179469-1131-42e6-ac12-a792fc5710fc.png)

### What did you see instead?

I'd expect to see the cookie on visiting the page at http://en.localexample.com:3838/ in the web developer tool of the Chrome browser, but it is missing:

![image](https://user-images.githubusercontent.com/1285650/139533519-f24de9e0-e8bf-4c95-9377-64bb0b7d6abb.png)

Also no evidence of a cookie with curl:

            $ curl -v http://en.localexample.com:3838
            * Rebuilt URL to: http://en.localexample.com:3838/
            *   Trying 127.0.0.2...
            * TCP_NODELAY set
            * Connected to en.localexample.com (127.0.0.2) port 3838 (#0)
            > GET / HTTP/1.1
            > Host: en.localexample.com:3838
            > User-Agent: curl/7.58.0
            > Accept: */*
            > 
            < HTTP/1.1 200 OK
            < Date: Sat, 30 Oct 2021 13:16:25 GMT
            < X-UA-Compatible: IE=edge,chrome=1
            < Content-Type: text/html; charset=UTF-8
            < Content-Length: 187094

### What version of Traefik are you using?

traefik 2.5.3

Version:      2.5.3
Codename:     livarot
Go version:   go1.17.1
Built:        2021-09-20T15:43:56Z
OS/Arch:      linux/amd64

docker --version
Docker version 20.10.10, build b485636

### What is your environment & configuration?

```yaml
My docker-compose-traefik.yml file:

        version: "3.7"
         services:
           traefik:
             image: traefik:latest
             deploy:
               restart_policy:
                 condition: any
               placement:
                 constraints:
                   - node.role == manager
               labels:
               - "traefik.http.services.traefik.loadbalancer.server.port=80"
             command: 
               - "--log.level=DEBUG"
               - "--api.insecure=true"
               - "--providers.docker=true"
               - "--providers.docker.swarmMode=true"
               - "--providers.docker.exposedbydefault=false"
               - "--entrypoints.web.address=:80"
             ports:
               - "80:80"
               - "9020:8080"
             volumes:
               - "/var/run/docker.sock:/var/run/docker.sock:ro"
             networks:
               - test_net2     
         networks:
           test_net2:
             driver: overlay
             external: true


My docker-compose-shinyapp.ylm file:

             version: "3.7"
             services:    
               dataservice:
                 image: sustainableos/shiny:9c9t_r4051_ub2004
               #   ports:
               #  - "3838:3838" 
                 deploy:
                   replicas: 5
                   labels:
                     - "traefik.enable=true"
                     - "traefik.http.routers.dataservice.rule=Host(`en.localexample.com`)"
                     - "traefik.http.routers.dataservice.entrypoints=web"
                     - "traefik.http.services.dataservice.loadbalancer.server.port=3838"
                     - "traefik.http.services.dataservice.loadbalancer.sticky=true"
                     - "traefik.http.services.dataservice.loadbalancer.sticky.cookie.name=stickycookie"       
                     - "traefik.http.services.dataservice.loadbalancer.sticky.cookie.secure=false"
                     - "traefik.http.services.dataservice.loadbalancer.sticky.cookie.httpOnly=true"
                   restart_policy:
                     condition: on-failure
                   update_config:
                     delay: 2s
                 volumes:
                   - /home/shiny/webapps/9c9t:/home/shiny/webapps/9c9t
            
                 networks:
                   - test_net2         
             networks:
               test_net2:
                 driver: overlay
                 external: true


```
