### ISSUE TITLE
Forbidden returned when trying to curl/request an url behind traefik

### ISSUE THREAD

**Issue by jules-datascientest** [traefik/traefik#8548]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

When I do `https://qbittorrent.MYDOMAIN.TLD/api/v2/app/webapiVersion` on my browser I get the version (2.8.2).

But when I curl it (`curl https://qbittorrent.MYDOMAIN.TLD/api/v2/app/webapiVersion`) on the server itself or on my machine I get a `Forbidden.`

 Can't figure out what the issue is.... I've tried adding cors but it didn't seem to work ?

### What did you see instead?

```
xxx@xxx:/home/data$ curl -v https://qbittorrent.MYDOMAIN.TLD/api/v2/app/webapiVersion
*   Trying x.x.x.x:443...
* TCP_NODELAY set
* Connected to qbittorrent.MYDOMAIN.TLD (x.x.x.x) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=qbittorrent.MYDOMAIN.TLD
*  start date: Oct 27 04:40:42 2021 GMT
*  expire date: Jan 25 04:40:41 2022 GMT
*  subjectAltName: host "qbittorrent.MYDOMAIN.TLD" matched cert's "qbittorrent.MYDOMAIN.TLD"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55b6ec996e10)
> GET /api/v2/app/webapiVersion HTTP/2
> Host: qbittorrent.MYDOMAIN.TLD
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 403 
< content-security-policy: default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src 'self' 'unsafe-inline'; object-src 'none'; form-action 'self'; frame-ancestors 'self';
< content-type: text/plain; charset=UTF-8
< date: Wed, 03 Nov 2021 15:27:27 GMT
< referrer-policy: same-origin
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< content-length: 9
< 
* Connection #0 to host qbittorrent.MYDOMAIN.TLD left intact
```

Still seems like a CORS issue ?

### What version of Traefik are you using?

```
Version:      2.5.3
Codename:     livarot
Go version:   go1.17.1
Built:        2021-09-20T15:43:56Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

Traefik config:
```yaml
[api]
  dashboard = true

[entryPoints.web]
  address = ":80"

  [entryPoints.web.http]
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"

[entryPoints.websecure]
  address = ":443"

[certificatesResolvers.leresolver.acme]
  email = "xxx"
  storage = "acme.json"
  [certificatesResolvers.leresolver.acme.httpChallenge]
    entryPoint = "web"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false
  network = "traefik_network"
  watch = true
```

docker-compose (shortened with only the important bits):

```yaml
version: '3.8'

services:

  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    command:
      - --accesslog.fields.names.StartUTC=drop
      - --api=true
    networks:
      - traefik_network
    depends_on:
      - authelia
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.MYDOMAIN.TLD`)
      - traefik.http.routers.api.entrypoints=web,websecure
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=leresolver
      - traefik.http.routers.api.middlewares=authelia@docker
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/data/config/traefik/traefik.toml:/traefik.toml:ro
      - /home/data/config/traefik/acme.json:/acme.json

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Paris
      - WEBUI_PORT=9080
      - UMASK=022
    ports:
      - '47989:47989'
      - '47989:47989/udp'
      - '9080:9080'
    expose:
      - '9080'
    networks:
      - traefik_network
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_network
      - traefik.http.routers.qbittorrent.entrypoints=web,websecure
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.MYDOMAIN.TLD`)
      - traefik.http.services.qbittorrent.loadbalancer.server.port=9080
      - traefik.http.routers.qbittorrent.tls=true
      - traefik.http.routers.qbittorrent.tls.certresolver=leresolver
      - traefik.http.routers.qbittorrent.middlewares=authelia@docker
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - /home/data/config/qbittorrent:/config
      - /home/data/torrents:/torrents

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    networks:
      - traefik_network
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`authelia.MYDOMAIN.TLD`)"
      - "traefik.http.routers.authelia.entrypoints=web,websecure"
      - "traefik.http.routers.authelia.tls=true"
      - "traefik.http.routers.authelia.tls.certresolver=leresolver"
      - "traefik.http.routers.authelia.service=authelia-svc"
      - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://authelia.MYDOMAIN.TLD/"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email"
      - "traefik.http.middlewares.authelia-basic.forwardauth.address=http://authelia:9091/api/verify?auth=basic"
      - "traefik.http.middlewares.authelia-basic.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia-basic.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email"
    expose:
      - 9091
    volumes:
      - /home/data/config/authelia:/config

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - /home/data/config/redis:/data
    networks:
      - traefik_network
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris

networks:
  traefik_network:
    external: true
  cloudflare:
    external: false
```

and Authelia config just in case (with some config removed for services not related to the error)

```yaml
totp:
  issuer: authelia.com
  period: 30
  skew: 1

# Create "Partner Auth API" type Duo app and uncomment below and paste the generated "hostname", "integration_key" and "secret_key" below:
#duo_api:
#  hostname: api-123456789.MYDOMAIN.TLD
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 128 # blocks this much of the RAM. Tune this.


access_control:
  default_policy: deny
  rules:
    #### BYPASS ####
    - domain: 
      - 'qbittorrent.MYDOMAIN.TLD'
      policy: bypass
    #### TWO-FACTOR ####
    - domain: 
      - 'traefik.MYDOMAIN.TLD'
      policy: two_factor


session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: unsecure_session_secret
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: MYDOMAIN.TLD # Should match whatever your root protected domain is

  redis:
    host: redis
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:

  filesystem:
    filename: /config/notification.txt

#  smtp:
#    username: <your-user@your-email-domain.org>
#    password: <your-user-email-password-for-smtp>
#    host: <your-email-host-url-or-ip>
#    port: <your-email-port-for-smtp>  # 25 non-ssl, 443 ssl, 587 tls
#    sender: <sender@your-email-domain.org>
#    subject: "[Authelia] {title}"
#    disable_require_tls: false # set to true if your domain uses no tls or ssl only
#    disable_html_emails: false # set to true if you don't want html in your emails
#    tls:
#      server_name: <your-email-host-url-or-ip>
#      skip_verify: false
#      minimum_version: TLS1.2
```
