### ISSUE TITLE
Traefik's docker provider does not read `Config.ExposedPorts` for port information

### ISSUE THREAD

**Issue by eduarrrd** [traefik/traefik#8551]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

**Setup**: Traefik has external access via default bridge network. Furthermore, traefik and $backend are on the a second bridge network with property internal=false.

**Situation**: Traefik correctly finds the service, creates router, routes traffic.

**Action**: That bridge network was switched to internal=true.

**Expectation**: Everything works as before from a traefik perspective. If there's any issue it would affect the backend only.

**Justification for expectation**: In https://doc.traefik.io/traefik/providers/docker/#port-detection it says

> If a container exposes a single port, then Traefik uses this port for private communication.

... and nothing about the container changed.

From `docker inspect`:
```json
[
    {
        "Id": "a537f16c81779cffb74e72f80aef576d9412a9e2e3a4b9800f3fed45229272da",
        "Path": "tini",
        "Args": [
            "-g",
            "--",
            "jupyter",
            "lab",
            "--LabApp.token="
        ],
        "State": {
            "Status": "running",
           ...
        },
        "Name": "/jupyterlab_jupyterlab_1",
         ...
              "Config": {
            "Hostname": "a537f16c8177",
            "Domainname": "",
            "User": "1000",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8888/tcp": {} # <<<<<<<<
            },
            "Tty": false,
           ...
        }
    }
]

```

### What did you see instead?

Traefik complains that `port is missing`. Does not create service/router. As per documentation above this is a bug.

## Reason

Reading the code it appears to me that in https://sourcegraph.com/github.com/traefik/traefik@85dd45cb817a017441bdafd92cdaeb360f196ce8/-/blob/pkg/provider/docker/docker.go?L407:1&subtree=true traefik reads only the portmap from `NetworkSettings.Ports` (which is becomes empty when setting internal=true on the network the container is in) but the not the exposed ports from `Config.ExposedPorts` (see API doc at https://docs.docker.com/engine/api/v1.41/#operation/ContainerInspect).

This is a bug in either the docker provider or the documentation.

### What version of Traefik are you using?

Version:      2.5.3
Codename:     livarot
Go version:   go1.17.1
Built:        2021-09-20T15:43:56Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

traefik:
```yaml
services:
        traefik:
                image: traefik
                restart: always
                ports:
                        - "80:80"
                        - "443:443"
                healthcheck:
                        test: traefik healthcheck
                volumes:
                        - ./traefik.toml:/traefik.toml
                        - ./traefik-dynamic.toml:/traefik-dynamic.toml
                        - # redacted
                networks:
                        - jupyterlab_default

networks:
        jupyterlab_default:
                external: true
```

backend:
```yaml
services:
  jupyterlab:
    image: jupyter/scipy-notebook
    restart: unless-stopped
    environment:
      - "JUPYTER_ENABLE_LAB=yes"
    command: "jupyter lab --LabApp.token=''"
    volumes:
      - # redacted
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jupyerlab.rule=Host(`jupyterlab.domain`)'
      - 'traefik.http.routers.jupyerlab.entrypoints=https'
      - 'traefik.http.routers.jupyerlab.tls=true'

networks:
  default:
    internal: false # set this to true to trigger
```

```toml
[serversTransport]
    InsecureSkipVerify = true

[api]
    dashboard = true
    insecure = true
    debug = true

[entryPoints]
    [entryPoints.http]
      address = ":80"

      [entryPoints.http.http]
        [entryPoints.http.http.redirections]
          [entryPoints.http.http.redirections.entryPoint]
            to = "https"
            scheme = "https"

    [entryPoints.https]
      address = ":443"
      [entryPoints.https.http.tls]
        certResolver = "default"
        [options]
          minVersion = "VersionTLS12"

[retry]

[log]
    level = "DEBUG"
    format = "json"

[providers.docker]
    watch = true
    exposedByDefault = false

[providers.file]
    filename = "traefik-dynamic.toml"

[metrics]
    [metrics.prometheus]

[accessLog]
    format = "json"

[ping]

[tracing]
  [tracing.jaeger]
    localAgentHostPort = "jaeger:6831"
    samplingServerURL = "http://jaeger:5778/sampling"
```

```toml
[tls.stores]
  [tls.stores.default]
   [tls.stores.default.defaultCertificate] 
     certFile = '/tls.crt' 
     keyFile = '/tls.key'

 [[tls.certificates]]
    certFile = "tls.crt"
    keyFile = "tls.key"
 [[tls.certificates]]
    certFile = "tls2.crt"
    keyFile = "tls2.key"
  stores = ["default"]


[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS13"
    sniStrict = true
  [tls.options.min12]
    minVersion = "VersionTLS12"
    sniStrict = true
```

### If applicable, please paste the log output in DEBUG level

```
traefik_1  | {"container":"jupyterlab-jupyterlab-46d283750ec84b14e3ee6ddd392964fdd7...hash","level":"error","msg":"service \"jupyterlab-jupyterlab\" error: port is missing","providerName":"docker","time":"2021-11-03..."}
```
