### ISSUE TITLE
Sticky with "networking.k8s.io/v1" does not work

### ISSUE THREAD

**Issue by A1994SC** [traefik/traefik#8569]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Applied the following `annotations` to a "whoami" ingress    
```yaml
traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
traefik.ingress.kubernetes.io/service.sticky.cookie.name: "sticky"
traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
traefik.ingress.kubernetes.io/service.sticky.cookie.samesite: "lax"
traefik.ingress.kubernetes.io/service.sticky.cookie.httponly: "true" 
```

Helm `values.yaml`
```yaml
image:
  name: traefik
  tag: ""
  pullPolicy: Always

deployment:
  enabled: true
  kind: DaemonSet
  repicas: 1
  annotations: {}
  labels: {}
  podAnnotations: {}
  podLabels: {}
  additionalContainers: []
  additionalVolumes: []
  initContainers: []
  imagePullSecrets: []

podDisruptionBudget:
  enabled: false

ingressClass:
  enabled: true
  isDefaultClass: false

pilot:
  enabled: true
  token: "<>"
  
experimental:
  plugins:
    enabled: true
  kubernetesGateway:
    enabled: false
    appLabelSelector: "traefik"
    certificates: []

ingressRoute:
  dashboard:
    enabled: false

rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    namespaces: []
  kubernetesIngress:
    enabled: true
    namespaces: []
    publishedService:
      enabled: false

logs:
  general:
    level: ERROR
  access:
    enabled: true
    filters:
      minduration: 2ms
    fields:
      general:
        defaultmode: keep
        names: {}
          # Examples:
          # ClientUsername: drop
      headers:
        defaultmode: drop
        names: {}

metrics:
  prometheus:
    entryPoint: metrics

globalArguments:
  - "--global.checknewversion"
  
ports:
  traefik:
    port: 9000
    expose: false
    exposedPort: 9000
    protocol: TCP
  web:
    port: 8000
    hostPort: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
    redirectTo: websecure
  websecure:
    port: 8443
    hostPort: 8443
    expose: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: false
  metrics:
    port: 9100
    expose: false
    exposedPort: 9100
    protocol: TCP

service:
  enabled: true
  type: LoadBalancer
  spec: {
    externalTrafficPolicy: Local,
    loadBalancerIP: "10.2.25.150"
  }

podSecurityPolicy:
  enabled: false

nodeSelector:
  node-role.kubernetes.io/master: "true"

```

### What did you see instead?

The `hostname` field changes on each refresh and `Cookie` field is never created.

### What version of Traefik are you using?

traefik:2.5.3

### What is your environment & configuration?

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  namespace: tools
  annotations:
    # default settings
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: "routes-default-header@kubernetescrd"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/service.passhostheader: "true"
    # sticky session
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "sticky"
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.samesite: "lax"
    traefik.ingress.kubernetes.io/service.sticky.cookie.httponly: "true"
spec:
  defaultBackend:
    service:
      name: whoami
      port:
        name: web
  rules:
  - host: whoami.domain.com
    http:
      paths:
      - backend:
          service:
            name: whoami
            port:
              name: web
        path: /
        pathType: Prefix
  tls:
  - secretName: secret
```

Add more configuration information here.
