### ISSUE TITLE
Weird basic auth behavior 

### ISSUE THREAD

**Issue by manuliner** [traefik/traefik#8571]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

i use a docker-compose file to handle my services on my server. I tried to add a new service ( basic website) and protect it with base auth. During this i recognized some weird behavior which i can't  explain my self. 

i have one docker-compose file to start my docker container with the website.

When i start the container with:

`BASIC_AUTH_PW =koelscheVita:$$2y$$05$$Wvx3ethoh8o91BytZ8gcPehF2m9puesLUPT2bmiTf4uZfxx6Ok7DK `  it works fine.

But when i start the container with  `BASIC_AUTH_PW=koelscheVita:$$2y$$05$$DUGa3J2TC4Gi.NE4dPinGOIXQzGrmdHq59/DG8i3FpJ3Mm/uiVnOW`  or any other htpasswd generated with  `echo $(htpasswd -nbB user "passwd") | sed -e s/\\$/\\$\\$/g`  i will get and 404 on the domain

``` yml

version: "3.3"

services:
  app:
    image: "gitlab.com:5050/myrepo/devs/website:dev"
    container_name: "website"    
    mem_limit: "1g"      
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"      
      - "traefik.http.middlewares.admin-auth.basicauth.users=BASIC_AUTH_PW"
      - "traefik.http.middlewares.website_redirect.redirectscheme.permanent=true"
      - "traefik.http.middlewares.website_redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.website-http.middlewares=website_redirect"    
      - "traefik.http.routers.website-http.entrypoints=http"            
      - "traefik.http.routers.website-http.rule=Host(`WEBSITEDOMAIN`)"
      - "traefik.http.routers.website-https.entrypoints=https"            
      - "traefik.http.routers.website-https.middlewares=admin-auth"
      - "traefik.http.routers.website-https.rule=Host(`WEBSITEDOMAIN`)"
      - "traefik.http.routers.website-https.tls.certresolver=le"
      - "traefik.http.routers.website-https.tls=true"
      - "traefik.http.routers.website-https.service=website_service"
      - "traefik.http.services.website_service.loadbalancer.server.port=8080"          
    networks:
      traefik-public:
        ipv4_address: "172.18.0.10"    
    restart: unless-stopped
volumes:
  traefik-public-certificates:
    name: traefik-public-certificates
    external: true
networks:
  traefik-public:
    external: true

```

### What did you see instead?

traefik and website container won't start up when using new generated htpasswd.
Works only with one specific htpasswd

### What version of Traefik are you using?

Version:      2.5.4
Codename:     livarot
Go version:   go1.17.3
Built:        2021-11-08T17:41:41Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.
