### ISSUE TITLE
Traefik:v2.4 with letsencrypt/pebble

### ISSUE THREAD

**Issue by mstaicu** [traefik/traefik#8574]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Running a single node, local k8s cluster, with all resources in the same namespace, trying to get `traefik` to talk to `letsencrypt/pebble` to automate the certificate issuance in order to have a local development setup that runs over TLS, but I cannot get `traefik` to get the CA root certificates with which `pebble` signs its own leaf certificates and the newly requested certificates via ACME clients, such as `lego` which is part of `traefik` AFAIK ( if this is not the case, I apologies )

I also mention that I was led to believe that you can instruct `traefik` to reach out via HTTP and update its root CA store by using the two environment variables. Note that I have no other ideas on how a pod would reach out to another pod and get the root CA from there

### What did you see instead?

There's a 50:50 changes that either I might have missed the relevant documentation, or `traefik`'s documentation is incomplete with regards to this aspect. I get an error when using these two environment variables with `traefik`

The logs:

```
time="2021-11-12T14:13:17Z" level=error msg="Error in Go routine: error reading LEGO_CA_CERTIFICATES=\"/test/certs/pebble.minica.pem\": open /test/certs/pebble.minica.pem: no such file or directory"
time="2021-11-12T14:13:17Z" level=error msg="Stack: goroutine 237 [running]:\nruntime/debug.Stack(0xc0000ee000, 0x343d39a, 0x17)\n\t/usr/local/golang/1.10.8/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine(0x2d182e0, 0xc0008f6080)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/safe/routine.go:66 +0xb4\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1.1(0x3558ca8)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/safe/routine.go:56 +0x5a\npanic(0x2d182e0, 0xc0008f6080)\n\t/usr/local/golang/1.10.8/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/go-acme/lego/v4/lego.initCertPool(0x3430059)\n\t/home/semaphore/go/pkg/mod/github.com/go-acme/lego/v4@v4.4.0/lego/client_config.go:93 +0x3a5\ngithub.com/go-acme/lego/v4/lego.createDefaultHTTPClient(0xc0005c0540)\n\t/home/semaphore/go/pkg/mod/github.com/go-acme/lego/v4@v4.4.0/lego/client_config.go:78 +0x53\ngithub.com/go-acme/lego/v4/lego.NewConfig(...)\n\t/home/semaphore/go/pkg/mod/github.com/go-acme/lego/v4@v4.4.0/lego/client_config.go:49\ngithub.com/traefik/traefik/v2/pkg/provider/acme.(*Provider).getClient(0xc00004c3c0, 0x0, 0x0, 0x0)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/provider/acme/provider.go:232 +0x32a\ngithub.com/traefik/traefik/v2/pkg/provider/acme.(*Provider).resolveCertificate(0xc00004c3c0, 0x399b060, 0xc0009fc2a0, 0xc0003fd710, 0x9, 0x0, 0x0, 0x0, 0x3408d6e, 0x7, ...)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/provider/acme/provider.go:472 +0x2b6\ngithub.com/traefik/traefik/v2/pkg/provider/acme.(*Provider).watchNewDomains.func1.2()\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/provider/acme/provider.go:433 +0xc5\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1(0x3558ca8, 0xc0008fc500)\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/safe/routine.go:59 +0x4f\ncreated by github.com/traefik/traefik/v2/pkg/safe.GoWithRecover\n\t/home/semaphore/go/src/github.com/traefik/traefik/pkg/safe/routine.go:53 +0x49\n"
```

So, how does one use the `LEGO_CA_SERVER_NAME` and `LEGO_CA_CERTIFICATES`?

### What version of Traefik are you using?

```
Version:      2.4.14
Codename:     livarot
Go version:   go1.16.7
Built:        2021-08-16T15:29:25Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

`traefik`'s deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.4
          env:
            - name: LEGO_CA_SERVER_NAME
              value: pebble
            - name: LEGO_CA_CERTIFICATES
              value: /test/certs/pebble.minica.pem
          args:
            - --api=true
            - --api.dashboard=true

            - --accesslog

            - --entrypoints.http.address=:80
            - --entrypoints.https.address=:443

            #
            # Email address used for registration.
            #
            # Required
            #
            - --certificatesresolvers.le.acme.email=stuff@gmail.com
            #
            # Use a HTTP-01 ACME challenge.
            #
            # Optional (but recommended)
            #
            - --certificatesresolvers.le.acme.httpchallenge=true
            #
            # EntryPoint to use for the HTTP-01 challenges.
            #
            # Required
            #
            - --certificatesresolvers.le.acme.httpchallenge.entrypoint=http
            #
            - --certificatesresolvers.le.acme.caserver=https://pebble/dir

            - --providers.kubernetescrd
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-srv
spec:
  type: ClusterIP
  selector:
    app: traefik
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-lb-srv
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: client-ingress-route-https
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`ticketing`)
      kind: Rule
      services:
        - name: client-srv
          port: 3000
  tls:
    certResolver: le
    domains:
      - main: ticketing
```

`pebble`'s deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pebble-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pebble
  template:
    metadata:
      labels:
        app: pebble
    spec:
      containers:
        - name: pebble
          image: letsencrypt/pebble
          env:
            # https://github.com/letsencrypt/pebble#testing-at-full-speed
            - name: PEBBLE_VA_NOSLEEP
              value: "1"
            # https://github.com/letsencrypt/pebble#skipping-validation
            - name: PEBBLE_VA_ALWAYS_VALID
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: pebble-srv
spec:
  type: ClusterIP
  selector:
    app: pebble
  ports:
    - name: pebble-http-api
      protocol: TCP
      port: 80
      targetPort: 14000
    - name: pebble-https-api
      protocol: TCP
      port: 443
      targetPort: 14000
```

**Comment by mstaicu** [comment]
Right, I got to this point

```
time="2021-11-12T14:37:47Z" level=error msg="Unable to obtain ACME certificate for domains \"ticketing\" : cannot get ACME client get directory at 'https://pebble/dir': Get \"https://pebble/dir\": x509: certificate signed by unknown authority" providerName=le.acme
```

With these new deployments

`traefik`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.4
          env:
            - name: LEGO_CA_SERVER_NAME
              value: pebble
            # - name: LEGO_CA_CERTIFICATES
            #   value: test/certs/pebble.minica.pem
          args:
            - --api=true
            - --api.dashboard=true

            - --accesslog

            - --entrypoints.http.address=:80
            - --entrypoints.https.address=:443

            #
            # Email address used for registration.
            #
            # Required
            #
            - --certificatesresolvers.le.acme.email=stuff@gmail.com
            #
            # Use a HTTP-01 ACME challenge.
            #
            # Optional (but recommended)
            #
            - --certificatesresolvers.le.acme.httpchallenge=true
            #
            # EntryPoint to use for the HTTP-01 challenges.
            #
            # Required
            #
            - --certificatesresolvers.le.acme.httpchallenge.entrypoint=http
            #
            - --certificatesresolvers.le.acme.caserver=https://pebble/dir

            - --providers.kubernetescrd
---
#
# Service to service communication endpoint
#
apiVersion: v1
kind: Service
metadata:
  name: traefik-srv
spec:
  type: ClusterIP
  selector:
    app: traefik
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
#
# Cluster gateway
#
apiVersion: v1
kind: Service
metadata:
  name: traefik-lb-srv
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
#
# Router configs
#
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: client-ingress-route-https
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`ticketing`)
      kind: Rule
      services:
        - name: client-srv
          port: 3000
  tls:
    certResolver: le
    domains:
      - main: ticketing
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: client-ingress-route-http
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`ticketing`)
      kind: Rule
      #
      # TODO: Route the requests TO the client to HTTPS if they're done by a client from HTTP
      # I think this is not necessary as when the client makes a request to Traefik via its ClusterIP
      # it will communicate via HTTP, so I think we can activate all communications to the client from the outside world
      # to use HTTPS, as the client will always communicate with Traefik via its HTTP ClusterIP endpoint
      #
      # middlewares:
      #   - name: client-ingress-route-redirect-https
      services:
        - name: client-srv
          port: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: auth-ingress-route-https
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`ticketing`) && PathPrefix(`/api/auth`)
      kind: Rule
      middlewares:
        - name: strip-auth-prefix
      services:
        - name: auth-srv
          port: 3000
  tls:
    certResolver: le
    domains:
      - main: ticketing
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: auth-ingress-route-http
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`ticketing`) && PathPrefix(`/api/auth`)
      kind: Rule
      middlewares:
        - name: strip-auth-prefix
      services:
        - name: auth-srv
          port: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ticket-ingress-route-https
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`ticketing`) && PathPrefix(`/api/tickets`)
      kind: Rule
      middlewares:
        - name: strip-ticket-prefix
      services:
        - name: tickets-srv
          port: 3000
  tls:
    certResolver: le
    domains:
      - main: ticketing
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ticket-ingress-route-http
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`ticketing`) && PathPrefix(`/api/tickets`)
      kind: Rule
      middlewares:
        - name: strip-ticket-prefix
      services:
        - name: tickets-srv
          port: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: order-ingress-route-https
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`ticketing`) && PathPrefix(`/api/orders`)
      kind: Rule
      middlewares:
        - name: strip-order-prefix
      services:
        - name: orders-srv
          port: 3000
  tls:
    certResolver: le
    domains:
      - main: ticketing
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: order-ingress-route-http
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`ticketing`) && PathPrefix(`/api/orders`)
      kind: Rule
      middlewares:
        - name: strip-order-prefix
      services:
        - name: orders-srv
          port: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: payments-ingress-route-https
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`ticketing`) && PathPrefix(`/api/payments`)
      kind: Rule
      middlewares:
        - name: strip-payments-prefix
      services:
        - name: payments-srv
          port: 3000
  tls:
    certResolver: le
    domains:
      - main: ticketing
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: payments-ingress-route-http
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`ticketing`) && PathPrefix(`/api/payments`)
      kind: Rule
      middlewares:
        - name: strip-payments-prefix
      services:
        - name: payments-srv
          port: 3000
---
#
# TODO: Secure the dashboard access
#
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`ticketing`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      kind: Rule
      # Lower the priority of this router in order to allow priority to our api routes
      priority: 40
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    certResolver: le
    domains:
      - main: ticketing
#
# Middlewares
#
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-auth-prefix
spec:
  stripPrefix:
    prefixes:
      - /api/auth
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-ticket-prefix
spec:
  stripPrefix:
    prefixes:
      - /api/tickets
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-order-prefix
spec:
  stripPrefix:
    prefixes:
      - /api/orders
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-payments-prefix
spec:
  stripPrefix:
    prefixes:
      - /api/payments
```

`pebble`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pebble-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pebble
  template:
    metadata:
      labels:
        app: pebble
    spec:
      containers:
        - name: pebble
          image: letsencrypt/pebble
          env:
            # https://github.com/letsencrypt/pebble#testing-at-full-speed
            - name: PEBBLE_VA_NOSLEEP
              value: "1"
            # https://github.com/letsencrypt/pebble#skipping-validation
            - name: PEBBLE_VA_ALWAYS_VALID
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: pebble
spec:
  type: ClusterIP
  selector:
    app: pebble
  ports:
    - name: pebble-http-api
      protocol: TCP
      port: 80
      targetPort: 14000
    - name: pebble-https-api
      protocol: TCP
      port: 443
      targetPort: 14000
```
