### ISSUE TITLE
Can not visit two sites in one browser at the same time

### ISSUE THREAD

**Issue by fwt11** [traefik/traefik#8576]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I deployed gitea and harbor on one machine with traefik as the proxy. 

### What did you see instead?

But I can not visit these two site as the same time in one browser. After I visit gitea, all requests will be transfered to gitea. But I can visit these two site in two browser at the same time.

### What version of Traefik are you using?

traefik docker image version v2.5 

### What is your environment & configuration?

```yaml

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    # Enables the web UI and tells Traefik to listen to docker
    command: 
    - --api.insecure=true 
    - --providers.docker 
    - --entrypoints.web.address=:80
    - --entrypoints.websecure.address=:443
    - --log
    - --accesslog
    - --log.level=DEBUG
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8000:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
    - traefik-public
networks:
  traefik-public:
    external: true
```

gitea config
```yaml
server:
    labels:
      - traefik.http.routers.gitea.entrypoints=web
      - traefik.http.routers.gitea.rule=Host(`git.abc.com`)
      - traefik.http.routers.gitea.service=gitea
      - traefik.http.services.gitea.loadbalancer.server.port=3000

      - traefik.tcp.routers.gitea.entrypoints=websecure
      - traefik.tcp.routers.gitea.rule=HostSNI(`git.abc.com`)
      - traefik.tcp.routers.gitea.service=gitea
      - traefik.tcp.routers.gitea.tls.passthrough=true
      - traefik.tcp.services.gitea.loadbalancer.server.port=3443
```

harbor config
```yaml
  proxy:
    labels:
    - traefik.http.routers.proxy.entrypoints=web
    - traefik.http.routers.proxy.rule=Host(`hub.abc.com`)
    - traefik.http.routers.proxy.service=proxy@docker
    - traefik.http.services.proxy.loadbalancer.server.port=8080
    - traefik.tcp.routers.proxy.entrypoints=websecure
    - "traefik.tcp.routers.proxy.rule=HostSNI(`hub.abc.com`)"
    - traefik.tcp.routers.proxy.service=proxy@docker
    - "traefik.tcp.routers.proxy.tls.passthrough=true"
    - "traefik.tcp.services.proxy.loadbalancer.server.port=8443"

```
