### ISSUE TITLE
X-Forwarded-Prefix is not used/recognized by dashboard

### ISSUE THREAD

**Issue by Muchaszewski** [traefik/traefik#8578]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

By adding PathPrefix to the dashboard and adding middleware that should strip this prefix should result in a working dashboard via a path in the prefix. 

The full request path should be used in the dashboard to make requests instead of the relative path to the server. If the server is generating js files in runtime X-Forwarded-Prefix should be used to reconstruct the path of the API routes

### What did you see instead?

404 on all API calls as they are routed to `/api/*` instead of `/traefik/api/*`

### What version of Traefik are you using?

Version:      2.5.4
Codename:     livarot
Go version:   go1.17.3
Built:        2021-11-08T17:41:41Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```
version: '3.8'
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`example.com`) && PathPrefix(`/traefik`)"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/traefik"
      - "traefik.http.routers.api.middlewares=api-stripprefix"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
```
