### ISSUE TITLE
Cannot add more then 1 domain for sidecar injection (Consul-Traefik)

### ISSUE THREAD

**Issue by dev852com** [traefik/traefik#8595]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Cannot add more then 1 domain for sidecar injection

traefik.http.routers.app-https.rule=Host(`example1.com`,`www.example1.com`) 

This does not work with consul traefik sidecar injection

```yaml
consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/service-tags: "\
          traefik.enable=true,\
          traefik.http.routers.wordpress-http.entrypoints=web,\
          traefik.http.routers.wordpress-http.middlewares=https-redirect,\
          traefik.http.routers.wordpress-http.rule=Host(`example1.com`,`www.example1.com`),\
          traefik.http.routers.wordpress-https.rule=Host(`example1.com`,`www.example1.com`),\
          traefik.http.routers.wordpress-https.entrypoints=websecure,\
          traefik.http.routers.wordpress-https.tls=true,\
          traefik.http.routers.wordpress-https.tls.certresolver=le,\
          traefik.http.middlewares.https-redirect.redirectscheme.scheme=https,\
          traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
```

### What did you see instead?

error while parsing rule Host(`example1.com`: 1:18: missing ',' before newline in argument list

### What version of Traefik are you using?

2.5.4

### What is your environment & configuration?

```yaml
deployment:
  enabled: true

hostNetwork: true
service:
  type: ClusterIP
  ports:
    ssh:
      port: 22
      nodePort: null
    web:  
      port: 80
      nodePort: null
      redirectTo: websecure
    websecure:
      port: 443
      nodePort: null
  annotations: 
    # Register the service in Consul as `traefik-system-ingress`:
    consul.hashicorp.com/service-sync: "true"
    consul.hashicorp.com/service-name: "traefik-system-ingress"

ingressRoute:
  dashboard:
    enabled: false

additionalArguments:
  - --entryPoints.ssh.address=:22/tcp
  - --entryPoints.web.address=:80/tcp
  - --entryPoints.websecure.address=:443/tcp
  - --api=true
  - --api.insecure=true
  - --api.dashboard=true
  - --providers.kubernetesingress=true
  - --providers.kubernetescrd=true
  - --providers.kubernetesingress.ingressclass=traefik
  - --serversTransport.insecureSkipVerify=true
  # Static Configuration
  # - --configFile=/data/traefik.yml
  # File Configuration
  - --providers.file.directory=/data
  - --providers.file.filename=/data/routes.yml
  - --certificatesresolvers.le.acme.storage=/data/acme.json
  - --certificatesresolvers.le.acme.email=emailaddress
  - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
  # Consul config: 
  # Enable Traefik to use Consul Connect:
  - "--providers.consulcatalog.connectAware=true" 
  # Traefik routes should only be created for services with explicit `traefik.enable=true` service-tags:
  - "--providers.consulcatalog.exposedByDefault=false"
  # For routes that are exposed (`traefik.enable=true`) use Consul Connect by default:
  - "--providers.consulcatalog.connectByDefault=true"
  # Rename the service inside Consul: `traefik-system-ingress`
  - "--providers.consulcatalog.servicename=traefik-system-ingress"
  # Connect Traefik to the Consul service:
  - "--providers.consulcatalog.endpoint.address=127.0.0.1:8501"
  - "--providers.consulcatalog.endpoint.scheme=https"
  - "--providers.consulcatalog.endpoint.tls.ca=/certs/consul-ca/tls.crt"
  - "--providers.consulcatalog.endpoint.tls.insecureskipverify=true"

persistence:
  enabled: true
  name: data
  accessMode: ReadWriteOnce
  size: 100M
  path: /data

volumes:
  - name: consul-ca-cert
    mountPath: "/certs/consul-ca/"
    type: secret

securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0

```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

```
time="2021-11-26T13:53:05Z" level=error msg="error while parsing rule Host(`exmaple1.com`: 1:18: missing ',' before newline in argument list" entryPointName=web routerName=wordpress-http@consulcatalog
time="2021-11-26T13:53:05Z" level=error msg="error while parsing rule Host(`example1.com`: 1:18: missing ',' before newline in argument list" entryPointName=websecure routerName=wordpress-https@consulcatalog
time="2021-11-26T13:53:05Z" level=error msg="Error parsing domains in provider ACME: 1:18: missing ',' before newline in argument list" providerName=le.acme routerName=wordpress-https@consulcatalog rule="Host(`example1.com`"
```
