### ISSUE TITLE
Support remove date header from response

### ISSUE THREAD

**Issue by xqin** [traefik/traefik#8605]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

i want remove  `date` from http response header, i use middlewares and customresponseheaders, set date with empty value, but `date` header stil in http response.

```
      - "traefik.http.middlewares.hide.headers.customresponseheaders.date="
 ```

I used google to find some information, which may be related to the current problem.

https://pkg.go.dev/net/http#ResponseWriter

https://lets-go.alexedwards.net/sample/02.05-customizing-http-headers.html#suppressing-system-generated-headers

### What did you see instead?

`date` header stil in http response.

### What version of Traefik are you using?

```
Version:      2.5.4
Codename:     livarot
Go version:   go1.17.3
Built:        2021-11-08T17:41:41Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

`docker-compose.yaml`

```yaml
version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.insecure
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --log.level=DEBUG
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - 'traefik.http.routers.traefik.middlewares=testheader'
      - "traefik.http.middlewares.testheader.headers.customresponseheaders.date="
```

```
$ docker-compose up -d
$ curl -I 127.0.0.1
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Sat, 04 Dec 2021 16:55:59 GMT
Content-Length: 19

```
Add more configuration information here.
