### ISSUE TITLE
Pilot down? Kills traefik startup

### ISSUE THREAD

**Issue by t0mtaylor** [traefik/traefik#8617]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Try to load with plugins enabled, but for some reason your service is down, this stops traefik from loading

### Workaround
localPlugins does work to get around this issue and its root of the docker img when you create a volume: 

docker-compose.yml
```
    volumes:
      - "/traefik/plugins-local:/plugins-local:ro"
```

traefik.yml - note version is removed when running locally
```
experimental:
  localPlugins:
    traefik-real-ip:
      moduleName: "github.com/soulbalz/traefik-real-ip"
    fail2ban:
      moduleName: "github.com/tommoulard/fail2ban"
```

How to set the folder structure is here for local plugins:
https://github.com/traefik/plugindemo#local-mode

### What did you see instead?
```yml
 time="2021-12-07T10:40:37Z" level=error msg="failed to create UUID: failed call Pilot: Post \"https://instance-info.pilot.traefik.io/public/\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

command traefik error: failed to download plugin github.com/tommoulard/fail2ban: failed to call service: Get "https://plugin.pilot.traefik.io/public/download/github.com/tommoulard/fail2ban/v0.6.2": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
### What version of Traefik are you using?

2.5.4

### What is your environment & configuration?
```
experimental:
  plugins:
    traefik-real-ip:
      moduleName: "github.com/soulbalz/traefik-real-ip"
      version: "v1.0.3"
    fail2ban:
      moduleName: "github.com/tommoulard/fail2ban"
      version: "v0.6.2"
```
### If applicable, please paste the log output in DEBUG level
```
 time="2021-12-07T10:40:37Z" level=error msg="failed to create UUID: failed call Pilot: Post \"https://instance-info.pilot.traefik.io/public/\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

command traefik error: failed to download plugin github.com/tommoulard/fail2ban: failed to call service: Get "https://plugin.pilot.traefik.io/public/download/github.com/tommoulard/fail2ban/v0.6.2": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
