### ISSUE TITLE
[MiddleWare] Health check status shall be reused across all middleware uses

### ISSUE THREAD

**Issue by TPXP** [traefik/traefik#8630]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I'm using a middleware chain to apply default error files on all routed servers. I'm expecting to see one health check coming to the backend server hosting those files from time to time.

### What did you see instead?

However I'm seeing a ton of requests made to the server hosting those static files.

I've determined that I'm getting 1 request for the service, plus 1 request per middleware using this service. Since I apply middlewares to all my backend servers, this is making a ton of requests.

### What version of Traefik are you using?

I have tested this against traefik v2.5.5 and v2.5.4. Both are impacted.

### What is your environment & configuration?

```yaml
# /etc/traefik/traefik.yml
providers:
  file:
    directory: /etc/traefik/servers
    watch: true
entryPoints:
  web:
    address: ":80"
```

```
# /etc/traefik/servers/localServer.yml
http:
  routers:
    localServer:
      rule: "PathPrefix(`/`)"
      service: localServer
      priority: 1
  services:
    localServer:
      loadBalancer:
        servers:
         - url: http://nginx
        healthCheck:
          path: /
          interval: '30s'
          timeout: '5s'
  middlewares:
    backendServer:
      chain:
        middlewares:
        - unavailableError
        - timeoutError
    unavailableError:
      errors:
        status: 503
        service: localServer
        query: /.errors/unavailable.html
    timeoutError:
      errors:
        status: 502,504
        service: localServer
        query: /.errors/internal.html
```

I define all my backend in separate files, like this
```
# /etc/traefik/servers/backend<N>.yml
http:
  routers:
    backend<N>:
      rule: "Host(`backend<N>`)"
      service: backend<N>
      priority: 100
      middlewares:
      - backendServer
  services:
    customer00:
      loadBalancer:
        servers:
         - url: http://backend<N>
        healthCheck:
          path: /
          interval: '30s'
          timeout: '5s'
```

### If applicable, please paste the log output in DEBUG level

Nginx is seeing 5 requests: 1 for the localServer service, then 2 requests per backend server since they have 2 middlewares each pointing to this service. For this example, I have 2 defined 2 backend servers.
```
traefik-traefik-1  | time="2021-12-13T15:31:39Z" level=debug msg="Routine health check refresh for backend: customer00@file"
traefik-traefik-1  | time="2021-12-13T15:31:40Z" level=debug msg="Routine health check refresh for backend: customer01@file"
traefik-traefik-1  | time="2021-12-13T15:32:09Z" level=debug msg="Routine health check refresh for backend: localServer@file"
traefik-nginx-1    | 172.25.0.3 - - [13/Dec/2021:15:32:09 +0000] "GET / HTTP/1.1" 200 615 "-" "Go-http-client/1.1" "-"
traefik-nginx-1    | 172.25.0.3 - - [13/Dec/2021:15:32:09 +0000] "GET / HTTP/1.1" 200 615 "-" "Go-http-client/1.1" "-"
traefik-nginx-1    | 172.25.0.3 - - [13/Dec/2021:15:32:09 +0000] "GET / HTTP/1.1" 200 615 "-" "Go-http-client/1.1" "-"
traefik-nginx-1    | 172.25.0.3 - - [13/Dec/2021:15:32:09 +0000] "GET / HTTP/1.1" 200 615 "-" "Go-http-client/1.1" "-"
traefik-nginx-1    | 172.25.0.3 - - [13/Dec/2021:15:32:09 +0000] "GET / HTTP/1.1" 200 615 "-" "Go-http-client/1.1" "-"
```
