### ISSUE TITLE
Traefik proxy does not pick up service-defined@file from consulcatalog service definition 

### ISSUE THREAD

**Issue by sanfx** [traefik/traefik#8640]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I have dnsmasq running on 2 baremetal nodes. Each of these nodes also have consul agent running. in the consul configurations I have defined the dnsmasq service which normally does gets registered.

node 1 **rockpi** 
_cat dnsmasq.service.json_ 
```
{
  "service": {
    "name": "dnsmasq",
    "port": 53,
    "tags": [
             "traefik.enable=true",
             "traefik.udp.routers.rockpi-dnsmasq-dns.service=canary@file",
	     "traefik.udp.routers.rockpi-dnsmasq-dns.entrypoints=dns",
             "traefik.udp.services.rockpi-dnsmasq-svc.loadbalancer.server.port=53"
            ],
    "check": {
      "tcp": "127.0.0.1:53",
      "interval": "10s",
      "success_before_passing": 3,
      "failures_before_critical": 3
    }
  }
}

```
node 2: rockpix
_cat dnsmasq.service.json_ 
```
{
  "service": {
    "name": "dnsmasq",
    "port": 53,
    "tags": [
             "traefik.enable=true",
             "traefik.udp.routers.rockpix-dnsmasq-dns.entrypoints=dns",
             "traefik.udp.services.rockpix-dnsmasq-svc.loadbalancer.server.port=53"
            ],
    "check": {
      "tcp": "127.0.0.1:53",
      "interval": "10s",
      "success_before_passing": 3,
      "failures_before_critical": 3
    }
  }
}
```
and the node running traefik proxy has canary.yaml file with the weighted load balanced service.
_$ cat canary.yml_ 
```
http:
  services:
    canary:
      weighted:
        services:
          # Load balancing between below services
          - name: rockpi-dnsmasq-svc@consulcatalog
            weight: 5
          - name: rockpix-dnsmasq-svc@consulcatalog
            weight: 1

```

restarted traefik and did consul reload on both the consul agent nodes 1 & 2

but I get error  **the udp service "canary@file" does not exist** 

### What did you see instead?

I am getting error:
**the udp service "canary@file" does not exist** 

### What version of Traefik are you using?

2.5.4

### What is your environment & configuration?

```yaml
global:
  # Send anonymous usage data
  sendAnonymousUsage: true

metrics:
  prometheus:
    addServicesLabels: true
    addRoutersLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

api:
  insecure: true
  dashboard: true
  debug: true

accessLog:
  filePath: "/mnt/storage/var/logs/access.log"
  format: json
  filters:
    statusCodes:
      - "200"
      - "300-302"
    retryAttempts: true
    minDuration: "10ms"

log:
  filePath: "/mnt/storage/var/logs/log-file.log"
  level: DEBUG

entryPoints:
  traefik:
    address: ":8080"
  http:
    address: ":80"
  https:
    address: ":443"
  tcpdns:
    address: ":5353"
  dohdns:
    address: ":5354/udp"
    udp:
      timeout: 20s
  dns:
    address: ":53/udp"
    udp:
      timeout: 10s
  mariadb:
    address: ":6306"

serversTransport:
  insecureSkipVerify: true

providers:
  file:
    directory: "/config/"
    watch: true
  consulCatalog:
    defaultRule: "Host(`{{ .Name }}.xs.domain.com`)"
    endpoint:
      address: http://127.0.0.1:8500
  docker:
    endpoint: "unix:///var/run/docker.sock"
    swarmMode: true
    exposedByDefault: false
```

Add more configuration information here.
