### ISSUE TITLE
Rate limiter doesn't take sourceCriterion.requestHeaderName config

### ISSUE THREAD

**Issue by yktd26** [traefik/traefik#8643]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I have configured a simple rate limiter with requestHeaderName
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ratelimit
spec:
  rateLimit:
    sourceCriterion:
      requestHeaderName: authorization
    average: 5
    burst: 1
```
But it looks like traefik doesn't take my connfig and keep using default IPStrategy
level=debug msg="Using IPStrategy" entryPointName=websecure routerName=contentv2-traefik-ingress-dev-dev-contentapi-traefik-dev-afe6c99ff5464f31beef-eastus-aksapp-io@kubernetes middlewareName=traefik-ratelimit@kubernetescrd middlewareType=RateLimiterType

### What did you see instead?

How can I config the headerName?

### What version of Traefik are you using?

traefik-10.6.2	2.5.4

### What is your environment & configuration?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ratelimit
spec:
  rateLimit:
    sourceCriterion:
      requestHeaderName: authorization
    average: 5
    burst: 1
```

### If applicable, please paste the log output in DEBUG level

level=debug msg="Using IPStrategy" entryPointName=websecure routerName=contentv2-traefik-ingress-dev-dev-contentapi-traefik-dev-afe6c99ff5464f31beef-eastus-aksapp-io@kubernetes middlewareName=traefik-ratelimit@kubernetescrd middlewareType=RateLimiterType
