### ISSUE TITLE
issue with too many subdomain levels

### ISSUE THREAD

**Issue by toxic0berliner** [traefik/traefik#8648]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

using traefik 2.5 on docker with letsencrypt configured correctly with DNS validation for wildcards.

traefik has sucessfully obtained a cert for *.example.com and uses it correctly when I go to gitlab.example.com
now it doesn't work for sub-subdomains, so traefik correctly obtained a letsencrypt cert for pages.gitlab.example.com

My issue is now that it's applying the traefik default cert when I go to myproject.pages.gitlab.example.com
I waited a bit just to see if opbtaining the cert was taking some time but no, it's not coming, and I see no issue in the traefik.log

I have one gitlab container only but lots of labels on it : 
````
    labels:
      traefik.http.routers.gitlab.service: gitlab
      traefik.http.routers.gitlab.rule: Host(`gitlab.example.com`,`gitlab.example.de`) 
      traefik.http.services.gitlab.loadbalancer.server.port: 80
      traefik.http.services.gitlab.loadBalancer.server.scheme: http
      traefik.http.routers.gitlab-prometheus.rule: Host(`prometheus.gitlab.example.com`,`prometheus.gitlab.example.de`) 
      traefik.http.routers.gitlab-prometheus.service: gitlab-prometheus
      traefik.http.services.gitlab-prometheus.loadbalancer.server.port: 9090
      traefik.http.services.gitlab-prometheus.loadBalancer.server.scheme: http
      traefik.http.routers.gitlab-registry.rule: Host(`registry.gitlab.example.com`,`registry.gitlab.example.de`) 
      traefik.http.routers.gitlab-registry.service: gitlab-registry
      traefik.http.services.gitlab-registry.loadbalancer.server.port: 8123
      traefik.http.services.gitlab-registry.loadBalancer.server.scheme: http
      traefik.http.routers.gitlab-pages.service: "gitlab-pages"
      traefik.http.routers.gitlab-pages.rule: "Host(`pages.gitlab.example.com`,`pages.gitlab.example.de`) || HostRegexp(`{subdomain:[a-z]+}.pages.gitlab.example.de`) || HostRegexp(`{subdomain:[a-z]+}.pages.gitlab.example.com`)"
      traefik.http.services.gitlab-pages.loadbalancer.server.port: "8081"
      traefik.http.services.gitlab-pages.loadbalancer.server.scheme: http
      traefik.http.routers.gitlab-mattermost.rule: Host(`mattermost.example.com`,`mattermost.example.de`) 
      traefik.http.routers.gitlab-mattermost.service: gitlab-mattermost
      traefik.http.services.gitlab-mattermost.loadbalancer.server.port: 8124
      traefik.http.services.gitlab-mattermost.loadBalancer.server.scheme: http
````
I did setup letsencrypt a while ago so I'm not even sure how I got it to request *.example.com, idealy, I'd like traefik to find out that it needs to get *.pages.gitlab.example.com but I'd settle for it requesting on the fly for the FQDN as I'm not expecting many possible urls for my pages it's a small gitlab instance.

I even tried adding `traefik.http.routers.gitlab-pages.tls.domains.main: "*.pages.gitlab.example.com"` but no luck.

Am I trying to do something not allowed or have I found an issue ?

### What did you see instead?

myproject.pages.gitlab.example.com gets served sucessfully by traefik but using the default self-signed certificate instead of getting a valid cert from letsencrypt

### What version of Traefik are you using?

Version:      2.5.5
Codename:     brie
Go version:   go1.17.5
Built:        2021-12-10T17:00:35Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

docker provider
