### ISSUE TITLE
rewrite error

### ISSUE THREAD

**Issue by kakaNo1** [traefik/traefik#8658]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I want to access http://123.com/aaa and redirect to http://123.com/bbb, but the URL still shows http://123.com/aaa
this is my ingress.yaml

### What did you see instead?

If I visit http://123.com/aaa, it will show http://123.com/bbb. This is not what I want. Can I set it to implicit forwarding

### What version of Traefik are you using?

version：traefik:1.7.26

### What is your environment & configuration?

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/request-modifier: 'ReplacePathRegex: ^/aaa/bbb'
  labels:
    app: weeee
  name: num1
spec:
  rules:
  - host: 123.com
    http:
      paths:
      - backend:
          service:
            name: dafasd
            port:
              number: 80
        path: /bbb
        pathType: Prefix
```
