### ISSUE TITLE
Unable to change the default `idleTimeout`

### ISSUE THREAD

**Issue by Totalus** [traefik/traefik#8668]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I tried changing the idleTimeout two ways:
- Adding the CLI option `--entrypoints.https.transport.respondingTimeouts.idleTimeout=360s`
- Configuring a custom servers transport with higher idle timeout and assigning it to the corresponding service in my router.

Both methods seem to fail, the idle timeout remains 180 seconds with any of those changes (one or both).

**Additional details**
- The connections are WebSocket (secure)
- If I make the client send a message at intervals of a bit less than 180 seconds, the connections remain alive. If I increase the interval to higher than 180 seconds, the connections drop, so the 180 seconds timeout is pretty clear.
- If I remove traefik and connect directly with the WebSocket server, there is no issue. The connections remain alive.

### What did you see instead?

The idle timeout remains 180 seconds (the default value).

### What version of Traefik are you using?

```
Version:      2.5.6
Codename:     brie
Go version:   go1.17.5
Built:        2021-12-22T16:30:52Z
OS/Arch:      linux/amd6
```

### What is your environment & configuration?

Traefik is deployed on a Kubernetes cluster.

<details>
<summary>My deployment configuration</summary>

```yaml
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: default
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-sa
      terminationGracePeriodSeconds: 60
      containers:
      - name: traefik
        image: traefik
        resources:
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        args:
          # Logging
          - --log.level=debug
          # Metrics
          - --metrics.prometheus=true
          - --entrypoints.metrics.address=:8082
          - --metrics.prometheus.entryPoint=metrics
          # Kubernetes provider
          - --providers.kubernetesingress=true
          - --providers.kubernetescrd=true
          # Entrypoints
          - --entrypoints.http.address=:80
          - --entrypoints.https.address=:443
          - --entrypoints.https.http.tls=letsencrypt
          - --entrypoints.http.http.redirections.entryPoint.scheme=https
          - --entrypoints.http.http.redirections.entryPoint.to=https
          - --entrypoints.http.http.redirections.entryPoint.permanent=true
          # Increase the default idle timeout (180s) so we can keep the websocket
          # connections alive for a longer time without having to send a message
          - --entrypoints.https.transport.respondingTimeouts.idleTimeout=360s # Does not seem to work...
          # Certificate resolvers
          - "--certificatesresolvers.letsencrypt.acme.email=notGivingAwayMyEmail@gmail.com"
          - "--certificatesresolvers.letsencrypt.acme.tlsChallenge=true"
```
```yaml
# servers-transport.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: $APP_NAME
spec:
  serverName: $APP_NAME
  forwardingTimeouts:
    # We need a idle connection timeout that is high enough not to close our websocket connections too fast
    idleConnTimeout: "360s"
  maxIdleConnsPerHost: 1000
```

```yaml
# ingress-route.yaml (partial)
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: $APP_NAME
spec:
  # ...
  routes:
  - match: Host(`$APP_URL`)
    kind: Rule
    services:
    - name: $APP_NAME
      port: 4000
      serversTransport: $APP_NAME # Assign custom server transport
```
</details>

Once Traefik is started, I can see that the idleTimeout is read from the client option in one of the log that prints some JSON configuration:

<details>
<summary>JSON configuration printed</summary>

```js
{
  "global": {
    "checkNewVersion": true
  },
  "serversTransport": {
    "maxIdleConnsPerHost": 200
  },
  "entryPoints": {
    // ...
    "https": {
      "address": ":443",
      "transport": {
        "lifeCycle": {
          "graceTimeOut": "10s"
        },
        "respondingTimeouts": {
          "idleTimeout": "6m0s" // So that seems to work
        }
      },
      "forwardedHeaders": {},
      "http": {},
      "udp": {
        "timeout": "3s"
      }
    },
    
    // ...
}
```
</details>

And if I check the `IngressRoute` and `ServersTransport` I've created for that service, they both seem to be configured correctly:
- the `IngressRoute` has the `serversTransport` assigned
- the `ServersTransport` is created and has the `idleTimeout` assigned
