### ISSUE TITLE
Getting NATS to work behind a Traefik ingress controller?

### ISSUE THREAD

**Issue by joeldeteves** [traefik/traefik#8670]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Cross posting from https://github.com/nats-io/nats-server/issues/2768

I am trying to get [NATS Server](https://github.com/nats-io/nats-server) working from behind Traefik using the Kubernetes CRD provider + a TCP router with TLS passthrough but it results in an I/O timeout from the NATS client

I have tested to make sure NATS is working by exposing it as a Load Balancer, and I can confirm it immediately starts to work when exposed that way - but the problem with this setup is that the particular app we are trying to deploy shares a domain across backend services, so some of those services break when we change the A record to point to the Load Balancer.

Ideally, Traefik should pass the TCP packets transparently without breaking the connection.

Hoping we can find a solution that works with Traefik and this app in our cluster

Thank you

### What did you see instead?

Trying to connect results in an i/o timeout from the NATS client.

### What version of Traefik are you using?

2.5.2 (Kubernetes Ingress)

### What is your environment & configuration?

```yaml
# ingress.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: tactical-nats
  namespace: tacticalrmm
spec:
  entryPoints:
    - tactical-nats
  routes:
  - match: HostSNI(`*`)
    services:
    - name: tactical-nats
      port: 4222
  tls:
    passthrough: true
```
```yaml
# service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: tacticalrmm
  labels:
    app: tacticalrmm
    service: tactical-nats
  name: tactical-nats
spec:
  ports:
    - name: "nats"
      port: 4222
      targetPort: 4222
      protocol: TCP
  selector:
    service: tactical-nats
```
```yaml
# Traefik config
      containers:
        - name: traefik
          image: traefik:v2.5.2
          args:
            - --api=true #Uncomment to enable the dashboard
            - --ping=true # Required for Kubernetes liveness probe
            - --accesslog
            - --entrypoints.web.Address=:8000
            - --entrypoints.websecure.Address=:4443
            - --entrypoints.era.Address=:2222
            - --entrypoints.tactical-nats.Address=:4222
            - --providers.kubernetescrd
            - --providers.kubernetesingress
            - --certificatesresolvers.default.acme.dnschallenge
            - --certificatesresolvers.default.acme.dnschallenge.provider=digitalocean
            - --certificatesresolvers.default.acme.dnschallenge.delaybeforecheck=15
            - --certificatesresolvers.default.acme.email=contact@mydomain.com
            - --serversTransport.insecureSkipVerify=true
          env:
            - name: DO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: do-token
                  key: token
          readinessProbe:
            httpGet:
              path: /ping
              port: api
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: api
              scheme: HTTP
            periodSeconds: 10
            initialDelaySeconds: 30
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            - name: api
              containerPort: 8080
```
