### ISSUE TITLE
[K8s-ingress][Traefik2] Ignores certificate from secret, and serves default self-signed cert instead for a few domains

### ISSUE THREAD

**Issue by Richard87** [traefik/traefik#8672]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I noticed 2 domains was serverd with `TRAEFIK DEFAULT CERT` suddenly, instead of the cert provisioned by lets-encrypt/cert-manager 11 days ago.

This is the ingress configuration:
```yaml
spec:
    tls:
    ...
    - hosts:
        - stasjonstorgetlegesenter.no
        - www.stasjonstorgetlegesenter.no
      secretName: stasjonstorgetlegesenter-no-cert
    ....
    spec:
    ...
        - host: stasjonstorgetlegesenter.no
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: nefle
                port:
                  number: 3000
    - host: www.stasjonstorgetlegesenter.no
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: nefle
                port:
                  number: 3000
```
I have a bout 500 domains, and the ingress is automatically configured, so they all look excactly the same.
The certificate generated looks like this:
```
-----BEGIN CERTIFICATE-----
MIIFXTCCBEWgAwIBAgISAxz0XVsfA3xSWQRV+wWidzpCMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMTEyMjMwMzIzMzZaFw0yMjAzMjMwMzIzMzVaMCYxJDAiBgNVBAMT
G3N0YXNqb25zdG9yZ2V0bGVnZXNlbnRlci5ubzCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBAMhldqNGojo1ih8LxOlA8G5vuIqlKki2rJJ1ftxGLISyjPhM
q3KgYiKxQkAsibWT6XRcWjYb0YhcYSsZI+qjLUZ06QFv9UJP1fPCdPWZ9oxcAnpq
6vBO7YnOrjMFTeI93zLNXroKzHh1n0K6Vj0T3T7AKQyB2F5pUmfsajOnd1P2AbhR
DZHfznd8uGckhcogcsHWcGZAOfmqg6fvdjgeBxI7mhVkR9PkDy3Bd69amfwp9QSw
VieDR/Qi3/IQnyP+bDKOZ4I1TDM5z9523lnGRtbHAdBQn+tG0NLa4DlHLkrp9Vwn
6pevsHRKMncT0gtUeKQnDhLs26BqIg6ot/z5LQUCAwEAAaOCAncwggJzMA4GA1Ud
DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
AQH/BAIwADAdBgNVHQ4EFgQUDJ/v4Lnq5mHZzp1tMYO9H2PGGaYwHwYDVR0jBBgw
FoAUFC6zF7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUF
BzABhhVodHRwOi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9y
My5pLmxlbmNyLm9yZy8wRwYDVR0RBEAwPoIbc3Rhc2pvbnN0b3JnZXRsZWdlc2Vu
dGVyLm5vgh93d3cuc3Rhc2pvbnN0b3JnZXRsZWdlc2VudGVyLm5vMEwGA1UdIARF
MEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEWGmh0dHA6
Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBBAYKKwYBBAHWeQIEAgSB9QSB8gDwAHUA
RqVV63X6kSAwtaKJafTzfREsQXS+/Um4havy/HD+bUcAAAF95Ye3dAAABAMARjBE
AiB+NyAWcbgjA4doYwgX4muPeXCtJ99dKhT75WdDV5Ko0gIgQkz0P1v1VdO2gIAu
K1Qn/hk2edTujeHfoUODK3F4ykMAdwBvU3asMfAxGdiZAKRRFf93FRwR2QLBACkG
jbIImjfZEwAAAX3lh7f3AAAEAwBIMEYCIQDu7hjbABdwTMYtw/qMESl9sJkOEOvS
YlPlqsiL+w5yZgIhAMSSOn2hOYtQAQbAtguIhz1ZRtsllyvOvLhRLxdaKJCrMA0G
CSqGSIb3DQEBCwUAA4IBAQAjUCNP1zJpOfYVMgoeW68IIDENCXQsBb29VIsodW3J
GAOsPAm3l+zG4H1M+J/DjZU7jv6Py90WLf6L0r/yEGf7O7q/HOA2/WEtK9lGtcX5
gKKLePGq97PgKr8m4c4kmmsV1J+tPxKTApLyQ0WtdSrR+UARxIZ3MA/OK3jk9YpA
FAVUAn8EGtjUOfXgdh4v1OPTLwvqnuEnmg2Q1wNOlqy1dl5aUy1TC0JdxRtHK0Cz
DpEBtgwWdoIP0xQTpzUAPFmMv0z/kKFEw0U3YZmjVBTnSNkkA9BhuImFwht0cOnu
rUsl6y6poAx3GDxqgy0BXVFTDzY+d6ISXMkZp6Npwwph
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
/kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
nLRbwHOoq7hHwg==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
+tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
-----END CERTIFICATE-----
```

### What did you see instead?

The default signed certificate:
```
-----BEGIN CERTIFICATE-----
MIIDXjCCAkagAwIBAgIRAO5W+ltF5+BmUWbarJU+ZgUwDQYJKoZIhvcNAQELBQAw
HzEdMBsGA1UEAxMUVFJBRUZJSyBERUZBVUxUIENFUlQwHhcNMjIwMTAzMTQwNTM5
WhcNMjMwMTAzMTQwNTM5WjAfMR0wGwYDVQQDExRUUkFFRklLIERFRkFVTFQgQ0VS
VDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALZzQ65kAcp2GoJKUvIp
UgF2FmHeHXTYdI69lAdFAX5fEKYfuPDpk3K+2M7cL5/3muWXQzhe7G3WHimFoXxb
IRm7M+280bAiOjlFAIMw1m8t0GXpTg9dsKkcte1bDVY5CF5GgxPLBJwO+VM63Cng
9TNt2vRy9RNZJu6iImqA//6Q9ZQ4k5Tk3PnYadLqpxRclEDxHHTfdQvpkZOZ4HQ4
R1NZ+2KS7oqMdWY56PYIGkKiKduMKK83Qi7oELmummwBM6QiQwfhMGU36j/Otx55
Sf66yhCJDzMAqk12r/0+wwpUQ1Gf5L1OXHsxipYCexQ1OXnRUlBcI6oICu44wDS/
I7cCAwEAAaOBlDCBkTAOBgNVHQ8BAf8EBAMCA7gwEwYDVR0lBAwwCgYIKwYBBQUH
AwEwDAYDVR0TAQH/BAIwADBcBgNVHREEVTBTglFmYWUwNmM1Y2M5MWExNzc5MDM1
MmUwNTIzZGQyOWVkMS5jNjU3NjY1ZTgyOWI2M2U5ZTFlZWM0YTM2MmQyMDFkYS50
cmFlZmlrLmRlZmF1bHQwDQYJKoZIhvcNAQELBQADggEBAC9jBUgL1kthNSi4cipl
7Fqfm9KwKgDhTuXKoCzbT1e8Hk9suWxJn7KZ/Z9S+i9BYzG1DAwNvxym1F6qip0u
nGaBnO2NvumEH1M80a2+pZED1gTWO4rmZElnryaDwlaxuIRcJB0UM92vEx09Zfeq
LBeQ7A51NcHelSL6wNericGtT1q9ceKtbM8MDBwFr+c2vNUT6XJkoQPi1baFIUgV
oTDUPBAutNSht1PsaONXaBbDOgvegJnTHyU5ZQfSlEdpGf+U513skboPoN12ZybK
v3Dz5BH60ThAhbqpMV0lRXdAQOhqEXg58ITK8uV3UTDEZ2hBtU2vPxuHLcMnLi6V6e0=
-----END CERTIFICATE-----
```

### What version of Traefik are you using?

I'm running this image on k8s (GKE): `traefik:v2.5.6`

### What is your environment & configuration?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: traefik1
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik
    spec:
      containers:
        - name: traefik-ingress-lb
          image: traefik:v2.5.6
          args:
            - '--api.insecure'
            - '--api.dashboard=true'
            - '--log=true'
            - '--log.level=DEBUG'
            - '--accesslog=true'
            - '--accesslog.filepath=/dev/stdout'
            - '--accesslog.format=json'
            - '--entrypoints.http.Address=:80'
            - '--entrypoints.http.http.redirections.entryPoint.to=https'
            - '--entrypoints.http.http.redirections.entryPoint.scheme=https'
            - '--entrypoints.https.Address=:443'
            - '--entrypoints.https.http.tls=true'
            - '--providers.kubernetesingress=true'
            - '--providers.kubernetesingress.ingressclass=traefik1'
            - '--providers.kubernetesingress.namespaces=default,nefle,traefik1,linkerd,nefle-video,nefle-decision'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: admin
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      serviceAccountName: traefik-ingress-controller
      serviceAccount: traefik-ingress-controller
```

### If applicable, please paste the log output in DEBUG level

Please see the attachment in the first comment :) (DEBUG Log is huge!)
