### ISSUE TITLE
RateLimit middleware don't terminate the request pipeline

### ISSUE THREAD

**Issue by majian159** [traefik/traefik#8677]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### Do you want to request a *feature* or report a *bug*?
Feature

### What did you do?
Reached the traffic limit and jumped to the error page

### What did you expect to see?
Reached the traffic limit and jumped to the error page

### What did you see instead?
Reached the traffic limit return 429 and terminated request pipeline.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v2.5.6
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ratelimit
  namespace: test
spec:
  rateLimit:
    period: 10s
    average: 3
    #burst: 2
    sourceCriterion:
      ipStrategy:
        excludedIPs:
          - 10.0.0.0/32
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: errorpage
  namespace: test
spec:
  errors:
    status:
      - "400-599"
    service:
      name: errorsvc
      port: 80
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: www.test.com
  namespace: test
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: test-ratelimit@kubernetescrd,test-errorpage@kubernetescrd
spec:
  rules:
    - host: www.test.com
      http:
        paths:
          - backend:
              serviceName: test
              servicePort: 80

```
