### ISSUE TITLE
Unable to create tracer: cannot obtain reporter config from env: cannot parse env var JAEGER_AGENT_PORT

### ISSUE THREAD

**Issue by jeusdi** [traefik/traefik#8691]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Here are current deployed traefik args:

```yaml
spec:
      containers:
      - args:
        - --global.checknewversion
        - --global.sendanonymoususage
        - --entryPoints.metrics.address=:9100/tcp
        - --entryPoints.traefik.address=:9000/tcp
        - --entryPoints.web.address=:8000/tcp
        - --entryPoints.websecure.address=:8443/tcp
        - --api.dashboard=true
        - --ping=true
        - --metrics.prometheus=true
        - --metrics.prometheus.entrypoint=metrics
        - --providers.kubernetescrd
        - --providers.kubernetesingress
        - --log.level=DEBUG
        - --accesslog=true
        - --accesslog.fields.defaultmode=keep
        - --accesslog.fields.headers.defaultmode=drop
        - --tracing.jaeger=true
        - --tracing.jaeger.samplingServerURL=http://jaeger-agent:5778/sampling
        - --tracing.jaeger.localAgentHostPort=jaeger-agent:6831
        image: traefik:2.5.6
```

As you can see, `tracing` is enabled using jaeger.

Dashboard:

![image|690x207](upload://oPtmvoqMOI6BTJKBbazmkOcu1Za.png)

I'm currently accessing to several exposed services.

Problem is that when I'm trying to get information of tracing into jaeger, it's only showing me one service.

Several entrypoints and routers are well configured.

But anyone of them is listed on jaeger listbox. Obviously, I'm reaching correctly to exposed services.

I've took a look on traefik pod logs:

> evel=warning msg="Unable to create tracer: cannot obtain reporter config from env: cannot parse env var JAEGER_AGENT_PORT=udp://10.43.85.36:5775: strconv.ParseInt: parsing \"udp://10.43.85.36:5775\": invalid syntax"

I don't know why this env variable `JAEGER_AGENT_PORT` is present.

By other hand, ip a port are correct. I mean, jaeger agent service has 10.43.85.36 allocated.

### What did you see instead?

Tracings are not sent at jaeger.

I've took a look on logs:

> level=warning msg="Unable to create tracer: cannot obtain reporter config from env: cannot parse env var JAEGER_AGENT_PORT=udp://10.43.85.36:5775: strconv.ParseInt: parsing \"udp://10.43.85.36:5775\": invalid syntax"

### What version of Traefik are you using?

I've installed traefik on kubernetes using helm chart:

    NAME           	CHART VERSION	APP VERSION
    traefik/traefik	10.9.1       	2.5.6

### What is your environment & configuration?

```yaml
spec:
      containers:
      - args:
        - --global.checknewversion
        - --global.sendanonymoususage
        - --entryPoints.metrics.address=:9100/tcp
        - --entryPoints.traefik.address=:9000/tcp
        - --entryPoints.web.address=:8000/tcp
        - --entryPoints.websecure.address=:8443/tcp
        - --api.dashboard=true
        - --ping=true
        - --metrics.prometheus=true
        - --metrics.prometheus.entrypoint=metrics
        - --providers.kubernetescrd
        - --providers.kubernetesingress
        - --log.level=DEBUG
        - --accesslog=true
        - --accesslog.fields.defaultmode=keep
        - --accesslog.fields.headers.defaultmode=drop
        - --tracing.jaeger=true
        - --tracing.jaeger.samplingServerURL=http://jaeger-agent:5778/sampling
        - --tracing.jaeger.localAgentHostPort=jaeger-agent:6831
        image: traefik:2.5.6
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

```
time="2022-01-11T22:11:54Z" level=info msg="Configuration loaded from flags."
time="2022-01-11T22:11:54Z" level=info msg="Traefik version 2.5.6 built on 2021-12-22T16:30:52Z"
time="2022-01-11T22:11:54Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true,\"sendAnonymousUsage\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"metrics\":{\"address\":\":9100/tcp\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}},\"traefik\":{\"address\":\":9000/tcp\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}},\"web\":{\"address\":\":8000/tcp\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}},\"websecure\":{\"address\":\":8443/tcp\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"kubernetesIngress\":{},\"kubernetesCRD\":{}},\"api\":{\"dashboard\":true},\"metrics\":{\"prometheus\":{\"buckets\":[0.1,0.3,1.2,5],\"addEntryPointsLabels\":true,\"addServicesLabels\":true,\"entryPoint\":\"metrics\"}},\"ping\":{\"entryPoint\":\"traefik\",\"terminatingStatusCode\":503},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"accessLog\":{\"format\":\"common\",\"filters\":{},\"fields\":{\"defaultMode\":\"keep\",\"headers\":{\"defaultMode\":\"drop\"}}},\"tracing\":{\"serviceName\":\"traefik\",\"jaeger\":{\"samplingServerURL\":\"http://jaeger-agent:5778/sampling\",\"samplingType\":\"const\",\"samplingParam\":1,\"localAgentHostPort\":\"jaeger-agent:6831\",\"propagation\":\"jaeger\",\"traceContextHeaderName\":\"uber-trace-id\",\"disableAttemptReconnecting\":true}},\"pilot\":{\"dashboard\":true}}"
time="2022-01-11T22:11:54Z" level=info msg="Stats collection is enabled."
time="2022-01-11T22:11:54Z" level=info msg="Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration."
time="2022-01-11T22:11:54Z" level=info msg="Help us improve Traefik by leaving this feature on :)"
time="2022-01-11T22:11:54Z" level=info msg="More details on: https://doc.traefik.io/traefik/contributing/data-collection/"
time="2022-01-11T22:11:54Z" level=debug msg="Configured Prometheus metrics" metricsProviderName=prometheus
time="2022-01-11T22:11:54Z" level=warning msg="Unable to create tracer: cannot obtain reporter config from env: cannot parse env var JAEGER_AGENT_PORT=udp://10.43.85.36:5775: strconv.ParseInt: parsing \"udp://10.43.85.36:5775\": invalid syntax"
time="2022-01-11T22:11:54Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2022-01-11T22:11:54Z" level=debug msg="Start TCP Server" entryPointName=websecure
time="2022-01-11T22:11:54Z" level=debug msg="Start TCP Server" entryPointName=web
time="2022-01-11T22:11:54Z" level=debug msg="Start TCP Server" entryPointName=metrics
time="2022-01-11T22:11:54Z" level=info msg="Starting provider *traefik.Provider {}"
time="2022-01-11T22:11:54Z" level=info msg="Starting provider *ingress.Provider {}"
time="2022-01-11T22:11:54Z" level=info msg="ingress label selector is: \"\"" providerName=kubernetes
time="2022-01-11T22:11:54Z" level=info msg="Creating in-cluster Provider client" providerName=kubernetes
time="2022-01-11T22:11:54Z" level=debug msg="Start TCP Server" entryPointName=traefik
```
