### ISSUE TITLE
Cannot load balance multiple instances of the same Docker container image

### ISSUE THREAD

**Issue by fomojola** [traefik/traefik#8694]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I am running a Docker container that uses labels and the Traefik 2 Docker provider to set up the router and services. My build service generates the container image and sets the labels:
```
"traefik.enable": "true",
"traefik.http.middlewares.prefix-main-app-2.stripprefix.forceSlash": "false",
"traefik.http.middlewares.prefix-main-app-2.stripprefix.prefixes": "/app",
"traefik.http.routers.router-main-app-2.middlewares": "prefix-main-app-2",
"traefik.http.routers.router-main-app-2.priority": "2",
"traefik.http.routers.router-main-app-2.rule": "Host(\"www.example.com\") && PathPrefix(\"/app/\")",
"traefik.http.routers.router-main-app-2.tls": "true",
"traefik.http.routers.router-main-app-2.tls.certresolver": "lets-encrypt",
"traefik.http.routers.router-main-app-2.tls.domains[0].main": "www.example.com"
```

On my server I run a single instance of the container image, and that works great. I then tried to run multiple instances of the same container image, expecting Traefik 2 to notice that the same image was running and then load balance using the standard round robin load balancer strategy.

### What did you see instead?

The moment I run a second instance of the same container, I get the error:
```
Jan 12 07:21:42 fleet-1 traefik[568271]: time="2022-01-12T07:21:42Z" level=error msg="Router defined multiple times with different configurations in [main-app-web-1-6f8022a0b0630fd49b6001c1d66b0902c6024033acab8c8b56f818bb8c53ee05 main-app-web-1-upcoming-29925-990b74d5717d780c2246567bb59b31ab887f992cde3c3b38d78eb59aa531a578]" providerName=docker routerName=router-main-app-2
```

If I was using the file providers, I'd use the loadbalancer.servers option, as documented at https://doc.traefik.io/traefik/v2.0/routing/services/: unfortunately that documentation ONLY covers the File provider, and there are NO Docker provider examples for load balancing. That option clearly doesn't work when using labels.

Is load balancing not possible using the Docker provider and labels? Would I need to use one of the KV providers?

### What version of Traefik are you using?

Version:      2.5.6
Codename:     brie
Go version:   go1.17.5
Built:        2021-12-22T16:30:52Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```toml
[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

  [entryPoints.internal]
    address = "127.0.0.1:8888"

[log]
  level = "WARN"

[accessLog]

[metrics]
  [metrics.prometheus]
    addEntryPointsLabels = true
    addServicesLabels = true
    addRoutersLabels = true
		
[certificatesResolvers.lets-encrypt.acme]
  email = "email@example.com"
  storage = "/etc/traefik/acme/acme.json"
  [certificatesResolvers.lets-encrypt.acme.tlsChallenge]

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = false
```

Add more configuration information here.

**Comment by fomojola** [comment]
I did look at https://iximiuz.com/en/posts/traefik-canary-deployments-with-weighted-load-balancing/: it requires the use of the file provider. I can attach a different label to each instance when it is launched: is there a way to use the equivalent of `http.services.my-service.loadBalancer.servers` as documented at https://doc.traefik.io/traefik/v2.0/routing/services/ when using Docker container labels?

**Comment by tomMoulard** [comment]
Hello @fomojola,

Thanks for your interest in Traefik!

Traefik tries to detect when 2 (or more) services have the same configuration in order to make a loadbalancer between those services (e.g. when scaling up deployments on docker-compose).
Also, when building a router with no user defined service, Traefik will generate the service name using values from the context(i.e. the service name and the docker compose project for [docker-compose](https://github.com/traefik/traefik/blob/ba822acb23db3d620f6b3773ac9eff3e98ce313f/pkg/provider/docker/config.go#L414)).
For example, given this service:

```yaml
services:
  whoami:
    image: traefik/whoami
    labels:
      traefik.http.routers.whoami.rule: Host(`whoami.localhost`)
```

Traefik will generate the service name `whoami-example` if running docker compose like: `docker-compose -p example up`.

In the example below, there are 2 definition of the same router but with different services.
In this case, I get the error described in the issue:

```yaml
version: '3.6'
services:
  traefik:
    image: traefik:v2.6
    command:
      - --providers.docker
      - --log.level=DEBUG
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  whoami: # service name: whoami-example
    image: traefik/whoami
    labels:
      traefik.http.routers.whoami.rule: Host(`whoami.localhost`)
  not-whoami: # service name: not-whoami-example
    image: traefik/whoami
    labels:
      traefik.http.routers.whoami.rule: Host(`whoami.localhost`)
```
```
> docker-compose up
...
example-traefik-1     | time="2022-00-00T00:00:00Z" level=error msg="Router defined multiple times with different configurations in [not-whoami-example-5d0d871caa159531c32c84ad43d06b73996f133f595faf4b5e8c03e2c83dedfd whoami-example-991695a2af818413afe9eefbfbdcb96203adc9a669554ba9bfb6b8cb3d1afab8]" routerName=whoami providerName=docker
...
```

To fix this, each docker services should to specify the **same** service name.
This allows Traefik to match routers with one another and load balance between them.

Here is a fixed version of the example above:

```yaml
services:
  whoami:
    image: traefik/whoami
    labels:
      traefik.http.routers.whoami.rule: Host(`whoami.localhost`)
      traefik.http.services.whoami-service.loadbalancer.server.port: 80 # set the service name to whoami-service
  not-whoami:
    image: traefik/whoami
    labels:
      traefik.http.routers.whoami.rule: Host(`whoami.localhost`)
      traefik.http.services.whoami-service.loadbalancer.server.port: 80 # set the service name to whoami-service
```
