### ISSUE TITLE
Cannot bind IP address from LAN subnet

### ISSUE THREAD

**Issue by emulated24** [traefik/traefik#8695]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Running Traefik 2 on Docker Swarm, trying to assign fixed IP address to Traefik from the LAN subnet. Unfortunately, it fails to bind:
2022/01/12 17:39:03 traefik.go:81: command traefik error: error while building entryPoint websecure: error preparing server: error opening listener: **listen tcp 192.168.1.39:443: bind: cannot assign requested address**

Part of my traefik.yml:

entryPoints:
  web:
    address: 192.168.1.39:80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: 192.168.1.39:443
    http:
      tls:
        certResolver: staging

### What did you see instead?

IP address bind doesn't work, container dies.

### What version of Traefik are you using?

Version:      2.5.6
Codename:     brie
Go version:   go1.17.5
Built:        2021-12-22T16:30:52Z
OS/Arch:      linux/arm64

### What is your environment & configuration?

docker-compose.yaml
```
version: '3'

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      # (Optional) Expose Dashboard
      - "8080:8080"  # Don't do this in production!
    volumes:
      - /ha_volume/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 20s
      placement:
        constraints:
          - node.role == manager

networks:
  traefik-public:
    external: true
```

traefik.yml
```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: true  # true by default

log:
  level: INFO # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: common  # common, json, logfmt
  filePath: /etc/traefik/logs/traefik.log

api:
  dashboard: true  # true by default
  insecure: true

# Entry Points configuration
# ---
entryPoints:
  web:
    address: :80
    # (Optional) Redirect to HTTPS
    # ---
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: 192.168.1.39:443
    http:
      tls:
        certResolver: staging

# Configure your CertificateResolver here...
# ---
certificatesResolvers:
  staging:
    acme:
      email: <REDACTED>
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false  # Default is true
    swarmMode: true
    watch: true
  file:
    # watch for dynamic configuration changes
    directory: /etc/traefik
    watch: true
```

Dedicated network created by command:
docker network create --driver=overlay traefik-public

Output of "docker network ls":
NETWORK ID     NAME                      DRIVER    SCOPE
3b6172838eea   bridge                    bridge    local
dac2f13328f2   docker_gwbridge           bridge    local
7fc6c3601958   host                      host      local
6vad5vpbyx3c   ingress                   overlay   swarm
1c5f82ae9dad   none                      null      local
yaa325pxgj51   portainer_agent_network   overlay   swarm
mc0ut9z61jx1   traefik-public            overlay   swarm
