### ISSUE TITLE
Creating the another rules of k8s ingress affects rule priority

### ISSUE THREAD

**Issue by sundongmin** [traefik/traefik#8703]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

In the `simon` namespace, I creating a ingress rule called `nginx-ing`,
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik-simon
    traefik.ingress.kubernetes.io/priority: "3" # set priority
  generation: 1
  name: nginx-ing
  namespace: simon
spec:
  rules:
  - host: simon-test.unipus.cn
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /
        pathType: Prefix
      - backend:
          serviceName: nginx-deployment
          servicePort: 80
        path: /api
        pathType: Prefix
```

when I execute the follow command 
```bash
# 30580 is traefik nodeport
curl --header 'Host: simon-test.unipus.cn' 10.3.21.249:30580/api
```
the traefik access log output:
```bash
10.3.21.249 - - [14/Jan/2022:17:02:33 +0000] "GET /api HTTP/1.1" 404 169 "-" "curl/7.29.0" 97 "3-simon-test.unipus.cn/" "http://10.3.22.255:80" 1ms
```
log shows macth the frontend `3-simon-test.unipus.cn/`

**But,** when I add another ingress rule, For example:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik-simon
    traefik.frontend.priority: "7"
  name: aaa
  namespace: simon
spec:
  rules:
  - host: bbb.unipus.cn
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /aa
        pathType: Prefix
```
I execute the previous command, the traefik access log output:
```bash
10.3.21.249 - - [14/Jan/2022:17:13:27 +0000] "GET /api HTTP/1.1" 404 169 "-" "curl/7.29.0" 98 "3-simon-test.unipus.cn/api" "http://10.3.19.242:80" 1ms
```
the log shows traefik match the frontend `3-simon-test.unipus.cn/api`

**That is very confused!**

### What did you see instead?

Creating another ingress rule affects rules priority.

### What version of Traefik are you using?

Version:      v1.7.34
Codename:     maroilles
Go version:   go1.16.12
Built:        2021-12-10_04:59:22PM
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
# ingress config detail
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik-simon
    traefik.ingress.kubernetes.io/priority: "3"
  generation: 1
  name: nginx-ing
  namespace: simon
spec:
  rules:
  - host: simon-test.unipus.cn
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /
        pathType: Prefix
      - backend:
          serviceName: nginx-deployment
          servicePort: 80
        path: /api
        pathType: Prefix
      - backend:
          serviceName: nginx-deployment
          servicePort: 80
        path: /aa
        pathType: Prefix
      - backend:
          serviceName: nginx-deployment
          servicePort: 80
        path: /bb
        pathType: Prefix
      - backend:
          serviceName: nginx-deployment
          servicePort: 80
        path: /cc
        pathType: Prefix
      - backend:
          serviceName: nginx-deployment
          servicePort: 80
        path: /dd
        pathType: Prefix
      - backend:
          serviceName: nginx-deployment
          servicePort: 80
        path: /ee
        pathType: Prefix
      - backend:
          serviceName: nginx-deployment
          servicePort: 80
        path: /ff
        pathType: Prefix
      - backend:
          serviceName: nginx-deployment
          servicePort: 80
        path: /gg
        pathType: Prefix
      - backend:
          serviceName: nginx-deployment
          servicePort: 80
        path: /hh
        pathType: Prefix
      - backend:
          serviceName: nginx-deployment
          servicePort: 80
        path: /ii
        pathType: Prefix
      - backend:
          serviceName: nginx-deployment
          servicePort: 80
        path: /jj
        pathType: Prefix
      - backend:
          serviceName: nginx-deployment
          servicePort: 80
        path: /kk
        pathType: Prefix
      - backend:
          serviceName: nginx-deployment
          servicePort: 80
        path: /ll
        pathType: Prefix
```

```bash
$ k -n simon get svc
NAME               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
nginx              ClusterIP   172.20.84.73    <none>        80/TCP    4d15h
nginx-deployment   ClusterIP   172.20.86.220   <none>        80/TCP    4d15h

$ k -n simon get po -o wide
NAME                                READY   STATUS    RESTARTS   AGE     IP            NODE                                             NOMINATED NODE   READINESS GATES
nginx-66b6c48dd5-dgrd8              1/1     Running   0          4d15h   10.3.22.255   xxx   <none>           <none>
nginx-deployment-65587f96cc-h8dft   1/1     Running   0          4d15h   10.3.19.242   xxx   <none>           <none>


### If applicable, please paste the log output in DEBUG level

```bash
time="2022-01-14T17:13:24Z" level=debug msg="Configuration received from provider kubernetes: {\"backends\":{\"3-simon-test.unipus.cn/\":{\"servers\":{\"nginx-66b6c48dd5-dgrd8\":{\"url\":\"http://10.3.22.255:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"3-simon-test.unipus.cn/aa\":{\"servers\":{\"nginx-deployment-65587f96cc-h8dft\":{\"url\":\"http://10.3.19.242:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"3-simon-test.unipus.cn/api\":{\"servers\":{\"nginx-deployment-65587f96cc-h8dft\":{\"url\":\"http://10.3.19.242:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"3-simon-test.unipus.cn/bb\":{\"servers\":{\"nginx-deployment-65587f96cc-h8dft\":{\"url\":\"http://10.3.19.242:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"3-simon-test.unipus.cn/cc\":{\"servers\":{\"nginx-deployment-65587f96cc-h8dft\":{\"url\":\"http://10.3.19.242:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"3-simon-test.unipus.cn/dd\":{\"servers\":{\"nginx-deployment-65587f96cc-h8dft\":{\"url\":\"http://10.3.19.242:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"3-simon-test.unipus.cn/ee\":{\"servers\":{\"nginx-deployment-65587f96cc-h8dft\":{\"url\":\"http://10.3.19.242:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"3-simon-test.unipus.cn/ff\":{\"servers\":{\"nginx-deployment-65587f96cc-h8dft\":{\"url\":\"http://10.3.19.242:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"3-simon-test.unipus.cn/gg\":{\"servers\":{\"nginx-deployment-65587f96cc-h8dft\":{\"url\":\"http://10.3.19.242:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"3-simon-test.unipus.cn/hh\":{\"servers\":{\"nginx-deployment-65587f96cc-h8dft\":{\"url\":\"http://10.3.19.242:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"3-simon-test.unipus.cn/ii\":{\"servers\":{\"nginx-deployment-65587f96cc-h8dft\":{\"url\":\"http://10.3.19.242:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"3-simon-test.unipus.cn/jj\":{\"servers\":{\"nginx-deployment-65587f96cc-h8dft\":{\"url\":\"http://10.3.19.242:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"3-simon-test.unipus.cn/kk\":{\"servers\":{\"nginx-deployment-65587f96cc-h8dft\":{\"url\":\"http://10.3.19.242:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"3-simon-test.unipus.cn/ll\":{\"servers\":{\"nginx-deployment-65587f96cc-h8dft\":{\"url\":\"http://10.3.19.242:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}},\"7-bbb.unipus.cn/aa\":{\"servers\":{\"nginx-66b6c48dd5-dgrd8\":{\"url\":\"http://10.3.22.255:80\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"3-simon-test.unipus.cn/\":{\"entryPoints\":[\"http\"],\"backend\":\"3-simon-test.unipus.cn/\",\"routes\":{\"/\":{\"rule\":\"PathPrefix:/\"},\"simon-test.unipus.cn\":{\"rule\":\"Host:simon-test.unipus.cn\"}},\"passHostHeader\":true,\"priority\":3,\"basicAuth\":null},\"3-simon-test.unipus.cn/aa\":{\"entryPoints\":[\"http\"],\"backend\":\"3-simon-test.unipus.cn/aa\",\"routes\":{\"/aa\":{\"rule\":\"PathPrefix:/aa\"},\"simon-test.unipus.cn\":{\"rule\":\"Host:simon-test.unipus.cn\"}},\"passHostHeader\":true,\"priority\":3,\"basicAuth\":null},\"3-simon-test.unipus.cn/api\":{\"entryPoints\":[\"http\"],\"backend\":\"3-simon-test.unipus.cn/api\",\"routes\":{\"/api\":{\"rule\":\"PathPrefix:/api\"},\"simon-test.unipus.cn\":{\"rule\":\"Host:simon-test.unipus.cn\"}},\"passHostHeader\":true,\"priority\":3,\"basicAuth\":null},\"3-simon-test.unipus.cn/bb\":{\"entryPoints\":[\"http\"],\"backend\":\"3-simon-test.unipus.cn/bb\",\"routes\":{\"/bb\":{\"rule\":\"PathPrefix:/bb\"},\"simon-test.unipus.cn\":{\"rule\":\"Host:simon-test.unipus.cn\"}},\"passHostHeader\":true,\"priority\":3,\"basicAuth\":null},\"3-simon-test.unipus.cn/cc\":{\"entryPoints\":[\"http\"],\"backend\":\"3-simon-test.unipus.cn/cc\",\"routes\":{\"/cc\":{\"rule\":\"PathPrefix:/cc\"},\"simon-test.unipus.cn\":{\"rule\":\"Host:simon-test.unipus.cn\"}},\"passHostHeader\":true,\"priority\":3,\"basicAuth\":null},\"3-simon-test.unipus.cn/dd\":{\"entryPoints\":[\"http\"],\"backend\":\"3-simon-test.unipus.cn/dd\",\"routes\":{\"/dd\":{\"rule\":\"PathPrefix:/dd\"},\"simon-test.unipus.cn\":{\"rule\":\"Host:simon-test.unipus.cn\"}},\"passHostHeader\":true,\"priority\":3,\"basicAuth\":null},\"3-simon-test.unipus.cn/ee\":{\"entryPoints\":[\"http\"],\"backend\":\"3-simon-test.unipus.cn/ee\",\"routes\":{\"/ee\":{\"rule\":\"PathPrefix:/ee\"},\"simon-test.unipus.cn\":{\"rule\":\"Host:simon-test.unipus.cn\"}},\"passHostHeader\":true,\"priority\":3,\"basicAuth\":null},\"3-simon-test.unipus.cn/ff\":{\"entryPoints\":[\"http\"],\"backend\":\"3-simon-test.unipus.cn/ff\",\"routes\":{\"/ff\":{\"rule\":\"PathPrefix:/ff\"},\"simon-test.unipus.cn\":{\"rule\":\"Host:simon-test.unipus.cn\"}},\"passHostHeader\":true,\"priority\":3,\"basicAuth\":null},\"3-simon-test.unipus.cn/gg\":{\"entryPoints\":[\"http\"],\"backend\":\"3-simon-test.unipus.cn/gg\",\"routes\":{\"/gg\":{\"rule\":\"PathPrefix:/gg\"},\"simon-test.unipus.cn\":{\"rule\":\"Host:simon-test.unipus.cn\"}},\"passHostHeader\":true,\"priority\":3,\"basicAuth\":null},\"3-simon-test.unipus.cn/hh\":{\"entryPoints\":[\"http\"],\"backend\":\"3-simon-test.unipus.cn/hh\",\"routes\":{\"/hh\":{\"rule\":\"PathPrefix:/hh\"},\"simon-test.unipus.cn\":{\"rule\":\"Host:simon-test.unipus.cn\"}},\"passHostHeader\":true,\"priority\":3,\"basicAuth\":null},\"3-simon-test.unipus.cn/ii\":{\"entryPoints\":[\"http\"],\"backend\":\"3-simon-test.unipus.cn/ii\",\"routes\":{\"/ii\":{\"rule\":\"PathPrefix:/ii\"},\"simon-test.unipus.cn\":{\"rule\":\"Host:simon-test.unipus.cn\"}},\"passHostHeader\":true,\"priority\":3,\"basicAuth\":null},\"3-simon-test.unipus.cn/jj\":{\"entryPoints\":[\"http\"],\"backend\":\"3-simon-test.unipus.cn/jj\",\"routes\":{\"/jj\":{\"rule\":\"PathPrefix:/jj\"},\"simon-test.unipus.cn\":{\"rule\":\"Host:simon-test.unipus.cn\"}},\"passHostHeader\":true,\"priority\":3,\"basicAuth\":null},\"3-simon-test.unipus.cn/kk\":{\"entryPoints\":[\"http\"],\"backend\":\"3-simon-test.unipus.cn/kk\",\"routes\":{\"/kk\":{\"rule\":\"PathPrefix:/kk\"},\"simon-test.unipus.cn\":{\"rule\":\"Host:simon-test.unipus.cn\"}},\"passHostHeader\":true,\"priority\":3,\"basicAuth\":null},\"3-simon-test.unipus.cn/ll\":{\"entryPoints\":[\"http\"],\"backend\":\"3-simon-test.unipus.cn/ll\",\"routes\":{\"/ll\":{\"rule\":\"PathPrefix:/ll\"},\"simon-test.unipus.cn\":{\"rule\":\"Host:simon-test.unipus.cn\"}},\"passHostHeader\":true,\"priority\":3,\"basicAuth\":null},\"7-bbb.unipus.cn/aa\":{\"entryPoints\":[\"http\"],\"backend\":\"7-bbb.unipus.cn/aa\",\"routes\":{\"/aa\":{\"rule\":\"PathPrefix:/aa\"},\"bbb.unipus.cn\":{\"rule\":\"Host:bbb.unipus.cn\"}},\"passHostHeader\":true,\"priority\":7,\"basicAuth\":null}}}"
time="2022-01-14T17:13:24Z" level=debug msg="Wiring frontend 3-simon-test.unipus.cn/ to entryPoint http"
time="2022-01-14T17:13:24Z" level=debug msg="Creating backend 3-simon-test.unipus.cn/"
time="2022-01-14T17:13:24Z" level=debug msg="Creating load-balancer wrr"
time="2022-01-14T17:13:24Z" level=debug msg="Creating server nginx-66b6c48dd5-dgrd8 at http://10.3.22.255:80 with weight 1"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route / PathPrefix:/"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route simon-test.unipus.cn Host:simon-test.unipus.cn"
time="2022-01-14T17:13:24Z" level=debug msg="Wiring frontend 3-simon-test.unipus.cn/aa to entryPoint http"
time="2022-01-14T17:13:24Z" level=debug msg="Creating backend 3-simon-test.unipus.cn/aa"
time="2022-01-14T17:13:24Z" level=debug msg="Creating load-balancer wrr"
time="2022-01-14T17:13:24Z" level=debug msg="Creating server nginx-deployment-65587f96cc-h8dft at http://10.3.19.242:80 with weight 1"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route /aa PathPrefix:/aa"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route simon-test.unipus.cn Host:simon-test.unipus.cn"
time="2022-01-14T17:13:24Z" level=debug msg="Wiring frontend 3-simon-test.unipus.cn/api to entryPoint http"
time="2022-01-14T17:13:24Z" level=debug msg="Creating backend 3-simon-test.unipus.cn/api"
time="2022-01-14T17:13:24Z" level=debug msg="Creating load-balancer wrr"
time="2022-01-14T17:13:24Z" level=debug msg="Creating server nginx-deployment-65587f96cc-h8dft at http://10.3.19.242:80 with weight 1"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route simon-test.unipus.cn Host:simon-test.unipus.cn"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route /api PathPrefix:/api"
time="2022-01-14T17:13:24Z" level=debug msg="Wiring frontend 3-simon-test.unipus.cn/bb to entryPoint http"
time="2022-01-14T17:13:24Z" level=debug msg="Creating backend 3-simon-test.unipus.cn/bb"
time="2022-01-14T17:13:24Z" level=debug msg="Creating load-balancer wrr"
time="2022-01-14T17:13:24Z" level=debug msg="Creating server nginx-deployment-65587f96cc-h8dft at http://10.3.19.242:80 with weight 1"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route /bb PathPrefix:/bb"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route simon-test.unipus.cn Host:simon-test.unipus.cn"
time="2022-01-14T17:13:24Z" level=debug msg="Wiring frontend 3-simon-test.unipus.cn/cc to entryPoint http"
time="2022-01-14T17:13:24Z" level=debug msg="Creating backend 3-simon-test.unipus.cn/cc"
time="2022-01-14T17:13:24Z" level=debug msg="Creating load-balancer wrr"
time="2022-01-14T17:13:24Z" level=debug msg="Creating server nginx-deployment-65587f96cc-h8dft at http://10.3.19.242:80 with weight 1"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route /cc PathPrefix:/cc"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route simon-test.unipus.cn Host:simon-test.unipus.cn"
time="2022-01-14T17:13:24Z" level=debug msg="Wiring frontend 3-simon-test.unipus.cn/dd to entryPoint http"
time="2022-01-14T17:13:24Z" level=debug msg="Creating backend 3-simon-test.unipus.cn/dd"
time="2022-01-14T17:13:24Z" level=debug msg="Creating load-balancer wrr"
time="2022-01-14T17:13:24Z" level=debug msg="Creating server nginx-deployment-65587f96cc-h8dft at http://10.3.19.242:80 with weight 1"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route /dd PathPrefix:/dd"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route simon-test.unipus.cn Host:simon-test.unipus.cn"
time="2022-01-14T17:13:24Z" level=debug msg="Wiring frontend 3-simon-test.unipus.cn/ee to entryPoint http"
time="2022-01-14T17:13:24Z" level=debug msg="Creating backend 3-simon-test.unipus.cn/ee"
time="2022-01-14T17:13:24Z" level=debug msg="Creating load-balancer wrr"
time="2022-01-14T17:13:24Z" level=debug msg="Creating server nginx-deployment-65587f96cc-h8dft at http://10.3.19.242:80 with weight 1"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route /ee PathPrefix:/ee"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route simon-test.unipus.cn Host:simon-test.unipus.cn"
time="2022-01-14T17:13:24Z" level=debug msg="Wiring frontend 3-simon-test.unipus.cn/ff to entryPoint http"
time="2022-01-14T17:13:24Z" level=debug msg="Creating backend 3-simon-test.unipus.cn/ff"
time="2022-01-14T17:13:24Z" level=debug msg="Creating load-balancer wrr"
time="2022-01-14T17:13:24Z" level=debug msg="Creating server nginx-deployment-65587f96cc-h8dft at http://10.3.19.242:80 with weight 1"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route /ff PathPrefix:/ff"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route simon-test.unipus.cn Host:simon-test.unipus.cn"
time="2022-01-14T17:13:24Z" level=debug msg="Wiring frontend 3-simon-test.unipus.cn/gg to entryPoint http"
time="2022-01-14T17:13:24Z" level=debug msg="Creating backend 3-simon-test.unipus.cn/gg"
time="2022-01-14T17:13:24Z" level=debug msg="Creating load-balancer wrr"
time="2022-01-14T17:13:24Z" level=debug msg="Creating server nginx-deployment-65587f96cc-h8dft at http://10.3.19.242:80 with weight 1"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route /gg PathPrefix:/gg"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route simon-test.unipus.cn Host:simon-test.unipus.cn"
time="2022-01-14T17:13:24Z" level=debug msg="Wiring frontend 3-simon-test.unipus.cn/hh to entryPoint http"
time="2022-01-14T17:13:24Z" level=debug msg="Creating backend 3-simon-test.unipus.cn/hh"
time="2022-01-14T17:13:24Z" level=debug msg="Creating load-balancer wrr"
time="2022-01-14T17:13:24Z" level=debug msg="Creating server nginx-deployment-65587f96cc-h8dft at http://10.3.19.242:80 with weight 1"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route simon-test.unipus.cn Host:simon-test.unipus.cn"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route /hh PathPrefix:/hh"
time="2022-01-14T17:13:24Z" level=debug msg="Wiring frontend 3-simon-test.unipus.cn/ii to entryPoint http"
time="2022-01-14T17:13:24Z" level=debug msg="Creating backend 3-simon-test.unipus.cn/ii"
time="2022-01-14T17:13:24Z" level=debug msg="Creating load-balancer wrr"
time="2022-01-14T17:13:24Z" level=debug msg="Creating server nginx-deployment-65587f96cc-h8dft at http://10.3.19.242:80 with weight 1"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route /ii PathPrefix:/ii"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route simon-test.unipus.cn Host:simon-test.unipus.cn"
time="2022-01-14T17:13:24Z" level=debug msg="Wiring frontend 3-simon-test.unipus.cn/jj to entryPoint http"
time="2022-01-14T17:13:24Z" level=debug msg="Creating backend 3-simon-test.unipus.cn/jj"
time="2022-01-14T17:13:24Z" level=debug msg="Creating load-balancer wrr"
time="2022-01-14T17:13:24Z" level=debug msg="Creating server nginx-deployment-65587f96cc-h8dft at http://10.3.19.242:80 with weight 1"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route simon-test.unipus.cn Host:simon-test.unipus.cn"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route /jj PathPrefix:/jj"
time="2022-01-14T17:13:24Z" level=debug msg="Wiring frontend 3-simon-test.unipus.cn/kk to entryPoint http"
time="2022-01-14T17:13:24Z" level=debug msg="Creating backend 3-simon-test.unipus.cn/kk"
time="2022-01-14T17:13:24Z" level=debug msg="Creating load-balancer wrr"
time="2022-01-14T17:13:24Z" level=debug msg="Creating server nginx-deployment-65587f96cc-h8dft at http://10.3.19.242:80 with weight 1"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route /kk PathPrefix:/kk"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route simon-test.unipus.cn Host:simon-test.unipus.cn"
time="2022-01-14T17:13:24Z" level=debug msg="Wiring frontend 3-simon-test.unipus.cn/ll to entryPoint http"
time="2022-01-14T17:13:24Z" level=debug msg="Creating backend 3-simon-test.unipus.cn/ll"
time="2022-01-14T17:13:24Z" level=debug msg="Creating load-balancer wrr"
time="2022-01-14T17:13:24Z" level=debug msg="Creating server nginx-deployment-65587f96cc-h8dft at http://10.3.19.242:80 with weight 1"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route /ll PathPrefix:/ll"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route simon-test.unipus.cn Host:simon-test.unipus.cn"
time="2022-01-14T17:13:24Z" level=debug msg="Wiring frontend 7-bbb.unipus.cn/aa to entryPoint http"
time="2022-01-14T17:13:24Z" level=debug msg="Creating backend 7-bbb.unipus.cn/aa"
time="2022-01-14T17:13:24Z" level=debug msg="Creating load-balancer wrr"
time="2022-01-14T17:13:24Z" level=debug msg="Creating server nginx-66b6c48dd5-dgrd8 at http://10.3.22.255:80 with weight 1"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route /aa PathPrefix:/aa"
time="2022-01-14T17:13:24Z" level=debug msg="Creating route bbb.unipus.cn Host:bbb.unipus.cn"
time="2022-01-14T17:13:24Z" level=info msg="Server configuration reloaded on :80"
time="2022-01-14T17:13:24Z" level=info msg="Server configuration reloaded on :8080"
time="2022-01-14T17:13:27Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.29.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"simon-test.unipus.cn\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.3.21.249:8000\",\"RequestURI\":\"/api\",\"TLS\":null}"
time="2022-01-14T17:13:27Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL="http://10.3.19.242:80" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.29.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"simon-test.unipus.cn\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.3.21.249:8000\",\"RequestURI\":\"/api\",\"TLS\":null}"
time="2022-01-14T17:13:27Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"10.3.19.242:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.29.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"simon-test.unipus.cn\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.3.21.249:8000\",\"RequestURI\":\"/api\",\"TLS\":null}"
time="2022-01-14T17:13:27Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"10.3.19.242:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.29.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"simon-test.unipus.cn\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.3.21.249:8000\",\"RequestURI\":\"/api\",\"TLS\":null}"
time="2022-01-14T17:13:27Z" level=debug msg="Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel."
time="2022-01-14T17:13:27Z" level=debug msg="vulcand/oxy/forward/http: Round trip: http://10.3.19.242:80, code: 404, Length: 169, duration: 752.361µs"
time="2022-01-14T17:13:27Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"10.3.19.242:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.29.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"simon-test.unipus.cn\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.3.21.249:8000\",\"RequestURI\":\"/api\",\"TLS\":null}"
time="2022-01-14T17:13:27Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"http\",\"Opaque\":\"\",\"User\":null,\"Host\":\"10.3.19.242:80\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.29.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"simon-test.unipus.cn\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.3.21.249:8000\",\"RequestURI\":\"/api\",\"TLS\":null}"
time="2022-01-14T17:13:27Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"User-Agent\":[\"curl/7.29.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"simon-test.unipus.cn\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.3.21.249:8000\",\"RequestURI\":\"/api\",\"TLS\":null}"
10.3.21.249 - - [14/Jan/2022:17:13:27 +0000] "GET /api HTTP/1.1" 404 169 "-" "curl/7.29.0" 98 "3-simon-test.unipus.cn/api" "http://10.3.19.242:80" 1ms
```
