### ISSUE TITLE
Kubernetes CRD for Entrypoint

### ISSUE THREAD

**Issue by danmasta** [traefik/traefik#8704]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Currently, routing for `HTTP/TCP` is pretty simple using similar ports with SNI via `IngressRoute` and `IngressRouteTCP`. However, with `UDP` services you don't have the same flexibility, there is no SNI or same port forwarding for multiple backends. If you are hosting game servers, vpns, dns servers, or anything using `UDP` you have to use a different port for each backend service, which means you have to update your traefik config each time. If we want to add a game server for a new user, for example, we have to also update traefik config and re-deploy. This can cause a slight bit a downtime because the containers have to restart to acquire the new config. Which is not ideal.

The configuration for each server also cannot be represented in one single kubernetes manifest alone, because the separate traefik deployment also has to be updated to add the new `entrypoint` (port). However if we had an entrypoint CRD we could represent the new entrypoint along with the routes in the same config file. This would make traefik probably the easiest and best choice for setting up as a reverse proxy entrypoint to a huge variety of networks on kubernetes. Along with the UDP routing/middleware it would be way beyond most of it's competitors in the same space.

We could then represent the entrypoint and routing config in one file like:
```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: Entrypoint
metadata:
  name: game1
  namespace: {{NAMESPACE}}
spec:
  ports:
    - name: game1
      port: 2456
      expose: true
      exposedPort: 2456
      protocol: UDP
      # redirectTo: websecure (optional)
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: game1
  namespace: {{NAMESPACE}}
spec:
  entryPoints:
    - game1
  routes:
    - services:
      - name: game1
        namespace: {{NAMESPACE}}
        port: game1
---
# service config
---
# deployment config
---
```
