### ISSUE TITLE
Support K8s Gateway API HTTPRouteFilter for middlewares

### ISSUE THREAD

**Issue by TeoGoddet** [traefik/traefik#8705]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

I'm wondering if the support of [HTTPRouteFilter](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.HTTPRouteFilter) is planned, it would be a great way to define middlewares for gatewayAPI

Some reflexions about the implementation : 
The core and extended filters are defined in the gateway api to be consistent between implementations and would need to be translated to traefik middlewares

core filters (mandatory support) : 
- requestHeaderModifier ->  Headers
- requestRedirect -> RedirectRegex

extended filter (optional support) : 
-  requestMirror -> define a mirroring service
- URLRewrite -> ReplacePathRegex

There is support for implementation specific filter. 
In traefik, users should be able to input any traefik middleware config here.

Here I think there be either a middleware spec (probably the same as in KubernetesCRD provider) or middleware reference (defined where ?)

```
ExtensionRef:
   middlewareSpec:
      stripPrefix:
        prefixes:
          - /stripit
   middlewareRef:
       name: my-statically-defined-middleware
```

**OUTDATED : See first comment**
The last point I want to raise is about reusable middleware definition : 
With some providers you can have middlewares defined once for multiple routers
here, you have no place to define such middleware, i would suggest to add the possibility to define them in the gateway object. 
I will suggest this in the kubernetes gatewayAPI spec but it may also be implemented as custom traefik annotation on the gateway.

Last note, TCPRouteFilterType will probably come someday. ([#kubernetes-sigs/gateway-api/408](https://github.com/kubernetes-sigs/gateway-api/pull/408))

**Comment by TeoGoddet** [comment]
See https://github.com/kubernetes-sigs/gateway-api/issues/997

**Comment by romantomjak** [comment]
👋  Anyone from Traefik already planning to pick this up? I'd be willing to have a go at this otherwise. From a quick look around the [RedirectScheme](https://doc.traefik.io/traefik/middlewares/http/redirectscheme/) would be a good place to start?

**Comment by kevinpollet** [comment]
Hello @romantomjak, you are welcome to pick this up.

> From a quick look around the [RedirectScheme](https://doc.traefik.io/traefik/middlewares/http/redirectscheme/) would be a good place to start?

Right, as said in the issue we should support at least the `requestRedirect` and `requestHeaderModifier`.

**Comment by romantomjak** [comment]
Awsome, thanks! 🙌 

If you have a spare minute, could you please check out this [draft PR](https://github.com/traefik/traefik/pull/9408) and let me know if I'm moving in the right direction? It's pretty much a proof of concept atm, but if it generally looks okay, I will clean it up, add comments, etc and have a proper think about how to structure it so that it doesn't complicate any future middleware work for Gateway API

**Comment by smnbbrv** [comment]
The example config at https://github.com/traefik/traefik/blob/7fc56454ea9a2baa004db509a5a644bc199297c6/pkg/provider/kubernetes/gateway/fixtures/httproute/filter_http_to_https.yml#L42 does not seem to work with latest Gateway API

> HTTPRoute.gateway.networking.k8s.io "route-http" is invalid: spec.rules[0]: Invalid value: "object": RequestRedirect filter must not be used together with backendRefs.

**Comment by kevinpollet** [comment]
Hello @smnbbrv,

Thanks for pointing this out, could you please open a pull request to fix the test fixture?

**Comment by smnbbrv** [comment]
@kevinpollet thank you for your response. I do not really mean the test fixture, I can't get `RequestRedirect` to work properly. Without `backendRefs`, the corresponding traefik middleware gets created (according to traefik dashboard), however the route does not. When I add backendRefs (to mimic how the native IngressRoute works, it is required there to have the target server event for 301 redirect routes; that's actually what I linked in your test fixture above), it throws the error.

The following **does not** create a traefik route:

```yml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-http
spec:
  parentRefs:
    - name: example-gateway
      sectionName: http
  hostnames:
    - example.com
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
```

and the following throws an error

```yml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-http
spec:
  parentRefs:
    - name: example-gateway
      sectionName: http
  hostnames:
    - example.com
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
      backendRefs:
        - name: test
          port: 80
```

> HTTPRoute.gateway.networking.k8s.io "route-http" is invalid: spec.rules[0]: Invalid value: "object": RequestRedirect filter must not be used together with backendRefs.

Without `filters` section the second example works pretty well (but does not perform the redirect of course)

Is there something I miss?
