### ISSUE TITLE
service defined in docker labels will add an extra \ which causes error

### ISSUE THREAD

**Issue by winkee01** [traefik/traefik#8726]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

defined a service in the docker labels when I started a web app in a container, but the dashboard displayed an error saying the service did not exist. 

### What did you see instead?

![CleanShot 2022-01-24 at 20 18 54@2x](https://user-images.githubusercontent.com/49930785/150781903-f1d2bdd3-913f-47df-b397-13b685debff2.png)

From the snapshot we can see, it added a slash **`/`** in the service name, thus it cannot find the service.

### What version of Traefik are you using?

```
$ docker run traefik:v2.6 version
Version:      2.6.0-rc3
Codename:     rocamadour
Go version:   go1.17.6
Built:        2022-01-20T10:08:02Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
version: "3.9"
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    hostname: portainer
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './data:/data'
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.portainer-http.entrypoints=web
      - traefik.http.routers.portainer-http.rule=Host(`portainer.cloudlab.io`)
      - traefik.http.routers.portainer-http.middlewares=portainer-https@docker
      - traefik.http.routers.portainer-https.tls=true
      - traefik.http.routers.portainer-https.entrypoints=websecure
      - traefik.http.routers.portainer-https.rule=Host(`portainer.cloudlab.io`)
      - traefik.http.routers.portainer-https.service=portainer@docker" # If omit this, no error. If define this, error service not exist
      - traefik.http.middlewares.portainer-https.redirectscheme.scheme=https
      - traefik.http.middlewares.portainer-https.redirectScheme.permanent=true
      - traefik.http.middlewares.portainer-https.redirectScheme.port="443"
      - traefik.http.services.portainer.loadbalancer.server.scheme=http
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    networks:
      - web

networks:
  web:
    external: true
```

Add more configuration information here.
