### ISSUE TITLE
Docker creating weird router when using with file provider

### ISSUE THREAD

**Issue by WLun001** [traefik/traefik#8732]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

- using file and docker provider
- label a service in docker compose without router
```yaml
labels:
  traefik.enable: true
  traefik.http.services.whoami.loadbalancer.server.port: 80

```
- refer to the docker service in file provider router 
```yaml
http:
  routers:
    example.local:
      rule: Host(`example.localhost`)
      entrypoints:
        - web
      service: whoami@docker
```

### What did you see instead?

On the dashboard it creates one additional router (last item on the list), 
```
Host(`whoami-test-traefik`)
```
which is not defined by me
![image](https://user-images.githubusercontent.com/23547929/150895532-a2c6ffaf-be4b-4b64-bac0-98c1b86b1bc4.png)

### What version of Traefik are you using?

```
Version:      2.6.0
Codename:     rocamadour
Go version:   go1.17.6
Built:        2022-01-24T17:08:39Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

docker-compose.yml
```yaml
version: "3"

services:
  traefik:
    image: "traefik"
    container_name: "traefik"
    restart: always
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.file=true
      - --providers.file.directory=/config
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
    labels:
      traefik.enable: true

      # dashboard
      traefik.http.routers.dashboard.entrypoints: web
      traefik.http.routers.dashboard.rule: Host(`monitor.localhost`)
      traefik.http.routers.dashboard.service: api@internal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./data:/config/


  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    user: 1000:1000
    depends_on:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.whoami.loadbalancer.server.port: 80
```

data/data.yml
```yaml
http:
  routers:
    example.local:
      rule: Host(`example.localhost`)
      entrypoints:
        - web
      service: whoami@docker

```

### If applicable, please paste the log output in DEBUG level

```
traefik  | time="2022-01-25T01:52:22Z" level=info msg="Configuration loaded from flags."
traefik  | time="2022-01-25T01:52:22Z" level=info msg="Traefik version 2.6.0 built on 2022-01-24T17:08:39Z"
traefik  | time="2022-01-25T01:52:22Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"web\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"},\"file\":{\"directory\":\"/config\",\"watch\":true}},\"api\":{\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"pilot\":{\"dashboard\":true}}"
traefik  | time="2022-01-25T01:52:22Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
traefik  | time="2022-01-25T01:52:22Z" level=info msg="Starting provider aggregator.ProviderAggregator"
traefik  | time="2022-01-25T01:52:22Z" level=debug msg="Start TCP Server" entryPointName=web
traefik  | time="2022-01-25T01:52:22Z" level=info msg="Starting provider *file.Provider"
traefik  | time="2022-01-25T01:52:22Z" level=debug msg="*file.Provider provider configuration: {\"directory\":\"/config\",\"watch\":true}"
traefik  | time="2022-01-25T01:52:22Z" level=info msg="Starting provider *traefik.Provider"
traefik  | time="2022-01-25T01:52:22Z" level=debug msg="*traefik.Provider provider configuration: {}"
traefik  | time="2022-01-25T01:52:22Z" level=info msg="Starting provider *acme.ChallengeTLSALPN"
traefik  | time="2022-01-25T01:52:22Z" level=debug msg="*acme.ChallengeTLSALPN provider configuration: {\"Timeout\":4000000000}"
traefik  | time="2022-01-25T01:52:22Z" level=info msg="Starting provider *docker.Provider"
traefik  | time="2022-01-25T01:52:22Z" level=debug msg="*docker.Provider provider configuration: {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"}"
traefik  | time="2022-01-25T01:52:22Z" level=debug msg="Configuration received from provider file: {\"http\":{\"routers\":{\"example.local\":{\"entryPoints\":[\"web\"],\"service\":\"whoami@docker\",\"rule\":\"Host(`example.localhost`)\"}}},\"tcp\":{},\"udp\":{},\"tls\":{}}" providerName=file
traefik  | time="2022-01-25T01:52:22Z" level=debug msg="Configuration received from provider internal: {\"http\":{\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{}},\"serversTransports\":{\"default\":{\"maxIdleConnsPerHost\":200}}},\"tcp\":{},\"tls\":{}}" providerName=internal
traefik  | time="2022-01-25T01:52:22Z" level=debug msg="No default certificate, generating one" tlsStoreName=default
traefik  | time="2022-01-25T01:52:22Z" level=debug msg="Provider connection established with docker 20.10.12 (API 1.41)" providerName=docker
traefik  | time="2022-01-25T01:52:22Z" level=debug msg="Configuration received from provider docker: {\"http\":{\"routers\":{\"dashboard\":{\"entryPoints\":[\"web\"],\"service\":\"api@internal\",\"rule\":\"Host(`monitor.localhost`)\"}},\"services\":{\"traefik-test-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.18.0.2:80\"}],\"passHostHeader\":true}}}},\"tcp\":{},\"udp\":{}}" providerName=docker
traefik  | time="2022-01-25T01:52:22Z" level=error msg="the service \"whoami@docker\" does not exist" entryPointName=web routerName=example.local@file
traefik  | time="2022-01-25T01:52:22Z" level=debug msg="Creating middleware" middlewareType=Recovery entryPointName=web middlewareName=traefik-internal-recovery
traefik  | time="2022-01-25T01:52:22Z" level=debug msg="No default certificate, generating one" tlsStoreName=default
traefik  | time="2022-01-25T01:52:22Z" level=error msg="the service \"whoami@docker\" does not exist" routerName=example.local@file entryPointName=web
traefik  | time="2022-01-25T01:52:22Z" level=debug msg="Added outgoing tracing middleware api@internal" middlewareName=tracing middlewareType=TracingForwarder entryPointName=web routerName=dashboard@docker
traefik  | time="2022-01-25T01:52:22Z" level=debug msg="Creating middleware" middlewareType=Recovery middlewareName=traefik-internal-recovery entryPointName=web
whoami   | 2022/01/25 01:52:23 Starting up on port 80
traefik  | time="2022-01-25T01:52:23Z" level=debug msg="Provider event received {Status:start ID:1b834f19abdce78e28a35bfb23e2ace4f405b02c818174262d15fcc7f0c50d44 From:traefik/whoami Type:container Action:start Actor:{ID:1b834f19abdce78e28a35bfb23e2ace4f405b02c818174262d15fcc7f0c50d44 Attributes:map[com.docker.compose.config-hash:e6f3e800397485d95cb7e63701d82a84d7ed9d315be55c24dd505a40ca466919 com.docker.compose.container-number:1 com.docker.compose.depends_on:traefik com.docker.compose.image:sha256:e21a57f872cebada4cdd5978b2ecbdea41b5d91916553c4a0664b0fa69343773 com.docker.compose.oneoff:False com.docker.compose.project:test-traefik com.docker.compose.project.config_files:/home/wlun/Documents/development/nuwa/config/test-traefik/docker-compose.yaml com.docker.compose.project.working_dir:/home/wlun/Documents/development/nuwa/config/test-traefik com.docker.compose.service:whoami com.docker.compose.version:2.2.3 desktop.docker.io/wsl-distro:Ubuntu-20.04 image:traefik/whoami name:whoami traefik.enable:true traefik.http.services.whoami.loadbalancer.server.port:80]} Scope:local Time:1643075543 TimeNano:1643075543208962641}" providerName=docker
traefik  | time="2022-01-25T01:52:23Z" level=debug msg="Configuration received from provider docker: {\"http\":{\"routers\":{\"dashboard\":{\"entryPoints\":[\"web\"],\"service\":\"api@internal\",\"rule\":\"Host(`monitor.localhost`)\"},\"whoami-test-traefik\":{\"service\":\"whoami\",\"rule\":\"Host(`whoami-test-traefik`)\"}},\"services\":{\"traefik-test-traefik\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.18.0.2:80\"}],\"passHostHeader\":true}},\"whoami\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.18.0.3:80\"}],\"passHostHeader\":true}}}},\"tcp\":{},\"udp\":{}}" providerName=docker
traefik  | time="2022-01-25T01:52:24Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [web]" routerName=whoami-test-traefik
traefik  | time="2022-01-25T01:52:24Z" level=debug msg="No default certificate, generating one" tlsStoreName=default
traefik  | time="2022-01-25T01:52:24Z" level=debug msg="Creating middleware" serviceName=whoami middlewareName=pipelining middlewareType=Pipelining entryPointName=web routerName=whoami-test-traefik@docker
traefik  | time="2022-01-25T01:52:24Z" level=debug msg="Creating load-balancer" entryPointName=web routerName=whoami-test-traefik@docker serviceName=whoami
traefik  | time="2022-01-25T01:52:24Z" level=debug msg="Creating server 0 http://172.18.0.3:80" serviceName=whoami entryPointName=web serverName=0 routerName=whoami-test-traefik@docker
traefik  | time="2022-01-25T01:52:24Z" level=debug msg="child http://172.18.0.3:80 now UP"
traefik  | time="2022-01-25T01:52:24Z" level=debug msg="Propagating new UP status"
traefik  | time="2022-01-25T01:52:24Z" level=debug msg="Added outgoing tracing middleware whoami" middlewareType=TracingForwarder entryPointName=web routerName=whoami-test-traefik@docker middlewareName=tracing
traefik  | time="2022-01-25T01:52:24Z" level=debug msg="Creating middleware" middlewareType=Pipelining entryPointName=web routerName=example.local@file serviceName=whoami@docker middlewareName=pipelining
traefik  | time="2022-01-25T01:52:24Z" level=debug msg="Creating load-balancer" routerName=example.local@file serviceName=whoami@docker entryPointName=web
traefik  | time="2022-01-25T01:52:24Z" level=debug msg="Creating server 0 http://172.18.0.3:80" entryPointName=web routerName=example.local@file serverName=0 serviceName=whoami@docker
traefik  | time="2022-01-25T01:52:24Z" level=debug msg="child http://172.18.0.3:80 now UP"
traefik  | time="2022-01-25T01:52:24Z" level=debug msg="Propagating new UP status"
traefik  | time="2022-01-25T01:52:24Z" level=debug msg="Added outgoing tracing middleware whoami@docker" routerName=example.local@file entryPointName=web middlewareName=tracing middlewareType=TracingForwarder
traefik  | time="2022-01-25T01:52:24Z" level=debug msg="Added outgoing tracing middleware api@internal" middlewareName=tracing middlewareType=TracingForwarder routerName=dashboard@docker entryPointName=web
traefik  | time="2022-01-25T01:52:24Z" level=debug msg="Creating middleware" middlewareType=Recovery entryPointName=web middlewareName=traefik-internal-recovery
```
