### ISSUE TITLE
Server crash/OOM when `--http.routers.traefik.service=api@internal` used

### ISSUE THREAD

**Issue by agneevX** [traefik/traefik#8741]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I have the Docker `defaultRule` set to use the `com.docker.compose.service` label so that's in the format `<SERVICE_NAME>.<MACHINE_NAME>.nt`.

So in order to access the traefik dashboard, I set a compose label for the traefik service. That has worked out well, except today I tried to move _it_ into a command, unsure whether it'd work or not.

```yml
# From
...
    labels:
      traefik.http.routers.traefik.service: api@internal

# To
...
    command:
      "--http.routers.traefik.service=api@internal"
```

Within seconds of trying to access `traefik.<MACHINE_NAME>.nt`, the Raspberry Pi server stopped responding and I had to power cycle it after waiting a while.

I tried to reproduce it on another Pi which uses a similar default dockerRule and upon accessing `traefik.<MACHINE_NAME>.nt`, I noticed high CPU and memory usage from Traefik.
I stopped the service immediately.

Graphs from Portainer upon accessing the site:

![image](https://user-images.githubusercontent.com/19761269/151322576-828cae12-b8bd-4302-9665-e1d5f4e344ea.png)

### What did you see instead?

☝️

### What version of Traefik are you using?

v2.5

### What is your environment & configuration?

```yaml
version: '3.9'
  traefik:
    container_name: traefik
    image: traefik:v2.5
    restart: unless-stopped
    command:
      "--http.routers.traefik.service=api@internal"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
    extra_hosts:
      - "host.docker.internal:10.0.0.11"
    ports:
      - 80:80
      - 444:443
    volumes:
      - /opt/appdata/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

Add more configuration information here.

**Comment by ldez** [comment]
Hello,

`--http.routers.traefik.service=api@internal` is a label, you cannot use it in the `command` section.

It will just produce an error and exit:
```
command traefik error: failed to decode configuration from flags: field not found, node: http
exited with code 1
```

**Comment by agneevX** [comment]
Ok, but it causes the reported issues, even if used improperly. Shouldn't this at least be investigated?

> It will just produce an error and exit

Except it did not.

**Comment by ldez** [comment]
The error is expected: if you provide an invalid flag Traefik has to stop.

**Comment by agneevX** [comment]
That server literally crashed due to rapid OOM, while the other server nearly OOMed. I think you fail to recognize the gravity of the issue. All without no errors and **not stopping**.

I've provided graphs above, that show just how fast traefik is consuming memory. What you're saying is simply not true.

**Comment by ldez** [comment]
```yml
version: '3.9'

services:
  traefik:
    image: traefik:v2.6.0
    command:
      - --http.routers.traefik.service=api@internal
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: 'true'

      traefik.http.routers.traefik.rule: Host(`traefik.localhost`)
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.service: api@internal

  whoami:
    image: traefik/whoami:v1.7.1
    labels:
      traefik.enable: 'true'

      traefik.http.routers.app.rule: Host(`whoami.localhost`)
```

```console
$ docker-compose up --remove-orphans
[+] Running 3/3
 ⠿ Container issue-traefik-whoami-1   Recreated                                                                                                                                 0.1s
 ⠿ Container issue-traefik-traefik-1  Recreated                                                                                                                                 0.1s
Attaching to issue-traefik-traefik-1, issue-traefik-whoami-1
issue-traefik-whoami-1   | 2022/01/27 10:27:08 Starting up on port 80
issue-traefik-traefik-1  | 2022/01/27 10:27:08 command traefik error: failed to decode configuration from flags: field not found, node: http
issue-traefik-traefik-1 exited with code 1
```

```console
$ docker ps
CONTAINER ID   IMAGE                   COMMAND     CREATED         STATUS          PORTS     NAMES
48b6d5de249e   traefik/whoami:v1.7.1   "/whoami"   9 minutes ago   Up 10 seconds   80/tcp    issue-traefik-whoami-1
```

**Comment by agneevX** [comment]
I've mounted `/etc/traefik`.

Contains `traefik.yml`:

```yml
pilot:
  token: 

api: {}
ping: {}
metrics:
  prometheus: {}

entrypoints:
  http:
     address: ":80"
  secure:
    address: ":443"

experimental:
  plugins:
    souin:
      moduleName: github.com/darkweak/souin
      version: v1.5.11-beta7
    fail2ban:
      moduleName: github.com/tommoulard/fail2ban
      version: v0.6.2

providers:
  file:
    filename: /etc/traefik/file-provider.yml
    watch: true

  docker:
    defaultRule: Host(`{{ index .Labels "com.docker.compose.service" }}.falcon.nt`)
```

**Comment by ldez** [comment]
I think that your problem is not related to the label but to the plugins, I recommend using v2.6.0 (or v2.5.7) by setting the version explicitly instead of `v2.5`

**Comment by agneevX** [comment]
I commented out the plugins to test and nope, the memory leak is still present.

```yml
traefik:
  container_name: traefik
  image: traefik:v2.6.0
  restart: unless-stopped
  command: ["--http.routers.traefik.service=api@internal"]
  ports:
    - 80:80
    - 444:443
  volumes:
    - /opt/appdata/traefik:/etc/traefik
    - /var/run/docker.sock:/var/run/docker.sock:ro
```

```yml
api: {}
ping: {}
metrics:
  prometheus: {}

entrypoints:
  http:
     address: ":80"
  secure:
    address: ":443"

providers:
  docker:
    defaultRule: Host(`{{ index .Labels "com.docker.compose.service" }}.falcon.nt`)
```
