### ISSUE TITLE
Can't activate HTTP3 Traefik 2.6

### ISSUE THREAD

**Issue by chichi13** [traefik/traefik#8744]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

- I enabled HTTP3 on traefik 2.6 (experimental)
- I went to https://http3check.net/ and checked my website : 

```
HTTP/3 Check could not get establish a QUIC connection due to the error given below.

QUIC connection could not be established
```

### What did you see instead?

HTTP3 is not enabled on my website.

### What version of Traefik are you using?

Traefik 2.6.0

### What is your environment & configuration?

I tried several configurations : 

```yaml
experimental:
  http3: true

entryPoints:
  name:
    http3:
      advertisedPort: 443
  web:
    address: :80
  websecured:
    http3: {}
    address: :443
```

Or : 

```yaml
experimental:
  http3: true

entryPoints:
  web:
    address: :80
  websecured:
    http3: {}
    address: :443
```

Did I do something wrong ?
