### ISSUE TITLE
Allow configuring server URLs with label providers

### ISSUE THREAD

**Issue by firstdorsal** [traefik/traefik#8753]
Hi i would love to have this possibility
Configure traefik via label providers: allow setting the `traefik.http.services.<service-name>.loadBalancer.server.url`

for example in docker:
```yaml
version: "3.7"
services:
    rp:
        labels:
            traefik.http.routers.proxy.entryPoints: web
            traefik.http.routers.proxy.service: proxy-crt
            traefik.http.routers.proxy.rule: PathPrefix(`/proxy-crt`)
            traefik.http.routers.proxy.middlewares: strip-crt, cors-crt

            traefik.http.services.proxy.loadBalancer.server.url: ${A_URL_AS_VARIABLE}

            traefik.http.middlewares.strip.stripPrefix.prefixes: /proxy-crt

            traefik.http.middlewares.cors.headers.accessControlAllowMethods: GET,OPTIONS
            traefik.http.middlewares.cors.headers.accessControlAllowOriginlist: "*"
            traefik.http.middlewares.cors.headers.accessControlMaxAge: 86400

```

I have seen this question:
https://community.traefik.io/t/traefik-v2-with-docker-compose-external-services-possible/5792/2

I know that setting this exact configuration is possible with the file provider but as far as i know not with a variable.

```yaml
http:
    routers:
        proxy:
            entryPoints:
                - web
            middlewares:
                - strip
                - cors
            service: proxy
            rule: PathPrefix(`/proxy`)

    services:
        proxy:
            loadBalancer:
                passHostHeader: false
                servers:
                    - url: https://example.com # NOT CONTROLLABLE VIA VARIABLE

    middlewares:
        strip:
            stripPrefix:
                prefixes:
                    - /proxy
        cors:
            headers:
                accessControlAllowMethods: GET,OPTIONS
                accessControlAllowOriginlist: "*"
                accessControlMaxAge: 86400


```

A similar thing is possible with domain certs:
```yaml
traefik.http.routers.myrouter.tls.domains[0].main: example.org
```
could then look like this:
```yaml
 traefik.http.services.proxy.loadBalancer.servers[0].url: ${A_URL_AS_VARIABLE}
```

**Comment by rtribotte** [comment]
Hello @firstdorsal,

Thanks for your interest in Traefik!

There is already a proposal opened for that feature for the ECS provider: https://github.com/traefik/traefik/issues/7568.

Could you widen the scope of the feature in the title and the description of your issue, in order to keep only yours and track the feature having all "labels" providers in scope?

**Comment by firstdorsal** [comment]
like this?

**Comment by ZaxLofful** [comment]
Any traction on this? It seems to have been open for awhile, I just recently found this issue; and would like to have an ETA for when I can use this?

**Comment by tomMoulard** [comment]
Hello @ZaxLofful,

Thanks for your interest in Traefik!

We labeled this issue as [`kind/proposal`](https://github.com/traefik/traefik/labels/kind%2Fproposal), which means that it needs to be refined before any implementation. While the use case is clear, we are wondering what the best option is.

As well, it means that it is not on our roadmap by any means, so it cannot be expected to see this implemented shortly.

**Comment by bjarnekrottje** [comment]
Same for me, would be great if this would be implemented!

**Comment by ZaxLofful** [comment]
> Hello @ZaxLofful,
> 
> Thanks for your interest in Traefik!
> 
> We labeled this issue as [`kind/proposal`](https://github.com/traefik/traefik/labels/kind%2Fproposal), which means that it needs to be refined before any implementation. While the use case is clear, we are wondering what the best option is.
> 
> As well, it means that it is not on our roadmap by any means, so it cannot be expected to see this implemented shortly.

Well it seems trivial to just add it, since you already use the actual parameters already; you just have not allowed it in this context.

Looking back at the original topic...You've had the better part two years to figure this out. So it sounds like you need someone to just make a decision about it. If so put it in front of someone important enough and make a decision.

**Comment by tfny** [comment]
Hey @ZaxLofful, I am thrilled that you are so passionate about this issue.  I am sure you understand that as a small team supporting an open-source project, we have to be ruthless about scope creep.

Unfortunately, as Tom said, this is not currently on our roadmap.  The team is evaluating the proposal, and it may land on the roadmap or they may invite the community to build this proposal (or they may decide it does not fit with the priorities of the next sprint).

Until then, you are welcome to fork and add it for yourself. :)

**Comment by ZaxLofful** [comment]
So it seems this is a bug in implementation?

According to the linked issue above: https://github.com/anomaly/lab-python-server/issues/62

It works for Kubernetes, but your Docker backed is just not configured correctly to accept the parameters?

**Comment by ldez** [comment]
It's not a bug: the Docker provider handles containers, so the service is related to containers, and container URLs are built automatically.
The providers cannot be compared because the constraints are not the same.
To handle backends outside Docker you have to use the file provider.

**Comment by ZaxLofful** [comment]
So it's possible, but ya'll refuse to do it?

**Comment by djarbz** [comment]
I would like to add my 2 cents in for a use case.
I currently have Traefik deployed with Podman.
My traefik container is setup to use `--network host` and my containers bind their port to `127.0.0.1`.
I would like to specify the URL as a label to point to localhost rather than the container IP.
My current workaround is to use the file provider, but I think a label provider would be much cleaner and able to deploy new services and take services down as the containers are started or stopped.

File Provider
```yaml
http:
  routers:
    whoami:
      rule: "Host(`whoami{{ env "DOMAIN" }}`)"
      middlewares:
        - chain-authentik
      service: whoami
  services:
    whoami:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8946"
```

Podman Labels
```ini
Label="traefik.enable=true"
Label="traefik.http.routers.whoami.rule=Host(`whoami.{{ env "DOMAIN" }}`)"
Label="traefik.http.routers.whoami.service=whoami"
Label="traefik.http.services.whoami.loadbalancer.server.url=http://127.0.0.1:8946"
```

**Comment by nmengin** [comment]
Hello @djarbz,

Could you please elaborate on your use case?
Indeed, from what I understood, the behavior you've described (podman, network mode host) should be handled by the Docker provider in its current implementation as described in [the documentation](https://doc.traefik.io/traefik/providers/docker/#host-networking).

**Comment by djarbz** [comment]
Sure.

I have Traefik running in host mode as it is more efficient, especially in rootless and getting the correct source IP.

My containers, however, are using the default bridge.

It is my understanding, and I could be wrong, that if Traefik is running in host mode, I am unable to add bridges as well.
As such, I bind my containers to 127.0.0.x and currently use dynamic files to describe how to connect to the downstream with 127.0.0.1.

To my experience, I was unable to specify the URL using a label as Traefik was expecting it to be available on a shared bridge.

Hopefully this clears things up.

**Comment by ruimarinho** [comment]
I'm on exactly @djarbz's scenario too. Ideally we would be able to keep the declarative approach of using a label on the container where the server url is not the typical service name - since traefik isn't connecting via a container network - but 127.0.0.1 instead.

**Comment by ZaxLofful** [comment]
My case is slightly different from the previous comments:

I am running Traefik/Docker on a Synology DS920+ and the Synology software runs its own UI that is not part of Docker.

I have forced Traefik to take the ports from Synology so that I can use it properly.

I want to be able to have Traefik be the reverse proxy for the Synology UI.

Since its not a container I cannot add these labels to a container, what I want to do is add the labels to the Traefik container itself to create another loadbalance service for DSM and give it a FQDN to use.

Since the feature listed here is not implemented to allow those labels, this fails.

I know I could just do that with a Traefik config file, but that would mean creating a config file for a single line of code; when every other possible parameter is configurable via the docker-compose syntax.

**Comment by nmengin** [comment]
Hello @djarbz @ruimarinho @ZaxLofful,
Thank you for your feedback.

If anybody else has another use case in mind, we'd like to hear about it: thus we could have a global overview of the underlying needs of this issue.

**Comment by jahartley** [comment]
I have development items running on bare metal, home assistant on bare metal and ghost blogs in docker containers. If I have traefik in a docker container, there is no way for it to route to the items on bare metal, as it is blocked by docker, even using the file provider. I really liked the idea of using the docker provider, but when I use the traefik container in network=host so that it can talk to everything not in containers, it will then still try and route to a url inside the containers, which is unreachable. If I expose the port for the container, there is no way to force traefik to route to HOST_IP:port specified in label. It always picks something unreachable. I'm back to just using open ports in the docker containers and removing the docker provider, and just using the file provider.

**Comment by antwacky** [comment]
I would also be interested in this feature, I am using ECS which means adding file providers is a pain. You have to build a new image with the file provider baked in.

If I could add a label to the traefik container, that would be much better. A label such as:

traefik.http.services.example.loadbalancer.server.url = "https://example.com/"

So that I can use the Traefik container to proxy requests without having rebuild the Traefik image.

**Comment by lost22git** [comment]
+1 hope this configuration is supported

**Comment by geraldcroes** [comment]
Thank you for the upvote.

I think at this point we have enough information to understand the use case, and we should decide on whether we want to support the feature or not.

We've had quite a long conversation during the triage process, with pros and cons.

Let's have a quick vote on 👍 in favor 👎 not in favor (and I think it's worth it to explain why as well)

**Comment by peterd550** [comment]
I am running traefik in docker-compose with nextcloud and having the same issue with the wrong IP address
being set:

level=debug msg="Creating load-balancer" entryPointName=web-secured routerName=nextcloud-secure@docker serviceName=nextcloud-nextcloud
time="2023-11-19T20:37:29+11:00" level=debug msg="Creating server 0 http://192.168.0.3:80" serverName=0 entryPointName=web-secured routerName=nextcloud-secure@docker serviceName=nextcloud-nextcloud
time="2023-11-19T20:37:29+11:00" level=debug msg="child http://192.168.0.3:80 now UP"
time="2023-11-19T20:37:29+11:00" level=debug msg="Propagating new UP status"
time="2023-11-19T20:37:29+11:00" level=debug msg="Added outgoing tracing middleware nextcloud-nextcloud" middlewareType=TracingForwarder routerName=nextcloud-secure@docker entryPointName=web-secured middlewareName=tracing
time="2023-11-19T20:37:29+11:00" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=web-secured
time="2023-11-19T20:37:29+11:00" level=debug msg="Adding route for nextcloud-nextcloud with TLS options default" entryPointName=web-secured

my label for docker-compose with nextcloud

- "traefik.http.services.nextcloud.loadbalancer.servers.url=http://10.0.0.140:81/"

in my dymanic docker-compose i am running the loadbalancer conf but is not working.
My certs are working. 

http:
  routers:
    routernextcloud:
      rule: "Host(`my domain`) && Path(`/`)"
        service: nextcloud
          tls:
            stores:
              default:
                defaultCertificate:
                  certFile: ./conf/nextcloud.cert
                  keyFile: ./conf/nextcloud.key

## Dynamic configuration
#http:
  services:
    nextcloud-nextcloud:
      loadBalancer:
        servers:
          - url: "http://10.0.0.140:81"

Am I missing something from my dynamic.yaml?
How can I get the loadbalancer to have my internal IPn address?

**Comment by ZaxLofful** [comment]
> I am running traefik in docker-compose with nextcloud and having the same issue with the wrong IP address
> 
> being set:
> 
> ```
> 
> level=debug msg="Creating load-balancer" entryPointName=web-secured routerName=nextcloud-secure@docker serviceName=nextcloud-nextcloud
> 
> time="2023-11-19T20:37:29+11:00" level=debug msg="Creating server 0 http://192.168.0.3:80" serverName=0 entryPointName=web-secured routerName=nextcloud-secure@docker serviceName=nextcloud-nextcloud
> 
> time="2023-11-19T20:37:29+11:00" level=debug msg="child http://192.168.0.3:80 now UP"
> 
> time="2023-11-19T20:37:29+11:00" level=debug msg="Propagating new UP status"
> 
> time="2023-11-19T20:37:29+11:00" level=debug msg="Added outgoing tracing middleware nextcloud-nextcloud" middlewareType=TracingForwarder routerName=nextcloud-secure@docker entryPointName=web-secured middlewareName=tracing
> 
> time="2023-11-19T20:37:29+11:00" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=web-secured
> 
> time="2023-11-19T20:37:29+11:00" level=debug msg="Adding route for nextcloud-nextcloud with TLS options default" entryPointName=web-secured
> 
> ```
> 
> my label for docker-compose with nextcloud
> 
> ```
> 
> - "traefik.http.services.nextcloud.loadbalancer.servers.url=http://10.0.0.140:81/"
> 
> ```
> 
> in my dymanic docker-compose i am running the loadbalancer conf but is not working.
> 
> My certs are working. 
> 
> ```
> 
> http:
> 
>   routers:
> 
>     routernextcloud:
> 
>       rule: "Host(`my domain`) && Path(`/`)"
> 
>         service: nextcloud
> 
>           tls:
> 
>             stores:
> 
>               default:
> 
>                 defaultCertificate:
> 
>                   certFile: ./conf/nextcloud.cert
> 
>                   keyFile: ./conf/nextcloud.key
> 
> 
> 
> ## Dynamic configuration
> 
> #http:
> 
>   services:
> 
>     nextcloud-nextcloud:
> 
>       loadBalancer:
> 
>         servers:
> 
>           - url: "http://10.0.0.140:81"
> 
> ```
> 
> Am I missing something from my dynamic.yaml?
> 
> How can I get the loadbalancer to have my internal IPn address?

It's not working yet, that is what this issue is about.

**Comment by hadim** [comment]
I would like to also be able to use `traefik.http.services.nextcloud.loadbalancer.servers[0].url=http://domain.com/` or something similar with the docker provider only.

My use case is basic: I just want to stick to the docker provider only and not have to deal with the file provider that I only use for this since the rest of the configuration is defined in my docker compose files.

**Comment by subvillion** [comment]
I would also be interested in this feature to. Now my real services hided behind tailscale like mesh network and something like `traefik.http.services.meshed.loadbalancer.servers[0].url=http://99.99.99.99:4444` looks pretty useful

**Comment by nmengin** [comment]
Hello @subvillion,

Thanks for reaching out.

We think this feature makes a lot of sense. 
Unfortunately, this would not make it to our roadmap for a while as we are focused elsewhere.

If you or another community member would like to build it, let us know, and we will work with you to make sure you have all the information needed so that it can be merged.

**Comment by Larry57** [comment]
First of all, a big thank you for this fantastic tool that saves us a lot of time and sweat.

It's understandable that the label-based notation in a docker-compose may not reflect 100% of the yaml/toml options, but this use case where you want to route a call to a service external to the container is very common.

You can see this just by looking at the amount of posts in forums where the question "how to route to an external service with docker and traefik" is asked, and invariably, the question revolves around "-- traefik.http.services.<service-name>.loadBalancer.server.url" which doesn't work, and only solutions using a rules.yml file rather than labels work for this reason alone. Also, the label notation implies "server", whereas the rules.yml file uses "servers", which is confusing.

I'm definitely convinced that this topic deserves attention.

**Comment by ivs** [comment]
A little bit hacky workaround:
```  yaml
reverse-proxy:
    image: traefik:2.11
    entrypoint: /bin/sh
    command: >
      -c "mkdir -p config && echo \"$$TLS_CONFIG\" > /config/tls.yml &&
      echo \"$$GITLAB_SERVICE\" > /config/gilab.yml && exec /entrypoint.sh
      --entrypoints.web.address=:80
      --entrypoints.websecure.address=:443
      --api.insecure=true
      --providers.docker
      --providers.file.directory=/config"

    environment:
      TLS_CONFIG: |
        tls:
          certificates:
            - certFile: /certs/fullchain1.pem
              keyFile: /certs/privkey1.pem
      GITLAB_SERVICE: |
        http:
          services:
            gitlab:
              loadBalancer:
                servers:
                  - url: http://host.docker.internal:88
    ports:
      - "80:80"
      - "443:443"
      - "${HOST_IP:-127.0.0.1}:8800:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/certs:/certs
    labels:
      - traefik.http.middlewares.auth.basicauth.users=<hidden>

      - traefik.http.routers.traefik.rule=Host(`traefik.$URL`)
      - traefik.http.routers.traefik.service=traefik
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.middlewares=auth

      - traefik.http.routers.gitlab.rule=Host(`gitlab.$URL`)
      - traefik.http.routers.gitlab.service=gitlab@file
      - traefik.http.routers.gitlab.entrypoints=websecure
      - traefik.http.routers.gitlab.tls=true
```
If ssl and external http service configs both can be moved to labels - it would be amazing!
