### ISSUE TITLE
Nil configuration instead of the real item value in plugin

### ISSUE THREAD

**Issue by darkweak** [traefik/traefik#8772]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I made a plugin which can handle the configuration
```yaml
myItem:
  firstChild:
  secondChild:
```

I must have an object like MyItem not nil

### What did you see instead?

MyItem is nil

### What version of Traefik are you using?

latest

### What is your environment & configuration?

```yaml
http:
  routers:
    whoami:
      middlewares:
        - myAwesomePlugin
      entrypoints:
        - http
      service: whoami
      rule: Host(`domain.com`)

  services:
    whoami:
      loadBalancer:
        servers:
          - url: http://whoami
        passHostHeader: false

  middlewares:
    myAwesomePlugin:
      plugin:
        awesome-plugin:
          myItem:
            firstChild:
            secondChild:
```

### If applicable, please paste the log output in DEBUG level

traefik_1  | time="2022-02-13T15:08:52Z" level=debug plugin=plugin-souin-plugin module=github.com/darkweak/souin
traefik_1  | time="2022-02-13T15:08:52Z" level=debug module=github.com/darkweak/souin plugin=plugin-souin-plugin

**Comment by ldez** [comment]
Hello,

The YAML spec says that an empty element must be written like that:

```yaml
myItem:
  firstChild: {}
  secondChild: {}
```
