### ISSUE TITLE
letsencrypt acme providers : move providers settings from envar to the main traefik config file

### ISSUE THREAD

**Issue by dginhoux** [traefik/traefik#8782]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Hi, 

When using letsencrypt acme with dnsChallenge, we need to use an API from our registrar/dns provider to create some DNS records for the challenge work.

In case of having multiples domain names, on the same registrar/dns provder BUT on differents "administratives" accounts, we a have a problem because we have more than one API keys.

My feature request is to move dnsChallenge providers settings documented here : https://doc.traefik.io/traefik/https/acme/#providers

To the main traefik config file like this example : 
```
certificatesResolvers:
  letsencrypt-ovh-1:
    acme:
      email: mail-1@mail.com
      storage: /traefik-certs/letsencrypt-ovh-1.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      keyType: RSA4096
      dnsChallenge:
        provider: ovh
        OVH_APPLICATION_KEY: 111111
        OVH_APPLICATION_SECRET: 111111
        OVH_CONSUMER_KEY: 111111
        OVH_ENDPOINT: ovh-eu
        OVH_HTTP_TIMEOUT: 300
        OVH_POLLING_INTERVAL: 20
        OVH_PROPAGATION_TIMEOUT: 600
        OVH_TTL: 3600
        delayBeforeCheck: 20
        resolvers:
          - dns113.ovh.net:53
          - ns113.ovh.net:53
  letsencrypt-ovh-2:
    acme:
      email: mail-2@mail.com
      storage: /traefik-certs/letsencrypt-ovh-2.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      keyType: RSA4096
      dnsChallenge:
        provider: ovh
        OVH_APPLICATION_KEY: 222222
        OVH_APPLICATION_SECRET: 222222
        OVH_CONSUMER_KEY: 222222
        OVH_ENDPOINT: ovh-eu
        OVH_HTTP_TIMEOUT: 300
        OVH_POLLING_INTERVAL: 20
        OVH_PROPAGATION_TIMEOUT: 600
        OVH_TTL: 3600
        delayBeforeCheck: 20
        resolvers:
          - dns113.ovh.net:53
          - ns113.ovh.net:53

```
