### ISSUE TITLE
Roundrobin reinit on config reload on each ingress event from kubernetes provider

### ISSUE THREAD

**Issue by a-bouts** [traefik/traefik#8787]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

We are using Traefik v2.6 as ingress controller on kubernetes cluster 1.20.
An application is deployed with several instances.

A classic roundrobin load balancing is configured to reach the application through traefik.

### What did you see instead?

We have notice that load balancing is not working properly : 80% of the requests are sent to the same application pod.

After investigation we noticed that :
- all ingresses configurations are reloaded on each ingress modification.
- The loadbalancers are recreated on each config reload (kind of roundrobin counter his reset)
- as a result. the next request will reach the first backend of the list

If the reload of the configuration is frequent and the requests to the service not so frequent, each request go to the same pod.
Combined with sticky session, most users reaching an application will be connected to the same pod every time.

### What version of Traefik are you using?

2.6.1

### What is your environment & configuration?

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: traefik-test
spec:
  containers:
    - name: traefik-test
      image: traefik:v2.6.1
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /ping
          port: ping
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      args:
        - --api=true
        - --api.dashboard=true
        - --api.insecure=true
        - --ping=true
        - --log.level=DEBUG
        - --log.format=json
        - --accesslog=true
        - --accesslog.format=json
        - --accesslog.fields.defaultmode=keep
        - --accesslog.fields.headers.defaultmode=keep
        - --metrics.prometheus
        - --entrypoints.web.address=:8081
        - --entrypoints.websecure.address=:8443
        - --entryPoints.websecure.http.tls=true
        - --entryPoints.ping.address=:8082
        - --ping.entryPoint=ping
        - --providers.kubernetesingress=true
        - --providers.kubernetescrd=true
        - --providers.kubernetesingress.ingressclass=traefik
      ports:
      - containerPort: 8081
        hostPort: 8080
        name: web
        protocol: TCP
      - containerPort: 8443
        hostPort: 8443
        name: websecure
        protocol: TCP
      - containerPort: 8080
        name: admin
        protocol: TCP
      - containerPort: 8082
        name: ping
        protocol: TCP
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
  serviceAccount: traefik-ingress-controller
```

We have about 2000 ingresses with permanent new Events asking for a configuration reload

### If applicable, please paste the log output in DEBUG level

Part of the log showing some ingress reloading without any modifications on this one.

```
{"entryPointName":"web","level":"debug","msg":"Creating load-balancer","routerName":"echo-traefik-jeff-echo-jeff-example-com@kubernetes","serviceName":"jeff-service-echo-headers-80","time":"2022-02-18T14:15:46Z"}
{"entryPointName":"web","level":"debug","msg":"Creating load-balancer","routerName":"echo-traefik-jeff-echo-jeff-example-com@kubernetes","serviceName":"jeff-service-echo-headers-80","time":"2022-02-18T14:15:52Z"}
{"entryPointName":"web","level":"debug","msg":"Creating load-balancer","routerName":"echo-traefik-jeff-echo-jeff-example-com@kubernetes","serviceName":"jeff-service-echo-headers-80","time":"2022-02-18T14:15:54Z"}
{"entryPointName":"web","level":"debug","msg":"Creating load-balancer","routerName":"echo-traefik-jeff-echo-jeff-example-com@kubernetes","serviceName":"jeff-service-echo-headers-80","time":"2022-02-18T14:17:03Z"}
{"entryPointName":"web","level":"debug","msg":"Creating load-balancer","routerName":"echo-traefik-jeff-echo-jeff-example-com@kubernetes","serviceName":"jeff-service-echo-headers-80","time":"2022-02-18T14:17:52Z"}
{"entryPointName":"web","level":"debug","msg":"Creating load-balancer","routerName":"echo-traefik-jeff-echo-jeff-example-com@kubernetes","serviceName":"jeff-service-echo-headers-80","time":"2022-02-18T14:18:04Z"}
{"entryPointName":"web","level":"debug","msg":"Creating load-balancer","routerName":"echo-traefik-jeff-echo-jeff-example-com@kubernetes","serviceName":"jeff-service-echo-headers-80","time":"2022-02-18T14:18:06Z"}
```
