### ISSUE TITLE
Use IPv6 address from Docker API for URL when available

### ISSUE THREAD

**Issue by joachimtingvold** [traefik/traefik#8789]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

1. Configure Docker to support IPv6 addresses.
2. Create docker-compose with Traefik + some service.
3. Configure labels on said service to enable Traefik
4. Expect Traefik to use IPv6 address for the service URL

### What did you see instead?

Traefik picks the containers IPv4 address for the backend server URL (even when IPv6 address is available).

I'd expect the URL to be `http://[fd10:255:3::2]:80`.

![image](https://user-images.githubusercontent.com/359918/154824608-f236864f-8ec3-445a-9a58-a9813fc85db0.png)

```
root@docker1:/srv/config/docker/test# docker inspect test-whoami
[
    {
        […]
            "Networks": {
                "test": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "test-whoami",
                        "a7c6ec8c1357"
                    ],
                    "NetworkID": "c2ccfda57d35f43d8e4dbaaeb9beb97c118f47c9454410c2132914af4cf2c640",
                    "EndpointID": "8f6c92c67c1ef4ab5faf861aadec883d91103cc1a6ab0133d8fb62aea30a7b71",
                    "Gateway": "10.128.3.1",
                    "IPAddress": "10.128.3.2",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "fd10:255:3::1",
                    "GlobalIPv6Address": "fd10:255:3::2",
                    "GlobalIPv6PrefixLen": 64,
                    "MacAddress": "02:42:0a:80:03:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

### What version of Traefik are you using?

```
Version:      2.6.1
Codename:     rocamadour
Go version:   go1.17.7
Built:        2022-02-14T16:50:25Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

Host OS: Debian Bullseye
docker: 20.10.5+dfsg1-1+deb11u1
docker-compose: 1.25.0-1

docker-compose.yml:
```yaml
version: '2.1'

services:
  test-traefik:
    container_name: test-traefik
    hostname: test-traefik
    image: "traefik:latest"
    restart: "${RESTART}"  
    environment:
      - TZ=${TZ}
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_BASE}/traefik:/etc/traefik
      - /srv/letsencrypt/webssl:/certs
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  test-whoami:
    container_name: test-whoami
    hostname: test-whoami
    image: traefik/whoami:latest
    restart: "${RESTART}"
    environment:
      - TZ=${TZ}
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.service=test-whoami-test"

networks:
  default:
    name: test
    enable_ipv6: true
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
       - subnet: fd10:255:3::/64
       - subnet: 10.128.3.0/24
```

/etc/traefik/traefik.yml
```yaml
log:
  level: DEBUG

api:
  dashboard: true
  debug: true
  insecure: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
  traefik:
    address: :8080

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
  file:
    directory: /etc/traefik/dynamic
    watch: true
 ```

**Comment by joachimtingvold** [comment]
One alternative would be to use the hostname of the container (`test-whoami`), rather than the IPv6-address directly, but the container doesn't seem to prioritize IPv6 above IPv4 currently (which probably would have to be solved in Docker). Not sure if Traefik could prioritize IPv6 above IPv4 if both are present in a hostname/FQDN, or if that is left to some other part of the stack.

```
/ # hostname
test-traefik
/ # nslookup test-whoami
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
Name:	test-whoami
Address: fd10:255:3::2

Non-authoritative answer:
Name:	test-whoami
Address: 10.128.3.2


/ # curl -o- http://test-whoami
Hostname: test-whoami
IP: 127.0.0.1
IP: ::1
IP: 10.128.3.2
IP: fd10:255:3::2
IP: fe80::42:aff:fe80:302
RemoteAddr: 10.128.3.3:49310
GET / HTTP/1.1
Host: test-whoami
User-Agent: curl/7.79.1
Accept: */*

/ # curl -6 -o- http://test-whoami
Hostname: test-whoami
IP: 127.0.0.1
IP: ::1
IP: 10.128.3.2
IP: fd10:255:3::2
IP: fe80::42:aff:fe80:302
RemoteAddr: [fd10:255:3::3]:53314
GET / HTTP/1.1
Host: test-whoami
User-Agent: curl/7.79.1
Accept: */*

```

**Comment by joachimtingvold** [comment]
Adding manual dynamic config via `/etc/traefik/dynamic/test.yml`;

```yaml
http:
  services:
    whoami-host:
      loadBalancer:
        servers:
        - url: "http://whoami-test:80"
    whoami-ipv6:
      loadBalancer:
        servers:
        - url: "http://[fd10:255:3::2]:80"
  routers:
    whoami-host:
      entryPoints:
        - "websecure"
      rule: "Host(`whoami-host.foo.bar`)"
      service: "whoami-host"
      tls: true
    whoami-ipv6:
      entryPoints:
        - "websecure"
      rule: "Host(`whoami-ipv6.foo.bar`)"
      service: "whoami-ipv6"
      tls: true
```

Trying `https://whoami-host.foo.bar`, it seems like it cannot resolve (even if it works with nslookup on the same container);

```
test-traefik    | time="2022-02-20T02:12:49+01:00" level=debug msg="'502 Bad Gateway' caused by: dial tcp: lookup whoami-test on 127.0.0.11:53: no such host"
```

Trying `https://whoami-ipv6.foo.bar` works as expected:

```
jocke@keklolwtf: ~ $ curl -k -o- https://whoami-ipv6.foo.bar
Hostname: test-whoami
IP: 127.0.0.1
IP: ::1
IP: 10.128.3.2
IP: fd10:255:3::2
IP: fe80::42:aff:fe80:302
RemoteAddr: [fd10:255:3::3]:53318
GET / HTTP/1.1
Host: whoami-ipv6.foo.bar
User-Agent: curl/7.64.1
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 2001::x
X-Forwarded-Host: whoami-ipv6.foo.bar
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: test-traefik
X-Real-Ip: 2001::x
```
