### ISSUE TITLE
Docs suggest middleware config, but yield field not found, node: accesscontrolalloworigin

### ISSUE THREAD

**Issue by cdaringe** [traefik/traefik#8796]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

# Problem

The following error in logs is against expectation:

`time="2022-02-23T01:06:12Z" level=error msg="field not found, node: accesscontrolalloworigin" providerName=docker container=pca-gql-reverse-proxy-e5b0896c979b12b119c1cd2556e5315c0cd3682feda66da740d2f08f308ad4fd`

# Research

- the associated configuration is recorded directly in top-level traefik docs: https://doc.traefik.io/traefik/v2.0/middlewares/headers/#cors-headers
- the docker compose config applies the labels as the docs request

```yaml
  pca_gql:
    image: hasura/graphql-engine:v2.2.0
   # snip
    labels:
- traefik.http.routers.pca_gql.tls=true
      - traefik.http.routers.pca_gql.tls.certresolver=leacme
      - traefik.http.routers.pca_gql.rule=Host(`pca.cdaringe.com`)
      - traefik.http.middlewares.pca_gql_headers.headers.accesscontrolallowmethods=GET,OPTIONS
      - traefik.http.middlewares.pca_gql_headers.headers.accesscontrolalloworigin=https://cdaringe.static.observableusercontent.com
      - traefik.http.middlewares.pca_gql_headers.headers.accesscontrolmaxage=100
      - traefik.http.middlewares.pca_gql_headers.headers.addvaryheader=true
      - traefik.http.routers.pca_gql.middlewares=pca_gql_headers@docker
```

Above, I,

1. define a new middleware, `pca_gql_headers`
2. apply `.headers.accesscontrolalloworigin` value, just as recorded in the docs
3. install the middleware into the route

### What did you see instead?

`field not found`, albeit this is what is recorded in the docs.

There are some related remarks on `field not found`, but none with explicit callout of parity between docs and configuration.

I will try using the camel case conventions used in the alt config formats in the interim

### What version of Traefik are you using?

tag: `traefik:v2.6.1`, which yields:

```
Status: Downloaded newer image for traefik:v2.6.1
Version:      2.6.1
Codename:     rocamadour
Go version:   go1.17.7
Built:        2022-02-14T16:50:25Z
```

### What is your environment & configuration?

```yaml
global:
  checkNewVersion: false
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
  # added via cli
  # websecure:
  #   address: :443
providers:
  providersThrottleDuration: 2s
  docker:
    watch: true
    endpoint: unix:///var/run/docker.sock
    swarmModeRefreshSeconds: 15s
certificatesResolvers:
  leacme:
    acme:
      email: myemail@whatever.org
      storage: /acme.json
      dnsChallenge:
        delayBeforeCheck: 0
        provider: digitalocean

```

The other config is inlined above

### If applicable, please paste the log output in DEBUG level

n/a
