### ISSUE TITLE
auto add "/" to url when use traefik rewrite

### ISSUE THREAD

**Issue by wayne-beep** [traefik/traefik#8797]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I use the rewrite function of traefik  to redirect url to / . The traefik config :
```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    app.protocol: http
    customer/ingress-domain: http://example.com
    customer/rewrite-path: /
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: test-web
          servicePort: 8080
        path: /tech/TQATaskFrontend
status:
  loadBalancer: {}
```

### What did you see instead?

when I request the url by curl:
```
curl http://example/tech/TQATaskFrontend
```
the response thows:
```
{"timestamp":"2022-02-23 11:22:57","status":404,"error":"Not Found","message":"No message available","path":"/tech/TQA/TaskFrontend/"}
```
the path TQATaskFrontend is auto added a "/" between "A" and "T"

### What version of Traefik are you using?

v1.7

### What is your environment & configuration?

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    app.protocol: http
    customer/ingress-domain: http://example.com
    customer/rewrite-path: /
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: test-web
          servicePort: 8080
        path: /tech/TQATaskFrontend
status:
  loadBalancer: {}

```

Add more configuration information here.
