### ISSUE TITLE
Host headers do not get carried over when using Docker + File with loadbalancer service

### ISSUE THREAD

**Issue by AskoCloud** [traefik/traefik#8811]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I added a single loadbalancer service within a dynamic toml accessed via traefik on docker. To this service i added a IP whitelist middleware and added my external IP. It didnt let me access the site so i checked what IP traefik compares. passHostHeader should be enabled by default (according to the docs). But i also tried passHostHeader = true with no different outcome.

If i use the whoami container with docker labels (not declared within the toml file) i get the correct X-Forwarded-For header:

```
X-Forwarded-For: 31.16.***.***
X-Forwarded-Host: whoami.*****
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: c0182946c367
X-Real-Ip: 31.16.***.***
```

if the connection is routed via the single loadbalancer service within the toml file the headers do not seem to get carried over. These are the headers:

```
X-Forwarded-For: 172.18.0.1
X-Forwarded-Host: s39362.***.***.**
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: c0182946c367
X-Real-Ip: 172.18.0.1
```

### What did you see instead?

Internal IP as forwarded header. 

### What version of Traefik are you using?

```
Version:      2.6.1
Codename:     rocamadour
Go version:   go1.17.7
Built:        2022-02-14T16:50:25Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

/traefik_dynamic.toml
```yaml
[http.routers.int]
  rule = "Host(`s39362.***.***.**`)"
  entrypoints = ["websecure"]
  service = "int-service"
  
[http.services.int-service.loadBalancer]
  [[http.services.int-service.loadBalancer.servers]]
    url = "http://172.18.0.3/"

```

/docker-compose.yml
```yaml
version: '3'

services:

    traefik:
        container_name: traefik
        image: traefik:v2.6
        restart: always
        ports:
          - "80:80"
          - "443:443"
        networks:
            - proxy
        environment:
            - HETZNER_API_KEY=${API}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./certs/acme.json:/acme.json
            - ./config/:/etc/traefik/
    whoami:
      image: "traefik/whoami"
      container_name: "simple-service"
      networks:
        - proxy
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.***.**`)"
        - "traefik.http.routers.whoami.entrypoints=web"

networks:
  proxy:
    external: true
```

Add more configuration information here.
