### ISSUE TITLE
Cannot avoid  Annonymous Stats collection

### ISSUE THREAD

**Issue by GuyKh** [traefik/traefik#8812]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

In my `traefik.yaml` configuration file -- this is what I have:
```
global:
  checkNewVersion: true
  # Send anonymous usage data
  sendAnonymousUsage: false
```

Either I remove it, set it to `false` or whatever -- I cannot 

### What did you see instead?

On startup of Traefik, i see in the logs:
```
time="2022-03-03T09:43:23Z" level=info msg="Traefik version 2.6.1 built on 2022-02-14T16:50:25Z"
time="2022-03-03T09:43:23Z" level=info msg="Stats collection is enabled."
time="2022-03-03T09:43:23Z" level=info msg="Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration."
time="2022-03-03T09:43:23Z" level=info msg="Help us improve Traefik by leaving this feature on :)"
time="2022-03-03T09:43:23Z" level=info msg="More details on: https://doc.traefik.io/traefik/contributing/data-collection/"
time="2022-03-03T09:43:23Z" level=info msg="Starting provider aggregator.ProviderAggregator"
```

### What version of Traefik are you using?

2.6.1

### What is your environment & configuration?

```yaml
...
...
global:
  checkNewVersion: true
  # Send anonymous usage data
  sendAnonymousUsage: false
...
```

Docker-compose settings:
```
traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}
    security_opt:
      - no-new-privileges:true
    ports:
    - target: 80
      published: 80
      protocol: tcp
      mode: host
    - target: 443
      published: 443
      protocol: tcp
      mode: host
    - target: 8080
      published: 8080
      protocol: tcp
      mode: host
      mode: ingress
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
      - CLOUDFLARE_ZONE_API_TOKEN=${CLOUDFLARE_ZONE_API_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.default-compress.compress=true"
      - "traefik.http.middlewares.default-http.redirectScheme.scheme=https"
      - "traefik.http.middlewares.default-http.redirectScheme.permanent=true"
      - "traefik.http.middlewares.default-https.chain.middlewares=default-compress"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${DOMAINNAME}`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=${DOMAINNAME}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.${DOMAINNAME}"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.routers.traefik-secure.middlewares=chain-oauth@file"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/docker/traefik:/etc/traefik
      - ${HOME}/docker/traefik/traefik.yaml:/traefik.yaml
      - ${HOME}/docker/traefik/logs:/logs
```

### If applicable, please paste the log output in DEBUG level

I of course found this piece of code: 
https://github.com/traefik/traefik/blob/master/cmd/traefik/traefik.go#L557
Which, by all means, is written as it should, but it still doesn't work for me

**Comment by ldez** [comment]
Hello,

`sendAnonymousUsage` is disabled by default.

```
time="2022-03-03T09:55:55Z" level=info msg="Configuration loaded from flags."
time="2022-03-03T09:55:55Z" level=info msg="Traefik version 2.6.1 built on 2022-02-14T16:50:25Z"
time="2022-03-03T09:55:55Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"web-secure\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"exposedByDefault\":true,\"swarmModeRefreshSeconds\":\"15s\"},\"file\":{\"watch\":true,\"filename\":\"/config-tls.yml\"}},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"pilot\":{\"dashboard\":true}}"
time="2022-03-03T09:55:55Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
```

You can check the state of the options using the DEBUG log level and checking the line `Static configuration loaded`.

Maybe you have a kind of cache issue, I recommend doing a `docker-compose down` to clean some elements.

**Comment by GuyKh** [comment]
@ldez 
Did that --
Got:
```
    "global": {
        "checkNewVersion": true,
        "sendAnonymousUsage": true
    },
```

**Comment by ldez** [comment]
`sendAnonymousUsage: true` implies that you defined this option.
Can you check the configuration inside the Traefik container?

**Comment by GuyKh** [comment]
```
❯ cat ${HOME}/docker/traefik/traefik.yaml | grep sendAnonymousUsage -B2 -A2
global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:




❯ docker exec -it traefik sh
/ # cat /traefik.yaml | grep sendAnonymousUsage -B2 -A2
global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:
```
