### ISSUE TITLE
can not list endpoint

### ISSUE THREAD

**Issue by yylt** [traefik/traefik#8818]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

1 create ingress & service & endpoint

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vscode
spec:
  ingressClassName: traefik
  rules:
  - host: code.local
    http:
      paths:
      - backend:
          service:
            name: vscode
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: vscode
spec:
  ports:
  - name: https
    port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vscode
subsets:
- addresses:
  - ip: 172.19.52.40
  ports:
  - port: 8080
    protocol: TCP

```

2 log traefik-779b68465d-gcskbv

```
$ kubectl logs -n ingress traefik-779b68465d-gcskb 
time="2022-03-01T09:40:58Z" level=info msg="Configuration loaded from flags."
time="2022-03-01T09:48:49Z" level=error msg="Skipping service: no endpoints found" providerName=kubernetes ingress=vscode serviceName=vscode servicePort="&ServiceBackendPort{Name:,Number:80,}" namespace=default
```

### What did you see instead?

1 can not open https://code.local/

expect open `https://code.local/` success

### What version of Traefik are you using?

2.6.1 

image: docker.io/library/traefik:2.6.1

### What is your environment & configuration?

```yaml
traefik traefik --global.checknewversion --global.sendanonymoususage --entrypoints.metrics.address=:9100/tcp --entrypoints.traefik.address=:9000/tcp --entrypoints.web.address=:8000/tcp --entrypoints.websecure.address=:8443/tcp --api.dashboard=true --ping=true --metrics.prometheus=true --providers.kubernetescrd.allowCrossNamespace=true --providers.kubernetescrd.allowexternalnameservices=true --metrics.prometheus.entrypoint=metrics --providers.kubernetescrd --providers.kubernetesingress
```

none

### If applicable, please paste the log output in DEBUG level

none
