### ISSUE TITLE
Traefik not using my certificats

### ISSUE THREAD

**Issue by MGMehdi** [traefik/traefik#8822]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I had to format my raspberry and know traefik doesn't use my certificates. My config worked before

docker-compose
```yml
services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik.toml:/etc/traefik/traefik.toml:ro"
      - "./config/dyn.toml:/etc/traefik/dyn.toml:ro"
      - "/etc/letsencrypt/live/[mydomain]/fullchain.pem:/certs/fullchain.pem:ro"
      - "/etc/letsencrypt/live/[mydomain]/privkey.pem:/certs/privkey.pem:ro"
      
networks:
  default:
    external: true
    name: web
```

traefik.toml
```toml
[global]
  sendAnonymousUsage = false

[log]
  level = "INFO"
  format = "common"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = false
    swarmMode = false

  [providers.file]
    filename = "/etc/traefik/dyn.toml"

[api]
  dashboard = true
  debug = false
  insecure = true

[entryPoints]
  [entryPoints.insecure]
    address = ":80"

    [entryPoints.insecure.http]
    [entryPoints.insecure.http.redirections]
      [entryPoints.insecure.http.redirections.entryPoint]
        to = "secure"
        scheme = "https"

  [entryPoints.secure]
    address = ":443" 
```
dyn.toml
```toml
[[tls.certificates]]
  certFile = "/certs/fullchain.pem"
  keyFile = "/certs/privkey.pem"
```

### What did you see instead?

![image](https://user-images.githubusercontent.com/48625769/156903997-abb2c940-1145-49b7-9e5e-34f85924375c.png)

### What version of Traefik are you using?

Version:      2.6.1
Codename:     rocamadour
Go version:   go1.17.7
Built:        2022-02-14T16:50:25Z
OS/Arch:      linux/arm64

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by MGMehdi** [comment]
Found a solution by modify my dyn.toml
```toml
[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/certs/fullchain.pem"
      keyFile = "/certs/privkey.pem"
```
