### ISSUE TITLE
SNI not correctly set for https backend

### ISSUE THREAD

**Issue by everflux** [traefik/traefik#8824]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

A wildcard router like

```
   router-devos:
      entryPoints:
      - https
      rule: "HostRegexp(`{subdomain:[a-z0-9-]+}.appsdemo.dev`)"
      tls:
        options: default
        certResolver: acme-dns
        domains:
        - main: "*.appsdemo.dev"
      service: service-devos
```

with a service like
```
    service-devos:
      loadBalancer:
        servers:
        - url: "https://10.23.211.105"
        passHostHeader: true
        serversTransport: httpsInsecure
```

The backend is not receiving SNI host matching the request from the router.
Even when setting passHostHeader the SNI value is not set correctly.

### What did you see instead?

The IP is used as SNI.
I noticed that I can override the hostname in the serversTransport, but only to a fixed value.

### What version of Traefik are you using?

2.6

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.
