### ISSUE TITLE
Allow setting SNI dynamically https backend

### ISSUE THREAD

**Issue by everflux** [traefik/traefik#8828]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

I have a backend that uses SNI for routing itself (like traefik behind traefik).

A configured router like

```
   router-devos:
      entryPoints:
      - https
      rule: "HostRegexp(`{subdomain:[a-z0-9-]+}.appsdemo.dev`)"
      tls:
        options: default
        certResolver: acme-dns
        domains:
        - main: "*.appsdemo.dev"
      service: service-devos
```

with a service like
```
    service-devos:
      loadBalancer:
        servers:
        - url: "https://10.23.211.105"
        passHostHeader: true
        serversTransport: httpsInsecure
```

should allow setting the host header dynamically, for example matching the request (like passHostHeader for HTTP).
