### ISSUE TITLE
Unable to renew wildcard certificate using Google Cloud DNS (REFUSED ACME challenge)

### ISSUE THREAD

**Issue by guarnacciaa** [traefik/traefik#8831]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I have the latest Traefik version running in a Docker container. This setup has been running for a few months with no issue, but now I'm not able to renew the certificates.

### What did you see instead?

It seems Traefik is waiting for the DNS propagation to validate the TXT records even if the records are already propagated.
I tested this setup using Google (8.8.8.8) and Cloudflare (1.1.1.1) DNS servers and while Traefik is Waiting for "DNS record propagation", I can already resolve the newly created TXT records from the same host:

```
root@Docker:~/traefik#` dig TXT _acme-challenge.mydomain.com @1.1.1.1

; <<>> DiG 9.16.22-Debian <<>> TXT _acme-challenge.mydomain.com @1.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31027
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;_acme-challenge.mydomain.com.       IN      TXT

;; ANSWER SECTION:
_acme-challenge.mydomain.com. 10     IN      TXT     "PznOpiZ1scTH_Wwvdj4-VtK9BfHPBoxaTeZqSpkh8HE"
_acme-challenge.mydomain.com. 10     IN      TXT     "IIWcqRsvmtGWuSRCvEzFKkFh_4PzJWKeDC-Ov5-a_U8"

;; Query time: 0 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Thu Mar 10 11:47:02 UTC 2022
;; MSG SIZE  rcvd: 164

root@Docker:~/traefik# dig TXT _acme-challenge.mydomain.com @8.8.8.8

; <<>> DiG 9.16.22-Debian <<>> TXT _acme-challenge.mydomain.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61750
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;_acme-challenge.mydomain.com.       IN      TXT

;; ANSWER SECTION:
_acme-challenge.mydomain.com. 116    IN      TXT     "IIWcqRsvmtGWuSRCvEzFKkFh_4PzJWKeDC-Ov5-a_U8"
_acme-challenge.mydomain.com. 116    IN      TXT     "PznOpiZ1scTH_Wwvdj4-VtK9BfHPBoxaTeZqSpkh8HE"

;; Query time: 0 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Mar 10 11:47:06 UTC 2022
;; MSG SIZE  rcvd: 164
``` 

### What version of Traefik are you using?

Version:      2.6.1
Codename:     rocamadour
Go version:   go1.17.7
Built:        2022-02-14T16:50:25Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

docker-compose.yml
```yaml
version: "3.8"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    #security_opt: null
    #- no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 512M
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      #- GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp_service_account
      - GCE_SERVICE_ACCOUNT_FILE=/run/secrets/gcp_service_account
      - GCE_PROJECT=lan-ooo
      - GCE_DEBUG=true
      #- GCE_SERVICE_ACCOUNT=traefik@mydomain-com.iam.gserviceaccount.com
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./log:/var/log/
      - ./conf:/conf

    secrets:
      - gcp_service_account
      - usersfile
    logging:
      driver: "json-file"

secrets:
  gcp_service_account:
    file: "secrets/mydomain-com-c1ad2db788c3.json"
  usersfile:
    file: "secrets/usersfile"

networks:
  proxy:
    external: true
```

traefik.yml

```yaml
entryPoints:
  web:
    address: ":80"
  secureweb:
    address: ":443"
  traefik:
    address: ":8080"

providers:
  file:
    directory: "/conf"
    watch: true

  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"

log:
  level: DEBUG
  #level: WARNING
  filepath: "/var/log/traefik/traefik.log"

api:
  dashboard: true
  insecure: true
  debug: true

serversTransport:
  insecureSkipVerify: true

certificatesResolvers:
  "googleresolver":
    acme:
      email: ************@gmail.com
      storage: /acme.json
      dnsChallenge:
        #delayBeforeCheck: 60
        provider: gcloud
        resolvers:
          #- "ns-cloud-b1.googledomains.com:53"
          #- "ns-cloud-b2.googledomains.com:53"
          #- "ns-cloud-b3.googledomains.com:53"
          #- "ns-cloud-b4.googledomains.com:53"
          - "1.1.1.1:53"
          - "8.8.8.8:53"
```

dynamic_conf.yml
```yaml
http:
  routers:
    http-catchall:
      entryPoints:
        - "web"
      rule: "HostRegexp(`{host:.+}`)"
      middlewares:
        - "redirect-to-https"
      service: api@internal

    traefik:
      entryPoints:
        - "secureweb"
      rule: "Host(`traefik.mydomain.com`)"
      service: api@internal
      tls:
        certResolver: "googleresolver"
        domains:
          - main: "mydomain.com"
            sans:
              - "*.mydomain.com"

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
```

### If applicable, please paste the log output in DEBUG level

```
time="2022-03-10T11:42:56Z" level=debug msg="Looking for provided certificate(s) to validate [\"mydomain.com\" \"*.mydomain.com\"]..." ACME CA="https://acme-v02.api.letsencrypt.org/directory" providerName=googleresolver.acme
time="2022-03-10T11:42:56Z" level=debug msg="No ACME certificate generation required for domains [\"mydomain.com\" \"*.mydomain.com\"]." providerName=googleresolver.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"
time="2022-03-10T11:43:02Z" level=debug msg="Building ACME client..." providerName=googleresolver.acme
time="2022-03-10T11:43:02Z" level=debug msg="https://acme-v02.api.letsencrypt.org/directory" providerName=googleresolver.acme
time="2022-03-10T11:43:02Z" level=info msg=Register... providerName=googleresolver.acme
time="2022-03-10T11:43:02Z" level=debug msg="legolog: [INFO] acme: Registering account for **********@gmail.com"
time="2022-03-10T11:43:03Z" level=debug msg="Using DNS Challenge provider: gcloud" providerName=googleresolver.acme
time="2022-03-10T11:43:03Z" level=debug msg="legolog: [INFO] [mydomain.com, *.mydomain.com] acme: Obtaining bundled SAN certificate"
time="2022-03-10T11:43:04Z" level=debug msg="legolog: [INFO] [*.mydomain.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/862079*****"
time="2022-03-10T11:43:04Z" level=debug msg="legolog: [INFO] [mydomain.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/862079*****"
time="2022-03-10T11:43:04Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: use dns-01 solver"
time="2022-03-10T11:43:04Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Could not find solver for: tls-alpn-01"
time="2022-03-10T11:43:04Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Could not find solver for: http-01"
time="2022-03-10T11:43:04Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: use dns-01 solver"
time="2022-03-10T11:43:04Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Preparing to solve DNS-01"
time="2022-03-10T11:43:05Z" level=debug msg="legolog: change (Create): {\"additions\":[{\"name\":\"_acme-challenge.mydomain.com.\",\"rrdatas\":[\"IIWcqRsvmtGWuSRCvEzFKkFh_4PzJWKeDC-Ov5-a_U8\"],\"ttl\":120,\"type\":\"TXT\"}]}"
time="2022-03-10T11:43:06Z" level=debug msg="legolog: [INFO] Wait for apply change [timeout: 30s, interval: 3s]"
time="2022-03-10T11:43:06Z" level=debug msg="legolog: change (Get): {\"additions\":[{\"name\":\"_acme-challenge.mydomain.com.\",\"rrdatas\":[\"IIWcqRsvmtGWuSRCvEzFKkFh_4PzJWKeDC-Ov5-a_U8\"],\"ttl\":120,\"type\":\"TXT\"}]}"
time="2022-03-10T11:43:09Z" level=debug msg="legolog: change (Get): {\"additions\":[{\"name\":\"_acme-challenge.mydomain.com.\",\"rrdatas\":[\"IIWcqRsvmtGWuSRCvEzFKkFh_4PzJWKeDC-Ov5-a_U8\"],\"ttl\":120,\"type\":\"TXT\"}]}"
time="2022-03-10T11:43:09Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Preparing to solve DNS-01"
time="2022-03-10T11:43:11Z" level=debug msg="legolog: change (Create): {\"deletions\":[{\"kind\":\"dns#resourceRecordSet\",\"name\":\"_acme-challenge.mydomain.com.\",\"rrdatas\":[\"IIWcqRsvmtGWuSRCvEzFKkFh_4PzJWKeDC-Ov5-a_U8\"],\"ttl\":120,\"type\":\"TXT\"}]}"
time="2022-03-10T11:43:11Z" level=debug msg="legolog: [INFO] Wait for apply change [timeout: 30s, interval: 3s]"
time="2022-03-10T11:43:11Z" level=debug msg="legolog: change (Get): {\"deletions\":[{\"kind\":\"dns#resourceRecordSet\",\"name\":\"_acme-challenge.mydomain.com.\",\"rrdatas\":[\"IIWcqRsvmtGWuSRCvEzFKkFh_4PzJWKeDC-Ov5-a_U8\"],\"ttl\":120,\"type\":\"TXT\"}]}"
time="2022-03-10T11:43:12Z" level=debug msg="legolog: change (Create): {\"additions\":[{\"name\":\"_acme-challenge.mydomain.com.\",\"rrdatas\":[\"PznOpiZ1scTH_Wwvdj4-VtK9BfHPBoxaTeZqSpkh8HE\",\"IIWcqRsvmtGWuSRCvEzFKkFh_4PzJWKeDC-Ov5-a_U8\"],\"ttl\":120,\"type\":\"TXT\"}]}"
time="2022-03-10T11:43:13Z" level=debug msg="legolog: [INFO] Wait for apply change [timeout: 30s, interval: 3s]"
time="2022-03-10T11:43:13Z" level=debug msg="legolog: change (Get): {\"additions\":[{\"name\":\"_acme-challenge.mydomain.com.\",\"rrdatas\":[\"PznOpiZ1scTH_Wwvdj4-VtK9BfHPBoxaTeZqSpkh8HE\",\"IIWcqRsvmtGWuSRCvEzFKkFh_4PzJWKeDC-Ov5-a_U8\"],\"ttl\":120,\"type\":\"TXT\"}]}"
time="2022-03-10T11:43:16Z" level=debug msg="legolog: change (Get): {\"additions\":[{\"name\":\"_acme-challenge.mydomain.com.\",\"rrdatas\":[\"PznOpiZ1scTH_Wwvdj4-VtK9BfHPBoxaTeZqSpkh8HE\",\"IIWcqRsvmtGWuSRCvEzFKkFh_4PzJWKeDC-Ov5-a_U8\"],\"ttl\":120,\"type\":\"TXT\"}]}"
time="2022-03-10T11:43:17Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Trying to solve DNS-01"
time="2022-03-10T11:43:17Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Checking DNS record propagation using [1.1.1.1:53 8.8.8.8:53]"
time="2022-03-10T11:43:22Z" level=debug msg="legolog: [INFO] Wait for propagation [timeout: 3m0s, interval: 5s]"
time="2022-03-10T11:43:22Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:43:27Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:43:32Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:43:37Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:43:42Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:43:47Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:43:52Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:43:57Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:44:02Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:44:07Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:44:12Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:44:17Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:44:22Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:44:27Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:44:32Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:44:37Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:44:42Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:44:47Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:44:52Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:44:57Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:45:02Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:45:07Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:45:12Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:45:17Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:45:22Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:45:27Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:45:32Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:45:37Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:45:42Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:45:47Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:45:52Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:45:57Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:46:02Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:46:07Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:46:12Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:46:17Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:46:22Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Trying to solve DNS-01"
time="2022-03-10T11:46:22Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Checking DNS record propagation using [1.1.1.1:53 8.8.8.8:53]"
time="2022-03-10T11:46:27Z" level=debug msg="legolog: [INFO] Wait for propagation [timeout: 3m0s, interval: 5s]"
time="2022-03-10T11:46:27Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:46:32Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:46:37Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:46:42Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:46:47Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:46:52Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:46:57Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:47:02Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:47:07Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:47:12Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:47:17Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:47:22Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:47:27Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:47:32Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:47:37Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:47:42Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:47:47Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:47:52Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:47:57Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:48:02Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:48:07Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:48:12Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:48:17Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:48:23Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:48:28Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:48:33Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:48:38Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:48:43Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:48:48Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:48:53Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:48:58Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:49:03Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:49:08Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:49:13Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:49:18Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:49:23Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Waiting for DNS record propagation."
time="2022-03-10T11:49:28Z" level=debug msg="legolog: [INFO] [*.mydomain.com] acme: Cleaning DNS-01 challenge"
time="2022-03-10T11:49:29Z" level=debug msg="legolog: [INFO] [mydomain.com] acme: Cleaning DNS-01 challenge"
time="2022-03-10T11:49:30Z" level=debug msg="legolog: [INFO] retry due to: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/authz-v3/86207900510 :: urn:ietf:params:acme:error:badNonce :: JWS has an invalid anti-replay nonce: \"0002UkOz4IZsZC3w8qZJ7AmLxbPM8udncTkV-HoziG4oE6c\""
time="2022-03-10T11:49:31Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/862079*****"
time="2022-03-10T11:49:31Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/862079*****"
time="2022-03-10T11:49:31Z" level=error msg="Unable to obtain ACME certificate for domains \"mydomain.com,*.mydomain.com\" : unable to generate a certificate for the domains [mydomain.com *.mydomain.com]: error: one or more domains had a problem:\n[*.mydomain.com] time limit exceeded: last error: NS ns-cloud-b4.googledomains.com. returned REFUSED for _acme-challenge.mydomain.com.\n[mydomain.com] time limit exceeded: last error: NS ns-cloud-b4.googledomains.com. returned REFUSED for _acme-challenge.mydomain.com.\n" providerName=googleresolver.acme
```
