### ISSUE TITLE
Traefik decodes the response from the proxy

### ISSUE THREAD

**Issue by erickskrauch** [traefik/traefik#8842]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I want to use Traefik as a frontend load balancer. There are several Nginx servers behind Traefik. Since Traefik [doesn't support brotli](https://github.com/traefik/traefik/issues/4202), I decided not to do the content encoding on the Traefik side and do it on the Nginx side. Unfortunately, Traefik decodes the content anyway, which [violates the documentation](https://doc.traefik.io/traefik/middlewares/http/compress/#configuration-examples).

### What did you see instead?

I see that the content is decoded anyway.

I made sure that the `Accept-Encoding` header reaches Nginx and that it encodes the response correctly. When I add a `compress` middleware, the response is always `gzip` encoded. According to [the documentation](https://doc.traefik.io/traefik/middlewares/http/compress/#configuration-examples) if the response already has a `Content-Encoding` header it will not be recompressed. After my checks, I see that the content is decompressed anyway and gets compressed if it is enabled in the settings.

### What version of Traefik are you using?

```
Version:      2.6.1
Codename:     rocamadour
Go version:   go1.17.7
Built:        2022-02-14T16:50:25Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
# Static
log:
  level: INFO

accessLog: {}

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  file:
    filename: "/etc/traefik/services.yml"
    watch: true

certificatesResolvers:
  le:
    acme:
      storage: /etc/traefik/acme.json
      email: email@my.com
      httpChallenge:
        entryPoint: http
```

```yaml
# Dynamic
http:
  routers:
    http-to-https:
      rule: "HostRegexp(`{host:.+}`)"
      entrypoints:
        - http
      middlewares:
        - redirect-to-https
      service: noop@internal

    backend-api-https:
      rule: "Host(`domain.com`) && PathPrefix(`/api`)"
      entrypoints:
        - https
      service: api
      middlewares:
        - compress
      tls:
        certResolver: le
        domains:
          - main: domain.com

    api:
      loadBalancer:
        servers:
          - url: http://10.132.0.4:82/
          - url: http://10.132.0.8:80/

  middlewares:
    compress:
      compress: true

    redirect-to-https:
      redirectscheme:
        scheme: https
        permanent: true

```

### If applicable, please paste the log output in DEBUG level

```
time="2022-03-15T23:33:19Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"br\"],\"User-Agent\":[\"curl/7.81.0\"],\"X-Forwarded-Host\":[\"domain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"domain.com\"],\"X-Real-Ip\":[\"1.2.3.4\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"domain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"1.2.3.4:33476\",\"RequestURI\":\"/api\",\"TLS\":null}"
time="2022-03-15T23:33:19Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"br\"],\"User-Agent\":[\"curl/7.81.0\"],\"X-Forwarded-Host\":[\"domain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"domain.com\"],\"X-Real-Ip\":[\"1.2.3.4\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"domain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"1.2.3.4:33476\",\"RequestURI\":\"/api\",\"TLS\":null}" ForwardURL="http://10.132.0.4:82/"
time="2022-03-15T23:33:19Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/api\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"br\"],\"User-Agent\":[\"curl/7.81.0\"],\"X-Forwarded-Host\":[\"domain.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"domain.com\"],\"X-Real-Ip\":[\"1.2.3.4\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"domain.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"1.2.3.4:33476\",\"RequestURI\":\"/api\",\"TLS\":null}"
1.2.3.4 - - [15/Mar/2022:23:33:19 +0000] "GET /api HTTP/2.0" 404 163 "-" "-" 2 "api-https@file" "http://10.132.0.4:82/" 13ms
```
