### ISSUE TITLE
Connection timeout when trying to access from outside local network 

### ISSUE THREAD

**Issue by ahmedelakkad** [traefik/traefik#8843]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I can ping the server and an nslookup resolves to the server IP correctly but whenever I try to connect from outside my network (over another wifi or 4G) the url just gives a timeout. I checked the propagation and it is fine, I have domain and CNAME records on cloudflare for the subdomains and the ports are forwarded on the router. I cant find what's wrong with it. All working fine locally. The ports are allowing the connection as the certs are generated without any problems

### What did you see instead?

Timeout

### What version of Traefik are you using?

2.6.1

### What is your environment & configuration?

```yaml
http:
 #region routers 
  routers:
    pihole:
      entryPoints:
        - "https"
      rule: "Host(`***.***.******.xyz`)"
      middlewares:
        - default-headers
        - addprefix-pihole
        - https-redirectscheme
      tls: {}
      service: pihole
      
    pstore:
      entryPoints:
        - "https"
      rule: "Host(`***.***.******.xyz`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: pstore


  services:
    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.1.20:8070"
        passHostHeader: true
        
    pstore:
      loadBalancer:
        servers:
          - url: "http://192.168.1.20:8081"
        passHostHeader: true    


  middlewares:
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://***.***.******.xyz"



    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https


    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        #- default-whitelist
        - default-headers
```

Add more configuration information here.
