### ISSUE TITLE
Traefik doesn't differentiate between IngressClasses

### ISSUE THREAD

**Issue by christianvw** [traefik/traefik#8856]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I have still the same problem as described in issue https://github.com/traefik/traefik/issues/7896. The PR https://github.com/traefik/traefik/pull/7915 claimed to have solved it.

I have two traefik instances on the same kubernetes cluster in different namespaces, one for the external domain (`*.example.com`) and one for the internal domain (`*.home`). 

**THE PROBLEM is that any Ingress automatically goes to any Traefik instance, regardless of whether you specify an IngressClass on the Ingress object.**

Both instances were installed via the [Helm Chart](https://artifacthub.io/packages/helm/traefik/traefik) as follows:

````
helm upgrade --install traefik-public traefik/traefik --values=traefik-values-public.yaml --namespace=traefik-public
helm upgrade --install traefik-internal traefik/traefik --values=traefik-values-internal.yaml --namespace=traefik-internal
````

<details>
  <summary>Helm values for traefik-public</summary>
  
  **traefik-values-public.yaml**
  
  ````yaml
  ports:
    web:
      port: 9080
      exposedPort: 9080
      protocol: TCP
      expose: true
    websecure:
      port: 9443
      exposedPort: 9443
      protocol: TCP
      expose: true
      tls:
        enabled: true
    traefik:
      port: 9000
      exposedPort: 9000
      protocol: TCP
      expose: true
      hostIP: 192.168.2.4
    udp:
      port: 9999
      exposedPort: 9999
      protocol: UDP
      expose: true
  
  ingressRoute:
    dashboard:
      enabled: true
  
  ingressClass:
    enabled: true
    isDefaultClass: false
  
  volumes:
    - name: cert-wildcard-example-com
      mountPath: "/certs"
      type: secret
    - name: config-traefik-public-dynamic
      mountPath: "/config"
      type: configMap
  
  additionalArguments:
    - "--providers.file.filename=/config/dynamic.yaml"
  ````
  
</details>

<details>
  <summary>Helm values for traefik-internal</summary>
  
  **traefik-values-internal.yaml**
  
  ````yaml
  ports:
    web:
      port: 80
      exposedPort: 80
      protocol: TCP
      expose: true
    websecure:
      port: 443
      exposedPort: 443
      protocol: TCP
      expose: true
      tls:
        enabled: true
    traefik:
      port: 9001
      exposedPort: 9001
      protocol: TCP
      expose: true
      hostIP: 192.168.2.4
  
  ingressRoute:
    dashboard:
      enabled: true
  
  ingressClass:
    enabled: true
    isDefaultClass: false
  
  volumes:
    - name: cert-wildcard-home
      mountPath: "/certs"
      type: secret
    - name: config-traefik-internal-dynamic
      mountPath: "/config"
      type: configMap
  
  additionalArguments:
    - "--providers.file.filename=/config/dynamic.yaml"
  ````
  
</details>

As defined in the helm chart, two IngressClasses get created with the traefik fullname:

````
root@kubernetes[~]# k get ingressclass
NAME               CONTROLLER                      PARAMETERS   AGE
traefik-public     traefik.io/ingress-controller   <none>       15h
traefik-internal   traefik.io/ingress-controller   <none>       3h52m
````

Now, I create two Ingresses as follows:

````yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-test-public
  namespace: nginx-test-public
  annotations:
#    kubernetes.io/ingress.class: traefik-public #if i set this, this doesn't work at all
spec:
  ingressClassName: traefik-public
  rules:
  - host: nginx-test-public.example.com
  # ...
````

````yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-test-internal
  namespace: nginx-test-internal
  annotations:
#    kubernetes.io/ingress.class: traefik-internal #if i set this, this doesn't work at all
spec:
  ingressClassName: traefik-internal
  rules:
  - host: nginx-test-internal.home
  # ...
````

I expected these two ingresses to map to the respective IngressClass and thus to the respective Traefik instance.

### What did you see instead?

However, both ingresses went to both Traefik instances. So the assignment of the IngressClass to the Ingress was completely ineffective.

On both traefik dashboards, both rules appear:

![image](https://user-images.githubusercontent.com/50269941/159165707-9094c0af-4d33-4df2-8027-0190707c89dd.png)

### What version of Traefik are you using?

Traefik v2.6.1 via [Helm](https://artifacthub.io/packages/helm/traefik/traefik) on Kubernetes 1.21.0 k3s

### What is your environment & configuration?

Described above.
