### ISSUE TITLE
Traefik WITHOUT IngressRoute or Middleware

### ISSUE THREAD

**Issue by wind57** [traefik/traefik#8860]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I have a very simple use-case. I want my requests to `reactive-discovery-it/services` to end-up calling `/services`. This should be fairly trivial, no? I am using `rancher/k3s:v1.21.10-k3s1` that already comes with traefik pre-installed.

I thought that a simple ingress definition as : 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: it-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/request-modifier: "ReplacePathRegex: ^/reactive-discovery-it/(.*) /$1"
spec:
  rules:
    - http:
        paths:
          - path: /reactive-discovery-it
            pathType: ImplementationSpecific
            backend:
              service:
                name: spring-cloud-kubernetes-client-reactive-discovery-it
                port:
                  number: 8080
```

would be enough, but it simply does not work.

### What did you see instead?

I would expect that requests to : `/reactive-discovery-it/services` would end up in `/services`, but that does not happen.

### What version of Traefik are you using?

2.6.1

### What is your environment & configuration?

this is already installed as part of `rancher/k3s:v1.21.10-k3s1`.
