### ISSUE TITLE
Kube api gateway problem: TCPRoute with a TLS listener in terminate mode not working if there exists an ingress resource

### ISSUE THREAD

**Issue by alisoam** [traefik/traefik#8861]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I am deploying traefik with the Kubernetes gateway provider. I have added a couple of ingress resources. Then, I applied a gateway resource with a tls listener in "terminate" mode, and a TCPRoute resource for this gateway.

I use openssl s_client to connect to the tcp service (service is whoamitcp):
``` sh
openssl s_client -connect mqtt.<example.org>:443 -servername mqtt.<example.org>
```

### What did you see instead?

When I run the open openssl s_client, I get the following response:
```
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad Requestclosed
```
If I remove all ingress resources, everything works fine and openssl s_client connects to the whoamitcp service.

* When I see the TCP routers in the traefik dashboard, there is a TCP router with the rule HostSNI("*"). I think the rule should be HostSNI("mqtt.example.org") (from listeners.hostname in the gateway resource)

### What version of Traefik are you using?

Version:      2.6.1
Codename:     rocamadour
Go version:   go1.17.7
Built:        2022-02-14T16:50:25Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

gateway.yaml
``` yaml
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: mqtt
  namespace: mqtt
spec:
  gatewayClassName: traefik
  listeners:
    - name: mqtt-tls
      protocol: TLS
      port: 8443
      hostname: mqtt.<example.org>
      tls:
        mode: "Terminate"
        certificateRefs:
          - group: ""
            kind: Secret
            name: mqtt-gateway-tls
      allowedRoutes:
        kinds:
          - kind: TCPRoute
            group: gateway.networking.k8s.io
        namespaces:
          from: Same
```
---
tcp-route.yaml
``` yaml
kind: TCPRoute
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: mqtt
  namespace: mqtt
spec:
  parentRefs:
    - name: mqtt
      sectionName: mqtt-tls
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - backendRefs:
      - name: whoamitcp
        port: 8080
        weight: 12
        kind: Service
        group: ""
```

### If applicable, please paste the log output in DEBUG level

```
time="2022-03-21T21:39:58Z" level=debug msg="No default certificate, generating one" tlsStoreName=default
time="2022-03-21T21:39:58Z" level=debug msg="Configuration received from provider kubernetesgateway: {\"http\":{},\"tcp\":{\"routers\":{\"mqtt-mqtt-mqtt-websecure-e3b0c44298fc1c149afb\":{\"entryPoints\":[\"websecure\"],\"service\":\"mqtt-mqtt-mqtt-websecure-e3b0c44298fc1c149afb-wrr-0\",\"rule\":\"HostSNI(`*`)\",\"tls\":{\"passthrough\":false}}},\"services\":{\"mqtt-mqtt-mqtt-websecure-e3b0c44298fc1c149afb-wrr-0\":{\"weighted\":{\"services\":[{\"name\":\"mqtt-whoamitcp-8080\",\"weight\":12}]}},\"mqtt-whoamitcp-8080\":{\"loadBalancer\":{\"servers\":[{\"address\":\"10.118.0.141:8080\"}]}}}},\"udp\":{},\"tls\":{}}" providerName=kubernetesgateway
time="2022-03-21T21:39:58Z" level=debug msg="No HTTPRoutes found in namespace \"traefik\""
time="2022-03-21T21:39:58Z" level=debug msg="No HTTPRoutes found" gateway=traefik-gateway namespace=traefik providerName=kubernetesgateway
time="2022-03-21T21:39:58Z" level=debug msg="Skipping Kubernetes event kind *v1alpha2.Gateway" providerName=kubernetesgateway
```
