### ISSUE TITLE
2.6.2 "servers transport not found" error

### ISSUE THREAD

**Issue by NReilingh** [traefik/traefik#8884]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I upgraded Traefik from 2.6.1 to 2.6.2 in a working environment, without making any other configuration changes.

### What did you see instead?

After upgrading, one of my services is now in an error state, reporting "servers transport not found confluence@docker" in the dashboard interface.

Restarting the Traefik service did not result in different behavior.

I will begin trying to isolate or workaround the issue after submitting this ticket since at face value this appears to be some kind of regression between 2.6.1 and 2.6.2.

### What version of Traefik are you using?

```
Version:      2.6.2
Codename:     rocamadour
Go version:   go1.17.8
Built:        2022-03-24T19:09:46Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
    labels:
      traefik.enable: "true"
      traefik.http.routers.confluence.rule: Host(`${DOMAIN_NAME}`)
      traefik.http.routers.confluence.service: confluence
      traefik.http.services.confluence.loadBalancer.server.port: 8090
      traefik.http.services.confluence.loadBalancer.serversTransport: confluence
      traefik.http.serversTransports.confluence.forwardingTimeouts.dialTimeout: 0
      traefik.http.routers.confluence.entrypoints: webtls
      traefik.http.routers.confluence_balsamiq-rtc.rule: Host(`${DOMAIN_NAME}`) && PathPrefix(`/balsamiq.io`)
      traefik.http.routers.confluence_balsamiq-rtc.service: confluence_balsamiq-rtc
      traefik.http.services.confluence_balsamiq-rtc.loadbalancer.server.port: 9083
      traefik.http.routers.confluence_balsamiq-rtc.entrypoints: webtls
```

### If applicable, please paste the log output in DEBUG level

time="2022-03-25T13:54:02Z" level=error msg="servers transport not found confluence@docker" entryPointName=webtls routerName=confluence@docker

**Comment by NReilingh** [comment]
commenting the `traefik.http.services.confluence.loadBalancer.serversTransport: confluence` line causes the error to be avoided.

I will test a bit later what happens when I rename the serversTransport to not "conflict" with the router and service name.

**Comment by tomMoulard** [comment]
Hello @NReilingh,

Thanks for your interest in Traefik!

There is currently no way to define a `serversTransport` using a docker label.

I would suggest using this as a file provider configuration:
```yaml
http:
  serversTransports:
    confluence-st:
      forwardingTimeouts:
        dialTimeout: 0s
```

And setting the service configuration with this label:
```yaml
    labels:
      ...
      traefik.http.services.confluence.loadBalancer.serversTransport: confluence-st@file

```

As your issue might be a configuration problem, this issue will be closed.
Fell free to join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik/5).

In case I'm wrong, feel free to re-open the issue.

In the meantime, you can double-check [Traefik's documentation](https://doc.traefik.io/traefik/).
