### ISSUE TITLE
After updating from 2.6.1 to 2.6.2: Dashboard respond with 404

### ISSUE THREAD

**Issue by andrepayone** [traefik/traefik#8887]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

After updating the docker traefik-container from 2.6.1 to 2.6.2, I was not able to access the dashboard anymore, but the functionality of routing is still available. After resetting to version 2.6.1. Everything was working as expected again.

### What did you see instead?

I'm getting a white page, showing "404 page not found". Logs just throw these messages:

### What version of Traefik are you using?

Version:      2.6.2
Codename:     rocamadour
Go version:   go1.17.8
Built:        2022-03-24T19:09:46Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
version: "3.7"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./cert/acme.json:/etc/traefik/acme.json
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 80:80
      - 443:443
    networks:
      - default
      - traefik
    environment:
      - TZ=Europe/Berlin


networks:
  traefik:
    name: traefik
```
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

```
[entryPoints.web]
  address = ":80"

[entryPoints.web.http.redirections.entryPoint]
  to = "websecure"
  scheme = "https"

[entryPoints.websecure]
  address = ":443"

[api]
  debug = true
  dashboard = true

[providers.file]
  directory = "/etc/traefik/dynamic"
  watch = true

[providers.docker]
  exposedByDefault = false
  network = "traefik"
  defaultRule = "Host(`{{ trimPrefix `/` .Name }}.patsy.dev`)"

[certificatesResolvers.le.acme]
  email = "integrations@payone.com"
  storage = "/etc/traefik/acme.json"
  [certificatesResolvers.le.acme.tlsChallenge]
```

### If applicable, please paste the log output in DEBUG level

```
Attaching to traefik
traefik    | time="2022-03-28T12:22:51+02:00" level=info msg="Configuration loaded from file: /etc/traefik/traefik.toml"
traefik    | time="2022-03-28T12:22:51+02:00" level=error msg="middleware \"apiauth, gzip, secHeaders@file\" does not exist" routerName=api@file entryPointName=websecure
traefik    | time="2022-03-28T12:22:52+02:00" level=error msg="middleware \"apiauth, gzip, secHeaders@file\" does not exist" entryPointName=websecure routerName=api@file
traefik    | time="2022-03-28T12:22:52+02:00" level=error msg="middleware \"apiauth, gzip, secHeaders@file\" does not exist" entryPointName=websecure routerName=api@file
```

**Comment by ldez** [comment]
Hello,

can you provide the files that contain your dynamic configuration (the file that contains the router named `api`)?

**Comment by andrepayone** [comment]
```
/srv/traefik/dynamic # ls
dashboard.toml  mailhog.toml  middlewares.toml
```

dashboard.toml
```
[http.routers.api]
  # define routing for traefik dashboard
  entryPoints = ["websecure"]
  rule = "Host(`some.domain.dev`)"
  middlewares = ["apiauth, gzip, secHeaders"]
  service = "api@internal"

[http.routers.api.tls]
  certResolver = "le"
  # define TLS default options for traefik dashboard
  options = "default"

[tls]
  [tls.options]
    [tls.options.default]
      # default TLS options: only TLS 1.2 and 1.3 with strong cyphers
      minVersion = "VersionTLS12"
      preferServerCipherSuites = true
      sniStrict = true
      cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        "TLS_AES_128_GCM_SHA256",
        "TLS_AES_256_GCM_SHA384",
        "TLS_CHACHA20_POLY1305_SHA256"
      ]
      curvePreferences = [
        "CurveP521",
        "CurveP384"
      ]

# Basic Auth Middlewares

[http.middlewares.apiauth.basicAuth]
  users = [
    "someUser:$$alonghash",
  ]

[http.middlewares.teamauth.basicAuth]
  users = [
    "someUser:$$alonghash",
  ]

[http.middlewares.appleauth.basicAuth]
  users = [
    "someUser:$$alonghash",
  ]

[http.middlewares.payoneauth.basicAuth]
  users = [
    "someUser:$$alonghash",
    "someUser2:$alonghash",
  ]
```

mailhog.toml
```
[http.middlewares.mailhogauth.basicAuth]
  users = [
    "someUser:$someHash",
  ]

```

middlewares.toml
```
[http]
  [http.middlewares]
    [http.middlewares.secHeaders]
      [http.middlewares.secHeaders.headers]
        # Define Security relevant Headers to be added as middleware
        frameDeny= true
        accessControlMaxAge= 100
        contentTypeNosniff= true
        sslRedirect= true
        #HSTS Configuration

        #Set this to false if you want to exclude subdomains from HSTS
        stsIncludeSubdomains=true

        #Set this to true if you want to add your domain to the hstspreload list.
        #This operation is very difficult and time consuming if not impossible to revert.
        #Make sure you read the explanation and do your research properly.
        stsPreload= false
        stsSeconds= 15768000

    [http.middlewares.gzip]
      [http.middlewares.gzip.compress]
      # compresses Server responses, helps with load times (marginally)


    [http.middlewares.replace-to-root-path.replacepathregex]
      regex = "^/[a-z]+/[0-9]+/(.*)"
      replacement ="/$$1"
```

**Comment by ldez** [comment]
There is an invalid configuration:

```toml
[http.routers.api]
  # define routing for traefik dashboard
  entryPoints = ["websecure"]
  rule = "Host(`some.domain.dev`)"
  middlewares = ["apiauth, gzip, secHeaders"] <---- here
  service = "api@internal"
```

the valid configuration:


```toml
[http.routers.api]
  # define routing for traefik dashboard
  entryPoints = ["websecure"]
  rule = "Host(`some.domain.dev`)"
  middlewares = ["apiauth", "gzip", "secHeaders"] <---- here
  service = "api@internal"
```
