### ISSUE TITLE
Support evaluating some runtime data for dynamic config values

### ISSUE THREAD

**Issue by ddtmachado** [traefik/traefik#8897]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

From time to time there are requests to make Traefik Proxy allow evaluation of runtime data from the dynamic config to be used as a value.

The goal for this issue if to spark discussions on the design of a feature that would allow it. Here are some use cases:

**Example 1)** One might want to set the Host header of requests to the hostname running the proxy instance, something like this:

```yaml
http:
  middlewares:
    replace-host:
      headers:
        customRequestHeaders:
          Host: "$hostname"
```

**Example 2)** Using more complex functions, one might want to pass the client certificate info on different headers [than usual](https://doc.traefik.io/traefik/middlewares/http/passtlsclientcert/#configuration-examples):

```yaml
http:
  middlewares:
    test-passtlsclientcert:
      passTLSClientCert:
        info:
          sans: true
  
    add-custom-sans:
      headers:
        customRequestHeaders:
          X-SANS: "get req.Header 'X-Forwarded-Tls-Client-Cert-Info' | regexSplit 'SANS='"
```

**Example 3)** As a final use case we could have a middleware or plugin injecting some data on the request already and then we want to iterate over it, this could be particularly useful for individual by code but dependent by data middleware like in an authentication and authorization situation.

```yaml
http:
  middlewares:
    my-authentication-middleware:
      plugin:
        auth-middleware:          
          proxyHeaderName: injectedPayload
  
    my-authorization-middleware:
      plugin:
        authrz-middleware:
          groupExtractor: "(get req.Header 'injectedPayload' | mustFromJson).User.Group"
          paths:
            - regex: "^/admin(.*)"
               groups: admin
```

The examples used the existing [sprig library](https://masterminds.github.io/sprig/) format just because its already a dependency for Traefik but it should not be a hard requirement for the proposal itself.

Further studies must be made to clear security and scope issues on the data that can be made available for a middleware / plugin.
