### ISSUE TITLE
YAML parsing does not work for arrays in Traefik v2.6.2

### ISSUE THREAD

**Issue by PascalMinder** [traefik/traefik#8901]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I am developing the extension https://github.com/PascalMinder/GeoBlock and came across an issue. The plugin allows defining a list of countries which are allowed to connect to a service. 

### What did you see instead?

The list is parsed from YAML to a []string. This worked fine up to version v2.6.2. Now the list of countries is one single string ("allowed:  GB║IS").

### What version of Traefik are you using?

It works on version 2.6.1 and stops working on version 2.6.2

### What is your environment & configuration?

```yaml
http:
  middlewares:
    my-plugin:
      plugin:
        geoblock:
          allowLocalRequests: true
          logLocalRequests: true
          logAllowedRequests: true
          logApiRequests: true
          api: "https://get.geojs.io/v1/ip/country/{ip}"
          cacheSize: 15
          forceMonthlyUpdate: true
          allowUnknownCountries: false
          unknownCountryApiResponse: "nil"
          countries:
            - GB
            - IS
```

```yaml
log:
  level: INFO

experimental:
  localPlugins:
    geoblock:
      moduleName: github.com/pascalminder/geoblock

# experimental:
#   devPlugin:
#       goPath: /plugins/go
#       moduleName: github.com/Develop/GeoBlock

# API and dashboard configuration
api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"
    forwardedHeaders:
      insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic-configuration.yml
```
