### ISSUE TITLE
2.6.3 encoding error on middleware headers accessControlAllowMethods

### ISSUE THREAD

**Issue by fitz-ddsg** [traefik/traefik#8903]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

After update to 2.6.3 the response on middleware headers accessControlAllowMethods shows encoding issues.

### What did you see instead?

2.6.1:
`Access-Control-Allow-Methods: POST,GET,OPTIONS,PUT,PATCH,DELETE`
2.6.3: 
`Access-Control-Allow-Methods: POST║GET║OPTIONS║PUT║PATCH║DELETE`

### What version of Traefik are you using?

traefik_v2.6.3_linux_amd64.tar.gz

### What is your environment & configuration?

```toml
# rewrite.toml
[http.middlewares]
  [http.middlewares.disable-cors.headers.customResponseHeaders]    
    Access-Control-Allow-Origin = "*"
    Access-Control-Max-Age = 600
    Access-Control-Allow-Methods = ["POST", "GET", "OPTIONS", "PUT","PATCH","DELETE"]
    Access-Control-Allow-Headers = ["*"]
```
```toml
# service.toml
[http]
  [http.routers]
    [http.routers.test]
      service="test"
      entrypoints="web"
      middlewares = ["rewrite@file"]
      rule="PathPrefix(`/api/v2/me`)"

  [http.services]
     [http.services.test]
        [http.services.test.loadBalancer]
            passHostHeader = false
            [[http.services.test.loadBalancer.servers]]
              url = "https://www.google.com"
```
```toml
[entryPoints]
  [entryPoints.web]
    address = ":80"
  
    [entryPoints.web.forwardedHeaders]
      insecure = true

[providers]
  [providers.file]
    directory = "/opt/traefik/dynamic"
    watch = true

[log]
  level = "DEBUG"
```

**Comment by ldez** [comment]
Hello,


we fixed a bug in our configuration parsing in the previous version (v2.6.1, v2.6.2).

So now, the exploitation of the bug a visible.

Your configuration is invalid because `customResponseHeaders` is a map of strings (keys are strings and values are strings)

Also the options (`Access-Control-Allow-Methods`, `Access-Control-Allow-Headers`, etc...) are options of `headers` and not `customResponseHeaders`.

```toml
[http.middlewares]
  [http.middlewares.disable-cors.headers.customResponseHeaders]  # <--- here
    Access-Control-Allow-Origin = "*"
    Access-Control-Max-Age = 600
    Access-Control-Allow-Methods = ["POST", "GET", "OPTIONS", "PUT","PATCH","DELETE"] # <-- HERE
    Access-Control-Allow-Headers = ["*"] # <-- HERE
```

You have 2 possibilities:
- use the right option on `header`
```toml
[http.middlewares]
  [http.middlewares.disable-cors.headers]   # <--- here
    Access-Control-Allow-Origin = "*"
    Access-Control-Max-Age = 600
    Access-Control-Allow-Methods = ["POST", "GET", "OPTIONS", "PUT","PATCH","DELETE"] # <--- here
    Access-Control-Allow-Headers = ["*"] # <--- here
```

- use `customResponseHeaders` and map of strings:
```toml
[http.middlewares]
  [http.middlewares.disable-cors.headers.customResponseHeaders]  # <--- here
    Access-Control-Allow-Origin = "*"
    Access-Control-Max-Age = 600
    Access-Control-Allow-Methods = "POST,GET,OPTIONS,PUT,PATCH,DELETE" # <--- here
    Access-Control-Allow-Headers = "*" # <--- here
```
