### ISSUE TITLE
stuck in accept4 too many files open error loop 

### ISSUE THREAD

**Issue by lamyotte** [traefik/traefik#8904]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

We have been trying to upgrade from Traefik v1 to Traefik v2 but we are experiencing sporadic errors in v2. 

We are running Traefik in 8 parallel containers behind an AWS ALB. The containers use a dynamic configuration with an http provider. 

We have a high volume of requests going through Traefik, along the lines of an average of 30,000 per minute per container during peek.

### What did you see instead?

Periodically, one the containers will enter an unresponsive state where all requests will fail with a 502. Our logs will show about **5 million lines** of : 
`level=error msg="accept tcp [::]:80: accept4: too many open files" entryPointName=http`

The ALB detects the container is unresponsive and the problem will self resolve once the container is killed automatically. 
So far we have not seen Traefik self recuperate from this state. This process can take about a minute and even with lower thresholds we are talking about 30,000 requests failing with 502s, which is noticeable by users. 

This bug does not happened immediately either, we've seen the container being healthy for days before it crashed. There is no visible pattern in timing between each incidence. 

We have ruled out memory and cpu shortage or sudden spikes of requests. The lasted incidence happened during a lower traffic hour. We also upped our container count from 4 to 8 in order to lower the impact of this bug and hoping the lowered load would fix the problem but it has not.

We have managed to rule out a slow creep of open connections or open files by using a companion script on our containers that log the number of open files every minute. We have seen the number of open files go from an average 5,000 to more than 200,000 within a minute on the fault Traefik container during the latest incident.

We suspect an error somewhere is causing Traefik to be stuck in an infinite loop but we have not been able to find the exact trigger. 

This does not happen in our dev environnement making this bug difficult to repro without having a clue at what causes it. 

At this stage, we are running low on things to check and would like to have some input.

This part of the code seems like it could get Traefik stuck into and endless loop of opening connections but we're still getting familiar with the source code and we lack the knowledge to dig deeper. 
https://github.com/traefik/traefik/blob/0d7d5a0318c29abc88e63cf4333f4234c0de7ad8/pkg/server/server_entrypoint_tcp.go#L183-L200

This error never happened in v1 and the only thing that changed between the versions in our configuration is the usage of an http provider (we were using a dynamodb provider in v1) 

I've seen a few reports of similar issues but all of them are closed now, leading us to believe this might be a new issue.

Could this be related to a request payload? Or perhaps something happens to the connection between Traefik and certain backends causing this? Any insights and things we could look into next would be greatly appreciated. 

### What version of Traefik are you using?

Version:      2.6.2
Codename:     rocamadour
Go version:   go1.17.8
Built:        2022-03-24T19:09:46Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```toml
[log]
  level = "INFO"

[accessLog]
  format = "json"
  [accessLog.filters]
    statusCodes = ["500-599"]
[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.forwardedHeaders]
      trustedIPs = ["10.0.0.0/8"]
    [entryPoints.http.transport]
      [entryPoints.http.transport.lifeCycle]
        graceTimeOut = "0s"
[ping]
  entryPoint = "http"
  manualRouting = true
[providers.http]
  endpoint = "--"
  pollInterval = "--"
  pollTimeout = "--"
[serversTransport.forwardingTimeouts]
  responseHeaderTimeout = "910s"
[serversTransport]
  insecureSkipVerify = true
```
(redacted some values)

All our router and service configuration is loaded from the http provider. 
This is the same configuration that we use in v1 adapted for v2.

### If applicable, please paste the log output in DEBUG level

Unfortunately, we cannot enable DEBUG logs in our production environnement due to the volume of logs that would generate.
