### ISSUE TITLE
ACME Hetzner "could not get zone" with internal DNSes

### ISSUE THREAD

**Issue by bryanpedini** [traefik/traefik#8910]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Træfik (Lego) is not able to find the DNS zone to issue a Let's Encrypt cert for a subdomain resolved internally.

Træfik is located under `traefik.home.mydomain.com` and has a valid certificate (issued before the DNS servers were configured), `heimdall.home.mydomain.com` does not get issued a Let's Encrypt certificate because Lego `could not get zone for domain home.mydomain.com not found`.

Some additional information that might be useful:
The `home.mydomain.com` domain is not public, it is resolved by two PowerDNS virtual machines internally, it's using a public domain to be able to issue valid LE certificates for HTTPS, since the network will soon be used by a tenant and I would like to not have HTTP unencrypted passwords floating around, even internally, even with a dumb tenant that doesn't know what a computer even is. Just to be sure, you know...
Temporarily removing the two PowerDNS servers gets Træfik to issue the certificate correctly, tho I don't understand why since the communication for issuing the cert should be between [Træfik, Let's Encrypt ACME servers, Hetzner's API servers].

I would like if possible to know the flow chart of the events and the systems that get involved when issuing a certificate, and to understand how to resolve the subdomain internally with private IP addresses but still being able to issue certificates using Hetzner's external DNS servers for the whole domain instead of the internal PowerDNS ones.

### What did you see instead?

```
traefik.home.mydomain.com  | time="2022-04-02T09:06:38Z" level=error msg="Unable to obtain ACME certificate for domains \"heimdall.home.mydomain.com\": unable to generate a certificate for the domains [heimdall.home.mydomain.com]: error: one or more domains had a problem:\n[heimdall.home.mydomain.com] [heimdall.home.mydomain.com] acme: error presenting token: hetzner: could not get zone for domain home.mydomain.com not found\n" rule="Host(`heimdall.home.mydomain.com`)" providerName=letsencrypt.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=https-heimdall_home_mydomain_com@docker
```

### What version of Traefik are you using?

```
Version:      2.6.3
Codename:     rocamadour
Go version:   go1.17.8
Built:        2022-03-29T13:09:27Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

<details>
<summary>Træfik YAML</summary>

```yaml
---
version: "3"

services:
  traefik:
    image: traefik:${TRAEFIK_VERSION}
    restart: unless-stopped
    command:
      # when debugging is needed
      - --accesslog=${TRAEFIK_ACCESSLOG}
      # enable Træfik dashboard
      - --api.dashboard=true
      # configure Let's Encrypt automatic certificates
      - --certificatesresolvers.${TRAEFIK_CERTRESOLVER}.acme.dnschallenge=true
      - --certificatesresolvers.${TRAEFIK_CERTRESOLVER}.acme.dnschallenge.provider=hetzner
      - --certificatesresolvers.${TRAEFIK_CERTRESOLVER}.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.${TRAEFIK_CERTRESOLVER}.acme.keytype=RSA4096
      - --certificatesresolvers.${TRAEFIK_CERTRESOLVER}.acme.storage=/certs.json
      # we listen on both HTTP and HTTPS
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      # logging level
      - --log.level=${TRAEFIK_LOGLEVEL}
      # Træfik Pilot token (of course retrieved from dotenv)
      - --pilot.token=${TRAEFIK_PILOT_TOKEN}
      # we only use Docker (for now)
      - --providers.docker=true
      # and we want to manually specify exposed containers
      - --providers.docker.exposedbydefault=false
      - --providers.docker.watch=true
      # should not need, but just in case, a folder for dynamic config files is also configured
      - --providers.file.directory=/config
      - --providers.file.watch=true
    environment:
      - HETZNER_API_KEY=${HETZNER_API_KEY}
    labels:
      # expose Træfik using Træfik (dashboard)
      - traefik.enable=${TRAEFIK_ENABLED}
      # configure a global whitelist for my home
      - traefik.http.middlewares.dashboard-whitelist.ipwhitelist.sourcerange=${TRAEFIK_DASHBOARD_WHITELIST}
      # configure the global redirect middleware
      - traefik.http.middlewares.http-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.http-to-https.redirectscheme.permanent=true
      ### Section HTTP
      - traefik.http.routers.http-${TRAEFIK_ROUTER}.entrypoints=http
      # only some people can access the dashboard, hence protect it with it's whitelist
      - traefik.http.routers.http-${TRAEFIK_ROUTER}.middlewares=dashboard-whitelist
      # redirect Træfik dashboard to HTTPS only
      - traefik.http.routers.http-${TRAEFIK_ROUTER}.middlewares=http-to-https
      - traefik.http.routers.http-${TRAEFIK_ROUTER}.rule=Host(`${TRAEFIK_MATCHRULE}`)
      - traefik.http.routers.http-${TRAEFIK_ROUTER}.service=api@internal
      ### Section HTTPS
      - traefik.http.routers.https-${TRAEFIK_ROUTER}.entrypoints=https
      # only some people can access the dashboard, hence protect it with it's whitelist
      - traefik.http.routers.https-${TRAEFIK_ROUTER}.middlewares=dashboard-whitelist
      # configure Træfik dashboard to be the exposed service
      - traefik.http.routers.https-${TRAEFIK_ROUTER}.rule=Host(`${TRAEFIK_MATCHRULE}`)
      - traefik.http.routers.https-${TRAEFIK_ROUTER}.service=api@internal
      # of course, enable TLS and it's certificate provider
      - traefik.http.routers.https-${TRAEFIK_ROUTER}.tls=${TRAEFIK_TLSENABLED}
      - traefik.http.routers.https-${TRAEFIK_ROUTER}.tls.certresolver=${TRAEFIK_CERTRESOLVER}
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/config:ro
      - ./certs.json:/certs.json

networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}
```
</details>
<details>
<summary>Træfik env</summary>

```sh
# General environment
TRAEFIK_VERSION=2.6.3
TRAEFIK_CERTRESOLVER=letsencrypt
TRAEFIK_DASHBOARD_WHITELIST=192.168.10.0/24
TRAEFIK_ENABLED=true
TRAEFIK_NETWORK=traefik
TRAEFIK_MATCHRULE=traefik.home.mydomain.com
TRAEFIK_ROUTER=traefik_home_mydomain_com
TRAEFIK_PILOT_TOKEN= #not used yet
TRAEFIK_TLSENABLED=true

# Certificate provider
HETZNER_API_KEY=REDACTED
LETSENCRYPT_EMAIL=domains@mydomain.com

# Debugging
TRAEFIK_ACCESSLOG=false
TRAEFIK_LOGLEVEL=DEBUG
```
</details>
<details>
<summary>Heimdall YAML</summary>

```yaml
---
version: "3"

services:
  heimdall:
    image: linuxserver/heimdall:${HEIMDALL_VERSION}
    restart: unless-stopped
    environment:
      - PUID=${HEIMDALL_PUID}
      - PGID=${HEIMDALL_PGID}
      - TZ=${HEIMDALL_TIMEZONE}
    labels:
      - traefik.enable=${TRAEFIK_ENABLED}
      - traefik.docker.network=traefik
      ### Section HTTP
      - traefik.http.routers.http-${TRAEFIK_ROUTER}.entrypoints=http
      # redirect to HTTPS only
      - traefik.http.routers.http-${TRAEFIK_ROUTER}.middlewares=http-to-https
      - traefik.http.routers.http-${TRAEFIK_ROUTER}.rule=Host(`${TRAEFIK_MATCHRULE}`)
      ### Section HTTPS
      - traefik.http.routers.https-${TRAEFIK_ROUTER}.entrypoints=https
      # configure the exposed service
      - traefik.http.routers.https-${TRAEFIK_ROUTER}.rule=Host(`${TRAEFIK_MATCHRULE}`)
      # of course, enable TLS and it's certificate provider
      - traefik.http.routers.https-${TRAEFIK_ROUTER}.tls=${TRAEFIK_TLSENABLED}
      - traefik.http.routers.https-${TRAEFIK_ROUTER}.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      # specify a service so a custom port can be used
      - traefik.http.services.${TRAEFIK_SERVICE}.loadbalancer.server.port=${TRAEFIK_SERVICE_PORT}
    networks:
      - traefik
    volumes:
      - ./config:/config

networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}
```
</details>
<details>
<summary>Heimdall env</summary>

```sh
# Heimdall
HEIMDALL_VERSION=2.2.2
HEIMDALL_PUID=1001
HEIMDALL_PGID=1001
HEIMDALL_TIMEZONE=Europe/Rome

# Træfik
TRAEFIK_CERTRESOLVER=letsencrypt
TRAEFIK_ENABLED=true
TRAEFIK_MATCHRULE=heimdall.home.mydomain.com
TRAEFIK_NETWORK=traefik
TRAEFIK_ROUTER=heimdall_home_mydomain_com
TRAEFIK_SERVICE=heimdall_home_mydomain_com
TRAEFIK_SERVICE_PORT=80
TRAEFIK_TLSENABLED=true
```
</details>

### If applicable, please paste the log output in DEBUG level

<details>
<summary>DEBUG logs</summary>

```
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=info msg="Configuration loaded from flags."
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=info msg="Traefik version 2.6.3 built on 2022-03-29T13:09:27Z"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"http\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}},\"https\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"},\"file\":{\"directory\":\"/config\",\"watch\":true}},\"api\":{\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"certificatesResolvers\":{\"letsencrypt\":{\"acme\":{\"email\":\"domains@mydomain.com\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"/certs.json\",\"keyType\":\"RSA4096\",\"certificatesDuration\":2160,\"dnsChallenge\":{\"provider\":\"hetzner\"}}}},\"pilot\":{\"dashboard\":true}}"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=info msg="Starting provider aggregator.ProviderAggregator"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Start TCP Server" entryPointName=https
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Start TCP Server" entryPointName=http
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=info msg="Starting provider *file.Provider"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="*file.Provider provider configuration: {\"directory\":\"/config\",\"watch\":true}"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=info msg="Starting provider *traefik.Provider"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="*traefik.Provider provider configuration: {}"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=info msg="Starting provider *acme.Provider"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="*acme.Provider provider configuration: {\"email\":\"domains@mydomain.com\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"/certs.json\",\"keyType\":\"RSA4096\",\"certificatesDuration\":2160,\"dnsChallenge\":{\"provider\":\"hetzner\"},\"ResolverName\":\"letsencrypt\",\"store\":{},\"TLSChallengeProvider\":{\"Timeout\":4000000000},\"HTTPChallengeProvider\":{}}"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Attempt to renew certificates \"720h0m0s\" before expiry and check every \"24h0m0s\"" providerName=letsencrypt.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=info msg="Testing certificate renew..." providerName=letsencrypt.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=info msg="Starting provider *docker.Provider"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="*docker.Provider provider configuration: {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"}"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Configuration received from provider file: {\"http\":{},\"tcp\":{},\"udp\":{},\"tls\":{\"options\":{\"compatible\":{\"minVersion\":\"VersionTLS11\",\"clientAuth\":{},\"alpnProtocols\":[\"h2\",\"http/1.1\",\"acme-tls/1\"]},\"default\":{\"minVersion\":\"VersionTLS12\",\"clientAuth\":{},\"alpnProtocols\":[\"h2\",\"http/1.1\",\"acme-tls/1\"]},\"mintls13\":{\"minVersion\":\"VersionTLS13\",\"clientAuth\":{},\"alpnProtocols\":[\"h2\",\"http/1.1\",\"acme-tls/1\"]},\"supercompatible\":{\"minVersion\":\"VersionTLS10\",\"clientAuth\":{},\"alpnProtocols\":[\"h2\",\"http/1.1\",\"acme-tls/1\"]}}}}" providerName=file
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Configuration received from provider internal: {\"http\":{\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{}},\"serversTransports\":{\"default\":{\"maxIdleConnsPerHost\":200}}},\"tcp\":{},\"tls\":{}}" providerName=internal
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Configuration received from provider letsencrypt.acme: {\"http\":{},\"tls\":{}}" providerName=letsencrypt.acme
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="No default certificate, generating one" tlsStoreName=default
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=info msg="Starting provider *acme.ChallengeTLSALPN"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="*acme.ChallengeTLSALPN provider configuration: {\"Timeout\":4000000000}"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Provider connection established with docker 20.10.13 (API 1.41)" providerName=docker
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Configuration received from provider docker: {\"http\":{\"routers\":{\"http-heimdall_home_mydomain_com\":{\"entryPoints\":[\"http\"],\"middlewares\":[\"http-to-https\"],\"service\":\"heimdall_home_mydomain_com\",\"rule\":\"Host(`heimdall.home.mydomain.com`)\"},\"http-traefik_home_mydomain_com\":{\"entryPoints\":[\"http\"],\"middlewares\":[\"http-to-https\"],\"service\":\"api@internal\",\"rule\":\"Host(`traefik.home.mydomain.com`)\"},\"https-heimdall_home_mydomain_com\":{\"entryPoints\":[\"https\"],\"service\":\"heimdall_home_mydomain_com\",\"rule\":\"Host(`heimdall.home.mydomain.com`)\",\"tls\":{\"certResolver\":\"letsencrypt\"}},\"https-traefik_home_mydomain_com\":{\"entryPoints\":[\"https\"],\"middlewares\":[\"dashboard-whitelist\"],\"service\":\"api@internal\",\"rule\":\"Host(`traefik.home.mydomain.com`)\",\"tls\":{\"certResolver\":\"letsencrypt\"}}},\"services\":{\"heimdall_home_mydomain_com\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.19.0.3:80\"}],\"passHostHeader\":true}},\"traefik_home_mydomain_com\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.19.0.2:80\"}],\"passHostHeader\":true}}},\"middlewares\":{\"dashboard-whitelist\":{\"ipWhiteList\":{\"sourceRange\":[\"192.168.10.0/24\"]}},\"http-to-https\":{\"redirectScheme\":{\"scheme\":\"https\",\"permanent\":true}}}},\"tcp\":{},\"udp\":{}}" providerName=docker
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="No default certificate, generating one" tlsStoreName=default
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Adding certificate for domain(s) traefik.home.mydomain.com"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="No default certificate, generating one" tlsStoreName=default
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Adding certificate for domain(s) traefik.home.mydomain.com"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Creating middleware" routerName=http-heimdall_home_mydomain_com@docker serviceName=heimdall_home_mydomain_com middlewareName=pipelining middlewareType=Pipelining entryPointName=http
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Creating load-balancer" entryPointName=http routerName=http-heimdall_home_mydomain_com@docker serviceName=heimdall_home_mydomain_com
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Creating server 0 http://172.19.0.3:80" entryPointName=http routerName=http-heimdall_home_mydomain_com@docker serviceName=heimdall_home_mydomain_com serverName=0
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="child http://172.19.0.3:80 now UP"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Propagating new UP status"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Added outgoing tracing middleware heimdall_home_mydomain_com" routerName=http-heimdall_home_mydomain_com@docker middlewareType=TracingForwarder middlewareName=tracing entryPointName=http
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Creating middleware" middlewareName=http-to-https@docker entryPointName=http routerName=http-heimdall_home_mydomain_com@docker middlewareType=RedirectScheme
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Setting up redirection to https " routerName=http-heimdall_home_mydomain_com@docker middlewareType=RedirectScheme middlewareName=http-to-https@docker entryPointName=http
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Adding tracing to middleware" routerName=http-heimdall_home_mydomain_com@docker middlewareName=http-to-https@docker entryPointName=http
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Added outgoing tracing middleware api@internal" routerName=http-traefik_home_mydomain_com@docker middlewareName=tracing middlewareType=TracingForwarder entryPointName=http
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Creating middleware" middlewareName=http-to-https@docker middlewareType=RedirectScheme entryPointName=http routerName=http-traefik_home_mydomain_com@docker
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Setting up redirection to https " middlewareName=http-to-https@docker middlewareType=RedirectScheme entryPointName=http routerName=http-traefik_home_mydomain_com@docker
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Adding tracing to middleware" middlewareName=http-to-https@docker entryPointName=http routerName=http-traefik_home_mydomain_com@docker
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Creating middleware" entryPointName=http middlewareName=traefik-internal-recovery middlewareType=Recovery
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Creating middleware" serviceName=heimdall_home_mydomain_com entryPointName=https routerName=https-heimdall_home_mydomain_com@docker middlewareName=pipelining middlewareType=Pipelining
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Creating load-balancer" entryPointName=https routerName=https-heimdall_home_mydomain_com@docker serviceName=heimdall_home_mydomain_com
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Creating server 0 http://172.19.0.3:80" serviceName=heimdall_home_mydomain_com serverName=0 entryPointName=https routerName=https-heimdall_home_mydomain_com@docker
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="child http://172.19.0.3:80 now UP"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Propagating new UP status"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Added outgoing tracing middleware heimdall_home_mydomain_com" middlewareName=tracing middlewareType=TracingForwarder entryPointName=https routerName=https-heimdall_home_mydomain_com@docker
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Added outgoing tracing middleware api@internal" entryPointName=https routerName=https-traefik_home_mydomain_com@docker middlewareName=tracing middlewareType=TracingForwarder
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Creating middleware" routerName=https-traefik_home_mydomain_com@docker middlewareName=dashboard-whitelist@docker middlewareType=IPWhiteLister entryPointName=https
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Setting up IPWhiteLister with sourceRange: [192.168.10.0/24]" entryPointName=https routerName=https-traefik_home_mydomain_com@docker middlewareName=dashboard-whitelist@docker middlewareType=IPWhiteLister
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Adding tracing to middleware" routerName=https-traefik_home_mydomain_com@docker entryPointName=https middlewareName=dashboard-whitelist@docker
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery entryPointName=https middlewareType=Recovery
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Adding route for traefik.home.mydomain.com with TLS options default" entryPointName=https
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Adding route for heimdall.home.mydomain.com with TLS options default" entryPointName=https
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Try to challenge certificate for domain [traefik.home.mydomain.com] found in HostSNI rule" routerName=https-traefik_home_mydomain_com@docker rule="Host(`traefik.home.mydomain.com`)" providerName=letsencrypt.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Try to challenge certificate for domain [heimdall.home.mydomain.com] found in HostSNI rule" rule="Host(`heimdall.home.mydomain.com`)" providerName=letsencrypt.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=https-heimdall_home_mydomain_com@docker
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Looking for provided certificate(s) to validate [\"heimdall.home.mydomain.com\"]..." rule="Host(`heimdall.home.mydomain.com`)" providerName=letsencrypt.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=https-heimdall_home_mydomain_com@docker
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Domains [\"heimdall.home.mydomain.com\"] need ACME certificates generation for domains \"heimdall.home.mydomain.com\"." routerName=https-heimdall_home_mydomain_com@docker rule="Host(`heimdall.home.mydomain.com`)" providerName=letsencrypt.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Loading ACME certificates [heimdall.home.mydomain.com]..." ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=https-heimdall_home_mydomain_com@docker rule="Host(`heimdall.home.mydomain.com`)" providerName=letsencrypt.acme
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Building ACME client..." providerName=letsencrypt.acme
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="https://acme-v02.api.letsencrypt.org/directory" providerName=letsencrypt.acme
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="Looking for provided certificate(s) to validate [\"traefik.home.mydomain.com\"]..." ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=https-traefik_home_mydomain_com@docker rule="Host(`traefik.home.mydomain.com`)" providerName=letsencrypt.acme
traefik.home.mydomain.com  | time="2022-04-02T09:06:35Z" level=debug msg="No ACME certificate generation required for domains [\"traefik.home.mydomain.com\"]." ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=https-traefik_home_mydomain_com@docker rule="Host(`traefik.home.mydomain.com`)" providerName=letsencrypt.acme
traefik.home.mydomain.com  | time="2022-04-02T09:06:36Z" level=debug msg="Using DNS Challenge provider: hetzner" providerName=letsencrypt.acme
traefik.home.mydomain.com  | time="2022-04-02T09:06:36Z" level=debug msg="legolog: [INFO] [heimdall.home.mydomain.com] acme: Obtaining bundled SAN certificate"
traefik.home.mydomain.com  | time="2022-04-02T09:06:37Z" level=debug msg="legolog: [INFO] [heimdall.home.mydomain.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/93984391280"
traefik.home.mydomain.com  | time="2022-04-02T09:06:37Z" level=debug msg="legolog: [INFO] [heimdall.home.mydomain.com] acme: Could not find solver for: tls-alpn-01"
traefik.home.mydomain.com  | time="2022-04-02T09:06:37Z" level=debug msg="legolog: [INFO] [heimdall.home.mydomain.com] acme: Could not find solver for: http-01"
traefik.home.mydomain.com  | time="2022-04-02T09:06:37Z" level=debug msg="legolog: [INFO] [heimdall.home.mydomain.com] acme: use dns-01 solver"
traefik.home.mydomain.com  | time="2022-04-02T09:06:37Z" level=debug msg="legolog: [INFO] [heimdall.home.mydomain.com] acme: Preparing to solve DNS-01"
traefik.home.mydomain.com  | time="2022-04-02T09:06:37Z" level=debug msg="legolog: [INFO] [heimdall.home.mydomain.com] acme: Cleaning DNS-01 challenge"
traefik.home.mydomain.com  | time="2022-04-02T09:06:37Z" level=debug msg="legolog: [WARN] [heimdall.home.mydomain.com] acme: cleaning up failed: hetzner: could not get zone for domain home.mydomain.com not found "
traefik.home.mydomain.com  | time="2022-04-02T09:06:37Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/93984391280"
traefik.home.mydomain.com  | time="2022-04-02T09:06:38Z" level=error msg="Unable to obtain ACME certificate for domains \"heimdall.home.mydomain.com\": unable to generate a certificate for the domains [heimdall.home.mydomain.com]: error: one or more domains had a problem:\n[heimdall.home.mydomain.com] [heimdall.home.mydomain.com] acme: error presenting token: hetzner: could not get zone for domain home.mydomain.com not found\n" rule="Host(`heimdall.home.mydomain.com`)" providerName=letsencrypt.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=https-heimdall_home_mydomain_com@docker
```
</details>
