### ISSUE TITLE
ipWhiteList parse issue using toml dynamic conf

### ISSUE THREAD

**Issue by anapivirtua** [traefik/traefik#8911]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Since 2.6.2 and still present in 2.6.3 the ipWhiteList parse is broken using TOML configuration:

```toml
  [http.middlewares]
     [http.middlewares.lan-whitelist.ipWhiteList]
       sourceRange = ["172.17.0.1/32, 192.168.0.0/24"] #Docker, LANv4, Nov6
```

Which match documentation: https://doc.traefik.io/traefik/middlewares/http/ipwhitelist/

Return

`cannot parse CIDR whitelist [172.17.0.1/32, 192.168.0.0/24]: parsing CIDR trusted IPs <nil>: invalid CIDR address: 172.17.0.1/32, 192.168.0.0/24 
`

Note that the list ["172.17.0.1/32, 192.168.0.0/24"] is returned as an unique string.

May be related to #8885 but while it is fixed for yml it isn't for toml.

### What did you see instead?

ipWhiteList arguments should be parsed correctly.

### What version of Traefik are you using?

2.6.3

**Comment by ldez** [comment]
Hello,

Yes, it's the same thing as #8885 but with TOML instead of YAML.

Your configuration is invalid:

```toml
  [http.middlewares]
     [http.middlewares.lan-whitelist.ipWhiteList]
       sourceRange = ["172.17.0.1/32, 192.168.0.0/24"] < -- Here
```

the valid configuration:

```toml
  [http.middlewares]
     [http.middlewares.lan-whitelist.ipWhiteList]
       sourceRange = ["172.17.0.1/32", "192.168.0.0/24"] < -- Here
```
