### ISSUE TITLE
Authelia middleware regression since 2.6.1

### ISSUE THREAD

**Issue by Tchoupinax** [traefik/traefik#8914]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Hello,

I meet a weird issue about Traefik and Authelia. I use Authelia as a middleware to authenticate my requests. After logged in, the client receives a cookie that is send in the request. The middleware intercepts the request, send it to Authelia and if all is Ok, return data that are forwared to the backend by traefik (remote-email is one). (The setup can be viewed here : https://www.authelia.com/docs/deployment/supported-proxies/traefik2.x.html)

However, my configuration does not work from Traefik 2.6.2 or higher, it works with Traefik 2.6.1.
It is very strange because I can't reproduce the issue in local... I correctly receive the remote email with 2.6.2, 2.6.3, 2.7.0-rc1, 2.7.0-rc2 but not in my production setup. 2.6.1 works perfectly, I change the docker image to 2.6.2 and it stops to work.

I have seen the difference between the two releases (https://github.com/traefik/traefik/compare/v2.6.1...v2.6.2) but I do not see anything. My production setup says clearly the issue come from Traefik because it is the only thing I change but as I can't reproduce the issue in local, I have a lot a doubt about what is the real problem. 

### What did you see instead?

.

### What version of Traefik are you using?

works on 2.6.1

does not work form > 2.6.1

### What is your environment & configuration?

.

### If applicable, please paste the log output in DEBUG level

When it works, I see in the logs the forwarded data from Authelia. When it does not work, I do not see them anymore

**Comment by kevinpollet** [comment]
Hello @Tchoupinax,

Thanks for your interest in Traefik,

Can you provide your static, dynamic configuration and the debug logs, or a reproducible use case?

We introduced some changes in the configuration parsing in `v2.6.2`, which introduced a bug fixed in `v2.6.3` and `v2.7.0-rc2`. So, maybe you are hitting https://github.com/traefik/traefik/issues/8885 and have to check that the `ForwardAuth` middleware configuration is valid.

**Comment by philw95** [comment]
Hello,

i have the same Problem with traefik-forward-auth (https://github.com/thomseddon/traefik-forward-auth)
Up to version 2.6.1 everything worked great.
Since 2.6.2 it will not working.

When I call a page with the middleware I get a 404 page.

Here my Config:
docker compose:
```
  traefik:
    image: traefik:2.6.3
    command: "traefik --providers.docker"
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
      - "51820:51820/udp"
    volumes:
      - type: bind
        source: ./traefik/traefik.toml
        target: /etc/traefik/traefik.toml
      - type: bind
        source: /_files/traefik/netcup_key
        target: /etc/traefik/netcup_key
        read_only: true
      - type: bind
        source: /_files/traefik/netcup_password
        target: /etc/traefik/netcup_password
        read_only: true
      - type: bind
        source: /_files/traefik/netcup_id
        target: /etc/traefik/netcup_id
        read_only: true
      - type: bind
        source: /_files/traefik/acme.json
        target: /etc/traefik/acme.json
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: ./traefik/conf.d
        target: /etc/traefik/conf.d
    container_name: traefik
    environment:
      TZ: "Europe/Berlin"
      NETCUP_API_KEY_FILE: "/etc/traefik/netcup_key"
      NETCUP_API_PASSWORD_FILE: "/etc/traefik/netcup_password"
      NETCUP_CUSTOMER_NUMBER_FILE: "/etc/traefik/netcup_id"
    restart: always

  oauth:
    image: thomseddon/traefik-forward-auth:2
    volumes:
      - type: bind
        source: /_files/traefik-forward-auth/config.ini
        target: /etc/traefik-forward-auth/config.ini
        read_only: true
    labels:
      traefik.enable: "true"
      traefik.docker.network: "network"
      traefik.http.routers.oauth-rtr.entrypoints: "https"
      traefik.http.routers.oauth-rtr.middlewares: "chain-oauth@file"
      traefik.http.routers.oauth-rtr.rule: "Host(`oauth.DOMAIN`)"
      traefik.http.routers.oauth-rtr.tls: "true"
      traefik.http.routers.oauth-rtr.service: "oauth-svc"
      traefik.http.services.oauth-svc.loadbalancer.server.port: "4181"
      com.centurylinklabs.watchtower.depends-on: "traefik"
    container_name: oauth
    environment:
      TZ: "Europe/Berlin"
      CONFIG: "/etc/traefik-forward-auth/config.ini"
      COOKIE_DOMAIN: "DOMAIN"
      AUTH_HOST: "oauth.DOMAIN"
      URL_PATH: "/_oauth"
    restart: always

  error-pages:
    image: tarampampam/error-pages
    labels:
      traefik.enable: "true"
      traefik.docker.network: "network"
      traefik.http.routers.error-pages-router.entrypoints: "https"
      traefik.http.routers.error-pages-router.middlewares: "error-pages-middleware@docker"
      traefik.http.routers.error-pages-router.rule: "HostRegexp(`{host:.+}`)"
      traefik.http.routers.error-pages-router.tls: "true"
      traefik.http.routers.error-pages-router.priority: "10"
      traefik.http.services.error-pages-service.loadbalancer.server.port: "8080"
      traefik.http.middlewares.error-pages-middleware.errors.query: "/{status}.html"
      traefik.http.middlewares.error-pages-middleware.errors.service: "error-pages-service@docker"
      traefik.http.middlewares.error-pages-middleware.errors.status: "400-599"
      com.centurylinklabs.watchtower.depends-on: "traefik"
    container_name: error-pages
    environment:
      TZ: "Europe/Berlin"
      TEMPLATE_NAME: "ghost"
    restart: always

whoami:
    image: containous/whoami
    labels:
      traefik.enable: "true"
      traefik.docker.network: "network"
      traefik.http.routers.whoami.rule: "Host(`whoami.DOMAIN`)"
      traefik.http.routers.whoami.middlewares: "error-pages-middleware@docker, chain-oauth@file"
      traefik.http.routers.whoami.entrypoints: "https"
      traefik.http.routers.whoami.tls: "true"
      traefik.http.routers.whoami.tls.certresolver: "letsencrypt"
      traefik.http.services.whoami.loadbalancer.server.port: "80"
    container_name: whoami
    environment:
      TZ: "Europe/Berlin"
    restart: always
```

default.yml (conf.d)
```
http:
  routers:
    traefik:
      entrypoints: ["https"]
      rule: "Host(`traefik.DOMAIN`)"
      middlewares: ["error-pages-middleware@docker", "chain-oauth@file"]
      service: "api@internal"
      tls:
        certresolver: "letsencrypt"
    wildcard-certs-DOMAIN:
      entrypoints: ["http", "https"]
      rule: "Host(`traefik-compose-traefik`)"
      service: "api@internal"
      tls:
        certresolver: "letsencrypt"
        domains:
          - main: "DOMAIN"
            sans: 
              - "*.DOMAIN"
          - main: "2.DOMAIN"
            sans:
              - "*.2.DOMAIN"
  middlewares:
    sslheader:
      headers:
        customrequestheaders:
          X-Forwarded-Proto: "https"
    ratelimit:
      rateLimit:
        average: 100
        burst: 50
    ipwhitelist:
      ipWhiteList:
        sourceRange:
          - "IP/16"
          - "IP/64"
    oauth:
      forwardAuth:
        address: "http://oauth:4181"
        trustForwardHeader: true
        authResponseHeaders: ["X-Forwarded-User"]
    chain-default:
      chain:
        middlewares: ["ratelimit@file, sslheader@file"]
    chain-oauth:
      chain:
        middlewares: ["ratelimit@file, sslheader@file, oauth@file"]
```

There is no error in the log.

**Comment by kevinpollet** [comment]
Hello @philw95,

As said in my previous comment you are hitting https://github.com/traefik/traefik/issues/8885, after a quick look at your configuration file, the following config:

```yaml
    chain-default:
      chain:
        middlewares: ["ratelimit@file, sslheader@file"]
    chain-oauth:
      chain:
        middlewares: ["ratelimit@file, sslheader@file, oauth@file"]
```

should be:

```yaml
    chain-default:
      chain:
        middlewares: ["ratelimit@file", "sslheader@file"]
    chain-oauth:
      chain:
        middlewares: ["ratelimit@file", "sslheader@file", "oauth@file"]
```

**Comment by Tchoupinax** [comment]
Hello @kevinpollet,

Thank for your answer. The issue 8885 could be instead my issue but after fixing the identation and have the list of middlwares like asked, it continues to not to work.

The following is my configuration **after** changes has been made

```yaml

http:
  routers:
    my-awesome-app:
      rule: "Host(`mydomain.com`) && PathPrefix(`/my-awesome-app`)"
      service: my-awesome-app
      tls:
        certresolver: letsencrypt
      middlewares: # I removed the tab before
      - authelia
      - my-awesome-app-replacepathregex
      - my-awesome-app-replacepathregex-home

    my-awesome-app-api:
      rule: "Host(`mydomain.com`) && PathPrefix(`/my-awesome-app-api`)"
      service: my-awesome-app-api
      tls:
        certresolver: letsencrypt
      middlewares:
      - authelia
      - my-awesome-app-api-replacepathregex
      - my-awesome-app-api-replacepathregex-home

    my-awesome-app-api2:
      rule: "Host(`mydomain.com`) && PathPrefix(`/my-awesome-app-dd`)"
      service: my-awesome-app-dd
      tls:
        certresolver: letsencrypt
      middlewares:
      - authelia
      - my-awesome-app-dd-replacepathregex
      - my-awesome-app-dd-replacepathregex-home

  services:
    my-awesome-app:
      loadBalancer:
        servers:
          - url: "http://X.X.X.X:11001"
        passHostHeader: true
    my-awesome-app-api:
      loadBalancer:
        servers:
          - url: "http://X.X.X.X:11000"
        passHostHeader: true
    my-awesome-app-dd:
      loadBalancer:
        servers:
          - url: "http://X.X.X.X:11009"
        passHostHeader: true

  middlewares:
    authelia:
      forwardauth:
        address: https://sso.mydomain.com/api/verify?rd=https://sso.mydomain.com
        trustForwardHeader: true
        authResponseHeaders: Remote-User, Remote-Groups, Remote-Name, Remote-Email
    my-awesome-app-replacepathregex:
      replacePathRegex:
        regex: "^/my-awesome-app/(.*)"
        replacement: "/$1"
    my-awesome-app-replacepathregex-home:
      replacePathRegex:
        regex: "^/my-awesome-app"
        replacement: "/"
    my-awesome-app-api-replacepathregex:
      replacePathRegex:
        regex: "^/my-awesome-app-api/(.*)"
        replacement: "/$1"
    my-awesome-app-api-replacepathregex-home:
      replacePathRegex:
        regex: "^/my-awesome-app-api"
        replacement: "/"
    my-awesome-app-dd-replacepathregex:
      replacePathRegex:
        regex: "^/my-awesome-app-dd/(.*)"
        replacement: "/$1"
    my-awesome-app-dd-replacepathregex-home:
      replacePathRegex:
        regex: "^/my-awesome-app-dd"
        replacement: "/"
```

**Comment by kevinpollet** [comment]
Hey @Tchoupinax,

As said in my previous comment you are hitting https://github.com/traefik/traefik/issues/8885, the configuration of the forwardauth middleware is not correct (see https://doc.traefik.io/traefik/middlewares/http/forwardauth/#authresponseheaders). The `authResponseHeaders` option value is an array, not a string. The configuration should be:

```yaml
  middlewares:
    authelia:
      forwardauth:
        address: https://sso.mydomain.com/api/verify?rd=https://sso.mydomain.com
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
```

Therefore, this issue is a duplicate of https://github.com/traefik/traefik/issues/8885
