### ISSUE TITLE
File provider parsing errors should be contained to the file in question

### ISSUE THREAD

**Issue by NReilingh** [traefik/traefik#8921]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I was experimenting with go templates in dynamic configuration using the file provider. In my test instance of Traefik, I have one dynamic config file for Traefik API/Dashboard routes (`conf/dynamic/traefik_api.yml`), and another that I was using to experiment with template syntax (`conf/dynamic/test_proxy.yml`). I don't know Go, so I was making a lot of mistakes in `test_proxy.yml`'s template syntax that rendered this file unparseable.

By using multiple dynamic config files, I expected that if one file were to enter an invalid state, other config files would still be read and their configuration would still be applied so long as those configurations did not have a dependency on the invalid file. I believe this mirrors the behavior of the Docker provider, since invalid labels on one container do not disrupt the configuration for other containers.

### What did you see instead?

I discovered that when I deployed invalid template syntax in `test_proxy.yml`, my dashboard and API would become unreachable. By turning on insecure dashboard from static config, I was able to see that all of my file configuration (including `traefik_api.yml` was disabled when `test_proxy.yml` failed to parse. Parsing errors could be seen in error log output.

### What version of Traefik are you using?

```
Version:      2.6.3
Codename:     rocamadour
Go version:   go1.17.8
Built:        2022-03-29T13:09:27Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

traefik.yml
```yaml
providers:
  file:
    directory: /etc/traefik/conf/dynamic
```

docker-compose.yml
```yaml
  traefik:
    image: traefik:v2.6
    container_name: traefik
    command: --configFile=/etc/traefik/conf/traefik.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/local/docker/traefik:/etc/traefik/conf:ro
      - traefik_acme:/etc/traefik/acme
```
I am running Traefik as a docker container with deployed with `docker-compose`. The `/etc/traefik/conf` directory in the container is mapped from the host, and the deployment process may deploy files to the host directory without restarting the container.

### If applicable, please paste the log output in DEBUG level

Template parsing errors are usually of the form `Error occurred during watcher callback`, like the following examples:

`time="2022-03-31T02:57:18Z" level=error msg="Error occurred during watcher callback: /etc/traefik/conf/dynamic/test_proxy.yml: unsupported simple value type: invalid" providerName=file`
`time="2022-03-31T03:06:34Z" level=error msg="Error occurred during watcher callback: /etc/traefik/conf/dynamic/test_proxy.yml: template: :19:36: executing \"\" at <.Key>: can't evaluate field Key in type bool" providerName=file`

I asked about this behavior on the community forum to see if there were any initial opinions. My post received one like:

https://community.traefik.io/t/should-a-failure-to-parse-a-single-dynamic-yaml-file-result-in-all-files-being-rejected/13995

Happy to provide a concise and targeted practical repro of the behavior, but wanted to see whether this would indeed be accepted as a bug first.
