### ISSUE TITLE
routers with default tls config cannot found in dashboard

### ISSUE THREAD

**Issue by suntory1** [traefik/traefik#8938]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I define default tls config in traefik static config file `traefik.toml` as below following the [EntryPoints-TLS](https://doc.traefik.io/traefik/routing/entrypoints/#tls) section:

- traefik.toml

```
# Other entrypoints
[entryPoints]
  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]
      certResolver = "leresolver"
      [[entryPoints.websecure.http.tls.domains]]
        main = "example.com"
        sans = ["*.example.com"]

[certificatesResolvers.leresolver.acme]
  email = "username@domain.com"
  storage = "acme.json"
  [certificatesResolvers.leresolver.acme.dnsChallenge]
    provider = "cloudflare"
```

And then, I create two different routers with the same entryPoints `websecure`

- traefik
```
labels:
 - 'traefik.enable=true'
 - 'traefik.docker.network=traefik'
 - 'traefik.http.routers.traefik.entrypoints=websecure'
 - 'traefik.http.routers.traefik.rule=Host(`traefik.example.com`)'
 - 'traefik.http.routers.traefik.middlewares=simpleAuth@file'
 - 'traefik.http.routers.traefik.service=api@internal'
```

- adminer
```
labels:
 - 'traefik.enable=true'
 - 'traefik.docker.network=traefik'
 - 'traefik.http.routers.adminer.entrypoints=websecure'
 - 'traefik.http.routers.adminer.rule=Host(`adminer.example.com`)'
 - 'traefik.http.routers.adminer.middlewares=simpleAuth@file'
 - 'traefik.http.services.adminer.loadbalancer.server.port=8080'
```

### What did you see instead?

- ACME works well which generate an cert for both `example.com` and `*.example.com`
- The website`traefik.example.com` and `adminer.example.com` can be visited normally
- But I cannot found the `adminer` router in the dashboard - HTTP Routers page. The only docker router I can see is `traefik.example.com`. And I try some TCP routers, the result is the same. I can just connect to the router but cannot found it in the dashboard
![screenshot-20220413-212603](https://user-images.githubusercontent.com/88955664/163190604-2646e32d-3b3d-44e6-8a45-09324a117676.png)

### What version of Traefik are you using?

~ > docker run traefik version
Version:      2.5.6
Codename:     brie
Go version:   go1.17.5
Built:        2021-12-22T16:30:52Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```toml
# (paste your configuration here)
[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[log]
  level = "DEBUG"
  format = "common"
  filePath = "/etc/traefik/logs/traefik.log"

[api]
  dashboard = true
  insecure = true
  debug = false

[ping]

[accessLog]
  filePath = "/etc/traefik/logs/access.log"
  bufferingSize = 100

[providers]
  [providers.docker]
    watch = true
    exposedByDefault = false
    endpoint = "unix:///var/run/docker.sock"
    swarmMode = false
    useBindPortIP = false
    network = "traefik"
  [providers.file]
    watch = true
    directory = "/etc/traefik/config"
    debugLogGeneratedTemplate = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

    [entryPoints.websecure.http.tls]
      certResolver = "leresolver"
      [[entryPoints.websecure.http.tls.domains]]
        main = "example.com"
        sans = ["*.example.com"]

  [entryPoints.postgres]
    address = ":5432"
  [entryPoints.mysql]
    address = ":3306"
  [entryPoints.redis]
    address = ":6379"

[certificatesResolvers.leresolver.acme]
  email = "username@example.com"
  storage = "acme.json"
  [certificatesResolvers.leresolver.acme.dnsChallenge]
    provider = "cloudflare"

```

Add more configuration information here.
