### ISSUE TITLE
traefik 2.7 mintls verison tls1.2 can't active http3 and return 421 code

### ISSUE THREAD

**Issue by liweilun1** [traefik/traefik#8955]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

i use traefik 2.7 and set tls minversion is tls1.2 ,preferServerCipherSuites is true , and enable http3 on 443 port 
i enforce the chrome to use http3 on my website with the command line --origin-to-force-quic-on=xxx.cn:443 

### What did you see instead?

i visit the website on chrome and firefox ,they return 421 code and the traefik log show like this
```
time="2022-04-20T13:04:11Z" level=debug msg="http: TLS handshake error from 140.143.66.88:3403: tls: no cipher suite supported by both client and server"
time="2022-04-20T13:04:11Z" level=debug msg="http: TLS handshake error from 140.143.66.88:62391: tls: client offered only unsupported versions: []"
time="2022-04-20T13:04:11Z" level=debug msg="http: TLS handshake error from 140.143.66.88:24822: tls: unsupported SSLv2 handshake received
```

### What version of Traefik are you using?
```
[root@studyo2 ~]# kubectl exec -it traefik-594f8b584c-gbtlq -- traefik version
Version:      2.7.0-rc2
Codename:     epoisses
Go version:   go1.17.8
Built:        2022-03-29T15:07:48Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

i use helm and this yaml install traefik v2.7 in kubernetes 1.23.5
```yaml
image:
  name: traefik
  tag: "v2.7"
deployment:
  kind: Deployment
ingressRoute:
  dashboard:
    enabled: false
experimental:
  http3:
    enabled: true
providers:
  kubernetesCRD:
    allowExternalNameServices: true
logs:
  general:
    level: DEBUG
additionalArguments:
  - "--experimental.http3=true"
  - "--entrypoints.websecure.http3=true"
  - "--entrypoints.websecure.http3.advertisedport=443"
ports:
  web:
    port: 80
  websecure:
    port: 443
    http3: true
service:
  type: ClusterIP
#  externalIPs:
hostNetwork: true
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: false
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0
```

i use this tlsoption in ingressRoute

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: tlsoption
  namespace: default
spec:
  sniStrict: true
  minVersion: VersionTLS12
  maxVersion: VersionTLS13
  preferServerCipherSuites: true
```

### If applicable, please paste the log output in DEBUG level

```
time="2022-04-20T13:04:11Z" level=debug msg="http: TLS handshake error from 140.143.66.88:24823: tls: no cipher suite supported by both client and server"
time="2022-04-20T13:04:11Z" level=debug msg="Serving default certificate for request: \"\""
time="2022-04-20T13:04:11Z" level=debug msg="http: TLS handshake error from 140.143.66.88:24824: EOF"
time="2022-04-20T13:04:11Z" level=debug msg="http: TLS handshake error from 140.143.66.88:3403: tls: no cipher suite supported by both client and server"
time="2022-04-20T13:04:11Z" level=debug msg="http: TLS handshake error from 140.143.66.88:62391: tls: client offered only unsupported versions: []"
time="2022-04-20T13:04:11Z" level=debug msg="http: TLS handshake error from 140.143.66.88:24822: tls: unsupported SSLv2 handshake received"
time="2022-04-20T13:04:11Z" level=debug msg="Serving default certificate for request: \"\""
time="2022-04-20T13:04:11Z" level=debug msg="http: TLS handshake error from 140.143.66.88:8777: tls: no cipher suite supported by both client and server"
time="2022-04-20T13:04:11Z" level=debug msg="Serving default certificate for request: \"\""
time="2022-04-20T13:04:11Z" level=debug msg="http: TLS handshake error from 140.143.66.88:62392: tls: no cipher suite supported by both client and server"
time="2022-04-20T13:04:12Z" level=debug msg="http: TLS handshake error from 140.143.66.88:8778: tls: client offered only unsupported versions: []"
time="2022-04-20T13:04:12Z" level=debug msg="http: TLS handshake error from 106.52.67.103:13253: EOF"
time="2022-04-20T13:04:12Z" level=debug msg="http: TLS handshake error from 193.112.153.14:52839: EOF"
time="2022-04-20T13:04:12Z" level=debug msg="http: TLS handshake error from 42.193.5.156:42025: EOF"
time="2022-04-20T13:04:12Z" level=debug msg="http: TLS handshake error from 106.52.69.80:61637: tls: unsupported SSLv2 handshake received"
time="2022-04-20T13:04:12Z" level=debug msg="http: TLS handshake error from 106.52.11.28:52839: tls: no cipher suite supported by both client and server"
time="2022-04-20T13:04:12Z" level=debug msg="Serving default certificate for request: \"\""
```
