### ISSUE TITLE
Traefik does not return accessControlAllowMethods in header and passes through all methods

### ISSUE THREAD

**Issue by jankohout95** [traefik/traefik#8961]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I created in k8s GKE cluster middleware where i configured  accessControlAllowMethods as this:

<img width="914" alt="image" src="https://user-images.githubusercontent.com/100849407/164505735-1e06aeeb-cd42-4ced-b5f8-2a144a7d8a10.png">

I expected accessControlAllowMethods and accessControlAllowHeaders will be listed in configuration of header returned in response.

### What did you see instead?

Both configuration of accessControlAllowMethods and accessControlAllowHeaders were ignored like this (curl response via postman):

<img width="963" alt="image" src="https://user-images.githubusercontent.com/100849407/164505319-834376b5-cff3-4187-b4a1-13d814d72d68.png">

or this (curl response via curl command in console):

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/100849407/164507519-9b011495-ff4b-401c-ab6a-a2639ba24561.png">

I was trying to even delete accessControlAllowCredentials and see if this configuration will be missing to prove Traefik consumed this configuration and it consumed -> accessControlAllowCredentials with value "true" was missing.

### What version of Traefik are you using?

<img width="349" alt="image" src="https://user-images.githubusercontent.com/100849407/164506310-98be67a3-9730-4ceb-9aad-4132639ef739.png">

### What is your environment & configuration?

```yaml
spec:
  headers:
    customResponseHeaders:
      Server: ""
      X-Envoy-Decorator-Operation: ""
      X-Envoy-Peer-Metadata: ""
      X-Envoy-Peer-Metadata-Id: ""
      X-Envoy-Upstream-Service-Time: ""
      Permissions-Policy: "geolocation=(self), microphone=(), camera=(), fullscreen=*"
    sslRedirect: true
    forceSTSHeader: true
    stsSeconds: 63072000
    contentTypeNosniff: true
    browserXssFilter: true
    accessControlAllowCredentials: true
    accessControlAllowMethods: [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
    accessControlAllowHeaders: [ "Accept", "Authorization", "Content-Type", "Locatee-Smart-Signage-Token", "Origin" ]
    
```
