### ISSUE TITLE
error-page middleware remove all headers

### ISSUE THREAD

**Issue by jfbelisle** [traefik/traefik#8963]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Using Traefik 2.6.3 with a service error-pages defined in my traefik docker-compose file

This service is an Apache server which does a proxypass to error pages hosted on another domain, but locally.

`RewriteRule ^/404 https://mydomain/error-pages/erreur404/ [P]`

My application is using this error-page middleware to show different error pages.

I should see the error page displayed properly with the headers being fowarded to the client (working under Traefik v1)

But the headers a not transfered to the client.

### What did you see instead?

The rewrite is functionnal but since there is no content-type header, the html is displayed as text/plain
![image](https://user-images.githubusercontent.com/586569/164725019-63652134-1f0b-4e7d-a514-7579ebd3d1af.png)

The error-page is working under traefik v1

### What version of Traefik are you using?

Version:      2.6.3
Codename:     rocamadour
Go version:   go1.17.8
Built:        2022-03-29T13:09:27Z
OS/Arch:      linux/arm64

### What is your environment & configuration?

```yaml
version: "3.8"
 
services:
 
  proxy:
   
    image: traefik
     
    command:
      - --providers.docker=true
      - --providers.docker.swarmmode=true
      - --providers.docker.network=traefik-net
      - --providers.file.filename=/traefik-certs.yml
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entryPoint.to=websecure
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls.domains[0].main=domain.ca
      - --entrypoints.https.http.tls.domains[0].sans=*.domain.ca
      - --providers.docker.exposedbydefault=false
      - --api.dashboard=true
      - --api.insecure=true
      - --accesslog=true
       
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
       
    secrets:
      - myhost.crt
      - myhost.key
       
    configs:
      - traefik-certs.yml
       
    networks:
      - traefik-net
       
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
         
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 15
 
 
  error-pages:
 
    image: my-error-pages
 
    networks:
      - traefik-net
 
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: "traefik-net"
        traefik.http.routers.error-pages.rule: "HostRegexp(`{host:.+}`)"
        traefik.http.routers.error-pages.service: "error-pages"
        traefik.http.routers.error-pages.priority: 1
        traefik.http.middlewares.return503_mw.replacepath.path: "/return503"
        traefik.http.middlewares.error-pages_mw.errors.status: "400-599"
        traefik.http.middlewares.error-pages_mw.errors.service: "error-pages"
        traefik.http.middlewares.error-pages_mw.errors.query: "/{status}"
        traefik.http.routers.error-pages.middlewares: error-pages_mw
        traefik.http.services.error-pages.loadbalancer.server.port: "80"
        traefik.http.services.error-pages.loadbalancer.passHostHeader: "true"
 
      restart_policy:
        condition: any
        max_attempts: 5
 
networks:
  traefik-net:
    driver: overlay
    external: true
 
configs:
  traefik-certs.yml:
    external: true
 
secrets:
  myhost.crt:
    external: true
  myhost.key:
    external: true
```

This is the labels of my app service using the middleware

```yaml
labels:
        - "traefik.docker.network=traefik-net"
        - "traefik.enable=true"
        - "traefik.http.routers.${STACK_NAME}monacces.rule=Host(`${APP_HOSTNAME}`)"
        - "traefik.http.routers.${STACK_NAME}monacces.middlewares=error-pages_mw"
        - "traefik.http.services.${STACK_NAME}monacces.loadbalancer.server.port=80"
```

Add more configuration information here.
