### ISSUE TITLE
environment variable TRAEFIK_ENTRYPOINTS_<NAME>_FORWARDEDHEADERS_TRUSTEDIPS gets ignored

### ISSUE THREAD

**Issue by JaneJeon** [traefik/traefik#8964]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm trying to "trust" forwarded headers from a proxy whose IP I know. However, setting `TRAEFIK_ENTRYPOINTS_<NAME>_FORWARDEDHEADERS_TRUSTEDIPS` environment variable does not work as stated in the documentation: https://doc.traefik.io/traefik/reference/static-configuration/env/

Specifically, I am trying to set this specific config: https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers via the environment variable (and I've tried it with the CLI as well, no luck).

When I set it to a list of IP ranges that I _know_ is being forwarded to traefik from, I expect traefik to trust the forwarded headers. And in fact, if I do it with static file configuration, it _does_ work (so I know it's _not_ some misconfiguration with the IP ranges) as expected.

### What did you see instead?

It still doesn't trust the X-Forwarded-* headers despite the request being sent from one of the ranges.

Again, it _only_ doesn't work when I'm trying to do my entrypoint configuration in static files and override only the `forwardedHeaders.trustedIPs` via CLI/environment variable (_as documented_ - again, I did not screw up the configuration).

### What version of Traefik are you using?

v2.6.3

### What is your environment & configuration?

The relevant part of the static configuration file:

```yaml
entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true

  https:
    address: :443
```

In `docker-compose.yml`:

```yaml
version: '3'

services:
  traefik:
    image: traefik:v2.6.3
    container_name: traefik
    command:
      # doesn't work:
      # --entryPoints.https.forwardedHeaders.trustedIPs=$iprange1,$iprange2,...
    restart: unless-stopped
    networks:
      - public
    ports:
      - 80:80
      - 443:443
    environment:
      # this doesn't work:
      # TRAEFIK_ENTRYPOINTS_HTTPS_FORWARDEDHEADERS_TRUSTEDIPS: $iprange1,$iprange2,...
      # also doesn't work:
      # TRAEFIK_ENTRYPOINTS_https_FORWARDEDHEADERS_TRUSTEDIPS: $iprange1,$iprange2,...
```

And no, I'm not "turning on" all 3 styles of config (CLI, ENV uppercase, ENV with the entrypoint name "as-is"); only 1 at a time. Again, I'm not screwing up the config.

Please, I've spent 10 hours on this...
