### ISSUE TITLE
Cannot find entryPoint for Gateway

### ISSUE THREAD

**Issue by barnettZQG** [traefik/traefik#8974]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I try to use Gateway API in the traefik, The HTTPRoute is working, but the Gateway+TCPRoute is not working.

The Gateway spec:
```
spec:
  gatewayClassName: traefik
  listeners:
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: Same
    name: listener-tcp-1000
    port: 1000
    protocol: TCP
status:
  conditions:
  - lastTransitionTime: "2022-04-28T04:19:11Z"
    message: All Listeners must be valid
    reason: ListenersNotValid
    status: "False"
    type: Ready
```

### What did you see instead?

```
time="2022-04-28T05:41:13Z" level=error msg="an error occurred while creating gateway status: 1 error occurred:\n\t* Cannot find entryPoint for Gateway: no matching entryPoint for port 1000 and protocol \"TCP\"\n\n" providerName=kubernetesgateway gateway=test-info-123-gateway-tcp-1000 namespace=default
```

### What version of Traefik are you using?

v2.6.3

### What is your environment & configuration?

```yaml
- --global.checknewversion
    - --global.sendanonymoususage
    - --entrypoints.metrics.address=:9100/tcp
    - --entrypoints.traefik.address=:9000/tcp
    - --entrypoints.web.address=:8000/tcp
    - --entrypoints.websecure.address=:8443/tcp
    - --api.dashboard=true
    - --ping=true
    - --metrics.prometheus=true
    - --metrics.prometheus.entrypoint=metrics
    - --providers.kubernetescrd
    - --providers.kubernetesingress
    - --providers.kubernetesgateway
    - --experimental.kubernetesgateway
    - --accesslog=true
    - --accesslog.fields.defaultmode=keep
    - --accesslog.fields.headers.defaultmode=drop
```

Add more configuration information here.

Maybe I must config the entrypoints?
