### ISSUE TITLE
Allow !HostSNI in TCP routers

### ISSUE THREAD

**Issue by neongreen** [traefik/traefik#8975]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I have a traefik instance that serves my site (say "product.com") as well as a bunch of arbitrary custom domains that Traefik doesn't know about and that can't be enumerated. For those custom domains, my backend does SSL termination by itself.

So I wanted to have a dynamic config like this:

```yaml
http:
  services: ...
  routers:
    app:
      rule: 'Host(`product.com`)'
      service: 'frontend'
      tls:
        certResolver: 'lets-encrypt'

tcp:
  services: ...
  routers:
    customDomains:
      rule: '!HostSNI(`product.com`)'
      service: 'backend'
      tls:
        passthrough: true
```

However, I get told that `!HostSNI` is not a valid rule.

How can I achieve this in Traefik?

---

_keywords: negate sni, negate hostsni_
