### ISSUE TITLE
Incorrect loadbalance docker swarm replicas if count of replicas is even

### ISSUE THREAD

**Issue by man4j** [traefik/traefik#8977]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I use docker provider with swarm mode. If i set even replicas count, f.e. 2,4,6... traefik does not use part of the replicas.
If i set odd replicas count (3,5,7...) traefik works correctly.

### What did you see instead?

Correct roundrobin balancing

### What version of Traefik are you using?

2.6, 2.7-rc2

### What is your environment & configuration?

my docker swarm service config:

        "Name": "traefik-whoami-traefik-test",
        "Labels": {
            "traefik.http.middlewares.my-basic-auth.basicAuth.users": "admin:$apr1$9O6lRT2m$y46NNFXGGzw2SpjtsQw3Z1",
            "traefik.http.middlewares.my-buffering.buffering.maxRequestBodyBytes": "20971520",
            "traefik.http.middlewares.my-buffering.buffering.maxResponseBodyBytes": "20971520",
            "traefik.http.middlewares.my-buffering.buffering.memRequestBodyBytes": "20971520",
            "traefik.http.middlewares.my-buffering.buffering.memResponseBodyBytes": "20971520",
            "traefik.http.routers.my-default-http-router.entrypoints": "http",
            "traefik.http.routers.my-default-http-router.middlewares": "my-basic-auth,my-buffering",
            "traefik.http.routers.my-default-http-router.service": "my-service",
            "traefik.http.services.my-service.loadbalancer.healthcheck.interval": "10s",
            "traefik.http.services.my-service.loadbalancer.healthcheck.path": "/foo",
            "traefik.http.services.my-service.loadbalancer.healthcheck.timeout": "3s",
            "traefik.http.services.my-service.loadbalancer.server.port": "80",
            "traefik.http.services.my-service.loadbalancer.sticky.cookie": "false"
        }
my traefik config:

exec /entrypoint.sh traefik $@
--entrypoints.http.address=:${PORT}
--entrypoints.https.address=:${HTTPS_PORT}
--entrypoints.traefik.address=:${DASHBOARD_PORT}
--api.dashboard=true
--metrics.prometheus=true
--providers.docker.swarmMode=true
--providers.docker.endpoint=tcp://docker-socket-proxy-${NAMESPACE}:2375
--providers.docker.network=clustercontrol-net
--providers.docker.defaultRule="PathPrefix("/")"
--providers.docker.constraints="Label("namespace", "${NAMESPACE}")"
--providers.file.filename=conf.yml
--tracing=${ENABLE_TRACING}
--tracing.jaeger=${ENABLE_TRACING}
--tracing.jaeger.disableAttemptReconnecting=false
--tracing.jaeger.collector.endpoint=${TRACING_URL}
--certificatesresolvers.my-cert-resolver.acme.tlschallenge=true
--certificatesresolvers.my-cert-resolver.acme.storage="/etc/traefik/acme.json"
--certificatesresolvers.my-cert-resolver.acme.email=${ACME_EMAIL}

**Comment by jakubhajek** [comment]
Hello @man4j 

Thank you for using Traefik. 

Would you please explain in detail what layer exactly you experience an issue with the Round Robin Load Balancing algorithm? 

1. Traefik works as a load balancer and will be able to route requests to your backend applications. Technically speaking if you scale up your backend to have multiple instances, Traefik will distribute incoming requests using RR algorithm. Here is the basic diagram:

`Traefik -> Multiple Replicas of the backend`

If you experience the issue in that scenario we have definitely to investigate that in detail, so would you please send us more information and provide a reproducible use case. 

2. However, I understood that you scale Traefik to have more replicas of the load balancer itself and you noticed that requests are not correctly distributed across available Traefik instances. 

`Multiple Traefik Instances -> Backend`

If this is the case, it is related to Swarm configuration and its built-it routing mesh that is described [here](https://docs.docker.com/engine/swarm/ingress/).  As you can see it is related to the way how the ports are exposed and how many nodes the cluster consists of.

Can you please indicate which issue from those two that I described you are experiencing?

Thank you for your feedback,

**Comment by man4j** [comment]
I create a simple test. 

My docker-compose file:

**docker-compose.yml**

```
version: '3'

services:
  reverse-proxy:
    image: traefik:v2.6
    command: --entrypoints.http.address=:80 --api.dashboard=true --providers.docker.swarmMode=true --api.insecure=true --providers.docker.defaultRule="PathPrefix(\"/\")" --providers.docker.constraints="Label(\"namespace\", \"test\")"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: traefik/whoami
    deploy:
      labels:
        - "namespace=test"
        - "traefik.http.routers.my-default-http-router.entrypoints=http"
        - "traefik.http.routers.my-default-http-router.service=my-service"
        - "traefik.http.services.my-service.loadbalancer.server.port=80"
```

I deploy this stack by command: **docker stack deploy --compose-file docker-compose.yml traefik**


And after I scale whoami service: 
docker service scale traefik_whoami=**2**
traefik works incorrectly (dont see second replica).

if i scale: 
docker service scale traefik_whoami=**3**
traefik works correctly

if i scale:
docker service scale traefik_whoami=**4**
traefik works incorrectly (dont see replicas).

if i scale:
docker service scale traefik_whoami=**5**
all works

if i scale:
docker service scale traefik_whoami=**6**
dont work

**7**
all works

**8**
dont work

etc...

In admin console traefik always see all replicas correctly. But problem in RR algorithm. If i try to navigate my browser to 127.0.0.1 I see that (and periodically CTRL+R).
