### ISSUE TITLE
Router priority is not shown in dashboard

### ISSUE THREAD

**Issue by aleksvujic** [traefik/traefik#8988]
Let's say that you define a router in `traefik.yml` like this:

```yml
http:
  routers:
    catch-all:
      rule: "HostRegexp(`{host:(blog|support)(-(dev|test))?\\.company\\.(local|com)}`)"
      priority: 1
      tls: {}
      service: "noop@internal"
```

Once you open the dashboard, priority isn't shown anywhere in router details:

![image](https://user-images.githubusercontent.com/17112542/160404637-3d1ae312-fed9-4357-97d0-08ae73118792.png)

Can priority info be added to router details?
