### ISSUE TITLE
Allow overriding of acme-http@internal router

### ISSUE THREAD

**Issue by Kirens** [traefik/traefik#8992]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

A certificate resolver using `acme.HTTPChallenge` currently requires an `entryPoint`. It seems this is to provide a router for `PathPrefix("/.well-known/acme-challenge/")`. For obvious reasons, this router has maximum priority. Being able to override this could however be useful (e.g. sending acme challenges to a downstream web server).

## Proposal
I suppose there are two ways to enable this:
1. Add a configuration option for router priority.
    ```toml
    [certificatesResolvers.myresolver.acme]
      email = "your-email@example.com"
      storage = "acme.json"
      [certificatesResolvers.myresolver.acme.httpChallenge]
        # used during the challenge
        entryPoint = "web"
        routerPriority = 1_000_000
    ```
2. Letting the user define their own router by not assigning an entryPoint.
    ```toml
    [certificatesResolvers.myresolver.acme]
      email = "your-email@example.com"
      storage = "acme.json"
      [certificatesResolvers.myresolver.acme.httpChallenge]
    ```

Alternative 2 would preferable to me as it enables even more customized handling of the router. It also implies that the responsibility of the router is on the end-user if this breaks acme authentication.

As far as I can tell, an entryPoint isn't required for the _acme-http@internal_ service to work. Assigning a non-existent entryPoint seems to work, which also suggests that to be the case.
https://github.com/traefik/traefik/blob/a49b537d9c3ddc96fb06394d7f351ed68ee13c74/pkg/provider/acme/provider.go#L312-L319

**Comment by kevinpollet** [comment]
Hello @Kirens,

Thanks for your interest in Traefik,

When an ACME resolver is configured without the `httpChallenge` option, no router for `PathPrefix("/.well-known/acme-challenge/")` is created. Therefore, if you want your own downstream webserver to handle the HTTP challenge, all you have to do is not enable the `httpChallenge` and set up your own `PathPrefix("/.well-known/acme-challenge/")` router.

**Comment by Kirens** [comment]
Thanks for the suggestion, although it doesn't seem to be a solution.
To clarify: I'd like _some, but not all_ hosts of an entryPoint to use the internal acme provider. If the resolver is specified without any challenge option this seems to fail by the following check:

https://github.com/traefik/traefik/blob/a49b537d9c3ddc96fb06394d7f351ed68ee13c74/pkg/provider/acme/provider.go#L277-L281

**Comment by tekook** [comment]
Has anybody ever found a workaround?
I'm currently trying to redirect the acme-challenge for one host to another server, so the server can generate its own certificates.
The priority of the acme-http@internal router seems to be max-int, so it will always get the request.

**Comment by Kirens** [comment]
I've set the entrypoint of httpChallange to something non-existent, which seems to disable the router without disabling the resolver, and then added a manual replacement for the router. IE:
```toml
[certificatesResolvers.letsencrypt.acme]
  storage = "/acme/letsencrypt.json"
  # NB: We're reimplementing this router in in the dynamic config
  httpChallenge.entryPoint = "pretend-entrypoint-for-httpChallenge"
```
```toml
### IMPORTANT! ###
# This router exist to change priority of acme-challenges
# If it is dissabled HTTPS will stop working
[http.routers."acme-http"]
  rule = 'PathPrefix("/.well-known/acme-challenge/")'
  service = "acme-http@internal"
  entrypoints = [ "web" ]
  priority = 100_000

```

**Comment by Links2004** [comment]
some technical question, why does the `acme-http@internal` need the full `PathPrefix("/.well-known/acme-challenge/")`?

I think a better solution for this problem is that traefik generates a specific rule for the ACME request that is currently processed by it and not a "Wildcard" catch all acme-challenges. This for example is how cert manager in k8s handles it.

# why is this helpful?
for example in the following use cases (where enabling acme http currently beaks everything)
- if you put traefik as load balance before a legacy application that does it own acme handling via HTTP-01
- if you have multiple traefik in a row (yes this can happen in complexes setups)

**Comment by kavolorn** [comment]
> I've set the entrypoint of httpChallenge to something non-existent, which seems to disable the router without disabling the resolver, and then added a manual replacement for the router. IE:
> 
> ```toml
> [certificatesResolvers.letsencrypt.acme]
>   storage = "/acme/letsencrypt.json"
>   # NB: We're reimplementing this router in in the dynamic config
>   httpChallenge.entryPoint = "pretend-entrypoint-for-httpChallenge"
> ```
> 
> ```toml
> ### IMPORTANT! ###
> # This router exist to change priority of acme-challenges
> # If it is dissabled HTTPS will stop working
> [http.routers."acme-http"]
>   rule = 'PathPrefix("/.well-known/acme-challenge/")'
>   service = "acme-http@internal"
>   entrypoints = [ "web" ]
>   priority = 100_000
> ```

I disabled default router as you suggested in static config:

```yaml
entryPoints:
  http:
    address: :80
  http-non-existent:
    address: :3080

certificatesResolvers:
  le-prod:
    acme:
      httpChallenge:
        entryPoint: http-non-existent
```

And then I created 2 rules with my own priority in dynamic config:

```yaml
http:
  routers:
    klaim-brainstaff-http:
      entrypoints:
        - http
      rule: Host(`example.com`)
      service: example-com-service
      priority: 1001
    acme-http:
      entrypoints:
        - http
      rule: PathPrefix(`/.well-known/acme-challenge/`)
      service: acme-http@internal
      priority: 1000
```

**Comment by Letme** [comment]
@kavolorn Thanks, this has helped me a lot.

I setup traefik through Helm and only needed to place acme to listen to noweb port, and then manually created IngressRoutes by hand as you suggested and now my mail server (not on kubernetes but still on local network) can get certificates from domains that I want, while all other domains can also get them automatically through Traefik.

**Comment by everyx** [comment]
Another workaround, set router priority to a value greater than `math.MaxInt32`  2147483647, for example 2147483649

**Comment by csthiang** [comment]
@kavolorn how can I do this in docker compose using labels? Especially acme-http part in the dynamic config

**Comment by emericv** [comment]
Great @kavolorn, thanks for this solution, I will don't have to make an ugly hack with nginx to bypass this limitation...

Hi @kevinpollet, nice to see you again here after these years! :)
In fact, I have several use cases where I have also two ranks of proxies :
* one on the host with a public IPv4&6
* one on each VM with a public IPv6 and private IPv4 (the IPv4 become expensive)
For the TCP over IPv6 the access is direct to the VM, but for TCP over IPv4 I have added a TCP route on the host side Traefik. This solution permits for each VM to manage its own certificates.

In this case, in my opinion, the default acme-http@internal rule should be dynamic and must match to "/.well-known/acme-challenge/" path prefix only for hosts (SNI) where the certificates are managed directly from this instance.

**Comment by racsnet** [comment]
Thanks for this workaround @kavolorn 
I try to configure this in my docker-compose.yml but get this error:
`level=error msg="unknown internal service acme-http@internal" routerName=acme-http@docker entryPointName=web`

did anyone managed to implement this workaround?

docker-compose.yml:
```

version: '3'
services:
  reverse-proxy:
    image: traefik:v2.2
    environment:
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_ACCESSLOG=true
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:443
      - TRAEFIK_ENTRYPOINTS_MQTTS_ADDRESS=:8883
      - TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_EMAIL=hostmaster@example.com
      - TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_STORAGE=/letsencrypt/acme.json
      - TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_HTTPCHALLENGE=true
      - TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_HTTPCHALLENGE_ENTRYPOINT=pretend-entrypoint-for-httpChallenge
    ports:
      - "80:80"
      - "443:443"
      - "8883:8883"
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.acme-http.rule=PathPrefix(/.well-known/acme-challenge/)"
      - "traefik.http.routers.acme-http.service=acme-http@internal"
      - "traefik.http.routers.acme-http.entrypoints=web"
      - "traefik.http.routers.acme-http.priority=100"
    restart: always
    container_name: traefik

networks:
  public:
    external: true
```
