### ISSUE TITLE
The BasicAuth system returns a 401 error when correct

### ISSUE THREAD

**Issue by QuentinDouarre** [traefik/traefik#8993]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

When I use a basic auth middleware and the user-password pair is not correct, I get the popup again. It's normal
When I enter the correct user and password couple, I would like to arrive on my landing page

### What did you see instead?

When I enter the correct user and password couple, a JSON is sent back to me with a 401 code:
`{"message":"invalid username or password"}`

### What version of Traefik are you using?

v2.6.6-windowsservercore-1809

### What is your environment & configuration?

In my docker-compose.yml
```yaml
  grafana:
    image: grafana:latest
    isolation: 'hyperv'
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.grafana.loadbalancer.server.port=3000
        - traefik.http.routers.grafana.entrypoints=web
        - traefik.http.routers.grafana.service=grafana
        - traefik.http.routers.grafana.rule=Path(`/grafana`) || PathPrefix(`/grafana/`)
        - "traefik.http.routers.grafana.middlewares=grafana-stripprefix,grafana-compress,test-auth"
        - traefik.http.middlewares.grafana-stripprefix.stripprefix.prefixes=/grafana
        - traefik.http.middlewares.grafana-compress.compress=true
        - "traefik.http.middlewares.test-auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/,test2:$$apr1$$d9hr9HBB$$4HxwgUir3HP4EsggP/QNo0"
```

Add more configuration information here.
