### ISSUE TITLE
Auto Redirect Host Problem.

### ISSUE THREAD

**Issue by ThankRain** [traefik/traefik#8996]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I want to match some host that did not bind on my server or some virtual host, such as `example.com`. And I write the rule 
```
Host(`example.com`)
``` 
but when I request it with customize Host example.com , it just simply return 404.
Furthermore, I replace this host to a reachable host, such as `google.com` ,then I found that it redirect me to the `google.com` instead of the service that match the virtual host.
I'm sure I have closed the http->https redirect middlewares.

### What did you see instead?

 I found that it redirect me to the virtual host instead of the service that match the virtual host.

### What version of Traefik are you using?

2.6.3

### What is your environment & configuration?

```yaml
traefik:
        image: traefik
        container_name: traefik
        command:
            - "--api.insecure=true"
            - "--accesslog=true"
            - "--providers.docker"
            - "--api.dashboard=true"
            - "--entrypoints.http.address=:80"
            - "--entrypoints.https.address=:443"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--certificatesresolvers.mresolver.acme.httpchallenge=true"
            - "--certificatesresolvers.mresolver.acme.httpchallenge.entrypoint=http"
            - "--certificatesresolvers.mresolver.acme.email=<my-email>"
            - "--certificatesresolvers.mresolver.acme.storage=/letsencrypt/acme.json"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik.rule=Host(`t.<my-domain>`)"
            - "traefik.http.routers.traefik.tls.certresolver=mresolver"
            - "traefik.http.routers.traefik.entrypoints=https"
            - "traefik.http.routers.traefik.tls=true"
            - "traefik.http.routers.http-catchall.entrypoints=https"
            - "traefik.http.services.traefik.loadbalancer.server.port=8080"
            #- "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
            #- "traefik.http.routers.http-catchall.entrypoints=http"
            #- "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
            #- "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"       
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./letsencrypt:/letsencrypt
        networks:
            - nets
```

Add more configuration information here.
