### ISSUE TITLE
Buffering middleware responds with 500 when request is canceled amidst executing

### ISSUE THREAD

**Issue by SivkovSavely** [traefik/traefik#9009]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

1. Make a request to the K8S Traefik IngressRoute with buffering middleware
2. Cancel the request before it's finished

I expected Traefik to not do anything or to allow to change the error code.

If you can't reproduce the bug, try to set the Content-Length explicitly to some big value, e.g. 10000. This way the response will be active for some time (for me it was 10 minutes) before it fails with 504 gateway timeout. You should not wait for the timeout, cancel the request right away. This way the response will be 500 for whoever did the request.

Approximate CURL query for reproduction:
```
curl --location --request POST 'https://{CLUSTER OUTER IP OR DOMAIN NAME}/{INGRESS ROUTE}' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'something=blahblahblah'
```
(If you cannot reproduce the bug try adding the `--header 'Content-Length: 10000'` option)

### What did you see instead?

I saw 500 response code and `vulcand/oxy/buffer: error when reading request body, err: unexpected EOF` error message in the traefik logs

### What version of Traefik are you using?

2.6.0

### What is your environment & configuration?

```yaml
entryPoints:
- websecure
routes:
- kind: Rule
  match: /* redacted, confidential, does not play a role in the bug report. it will be different if you try to reproduce the issue anyways */
  middlewares:
  - name: security-headers
    namespace: traefik-api
  - name: app-buffering
    namespace: traefik-api
  priority: 42
  services:
  - kind: Service
    name: app-services
    namespace: app
    port: 8080
tls:
  options:
    name: bgrade-tls-options
    namespace: traefik-api
```
(app is replaced with the actual app name, redacted for itsec purposes)

buffering middleware:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: app-buffering
spec:
  buffering:
    maxRequestBodyBytes: 20000
```

The application is running in Kubernetes
The framework used is ASP.NET Core with .NET 6.0 runtime
Also we use this buffering middleware: https://github.com/vulcand/oxy/tree/master/buffer (if the issue should be created there I'm sorry, I will also create it there because I don't know where it belongs to and who is responsible for this bug)
