### ISSUE TITLE
Allow multiple listeners on same port in Gateway API provider

### ISSUE THREAD

**Issue by TeoGoddet** [traefik/traefik#9026]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Concern K8SGatewayAPI provider: 
Sould be possible to have multiple HTTP/HTTPS listeners on the same port (the goal of a reverse proxy :)
Now this is forbidden by this line : https://github.com/traefik/traefik/blob/1048348ae65497feb4a05e090f0ac910586c7996/pkg/provider/kubernetes/gateway/kubernetes.go#L343

Am I right ?

**Comment by TeoGoddet** [comment]
The config I would like to be working : 
```
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    hostname: hello.agepoly.ch
    name: hello.agepoly.ch
    port: 8443
    protocol: HTTPS
  - allowedRoutes:
      namespaces:
        from: All
    hostname: agevote-api.agepoly.ch
    name: agevote-api.agepoly.ch
    port: 8443
    protocol: HTTPS
```
