### ISSUE TITLE
 configure maintenance page in Traefik v1.7.33

### ISSUE THREAD

**Issue by rajakumarbabu** [traefik/traefik#9042]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We are using Traefik V1.7.33 as Azure ServiceFabric Application, which will perform traffic redirection to the windows containers in VMSS. We need to redirect traffic to the maintenance web page when there is an container image refresh

### What did you see instead?

TOML configuration change didn't help.

![image](https://user-images.githubusercontent.com/57990039/169949329-1878cae4-9318-46f6-8ba4-17d143f749ee.png)

![image](https://user-images.githubusercontent.com/57990039/169949395-7d24fbd6-73b4-46f2-b2b5-53a401de4cb8.png)

### What version of Traefik are you using?

V1.7.33

### What is your environment & configuration?

```yaml

[http.middlewares]
  [http.middlewares.test-errorpage.errors]
    status = ["500-599"]
    service = "serviceError"
    query = "/{status}.html"


[frontends]
  [frontends.website]
  backend = "website"
  [frontends.website.errors]
    [frontends.website.errors.network]
    status = ["500-599"]
    backend = "error"
    query = "/{status}.html"
  [frontends.website.routes.website]
  rule = "Host: website.mydomain.com"
```

Add more configuration information here.

**Comment by rtribotte** [comment]
Hello @rajakumarbabu,

I am going close this as we do not support version one anymore.
Thus, as it seems that you are requesting help with a configuration issue, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik v1 section](https://community.traefik.io/c/traefik/traefik-v1).

**Comment by rajakumarbabu** [comment]
The latest Traefik version will not support Azure Service Fabric, Due to this we are forced to use V1.7.33. Requesting you to re-open this request

**Comment by rtribotte** [comment]
@rajakumarbabu Did you try the Service Fabric provider plugin for the v2?
Please take a look at https://github.com/microsoft/service-fabric-traefik.

**Comment by rajakumarbabu** [comment]
I am trying to install Service Fabric plugin for v2, stuck with dynamic redirection.  Our applications are configured behind Azure application gateway.  All public traffic will reach application gateway, application gateway will redirect all https request to traefik, based on the request traefik will server.  These requests are dynamic.  Would like to know how to configure dynamic redirection in Traefik V2.

**Comment by rtribotte** [comment]
Hello @rajakumarbabu,

Glad to hear that you tried the v2 with the new Service fabric plugin.
Regarding redirections, it is covered in our migration guide, from v1 to v2: https://doc.traefik.io/traefik/migration/v1-to-v2/#http-to-https-redirection-is-now-configured-on-routers.
To request help with configuration issues, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik v1 section](https://community.traefik.io/c/traefik/traefik-v1).

**Comment by rajakumarbabu** [comment]
After Traefik 2.6.1 installation, tried with [PingerService](https://github.com/microsoft/service-fabric-traefik) application, received "**Service Unavailable**" error.  Sharing YAML and manifest for reference.  Would like to know any additional configuration changes required.

**Traefik.YAML**
```
global:
  checkNewVersion: false
  sendAnonymousUsage: false 
defaultEntryPoints : "web"
entryPoints:
  web:
    address: :443
api:
  dashboard: true
log:
  level: DEBUG
  filePath: "log/traefik.log"
  format: json
providers:
  file:
    directory: D:\SvcFab\_App\TraefikType_App568\work
    watch: true
```
**dyn.yaml**
```
providers:
  file:
    directory: C:\SvcFab\_App\TraefikType_App\work
    watch: true
tls:
  certificates:
    - certFile: "./certs/fortraefik.crt"
      keyFile: "./certs/fortraefik.key"
```
**PingerService Servicemanifest.xml**
```
<Label Key="traefik.http.PingerEndpoint0">true</Label>
            <Label Key="traefik.http.PingerEndpoint0.router.rule">PathPrefix(`/pinger`)</Label>
            <Label Key="traefik.http.PingerEndpoint0.middlewares.1.stripPrefix.prefixes">/pinger</Label> 
            <Label Key="traefik.http.PingerEndpoint0.router.tls.options">foobar</Label> 
			<Label Key="traefik.http.PingerEndpoint0.service.loadbalancer.passhostheader">true</Label>
            <Label Key="traefik.http.PingerEndpoint0.service.loadbalancer.healthcheck.path">/</Label>
            <Label Key="traefik.http.PingerEndpoint0.service.loadbalancer.healthcheck.interval">10s</Label>
            <Label Key="traefik.http.PingerEndpoint0.service.loadbalancer.healthcheck.scheme">web</Label>
```
