### ISSUE TITLE
[2.7.0] Migrating from annotation kubernetes.io/ingress.class to spec.ingressClassName breaks the ingress

### ISSUE THREAD

**Issue by Richard87** [traefik/traefik#9049]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Tried migrating a ingress from using the deprecated `kubernetes.io/ingress.class: traefik1` to `spec.ingressClassName: traefik1`.

First I tried with Traefik 2.5.6, when that failed, I upgreaded to v2.7.0, with the same failure.

If I keep open the admin window while doing the change, my ingress dissapear a few seconds after removing the annotation, but reappears a few seconds adding the annotation again.

### What did you see instead?

No ingress found

### What version of Traefik are you using?

version 2.7.0 in kuberentes

### What is your environment & configuration?

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: dns-issuer
    kubernetes.io/ingress.class: traefik1
    traefik.ingress.kubernetes.io/redirect-entry-point: https
  creationTimestamp: "2020-05-07T12:14:26Z"
  generation: 6
  name: decision
  namespace: domain-decision
  resourceVersion: "650244583"
  uid: 4b21783e-905c-11ea-8e78-42010aa600f5
spec:
  rules:
  - host: decision.domain.no
    http:
      paths:
      - backend:
          service:
            name: decision
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - decision.domain.no
    secretName: decision-domain-cert
status:
  loadBalancer: {}
```

Traefik deployment yaml:
```yaml
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-01-03T14:44:25Z"
      creationTimestamp: null
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik
    spec:
      containers:
      - args:
        - --api.insecure
        - --api.dashboard=true
        - --log=true
        - --log.level=INFO
        - --accesslog=true
        - --accesslog.filepath=/dev/stdout
        - --accesslog.format=json
        - --entrypoints.http.Address=:80
        - --entrypoints.http.http.redirections.entryPoint.to=https
        - --entrypoints.http.http.redirections.entryPoint.scheme=https
        - --entrypoints.https.Address=:443
        - --entrypoints.https.http.tls=true
        - --providers.kubernetesingress=true
        - --providers.kubernetesingress.ingressclass=traefik1
        - --providers.kubernetesingress.namespaces=default,domain,traefik1,linkerd,domain-video,domain-decision
        image: traefik:v2.7.0
        imagePullPolicy: Always
        name: traefik-ingress-lb
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 8080
          name: admin
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: traefik-ingress-controller
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
```

### If applicable, please paste the log output in DEBUG level

When I remove the annotation and insert ingressClassName, no log-messages occure.
If I add the annotation, no log messages
When I remove the ingressClassName, so only the annotation remains this happens:

```
time="2022-05-27T10:56:25Z" level=debug msg="Configuration received: {...}" providerName=kubernetes
time="2022-05-27T10:56:25Z" level=debug msg="No entryPoint defined for this router, using the default one(s) instead: [http https]" routerName=decision-domain-decision-decision-domain-no
time="2022-05-27T10:56:25Z" level=debug msg="Adding certificate for domain(s) decision.domain.no"
time="2022-05-27T10:56:25Z" level=debug msg="Creating middleware" serviceName=domain-decision-decision-80 middlewareName=pipelining middlewareType=Pipelining entryPointName=http routerName=decision-domain-decision-decision-domain-no@kubernetes
time="2022-05-27T10:56:25Z" level=debug msg="Creating load-balancer" entryPointName=http routerName=decision-domain-decision-decision-domain-no@kubernetes serviceName=domain-decision-decision-80
time="2022-05-27T10:56:25Z" level=debug msg="Creating server 0 http://10.52.12.11:80" entryPointName=http serverName=0 routerName=decision-domain-decision-decision-domain-no@kubernetes serviceName=domain-decision-decision-80
time="2022-05-27T10:56:25Z" level=debug msg="Creating server 1 http://10.52.9.15:80" serverName=1 serviceName=domain-decision-decision-80 entryPointName=http routerName=decision-domain-decision-decision-domain-no@kubernetes
time="2022-05-27T10:56:25Z" level=debug msg="Added outgoing tracing middleware domain-decision-decision-80" entryPointName=http routerName=decision-domain-decision-decision-domain-no@kubernetes middlewareName=tracing middlewareType=TracingForwarder
time="2022-05-27T10:56:25Z" level=debug msg="Creating middleware" entryPointName=https routerName=https-decision-domain-decision-decision-domain-no@kubernetes serviceName=domain-decision-decision-80 middlewareName=pipelining middlewareType=Pipelining
time="2022-05-27T10:56:25Z" level=debug msg="Creating load-balancer" entryPointName=https routerName=https-decision-domain-decision-decision-domain-no@kubernetes serviceName=domain-decision-decision-80
time="2022-05-27T10:56:25Z" level=debug msg="Creating server 0 http://10.52.12.11:80" routerName=https-decision-domain-decision-decision-domain-no@kubernetes serviceName=domain-decision-decision-80 serverName=0 entryPointName=https
time="2022-05-27T10:56:25Z" level=debug msg="Creating server 1 http://10.52.9.15:80" entryPointName=https routerName=https-decision-domain-decision-decision-domain-no@kubernetes serviceName=domain-decision-decision-80 serverName=1
time="2022-05-27T10:56:25Z" level=debug msg="Added outgoing tracing middleware domain-decision-decision-80" entryPointName=https routerName=https-decision-domain-decision-decision-domain-no@kubernetes middlewareName=tracing middlewareType=TracingForwarder
time="2022-05-27T10:56:25Z" level=debug msg="Adding route for decision.domain.no with TLS options default" entryPointName=https
```

**Comment by ddtmachado** [comment]
Thanks for the report @Richard87 , so far I was unable to reproduce the issue with the following setup:

```yaml
#Static Config
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  kubernetesIngress:
    ingressclass: traefik-lb
```

```yaml
#IngressClass
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik-lb
spec:
  controller: traefik.io/ingress-controller
```

```yaml
#Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # Works with and without
  #annotations:
  #  kubernetes.io/ingress.class: traefik-lb
  name: whoami-ingress
spec:
  # Also works with and without ingressClassName
  ingressClassName: traefik-lb
  rules:
  - host: whoami.docker.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:        
          service: 
            name: whoami
            port: 
              number: 80
```

The tricky part is matching the reference on all three objects, Static configuration + IngressClass definition + Ingress object.

Let us know if you still face this problem after checking that, and if so please attach the instance logs in debug mode for when the ingress is not found.
