### ISSUE TITLE
Discrepancies in parsing http request line

### ISSUE THREAD

**Issue by blessingcharles** [traefik/traefik#9053]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

1. According to RFC HTTP ABNF grammar DIGIT "." DIGIT should be accepted , while analyzing the parsing behavior of traefik , multiple 1*DIGIT and + sign also got accepted in HTTP major and minor version

#### RFC ABNF grammar

HTTP-version  = HTTP-name "/" DIGIT "." DIGIT
HTTP-name     = %x48.54.54.50 ; "HTTP", case-sensitive

### Steps to reproduce

1. Accepts [0]1.d\* versions d = [0-9]

```bash

echo -ne "GET / HTTP/1.189811\r\nHost: localhost\r\nContent-Length: 3\r\n\r\naaa" | nc localhost 9005

echo -ne "GET / HTTP/0001.+189811\r\nHost: localhost\r\nContent-Length: 3\r\n\r\naaa" | nc localhost 9005

```

2. Accepts + symbol before the major and minor version

```bash
echo -ne "GET / HTTP/+1.+189811\r\nHost: localhost\r\nContent-Length: 3\r\n\r\naaa" | nc localhost 9005
```

### Forwarded Downstream request from traefik

```bash
GET / HTTP/1.1
Host: localhost
Content-Length: 3
X-Forwarded-For: 172.17.0.1
X-Forwarded-Host: localhost
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: 5bfcd6117307
X-Real-Ip: 172.17.0.1
Accept-Encoding: gzip

aaa
```

### What version of Traefik are you using?

Version:      2.6.6
Codename:     rocamadour
Go version:   go1.17.9
Built:        2022-05-03T16:58:48Z
OS/Arch:      linux/amd64

### Dockerfile

```Dockerfile
FROM traefik
COPY traefik.toml /etc/traefik/traefik.toml
RUN mkdir /etc/traefik/dynconf
COPY dynconf.toml /etc/traefik/dynconf/dynconf.toml
```

### traefik.toml
```toml
## Static configuration
[entryPoints]
  [entryPoints.web]
    address = ":80"

[providers]
  [providers.file]
    directory = "/etc/traefik/dynconf"
```

### dynconf.toml
```
## Dynamic configuration
[http]
  [http.routers]
    [http.routers.Router-1]
      # By default, routers listen to every entry points
      rule = "Host(`localhost`)"
      service = "my-service"

  [http.services]
    [http.services.my-service.loadBalancer]
      [[http.services.my-service.loadBalancer.servers]]
        url = "http://172.17.0.1:5000/"
```

**Comment by tomMoulard** [comment]
Hello @blessingcharles,

Thanks for your interest in Traefik!

Unfortunately, I could not reproduce your issue, on all of `nc` requests, I get the same response that seems to be valid:
```
$ echo -ne "GET / HTTP/1.189811\r\nHost: localhost\r\nContent-Length: 3\r\n\r\naaa" | nc localhost 80
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

```

<details>
  <summary markdown="span">Here's docker-compose.yml file content</summary>

```yml
version: '3.9'

services:
  traefik:
    image: traefik:v2.6.6
    command:
      - --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: traefik/whoami # https://github.com/traefik/whoami
    labels:
      traefik.http.routers.whoami.rule: PathPrefix(`/`)
```

</details>

Can you provide a reproducible use case ?

Thanks in advance :)
