### ISSUE TITLE
Ingress ok but ingressroute 404

### ISSUE THREAD

**Issue by kong62** [traefik/traefik#9059]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

no

### What did you see instead?

Ingress OK：
```
# cat sentry-ingress.yaml 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app: sentry
  name: sentry
  namespace: sentry
spec:
  rules:
  - host: sentry-stg.hupu.com
    http:
      paths:
      - backend:
          serviceName: sentry-web
          servicePort: 9000
        path: /
```

ingressroute 404：
```
# cat sentry-ingressroute.yaml 
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sentry
  namespace: sentry
spec:
  entryPoints:
  - "web"
  routes:
  - kind: Rule
    match: Host(`sentry-stg.hupu.com`)
    services:
    - name: "sentry-web"
      port: 9000
      namespace: sentry
      scheme: http
```

### What version of Traefik are you using?

v2.5.4

### What is your environment & configuration?

```yaml
        - --entryPoints.web.address=:8000/tcp
        - --entryPoints.websecure.address=:8443/tcp
        - --entryPoints.traefik.address=:9000/tcp
        - --entryPoints.metrics.address=:9100/tcp
        - --providers.kubernetescrd
        - --providers.kubernetescrd.ingressclass=traefik
        - --providers.kubernetesingress
        - --providers.kubernetesingress.ingressclass=traefik
        - --providers.kubernetesGateway
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by kong62** [comment]
need  kubernetes.io/ingress.class: traefik  annotations,but  another cluster not
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sentry
  namespace: sentry
  # 恶心死了，使用 ingress 访问正常，使用 ingressroute 返回 404，居然要加一个这个注解，但是另外一个集群没这个问题
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`sentry-stg.hupu.com`) && PathPrefix(`/`)
    services:
    - name: sentry-web
      port: 9000
    middlewares:
    - name: sentry
```
