### ISSUE TITLE
Issues parsing comma separated status pages string in ErrorPage middleware after upgrade from 2.5 to 2.7

### ISSUE THREAD

**Issue by DOCaCola** [traefik/traefik#9061]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I upgraded from 2.5 to 2.7

I have a custom errorpage middle ware in use
excerpt from my yml configuration file

```yaml
    override-errorpage:
      errors:
        status:
          - "400,403,404,405,406,407,410,412,414,500,501,502"
        service: xyz-service
        query: "/errorpages/{status}.html"
```

### What did you see instead?

After upgrade from 2.5 to 2.7, i get the following output in the log on startup
`level=error msg="strconv.Atoi: parsing \"400,403,404,405,406,407,410,412,414,500,501,502\": invalid syntax"`
Accordingly, the error pages are not displayed.

### What version of Traefik are you using?

Version:      2.7.0
Codename:     epoisses
Go version:   go1.17.10
Built:        2022-05-24T17:07:05Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.
