### ISSUE TITLE
Setting the timezone for Access Logs from environment variables seems not working in kubernetes

### ISSUE THREAD

**Issue by superwjc** [traefik/traefik#9069]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

create a configmap(traefik-configs-env) from a environment file(traefik-env) in the namespace "traefik". Specially, set the  "TZ" and the "TRAEFIK_ACCESSLOG_FIELDS_NAMES_StartUTC" environment variables.

_**`# cat traefik-env`**_
```
TZ=Asia/Shanghai

# --accesslog
TRAEFIK_ACCESSLOG=true

# --accesslog.fields.defaultmode
TRAEFIK_ACCESSLOG_FIELDS_DEFAULTMODE=keep

# --accesslog.fields.headers.defaultmode
TRAEFIK_ACCESSLOG_FIELDS_HEADERS_DEFAULTMODE=drop

# --accesslog.fields.names.StartUTC
TRAEFIK_ACCESSLOG_FIELDS_NAMES_StartUTC=drop

# --entrypoints.metrics.address
TRAEFIK_ENTRYPOINTS_METRICS_ADDRESS=:9100/tcp

# --entrypoints.traefik.address
TRAEFIK_ENTRYPOINTS_TRAEFIK_ADDRESS=:9000/tcp

# --entrypoints.web.address
TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:8000/tcp

# --entrypoints.websecure.address
TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:8443/tcp

# --api.dashboard
TRAEFIK_API_DASHBOARD=true

# --api.debug
TRAEFIK_API_DEBUG=true

# --log.level
TRAEFIK_LOG_LEVEL=DEBUG

# --ping
TRAEFIK_PING=true

# --metrics.prometheus
TRAEFIK_METRICS_PROMETHEUS=true

# --metrics.prometheus.entrypoint
TRAEFIK_METRICS_PROMETHEUS_ENTRYPOINT=metrics

# --providers.kubernetescrd
TRAEFIK_PROVIDERS_KUBERNETESCRD=true

# --providers.kubernetesingress
TRAEFIK_PROVIDERS_KUBERNETESINGRESS=true
```
_**`# kubectl -n traefik create configmap traefik-configs-env --from-env-file=traefik-env`**_
```
configmap/traefik-configs-env created
```
add a reference to the configmap with the "envFrom" field in a daemonset(traefik-daemonset.yaml) in the namespace "traefik", and the image is "docker.io/library/traefik:v2.7.0".

_**`# cat traefik-daemonset.yaml`**_
```
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  name: traefik
  namespace: traefik
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/instance: traefik
        app.kubernetes.io/name: traefik
    spec:
      containers:
      - name: traefik
        image: docker.io/library/traefik:v2.7.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: traefik-configs-env
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        ports:
        - containerPort: 9100
          name: metrics
          protocol: TCP
        - containerPort: 9000
          name: traefik
          protocol: TCP
        - containerPort: 8000
          hostPort: 80
          name: web
          protocol: TCP
        - containerPort: 8443
          hostPort: 443
          name: websecure
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 65532
      serviceAccount: traefik
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60
      volumes:
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: tmp
```
after creating the daemonset successfully, pick up one pod(traefik-mtj5g), check the environment variables set above, the timezone, and the access log timestamp.
nothing wrong with the env and timezone, but the timestamp mixed with the UTC and CST.

_**`# kubectl apply -f traefik-daemonset.yaml`**_
```
daemonset.apps/traefik created
```
_**`# kubectl -n traefik get pods`**_
```
NAME            READY   STATUS    RESTARTS   AGE
traefik-kjs5h   1/1     Running   0          4m57s
traefik-mtj5g   1/1     Running   0          4m57s
traefik-tzd9v   1/1     Running   0          4m57s
```
_**`# kubectl -n traefik exec -it traefik-mtj5g -- env`**_
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=traefik-kjs5h
TRAEFIK_ENTRYPOINTS_METRICS_ADDRESS=:9100/tcp
TRAEFIK_PROVIDERS_KUBERNETESINGRESS=true
TRAEFIK_PING=true
TRAEFIK_ACCESSLOG_FIELDS_DEFAULTMODE=keep
TRAEFIK_API_DEBUG=true
TRAEFIK_ENTRYPOINTS_TRAEFIK_ADDRESS=:9000/tcp
TZ=Asia/Shanghai
TRAEFIK_METRICS_PROMETHEUS=true
TRAEFIK_ACCESSLOG_FIELDS_NAMES_StartUTC=drop
TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:8443/tcp
TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:8000/tcp
TRAEFIK_METRICS_PROMETHEUS_ENTRYPOINT=metrics
TRAEFIK_PROVIDERS_KUBERNETESCRD=true
TRAEFIK_ACCESSLOG_FIELDS_HEADERS_DEFAULTMODE=drop
TRAEFIK_LOG_LEVEL=DEBUG
TRAEFIK_ACCESSLOG=true
TRAEFIK_API_DASHBOARD=true
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
KUBERNETES_SERVICE_HOST=10.96.0.1
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP_PROTO=tcp
TERM=xterm
HOME=/
```
_**`# kubectl -n traefik exec -it traefik-mtj5g -- date`**_
```
Fri Jun  3 09:54:01 CST 2022
```
_**`# # kubectl -n traefik logs -f traefik-mtj5g`**_
```
time="2022-06-03T09:54:40+08:00" level=debug msg="Authentication succeeded" middlewareName=traefik-traefik-ui-basic-auth@kubernetescrd middlewareType=BasicAuth
time="2022-06-03T09:54:40+08:00" level=debug msg="Removing authorization header" middlewareName=traefik-traefik-ui-basic-auth@kubernetescrd middlewareType=BasicAuth
22.99.22.118 - admin [03/Jun/2022:01:54:40 +0000] "GET /api/overview HTTP/2.0" 200 534 "-" "-" 439 "traefik-traefik-dashboard-2ea68866e9720d881f38@kubernetescrd" "-" 0ms
22.99.22.11 - - [03/Jun/2022:01:54:41 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 440 "ping@internal" "-" 0ms
22.99.22.11 - - [03/Jun/2022:01:54:41 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 441 "ping@internal" "-" 0ms
```

### What did you see instead?

following [[the official documents](https://doc.traefik.io/traefik/observability/access-logs/#time-zones)](url)，I've passed the static configuration with command-line arguments, and it works as expect.
in totally, setting access log timestamp with the command-line arguments "**--accesslog.fields.names.StartUTC=drop**" and the environment variable "**TRAEFIK_ACCESSLOG_FIELDS_NAMES_StartUTC=drop**" leads to different results, or is there something wrong with my settings?

### What version of Traefik are you using?

2.7.0
`# kubectl -n traefik exec -it traefik-mtj5g -- traefik version`
```
Version:      2.7.0
Codename:     epoisses
Go version:   go1.17.10
Built:        2022-05-24T17:07:05Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

`# kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

Add more configuration information here.
**namespace, serviceaccount, permissions:**
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: traefik
  namespace: traefik

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - middlewaretcps
      - tlsoptions
      - tlsstores
      - traefikservices
      - serverstransports
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: traefik
```
**daemonset manifest with environment variables reference:**
```
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  name: traefik
  namespace: traefik
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/instance: traefik
        app.kubernetes.io/name: traefik
    spec:
      containers:
      - name: traefik
        image: docker.io/library/traefik:v2.7.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: traefik-configs-env
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        ports:
        - containerPort: 9100
          name: metrics
          protocol: TCP
        - containerPort: 9000
          name: traefik
          protocol: TCP
        - containerPort: 8000
          hostPort: 80
          name: web
          protocol: TCP
        - containerPort: 8443
          hostPort: 443
          name: websecure
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 65532
      serviceAccount: traefik
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60
      volumes:
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: tmp

```

**daemonset manifest with command-line arguements:**
```
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  name: traefik
  namespace: traefik
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: traefik
        app.kubernetes.io/name: traefik
    spec:
      containers:
      - args:
        - --entrypoints.metrics.address=:9100/tcp
        - --entrypoints.traefik.address=:9000/tcp
        - --entrypoints.web.address=:8000/tcp
        - --entrypoints.websecure.address=:8443/tcp
        - --api.dashboard=true
        - --ping=true
        - --metrics.prometheus=true
        - --metrics.prometheus.entrypoint=metrics
        - --providers.kubernetescrd
        - --providers.kubernetesingress
        - --log.level=DEBUG
        - --accesslog=true
        - --accesslog.fields.defaultmode=keep
        - --accesslog.fields.names.StartUTC=drop
        - --accesslog.fields.headers.defaultmode=drop
        env:
        - name: TZ
          value: Asia/Shanghai
        image: docker.io/library/traefik:v2.7.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: traefik
        ports:
        - containerPort: 9100
          name: metrics
          protocol: TCP
        - containerPort: 9000
          name: traefik
          protocol: TCP
        - containerPort: 8000
          hostPort: 80
          name: web
          protocol: TCP
        - containerPort: 8443
          hostPort: 443
          name: websecure
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 65532
      serviceAccount: traefik
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60
      volumes:
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: tmp
```
**environment file from which configmap create:**
```
TZ=Asia/Shanghai

# --accesslog
TRAEFIK_ACCESSLOG=true

# --accesslog.fields.defaultmode
TRAEFIK_ACCESSLOG_FIELDS_DEFAULTMODE=keep

# --accesslog.fields.headers.defaultmode
TRAEFIK_ACCESSLOG_FIELDS_HEADERS_DEFAULTMODE=drop

# --accesslog.fields.names.StartUTC
TRAEFIK_ACCESSLOG_FIELDS_NAMES_StartUTC=drop

# --entrypoints.metrics.address
TRAEFIK_ENTRYPOINTS_METRICS_ADDRESS=:9100/tcp

# --entrypoints.traefik.address
TRAEFIK_ENTRYPOINTS_TRAEFIK_ADDRESS=:9000/tcp

# --entrypoints.web.address
TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:8000/tcp

# --entrypoints.websecure.address
TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:8443/tcp

# --api.dashboard
TRAEFIK_API_DASHBOARD=true

# --api.debug
TRAEFIK_API_DEBUG=true

# --log.level
TRAEFIK_LOG_LEVEL=DEBUG

# --ping
TRAEFIK_PING=true

# --metrics.prometheus
TRAEFIK_METRICS_PROMETHEUS=true

# --metrics.prometheus.entrypoint
TRAEFIK_METRICS_PROMETHEUS_ENTRYPOINT=metrics

# --providers.kubernetescrd
TRAEFIK_PROVIDERS_KUBERNETESCRD=true

# --providers.kubernetesingress
TRAEFIK_PROVIDERS_KUBERNETESINGRESS=true
```

### If applicable, please paste the log output in DEBUG level

```
time="2022-06-03T09:54:40+08:00" level=debug msg="Authentication succeeded" middlewareName=traefik-traefik-ui-basic-auth@kubernetescrd middlewareType=BasicAuth
time="2022-06-03T09:54:40+08:00" level=debug msg="Removing authorization header" middlewareName=traefik-traefik-ui-basic-auth@kubernetescrd middlewareType=BasicAuth
22.99.22.118 - admin [03/Jun/2022:01:54:40 +0000] "GET /api/overview HTTP/2.0" 200 534 "-" "-" 439 "traefik-traefik-dashboard-2ea68866e9720d881f38@kubernetescrd" "-" 0ms
22.99.22.11 - - [03/Jun/2022:01:54:41 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 440 "ping@internal" "-" 0ms
22.99.22.11 - - [03/Jun/2022:01:54:41 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" 441 "ping@internal" "-" 0ms
```
