### ISSUE TITLE
Domain for ACME doesn't get picked up when relying on `defaultRule`

### ISSUE THREAD

**Issue by rtm516** [traefik/traefik#9073]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Attempted to use ACME certs for routes configured by the docker provider that uses the `defaultRule` setting

### What did you see instead?

Alot of these in the logs and the default cert still being used on routes/domains
```
time="2022-06-04T19:47:59+01:00" level=error msg="Unable to obtain ACME certificate for domains \"\" : unable to generate a certificate in ACME provider when no domain is given" providerName=default.acme
```

### What version of Traefik are you using?

Version:      2.5.4
Codename:     livarot
Go version:   go1.17.3
Built:        2021-11-08T17:41:41Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.int.example.com`)"
    exposedByDefault: false
    network: bridge
  file:
    directory: /etc/traefik/conf

# API and dashboard configuration
api:
  dashboard: true

# Entrypoints
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true

  https:
    address: ":443"
    http:
      tls:
        # Placeholder to enable tls
        domains:
          main: "traefik.int.example.com"
        certResolver: default

certificatesResolvers:
  default:
    acme:
      email: ryan@example.com
      storage: acme.json
      httpChallenge:
        entryPoint: http
      caServer: https://192.168.1.5:9000/

```

I have this with then all containers labeled with `traefik.enable=true` with a few extra on the main traefik container
```
traefik.http.routers.api.rule=Host("traefik.int.rtm516.co.uk")
traefik.http.routers.api.service=api@internal
traefik.http.services.traefik.loadbalancer.server.port=8080
traefik.backend=traefik
```

### If applicable, please paste the log output in DEBUG level

time="2022-06-04T20:16:02+01:00" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
time="2022-06-04T20:16:04+01:00" level=error msg="Unable to obtain ACME certificate for domains \"\" : unable to generate a certificate in ACME provider when no domain is given" providerName=default.acme
time="2022-06-04T20:16:04+01:00" level=error msg="Unable to obtain ACME certificate for domains \"\" : unable to generate a certificate in ACME provider when no domain is given" providerName=default.acme
time="2022-06-04T20:16:04+01:00" level=error msg="Unable to obtain ACME certificate for domains \"\" : unable to generate a certificate in ACME provider when no domain is given" providerName=default.acme
time="2022-06-04T20:16:04+01:00" level=error msg="Unable to obtain ACME certificate for domains \"\" : unable to generate a certificate in ACME provider when no domain is given" providerName=default.acme
time="2022-06-04T20:16:04+01:00" level=error msg="Unable to obtain ACME certificate for domains \"\" : unable to generate a certificate in ACME provider when no domain is given" providerName=default.acme
time="2022-06-04T20:16:04+01:00" level=error msg="Unable to obtain ACME certificate for domains \"\" : unable to generate a certificate in ACME provider when no domain is given" providerName=default.acme
time="2022-06-04T20:16:04+01:00" level=error msg="Unable to obtain ACME certificate for domains \"\" : unable to generate a certificate in ACME provider when no domain is given" providerName=default.acme
time="2022-06-04T20:16:04+01:00" level=error msg="Unable to obtain ACME certificate for domains \"\" : unable to generate a certificate in ACME provider when no domain is given" providerName=default.acme

**Comment by ldez** [comment]
Hello,

you have to typo in your configuration:
```yml
  https:
    address: ":443"
    http:
      tls:
        # Placeholder to enable tls
        domains:
          main: "traefik.int.example.com" # <--- HERE
        certResolver: default
```

It must be:
```yml
  https:
    address: ":443"
    http:
      tls:
        # Placeholder to enable tls
        domains:
          - main: "traefik.int.example.com" # <--- HERE
        certResolver: default
```

https://doc.traefik.io/traefik/routing/entrypoints/#tls
