### ISSUE TITLE
tcp routers documentation issue

### ISSUE THREAD

**Issue by firstdorsal** [traefik/traefik#9075]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

See:
https://doc.traefik.io/traefik/routing/routers/#rule_1
"HostSNI & TLS"
It says to configure the rule like this for non tls tcp routers: `HostSNI(*)`
But this does not work:

![image](https://user-images.githubusercontent.com/10563452/172153230-a48be360-5714-48b7-bbec-e8722c77fcd5.png)

I tried it with backticks ```HostSNI(`*`)``` but at least for my usecase (proxy tcp and udp traffic to minecraft) this does not work either.

### What did you see instead?

See above

### What version of Traefik are you using?

2.7

### What is your environment & configuration?

**static config**
```yaml
docker:
    network: rp
providers:
    providersThrottleDuration: 5s
    docker:
        exposedbydefault: false
    file:
        directory: /traefik/dynamic/
        watch: true
entryPoints:
    web:
        address: :80
    websecure:
        address: :443
        http3: {}
    # mail
    smtp:
        address: :25/tcp
    smtps:
        address: :465/tcp
    submission:
        address: :587/tcp
    imaps:
        address: :993/tcp
    pop3s:
        address: :995/tcp
    sieve:
        address: :4190/tcp
    #pop3:
    #    address: :110/tcp
    #imap:
    #    address: :143/tcp
    # minecraft
    minecraft-vanilla-tcp:
        address: :25565/tcp
    minecraft-vanilla-udp:
        address: :25565/udp

experimental:
    http3: true

certificatesResolvers:
    default:
        acme:
            storage: /letsencrypt/acme.json
            email: xxx
            dnschallenge:
                provider: pdns
api:
    insecure: true
    dashboard: true
log:
    level: DEBUG

```
minecraft-compose.yml
```yaml
...
        labels:
            traefik.enable: "true"
            traefik.tcp.routers.minecraft-vanilla.entrypoints: minecraft-vanilla-tcp
            traefik.tcp.routers.minecraft-vanilla.rule: "HostSNI(*)"
            traefik.tcp.services.minecraft-vanilla.loadbalancer.server.port: "25565"

            traefik.udp.routers.minecraft-vanilla.entrypoints: minecraft-vanilla-udp
            traefik.udp.services.minecraft-vanilla.loadbalancer.server.port: "25565"
```

Add more configuration information here.
