### ISSUE TITLE
Removing TCP service and router does not close ESTABLISHED connections

### ISSUE THREAD

**Issue by hidemire** [traefik/traefik#9077]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

The main task is to dynamically provide access to TCP services behind a proxy.
Redis KV is used for dynamic configuration.

After deleting the configuration from KV, it is expected that all established connections will be closed.

Example configuration from KV:
```
traefik/tcp/routers/tcp-echo/entrypoints/0 5000
traefik/tcp/routers/tcp-echo/rule HostSNI(`*`)
traefik/tcp/routers/tcp-echo/service tcp-echo
traefik/tcp/services/tcp-echo/loadBalancer/servers/0/address 172.28.241.24:9000
```

In this case, `172.28.241.24:9000` is a TCP echo server.

### What did you see instead?

After deleting the configuration, the established connections still remain established.
New connections, as expected, are not established.

### What version of Traefik are you using?

Version:      2.7.0
Codename:     epoisses
Go version:   go1.17.10
Built:        2022-05-24T17:07:05Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

**docker-compose.yml**
```yaml
version: '3.7'

services:
  traefik:
    image: traefik:v2.7
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - '80:80'
      - '5000-5010:5000-5010'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    networks:
      backend:
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --log.level=INFO
      # docker & dynamic configuration
      - --providers.docker=true
      - --providers.docker.network=backend
      - --providers.docker.exposedbydefault=false
      - --providers.redis.endpoints=${REDIS_ENDPOINT}
      - --providers.redis.rootkey=traefik
      - --providers.redis.username=${REDIS_USERNAME}
      - --providers.redis.password=${REDIS_PASSWORD}
      # entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.5000.address=:5000
      - --entrypoints.5001.address=:5001
      - --entrypoints.5002.address=:5002

  redis:
    image: bitnami/redis:6.2
    restart: unless-stopped
    networks:
      backend:
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: /opt/bitnami/scripts/redis/run.sh --notify-keyspace-events KEA

  tcp-echo:
    image: istio/tcp-echo-server:1.2
    restart: unless-stopped
    networks:
      backend:
        ipv4_address: 172.28.241.24

networks:
  backend:
    external: true
```
**network setup**
```
docker network create --subnet=172.28.241.0/24 backend
```
