### ISSUE TITLE
CA certificate from secret is not served

### ISSUE THREAD

**Issue by sl1288** [traefik/traefik#9087]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I did create an secret with cert-manager which contains the server certificate and the ca certificate.

```yaml
apiVersion: v1
data:
  ca.crt: LS0tLS...
  tls.crt: LS0tLS...
  tls.key: LS0tLS...
kind: Secret
```

After adding an IngressRoute with secretName set, I call "openssl s_client" to fetch the certificates from the https port.

### What did you see instead?

"openssl s_client" only shows the "tls.crt" certificate, the "ca.crt" certificate is missing.

### What version of Traefik are you using?

rancher/mirrored-library-traefik:2.6.2

### What is your environment & configuration?

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: ca-key-pair
  namespace: cert-manager
data:
  tls.crt: LS0tLS1CRUd...
  tls.key: LS0tLS1CRUd...
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: ca-key-pair
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-certificate
  namespace: web-namespace
spec:
  commonName: kunde.tld
  duration: 8760h
  dnsNames:
    - kunde.tld
  secretName: web-certificate
  issuerRef:
    name: cert-manager-issuer
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web
  namespace: web-namespace
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`kunde.tld`)
      kind: Rule
      services:
        - name: backend
          port: 80
  tls:
    secretName: web-certificate
```
