### ISSUE TITLE
Traefik does not respect comments containing go templates in yaml config

### ISSUE THREAD

**Issue by vorpalhex** [traefik/traefik#9089]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Yaml comments that contain go templates are executed. Eg the following should not execute:

```
# Docker configuration backend
providers:
  docker:
    exposedByDefault: false
      #defaultRule: 'Host("{{ regexReplaceAll `-(.*)` ``}}.example.com")'
```

### What did you see instead?

Traefik executed the comment and found an error:

```
time="2022-06-11T14:57:48-05:00" level=error msg="Error occurred during watcher callback: /etc/traefik/traefik.yml: template: :23:30: executing \"\" at <regexReplaceAll>: wrong number of args for regexReplaceAll: want 3 got 2" providerName=file
```

### What version of Traefik are you using?

Version:      2.7.0
Codename:     epoisses
Go version:   go1.17.10
Built:        2022-05-24T17:07:05Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
## traefik.yml
log:
  level: WARN

entryPoints:
  web:
    address: ":80"

  web-secure:
    address: ":443"

accessLog:
  filePath: "/var/log/access.log"
api:
  dashboard: true
  debug: true
  insecure: false

# Docker configuration backend
providers:
  docker:
    exposedByDefault: false
      #defaultRule: 'Host("{{ regexReplaceAll `-(.*)` ``}}.example.com")'
  file:
    directory: /etc/traefik/
    watch: true

certificatesResolvers:
  le:
    acme:
      email: me@mydomain.com
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

http:
  routers:
    node-exporter:
      service: node-exporter
      rule: Host(`node.mydomain.com`)
      middlewares:
        - auth_monitoring
  services:
    node-exporter:
      loadBalancer:
        servers:
        - url: http://some-ip
  middlewares:
    auth_monitoring:
      basicauth:
        users: "some-user-some-key"
```

Add more configuration information here.
