### ISSUE TITLE
Allow multiple providers of the same type

### ISSUE THREAD

**Issue by ddtmachado** [traefik/traefik#9101]
### What did you expect to see?

This feature proposal should unify other isolated requests on specific providers like HTTP, Docker and Consul.

The goal is to add support for specifying and instantiating multiple providers of the same type. To achieve that the providers section must be modified so it uses named resources similar to a middleware. Example:

```yaml
providers:
  mycrd:
    kubernetescrd: {}
  myingress:
    kubernetesIngress: {}      
```

As this is a breaking change (configuration wise) it is only possible in a new major version.
