### ISSUE TITLE
Traefik v2.7.1 redirectScheme Middlewhere does not honor `port` property when loading configuration from Kubernetes CRD

### ISSUE THREAD

**Issue by Matthew-Beckett** [traefik/traefik#9123]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Create redirectScheme middleware CRD object:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  creationTimestamp: '2022-06-22T17:35:04Z'
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: traefik-middlewares
    kustomize.toolkit.fluxcd.io/namespace: traefik-ingress
spec:
  redirectScheme:
    permanent: true
    port: '443'
    scheme: https
```

and attach it to a http ingress object

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-demo-frontend-http
  namespace: microservices-demo
  uid: c0310500-e3f1-4e85-9096-7a5ba2309d6d
  resourceVersion: '133988'
  generation: 1
  creationTimestamp: '2022-06-22T17:42:51Z'
  labels:
    kustomize.toolkit.fluxcd.io/name: microservices-demo
    kustomize.toolkit.fluxcd.io/namespace: microservices-demo
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: traefik-ingress-redirect-https-scheme@kubernetescrd
spec:
  rules:
    - host: microservices-demo.xxx.xxx.xxx
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
```

### What did you see instead?

I continue to be redirected to HTTPS on `websecure`'s port of 8443 instead of the provided port in the CRD/middleware.

### What version of Traefik are you using?

2.7.1

### What is your environment & configuration?

```
--global.checknewversion
--global.sendanonymoususage
--entrypoints.metrics.address=:9100/tcp 
--entrypoints.traefik.address=:9000/tcp 
--entrypoints.web.address=:8000/tcp 
--entrypoints.websecure.address=:8443/tcp 
--api.dashboard=true 
--ping=true 
--metrics.prometheus=true
 --metrics.prometheus.entrypoint=metrics 
--providers.kubernetescrd 
--providers.kubernetesingress
 --providers.kubernetesingress.ingressendpoint.publishedservice=traefik-ingress/traefik
```

**Comment by kevinpollet** [comment]
Hello @Matthew-Beckett,

Thanks for your interest in Traefik,

We tried to reproduce the issue but without any success.

Are you sure that you do not have a redirection configured at the [entrypoint level](https://doc.traefik.io/traefik/routing/entrypoints/#entrypoint)? (which could explain that you are redirected to port `8443`)

How do you install Traefik in Kubernetes?

**Comment by Matthew-Beckett** [comment]
> Hello @Matthew-Beckett,
> 
> Thanks for your interest in Traefik,
> 
> We tried to reproduce the issue but without any success.
> 
> Are you sure that you do not have a redirection configured at the [entrypoint level](https://doc.traefik.io/traefik/routing/entrypoints/#entrypoint)? (which could explain that you are redirected to port `8443`)
> 
> How do you install Traefik in Kubernetes?

Hi Kevin,

Thanks for your swift reply, I am deplying Traefik via Helm chart using FluxCD GitOps. Please find my Values YAML below:

```yaml
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: true
    ports:
      traefik:
        port: 9000
        expose: false
        exposedPort: 9000
        protocol: TCP
      web:
        port: 8000
        expose: true
        exposedPort: 80
        protocol: TCP
      websecure:
        port: 8443
        expose: true
        exposedPort: 443
        protocol: TCP
        tls:
          enabled: false
          options: ""
          certResolver: ""
          domains: []
```
