### ISSUE TITLE
Support fetching headers only for HTTP health check

### ISSUE THREAD

**Issue by Dragnell87** [traefik/traefik#9138]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### Do you want to request a feature or report a bug?
Feature

###  What did you expect to see?

It would be great to see this feature in the health check:

Be able to select the headers only in an HTTP check

Use case:
Minio uses a healthcheck API but only gives back the header, anything different from a 200 is indicative that something is wrong with the node.
According to the minio [doc](https://docs.min.io/minio/baremetal/monitoring/healthcheck-probe.html)

```
curl -I http://minio.example.com:9000/minio/health/live
```

result in

```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 0
Content-Security-Policy: block-all-mixed-content
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
X-Amz-Request-Id: 16F6A51C19B2FD3A
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Date: Wed, 08 Jun 2022 12:30:53 GMT
```
Traefik attempts to health check like so, it fails

```yml
services:
    minio-api:
      loadBalancer:
        healthCheck:
          path: /minio/health/live/
          port: 9000  
          interval: 10s
          timeout: 3s
        servers:
        - url  "http://172.26.3.41:9000"
        - url: "http://172.26.3.42:9000"
        - url: "http://172.26.3.43:9000"
        - url: "http://172.26.3.44:9000"
```
