### ISSUE TITLE
There is a problem with docker compose deployment

### ISSUE THREAD

**Issue by ChenpiDog** [traefik/traefik#9145]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

The following is my docker compose content：

```yml
version: '3'

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:2.7.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker --entryPoints.web.address=:80 --entryPoints.websecure.address=:443
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"    
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  
  tomcat:
    image: tomcat:9.0.64
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tomcat-https.rule=Host(`trxn.tomcat.cn`)"
      - "traefik.http.routers.tomcat-https.tls=true"
      - "traefik.http.routers.tomcat-https.tls.certresolver=myresolver"
      - "traefik.http.routers.tomcat-https.service=tomcat"
      
      - "traefik.http.routers.tomcat-http.rule=Host(`trxn.tomcat.cn`)"
      - "traefik.http.routers.tomcat-http.service=tomcat"
      
      - "traefik.http.routers.tomcat-https.entrypoints=websecure"
      - "traefik.http.routers.tomcat-http.entrypoints=web"
      
      - "traefik.http.services.tomcat.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.redirect-http-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-http-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.tomcat-http.middlewares=redirect-http-to-https"
```

### What did you see instead?

When I enter "https://trxn.tomcat.cn", 404 page not found.

### What version of Traefik are you using?

2.7.2

### What is your environment & configuration?

```yml
version: '3'

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:2.7.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker --entryPoints.web.address=:80 --entryPoints.websecure.address=:443
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"    
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  
  tomcat:
    image: tomcat:9.0.64
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tomcat-https.rule=Host(`trxn.tomcat.cn`)"
      - "traefik.http.routers.tomcat-https.tls=true"
      - "traefik.http.routers.tomcat-https.tls.certresolver=myresolver"
      - "traefik.http.routers.tomcat-https.service=tomcat"
      
      - "traefik.http.routers.tomcat-http.rule=Host(`trxn.tomcat.cn`)"
      - "traefik.http.routers.tomcat-http.service=tomcat"
      
      - "traefik.http.routers.tomcat-https.entrypoints=websecure"
      - "traefik.http.routers.tomcat-http.entrypoints=web"
      
      - "traefik.http.services.tomcat.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.redirect-http-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-http-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.tomcat-http.middlewares=redirect-http-to-https"
```
