### ISSUE TITLE
Remove old SAN when renewing certificates

### ISSUE THREAD

**Issue by rossnick** [traefik/traefik#9162]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I had a certificate on an internal ACME step-ca CA server (I suspect it would do the same on Let's encrypt CA) with 2 domain name via a router rule. Certificate was issued with the first one as "main" domain and second one as 2nd SAN. That 2nd SAN was later removed from configuration. At the time of renew, certificate resolver was trying to renew the certificate as-is with the 2 SAN, one of which was no longer existing in DNS, hence not working. 

### What did you see instead?

Certificate was not renewed.

### What version of Traefik are you using?

Version:      2.7.3
Codename:     epoisses
Go version:   go1.17.11
Built:        2022-06-29T13:48:15Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

At first :
```yaml
http:
  routers:
    traefik-dashboard-http:
      rule: "Host(`HOSTNAME1`, `HOSTNAME2`)"
      service: "api@internal"
      middlewares: redirect-to-https
    traefik-dashboard-https:
      rule: "Host(`HOSTNAME1`, `HOSTNAME2`)"
      service: "api@internal"
      entrypoints: "websecure"
      middlewares:
        - "auth"
        - "compress"
      tls:
        certResolver: acme-c4-resolver
```
Then changed to :
```yaml
http:
  routers:
    traefik-dashboard-http:
      rule: "Host(`HOSTNAME1`)"
      service: "api@internal"
      middlewares: redirect-to-https
    traefik-dashboard-https:
      rule: "Host(`HOSTNAME1`)"
      service: "api@internal"
      entrypoints: "websecure"
      middlewares:
        - "auth"
        - "compress"
      tls:
        certResolver: acme-c4-resolver
```
