### ISSUE TITLE
Traefik >= 2.7.2 changes ";" to "&" in URL request string

### ISSUE THREAD

**Issue by wollomatic** [traefik/traefik#9164]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have a request like `https://whoami.example.com/?testurl=http://test/?a=1;b=2;c=3`

I expect the request to be `GET /?testurl=http://test/?a=1;b=2;c=3 HTTP/1.1`

The issue can be reproduced with using 

### What did you see instead?

Request is `GET /?testurl=http://test/?a=1&b=2&c=3 HTTP/1.1`

### What version of Traefik are you using?

Issue starts with version 2.7.2

```
Version:      2.7.3
Codename:     epoisses
Go version:   go1.17.11
Built:        2022-06-29T13:48:15Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```
services:

  whoami:
    image: "containous/whoami"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wwhoami.entrypoints=web-secure"
      - "traefik.http.routers.wwhoami.rule=Host(`whoami.example.com`)"
      - "traefik.http.routers.wwhoami.tls=true"
      - "traefik.http.routers.wwhoami.tls.certresolver=acme"
      - "traefik.http.routers.wwhoami.middlewares=secHeaders@file"
      - "traefik.http.services.wwhoami.loadbalancer.server.port=80"
    networks:
      - traefik_servicenet

networks:
  traefik_servicenet:
    external: true
    name: traefik_servicenet
```

Configuration like https://github.com/wollomatic/traefik2-hardened with a few changes such as http3 disabled.
