### ISSUE TITLE
DynamoDB provider support for WebIdentityRoleProvider

### ISSUE THREAD

**Issue by pompeyjoe** [traefik/traefik#9166]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I've taken the public traefik Docker image ([v1.7.34](https://github.com/traefik/traefik-library-image/blob/4434758cf14bbd1ec9511b3f2a37b0a6ce846db6/scratch/Dockerfile)) and I'm trying to run it up on AWS EKS, configured to use the [DynamoDB provider](https://doc.traefik.io/traefik/v1.7/configuration/backends/dynamodb/), using an IAM Role associated with a [Kubernetes Service Account](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) but I'm getting this error on start up:

```
Provider error: AccessDeniedException: User: arn:aws:sts::<redacted>:assumed-role/joe20210824175302473300000009/i-abcdefg123 is not authorized to perform: dynamodb:Scan on resource: arn:aws:dynamodb:us-west-2:<redacted>:table/traefik because no identity-based policy allows the dynamodb:Scan action
    status code: 400, request id: <redacted> time: 1.197095801s 
```

The IAM role associated with the Kubernetes service account has an inline policy that allows "dynamodb:Scan":

```
  - effect: Allow
    actions:
      - "dynamodb:GetItem"
      - "dynamodb:Query"
      - "dynamodb:Scan"
    resources:
      - "arn:aws:dynamodb:us-west-2:<redacted>:table/traefik"
```

The Helm chart for my traefik deploy has the following Service Account definition:

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::<redacted>:role/traefik"
```

The AWS docs stipulate a [minimum SDK version](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html) (v1.23.13 for Go, which is what traefik is written in), if we want to assume an IAM role via an OIDC web identity token file. It looks like traefik v1.7.34 is [using Go v1.39.0](https://github.com/traefik/traefik/blob/25757d2a27bb38c1cdf49c95f8a018a34a5f72ed/go.mod#L21), so that should be sufficient.

However, I think that the way the credential chain is constructed [here](https://github.com/traefik/traefik/blob/25757d2a27bb38c1cdf49c95f8a018a34a5f72ed/provider/dynamodb/dynamodb.go#L57) means that `AWS_WEB_IDENTITY_TOKEN_FILE` is ignored.

This could be fixed by adding [WebIdentityRoleProvider](https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/stscreds/#WebIdentityRoleProvider) to the credentials chain, similar to what Hashicorp have done for Vault here: https://github.com/hashicorp/vault/pull/7738/files
