### ISSUE TITLE
Traefik load balancer sends traffic to services without any server available and partially results in 503 responses

### ISSUE THREAD

**Issue by ffilippopoulos** [traefik/traefik#9172]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am running traefik in Kubernetes using kubernetesCRD provider for dynamic configuration.  I am trying to load balance between 3 services that run under separate namespaces.
For that purpose I have the following `IngressRoute` defined in my cluster: 
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: echo
  labels:
    kubernetes.io/ingress.class: traefik-private-v2
spec:
  entryPoints:
    - web-secure
  routes:
    - kind: Rule
      match: Host(`echo.mydomain.co.uk`)
      services:
        - kind: Service
          name: echo
          namespace: ns1
          port: 80
        - kind: Service
          name: echo
          namespace: ns2
          port: 80
        - kind: Service
          name: echo
          namespace: bs3
          port: 80
  tls: {}
```
and it seems to work as expected when all services are up and have healthy endpoints. When a service is down (no Kubernetes Endpoints available -> No Servers configured in traefik service) I see that I get 503 responses in approximately 1/3 of my requests, which means that traefik is still load balancing including the "dead" service.

### What did you see instead?

Traefik sends traffic down to a service without any servers resulting in `503`s, even though we still have available servers in other services that this load balancer targets.

### What version of Traefik are you using?

traefik:v2.7.2

### What is your environment & configuration?

Running as Kubernetes deployment with the following arguments
```
          args:
            - --api.insecure=true
            - --ping
            - --metrics.prometheus
            - --log.level=ERROR # default: ERROR
            - --providers.kubernetescrd.labelselector=kubernetes.io/ingress.class=traefik-private-v2
            - --providers.kubernetescrd.allowexternalnameservices=true
            - --providers.kubernetescrd.allowcrossnamespace=true
            - --providers.kubernetescrd.allowemptyservices=true
            - --providers.kubernetesingress.labelselector=kubernetes.io/ingress.class=traefik-private-v2
            - --providers.kubernetesingress.allowemptyservices=true
            - --entryPoints.web.address=:80
            - --entrypoints.web.http.redirections.entryPoint.to=web-secure
            # Redirection can be skipped by creating an IngressRoute with higher priority
            - --entrypoints.web.http.redirections.entrypoint.priority=1000
            - --entryPoints.web-secure.address=:443
            - --entryPoints.web-secure.http.tls=true
            - --entryPoints.traefik.address=:8080
            # Default rate limit for all IngressRoutes
            - --entrypoints.web-secure.http.middlewares=$(POD_NAMESPACE)-default-ratelimit@kubernetescrd
```
