### ISSUE TITLE
Avoid routing to dead Kubernetes services when there are other available with live endpoints

### ISSUE THREAD

**Issue by ffilippopoulos** [traefik/traefik#9174]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

We are running traefik in Kubernetes using kubernetesCRD provider for dynamic configuration and trying to load balance between 3 services that run under separate namespaces. For that purpose we have the following `IngressRoute` defined:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: echo
  labels:
    kubernetes.io/ingress.class: traefik-private-v2
spec:
  entryPoints:
    - web-secure
  routes:
    - kind: Rule
      match: Host(`echo.mydomain.co.uk`)
      services:
        - kind: Service
          name: echo
          namespace: ns1
          port: 80
        - kind: Service
          name: echo
          namespace: ns2
          port: 80
        - kind: Service
          name: echo
          namespace: ns3
          port: 80
  tls: {}
  ```
  Also, we have enabled `allowEmptyServices` to be able to register a router from the above config even if a service is down.
  We do that via the following argument:
  ```
  --providers.kubernetescrd.allowemptyservices=true
  ```
  
We see that when one of above services does not have any available endpoints, the load balancer is still forwarding to that service and a portion of our requests result in `503` responses.
Since, the remaining services have live endpoints, we'd expect to see traffic load balanced to them and traefik avoiding to try the "dead" one and respond with a `503`.
Related issue, closed with a suggestion to raise a feature request: https://github.com/traefik/traefik/issues/9172
