### ISSUE TITLE
For HTTP POST request net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by openspeedtest** [traefik/traefik#9175]
- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am trying to install https://hub.docker.com/r/openspeedtest/latest
which runs on port 3000 for http and 3001 for https.

I need to run just HTTP version on LocalNetwork. 

I am getting network error in browser console when upload test is running. 

### What did you see instead?

![Screen Shot 2022-07-09 at 1 56 25 PM](https://user-images.githubusercontent.com/51720450/178098138-e0dda25b-eedb-4a96-810c-b7fc138e9ab6.png)

### What version of Traefik are you using?
```
Version:      2.8.0
Codename:     vacherin
Go version:   go1.17.11
Built:        2022-06-29T15:43:58Z
OS/Arch:      linux/amd64
```
### What is your environment & configuration?

```yaml
version: "3.3"

services:

  traefik:
    image: "traefik:v2.8"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "5000:80"
      - "5001:8080"
     
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  openspeedtest:
    image: "openspeedtest/latest"
    container_name: "speedtest-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openspeedtest.rule=Host(`unraid.vishnu.pro`)"
      - "traefik.http.routers.openspeedtest.entrypoints=web"
```

```
time="2022-07-09T08:37:05Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/upload\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"n=0.36725841504914936\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Accept-Language\":[\"en-US,en;q=0.9,ml;q=0.8\"],\"Connection\":[\"keep-alive\"],\"Content-Length\":[\"31457280\"],\"Content-Type\":[\"application/octet-stream\"],\"Cookie\":[\"_ga=GA1.1.915523062.1654603567; _ga_M7SQP9HBT3=GS1.1.1656487738.10.1.1656488034.0; unraid_9ab9515587850653f020d57cf5338fbe=91c99aa696758bc05c3574b741d5f9d4\"],\"Dnt\":[\"1\"],\"Origin\":[\"http://unraid.vishnu.pro:5000\"],\"Referer\":[\"http://unraid.vishnu.pro:5000/?t=u\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36\"],\"X-Forwarded-Host\":[\"unraid.vishnu.pro:5000\"],\"X-Forwarded-Port\":[\"5000\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"884efa581f66\"],\"X-Real-Ip\":[\"192.168.1.9\"]},\"ContentLength\":31457280,\"TransferEncoding\":null,\"Host\":\"unraid.vishnu.pro:5000\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.1.9:62347\",\"RequestURI\":\"/upload?n=0.36725841504914936\",\"TLS\":null}"
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by openspeedtest** [comment]
Posted : https://community.traefik.io/t/for-http-post-request-net-err-connection-reset/15041

**Comment by openspeedtest** [comment]
https://stackoverflow.com/questions/72925309/traefik-http-post-request-neterr-connection-reset

**Comment by openspeedtest** [comment]
https://www.reddit.com/r/docker/comments/vvf11y/traefik_http_post_request_neterr_connection_reset/

**Comment by openspeedtest** [comment]
https://www.reddit.com/r/Traefik/comments/vvelu5/for_http_post_request_neterr_connection_reset_6/

**Comment by openspeedtest** [comment]
I don't know why i need to add
` "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes
`
now it is working for me.

mytraefik yml
````

version: "3.9"
services:
  traefik:
    image: traefik:v2.8.0
    container_name: traefik
    command:
      - --log.level=INFO
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - 5000:80
      - 5001:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  openspeedtest:
    image: openspeedtest/latest
    container_name: speedtest-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openspeedtest.rule=Host(`192.168.1.15`)"
      - "traefik.http.routers.openspeedtest.entrypoints=web"
      - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=10000000000"
      - "traefik.http.routers.openspeedtest.middlewares=limit"
      - "traefik.http.routers.openspeedtest-https.rule=Host(`192.168.1.15`)"
      - "traefik.http.routers.openspeedtest-https.entrypoints=websecure"
      # - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=10000000000"
      - "traefik.http.routers.openspeedtest-https.middlewares=limit"
      - "traefik.http.routers.openspeedtest-https.tls=true"
      - "traefik.http.routers.openspeedtest-https.tls.certresolver=leresolver"

````
