### ISSUE TITLE
Drop all Ingress host backends when one service port configuration is invalid

### ISSUE THREAD

**Issue by applejag** [traefik/traefik#9181]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Trying to detect misconfigured ingress objects.

We had a case where the service was up and running, but the ingress was misconfigured and pointed to the wrong port. This lead it to respond with HTTP 200, but from the wrong service.

Given two services, named "root" and "api", hosted on `localhost`. We have the following (Kubernetes) Ingress objects:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-root
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: app-root
                port:
                  number: 8080
            path: /
            pathType: Prefix
          - backend:
              service:
                name: app-api
                port:
                  number: 8081 # intentionally wrong port
            path: /api
            pathType: Prefix
```

### What did you see instead?

All requests to `http://localhost/api/` were sent to the `root` service instead of Traefik responding with `503 Service Unavailable` HTTP status. Adding this would be nice. This is backward incompatible change, but allowing to override this with a config would be nice. Something like `--routers.invalidRoute.respond503=true`

Exposing invalid routes through Prometheus would make us able to add alerts on this. I tried enabling [`--metrics.prometheus.addRoutersLabels`](https://doc.traefik.io/traefik/observability/metrics/prometheus/#addrouterslabels) but that doesn't seem to contain any metrics about invalid routes.

### What version of Traefik are you using?

```
Version:      2.7.3
Codename:     epoisses
Go version:   go1.17.11
Built:        2022-06-29T13:48:15Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

<details><summary>YAML manifests to repro issue</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-api
  name: app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-api
  template:
    metadata:
      labels:
        app: app-api
    spec:
      initContainers:
        - name: init
          image: nginx:alpine
          command: [sh, -c]
          args:
            - |
              echo 'index.html from app-api' > /usr/share/nginx/html/index.html
              mkdir /usr/share/nginx/html/api
              echo '{"host": "app-api"}' > /usr/share/nginx/html/api/index.html

          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html

      containers:
        - name: app
          image: nginx:alpine
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html

      volumes:
        - name: html
          emptyDir: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-root
  name: app-root
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-root
  template:
    metadata:
      labels:
        app: app-root
    spec:
      initContainers:
        - name: init
          image: nginx:alpine
          command: [sh, -c]
          args:
            - |
              echo 'index.html from app-root' > /usr/share/nginx/html/index.html
              mkdir /usr/share/nginx/html/api
              echo '{"host": "app-root"}' > /usr/share/nginx/html/api/index.html

          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html

      containers:
        - name: app
          image: nginx:alpine
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html

      volumes:
        - name: html
          emptyDir: {}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-root
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: app-root
                port:
                  number: 8080
            path: /
            pathType: Prefix
          - backend:
              service:
                name: app-api
                port:
                  number: 8081 # intentionally wrong port
            path: /api
            pathType: Prefix

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-root
  name: app-root
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: app-root
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-api
  name: app-api
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: app-api
  type: ClusterIP
```

</details>

With above manifests, I could then port-forward Traefik locally and then run:

```console
$ curl http://localhost/
index.html from app-root

$ curl http://localhost/api/
{"host": "app-root"}
                ^ should've said "app-api", or "503 Service Unavailable"
```

### If applicable, please paste the log output in DEBUG level

```
time="2022-07-12T07:29:54Z" level=error msg="Cannot create service: service port not found" namespace=traefik-test serviceName=app-api servicePort="&ServiceBackendPort{Name:,Number:8081,}" providerName=kubernetes ingress=app-root
```

**Comment by rtribotte** [comment]
Hello @jilleJr,

Thanks for reporting this!

While we understand the use case, and the issue you are facing, adding a new option to allow broken services is something we are not willing to do.

What do you think about modifying the contract and "mount" all the routes of an Ingress only if there are no errors (here with services)? Of course, having the Ingress status updated would be a way to diagnose what happened.

**Comment by jilleJr** [comment]
Hello @rtribotte, thanks for quick response :)

> /.../ adding a new option to allow broken services is something we are not willing to do.

Reasonable. At our company we're discussing ways around this, and if it's really necessary to put energy into this as misconfigurations are very rare and are usually caught during either system integration tests or manual tests. We had one edge case where this issue slipped through though.

Our possible workarounds are either:

- Update `app-root` to respond 404 on `/api/` endpoints
- Update our system test to ensure the `/api/` healthcheck polling ensures JSON response and rejects the HTML response given from the `app-root`'s login redirect.
- Add alerts on error logs by scraping the logs, such as via Loki to Prometheus AlertManager integration

> What do you think about modifying the contract and "mount" all the routes of an Ingress only if there are no errors (here with services)?

That would make sense to me. "If something in the Ingress is broken, then reject it". Is there a technical detail here that makes such an implementation easier than only rejecting the invalid `/api/` route while still allowing `/`?

> Of course, having the Ingress status updated would be a way to diagnose what happened.

This would not help our use case in particular, but it does make sense and would allow 3rd party software to detect when something is wrong easier, as well as be helpful when debugging via `kubectl`

**Comment by rtribotte** [comment]
Hello @jilleJr,

> Our possible workarounds are either:
>   - Update app-root to respond 404 on /api/ endpoints
>   - Update our system test to ensure the /api/ healthcheck polling ensures JSON response and rejects the HTML response given from the app-root's login redirect.
>   - Add alerts on error logs by scraping the logs, such as via Loki to Prometheus AlertManager integration

You can leverage a dummy router catching `/api` with the lowest possible priority value set.
This router could be provided with the file provider and associated with an empty server load balancer to produce 503:
```
http:
  routers:
    api:
      rule: "Host(`localhost`) && PathPrefix(`/api`)"
      service: unavailable
      # lowest possible priority
      # evaluated when no other router is matched (the one from the Ingress)
      priority: 1

  services:
    # Service that will always answer a 503 Service Unavailable response
    unavailable:
      loadBalancer:
        servers: {}
```

In any case, we are considering the issue as a proposal for modifying the Ingress provider behavior and dropping the Ingress resource completely in case of error.

We will change the title of the issue to reflect the proposal goal.

**Comment by mozarik** [comment]
Somewhat i encountered this too

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-main
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: main.zeinfahrozi.club
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: nginx-deploy-main
                port:
                  number: 80
          - path: /blue
            pathType: Exact
            backend:
              service:
                name: nginx-deploy-blue
                port:
                  number: 80
```

But i cannot hit `/blue`. but `/` is work
