### ISSUE TITLE
network `internal: true`

### ISSUE THREAD

**Issue by loynoir** [traefik/traefik#9184]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Given
- traefik and whoami in same network, using docker-compose

### What did you see instead?

Without `docker-compose.networks.X.internal: true` (rebuild from scratch)
- whoami service is OK.

With `docker-compose.networks.X.internal: true` (rebuild from scratch)
- got 404 page not found.
- `http://traefik:8080/dashboard/#/http/services` only 3 builtin services

Same network setting using `nginx-proxy` + `jwilder/whoami`, 200 OK. 

### What version of Traefik are you using?

traefik:v2.8.1@sha256:1212133eacd6dd169f9cdc56161bc866788ec2debf66d7d504acf2fc80233c10

### What is your environment & configuration?

```yaml
# traefik.yml
api:
  insecure: true

log:
  level: DEBUG

providers:
  docker:
    exposedbydefault: false
    endpoint: "unix:///var/run/docker.sock"

```

```yaml
# docker-compose.yml
version: "3.3"

networks:
  foo:
    name: foo
    internal: true

services:
  traefik:
    networks:
      - foo
    image: traefik:v2.8.1@sha256:1212133eacd6dd169f9cdc56161bc866788ec2debf66d7d504acf2fc80233c10
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    networks:
      - foo
    image: traefik/whoami:v1.8.1@sha256:8932271344cf4da580c43c41dbf56a49cb15b250fe60e5dc43530f217eff0daf
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=foo"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.port=80"
```

### If applicable, please paste the log output in DEBUG level

DEBUG level log seems not helpful, same network setting proved can ping each other using `nginx-proxy` + `jwilder/whoami`, below is `traefik` + `traefik/whoami`.

```sh
$ docker-compose logs -f | grep -i whoami
reproduce-whoami-1  | Starting up on port 80
```
