### ISSUE TITLE
Traefik Service does not mirror on different namespace

### ISSUE THREAD

**Issue by Ghiro94** [traefik/traefik#9185]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have updated Traefik deployment on Kubernetes cluster from v2.3 to v2.8(also update CRD definitions). In my configuration on v2.3 version TraefikService correctly mirrors traffic on a Service in a different namespace. When I update to v2.8 TraefikService does not work anymore. Both the service and mirror are impacted.

### What did you see instead?

![image](https://user-images.githubusercontent.com/5656464/178735045-0c26459a-23f7-46e8-aeda-65274bed985a.png)

### What version of Traefik are you using?

v2.8

### What is your environment & configuration?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-1
  name: nginx-1
  namespace: nginx-1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-1
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-2
  name: nginx-2
  namespace: nginx-2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-2
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-1
  name: svc-nginx-1
  namespace: nginx-1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-1
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-2
  name: svc-nginx-2
  namespace: nginx-2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-2
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  labels:
    traefik-ingress: internal
  name: mrr-test
  namespace: nginx-1
spec:
  mirroring:
    mirrors:
    - name: svc-nginx-2
      namespace: nginx-2
      percent: 100
      port: 80
    name: svc-nginx-1
    namespace: nginx-1
    port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
    traefik-ingress: internal
  name: backend-test
  namespace: nginx-1
spec:
  entryPoints:
  - https
  routes:
  - kind: Rule
    match: Host(`devel-test.k8s.nip.io`) && PathPrefix(`/`)
    mirror: true
    services:
    - kind: TraefikService
      name: mrr-test
      port: 80
  tls: {}

```

### If applicable, please paste the log output in DEBUG level

time="2022-07-13T12:24:32Z" level=error msg="Error while building TraefikService: service nginx-2/svc-nginx-2 not in the parent resource namespace nginx-1" providerName=kubernetescrd serviceName=mrr-test
time="2022-07-13T12:24:32Z" level=error msg="the service \"nginx-1-mrr-test@kubernetescrd\" does not exist" routerName=nginx-1-backend-test-b655d80013f8db3bc57b@kubernetescrd entryPointName=https
time="2022-07-13T12:24:44Z" level=error msg="Error while building TraefikService: service nginx-2/svc-nginx-2 not in the parent resource namespace nginx-1" serviceName=mrr-test providerName=kubernetescrd
time="2022-07-13T12:24:44Z" level=error msg="Error while building TraefikService: service nginx-2/svc-nginx-2 not in the parent resource namespace nginx-1" providerName=kubernetescrd serviceName=mrr-test
time="2022-07-13T12:24:44Z" level=error msg="the service \"nginx-1-mrr-test@kubernetescrd\" does not exist" entryPointName=https routerName=nginx-1-backend-test-b655d80013f8db3bc57b@kubernetescrd
