### ISSUE TITLE
Prometheus metrics: Duplicated services in server up gauge

### ISSUE THREAD

**Issue by tringel** [traefik/traefik#9194]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We run several environments as independent clusters.
After updating one of the environments to 2.8 we experienced the traefik_service_server_up gauge in the Prometheus metrics to duplicate the metric for every service.

2.7.2
```
# TYPE traefik_service_server_up gauge
traefik_service_server_up{service="serv1@docker",url="http://172.18.0.10:8888"} 1
traefik_service_server_up{service="serv2@docker",url="http://172.18.0.7:8080"} 1
```

### What did you see instead?

Output with duplicated entries, the URLs match over all of our services (shortened to two here for legibility):

2.8.1
```
# TYPE traefik_service_server_up gauge
traefik_service_server_up{service="serv1@docker",url="http://172.18.0.10:8080"} 1
traefik_service_server_up{service="serv1@docker",url="http://172.18.0.11:8080"} 1
traefik_service_server_up{service="serv2@docker",url="http://172.18.0.10:8080"} 1
traefik_service_server_up{service="serv2@docker",url="http://172.18.0.11:8080"} 1
```

### What version of Traefik are you using?

Correct output:
```
Version:      2.7.2
Codename:     epoisses
Go version:   go1.17.11
Built:        2022-06-27T13:58:55Z
OS/Arch:      linux/amd64
```

Incorrect output:
```
Version:      2.8.1
Codename:     vacherin
Go version:   go1.17.11
Built:        2022-07-11T14:06:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
api:
  dashboard: true
  insecure: false

ping: {}

metrics:
  prometheus:
    manualRouting: true
    addRoutersLabels: true

providers:
  docker:
    exposedByDefault: false
    watch: true
    network: "proxy"
  file:
    directory: "/dynamic"
    watch: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "https"
  https:
    address: ":443"
    http:
      tls: { }
```

Example labels for one of the services:
```yaml
    labels:
      - "traefik.enable=true"
      # Serv1 application
      - "traefik.http.routers.serv1.rule=Host(`qa.serv1.domain.de`)"
      - "traefik.http.routers.serv1.priority=20"
      - "traefik.http.routers.serv1.entrypoints=https"
      - "traefik.http.routers.serv1.service=serv1"
      - "traefik.http.services.serv1.loadbalancer.server.port=8080"
      # Serv1 actuator endpoint
      - "traefik.http.routers.serv1-actuator.rule=(Host(`qa.serv1.domain.de`) && PathPrefix(`/actuator`))"
      - "traefik.http.routers.serv1-actuator.priority=30"
      - "traefik.http.routers.serv1-actuator.entrypoints=https"
      - "traefik.http.routers.serv1-actuator.service=serv1-actuator"
      - "traefik.http.services.serv1-actuator.loadbalancer.server.port=8081"
      # Traefik Health Check for Serv1 application
      - "traefik.http.services.serv1.loadbalancer.healthcheck.scheme=http"
      - "traefik.http.services.serv1.loadbalancer.healthcheck.hostname=serv1"
      - "traefik.http.services.serv1.loadbalancer.healthcheck.port=8081"
      - "traefik.http.services.serv1.loadbalancer.healthcheck.path=/actuator"
      - "traefik.http.services.serv1.loadbalancer.healthcheck.interval=5s"
      - "traefik.http.services.serv1.loadbalancer.healthcheck.timeout=100ms"
```
