### ISSUE TITLE
Wrong certificate is chosen when using `TLSStore` with multiple certificates.

### ISSUE THREAD

**Issue by reitermarkus** [traefik/traefik#9198]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have this `TLSStore` configured in my K8s cluster:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik-system
spec:
  certificates:
    - secretName: example.org
    - secretName: example.com
  defaultCertificate:
    secretName: example.org
```

Both secrets contain wildcard certificates for the respective domains.

I also have this `IngressRoute` deployed:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: app
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`app.example.com`)
      services:
        - name: app
          namespace: default
          port: http
  tls:
    store:
      name: default
```

When I access `https://app.example.com`, I would expect Traefik to choose the matching `example.com` certificate.

### What did you see instead?

When I access `https://app.example.com`, the default `example.org` certificate is chosen.

I expected Traefik to choose the matching `example.com` wildcard certificate.

### What version of Traefik are you using?

2.8.0

### What is your environment & configuration?

Helm values:

```yaml
additionalArguments:
  - --serverstransport.insecureskipverify=true # Don't validate certificates for backends.
  - --providers.kubernetescrd.allowCrossNamespace=true # Allow accessing middlewares across namespaces.
```

### If applicable, please paste the log output in DEBUG level

```
time="2022-07-15T21:32:19Z" level=debug msg="Serving default certificate for request: \"app.example.us\""
```

**Comment by rtribotte** [comment]
Hello @reitermarkus,

Thanks for your interest in Traefik!

The issue seems to be related to an empty or wrong SNI.
Can you share/explain how the client request is made?

To make sure that the client request doesn't contain any SNI or the valid SNI, you can enable temporarily the [SNI strict](https://doc.traefik.io/traefik/master/https/tls/#strict-sni-checking) option.

**Comment by reitermarkus** [comment]
> Can you share/explain how the client request is made?

The request is made using a browser, i.e. visiting the URL.

> you can enable the [SNI strict](https://doc.traefik.io/traefik/master/https/tls/#strict-sni-checking) option temporarily

Okay, I deployed

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: default
  namespace: traefik-system
spec:
  sniStrict: true
```

and it seems to be related to empty or wrong SNI. 

With strict SNI, I am getting an “unrecognized name” error, with Chromium, Safari and `curl`.
