### ISSUE TITLE
Allow to set name for rules in IngressRoute

### ISSUE THREAD

**Issue by longshine** [traefik/traefik#9207]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

It would be great if name can be defined for `routes` in IngressRoute.

For example:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: foo
  namespace: bar
spec:
  routes:
  - kind: Rule
    name: hello  # Give a name to this rule
    services:
    - name: world
```

Will generate a rule with name `bar-foo-hello` and a service with name `bar-foo-hello-world`.

Currently there is no such `name` field, and it will generate names like `bar-foo-d012b7f875133eeab4e5`, which is quite difficult to understand in logs or metrics.
