### ISSUE TITLE
Config array plugin bug in Yaegi plugin validator

### ISSUE THREAD

**Issue by mrinc** [traefik/traefik#9217]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Related too past bug report: #8885

### What did you see instead?

current issue: https://github.com/BetterCorp/cloudflarewarp/issues/9 

```
failed to run the plugin with Yaegi: failed to create a new plugin instance: invalid CIDR address: 10.0.0.0/8║172.0.0.0/8║192.0.0.0/8  
```  

### What version of Traefik are you using?

2.8.0 - but irrelevant since the issue is with the plugin validator

### What is your environment & configuration?

`.traefik.yml`  file:  

```
displayName: Real IP from Cloudflare WARP
type: middleware
import: github.com/BetterCorp/cloudflarewarp

summary: get real IP and proto from Cloudflare WARP

testData:
  disableDefault: false
  trustip:  
    - 10.0.0.0/8  
    - 172.0.0.0/8  
    - 192.0.0.0/8  
```   

I run tests by spinning up traefik to make sure the plugin works:  https://github.com/BetterCorp/cloudflarewarp/tree/master/test/config

So I know the config and plugin works, but the validator isn't parsing the test data correctly.  
Test run: https://github.com/BetterCorp/cloudflarewarp/actions/runs/2756756514

I also wrote yaegi tests right into the workflow to mitigate this type of issue occurring however it doesn't seem to have helped: https://github.com/BetterCorp/cloudflarewarp/runs/7568748739?check_suite_focus=true#step:11:1
