### ISSUE TITLE
Cannot renew/generate certificates (acme: error presenting token)

### ISSUE THREAD

**Issue by arulagrawal** [traefik/traefik#9232]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am using traefik with docker-compose.
Noticed that my certs were not renewing as they were in the past.
Found the logs below:

### What did you see instead?

```time="2022-08-05T12:09:03Z" level=info msg="Configuration loaded from file: /traefik.yml"
time="2022-08-05T12:09:05Z" level=error msg="Error renewing certificate from LE: {irc.arul.io []}, error: one or more domains had a problem:\n[irc.arul.io] [irc.arul.io] acme: error presenting token: njalla: failed to add record: failed to unmarshal response result: json: cannot unmarshal string into Go struct field Record.id of type int\n" providerName=http.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"
time="2022-08-05T12:09:07Z" level=error msg="Error renewing certificate from LE: {arul.io [*.arul.io]}, error: one or more domains had a problem:\n[*.arul.io] [*.arul.io] acme: error presenting token: njalla: failed to add record: failed to unmarshal response result: json: cannot unmarshal string into Go struct field Record.id of type int\n[arul.io] [arul.io] acme: error presenting token: njalla: failed to add record: failed to unmarshal response result: json: cannot unmarshal string into Go struct field Record.id of type int\n" ACME CA="https://acme-v02.api.letsencrypt.org/directory" providerName=http.acme
time="2022-08-05T12:09:09Z" level=error msg="Error renewing certificate from LE: {*.update.arul.io []}, error: one or more domains had a problem:\n[*.arul.io] [*.arul.io] acme: error presenting token: njalla: failed to add record: failed to unmarshal response result: json: cannot unmarshal string into Go struct field Record.id of type int\n[*.update.arul.io] [*.update.arul.io] acme: error presenting token: njalla: failed to add record: failed to unmarshal response result: json: cannot unmarshal string into Go struct field Record.id of type int\n[arul.io] [arul.io] acme: error presenting token: njalla: failed to add record: failed to unmarshal response result: json: cannot unmarshal string into Go struct field Record.id of type int\n" providerName=http.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"
```

### What version of Traefik are you using?

Version:      2.8.1
Codename:     vacherin
Go version:   go1.17.11
Built:        2022-07-11T14:06:57Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
#experimental:
#  http3: true

#log:
  #  level: DEBUG

ping: {}
api:
  dashboard: true
  debug: false

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
  https:
    #http3: {}
    address: ":443"
    http:
      middlewares:
        - default-headers@file
      tls:
        certResolver: http
        domains:
          - main: "arul.io"
            sans:
              - "*.arul.io"
              - "*.update.arul.io"
  tcps:
    address: ":7000"

providers:
  providersThrottleDuration: 100
  docker:
    endpoint: "tcp://dockerproxy:2375"
    exposedByDefault: false
    network: web
    defaultRule: Host(`{{ index .Labels "com.docker.compose.service" }}.arul.io`)
  file:
    filename: /config.yml

certificatesResolvers:
  http:
    acme:
      email: me@arul.io
      storage: acme.json
      dnsChallenge:
        provider: njalla
        delayBeforeCheck: 1200
        resolvers:
          - "9.9.9.9:53"
          - "8.8.8.8:53"
```
I tried with and without delayBeforeCheck and providersThrottleDuration (I found these on other issues)

Add more configuration information here.
config.yml:
```yaml
http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https

    default-headers:
      headers:
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        contentSecurityPolicy: "upgrade-insecure-requests"
        referrerPolicy: "strict-origin-when-cross-origin"
        customResponseHeaders:
          Permissions-Policy: "geolocation=(), camera=(), fullscreen=*, interest-cohort=(), browsing-topics=()"
          X-Frame-Options: "SAMEORIGIN"
          Server: ""

    default-whitelist:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/24"
          - "192.168.0.0/16"
          - "172.0.0.0/8"

    comp:
      compress: {}

    secured:
      chain:
        middlewares:
          - default-whitelist
          - default-headers
          - comp

tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      curvePreferences:
        - CurveP521
        - CurveP384
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
```

docker-compose.yml:
```yaml
version: '3.4'

services:
  dockerproxy:
    restart: unless-stopped
    image: tecnativa/docker-socket-proxy
    networks:
      - docker_proxy
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - NETWORKS=1
      - TASKS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 2375

  traefik:
    image: traefik:vacherin
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
        #  - 443:443/udp
      - 7000:7000
    volumes:
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/config.yml:/config.yml:ro
      - ./data/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.rule=Host(`traefik.arul.io`)"
      - "traefik.http.routers.traefik.middlewares=authentik@docker"
      - "traefik.http.routers.traefik.service=api@internal"
    environment:
      NJALLA_TOKEN: ${NJALLA_TOKEN}
    healthcheck:
      test: wget -q --spider http://localhost:8080/ping
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - web
      - docker_proxy

networks:
  web:
    external: true
  docker_proxy:
    external: false
```
