### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by kevinirlen** [traefik/traefik#9239]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am using traefik:roquefort on docker. When I run `docker-compose up -d`, it downloads traefik, but then it keeps restarting.

I expected it to work.

Then i run `docker-compose logs`, to see what's going on. I got a panic error

### What did you see instead?

This is the docker-compose log

```
panic: runtime error: slice bounds out of range
traefik  |
traefik  | goroutine 1 [running]:
traefik  | github.com/containous/traefik/vendor/github.com/miekg/dns.ClientConfigFromFile(0x1f6bcfd, 0x10, 0x0, 0x0, 0x0)
traefik  | 	/go/src/github.com/containous/traefik/vendor/github.com/miekg/dns/clientconfig.go:86 +0xad6
traefik  | github.com/containous/traefik/vendor/github.com/xenolf/lego/acme.getNameservers(0x1f6bcfd, 0x10, 0x2f2a7a0, 0x2, 0x2, 0xc42000e280, 0xc4201f3f50, 0x6958b2)
traefik  | 	/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/acme/dns_challenge.go:40 +0x4d
traefik  | github.com/containous/traefik/vendor/github.com/xenolf/lego/acme.init()
traefik  | 	/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/acme/dns_challenge.go:33 +0x12d
traefik  | github.com/containous/traefik/acme.init()
traefik  | 	<autogenerated>:1 +0x84
traefik  | main.init()
traefik  | 	<autogenerated>:1 +0x75
traefik  | panic: runtime error: slice bounds out of range
```

### What version of Traefik are you using?

Traefik 1.4

### What is your environment & configuration?

docker-compose.yaml

```yaml
version: '2'

services:
    traefik:
        container_name: traefik
        image: traefik:roquefort
        restart: "always"
        command: -c /dev/null --configFile=/etc/traefik/traefik.toml --debug
        networks:
            - reverse_proxy
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            #comment or uncommend
            #- traefik.toml:/etc/traefik/traefik.toml:delegated
            - ./traefik.toml:/etc/traefik/traefik.toml:delegated
            - /var/run/docker.sock:/var/run/docker.sock

networks:
    reverse_proxy:
        external: true

```

traefik.toml

```yaml
logLevel = "DEBUG"

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "mydomain.localhost"
```

More information:

Linux Mint 21 (Vanessa)
Docker Version: 20.10.12
Docker Compose version v2.9.0
