### ISSUE TITLE
Traefik does not start after docker image upgrade to 2.8.2 (latest)

### ISSUE THREAD

**Issue by alexanderhofstaetter** [traefik/traefik#9251]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

After upgrading our traefik docker to 2.8.2, traefik does not start anymore, all sites where on error. After an downgrade to 2.8.1 everything is working again. We are running docker on ubuntu 20.04.4 LTS.

### What did you see instead?

```
time="2022-08-12T09:10:25+02:00" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
time="2022-08-12T09:10:25+02:00" level=error msg="Error in Go routine: runtime error: slice bounds out of range [2:1]"
time="2022-08-12T09:10:25+02:00" level=error msg="Stack: goroutine 67 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine({0x36a75c0?, 0xc0000a4978})\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:66 +0xa5\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1.1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:56 +0x36\npanic({0x36a75c0, 0xc0000a4978})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/paerser/parser.filler.setSlice({{0x1c?, {0x3989c0e?, 0x0?}}}, {0x2ff49c0?, 0xc000103d88?, 0x354fbdd?}, 0xc000222b40)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:157 +0xaa5\ngithub.com/traefik/paerser/parser.filler.fill({{0x40?, {0x3989c0e?, 0x7?}}}, {0x2ff49c0?, 0xc000103d88?, 0x0?}, 0xc0008ac740?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:105 +0x477\ngithub.com/traefik/paerser/parser.filler.setStruct({{0x40?, {0x3989c0e?, 0x2e052ac?}}}, {0x38e4f40?, 0xc000103d40?, 0xc0008ac818?}, 0x4a2e28?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x178\ngithub.com/traefik/paerser/parser.filler.fill({{0xa0?, {0x3989c0e?, 0x3306580?}}}, {0x38e4f40?, 0xc000103d40?, 0xc0001b89c0?}, 0x32956e0?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x4b3\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x7?, {0x3989c0e?, 0x0?}}}, {0x34af1a0?, 0xc0001b89f8?, 0x32956e8?}, 0x58?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x20?, {0x3989c0e?, 0x447fe98?}}}, {0x34af1a0?, 0xc0001b89f8?, 0x5e?}, 0xc0008ac9c0?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setStruct({{0xc0?, {0x3989c0e?, 0x2d8dfd4?}}}, {0x3891120?, 0xc0001b89c0?, 0xc0008aca98?}, 0x4a2e28?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x178\ngithub.com/traefik/paerser/parser.filler.fill({{0x20?, {0x3989c0e?, 0x3306580?}}}, {0x3891120?, 0xc0001b89c0?, 0x349bc00?}, 0xc0008acb50?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x4b3\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x88?, {0x3989c0e?, 0x39a1241?}}}, {0x32c8e20?, 0xc000206388?, 0xc0008acba8?}, 0x4a2e28?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x0?, {0x3989c0e?, 0x3306580?}}}, {0x32c8e20?, 0xc000206388?, 0x203000?}, 0xc00003c680?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x90?, {0x3989c0e?, 0x411cc4?}}}, {0xc0000a8700?, 0xc000206370?, 0x960000c00003c680?}, 0x4?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x40?, {0x3989c0e?, 0x491efd?}}}, {0xc0000a8700?, 0xc000206370?, 0x349bc00?}, 0xc0008acd70?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x8b?, {0x3989c0e?, 0x46b087?}}}, {0xc0000a8740?, 0xc000206370?, 0x1?}, 0xc0008acdc8?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x98?, {0x3989c0e?, 0x1?}}}, {0xc0000a8740?, 0xc000206370?, 0x98?}, 0x32c8e20?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setMap({{0xb?, {0x3989c0e?, 0x0?}}}, {0x3230760?, 0xc0002b8a00?, 0x334faff?}, 0xc000222750)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:308 +0x3e5\ngithub.com/traefik/paerser/parser.filler.fill({{0x60?, {0x3989c0e?, 0x4?}}}, {0x3230760?, 0xc0002b8a00?, 0x0?}, 0x0?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:103 +0x44f\ngithub.com/traefik/paerser/parser.filler.setStruct({{0x80?, {0x3989c0e?, 0xc000280188?}}}, {0x367f560?, 0xc0002b89f0?, 0x31ce40b?}, 0x4f?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x178\ngithub.com/traefik/paerser/parser.filler.fill({{0xa0?, {0x3989c0e?, 0x199?}}}, {0x367f560?, 0xc0002b89f0?, 0xc000476b80?}, 0x31ce406?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x4b3\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x4?, {0x3989c0e?, 0x0?}}}, {0x32c8ba0?, 0xc000476b80?, 0x31ce40b?}, 0x4f?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x60?, {0x3989c0e?, 0x98?}}}, {0x32c8ba0?, 0xc000476b80?, 0xc0003bf5d8?}, 0x398aac3?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setStruct({{0x18?, {0x3989c0e?, 0x1?}}}, {0x35e3060?, 0xc000476b80?, 0xc0008ad338?}, 0x1af1bb9?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x178\ngithub.com/traefik/paerser/parser.filler.fill({{0xa0?, {0x3989c0e?, 0x4?}}}, {0x35e3060?, 0xc000476b80?, 0xc0008ad3c0?}, 0x1af1a26?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x4b3\ngithub.com/traefik/paerser/parser.filler.Fill({{0xa0?, {0x3989c0e?, 0x32c87a0?}}}, {0x32c87a0?, 0xc000476b80?}, 0xc000222630)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:58 +0x13d\ngithub.com/traefik/paerser/parser.Fill({0x32c87a0?, 0xc000476b80?}, 0x4?, {0xa0?, {0x3989c0e?, 0xc000222630?}})\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:28 +0x59\ngithub.com/traefik/paerser/file.DecodeContent({0xc00054d880, 0x342}, {0xc000634e54, 0x4}, {0x32c87a0, 0xc000476b80})\n\tgithub.com/traefik/paerser@v0.1.6/file/file.go:83 +0x1d8\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).decodeConfiguration(0xc0000a81c0?, {0xc000634e40, 0x18}, {0xc00054d880, 0x342})\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:522 +0x31d\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).CreateConfiguration(0xc00063f170, {0x4458090, 0xc0002b8600}, {0xc000634e40, 0x18}, 0x3306600?, {0x3021fc0, 0x61ccfe0})\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:486 +0x746\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).loadFileConfig(0x4458020?, {0x4458090, 0xc0002b8600}, {0xc000634e40, 0x18}, 0xbf?)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:160 +0xfb\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).BuildConfiguration(0xc00063f170)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:85 +0xca\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).Provide(0xc00063f170, 0xc000476b60?, 0x443ca50?)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:49 +0x2f\ngithub.com/traefik/traefik/v2/pkg/provider/aggregator.maybeThrottledProvide.func1(0xc0007b6de0, 0xc00063f170?)\n\tgithub.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:57 +0xcf\ngithub.com/traefik/traefik/v2/pkg/provider/aggregator.ProviderAggregator.launchProvider({{0x443d298, 0xc000189480}, {0x443ca50, 0xc00063f170}, {0xc000421540, 0x3, 0x4}, 0x77359400}, 0x0?, 0xc00087edb0, ...)\n\tgithub.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:208 +0x339\ngithub.com/traefik/traefik/v2/pkg/provider/aggregator.ProviderAggregator.Provide({{0x443d298, 0xc000189480}, {0x443ca50, 0xc00063f170}, {0xc000421540, 0x3, 0x4}, 0x77359400}, 0xc0007b6de0, 0xc00087edb0)\n\tgithub.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:180 +0xb0\ngithub.com/traefik/traefik/v2/pkg/server.(*ConfigurationWatcher).startProviderAggregator.func1()\n\tgithub.com/traefik/traefik/v2/pkg/server/configurationwatcher.go:76 +0x48\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:59 +0x5b\ncreated by github.com/traefik/traefik/v2/pkg/safe.GoWithRecover\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:53 +0x72\n"
root@container3:~# ^C
```

### What version of Traefik are you using?

NOT WORKING on 2.8.2:

Version:      2.8.2
Codename:     vacherin
Go version:   go1.19
Built:        2022-08-11T14:55:50Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml traefik.yml 
global:
  checkNewVersion: true
  
serversTransport:
  insecureSkipVerify: true
  
entryPoints:
  http:
    address: ':80'
    forwardedHeaders:
      trustedIPs:
        - 173.y.x.0/20
#    http:
#      redirections:
#        entryPoint:
#          to: https          
  
  https:
    address: ':443'
    forwardedHeaders:
      trustedIPs:
        - 173.y.x.0/20
    http:
      middlewares:
        - http-to-https@file
        - secure-headers@file
        
      tls:
        certResolver: letsencrypt

providers:
  docker:
    watch: true
    exposedByDefault: false
    network: proxy_intern
  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true
  
api:
  dashboard: true
  
certificatesResolvers:
  letsencrypt:
    acme:
      storage: '/etc/traefik/acme/acme.json'
      email: 'admin@example.org'
      httpChallenge:
        entrypoint: http
```

```yaml dynamic.yml 
http:
  middlewares:
            
    http-to-https:
      redirectScheme:
        scheme: https
        permanent: true
        
    secure-headers:
      headers:
        sslRedirect: true
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        browserXssFilter: true
        accesscontrolalloworiginlist: '*'
                
tls:
  options:
    default:
      sniStrict: true
      preferServerCipherSuites: true
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
```

Add more configuration information here.
