### ISSUE TITLE
Traefik 2.8.2 unable to start

### ISSUE THREAD

**Issue by dguihal** [traefik/traefik#9252]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hello Traefik team, I met a string issue while upgrading from traefik 2.8.1 to 2.8.2 using public docker images

traefik 2.8.1 works perfectly fine
traefik 2.8.2 fails at  startup

### What did you see instead?

Startup failure

> goroutine 1 [running]:
> github.com/traefik/paerser/parser.filler.setSlice({{0xb?, {0x3989c0e?, 0x0?}}}, {0x2ff49c0?, 0xc0003e8810?, 0x35c3256?}, 0xc00032ddd0)
>         github.com/traefik/paerser@v0.1.6/parser/element_fill.go:157 +0xaa5
> github.com/traefik/paerser/parser.filler.fill({{0x40?, {0x3989c0e?, 0x352aa40?}}}, {0x2ff49c0?, 0xc0003e8810?, 0x28?}, 0xc0005d4fa8?)
>         github.com/traefik/paerser@v0.1.6/parser/element_fill.go:105 +0x477
> github.com/traefik/paerser/parser.filler.setStruct({{0x4?, {0x3989c0e?, 0x0?}}}, {0x352aa40?, 0xc0003e8808?, 0x33881d7?}, 0x71?)
>         github.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x178
> github.com/traefik/paerser/parser.filler.fill({{0x20?, {0x3989c0e?, 0x8?}}}, {0x352aa40?, 0xc0003e8808?, 0x0?}, 0x0?)
>         github.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x4b3
> github.com/traefik/paerser/parser.filler.setStruct({{0x68?, {0x3989c0e?, 0x398a1c7?}}}, {0x3778720?, 0xc0003e87e0?, 0x0?}, 0x447fe98?)
>         github.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x178
> github.com/traefik/paerser/parser.filler.fill({{0xc0?, {0x3989c0e?, 0x3306580?}}}, {0x3778720?, 0xc0003e87e0?, 0x349bc00?}, 0xc0009ad560?)
>         github.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x4b3
> github.com/traefik/paerser/parser.filler.setPtr({{0x68?, {0x3989c0e?, 0x39a1241?}}}, {0x33745c0?, 0xc000013268?, 0xc0009ad5b8?}, 0x4a2e28?)
>         github.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b
> github.com/traefik/paerser/parser.filler.fill({{0x40?, {0x3989c0e?, 0x3306580?}}}, {0x33745c0?, 0xc000013268?, 0xc0009ad610?}, 0xc0009ad680?)
>         github.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465
> github.com/traefik/paerser/parser.filler.setPtr({{0x8?, {0x3989c0e?, 0xc0009ad700?}}}, {0xc000337c40?, 0xc000013260?, 0x322c920?}, 0xc00056de90?)
>         github.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b
> github.com/traefik/paerser/parser.filler.fill({{0x80?, {0x3989c0e?, 0xc00005dcd0?}}}, {0xc000337c40?, 0xc000013260?, 0x389cfa0?}, 0xc0009ad780?)
>         github.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465
> github.com/traefik/paerser/parser.filler.setPtr({{0xe0?, {0x3989c0e?, 0x46b087?}}}, {0xc000337c80?, 0xc000013260?, 0x1?}, 0xc0009ad7d8?)
>         github.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b
> github.com/traefik/paerser/parser.filler.fill({{0x98?, {0x3989c0e?, 0x2?}}}, {0xc000337c80?, 0xc000013260?, 0x98?}, 0x34d00fc?)
>         github.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465
> github.com/traefik/paerser/parser.filler.setMap({{0xb?, {0x3989c0e?, 0x0?}}}, {0x3306700?, 0xc00032d2a0?, 0x34d0109?}, 0xc00032db90)
>         github.com/traefik/paerser@v0.1.6/parser/element_fill.go:308 +0x3e5
> github.com/traefik/paerser/parser.filler.fill({{0x0?, {0x3989c0e?, 0xc0005e4120?}}}, {0x3306700?, 0xc00032d2a0?, 0xc00005da20?}, 0x398aac3?)
>         github.com/traefik/paerser@v0.1.6/parser/element_fill.go:103 +0x44f
> github.com/traefik/paerser/parser.filler.setStruct({{0x18?, {0x3989c0e?, 0x1?}}}, {0x3477300?, 0xc00032d290?, 0xc0009adac8?}, 0x1af1bb9?)
>         github.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x178
> github.com/traefik/paerser/parser.filler.fill({{0xc0?, {0x3989c0e?, 0x4?}}}, {0x3477300?, 0xc00032d290?, 0xc0009adb50?}, 0x1af1a26?)
>         github.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x4b3
> github.com/traefik/paerser/parser.filler.Fill({{0xc0?, {0x3989c0e?, 0x34aefc0?}}}, {0x34aefc0?, 0xc00032d290?}, 0xc00032d440)
>         github.com/traefik/paerser@v0.1.6/parser/element_fill.go:58 +0x13d
> github.com/traefik/paerser/parser.Fill({0x34aefc0?, 0xc00032d290?}, 0xc0001a05a0?, {0xc0?, {0x3989c0e?, 0xc00032d440?}})
>         github.com/traefik/paerser@v0.1.6/parser/element_fill.go:28 +0x59
> github.com/traefik/paerser/file.Decode({0xc0005d60f0, 0x18}, {0x34aefc0, 0xc00032d290})
>         github.com/traefik/paerser@v0.1.6/file/file.go:37 +0xc5
> github.com/traefik/traefik/v2/pkg/cli.loadConfigFiles({0x0?, 0x0?}, {0x34aefc0, 0xc00032d290})
>         github.com/traefik/traefik/v2/pkg/cli/loader_file.go:81 +0x1e9
> github.com/traefik/traefik/v2/pkg/cli.(*FileLoader).Load(0xc000819500, {0xc000120000?, 0x8?, 0x0?}, 0xc00072dd80)
>         github.com/traefik/traefik/v2/pkg/cli/loader_file.go:44 +0x189
> github.com/traefik/paerser/cli.run(0xc00072dd80, {0xc000120000?, 0x0, 0x0})
>         github.com/traefik/paerser@v0.1.6/cli/commands.go:124 +0x1e3
> github.com/traefik/paerser/cli.execute(0xc00072dd80, {0xc000120000?, 0x2, 0x2}, 0xb8?)
>         github.com/traefik/paerser@v0.1.6/cli/commands.go:76 +0x74a
> github.com/traefik/paerser/cli.Execute(...)
>         github.com/traefik/paerser@v0.1.6/cli/commands.go:51
> main.main()
>         github.com/traefik/traefik/v2/cmd/traefik/traefik.go:78 +0x405
> panic: runtime error: slice bounds out of range [2:1]

### What version of Traefik are you using?

Version:      2.8.2
Codename:     vacherin
Go version:   go1.19
Built:        2022-08-11T14:55:50Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
keepTrailingSlash: true

accessLog:

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: web

# API and dashboard configuration
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      middlewares: "crowdsec-bouncer@docker"
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"
    http:
      middlewares: "crowdsec-bouncer@docker"
      tls:
        certResolver: "gandi"

certificatesResolvers:
  gandi:
    acme:
      email: "redacted@provider.com"
      storage: "/acme.json"
      dnsChallenge:
        provider: gandiv5

tls:
  options:
    default:
      minVersion: VersionTLS12

log:
  level: "INFO"
  filePath: "/log/traefik.log"

accesslog:
  filepath: "/log/traefik-access.log"
```

Public docker images

Traefik 2.8.1 worked perfectly fine

### If applicable, please paste the log output in DEBUG level

same output
