### ISSUE TITLE
docker provider did support `traefik.http.services.serviceA.loadbalancer.server.url="http://ip:port"` field

### ISSUE THREAD

**Issue by yuanyp8** [traefik/traefik#9254]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

**traefik config**
```yaml
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    swarmMode: false  # 是否启用Docker Swarm
    exposedByDefault: false
```

**start a docker container to registry a service in traefik called 'serviceA'**
```shell
# docker run -itd \
> --name whoamiA \
> -p 881:80 \
> --label 'traefik.enable=true' \
> --label 'traefik.http.routers.serviceA.rule=Host("svca.gateway.metavarse.tech")'  \
> --label 'traefik.http.services.serviceA.loadbalancer.server.url="http://172.20.94.159:881"'  \
> traefik/whoami
```

**The ServiceA**
![image](https://user-images.githubusercontent.com/51024420/184327745-89ea6c93-e0de-43ee-a1ba-73bdb987658c.png)

### What did you see instead?

find in the traefik log

```json
{"level":"debug","msg":"Provider event received {Status:start ID:8d957a89c44daefc90a55db7189e1a0bdbc09e05acb2f3d15b7643c3ad1ec280 From:traefik/whoami Type:container Action:start Actor:{ID:8d957a89c44daefc90a55db7189e1a0bdbc09e05acb2f3d15b7643c3ad1ec280 Attributes:map[image:traefik/whoami name:whoamiA traefik.enable:true traefik.http.routers.serviceA.rule:Host(\"svca.gateway.metavarse.tech\") traefik.http.services.serviceA.loadbalancer.server.url:\"http://172.20.94.159:881\"]} Scope:local Time:1660296932 TimeNano:1660296932519213519}","providerName":"docker","time":"2022-08-12T17:35:32+08:00"}
```

```json
{"entryPointName":"https","level":"debug","msg":"Creating load-balancer","routerName":"serviceA@docker","serviceName":"serviceA","time":"2022-08-12T17:35:52+08:00"}
{"entryPointName":"https","level":"debug","msg":"Creating server 0 http://172.17.0.4:80","routerName":"serviceA@docker","serverName":0,"serviceName":"serviceA","time":"2022-08-12T17:35:52+08:00"}
{"level":"debug","msg":"child http://172.17.0.4:80 now UP","time":"2022-08-12T17:35:52+08:00"}
{"level":"debug","msg":"Propagating new UP status","time":"2022-08-12T17:35:52+08:00"}
```

## add more
The reason I use the `url` option instead of the `port` option is because the default IP of the `port` option is the virtual IP of the Docker network, which is not what I expected

### What version of Traefik are you using?

```shell
Version:      2.8.1
Codename:     vacherin
Go version:   go1.17.11
Built:        2022-07-11T14:06:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
api:
  dashboard: true # Enable the dashboard
  insecure: true
  debug: true
log:
  filePath: "/var/log/traefik/traefik.log"
  level: DEBUG
  format: json
accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  bufferingSize: 100

certificatesResolvers:
  letsEncrypt:
    acme:
      email: "geniusgavin@163.com" # Email address used for registration
      storage: "/etc/traefik/acme/acme.json" # File or key used for certificates storage
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: alidns
        delayBeforeCheck: 30
entryPoints:
  http:
    address: ":80" # Create the HTTP entrypoint on port 80
    forwardedHeaders:
      insecure: true
  https:
    address: ":443" # Create the HTTPS entrypoint on port 443
  traefik:
    address: ":8081"
global:
  checknewversion: true # Periodically check if a new version has been released.
  sendanonymoususage: false # Periodically send anonymous usage statistics.

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    swarmMode: false  # 是否启用Docker Swarm
    exposedByDefault: false

  file:
    directory: "/etc/traefik/dynamic/"
    filename: "*.yaml" # Link to the dynamic configuration
    watch: true # Watch for modifications
  providersThrottleDuration: 30 # Configuration reload frequency
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

none
