### ISSUE TITLE
Update to 2.8.2 bricks traefik

### ISSUE THREAD

**Issue by nils1323** [traefik/traefik#9255]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Update from docker 2.8.1 to 2.8.2

### What did you see instead?

Traefik is not starting up correctly anymore. And every page is displayed as 404. 

Downgrading to 2.8.1 fixes the problem

### What version of Traefik are you using?

Version:      2.8.2
Codename:     vacherin
Go version:   go1.19
Built:        2022-08-11T14:55:50Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

traefik.yml
```yaml
providers:
  docker:
    exposedByDefault: false
    network: behind_traefik
  file:
    directory: /config/dynamic_conf
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: false
  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true
    http:
      tls: true

certificatesResolvers:
  lets-encrypt:
    acme:
      email: "priv@priv.de"
      storage: "/letsencrypt/acme.json"
      tlschallenge: true
api:
  dashboard: true
  insecure: true

log:
  level: DEBUG
```

dynamic_conf.yml
```yaml
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    mintls13:
      minVersion: VersionTLS13

http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: false
    sslheader:
      headers:
        customrequestheaders:
          X-Forwarded-Proto: https
    secHeaders:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        sslRedirect: true
    priv-auth:
      basicAuth:
        users:
          - "REMOVED:$REMOVED"
    redirect-to-unraid:
      redirectRegex:
        regex: ".*"
        replacement: "REMOVED"
        permanent: false
    internal-services:
      ipWhiteList:
        sourceRange:
          - "PRIV NETWORK/24"
          # whitelist dockerinternal network
          - "172.16.0.0/12"
          - "PUBLIC IP/32"

  services:
    unraid:
      loadBalancer:
        servers:
        - url: "removed:4443"

  routers:
    proxy-secure:
      rule: "Host(`REMOVED`)"
      entrypoints: websecure
      middlewares:
        - priv-auth
      service: api@internal
      tls:
        certResolver: lets-encrypt
    unraid:
      rule: "Host(`removed`)"
      entrypoints: websecure
      service: unraid
      middlewares:
        - internal-services
      tls:
        certResolver: lets-encrypt
    unraid-redirect:
      rule: "Host(`removed`)"
      entrypoints: websecure
      service: noop@internal
      middlewares:
        - redirect-to-unraid
      tls:
        certResolver: lets-encrypt

```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

time="2022-08-12T11:53:57+02:00" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
time="2022-08-12T11:53:57+02:00" level=info msg="Traefik version 2.8.2 built on 2022-08-11T14:55:50Z"
time="2022-08-12T11:53:57+02:00" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}},\"web\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{\"redirections\":{\"entryPoint\":{\"to\":\"websecure\",\"scheme\":\"https\",\"priority\":2147483646}}},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}},\"websecure\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{\"insecure\":true},\"http\":{\"tls\":{}},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"network\":\"behind_traefik\",\"swarmModeRefreshSeconds\":\"15s\"},\"file\":{\"directory\":\"/config/dynamic_conf\",\"watch\":true}},\"api\":{\"insecure\":true,\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"certificatesResolvers\":{\"lets-encrypt\":{\"acme\":{\"email\":\"priv\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"/letsencrypt/acme.json\",\"keyType\":\"RSA4096\",\"certificatesDuration\":2160,\"tlsChallenge\":{}}}},\"pilot\":{\"dashboard\":true}}"
time="2022-08-12T11:53:57+02:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
time="2022-08-12T11:53:57+02:00" level=warning msg="Traefik Pilot is deprecated and will be removed soon. Please check our Blog for migration instructions later this year."
time="2022-08-12T11:53:57+02:00" level=info msg="Starting provider aggregator aggregator.ProviderAggregator"
time="2022-08-12T11:53:57+02:00" level=debug msg="Starting TCP Server" entryPointName=web
time="2022-08-12T11:53:57+02:00" level=debug msg="Starting TCP Server" entryPointName=websecure
time="2022-08-12T11:53:57+02:00" level=debug msg="Starting TCP Server" entryPointName=traefik
time="2022-08-12T11:53:57+02:00" level=info msg="Starting provider *file.Provider"
time="2022-08-12T11:53:57+02:00" level=debug msg="*file.Provider provider configuration: {\"directory\":\"/config/dynamic_conf\",\"watch\":true}"
time="2022-08-12T11:53:57+02:00" level=error msg="Error in Go routine: runtime error: slice bounds out of range [2:1]"
time="2022-08-12T11:53:57+02:00" level=error msg="Stack: goroutine 82 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine({0x36a75c0?, 0xc000054e88})\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:66 +0xa5\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1.1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:56 +0x36\npanic({0x36a75c0, 0xc000054e88})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/paerser/parser.filler.setSlice({{0xb?, {0x3989c0e?, 0x0?}}}, {0x2ff49c0?, 0xc000d62540?, 0x334f7e1?}, 0xc000a4b290)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:157 +0xaa5\ngithub.com/traefik/paerser/parser.filler.fill({{0xe0?, {0x3989c0e?, 0x447fe98?}}}, {0x2ff49c0?, 0xc000d62540?, 0x61?}, 0xc000d7a080?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:105 +0x477\ngithub.com/traefik/paerser/parser.filler.setStruct({{0x40?, {0x3989c0e?, 0x2d8dfd4?}}}, {0x36cfce0?, 0xc000d62540?, 0xc000d7a158?}, 0x4a2e28?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x178\ngithub.com/traefik/paerser/parser.filler.fill({{0xa0?, {0x3989c0e?, 0x3306580?}}}, {0x36cfce0?, 0xc000d62540?, 0x349bc00?}, 0xc000d7a210?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x4b3\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x58?, {0x3989c0e?, 0x39a1241?}}}, {0x32c93a0?, 0xc000128958?, 0xc000d7a268?}, 0x4a2e28?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x80?, {0x3989c0e?, 0x3306580?}}}, {0x32c93a0?, 0xc000128958?, 0xc000d7a2c0?}, 0xc000d7a330?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x8?, {0x3989c0e?, 0xc000d7a3b0?}}}, {0xc00023aa80?, 0xc000128950?, 0x322c920?}, 0xc000ad1e00?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0xc0?, {0x3989c0e?, 0xc000ad2220?}}}, {0xc00023aa80?, 0xc000128950?, 0x389cfa0?}, 0xc000d7a430?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setPtr({{0xe0?, {0x3989c0e?, 0x46b087?}}}, {0xc00023aac0?, 0xc000128950?, 0x1?}, 0xc000d7a488?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x98?, {0x3989c0e?, 0x1?}}}, {0xc00023aac0?, 0xc000128950?, 0x98?}, 0x3295fae?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setMap({{0x7?, {0x3989c0e?, 0x0?}}}, {0x3230820?, 0xc000ad10b0?, 0x3295fb6?}, 0xc000a4b170)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:308 +0x3e5\ngithub.com/traefik/paerser/parser.filler.fill({{0x60?, {0x3989c0e?, 0x4?}}}, {0x3230820?, 0xc000ad10b0?, 0x0?}, 0x0?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:103 +0x44f\ngithub.com/traefik/paerser/parser.filler.setStruct({{0xe0?, {0x3989c0e?, 0xc0002025b8?}}}, {0x367f560?, 0xc000ad10b0?, 0x31ce40b?}, 0x4f?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x178\ngithub.com/traefik/paerser/parser.filler.fill({{0xa0?, {0x3989c0e?, 0x199?}}}, {0x367f560?, 0xc000ad10b0?, 0xc0005c63e0?}, 0x31ce406?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x4b3\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x4?, {0x3989c0e?, 0x0?}}}, {0x32c8ba0?, 0xc0005c63e0?, 0x31ce40b?}, 0x4f?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x60?, {0x3989c0e?, 0x98?}}}, {0x32c8ba0?, 0xc0005c63e0?, 0xc0003bbc98?}, 0x398aac3?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setStruct({{0x18?, {0x3989c0e?, 0x1?}}}, {0x35e3060?, 0xc0005c63e0?, 0xc000d7a9f8?}, 0x1af1bb9?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x178\ngithub.com/traefik/paerser/parser.filler.fill({{0xa0?, {0x3989c0e?, 0x4?}}}, {0x35e3060?, 0xc0005c63e0?, 0xc000d7aa80?}, 0x1af1a26?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x4b3\ngithub.com/traefik/paerser/parser.filler.Fill({{0xa0?, {0x3989c0e?, 0x32c87a0?}}}, {0x32c87a0?, 0xc0005c63e0?}, 0xc000a4a1b0)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:58 +0x13d\ngithub.com/traefik/paerser/parser.Fill({0x32c87a0?, 0xc0005c63e0?}, 0x4?, {0xa0?, {0x3989c0e?, 0xc000a4a1b0?}})\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:28 +0x59\ngithub.com/traefik/paerser/file.DecodeContent({0xc000a44000, 0x7f8}, {0xc0000e4441, 0x4}, {0x32c87a0, 0xc0005c63e0})\n\tgithub.com/traefik/paerser@v0.1.6/file/file.go:83 +0x1d8\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).decodeConfiguration(0xc00023a3c0?, {0xc0000e4420, 0x25}, {0xc000a44000, 0x7f8})\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:522 +0x31d\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).CreateConfiguration(0xc000a36990, {0x4458090, 0xc000ad09c0}, {0xc0000e4420, 0x25}, 0x1548c8072600?, {0x3021fc0, 0x61ccfe0})\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:486 +0x746\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).loadFileConfig(0xc000d315f8?, {0x4458090, 0xc000ad09c0}, {0xc0000e4420, 0x25}, 0xb8?)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:160 +0xfb\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).loadFileConfigFromDirectory(0x4458020?, {0x4458090, 0xc000ad09c0}, {0xc00024b260, 0x14}, 0x0)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:333 +0xa7f\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).BuildConfiguration(0xc000a36990)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:81 +0x11e\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).Provide(0xc000a36990, 0xc0005c63a0?, 0x443ca50?)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:49 +0x2f\ngithub.com/traefik/traefik/v2/pkg/provider/aggregator.maybeThrottledProvide.func1(0xc000115ce0, 0xc000a36990?)\n\tgithub.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:57 +0xcf\ngithub.com/traefik/traefik/v2/pkg/provider/aggregator.ProviderAggregator.launchProvider({{0x443d298, 0xc000532880}, {0x443ca50, 0xc000a36990}, {0xc000510c40, 0x3, 0x4}, 0x77359400}, 0x0?, 0xc0009a1860, ...)\n\tgithub.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:208 +0x339\ngithub.com/traefik/traefik/v2/pkg/provider/aggregator.ProviderAggregator.Provide({{0x443d298, 0xc000532880}, {0x443ca50, 0xc000a36990}, {0xc000510c40, 0x3, 0x4}, 0x77359400}, 0xc000115ce0, 0xc0009a1860)\n\tgithub.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:180 +0xb0\ngithub.com/traefik/traefik/v2/pkg/server.(*ConfigurationWatcher).startProviderAggregator.func1()\n\tgithub.com/traefik/traefik/v2/pkg/server/configurationwatcher.go:76 +0x48\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:59 +0x5b\ncreated by github.com/traefik/traefik/v2/pkg/safe.GoWithRecover\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:53 +0x72\n"

time="2022-08-12T11:45:08+02:00" level=debug msg="http: panic serving PUBLIC IP:51966: runtime error: invalid memory address or nil pointer dereference"
time="2022-08-12T11:45:08+02:00" level=debug msg="goroutine 777 [running]:"
time="2022-08-12T11:45:08+02:00" level=debug msg="net/http.(*conn).serve.func1()"
time="2022-08-12T11:45:08+02:00" level=debug msg="\tnet/http/server.go:1850 +0xbf"
time="2022-08-12T11:45:08+02:00" level=debug msg="panic({0x328c620, 0x62216c0})"
time="2022-08-12T11:45:08+02:00" level=debug msg="\truntime/panic.go:890 +0x262"
time="2022-08-12T11:45:08+02:00" level=debug msg="crypto/tls.(*Conn).readClientHello(0xc0005cd880, {0x4457fe8?, 0xc0002c9d40})"
time="2022-08-12T11:45:08+02:00" level=debug msg="\tcrypto/tls/handshake_server.go:144 +0x92"
time="2022-08-12T11:45:08+02:00" level=debug msg="crypto/tls.(*Conn).serverHandshake(0xc0005cd880, {0x4457fe8, 0xc0002c9d40})"
time="2022-08-12T11:45:08+02:00" level=debug msg="\tcrypto/tls/handshake_server.go:43 +0x46"
time="2022-08-12T11:45:08+02:00" level=debug msg="crypto/tls.(*Conn).handshakeContext(0xc0005cd880, {0x4458090, 0xc001299920})"
time="2022-08-12T11:45:08+02:00" level=debug msg="\tcrypto/tls/conn.go:1462 +0x32f"
time="2022-08-12T11:45:08+02:00" level=debug msg="crypto/tls.(*Conn).HandshakeContext(...)"
time="2022-08-12T11:45:08+02:00" level=debug msg="\tcrypto/tls/conn.go:1405"
time="2022-08-12T11:45:08+02:00" level=debug msg="net/http.(*conn).serve(0xc000982b40, {0x4458090, 0xc0006ab140})"
time="2022-08-12T11:45:08+02:00" level=debug msg="\tnet/http/server.go:1873 +0xdd3"
time="2022-08-12T11:45:08+02:00" level=debug msg="created by net/http.(*Server).Serve"
time="2022-08-12T11:45:08+02:00" level=debug msg="\tnet/http/server.go:3102 +0x4db"
time="2022-08-12T11:45:12+02:00" level=debug msg="http: panic serving PUBLIC IP:51684: runtime error: invalid memory address or nil pointer dereference"
time="2022-08-12T11:45:12+02:00" level=debug msg="goroutine 831 [running]:"
time="2022-08-12T11:45:12+02:00" level=debug msg="net/http.(*conn).serve.func1()"
time="2022-08-12T11:45:12+02:00" level=debug msg="\tnet/http/server.go:1850 +0xbf"
time="2022-08-12T11:45:12+02:00" level=debug msg="panic({0x328c620, 0x62216c0})"
time="2022-08-12T11:45:12+02:00" level=debug msg="\truntime/panic.go:890 +0x262"
time="2022-08-12T11:45:12+02:00" level=debug msg="crypto/tls.(*Conn).readClientHello(0xc000810e00, {0x4457fe8?, 0xc0006578c0})"
time="2022-08-12T11:45:12+02:00" level=debug msg="\tcrypto/tls/handshake_server.go:144 +0x92"
time="2022-08-12T11:45:12+02:00" level=debug msg="crypto/tls.(*Conn).serverHandshake(0xc000810e00, {0x4457fe8, 0xc0006578c0})"
time="2022-08-12T11:45:12+02:00" level=debug msg="\tcrypto/tls/handshake_server.go:43 +0x46"
time="2022-08-12T11:45:12+02:00" level=debug msg="crypto/tls.(*Conn).handshakeContext(0xc000810e00, {0x4458090, 0xc00063dcb0})"
time="2022-08-12T11:45:12+02:00" level=debug msg="\tcrypto/tls/conn.go:1462 +0x32f"
time="2022-08-12T11:45:12+02:00" level=debug msg="crypto/tls.(*Conn).HandshakeContext(...)"
time="2022-08-12T11:45:12+02:00" level=debug msg="\tcrypto/tls/conn.go:1405"
time="2022-08-12T11:45:12+02:00" level=debug msg="net/http.(*conn).serve(0xc000397a40, {0x4458090, 0xc0006ab140})"
time="2022-08-12T11:45:12+02:00" level=debug msg="\tnet/http/server.go:1873 +0xdd3"
time="2022-08-12T11:45:12+02:00" level=debug msg="created by net/http.(*Server).Serve"
time="2022-08-12T11:45:12+02:00" level=debug msg="\tnet/http/server.go:3102 +0x4db"
time="2022-08-12T11:45:12+02:00" level=debug msg="http: panic serving PUBLIC IP:51685: runtime error: invalid memory address or nil pointer dereference"
