### ISSUE TITLE
Traefik 2.8 Latest Push Won't Start

### ISSUE THREAD

**Issue by Zanathoz** [traefik/traefik#9256]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

The latest update pushed 16 hours ago will not load with file provider. This instance was working fine yesterday with no issue on the latest 2.8 build. My server grabbed the latest push from 16 hours ago and now Traefik won't start on any version 2.8 build. 2.7 works without issue with no changes to the Traefik configuration.

This has happened on two different VM's I'm running with very similar configuration (one in DMZ and one in LAN) and I've confirmed 2.7 still works while 2.8 is broken.

### What did you see instead?

Container fails with the following errors in my Fedora console (running Podman - this has not been an issue before)
7:54 AM
2022/08/12 07:54:46 command traefik error: strconv.ParseBool: parsing "yes": invalid syntax
traefik
7:54 AM
Started container-traefik.service - Podman container-traefik.service.
systemd

### What version of Traefik are you using?

I've confirmed this is an issue with v2.8 and 2.8.2. If I pull 2.7, the configuration works as it previously had.

docker.io/library/traefik                   latest        186b1b030a2b  16 hours ago   108 MB
docker.io/library/traefik                   v2.8.2        186b1b030a2b  16 hours ago   108 MB
docker.io/library/traefik                   v2.8          186b1b030a2b  16 hours ago   108 MB
docker.io/library/traefik                   v2.7          5c54a6d9bbe9  6 weeks ago    107 MB

### What is your environment & configuration?

```yaml
global:
  checkNewVersion: yes
  sendAnonymousUsage: no
api:
#  insecure: true
  dashboard: true
serversTransport:
  insecureSkipVerify: true
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          permanent: true
          to: websecure
          scheme: https
          priority: 1000
  websecure:
    address: :443
    proxyProtocol:
      insecure: true
    http:
      tls:
        options: default
        certResolver: letsEncrypt
        domains:
          - main: "mydomain.com"
            sans:
              - "*.mydomain.com"
certificatesResolvers:
  letsEncrypt:
    acme:
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      #caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      email: djgalmarini@gmail.com
      storage: /acme.json
      keyType: 'RSA4096'
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
tls:
  stores:
    default:
  options:
    default:
      minVersion: VersionTLS12
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
providers:
#  docker:
#    endpoint: unix:///var/run/docker.sock
#    exposedByDefault: false
  file:
    directory: /etc/traefik/configuration/
    watch: true
tracing:
  jaeger:
    samplingServerURL: http://192.168.1.50:5778/sampling
    samplingType: const
    samplingParam: 1.0
    localAgentHostPort: 192.168.1.50:6831
log:
  filePath: "/logs/traefik.log"
  format: common json
  level: DEBUG
accessLog:
  filePath: "/logs/access.log"
  bufferingSize: 100
#NEW HUB ITEMS 2.8+
#experimental:
#  hub: true
#hub: {}
#metrics:
#  prometheus:
#    addRoutersLabels: true
#DEPRECIATED CONFIGURATION ITEMS
#pilot:
#    token: "omitted"
#experimental:
#  plugins:
#    log4shell:
#      modulename: github.com/traefik/plugin-log4shell
#      version: v0.1.2
```

Add more configuration information here.
Running Fedora 36 with Podman container in rootful mode and file configuration. 

### If applicable, please paste the log output in DEBUG level

Logs are not generated as the container is crashing as soon as it is created with the above error:

2022/08/12 07:54:46 command traefik error: strconv.ParseBool: parsing "yes": invalid syntax

**Comment by choque88** [comment]
From what I've seen, the problem lies with a Go routine that's something to do with the providers? At least when I try to start 2.8.2 I get the following error in my traefik.log

```bash
time="2022-08-12T14:15:23+02:00" level=info msg="Starting provider aggregator aggregator.ProviderAggregator"
time="2022-08-12T14:15:23+02:00" level=info msg="Starting provider *file.Provider"
time="2022-08-12T14:15:23+02:00" level=error msg="Error in Go routine: runtime error: slice bounds out of range [2:1]"
time="2022-08-12T14:15:23+02:00" level=error msg="Stack: goroutine 97 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine({0x36a75c0?, 0xc0004b84e0})\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:66 +0xa5\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1.1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:56 +0x36\npanic({0x36a75c0, 0xc0004b84e0})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/paerser/parser.filler.setSlice({{0x5?, {0x3989c0e?, 0x0?}}}, {0x3306680?, 0xc000308730?, 0x324db43?}, 0xc0006bc120)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:157 +0xaa5\ngithub.com/traefik/paerser/parser.filler.fill({{0xe0?, {0x3989c0e?, 0x9?}}}, {0x3306680?, 0xc000308730?, 0x0?}, 0xc000418740?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:105 +0x477\ngithub.com/traefik/paerser/parser.filler.setStruct({{0x30?, {0x3989c0e?, 0x2d8dfd4?}}}, {0x367f1e0?, 0xc000308730?, 0xc000418818?}, 0x4a2e28?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x178\ngithub.com/traefik/paerser/parser.filler.fill({{0xa0?, {0x3989c0e?, 0x3306580?}}}, {0x367f1e0?, 0xc000308730?, 0xc000128b40?}, 0x33194b1?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x4b3\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x9?, {0x3989c0e?, 0x0?}}}, {0x32c85a0?, 0xc000128ba0?, 0x33194bb?}, 0x5e?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x20?, {0x3989c0e?, 0x447fe98?}}}, {0x32c85a0?, 0xc000128ba0?, 0x5e?}, 0xc0004189c0?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setStruct({{0x40?, {0x3989c0e?, 0x2d8dfd4?}}}, {0x3891120?, 0xc000128b40?, 0xc000418a98?}, 0x4a2e28?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x178\ngithub.com/traefik/paerser/parser.filler.fill({{0x20?, {0x3989c0e?, 0x3306580?}}}, {0x3891120?, 0xc000128b40?, 0x349bc00?}, 0xc000418b50?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x4b3\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x90?, {0x3989c0e?, 0x39a1241?}}}, {0x32c8e20?, 0xc000212690?, 0xc000418ba8?}, 0x4a2e28?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x0?, {0x3989c0e?, 0x3306580?}}}, {0x32c8e20?, 0xc000212690?, 0x203000?}, 0xc0006a00d0?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x90?, {0x3989c0e?, 0x411cc4?}}}, {0xc000450f00?, 0xc000212688?, 0xea0000c0006a00d0?}, 0x5?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x40?, {0x3989c0e?, 0x491efd?}}}, {0xc000450f00?, 0xc000212688?, 0x349bc00?}, 0xc000418d70?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x8b?, {0x3989c0e?, 0x46b087?}}}, {0xc000450f40?, 0xc000212688?, 0x1?}, 0xc000418dc8?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x98?, {0x3989c0e?, 0x1?}}}, {0xc000450f40?, 0xc000212688?, 0x98?}, 0x32c8e20?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setMap({{0xb?, {0x3989c0e?, 0x0?}}}, {0x3230760?, 0xc0004029d0?, 0x334faff?}, 0xc000397320)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:308 +0x3e5\ngithub.com/traefik/paerser/parser.filler.fill({{0x60?, {0x3989c0e?, 0x4?}}}, {0x3230760?, 0xc0004029d0?, 0x0?}, 0x0?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:103 +0x44f\ngithub.com/traefik/paerser/parser.filler.setStruct({{0x0?, {0x3989c0e?, 0xc0001aceb0?}}}, {0x367f560?, 0xc0004029c0?, 0x31ce40b?}, 0x4f?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x178\ngithub.com/traefik/paerser/parser.filler.fill({{0xa0?, {0x3989c0e?, 0x199?}}}, {0x367f560?, 0xc0004029c0?, 0xc00037b400?}, 0x31ce406?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x4b3\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x4?, {0x3989c0e?, 0x0?}}}, {0x32c8ba0?, 0xc00037b400?, 0x31ce40b?}, 0x4f?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x60?, {0x3989c0e?, 0x98?}}}, {0x32c8ba0?, 0xc00037b400?, 0xc000328aa0?}, 0x398aac3?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setStruct({{0x18?, {0x3989c0e?, 0x1?}}}, {0x35e3060?, 0xc00037b400?, 0xc000419338?}, 0x1af1bb9?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x178\ngithub.com/traefik/paerser/parser.filler.fill({{0xa0?, {0x3989c0e?, 0x4?}}}, {0x35e3060?, 0xc00037b400?, 0xc0004193c0?}, 0x1af1a26?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x4b3\ngithub.com/traefik/paerser/parser.filler.Fill({{0xa0?, {0x3989c0e?, 0x32c87a0?}}}, {0x32c87a0?, 0xc00037b400?}, 0xc000397200)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:58 +0x13d\ngithub.com/traefik/paerser/parser.Fill({0x32c87a0?, 0xc00037b400?}, 0x4?, {0xa0?, {0x3989c0e?, 0xc000397200?}})\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:28 +0x59\ngithub.com/traefik/paerser/file.DecodeContent({0xc0005bc000, 0x7e1}, {0xc00005a3d7, 0x4}, {0x32c87a0, 0xc00037b400})\n\tgithub.com/traefik/paerser@v0.1.6/file/file.go:83 +0x1d8\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).decodeConfiguration(0xc000450240?, {0xc00005a3c0, 0x1b}, {0xc0005bc000, 0x7e1})\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:522 +0x31d\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).CreateConfiguration(0xc000694480, {0x4458090, 0xc0004025d0}, {0xc00005a3c0, 0x1b}, 0x0?, {0x3021fc0, 0x61ccfe0})\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:486 +0x746\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).loadFileConfig(0x4458020?, {0x4458090, 0xc0004025d0}, {0xc00005a3c0, 0x1b}, 0xbf?)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:160 +0xfb\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).BuildConfiguration(0xc000694480)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:85 +0xca\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).Provide(0xc000694480, 0xc00037b3c0?, 0x443ca50?)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:49 +0x2f\ngithub.com/traefik/traefik/v2/pkg/provider/aggregator.maybeThrottledProvide.func1(0xc0007e6960, 0xc000694480?)\n\tgithub.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:57 +0xcf\ngithub.com/traefik/traefik/v2/pkg/provider/aggregator.ProviderAggregator.launchProvider({{0x443d298, 0xc000480000}, {0x443ca50, 0xc000694480}, {0xc000412b40, 0x3, 0x4}, 0x77359400}, 0x0?, 0xc000796300, ...)\n\tgithub.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:208 +0x339\ngithub.com/traefik/traefik/v2/pkg/provider/aggregator.ProviderAggregator.Provide({{0x443d298, 0xc000480000}, {0x443ca50, 0xc000694480}, {0xc000412b40, 0x3, 0x4}, 0x77359400}, 0xc0007e6960, 0xc000796300)\n\tgithub.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:180 +0xb0\ngithub.com/traefik/traefik/v2/pkg/server.(*ConfigurationWatcher).startProviderAggregator.func1()\n\tgithub.com/traefik/traefik/v2/pkg/server/configurationwatcher.go:76 +0x48\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:59 +0x5b\ncreated by github.com/traefik/traefik/v2/pkg/safe.GoWithRecover\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:53 +0x72\n"
```

With 2.8.1 traefik starts as expected
```bash
time="2022-08-12T14:17:54+02:00" level=info msg="Starting provider aggregator aggregator.ProviderAggregator"
time="2022-08-12T14:17:54+02:00" level=info msg="Starting provider *file.Provider"
time="2022-08-12T14:17:54+02:00" level=info msg="Starting provider *traefik.Provider"
time="2022-08-12T14:17:54+02:00" level=info msg="Starting provider *acme.ChallengeTLSALPN"
time="2022-08-12T14:17:54+02:00" level=info msg="Starting provider *docker.Provider"
time="2022-08-12T14:17:54+02:00" level=info msg="Starting provider *acme.Provider"
time="2022-08-12T14:17:54+02:00" level=info msg="Testing certificate renew..." ACME CA="https://acme-v02.api.letsencrypt.org/directory" providerName=cloudflare.acme
```

**Comment by SoulEater45** [comment]
I have similar logs as @choque88 
Reverting to the image `2.8.1` can be used as a workaround for now.

**Comment by ldez** [comment]
duplicate of #9249

Hello,

the `strconv.ParseBool` is still the same.

`yes` and `no` are not valid values for boolean in the Traefik configuration.

https://github.com/golang/go/blob/release-branch.go1.17/src/strconv/atob.go
https://github.com/golang/go/blob/release-branch.go1.19/src/strconv/atob.go

**Comment by Zanathoz** [comment]
I changed both of the options for 

global:
  checkNewVersion: yes
  sendAnonymousUsage: no

to true/false (before posting this issue) and the container was still not starting correctly. Commenting those options out got it started again. I also noticed recently that my container is still sending Usage statistics even when that was set to false. I had copied those directly from the YAML example on the Traefik site - https://doc.traefik.io/traefik/contributing/data-collection/

 I just tried it again with setting to false and the container will not launch. Is this a deprecated option or should I simply omit the line to not send Anonymous Usage?

**Comment by ldez** [comment]
your problem is related to #9249

**Comment by SoulEater45** [comment]
@Zanathoz maybe there are some other config issues? My problem were the middlewares I configured using a file provider to whitelist some IP ranges. I had to modify the `sourceRange` from a single entry to an array with a single entry.

**Comment by Zanathoz** [comment]
I've made no changes to my routers/middlewares/services, simply commenting out those two lines gets everything started again.

If anything it's my Middlewares as I'm seeing this on my DMZ and LAN instances and my DMZ is very slimmed down.

**Comment by ldez** [comment]
Can you give me your dynamic configuration file(s)?

**Comment by Zanathoz** [comment]
DMZ Middlewares
'''
http:
  middlewares:
    user-auth:
      basicAuth:
        users:
          - "omitted:omitted"
    block-log4shell:
      plugin:
        log4shell:
          errorCode: 200
    authelia:  #use authelia if you want to have local oauth service
      forwardAuth:
        address: "http://192.168.10.200:9091/api/verify?rd=https://login.mydomain.com"
        trustForwardHeader: true
        authResponseHeaders:
          - "adminGroup"
          - "Remote-User"
          - "Remote-Groups"
    chain-authelia:
      chain:
        middlewares:
          - middlewares-rate-limit
          - middlewares-secure-headers
          - authelia
    middlewares-rate-limit:
      rateLimit:
        average: 100
        burst: 50
    middlewares-secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        sslRedirect: true
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        # frameDeny: true #overwritten by customFrameOptionsValue
        customFrameOptionsValue: "allow-from https:mydomain.com" #CSP takes care of this but may be needed for organizr.
        contentTypeNosniff: true
        browserXssFilter: true
        # sslForceHost: true # add sslHost to all of the services
        # sslHost: "vtulluru.com"
        referrerPolicy: "same-origin"
        # Setting contentSecurityPolicy is more secure but it can break things. Proper auth will reduce the risk.
        # the below line also breaks some apps due to 'none' - sonarr, radarr, etc.
        # contentSecurityPolicy: "frame-ancestors '*.vtulluru.com:*';object-src 'none';script-src 'none';"
        featurePolicy: "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none';"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
          server: ""
    nextcloud-middlewares-secure-headers:
      headers:
        accessControlMaxAge: 100
        sslRedirect: true
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
#   ### We will modify this value for Nextcloud to remove the X-Frame-Options error:
        customFrameOptionsValue: "SAMEORIGIN" #CSP takes care of this but may be needed for organizr.
        contentTypeNosniff: true
        browserXssFilter: true
#       sslForceHost: true # add sslHost to all of the services
#       sslHost: "example.com"
        referrerPolicy: "no-referrer"
#   ### While CSP is a good security setting, Nextcloud's Apache server takes care of this for us!
#       contentSecurityPolicy: "frame-ancestors '*.example.com:*';object-src 'none';script-src 'none';"
        featurePolicy: "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
        customResponseHeaders:
#    ### Change this to none to remove the Robots error:
          X-Robots-Tag: "none"
          server: ""
    nextcloud-redirect:
      redirectRegex:
        permanent: true
        regex: "https://(.*)/.well-known/(card|cal)dav"
        replacement: "https://${1}/remote.php/dav/"
    gameon-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "https://*.mydomain.com"
          - "https://sub1.mydomain.com"
          - "https://sub2.mydomain.com"
        accessControlMaxAge: 100
        addVaryHeader: true
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        referrerPolicy: "strict-origin-when-cross-origin"
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
    wings-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        sslProxyHeaders:
          X-Forwarded-Proto: https
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "https://*.mydomain.com"
          - "https://sub1.mydomain.com"
        accessControlMaxAge: 100
        addVaryHeader: true
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        referrerPolicy: "strict-origin-when-cross-origin"
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
'''

DMZ Routers
'''
http:
  routers:
    authelia:
      rule: (Host(`login.mydomain.com`))
      service: authelia
      entryPoints:
        - "websecure"
      middlewares:
        - authelia
    dashboard:
      rule: (Host(`proxyext.mydomain.com`) && (PathPrefix(`/api/`)) || (PathPrefix(`/dashboard/`)))
      service: api@internal
      entryPoints:
        - "websecure"
      middlewares:
        - chain-authelia
#        - block-log4shell
    plex:
      rule: (Host(`plex.mydomain.com`))
      service: plex
      entryPoints:
        - "websecure"
    mail:
      rule: (Host(`mail.mydomain.com`) && (PathPrefix(`/SOGo/`)))
      service: mail
      entryPoints:
        - "websecure"
      middlewares:
        - chain-authelia
    homeassistant:
      rule: (Host(`home.mydomain.com`))
      service: homeassistant
      entryPoints:
        - "websecure"
    overseerr:
      rule: (Host(`request.mydomain.com`))
      service: overseerr
      entryPoints:
        - "websecure"
    nextcloud:
      rule: (Host(`cloud.mydomain.com`))
      service: nextcloud
      entryPoints:
        - "websecure"
      middlewares:
        - chain-authelia
        - nextcloud-redirect
        - nextcloud-middlewares-secure-headers
    cockpit:
      rule: (Host(`proxyext.mydomain.com`) && (PathPrefix(`/cockpit/`)))
      service: cockpit
      entryPoints:
        - "websecure"
      middlewares:
        - chain-authelia
#    jaeger:
#      rule: (Host(`proxyext.mydomain.com`) && (PathPrefix(`/log/`)))
#      service: jaeger
#      entryPoints:
#        - "websecure"
    pterodactyl-panel:
      rule: (Host(`gameon.mydomain.com`))
      service: pterodactyl-panel
      entryPoints:
        - "websecure"
      middlewares:
        - gameon-headers
    pterodactyl-wing01:
      rule: (Host(`gameona.mydomain.com`) #&& (PathPrefix(`/api/system`)))
      service: pterodactyl-wing01
      entryPoints:
        - "websecure"
      middlewares:
        - wings-headers
#        - addprefix-wings
    pterodactyl-wing02:
      rule: (Host(`gameonb.mydomain.com`))
      service: pterodactyl-wing02
      entryPoints:
        - "websecure"
      middlewares:
        - pterodactyl-headers
'''

DMZ Services
'''
http:
  services:
    authelia:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://192.168.1.5:9091
    plex:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://192.168.1.5:32400
    mail:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: https://192.168.1.10:443
    homeassistant:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: https://192.168.1.11:8123
    nextcloud:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: https://192.168.1.5:8443
    overseerr:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://192.168.1.5:5055
    cockpit:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://172.16.0.25:9090
    jaeger:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://172.16.0.25:16686
    pterodactyl-panel:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: https://192.168.1.5:445
    pterodactyl-wing01:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: https://192.168.10.203
    pterodactyl-wing02:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: https://192.168.10.204
'''

**Comment by Zanathoz** [comment]
Middlewares
```
http:
  middlewares:
    user-auth:
      basicAuth:
        users:
          - "admin:$apr1$5ov2s0t8$OKKzjmknFwdajVpX0/8S9."
    block-log4shell:
      plugin:
        log4shell:
          errorCode: 200
    authelia:  #use authelia if you want to have local oauth service
      forwardAuth:
        address: "http://192.168.10.200:9091/api/verify?rd=https://login.mydomain.com"
        trustForwardHeader: true
        authResponseHeaders:
          - "adminGroup"
          - "Remote-User"
          - "Remote-Groups"
    chain-authelia:
      chain:
        middlewares:
          - middlewares-rate-limit
          - middlewares-secure-headers
          - authelia
    middlewares-rate-limit:
      rateLimit:
        average: 100
        burst: 50
    middlewares-secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        sslRedirect: true
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        # frameDeny: true #overwritten by customFrameOptionsValue
        customFrameOptionsValue: "allow-from https:mydomain.com" #CSP takes care of this but may be needed for organizr.
        contentTypeNosniff: true
        browserXssFilter: true
        # sslForceHost: true # add sslHost to all of the services
        # sslHost: "vtulluru.com"
        referrerPolicy: "same-origin"
        # Setting contentSecurityPolicy is more secure but it can break things. Proper auth will reduce the risk.
        # the below line also breaks some apps due to 'none' - sonarr, radarr, etc.
        # contentSecurityPolicy: "frame-ancestors '*.vtulluru.com:*';object-src 'none';script-src 'none';"
        featurePolicy: "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none';"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
          server: ""
    nextcloud-middlewares-secure-headers:
      headers:
        accessControlMaxAge: 100
        sslRedirect: true
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
#   ### We will modify this value for Nextcloud to remove the X-Frame-Options error:
        customFrameOptionsValue: "SAMEORIGIN" #CSP takes care of this but may be needed for organizr.
        contentTypeNosniff: true
        browserXssFilter: true
#       sslForceHost: true # add sslHost to all of the services
#       sslHost: "example.com"
        referrerPolicy: "no-referrer"
#   ### While CSP is a good security setting, Nextcloud's Apache server takes care of this for us!
#       contentSecurityPolicy: "frame-ancestors '*.example.com:*';object-src 'none';script-src 'none';"
        featurePolicy: "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
        customResponseHeaders:
#    ### Change this to none to remove the Robots error:
          X-Robots-Tag: "none"
          server: ""
    nextcloud-redirect:
      redirectRegex:
        permanent: true
        regex: "https://(.*)/.well-known/(card|cal)dav"
        replacement: "https://${1}/remote.php/dav/"
    gameon-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "https://*.mydomain.com"
          - "https://gameon.mydomain.com"
          - "https://gameona.mydomain.com"
        accessControlMaxAge: 100
        addVaryHeader: true
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        referrerPolicy: "strict-origin-when-cross-origin"
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
    wings-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        sslProxyHeaders:
          X-Forwarded-Proto: https
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "https://*.mydomain.com"
          - "https://gameon.mydomain.com"
        accessControlMaxAge: 100
        addVaryHeader: true
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        referrerPolicy: "strict-origin-when-cross-origin"
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
```
Services
```
http:
  services:
    authelia:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://192.168.1.5:9091
    plex:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://192.168.1.5:32400
    mail:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: https://192.168.1.10:443
    homeassistant:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: https://192.168.1.11:8123
    nextcloud:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: https://192.168.1.5:8443
    overseerr:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://192.168.1.5:5055
    cockpit:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://172.16.0.25:9090
    jaeger:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://172.16.0.25:16686
    pterodactyl-panel:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: https://192.168.1.5:445
    pterodactyl-wing01:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: https://192.168.10.203
    pterodactyl-wing02:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: https://192.168.10.204
```

Routers
```
http:
  routers:
    authelia:
      rule: (Host(`login.mydomain.com`))
      service: authelia
      entryPoints:
        - "websecure"
      middlewares:
        - authelia
    dashboard:
      rule: (Host(`proxyext.mydomain.com`) && (PathPrefix(`/api/`)) || (PathPrefix(`/dashboard/`)))
      service: api@internal
      entryPoints:
        - "websecure"
      middlewares:
        - chain-authelia
#        - block-log4shell
    plex:
      rule: (Host(`plex.mydomain.com`))
      service: plex
      entryPoints:
        - "websecure"
    mail:
      rule: (Host(`mail.mydomain.com`) && (PathPrefix(`/SOGo/`)))
      service: mail
      entryPoints:
        - "websecure"
      middlewares:
        - chain-authelia
    homeassistant:
      rule: (Host(`home.mydomain.com`))
      service: homeassistant
      entryPoints:
        - "websecure"
    overseerr:
      rule: (Host(`request.mydomain.com`))
      service: overseerr
      entryPoints:
        - "websecure"
    nextcloud:
      rule: (Host(`cloud.mydomain.com`))
      service: nextcloud
      entryPoints:
        - "websecure"
      middlewares:
        - chain-authelia
        - nextcloud-redirect
        - nextcloud-middlewares-secure-headers
    cockpit:
      rule: (Host(`proxyext.mydomain.com`) && (PathPrefix(`/cockpit/`)))
      service: cockpit
      entryPoints:
        - "websecure"
      middlewares:
        - chain-authelia
#    jaeger:
#      rule: (Host(`proxyext.mydomain.com`) && (PathPrefix(`/log/`)))
#      service: jaeger
#      entryPoints:
#        - "websecure"
    pterodactyl-panel:
      rule: (Host(`gameon.mydomain.com`))
      service: pterodactyl-panel
      entryPoints:
        - "websecure"
      middlewares:
        - gameon-headers
    pterodactyl-wing01:
      rule: (Host(`gameona.mydomain.com`) #&& (PathPrefix(`/api/system`)))
      service: pterodactyl-wing01
      entryPoints:
        - "websecure"
      middlewares:
        - wings-headers
#        - addprefix-wings
    pterodactyl-wing02:
      rule: (Host(`gameonb.mydomain.com`))
      service: pterodactyl-wing02
      entryPoints:
        - "websecure"
      middlewares:
        - pterodactyl-headers
```
