### ISSUE TITLE
v2.8.2 service@file bad characters

### ISSUE THREAD

**Issue by thechubbypanda** [traefik/traefik#9260]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Updated from 2.8.1 to 2.8.2

I had a perfectly working pihole service defined in a config file

### What did you see instead?

The pihole service now has a `|| 24 ||` in front of it and traefik is complaining that it cant find it.

### What version of Traefik are you using?

2.8.2

### What is your environment & configuration?

```yaml
http:
  routers:
    pihole:
      rule: Host(`pihole.kapdee.uk`)
      entrypoints:
        - https
      middlewares:
        - pihole
      service:
        - pihole
  middlewares:
    pihole:
      addPrefix:
        prefix: "/admin"
  services:
    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.1.2:2080"
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

traefik  | time="2022-08-12T20:36:28+01:00" level=error msg="the service \"║24║pihole@file\" does not exist" entryPointName=https routerName=pihole@file

**Comment by ldez** [comment]
Duplicate of #9249

Your configuration is malformed, `service` is not an array.

```yml
http:
  routers:
    pihole:
      rule: Host(`pihole.kapdee.uk`)
      entrypoints:
        - https
      middlewares:
        - pihole
      service:
        - pihole ## <----- HERE
  middlewares:
    pihole:
      addPrefix:
        prefix: "/admin"
  services:
    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.1.2:2080"
```

The right configuration:
```yml
http:
  routers:
    pihole:
      rule: Host(`pihole.kapdee.uk`)
      entrypoints:
        - https
      middlewares:
        - pihole
      service: pihole ## <--- the fix
  middlewares:
    pihole:
      addPrefix:
        prefix: "/admin"
  services:
    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.1.2:2080"
```
