### ISSUE TITLE
Latency HTTPS request on first load

### ISSUE THREAD

**Issue by Drealine** [traefik/traefik#9262]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

If I make an  HTTPS request on first load (reload cache), my page take 5 or 6 seconds to load.

### What did you see instead?

If I disable HTTPS on Traefik, my page load in 60ms.

### What version of Traefik are you using?

v2.8 runing in docker environment

### What is your environment & configuration?

```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

# (Optional) Log information
# ---
log:
  level: INFO
  format: common
  filePath: /etc/traefik/log/traefik.log

# (Optional) Accesslog
# ---
accesslog:
  format: common  # common, json, logfmt
  filePath: /etc/traefik/log/access.log
  fields:
    defaultMode : keep
    names:
      defaultMode: keep
    headers:
      defaultMode: keep
# (Optional) Enable API and Dashboard
# ---
api:
  dashboard: true  # true by default
  insecure: false # Don't do this in production!

# Entry Points configuration
# ---
entryPoints:
  web:
    address: :80
    # (Optional) Redirect to HTTPS
    # ---
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

# Configure your CertificateResolver here...
# ---
certificatesResolvers:
#   staging:
#     acme:
#       email: your-email@example.com
#       storage: /etc/traefik/certs/acme.json
#       caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
#       httpChallenge:
#         entryPoint: web
#
  production:
    acme:
      email: blabla@blabla.com
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

# (Optional) Overwrite Default Certificates
# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /etc/traefik/certs/cert.pem
#         keyFile: /etc/traefik/certs/cert-key.pem
# (Optional) Disable TLS version 1.0 and 1.1
#   options:
#     default:
#       minVersion: VersionTLS12



providers:
  docker:
    exposedByDefault: false  # Default is true
    #swarmMode: true
  file:
    # watch for dynamic configuration changes
    directory: /etc/traefik/dynamics
    watch: true


#tracing:
#  jaeger:
#    samplingServerURL: http://jaeger:5778/sampling
#    localAgentHostPort: jaeger:6831

tracing:
  #zipkin:
    #httpEndpoint: http://zipkin:9411/api/v2/spans
    #sameSpan: true
  elastic:
    serverURL: "http://apm-server:8200"
    serviceEnvironment: "production"

```

Add more configuration information here.
