### ISSUE TITLE
PR#9224 breaks `htransformation` plugin functionality

### ISSUE THREAD

**Issue by leshik** [traefik/traefik#9269]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

While I understand that `traefik` plugins are an experimental feature, I would love to know if this is something that should be addressed by `traefik` team or the plugin author. After the changes introduced in the [PR#9224](https://github.com/traefik/traefik/pull/9224), the [htransformation](https://github.com/tomMoulard/htransformation) plugin headers manipulation functionality is broken. I added my very simple `htransformation` plugin middleware configuration to the "configuration" section of this issue. Below is an HTTPBin output of the request with `traefik` v2.8.1 (and v2.8.2 with PR#9224 reverted):

```json
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.79.1",
    "X-Amzn-Trace-Id": "Root=1-62ff074f-65675efb361949c26859e958",
    "X-Forwarded-Host": "custom.localhost",
    "X-Forwarded-Server": "Alexeys-MacBook-Pro.local"
  },
  "origin": "127.0.0.1, 184.22.158.53",
  "url": "https://custom.localhost/get"
}
```

### What did you see instead?

This is the output of the same request with the same configuration, but with `traefik` v2.8.2 and v2.8.3:

```json
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.79.1",
    "X-Amzn-Trace-Id": "Root=1-62ff0774-449387a219ccf1af73b91d4f",
    "X-Forwarded-Host": "custom.\u00e2\u0095\u009124\u00e2\u0095\u0091^X-Forwarded-Host",
    "X-Forwarded-Server": "Alexeys-MacBook-Pro.local"
  },
  "origin": "127.0.0.1, 184.22.158.53",
  "url": "https://custom.\u00e2\u0095\u009124\u00e2\u0095\u0091^X-Forwarded-Host/get"
}
```

### What version of Traefik are you using?

Version:      2.8.3
Codename:     cheddar
Go version:   go1.18.5
Built:        I don't remember exactly
OS/Arch:      darwin/amd64

### What is your environment & configuration?

```yaml
http:
  middlewares:
    build_client_fqdn:
      plugin:
        htransformation:
          Rules:
            - Header: X-Forwarded-Host
              Type: RewriteValueRule
              Value: "api.(.*)"
              ValueReplace: "$1"

            - Header: X-Client-Subdomain
              Type: Join
              Sep: "."
              HeaderPrefix: "^"
              Values:
                - "^X-Forwarded-Host"

            - Header: X-Client-Subdomain
              Type: Rename
              Value: X-Forwarded-Host
```
