### ISSUE TITLE
In the log "failed to sufficiently increase receive buffer size"

### ISSUE THREAD

**Issue by stepanov1975** [traefik/traefik#9272]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Just starting the latest docker of traefik

### What did you see instead?

`traefik     | 2022/08/20 16:27:21 packet_handler_map.go:142: failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.`

### What version of Traefik are you using?

Version:      2.8.3
Codename:     vacherin
Go version:   go1.19
Built:        2022-08-12T14:24:34Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
# 
services:
  #Traefik
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL=edited
      - CF_DNS_API_TOKEN=edited
      # - CF_API_KEY=YOU_API_KEY
      # be sure to use the correct one depending on if you are using a token or key
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /docker_installs/traefik_authelia/traefik_data/traefik.yml:/traefik.yml:ro
      - /docker_installs/traefik_authelia/traefik_data/acme.json:/acme.json
      - /docker_installs/traefik_authelia/traefik_data/sites_list.yml:/sites_list.yml:ro
      - /docker_installs/traefik_authelia/traefik_logs:/logs
      #- /docker_installs/certbot/certs/live:/etc/traefik/ssl:ro
    labels:
      - "traefik.enable=true"
      #Traefic https
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.rule=Host(`traefik-dashboard.edited.work`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=edited"

  whoami:
    image: traefik/whoami
    container_name: whoami
    security_opt:
      - no-new-privileges:true
    ports:
      - 81:80
    restart: unless-stopped
  #authelia
  authelia:
    image: authelia/authelia
    container_name: authelia
    security_opt:
      - no-new-privileges:true
    depends_on:
      - traefik
      - redis
    volumes:
      - /docker_installs/traefik_authelia/authelia_config:/config
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`auth.edited.work`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      #- 'traefik.http.routers.authelia.tls=true'
    expose:
      - 9091
    restart: unless-stopped
    environment:
      - TZ=Asia/Jerusalem
    healthcheck:
      disable: false
  redis:
    image: redis:alpine
    container_name: authelia_redis
    security_opt:
      - no-new-privileges:true
    volumes:
      - /docker_installs/traefik_authelia/authelia_redis:/data
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=Asia/Jerusalem

#Networks
networks:
  default:
    enable_ipv6: false
```

traefik.yml
```yaml
experimental:
  http3: true

global:
  # Send anonymous usage data
  sendAnonymousUsage: true
  checkNewVersion: true
log:
  filePath: "/logs/log-file.log"
  level: INFO
  format: json
accessLog:
  filePath: "/logs/access.log"
  bufferingSize: 100
  format: json
api:
  dashboard: true
  debug: true
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    http3: {}
    address: ":443"
    http:
      tls: 
        # Generate a wildcard domain certificate
        certResolver: cloudflare
        domains:
          - main: edited.work
            sans:
              - '*.edited.work'
          - main: edited1.com
            sans:
              - '*.edited1.com'
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
  file:
    filename: "/sites_list.yml"
    watch: true
certificatesResolvers:
  cloudflare:
    acme:
      email: edited
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
```

```yaml
http:
 #region routers 
  routers:
    tracks:
      entryPoints:
        - "https"
      rule: "Host(`tracks.edited.work`)"
      middlewares:
        - authelia
        - default-headers
      service: tracks
#endregion routers

#region services
  services:
    tracks:
      loadBalancer:
        servers:
          - url: "http://192.168.1.226"
        passHostHeader: true

#endregion
  middlewares:
    limit:
      buffering:
        maxRequestBodyBytes: 200000000
        maxResponseBodyBytes: 200000000
        memRequestBodyBytes: 200000000
        memResponseBodyBytes: 200000000
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"
    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://auth.edited.work"
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
          X-Forwarded-Proto: "https,wss"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
```

### If applicable, please paste the log output in DEBUG level

[log-file.log](https://github.com/traefik/traefik/files/9387221/log-file.log)
