### ISSUE TITLE
How to use public ip and port visit traefik dashboard

### ISSUE THREAD

**Issue by aliuq** [traefik/traefik#9273]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I tried add a service, but it not works

```yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      name: web
      port: 8000
      targetPort: web
  selector:
    app.kubernetes.io/name: traefik
  type: NodePort
```

### What did you see instead?

404 not found

### What version of Traefik are you using?

In k3s `v1.23.9+k3s1`, used image `rancher/mirrored-library-traefik:2.6.2`

### What is your environment & configuration?

```yaml
- args:
  - --global.checknewversion
  - --global.sendanonymoususage
  - --entrypoints.metrics.address=:9100/tcp
  - --entrypoints.traefik.address=:9000/tcp
  - --entrypoints.web.address=:8000/tcp
  - --entrypoints.websecure.address=:8443/tcp
  - --api.dashboard=true
  - --ping=true
  - --metrics.prometheus=true
  - --metrics.prometheus.entrypoint=metrics
  - --providers.kubernetescrd
  - --providers.kubernetesingress
  - --providers.kubernetesingress.ingressendpoint.publishedservice=kube-system/traefik
  - --entrypoints.websecure.http.tls=true
  image: rancher/mirrored-library-traefik:2.6.2
```

Add more configuration information here.
