### ISSUE TITLE
ingressRouteTCP: unknown field "priority"

### ISSUE THREAD

**Issue by sando38** [traefik/traefik#9290]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hello,

I wanted to set a [priority](https://github.com/traefik/traefik/blob/c51e59059195257adba402ece7583083e91bd350/docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutetcps.yaml#L74-L77) for a TCP router with traefik's ingressRouteTCP kind within kubernetes.

### What did you see instead?

  ```
  error validating data: ValidationError(IngressRouteTCP.spec.routes[0]): unknown field "priority" in us.containo.traefik.v1alpha1.IngressRouteTCP.spec.routes; if you choose to ignore these errors, turn validation off with --validate=false
  ```

### What version of Traefik are you using?

```
Version:      2.8.3
Codename:     vacherin
Go version:   go1.19
Built:        2022-08-12T14:24:34Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: c2ss
  namespace: xmpp
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`example.net`, `example.com`)
    priority: 50
    services:
    - name: ejabberd
      port: 5223
      proxyProtocol:
        version: 2
  tls:
    passthrough: true
```

Add more configuration information here.

traefik is deployed with helm.
