### ISSUE TITLE
Pass IP of ProxyProtocol host to HTTP headers

### ISSUE THREAD

**Issue by bluepuma77** [traefik/traefik#9294]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

We run multiple Traefik instances behind a load balancer using ProxyProtocol. 
```
entryPoints:
  web:
    address: :80
    proxyProtocol:
      insecure: true
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    proxyProtocol:
      trustedIPs:
        - 1.2.3.4
        - 5.6.7.8
```
It would be great if Traefik could add the IP of the ProxyProtocol host to the HTTP headers, so our app can see which load balancer was used for the request.
```
Hostname: myhost
IP: 127.0.0.1
IP: 10.0.16.28
IP: 172.19.0.5
RemoteAddr: 10.0.16.26:42274
GET / HTTP/1.1
Host: myhost.example.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 67.78.89.90
X-Forwarded-Host: myhost.example.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: myhost
X-Forwarded-Proxy: 1.2.3.4 <====================
X-Real-Ip: 67.78.89.90
```
