### ISSUE TITLE
Enable static TLS/SSL certificates and LetsEncrypt for other domains in parallel

### ISSUE THREAD

**Issue by bluepuma77** [traefik/traefik#9296]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

We currently use Traefik with some static purchased wildcard certificates for our TLS/SSL encryption. So `example.com`, `subdomain.example.com` and `example2.com` can show the OV data of the TLS/SSL certificate. Routing is established via Docker Swarm config discovery with labels on the services for the domain name.
```
tls:
  options:
    default:
      minVersion: VersionTLS12
  certificates:
    - certFile: /data/traefik/certs/example.com.crt
      keyFile: /data/traefik/certs/example.com.key
    - certFile: /data/traefik/certs/example2.com.crt
      keyFile: /data/traefik/certs/example2.com.key
```
It would be great to be able to use LetsEncrypt in parallel, so it creates certificates for other domains (like `example3.com`), that do not have a static purchased certificate already installed.
