### ISSUE TITLE
Internal server error on https backend with wilcard certificate

### ISSUE THREAD

**Issue by hlidotbe** [traefik/traefik#9305]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hi,

I'm trying to proxy an S3 (scaleway) bucket without having to start a pod. To do so I declared an `ExternalName` service, a `ServersTransport` and the relevant `IngressRoute`.

### What did you see instead?

Unless I'm setting the `insecureSkipVerify` flag to true, I get an internal server error and when debugging the logs I see that Traefik complains about the certificate which is a wilcard one. Accessing the resource directly works fine so the certificate is valid and I would expect Traefik to accept it.

While this setup currently works I'd rather have the insecureSkipVerify at false given it's not on a private network (and even then...).

### What version of Traefik are you using?

2.8.0

### What is your environment & configuration?

Traefik is running on an internal k3s cluster from the helm chart with the following flags:

```
        - --global.checknewversion
        - --global.sendanonymoususage
        - --entrypoints.gulp.address=:3000/tcp
        - --entrypoints.metrics.address=:8082/tcp
        - --entrypoints.traefik.address=:9000/tcp
        - --entrypoints.web.address=:80/tcp
        - --entrypoints.websecure.address=:443/tcp
        - --api.dashboard=true
        - --ping=true
        - --metrics.prometheus=true
        - --metrics.prometheus.entrypoint=metrics
        - --providers.kubernetescrd
        - --providers.kubernetesingress
        - --entrypoints.websecure.http.tls=true
        - --pilot.token=4fa86e74-9a6e-49c4-b58d-b3af7d4f98e7
        - --api.insecure
        - --providers.kubernetesIngress.ingressClass=traefik-cert-manager
        - --providers.kubernetesIngress.allowemptyservices=true
        - --providers.kubernetesIngress.allowexternalnameservices=true
        - --providers.kubernetescrd.allowemptyservices=true
        - --providers.kubernetescrd.allowexternalnameservices=true
        - --entryPoints.web.forwardedHeaders.trustedIPs=0.0.0.0/0
        - --entryPoints.web.forwardedHeaders.insecure
        - --entryPoints.web.proxyProtocol.trustedIPs=0.0.0.0/0
        - --entryPoints.web.proxyProtocol.insecure
        - --entryPoints.websecure.forwardedHeaders.trustedIPs=0.0.0.0/0
        - --entryPoints.websecure.forwardedHeaders.insecure
        - --entryPoints.websecure.proxyProtocol.trustedIPs=0.0.0.0/0
        - --entryPoints.websecure.proxyProtocol.insecure
        - --entryPoints.gulp.address=10.100.100.2:3000/tcp
        - --entryPoints.gulp.forwardedHeaders.trustedIPs=0.0.0.0/0
        - --entryPoints.gulp.forwardedHeaders.insecure
        - --entryPoints.gulp.proxyProtocol.trustedIPs=0.0.0.0/0
        - --entryPoints.gulp.proxyProtocol.insecure
```

The service:

```
apiVersion: v1
kind: Service
metadata:
  name: website-v1-cdn
spec:
  externalName: [some-bucket-name].s3.fr-par.scw.cloud
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  type: ExternalName
```

The serverstransport:
```
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: website-v1-cdn
spec:
  disableHTTP2: false
  insecureSkipVerify: true
  serverName: https://[some-bucket-name].s3.fr-par.scw.cloud
```

And the route:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: website-v1-cdn
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`[some-host]`)
    services:
    - name: website-v1-cdn
      passHostHeader: false
      port: https
      serversTransport: website-v1-cdn
  tls:
    secretName: [some-secret]
```

### If applicable, please paste the log output in DEBUG level

```
time="2022-09-04T08:47:17Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"[some-path]\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-US,en;q=0.5\"],\"Dnt\":[\"1\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"cross-site\"],\"Sec-Gpc\":[\"1\"],\"Te\":[\"trailers\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0\"],\"X-Forwarded-Host\":[\"[some-host]\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"master.local-cluster.epic-sys.io\"],\"X-Real-Ip\":[\"172.22.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"[some-host]\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.22.0.1:49713\",\"RequestURI\":\"[some-path]\",\"TLS\":null}"
time="2022-09-04T08:47:17Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"[some-path]\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-US,en;q=0.5\"],\"Dnt\":[\"1\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"cross-site\"],\"Sec-Gpc\":[\"1\"],\"Te\":[\"trailers\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0\"],\"X-Forwarded-Host\":[\"[some-host]\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"master.local-cluster.epic-sys.io\"],\"X-Real-Ip\":[\"172.22.0.1\"]},\"ContentLength\":0,\"Transfer Encoding\":null,\"Host\":\"[some-host]\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.22.0.1:49713\",\"RequestURI\":\"[some-path]\",\"TLS\":null}" ForwardURL="https://[some-bucket-name].s3.fr-par.scw.cloud:443"
time="2022-09-04T08:47:17Z" level=debug msg="'500 Internal Server Error' caused by: x509: certificate is valid for *.s3-website.fr-par.scw.cloud, *.s3.fr-par.scw.cloud, s3-website.fr-par.scw.cloud, s3.fr-par.scw.cloud, not https://[some-bucket-name].s3.fr-par.scw.cloud"
```

**Comment by rtribotte** [comment]
It seems that the `serversTransport` definition is wrong, it should be:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: website-v1-cdn
spec:
  disableHTTP2: false
  insecureSkipVerify: true
  serverName: [some-bucket-name].s3.fr-par.scw.cloud
```

It seems that your issue is related to a configuration issue and the GitHub issue tracker is dedicated to bug and feature requests.

For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik). 

We will close this issue accordingly but feel free to re-open it if you think that we missed something.
