### ISSUE TITLE
Default SecretStore seems to have priority over "tls.secretName".

### ISSUE THREAD

**Issue by ScionOfDesign** [traefik/traefik#9309]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have several wildcard certificates stored in the default traefik secret store such as `*.domain.net`. These are working fine, but I have one app `myapp.domain.net` for which I want to use a self-signed certificate.

I created a secret and refer to it in the "secretName" field in my IngressRoute. (See below)

Traefik does not report any errors about importing the certificate, but when I visit the website only the wildcard certificate is used, not my self-signed one in the secret.

### What did you see instead?

I saw that the wildcard certificate was being used, and not my self-signed certificate.

### What version of Traefik are you using?

```bash
Version:      2.8.0
Codename:     vacherin
Go version:   go1.17.11
Built:        2022-06-29T15:43:58Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

I create a secret below like so:
```yaml
kind: Secret
apiVersion: v1
metadata:
  name: cert
  namespace: myapp
data:
  tls.crt: "<certificate data>"
  tls.key: "<key data>"
```
This is paired with the following IngressRoute:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myapp-ingress
  namespace: myapp
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - match: Host("myapp.domain.net")
    kind: Rule
    services:
    - name: "myapp-service"
      namespace: "myapp"
      port: 444
      scheme: https
  tls:
    secretName: cert
```
