### ISSUE TITLE
Traefik (Windows) did not configure to use ACME but it still started, and dynamic configuration TLS store is not detected

### ISSUE THREAD

**Issue by mizzPpY** [traefik/traefik#9320]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

OS: Windows Server 2019
Docker Standalone (not swarm mode)
I have a docker-compose.yml that have 2 windows containers and Traefik service, I created self signed cert and a dynamic configuration yaml file and planning for Traefik to use my self signed cert.

### What did you see instead?

When access my page via https://random.hostname:8443/portal , I get `ERR_TUNNEL_CONNECTION_FAILED`
Then I notice Traefik startup logs always shows `Starting provider *acme.ChallengeTLSALPN`, but I did not configure anything on ACME.
I suspect it is because provider ACME is started so Traefik is not picking up the TLS cert and key in my dynamic config, or it could be my docker-compose is wrongly define? Please advise, thank you. 

### What version of Traefik are you using?

traefik:windowsservercore-1809

### What is your environment & configuration?

```yaml
traefik:
    container_name: traefik
    image: traefik:windowsservercore-1809    
    command:      
      - --api=true
      - --api.insecure=true 
      - --api.dashboard=true       
      - --log.level=DEBUG 
      - --providers.docker=true 
      - --providers.docker.exposedbydefault=false 
      - --providers.docker.endpoint=npipe:////./pipe/docker_engine      
      - --entrypoints.web.address=:8002 
      - --entrypoints.websecure.address=:8443 
      - --providers.file.directory=C:/etc/traefik/
      - --providers.file.watch=true
    ports:
      - "8002:8002"
      - "8443:443"
    volumes:
      - ./config:C:/etc/traefik
      - type: npipe
        source: \\.\pipe\docker_engine\
        target: \\.\pipe\docker_engine\    
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)    
      - traefik.http.routers.traefik.entryPoints=web
      - traefik.http.routers.traefik.service=api@internal                
      - traefik.http.services.api@internal.loadbalancer.server.port=8080      
```

The simplified configuration of my other service that I want to enable Traefik:
```yaml
myservice:
    container_name: myservice
    image: myservice:latest         
    labels:   
      - traefik.enable=true
      - traefik.http.routers.myservice.service=myservice
      - traefik.http.routers.myservice.rule=PathPrefix(`/portal`) 
      - traefik.http.routers.myservice.entryPoints=web
      - traefik.http.services.myservice.loadbalancer.server.port=80
      # https        
      - traefik.http.routers.myservice-secure.service=myservice 
      - traefik.http.routers.myservice-secure.entryPoints=websecure 
      - traefik.http.routers.myservice-secure.tls=true
      - traefik.http.routers.myservice-secure.rule=host(`random.hostname`) && PathPrefix(`/portal`) 
      - traefik.http.services.myservice-secure.loadbalancer.server.port=80 
```

My dynamic configuration cert.yml:
```yaml
tls:
    stores:
      default:
        defaultCertificate:
          certFile: C:\etc\traefik\randomhostname.crt
          keyFile: C:\etc\traefik\randomhostname.key
```

### The log output in DEBUG level
```
traefik                  | time="2022-09-10T16:19:50Z" level=info msg="Configuration loaded from flags."
traefik                  | time="2022-09-10T16:19:50Z" level=info msg="Traefik version 2.8.4 built on 2022-09-02T14:42:59Z"
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"traefik\":{\"address\":\":8080\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}},\"web\":{\"address\":\":8002\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}},\"websecure\":{\"address\":\":8443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"npipe:////./pipe/docker_engine\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"},\"file\":{\"directory\":\"C:/etc/traefik/\",\"watch\":true}},\"api\":{\"insecure\":true,\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"pilot\":{\"dashboard\":true}}"
traefik                  | time="2022-09-10T16:19:50Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
traefik                  | time="2022-09-10T16:19:50Z" level=warning msg="Traefik Pilot is deprecated and will be removed soon. Please check our Blog for migration instructions later this year."
traefik                  | time="2022-09-10T16:19:50Z" level=info msg="Starting provider aggregator aggregator.ProviderAggregator"
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="Starting TCP Server" entryPointName=websecure
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="Starting TCP Server" entryPointName=web
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="Starting TCP Server" entryPointName=traefik
traefik                  | time="2022-09-10T16:19:50Z" level=info msg="Starting provider *file.Provider"
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="*file.Provider provider configuration: {\"directory\":\"C:/etc/traefik/\",\"watch\":true}"
traefik                  | time="2022-09-10T16:19:50Z" level=info msg="Starting provider *traefik.Provider"
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="*traefik.Provider provider configuration: {}"
traefik                  | time="2022-09-10T16:19:50Z" level=info msg="Starting provider *acme.ChallengeTLSALPN"
traefik                  | time="2022-09-10T16:19:50Z" level=info msg="Starting provider *docker.Provider"
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="*acme.ChallengeTLSALPN provider configuration: {}"
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="*docker.Provider provider configuration: {\"watch\":true,\"endpoint\":\"npipe:////./pipe/docker_engine\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"}"
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="Provider connection established with docker 20.10.9 (API 1.41)" providerName=docker
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="Configuration received: {\"http\":{},\"tcp\":{},\"udp\":{},\"tls\":{\"stores\":{\"default\":{}}}}" providerName=file
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="Configuration received: {\"http\":{\"routers\":{\"api\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/api`)\",\"priority\":2147483646},\"dashboard\":{\"entryPoints\":[\"traefik\"],\"middlewares\":[\"dashboard_redirect@internal\",\"dashboard_stripprefix@internal\"],\"service\":\"dashboard@internal\",\"rule\":\"PathPrefix(`/`)\",\"priority\":2147483645}},\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{}},\"middlewares\":{\"dashboard_redirect\":{\"redirectRegex\":{\"regex\":\"^(http:\\\\/\\\\/(\\\\[[\\\\w:.]+\\\\]|[\\\\w\\\\._-]+)(:\\\\d+)?)\\\\/$\",\"replacement\":\"${1}/dashboard/\",\"permanent\":true}},\"dashboard_stripprefix\":{\"stripPrefix\":{\"prefixes\":[\"/dashboard/\",\"/dashboard\"]}}},\"serversTransports\":{\"default\":{\"maxIdleConnsPerHost\":200}}},\"tcp\":{},\"udp\":{},\"tls\":{}}" providerName=internal
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="Added outgoing tracing middleware api@internal" entryPointName=traefik routerName=api@internal middlewareName=tracing middlewareType=TracingForwarder
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="Added outgoing tracing middleware dashboard@internal" middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik routerName=dashboard@internal
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="Creating middleware" middlewareType=StripPrefix entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_stripprefix@internal
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="Adding tracing to middleware" middlewareName=dashboard_stripprefix@internal entryPointName=traefik routerName=dashboard@internal
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="Creating middleware" entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_redirect@internal middlewareType=RedirectRegex
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="Setting up redirection from ^(http:\\/\\/(\\[[\\w:.]+\\]|[\\w\\._-]+)(:\\d+)?)\\/$ to ${1}/dashboard/" entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_redirect@internal middlewareType=RedirectRegex
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="Adding tracing to middleware" routerName=dashboard@internal middlewareName=dashboard_redirect@internal entryPointName=traefik
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery
traefik                  | time="2022-09-10T16:19:50Z" level=debug msg="Filtering disabled container" providerName=docker container=rediswin-liveview-withtraefik-6d7b296bc92fc87211ff9aef8a0d131dd149fffa0e2fe3c0095ef2c30b3e8af5
```
