### ISSUE TITLE
Error in YAML parsing

### ISSUE THREAD

**Issue by TheFou** [traefik/traefik#9321]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hi,
I upgraded a Traefik docker container from a quite old version (I don't remember which one exactly... Surely a 2.4.x) to the latest.
It was running flawlessly before, never had any error although it's been rebooted many times.
However, after upgrading, I got errors : 

```
time="2022-09-11T03:55:43Z" level=info msg="Configuration loaded from file: /traefik.yml"
time="2022-09-11T03:55:43Z" level=error msg="Cannot start the provider *file.Provider: /configs/app-vcsa-tcp.yml: strconv.ParseBool: parsing \"║1║true\": invalid syntax"
time="2022-09-11T03:55:44Z" level=error msg="middleware \"chain-authelia@file\" does not exist" routerName=freshrss-external-https-rtr@docker entryPointName=https
time="2022-09-11T03:55:44Z" level=error msg="middleware \"chain-authelia@file\" does not exist" entryPointName=https routerName=adguard-external-https-rtr@docker
```

I didn't modify anything in my config files.
Here is the original app-vcsa-tcp.yml :
```yaml
tcp:
  routers:
    vcsa-internal-https-rtr:
      rule: "HostSNI(`vcsa.foo.bar`)" # will only work with cloudflare Full SSL (not Strict)
      entryPoints:
        - https
      tls:
        passthrough: true
          - true
      service:
        - vcsa-tcp-svc
  services:
    vcsa-tcp-svc:
      loadbalancer:
        servers:
          - address: "x.x.x.x:5480"
```
... and there are other files for middlewares configuration.

### What did you see instead?

To finally make it work again, I had to modify the file above to this :
```yaml
tcp:
  routers:
    vcsa-internal-https-rtr:
      rule: "HostSNI(`vcsa.foo.bar`)" # will only work with cloudflare Full SSL (not Strict)
      entryPoints:
        - https
      tls:
        passthrough: true
      service: vcsa-tcp-svc
  services:
    vcsa-tcp-svc:
      loadbalancer:
        servers:
          - address: "x.x.x.x:5480"
```

To make it clear, the modified lines are :

```yaml
        passthrough: true
      service: vcsa-tcp-svc
```

Then everything worked. I didn't have to modify any other file
I checked online against some yaml validators, and they all consider the initial syntax as valid, as was my previous traefik instance.
Seems you have some issue on your yaml parser.

And that was preventing the other config files from being loaded, thus causing the middlewares errors

### What version of Traefik are you using?

2.8.4

### What is your environment & configuration?

See above

**Comment by ldez** [comment]
Hello,

> level=error msg="Cannot start the provider *file.Provider: /configs/app-vcsa-tcp.yml: strconv.ParseBool: parsing \"║1║true\": invalid syntax"


This error is expected because the YAML configuration is invalid: `tls` cannot be an array and a map at the same time.

> ```yml
>      tls:
>        passthrough: true
>          - true
> ```

To detect the problems, you can use JSON schema validation https://www.schemastore.org/json/.
The schema validation can be integrated into your IDE/text editor.

Duplicate of #9249

**Comment by TheFou** [comment]
Thanks for the answer.
I'm sorry, but this was a mistake while copying / pasting the before / after config.
The original file contained :
```yaml
     tls:
       passthrough:
         - true
```
I edited the original post to correct the typo.
