### ISSUE TITLE
How to forward Authentication header when using redirectRegex

### ISSUE THREAD

**Issue by bppn** [traefik/traefik#9331]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We are using the redirectRegex, but for some reason, the Authentication Header is not forwarded to the replacement.

How can we forward the Authentication header?  The service / passHostHeader has no effect.

Current dynamic template:

```
http:
  services:
    rpcservice:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: 'http://localhost:8084'
  middlewares:
    redirect-rpcservice:
      redirectRegex:
        regex: "^http[s]?://([^/]*)/rpc/([^/]*)/([^/]*)(/|$)(.*)"
        replacement: 'https://${2}container---${3}.{{env "WEBHOST"}}/rpc${4}${5}'
        permanent: false
  routers:
    rpcservice:
      rule: "PathPrefix(`/rpc`)"
      middlewares:
        - "redirect-rpcservice"        
      service: rpcservice
      priority: 50

```

### What did you see instead?

Request are correctly redirected, however, the Authentication header is missing.

### What version of Traefik are you using?

Version: 2.8.4

### What is your environment & configuration?

static configuration:

```yaml
entryPoints:
  http:
    address: ":80"
providers:
  file:
    directory: "/etc/traefik/dynamic"
log:
  level: DEBUG
serversTransport:
  forwardingTimeouts:
    dialTimeout: 120
    idleConnTimeout: 120
ping: {}
# accessLog:
#   format: json
#   fields:
#     defaultMode: keep
#     names:
#       ClientUsername: drop
#     headers:
#       defaultMode: keep
```

Add more configuration information here.
