### ISSUE TITLE
Middleware \"user-auth@file\" does not exist" after traefik update from 2.8.1 to higher releases

### ISSUE THREAD

**Issue by m1sl** [traefik/traefik#9336]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

After the update from 2.8.1 to higher releases (up to the latest stable 2.8.5) error message "user-auth@file does not exist" persists. Rolling back to 2.8.1 helps to solve the issue. Obviously during the update and rolling back the corresponding file is untouched. 

### What did you see instead?

level=error msg="middleware \"user-auth@file\" does not exist" routerName=traefik@docker entryPointName=https

### What version of Traefik are you using?

2.8.1 up to 2.8.5

### What is your environment & configuration?

```yaml
version: "3.7"

services:
  traefik:
    image: traefik:2.8.5
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL=email@gmail.com
      - CF_DNS_API_TOKEN=$TOKEN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/docker/traefik/data/traefik.yml:/traefik.yml:ro
      - /home/docker/traefik/data/acme.json:/acme.json
      - /home/docker/traefik/data/dynamic.yml:/dynamic.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.rule=Host(`traefik.domainname.com`)"
      - "traefik.http.routers.traefik.middlewares=https-redirect@file"
      - "traefik.http.routers.traefik.middlewares=user-auth@file"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik.tls.domains[0].main=*.domainname.com"
      - "traefik.http.routers.traefik.tls.domains[0].sans=domainname.com"
      - "traefik.http.routers.traefik.service=api@internal"

networks:
  proxy:
    external:
      name: proxy
  default:
    driver: bridge
```

Add more configuration information here.

**Comment by rtribotte** [comment]
Hello @m1sl,

Thanks for your interest in Traefik!

We opened https://github.com/traefik/traefik/pull/9340 to add documentation on how to use [JSON schema](https://www.schemastore.org/json/) to validate a dynamic YAML configuration.

The issue you are facing is most probably due to a stricter parsing of the dynamic configuration for "array" types (introduced by https://github.com/traefik/traefik/pull/9258).

Please ensure that the dynamic configuration is valid.

**Comment by m1sl** [comment]
Hello @rtribotte,

Thank you for your prompt reply!
I followed a standard method as described [here ](https://github.com/traefik/traefik/blob/master/docs/content/middlewares/http/basicauth.md) in the documentation:

```
# Declaring the user list
http:
  middlewares:
    user-auth:
      basicAuth:
        users:
          - "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"
```
