### ISSUE TITLE
Cannot use a plugin that doesn't require configuration

### ISSUE THREAD

**Issue by darkweak** [traefik/traefik#9337]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm trying to load a plugin that doesn't require any configuration

In the traefik configuration file I have to declare something like below to bypass:
```yaml
  middlewares:
    dummy_plugin:
      plugin:
        dummy_plugin:
          key: value
```

### What did you see instead?

With the configuration 
```yaml
  middlewares:
    dummy_plugin:
      plugin:
        dummy_plugin: {}
```

`plugin: missing plugin configuration: dummy_plugin`

### What version of Traefik are you using?

from v2.5 to latest

### What is your environment & configuration?

```yaml
http:
  routers:
    whoami:
      middlewares:
        - dummy_plugin
      entrypoints:
        - http
      service: whoami
      rule: Host(`domain.com`)

  services:
    whoami:
      loadBalancer:
        servers:
          - url: http://whoami
        passHostHeader: false

  middlewares:
    dummy_plugin:
      plugin:
        esi: {}
```

Add more configuration information here.
