### ISSUE TITLE
Traffic distribution with K8s ExternalName service is not uniform

### ISSUE THREAD

**Issue by shettyh** [traefik/traefik#9339]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

K8s service 

```yaml
apiVersion: v1
kind: Service
metadata:
  name: test-redirect
spec:
  externalName: test.new_keyspace.svc.cluster.local
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
```

Ingress Route

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: test
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`test.com`) && PathPrefix(`/`)
    services:
    - kind: Service
      name: test-redirect
      port: 8000
```

### What did you see instead?

Traffic distribution with Traefik

![Screenshot 2022-09-15 at 1 39 21 PM](https://user-images.githubusercontent.com/13759916/190350859-486171ed-1df0-4fe9-aa56-f38c192d9fe2.png)

Traffic distribution with K8s service directly

 
![Screenshot 2022-09-15 at 1 43 17 PM](https://user-images.githubusercontent.com/13759916/190351583-554b4d4c-8f1e-4f00-bcd6-d78a375543f4.png)

### What version of Traefik are you using?

2.8.4

### What is your environment & configuration?

```toml
    [entryPoints]
      [entryPoints.web]
        address = ":80"
        [entryPoints.web.forwardedHeaders]
            insecure = true
        [entryPoints.web.transport]
          [entryPoints.web.transport.lifeCycle]
            requestAcceptGraceTimeout = "10s"
            graceTimeOut = "10m0s"
          [entryPoints.web.transport.respondingTimeouts]
            readTimeout = "0s"
            writeTimeout = "0s"
            idleTimeout = "10m0s"
      [entryPoints.metrics]
        address = ":8081"
        [entryPoints.metrics.transport]
          [entryPoints.metrics.transport.lifeCycle]
            requestAcceptGraceTimeout = "10s"
            graceTimeOut = "10m0s"
          [entryPoints.metrics.transport.respondingTimeouts]
            readTimeout = "0s"
            writeTimeout = "0s"
            idleTimeout = "10m0s"
    [ping]
      entryPoint = "web"
      terminatingStatusCode = 0
    [api]
      dashboard = true
      insecure=true
    [metrics]
      [metrics.prometheus]
        buckets = [0.1, 0.3, 1.2, 5.0, 7.0, 9.0, 10.0, 15.0]
        entryPoint = "metrics"
        addRoutersLabels = true

    [providers]

      # Kubernetes CRD provider
      [providers.kubernetescrd]
        ingressClass= "traefik-external"
        allowExternalNameServices = true
        allowCrossNamespace = true
        allowEmptyServices = true
      [providers.kubernetesIngress]
        ingressClass= "traefik-external"
    [log]

    [accessLog]
      format = "json"
      bufferingSize = 0
      [accessLog.fields]
        defaultMode = "keep"
        [accessLog.fields.headers]
          defaultMode = "drop"
          [accessLog.fields.headers.names]
            Accept = "keep"
            Accept-Encoding = "keep"
            Access-Control-Allow-Credentials = "keep"
            Access-Control-Allow-Origin = "keep"
            Access-Control-Request-Headers = "keep"
            Connection = "keep"
            Content-Encoding = "keep"
            Content-Length = "keep"
            Content-Type = "keep"
            Origin = "keep"
            Referer = "keep"
            User-Agent = "keep"
            X-Forwarded-For = "keep"
            X-Requested-With = "keep"
            X-Amz-Cf-Id = "keep"
            x-identifier = "keep"
```

Add more configuration information here.

With ExternalName service Traefik should not try to do Round Robin right ?

**Comment by shettyh** [comment]
Also tried with [this](https://github.com/traefik/traefik/commit/788f8fa951ee215d0d9bd3d43299e400f015e2c1) patch on top of `2.8.4`, issue still exists when the service is of type ExternalName. With this patch distribution is much better for normal k8s services

**Comment by kevinpollet** [comment]
Hello @shettyh,

Thanks for your interest in Traefik,

> With ExternalName service Traefik should not try to do Round Robin right ?

When using an ExternalName service Traefik will not do any load-balancing, and will forward the request to the component with the configured DNS name. As this name is the DNS name of a Kubernetes service, the load-balancing should be done by k8s.

As we are unsure to understand fully what we are seeing, can you explain again what is the setup and the various components for each of the graphs?

**Comment by shettyh** [comment]
Hey @kevinpollet thanks for the response. 

## Scenario 1: With Traefik v2.8.4 ( also with/without patch mentioned above ). 
![Screenshot 2022-09-15 at 8 04 25 PM](https://user-images.githubusercontent.com/13759916/190431801-63047134-9291-4018-a97d-725c3ea109d8.png)

### Traffic Distribution
![](https://user-images.githubusercontent.com/13759916/190350859-486171ed-1df0-4fe9-aa56-f38c192d9fe2.png)

## Scenario 2: Client directly sending requests to External Name service

![Screenshot 2022-09-15 at 8 07 03 PM](https://user-images.githubusercontent.com/13759916/190432440-fb40a4b6-766b-4df8-aac8-23d49bf9aea4.png)

### Traffic Distribution

![](https://user-images.githubusercontent.com/13759916/190351583-554b4d4c-8f1e-4f00-bcd6-d78a375543f4.png)

## Other scenarios
We have also tested similar setup as Traefik v2.8.4 with Traefik v1.7, distribution is much better ( closer to the direct k8s service distribution )

We also had the similar assumption as k8s should be responsible for the round robin, not sure why it is not the case. Any config in tarefik that can cause this ( we are using similar config for v1 and v2 ) or any other reason why this is happening ?.

Please let me know if you need more details on the issue, happy to provide

**Comment by mpl** [comment]
@shettyh 

thanks, the situation is a bit clearer now.
Unfortunately we can only make wild guesses until we have actually reproduced the issue ourselves. We'll let you know whenever that happens.

FYI, one of these wild guesses would be that traefik is keeping connections open (with the pods), that they are being reused, and that it somehow messes up with the load-balancing. But we don't think there's anything you can tinker with to test that hypothesis atm (although do feel free to explore it of course).

**Comment by mpl** [comment]
@shettyh btw, have you tried actually monitoring for a long enough time?
It could very well be that this issue is only temporary, just for things to "settle", and that in the long run the difference does not actually matter at all.

**Comment by sdelicata** [comment]
After further investigation, we found out that the behavior you describe is actually expected.

When using a Kubernetes Service of type ExternalName, the internal loadbalancer created by Traefik contains only one address (the one set in the service with the externalName property). When receiving a request, Traefik creates a connection to a Pod behind this Service and reuses it as long as it stays open (and it stays open as long as it is active + more or less idling time allowed, but more on that below).

In contrast, when using a “regular” Service (i.e.: not of type ExernalName), Traefik creates an internal loadbalancer containing all addresses of Pods behind this Service (Kubernetes Endpoints), then it opens a connection with each pod and properly applies a Round Robin strategy between them.

You can set the maximum amount of time an idle connection stays opened between Traefik and the backend servers (pods) before being closed, but it may have a negative impact on performance (given that opening a connection is a somewhat costly operation):
```yaml
## Static configuration
serversTransport:
  forwardingTimeouts:
    idleConnTimeout: 1s
```

More information: [https://doc.traefik.io/traefik/routing/overview/#forwardingtimeouts](https://doc.traefik.io/traefik/routing/overview/#forwardingtimeouts)

What is likely to happen in your 2nd scenario (https://github.com/traefik/traefik/issues/9339#issue-1374141125) is that the client you are using is not keeping connections open between requests (curl does that for example). A new connection is opened for each request and gets properly distributed between your pods.
