### ISSUE TITLE
traefik error: field not found, node: production

### ISSUE THREAD

**Issue by elax46** [traefik/traefik#9342]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am installing traefik for the first time but I am getting the error 

### What did you see instead?

`traefik error: field not found, node: production`

### What version of Traefik are you using?

```
Status: Downloaded newer image for traefik:latest
Version:      2.8.5
Codename:     vacherin
Go version:   go1.19.1
Built:        2022-09-13T15:19:09Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

Debian 10
Docker version: 20.10.17
Portainer 2.15.0

docker compose file

```yml
version: '3'

services:
  traefik:
    image: traefik:v2.8
    command: --api.insecure=true --providers.docker
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
```
`traefik.yml file`

```yml
global:
  checkNewVersion: true
  sendAnonymousUsage: false  

log:
 level: ERROR  
 format: common 
 filePath: /var/log/traefik/traefik.log

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

 certificatesResolvers:
   staging:
     acme:
       email: emanuele.ladaga@gmail.com
       storage: /etc/traefik/certs/acme.json
       caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
       httpChallenge:
         entryPoint: web

   production:
     acme:
       email: emanuele.ladaga@gmail.com
       storage: /etc/traefik/certs/acme.json
       caServer: "https://acme-v02.api.letsencrypt.org/directory"
       httpChallenge:
       entryPoint: web

providers:
  docker:
    exposedByDefault: false  
  file:
    directory: /etc/traefik
    watch: true
```

**Comment by rtribotte** [comment]
Hello @elax46,

Thanks for your interest in Traefik!

There are two errors in the static configuration, the `certificatesResolvers` node is at the root level and `entryPoint` was not well indented as well:

```yaml
...

certificatesResolvers:
  staging:
    acme:
      email: emanuele.ladaga@gmail.com
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

  production:
    acme:
      email: emanuele.ladaga@gmail.com
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
...
```

We created a dedicated section for these errors in our FAQ (please take a look at https://doc.traefik.io/traefik/getting-started/faq/#what-does-the-field-not-found-error-mean).

Your issue is related to a configuration issue and the GitHub issue tracker is dedicated to bug and feature requests.

For help with your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik). 

We will close this issue accordingly but feel free to re-open it if you think that we missed something.
