### ISSUE TITLE
'Gateway timeout' Kubernetes

### ISSUE THREAD

**Issue by lvijnck** [traefik/traefik#9345]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hi, 

For a while I've been struggling with a 'Gateway timeout' error that I am getting while leveraging Traefik's IngressRoute EKS. My lineage is visualized below. Remarkable here is that on my local (kubernetes-in-docker) setup, everything is working as expected, while my EKS cluster is returning a 'Gateway timeout'. On my Traefik dashboard the IngressRoute is shown as healthy.

```
Local machine/				# SSH into EC2 instance
├─ EC2 instance/			# Port forward into Traefik
│  ├─ Traefik/				# Host based routing into service
│  │  ├─ Service/			# Port based routing into Pod
│  │  │  ├─ Deployment/
│  │  │  │  ├─ Pod/
```

Given the port-forwarding from EC2 into the cluster, i.e.,

```
kubectl port-forward service/traefik 8000:80 -n qb
```

My initial hypothesis was that, due to the SSH setup, the connection timed out. When I curl'ed the host directly from EC2, I was also receiving the timeout.

```
curl -H "Host: workspace.localhost" localhost:8000
``` 

As an additional experiment, I tried to setup port-forwarding from EC2 directly into the service and pod objects. Both of these experiments were successful. I am currently using this approach as a workaround, but I would really like to understand why this is happening. Adding my manifests below.

P.S. I had two services up this way in an identical fashion. First, I was running on Traefik version 2.8.4, at that point one of the two services was working. I noticed my local KinD cluster was running on 2.8.5, so I updated the service on my cluster. Hereafter, both services generated the Gateway timeout.

Thanks in advance!

### What did you see instead?

Gateway timeout

### What version of Traefik are you using?

2.8.5

### What is your environment & configuration?

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: lvi-workspace
  labels:
    app: lvi-workspace
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: "Host(`workspace.localhost`)"
    services:
    - name: lvi-workspace-service
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lvi-workspace-service
  namespace: workspace
  labels:
    app: lvi-workspace
spec:
  selector:
    app: lvi-workspace
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lvi-workspace
  namespace: workspace
  labels:
    app: lvi-workspace
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: lvi-workspace
  template:
    metadata:
      labels:
        app: lvi-workspace
    spec:
      containers:
      - name: workspace
        image: codercom/code-server
        command: ["/bin/sh"]
        args: ["/usr/bin/entrypoint.sh", "--bind-addr", "0.0.0.0:8080", "--auth", "none", "."]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
      restartPolicy: Always
```
