### ISSUE TITLE
Middleware is sometimes not found when defined in the traefik service's docker labels

### ISSUE THREAD

**Issue by PotcFdk** [traefik/traefik#9363]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm using traefik as part of a rather simple docker compose based setup.
On the traefik service I set a label similar to this one:
`- traefik.http.middlewares.default-ssl.headers.STSSeconds=3600`

Another service has a label similar to this one:
`- traefik.http.routers.someservice.middlewares=default-ssl`

This usually works fine, the only log line is
> level=info msg="Configuration loaded from flags."

and all is well.

### What did you see instead?

"Sometimes" (about 1 in 10 times) after stopping, removing and restarting the traefik service, it starts up with additional errors similar to:
> level=error msg="middleware \"default-ssl@docker\" does not exist" entryPointName=websecure routerName=someservice@docker

Since usually this seems to work (as I said, it works like 9 out of 10 times) it feels like some kind of race condition, where apparently traefik seems to load the router configuration (including the referenced middleware) before it sets up the middleware itself?

### What version of Traefik are you using?

```
traefik             v2.8             2caeed3432ab   8 days ago     106MB
```
```
Version:      2.8.5
Codename:     vacherin
Go version:   go1.19.1
Built:        2022-09-13T15:19:09Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
version: '3'
[...]
services:
  reverse-proxy:
    image: traefik:v2.8
    restart: always
    [...]
    labels:
      [...]
      - traefik.http.middlewares.default-ssl.headers.STSSeconds=3600
      [...]
  someservice:
    image: [...]
    restart: always
    labels:
      [...]
      - traefik.http.routers.someservice.entrypoints=websecure
      - traefik.http.routers.someservice.middlewares=default-ssl
      [...]

```
