### ISSUE TITLE
Enable dynamic configuration for proxyProtocol.trustedIPs

### ISSUE THREAD

**Issue by bluepuma77** [traefik/traefik#9378]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

It would be great to have `trustedIPs` as dynamic config, so when we add a load balancer we don't need to restart Traefik, but we can just update a dynamic configuration file for "zero downtime deployments".

From the [Traefik EntryPoints docs](https://doc.traefik.io/traefik/routing/entrypoints/#proxyprotocol):

```
## Static configuration
entryPoints:
  web:
    address: ":80"
    proxyProtocol:
      trustedIPs:
        - "127.0.0.1/32"
        - "192.168.1.7" 
```
