### ISSUE TITLE
Constant reloading of the whole rule set every 30 seconds causing disruption

### ISSUE THREAD

**Issue by clauderobi** [traefik/traefik#9384]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am using traefik in a docker environment (not swarm) using proper labels for the containers that need to be exposed. For TLS certificates I am using a combination of lets encrypt public certificates for certain service and static certificates for others. 

All is working as expected except that the rule set is completely rebuilt every 30 seconds

### What did you see instead?

Because of the constant rebuild, if a request comes at a bad moment, the default certificate is provided instead of the lets encrypt or static one. I also suspect that some requests are actually simply ignored / rejected (but this is speculative).

The end effect is obviously that my service is not reliable.

### What version of Traefik are you using?

Version:      2.8.7
Codename:     vacherin
Go version:   go1.19.1
Built:        2022-09-23T14:34:26Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
# The Traefik dashboard
api:
  dashboard: true
  debug: true
  insecure: true


log:
  level: DEBUG
  format: common

# Define an HTTPS entrypoints
entryPoints:
  web:
    address: ":80"
  secure:
    address: ":443"

providers:
  file:
    directory: /datastore/loadBalancer
    watch: true

  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedbydefault: false
    network: "thor_default"
    swarmMode: false
    swarmModeRefreshSeconds: 30

# Static TLS files
tls:
  certificates:
  - certFile: /datastore/certificates/ap.crt
    keyfile: /datastore/certificates/ap.key
  - certFile: /datastore/certificates/api.crt
    keyfile: /datastore/certificates/api.key
  - certFile: /datastore/certificates/charon.crt
    keyfile: /datastore/certificates/charon.key        
  - certFile: /datastore/certificates/portunus.crt
    keyfile: /datastore/certificates/portunus.key
  options:
    default:
      minVersion: VersionTLS12

    mintls13:
      minVersion: VersionTLS13

certificatesResolvers:
  letsEncryptResolver:
    acme:
      email: xxxxxxxxxx
      storage: /datastore/loadBalancer/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

Example of lines that appears every ~30 sec

time="2022-09-28T12:12:10Z" level=debug msg="Configuration received: {\"http\":{},\"tcp\":{},\"udp\":{},\"tls\":{\"options\":{\"default\":{\"minVersion\":\"VersionTLS12\",\"clientAuth\":{},\"alpnProtocols\":[\"h2\",\"http/1.1\",\"acme-tls/1\"]},\"mintls13\":{\"minVersion\":\"VersionTLS13\",\"clientAuth\":{},\"alpnProtocols\":[\"h2\",\"http/1.1\",\"acme-tls/1\"]}}}}" providerName=file

time="2022-09-28T12:15:14Z" level=debug msg="Adding certificate for domain(s) xxxxx"

time="2022-09-28T12:49:37Z" level=debug msg="Adding route for xxxxxx with TLS options default" entryPointName=secure
