### ISSUE TITLE
BasicAuth/DigestAuth support for multiple paths in usersFile option

### ISSUE THREAD

**Issue by jguizarj** [traefik/traefik#9388]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

## Context 

Hello everyone! 

I'm implementing a Docker private registry using Traefik as a reverse proxy and authentication provider.

The registry is using BasicAuth middleware.  Two type of users are distinguished:

-  **Read-only** users can use `GET` and `HEAD` methods
-  `POST`, `PUT`, `DELETE` and `PATCH` methods are limited to the **read/write** users.

To separate the permissions I'm using two routers:
- **read-only** router Rule: ``Host(`my-registry.com`) && Method(`GET`, `HEAD`)``
- **read/write** router Rule: ``Host(`my-registry.com`) && Method(`POST`, `PUT`, `DELETE`, `PATCH`)``

Each router has its own BasicAuth middleware:
- **read-only** auth middleware: ``read-only-auth@file``
- **read/write** auth middleware: ``read-write-auth@file``

Due to the separation of HTTP methods, allowing read/write users to use `GET` and `HEAD` implies:
1. Add read/write users to the read-only list **(duplication is not an option)**
2. Merge read/write users list into the read-only users middleware **(current solution)**

## Current solution

My current solution adds the `usersFile` option to the `read-only-auth` middleware, merging **read/write** users with **read-only users**

> registry-auth.yaml

```
http:
  middlewares:
    read-only-auth:
      basicAuth:
        # Read-write users also access GET and HEAD methods
        usersFile: /path/to/read-write-users
        users:
          # Read-only users
          - "read-only-user:$apr1$Cht.GI/c$4Et2jkn7YSuj0Gq3B5/2t0"
      
    read-write-auth:
      basicAuth:
        # Read-write users
        usersFile: /path/to/read-write-users
```

I see two problems in this approach:
1. **Read-only** users are managed as a list in the `yaml` file and **read/write** users are kept in a separate text file
2.  Merging more than 2 sets of users is not posible.

## Design proposal
Parse an array of paths as the `usersFile` value, allowing merging any number of user sets

> registry-auth.yaml

```
http:
  middlewares:
    read-only-auth:
      basicAuth:
        usersFile:
          - "/path/to/read-only-users"
          - "/path/to/read-write-users"
      
    read-write-auth:
      basicAuth:
        usersFile:
          - "/path/to/read-write-users"
```
