### ISSUE TITLE
unknown TLS options: traefik-default@kubernetescrd

### ISSUE THREAD

**Issue by KqLLL** [traefik/traefik#9390]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We create a tlsoption (name is default) in the traefik namespace and use it in the kubernetes ingress( traefik.ingress.kubernetes.io/router.tls.options: traefik-default@kubernetescrd);

Traefik will have a lot of error logs is `unknown TLS options: traefik-default@kubernetescrd`;
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/76542414/193001408-fe6f42ec-4490-4746-91e4-ee451dbc4e89.png">

### What did you see instead?

null

### What version of Traefik are you using?

v2.87

### What is your environment & configuration?

```yaml
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
    traefik.ingress.kubernetes.io/router.tls.options: traefik-default@kubernetescrd
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

null
