### ISSUE TITLE
FastCGI support proposal

### ISSUE THREAD

**Issue by Scorpil** [traefik/traefik#9393]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### Abstract

FastCGI is a popular binary protocol for a script-to-server communication. Ability to configure FastCGI as a destination would simplify workflows for user who are currently forced to introduce another internal proxy just for FastCGI-to-HTTP conversion.

- Previous discussion: #753
- Proof-of-concept PR: #9382

### Configuration Schema

Within Traefik's architecture, FastCGI is viewed as a type of transport configuration, so most of FastCGI configuration parameters are placed in `http.serversTransport.<name>` dynamic configuration object. Notable exception is an endpoint URI, which are defined in a way similar to other endpoint type, e.g. `http.services.<name>.loadBalancer.servers.*.url`.

#### Endpoint URI

For FastCGI endpoints, `tcp://` and `unix:/` uri schemas are supported, for either TCP or socket connections.

```
http:
  services:
    app:
      loadBalancer:
        servers:
        - url: "tcp://wordpress:9000/"
        serversTransport: fastcgiApp
```

#### Transport configuration

To create a serverTransport for FastCGI connection, `fastCGI` object with an `index` record needs to be specified. `index` field is a required parameter.

By default, Traefik sends FastCGI environment variables [compatible with PHP-fpm](https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/), but it is possible to override those through `env` parameter. For maximum configuration flexibility, `env` allows **any** environment variable names (as oppsoed to a predefined set of supported values).

```
http:
  serversTransports:
    fastcgiApp:
      fastCGI:
        index: index.php
        env:
            HTTP_PROXY: ""
            MY_CUSTOM_VAR: "value"
```

If `fastCGI` is defined, HTTP-specific `serversTransports` parameters are ignored with a warning. For example:

```yaml
http:
  serversTransports:
    app:
      fastCGI:
        index: index.php
      insecureSkipVerify: true
```

Config above should result in a warning log message, for example:

> Warning: `htpp.serversTransports.app.insecureSkipVerify` is not compatible with `http.serversTransports.app.fastCGI` and will be ignored.

#### Implementation concerns

Implementation: unfortunately, no well-maintained Fast-CGI library exists currently for Go. The most promising one is https://github.com/yookoala/gofast.

The main benefit of FastCGI is an ability to maintain a persistent tcp/socket connection between a webserver and an application, multiplexing incoming HTTP requests through it. In a context of a loadbalancer service, this means maintaining a pool of connected services.

#### References

- [FastCGI specification](https://fast-cgi.github.io/spec)
- [Nginx FastCGI](https://www.nginx.com/resources/wiki/start/topics/examples/fastcgiexample/)

#### Full config example

```
http:

  routers:
    root:
      rule: "PathPrefix(`/`)"
      service: app

  serversTransports:
    fastcgiApp:
      fastCGI:
        index: index.php

  services:
    app:
      loadBalancer:
        servers:
        - url: "tcp://wordpress:9000/"
        serversTransport: fastcgiApp
```
