### ISSUE TITLE
Unable to proxy traffic to TLS backend?

### ISSUE THREAD

**Issue by larsks** [traefik/traefik#9401]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have a backend service that exposes a TLS port.

I'm trying to configure Traefik to proxy access to this backend service using the following ingress resource:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: step-certificates
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: incluster

spec:
  rules:
    - host: ca.apps.infra.house
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  step-certificates
                port:
                  name: https
```

The certificate presented by the backend service is signed by an internal certificate authority. The CA certificate has been injected into the Traefik container at `/etc/ssl/certs/<hash>.0`, and we can verify the certificate is trusted by e.g. using `wget` in the Traefik container to access the backend service.

### What did you see instead?

When attempting to access the backend service through this ingress resource, Traefik logs:

```
traefik-5b7846f4fd-94jxx traefik time="2022-09-30T11:37:24Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="..." ForwardURL="https://10.244.0.73:9000"
traefik-5b7846f4fd-94jxx traefik time="2022-09-30T11:37:24Z" level=debug msg="'500 Internal Server Error' caused by: x509: cannot validate certificate for 10.244.0.73 because it doesn't contain any IP SANs"
```

It looks like Traefik is simply using the IP address of the pod in the forwarding URL, which means there's effectively no way to trust the backend certificate: since we're not using a hostname, the names in the certificate will never match.

Because the backend IP is dynamic, it's not possible to make the certificate valid for just the IP address. Additionally, it doesn't appear to be possible to configure Traefik to use a hostname in the request rather than using the IP address.

Is there any way to configure this correctly *without* configuring passthrough TLS using an IngressRouteTCP resource?

---

I've worked around the problem for now by adding an nginx http-to-https proxy sidecar to the target pod, so that the Service exposes a non-TLS port for use by Traefik.

### What version of Traefik are you using?

Version:      2.8.7
Codename:     vacherin
Go version:   go1.19.1
Built:        2022-09-23T14:34:26Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

Traefik ingress using version 10.24.3 of the Helm chart.
