### ISSUE TITLE
Getting a 502 Bad Gateway with secured websocket

### ISSUE THREAD

**Issue by JulienChampagnol** [traefik/traefik#9403]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I tried to connect to a secured websocket (using aiohttp) via traefik using AWS Fargate and an ECS provider
I tried with another (http) container (using flask) and it's working fine.
The WSS container is working by pinging its direct address with a simple GET request but not via traefik:

- https://IP/viewer => not working via traefik, returns 502
- https://IP:1234 => working without traefik, returns 200

### What did you see instead?

502 - Bad Gateway

### What version of Traefik are you using?

v2.8.4

### What is your environment & configuration?

```yaml
{
  "containerDefinitions": [
    {
      "portMappings": [
        {
          "hostPort": 443,
          "protocol": "tcp",
          "containerPort": 443
        },
        {
          "hostPort": 8080,
          "protocol": "tcp",
          "containerPort": 8080
        }
      ],
      "image": "traefik",
      "name": "Traefik",
      "command": [
        "--api.dashboard=true",
        "--api.insecure=true",
        "--log.level=DEBUG",
        "--providers.ecs=true",
        "--providers.ecs.exposedbydefault=false",
        "--providers.ecs.autoDiscoverClusters=false",
        "--providers.ecs.clusters=Dev_VisualizationCluster",
        "--entrypoints.websecure.address=:443",
        "--serversTransport.insecureSkipVerify=true"
      ],
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-create-group": "true",
          "awslogs-group": "/ecs/Dev_VisualizationTaskDefinition/traefik",
          "awslogs-region": "eu-west-3",
          "awslogs-stream-prefix": "ecs"
        }
      }
    },
    {
      "name": "VisualizationContainer",
      "image": "ghcr.io/geode-solutions/visualization_backend:develop",
      "cpu": 0,
      "portMappings": [
        {
          "hostPort": 1234,
          "protocol": "tcp",
          "containerPort": 1234
        }
      ],
      "essential": true,
      "dockerLabels": {
        "traefik.enable": "true",
        "traefik.http.middlewares.viewer-strip.stripprefix.forceSlash": "false",
        "traefik.http.middlewares.viewer-strip.stripprefix.prefixes": "/viewer",
        "traefik.http.routers.viewer-router.entrypoints": "websecure",
        "traefik.http.routers.viewer-router.middlewares": "viewer-strip",
        "traefik.http.routers.viewer-router.rule": "PathPrefix(`/viewer`)",
        "traefik.http.routers.viewer-router.tls": "true",
        "traefik.port": "1234"
      },
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-create-group": "true",
          "awslogs-group": "/ecs/Dev_VisualizationTaskDefinition/viewer",
          "awslogs-region": "eu-west-3",
          "awslogs-stream-prefix": "ecs"
        }
      }
    }
  ],
  "memory": "8192",
  "family": "Dev_VisualizationTaskDefinition",
  "networkMode": "awsvpc",
  "cpu": "4096",
  "requiresCompatibilities": [
    "FARGATE"
  ]
}
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

<html><body>

30/09/2022 16:55:20 | time="2022-09-30T14:55:20Z" level=debug msg="'502 Bad Gateway' caused by: EOF" | Traefik
-- | -- | --
30/09/2022 16:55:20 | time="2022-09-30T14:55:20Z"  level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on  request"  Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"\",\"RawPath\":\"\",\"OmitHost\":false,\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip,  deflate, br\"],\"Connection\":[\"close\"],\"User-Agent\":[\"Thunder  Client  (https://www.thunderclient.com)\"],\"X-Forwarded-Host\":[\"13.38.98.224\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Prefix\":[\"/viewer\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"ip-172-31-18-187.eu-west-3.compute.internal\"],\"X-Real-Ip\":[\"185.146.220.125\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"13.38.98.224\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"185.146.220.125:48211\",\"RequestURI\":\"/\",\"TLS\":null}" | Traefik

</body>
</html>
