### ISSUE TITLE
Redis connect failed just show NOAUTH Authentication required

### ISSUE THREAD

**Issue by leotu** [traefik/traefik#9416]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I run new release version [v2.9.1](https://github.com/traefik/traefik/releases/tag/v2.9.1) [Latest](https://github.com/traefik/traefik/releases/latest)

It still has problem that can't login Redis with specified username & password

https://github.com/traefik/traefik/issues/9304
https://github.com/kvtools/redis/issues/3

### What did you see instead?

It does have to have an account and password,
but whether to provide a password or not, it always show
"KV connection error: KV store connection error: NOAUTH Authentication required..."

I write java test code, it login success, but Traefik failed

- https://lettuce.io/

```java
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.CountDownLatch;

import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.lettuce.core.RedisClient;
import io.lettuce.core.RedisURI;
import io.lettuce.core.codec.StringCodec;

class TestRedisClient {
    private static final Logger log = LoggerFactory.getLogger(TestRedisClient.class);

    @Test
    void test() {
        log.debug("Begin...");
        CountDownLatch latch = new CountDownLatch(1);
        try {
            String username = URLEncoder.encode("traefik-user", StandardCharsets.UTF_8);
            String password = URLEncoder.encode("~treafik-Test-109!", StandardCharsets.UTF_8);
            String connectionString = "redis://" + username + ":" + password
                    + "@redis-14654.c289.us-west-1-2.ec2.cloud.redislabs.com:14654/0";
            
            RedisURI redisURI = RedisURI.create(connectionString);

            RedisClient client = RedisClient.create();
            client.connectAsync(StringCodec.UTF8, redisURI)
                    .thenAccept(conn -> {
                        log.debug("onSuccess, conn: {}", conn);
                        conn.close();
                        latch.countDown();
                    })
                    .exceptionally(err -> {
                        log.error("onFailure", err);
                        latch.countDown();
                        return null;
                    });

            log.debug("Before await");
            latch.await();
            
            client.close();
            log.debug("After await");
        } catch (Exception e) {
            log.error(e.toString());
        } finally {
            log.debug("End.");
        }
    }
}
```

### What version of Traefik are you using?

[traefik_v2.9.1_windows_amd64.zip](https://github.com/traefik/traefik/releases/download/v2.9.1/traefik_v2.9.1_windows_amd64.zip)

```sh
D:\traefik>traefik version
2022/10/05 23:42:47 Datadog Tracer v1.38.1 WARN: Unable to load high precison timer, defaulting to time.Now()
Version:      2.9.1
Codename:     banon
Go version:   go1.19.1
Built:        2022-10-03T14:22:13Z
OS/Arch:      windows/amd64
```

### What is your environment & configuration?

 Here is test Account

```yaml
providers:
  redis: 
    rootKey: "traefik"
    username: "traefik-user"
    password: "~treafik-Test-109!"  
    endpoints:
      - "redis-14654.c289.us-west-1-2.ec2.cloud.redislabs.com:14654"
```

### If applicable, please paste the log output in DEBUG level

```sh
time="2022-10-05T21:20:47+08:00" level=info msg="Traefik version 2.9.1 built on 2022-10-03T14:22:13Z"
time="2022-10-05T21:20:47+08:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
time="2022-10-05T21:20:47+08:00" level=info msg="Enabling ProxyProtocol without trusted IPs: Insecure" entryPointName=http
time="2022-10-05T21:20:47+08:00" level=info msg="Enabling ProxyProtocol without trusted IPs: Insecure" entryPointName=https
time="2022-10-05T21:20:47+08:00" level=info msg="Starting provider aggregator aggregator.ProviderAggregator"
time="2022-10-05T21:20:47+08:00" level=info msg="Starting provider *file.Provider"
time="2022-10-05T21:20:47+08:00" level=info msg="Starting provider *traefik.Provider"
time="2022-10-05T21:20:47+08:00" level=info msg="Starting provider *consulcatalog.Provider"
time="2022-10-05T21:20:47+08:00" level=info msg="Starting provider *acme.ChallengeTLSALPN"
time="2022-10-05T21:20:47+08:00" level=info msg="Starting provider *redis.Provider"
time="2022-10-05T21:20:48+08:00" level=error msg="KV connection error: KV store connection error: NOAUTH Authentication required, retrying in 525.860654ms" providerName=redis
time="2022-10-05T21:20:48+08:00" level=error msg="KV connection error: KV store connection error: NOAUTH Authentication required, retrying in 922.623964ms" providerName=redis
time="2022-10-05T21:20:49+08:00" level=error msg="KV connection error: KV store connection error: NOAUTH Authentication required, retrying in 1.542543566s" providerName=redis
time="2022-10-05T21:20:51+08:00" level=error msg="KV connection error: KV store connection error: NOAUTH Authentication required, retrying in 1.281710557s" providerName=redis
time="2022-10-05T21:20:52+08:00" level=error msg="KV connection error: KV store connection error: NOAUTH Authentication required, retrying in 2.089869192s" providerName=redis
time="2022-10-05T21:20:55+08:00" level=error msg="KV connection error: KV store connection error: NOAUTH Authentication required, retrying in 5.110286725s" providerName=redis
```

**Comment by alorle** [comment]
Same here. I can confirm that in v2.8.8 the problem is not present.

**Comment by ldez** [comment]
in v2.8.8 the username was not supported -> #9304.

**Comment by ldez** [comment]
I'm looking for a `redis.conf` to reproduce the problem.

**Comment by leotu** [comment]
# Here is a sample config file (My MacOS)

## traefik.yml

```yaml
log:
  level: info
  filePath: "./log/traefik.log"

accessLog:
  filePath: "./log/access.log"
  bufferingSize: 100
  filters:    
    statusCodes:
      - "200"
      - "300-302"
    retryAttempts: true
    minDuration: "10ms"
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: redact
        Authorization: drop
        Content-Type: keep

providers:
  file:
    watch: true
    directory: "./conf"
    debugLogGeneratedTemplate: true
 
  redis: 
    rootKey: "traefik:"
    username: "emojiwe.io"
    password: "Powerk6~"
    endpoints:
      - "redis-16561.c289.us-west-1-2.ec2.cloud.redislabs.com:16561"

entryPoints:
  http: # web
    address: ":8181"
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      insecure: true
    transport:
      respondingTimeouts:
        readTimeout: 60s  
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          
  https:
    address: ":8443"
    proxyProtocol:
      insecure: true
    transport:
      respondingTimeouts:
        readTimeout: 60s

  traefik:
    address: ":8282"

api:
  insecure: true
  debug: true
  dashboard: true
```

## traefik.log

```txt
time="2022-10-12T22:04:58+08:00" level=info msg="Traefik version 2.9.1 built on 2022-10-03T14:22:13Z"
time="2022-10-12T22:04:58+08:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
time="2022-10-12T22:04:58+08:00" level=info msg="Enabling ProxyProtocol without trusted IPs: Insecure" entryPointName=http
time="2022-10-12T22:04:58+08:00" level=info msg="Enabling ProxyProtocol without trusted IPs: Insecure" entryPointName=https
time="2022-10-12T22:08:50+08:00" level=info msg="Traefik version 2.9.1 built on 2022-10-03T14:22:13Z"
time="2022-10-12T22:08:50+08:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
time="2022-10-12T22:08:50+08:00" level=info msg="Enabling ProxyProtocol without trusted IPs: Insecure" entryPointName=http
time="2022-10-12T22:08:50+08:00" level=info msg="Enabling ProxyProtocol without trusted IPs: Insecure" entryPointName=https
time="2022-10-12T22:08:50+08:00" level=info msg="Starting provider aggregator aggregator.ProviderAggregator"
time="2022-10-12T22:08:50+08:00" level=info msg="Starting provider *file.Provider"
time="2022-10-12T22:08:50+08:00" level=info msg="Starting provider *traefik.Provider"
time="2022-10-12T22:08:50+08:00" level=info msg="Starting provider *acme.ChallengeTLSALPN"
time="2022-10-12T22:08:50+08:00" level=info msg="Starting provider *redis.Provider"
time="2022-10-12T22:08:50+08:00" level=error msg="KV connection error: KV store connection error: NOAUTH Authentication required, retrying in 619.568247ms" providerName=redis
time="2022-10-12T22:08:51+08:00" level=error msg="KV connection error: KV store connection error: NOAUTH Authentication required, retrying in 809.331073ms" providerName=redis
time="2022-10-12T22:08:52+08:00" level=error msg="KV connection error: KV store connection error: NOAUTH Authentication required, retrying in 1.098028431s" providerName=redis
time="2022-10-12T22:08:53+08:00" level=error msg="KV connection error: KV store connection error: NOAUTH Authentication required, retrying in 1.559602842s" providerName=redis
time="2022-10-12T22:08:55+08:00" level=error msg="KV connection error: KV store connection error: NOAUTH Authentication required, retrying in 3.066236807s" providerName=redis


```

**Comment by leotu** [comment]
# Redis GUI tool login screenshot
- https://redis.com/redis-enterprise/redis-insight/

<img width="606" alt="截圖 2022-10-12 22 32 15" src="https://user-images.githubusercontent.com/1053138/195372209-8b91d7eb-13ce-448a-b941-5e741ffde8d1.png">


<img width="981" alt="截圖 2022-10-12 22 34 09" src="https://user-images.githubusercontent.com/1053138/195372373-d644f8e1-59e1-4a69-9ce3-7a9c23c252b2.png">

**Comment by ldez** [comment]
I don't have Redis Enterprise, I just have the open-source version, so I'm looking for a `redis.conf` file.

**Comment by leotu** [comment]
## redis.conf

```yaml
#protected-mode no
requirepass "_default_pwd~"

user traefik-user on >~treafik-Test-109! ~* +@all
```

## Step by step

```sh
sudo mkdir /opt/redis-test
sudo chown -R $(whoami) /opt/redis-test
sudo chmod +wr /opt/redis-test

cd /opt/redis-test
cp -r $HOME/.../redis.conf /opt/redis-test

docker run -v /opt/redis-test:/usr/local/etc/redis -d --name redis-test -p 14654:6379 --restart always redis:6 /usr/local/etc/redis/redis.conf
```

## traefik.yml

```
...
providers:
  file:
    watch: true
    directory: "./conf"
    debugLogGeneratedTemplate: true
 
  redis: 
    rootKey: "traefik"
    username: "traefik-user"
    password: "~treafik-Test-109!"  
    endpoints:
      #- "redis-14654.c289.us-west-1-2.ec2.cloud.redislabs.com:14654"
      - "127.0.0.1:14654"
...
```

**Comment by leotu** [comment]
GUI Tool  login default user success, traefik login failed

```yaml
providers:
  ...
  redis: 
    rootKey: "traefik"
    #username: "traefik-user"
    #password: "~treafik-Test-109!"
    username: "default"
    password: "_default_pwd~"
    endpoints:
      - "127.0.0.1:14654"
  ...
 ```
