### ISSUE TITLE
[Docker Swarm] redis tls passthrough issue

### ISSUE THREAD

**Issue by gray380** [traefik/traefik#9420]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have the following configuration:

traefik static config:
```
entryPoints:
  redisacl:
    address: ":16100"
```

docker-compose (exposed port 16379 and labeled traefik entrypoint 16100 at the same time for the debugging purpose):
```
  testredis:
    image: redis:7.0.4
    ports:
      - 16379:6379
    hostname: testredis
    deploy:
      labels:
         # Add labels for Traefik loadbalancer
         - traefik.enable=true
         - traefik.tcp.routers.testredis.rule=HostSNI(`redisssl.test.lan`)
         - traefik.tcp.routers.testredis.service=testredis
         - traefik.tcp.routers.testredis.entrypoints=redisacl
         - traefik.tcp.services.testredis.loadbalancer.server.port=6379
         - traefik.tcp.routers.testredis.tls=true
         - traefik.tcp.routers.testredis.tls.passthrough=true
```
I've tried 
```
traefik.tcp.routers.testredis.rule=HostSNI(`*`) 
```
as well.
I can see the TCP Service and Routers in the Traefik dashboard.

Ports are open:
```
nc -zv redisssl.test.lan 16379
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to xxx.xxx.xxx.35:16100.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.

nc -zv redisssl.test.lan 16100
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to xxx.xxx.xxx.35:16379.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
```
But connection to the redis via port 16100 has failed.
```
redis-cli --sni redisssl.test.lan -h redisssl.test.lan -p 16379 --tls --cacert /usr/local/etc/redis/tls/ca.crt --cert /usr/local/etc/redis/tls/redis.crt --key /usr/local/etc/redis/tls/redis.key
OK

redis-cli --sni redisssl.test.lan -h redisssl.test.lan -p 16100 --tls --cacert /usr/local/etc/redis/tls/ca.crt --cert /usr/local/etc/redis/tls/redis.crt --key /usr/local/etc/redis/tls/redis.key
Could not connect to Redis at redisssl.test.lan:16100: SSL_connect failed: Success
```
From the remote windows client the following error has appeared: `Error: Protocol error, got "H" as reply type byte`

### What did you see instead?

Could not connect to Redis at redisssl.test.lan:16100: SSL_connect failed: Success
Error: Protocol error, got "H" as reply type byte

### What version of Traefik are you using?

/ # traefik version
Version:      2.8.3
Codename:     vacherin
Go version:   go1.19
Built:        2022-08-12T14:24:34Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
api:
  dashboard: true

log:
  level: ERROR

accessLog:
  format: json
  bufferingSize: 5

providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: true
    network: traefik
    swarmModeRefreshSeconds: 5
  file:
    directory: /dynamic/conf.d
    watch: true


entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
  ping:
    address: ":8082"
  metrics:
    address: ":8083"
  redisacl:
    address: ":16100"

ping:
  entryPoint: ping

metrics:
  prometheus:
    entryPoint: metrics

```

Add more configuration information here.
