### ISSUE TITLE
AllowEmptyService flag is not taken into account on traefikService in kubernetes crd

### ISSUE THREAD

**Issue by jeromeguiard** [traefik/traefik#9423]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I was adding an empty service to a TraefikService

This parameter was setted
```
--providers.kubernetescrd.allowemptyservices=true
```

### What did you see instead?

Building a TraefikService object with empty service as source led to this error:

```
Error while building TraefikService: subset not found for web/my-app-canary","providerName":"kubernetescrd","serviceName":"my-app","time":"2022-08-05T12:34:56Z"}
```

### What version of Traefik are you using?

v2.9.1

### What is your environment & configuration?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: my-app
  namespace: web
spec:
  weighted:
    services:
      - name: my-app-canary
        namespace: web
        port: 80
        weight: 0
      - name: my-app-stable
        namespace: web
        port: 80
        weight: 100

---

apiVersion: v1
kind: Service
metadata:
  name: my-app-stable
  namespace: web
spec:
  selector:
    app: my-app-stable
  type: ClusterIP
  ports:
    - name: main
      port: 80
      targetPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: my-app-canary
  namespace: web-ui
spec:
  selector:
    app: my-app-canary
  type: ClusterIP
  ports:
    - name: main
      port: 80
      targetPort: 80
      protocol: TCP

```
