### ISSUE TITLE
Unable to connect to service, web GUI shows active Router for unconfigured Entrypoints

### ISSUE THREAD

**Issue by aSemy** [traefik/traefik#9425]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm running Traefik from a docker-compose.yml. I've connected it to Docker via a network.

I'm trying to connect to a container, `foundry-foundry@docker`. I've configured the config last week, but yesterday I upgraded to 2.9.1 from 2.7.1, and it no longer works. When I visit `https://foundry.mywebsite.com/` I get a 404 (or, depending on my config, a redirect to a whoami container I've setup as a fallback to debug issues). Downgrading to 2.7.1 doesn't change things.

### What did you see instead?

I'm not able to connect to `http://foundry.mywebsite.com/` - get a 404

When I look in the web GUI I can see that there are multiple entry points for the Foundry router, even though I've only defined one.

```yaml
http:
  routers:
    foundry-route:
      rule: "Host(`foundry.adamko.dev`) && PathPrefix(`/`)"
      service: "foundry-foundry@docker"
      entrypoints:
        - "websecure"
```

![image](https://user-images.githubusercontent.com/897017/194698623-a1990da1-aeb9-4e53-81dd-d4b525ea9152.png)

I don't expect to see Foundry using these Entrypoints:

```
Host(`foundry-foundry`) | factorio-server-rcon-tcp1kafkatorio-events-serverweb | foundry-foundry@docker | foundry-foundry |  
```

### What version of Traefik are you using?

2.9.1

### Traefik `docker-compose.yml`

```yaml
version: "3.9"

services:

  traefik:
    image: "traefik:v2.9.1"
    container_name: "traefik"
    restart: "unless-stopped"
    ports:
      # web, http
      - "80:80"
      # websecure, https
      - "443:443"
      # traefik web-ui
      - "8080:8080"

    environment:
      GCE_SERVICE_ACCOUNT_FILE: "/auth/.secret.dns-api-key.json"
    volumes:
      # docker
      - "/run/user/1000/docker.sock:/var/run/docker.sock:ro"
      # config
      - "./config/static:/etc/traefik/"
      - "./config/dynamic:/etc/traefik-dynamic/"
      - "./auth:/auth"
      # cert
      - "./letsencrypt:/letsencrypt"

  whoami:
    image: "traefik/whoami"
    container_name: "traefik-whoami"
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/`)"
      - "traefik.http.routers.whoami.entrypoints=web,websecure"
      - "traefik.http.routers.whoami.priority=1"

networks:
  default:
    name: traefik-nw
```

### Traefik static config

```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:

  # http
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"

  # https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: "le-cert"
        domains: 
          - main: "mywebsite.com"
            sans: 
              - "*.mywebsite.com"

  # factorio
  factorio-server-upd1:
    address: ":34197/udp"
  factorio-server-rcon-tcp1:
    address: ":27015/tcp"

  # kafkatorio
  kafkatorio-events-server:
    address: ":12081/tcp"

providers:
  file:
    directory: "/etc/traefik-dynamic/"
    watch: true
  docker:
    network: "traefik-nw"
    watch: true
    exposedByDefault: false
    allowEmptyServices: true

api:
  insecure: true
  dashboard: true
  debug: true

log:
  level: "debug"

ping: {}

certificatesResolvers:
  le-cert:
    acme:
      email: "x@mywebsite.com"
      # LE staging server - uncomment to test
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: gcloud
        delayBeforeCheck: 0
#        resolvers:
#        disablePropagationCheck: true
```

### Traefik dynamic config

```yaml
http:
  routers:
    foundry-route:
      rule: "Host(`foundry.mywebsite.com`) && PathPrefix(`/`)"
      service: "foundry-foundry@docker"
      entrypoints:
        - "websecure"
#   middlewares:
  # services:
  #   foundry-service:
  #     loadBalancer:
  #       servers:
  #         - address: "foundry:30000"
```

### If applicable, please paste the log output in DEBUG level

I get a GitHub error when pasting logs here: "There was an error creating your Issue: body is too long (maximum is 65536 characters)."

There are a lot of debug logs. I can upload the relevant parts on request.

**Comment by aSemy** [comment]
If I try creating a HTTP service, it doesn't look like Traefik recognises this. I can't see it in the web GUI.

```yaml

http:
  routers:
    foundry-route:
      rule: "Host(`foundry.mywebsite.com`) && PathPrefix(`/`)"
      service: "foundry-service"
      # service: "foundry-foundry@docker"
      entrypoints:
        - "websecure"
      priority: 101
      # middlewares:
      #   - "common-basic-auth"
#   middlewares:
  services:
    foundry-service:
      loadBalancer:
        servers:
          - url: "foundry:30000"
```

![image](https://user-images.githubusercontent.com/897017/194699723-f974c360-1183-46ec-89fa-0ea4c5390a81.png)
