### ISSUE TITLE
Non-docker service on localhost

### ISSUE THREAD

**Issue by mscrocdile** [traefik/traefik#9472]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

i expect that i will see "hello world" in browser at https://thisis.example.com the same way as i see it using
curl http://localhost:3400 on that linux vps.

### What did you see instead?

However i see Bad Gateway.

I tested also with xyz where xyz was defined in /etc/hosts. I can ping xyz from traefik container but then i get Gateway Timeout.

I found here
https://community.traefik.io/t/unable-to-reverse-proxy-to-non-docker-target/14578
that it should work but there is local ip address used instead of localhost. Problem is that i don't have any local ip. I have only public ip or localhost ip.

### What version of Traefik are you using?

2.9.1

### What is your environment & configuration?

```yaml
tomysvc:
      rule: "Host(`thisis.example.com`)"
      service: mysvc
      tls:
        certResolver: letsencrypt

mysvc:
      loadBalancer:
        servers:
          - url: "http://localhost:3400/"

```
