### ISSUE TITLE
Missing Authorization header with ForwardAuth in Traefik

### ISSUE THREAD

**Issue by basilboli** [traefik/traefik#9473]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have the following traefik setup:

`mybackend` - golang backend
`myauth` - dedicated auth backend validating jwt token

all run with traefik.

I want all requests to first pass through `myauth` backend to validate jwt token / rate limit users before reaching `mybackend`.

### What did you see instead?

When using below configuration `myauth` doesn't receive the Authorization header containing authorization jwt token.

When I don't use the `forwardauth` middleware, the Authorization header is there.

### What version of Traefik are you using?

Version:      2.9.1
Codename:     banon
Go version:   go1.19.1
Built:        2022-10-03T14:22:13Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
 mybackend:
    image: mybackend
    restart: always
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      # creates new middleware called redirect-to-https
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # creates new router called redirect-https
      - "traefik.http.routers.redirect-https.rule=Host(`api.mydomain.com`)"
      - "traefik.http.routers.redirect-https.entryPoints=http"
      # applies middleware to router
      - "traefik.http.routers.redirect-https.middlewares=redirect-to-https"
      # creates new router called api_tls
      - "traefik.http.routers.api.entryPoints=https"
      - "traefik.http.routers.api.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.api.rule=Host(`api.mydomain.com`)"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.middlewares=ratelimitme"
      - "traefik.http.middlewares.ratelimitme.forwardauth.address=http://myauth:8080"
      - "traefik.http.middlewares.ratelimitme.forwardauth.trustforwardheader=true"
      - "traefik.http.middlewares.ratelimitme.forwardauth.authresponseheaders=X-Forwarded-User"


  myauth:
    image: myauth
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rate_limiting.entrypoints=http"
        - "traefik.http.services.rate_limiting.loadbalancer.server.port=8080"
```

Add more configuration information here.
