### ISSUE TITLE
2.8.8: unknown TLS options w/ Kubernetes CRD

### ISSUE THREAD

**Issue by bitsofinfo** [traefik/traefik#9478]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Traefik 2.8.8 on k8s

namespace: `traefik-external`

relevant startup options:
```
- --providers.kubernetescrd
- --providers.kubernetescrd.ingressClass=traefik-external
- --providers.kubernetesingress
- --providers.kubernetesingress.ingressendpoint.publishedservice=traefik-external/traefik-external
- --providers.kubernetesingress.labelSelector=traefik-context=external
- --providers.kubernetesingress.ingressClass=traefik-external
- --providers.kubernetescrd.namespaces=traefik-external,my-apps 
```

tls option within this name pace:
```
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  labels:
    app.kubernetes.io/instance: traefik-external-traefik-external
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-18.0.0
    traefik-context: external
  name: external
  namespace: traefik-external
spec:
  maxVersion: VersionTLS13
  minVersion: VersionTLS12
  sniStrict: true
```

error in logs: 
```
time="2022-10-27T14:52:15Z" level=error msg="unknown TLS options: traefik-external-external@kubernetescrd" entryPointName=websecure routerName=my-apps-httpbin-test-http-bin-test101-my-net@kubernetes
```

I'm at loss as to what is going on

similar? https://github.com/traefik/traefik/issues/7408

### What did you see instead?

see above

### What version of Traefik are you using?

2.8.8

### What is your environment & configuration?

see above
