### ISSUE TITLE
Traefik 2.9.4 has incorrect values in OriginStatus and DownstreamStatus fields in the access log

### ISSUE THREAD

**Issue by jim-barber-he** [traefik/traefik#9487]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I deployed Traefik version `2.9.4` into our cluster using version `18.2.0` of the Helm chart.
If I redeploy the Helm chart and set `image.tag: 2.9.1` to go to the previous point release of Traefik, then the problem stops happening.

### What did you see instead?

After deploying version `2.9.4` I have a heap of requests with the access logs showing `OriginStatus = 0` but with `DownstreamStatus = 200`.
This is happening across to board to our various services, and also happens to Traefik's own `/ping` endpoint that is used for liveness and readiness probes.

If I redeploy the Helm chart and set `image.tag: 2.9.1` to go to the previous point release of Traefik, then this problem stops happening and `OriginStatus == DownstreamStatus` in all our logs.

Here is a sample log from one of the `/ping` requests that shows the problem.
```
{"ClientAddr":"10.9.129.184:47134","ClientHost":"10.9.129.184","ClientPort":"47134","ClientUsername":"-","DownstreamContentSize":2,"DownstreamStatus":200,"Duration":80879,"GzipRatio":0,"OriginContentSize":0,"OriginDuration":39838,"OriginStatus":0,"Overhead":41041,"RequestAddr":"10.9.129.184:9000","RequestContentSize":0,"RequestCount":381161,"RequestHost":"10.9.129.184","RequestMethod":"GET","RequestPath":"/ping","RequestPort":"9000","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"ping@internal","StartLocal":"2022-11-02T00:22:41.640464109Z","StartUTC":"2022-11-02T00:22:41.640464109Z","entryPointName":"traefik","level":"info","msg":"","request_User-Agent":"kube-probe/1.23","request_X-Forwarded-Port":"9000","request_X-Forwarded-Proto":"http","time":"2022-11-02T00:22:41Z"}
```

### What version of Traefik are you using?

2.9.4

### What is your environment & configuration?

These are the values we provide to our Helm chart

```yaml
additionalArguments:
  - "--entrypoints.websecure.forwardedheaders.trustedips=127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,100.64.0.0/10"
  - "--entrypoints.websecure.transport.lifecycle.gracetimeout=180"
  - "--entrypoints.websecure.transport.lifecycle.requestacceptgracetimeout=240"
  - "--providers.kubernetesingress.allowexternalnameservices=true"
  - "--serversTransport.forwardingTimeouts.idleConnTimeout=360s"
  - "--serversTransport.insecureSkipVerify=true"

deployment:
  dnsPolicy: ClusterFirstWithHostNet
  kind: DaemonSet
  terminationGracePeriodSeconds: 360

# Don't check for new version, nor send anonymous usage.
globalArguments: []

hostNetwork: true

ingressRoute:
  dashboard:
    enabled: false

logs:
  access:
    enabled: true
    fields:
      headers:
        defaultMode: drop
        names:
          Content-Type: keep
          Referer: keep
          Sec-Fetch-Dest: keep
          Sec-Fetch-Site: keep
          User-Agent: keep
          X-Amzn-Trace-Id: keep
          X-Forwarded-For: keep
          X-Forwarded-Port: keep
          X-Forwarded-Proto: keep
    format: json
  general:
    format: json

metrics:
  prometheus:
    addRoutersLabels: true

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1

ports:
  metrics:
    port: 9200
  web:
    port: 80
    redirectTo: websecure
  websecure:
    port: 443
    tls:
      enabled: true

providers:
  kubernetesCRD:
    allowExternalNameServices: true

resources:
  limits:
    memory: 2500Mi
  requests:
    cpu: 650m
    memory: 1250Mi

rollingUpdate:
  maxSurge: 0
  maxUnavailable: 1

securityContext:
  capabilities:
    add:
      - NET_BIND_SERVICE
  runAsNonRoot: false
  runAsUser: 0

service:
  enabled: false

tlsOptions:
  default:
    minVersion: VersionTLS12

tolerations:
  - key: dedicated
    operator: Equal
    value: ingress-controller
    effect: NoSchedule
```

Add more configuration information here.
