### ISSUE TITLE
RedirectScheme http to https is not working with Traefik Dashboard

### ISSUE THREAD

**Issue by nighttiger1990** [traefik/traefik#9496]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I tried to configure for Dashboard support HTTPS. I want to redirect from HTTP to HTTPS but not work with below config.

- When I type in Browser `https://traefik.mydomain.tk`, browser redirect to `https://traefik.mydomain.tk/dashboard/#/`
- When I type in Browser `http://traefik.mydomain.tk`,  browser show `This page isn’t working right now traefik.mydomain.tk didn’t send any data.
ERR_EMPTY_RESPONSE`
I expected when using `http`, the browser will redirect to `https` and show TraefikDashboard

### What did you see instead?

Access HTTPS doesn't redirect to HTTPS

### What version of Traefik are you using?

v2.9.4

### What is your environment & configuration?

```yaml
version: '3.9'

services:
  traefik-balancer:
    image: traefik:v2.9.4
    container_name: traefik-balancer
    command:
      - --log.level=DEBUG
      - --api.dashboard=true
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # Enable below for using Letsencrypt SSL/ Enable in volumes with LetsEncrypt too
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      #- --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory #using Staging Server LetsEnscrypt
      - --certificatesresolvers.myresolver.acme.email=myemail@mycompany.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      # End of section
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.mydomain.tk`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.entrypoints=web
      # Enable redirect from http to https when access Dashboard
      - traefik.http.routers.dashboard.middlewares=toHttps
      - traefik.http.middlewares.toHttps.redirectScheme.scheme=https
      # End of section
      # Enable below for using Secure Mode Dashboard
      - traefik.http.routers.dashboard-secure.rule=Host(`traefik.mydomain.tk`)
      - traefik.http.routers.dashboard-secure.service=api@internal
      - traefik.http.routers.dashboard-secure.entrypoints=websecure
      # Enable redirect from http to https when access Dashboard
      - traefik.http.routers.dashboard-secure.tls=true
      - traefik.http.routers.dashboard-secure.tls.certresolver=myresolver
      # End section
      # Uncomment below line for add Basic Authentication when access Dashboard
      #- traefik.http.routers.dashboard.middlewares=auth
      #- traefik.http.middlewares.auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/,test2:$$apr1$$d9hr9HBB$$4HxwgUir3HP4EsggP/QNo
      # End of section
    ports:
      - 80:80
      - 443:443
      #- 8080:8080 # --api.insecure=true Dashboard will expose at 8080 in container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Enable below for using Letsencrypt SSL
      - /home/ubuntu/letsencrypt:/letsencrypt
```
