### ISSUE TITLE
Custom plugin not working

### ISSUE THREAD

**Issue by scrazy77** [traefik/traefik#9512]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I tested custom plugin in EKS  traefik deployment,  but it's not working.
helm chart config:

```
additionalArguments: 
  - "--log.level=DEBUG"
  - "--experimental.plugins.example.modulename=github.com/traefik/plugindemo"
  - "--experimental.plugins.example.version=v0.2.2"
```

the pod error message:

```
time="2022-11-08T15:42:07Z" level=debug msg="loading of plugin: example: github.com/traefik/plugindemo@v0.2.2"
time="2022-11-08T15:42:12Z" level=error msg="Plugins are disabled because an error has occurred." error="failed to download plugin github.com/traefik/plugindemo: failed to call service: Get \"https://plugins.traefik.io/public/download/github.com/traefik/plugindemo/v0.2.2\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

the network is ok, I can wget https://plugins.traefik.io/public/download/github.com/traefik/plugindemo/v0.2.2 in the pod

Then I test different version of traefik docker image:

Custom plugin working fine:
v2.7.0
v2.8.0
v2.8.1
v2.8.3

Custom plugin not working:
v2.8.4
v2.8.8
v2.9.4

Conclusion:
The latest working version is Traefik v2.8.3

### What did you see instead?

time="2022-11-08T15:42:07Z" level=debug msg="loading of plugin: example: github.com/traefik/plugindemo@v0.2.2"
time="2022-11-08T15:42:12Z" level=error msg="Plugins are disabled because an error has occurred." error="failed to download plugin github.com/traefik/plugindemo: failed to call service: Get \"https://plugins.traefik.io/public/download/github.com/traefik/plugindemo/v0.2.2\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

### What version of Traefik are you using?

v2.9.4

### What is your environment & configuration?

```yaml
additionalArguments: 
  - "--log.level=DEBUG"
  - "--experimental.plugins.example.modulename=github.com/traefik/plugindemo"
  - "--experimental.plugins.example.version=v0.2.2"
```

### If applicable, please paste the log output in DEBUG level

time="2022-11-08T15:42:07Z" level=debug msg="loading of plugin: example: github.com/traefik/plugindemo@v0.2.2"
time="2022-11-08T15:42:12Z" level=error msg="Plugins are disabled because an error has occurred." error="failed to download plugin github.com/traefik/plugindemo: failed to call service: Get \"https://plugins.traefik.io/public/download/github.com/traefik/plugindemo/v0.2.2\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

**Comment by rtribotte** [comment]
Hello @scrazy77,

Thanks for your interest in Traefik!

To debug this further, can you share with us the version of the HelmChart you are using?
Can you also share the command and the values.yaml file?

**Comment by scrazy77** [comment]
Chart.yaml

```
apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 18.3.0
appVersion: 2.9.4
keywords:
  - traefik
  - ingress
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: emilevauge
    email: emile@vauge.com
  - name: dtomcej
    email: daniel.tomcej@gmail.com
  - name: ldez
    email: ldez@traefik.io
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: charlie-haley
    email: charlie.haley@traefik.io
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - ⬆️  Update Traefik appVersion to 2.9.4

```

values.yaml

```
# Default values for Traefik
image:
  name: traefik
  # defaults to appVersion
  tag: v2.9.4
  pullPolicy: IfNotPresent
hub:
  enabled: false
deployment:
  enabled: true
  kind: Deployment
  replicas: 2
  terminationGracePeriodSeconds: 60
  minReadySeconds: 0
  annotations: {}
  labels: {}
  podAnnotations: {}
  podLabels: {}
  additionalContainers: []
  additionalVolumes: []
  initContainers: []
  shareProcessNamespace: false
  imagePullSecrets: []
  lifecycle: {}
podDisruptionBudget:
  enabled: false
ingressClass:
  enabled: false
  isDefaultClass: false
experimental:
  plugins:
    enabled: true 
    plugin-requestid:
      modulename: github.com/pipe01/plugin-requestid
      version: v1.0.0
    traefikxrequeststart:
      modulename: github.com/EasySolutionsIO/traefikxrequeststart
      version: v0.0.3    
  kubernetesGateway:
    enabled: false
    gateway:
      enabled: true
ingressRoute:
  dashboard:
    enabled: true
    annotations: {}
    labels: {}
    entryPoints: ["traefik"]

rollingUpdate:
  maxUnavailable: 0
  maxSurge: 1
readinessProbe:
  failureThreshold: 1
  initialDelaySeconds: 2
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 2
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: false
    allowExternalNameServices: true
    allowEmptyServices: false
    namespaces:
      - "default"
      - "traefik"

  kubernetesIngress:
    enabled: true
    allowExternalNameServices: false
    allowEmptyServices: false
    namespaces: 
      - "default"
      - "traefik"    
    publishedService:
      enabled: false
volumes: []
additionalVolumeMounts: []
logs:
  general:
    level: ERROR
  access:
    enabled: true
    filters: {}
    fields:
      general:
        defaultmode: keep
        names: {}
      headers:
        defaultmode: drop
        names: {}
metrics:
  prometheus:
    entryPoint: metrics
tracing: {}
globalArguments:
  - "--global.checknewversion"
additionalArguments: 
  - "--log.level=DEBUG"
  - "--experimental.plugins.plugin-requestid.modulename=github.com/pipe01/plugin-requestid"
  - "--experimental.plugins.plugin-requestid.version=v1.0.0"
  - "--experimental.plugins.traefikxrequeststart.modulename=github.com/EasySolutionsIO/traefikxrequeststart"
  - "--experimental.plugins.traefikxrequeststart.version=v0.0.3"
env: []
envFrom: []
ports:
  traefik:
    port: 9000
    expose: false
    exposedPort: 9000
    protocol: TCP
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP
    http3:
      enabled: false
    tls:
      enabled: true
      options: ""
      certResolver: ""
      domains: []
    middlewares: []
  metrics:
    port: 9100
    expose: false
    exposedPort: 9100
    protocol: TCP
tlsOptions: {}
tlsStore: {}
service:
  enabled: true
  single: true
  type: LoadBalancer
  annotationsTCP: {}
  annotationsUDP: {}
  labels: {}
  spec: {}
  loadBalancerSourceRanges: []
  externalIPs: []
autoscaling:
  enabled: false
persistence:
  enabled: false
  name: data
  accessMode: ReadWriteOnce
  size: 128Mi
  path: /data
  annotations: {}
certResolvers: {}
hostNetwork: false
rbac:
  enabled: true
  namespaced: false
podSecurityPolicy:
  enabled: false
serviceAccount:
  name: ""
serviceAccountAnnotations: {}
resources: {}
nodeSelector: {}
tolerations: []
topologySpreadConstraints: []
securityContext:
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

podSecurityContext:
  fsGroup: 65532
extraObjects: []

```
