### ISSUE TITLE
passTLSClientCert Middleware doesn't pass client cert serial number in the info header

### ISSUE THREAD

**Issue by yoeluk** [traefik/traefik#9518]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

traefik is configured to pass the X-Forwarded-Tls-Client-Cert-Info to the service with the following middleware config

```yaml
  apiVersion: traefik.containo.us/v1alpha1
  kind: Middleware
  metadata:
    name: myhost-passtls-info
    namespace: ${kubernetes_namespace.notary.metadata.0.name}
  spec:
    passTLSClientCert:
      info:
        notAfter: true
        notBefore: true
        sans: true
        subject:
          country: false
          province: false
          locality: false
          organization: false
          commonName: true
          serialNumber: true
          domainComponent: false
        issuer:
          country: false
          province: false
          locality: false
          organization: false
          commonName: true
          serialNumber: true
          domainComponent: false
```

however, the service gets this which is missing the serial number

```
Issuer="CN=<the cn>";NB="1669009953";NA="1676785953";SAN="<the san>",Subject="CN=<the cn>";Issuer="CN=<the cn>";NB="1668884348";NA="1984244348"
```

traefik dashboard shows the expected configuration of the middleware to be correct

![image](https://user-images.githubusercontent.com/2067872/203020532-50bc35d0-70de-4b35-be3d-571add8ee4ec.png)

### What did you see instead?

No solution to this

### What version of Traefik are you using?

2.9.4

### What is your environment & configuration?

```yaml
  apiVersion: traefik.containo.us/v1alpha1
  kind: IngressRoute
  metadata:
    name: notary-m
    namespace: ${kubernetes_namespace.notary.metadata.0.name}
  spec:
    entryPoints:
      - websecure
    routes:
      - match: Host(`myhost.${var.cluster_domain}`)
        kind: Rule
        middlewares:
          - name: myhost-passtls-info
        services:
          - name: notary
            port: 8080
    tls:
      certResolver: le
      options:
        name: notary-mtls-opts
```

Add more configuration information here.
