### ISSUE TITLE
Support FastCGI as a servers transport

### ISSUE THREAD

**Issue by ddtmachado** [traefik/traefik#9521]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

FastCGI is a popular binary protocol for script-to-server communication. The ability to configure FastCGI as a valid server transport would simplify workflows for users who are currently forced to introduce another internal proxy just for FastCGI-to-HTTP conversion.

The goal of this proposal is to add support for the FastCGI protocol between the proxy and a backend php fpm application.

![Flowchart Template (2)](https://user-images.githubusercontent.com/37125990/203125328-2fd1d05f-3990-4c63-824d-570b1bb80a58.jpg)

Traefik can not serve static resources, thus you’ll still need to set up a web server behind it to host your files, this can be viewed as a limitation to some that would expect to replace their existing stack, as there are web servers that sometimes act as a reverse proxy as well, most notably Nginx and Caddy.

The main benefit of FastCGI is an ability to maintain a persistent tcp/socket connection between a webserver and an application, multiplexing incoming HTTP requests through it. In a context of a load balancer service, this means maintaining a pool of connected services.

**Configuration Schema**

Within Traefik's architecture, FastCGI should be viewed as a type of server transport configuration, this way it can be referenced from the service load balancer configuration.

```yaml
#For FastCGI endpoints, tcp:// and unix:// uri schemas would be supported, for both TCP and Socket connections.
http:
  services:
    app:
      loadBalancer:
        servers:
        - url: "tcp://wordpress:9000/"
        serversTransport: fastcgiApp
 ```

**Transport configuration**

A typical server transport configuration for a FastCGI connection will require the configuration of an index file.
By default, Traefik sends FastCGI environment variables [compatible with PHP-fpm](https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/), but it is possible to override those through env parameters. For maximum configuration flexibility, env allows any environment variable names (as opposed to a predefined set of supported values).

```yaml
http:
  serversTransports:
    fastcgiApp:
      fastCGI:
        index: index.php
        env:
            HTTP_PROXY: ""
            MY_CUSTOM_VAR: "value"
```

If fastCGI is defined, HTTP-specific serversTransports parameters are ignored with a warning. For example:

```yaml
http:
  serversTransports:
    app:
      fastCGI:
        index: index.php
      insecureSkipVerify: true
```

The configuration above should result in a warning log message, like 

```bash
Warning: htpp.serversTransports.app.insecureSkipVerify is not compatible with http.serversTransports.app.fastCGI and will be ignored.
```

Full config example:
```yaml
http:

  routers:
    root:
      rule: "PathPrefix(`/`)"
      service: app

  serversTransports:
    fastcgiApp:
      fastCGI:
        index: index.php

  services:
    app:
      loadBalancer:
        servers:
        - url: "tcp://wordpress:9000/"
        serversTransport: fastcgiApp
```

**Implementation concerns**

Unfortunately, no well-maintained Fast-CGI library exists currently for Go. The most promising one is https://github.com/yookoala/gofast.

**References**

[Previous discussions](https://github.com/traefik/traefik/issues/753)
[Hackathon proof-of-concept](https://github.com/traefik/traefik/pull/9382)
[FastCGI specification](https://fast-cgi.github.io/spec)
[Nginx FastCGI](https://www.nginx.com/resources/wiki/start/topics/examples/fastcgiexample/)
