### ISSUE TITLE
cloudflare: failed to create TXT record: Authentication error (10000)

### ISSUE THREAD

**Issue by Visne** [traefik/traefik#9522]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I launched Traefik as follows:

```bash
podman create --name traefik \
	--restart always \
	--network slirp4netns:port_handler=slirp4netns \
	--replace \
	--publish 8080:8080 \
	--publish 8443:8443 \
	--volume /home/traefik/containers/traefik/traefik.yml:/etc/traefik/traefik.yml:Z \
	--volume /home/traefik/containers/traefik/conf/:/root/conf/:Z \
	--secret cloudflare-zone-read \
	--env CF_ZONE_API_TOKEN_FILE=/run/secrets/cloudflare-zone-read \
	--secret cloudflare-vegoon-party-dns-edit \
	--env CF_DNS_API_TOKEN=/run/secrets/cloudflare-vegoon-party-dns-edit \
	--volume /home/traefik/containers/traefik/acme.json:/root/acme.json:Z 'docker.io/library/traefik:v2.9.5'
```

Apologies for the long command, but I want to be as complete as possible.
This gives the following output:

```
time="2022-11-22T00:16:02Z" level=debug msg="Looking for provided certificate(s) to validate [\"vegoon.party\"]..." providerName=letsencryptDns.acme ACME CA="https://acme-staging-v02.api.letsencrypt.org/directory"
time="2022-11-22T00:16:02Z" level=debug msg="Domains [\"vegoon.party\"] need ACME certificates generation for domains \"vegoon.party\"." providerName=letsencryptDns.acme ACME CA="https://acme-staging-v02.api.letsencrypt.org/directory"
time="2022-11-22T00:16:02Z" level=debug msg="Loading ACME certificates [vegoon.party]..." ACME CA="https://acme-staging-v02.api.letsencrypt.org/directory" providerName=letsencryptDns.acme
time="2022-11-22T00:16:02Z" level=debug msg="Building ACME client..." providerName=letsencryptDns.acme
time="2022-11-22T00:16:02Z" level=debug msg="https://acme-staging-v02.api.letsencrypt.org/directory" providerName=letsencryptDns.acme
time="2022-11-22T00:16:03Z" level=debug msg="Using DNS Challenge provider: cloudflare" providerName=letsencryptDns.acme
time="2022-11-22T00:16:03Z" level=debug msg="legolog: [INFO] [vegoon.party] acme: Obtaining bundled SAN certificate"
time="2022-11-22T00:16:03Z" level=debug msg="legolog: [INFO] [vegoon.party] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/4399196724"
time="2022-11-22T00:16:03Z" level=debug msg="legolog: [INFO] [vegoon.party] acme: Could not find solver for: tls-alpn-01"
time="2022-11-22T00:16:03Z" level=debug msg="legolog: [INFO] [vegoon.party] acme: Could not find solver for: http-01"
time="2022-11-22T00:16:03Z" level=debug msg="legolog: [INFO] [vegoon.party] acme: use dns-01 solver"
time="2022-11-22T00:16:03Z" level=debug msg="legolog: [INFO] [vegoon.party] acme: Preparing to solve DNS-01"
time="2022-11-22T00:16:05Z" level=debug msg="legolog: [INFO] [vegoon.party] acme: Cleaning DNS-01 challenge"
time="2022-11-22T00:16:05Z" level=debug msg="legolog: [WARN] [vegoon.party] acme: cleaning up failed: cloudflare: unknown record ID for '_acme-challenge.vegoon.party.' "
time="2022-11-22T00:16:05Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/4399196724"
time="2022-11-22T00:16:06Z" level=error msg="Unable to obtain ACME certificate for domains \"vegoon.party\"" error="unable to generate a certificate for the domains [vegoon.party]: error: one or more domains had a problem:\n[vegoon.party] [vegoon.party] acme: error presenting token: cloudflare: failed to create TXT record: Authentication error (10000)\n" rule="PathPrefix(`/dashboard`)" providerName=letsencryptDns.acme ACME CA="https://acme-staging-v02.api.letsencrypt.org/directory" routerName=https-dashboard@file
```

But weirdly enough, if I go inside the container and copy-paste the output of `cat /run/secrets/cloudflare-vegoon-party-dns-edit` and `cat /run/secrets/cloudflare-zone-read`, and then use these for the following command:

```bash
podman run -it --env CLOUDFLARE_DNS_API_TOKEN=<contents of cloudflare-vegoon-party-dns-edit> \
                            --env CLOUDFLARE_ZONE_API_TOKEN=<contents of cloudflare-zone-read> \
                            docker.io/goacme/lego \
							--email <my email> \
                            --dns cloudflare \
                            --domains vegoon.party run
```

I get the following output:

```
[...]
2022/11/22 00:48:10 [INFO] [vegoon.party] acme: Waiting for DNS record propagation.
2022/11/22 00:48:18 [INFO] [vegoon.party] The server validated our request
2022/11/22 00:48:18 [INFO] [vegoon.party] acme: Cleaning DNS-01 challenge
2022/11/22 00:48:20 [INFO] [vegoon.party] acme: Validations succeeded; requesting certificates
2022/11/22 00:48:21 [INFO] [vegoon.party] Server responded with a certificate.
```

Thus, the API tokens are definitely correct, yet when Traefik tries to use them I get `cloudflare: failed to create TXT record: Authentication error (10000)`.

### What did you see instead?

-

### What version of Traefik are you using?

v2.9.5

### What is your environment & configuration?

`traefik.yml`
```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  http:
    address: :8080
    http:
      redirections:
        entryPoint:
          to: https

  https:
    address: :8443
    http:
      tls:
        options: modern
        certResolver: letsencryptDns
        domains:
          - main: my.domain
      middlewares:
        - auth

log:
  level: DEBUG

api:
  dashboard: true

certificatesResolvers:
  letsencryptDns:
    acme:
      email: <my email>
      storage: /root/acme.json
      dnsChallenge:
        provider: cloudflare
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory  # Staging environment

providers:
  file:
    directory: /root/conf  # Path inside container
    watch: true
```

Inside `/home/traefik/containers/traefik/conf/` I have:

`modern.yml`
```yaml
tls:
  options:
    modern:
      minVersion: VersionTLS13
```

`auth.yml`
```yaml
http:
  middlewares:
    auth:
      basicAuth:
        users:
          - "<username>:<password hash>"
```

`dashboard.yml`
```yaml
http:
  routers:
    dashboard:
      rule: PathPrefix(`/dashboard`)
      service: api@internal
```
