### ISSUE TITLE
Datadog Synthetic Traces not working

### ISSUE THREAD

**Issue by dsenske** [traefik/traefik#9525]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We are using Datadog and their Synthetic Tests, but the connected Traces are empty.

There is a bug in your used Datadog Tracing Package, they have fixed it in the latest version.

Please take a look here: https://github.com/DataDog/dd-trace-go/issues/1270

and update the package: https://github.com/traefik/traefik/blob/master/go.mod#L85

### What did you see instead?

Empty Traces because of mismatching the Datadog Trace IDs

### What version of Traefik are you using?

2.9.4

### What is your environment & configuration?

```yaml
     TRAEFIK_TRACING: "true"
      TRAEFIK_TRACING_DATADOG: "True"
      TRAEFIK_TRACING_DATADOG_PRIORITYSAMPLING: "True"
      TRAEFIK_TRACING_DATADOG_PARENTIDHEADERNAME: "x-datadog-parent-id"
      TRAEFIK_TRACING_DATADOG_SAMPLINGPRIORITYHEADERNAME: "x-datadog-sampling-priority"
      TRAEFIK_TRACING_DATADOG_TRACEIDHEADERNAME: "x-datadog-trace-id"
```
