### ISSUE TITLE
customRequestHeaders not work 

### ISSUE THREAD

**Issue by tm2018** [traefik/traefik#9538]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

i have a yaml in my kubernetes which use traefik, it include customRequestHeaders and customResponseHeaders, i can find the customResponseHeaders but customRequestHeaders not show in my requests. please help me.

### What did you see instead?

Accept-Ranges: bytes
Connection: keep-alive
Content-Length: 612
Content-Type: text/html
Date: Thu, 24 Nov 2022 09:42:23 GMT
Etag: "5fd8c14a-264"
Last-Modified: Tue, 15 Dec 2020 13:59:38 GMT
Server: elb
X-Custom-Response-Header: value

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: zh,zh-TW;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6
Cache-Control: no-cache
Connection: keep-alive
Cookie: xxx
Host: web3.example.com
Pragma: no-cache
sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

### What version of Traefik are you using?

2.8.5

### What is your environment & configuration?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-header
spec:
  headers:
    customRequestHeaders:
      X-Script-Name: "test"
    customResponseHeaders:
      X-Custom-Response-Header: "value"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: test-header
spec:
  entryPoints:
    - websecure
  routes:
  - match: 'Host(`web3.example.com`)'
    kind: Rule
    services:
    - name: nginx
      port: 80
    middlewares:
    - name: test-header
  tls:
    secretName: ssl-example.com
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

--
