### ISSUE TITLE
Got unexpected certificate error when using TCP router

### ISSUE THREAD

**Issue by xzycn** [traefik/traefik#9543]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

executing a command:
**kubectl get pod**

here is a part of my kubeconfig:
```yaml
server: https://xxxx.net:10000
```

### What did you see instead?

Unable to connect to the server: x509: certificate is valid for 165877b9dd04f
1a638db01f2b93067b5.6028de27899f9ff3a62d618482f8cbea.traefik.default, not xxxx.net

### What version of Traefik are you using?

Version:      2.9.5
Codename:     banon
Go version:   go1.19.3
Built:        2022-11-17T15:04:26Z
OS/Arch:      linux/amd64

### What is your environment & configuration?
static:
```yaml
ping: ""
checknewversion: false
serversTransport:
  insecureSkipVerify: true
api:
  insecure: true
  dashboard: false
  debug: false
entryPoints:
    port10000: {address: ":10000"}
providers:
  file:
    filename: dynamic.yaml
log:
  filePath: ""
  level: debug
  format: json
```
dynamic:
```yaml
tcp:     
  routers:
    k3s: 
      entryPoints:
        - port10000
      rule: "HostSNI(`*`)"
      service: "service-k3s"
  services:
  - service-k3s:
     loadBalancer: 
       servers:
         - address: "192.168.0.153:6443"
```

### If applicable, please paste the log output in DEBUG level

```bash
Nov 25 13:22:15 test traefik[10641]: {"level":"debug","msg":"Serving default certificate for request: \"xxxx.net\"","time":"2022-11-25T13:22:15+08:00"}
Nov 25 13:22:15 test traefik[10641]: {"level":"debug","msg":"http: TLS handshake error from x.x.x.x:1390: remote error: tls: bad certificate","time":"2022-11-25T13:22:15+08:00"}
```

my question:
I don't set TLS section, why clould I get a certificate error？
