### ISSUE TITLE
Traefik returns 404 when service with 0 pods and service with ExternalName are combined

### ISSUE THREAD

**Issue by ErikLundJensen** [traefik/traefik#9547]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Loadbalancing is applied as expected when having an IngressRoute with references to a regular service with selector and a service with ExternalName.

IngressRoute with two services is show below. The weight is set very high for the regular service and thereby most request will stay within cluster unless no pods matches the regular service.

```yaml
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: hello-world-with-failover
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`hello-world.apps.foo.bar`)
      services:
        - kind: Service
          name: regular-service
          namespace: demo
          port: 80
          weight: 10000000
        - kind: Service
          name: externalname-service
          namespace: demo
          port: 443
          scheme: https
          weight: 1
  tls:
    secretName: hello-world-tls
```

### What did you see instead?

When the regular service does not match any pods (e.g. scaled to 0) then I expected all requests to be handled by the ExternalName service.
Instead Traefik returns 404 Not Found in that case.

It could be related to the change in [pull-request 8057](https://github.com/traefik/traefik/pull/8057).

### What version of Traefik are you using?

Version: 2.9.4
Kubernetes: 1.23
Traefik Helm Chart: 20.2.0

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

Enabled TRACE log level.

When we remove the regular-service and only have an ExternalName Service then the server is added. Here is the log from that scenario:
```
{"entryPointName":"websecure","level":"debug","middlewareName":"metrics-service","middlewareType":"Metrics","msg":"Creating middleware","routerName":"verification-hello-world-with-failover-1234@kubernetescrd","serviceName":"verification-hello-world-with-failover-1234","time":"2022-11-28T09:13:11Z"}
{"entryPointName":"websecure","level":"debug","msg":"Creating load-balancer","routerName":"verification-hello-world-with-failover-1234@kubernetescrd","serviceName":"verification-hello-world-with-failover-1234","time":"2022-11-28T09:13:11Z"}
{"entryPointName":"websecure","level":"debug","msg":"Creating server 0 https://hello-world.site2.foo.bar.dk:443","routerName":"verification-hello-world-with-failover-1234@kubernetescrd","serverName":0,"serviceName":"verification-hello-world-with-failover-1234","time":"2022-11-28T09:13:11Z"}
{"level":"debug","msg":"child https://hello-world.site2.foo.bar.dk:443 now UP","time":"2022-11-28T09:13:11Z"}
{"level":"debug","msg":"Propagating new UP status","time":"2022-11-28T09:13:11Z"}
```
And the route is added:
```
{"entryPointName":"websecure","level":"debug","msg":"Adding route for hello-world.apps.foo.bar with TLS options default","time":"2022-11-28T09:13:11Z"}
```

However, then the regular-service and the ExternalName service are added the non of these kinds of log statements are shown.
