### ISSUE TITLE
Traefik 2.9.5 picks unattached network to talk to service

### ISSUE THREAD

**Issue by mkarg** [traefik/traefik#9551]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Using docker-compose I have set up a composition of several services and networks. Traefik is only connected to one of these networks, while the containers are using several networks. What I expect is that Traefik inspects each container to learn which networks they have, and chose that network to talk to the container that Traefik itself is attached to.

### What did you see instead?

Most of the time this works correct, but adding another container with two networks makes Traefik suddenly select the IP address of that container from the WRONG network (the one that Traefik is NOT attached to). Removing that container again fixes this. Another fix is to force the correct network using `traefik.docker.network` label.

### What version of Traefik are you using?

2.9.5

### What is your environment & configuration?

```yaml
## traefik.yaml
# Docker configuration backend
providers:
  docker:
    exposedbydefault: false
#    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
# API and dashboard configuration
api:
  insecure: true
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver
        domains:
          - main: ...
            sans: ...
  msa:
    address: ":587"
  matrix:
    address: ":8448"
    http:
      tls:
        certResolver: myresolver
        domains:
          - main: ...
  slack-bridge:
    address: ":9898"
    http:
      tls:
        certResolver: myresolver
        domains:
          - main: ...
certificatesResolvers:
  myresolver:
    acme:
#      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: ...
      storage: /etc/traefik-acme/acme.json
      httpChallenge:
        entryPoint: web
```
