### ISSUE TITLE
It would be great if Traefik supported wasm plugins

### ISSUE THREAD

**Issue by jicvi** [traefik/traefik#9552]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Envoy WASM plugins：
https://github.com/envoyproxy/envoy/tree/master/examples/wasm-cc

**Comment by tfny** [comment]
Hiya! Thanks for your suggestion.  We are interested in this issue but are unsure about the use case and the traction it will receive, so we are going to leave the status as "needs triage" to give the community time to let us know that they would like this.  

We will reevaluate as people respond.  

If you or another community member would like to build it before that happens, let us know and we will work with you to make sure you have all the information needed.  

Let us know here before you start. We prefer to work with our community members at the beginning of the design process to ensure that we are aligned and can move quickly with the review and merge process.

**Comment by dbit-xia** [comment]
If possible, it is best to refer to the interface of the [wasm-nginx-module](https://github.com/api7/wasm-nginx-module) project

**Comment by acouvreur** [comment]
I'd be really interested about this feature too. Right now creating plugins for multiple reverse proxies is a pain because of all the different API each reverse proxy propose.

[WasmProxy](https://github.com/proxy-wasm/spec) seems to be a very well fit usage.

**Comment by jcchavezs** [comment]
I am glad this issue already exists on this repository. I have been working with Wasm, proxy-wasm and proxies' features for a long time and I really like to see a way to extend traefik through Wasm soon.

There are a few reasons why Wasm is a good match for this use case, the first one is the fact that currently using yaegi is the only way to extend Traefik with custom functionality, however it comes with some limitations:
1. it needs to catch up with Go language syntax on every release
2. is limited to Go
3. Panics
4. Libraries incompatibility
5. Lack of profiling tooling

As opposed Wasm present several advantages on these matters:
1. Polyglot
2. Sandboxed (hence no panics)
3. More mature compatibility matrix for different libraries
4. Profiling tooling
5. More mature ecosystem, broader community

that said, we have three alternatives to pursue this goal:
1. proxy-wasm: dead standard used in envoy, focused on envoy and with unexisting community. Still there are some cool projects built on top of it, although since the standard is mainly based in Envoy, some of the features won't be portable. (Spoiler alert, I worked a lot with proxy-wasm)
2. http-wasm: new alternative with a host available in Go that bring several improvements from the main issues with proxy-wasm (less envoy focused request/response lifecycle, works as middleware and proxy feature, more performant, etc).
3. custom ABI: this is an alternative but very laborous to implement as it would require us to write an own host, define an ABI and write a TCK for host and guests SDK. While this is possible I would rather not reinvent the wheel.

I am happy to contribute with a PR supporting http-wasm. Any thoughts on this?

**Comment by emilevauge** [comment]
Thanks for your feedback @jcchavezs, very much appreciated.
[http-wasm](https://http-wasm.io/) looks promising, but young, and from the author, not production ready:

> The current maturity phase is early draft

But it would make things a lot easier to integrate.
@jcchavezs how far have you been experimenting with http-wasm?
Any other known alternative?

**Comment by juliens** [comment]
Some time ago, I attempted to integrate Proxy-WASM, and my experience left me somewhat dissatisfied. Regrettably, I couldn't achieve the seamless functionality of a proper Envoy plugin. It seemed like a substantial amount of effort would be necessary to address the missing components.

While I haven't explored HTTP-WASM, it appears to be a more attractive alternative. It seems relatively straightforward to integrate with Traefik. 
If someone has already developed a plugin for Envoy, such as CorazaWaf, they might need to create another plugin, but I'm not sure it's a real problem.

With the Yaegi plugin mechanism, you gain extensive access to the underlying Go objects, including the complete ResponseWriter. 
In theory, you could even hijack the connection, among other possibilities.
I'm curious if the HTTP-WASM "interface" will provide the required functionality for various middleware plugins. What kinds of middleware can be implemented with it? Perhaps we should consider implementing real middleware, similar to some of the existing Yaegi plugins, or even adapting the CorazaWaf middleware.

**Comment by mmatur** [comment]
Hello,

I recently conducted some tests using `proxy-wasm`, but unfortunately, I encountered challenges in getting it to work effectively. I share the sentiment with you, @jcchavezs, that proxy-wasm is mainly based on Envoy. I'm not sure we will be able to have current Envoy Wasm filters working with Traefik. It 

On a more positive note, I found `http-wasm` to be a much simpler and more straightforward option, particularly when it comes to integration with Traefik. In fact, I even worked on a small project to explore its capabilities, which you can find [here](https://github.com/mmatur/http-wasm-traefik).

I'm in agreement with @juliens about implementing a real middleware with `http-wasm`. While it may not cover all the use cases that Yaegi currently handles, I view it as a promising initial step. Moreover, it can seamlessly coexist with plugin middleware.

**Comment by zetaab** [comment]
@mmatur nice work! the actual change does not look even big! of course that is missing configurable parameters and kubernetes part etc. Anyway looks promising

**Comment by jcchavezs** [comment]
Really nice work @mmatur. I wonder if we could start a PR on this repo attempting to add http-wasm for traefik. There are a few things I want to discuss on this, for starting I would also suggest we look at existing impl. in dapr which also supports http-wasm (see https://github.com/dapr/docs/blob/v1.11/daprdocs/content/en/reference/components-reference/supported-middleware/middleware-wasm.md).

Some of the questions are:
- Do we support only local wasm files or also remote
- How do we pass config to the middlewares

**Comment by juliens** [comment]
@jcchavezs I'm curious if attempting to incorporate it into the existing plugin system might provide a solution. We've already established a mechanism for handling configuration, and for addressing the remote or local issue, this could potentially be a viable option. Although I'm uncertain about how straightforward it would be to integrate it into the current catalog system. Perhaps @ldez could share their perspective on this matter.

**Comment by ldez** [comment]
I can see solutions to integrate WASM plugins inside the catalog and Traefik (even if I still think that the best use of WASM is not for plugins).
It is useless to talk about that now, this is a detail that we will talk about when something will work locally inside Traefik (during the PR).

**Comment by mmatur** [comment]
@jcchavezs,

I believe Traefik should support both local and remote Wasm files. Perhaps this support could be integrated into https://plugins.traefik.io for better accessibility.

Regarding the middleware configuration, I conducted some research and found that http-wasm-host-go offers a guestConfig option, which appears suitable for passing the config to the middleware. 

https://github.com/http-wasm/http-wasm-host-go/blob/4171a60674e821aa956c985fede9beb295d026c9/handler/options.go#L25-L30.

@ldez, could you please provide more details about your vision for the Wasm integration in Traefik?

> (even if I still think that the best use of WASM is not for plugins)

What are your ideas for utilizing Wasm in Traefik?

**Comment by ldez** [comment]
> What are your ideas for utilizing Wasm in Traefik?

This is off-topic: this topic is about WASM and plugins, we can talk about it somewhere else.

**Comment by ldez** [comment]
Maybe I was not clear: it's easy to integrate a different type of plugin if the repository follows the same convention as the existing plugins.
Some changes will be needed inside the remote plugin services and Traefik but, for now, based on the current information, I don't see any blockers.

**Comment by emilevauge** [comment]
@ldez, You started this conversation with:

> even if I still think that the best use of WASM is not for plugins

An suddently, you declare this is off-topic.

> This is off-topic: this topic is about WASM and plugins, we can talk about it somewhere else.

There is no need to lock this conversation down, it's unnecessarily protective.
Please keep this conversation positive & constructive.

**Comment by ldez** [comment]
This sentence is in parenthesis because it was just an off-topic remark only to contextualize my opinion about WASM plugins.
I answered the interrogations and provided information related to WASM plugin integration despite this opinion, and I will help with the incoming work as suggested by my previous comments. I considered that as positive and constructive.

**Comment by emilevauge** [comment]
> I considered that as positive and constructive.

That was clearly not perceived this way, you should hear my feedback.
Let's get back to the main topic. Thanks.

**Comment by emilevauge** [comment]
All in all, here are important questions that still needs to be answered regarding the WASM plugin implementation: 
- can we reuse the same plugin middleware contract?
- can we reuse exsiting plugins?
Even if that's not the case, I think it's worth exploring this WASM plugin implementation, but this would definitely make things easier.

**Comment by jcchavezs** [comment]
Thanks for the feedback. 

http-wasm plugins are agnostic so ideally you could use **any** http-wasm binary into traefik which in the end is beneficial for everyone and they can be hosted in traefik plugin system (if they allow to download a file) or any other artifact published somewhere.

I was thinking of something like this for syntax for using http-wasm middleware with custom binaries

```yaml
# example for https://plugins.traefik.io/plugins/628c9f11108ecc83915d7772/traefik-token-middleware
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: http-wasm
spec:
    file: https://plugins.traefik.io/plugins/628c9f11108ecc83915d7772/traefik-token-middleware-wasm
    config:
        queryParam: token
        secret: secret
```

## can we reuse the same plugin middleware contract?

I think so.

```yaml
command:
  - --experimental.plugins.traefik-token-middleware.modulename=url-for-wasm-plugin
  - --experimental.plugins.traefik-token-middleware.version=v0.1.4
```

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: my-jwtauth
spec:
  plugin:
    traefik-token-middleware:
      queryParam: token
      secret: secret
```

and the `traefik.yml`:

```yaml
displayName: Traefik Token Middleware
type: http-wasm-middleware
binary: https://github.com/corazawaf/coraza-proxy-wasm/releases/download/{version}/coraza-proxy-wasm-{version}.zip
summary: 'Verify JWT Token from query Param'

testData:
  encodedHeader:
    - "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImp0aSI6ImY1NzVlNDZlLTU2ZDQtNGU0Zi04MDQ1LTcwMWJmYjViM2RmNCIsImlhdCI6MTYwODE1MDg1MSwiZXhwIjoxNjA4MTU0NDUxfQ.g_XGqgyR-vo1DZzHiw-HwPQJpJYSsYMvI9rdeMRJEg8"
```

## can we reuse exsiting plugins?

Some work needs to happen to recompile them in wasm (using tinygo)

**Comment by ldez** [comment]
There are 4 plugin contracts:
- the repository convention
- the programmatic "interface":
    - A type type `Config struct { ... }`.
    - A function `func CreateConfig() *Config`.
    - A function `func New(ctx context.Context, next http.Handler, config *Config, name string) (http. Handler, error)`.
- the static configuration
```yml
experimental:
  plugins:
    example:
      moduleName: github.com/traefik/plugindemo
      version: v0.2.1
# OR
experimental:
  localPlugins:
    example:
      moduleName: github.com/traefik/plugindemo
```
- the dynamic configuration
```yml
  middlewares:
    my-plugin:
      plugin:
        example:
          headers:
            Foo: Bar
```

The repository convention should be kept to ease the integration inside the catalog.
The programmatic "interface" could be only partially different because it should follow the middleware signature.
The static configuration should be changed to use another field than `moduleName` to avoid confusion and ease the handling of the current plugins.
The dynamic configuration will stay the same.

---

The 2 plugin systems can live together: we don't control the code of the current plugins so we cannot really compile for them, a compilation of plugins inside the infrastructure will lead to security issues, and the 2 systems can be handled without major difficulties.
