### ISSUE TITLE
DNS Letsencrypt for desec leads to panic

### ISSUE THREAD

**Issue by hr87** [traefik/traefik#9553]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Trying to renew letsencrypt certificate using DNS challenge for provider DESEC. Works on 2.8 tag, fails on latest tage (2.9.5).

### What did you see instead?

```
time="2022-11-27T08:53:43-07:00" level=error msg="Stack: goroutine 129 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine({0x42db560?, 0xc000155218})
	github.com/traefik/traefik/v2/pkg/safe/routine.go:66 +0xa5
github.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1.1()
	github.com/traefik/traefik/v2/pkg/safe/routine.go:56 +0x36
panic({0x42db560, 0xc000155218})
	runtime/panic.go:884 +0x212
github.com/go-acme/lego/v4/providers/dns/desec.getRecordName(...)
	github.com/go-acme/lego/v4@v4.9.0/providers/dns/desec/desec.go:184
github.com/go-acme/lego/v4/providers/dns/desec.(*DNSProvider).Present(0xc001a4e440, {0xc00123a168, 0x13}, {0xedb1eb983?, 0x0?}, {0xc0011e8720?, 0x3?})
	github.com/go-acme/lego/v4@v4.9.0/providers/dns/desec/desec.go:112 +0x7e5
github.com/go-acme/lego/v4/challenge/dns01.(*Challenge).PreSolve(0xc0005367c0, {{0xc0011345c3, 0x7}, {0x0, 0xedb1eb983, 0x0}, {{0xc0011345c0, 0x3}, {0xc00123a168, 0x13}}, ...})
	github.com/go-acme/lego/v4@v4.9.0/challenge/dns01/dns_challenge.go:94 +0x29a
github.com/go-acme/lego/v4/challenge/resolver.parallelSolve({0xc001860d30?, 0x2, 0x2}, 0xedb1eb983?)
	github.com/go-acme/lego/v4@v4.9.0/challenge/resolver/prober.go:135 +0x138
github.com/go-acme/lego/v4/challenge/resolver.(*Prober).Solve(0xc0000120c8, {0xc0016809c0, 0x2, 0x14?})
	github.com/go-acme/lego/v4@v4.9.0/challenge/resolver/prober.go:84 +0xb3
github.com/go-acme/lego/v4/certificate.(*Certifier).Obtain(0xc000feac60, {{0xc0001354a0, 0x2, 0x2}, 0x1, {0x40e8160, 0xc000bbc060}, 0x0, {0x0, 0x0}, ...})
	github.com/go-acme/lego/v4@v4.9.0/certificate/certificates.go:132 +0x362
github.com/go-acme/lego/v4/certificate.(*Certifier).Renew(0x0?, {{0xc00020f698, 0x13}, {0x0, 0x0}, {0x0, 0x0}, {0xc00051e880, 0xcab, 0xcab}, ...}, ...)
	github.com/go-acme/lego/v4@v4.9.0/certificate/certificates.go:450 +0x5a5
github.com/traefik/traefik/v2/pkg/provider/acme.(*Provider).renewCertificates(0xc000dcaa90, {0x52a21f0, 0xc000530390}, 0xc000fde200?)
	github.com/traefik/traefik/v2/pkg/provider/acme/provider.go:820 +0x525
github.com/traefik/traefik/v2/pkg/provider/acme.(*Provider).Provide(0xc000dcaa90, 0xc001a491a0, 0xc000c93170)
	github.com/traefik/traefik/v2/pkg/provider/acme/provider.go:217 +0x78e
github.com/traefik/traefik/v2/pkg/provider/aggregator.ProviderAggregator.launchProvider({{0x5286d00, 0xc0007b7780}, {0x52864b8, 0xc000b8e840}, {0xc000fb1c40, 0x3, 0x4}, 0x77359400}, 0x0?, 0xc000c93170, ...)
	github.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:208 +0x339
github.com/traefik/traefik/v2/pkg/provider/aggregator.ProviderAggregator.Provide.func1()
	github.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:186 +0x57
github.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1()
	github.com/traefik/traefik/v2/pkg/safe/routine.go:59 +0x5b
created by github.com/traefik/traefik/v2/pkg/safe.GoWithRecover
	github.com/traefik/traefik/v2/pkg/safe/routine.go:53 +0x72
"
```

### What version of Traefik are you using?

docker tag latest (as of writing 2.9.5)
Works with docker tag 2.8

### What is your environment & configuration?

Docker compose
```yaml
version: '3.8'

services:
  traefik:
    image: traefik:latest # works with 2.8
    container_name: traefik
    hostname: traefik
    domainname: ${DOMAIN?err}
    restart: unless-stopped
    privileged: false
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=internal@file,modsecurity@file,authentik-auth,headers@file"

    environment:
      - TZ=${TZ?err}

      - DESEC_TOKEN=<hidden>
      - DESEC_HTTP_TIMEOUT=600
      - DESEC_PROPAGATION_TIMEOUT=600
      - DESEC_TTL=900
      - DESEC_POLLING_INTERVAL=60
    volumes:
      - ./config:/etc/traefik:Z
      - plugins:/plugins-storage:Z
      - letsencrypt:/letsencrypt/:Z
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
      - default
    depends_on:
      - socket-proxy
      - modsecurity


  socket-proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    privileged: true
    security_opt:
      - no-new-privileges:true
    expose:
      - 2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
    environment:
      - TZ=${TZ?err}
      - CONTAINERS=1

  modsecurity:
    image: owasp/modsecurity-crs:apache
    restart: unless-stopped
    privileged: false
    security_opt:
      - no-new-privileges:true
    environment:
      - PARANOIA=1
      - ANOMALY_INBOUND=10
      - ANOMALY_OUTBOUND=5
      - BACKEND=http://dummy
    depends_on:
      - dummy

  dummy:
    image: traefik/whoami
    restart: unless-stopped
    privileged: false
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true


volumes:
  letsencrypt:
  plugins:
```

Traefik config

```yaml
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true

  https:
    address: ":443"
    http:
      #middlewares:
      #  - headers@file
      tls:
        certResolver: desec
        domains:
          - main: 'hidden.dedyn.io'
            sans:
              - '*.hidden.dedyn.io'
          - main: 'hidden2.dedyn.io'
            sans:
              - '*.hidden2.dedyn.io'

certificatesResolvers:
  desec:
    acme:
      email: <hidden>
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: desec
        delayBeforeCheck: 10
        resolvers: 
          - "1.1.1.1:53"
          - "8.8.8.8:53"

# Docker configuration backend
providers:
  file:
    filename: /etc/traefik/config.yml
    watch: true
  docker:
    exposedByDefault: false
    network: proxy
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.hidden.dedyn.io`)"
    endpoint: tcp://socket-proxy:2375

# API and dashboard configuration
api:
  dashboard: true
  insecure: false

logs:
  level: INFO


tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256

experimental:
  plugins:
    modsecurity:
      moduleName: "github.com/acouvreur/traefik-modsecurity-plugin"
      version: "v1.2.1"
```

File provider config
```yaml
http:
  middlewares:
    internal:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/32" 
          - "192.168.0.0/16"
          - "172.16.0.0/12"
          - "10.0.0.0/8"

    headers:
      headers:
        sslRedirect: true
        stsSeconds: 315360000
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        sslHost: hammerhaus.dedyn.io
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        customFrameOptionsValue: SAMEORIGIN

    modsecurity:
      plugin:
        modsecurity:
          MaxBodySize: "419430400"
          ModsecurityUrl: http://modsecurity:80
```
