### ISSUE TITLE
Router exposed with an empty TLS Option 

### ISSUE THREAD

**Issue by nmengin** [traefik/traefik#9557]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I want to secure a router using an mTLS connection.
I misspelled the `caFiles` path in the [TLSOption](https://doc.traefik.io/traefik/https/tls/#client-authentication-mtls) configuration.
I expected the router to not be used.

### What did you see instead?

The router is exposed using an empty TLS configuration, which is extra-permissive (with no mTLS).

### What version of Traefik are you using?

Traefik v2.9

### What is your environment & configuration?

```yaml
tls:
  options:
    default:
      clientAuth:
        # in PEM format. each file can contain multiple CAs.
        caFiles:
          - wrongpath/clientca1.crt
```

Add more configuration information here.
