### ISSUE TITLE
Unknown plugin type

### ISSUE THREAD

**Issue by LaboTec132** [traefik/traefik#9561]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

0. I won't be writing which plugin because I tested a lot of them and every single one is throwing this error
1. Pasted the YAML snippet to the static yaml config _(traefik.yml)_:
```yml
experimental:
  plugins:
    souin:
      moduleName: "github.com/darkweak/souin"
      version: "v1.6.23"
```
2. Restarted Traefik
3. Pasted the dynamic config to the dynamic YAML file _(fileConfig.yml)_:
```yml
http:
    middlewares:
        my-souin:
            plugin:
                souin:
                    api:
                        prometheus: ""
                        souin: ""
                    default_cache:
                        headers:
                            - Authorization
                            - Content-Type
                        regex:
                            exclude: ARegexHere
                        ttl: 10s
                    log_level: debug
                    urls:
                        domain.com/testing:
                            headers:
                                - Authorization
                            ttl: 2s
                        mysubdomain.domain.com:
                            headers:
                                - Authorization
                                - Content-Type
                            ttl: 50s
                    ykeys:
                        The_First_Test:
                            headers:
                                Content-Type: .+
                        The_Second_Test:
                            url: the/second/.+
```
4. I added the _my-souin@file_ to the middlewares in static file
5. Restarted traefik
6. Got this error 
`time="2022-11-29T22:09:25+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=https-meshcentral@docker`

- I tried like 10 different plugins
- Google gave me only old solutions like enabling pilot etc.
- When I won't add the middleware in static and try to add the middleware via docker to a specific app the middleware seems to be not working (I cant see it in HUB with other middlewares with that app). App is still working
- Tried to change names of plugins ie: deleting "_my-_" or adding "_my-_" to the plugin name or middleware name. It only changes the error message

### What did you see instead?

For every docker I have proxied by Traefik I got a line like this:

`level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=https-meshcentral@docker`

### What version of Traefik are you using?

```
Version:      2.9.5
Codename:     banon
Go version:   go1.19.3
Built:        2022-11-17T15:04:26Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

Static:
```yml
global:
  checkNewVersion: true
  sendAnonymousUsage: true

serversTransport:
  insecureSkipVerify: true

entryPoints:
  # Not used in apps, but redirect everything from HTTP to HTTPS
  http:
    address: :80
    forwardedHeaders:
      trustedIPs: &trustedIps
        # Start of Clouflare public IP list for HTTP requests, remove this if you don't use it
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 172.64.0.0/13
        - 131.0.72.0/22
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
        # End of Cloudlare public IP list
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  # HTTPS endpoint, with domain wildcard
  https:
    address: :443
    forwardedHeaders:
      # Reuse list of Cloudflare Trusted IP's above for HTTPS requests
      trustedIPs: *trustedIps
    http:
      tls:
        # Generate a wildcard domain certificate
        certResolver: letsencrypt
        domains:
          - main: xxxxx
            sans:
              - '*.xxxxx'
      middlewares:
        - securityHeaders@file
        - my-souin@file

providers:
  providersThrottleDuration: 2s

    # File provider for connecting things that are outside of docker / defining middleware
  file:
    filename: /etc/traefik/fileConfig.yml
    watch: true

  # Docker provider for connecting all apps that are inside of the docker network
  docker:
    watch: true
    network: proxynet # Add Your Docker Network Name Here
    # Default host rule to containername.domain.example
    defaultRule: "Host(`{{ lower (trimPrefix `/` .Name )}}.xxxxx.xx`)"    # Replace with your domain
    swarmModeRefreshSeconds: 5s
    exposedByDefault: false
    endpoint: "tcp://dockersocket:2375" # Uncomment if you are using docker socket proxy

# Enable traefik ui
api:
  dashboard: true
  insecure: true

# Log level INFO|DEBUG|ERROR
log:
  level: INFO

# Use letsencrypt to generate ssl serficiates
certificatesResolvers:
  letsencrypt:
    acme:
      email: xx@xxx
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        # Used to make sure the dns challenge is propagated to the rights dns servers
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
          
# plugins and other
experimental:
  plugins:
    # Souin cache
    souin:
      moduleName: "github.com/darkweak/souin"
      version: "v1.6.23"
```

Dynamic:
```yml
http:

  ## EXTERNAL ROUTING - Only use if you want to proxy something manually ##
  routers:
    ## Panoramix unRaid server
    panoramix:
      entryPoints:
        - https
      rule: Host("xxxxxx") || Host("xxxxxx") || Host("xxxxxx.xxx")
      service: xxxx
      middlewares:
        - "auth"
        - "securityHeaders"

    ## xxxx Ubiquiti router
    obelix:
      entryPoints:
        - https
      rule: Host("xxx") || Host("xxx") || Host("xxx")
      service: xxxx
      middlewares:
        - "auth"
        - "securityHeaders"

    ##  START THEME PARK ROUTERS  ##
    # Sonarr
    # sonarr-theme:
    #   entryPoints:
    #     - https
    #   rule: Host("sonarr.xxxx.xx")
    #   service: sonarr
    #   middlewares:
    #     - "auth"
    #     - "securityHeaders"
    #     - "sonarr-theme"

    # # Radarr
    # radarr-theme:
    #   entryPoints:
    #     - https
    #   rule: Host("radarr.xxxxx.xx")
    #   service: radarr
    #   middlewares:
    #     - "auth"
    #     - "securityHeaders"
    #     - "radarr-theme"
    ##  END THEME PARK ROUTERS     ##

  ## SERVICES ##
  services:
    xxxx:
      loadBalancer:
        servers:
          - url: https://xxxxx
    xxxx:
      loadBalancer:
        servers:
          - url: https://xxxxx
    ## START THEME PARK SERVICES  ##
    # Sonarr
    # sonarr-theme:
    #   loadBalancer:
    #     servers:
    #       - url: https://xxxx
    # Radarr
    # radarr-theme:
    #   loadBalancer:
    #     servers:
    #       - url: https://xxxx
    ## END THEME PARK SERVICES    ##

  ## MIDDLEWARES ##
  middlewares:
    # Only Allow Local networks
    local-ipwhitelist:
      ipWhiteList:
        sourceRange:
          - 127.0.0.1/32 # localhost
          - 192.168.1.1/24 # LAN Subnet

    # Authelia guard
    auth:
      forwardauth:
        address: http://authelia:9091/api/verify?rd=https://xxxx.xxxx.xx/ # replace auth with your authelia container name
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email

    # Authelia basic auth guard
    auth-basic:
      forwardauth:
        address: http://authelia:9091/api/verify?auth=basic # replace auth with your authelia container name
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email

    # Security headers
    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          X-Forwarded-Proto: "https"
          server: ""
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        sslProxyHeaders:
          X-Forwarded-Proto: "https"
        referrerPolicy: "same-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true

        
    #Souin plugin
    my-souin:
      plugin:
          my-souin:
              api:
                  prometheus: ""
                  souin: ""
              default_cache:
                  headers:
                      - Authorization
                      - Content-Type
                  regex:
                      exclude: ARegexHere
                  ttl: 10s
              log_level: debug
              urls:
                  domain.com/testing:
                      headers:
                          - Authorization
                      ttl: 2s
                  mysubdomain.domain.com:
                      headers:
                          - Authorization
                          - Content-Type
                      ttl: 50s
              ykeys:
                  The_First_Test:
                      headers:
                          Content-Type: .+
                  The_Second_Test:
                      url: the/second/.+
    # # Sabler plugin
    # my-sablier:
    #         plugin:
    #             sablier:
    #                 dynamic:
    #                     displayName: My Title
    #                     refreshFrequency: 5s
    #                     showDetails: "true"
    #                     theme: hacker-terminal
    #                 names: whoami,nginx
    #                 sablierUrl: http://sablier:10000
    #                 sessionDuration: 1m

    # # Fail to ban plugin
    # my-fail2ban:
    #         plugin:
    #             fail2ban:
    #                 blacklist:
    #                     ip:
    #                         - 192.168.0.0/24
    #                 rules:
    #                     action: ""
    #                     actionAbuseipdb: ""
    #                     backend: ""
    #                     banaction: ""
    #                     banactionAllports: ""
    #                     bantime: 3h
    #                     chain: ""
    #                     destemail: ""
    #                     enabled: "true"
    #                     fail2banAgent: ""
    #                     filter: ""
    #                     findtime: 10m
    #                     ignorecommand: ""
    #                     logencoding: UTF-8
    #                     maxretry: "4"
    #                     mode: ""
    #                     mta: ""
    #                     ports: 0:8000
    #                     protocol: ""
    #                     sender: ""
    #                     urlregexp: ""
    #                     usedns: ""
    #                 whitelist:
    #                     ip:
    #                         - ::1
    #                         - 127.0.0.1
    #                         - 192.168.1.8

    # # Geo block plugin
    # my-geoblock:
    #         plugin:
    #             geoblock:
    #                 allowLocalRequests: "true"
    #                 allowUnknownCountries: "false"
    #                 api: https://get.geojs.io/v1/ip/country/{ip}
    #                 apiTimeoutMs: "150"
    #                 cacheSize: "15"
    #                 countries:
    #                     - SK
    #                     - CZ
    #                 forceMonthlyUpdate: "true"
    #                 logAllowedRequests: "true"
    #                 logApiRequests: "true"
    #                 logLocalRequests: "true"
    #                 unknownCountryApiResponse: nil   
                                
    # # Simple cache https://plugins.traefik.io/plugins/62947353108ecc83915d778d/simple-cache
    # my-plugin-simplecache:
    #         plugin:
    #             plugin-simplecache:
    #                 path: /cache
    #                 maxExpiry: 600 # default: 300
    #                 cleanup: 1200 # default: 600
    #                 addStatusHeader: true # default: true

    ### Theme park https://plugins.traefik.io/plugins/62947288ffc0cd18356a97c1/theme-park ###
    # sonarr-theme:
    #   plugin:
    #     themepark:
    #       # The name of the supported application listed on https://docs.theme-park.dev/themes.
    #       app: sonarr

    #       # The name of the supported theme listed on https://docs.theme-park.dev/theme-options/ or https://docs.theme-park.dev/community-themes/
    #       theme: dark

    #       # baseUrl is optional if you want to use a self-hosted version of theme.park
    #       baseUrl: https://theme-park.xxxxx

    #       # This currently only supports '4k-logo' and 'darker' addons. Future addons that follow a similar syntax will work as well.
    #       # For refernce: https://docs.theme-park.dev/themes/addons/
    #       addons:
    #         - 4k-logo
    # radarr-theme:
    #   plugin:
    #     themepark:
    #       # The name of the supported application listed on https://docs.theme-park.dev/themes.
    #       app: radarr

    #       # If using the 'darker' addon the theme MUST be excluded or set to 'base'
    #       theme: base

    #       # Multiple addons can be included at the same time
    #       addons:
    #         - darker
    #         - 4k-logo
          ## Theme Park end ##                
    
    # # Log 4 Shell https://plugins.traefik.io/plugins/628c9ec2ffc0cd18356a97a2/log4-shell
    # my-plugin-log4shell:
    #         plugin:
    #             plugin-log4shell:
    #                 errorCode: "200"

    # #  Deny IP https://plugins.traefik.io/plugins/62947363ffc0cd18356a97d1/deny-ip-plugin
    # my-denyip:
    #         plugin:
    #             denyip:
    #                 ipDenyList:
    #                     - 127.0.0.1
    
    # # Traefik real IP https://plugins.traefik.io/plugins/628c9f01108ecc83915d776c/traefik-real-ip
    # my-traefik-real-ip:
    #         plugin:
    #             traefik-real-ip:
    #                 excludednets:
    #                     - 1.1.1.1/24


# Only use secure ciphers - https://ssl-config.mozilla.org/#server=traefik&version=2.6.0&config=intermediate&guideline=5.6              
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
```

```
docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 40
  Running: 38
  Paused: 0
  Stopped: 2
 Images: 43
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d1
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.19.17-Unraid
 Operating System: Slackware 15.0 x86_64 (post 15.0 -current)
 OSType: linux
 Architecture: x86_64
 CPUs: 36
 Total Memory: 62.69GiB
 Name: Panoramix
 ID: xxxx
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### If applicable, please paste the log output in DEBUG level

```
29. 11. 2022 22:28:55
time="2022-11-29T22:28:55+01:00" level=info msg="Stats collection is enabled."
29. 11. 2022 22:28:55
time="2022-11-29T22:28:55+01:00" level=info msg="Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration."
29. 11. 2022 22:28:55
time="2022-11-29T22:28:55+01:00" level=info msg="Help us improve Traefik by leaving this feature on :)"
29. 11. 2022 22:28:55
time="2022-11-29T22:28:55+01:00" level=info msg="More details on: https://doc.traefik.io/traefik/contributing/data-collection/"
29. 11. 2022 22:28:55
time="2022-11-29T22:28:55+01:00" level=info msg="Starting provider aggregator.ProviderAggregator"
29. 11. 2022 22:28:55
time="2022-11-29T22:28:55+01:00" level=info msg="Starting provider *file.Provider"
29. 11. 2022 22:28:55
time="2022-11-29T22:28:55+01:00" level=info msg="Starting provider *traefik.Provider"
29. 11. 2022 22:28:55
time="2022-11-29T22:28:55+01:00" level=info msg="Starting provider *docker.Provider"
29. 11. 2022 22:28:55
time="2022-11-29T22:28:55+01:00" level=info msg="Starting provider *acme.Provider"
29. 11. 2022 22:28:55
time="2022-11-29T22:28:55+01:00" level=info msg="Testing certificate renew..." providerName=letsencrypt.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"
29. 11. 2022 22:28:55
time="2022-11-29T22:28:55+01:00" level=info msg="Starting provider *acme.ChallengeTLSALPN"
29. 11. 2022 22:28:56
time="2022-11-29T22:28:56+01:00" level=error msg="plugin: unknown plugin type: my-souin" routerName=xxx@file entryPointName=https
29. 11. 2022 22:28:56
time="2022-11-29T22:28:56+01:00" level=error msg="plugin: unknown plugin type: my-souin" routerName=xxxx@file entryPointName=https
29. 11. 2022 22:28:56
time="2022-11-29T22:28:56+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=xxx@file
29. 11. 2022 22:28:56
time="2022-11-29T22:28:56+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=xxx@file
29. 11. 2022 22:28:56
time="2022-11-29T22:28:56+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=authelia@docker
29. 11. 2022 22:28:56
time="2022-11-29T22:28:56+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=https-meshcentral@docker
29. 11. 2022 22:28:56
time="2022-11-29T22:28:56+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=https-radarr@docker
29. 11. 2022 22:28:56
time="2022-11-29T22:28:56+01:00" level=error msg="plugin: unknown plugin type: my-souin" routerName=https-duplicati@docker entryPointName=https
29. 11. 2022 22:28:56
time="2022-11-29T22:28:56+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=xxx@file
29. 11. 2022 22:28:56
time="2022-11-29T22:28:56+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=https-code-server@docker
29. 11. 2022 22:28:56
time="2022-11-29T22:28:56+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=https-dashy@docker
29. 11. 2022 22:28:56
time="2022-11-29T22:28:56+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=https-sonarr@docker
29. 11. 2022 22:28:56
time="2022-11-29T22:28:56+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=https-netdata@docker
29. 11. 2022 22:28:56
time="2022-11-29T22:28:56+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=https-Dozzle@docker
29. 11. 2022 22:28:56
time="2022-11-29T22:28:56+01:00" level=error msg="plugin: unknown plugin type: my-souin" routerName=https-vaultwarden@docker entryPointName=https
29. 11. 2022 22:28:56
time="2022-11-29T22:28:56+01:00" level=error msg="plugin: unknown plugin type: my-souin" routerName=xxx@file entryPointName=https
29. 11. 2022 22:28:58
time="2022-11-29T22:28:58+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=https-code-server@docker
29. 11. 2022 22:28:58
time="2022-11-29T22:28:58+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=https-sonarr@docker
29. 11. 2022 22:28:58
time="2022-11-29T22:28:58+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=https-radarr@docker
29. 11. 2022 22:28:58
time="2022-11-29T22:28:58+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=xxx@file
29. 11. 2022 22:28:58
time="2022-11-29T22:28:58+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=https-Dozzle@docker
29. 11. 2022 22:28:58
time="2022-11-29T22:28:58+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=https-vaultwarden@docker
29. 11. 2022 22:28:58
time="2022-11-29T22:28:58+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=https-netdata@docker
29. 11. 2022 22:28:58
time="2022-11-29T22:28:58+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=https-duplicati@docker
29. 11. 2022 22:28:58
time="2022-11-29T22:28:58+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=xxx@file
29. 11. 2022 22:28:58
time="2022-11-29T22:28:58+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=api@docker
29. 11. 2022 22:28:58
time="2022-11-29T22:28:58+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=https-meshcentral@docker
29. 11. 2022 22:28:58
time="2022-11-29T22:28:58+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=https-dashy@docker
29. 11. 2022 22:28:58
time="2022-11-29T22:28:58+01:00" level=error msg="plugin: unknown plugin type: my-souin" entryPointName=https routerName=authelia@docker
```

**Comment by ldez** [comment]
Hello,

it's because you made a mistake in your configuration:


```yml
 
    #Souin plugin
    my-souin:
      plugin:
          my-souin: # <--------------------- HERE
              api:
                  prometheus: ""
                  souin: ""

```

the element after `plugin:` must be the name of the plugin from the static configuration.


```yml
# plugins and other
experimental:
  plugins:
    # Souin cache
    souin: # <-------------------- HERE
      moduleName: "github.com/darkweak/souin"
      version: "v1.6.23"

```


so expected yaml is:

```yml
```yml
 
    #Souin plugin
    my-souin: # <--------------- Name of the instance of the plugin (use for router)
      plugin:
          souin: # <------------ Name of plugin (from static configuration)
              api:
                  prometheus: ""
                  souin: ""

```

**Comment by LaboTec132** [comment]
> 

No, I did not, I just forgot to edit it back from testing. As I am saying in my post:

_Tried to change names of plugins ie: deleting "my-" or adding "my-" to the plugin name or middleware name. It only changes the error message_

**Comment by ldez** [comment]
Sorry but if I take your configuration and change the name the problem is fixed.

**Comment by LaboTec132** [comment]
> Sorry but if I take your configuration and change the name the problem is fixed.

I changed it back, tried it and it posted the same errors as before.

![vivaldi_gPqyKOjYha](https://user-images.githubusercontent.com/39591176/204671374-04dd104d-5c6f-4087-801e-d23dae485710.png)

![vivaldi_QycWbL6wN2](https://user-images.githubusercontent.com/39591176/204671365-289fd479-72cb-4252-b6d3-d8d25ea8ff66.png)
![vivaldi_mJ8eOlUDI4](https://user-images.githubusercontent.com/39591176/204671489-8113c1a6-b755-4f65-bc1f-7ba5a49b6689.png)

**Comment by ldez** [comment]
Have you tried to stop and restart Traefik after for changes?

**Comment by ldez** [comment]
just a quick example:


<details>
<summary>static</summary>

```yml
log:
  level: debug

providers:
  file:
    filename: ./example.yml
    watch: true

entryPoints:
  web:
    address: :8081
    http:
      middlewares:
        - my-plugin@file

experimental:
  plugins:
    example:
      moduleName: github.com/traefik/plugindemo
      version: v0.2.2
```

</details>

<details>
<summary>example.yml</summary>

```yml
http:

  routers:
    my-router:
      entryPoints:
        - web
      rule: Host(`localhost`)
      service: my-service

  services:
    my-service:
      loadBalancer:
        servers:
          - url: http://foo.localhost

  middlewares:
    my-plugin:
      plugin:
        example:
          headers:
            Foo: Bar

```

</details>


<details>
<summary>run</summary>

```console
$ traefik
...
DEBU[2022-11-30T00:46:27+01:00] Static configuration loaded {"global":{"checkNewVersion":true},"serversTransport":{"maxIdleConnsPerHost":200},"entryPoints":{"web":{"address":":8081","transport":{"lifeCycle":{"graceTimeOut":"10s"},"respondingTimeouts":{"idleTimeout":"3m0s"}},"forwardedHeaders":{},"http":{"middlewares":["my-plugin@file"]},"http2":{"maxConcurrentStreams":250},"udp":{"timeout":"3s"}}},"providers":{"providersThrottleDuration":"2s","file":{"watch":true,"filename":"./example.yml"}},"log":{"level":"debug","format":"common"},"experimental":{"plugins":{"example":{"moduleName":"github.com/traefik/plugindemo","version":"v0.2.2"}}}} 
INFO[2022-11-30T00:46:27+01:00] 
Stats collection is disabled.
Help us improve Traefik by turning this feature on :)
More details on: https://doc.traefik.io/traefik/contributing/data-collection/ 
DEBU[2022-11-30T00:46:27+01:00] loading of plugin: example: github.com/traefik/plugindemo@v0.2.2 
INFO[2022-11-30T00:46:27+01:00] Starting provider aggregator aggregator.ProviderAggregator 
DEBU[2022-11-30T00:46:27+01:00] Starting TCP Server                           entryPointName=web
INFO[2022-11-30T00:46:27+01:00] Starting provider *file.Provider             
DEBU[2022-11-30T00:46:27+01:00] *file.Provider provider configuration: {"watch":true,"filename":"./example.yml"} 
INFO[2022-11-30T00:46:27+01:00] Starting provider *traefik.Provider          
DEBU[2022-11-30T00:46:27+01:00] *traefik.Provider provider configuration: {} 
INFO[2022-11-30T00:46:27+01:00] Starting provider *acme.ChallengeTLSALPN     
DEBU[2022-11-30T00:46:27+01:00] *acme.ChallengeTLSALPN provider configuration: {} 
DEBU[2022-11-30T00:46:27+01:00] Configuration received: {"http":{"services":{"noop":{}},"models":{"web":{"middlewares":["my-plugin@file"]}},"serversTransports":{"default":{"maxIdleConnsPerHost":200}}},"tcp":{},"udp":{},"tls":{}}  providerName=internal
DEBU[2022-11-30T00:46:27+01:00] Configuration received: {"http":{"routers":{"my-router":{"entryPoints":["web"],"service":"my-service","rule":"Host(`localhost`)"}},"services":{"my-service":{"loadBalancer":{"servers":[{"url":"http://foo.localhost"}],"passHostHeader":true}}},"middlewares":{"my-plugin":{"plugin":{"example":{"headers":{"Foo":"Bar"}}}}}},"tcp":{},"udp":{},"tls":{}}  providerName=file
DEBU[2022-11-30T00:46:27+01:00] No default certificate, fallback to the internal generated certificate  tlsStoreName=default
DEBU[2022-11-30T00:46:27+01:00] No default certificate, fallback to the internal generated certificate  tlsStoreName=default
DEBU[2022-11-30T00:46:27+01:00] Creating middleware                           middlewareType=Pipelining entryPointName=web routerName=my-router@file serviceName=my-service middlewareName=pipelining
DEBU[2022-11-30T00:46:27+01:00] Creating load-balancer                        serviceName=my-service entryPointName=web routerName=my-router@file
DEBU[2022-11-30T00:46:27+01:00] Creating server 0 http://foo.localhost        serverName=0 entryPointName=web routerName=my-router@file serviceName=my-service
DEBU[2022-11-30T00:46:27+01:00] child http://foo.localhost now UP            
DEBU[2022-11-30T00:46:27+01:00] Propagating new UP status                    
DEBU[2022-11-30T00:46:27+01:00] Added outgoing tracing middleware my-service  entryPointName=web routerName=my-router@file middlewareName=tracing middlewareType=TracingForwarder
DEBU[2022-11-30T00:46:27+01:00] Creating middleware                           middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=web
```

</details>

I want to continue the discussion you can come to the [Traefik Community Forum](https://community.traefik.io/)
