### ISSUE TITLE
Traefik container not honouring DNS addresses to resolve ACME challenges

### ISSUE THREAD

**Issue by Kangie** [traefik/traefik#9588]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I've recently noticed that Traefik has stopped successfully renewing ACME/LetsEncrypt certificates via DNS-01 challenge.

After initially suspecting an issue with my LEGO DNS API, I have validated that appropriate TXT records are created and that Traefik is failing to resolve this.

After some time debugging I noticed that the final ACME errors are:

```
traefik_traefik.1.u65rbljbkylr@docker01    | time="2022-12-07T13:26:47Z" level=error msg="Unable to obtain ACME certificate for domains \"lab.footclan.ninja,*.lab.footclan.ninja\"" rule="Host(`traefik.lab.footclan.ninja`)" error="unable to generate a certificate for the domains [lab.footclan.ninja *.lab.footclan.ninja]: error: one or more domains had a problem:\n[*.lab.footclan.ninja] time limit exceeded: last error: read udp 127.0.0.1:34480->127.0.0.1:53: read: connection refused\n[lab.footclan.ninja] time limit exceeded: last error: read udp 127.0.0.1:44817->127.0.0.1:53: read: connection refused\n" providerName=letsencrypt.acme ACME CA="https://acme-staging-v02.api.letsencrypt.org/directory" routerName=traefik-https@docker
traefik_traefik.1.u65rbljbkylr@docker01    | time="2022-12-07T13:26:47Z" level=error msg="Unable to obtain ACME certificate for domains \"home.footclan.ninja,*.home.footclan.ninja\"" rule="Host(`medusa.home.footclan.ninja`)" error="unable to generate a certificate for the domains [home.footclan.ninja *.home.footclan.ninja]: error: one or more domains had a problem:\n[*.home.footclan.ninja] time limit exceeded: last error: read udp 127.0.0.1:56878->127.0.0.1:53: read: connection refused\n[home.footclan.ninja] time limit exceeded: last error: read udp 127.0.0.1:55083->127.0.0.1:53: read: connection refused\n" routerName=medusa-websecure@docker providerName=letsencrypt.acme ACME CA="https://acme-staging-v02.api.letsencrypt.org/directory"
```

The 127.0.0.1 is telling:

1. traefik has a global configuration directive to attempt to use 8.8.8.8 and 1.1.1.1 to resolve DNS challenges
2. 127.0.0.1 is *not* in /etc/resolv.conf

```bash
/ # nslookup -q=TXT footclan.ninja
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:
footclan.ninja  text = "google-site-verification=MFGYwX4z0WiAIfn2JQgWMOwvphYvNf0r8-DeE7WusVo"
footclan.ninja  text = "v=spf1 include:_spf.google.com ~all"

/ # nslookup -q=TXT footclan.ninja 127.0.0.1
nslookup: read: Connection refused
nslookup: read: Connection refused
^C
/ # nslookup -q=TXT footclan.ninja 127.0.0.1:53
nslookup: read: Connection refused
nslookup: read: Connection refused
;; connection timed out; no servers could be reached

/ # cat /etc/resolv.conf 
search lab.footclan.ninja infra.footclan.ninja
nameserver 127.0.0.11
options ndots:0
```

### What did you see instead?

Certificates do not renew; Traefik successfully creates TXT records which I am able to successfully validate.

### What version of Traefik are you using?

```
/ # traefik version
Version:      2.9.5
Codename:     banon
Go version:   go1.19.3
Built:        2022-11-17T15:04:26Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```toml
/ # cat /etc/traefik/traefik.toml 
[global]
  checkNewVersion = true
  sendAnonymousUsage = false

#[pilot]
#  token = ""

[log]
  level = "DEBUG"

[api]
  insecure = false
  dashboard = true
  debug = true

[entryPoints]
  [entrypoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]
      certResolver = "letsencrypt"

  [entryPoints.ssh]
    address = ":22"

  [entryPoints.irc]
    address = ":6697"

# Do not verify that services we connect to have a valid SSL certificate
# Looking at you; unifi...
[serversTransport]
  insecureSkipVerify = true

[providers]
  [providers.docker]
    swarmMode = true
    watch = true
    exposedByDefault = false
    network = "traefik-network"

[certificatesResolvers]
  [certificatesResolvers.letsencrypt]
    [certificatesResolvers.letsencrypt.acme]
      email = "Matt.Jolly@footclan.ninja"
      storage = "/letsencrypt/acme.json"
      # Staging CA for testing purposes; uncomment to test your configuration and avoid being rate-limited
      caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

    [certificatesResolvers.letsencrypt.acme.dnsChallenge]
      provider = "namecheap"
      delayBeforeCheck = 0
      # Often internal DNS resolers will cache txt records for longer than the LEGO challenge takes. Specify external providers here to validate the records.
      resolvers = ["1.1.1.1:53", "8.8.8.8:53"]


[metrics]
  [metrics.prometheus]
    buckets = [0.1,0.3,1.2,5.0]
    addEntryPointsLabels = true
    addServicesLabels = true

```

This service is running in the official Docker contianer.

### If applicable, please paste the log output in DEBUG level

[traefik-logs.tar.gz](https://github.com/traefik/traefik/files/10180311/traefik-logs.tar.gz)
