### ISSUE TITLE
RedirectScheme middleware returns bad gateway for joined X-Forwarded-Proto header

### ISSUE THREAD

**Issue by Thor77** [traefik/traefik#9597]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

If Traefik is used behind a proxy server it might receive requests containing a `X-Forwarded-Proto` header. If there are multiple proxies involved or one of them is misbehaving it might happen that there are multiple X-Forwarded-Proto headers.
According to the [HTTP/1.1 RFC](https://www.rfc-editor.org/rfc/rfc2616#page-31)
>     Multiple message-header fields with the same field-name MAY be
>     present in a message if and only if the entire field-value for that
>     header field is defined as a comma-separated list [i.e., #(values)].
>     It MUST be possible to combine the multiple header fields into one
>     "field-name: field-value" pair, without changing the semantics of the
>     message, by appending each subsequent field-value to the first, each
>     separated by a comma. The order in which header fields with the same
>     field-name are received is therefore significant to the
>     interpretation of the combined field value, and thus a proxy MUST NOT
>     change the order of these field values when a message is forwarded.
So in that case the values of the X-Forwarded-Proto might be joined together by a proxy in front of Traefik which will result in the header `X-Forwarded-Proto: https, https`.

In #9121 the RedirectScheme middleware got the ability to interpret that header to decide whether it should return a redirect. In those cases it doesn't behave correctly, though.

For requests **with** the space between the header values Traefik always returns status code 502 with this error in the debug logs:
```
'502 Bad Gateway' caused by: parse \"https://https, https://<router>/\": invalid character \" \" in host name
```

Note this is only possible with insecure forwarded headers enabled.

Relevant part in the code: https://github.com/traefik/traefik/blob/e54ee89330a800d509da7b11b46a6ecbb331e791/pkg/middlewares/redirect/redirect_scheme.go

### What did you see instead?

Traefik returns a response with status code 502

### What version of Traefik are you using?

2.9.5, problem was introduced in 2.7.2 by #9121

### What is your environment & configuration?

relevant CLI args
```
--entrypoints.http.address=:8000/tcp
--entrypoints.http.forwardedheaders.insecure=true
```

middleware configuration:
```
redirectScheme:
  permanent: true
  scheme: https
```

ingressroute (but also works with ingress or other kinds of configuration):
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: httpbin-with-middleware
spec:
  entryPoints:
  - http
  - https
  routes:
  - kind: Rule
    match: Host(`<router>`) && PathPrefix(`/`)
    services:
    - port: 8080
      name: httpbin
    middlewares:
    - name: ingress-controller-redirect-to-https@kubernetescrd
```
