### ISSUE TITLE
Kubernetes `IngressRoute` is ignoring `sniStrict` set on the router

### ISSUE THREAD

**Issue by xinbinhuang** [traefik/traefik#9605]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Try to set explicit `TLSOption` on a router, with `sniStrict=false` (default option has `sniStrict=true`). But the config seem to be ignored.

### What did you see instead?

Redirect not happening, with error log indicating strict SNI is enabled, while is not.  

### What version of Traefik are you using?

2.9.6

### What is your environment & configuration?

Using helm chart

```
...
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
    allowEmptyServices: false

# routers section
websecure:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true
      options: ""
      certResolver: myresolver
      domains: []
...
# tlsOptions section
tlsOptions:
  default:
    sniStrict: true
    preferServerCipherSuites: true
  
  redirect:
    sniStrict: false
```

Here is the ingress route & middleware config
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fallback-homepage
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: HostRegexp(`{subdomain:[a-z]+}.example.com`)
      priority: 1
      middlewares:
        - name: fallback-redirect-homepage
      services:
        - name: noop@internal
          kind: TraefikService
  tls:
    options:
      name: redirect
      namespace: traefik

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: fallback-redirect-homepage
spec:
  redirectRegex:
    permanent: true
    regex: .+
    replacement: https://example.com
```

The actual generated `TLSOption` config

```
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 'traefik:traefik.containo.us/TLSOption:traefik/redirect'
  labels:
    app.kubernetes.io/instance: traefik-argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-20.8.0
  name: redirect
  namespace: traefik
spec:
  sniStrict: false
```

UI page for the router:
<img width="1480" alt="Screen Shot 2022-12-13 at 7 54 36 PM" src="https://user-images.githubusercontent.com/27927454/207501953-62a0637c-45de-4385-a5a9-02ca861cb52f.png">

### If applicable, please paste the log output in DEBUG level

Error debug log:

```
time="2022-12-14T03:49:44Z" level=debug msg="TLS: strict SNI enabled - No certificate found for domain: \"testing.example.com\", closing connection"
5
time="2022-12-14T03:49:44Z" level=debug msg="http: TLS handshake error from 192.168.0.25:52517: tls: no certificates configured"
4
time="2022-12-14T03:49:44Z" level=debug msg="TLS: strict SNI enabled - No certificate found for domain: \"testing.example.com\", closing connection"
3
time="2022-12-14T03:49:44Z" level=debug msg="http: TLS handshake error from 192.168.0.25:42087: tls: no certificates configured"
```
