### ISSUE TITLE
GrpcWeb Middleware not being loaded in v3.0.0-beta2

### ISSUE THREAD

**Issue by Inveracity** [traefik/traefik#9607]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

It appears adding 
```yaml
  - "traefik.http.middlewares.mooncar.grpcweb.allowOrigins=*"
``` 
does not load GrpcWeb middleware as expected.

Nothing is loaded and `fmt.Println(config.GrpcWeb)` prints out `<nil>` when adding it on [line 220 in middlewares.go](https://github.com/traefik/traefik/blob/master/pkg/server/middleware/middlewares.go#L220)

I created a [community post here](https://community.traefik.io/t/getting-started-with-the-grpcweb-middleware/16778/2)

### What did you see instead?

I was expecting to see something like this:

```go
Creating middleware entryPointName=http middlewareName=grpc-web
```

### What version of Traefik are you using?

```
Version:      3.0.0-beta2
Codename:     beaufort
Go version:   go1.19.4
Built:        2022-12-07T16:32:34Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
version: '3'

services:
  reverse-proxy:
    image: traefik:v3.0.0-beta2
    command: --api.insecure=true --providers.docker --log.level=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mooncar:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    ports:
      - "50051:50051"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mooncar.rule=Host(`mooncar.docker.localhost`)"
      - "traefik.http.services.mooncar.loadbalancer.server.scheme=h2c"
      - "traefik.http.middlewares.mooncar.grpcweb.allowOrigins=*"
```
