### ISSUE TITLE
Enable serverstransports and insecureskipverify on container labels

### ISSUE THREAD

**Issue by bluepuma77** [traefik/traefik#9611]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

In our world of IT, security gets more and more important, even within networks. Services are compartmentalised, connections within are encrypted. Traefik can support this with loadbalancing to targets with custom TLS using [insecureskipverify](https://doc.traefik.io/traefik/routing/services/#insecureskipverify). 

The current challenge is that `insecureskipverify` can not just be enabled for a loadbalancer via Docker container labels, but it needs to be defined within a `servertransport`, which then needs to be assigned. But the `servertransport` can not be created within labels, but it needs to come via `provider.file`, meaning you have an extra file to take care of and can not just use a single `docker-compose.yml`. Or you define a global `servertransport`, but then you can not verify any internal TLS.

This feature request calls for enabling `servertransport` and `insecureskipverify` on Docker labels to make use easier, make our IT world a bit more secure and reduce the support requests in the Traffic community. 

Example how it should work:
```
version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce:2.16.2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - portainer_data:/data
    networks:
      - proxy
      - agent_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.example.com`)
      - traefik.http.routers.portainer.tls.certresolver=myresolver
      - traefik.http.services.portainer.loadbalancer.passhostheader=true
      - traefik.http.services.portainer.loadbalancer.server.port=9443
      - traefik.http.services.portainer.loadbalancer.serverstransport=mytransport
      - traefik.http.serverstransports.mytransport.insecureskipverify=true

```

Some Traefik community references: [1](https://community.traefik.io/t/insecureskipverify-how-to-apply-this-at-a-service-level-in-docker-compose/16155/4), [2](https://community.traefik.io/t/traefik-portainer-bad-certificate/16799/14), [3](https://community.traefik.io/t/servers-transport-not-found/11513), [4](https://community.traefik.io/t/insecureskipverify-true/11316/3)
