### ISSUE TITLE
k3s traefik dashboard 404

### ISSUE THREAD

**Issue by PahaCore** [traefik/traefik#9624]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

traefik dashboard does not work according to the instructions in k3s (Kubernetes) - error 404, I read on the Internet this is a massive problem, maybe it's worth making the instructions better?

links to instructions and procedure :

1) `curl -sfL https://get.k3s.io | sh -`
2) https://doc.traefik.io/traefik/operations/dashboard/#dashboard-router-rule

```sh
$ k3s kubectl apply -f dashboard.yaml
```

```yml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`domains.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
```

3) domains.com = 404

I tried a lot of options that I found on the web - it didn't work out
therefore, I wrote here the simplest and described instructions and it also does not work

### What did you see instead?

404

### What version of Traefik are you using?

v20.8.0

### What is your environment & configuration?

k3s
