### ISSUE TITLE
Traefik auto-update broke path-matching, until deployments were restarted

### ISSUE THREAD

**Issue by marcusbuffett** [traefik/traefik#9629]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

At midnight, Traefik updated itself:
```
➜ k get pods --namespace kube-system
NAME                                      READY   STATUS      RESTARTS   AGE
helm-install-traefik-nrsmt                0/1     Completed   0          8h
```

After this, all my ingresses with path-matching stopped working. I had an ingress like this:

```yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chess
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: chessmadra.com
      http: &http_rules
        paths:
          - path: "/api"
            pathType: Prefix
            backend:
              service:
                name: chess
                port:
                  number: 80
  tls:
    - hosts:
        - chessmadra.com
      secretName: chess-madra-cert-prod
```
After the update, `/api` requests were no longer routed to this service. Instead they were routed to this service:
```yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chess-frontend
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: chessmadra.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: chess-frontend
                port:
                  number: 80
  tls:
    - hosts:
        - chessmadra.com
      secretName: chess-madra-cert-prod
```

This caused the site to go down, until I ran `kubectl -n kube-system rollout restart daemonsets,deployments` and `kubectl rollout restart deployments`. 

Is there anything wrong with my ingress config for these, that would cause traefik to not pick up their paths until they were restarted?

Is there a way to disable auto-updates so this doesn't happen again?

### What did you see instead?

_

### What version of Traefik are you using?

2.9.4

### What is your environment & configuration?

k3s, helm installed traefik

### If applicable, please paste the log output in DEBUG level

No logs unfortunately, the old pod isn't around anymore after the restart.
