### ISSUE TITLE
Possible memory leak in v2.8.3

### ISSUE THREAD

**Issue by zzzkl** [traefik/traefik#9636]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

In k8s traefik v2.8.3. With 1500 QPS requests which are all 404.
Causing traefik pod memory (container_memory_working_set_bytes) increase to 30GB in 6.5 hours. 
But RSS(container_memory_rss) remain the same
<img width="933" alt="image" src="https://user-images.githubusercontent.com/879096/210321447-658f8b3d-c411-4321-b314-ab93ce0ee6f6.png">

It seems like the massive log print causing pod memory increase.

### What did you see instead?

Causing traefik pod memory (container_memory_working_set_bytes) increase to 30GB in 6.5 hours. 
But RSS(container_memory_rss) remain the same
<img width="933" alt="image" src="https://user-images.githubusercontent.com/879096/210321447-658f8b3d-c411-4321-b314-ab93ce0ee6f6.png">

Below is pprof alloc space, inuse space keeps low.
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/879096/210321874-3da02ddd-155e-481b-a54a-fd2a525c7081.png">

### What version of Traefik are you using?

v2.8.3

### What is your environment & configuration?

```yaml

global:
  checkNewVersion: false    ## 周期性的检查是否有新版本发布
  sendAnonymousUsage: false ## 周期性的匿名发送使用统计信息
serversTransport:
  insecureSkipVerify: true  ## Traefik 忽略验证代理服务的 TLS 证书
api:
  insecure: true            ## 允许 HTTP 方式访问 API
  dashboard: true           ## 启用 Dashboard
  debug: true              ## 启用 Debug 调试模式
metrics:
  prometheus:               ## 配置 Prometheus 监控指标数据，并使用默认配置
    addRoutersLabels: true  ## 添加 routers metrics
    entryPoint: metrics     ## 指定 metrics 8082为metric监听地址
entryPoints:
  web:
    address: ":80"          ## 配置 80 端口，并设置入口名称为 web
    forwardedHeaders: 
      insecure: true        ## 信任所有的forward headers
  websecure:
    address: ":443"         ## 配置 443 端口，并设置入口名称为 websecure
    forwardedHeaders: 
      insecure: true
  traefik:
    address: ":8090"        ## 配置 8090 端口，并设置入口名称为 dashboard
  metrics:
    address: ":8082"        ## 配置 8082 端口，作为metrics收集入口
  tcp:                    
    address: ":8079"        ## 配置 8079 端口，作为tcp访问入口
providers:
  kubernetesCRD:            ## 启用 Kubernetes CRD 方式来配置路由规则
    #ingressClass: traefik-v2.8
    allowCrossNamespace: true   ##允许跨namespace
    allowEmptyServices: true    ##允许空endpoints的service
  kubernetesIngress:        ## 启动 Kubernetes Ingress 方式来配置路由规则
    ingressClass: ""
log:
  filePath: "/etc/traefik/logs/traefik.log"              ## 设置调试日志文件存储路径，如果为空则输出到控制台
  level: error              ## 设置调试日志级别
  format: "common"                ## 设置调试日志格式
accessLog:
  filePath: "/etc/traefik/logs/access.log"              ## 设置访问日志文件存储路径，如果为空则输出到控制台
  format: "json"                ## 设置访问调试日志格式
  bufferingSize: 1000          ## 设置访问日志缓存行数
  filters:
    #statusCodes: ["200"]   ## 设置只保留指定状态码范围内的访问日志
    #retryAttempts: true     ## 设置代理访问重试失败时，保留访问日志
    #minDuration: 20         ## 设置保留请求时间超过指定持续时间的访问日志
  fields:                   ## 设置访问日志中的字段是否保留（keep 保留、drop 不保留）
    defaultMode: keep       ## 设置默认保留访问日志字段
    names:                  ## 针对访问日志特别字段特别配置保留模式
      ClientUsername: drop
      StartUTC: drop        ## 禁用日志 timestamp 使用UTC
    headers:                ## 设置 Header 中字段是否保留
      defaultMode: keep     ## 设置默认保留 Header 中字段
      names:                ## 针对 Header 中特别字段特别配置保留模式
        User-Agent: redact  ## 可以针对指定agent
        Authorization: drop
        Content-Type: keep
        Cookie: keep
```

Add more configuration information here.
