### ISSUE TITLE
YAML config works with Traefik 2.7.3 but not in newer releases

### ISSUE THREAD

**Issue by aki-k** [traefik/traefik#9641]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I created multiple http routers and services. The routers and services
work in Traefik 2.7.3 but not in newer releases.

### What did you see instead?

```
{"level":"error","entryPointName":"websecure","routerName":"vnc_timo@file","error":"the service \"║24║vnc_timo@file\" does not exist","time":"2023-01-05T15:18:32Z"}
```

### What version of Traefik are you using?

```
Version:      2.7.3
Codename:     epoisses
Go version:   go1.17.11
Built:        2022-06-29T13:48:15Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```
http:
  routers:
    vnc_timo:
      entryPoints:
        - websecure
      rule: "Host(`FQDN`) && PathPrefix(`/vnc_timo/`)"
      middlewares:
      - rewrite_vnc_timo
      service:
      - vnc_timo
      tls:
        certResolver: letsencrypt

  middlewares:
    rewrite_vnc_timo:
      stripPrefix:
        prefixes:
          - "/vnc_timo/"

  services:
    vnc_timo:
      loadBalancer:
        servers:
          - url: "http://container.hostname:6080/"

```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

```
{"entryPointName":"websecure","level":"error","msg":"the service \"║24║vnc_timo@file\" does not exist","routerName":"vnc_timo@file","time":"2023-01-05T18:16:28Z"}
```

**Comment by aki-k** [comment]
Configuration info:

Hosts are CentOS 7
3 node Docker Swarm

**Comment by ldez** [comment]
Hello,


It's because the configuration validation is more strict now, your configuration contains an error: `service` is a string and not an array.



```yml
http:
  routers:
    vnc_timo:
      entryPoints:
        - websecure
      rule: "Host(`FQDN`) && PathPrefix(`/vnc_timo/`)"
      middlewares:
        - rewrite_vnc_timo
      service: vnc_timo # <------------- THE FIX HERE
      tls:
        certResolver: letsencrypt

  middlewares:
    rewrite_vnc_timo:
      stripPrefix:
        prefixes:
          - "/vnc_timo/"

  services:
    vnc_timo:
      loadBalancer:
        servers:
          - url: "http://container.hostname:6080/"
```
