### ISSUE TITLE
 Docker instance of Traefik shutting down on it’s own

### ISSUE THREAD

**Issue by gustavodeon** [traefik/traefik#9643]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

i'm setting up my homelab with Traefik through the official docker image, simple reverse proxy from subdomain to internal ports through a docker network, the plan is for traefik to run 24/7 serving my services on external network. I'm currently using portainer (2.16.2) to deploy the container.

### What did you see instead?

When i leave my instance of Traefik up for a long-ish period of time it stops itself out of nowhere, the server wasn't being ssh into, traefik wasn't receiving any requests and there aren't any configurations defining resources limitations on the docker-compose.yml.

### What version of Traefik are you using?

Version:      2.9.6
Codename:     banon
Go version:   go1.19.4
Built:        2022-12-07T14:17:58Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

Traefik yaml:

```yml
version: '3'
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.network=reverseproxy-nw"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      
      #- "--entrypoints.websecure.address=:443"

      # cert resolver
      #- "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      #- "--certificatesresolvers.myresolver.acme.email=email@example.com"
      #- "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "/home/gustavo/aplications/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.domain.com`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
    networks:
      - reverseproxy-nw
    
networks:
  reverseproxy-nw:
    name: reverseproxy-nw
    external: true
```

PS: Commented lines are for enabling SSL certificates once i can lay down the foundation and iron out all the "unwanted behaviours".

Example service that uses traefik proxy:

```yml
version: '3.3'
services:
    portainer:
        labels:
            - "traefik.http.routers.portainer.rule=Host(`portainer.domain.com`)"
            - "traefik.http.routers.portainer.entrypoints=web"
            - "traefik.http.services.portainer.loadbalancer.server.port=9000"
            - "traefik.enable=true"
        container_name: portainer
        command: -H unix:///var/run/docker.sock
        ports:
            - '8000:8000'
            - '9000:9000'
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - './portainer_data:/data'
        image: portainer/portainer-ce
        environment:
            - VIRTUAL_HOST=portainer.domain.com
            - VIRTUAL_PORT=9000
        networks:
            - reverseproxy-nw

networks:
  reverseproxy-nw:
    external: true
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

```
time="2023-01-03T17:34:12Z" level=error msg="Error while Peeking first byte: read tcp 172.25.0.3:80->200.71.120.196:42276: read: connection timed out"
time="2023-01-03T17:59:52Z" level=debug msg="'499 Client Closed Request' caused by: context canceled"
time="2023-01-03T18:32:27Z" level=info msg="I have to go..."
time="2023-01-03T18:32:27Z" level=info msg="Stopping server gracefully"
time="2023-01-03T18:32:28Z" level=debug msg="Waiting 10s seconds before killing connections." entryPointName=traefik
time="2023-01-03T18:32:28Z" level=debug msg="Waiting 10s seconds before killing connections." entryPointName=web
time="2023-01-03T18:32:28Z" level=error msg="accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2023-01-03T18:32:28Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2023-01-03T18:32:28Z" level=error msg="close tcp [::]:80: use of closed network connection" entryPointName=web
time="2023-01-03T18:32:28Z" level=debug msg="Entry point web closed" entryPointName=web
time="2023-01-03T18:32:28Z" level=error msg="close tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2023-01-03T18:32:28Z" level=debug msg="Entry point traefik closed" entryPointName=traefik
time="2023-01-03T18:32:28Z" level=info msg="Server stopped"
time="2023-01-03T18:32:28Z" level=info msg="Shutting down"
```
