### ISSUE TITLE
Linked SVG images are broken in control panel

### ISSUE THREAD

**Issue by hdecarne** [traefik/traefik#9647]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Installed and setup Traefik 3.0.0-beta2.
Accessed the control panel.

### What did you see instead?

Linked SVG images (e.g. for file provider) are broken respectively shown as XML source if opended directly.
![image](https://user-images.githubusercontent.com/2044567/211131302-41e5f55d-19de-470b-8ba3-ac09770c3ae4.png)
Most likely, as they are considered as text by the browser. Same result for different browsers (Chrome, Edge, Safari).

### What version of Traefik are you using?

```
Version:      3.0.0-beta2
Codename:     beaufort
Go version:   go1.19.4
Built:        2022-12-07T16:32:34Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
global:
  checkNewVersion: false
  sendAnonymousUsage: false
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: www.<mydomain>
            sans:
              - login.<mydomain>
              - cloud.<mydomain>
    http3: {}
  admin:
    address: :8443
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: <traefik server name>
    http3: {}
api:
  insecure: false
  dashboard: true
metrics:
  influxDB2:
    address: <influxdb2 server name>
    token: <token>
    org: <org>
    bucket: <bucket>
    addEntryPointsLabels: true
    addRoutersLabels: false
    addServicesLabels: true
log:
  level: INFO
  filePath: /var/log/traefik/traefik.log
accessLog:
  filePath: /var/log/traefik/access.log
  format: json
certificatesResolvers:
  letsencrypt:
    acme:
      storage: /etc/traefik/acme.json
      email: webmaster@<mydomain>
      tlsChallenge: {}
providers:
  file:
    directory: /etc/traefik/traefik.d
    watch: true
```
