### ISSUE TITLE
Router name empty in access log

### ISSUE THREAD

**Issue by knipknap** [traefik/traefik#9648]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have a problem that Traefik responds with HTTP on a TCP endpoint. In order to debug the issue, I executed a request to the TCP port like this:

```
$ telnet mail.mydomain.com 587
Trying 1.2.3.4...
Connected to mail.mydomain.com.
Escape character is '^]'.
GET / HTTP/1.0

HTTP/1.0 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Sun, 08 Jan 2023 12:28:57 GMT
Content-Length: 19

404 page not found
Connection closed by foreign host.
```

And then took a look into the access log to find out which router is handling the request.
 
[According to the docs](https://doc.traefik.io/traefik/observability/access-logs/#format), the last three fields should be the interesting ones, as they *should* include:

    "<Traefik_router_name>" "<Traefik_server_URL>" <request_duration_in_ms>ms

However, the access log contains no router name.

### What did you see instead?

From the access log:

    myswarm_traefik.1.of166iz3i553@swarm    | 10.0.0.2 - - [08/Jan/2023:12:28:57 +0000] "GET / HTTP/1.0" - - "-" "-" 746 "-" "-" 0ms

Note that the last three fields are empty, not showing the information required for debugging.

### What version of Traefik are you using?

2.9.6

### What is your environment & configuration?

Here is my `docker-compose.yml` to reproduce the issue:

```
version: "3.8"
services:
  traefik:
    # Use the latest Traefik image
    image: traefik:2.9.6
    ports:
      - "80:80"
      - "443:443"
      - "587:587"
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the manager node,
          # as the node with it has the volume for the certificates
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.middlewares.admin-auth.basicauth.users=traefik-admin:admin-pwd
        - traefik.http.routers.traefik-dashboard-http.rule=Host(`traefik.mydomain.com`)
        - traefik.http.routers.traefik-dashboard-http.entrypoints=http
        - traefik.http.routers.traefik-dashboard-http.middlewares=https-redirect
        - traefik.http.routers.traefik-dashboard-https.rule=Host(`traefik.mydomain.com`)
        - traefik.http.routers.traefik-dashboard-https.entrypoints=https
        - traefik.http.routers.traefik-dashboard-https.tls=true
        - traefik.http.routers.traefik-dashboard-https.tls.certresolver=le
        - traefik.http.routers.traefik-dashboard-https.service=api@internal
        - traefik.http.routers.traefik-dashboard-https.middlewares=admin-auth
        - traefik.http.services.traefik-dashboard-https.loadbalancer.server.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates
    command:
      - --log.level=DEBUG
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entrypoints.smtptls.address=:587
      - --providers.docker
      - --providers.docker.swarmmode
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.le.acme.email=me@mydomain.com
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --accesslog
      - --log
      - --api
      - --serverstransport.insecureskipverify=true
    networks:
      - traefik-public
      - default

  mail_relay:
    image: knipknap/docker-simple-mail-forwarder:latest
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.tcp.routers.mail_relay.tls=true
        - traefik.tcp.routers.mail_relay.tls.certresolver=le
        - traefik.tcp.routers.mail_relay.rule=HostSNI(`mail.mydomain.com`)
        - traefik.tcp.routers.mail_relay.entrypoints=smtptls
        - traefik.tcp.routers.mail_relay.service=mail_relay
        - traefik.tcp.services.mail_relay.loadbalancer.server.port=25
    environment:
      - SMF_CONFIG=source@mydomain.com:destination@elsewhere
      - SMF_DOMAIN=mail.mydomain.com
      - SMF_POSTFIX_myhostname=mail.mydomain.com

volumes:
  # Create a volume to store the certificates. Make sure there is a constraint to have
  # Traefik always deployed to the same Docker node with the same volume containing
  # the HTTPS certificates. (by default this is done my constraining Traefik to the
  # manager node, see above.
  traefik-public-certificates:
    driver: local

networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true
```

Docker version 20.10.12, build 20.10.12-0ubuntu4

### If applicable, please paste the log output in DEBUG level

Already included above.
