### ISSUE TITLE
Error while Peeking first bytes 

### ISSUE THREAD

**Issue by rscorer** [traefik/traefik#9653]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I just installed Hub on an existing traefik installation which runs in docker-compose. It installed simply and quickly, for which I'm grateful!

However, once it was up and running I encounter this error log every few seconds (or quicker)

Error while Peeking first bytes error=EOF

This is different from the reports on google and the community forum which refer to `Error while Peeking first byte` and have an IP address to show which service is causing the issue.

There is nothing for me to track down here, I've no idea who is causing the problem.

I had seen this error once or twice prior to installing the hub... certainly not as frequently though

### What did you see instead?

`traefik-traefik-1     | 2023-01-10T13:44:28Z ERR Error while Peeking first bytes error=EOF
traefik-traefik-1     | 2023-01-10T13:44:28Z ERR Error while Peeking first bytes error=EOF
traefik-traefik-1     | 2023-01-10T13:44:28Z ERR Error while Peeking first bytes error=EOF
traefik-traefik-1     | 2023-01-10T13:44:28Z ERR Error while Peeking first bytes error=EOF
traefik-traefik-1     | 2023-01-10T13:44:53Z ERR Error while Peeking first bytes error=EOF
traefik-traefik-1     | 2023-01-10T13:44:53Z ERR Error while Peeking first bytes error=EOF
traefik-traefik-1     | 2023-01-10T13:44:54Z ERR Error while Peeking first bytes error=EOF
traefik-traefik-1     | 2023-01-10T13:44:54Z ERR Error while Peeking first bytes error=EOF
traefik-traefik-1     | 2023-01-10T13:44:57Z ERR Error while Peeking first bytes error=EOF
traefik-traefik-1     | 2023-01-10T13:44:57Z ERR Error while Peeking first bytes error=EOF
traefik-traefik-1     | 2023-01-10T13:44:57Z ERR Error while Peeking first bytes error=EOF
traefik-traefik-1     | 2023-01-10T13:44:57Z ERR Error while Peeking first bytes error=EOF
traefik-traefik-1     | 2023-01-10T13:44:58Z ERR Error while Peeking first bytes error=EOF
traefik-traefik-1     | 2023-01-10T13:44:58Z ERR Error while Peeking first bytes error=EOF
traefik-traefik-1     | 2023-01-10T13:44:58Z ERR Error while Peeking first bytes error=EOF
traefik-traefik-1     | 2023-01-10T13:44:58Z ERR Error while Peeking first bytes error=EOF
traefik-traefik-1     | 2023-01-10T13:45:23Z ERR Error while Peeking first bytes error=EOF
traefik-traefik-1     | 2023-01-10T13:45:23Z ERR Error while Peeking first bytes error=EOF
traefik-traefik-1     | 2023-01-10T13:45:24Z ERR Error while Peeking first bytes error=EOF`

### What version of Traefik are you using?

Version:      3.0.0-beta2
Codename:     beaufort
Go version:   go1.19.4
Built:        2022-12-07T16:32:34Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
  traefik:
    image: traefik:v3.0
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 8080
    command:
      - --providers.docker.exposedByDefault=false
      - --api.insecure=true
      # Enable Hub communication (open the port 9900 and 9901 by default)
      - --experimental.hub=true
      - --hub.tls.insecure=true
      - --metrics.prometheus.addrouterslabels=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

```

Add more configuration information here.
docker-compose running on a Digital Ocean Ubuntu :
`Linux sili52 5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
