### ISSUE TITLE
Docker-Compose labels picking up wrong Router-Service-Connection

### ISSUE THREAD

**Issue by Te-eMster** [traefik/traefik#9666]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hi,
I have Traefik running in front of a Docker-host which is used to test various frontend-backend scenarios. The frontend is the part which is exposed to traefik and each frontend-container is based on the same image.

So right now I have 2 instances up. The middleware "httpsredirect" is defined directly in the traefik-container.
Below are the two docker-compose labels (cutting out sensitive information):

No. 1:
```
  dev01_frontend:
    container_name: dev01_frontend
    image: devshop:jenkins-final
    labels:
      - "traefik.enable=true"
      # ROUTERS
      - "traefik.http.routers.docker-deployment.rule=Host(`dev01.domain.com`)"
      - "traefik.http.routers.docker-deployment.entrypoints=web"
      - "traefik.http.routers.docker-deployment.middlewares=httpsredirect"
      - "traefik.http.routers.docker-deployment.service=docker-deployment"
      - "traefik.http.routers.docker-deployment-secure.rule=Host(`dev01.domain.com`)"
      - "traefik.http.routers.docker-deployment-secure.entrypoints=websecure"
      - "traefik.http.routers.docker-deployment-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.docker-deployment-secure.service=docker-deployment"
      # SERVICES
      - "traefik.http.services.docker-deployment.loadbalancer.server.port=80"
```

No. 2:
```
  dev02_frontend:
    container_name: dev02_frontend
    image: devshop:jenkins-final
    labels:
      - "traefik.enable=true"
      # ROUTERS
      - "traefik.http.routers.docker-deployment-02.rule=Host(`dev02.domain.com`)"
      - "traefik.http.routers.docker-deployment-02.entrypoints=web"
      - "traefik.http.routers.docker-deployment-02.middlewares=httpsredirect"
      - "traefik.http.routers.docker-deployment-02.service=docker-deployment"
      - "traefik.http.routers.docker-deployment-02-secure.rule=Host(`dev02.domain.com`)"
      - "traefik.http.routers.docker-deployment-02-secure.entrypoints=websecure"
      - "traefik.http.routers.docker-deployment-02-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.docker-deployment-02-secure.service=docker-deployment-02"
      # SERVICES
      - "traefik.http.services.docker-deployment-02.loadbalancer.server.port=80"
```

Expected behaviour:
- Routing:
  - docker-deployment -> http for service "docker-deployment"
  - docker-deployment-secure -> https for service "docker-deployment"
  - docker-deployment-02 -> http for service "docker-deployment-**02**"
  - docker-deployment-02-secure -> https for service "docker-deployment-**02**"

### What did you see instead?

So the actual routing is:
  - docker-deployment -> http for service "docker-deployment"
  - docker-deployment-secure -> https for service "docker-deployment"
  **- docker-deployment-02 -> http for service "docker-deployment"**
  - docker-deployment-02-secure -> https for service "docker-deployment-02"

I have no idea where this link from router "docker-deployment-02" to service "docker-deployment" (without "-02") is being made. In the Debug-Log it is found that the configuration is "received" like that - but I cannot find the reason in the container labels.
I had a similar problem once which could be resolved by using different images (i.e. "duplicating" the original image) per instance.

### What version of Traefik are you using?

2.9.6

### What is your environment & configuration?

traefik.yml:

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    watch: true
  file:
    filename: /dynconf/dynconf.yml 
    watch: true

entryPoints:
  web:
    address: :80
  websecure:
    address: :443
  dashboardsecure:
    address: :8443

accesslog: {}

log:
  level: INFO

certificatesResolvers:
  myresolver:
    acme:
      tlschallenge: {}

### If applicable, please paste the log output in DEBUG level

level=debug msg="Configuration received: 
{\"http\":{
	\"routers\":{
		\"docker-deployment\":{
			\"entryPoints\":[\"web\"],
			\"middlewares\":[\"httpsredirect\"],
			\"service\":\"docker-deployment\",
			\"rule\":\"Host(`dev01.domain.com`)\“
		},
		\"docker-deployment-02\":{
			\"entryPoints\":[\"web\"],
			\"middlewares\":[\"httpsredirect\"],
			\"service\":\"docker-deployment\",
			\"rule\":\"Host(`dev02.domain.com`)\"
		},
		\"docker-deployment-02-secure\":{
			\"entryPoints\":[\"websecure\"],
			\"middlewares\":[],
			\"service\":\"docker-deployment-02\",
			\"rule\":\"Host(`dev02.domain.com`)\“,
			\"tls\":{\"certResolver\":\"myresolver\"}
		},
		\"docker-deployment-secure\":{
			\"entryPoints\":[\"websecure\"],
			\"middlewares\":[],
			\"service\":\"docker-deployment\",
			\"rule\":\"Host(`dev01.domain.com`)\“,
			\"tls\":{\"certResolver\":\"myresolver\"}
		},
	},
	\"services\":{
		\"docker-deployment\":{
			\"loadBalancer\":{
				\"servers\":[{\"url\":\"http://XXX.XX.X.XX:80\"}],
				\"passHostHeader\":true
			}
		},
		\"docker-deployment-02\":{
			\"loadBalancer\":{
				\"servers\":[{\"url\":\"http://XXX.XX.X.XX:80\"}],
				\"passHostHeader\":true
			}
		},
	},
},
\"tcp\":{},
\"udp\":{}
}" providerName=docker
