### ISSUE TITLE
Unexpected EOF when making request with Safari

### ISSUE THREAD

**Issue by A1Liu** [traefik/traefik#9668]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Sent request to https://nyu.a1liu.com/ with Safari

Used Traefik with Docker Compose, here's the `docker-compose.yml` contents:

Expected the server to respond with a webpage, which is the behavior on Firefox and Chrome.

### What did you see instead?

1. Safari responds with the following:
   
   ![324368330_1137197603665846_155495665607981708_n](https://user-images.githubusercontent.com/3584830/212775030-563415bb-e98f-4a7f-adb9-6c2ad0e07fbd.png)

2. Traefik has the following log message:

   ![image](https://user-images.githubusercontent.com/3584830/212775096-dbc94c9f-94c4-4a2f-ae77-d4595c5712ee.png)

   ```
   reverseproxy.go:505: httputil: ReverseProxy read error during body copy: unexpected EOF
   ```

### What version of Traefik are you using?

Version:      2.9.6
Codename:     banon
Go version:   go1.19.4
Built:        2022-12-07T14:17:58Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

Docker compose file
```yaml
version: '3.3'

services:
reverse-proxy:
  # The official v2.1 Traefik docker image
  image: traefik:v2.9.6
  restart: always

  command:
    # You need to actively say traefik.enable=true
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"

    - "--entrypoints.web.address=:80"
    - "--entrypoints.websecure.address=:443"

    - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
    - "--certificatesresolvers.mytlschallenge.acme.email=albertymliu@gmail.com"
    - "--certificatesresolvers.mytlschallenge.acme.storage=/.letsencrypt/acme.json"

  ports:
    - "80:80"
    - "443:443"

  volumes:
    # So that Traefik can listen to the Docker events
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "/home/ubuntu/schedge/.letsencrypt:/.letsencrypt"

postgres:
  image: postgres:14.1-alpine
  restart: always
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  logging:
    options:
      max-size: 10m
      max-file: "3"
  expose:
    - "5432"

  volumes:
    - "/home/ubuntu/schedge/.build/postgres:/var/lib/postgresql/data"

schedge:
  image: ghcr.io/a1liu/schedge:latest
  restart: always
  environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=postgres
    - SCHEDGE_ADMIN_PASSWORD=$SCHEDGE_ADMIN_PASSWORD
    - JDBC_URL=jdbc:postgresql://postgres/postgres

  expose:
    - "4358"

  labels:
    - "traefik.enable=true"
    - "com.centurylinklabs.watchtower.enable=true"
    - "com.centurylinklabs.watchtower.stop-signal=SIGKILL"

    - "traefik.http.services.schedge.loadbalancer.server.port=4358"

      # HTTPS
    - "traefik.http.routers.schedge-https.rule=Host(`nyu.a1liu.com`)"
    - "traefik.http.routers.schedge-https.service=schedge"
    - "traefik.http.routers.schedge-https.entrypoints=websecure"
    - "traefik.http.routers.schedge-https.tls.certresolver=mytlschallenge"

      # HTTP
    - "traefik.http.routers.schedge-http.rule=Host(`nyu.a1liu.com`)"
    - "traefik.http.routers.schedge-http.service=schedge"
    - "traefik.http.routers.schedge-http.entrypoints=web"

watchtower:
  image: containrrr/watchtower:1.4.0
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: --interval 300 --cleanup --label-enable
  restart: unless-stopped
```

**Comment by A1Liu** [comment]
As a note, other paths work, like for example, https://nyu.a1liu.com/api works on safari as expected

**Comment by mpl** [comment]
Hello @A1Liu ,

Do you see the same discrepancy with http://nyu.a1liu.com VS http://nyu.a1liu.com/api (with `http`) or do you only see the problem with `https` ?

**Comment by A1Liu** [comment]
The problem only seems to come up with https, http://nyu.a1liu.com works fine on all platforms i've tested

**Comment by mpl** [comment]
Ok, I'm also seeing a problem specific to safari in the https case, but my error is different. Mine is "cannot parse response. NSURLErrorDomain:-1017".
So atm I'm not sure that I've reproduce the same error.

**Comment by mpl** [comment]
@A1Liu oh btw, I had not thought of it earlier, but with my safari (Version 15.2 (17612.3.6.1.6)), I can actually access your server, as shown on the screenshot.
So tbh, I don't think this is a Traefik problem, but rather a safari one.
Could you please maybe retry with another version of Safari?

![Screenshot 2023-01-18 at 17 26 32](https://user-images.githubusercontent.com/626071/213238103-9d34ab83-b264-419c-b3b5-d0343811422c.png)

**Comment by A1Liu** [comment]
Hmmm, I'm on a more upgraded version of Safari: 16.2 (18614.3.7.1.5)

I will see what I can do

**Comment by mpl** [comment]
And I can also access your server from Firefox Mobile (Android, 108.2.0).

**Comment by A1Liu** [comment]
Also though, Traefik is still outputting an error log when responding to Safari, so I don't think it's soley a Safari thing.

```
reverseproxy.go:505: httputil: ReverseProxy read error during body copy: unexpected EOF
```

Firefox Mobile uses a different engine on Android and iOS; I found it works on Android Firefox but not on iOS Firefox or iOS Safari, but I am updating my phone now to see what happens with a newer Safari.

**Comment by mpl** [comment]
Sure, I had noticed that the log line was happening when requesting with Chrome as well. However there's no guarantee that this log error as anything to do with your problem (but we certainly would have to make sure of it).

btw, one possible hint (that we will look into) is:
https://apple.stackexchange.com/questions/409055/safari-iphone-macbook-gives-nsurlerrordomain-1017

**Comment by mpl** [comment]
btw, it looks like we're not doing anything wrong regarding sending an HTTP/2 upgrade when not needed (the lead I mentioned above), because it seems to be going fine with curl:

```
mbp:9668 mpl$ docker run -t --rm badouralix/curl-http2 -I -v https://nyu.a1liu.com
*   Trying 44.196.192.39:443...
* Connected to nyu.a1liu.com (44.196.192.39) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* [CONN-0-0][CF-SSL] TLSv1.0 (OUT), TLS header, Certificate Status (22):
* [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS handshake, Client hello (1):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Certificate Status (22):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Server hello (2):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Finished (20):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Certificate (11):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, CERT verify (15):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Finished (20):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Finished (20):
* [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=nyu.a1liu.com
*  start date: Nov 25 03:27:01 2022 GMT
*  expire date: Feb 23 03:27:00 2023 GMT
*  subjectAltName: host "nyu.a1liu.com" matched cert's "nyu.a1liu.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):
* h2h3 [:method: HEAD]
* h2h3 [:path: /]
* h2h3 [:scheme: https]
* h2h3 [:authority: nyu.a1liu.com]
* h2h3 [user-agent: curl/7.87.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x7fd30b2a6a90)
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):
> HEAD / HTTP/2
> Host: nyu.a1liu.com
> user-agent: curl/7.87.0
> accept: */*
>
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 200
HTTP/2 200
< cache-control: max-age=0
cache-control: max-age=0
< date: Wed, 18 Jan 2023 17:23:43 GMT
date: Wed, 18 Jan 2023 17:23:43 GMT
< etag: W/"z5UTP/K38mEz5USukpV0II"
etag: W/"z5UTP/K38mEz5USukpV0II"
< content-length: 4179
content-length: 4179

<
* Connection #0 to host nyu.a1liu.com left intact
```

**Comment by mpl** [comment]
> As a note, other paths work, for example, https://nyu.a1liu.com/api works on safari as expected

Btw, the most likely reason why you're not seeing any problem on /api is because you have a redirect to http on that endpoint, so your browser actually ends up trying on http://nyu.a1liu.com/api , and as you said, you didn't see any problem with http.

```
$ curl -I https://nyu.a1liu.com/api
HTTP/2 302
cache-control: max-age=0
date: Wed, 18 Jan 2023 17:44:47 GMT
location: http://nyu.a1liu.com/api/
content-length: 0
```

**Comment by mpl** [comment]
finally, if you replace your whole schedge section in your docker compose, with a dumb server, like

```
  whoami:
    image: traefik/whoami
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.entrypoints: web
      traefik.http.routers.whoami.rule: Host(`nyu.a1liu.com`)
      traefik.http.routers.whoami-https.entrypoints: websecure
      traefik.http.routers.whoami-https.tls: true
      traefik.http.routers.whoami-https.rule: Host(`nyu.a1liu.com`)
      traefik.http.routers.whoami-https.tls.certresolver: mytlschallenge
```
then it looks like even with safari there is no problem (a coworker has a higher safari version, like yours, and tried for me).
So we're inclined to think there's something funky going on with schedge.
