### ISSUE TITLE
X-Forwarded-Tls-Client-Cert not encoded anymore in v2.9.4+

### ISSUE THREAD

**Issue by mlesaout** [traefik/traefik#9669]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Traefik is configured to pass the `X-Forwarded-Tls-Client-Cert`. 
* Service 
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:

  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      volumes:
      - name: certificate
        secret:
          secretName: whoami
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: whoami
        image: containous/whoami:latest
        args:
          - "--port"
          - "8080"
          - "--key"
          - "/certs/tls.key"
          - "--cert"
          - "/certs/tls.crt"
        volumeMounts:
        - name: certificate
          mountPath: /certs/
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: whoami
spec:
  selector:
    app: whoami
  ports:
  - port: 8080
    targetPort: 8080
```
* Ingress
```yaml 
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: requestclientcert
spec:
  clientAuth:
    clientAuthType: RequestClientCert
---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-servertransport
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: passtlsclientcert
spec:
  passTLSClientCert:
    pem: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`whoami.127.0.0.1.nip.io`) && PathPrefix(`/`)
    middlewares:
    - name: passtlsclientcert
    priority: 1
    services:
    - name: whoami
      port: 8080
      scheme: https
      serversTransport: insecure-servertransport
  tls:
    options:
      name: requestclientcert
    secretName: 127-0-0-1-nip-io
```
from v2.8 to v2.9.1, `X-Forwarded-Tls-Client-Cert` request value is url-encoded (with delimiters et `\n` removed)
```
X-Forwarded-Tls-Client-Cert: MII***O2%2FHx***k%2F***I%3D
```

### What did you see instead?

In v2.9.4, v2.9.5, v2.9.6,  `X-Forwarded-Tls-Client-Cert` request header is forwarded but its value doesn't seem to be url-encoded anymore
```
X-Forwarded-Tls-Client-Cert: MII***O2/Hx***k/***I=
```

### What version of Traefik are you using?

v2.8 to v2.9.6

### What is your environment & configuration?

```yaml
      --global.checknewversion
      --global.sendanonymoususage
      --entrypoints.metrics.address=:9100/tcp
      --entrypoints.traefik.address=:9000/tcp
      --entrypoints.web.address=:8000/tcp
      --entrypoints.websecure.address=:8443/tcp
      --api.dashboard=true
      --ping=true
      --metrics.prometheus=true
      --metrics.prometheus.entrypoint=metrics
      --providers.kubernetescrd
      --providers.kubernetescrd.allowCrossNamespace=true
      --providers.kubernetesingress
      --entrypoints.websecure.http.tls=true
      --accesslog=true
      --accesslog.fields.defaultmode=keep
      --accesslog.fields.headers.defaultmode=drop
      --api.insecure=true
      --providers.kubernetesingress.allowemptyservices=true
      --providers.kubernetesingress.allowexternalnameservices=true
      --providers.kubernetescrd.allowemptyservices=true
      --providers.kubernetescrd.allowexternalnameservices=true
      --log.level=DEBUG
```
