### ISSUE TITLE
Traefik access log ignoring some fields/headers settings in traefik-config.yaml (K3S)

### ISSUE THREAD

**Issue by mcordova1967** [traefik/traefik#9676]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

As recommended by the K3S docs, I edited /var/lib/rancher/k3s/server/manifests/traefik-config.yaml to enable access logs and configure fields and headers to keep or drop:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    logs:
      access:
        enabled: true
        fields:
          general:
            defaultmode: keep
            names:
              StartUTC: drop
              StartLocal: keep
              RouterName: drop
              ServiceURL: drop
              RequestCount: drop
              OriginDuration: keep
              ClientUsername: drop
          headers:
            defaultmode: keep
            names:
              Cookie: keep
              User-Agent: drop
              Referer: drop
```

It partially worked, not all drop|keep directives were respected.

I used these reference materials from Traefik, which I think are the most updated:

I am using these traefik references:
https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml#L147
https://doc.traefik.io/traefik/observability/access-logs/

### What did you see instead?

The configuration partially works, but:

Cookie header is not printed in log record.
StartLocal and OriginDuration fields are not printed in log record.
StartUTC is not being dropped, still printed.

### What version of Traefik are you using?

K3s Version: 
k3s version v1.25.5+k3s2 (de654222)
go version go1.19.4
rancher/mirrored-library-traefik:2.9.4

Cluster Configuration:
Single node installation with: 
```
curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -
```

### What is your environment & configuration?

The manifest installed by k3s:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik-crd
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-crd-20.3.1+up20.3.0.tgz
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-20.3.1+up20.3.0.tgz
  set:
    global.systemDefaultRegistry: ""
  valuesContent: |-
    logs:
      access:
        enabled: true
    podAnnotations:
      prometheus.io/port: "8082"
      prometheus.io/scrape: "true"
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    priorityClassName: "system-cluster-critical"
    image:
      name: "rancher/mirrored-library-traefik"
      tag: "2.9.4"
    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    service:
      ipFamilyPolicy: "PreferDualStack"

```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

This is a sample of the access logs obtained via kubectl:

kubectl logs -n kube-system $(kubectl get pod -n kube-system -o name | grep "^pod/traefik")

```
10.42.0.1 - - [27/Jan/2023:04:01:49 +0000] "POST /ms/login HTTP/2.0" 200 61 "-" "-" - "-" "-" 5ms
10.42.0.1 - - [27/Jan/2023:04:01:49 +0000] "GET /demo/menu.html HTTP/2.0" 200 1005 "-" "-" - "-" "-" 0ms
10.42.0.1 - - [27/Jan/2023:04:01:52 +0000] "GET /demo/products.html HTTP/2.0" 200 1923 "-" "-" - "-" "-" 1ms
10.42.0.1 - - [27/Jan/2023:04:01:52 +0000] "GET /ms/products/view HTTP/2.0" 200 11520 "-" "-" - "-" "-" 3ms
10.42.0.1 - - [27/Jan/2023:04:01:54 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" - "-" "-" 0ms
10.42.0.1 - - [27/Jan/2023:04:01:54 +0000] "GET /ping HTTP/1.1" 200 2 "-" "-" - "-" "-" 0ms
10.42.0.1 - - [27/Jan/2023:04:01:54 +0000] "GET /demo/menu.html HTTP/2.0" 200 1005 "-" "-" - "-" "-" 0ms
10.42.0.1 - - [27/Jan/2023:04:01:55 +0000] "GET /demo/shippers.html HTTP/2.0" 200 1612 "-" "-" - "-" "-" 0ms
10.42.0.1 - - [27/Jan/2023:04:01:55 +0000] "GET /ms/shippers/view HTTP/2.0" 200 456 "-" "-" - "-" "-" 2ms
10.42.0.1 - - [27/Jan/2023:04:01:56 +0000] "GET /demo/menu.html HTTP/2.0" 200 1005 "-" "-" - "-" "-" 1ms
10.42.0.1 - - [27/Jan/2023:04:01:57 +0000] "GET /demo/categ.html HTTP/2.0" 200 2332 "-" "-" - "-" "-" 0ms
10.42.0.1 - - [27/Jan/2023:04:01:57 +0000] "GET /ms/categ/view HTTP/2.0" 200 308 "-" "-" - "-" "-" 2ms
10.42.0.1 - - [27/Jan/2023:04:01:59 +0000] "GET /ms/categ/get?categ_id=49 HTTP/2.0" 200 58 "-" "-" - "-" "-" 3ms
10.42.0.1 - - [27/Jan/2023:04:01:59 +0000] "POST /ms/categ/update HTTP/2.0" 200 16 "-" "-" - "-" "-" 2ms
10.42.0.1 - - [27/Jan/2023:04:01:59 +0000] "GET /ms/categ/view HTTP/2.0" 200 308 "-" "-" - "-" "-" 1ms
10.42.0.1 - - [27/Jan/2023:04:02:01 +0000] "GET /ms/logout HTTP/2.0" 200 16 "-" "-" - "-" "-" 1ms
10.42.0.1 - - [27/Jan/2023:04:02:01 +0000] "GET /demo/index.html HTTP/2.0" 200 2314 "-" "-" - "-" "-" 1ms
```

**Comment by mpl** [comment]
Hello @mcordova1967 ,

I see two potential problems in your static conf that could be the reasons for your issues:

1) I never remember off the top of my head if case sensitivity matters in YAML, but if it does, then you you need `defaultMode` instead of `defaultmode` for both occurrences.

2) I don't think this `general` object right below your `fields` is legit.
the `defaultMode` and `names` should be direct children of the `fields` object , according to what I see on https://doc.traefik.io/traefik/observability/access-logs/#limiting-the-fieldsincluding-headers

**Comment by mcordova1967** [comment]
Hello @mpl, thanks for the reply, I used for reference their helm chart example:

[https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml](url)

```
  access:
    # To enable access logs
    enabled: false
    ## By default, logs are written using the Common Log Format (CLF) on stdout.
    ## To write logs in JSON, use json in the format option.
    ## If the given format is unsupported, the default (CLF) is used instead.
    # format: json
    # filePath: "/var/log/traefik/access.log
    ## To write the logs in an asynchronous fashion, specify a bufferingSize option.
    ## This option represents the number of log lines Traefik will keep in memory before writing
    ## them to the selected output. In some cases, this option can greatly help performances.
    # bufferingSize: 100
    ## Filtering https://docs.traefik.io/observability/access-logs/#filtering
    filters: {}
      # statuscodes: "200,300-302"
      # retryattempts: true
      # minduration: 10ms
    ## Fields
    ## https://docs.traefik.io/observability/access-logs/#limiting-the-fieldsincluding-headers
    fields:
      general:
        defaultmode: keep
        names: {}
          ## Examples:
          # ClientUsername: drop
      headers:
        defaultmode: drop
        names: {}
          ## Examples:
          # User-Agent: redact
          # Authorization: drop
          # Content-Type: keep

````

I wonder which docs are right?
