### ISSUE TITLE
There is no documentation about what Nomad permissions are required when using ACLs with the Nomad provider

### ISSUE THREAD

**Issue by regner** [traefik/traefik#9677]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Ran Traefik with the Nomad provider enabled pointing at a Nomad cluster that has ACLs enabled.

### What did you see instead?

```
time="2023-01-27T14:46:48Z" level=error msg="Provider connection error failed to load initial nomad services: Unexpected response code: 403 (Permission denied), retrying in 6.129399793s" providerName=nomad
```

### What version of Traefik are you using?

2.9.6

### What is your environment & configuration?

```yaml
providers:
  nomad:
    exposedByDefault: false
    endpoint:
      address: "http://{{ env "attr.unique.network.ip-address" }}:4646"
```
