### ISSUE TITLE
rabbitmq console 404

### ISSUE THREAD

**Issue by skylarkn** [traefik/traefik#9678]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I deployed minio and the console in K8S, used ClusterIP to expose ports 9000 & 5000

Listening for port 80 and 5000 forwarding requests to minio.service(ClusterIP)

Request console all right through port 5000

By requesting the console on port 80, you can see the console, but the request is 404 in the browser

### What did you see instead?

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/40782008/215121687-56510a25-ec10-4b74-98b3-772e6c18817f.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/40782008/215121745-25493a3d-0f6d-4c6e-8507-a21fe8d10e47.png">

### What version of Traefik are you using?

helm

### What is your environment & configuration?

```yaml

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: minio-headless
  labels:
    app: minio-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: server
      port: 9000
      targetPort: 9000
    - name: console
      port: 5000
      targetPort: 5000
  selector:
    app: minio
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route-minio
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - minio
    - web
  routes:
    - kind: Rule
      match: Host(`minio-console.{{ .Release.Namespace }}.k8s.zszc`)
      priority: 10
      services:
        - kind: Service
          name: minio-headless
          namespace: {{ .Release.Namespace }}
          port: 5000
          responseForwarding:
            flushInterval: 1ms
          scheme: http
          strategy: RoundRobin
          weight: 10
```

### If applicable, please paste the log output in DEBUG level

```json
{
  "ClientAddr": "192.168.4.250:55485",
  "ClientHost": "192.168.4.250",
  "ClientPort": "55485",
  "ClientUsername": "-",
  "DownstreamContentSize": 19,
  "DownstreamStatus": 404,
  "Duration": 688075,
  "OriginContentSize": 19,
  "OriginDuration": 169976,
  "OriginStatus": 404,
  "Overhead": 518099,
  "RequestAddr": "minio-console.etb-0-0-1.k8s.zszc",
  "RequestContentSize": 0,
  "RequestCount": 1018,
  "RequestHost": "minio-console.etb-0-0-1.k8s.zszc",
  "RequestMethod": "GET",
  "RequestPath": "/api/v1/login",
  "RequestPort": "-",
  "RequestProtocol": "HTTP/1.1",
  "RequestScheme": "http",
  "RetryAttempts": 0,
  "RouterName": "traefik-traefik-dashboard-6e26dcbaf28841493448@kubernetescrd",
  "StartLocal": "2023-01-27T13:20:06.337540015Z",
  "StartUTC": "2023-01-27T13:20:06.337540015Z",
  "entryPointName": "web",
  "level": "info",
  "msg": "",
  "time": "2023-01-27T13:20:06Z"
}
```
