### ISSUE TITLE
3.0.0-beta2 dashboard missing content type header --> html code as plain text in browser

### ISSUE THREAD

**Issue by Links2004** [traefik/traefik#9679]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

switch from traefik V2.9 to V3.0.

deployed via helm version 20.8.0
repo: https://traefik.github.io/charts

after the update the dashboard does not work any more.
from what I can see the Content type header is missing on the http/https response to the browser.

```
accept-ranges: bytes
content-length: 3124
date: Sat, 28 Jan 2023 11:03:55 GMT
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
```

### What did you see instead?

plan html code

![image](https://user-images.githubusercontent.com/974709/215263248-b492ba6f-116b-4cc1-af03-ced0abdefd99.png)

### What version of Traefik are you using?

Version:      3.0.0-beta2
Codename:     beaufort
Go version:   go1.19.4
Built:        2022-12-07T16:32:34Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security
  namespace: traefik
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    #HSTS
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
  namespace: traefik
spec:
  tls:
    secretName: traefik-tls
  routes:
    - match: Host(`traefik.demo.test`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
      middlewares:
        - name: security
          namespace: traefik
```
