### ISSUE TITLE
Certificate renewal and generation fails for wildcard domain using gandiv5 DNS challenge

### ISSUE THREAD

**Issue by Lefuneste83** [traefik/traefik#9680]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Upgrading from docker image for Traefik 2.9.1 to 2.9.4 and subsequent (bringing lego 4.9.0+).
I am unable to process a cert renewal (wildcard gandiv5 dns challenge) with the following error :

`time="2023-01-28T17:13:58+01:00" level=error msg="Error renewing certificate from LE: {subdomain.domain.name [*.subdomain.domain.name]}" providerName=letsencrypt.acme error="error: one or more domains had a problem:\n[*.subdomain.domain.name] [*.subdomain.domain.name] acme: error presenting token: gandiv5: unexpected authZone domain.name. for fqdn domain.name.\n[subdomain.domain.name] [subdomain.domain.name] acme: error presenting token: gandiv5: unexpected authZone domain.name. for fqdn domain.name.\n" ACME CA="https://acme-v02.api.letsencrypt.org/directory"`

### What did you see instead?

The issue seems related to the packaged lego component from version 4.9.0 brought with Traefik 2.9.4 and subsequent.

Since [v4.9.0](https://github.com/go-acme/lego/releases/tag/v4.9.0) lego follows CNAME as expected by the ACME, see https://letsencrypt.org/2019/10/09/onboarding-your-customers-with-lets-encrypt-and-acme.html#the-advantages-of-a-cname

In order to allow certificate generation or renewal in such a case, one must add the following to the Traefik docker definition file : 

`      - LEGO_DISABLE_CNAME_SUPPORT=true`

### What version of Traefik are you using?

2.9.6

### What is your environment & configuration?

```yaml

    environment:
      - GANDIV5_API_KEY=APIKEYGOESHERE
    
    labels:
      - "traefik.http.routers.traefik-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=subdomain.domain.name"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.subdomain.domain.name"
```

Add more configuration information here.
traefik.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: emacron@gmail.com
      storage: /acme.json
      dnsChallenge:
        provider: gandiv5
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
