### ISSUE TITLE
HTTPRoute wildcard hostname precedence doesn't match spec

### ISSUE THREAD

**Issue by pl4nty** [traefik/traefik#9681]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I've deployed two HTTPRoutes, one with a wildcard hostname (*.tplant.au) and one specific (myhost.tplant.au). The second route should take precedence per the [Gateway API spec](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io%2fv1alpha2.HTTPRoute), and did when implemented with the https://github.com/nginxinc/nginx-kubernetes-gateway GatewayClass.

### What did you see instead?

The wildcard route took precedence over the specific route, and traffic only flowed to it.

### What version of Traefik are you using?

2.9.6 via the official Helm chart (20.8.0)

### What is your environment & configuration?

https://github.com/pl4nty/lab-infra/blob/main/kubernetes/base/networking/traefik/traefik.yaml

**Comment by rtribotte** [comment]
Hello @pl4nty,

You are right about the precedence that should apply and this is indeed the default behavior in Traefik, but it applies only when evaluating two routes/routers against each other. After double-checking the code base, it seems that the current implementation satisfies the expected behavior from the Gateway API Spec.

In the referenced [commit](https://github.com/pl4nty/lab-infra/commit/bd678d4abb9e94eeab1a72fd15c61c357e82f772), it seems that the two hostnames were defined on the same route, which would have produced only one router in Traefik, with a host rule combining the two hostnames. Which could explain the behavior you have experienced.

As a side note, the hostnames in the configuration in the referenced commit do not match the example you provided (i.e.: `*.tplant.au` and `myhost.tplant.au`).

We are closing this issue, but feel free to ask to re-open it if you think we are missing something. In such a case, could you please share the HTTPRoute/s definition/s?

**Comment by pl4nty** [comment]
@rtribotte thanks for the reply. The referenced commit was my workaround by removing the wildcard route, since the wildcard route was overriding other routes that I wanted to use. The examples are:

```yaml
Name:         home-assistant
Namespace:    default
Labels:       app.kubernetes.io/instance=home-assistant
              app.kubernetes.io/name=home-assistant
API Version:  gateway.networking.k8s.io/v1alpha2
Kind:         HTTPRoute
Spec:
  Hostnames:
    home-assistant.tplant.au
  Parent Refs:
    Group:      gateway.networking.k8s.io
    Kind:       Gateway
    Name:       traefik-gateway
    Namespace:  default
  Rules:
    Backend Refs:
      Group:
      Kind:       Service
      Name:       home-assistant
      Namespace:  default
      Port:       8123
      Weight:     1
    Matches:
      Path:
        Type:   PathPrefix
        Value:  /
```

```yaml
Name:         well-known
Namespace:    default
Labels:       app.kubernetes.io/instance=well-known
              app.kubernetes.io/name=well-known
API Version:  gateway.networking.k8s.io/v1alpha2
Kind:         HTTPRoute
Spec:
  Hostnames:
    *.tplant.au
    tplant.au
  Parent Refs:
    Group:      gateway.networking.k8s.io
    Kind:       Gateway
    Name:       traefik-gateway
    Namespace:  default
  Rules:
    Backend Refs:
      Group:
      Kind:       Service
      Name:       well-known
      Namespace:  default
      Port:       80
      Weight:     1
    Matches:
      Path:
        Type:   PathPrefix
        Value:  /
```

In this instance, all traffic was routed to `well-known`, and `home-assistant` was unreachable.
