### ISSUE TITLE
RedirectRegex returning gibberish in AWS ECS(Fargate)

### ISSUE THREAD

**Issue by BogdanNic** [traefik/traefik#9686]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I created and deployed a traefik service into AWS ECS(Fargate) to help me with some regex redirects based on the path. The basic idea I sent it a url and traefik should parse the url get the regex group and then redirect to a new path based on a specific regex group.

### What did you see instead?

Instead of the showing the regex groups and replacing them it shows the first group as `$%7B1%7D`

### What version of Traefik are you using?

2.8.8 but also 2.9

### What is your environment & configuration?

```yaml
version: '3'

services:
  traefik:
    image: traefik:v2.9
    command:
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    environment:
      - TRAEFIK_PING=true
      - TRAEFIK_PING_ENTRYPOINT=web
      - TRAEFIK_ENTRYPOINTS_WEB=true
      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=":80"
      - TRAEFIK_LOG_LEVEL=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.redirect-router.entrypoints=web"
      - "traefik.http.routers.redirect-router.rule=Host(`myserver`)"
      - "traefik.http.routers.redirect-router.middlewares=redirect-regex"
      - "traefik.http.middlewares.redirect-regex.redirectregex.regex=^http://myserver/test-(.*)-mytest"
      - "traefik.http.middlewares.redirect-regex.redirectregex.replacement=http://myserver/test2-$${1}-mytest2"
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

Not error showed.
