### ISSUE TITLE
Traefik reuses connection for different router and service

### ISSUE THREAD

**Issue by ginuerzh** [traefik/traefik#9688]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have a reverse proxy with single entry point port 8000 and two backend services (service-1, service-2), the reverse proxy routes traffic based on the host name(s1.example.com to service-1, s2.example.com to service-2), **BUT the routing only happened when a new connection is established**.

I configure two separated routers and services (ingress-0, ingress-1), see the configuration below.

### What did you see instead?

When I issue an HTTP request to s1.example.com (http://s1.example.com), a new connection to reverse proxy :8000 established, the routing is as expected.

When I issue an HTTP request to s2.example.com (http://s2.example.com) again, it reuses the last connection to s1.example.com, and the routing not happening. 

I think the connection should not be reused between different routers.

### What version of Traefik are you using?

Version:      2.9.6
Codename:     banon
Go version:   go1.19.4
Built:        2022-12-07T14:17:58Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
version: '3'

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.9.6
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    ports:
      # The HTTP port
      - "80:80"
    volumes:
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  reverse-proxy: 
    image: image/name
    labels:
      - "traefik.http.routers.ingress-0.rule=Host(`s1.example.com`)"
      - "traefik.http.routers.ingress-0.service=ingress-0"
      - "traefik.http.services.ingress-0.loadbalancer.server.port=8000"
      - "traefik.http.routers.ingress-1.rule=Host(`s2.example.com`)"
      - "traefik.http.routers.ingress-1.service=ingress-1"
      - "traefik.http.services.ingress-1.loadbalancer.server.port=8000"
```

**Comment by mpl** [comment]
Hello @ginuerzh 

Are you talking about the connection between the client and traefik? If yes, reuse of the connection is then expected (and desired, in most cases). But in any case, I would think that it is irrelevant, and your problem might come from something else.

When you say that the routing to s2.example.com is not happening, what is the observed behaviour exactly? Do you get a 404, or does the request go to s1 instead? Or something else?

Can you please enable debug level and provide the traefik logs at the moment of the observed behaviour? Are you able to reproduce with a command line client such as curl? If yes, can you show us the commands that you're using?

**Comment by gdonoso94** [comment]
Hi, I'm encountering a similiar issue with my setup and the same Traefik version. 

These are the two IngressRoutes I have

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "toolbox.fullname" . }}-web
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ include "toolbox.fullname" . }}.{{ .Values.env.ENVIRONMENT }}.domain`)
      kind: Rule
      services:
        - name: {{ include "toolbox.fullname" . }}
          port: http
      middlewares:
        - name: cors


---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "toolbox.fullname" . }}-websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ include "toolbox.fullname" . }}.{{ .Values.env.ENVIRONMENT }}.domain`)
      kind: Rule
      services:
        - name: {{ include "toolbox.fullname" . }}
          port: http
      middlewares:
        - name: cors
```

(toolbox is the app name)
I also have global redirection setup and, when I call my service I can see how the request is being redirected:

```
│ 10.60.20.204 - - [07/Feb/2023:20:04:03 +0000] "GET /files/jejeje HTTP/1.1" 301 17 "-" "-" 4 "web-to-websecure@internal" "-" 0ms                          │
```

But it gets stuck there and nothing else happens. It's like something changes in the connection and then it is unable to match the host and therefore is not calling my backend.

Here are the cURL logs:

```
❯ curl http://service.url/files/jejeje -v -L -k
*   Trying xxxx:80...
* Connected to service.url (xxxx) port 80 (#0)
> GET /files/jejeje HTTP/1.1
> Host: this-is-the-correct-host
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Location: https://service.url/files/jejeje
< Date: Tue, 07 Feb 2023 20:04:03 GMT
< Content-Length: 17
< Content-Type: text/plain; charset=utf-8
<
* Ignoring the response-body
* Connection #0 to host service.url left intact
* Issue another request to this URL: 'https://service.url/files/jejeje'
*   Trying xxxx:443...
* Connected to service.url (xxxx) port 443 (#1)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.xxxxxxxx
*  start date: Dec  7 00:00:00 2022 GMT
*  expire date: Jan  5 23:59:59 2024 GMT
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M01
*  SSL certificate verify ok.
> GET /files/jejeje HTTP/1.1
> Host: this-is-the-correct-host-too
> User-Agent: curl/7.79.1
> Accept: */*
>
* TLSv1.2 (IN), TLS alert, close notify (256):
* Empty reply from server
* Closing connection 1
* TLSv1.2 (OUT), TLS alert, close notify (256):
curl: (52) Empty reply from server
```

In another setup, adding a middleware that redirects to https, what I get is a 404 via https while I can reach the service via http (removing the middleware, of course)

I have another service with the very same setup but using Traefik 2.5.6 and it works as expected. 

Can I get some help here? #9359 
Thanks in advance
