### ISSUE TITLE
The log reports an error, but the function is normal.

### ISSUE THREAD

**Issue by Narcissus666** [traefik/traefik#9691]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I configure dynamic file during runtime.
Dynamic file is below:
```yaml
http:

  routers:
    dashboard-http:
      rule: "Host(`xxxx:xxxx::xx``)"  # xxxx:xxxx::xx is an IPv6 address
      service: service
      entryPoints:
        - web
      middlewares:
        - redirect-https
      priority: 1

    dashboard-https:
      entryPoints:
        - websecure
      rule: "Host(`xxxx:xxxx::xx`)" # xxxx:xxxx::xx is an IPv6 address
      service: service
      priority: 1
      tls: {}

  services:
    service:
      loadBalancer:
        servers:
          - url: "https://xxx.xx.xxx.xx:xxxxx" # xxx.xx.xxx.xx:xxxxx is an IPv4 address + port
```

The log will report an error：time="2023-02-02T16:45:18+08:00" level=error msg="Error while adding route for host: invalid value for \"HostSNI\" matcher, \"xxxx:xxxx::xx\" is not a valid hostname".However, the agent function can work normally.

This error should not occur under normal circumstances.

### What did you see instead?

The log will report an error：time="2023-02-02T16:45:18+08:00" level=error msg="Error while adding route for host: invalid value for \"HostSNI\" matcher, \"xxxx:xxxx::xx\" is not a valid hostname".

### What version of Traefik are you using?

v2.9.6 （I tested it on a physical machine）

### What is your environment & configuration?

```yaml
http:

  routers:
    dashboard-http:
      rule: "Host(`xxxx:xxxx::xx``)"  # xxxx:xxxx::xx is an IPv6 address
      service: service
      entryPoints:
        - web
      middlewares:
        - redirect-https
      priority: 1

    dashboard-https:
      entryPoints:
        - websecure
      rule: "Host(`xxxx:xxxx::xx`)" # xxxx:xxxx::xx is an IPv6 address
      service: service
      priority: 1
      tls: {}

  services:
    service:
      loadBalancer:
        servers:
          - url: "https://xxx.xx.xxx.xx:xxxxx" # xxx.xx.xxx.xx:xxxxx is an IPv4 address + port

# middlewares
http:
  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
        permanent: true
```

Add more configuration information here.

```yaml
api:
  debug: true
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"


providers:
  file:
    directory: /etc/traefik/configurations/

log:
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log
  bufferingSize: 100
  fields:
    names:
      StartLocal: keep
      StaartUTC: drop

serversTransport:
  insecureSkipVerify: true
```

### If applicable, please paste the log output in DEBUG level

```json
time="2023-02-02T17:17:04+08:00" level=debug msg="Creating middleware" middlewareType=Recovery entryPointName=websecure middlewareName=traefik-internal-recovery
time="2023-02-02T17:17:04+08:00" level=debug msg="Adding route for xxxx:xxxx::xx with TLS options default" entryPointName=websecure
time="2023-02-02T17:17:04+08:00" level=error msg="Error while adding route for host: invalid value for \"HostSNI\" matcher, \"xxxx:xxxx::xx\" is not a valid hostname"
time="2023-02-02T17:17:06+08:00" level=debug msg="Configuration received: {\"http\":{\"routers\":{\"dashboard-http\":{\"entryPoints\":[\"web\"],\"middlewares\":[\"redirect-https\"],\"service\":\"service\",\"rule\":\"Host(`xxxx:xxxx::xx`)\",\"priority\":1},\"dashboard-https\":{\"entryPoints\":[\"websecure\"],\"service\":\"service\",\"rule\":\"Host(`xxxx:xxxx::xx`)\",\"priority\":1,\"tls\":{}}},\"services\":{\"k8s-service\":{\"loadBalancer\":{\"servers\":[{\"url\":\"https://xxx.xx.xxx.xx:xxxxx\"}],\"passHostHeader\":true}}},\"middlewares\":{\"redirect-https\":{\"redirectScheme\":{\"scheme\":\"https\",\"permanent\":true}}}},\"tcp\":{},\"udp\":{},\"tls\":{}}" providerName=file
time="2023-02-02T17:17:06+08:00" level=debug msg="Skipping unchanged configuration." providerName=file
```
