### ISSUE TITLE
Bug: Getting error "middleware does not exist"

### ISSUE THREAD

**Issue by rikeshpatel14** [traefik/traefik#9703]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

**Team** - Am trying to create an HTTP replacePath middleware available in Traefik (v2.8.1) with Kubernetes (v1.21) by following the documentation for replacePath middleware at https://doc.traefik.io/traefik/middlewares/http/replacepath. Steps followed:

1. Create a CRD for the replacePath middleware
2. Create replacePath middleware
3. Update Ingress resource and add the Traefik middleware annotation 

The manifest details are shared below

Am able to access the backend service directly through curl as per below:
```
curl http://<backend-service-ip>:<port>/api/v1/dummy-path -H 'Content-Type: application/json' -H 'X-Replaced-Path: /1234/test-path' -d '[{"key":{"tweetId":"100"},"data":{"tweet":"The new augmented reality is ground breaking!!","author":"dummy"},"metadata":{},"version":"1.0"}]'
{"status":true}
```

### What did you see instead?

When trying to access the service through Ingress (kube-apiserver) getting "HTTP 404" as shown below:
```
curl http://<kube-api-server>/1234/test-path -H 'Content-Type: application/json' -d '[{"key":{"tweetId":"100"},"data":{"tweet":"The new augmented reality is ground breaking!!","author":"dummy"},"metadata":{},"version":"1.0"}]'
404 page not found
```

Observed the below error message in Traefik logs
`middleware \"2765-dataflow-ns-mw-admin@kubernetescrd\" does not exist`

### What version of Traefik are you using?

Traefik version 2.8.1 and Kubernetes version 1.21

### What is your environment & configuration?

CRD Manifest

```
---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: middlewares.traefik.containo.us
spec:
  group: traefik.containo.us
  names:
    kind: Middleware
    plural: middlewares
    singular: middleware
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Middleware is the Schema for Traefik HTTP Middleware replacePath
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase'
            type: string
          metadata:
            type: object
          spec:
            description: HttpReplacePathSpec defines the desired state of HttpReplacePathMiddleware
            properties:
              replacePath:
                description: 'Updates the Path Before Forwarding the Request to Backend'
                properties:
                  path:
                    description: 'Replace the actual path with the specified one'
                    type: string
                required:
                - path
                type: object
            type: object
        type: object
    served: true
    storage: true
```

Middleware Manifest

```
---

apiVersion: traefik.containo.us/v1
kind: Middleware
metadata:
  name: replacepathmw
  namespace: mw-ns
spec:
  replacePath:
    path: /api/v1/dummy-path
```

Ingress Manifest

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: http
    traefik.ingress.kubernetes.io/router.middlewares: mw-ns-replacepathmw@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "false"
  name: traefik-ingress
  namespace: ingress-ns
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: backend-service
            port:
              number: 80
        path: /1234/test-path
        pathType: Prefix
```

### If applicable, please paste the log output in DEBUG level

`level=error msg="middleware \"mw-ns-replacepathmw@kubernetescrd\" does not exist" entryPointName=http routerName=***@kubernetes`
