### ISSUE TITLE
High CPU and memory with v2.9.6 and docker swarm mode

### ISSUE THREAD

**Issue by yorickdowne** [traefik/traefik#9707]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We are seeing maxed CPU and memory on a docker swarm node when running traefik v2.9.6. This is intermittent and doesn't "always" happen. Usual load is ~25%; when this happens we max both CPUs.

Symptoms were max CPU and memory on the manager node hosting traefik. The node would then fail, traefik would be started on another manager, and cause that one to fail, and so on.

Info level logs were uninstructive.

We can deliberately break this again very briefly to help find the issue. Please guide us as to which log level would be most helpful, and what other data we might gather for you.

### What did you see instead?

CPU and memory maxed

### What version of Traefik are you using?

v2.9.6

### What is your environment & configuration?

```yaml
  traefik:
    image: "traefik:latest"
    command:
      - --providers.docker.swarmmode
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=public
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.transport.respondingTimeouts.idleTimeout=15m
      #- --api
      #- --log.level=debug
      #- --accesslog
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CF_API_TOKEN}
    ports:
      - "443:443/tcp"
    networks:
      - public
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - certs:/letsencrypt
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: ["node.labels.running_cfddns == 1","node.role == manager"]
    <<: *logging
```

Running as one replica in a docker swarm mode, docker version `20.10.22`, three manager nodes and three worker nodes.
