### ISSUE TITLE
Traefik cannot process CONNECT http request method.

### ISSUE THREAD

**Issue by OrvilleQ** [traefik/traefik#9708]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I was trying to deploy an applications which need [`CONNECT`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT) http request method to work, using Traefik as it's TLS layer and reverse proxy. 

The application expose h2c on port 8080, and I was using this IngressRoute:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: h2c
  namespace: applications
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`www.example.com`)
    kind: Rule
    services:
    - name: h2c
      kind: Service
      port: 8080
      scheme: h2c
  tls:
    secretName: com-example-www
``

### What did you see instead?

1. If I `PUT` or `GET` the server, I'll see that the traffic been redirect to the application I deployed and the application reported a bug since it require `CONNECT` to work.

Log from Traefik:
```
time="2023-02-11T13:11:50Z" level=debug msg="'502 Bad Gateway' caused by: read tcp 10.244.3.203:59980->10.244.3.36:8080: read: connection reset by peer"
[IPADDRESS] - - [11/Feb/2023:13:11:50 +0000] "GET / HTTP/2.0" 502 11 "-" "-" 18553 "applications-h2c-9a98d4be767ad3f49819@kubernetescrd" "h2c://10.244.3.36:8080" 5ms
```

Log from the application:
```
+0000 2023-02-11 13:11:50 ERROR [1313487149]: process connection from 10.244.3.203:59980: not CONNECT request
```

2. If I `CONNECT` the server, I'll see that the traffic been dropped to nowhere.

Log form Traefik:
```
[IPADDRESS] - - [11/Feb/2023:13:14:02 +0000] "CONNECT - HTTP/2.0" 404 19 "-" "-" 18580 "-" "-" 0ms
[IPADDRESS] - - [11/Feb/2023:13:14:02 +0000] "CONNECT - HTTP/2.0" 404 19 "-" "-" 18581 "-" "-" 0ms
```

no log from the application.

3. If I add ```Method(`CONNECT`)``` to the `match` section following suggestion from [here](https://community.traefik.io/t/proxmox-behind-traefik/9338/2) , `PUT` or `GET` will get 405 but `CONNECT` still got dropped.

Rule:
```
  - match: Host(`cell.anislet.dev`) && Method(`CONNECT`)
```

Log from Traefik:
```
[IPADDRESS] - - [11/Feb/2023:13:16:57 +0000] "GET / HTTP/2.0" 405 0 "-" "-" 18618 "-" "-" 0ms
[IPADDRESS] - - [11/Feb/2023:13:17:04 +0000] "CONNECT - HTTP/2.0" 404 19 "-" "-" 18619 "-" "-" 0ms
[IPADDRESS] - - [11/Feb/2023:13:17:04 +0000] "CONNECT - HTTP/2.0" 404 19 "-" "-" 18620 "-" "-" 0ms
```

### What version of Traefik are you using?

```
Version:      2.9.6
Codename:     banon
Go version:   go1.19.4
Built:        2022-12-07T14:17:58Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

Traefik helm chart with default values on k3s v1.26.1+k3s1 using cilium and metallb.

### If applicable, please paste the log output in DEBUG level

See above.
