### ISSUE TITLE
Traefik doesn't respect the `X-Forwarded-Host` header in `Host` rules

### ISSUE THREAD

**Issue by mavolin** [traefik/traefik#9712]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I currently have an Apache web server running on Port 80/443, which is serving some PHP/HTML sites for different (sub-) domains.
Since I also have some other web apps that I'm running in containers, my plan was to connect them all to a Traefik container, so that instead of assigning each of my containers a static IP (and having to keep track of those), I would have just one static IP: The Traefik container. 

Then in Apache, I could just set up a reverse proxy to Traefik's IP (instead of the individual container ones) for all (sub-) domains that use a container, and Traefik would route/proxy to the correct container based on the host.

For that I configured Traefik like so:
```yaml
entryPoints:
  web:
    address: :80
    forwardedHeaders:
      insecure: true
```

Then I configured one of my container to use the Traefik container's network and added the following labels:
```yaml
traefik.enable: true
traefik.http.routers.ji.entrypoints: web
traefik.http.routers.ji.rule: Host(`intra.domain.de`)
traefik.http.services.ji.loadbalancer.server.port: 8080
```

Lastly, I configured Apache to proxy requests for `intra.domain.de` to Traefik's IP.

### What did you see instead?

Instead of seeing my container's web interface when accessing `intra.domain.de`, Traefik (not Apache) showed me a 404.

This is an excerpt of an access log entry for one of those 404s:

```json
{
  "ClientAddr": "172.20.0.1:41196",
  "ClientHost": "myIP",
  "ClientPort": "41196",
  "RequestAddr": "172.20.255.254",
  "RequestHost": "172.20.255.254",
  "RequestMethod": "GET",
  "RequestPath": "/",
  "RequestPort": "-",
  "RequestProtocol": "HTTP/1.1",
  "RequestScheme": "http",
  "entryPointName": "web",
  "request_X-Forwarded-For": "myIP",
  "request_X-Forwarded-Host": "intra.domain.de",
  "request_X-Forwarded-Port": "80",
  "request_X-Forwarded-Proto": "http",
  "request_X-Forwarded-Server": "99aede28d19a",
  "request_X-Real-Ip": "172.20.0.1"
}
```

This is surprising to me, since I set
```yaml
forwardedHeaders:
  insecure: true
```
which according to the docs "configure[s] Traefik to trust the forwarded headers information", and should therefore use `X-Forwarded-Hosts` for the `Host` rule instead of the `Host` header set by Apache, as seen in the log above.

### What version of Traefik are you using?

```
Version:      2.8.8
Codename:     vacherin
Go version:   go1.19.1
Built:        2022-09-30T12:20:13Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

`/etc/traefik/traefik.yml`
```yaml
accessLog:
  format: json
  fields:
    headers:
      defaultMode: keep

log:
  level: DEBUG

global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
    forwardedHeaders:
      insecure: true

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    network: traefik
```

`traefik/docker-compose.yml`
```yaml
networks:
  traefik:
    external: true

services:
  traefik:
    container_name: traefik
    image: traefik:v2.8
    restart: always
    networks:
      traefik:
        ipv4_address: 172.20.255.254
    volumes:
      - /etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

`someservice/docker-compose.yml`
```yaml
name: some-prefix

networks:
  some-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.32/28
  traefik:
    external: true

services:
  some-service:
    image: some-image:latest
    user: "${UID}:${GID}"
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      some-network:
        ipv4_address: 172.28.0.46
      traefik:
    volumes:
      - ./assets:/assets:ro
    labels:
      traefik.enable: true
      traefik.http.routers.ji.entrypoints: web
      traefik.http.routers.ji.rule: Host(`intra.domain.de`)
      traefik.http.services.ji.loadbalancer.server.port: 8080

    env_file: .env
    environment:
      # ...

  mysql:
    # ...
```

### If applicable, please paste the log output in DEBUG level

```
time="2023-02-14T09:09:41Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
time="2023-02-14T09:09:41Z" level=info msg="Traefik version 2.8.8 built on 2022-09-30T12:20:13Z"
time="2023-02-14T09:09:41Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"web\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{\"insecure\":true},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"network\":\"traefik\",\"swarmModeRefreshSeconds\":\"15s\"}},\"api\":{\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"accessLog\":{\"format\":\"json\",\"filters\":{},\"fields\":{\"defaultMode\":\"keep\",\"headers\":{\"defaultMode\":\"keep\"}}},\"pilot\":{\"dashboard\":true}}"
time="2023-02-14T09:09:41Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
time="2023-02-14T09:09:41Z" level=warning msg="Traefik Pilot is deprecated and will be removed soon. Please check our Blog for migration instructions later this year."
time="2023-02-14T09:09:41Z" level=info msg="Starting provider aggregator aggregator.ProviderAggregator"
time="2023-02-14T09:09:41Z" level=debug msg="Starting TCP Server" entryPointName=web
time="2023-02-14T09:09:41Z" level=info msg="Starting provider *traefik.Provider"
time="2023-02-14T09:09:41Z" level=debug msg="*traefik.Provider provider configuration: {}"
time="2023-02-14T09:09:41Z" level=info msg="Starting provider *docker.Provider"
time="2023-02-14T09:09:41Z" level=info msg="Starting provider *acme.ChallengeTLSALPN"
time="2023-02-14T09:09:41Z" level=debug msg="*acme.ChallengeTLSALPN provider configuration: {}"
time="2023-02-14T09:09:41Z" level=debug msg="*docker.Provider provider configuration: {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"network\":\"traefik\",\"swarmModeRefreshSeconds\":\"15s\"}"
time="2023-02-14T09:09:41Z" level=debug msg="Configuration received: {\"http\":{\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{}},\"serversTransports\":{\"default\":{\"maxIdleConnsPerHost\":200}}},\"tcp\":{},\"udp\":{},\"tls\":{}}" providerName=internal
time="2023-02-14T09:09:41Z" level=debug msg="No default certificate, generating one" tlsStoreName=default
time="2023-02-14T09:09:41Z" level=debug msg="Provider connection established with docker 23.0.0 (API 1.42)" providerName=docker
time="2023-02-14T09:09:41Z" level=debug msg="Filtering disabled container" providerName=docker container=traefik-traefik-99aede28d19ab2f0913006bccd360531545b4e071eec719b402cbb23eea143e0
time="2023-02-14T09:09:41Z" level=debug msg="Filtering disabled container" providerName=docker container=unrelated-container-c945033fddc4b4e407cd3204442d0b1a5a62fda6d4c1f6425bac4bf2364fcffc
time="2023-02-14T09:09:41Z" level=debug msg="Filtering disabled container" providerName=docker container=unrelated-container-b8edf405d4c6179aeb75fd26405e5aa437df5981f7799455337a5acf31edba76
time="2023-02-14T09:09:41Z" level=debug msg="Filtering disabled container" providerName=docker container=unrelated-container-277e0a26325b9cbe1e7b53eaeab60b363e5e99519ecc1f1b751894c8d31b40be
time="2023-02-14T09:09:41Z" level=debug msg="Filtering disabled container" providerName=docker container=unrelated-container-a718fd41eb706fe3858f87f98a28476cfd594c54df8047fb9a342aa718a59807
time="2023-02-14T09:09:41Z" level=debug msg="Filtering disabled container" providerName=docker container=unrelated-container-bf73a4c8294736139ead762a8b487578a71c3ca833fc7df525fc63bb17625b0c
time="2023-02-14T09:09:41Z" level=debug msg="Filtering disabled container" providerName=docker container=unrelated-container-a395725a6b77197290e5ee4b0019503627678f1cb0793d4cf1b01e0c420f2558
time="2023-02-14T09:09:41Z" level=debug msg="Filtering disabled container" providerName=docker container=unrelated-container-2cbc65fdeed98ef4b914ad914e7ed100f2a71ae34067877035c0fc9fd6119792
time="2023-02-14T09:09:41Z" level=debug msg="Filtering disabled container" container=unrelated-container-1c3c18360f5f775a606755f11c2b81f26e1963689d654ea50e42d4e4de2d3e1b providerName=docker
time="2023-02-14T09:09:41Z" level=debug msg="Configuration received: {\"http\":{\"routers\":{\"ji\":{\"entryPoints\":[\"web\"],\"service\":\"ji\",\"rule\":\"Host(`intra.domain.de`)\"}},\"services\":{\"ji\":{\"loadBalancer\":{\"servers\":[{\"url\":\"http://172.20.0.2:8080\"}],\"passHostHeader\":true}}}},\"tcp\":{},\"udp\":{}}" providerName=docker
time="2023-02-14T09:09:41Z" level=debug msg="No default certificate, generating one" tlsStoreName=default
time="2023-02-14T09:09:41Z" level=debug msg="Creating middleware" entryPointName=web routerName=ji@docker serviceName=ji middlewareName=pipelining middlewareType=Pipelining
time="2023-02-14T09:09:41Z" level=debug msg="Creating load-balancer" routerName=ji@docker serviceName=ji entryPointName=web
time="2023-02-14T09:09:41Z" level=debug msg="Creating server 0 http://172.20.0.2:8080" serviceName=ji serverName=0 entryPointName=web routerName=ji@docker
time="2023-02-14T09:09:41Z" level=debug msg="child http://172.20.0.2:8080 now UP"
time="2023-02-14T09:09:41Z" level=debug msg="Propagating new UP status"
time="2023-02-14T09:09:41Z" level=debug msg="Added outgoing tracing middleware ji" middlewareName=tracing middlewareType=TracingForwarder entryPointName=web routerName=ji@docker
time="2023-02-14T09:09:41Z" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=web
{"ClientAddr":"172.20.0.1:41196","ClientHost":"myIP","ClientPort":"41196","ClientUsername":"-","DownstreamContentSize":19,"DownstreamStatus":404,"Duration":39010,"OriginContentSize":19,"OriginDuration":16267,"OriginStatus":404,"Overhead":22743,"RequestAddr":"172.20.255.254","RequestContentSize":0,"RequestCount":1,"RequestHost":"172.20.255.254","RequestMethod":"GET","RequestPath":"/","RequestPort":"-","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"StartLocal":"2023-02-14T09:10:09.664016066Z","StartUTC":"2023-02-14T09:10:09.664016066Z","downstream_Content-Type":"text/plain; charset=utf-8","downstream_X-Content-Type-Options":"nosniff","entryPointName":"web","level":"info","msg":"","origin_Content-Type":"text/plain; charset=utf-8","origin_X-Content-Type-Options":"nosniff","request_Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8","request_Accept-Encoding":"gzip, deflate","request_Accept-Language":"en-GB,en;q=0.7","request_Connection":"close","request_Cookie":"flash=MTY3NjMwMTY0MHxEdi1EQkFFQ180UUFBUkFCRUFBQUJQLUVBQUE9fFv07Pz9rOXkf8LTDtMG4V5eCWsNmrfTqRWCfmFemofv","request_Sec-Gpc":"1","request_Upgrade-Insecure-Requests":"1","request_User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36","request_X-Forwarded-For":"myIP","request_X-Forwarded-Host":"intra.domain.de","request_X-Forwarded-Port":"80","request_X-Forwarded-Proto":"http","request_X-Forwarded-Server":"99aede28d19a","request_X-Real-Ip":"172.20.0.1","time":"2023-02-14T09:10:09Z"}
{"ClientAddr":"172.20.0.1:54684","ClientHost":"myIP","ClientPort":"54684","ClientUsername":"-","DownstreamContentSize":19,"DownstreamStatus":404,"Duration":21848,"OriginContentSize":19,"OriginDuration":6130,"OriginStatus":404,"Overhead":15718,"RequestAddr":"172.20.255.254","RequestContentSize":0,"RequestCount":2,"RequestHost":"172.20.255.254","RequestMethod":"GET","RequestPath":"/favicon.ico","RequestPort":"-","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"StartLocal":"2023-02-14T09:10:09.81294225Z","StartUTC":"2023-02-14T09:10:09.81294225Z","downstream_Content-Type":"text/plain; charset=utf-8","downstream_X-Content-Type-Options":"nosniff","entryPointName":"web","level":"info","msg":"","origin_Content-Type":"text/plain; charset=utf-8","origin_X-Content-Type-Options":"nosniff","request_Accept":"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8","request_Accept-Encoding":"gzip, deflate","request_Accept-Language":"en-GB,en;q=0.7","request_Connection":"close","request_Cookie":"flash=MTY3NjMwMTY0MHxEdi1EQkFFQ180UUFBUkFCRUFBQUJQLUVBQUE9fFv07Pz9rOXkf8LTDtMG4V5eCWsNmrfTqRWCfmFemofv","request_Referer":"http://intra.domain.de/","request_Sec-Gpc":"1","request_User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36","request_X-Forwarded-For":"myIP","request_X-Forwarded-Host":"intra.domain.de","request_X-Forwarded-Port":"80","request_X-Forwarded-Proto":"http","request_X-Forwarded-Server":"99aede28d19a","request_X-Real-Ip":"172.20.0.1","time":"2023-02-14T09:10:09Z"}
```
