### ISSUE TITLE
Multi Subdomain Wildcard Certificates do not work

### ISSUE THREAD

**Issue by Cave-Johnson** [traefik/traefik#9725]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Created an IngressRoute with a multi level subdomain (`myservice.kube.mydomain.com`). 

Created a letsencrypt wildcard cert for `*.kube.mydomain.com` (confirmed in certificate transparency logs that it is valid)

### What did you see instead?

Since a recent update to my Traefik installation this no longer works, it will not use my wildcard certificate and defaults to the Traefik default certificate (this did not use to be the case)

### What version of Traefik are you using?

2.9.7

### What is your environment & configuration?

K3S - Traefik to expose internal cluster resources

**Comment by ldez** [comment]
Hello,

are you using CNAME or CNAME wildcard?

if yes, you can disable the CNAME support by setting the env var `LEGO_DISABLE_CNAME_SUPPORT` to `true`.

https://doc.traefik.io/traefik/https/acme/#dnschallenge

**Comment by Cave-Johnson** [comment]
I am not using CNAME and the issue isnt in the ACME challenge.

The issue is in serving a subdomain via traefik with a wildcard certificate.

**Comment by ldez** [comment]
so you will have to provide a reproducible context, logs, configuration, etc.

**Comment by Cave-Johnson** [comment]
To reproduce:

- A valid wildcard certificate for `*.kube.mydomain.com`
- Traefik 2.9.7
- Apply the below `IngressRoute`

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myservice-dashboard
  namespace: myservice
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`myservice-dash.kube.mydomain.com`)
      priority: 10
      services:
        - name: myservice-cluster
          port: 9000
  tls:
    secretName: production-com-tls
```

What logs can i provide for this and how would i get these?
