### ISSUE TITLE
Traefik bungles the PDNS_API_URL string for accessing the PowerDNS API

### ISSUE THREAD

**Issue by rptaylor** [traefik/traefik#9726]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm trying to do a Let's Encrypt DNS challenge using PowerDNS.  My PowerDNS server is ns1.example.org and I confirmed that I can successfully query the API like this:
`curl  -H 'X-API-Key: $PDNS_API_KEY' https://ns1.example.org/api/v1/servers/localhost/zones/example.net`

Traefik is running with these args:
`--certificatesresolvers.letsencrypt.acme.dnsChallenge.provider=pdns --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json`

When I set the environment variable `PDNS_API_URL=https://ns1.example.org/api/v1` then I get this error message:
```
time="2023-02-15T23:13:32Z" level=error msg="Unable to obtain ACME certificate for domains \"cluster.example.net\": unable to generate a certificate for the domains [cluster.example.net]: error: one or more domains had a problem:\n[cluster.example.net] [cluster.example.net] acme: error presenting token: pdns: unexpected HTTP status code 404 when GETing 'https://ns1.example.org/api/v1/api/v1/servers/localhost/zones/example.net.'\n" providerName=letsencrypt.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=grafana-grafana-cluster-example-net-grafana@kubernetes rule="Host(`cluster.example.net`) && PathPrefix(`/grafana`)"
```

When I set the environment variable `PDNS_API_URL=https://ns1.example.org/` then I get this error message:
```
time="2023-02-15T23:14:45Z" level=error msg="Unable to obtain ACME certificate for domains \"cluster.example.net\": unable to generate a certificate for the domains [cluster.example.net]: error: one or more domains had a problem:\n[cluster.example.net] [cluster.example.net] acme: error presenting token: pdns: unexpected HTTP status code 404 when GETing 'https://ns1.example.org/servers/localhost/zones/example.net.'\n" routerName=grafana-grafana-cluster-example-net-grafana@kubernetes rule="Host(`cluster.example.net`) && PathPrefix(`/grafana`)" providerName=letsencrypt.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"
```

### What did you see instead?

Traefik is changing the $PDNS_API_URL string that I provide. It either adds or removes the "api/v1" part but it has inverted the logic, changing it so that "api/v1" is present either 0 or 2 times instead of exactly once. So no matter what string I provide I can not get it to query the correct API path.

### What version of Traefik are you using?

/ $ traefik version
Version:      2.9.6
Codename:     banon
Go version:   go1.19.4
Built:        2022-12-07T14:17:58Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

Helm chart v21.0.0
Pod is running with
```
spec:
  containers:
  - args:
    - --entrypoints.metrics.address=:9100/tcp
    - --entrypoints.traefik.address=:9000/tcp
    - --entrypoints.web.address=:8000/tcp
    - --entrypoints.websecure.address=:8443/tcp
    - --api.dashboard=true
    - --ping=true
    - --metrics.prometheus=true
    - --metrics.prometheus.entrypoint=metrics
    - --providers.kubernetescrd
    - --providers.kubernetesingress
    - --entrypoints.websecure.http.tls=true
    - --log.level=DEBUG
    - --certificatesresolvers.letsencrypt.acme.dnsChallenge.provider=pdns
    - --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
```
