### ISSUE TITLE
Cloudflare: Unable to generate a certificate for the domains [dev.example.com *.dev.example.com]

### ISSUE THREAD

**Issue by jurgenhaas** [traefik/traefik#9731]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We have local dev environments with domains like `*.dev.example.com` with different subdomains for each project. We are creating the wildcard certs with certbot and DNS challenge so far and now want to automate that with Traefik, which we use as a proxy already.

The API token is correct, but the log state that the zone can not be found. Config and logs are below.

If we change the domains from `dev.example.com / *.dev.example.com` to  `example.com / *.example.com` , then everything works just fine. So, the configuration as such seems to be valid, just the subdomain part doesn't find the zones on Cloudflare.

### What did you see instead?

Seeing the error in the log that the zones can not be found, details see below in the log.

### What version of Traefik are you using?

Version:      2.7.3
Codename:     epoisses
Go version:   go1.17.11
Built:        2022-06-29T13:48:15Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
version: '3.3'
services:
  traefik:
    container_name: traefik
    image: 'traefik:2.7'
    command:
      - '--api=true'
      - '--api.dashboard=true'
      - '--api.insecure=true'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.lakedrops.acme.email=admin@example.com'
      - "--certificatesresolvers.lakedrops.acme.dnschallenge=true"
      - "--certificatesresolvers.lakedrops.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.lakedrops.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - '--providers.file.directory=/configuration/'
      - '--providers.file.watch=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--log.level=debug'
      - '--experimental.hub=true'
      - '--hub.tls.insecure=true'
      - '--metrics.prometheus.addrouterslabels=true'
    restart: unless-stopped
    environment:
      CF_DNS_API_TOKEN: string-obtained-from-cf
    networks:
      - traefik-public
    ports:
      - '80:80'
      - '443:443'
      - '9900:9900'
      - '9901:9901'
    labels:
      - traefik.enable=true
      - traefik.network=traefik-public
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.rule=Host(`traefik.dev.example.com`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=lakedrops
      - traefik.http.routers.traefik.tls.domains[0].main=dev.example.com
      - traefik.http.routers.traefik.tls.domains[0].sans=*.dev.example.com
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
networks:
  traefik-public:
    external: true
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

```
traefik  | time="2023-02-21T07:03:27Z" level=debug msg="Looking for provided certificate(s) to validate [\"dev.example.com\" \"*.dev.example.com\"]..." providerName=lakedrops.acme ACME CA="https://acme-staging-v02.api.letsencrypt.org/directory"
traefik  | time="2023-02-21T07:03:27Z" level=debug msg="Domains [\"dev.example.com\" \"*.dev.example.com\"] need ACME certificates generation for domains \"dev.example.com,*.dev.example.com\"." providerName=lakedrops.acme ACME CA="https://acme-staging-v02.api.letsencrypt.org/directory"
traefik  | time="2023-02-21T07:03:27Z" level=debug msg="Loading ACME certificates [dev.example.com *.dev.example.com]..." ACME CA="https://acme-staging-v02.api.letsencrypt.org/directory" providerName=lakedrops.acme
traefik  | time="2023-02-21T07:03:29Z" level=debug msg="Building ACME client..." providerName=lakedrops.acme
traefik  | time="2023-02-21T07:03:29Z" level=debug msg="https://acme-staging-v02.api.letsencrypt.org/directory" providerName=lakedrops.acme
traefik  | time="2023-02-21T07:03:30Z" level=info msg=Register... providerName=lakedrops.acme
traefik  | time="2023-02-21T07:03:30Z" level=debug msg="legolog: [INFO] acme: Registering account for admin@example.com"
traefik  | time="2023-02-21T07:03:30Z" level=debug msg="Using DNS Challenge provider: cloudflare" providerName=lakedrops.acme
traefik  | time="2023-02-21T07:03:30Z" level=debug msg="legolog: [INFO] [dev.example.com, *.dev.example.com] acme: Obtaining bundled SAN certificate"
traefik  | time="2023-02-21T07:03:31Z" level=debug msg="legolog: [INFO] [*.dev.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/5457402704"
traefik  | time="2023-02-21T07:03:31Z" level=debug msg="legolog: [INFO] [dev.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/5457402714"
traefik  | time="2023-02-21T07:03:31Z" level=debug msg="legolog: [INFO] [*.dev.example.com] acme: use dns-01 solver"
traefik  | time="2023-02-21T07:03:31Z" level=debug msg="legolog: [INFO] [dev.example.com] acme: Could not find solver for: tls-alpn-01"
traefik  | time="2023-02-21T07:03:31Z" level=debug msg="legolog: [INFO] [dev.example.com] acme: Could not find solver for: http-01"
traefik  | time="2023-02-21T07:03:31Z" level=debug msg="legolog: [INFO] [dev.example.com] acme: use dns-01 solver"
traefik  | time="2023-02-21T07:03:31Z" level=debug msg="legolog: [INFO] [*.dev.example.com] acme: Preparing to solve DNS-01"
traefik  | time="2023-02-21T07:03:33Z" level=debug msg="legolog: [INFO] cloudflare: new record for dec.example.com, ID d9643eedfd5855efbd856c9ba5aeb9d2"
traefik  | time="2023-02-21T07:03:33Z" level=debug msg="legolog: [INFO] [dev.example.com] acme: Preparing to solve DNS-01"
traefik  | time="2023-02-21T07:03:34Z" level=debug msg="legolog: [INFO] [*.dev.example.com] acme: Trying to solve DNS-01"
traefik  | time="2023-02-21T07:03:34Z" level=debug msg="legolog: [INFO] [*.dev.example.com] acme: Checking DNS record propagation using [127.0.0.11:53]"
traefik  | time="2023-02-21T07:03:36Z" level=debug msg="legolog: [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]"
traefik  | time="2023-02-21T07:03:36Z" level=debug msg="legolog: [INFO] [*.dev.example.com] acme: Waiting for DNS record propagation."
traefik  | time="2023-02-21T07:03:38Z" level=debug msg="legolog: [INFO] [*.dev.example.com] acme: Waiting for DNS record propagation."
traefik  | time="2023-02-21T07:03:47Z" level=debug msg="legolog: [INFO] [*.dev.example.com] The server validated our request"
traefik  | time="2023-02-21T07:03:47Z" level=debug msg="legolog: [INFO] [*.dev.example.com] acme: Cleaning DNS-01 challenge"
traefik  | time="2023-02-21T07:03:48Z" level=debug msg="legolog: [INFO] [dev.example.com] acme: Cleaning DNS-01 challenge"
traefik  | time="2023-02-21T07:03:48Z" level=debug msg="legolog: [WARN] [dev.example.com] acme: cleaning up failed: cloudflare: failed to find zone dev.example.com.: zone could not be found "
traefik  | time="2023-02-21T07:03:49Z" level=debug msg="legolog: [INFO] Skipping deactivating of valid auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/5457402704"
traefik  | time="2023-02-21T07:03:49Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/5457402714"
traefik  | time="2023-02-21T07:03:49Z" level=error msg="Unable to obtain ACME certificate for domains \"dev.example.com,*.dev.example.com\" : unable to generate a certificate for the domains [dev.example.com *.dev.example.com]: error: one or more domains had a problem:\n[dev.example.com] [dev.example.com] acme: error presenting token: cloudflare: failed to find zone dev.example.com.: zone could not be found\n" providerName=lakedrops.acme
```
