### ISSUE TITLE
Missing `traefik_tls_certs_not_after` metric for default certificate

### ISSUE THREAD

**Issue by trinhpham** [traefik/traefik#9735]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I deploy latest Traefik helm chart and use a default wildcard certificate for serving ingresses & ingressroutes (they all works as expected)
Then I found that I have all other metrics but not `traefik_tls_certs_not_after` one.

### What did you see instead?

No `traefik_tls_certs_not_after` value is collected by Prometheus.

### What version of Traefik are you using?

`Image:         traefik:2.9.4`

### What is your environment & configuration?

```yaml

  fullnameOverride: traefik-private

  deployment:
    enabled: true
    kind: DaemonSet

  providers:
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: true
      allowExternalNameServices: true

    kubernetesIngress:
      enabled: true
      allowExternalNameServices: true
      allowEmptyServices: false
      ingressClass: traefik-private

  metrics:
    prometheus:
      entryPoint: metrics

  tracing: {}
  ports:
    web:
      port: 8000
      expose: true
      exposedPort: 80
      protocol: TCP
      proxyProtocol:
        #trustedIPs: []
        insecure: true
    websecure:
      port: 8443
      expose: true
      exposedPort: 443
      protocol: TCP
      http3:
        enabled: true
        
      tls:
        enabled: true
        # this is the name of a TLSOption definition
        options: ""
        certResolver: ""
        domains: []
        
      proxyProtocol:
        #trustedIPs: []
        insecure: true

      middlewares: []

  tlsStore:
    default:
      defaultCertificate:
        secretName: wildcard-mydomain-com

  service:
    enabled: true
    type: LoadBalancer
    spec:
      externalTrafficPolicy: Local
```

Add more configuration information here.
