### ISSUE TITLE
IngressrouteTCP doesn't work!

### ISSUE THREAD

**Issue by KR-Ravindra** [traefik/traefik#9754]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hi, I will write this short and sweet

Here are few options I have on my ingress controller of traefik

```
            - '--global.checknewversion'
            - '--global.sendanonymoususage'
            - '--entrypoints.metrics.address=:9100/tcp'
            - '--entrypoints.traefik.address=:9000/tcp'
            - '--entrypoints.web.address=:8000/tcp'
            - '--entrypoints.ampq.address=:5672/tcp'
            - '--entrypoints.websecure.address=:8443/tcp'
            - '--api.insecure'
            - '--ping=true'
            - '--metrics.prometheus=true'
            - '--metrics.prometheus.entrypoint=metrics'
            - '--providers.kubernetescrd'
            - '--providers.kubernetescrd.ingressClass=traefik-internal'
            - '--providers.kubernetesingress'
            - '--entrypoints.websecure.http.tls=true'
            - '--accesslog.fields.defaultmode=keep'
            - '--accesslog.fields.headers.defaultmode=drop'
            - '--providers.kubernetesingress.ingressclass=traefik-internal'
            - '--accesslog=true'
            - '--log.level=DEBUG'
            - '--accesslog.filepath=/dev/stdout'

```

Here is my  traefik service... which is exposed as a loadbalancer endpoint from cloud k8s cluster

```
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: metrics
      nodePort: 30216
    - name: web
      protocol: TCP
      port: 80
      targetPort: web
      nodePort: 30735
    - name: websecure
      protocol: TCP
      port: 443
      targetPort: websecure
      nodePort: 32403
    - name: ampq
      protocol: TCP
      port: 5672
      targetPort: ampq
      nodePort: 30137
    - name: traefik
      protocol: TCP
      port: 9000
      targetPort: traefik
      nodePort: 30217
  selector:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik
  clusterIP: 10.30.130.159
  clusterIPs:
    - 10.30.130.159
  type: LoadBalancer
```

Now here is my ingressrouteTCP

```

spec:
  entryPoints:
    - ampq
  routes:
    - match: HostSNI(`ampq-rabbitmq-kardex.cortex.addverb.com`)
      services:
        - name: rabbitmq
          port: 5672
          protocol: tcp
    - match: HostSNI(`wss-rabbitmq-kardex.cortex.addverb.com`)
      services:
        - name: rabbitmq
          port: 15673
          protocol: tcp
  tls:
    passthrough: true

```

Yes my service `rabbitmq` is working fine using kubectl port-forward or setting it as a loadbalancer type.
I had banged my head to my desk, then to the wall, then to the laptop before I join you over here for some enlightment. 

When I do a telnet 
```
➜  ~ telnet ampq-rabbitmq.something.com 5672
Trying x.x.x.x...
Connected to something.com.
Escape character is '^]'.
/
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad RequestConnection closed by foreign host.
```

This is returning a HTTP response.. while desired should look something like this - 
```
➜  ~ telnet serviceLoadbalncerip 5672
Trying x.x.x.x...
Connected to something.com.
Escape character is '^]'.
/
/
/
Connection closed by foreign host.
```

Removing TLS is not an option, I want this to be working with host defined routing for tcp. I have special ampq entrypoint on my traefik ingress controller exposed for this.

![image](https://user-images.githubusercontent.com/42912207/222086684-2c3e2233-9c97-43f6-8307-3de1bd48d73c.png)

Can't show more, but on UI, the TCP Router shows up and fine..

Here are logs in traefik pod when I establishing a connection 

```
time="2023-03-01T08:37:28Z" level=debug msg="'500 Internal Server Error' caused by: net/http: HTTP/1.x transport connection broken: malformed HTTP response \"AMQP\\x00\\x00\\t\\x01\""
```

So what I estimate is... the traffic went to my rabbitmq and then in response it gave me back AMPQ connection string.. however my traefik ingress controller doesn't understand that its tcp (god knows why!). 

Am I missing some conifguration on my ingress controller? I have checked my CRDs and I understood TCPRouter gets auto created by attaching to service, and I confirmed same from UI and Logs.

### What did you see instead?

When I do a telnet 
```
➜  ~ telnet ampq-rabbitmq.something.com 5672
Trying x.x.x.x...
Connected to something.com.
Escape character is '^]'.
/
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad RequestConnection closed by foreign host.
```

### What version of Traefik are you using?

```
Version:      2.9.6
Codename:     banon
Go version:   go1.19.4
Built:        2022-12-07T14:17:58Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
    - '--global.checknewversion'
            - '--global.sendanonymoususage'
            - '--entrypoints.metrics.address=:9100/tcp'
            - '--entrypoints.traefik.address=:9000/tcp'
            - '--entrypoints.web.address=:8000/tcp'
            - '--entrypoints.ampq.address=:5672/tcp'
            - '--entrypoints.websecure.address=:8443/tcp'
            - '--api.insecure'
            - '--ping=true'
            - '--metrics.prometheus=true'
            - '--metrics.prometheus.entrypoint=metrics'
            - '--providers.kubernetescrd'
            - '--providers.kubernetescrd.ingressClass=traefik-internal'
            - '--providers.kubernetesingress'
            - '--entrypoints.websecure.http.tls=true'
            - '--accesslog.fields.defaultmode=keep'
            - '--accesslog.fields.headers.defaultmode=drop'
            - '--providers.kubernetesingress.ingressclass=traefik-internal'
            - '--accesslog=true'
            - '--log.level=DEBUG'
            - '--accesslog.filepath=/dev/stdout'
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

Here are logs in traefik pod when I establishing a connection 

```
time="2023-03-01T08:37:28Z" level=debug msg="'500 Internal Server Error' caused by: net/http: HTTP/1.x transport connection broken: malformed HTTP response \"AMQP\\x00\\x00\\t\\x01\""
```
