### ISSUE TITLE
TCP Router with no available service behaves like a HTTP server 

### ISSUE THREAD

**Issue by bgK** [traefik/traefik#9756]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We're using the Traefik k8s ingressroute controller mostly for HTTP(S) on ports 80 and 443. We also proxy postgresql connections through an `IngressRouteTCP` on port 1234.

This works fine except when the postgresql server is down. In that case, the k8s service for postgresql has no associated endpoint. The Traefik postgresql entrypoint then acts like a HTTP server.

This is an issue because Traefik does not close the connection until something looking like an HTTP request is received. The initial packet the postgresql client sends does not contain a newline which means Traefik does not send a reply and does not immediately close the connection. The postgresql client remains in a state where it waits for a response from the server. 
This is compounded by the infinite default socket read timeout of the java postgresql client. Clients trying to reconnect during a postgresql outage essentially get stuck indefinitely.

### What did you see instead?

I would expect a Traefik TCP router to refuse / immediately close / immediately reset the connection when there is no available service instead of acting like a HTTP server.

### What version of Traefik are you using?

v2.5.7

### What is your environment & configuration?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgresql
  namespace: kube-ns
spec:
  entryPoints:
  - postgresql
  routes:
  - match: HostSNI(`*`)
    services:
    - name: postgresql
      port: 1234
```
