### ISSUE TITLE
Application redirect (302) in combination with PathPrefix results in unexpected behaviour

### ISSUE THREAD

**Issue by micaeb** [traefik/traefik#9767]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

First up I am a new user of traefik and already looked at similar issues #1957, #2510 and #1081. Over all I have the same use-case and setup as #1957 but even with the latest version of traefik (v2.9) I see an unexpected behaviour.

traefik runs together with standalone docker and I want to access prometheus under `https://example.com/prometheus/`.
When I access `https://example.com/prometheus/` the prometheus application responds with a 302 redirect to /graph and I expected traefik to resolve this to `https://example.com/prometheus/graph`.

I assume I might be doing something wrong here, but I see the same bug behaviour as #1957 even so this was allegedly fixed by #3631.

### What did you see instead?

I observe the same behaviour as #1957 after the 302 redirect the browser tries to access `https://example.com/graph` which results in a 404 for obvious reasons.

### What version of Traefik are you using?

```sh
# traefik version
Version:      2.9.8
Codename:     banon
Go version:   go1.19.6
Built:        2023-02-15T15:23:25Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

This is my static configuration file traefik.yml:
```yaml
serversTransport:
  insecureSkipVerify: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: false
    http:
      tls: {}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    httpClientTimeout: 100s
    watch: true
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

api:
  insecure: true

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
```

For my HTTPS setup I use existing wildcard certificates with the following dynamic configuration file:
```yaml
tls:
  certificates:
    - certFile: /etc/certs/live/example.com/fullchain.pem
      keyFile: /etc/certs/live/example.com/privkey.pem
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/live/example.com/fullchain.pem
        keyFile: /etc/certs/live/example.com/privkey.pem
```

I apply the configurations by building (and hosting) a customized docker image with this Dockerfile:
```Dockerfile
FROM traefik:2.9
RUN mkdir -p /etc/traefik/dynamic

COPY ./config/traefik.yaml /etc/traefik/traefik.yaml
COPY ./config/dynamic.yaml /etc/traefik/dynamic/dynamic.yaml
VOLUME [ "/etc/certs" ]
```

The docker container(s) are setup with the following docker-compose file:
```yaml
version: '3'

services:
  reverse-proxy:
    image: <my-registry>/traefik:2.9
    container_name: ${COMPOSE_PROJECT_NAME}_traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt:/etc/certs:ro
    userns_mode: "host"
  prometheus:
    image: <my-registry>/prometheus:2.37
    container_name: ${COMPOSE_PROJECT_NAME}_prometheus
    volumes:
      - prometheus_data:/prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`example.com`) && PathPrefix(`/prometheus`)"
      - "traefik.http.middlewares.stripprometheus.stripprefix.prefixes=/prometheus"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.middlewares=stripprometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

volumes:
  prometheus_data:
```
