### ISSUE TITLE
TLS error shown only in debug mode

### ISSUE THREAD

**Issue by nerzhul** [traefik/traefik#9768]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Traefik have a TLS logging issue, it seems to be related to a private key not matching a public one. Traefik want to load it and silently fail in INFO loglevel, the real issue is only in debug, which doesn't permit to understand at first what's the issue, especially when you have 8k ingresses and thousands of queries per second.

here is the error in debug mode

```
{"level":"debug","msg":"Serving default certificate for request: \"amazing.svc.veepee.fr\"","time":"2023-03-10T08:55:40Z"}
{"level":"debug","msg":"http: TLS handshake error from 10.154.55.32:4418: remote error: tls: bad certificate","time":"2023-03-10T08:55:40Z"}
```

i think it should be shown in error, not in debug

### What did you see instead?

nothing

### What version of Traefik are you using?

2.9.8

### What is your environment & configuration?

```yaml
containers:
      - args:
        - --api
        - --api.dashboard=true
        - --api.insecure=true
        - --providers.kubernetescrd=true
        - --providers.kubernetesingress=true
        - --providers.kubernetesingress.ingressclass=
        - --providers.kubernetesingress.ingressendpoint.hostname=traefik-ingress-controller-default
        - --providers.kubernetesingress.throttleDuration=0
        - --providers.kubernetesingress.allowEmptyServices=false
        - --ping=true
        - --log.format=json
        - --log.level=INFO
        - --accesslog=true
        - --accesslog.format=json
        - --accesslog.bufferingsize=10
        - --accesslog.fields.headers.defaultmode=drop
        - --accesslog.fields.headers.names.x-forwarded-for=keep
        - --accesslog.fields.headers.names.x-forwarded-fortmp=keep
        - --accesslog.fields.headers.names.forwarded=keep
        - --entryPoints.https.address=:8443
        - --entryPoints.https.http.tls=true
        - --entryPoints.https.proxyProtocol.insecure=true
        - --entryPoints.http.address=:1080
        - --metrics.prometheus=true
        - --serversTransport.insecureSkipVerify=true
        - --providers.file=true
        - --providers.file.filename=/etc/traefik/dynamic.yaml
        - --tracing=true
        - --tracing.serviceName=k8s-traefik-ingress
        - --tracing.elastic=true
        - --tracing.elastic.serverurl=https://apm
        - --tracing.elastic.secrettoken=
        - --tracing.elastic.serviceenvironment=production

```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

```
{"level":"debug","msg":"Serving default certificate for request: \"amazing.svc.veepee.fr\"","time":"2023-03-10T08:55:40Z"}
{"level":"debug","msg":"http: TLS handshake error from 10.154.55.32:4418: remote error: tls: bad certificate","time":"2023-03-10T08:55:40Z"}
```
