### ISSUE TITLE
sendAnonymousUsage not working docker image: traefik:v2.9.8

### ISSUE THREAD

**Issue by ganuonglachanh** [traefik/traefik#9771]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

The latest docker image traefik:v2.9.8 when setting the sendAnonymousUsage in both

```
## STATIC CONFIGURATION in traefik.yaml
global:
  checkNewVersion: false
  sendAnonymousUsage: false  
```

and in docker-compose.yaml file:

```
- "--global.sendAnonymousUsage false"
 - "--global.sendAnonymousUsage=false"
```

does not work!

### What did you see instead?

```
time="2023" level=info msg="Traefik version 2.9.8 built on 2023-02-15T15:23:25Z"
time="2023" level=info msg="Stats collection is enabled."
time="2023" level=info msg="Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration."
time="2023" level=info msg="Help us improve Traefik by leaving this feature on :)"
```

### What version of Traefik are you using?

traefik:v2.9.8

### What is your environment & configuration?

```yaml
## STATIC CONFIGURATION
global:
  checkNewVersion: false
  sendAnonymousUsage: false  

log:
  level: INFO
  filePath: "/logs/traefik.log"

accessLog:
  filePath: "/logs/access.log"
  bufferingSize: 100
api:
  #insecure: true
  dashboard: true

pilot:
  dashboard: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "web"
  file:
    directory: "/traefix"
    watch: true

entryPoints:
  console:
    address: ":8080"
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      middlewares:
        #- secureHeaders@file
    forwardedHeaders:
      trustedIPs:
        - "173.245.48.0/20" #https://www.cloudflare.com/ips/
        - "103.21.244.0/22"
        - "103.22.200.0/22"
        - "103.31.4.0/22"
        - "141.101.64.0/18"
        - "108.162.192.0/18"
        - "190.93.240.0/20"
        - "188.114.96.0/20"
        - "197.234.240.0/22"
        - "198.41.128.0/17"
        - "162.158.0.0/15"
        - "104.16.0.0/13"
        - "104.24.0.0/14"
        - "172.64.0.0/13"
        - "131.0.72.0/22"
        - "2400:cb00::/32"
        - "2606:4700::/32"
        - "2803:f800::/32"
        - "2405:b500::/32"
        - "2405:8100::/32"
        - "2a06:98c0::/29"
        - "2c0f:f248::/32"
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

```
time="2023" level=info msg="Traefik version 2.9.8 built on 2023"
time="2023" level=info msg="Stats collection is enabled."
time="2023" level=info msg="Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration."
time="2023" level=info msg="Help us improve Traefik by leaving this feature on :)"
time="2023" level=info msg="More details on: https://doc.traefik.io/traefik/contributing/data-collection/"
time="2023" level=warning msg="Traefik Pilot has been removed."
time="2023" level=info msg="Starting provider aggregator aggregator.ProviderAggregator"
time="2023" level=info msg="Starting provider *file.Provider"
time="2023" level=info msg="Starting provider *traefik.Provider"
time="2023" level=info msg="Starting provider *docker.Provider"
time="2023" level=info msg="Starting provider *acme.ChallengeTLSALPN"
time="2023" level=info msg="I have to go..."
time="2023" level=info msg="Stopping server gracefully"
time="2023" level=error msg="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2023" level=error msg="accept tcp [::]:8080: use of closed network connection" entryPointName=console
time="2023" level=error msg="close tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2023" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2023" level=error msg="close tcp [::]:8080: use of closed network connection" entryPointName=console
time="2023" level=error msg="close tcp [::]:80: use of closed network connection" entryPointName=web
time="2023" level=info msg="Server stopped"
time="2023" level=info msg="Shutting down"
time="2023" level=info msg="Traefik version 2.9.8 built on 2023-02-15T15:23:25Z"
time="2023" level=info msg="Stats collection is enabled."
time="2023" level=info msg="Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration."
time="2023" level=info msg="Help us improve Traefik by leaving this feature on :)"
time="2023" level=info msg="More details on: https://doc.traefik.io/traefik/contributing/data-collection/"
time="2023" level=warning msg="Traefik Pilot has been removed."
time="2023" level=info msg="Starting provider aggregator aggregator.ProviderAggregator"
time="2023" level=info msg="Starting provider *file.Provider"
time="2023" level=info msg="Starting provider *traefik.Provider"
time="2023" level=info msg="Starting provider *docker.Provider"
time="2023" level=info msg="Starting provider *acme.ChallengeTLSALPN"
time="2023" level=info msg="Anonymous stats sent to https://collect.traefik.io/9vxmmkcdmalbdi635d4jgc5p5rx0h7h8: {\"global\":{\"sendAnonymousUsage\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"console\":{\"address\":\"xxxx\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250}},\"web\":{\"address\":\"xxxx\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{\"redirections\":{\"entryPoint\":{\"to\":\"websecure\",\"scheme\":\"https\",\"permanent\":true,\"priority\":2147483646}}},\"http2\":{\"maxConcurrentStreams\":250}},\"websecure\":{\"address\":\"xxxx\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{\"trustedIPs\":[\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\",\"xxxx\"]},\"http\":{\"middlewares\":[\"RealIP@file\",\"ScanBlock@file\"]},\"http2\":{\"maxConcurrentStreams\":250}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"xxxx\",\"defaultRule\":\"xxxx\",\"network\":\"web\",\"swarmModeRefreshSeconds\":\"15s\"},\"file\":{\"directory\":\"/traefix\",\"watch\":true}},\"api\":{\"dashboard\":true},\"log\":{\"level\":\"INFO\",\"filePath\":\"xxxx\",\"format\":\"common\"},\"accessLog\":{\"filePath\":\"xxxx\",\"format\":\"common\"}}},\"bufferingSize\":100},\"pilot\":{},}}}}"
```
