### ISSUE TITLE
Tailscale Integration: Unable to fetch certificate for domain - error="unexpected output: no delimiter"

### ISSUE THREAD

**Issue by anaisbetts** [traefik/traefik#9772]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Trying to set up a simple example of using the new Tailscale provider, but running into an issue. After mapping the Tailscale socket (which isn't in the documentation), the provider throws the error in the title

### What did you see instead?

Can't connect to Tailscale

### What version of Traefik are you using?

v3.0.0-beta2

### What is your environment & configuration?

Docker Compose:

```yaml
services:
  proxy:
    image: traefik:v3.0
    network_mode: host
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--certificatesresolvers.tsresolver.tailscale=true"
      - "--log.level=DEBUG"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
      - ./letsencrypt:/letsencrypt
  hello:
    image: crccheck/hello-world
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello.rule=Host(`ts-hello-test.****.ts.net`)"
      - "traefik.http.routers.hello.tls.certresolver=tsresolver"
      - "traefik.http.services.hello.loadbalancer.server.port=8000"
```

### If applicable, please paste the log output in DEBUG level

```
ts-test-proxy-1  | 2023-03-12T13:00:44Z DBG github.com/traefik/traefik/v2/pkg/middlewares/tracing/wrapper.go:32 > Adding tracing to middleware entryPointName=traefik middlewareName=dashboard_redirect@internal routerName=dashboard@internal
ts-test-proxy-1  | 2023-03-12T13:00:44Z DBG github.com/traefik/traefik/v2/pkg/middlewares/tracing/forwarder.go:26 > Added outgoing tracing middleware entryPointName=traefik middlewareName=tracing middlewareType=TracingForwarder routerName=api@internal serviceName=api@internal
ts-test-proxy-1  | 2023-03-12T13:00:44Z DBG github.com/traefik/traefik/v2/pkg/middlewares/recovery/recovery.go:22 > Creating middleware entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery
ts-test-proxy-1  | 2023-03-12T13:00:44Z DBG github.com/traefik/traefik/v2/pkg/server/service/service.go:256 > Creating load-balancer entryPointName=web routerName=hello@docker serviceName=hello@docker
ts-test-proxy-1  | 2023-03-12T13:00:44Z DBG github.com/traefik/traefik/v2/pkg/server/service/service.go:298 > Creating server entryPointName=web routerName=hello@docker serverName=82a992d8b7725f97 serviceName=hello@docker target=http://172.20.0.2:8000
ts-test-proxy-1  | 2023-03-12T13:00:44Z DBG github.com/traefik/traefik/v2/pkg/middlewares/tracing/forwarder.go:26 > Added outgoing tracing middleware entryPointName=web middlewareName=tracing middlewareType=TracingForwarder routerName=hello@docker serviceName=hello
ts-test-proxy-1  | 2023-03-12T13:00:44Z DBG github.com/traefik/traefik/v2/pkg/middlewares/recovery/recovery.go:22 > Creating middleware entryPointName=web middlewareName=traefik-internal-recovery middlewareType=Recovery
ts-test-proxy-1  | 2023-03-12T13:00:44Z DBG github.com/traefik/traefik/v2/pkg/middlewares/recovery/recovery.go:22 > Creating middleware entryPointName=websecure middlewareName=traefik-internal-recovery middlewareType=Recovery
ts-test-proxy-1  | 2023-03-12T13:00:44Z DBG github.com/traefik/traefik/v2/pkg/server/router/tcp/manager.go:235 > Adding route for ts-hello-test.****.ts.net with TLS options default entryPointName=web
ts-test-proxy-1  | 2023-03-12T13:00:44Z DBG github.com/traefik/traefik/v2/pkg/server/router/tcp/manager.go:235 > Adding route for ts-hello-test.****.ts.net with TLS options default entryPointName=websecure
ts-test-proxy-1  | 2023-03-12T13:00:45Z ERR github.com/traefik/traefik/v2/pkg/provider/tailscale/provider.go:249 > Unable to fetch certificate for domain "ts-hello-test.****.ts.net" error="unexpected output: no delimiter" providerName=tsresolver.tailscale
ts-test-proxy-1  | 2023-03-12T13:00:45Z DBG github.com/traefik/traefik/v2/pkg/server/configurationwatcher.go:118 > Skipping empty configuration providerName=tsresolver.tailscale
```
