### ISSUE TITLE
command traefik error: field not found, node: watch

### ISSUE THREAD

**Issue by zhaochunxue** [traefik/traefik#9774]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?
```yml
请问zookeeper是不是不支持配置的自动更新，配置写在zk里边，更改zk内的地址发现不能动态获取更改的参数，加了watch后发现没有这个配置
log:
  # 设置调试日志文件存储路径，如果为空则输出到控制台
  #filePath: "/etc/traefik/logs/traefik.log"
  # 设置调试日志级别
  level: "debug"
  # 设置调试日志格式
  #format: "common"

global:
  # 周期性的检查是否有新版本发布
  checkNewVersion: false    
  # 周期性的匿名发送使用统计信息
  sendAnonymousUsage: false 
  
serversTransport:
  # Traefik忽略验证代理服务的TLS证书
  insecureSkipVerify: true  
  
api:
  # 启用Dashboard
  dashboard: true
  # 允许HTTP 方式访问API
  insecure: true
  # 启用Debug调试模式
  debug: false
  
entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"
  traefik:
    address: ":8080"
  cluster-6601:
    address: ":6601"

#static configuration
providers:
  providersThrottleDuration: 2s
  zooKeeper:
    watch: true
    rootKey: "traefik"
    endpoints:
      - "10.172.48.19:6602"
```
