### ISSUE TITLE
Transfer-Encoding: chunked HTTP response - missing data

### ISSUE THREAD

**Issue by aleksvujic** [traefik/traefik#9775]
# What did you do?

## Architecture diagram
We are using Apache Thrift RPC server written in C#. It is exposed behind Traefik and Kestrel over HTTP protocol. Architecture diagram looks like this:

![Traefik and Thrift](https://user-images.githubusercontent.com/17112542/224711860-08ac0a22-5aed-422f-8961-819b0f54e4c3.png)

We noticed that sometimes not all the data returned by the server comes through to the Python client.

## Investigation and related issues
The problem occurs only when responses are chunked. If the `Content-Length` HTTP header is set, everything works as expected.
1. Chunked response
    1. Responses are chunked because of the design of ASP.NET Core servers (see issue [2417](https://github.com/aspnet/KestrelHttpServer/issues/2417)).
    2. `UseResponseBuffering()` is deprecated and will be maybe implemented in .NET 8 (see issue [27470](https://github.com/dotnet/aspnetcore/issues/27470)).
    3. Workaround, if Traefik does not fix the issue, would be to set the `Content-Length` HTTP header (see issue [17413](https://github.com/dotnet/aspnetcore/issues/17413)).
2. No option in Traefik seems to fix this ([Middlewares - Buffering](https://doc.traefik.io/traefik/middlewares/http/buffering/)).
3. Only similar issue: [Traefik ingress route on k8s, modifies chunked response from service](https://community.traefik.io/t/traefik-ingress-route-on-k8s-modifies-chunked-response-from-service/9013)

## Attachment
[`traefik-report.zip`](https://github.com/traefik/traefik/files/10958588/traefik-report.zip) - contains all the necessary files to reproduce the issue and a Wireshark recording

1. `traefik` folder - Traefik configuration
2. `thrift_server_netstd` folder - implementation and deployment files for C# server
3. `thrift_client_py` folder - implementation and deployment files for Python client
4. `traefik-bug.pcapng` - Wireshark capture of the network traffic when the issue occurred

## Steps to reproduce

1. Deployment machine `depl1` info:
```
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Docker Version 20.10.21, build baeda1f
```
2. Unzip [`traefik-report.zip`](https://github.com/traefik/traefik/files/10958588/traefik-report.zip) (attachment of this issue) on the deployment machine `depl1` and test machine `test1`.
3. Go to `traefik-report/traefik` folder and run the following command on `depl1`:
```sh
docker stack deploy -c docker-compose-Traefik.yml Traefik
```
4. Go to `traefik-report/thrift_server_netstd` folder and deploy Thrift server on `depl1`:
```sh
docker build -t thrift-server -f Dockerfile .
docker stack deploy -c docker-compose.yml thrift-service
```
5. Add a new record to `hosts` file which resolves `thrift-service.com` on `test1` to the IP where `thrift-service` is deployed (`depl1`).
6. Go to `traefik-report/thrift_client_py` folder and run client in Python environment with [Thrift library](https://pypi.org/project/thrift/) on `test1` (_it does not always fail and maybe a couple of retries are necessary_):
```
python3 thrift_client.py
```

# What did you see instead?

Sometimes not all the data that the C# server sends back comes through to the client. This is the error that we receive in the Python client:

```
Traceback (most recent call last):
  File "C:\Users\dejank\Desktop\dev\traefik-report\thrift_client_py\thrift_client.py", line 22, in <module>
    client.read_data(strData)
  File "C:\Users\dejank\Desktop\dev\traefik-report\thrift_client_py\gen_py\helloWorld\helloWorldInterface.py", line 45, in read_data
    return self.recv_read_data()
  File "C:\Users\dejank\Desktop\dev\traefik-report\thrift_client_py\gen_py\helloWorld\helloWorldInterface.py", line 64, in recv_read_data
    result.read(iprot)
  File "C:\Users\dejank\Desktop\dev\traefik-report\thrift_client_py\gen_py\helloWorld\helloWorldInterface.py", line 209, in read
    self.success.read(iprot)
  File "C:\Users\dejank\Desktop\dev\traefik-report\thrift_client_py\gen_py\helloWorld\ttypes.py", line 58, in read
    (fname, ftype, fid) = iprot.readFieldBegin()
  File "C:\isys_venv\lib\site-packages\thrift\protocol\TBinaryProtocol.py", line 163, in readFieldBegin
    type = self.readByte()
  File "C:\isys_venv\lib\site-packages\thrift\protocol\TBinaryProtocol.py", line 207, in readByte
    buff = self.trans.readAll(1)
  File "C:\isys_venv\lib\site-packages\thrift\transport\TTransport.py", line 68, in readAll
    raise EOFError()
EOFError

Process finished with exit code 1
```

# What version of Traefik are you using?

```
Version:      2.9.8
Codename:     banon
Go version:   go1.19.6
Built:        2023-02-15T15:23:25Z
OS/Arch:      linux/amd64
```

# What is your environment & configuration?

All the relevant Traefik configuration is also included in [`traefik-report.zip`](https://github.com/traefik/traefik/files/10958588/traefik-report.zip) attachment in `traefik` folder.

`docker-compose-Traefik.yml`:
```yml
version: "3.7"

services:
  traefik:
    image: "traefik:v2.9.8"
    networks:
      - traefik-net
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./TraefikConfig/:/etc/traefik/"
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"

networks:
  traefik-net:
    external: true
    name: traefik-net
```

`traefik.yml`:
```yml
serversTransport:
  insecureSkipVerify: true

providers:
  file:
    directory: "/etc/traefik"
    watch: true
  docker:
    swarmMode: true
    exposedByDefault: false

entrypoints:
  thrift-service:
    address: ":9090"

```
