### ISSUE TITLE
 Cannot get ACME client unrecognized DNS provider: InternetX

### ISSUE THREAD

**Issue by 1Shiroyuuki1** [traefik/traefik#9776]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I tried to use InternetX as DNS Provider which should be supported according to: https://github.com/traefik/traefik/blob/a5c520664aae954f1a8cafbacf772a06c6f78b36/docs/content/https/acme.md?plain=1

Here is my Traefik config docker-compose:
```
networks:
  airflow:
    name: airflow
  traefik:
    name: traefik
  gitlab:
    name: gitlab
  zammad:
    name: zammad
services:
  traefik:
    command:
      - --api.insecure=true
      - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.disablepropagationcheck=true
      # InternetX
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=internetx
      - --certificatesresolvers.myresolver.acme.dnschallenge.delaybeforecheck=0

      - --certificatesresolvers.letsencrypt.acme.email=xxxx
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    container_name: traefik
    environment:
      - INTERNETX_USERNAME=xxxx
      - INTERNETX_PASSWORD=xxxx
      - INTERNETX_CONTEXT=xxxx
      - INTERNETX_SOLVER_NAME=xxxx
    image: traefik:2.9.8
    networks:
      - airflow
      - traefik
      - gitlab
      - zammad
    ports:
      - 22:22
      - 80:80
      - 443:443
      - 8080:8080
      - 5000:5000
    restart: always
    volumes:
      - /opt/connectr/docker-compose/traefik/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
version: '3.8'
```

### What did you see instead?

`level=error msg="Unable to obtain ACME certificate for domains \"gitlab.xxxx.de\": cannot get ACME client unrecognized DNS provider: internetx"
`
### What version of Traefik are you using?

2.9.8

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.
