### ISSUE TITLE
Traefik not return exactly error from gRPC service

### ISSUE THREAD

**Issue by longit644** [traefik/traefik#9788]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

gRPC client alway receive `unexpected HTTP status code received from server: 500 (Internal Server Error)` when make rpc call through Traefik while gRPC server return `SayHello error` when call directly.

<img width="1440" alt="Screen Shot 2023-03-20 at 6 25 36 PM" src="https://user-images.githubusercontent.com/24292696/226326377-afa0a1d3-6e10-4be0-92e5-c8d2e6025a42.png">

gRPC service repo: https://github.com/longit644/grpc-helloworld-error

### What did you see instead?

Traefik forward error from upstream server.

### What version of Traefik are you using?

2.9.8

### What is your environment & configuration?

`dynamic.yml`
```yaml
## dynamic configuration ##
http:
  routers:
    grpc:
      service: grpc
      rule: PathPrefix(`/`)
      middlewares:
        - limit

  services:
    grpc:
      loadBalancer:
        servers:
          - url: h2c://localhost:50051
            scheme: h2c
  middlewares:
    limit:
      buffering:
        maxRequestBodyBytes: 2000000

```
`static.yml`
```yaml
providers:
  file:
    filename: ./dynamic.yml
    watch: true

entryPoints:
  web:
    address: :50052

api:
  insecure: true
```
Add more configuration information here.
