### ISSUE TITLE
Website went down when Docker Network auto-assign 192.168.0.0/16 to service

### ISSUE THREAD

**Issue by venhomelab** [traefik/traefik#9801]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

First, I appreciate your hard work on this project. I have a working Traefik Docker compose file.

When Traefik auto-assigns the ip address to the service, e.g., 192.168.144.5:80, the website goes down. When it is, e.g., 172.18.0.6:80, it goes up. What would be the problem?

I have a health check inside the container, and it seems to be working fine.

I believe the conflict has to be in the proxy server (Traefik) or Docker virtual network.

I tried adding some network configs below, but still it auto assigns to 192.168.0.0/16.
```yaml
networks:
  traefik-network1:
    name: traefik-network1
    external: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
```
The problem takes place when i clone the Project1 folder to Project2

./Project1/docker-compose.yml or will be replicate as ./Project2/docker-compose.yml

I am gladly appreciate your help

### What did you see instead?

The ip auto assigns 192.168.0.0/16 IP range

### What version of Traefik are you using?

traefik version 3.0 and 2.9.8

### Traefik config file
```yaml
version: '3.9'
services:
  traefik:
    #image: traefik:2.9.8
    image: traefik:3.0
    # container_name: traefik-1
    command:
      - "--log.level=DEBUG" # DEBUG, INFO, WARNING, ERROR
      - "--api.dashboard=true" # Traefik Dashboard
      - "--api.debug=true"
      - "--api.insecure=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=web-secure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--serverstransport.insecureskipverify=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.${CF_ACME_RESOLVER}.acme.dnschallenge=true"
      - "--certificatesresolvers.${CF_ACME_RESOLVER}.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.${CF_ACME_RESOLVER}.acme.dnschallenge.delaybeforecheck=10"
      - "--certificatesresolvers.${CF_ACME_RESOLVER}.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      - "--certificatesresolvers.${CF_ACME_RESOLVER}.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.${CF_ACME_RESOLVER}.acme.storage=acme.json"
    #  - "--ping=true"
    restart: unless-stopped
    networks:
      - traefik-network1
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - CF_ACME_RESOLVER=${CF_ACME_RESOLVER}
      - ACME_EMAIL=${ACME_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # So that Traefik can listen to the Docker events
      - ./vol/etc/traefik/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      # basic auth middleware
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${BASIC_AUTH_USR}:${BASIC_AUTH_PASSWD}"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=web-secure"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      # HTTP
      # - "traefik.http.routers.traefik.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`${HOST_TRAEFIK}`)"
        # Redirect traffic to HTTPS
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      # HTTPS
      # - "traefik.http.routers.traefik-secure.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.traefik-secure.entrypoints=web-secure"
      - "traefik.http.routers.traefik-secure.rule=Host(`${HOST_TRAEFIK}`)"

      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=${CF_ACME_RESOLVER}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=${HOST_TRAEFIK}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.${HOST_TRAEFIK}"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik-secure.service=api@internal"
networks:
  traefik-network1:
    name: traefik-network1
    external: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16


```
### App1 Docker compose file
```yaml
version: '3.9'
services:
  #
  # Nginx Unprivileged Setup
  # Make more secure web
  nginx:
    build:
      args:
        user: $APP_USER # or $USER your current machine user
        uid: $APP_UID
        group: $APP_GROUP
        gid: $APP_GID
      context: ./
      dockerfile: ./nginx.Dockerfile
    container_name: ${PROJECT_NAME}-nginx
    image: ${NGINX_IMAGE}
    restart: unless-stopped
    command: /bin/sh -c "
      sed 's/localhost/$APP_HOST/g' /etc/nginx/default.conf.template > /etc/nginx/conf.d/default.conf &&
      sed -i 's/127.0.0.1:9000/php:9000/g' /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'"
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 20s
      retries: 5
      start_period: 10s
      timeout: 10s
   # ports:
   #   - "8080:80"
   #   - "8443:443"
    environment:
      - NGINX_HOST=${APP_HOST}
      - NGINX_UID=${APP_UID}
      - NGINX_USER=${APP_USER}
    volumes:
      - "/etc/localtime:/etc/localtime:ro" # sync time to host machine
      - "./vol/etc/nginx/default.template.conf:/etc/nginx/default.conf.template:rw" # convert to .template to avoid future conflicts
    #  - "./vol/var/www/html:/var/www/html:ro"
      - "${WEB_PATH}:/var/www/html"
    networks:
      - traefik-network
      - internal-network
    depends_on:
      - php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}-nginx.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}-nginx.rule=Host(`${APP_HOST}`)"
      - "traefik.http.middlewares.${PROJECT_NAME}-nginx-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${PROJECT_NAME}-nginx.middlewares=${PROJECT_NAME}-nginx-https-redirect"
      - "traefik.http.routers.${PROJECT_NAME}-nginx-secure.entrypoints=web-secure"
      - "traefik.http.routers.${PROJECT_NAME}-nginx-secure.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.${PROJECT_NAME}-nginx-secure.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}-nginx-secure.tls.certresolver=cloudflare1"
    #  - "traefik.http.routers.${PROJECT_NAME}-nginx-secure.service=nginx"
    #  - "traefik.http.routers.${PROJECT_NAME}-nginx-secure.tls.domains[0].main=*.${DOMAIN}"
      - "traefik.http.services.${PROJECT_NAME}-nginx.loadbalancer.server.port=80"  

  php:
    build:
      args:
        user: $APP_USER # or $USER your current machine user
        uid: $APP_UID
      context: ./
      dockerfile: ./php.Dockerfile
    container_name: ${PROJECT_NAME}-php
    image: ${PHP_IMAGE}
    restart: unless-stopped
    volumes:
      - "${WEB_PATH}:/var/www/html"
      - "./vol/etc/php/php.ini:/usr/local/etc/php/conf.d/newly.ini"
    # ports:
    #   - 9090:9000
    # https://docs.docker.com/compose/compose-file/deploy/
    deploy:
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: any
      resources:
        reservations:
          cpus: '0.2'
          memory: 256m
        limits:
          cpus: '0.8'
          memory: 1024m
    environment:
     - PHP_FPM_USER=${APP_USER}
    networks:
      - internal-network
    labels:
      - "traefik.enable=false"
      - "traefik.docker.network=traefik-network"
      - "traefik.http.services.${PROJECT_NAME}-php.loadbalancer.server.port=9000" 
networks:
  internal-network:
    name: ${PROJECT_NAME}-internal-network
  traefik-network:
    name: traefik-network1
    external: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
```

### If applicable, please paste the log output in DEBUG level

There's no error or warning indication in the DEBUG
