### ISSUE TITLE
Middleware errors not recognized by traeffik

### ISSUE THREAD

**Issue by StefanGeiger** [traefik/traefik#9806]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We have traefik version 2.5.3 running in our cluster. I want to configure the Middleware [errors](https://doc.traefik.io/traefik/middlewares/http/errorpages/). We deploy the following Kubernetes Resource successfully in the cluster
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: failover-site
spec:
  errors:
    status:
      - "500-599"
    query: /
    service:
      name: one-of-our-services
      port: 80
```
First strange thing that we notice, is that the middleware is not shown in the dashboard of traefik. When we, just for testing, deploy an ipwhitelist, this is shown in the dashboard. We netherless try to configure one of our ingresses with this middleware, but get back the following error message
```
middleware "ticket-failover-site@kubernetescrd" does not exist 
```
(where ticket is the namespace we deployed the failure to). On the contrast, with the ipwhitelist, everything works as expected.
Any ideas on the issue here?

### What did you see instead?

Nothing (instead of the middleware) in the traefik dashboard

### What version of Traefik are you using?

2.5.3

### What is your environment & configuration?

We are using traefik helm chart version 10.3.6 with this configuration

```yaml
# Default values.yaml: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

additionalArguments:
  - "--providers.kubernetesingress.allowexternalnameservices=true"
  - "--ping"
  - "--ping.entrypoint=web"

ports:
  traefik:
    healthchecksPort: 8000

service:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  spec:
    loadBalancerIP: ${loadbalancer_ip}
```

### If applicable, please paste the log output in DEBUG level

Error message see above

**Comment by StefanGeiger** [comment]
Hi
thanks for the quick response, will do so

**Comment by cheonyujung** [comment]
I have a same issue. I also tried in v2.9.9. But it's not working too. :(

I think traefik cannot detect middleware maked by kubernetesCRD.

How does fix it ?

```
time="2023-03-23T21:34:39+09:00" level=error msg="middleware \"sally-stripprefix@kubernetescrd\" does not exist" entryPointName=http routerName=sally-simple-apis-bf28f50a59289f6da2cd@kubernetescrd
```

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: simple-apis
  namespace: sally
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: http
  labels:
    ingress: apis
spec:
  entryPoints:
    - http
  routes:
    - match: PathPrefix(`/pinyin`)
      kind: Rule
      middlewares:
        - name: stripprefix
      services:
        - name: pinyin-app
          port: 8000
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: prefixmw
  namespace: sally
spec:
  stripPrefix:
    prefixes:
      - /pinyin
```
