### ISSUE TITLE
Traefik not returning statusText when returning Status code in response

### ISSUE THREAD

**Issue by fluzzi** [traefik/traefik#9819]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm using Traefik as a reverse https proxy for an http server (EVE-NG). when i'm trying to login to the app using traefik it fails, after investigating I found out that when the server respond with status code 200,400 or whichever code it sends, it also send "statusText", example:

![image](https://user-images.githubusercontent.com/5794882/229135455-aca62a00-868d-4f39-976d-1473e149dfb1.png)

### What did you see instead?

When i have Traefik in the middle, traefik sends to the browser the following code without the statusText:

![image](https://user-images.githubusercontent.com/5794882/229135604-df8bc375-c05a-46af-ad49-cd4067f04080.png)

This app is using angular that it looks like matches both status code and status text, so it stuck as it coudn't match the statusText:

function successCallback(response) {
					if (response.status == '200' && response.statusText == 'OK'){
					blockUI();
					$scope.testAUTH("/main");}
				}, 

### What version of Traefik are you using?

2.99

### What is your environment & configuration?

```yaml
# (paste your configuration here)
http:
  routers:
    eve:
      rule: Host(`eve.domain`)
      service: eve
      entryPoints:
        - websecure
      tls:
       certResolver: leresolver

  services:
    eve:
      loadBalancer:
        servers:
          - url: http://eve-ng.lan:80
        passHostHeader: true


```

Add more configuration information here.

version: "3.3"

services:
  traefik:
    restart: unless-stopped
    image: "traefik:2.9"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --providers.file.directory=/data/config/
      - --providers.docker.exposedByDefault=false
      - --providers.file.watch=true
      - --providers.docker
      - --api
      - --certificatesresolvers.leresolver.acme.storage=/data/acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true
      - --certificatesresolvers.leresolver.acme.email=mail@gmail.com
      - --serversTransport.insecureSkipVerify=true
      #- --log.filePath=/data/traefik.log
      #- --log.level=DEBUG
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/fluzzi32/docker-compose/traefik2/:/data"
    networks:
      - web
    container_name: traefik2
    labels:
      # redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"

networks:
  web:
    external: true
