### ISSUE TITLE
Exclude tracing for particular service

### ISSUE THREAD

**Issue by suikast42** [traefik/traefik#9825]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I am looking for a possibility to propagate tracing for particular services.

My tracing config:
```toml
[tracing]
#  [tracing.zipkin]
#    httpEndpoint = "http://tempo-zipkin.service.consul:9411/api/v2/spans"
#    sameSpan = true
#    id128Bit = true
  [tracing.jaeger]
    samplingServerURL = "http://tempo-jaeger-http.service.consul:14268/sampling"
    propagation  = "jaeger"
    gen128Bit = true
  [tracing.jaeger.collector]
    endpoint = "http://tempo-jaeger-http.service.consul:14268/api/traces?format=jaeger.thrift"
```

My idea was that I delete the tracing headers with midelware:

```toml 
[http.middlewares]
  [http.middlewares.exclude-trace]
    # Define the middleware to exclude tracing headers
    [http.middlewares.exclude-trace.headers]
      # Delete trace headers. See https://github.com/opentracing/specification/blob/master/rfc/trace_identifiers.md
      #  ["X-Request-Id", "X-B3-TraceId", "X-B3-SpanId", "X-B3-ParentSpanId", "X-B3-Sampled", "X-B3-Flags", "traceparent", "tracestate"]
       [http.middlewares.exclude-trace.headers.customRequestHeaders]
        X-Request-Id =""
        X-B3-TraceId =""
        X-B3-SpanId =""
        X-B3-ParentSpanId =""
        X-B3-Sampled =""
        X-B3-Flags =""
        traceparent =""
        tracestate =""
        uber-trace-id =""
```

Add this middleware to the service route
```toml 
# Route to nomad ui
  [http.routers.nomad]
    entryPoints = ["https"]
    rule = "Host(`nomad.{{tls_san}}`) "
    service = "nomad"
     middlewares = ["traefik-forward-auth@consulcatalog","exclude-trace"]
    [[http.routers.nomad.tls.domains]]
      sans = ["nomad.{{tls_san}}"]
```

But that approach does not works. The trace is evertime captured. 

Is it in principle possible to achive this ?
