### ISSUE TITLE
Reverse proxy is not working for 

### ISSUE THREAD

**Issue by Jim0530** [traefik/traefik#9838]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I run traefik via docker-compose and use networkmode (host)
I hope traefik can help me proxy pass request to http://chaosadvisor.iteoa-test.ftest.com/ (a service which can be touched in my env, and it's a service in K8s) when accessing localhost/api
and it turns out 404 when i access traefik.

### What did you see instead?

when accessing localhost/api
404 not found
page cannot be found

### What version of Traefik are you using?

v2.9

### What is your environment & configuration?

```yaml
global:
  checkNewVersion: false
 
entryPoints:
  web:
    address: ":80"

api:
  insecure: true
  debug: true
accessLog:
  filePath: "/etc/traefik/access.log"
  bufferingSize: 100
providers:
  file:
    directory: /etc/traefik
    watch: true

log:
  level: DEBUG
```

docker-compose
```yaml
version: '3'


services:
  traefik:
    image: traefik:v2.9
    ports:
      - "80:80"  
      - "8080:8080"
    volumes:
      - $PWD:/etc/traefik
    network_mode: "host"
```

dynamic_conf.yaml
```yaml
http:
  routers:
    # Define a connection between requests and services
    my-router:
      rule: "PathPrefix(`/api`)"
      middlewares: test-replacepath
      service: jim
  services:
      # Define how to reach an existing service on our infrastructure
      jim:
        loadBalancer:
          servers:
            - url: "http://teacctmgmt.iteoa-test.ftest.com/"
  middlewares:
      test-replacepath:
        replacePath:
          path:  "/api/v1/docs"
```
Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

127.0.0.1 - - [13/Apr/2023:07:51:52 +0000] "GET /qest/ HTTP/1.1" 404 0 "-" "-" 1 "my-router3@file" "http://chaosadvisor.iteoa-test.ftest.com/"
