### ISSUE TITLE
Access log has many items with "0" or "-" status code

### ISSUE THREAD

**Issue by taoyouh** [traefik/traefik#9842]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I used the Traefik instance bundled with k3s as an ingress controller. I enabled the access log with helm `values.yaml`. I wish to check the response status code in my access log to see if my services are working correctly. I expect the status code to be 2xx, 3xx, 4xx or 5xx.

### What did you see instead?

I see some lines with status code "0" or "-". If I try the HTTP endpoints from my local browser, there could be some log entries with "0" status code even if the endpoint loads successfully in my browser.

> {IP address hidden} - - [15/Apr/2023:09:06:48 +0000] "PUT /gomoku-api/board-v2/24895/computer-move/1 HTTP/2.0" **0** **0** "-" "-" 70159 "websecure-taoyouh-ingress-4980e08814b53bd31f55@kubernetescrd" "http://10.46.0.57:80" 2676ms
> {IP address hidden} - - [15/Apr/2023:08:27:57 +0000] "GET /ping HTTP/1.1" **0** **0** "-" "-" 69237 "ping@internal" "-" 0ms
> {IP address hidden} - - [15/Apr/2023:08:18:45 +0000] "GET /doc/xml/version.xml HTTP/1.1" **-** **-** "-" "-" 69019 "-" "-" 0ms
> {IP address hidden} - - [15/Apr/2023:08:17:34 +0000] "GET /wp-content/plugins/wp-code-highlightjs/highlight.common.pack.js?ver=0.6.2 HTTP/2.0" **0** **0** "-" "-" 68990 "websecure-taoyouh-ingress-b8c30380ce137c845296@kubernetescrd" "http://10.46.0.61:80" 13ms

### What version of Traefik are you using?

Version:      2.9.4
Codename:     banon
Go version:   go1.19.2
Built:        2022-10-27T18:44:34Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

/var/lib/rancher/k3s/server/manifests/traefik.yaml
```yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik-crd
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-crd-20.3.1+up20.3.0.tgz
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-20.3.1+up20.3.0.tgz
  set:
    global.systemDefaultRegistry: ""
  valuesContent: |-
    podAnnotations:
      prometheus.io/port: "8082"
      prometheus.io/scrape: "true"
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    priorityClassName: "system-cluster-critical"
    image:
      name: "rancher/mirrored-library-traefik"
      tag: "2.9.4"
    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    service:
      ipFamilyPolicy: "PreferDualStack"
```

/var/lib/rancher/k3s/server/manifests/traefik-config.yaml
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      spec:
        externalTrafficPolicy: Local
    logs:
      access:
        enabled: true
```
