### ISSUE TITLE
acme.json permission issue kubernetes + digital ocean 

### ISSUE THREAD

**Issue by KursLabIgor** [traefik/traefik#9853]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm quite new guy in kebernetes world. Idea following: cloudflare + traefik(TLS)+ kubernetes
So I found guide here: 
https://traefik.io/blog/install-and-configure-traefik-with-helm/ 

1. Install kubernetes cluster on DO `Kubernetes 1.26.3-do.0`
2. Install helm `version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.20.2"}`
3. Add official traefik repo to helm `https://traefik.github.io/charts `
4. Create custom values file. 
5. Run helm: `helm install traefik traefik/traefik --namespace=traefik --values=traefik/traefik_values.yaml`
6. Pod started I see in logs that no permissions to `/data/acme.json`
7. Applied workaround.  
8. Pod doesnt start.

Workaround mentioned [here](https://github.com/traefik/traefik-helm-chart/issues/164) not helped to me.

Any advice appreciate. 

### What did you see instead?

Always init container fails with command: Permission denied 
```
k logs traefik-5b97f7fc54-s6wn4 -c volume-permissions -n traefik
touch: /data/acme.json: Permission denied
```

### What version of Traefik are you using?

Traefik Proxy v2.9.10

### What is your environment & configuration?

```yaml
---
globalArguments:
  - --global.checknewversion=false
  - --global.sendanonymoususage=false
additionalArguments:
  - --entrypoints.websecure.http.tls.certresolver=cloudflare
  - --entrypoints.websecure.http.tls.domains[0].main=i**.org
  - --entrypoints.websecure.http.tls.domains[0].sans=*.i**r.org
  - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
  - --certificatesresolvers.cloudflare.acme.email=**@gmail.com
  - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
  - --certificatesresolvers.cloudflare.acme.storage=/data/acme.json

ports:
  web:
    port: 8080
    redirectTo: websecure
  websecure:
    port: 8443
    certResolver: cloudflare

env:
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        key: email
        name: cloudflare-api-credentials
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        key: apiKey
        name: cloudflare-api-credentials
ingressRoute:
  dashboard:
    enabled: false

persistence:
  enabled: true
  name: ssl-certs
  path: /data
  size: 1Gi
  
deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:1.31.1
      command: ["sh", "-c", "chmod -Rv 777 /data/* && touch /data/acme.json && chmod -Rv 600 /data/* && chown 65532:65532 /data/acme.json"]
      volumeMounts:
        - name: ssl-certs
          mountPath: /data
```
