### ISSUE TITLE
ClientIP in TCP route does not seem to work

### ISSUE THREAD

**Issue by vladimirtiukhtin** [traefik/traefik#9856]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Declared a route like this
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mariadb
spec:
  entryPoints:
    - mariadb
  routes:
    - match: ClientIP(`0.0.0.0/0`)
      services:
        - name: mariadb
          port: mariadb
```

So it appears green in traefik dashboard. Then curl it

### What did you see instead?

My understanding is that TCP route should forward request to mariadb but instead it falls back to http like it did not find a match. MariaDB does not support SNI, so I need plain TCP

### What version of Traefik are you using?

2.8.8

### What is your environment & configuration?

```sh
      "--entrypoints.mariadb",
      "--entrypoints.mariadb.address=:3306"
```
