### ISSUE TITLE
how to connect to https backend？

### ISSUE THREAD

**Issue by kasini3000** [traefik/traefik#9864]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I use traifik to connect "http://test123.com/baidu" to the HTTP backend normally.
How to connect to the HTTPS backend? Is there a way to not require an HTTPS certificate?

chrome --> http://test123.com/baidu  -->  https://www.baidu.com 

Is it necessary "/" at the tail on toml service field ?

why I cannot register to traifik community ?
After i entering the email and clicking to establish an account, why didn't respond?

### What did you see instead?

change backend to other,will return http 500,403,400,508

### What version of Traefik are you using?

traefik 2.9.10

### What is your environment & configuration?

```toml
---a.toml---

[serversTransport]
  insecureSkipVerify = true
  
[http]
  [http.middlewares]
    [http.middlewares.redirect2https.redirectScheme]
      scheme = "https"
      port = 443


[http.services]
  [http.services.my-service]
  [http.services.my-service.loadBalancer]
  servers = [{url = "https://www.baidu.com/"}]
  
[http.routers]
  [http.routers.my-router]
    rule = "Host(`test123.com`) && PathPrefix(`/baidu`)"
    service = "my-service"
    #middlewares = "redirect2https"
    entryPoints = "web"


```
