### ISSUE TITLE
Middleware gets error when k8s secret is deleted

### ISSUE THREAD

**Issue by longquan0104** [traefik/traefik#9870]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Delete a secret. For example with the **_basic auth_** middleware, I delete the _**user**_ secret. I expect that the middleware was loaded successfully before, when I delete the secret, the middleware won't meet any error. Or there should be a preparing / planning update for checking errors before applying the new config.

### What did you see instead?

The _**basic auth**_ middleware is unavailable

### What version of Traefik are you using?

2.9.5

### What is your environment & configuration?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-auth-middleware
  namespace: default
spec:
  basicAuth:
    secret: test-auth-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: test-auth-secret
  namespace: default

data:
  users: |2
    dGVzdDokYXByMSRINnVza2trVyRJZ1hMUDZld1RyU3VCa1RycUU4d2ovCnRlc3QyOiRhcHIxJGQ5
    aHI5SEJCJDRIeHdnVWlyM0hQNEVzZ2dQL1FObzAK

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: test-auth-ingress-route
  namespace: default
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: ((Host(`test.mydomain.com`)) && (PathPrefix(`/`)))
    middlewares:
    - name: test-auth-middleware
      namespace: default
    services:
    - name: account-webapp
      port: http
  
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: account-webapp
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-08-04T08:54:55Z"
  labels:
    app.kubernetes.io/component: api-service
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: test-api
    app.kubernetes.io/part-of: ""
  name: account-webapp
  namespace: default
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9500
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: test
    app.kubernetes.io/part-of: ""
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

```
time="2023-04-26T05:03:42Z" level=error msg="Error while reading basic auth middleware: secret 'default/test-auth-secret' not found" providerName=kubernetescrd middlewareName=default-test-auth-middleware
time="2023-04-26T05:03:42Z" level=error msg="middleware \"default-test-auth-middleware@kubernetescrd\" does not exist" entryPointName=web routerName=default-test-auth-ingress-route-7b94633cc65f4c25b3b3@kubernetescrd
```
