### ISSUE TITLE
WebDAV PUT fails since v2.9.9

### ISSUE THREAD

**Issue by coilock** [traefik/traefik#9873]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am trying to use a C# mobile app on Android to PUT a file via WEBDAV onto my Nextcloud Hub 4 (26.0.1) container.

### What did you see instead?

Since my last upgrade of traefik, this fails with the error message: "The server returned an invalid or unrecognized response."

The Stream between Traefik and Nextcloud is looking like this:
```
PUT /remote.php/dav/files/REDACTED HTTP/1.1
Host: REDACTED
User-Agent: Mozilla/5.0 (REDACTED)
Content-Length: 2586624
Authorization: Basic REDACTED
Content-Type: application/octet-stream
Cookie: REDACTED; oc_sessionPassphrase=REDACTED; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true
Expect: 100-continue
X-Forwarded-For: REDACTED
X-Forwarded-Host: REDACTED
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: 0b0db0fce336
X-Real-Ip: REDACTED
Accept-Encoding: gzip

HTTP/1.1 100 Continue

HTTP/1.1 400 Bad Request
Date: Tue, 25 Apr 2023 14:37:24 GMT
Server: Apache/2.4.56 (Debian)
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: noindex, nofollow
X-XSS-Protection: 1; mode=block
X-Powered-By: PHP/8.1.18
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Security-Policy: default-src 'none';
Content-Length: 461
Connection: close
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
  <s:message>Erwartete Dateigröße von 2586624 bytes, aber 0 bytes gelesen (vom Nextcloud-Client) und geschrieben (in den Nextcloud-Speicher). Dies kann entweder ein Netzwerkproblem auf der sendenden Seite oder ein Problem beim Schreiben in den Speicher auf der Serverseite sein.</s:message>
</d:error>
```

A flow graph of the stream: 
![image](https://user-images.githubusercontent.com/8780373/234677297-05f53b11-390e-4d7f-82df-382571e0fa21.png)

### What version of Traefik are you using?

The problem occurs in every version since (including):
```
Version:      2.9.9
Codename:     banon
Go version:   go1.20.2
Built:        2023-03-21T15:52:28Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

The Environment is based on docker-compose with the following configuration.

traefik.toml:
```
[entryPoints.web]
  address = ":80"
  [entryPoints.web.http.redirections.entryPoint]
    to = "web-secure"
    scheme = "https"
[entryPoints.web-secure]
  address = ":443"
[entryPoints.matrix-federation]
  address = ":8448"
[entryPoints.ldaps]
  address = ":636"

[providers.docker]
  watch = true
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

[providers.file]
  directory = "dynamicConf"

[api]
  dashboard = true

[accessLog]

[log]
  filePath = "/traefik.log"
  level = "DEBUG"

[certificatesResolvers.boehnet-letsencrypt.acme]
  email = "REDACTED"
  storage = "acme.json"
  [certificatesResolvers.REDACTED-letsencrypt.acme.tlsChallenge]

[serversTransport]
  insecureSkipVerify = true

[pilot]
    token = "REDACTED"
```

dynamicConf/api.toml:
```
[http.routers.api]
  rule = "Host(`REDACTED`)"
  entrypoints = ["web-secure"]
  service = "api@internal"
  middlewares = ["auth", "lanfilter"]
  [http.routers.api.tls]
    certResolver = "REDACTED-letsencrypt"

[http.middlewares.auth.basicAuth]
  users = [
    "root:REDACTED",
    "REDACTED"
  ]
```

dynamicConf/lanfilter.toml:
```
[http.middlewares]
  [http.middlewares.lanfilter.ipWhiteList]
    sourceRange = ["127.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12"]
```

dynamicConf/tls.yml:
```
tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 # TLS 1.2
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305  # TLS 1.2
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384   # TLS 1.2
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305    # TLS 1.2
        - TLS_AES_256_GCM_SHA384                  # TLS 1.3
        - TLS_CHACHA20_POLY1305_SHA256            # TLS 1.3
        - TLS_FALLBACK_SCSV                       # TLS FALLBACK
      curvePreferences:
        - secp521r1
        - secp384r1
    modern:
      minVersion: VersionTLS13
```

Labels of Nextcloud container:
```
labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
      - traefik.http.routers.nextcloud.rule=Host(`REDACTED`)
      - traefik.http.routers.nextcloud.entrypoints=web-secure
      - traefik.http.routers.nextcloud.tls.certresolver=boehnet-letsencrypt
      - traefik.http.middlewares.nextcloudredir.redirectregex.permanent=true
      - traefik.http.middlewares.nextcloudredir.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav
      - traefik.http.middlewares.nextcloudredir.redirectregex.replacement=https://$$1/remote.php/dav/
      - traefik.http.middlewares.nextcloudsts.headers.stsincludesubdomains=false
      - traefik.http.middlewares.nextcloudsts.headers.stspreload=true
      - traefik.http.middlewares.nextcloudsts.headers.stsseconds=31536000
      - traefik.http.middlewares.nextcloudsts.headers.isdevelopment=false
      - traefik.http.routers.nextcloud.middlewares=nextcloudredir,nextcloudsts
```

### If applicable, please paste the log output in DEBUG level

This line appears in the log, at the time the request fails:
`time="2023-04-26T18:46:25Z" level=debug msg="'499 Client Closed Request' caused by: context canceled"`
