### ISSUE TITLE
HTTPRouteStatus resource is not being updated

### ISSUE THREAD

**Issue by romantomjak** [traefik/traefik#9884]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm trying to make it so that [ExternalDNS](https://github.com/kubernetes-sigs/external-dns) updates DNS records from the [HTTPRoute resource](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRoute), but all I get in ExternalDNS logs is:
```
No endpoints could be generated from HTTPRoute monitoring/prometheus
```

I suspect it's because there is no address assigned to the Gateway and it cannot figure out what IP address to use for the DNS record:

```sh
$ kubectl -n gateway-ingress get gateway public-gw
NAME        CLASS     ADDRESS   PROGRAMMED   AGE
public-gw   traefik                          107m
```

### What did you see instead?

When Traefik updates the gateway status, it [nullifies the address field](https://github.com/traefik/traefik/blob/619045eb4bbe842be550fd16d67dc7c8eb61ebe8/pkg/provider/kubernetes/gateway/kubernetes.go#L513).

Ideally, Traefik would grab the assigned IP/Hostname from the exposed `type: LoadBalancer` service and then update the gateway with those addresses, but that may be a substantial amount of work.

Alternatively, Traefik could perhaps just copy the addresses from the Gateway spec (if they are set)?
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: public-gw
  namespace: gateway-ingress
spec:
  gatewayClassName: traefik
  addresses:
    - type: IPAddress
      value: a.b.c.d 
  listeners:
    ...
```

At minimum, it should at least stop nullifying it for now so that you can at least `kubectl edit` it and set it manually.

### What version of Traefik are you using?

2.10.1

### What is your environment & configuration?

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: gateway-ingress
spec:
  selector:
    matchLabels:
      app: traefik-lb
  template:
    metadata:
      labels:
        app: traefik-lb
    spec:
      serviceAccountName: traefik-controller
      containers:
        - name: traefik
          image: traefik:v2.10.1
          args:
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --experimental.kubernetesgateway
            - --providers.kubernetesgateway
            - --api.dashboard=true
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
```

**Comment by romantomjak** [comment]
I'm happy to take this on as a personal crusade if we can align on what's the expected behaviour here 👍

**Comment by rtribotte** [comment]
Hello @romantomjak,

Thanks for reporting this!

> When Traefik updates the gateway status, it [nullifies the address field](https://github.com/traefik/traefik/blob/619045eb4bbe842be550fd16d67dc7c8eb61ebe8/pkg/provider/kubernetes/gateway/kubernetes.go#L513).

At a glance, I'm not sure that Traefik nullifies the addresses field, because it initializes the gateway status with empty `Addresses` slice:

```go
// As Status.Addresses are not implemented yet, we initialize an empty array to follow the API expectations.
gatewayStatus := gatev1alpha2.GatewayStatus{
	Addresses: []gatev1alpha2.GatewayAddress{},
}
```

Isn't it that the slice should contain at least one address? (I did not verify that, I'm just wondering)

> At minimum, it should at least stop nullifying it for now so that you can at least kubectl edit it and set it manually.

This would be indeed the easiest thing to do, what do you suggest?

**Comment by romantomjak** [comment]
Yep, you're right - it doesn't! I had assumed that it does that because the status resource did not keep any of my changes after editing. Turns out, you need to specify `--subresource='status'` to the kubectl edit command in order for it to make changes to the status resource 🤷‍♀️ 

I did some more digging tonight and managed to get it to work with the following config:

```yaml
# kubectl -n gateway-ingress edit gateway public-gw --subresource='status'
status:
  addresses:
  - type: IPAddress
    value: a.b.c.d
```

```yaml
# kubectl -n monitoring edit httproute prometheus --subresource='status' 
status:
  parents:
  - controllerName: traefik.io/gateway-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: public-gw
      namespace: gateway-ingress
    conditions:
    - type: Accepted
      status: "True"
      # the values below are not used by externaldns, but mandatory in k8s API, so
      # I just stubbed them out with some semi sensible values
      message: No error found
      reason: ListenerReady
      lastTransitionTime: "2023-05-03T22:08:18Z"
```

So, I _think_ the actual problem is that Traefik is not updating GatewayStatus and HTTPRouteStatus resources. Sorry for the roller coaster 🎢 

I'll have a read through the spec and see if I can prepare a PR to update the status resources 👌
