### ISSUE TITLE
setting  traefik.ingress.kubernetes.io/service.nativelb: "true"  does not take effect

### ISSUE THREAD

**Issue by fumenglin** [traefik/traefik#9885]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

my ingress 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/service.nativelb: "true"
spec:
  rules:
  - http:
      paths:
      - path: /hostname-edge
        pathType: Prefix
        backend:
          service:
            name: hostname-edge
            port:
              number: 9376
```
but visit Ip is Pods Ip，not the serviece Ip;
How do I configure my ingress files ?

### What did you see instead?

![1683271979827](https://user-images.githubusercontent.com/15940670/236400619-c4440f56-dbd8-4b4a-96e5-28dc3d616bb8.png)

time="2023-05-05T07:26:37Z" level=debug msg="'502 Bad Gateway' caused by: dial tcp 172.18.0.1:9376: connect: no route to host"

### What version of Traefik are you using?

Version:      2.10.1
Codename:     saintmarcelin
Go version:   go1.20.3
Built:        2023-04-27T14:52:35Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/service.nativelb: "true"
spec:
  rules:
  - http:
      paths:
      - path: /hostname-edge
        pathType: Prefix
        backend:
          service:
            name: hostname-edge
            port:
              number: 9376
