### ISSUE TITLE
customFrameOptionsValue doesn't override frameDeny

### ISSUE THREAD

**Issue by donihalim** [traefik/traefik#9888]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have `frameDeny: true` on secureHeaders middlewares, I want to override that headers using `customFrameOptionsValue: sameorigin` however it doesn't override the X-Frame-Options

### What did you see instead?

I still see 'X-Frame-Options' set to 'deny' on the chrome dev tool

### What version of Traefik are you using?
```
Version:      2.10.1
Codename:     saintmarcelin
Go version:   go1.20.3
Built:        2023-04-27T14:52:35Z
OS/Arch:      linux/amd64
```
### What is your environment & configuration?
```
http:
  middlewares:
    frameOptionsSameOrigin:
      headers:
        customFrameOptionsValue: "sameorigin"

  routers:
    code:
      service: code
      rule: Host(`code.mydomain.com`)
      entrypoints:
        - websecure
      tls: true
      middlewares:
        - authelia@docker
        - frameOptionsSameOrigin@file

  services:
    code:
      loadbalancer:
        servers:
          - url: "http://10.8.0.10:8080"
```
