### ISSUE TITLE
k8s traefik ingressroute tls secret update not working 

### ISSUE THREAD

**Issue by shengkaixuan** [traefik/traefik#9893]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

in k8s cluster, created a ingressroute with tls secret set ,
when the secret updated, the web is still using the old certificate

### What did you see instead?

when updated the tls secret, ingressroute seems like no working ,still using the old certificate

### What version of Traefik are you using?

traefik:v2.9.7

### What is your environment & configuration?

```yaml
# (paste your configuration here)
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fcs-beta-minio
  namespace: ccs
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`console-minio-beta.test.cloud`)
    services:
    - name: ccs-minio
      port: 9001
  - kind: Rule
    match: Host(`api-minio-beta.test.cloud`)
    services:
    - name: ccs-minio
      port: 9000
  tls:
    secretName: test-cloud-tls

```

Add more configuration information here.
