### ISSUE TITLE
Entrypoints are truncated in the dashboard when listening to a specific interface

### ISSUE THREAD

**Issue by koke** [traefik/traefik#9899]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have Traefik listening on a specific interface (`--entrypoints.web.address=192.168.1.10:80`). 

### What did you see instead?

When I visit the dashboard, the entrypoints section contains truncated text (`192.1...`) instead of just the port (`:80`).

![Screenshot 2023-05-19 at 12 37 17](https://github.com/traefik/traefik/assets/8739/07d0ee8b-0cc3-4c48-b954-9345c370eee9)

### What version of Traefik are you using?

```
Version:      2.10.1
Codename:     saintmarcelin
Go version:   go1.20.3
Built:        2023-04-27T14:52:35Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--entrypoints.web.address=192.168.1.10:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=192.168.1.10:443"
      - "--api"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: unless-stopped
```
