### ISSUE TITLE
Support for ALPN('xmpp-client') and ALPN('xmpp-server')

### ISSUE THREAD

**Issue by saqeria** [traefik/traefik#9904]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hi,
Support for ALPN has been added in PR [#8913](https://github.com/traefik/traefik/pull/8913). However, it does not include ALPN types 'xmpp-client' and 'xmpp-server'. It has been requested [before](https://github.com/traefik/traefik/issues/7906#issuecomment-1008075126) and my understanding was that it has also been implemented already. However, upon testing, I came to the conclusion that it does not work yet. [Here](https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids) are all the ALPN protocols including 'xmpp-client' and 'xmpp-server'

**Traefik tcp router/service config:**
```
tcp:
  routers:
    xmpps-client:
      entryPoints:
        - websecure
        - xmpp-client-dtls
      service: xmpps-client-ejabberd
      rule: "HostSNI(`example.com`) && ALPN(`xmpp-client`)"
      tls:
        options: default
        passthrough: true
    xmpps-server:
      entryPoints:
        - xmpps-server
        - websecure
      service: xmpps-server-ejabberd
      rule: "HostSNI(`example.com`) && ALPN(`xmpp-server`)"
      tls:
        options: default
        passthrough: true

  services:
    xmpps-client-ejabberd:
      loadBalancer:
        proxyProtocol:
          version: 2
        servers:
          - address: 10.1.4.100:5223
    xmpps-server-ejabberd:
      loadBalancer:
        proxyProtocol:
          version: 2
        servers:
          - address: 10.1.4.100:5270

tls:
  options:
    default:
      alpnProtocols:
        - xmpp-client
        - xmpp-server
        - http/1.1
        - h2
```

**Traefik log shows:**
```
level=debug msg="http: TLS handshake error from X.X.X.X:57750: tls: client requested unsupported application protocols ([xmpp-client])"
level=debug msg="http: TLS handshake error from X.X.X.X:57760: tls: client requested unsupported application protocols ([xmpp-client])"
```

I want to use ALPN(xmpp-client) and ALPN(xmpp-server) as to route the correct traffic to the correct container (xmpp server container). As these ALPN protocols are not supported, I can't multiplex on 443 main domain. As described [here](https://xmpp.org/extensions/xep-0368.html) and [here](https://wiki.xmpp.org/web/Tech_pages/XEP-0368), the server should set hostsni and ALPN to correctly use xmpp over tls (443).
