### ISSUE TITLE
Plugins disabled in Kubernetes

### ISSUE THREAD

**Issue by paulyhedral** [traefik/traefik#9911]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm trying to enable and install plugins.

### What did you see instead?

```
time="2023-05-25T14:36:04Z" level=error msg="Plugins are disabled because an error has occurred." error="mkdir plugins-storage: read-only file system"
```

In the configuration snippet below, I have mounted an `emtpyDir` volume in `/usr/local/bin`, because the documentation states that the plugins are expected to be found within the same directory as the binary. Note that this error occurs also if there is no volume mount at all, or if it is pointed at any arbitrary location.

### What version of Traefik are you using?

```sh
~ $ traefik version
Version:      2.10.1
Codename:     saintmarcelin
Go version:   go1.20.3
Built:        2023-04-27T14:52:35Z
OS/Arch:      linux/amd64
```

```
image: docker.io/traefik:v2.10
```

### What is your environment & configuration?

```sh
--accesslog 
--api.dashboard 
--api.insecure 
--entrypoints.metrics.address=:9100/tcp 
--entrypoints.traefik.address=:9000/tcp 
--entryPoints.web.address=:8000/tcp 
--entrypoints.web.forwardedHeaders.insecure 
--entrypoints.web.ProxyProtocol.insecure 
--entrypoints.websecure.address=:8443/tcp 
--entrypoints.websecure.http.tls=true 
--global.checknewversion=false 
--global.sendanonymoususage 
--log.level=INFO 
--metrics 
--metrics.prometheus 
--metrics.prometheus.entrypoint=metrics 
--ping 
--providers.kubernetescrd 
--providers.kubernetesingress 
--providers.kubernetesgateway 
--experimental.kubernetesgateway 
--experimental.plugins.geoBlock.modulename=github.com/PascalMinder/geoblock 
--experimental.plugins.geoBlock.version=v0.2.5 
--experimental.plugins.addTraceId.modulename=github.com/trinnylondon/traefik-add-trace-id 
--experimental.plugins.addTraceId.version=v0.1.5 
--experimental.plugins.correlationId.modulename=github.com/soulbalz/correlationid 
--experimental.plugins.correlationId.version=v1.0.0 
--tracing.zipkin 
--tracing.zipkin.httpEndpoint=http://jaeger-collector.observability:9411/api/v2/spans 
--certificatesresolvers.http.acme.email=REDACTED
--certificatesresolvers.http.acme.storage=/data/acme.json 
--certificatesresolvers.http.acme.httpchallenge.entrypoint=web 
--certificatesresolvers.dreamhost.acme.dnschallenge.provider=dreamhost 
--certificatesresolvers.dreamhost.acme.email=REDACTED
--certificatesresolvers.dreamhost.acme.storage=/data/acme.json 
--certificatesresolvers.linode.acme.dnschallenge.provider=linode 
--certificatesresolvers.linode.acme.email=REDACTED
--certificatesresolvers.linode.acme.storage=/data/acme.json
```

Add more configuration information here.

Volumes:
```yaml
          volumeMounts:
            - name: data
              mountPath: /data
            - name: plugins
              mountPath: /usr/local/bin/plugins-storage
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: data
          emptyDir: {}
        - name: plugins
          emptyDir: {}
        - name: tmp
          emptyDir: {}
```
