### ISSUE TITLE
plugin: unknown plugin type: apiKey

### ISSUE THREAD

**Issue by yidongw** [traefik/traefik#9915]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

use the file from [here](https://doc.traefik.io/traefik-enterprise/middlewares/apikey/#advanced-configuration-example) 
and did `kubectl apply -f apiKey.yaml`

### What did you see instead?

logs show 
```
time="2023-05-26T10:21:28Z" level=error msg="plugin: unknown plugin type: apiKey" entryPointName=websecure routerName=xxxxx
```

### What version of Traefik are you using?

 traefik helmfile chart 23.0.1

### What is your environment & configuration?

```yaml
logs:
  general:
    level: DEBUG
  access:
    enabled: true
ports:
  websecure:
    tls:
      enabled: true
providers:
  kubernetesIngress:
    publishedService:
      enabled: true
ingressRoute:
  dashboard:
    enabled: false
```
