### ISSUE TITLE
failover option on TraefikService Kubernetes CRD

### ISSUE THREAD

**Issue by jjsiv** [traefik/traefik#9919]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Currently the failover load balancing feature is only available with the file provider:
https://doc.traefik.io/traefik/routing/services/#failover-service
Would be nice to have it configurable on the TraefikService CRD as well. This would also require implementing healthchecks on the Kubernetes CRD which would benefit mirroring & wrr too.

I'd be interested in contributing this in case it is agreed that this would be worthwhile enhancement.

**Comment by Kriys94** [comment]
This is clearly something I would be very interested

**Comment by jainasanthosh2023** [comment]
Yes we would definitely need this feature crd, configuring failover for each service through static file provide is tedious, is there any workaround like, in file provider like for all my ingress routes to provide common failover service. My idea is point failover service to second cluster's ingress controller as we have multi cluster deployments (east, west) for all my applications.

**Comment by jainasanthosh2023** [comment]
Hi All,

Meanwhile, I would like to define a TraefikService with failover using file provider config mount within same cluster of 
across kubernetes native service A main to service B fallback (which sits in different namespace) and would like to refer this TraefikService from TraefikIngressRoutes using @file. 

Do we have any working example or any reference for full example of this use case?.

**Comment by jainasanthosh2023** [comment]
Hi All,

Kubernetes version 1.21
Traefik Version 2.10

I have done bit progress and found 2 of the options to achieve failover for all the applications that deployed in multi cluster(east/west).
But I would need someone to suggest overall sustainabilty of my solutions w.r.t maintinance overhead.

**_Option - 1_**

**Cluster A -> app-a --> IngressRoute CRD --> error-on-page middleware (502 bad gateway) --> Route to Cluster B ingress Load Balancer --> Cluster B IngressRoute CRD.**

**_Option - 2_**

**Using Official Failover File Provider strategy which involves every time new application is added to cluster, someone or some process needs to add an entry in Traefik controller config dir path.**

```
Flags added to traefik deployment:
        - --providers.file.directory=/config
        - --providers.file.watch=true
```

Using go templating..

kubectl get cm dynamic-template-config -oyaml
```
apiVersion: v1
data:
  cm-template.yaml: |-
    {{$services := dict}}
    {{$_ := set $services "nginx-deploy-main" "traefik2-demo"}}
    {{$_ := set $services "nginx-deploy-demo2" "traefik2-demo2"}}  [--For every new application we need to add an entry here, which is still not obvious, will question the maintainance overhead also -- resource locking when multiple new deployments happens at same time.]
    http:
      services:
    {{range $app, $namespace := $services}}

            {{$app}}-with-failover:
              failover:
                service: {{$app}}-main
                fallback: fallback

            {{$app}}-main:
              loadBalancer:
                healthCheck:
                  path: /
                  interval: 10s
                  timeout: 3s
                servers:
                - url: "http://{{$app}}.{{$namespace}}.svc.cluster.local/"
    {{end}}
            fallback:
              loadBalancer:
                servers:
                - url: "http://traefik2-east-ui.mycompany.corp/"  -- routing the traefik to opposite cluster ingress load balncer.
kind: ConfigMap
metadata:
  name: dynamic-template-config
  namespace: traefik
```


**_Option - 2A (Under evaluation)_**

I would like to try creating config file for each application and mount to traefik /config directory and as individual file, which is a again a challenging task, since i can create configmap in traefik namespace but i may not be able to be mount each time without modifying volumeMounts. May be I am not aware if any other best practices we can use to achieve this.


> Option 1 and 2 are working fine, but we feel like option 1 better over  option 2 due to less maintaince over head. I would get our commuinity assistance/suggestions on this option 1. Happy to discuss further.
