### ISSUE TITLE
Minimal example for traefik with dashboard and basic auth

### ISSUE THREAD

**Issue by lonix1** [traefik/traefik#9925]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm trying to implement traefik with basic auth to protect the dashboard. I wrote a minimal example, but it doesn't work.

I generated the password like this:
````console
$ htpasswd -nb admin password
admin:$apr1$vO3/IDvg$JrbhU9NSQub83/mQu9/fP1
````

`docker-compose.yml`
````yml
services:
  traefik:
    image: traefik:v2.10.1
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro
````

`traefik.yml`
````yml
providers:
  docker:
    exposedByDefault: false
    network: web
    watch: true
  file:
    filename: /etc/traefik/traefik_dynamic.yml
    watch: true

entryPoints:
  web:
    address: ":80"

api:
  dashboard: true
  insecure: true
````

`traefik_dynamic.yml`
````yml
http:
  middlewares:
    dashboard-auth:
      basicAuth:
        users:
          - "admin:$apr1$vO3/IDvg$JrbhU9NSQub83/mQu9/fP1"
  routers:
    api:
      rule: "Host(`localhost`)"
      entrypoints: ["web"]
      middlewares: ["dashboard-auth"]
      service: "api@internal"
````

I can browse to `http://myserver/dashboard/` which loads without errors.

*But it does not ask for a username:password.* How do I fix that?

### What did you see instead?

It loads without asking for username:password.

### What version of Traefik are you using?

2.10.1

### What is your environment & configuration?

debian 11
dockerised
