### ISSUE TITLE
RedirectRegex not working

### ISSUE THREAD

**Issue by nilnaijgnid** [traefik/traefik#9927]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I crearte a middleware for redirect and ingressroute.

### What did you see instead?

I want the request redirect to the new url, but the request still sent to the service.

### What version of Traefik are you using?

2.6

### What is your environment & configuration?

```yaml
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: aaa-redirect
  namespace: traefik
spec:
  entryPoints:
  - traefik
  routes:
  - match: PathPrefix(`/aaa`)
    kind: Rule
    priority: 100
    services:
      - name: accounts
        kind: TraefikService
    middlewares:
      - name: aaa-redirect
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: aaa-redirect
  namespace: traefik
spec:
  redirectRegex:
    regex: ^/aaa
    replacement: https://www.google.com
```

Add more configuration information here.
