### ISSUE TITLE
Multiple local private plugins?

### ISSUE THREAD

**Issue by yongzhang** [traefik/traefik#9957]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have 2 local private plugins with structure like this:

```
plugins-local/src/github.com/A
plugins-local/src/github.com/B
```

And config like this (just an example):

```
experimental:
  localPlugins:
    A:
      moduleName: github.com/A
    B:
      moduleName: github.com/B
```

I would expect both plugins work.

### What did you see instead?

I see below behavior:

Only ONE source code can be in src.

If I put 2 plugins there, I will see 

```
configuration: invalid middleware type or middleware does not exist
```

### What version of Traefik are you using?

v2.9.10

### What is your environment & configuration?

```yaml
experimental:
  localPlugins:
    A:
      moduleName: github.com/A
    B:
      moduleName: github.com/B
```

Add more configuration information here.
