### ISSUE TITLE
Wildcard domain

### ISSUE THREAD

**Issue by kilgaloon** [traefik/traefik#9958]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

What I want is to enable multilevel subdomains on traefik. But I'm unable to generate wildcard certificate for domain. This is the error Traefik is reporting `SAN \"*.stage.example.io\" can not be a wildcard domain"`.

I also added A DNS record: `*.stage.example.io`.

What is the correct way to add this kind of wildcard domain and get certificates generated for it? Thanks

### What did you see instead?

I see the error `SAN \"*.stage.example.io\" can not be a wildcard domain"`  

### What version of Traefik are you using?

1.7.2

### What is your environment & configuration?
```toml
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$apr1$fDMGLdhN$9AxlcGtWmK1szLwcU2sRq0"]

  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[api]
entrypoint="dashboard"


[acme]
email = "support@example.io"
storage = "acme.json"
onHostRule = true
entryPoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
  main = "stage.example.io"
  sans = ["*.stage.example.io"]


[docker]
domain = "stage.example.io"
watch = true
network = "intranet"
```
