### ISSUE TITLE
Preflight cors header not pass to response with customErrors middleware 

### ISSUE THREAD

**Issue by ralmn** [traefik/traefik#9976]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

In the case of an application, exposed with traefik, where we would have setup a middleware header to define CORS headers and a middleware errors (custom errors). In the case of a preflight request, CORS headers are not transmitted to the client.

### What did you see instead?

``` 
curl 'http://test.www.lab.k8s.xxx.xxx/' -X OPTIONS  -H 'Access-Control-Request-Method: POST' -H 'Origin: https://google.fr'  -v -I
*   Trying xxx.xxx.xxx.xxx:80...
* Connected to test.www.lab.k8s.xxx.xxx (xxx.xxx.xxx.xxx) port 80 (#0)
> OPTIONS / HTTP/1.1
> Host: test.www.lab.k8s.xxx.xxx
> User-Agent: curl/7.88.1
> Accept: */*
> Access-Control-Request-Method: POST
> Origin: https://google.fr
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Via: proxy A
Via: proxy A
< Date: Tue, 20 Jun 2023 15:26:58 GMT
Date: Tue, 20 Jun 2023 15:26:58 GMT
< Connection: Keep-Alive
Connection: Keep-Alive
< Content-Length: 0
Content-Length: 0

< 
* Connection #0 to host test.www.lab.k8s.xxx.xxx left intact
```

```
curl 'http://test.www.lab.k8s.xxx.xxx/' -X GET  -H 'Access-Control-Request-Method: POST' -H 'Origin: https://google.fr'  -v -I    
*   Trying xxx.xxx.xxx.xxx:80...
* Connected to test.www.lab.k8s.xxx.xxx (xxx.xxx.xxx.xxx) port 80 (#0)
> GET / HTTP/1.1
> Host: test.www.lab.k8s.xxx.xxx
> User-Agent: curl/7.88.1
> Accept: */*
> Access-Control-Request-Method: POST
> Origin: https://google.fr
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Via: proxy A
Via: proxy A
< Date: Tue, 20 Jun 2023 15:21:18 GMT
Date: Tue, 20 Jun 2023 15:21:18 GMT
< Etag: "6488865a-267"
Etag: "6488865a-267"
< Server: nginx/1.25.1
Server: nginx/1.25.1
< X-Cache: HIT from 192.168.50.37
X-Cache: HIT from 192.168.50.37
< Connection: Keep-Alive
Connection: Keep-Alive
< Content-Type: text/html
Content-Type: text/html
< Accept-Ranges: bytes
Accept-Ranges: bytes
< Last-Modified: Tue, 13 Jun 2023 15:08:10 GMT
Last-Modified: Tue, 13 Jun 2023 15:08:10 GMT
< Content-Length: 615
Content-Length: 615
< X-Custom-Response-Header: Its a test
X-Custom-Response-Header: Its a test
< Access-Control-Allow-Credentials: true
Access-Control-Allow-Credentials: true

< 
* Excess found: excess = 615 url = / (zero-length body)
* Connection #0 to host test.www.lab.k8s.xxx.xxx left intact

```

If we remove errors middleware : 

```
curl 'http://test.www.lab.k8s.xxx.xxx/' -X OPTIONS  -H 'Access-Control-Request-Method: POST' -H 'Origin: https://google.fr'  -v -I
*   Trying xxx.xxx.xxx.xxx:80...
* Connected to test.www.lab.k8s.xxx.xxx (xxx.xxx.xxx.xxx) port 80 (#0)
> OPTIONS / HTTP/1.1
> Host: test.www.lab.k8s.xxx.xxx
> User-Agent: curl/7.88.1
> Accept: */*
> Access-Control-Request-Method: POST
> Origin: https://google.fr
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Via: proxy A
Via: proxy A
< Date: Tue, 20 Jun 2023 15:33:39 GMT
Date: Tue, 20 Jun 2023 15:33:39 GMT
< Connection: Keep-Alive
Connection: Keep-Alive
< Content-Length: 0
Content-Length: 0
< Access-Control-Max-Age: 0
Access-Control-Max-Age: 0
< Access-Control-Allow-Methods: *
Access-Control-Allow-Methods: *
< Access-Control-Allow-Credentials: true
Access-Control-Allow-Credentials: true

< 
* Connection #0 to host test.www.lab.k8s.xxx.xxx left intact
```

### What version of Traefik are you using?

```
traefik version     
Version:      2.10.1
Codename:     saintmarcelin
Go version:   go1.20.3
Built:        2023-04-27T14:52:35Z
OS/Arch:      linux/amd64
```

(tested in 2.9.8, and with image `traefik/traefik:v2.10-experimental` (`7741c68`) )

### What is your environment & configuration?

values of traefik helm charts 
```yaml
certResolvers:
  letsencrypt:
    email: <redacted>
    storage: /tmp/acme.json
    tlsChallenge: true
deployment:
  kind: Deployment
replicas: 1
ports:
  web:
    hostPort: 80
  websecure:
    hostPort: 443
    tls:
      certResolver: letsencrypt
providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
```

App manifest
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-error
spec:
  selector:
    matchLabels:
      app: whoami-error
  template:
    metadata:
      labels:
        app: whoami-error
    spec:
      containers:
      - name: whoami-error
        image: traefik/whoami
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-error
spec:
  selector:
    app: whoami-error
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

--- 
# dashboard.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx
  namespace: appli
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`test.www.lab.k8s.xxx.xxx`)
      kind: Rule
      middlewares:
        - name: test-errors
        - name: cors-whoami
      services:
        - name: nginx
          kind: TraefikService
          namespace: appli
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: nginx
  namespace: appli
spec:
  weighted:
    services:
      - name: nginx
        port: 80
        weight: 1
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors-whoami
  namespace: appli
  labels:
    published: "true"
spec:
  headers:
    accessControlAllowCredentials: true
    accessControlAllowMethods: ['*']
    customResponseHeaders:
      X-Custom-Response-Header: "Its a test"
--- 
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: test-errors
  labels:
    published: "true"
spec:
  errors:
    status:
      - "404"
      - "502"
      - "503"
    query: /
    service:
      name: whoami-error
      port: 80
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

[log-9976.txt](https://github.com/traefik/traefik/files/11802352/log-9976.txt)

**Comment by nmengin** [comment]
Hello @ralmn,

Thank you for reaching out.
At first glance, you should reverse the order of your middlewares to fix your issue.

```yaml
# Current configuration
      middlewares:
        - name: test-errors
        - name: cors-whoami
 ```

```yaml
# Current configuration
      middlewares:
        - name: cors-whoami
        - name: test-errors
 ```

If you need more assistance, to keep the repository focused, we ask that all questions be asked in the [community forum] (https://community.traefik.io/).
It is active, you can ask and get help from other community members pretty quickly.
