### ISSUE TITLE
Incorrect routing using a TCP router and HTTP/2 traffic

### ISSUE THREAD

**Issue by jsprzybylski** [traefik/traefik#9983]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I've configured two applications with their own proxies, both handling traffic with HTTP/2. I expected Traefik to route requests based on the `HostSNI` configuration using a TCP router with SSL passthrough.

```
                         |-- app A --> nginx (HTTP/2, SSL termination) -> actual app
Traefik -- TCP routing --+
                         |-- app B --> nginx (HTTP/2, SSL termination) -> actual app
```

### What did you see instead?

When HTTP/2 was used, I observed that the connection to the first application (whichever was requested first) was re-used by the request to the other app until the connection was dropped. After that, I could reach the second app, but the first one became unreachable in the same manner as before.

The issue is reproducible only in the browser (any). Requests with `curl` always returned correct results. My understanding is that it happens because `curl` closes the connection immediately. Switching to HTTP/1 caused Traefik to work as expected when using a browser.

I'm actually not sure if it's a bug or a normal behavior.

### What version of Traefik are you using?

2.10.3

## Hosts
```
# /etc/hosts
127.0.0.1 vm.example.com service-a.example.com service-b.example.com
```

## Traefik gateway
```yaml
# gateway/compose.yaml
# Dashboard configuration is not needed to reproduce the issue, but I'm leaving it as comments.
services:
  traefik:
    image: "traefik:v2.10.3"
    environment:
      TRAEFIK_ACCESSLOG_FORMAT: "json"
      TRAEFIK_LOG_LEVEL: "debug"
#      TRAEFIK_API_DASHBOARD: "true"
      TRAEFIK_ENTRYPOINTS_WEB_ADDRESS: ":80"
      TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO: "websecure"
      TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME: "https"
      TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS: ":443"
      TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE: "false"
      TRAEFIK_PROVIDERS_DOCKER: "true"
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: "false"
      TRAEFIK_PROVIDERS_DOCKER_NETWORK: "gateway_public_network"
#      TRAEFIK_PROVIDERS_FILE_DIRECTORY: "/traefik"
#    labels:
#      traefik.enable: "true"
#      traefik.http.routers.traefik.entrypoints: "websecure"
#      traefik.http.routers.traefik.rule: "Host(`vm.example.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
#      traefik.http.routers.traefik.service: "api@internal"
#      traefik.http.routers.traefik.tls: "true"
    networks:
      - "public_network"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
#      - "./config:/traefik/config:ro"
#      - "/etc/letsencrypt/common:/traefik/letsencrypt:ro"


networks:
  public_network:
```
```yaml
# gateway/config/dynamic.yaml
tls:
  certificates:
    - certFile: /traefik/letsencrypt/live/wildcard.example.com/fullchain.pem
      keyFile: /traefik/letsencrypt/live/wildcard.example.com/privkey.pem
```

## App A (service-a)
```yaml
# service-a/compose.yaml
services:
  nginx:
    image: "nginx:1.24.0-alpine"
    expose:
      - "80"
      - "443"
    labels:
      traefik.enable: "true"
      traefik.tcp.routers.servicea.rule: "HostSNI(`service-a.example.com`)"
      traefik.tcp.routers.servicea.tls.passthrough: "true"
      traefik.tcp.services.nginx-servicea.loadbalancer.server.port: "443"
    networks:
      - "network"
      - "gateway_public_network"
    restart: always
    volumes:
      - "/etc/letsencrypt/common:/etc/letsencrypt/common:ro"
      - "./service.nginx.conf:/etc/nginx/conf.d/service.conf"
  whoami:
    image: "traefik/whoami"
    command:
      - --port=8080
      - --name=service-a
    networks:
      - "network"
    restart: always


networks:
  network:
  gateway_public_network:
    external: true
```
```nginx configuration
# service-a/service.nginx.conf
upstream whoami-a {
    server whoami:8080;
}

server {
    server_name service-a.example.com;
    listen 443 ssl http2;

    ssl_certificate /etc/letsencrypt/common/live/wildcard.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/common/live/wildcard.example.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/common/live/wildcard.example.com/chain.pem;

    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options SAMEORIGIN;

    location / {
        client_max_body_size 1000M;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-By service-a-nginx;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_pass http://whoami-a/;
    }
}

server {
    if ($host = service-a.example.com) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name service-a.example.com;
        return 404;
}
```

## App B (service-b)
```yaml
# service-b/compose.yaml
services:
  nginx:
    image: "nginx:1.24.0-alpine"
    expose:
      - "80"
      - "443"
    labels:
      traefik.enable: "true"
      traefik.tcp.routers.serviceb.rule: "HostSNI(`service-b.example.com`)"
      traefik.tcp.routers.serviceb.tls.passthrough: "true"
      traefik.tcp.services.nginx-serviceb.loadbalancer.server.port: "443"
    networks:
      - "network"
      - "gateway_public_network"
    restart: always
    volumes:
      - "/etc/letsencrypt/common:/etc/letsencrypt/common:ro"
      - "./service.nginx.conf:/etc/nginx/conf.d/service.conf"
  whoami:
    image: "traefik/whoami"
    command:
      - --port=8090
      - --name=service-b
    networks:
      - "network"
    restart: always


networks:
  network:
  gateway_public_network:
    external: true
```
```nginx configuration
# service-b/service.nginx.conf
upstream whoami-b {
    server whoami:8090;
}

server {
    server_name service-b.example.com;
    listen 443 ssl http2;

    ssl_certificate /etc/letsencrypt/common/live/wildcard.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/common/live/wildcard.example.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/common/live/wildcard.example.com/chain.pem;

    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options SAMEORIGIN;

    location / {
        client_max_body_size 1000M;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-By service-b-nginx;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_pass http://whoami-b/;
    }
}

server {
    if ($host = service-b.example.com) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name service-b.example.com;
        return 404;
}
```

## Traefik
```
# Container log
time="2023-06-22T08:41:55Z" level=info msg="Configuration loaded from environment variables."
time="2023-06-22T08:41:55Z" level=info msg="Traefik version 2.10.3 built on 2023-06-19T16:18:54Z"
time="2023-06-22T08:41:55Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"web\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{\"redirections\":{\"entryPoint\":{\"to\":\"websecure\",\"scheme\":\"https\",\"permanent\":true,\"priority\":2147483646}}},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}},\"websecure\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"network\":\"gateway_public_network\",\"swarmModeRefreshSeconds\":\"15s\"}},\"log\":{\"level\":\"debug\",\"format\":\"common\"},\"accessLog\":{\"format\":\"json\",\"filters\":{},\"fields\":{\"defaultMode\":\"keep\",\"headers\":{\"defaultMode\":\"drop\"}}}}"
time="2023-06-22T08:41:55Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
time="2023-06-22T08:41:55Z" level=info msg="Starting provider aggregator aggregator.ProviderAggregator"
time="2023-06-22T08:41:55Z" level=info msg="Starting provider *traefik.Provider"
time="2023-06-22T08:41:55Z" level=debug msg="*traefik.Provider provider configuration: {}"
time="2023-06-22T08:41:55Z" level=debug msg="Starting TCP Server" entryPointName=websecure
time="2023-06-22T08:41:55Z" level=info msg="Starting provider *docker.Provider"
time="2023-06-22T08:41:55Z" level=debug msg="*docker.Provider provider configuration: {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"network\":\"gateway_public_network\",\"swarmModeRefreshSeconds\":\"15s\"}"
time="2023-06-22T08:41:55Z" level=debug msg="Starting TCP Server" entryPointName=web
time="2023-06-22T08:41:55Z" level=info msg="Starting provider *acme.ChallengeTLSALPN"
time="2023-06-22T08:41:55Z" level=debug msg="*acme.ChallengeTLSALPN provider configuration: {}"
time="2023-06-22T08:41:55Z" level=debug msg="Configuration received: {\"http\":{\"routers\":{\"web-to-websecure\":{\"entryPoints\":[\"web\"],\"middlewares\":[\"redirect-web-to-websecure\"],\"service\":\"noop@internal\",\"rule\":\"HostRegexp(`{host:.+}`)\",\"priority\":2147483646}},\"services\":{\"noop\":{}},\"middlewares\":{\"redirect-web-to-websecure\":{\"redirectScheme\":{\"scheme\":\"https\",\"port\":\"443\",\"permanent\":true}}},\"serversTransports\":{\"default\":{\"maxIdleConnsPerHost\":200}}},\"tcp\":{},\"udp\":{},\"tls\":{}}" providerName=internal
time="2023-06-22T08:41:55Z" level=debug msg="Provider connection established with docker 24.0.2 (API 1.43)" providerName=docker
time="2023-06-22T08:41:55Z" level=debug msg="Filtering disabled container" container=traefik-gateway-3f60ed45a0608ba8f05b385a7181b3eee70419582dc15c46375af3a580717188 providerName=docker
time="2023-06-22T08:41:55Z" level=debug msg="Filtering disabled container" providerName=docker container=whoami-service-b-626933dbecd641efbb92eccb9ccbbd0483dfa72de5125efa0fbfd7bd11b92de5
time="2023-06-22T08:41:55Z" level=debug msg="Filtering disabled container" providerName=docker container=whoami-service-a-1cb586fe56fe9e255da9ccfd7b5652553468d4419ee760de5357424705d5af4a
time="2023-06-22T08:41:55Z" level=debug msg="Configuration received: {\"http\":{},\"tcp\":{\"routers\":{\"servicea\":{\"entryPoints\":[\"websecure\"],\"service\":\"nginx-servicea\",\"rule\":\"HostSNI(`service-a.example.com`)\",\"tls\":{\"passthrough\":true}},\"serviceb\":{\"entryPoints\":[\"websecure\"],\"service\":\"nginx-serviceb\",\"rule\":\"HostSNI(`service-b.example.com`)\",\"tls\":{\"passthrough\":true}}},\"services\":{\"nginx-servicea\":{\"loadBalancer\":{\"terminationDelay\":100,\"servers\":[{\"address\":\"172.18.0.3:443\"}]}},\"nginx-serviceb\":{\"loadBalancer\":{\"terminationDelay\":100,\"servers\":[{\"address\":\"172.18.0.4:443\"}]}}}},\"udp\":{}}" providerName=docker
time="2023-06-22T08:41:55Z" level=debug msg="No default certificate, fallback to the internal generated certificate" tlsStoreName=default
time="2023-06-22T08:41:55Z" level=debug msg="Added outgoing tracing middleware noop@internal" middlewareType=TracingForwarder routerName=web-to-websecure@internal entryPointName=web middlewareName=tracing
time="2023-06-22T08:41:55Z" level=debug msg="Creating middleware" middlewareName=redirect-web-to-websecure@internal middlewareType=RedirectScheme entryPointName=web routerName=web-to-websecure@internal
time="2023-06-22T08:41:55Z" level=debug msg="Setting up redirection to https 443" entryPointName=web routerName=web-to-websecure@internal middlewareName=redirect-web-to-websecure@internal middlewareType=RedirectScheme
time="2023-06-22T08:41:55Z" level=debug msg="Creating middleware" entryPointName=web middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2023-06-22T08:41:55Z" level=debug msg="No default certificate, fallback to the internal generated certificate" tlsStoreName=default
time="2023-06-22T08:41:55Z" level=debug msg="Added outgoing tracing middleware noop@internal" routerName=web-to-websecure@internal entryPointName=web middlewareName=tracing middlewareType=TracingForwarder
time="2023-06-22T08:41:55Z" level=debug msg="Creating middleware" middlewareType=RedirectScheme entryPointName=web routerName=web-to-websecure@internal middlewareName=redirect-web-to-websecure@internal
time="2023-06-22T08:41:55Z" level=debug msg="Setting up redirection to https 443" entryPointName=web routerName=web-to-websecure@internal middlewareName=redirect-web-to-websecure@internal middlewareType=RedirectScheme
time="2023-06-22T08:41:55Z" level=debug msg="Creating middleware" middlewareName=traefik-internal-recovery middlewareType=Recovery entryPointName=web
time="2023-06-22T08:41:55Z" level=debug msg="Creating TCP server 0 at 172.18.0.4:443" routerName=serviceb@docker entryPointName=websecure serverName=0 serviceName=nginx-serviceb
time="2023-06-22T08:41:55Z" level=debug msg="Adding Passthrough route for \"HostSNI(`service-b.example.com`)\"" entryPointName=websecure routerName=serviceb@docker
time="2023-06-22T08:41:55Z" level=debug msg="Creating TCP server 0 at 172.18.0.3:443" serviceName=nginx-servicea entryPointName=websecure serverName=0 routerName=servicea@docker
time="2023-06-22T08:41:55Z" level=debug msg="Adding Passthrough route for \"HostSNI(`service-a.example.com`)\"" routerName=servicea@docker entryPointName=websecure
time="2023-06-22T08:46:17Z" level=debug msg="Handling TCP connection from 172.18.0.1:58194 to 172.18.0.3:443" <-- both browser requests
time="2023-06-22T08:46:25Z" level=debug msg="Handling TCP connection from 172.18.0.1:48664 to 172.18.0.3:443" <-- curl service-a
time="2023-06-22T08:46:27Z" level=debug msg="Handling TCP connection from 172.18.0.1:48672 to 172.18.0.4:443" <-- curl service-b
```

## App A (service-a)
```
# nginx log
172.18.0.2 - - [22/Jun/2023:08:46:17 +0000] "GET / HTTP/2.0" 200 913 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
172.18.0.2 - - [22/Jun/2023:08:46:17 +0000] "GET /favicon.ico HTTP/2.0" 200 816 "https://service-a.example.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
172.18.0.2 - - [22/Jun/2023:08:46:20 +0000] "GET / HTTP/2.0" 200 913 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
172.18.0.2 - - [22/Jun/2023:08:46:20 +0000] "GET /favicon.ico HTTP/2.0" 200 816 "https://service-b.example.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
172.18.0.2 - - [22/Jun/2023:08:46:25 +0000] "GET / HTTP/2.0" 200 307 "-" "curl/7.87.0" "-"
```
```
# Browser page for service-a.example.com
Name: service-a
Hostname: 1cb586fe56fe
IP: 127.0.0.1
IP: 172.29.0.2
RemoteAddr: 172.29.0.3:33156
GET / HTTP/1.1
Host: service-a.example.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate, br
Accept-Language: pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: max-age=0
Connection: close
Sec-Ch-Ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "macOS"
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
X-Forwarded-By: service-a-nginx
X-Forwarded-For: 172.18.0.2
X-Forwarded-Proto: https
X-Real-Ip: 172.18.0.2
```
```
$ curl https://service-a.example.com
Name: service-a
Hostname: 1cb586fe56fe
IP: 127.0.0.1
IP: 172.29.0.2
RemoteAddr: 172.29.0.3:37022
GET / HTTP/1.1
Host: service-a.example.com
User-Agent: curl/7.87.0
Accept: */*
Connection: close
X-Forwarded-By: service-a-nginx
X-Forwarded-For: 172.18.0.2
X-Forwarded-Proto: https
X-Real-Ip: 172.18.0.2
```

## App B (service-b)
```
# nginx log
172.18.0.2 - - [22/Jun/2023:08:46:27 +0000] "GET / HTTP/2.0" 200 307 "-" "curl/7.87.0" "-"
```
```
# Browser page for service-b.example.com
Name: service-a
Hostname: 1cb586fe56fe
IP: 127.0.0.1
IP: 172.29.0.2
RemoteAddr: 172.29.0.3:33184
GET / HTTP/1.1
Host: service-b.example.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate, br
Accept-Language: pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: max-age=0
Connection: close
Sec-Ch-Ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "macOS"
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
X-Forwarded-By: service-a-nginx
X-Forwarded-For: 172.18.0.2
X-Forwarded-Proto: https
X-Real-Ip: 172.18.0.2
```
```
curl https://service-b.example.com
Name: service-b
Hostname: 626933dbecd6
IP: 127.0.0.1
IP: 172.28.0.2
RemoteAddr: 172.28.0.3:38480
GET / HTTP/1.1
Host: service-b.example.com
User-Agent: curl/7.87.0
Accept: */*
Connection: close
X-Forwarded-By: service-b-nginx
X-Forwarded-For: 172.18.0.2
X-Forwarded-Proto: https
X-Real-Ip: 172.18.0.2
```

**Comment by rtribotte** [comment]
Hello @jsprzybylski,

Thanks for your interest in Traefik,

We noticed that the `AppB` labels redefine the same router (`servicea`) as the `AppA`. This is probably the cause of the problem you are facing.

It seems that your issue is related to a configuration issue, but the GitHub issue tracker is dedicated to bug and feature requests.

For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik v2 section](https://community.traefik.io/c/traefik/traefik-v2). 

We will close this issue accordingly but feel free to re-open it if you think that we missed something.

**Comment by jsprzybylski** [comment]
Hi @rtribotte,

It was a typo as I copy-pasted the compose file. I've updated the example.

**Comment by rtribotte** [comment]
Hello @jsprzybylski,

Ok, we are reopening this issue.

Are you using a wildcard certificate? What browser are you using?

Just so you know, there is a known behavior about connection reuse with wildcard certificates and notably with chromium-based browsers, please see:
- https://bugs.chromium.org/p/chromium/issues/detail?id=954160
- https://daniel.haxx.se/blog/2016/08/18/http2-connection-coalescing/
- https://datatracker.ietf.org/doc/html/rfc7540#section-9.1.1

**Comment by jsprzybylski** [comment]
> Are you using a wildcard certificate?

Yes, I am using a Let's Encrypt wildcard certificate. In the example above you can see that it's located in `/etc/letsencrypt/common`. It's because I share them among a couple of VMs.

> What browser are you using?

Chrome, Firefox, Safari. All of them show the same behavior.

> Just so you know, there is a known behavior about connection reuse with wildcard certificates

I've created two regular certificates, one for each application, and the problem disappeared.


Is there anything I could do with Treafik to be able to use the wildcard certificate and still have proper connection reuse?

**Comment by jsprzybylski** [comment]
Apparently, if an nginx proxy would return a 421 Misdirected request status, the browser should drop the previous connection and create a new one. I'll experiment with it tomorrow.

**Comment by jsprzybylski** [comment]
So, I tried changing TLS options but it didn't do much. Maybe it's because I don't know Traefik too well. Another issue with this solution is that AFAIK I would have to update Traefik's config file each time a new application is deployed and that's not something I want to do - my goal was to deploy the apps independently of Traefik. Randomly changing TLS options also seems a little bit hackish.

What did work, however, was a slight change in nginx's default config. My final, working setup is as follows:

## Traefik gateway
Configuration remains unchanged.

## App A (service-a)
```yaml
# service-a/compose.yaml
services:
  nginx:
    image: "nginx:1.24.0-alpine"
    expose:
      - "80"
      - "443"
    labels:
      traefik.enable: "true"
      traefik.tcp.routers.servicea.rule: "HostSNI(`service-a.example.com`)"
      traefik.tcp.routers.servicea.tls.passthrough: "true"
      traefik.tcp.services.nginx-servicea.loadbalancer.server.port: "443"
    networks:
      - "network"
      - "gateway_public_network"
    restart: always
    volumes:
      - "/etc/letsencrypt/common:/etc/letsencrypt/common:ro"
      - "./service.nginx.conf:/etc/nginx/conf.d/service.conf"
      - "./default.nginx.conf:/etc/nginx/conf.d/default.conf" # <-- added this line
  whoami:
    image: "traefik/whoami"
    command:
      - --port=8080
      - --name=service-a
    networks:
      - "network"
    restart: always


networks:
  network:
  gateway_public_network:
    external: true
```
```nginx configuration
# service-a/service.nginx.conf
# Remains unchanged
```
```nginx configuration
# service-a/default.nginx.conf
server {
    server_name _;
    listen 443 ssl http2 default_server;

    ssl_certificate /etc/letsencrypt/common/live/wildcard.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/common/live/wildcard.example.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/common/live/wildcard.example.com/chain.pem;

    return 421;
}
```

## App B (service-b)
```yaml
# service-b/compose.yaml
services:
  nginx:
    image: "nginx:1.24.0-alpine"
    expose:
      - "80"
      - "443"
    labels:
      traefik.enable: "true"
      traefik.tcp.routers.serviceb.rule: "HostSNI(`service-b.example.com`)"
      traefik.tcp.routers.serviceb.tls.passthrough: "true"
      traefik.tcp.services.nginx-serviceb.loadbalancer.server.port: "443"
    networks:
      - "network"
      - "gateway_public_network"
    restart: always
    volumes:
      - "/etc/letsencrypt/common:/etc/letsencrypt/common:ro"
      - "./service.nginx.conf:/etc/nginx/conf.d/service.conf"
      - "./default.nginx.conf:/etc/nginx/conf.d/default.conf" # <-- added this line
  whoami:
    image: "traefik/whoami"
    command:
      - --port=8090
      - --name=service-b
    networks:
      - "network"
    restart: always


networks:
  network:
  gateway_public_network:
    external: true
```
```nginx configuration
# service-b/service.nginx.conf
# Remains unchanged
```
```nginx configuration
# service-b/default.nginx.conf
server {
    server_name _;
    listen 443 ssl http2 default_server;

    ssl_certificate /etc/letsencrypt/common/live/wildcard.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/common/live/wildcard.example.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/common/live/wildcard.example.com/chain.pem;

    return 421;
}
```

This way, when the request is routed incorrectly, nginx will send the 421 response and the browser will create a new connection without affecting the previous one. Using a custom `default.conf` seems to be a little bit cleaner as well.

@rtribotte, thank you for your help. If there's nothing you'd like to add, this issue can be closed.
