### ISSUE TITLE
advertises disabled, weak cipher suites

### ISSUE THREAD

**Issue by steven-omaha** [traefik/traefik#9984]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I checked and updated my traefik configuration. According to https://www.ssllabs.com/ssltest traefik advertises weak cipher suites. 

I have enabled the following.

```
TLSv13:
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256

TLSv12: 
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
```

A similar issue is reported in #3419, but this does not seem to apply here. I checked that I had no typo in any of the suites.

### What did you see instead?

https://www.ssllabs.com/ssltest indicates traefik supports weak cipher suites, 

```
Cipher Suites
--
# TLS 1.3                                                 (suites in server-preferred order)
TLS_AES_128_GCM_SHA256 (0x1301)                                                                                    ECDH x25519 (eq. 3072 bits RSA)   FS | 128
TLS_AES_256_GCM_SHA384 (0x1302)                                                                                    ECDH x25519 (eq. 3072 bits RSA)   FS | 256
TLS_CHACHA20_POLY1305_SHA256 (0x1303)                                                                                    ECDH x25519 (eq. 3072 bits RSA)   FS | 256P
# TLS 1.2                                                 (suites in server-preferred order)
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8)                                                                                    ECDH secp521r1 (eq. 15360 bits RSA)   FS | 256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)                                                                                    ECDH secp521r1 (eq. 15360 bits RSA)   FS | 128
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)                                                                                    ECDH secp521r1 (eq. 15360 bits RSA)   FS | 256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)                                                               ECDH secp521r1 (eq. 15360 bits RSA)   FS                                                       WEAK | 128
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)                                                               ECDH secp521r1 (eq. 15360 bits RSA)   FS                                                       WEAK | 256
TLS_RSA_WITH_AES_128_GCM_SHA256 (0x9c)                                                                                       WEAK | 128
TLS_RSA_WITH_AES_256_GCM_SHA384 (0x9d)                                                                                       WEAK | 256
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)                                                                                       WEAK | 128
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)                                                                                       WEAK | 256
```

![screen](https://github.com/traefik/traefik/assets/35634100/8b9a7872-83eb-4e68-b9e3-aa3e801d1ed7)

### What version of Traefik are you using?

```
Version:      2.10.3
Codename:     saintmarcelin
Go version:   go1.20.5
Built:        2023-06-19T16:18:54Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

docker-compose.yml

```yaml
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    domainname: "XXXXXXXX.one"
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    command:
      - "--log.level=DEBUG"
      - "--log.filePath=/log/traefik.log"
      - "--log.format=common"

      - "--accesslog=true"
      - "--accesslog.format=common"
      - "--accesslog.filepath=/log/access.log"

      - "--api=true"
      - "--api.dashboard=true"
      - "--pilot.dashboard=false"

      - "--experimental.http3=true"

      - "--providers.docker=true"
      - "--providers.docker.network=traefik_proxy"  # use this network to connect to other containers
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/rules"
      - "--providers.file.watch=true"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http3=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http3=true"
      ### for jitsi:
      # - "--entrypoints.video-tcp.address=:4443/tcp"
      # - "--entrypoints.video-udp.address=:10000/udp"

      - "--certificatesresolvers.myresolver.acme.email=webmaster@XXXXXXXX.one"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesResolvers.myresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"

    ports:
      - "80:80"
      - "443:443"
      ### for jitsi:
      # - "4443:4443"
      # - "10000:10000"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "./rules:/rules:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./log:/log:rw"
    networks:
      - traefik_proxy
      - bridge
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.dashboard.rule=Host(`traefik.XXXXXXXX.one`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.dashboard.middlewares=securityheaders-all@docker,permissionspolicy-default@docker,authenticate@docker"

      - "traefik.http.middlewares.authenticate.basicauth.users=xxxxxxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

      - "traefik.http.middlewares.securityheaders-default.headers.framedeny=true"
      - "traefik.http.middlewares.securityheaders-default.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.securityheaders-default.headers.contentTypeNoSniff=true"
      - "traefik.http.middlewares.securityheaders-default.headers.stsPreload=true"
      - "traefik.http.middlewares.securityheaders-default.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.securityheaders-default.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.securityheaders-default.headers.forceSTSHeader=true"

      - "traefik.http.middlewares.securityheaders-onlystrict.headers.contentSecurityPolicy=script-src 'self'"
      - "traefik.http.middlewares.securityheaders-onlystrict.headers.referrerPolicy=same-origin"

      - "traefik.http.middlewares.securityheaders-all.chain.middlewares=securityheaders-default@docker,securityheaders-onlystrict@docker"

      - "traefik.http.middlewares.permissionspolicy-lenient.headers.customResponseHeaders.Permissions-Policy=geolocation 'none'; microphone 'none'; autoplay 'self'; camera 'none'; display-capture 'none'; midi 'none'; payment 'none'; fullscreen 'self'"
      - "traefik.http.middlewares.permissionspolicy-default.headers.customResponseHeaders.Permissions-Policy=geolocation 'none'; microphone 'none'; autoplay 'none'; camera 'none'; display-capture 'none'; midi 'none'; payment 'none'; fullscreen 'none'"

    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true
  bridge:
    driver: bridge
```

rules/tls.yml:

```yml
tls:
  options:
    TLSv13:
      minVersion: VersionTLS13
      cipherSuites:
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      sniStrict: true
      preferServerCipherSuites: true

    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      sniStrict: true
      preferServerCipherSuites: true
```
