### ISSUE TITLE
Accesslog bufferingSize parameter not applying

### ISSUE THREAD

**Issue by GittyBruce** [traefik/traefik#9990]
- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Specified bufferingSize: 100 parameter in traefik.yml static configuration file. Expected Traefik AccessLog to be updated only every 100 lines.

Extra information:
- Setting bufferingSize: foo raises appropriate error: "command traefik error: strconv.ParseInt: parsing "Foo": invalid syntax"
- Setting --accesslog.bufferingsize=100 or TRAEFIK_ACCESSLOG_BUFFERINGSIZE=100 under command or environment sections respectively in docker compose.yml does nothing.
- All other settings in traefik.yml apply appropriately.

### What did you see instead?

bufferingSize parameter did not apply. AccessLog file is updated on each log entry.

### What version of Traefik are you using?

Traefik version 2.9.10 built on 2023-04-06T16:15:08Z

### What is your environment & configuration?

Docker Compose.yml, Traefik section.
```yaml
services:
    reverse-proxy:
      image: traefik:v2.9
      container_name: traefik
      restart: unless-stopped
      depends_on:
        - socket-proxy
      ports:
        - "443:443"
      networks:
        - default
        - traefik_proxy
      volumes:
        - ./traefik/traefik.yml:/traefik.yml:ro
        - ./traefik/acme.json:/etc/traefik/acme.json
        - ./traefik/traefik-provider.yml:/traefik-provider.yml
        - /run/log/traefik:/run/log/
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.entrypoints=https"
        - "traefik.http.routers.dashboard.rule=Host(`REDACTED`)"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
        - "traefik.http.routers.dashboard.tls.domains[0].main=REDACTED"
        - "traefik.http.routers.dashboard.tls.domains[0].sans=REDACTED"
```

Traefik.yml, Static Configuration
```yaml
global:
  checkNewVersion: false

api:
  dashboard: true

entryPoints:
  https:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "REDACTED"
            sans: "REDACTED"

certificatesResolvers:
  letsencrypt:
    acme:
      dnsChallenge:
        provider: REDACTED
      storage: "/etc/traefik/acme.json"

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    watch: true
    exposedbydefault: false
  file:
    filename: "/traefik-provider.yml"

log:
  level: "DEBUG"
  filePath: "/run/log/traefik.log"

accessLog:
  filePath: "/run/log/traefikaccess.log"
  bufferingSize: 100
  fields:
    names:
      StartUTC: drop
```

### If applicable, please paste the log output in DEBUG level

```json
time="2023-06-25T18:56:16-07:00" level=debug msg="Static configuration loaded {\"global\":{},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"https\":{\"address\":\":443\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{\"tls\":{\"certResolver\":\"letsencrypt\",\"domains\":[{\"main\":\"REDACTED\",\"sans\":[\"REDACTED\"]}]}},\"http2\":{\"maxConcurrentStreams\":250},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"docker\":{\"watch\":true,\"endpoint\":\"tcp://socket-proxy:2375\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"},\"file\":{\"watch\":true,\"filename\":\"/traefik-provider.yml\"}},\"api\":{\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"filePath\":\"/run/log/traefik.log\",\"format\":\"common\"},\"accessLog\":{\"filePath\":\"/run/log/traefikaccess.log\",\"format\":\"common\",\"filters\":{},\"fields\":{\"defaultMode\":\"keep\",\"names\":{\"StartUTC\":\"drop\"},\"headers\":{\"defaultMode\":\"drop\"}},\"bufferingSize\":100},\"certificatesResolvers\":{\"letsencrypt\":{\"acme\":{\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"/etc/traefik/acme.json\",\"keyType\":\"RSA4096\",\"certificatesDuration\":2160,\"dnsChallenge\":{\"provider\":\"REDACTED\"}}}}}"
```
