### ISSUE TITLE
Error renewing certificate from LE - wildcard with DNS Made Easy

### ISSUE THREAD

**Issue by rossnick** [traefik/traefik#9999]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Auto-renew with acme resolver and dnsmadeeasy provider fails with 2.9.x and 2.10.x

Note the hyphens in the domain names, I don't know if changes something.

The same config works with 2.8.8

### What did you see instead?

This error occurred :

Error renewing certificate from LE: {domain-one.net [*.domain-one.net domaintwo.net *.domaintwo.net]}" ACME CA="https://acme-v02.api.letsencrypt.org/directory" error="error: one or more domains had a problem:\n[*.domaintwo.net] [*.domaintwo.net] acme: error presenting token: dnsmadeeasy: unable to create record for domaintwo.net.: unexpected status code: [status code: 400] body: {\"error\":[\"Record name 'domaintwo.net.' may not begin or end with a dot.\"]}\n[domaintwo.net] [domaintwo.net] acme: error presenting token: dnsmadeeasy: unable to create record for domaintwo.net.: unexpected status code: [status code: 400] body: {\"error\":[\"Record name 'domaintwo.net.' may not begin or end with a dot.\"]}\n

### What version of Traefik are you using?

Version:      2.10.3
Codename:     saintmarcelin
Go version:   go1.20.5
Built:        2023-06-19T16:18:54Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

Resolver in traefik.yml :
```
  acme-resolver-dns:
    acme:
      email: email@domain.com
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: dnsmadeeasy
        delayBeforeCheck: 30
        resolvers:
          - "208.94.148.4:53"
          - "208.80.124.4:53"
          - "208.80.126.4:53"
          - "208.80.125.4:53"
          - "208.80.127.4:53"
          - "208.94.149.4:53"
```

Router :
```
    domaintwo-https:
      rule: "HostRegexp(`{subdomain:.+}.domain-one.net`, `domain-one.net`, `{subdomain:.+}.domaintwo.net`, `domaintwo.net`)"
      service: "webserver-hcf@file"
      entrypoints: "websecure"
      middlewares:
        - "hsts-header"
        - "compress"
        - "country-auth-denyru"
      tls:
        certResolver: acme-resolver-dns
        domains:
          - main: "domain-one.net"
            sans:
              - "*.domain-one.net"
              - "domaintwo.net"
              - "*.domaintwo.net"
```
